### ISSUE TITLE
Accepting Pull Requests: Add minimum height to Member Menu so dropdown shows in all cases

### ISSUE THREAD

**Issue by petramies** [mattermost/platform#1005]
Dropdown "member menu" doesn't show all options. 

![manage_team_member](https://cloud.githubusercontent.com/assets/14278742/10415879/ff3c1ab6-7005-11e5-9ec2-6e1815260cbb.PNG)

css:
.ps-container{
	overflow:hidden !important
}

**Comment by it33** [comment]
Thanks @petramies, appreciate the clear report! [Ticket filed for fix](https://mattermost.atlassian.net/browse/PLT-630).

**Comment by it33** [comment]
Fixed in this PR: https://github.com/mattermost/platform/pull/1018
