### ISSUE TITLE
Accepting Pull Requests: Add ability to change time format to 24h

### ISSUE THREAD

**Issue by hashworks** [mattermost/platform#1011]
Also it would be great to be able to adjust the date format as well.

**Comment by it33** [comment]
Hi @hashworks, 

Appreciate the feedback. The team's reviewed this feature and [opened a ticket to accept pull requests here](https://mattermost.atlassian.net/browse/PLT-637).

**Comment by coreyhulen** [comment]
A pull request was submitted and accepted.
