### ISSUE TITLE
Question: SMTP error 554 5.7.1 "Client host rejected: Access denied"

### ISSUE THREAD

**Issue by lottietoday** [mattermost/platform#1012]
Hello Im running mattermost on docker but have problem to activate emails.

```
Connection unsuccessful: Failed to add to email address - 554 5.7.1 <unknown[IP-ADDRESS]>: Client host rejected: Access denied
```

Im connectiong from outside to domain (and NAT port inside). Ho to config email to working. Or its bug?

**Comment by it33** [comment]
Hi @lottietoday, not totally sure, propose web searching the `554 5.7.1` error code and see if any of the solutions that come up apply to your situation? My guess is it's an SMTP setting,

**Comment by coreyhulen** [comment]
maybe similar to https://forum.mattermost.org/t/connection-unsuccessful-failed-to-add-to-email-address-454-4-7-1-xxxxxxxx-gmail-com-relay-access-denied/331

**Comment by coreyhulen** [comment]
Searching for the error code looks like

```Problem
You are sending emails to an external domain and you get a Delivery Failure Message which says: 554. 5.7.1.

Cause
SMTP Code 554. 5.7.1 is basically a rejection from the Recipient Domain. SMTP Code 554. 5.7.1 means 'Not allowed'.  The address in MAIL FROM appears to have insufficient submission rights, or is invalid, or is not authorized with the authentication used; the address in a RCPT TO command is inconsistent with the permissions given to the user; the message data is rejected based on the submitting user.
```

**Comment by lottietoday** [comment]
same issue with 0.7 and 1.0

**Comment by lottietoday** [comment]
Its trying to send email from local server... however i set email server to send (SMTP address)... Prowider of my email told me email not exists on my own server...

**Comment by trashcan** [comment]
What SMTP configuration options do you have set? It sounds like your SMTP server is not allowing you to pass the message on, either due to lack of authentication, or not understanding that you own a particular domain.

**Comment by lottietoday** [comment]
from our local provider... 
Email is created and working (jira and gilab using it without problems) so there no authentication problems.
With google i have problem with encrypted comunication it testing very long and do nothing...

**Comment by coreyhulen** [comment]
are 
```
"FeedbackName": "",
 "FeedbackEmail": "",
```

set correctly ?  From the error it looks like they don't have permissions to send an email.  Those fields are placed on the from clause of the email.

what email provider are you using?

**Comment by trashcan** [comment]
I can't say for sure but 
```
Client host rejected: Access denied
```

Generally means you aren't sending SMTP authentication, or you are are not sending the correct from address as @coreyhulen mentioned. Your SMTP server is not accepting the email for some reason. If you can paste your SMTP settings (minus the pw of course) I might be able to give some more info.

**Comment by lottietoday** [comment]
@coreyhulen im using websupport provider.... 
email setting for smtp are smtp.websupport.sk and imap is imap.websupport.sk (ports are standard without encryption)

**Comment by it33** [comment]
Hi @lottietoday, 

Just circling back, were you able to clear this issue?

**Comment by it33** [comment]
Hi @lottietoday, 

Thanks again for your work on the [Docker image for the GitLab Mattermost integration](https://twitter.com/LottieToday/status/661827546112241664), really great work!

I'm hoping you were able to solve the SMTP issue. Closing this ticket for now since it's been a while--please re-open or add a new issue if things aren't working,

**Comment by arifulislamat** [comment]
Sharing my solution in case others have face same problem. However my error it little bit different.

Error: **Connection unsuccessful: failed to set the to address: 553 5.7.1 <test@example.com>: Sender address rejected: not owned by user**  

**Solution:** 
- vim config.json
- replace "test@example.com" with valid mail or leave it empty
- if you are on docker, then restart the container
