### ISSUE TITLE
Email is broke

### ISSUE THREAD

**Issue by Corwin7** [mattermost/platform#1043]
I can send email on the server I have the docker container installed on by `telnet 0.0.0.0 25` and entering the email.

Here is the relevant part of `config/config.json`:

```
    "EmailSettings": {
        "ByPassEmail" : false,
        "EnableSignUpWithEmail": true,
        "SendEmailNotifications": true,
        "RequireEmailVerification": true,
        "FeedbackName": "feedback",
        "FeedbackEmail": "feedback@example.com",
        "SMTPUsername": "",
        "SMTPPassword": "",
        "SMTPServer": "0.0.0.0",
        "SMTPPort": "25",
        "ConnectionSecurity": "",
        "InviteSalt": "b....S",
        "PasswordResetSalt": "v....L",
        "ApplePushServer": "",
        "ApplePushCertPublic": "",
        "ApplePushCertPrivate": ""
    },
```

I know nothing about docker so maybe 0.0.0.0 doesn't work inside a container...

I wish vim worked inside the container, editing files with vi pisses me off.

**Comment by Corwin7** [comment]
After some googling it appears this is what is required to reach the server: `"SMTPServer": "172.17.42.1",`. This still does not work.

**Comment by it33** [comment]
Hi @Corwin7, 

Thanks for the issue report, could we have your help looking at `System Console > Logs` ([see "Troubleshooting" in SMTP docs](https://github.com/mattermost/platform/blob/master/doc/install/SMTP-Email-Setup.md#troubleshooting-smtp)) to see if there's an error message that could offer a starting point?

**Comment by Corwin7** [comment]
`If you have issues with your SMTP install, from your Mattermost team site go to the main menu and open System Console > Logs`

Where do I find this "main menu"? There is a menu at the top left but System Console is not an option.

**Comment by Corwin7** [comment]
The log is completely filled with:
```
[2015/10/14 17:55:21 UTC] [EROR] websocket connect err: websocket: could not find connection header with token 'upgrade'
[2015/10/14 17:55:21 UTC] [EROR] /api/v1/websocket:connect code=500 rid=3ttw6yrahtghddnbxkjnd6agor uid=pf8yt8tjjtgwipuq8kmuuaon8y ip=216.253.238.138 Failed to upgrade websocket connection [details: ]
```

I don't see anything about SMTP but it's not like I can run grep in that window.

**Comment by coreyhulen** [comment]
` websocket: could not find connection header with token 'upgrade'` looks like nginx (or your proxy server) isn't setup properly to allow a http connection to be upgraded to a websocket connection.

**Comment by coreyhulen** [comment]
I think your email problem is you cannot connect to the docker host from the container without some special magic that's dependent on the docker enviro (mac vs linux, etc).

something like https://github.com/docker/docker/issues/1143  or http://stackoverflow.com/questions/27556301/connect-to-local-mysql-server-through-docker

**Comment by Corwin7** [comment]
I used the Nginx config from `http://forum.mattermost.org/t/setup-behind-nginx/86` and that looks like it took care of the websocket errors. Thanks. :)

Is there a way to clear the logs? It seems that the menu item for `System Console` usually dies not display. I've found that If I switch rooms and click around a bit then the menu item pops up. Must be a caching issue.

Since docker seems totally foobar in regards to communicating to the parent, it seems like you guys should include a mail server like OpenSMTP (By far the best general purpose SMTP server availiable) in the container.

**Comment by Corwin7** [comment]
I found the logs in logs/mattermost.log inside the container. :)

**Comment by Corwin7** [comment]
Here's the log output now that the websocket problem is fixed:
```
[2015/10/15 22:05:50 UTC] [INFO] Current version is 1.0.0 (2467/Fri Oct 2 16:47:14 UTC 2015/a049b34dfb6b7c6251bcc0642284b6f4a0bff8ec)
[2015/10/15 22:05:50 UTC] [INFO] Current working directory is /mattermost/bin
[2015/10/15 22:05:50 UTC] [INFO] Loaded config file from /config_docker.json
[2015/10/15 22:05:50 UTC] [INFO] Server is initializing...
[2015/10/15 22:05:50 UTC] [INFO] Pinging sql master database
[2015/10/15 22:05:50 UTC] [INFO] Pinging sql replica-0 database
[2015/10/15 22:05:50 UTC] [INFO] Starting Server...
[2015/10/15 22:05:50 UTC] [INFO] Server is listening on :80
[2015/10/15 22:05:50 UTC] [INFO] RateLimiter is enabled
```

**Comment by coreyhulen** [comment]
Has this been resolved?  where you able to get the docker img talking to the docker container?  

You can try to shell into the machine
```
docker exec -ti mattermost-dev /bin/bash
```
and test with telent
``` 
telent 0.0.0.0 25
```

something like https://support.microsoft.com/en-us/kb/153119

**Comment by it33** [comment]
Hi @Corwin7, closing this issue for now as it's been a month since the report, please post in the [Troubleshooting forum](https://forum.mattermost.org/t/how-to-use-the-troubleshooting-forum/150) if you have further issues?
