### ISSUE TITLE
SMTP Authentication

### ISSUE THREAD

**Issue by danielsreichenbach** [mattermost/platform#1044]
Would it be possible to extend the email handling to support more than just plain authentication?

I'm currently having the issue that I can not use Mattermost due to it using plain text authentication, as most mail servers prohibit it these days (and rightfully so).

**Comment by coreyhulen** [comment]
From the system console you can set Email Settings -> Connection Security to 'TLS' or 'STARTTLS'

**Comment by danielsreichenbach** [comment]
Yeah, :+1: that works, thanks!
