### ISSUE TITLE
UseTLS option in documentation

### ISSUE THREAD

**Issue by df-5** [mattermost/platform#1060]
Is `UseTLS` still valid, or has it been replaced with `ConnectionSecurity = '', 'TLS', 'STARTTLS'`?

A quick grep -r shows no other results for UseTLS than in `./doc/install/SMTP-Email-Setup.md`.

**Comment by coreyhulen** [comment]
It's no longer valid and should be converted to ConnectionSecurity=TLS.  This is being addressed with PR https://github.com/mattermost/platform/pull/1056/files.

**Comment by it33** [comment]
Also, new documentation for System Console including this param [is here](https://github.com/mattermost/platform/blob/master/doc/install/Configuration-Settings.md)
