### ISSUE TITLE
Possible to remove the google API calls?  Makes mattermost not work in China

### ISSUE THREAD

**Issue by bryanbecker** [mattermost/platform#1064]
This is possibly too specific of a request to change the code base, but is there anything I can edit to make mattermost not load code from google?  Makes the site timeout without a VPN, even when hosted locally.

I'm assuming it's to load javascript libraries, but my firefox console-fu is very lacking

**Comment by it33** [comment]
Hi @bryanbecker, 

Appreciate the feedback, I believe the requests time out, but the system still works (let us know if you see failures?) 

Very open to pull requests to fix this, [existing ticket here](https://mattermost.atlassian.net/browse/PLT-632). We had previous feedback on this and the reporter said it was low priority and didn't see errors,

**Comment by bryanbecker** [comment]
Sure,

what do you mean by 'errors'?  I mean, it works as intended, I guess.  The error is that the user device times out when opening the site 'request timed out', so users can't get in.  To be fair, lots of websites have this issue accidentally in China  (China blocks and/or severely throttles google).

If you or someone else can point me in the direction of where and how these calls are being used, I imagine it's very simple to fix (i.e. just host the loaded libraries locally, or dl from a local server), right?

**Comment by it33** [comment]
Hi @bryanbecker, 

Had an internal conversation and it seems that you shouldn't get those timeouts if you upgrade to the latest version of [Mattermost (v1.1)](http://www.mattermost.org/download/), would you be up for trying this and seeing if your issue is still there?

**Comment by bryanbecker** [comment]
@it33 

Thanks for looking into this.  I'm using the gitlab mattermost, which I believe is upgrading on the 22nd, right?  If so, we can close this issue, and I'll reopen it if the problem persists at that time.

Thanks again for the great software!
