### ISSUE TITLE
[feature] add click count next to embedded links

### ISSUE THREAD

**Issue by blaskovicz** [mattermost/platform#1068]
A really nice feature of [discourse](https://www.discourse.org/) is that it tracks and displays (to all users) how many people have clicked on a given link:

![image](https://cloud.githubusercontent.com/assets/10687433/10515034/6c010e38-731f-11e5-8345-2f5979ecd1f7.png) 

I think this is a really useful feature for determining conversation engagement that (:star:)Slack doesn't yet have

**Comment by it33** [comment]
Thanks @blaskovicz for the feature idea, 

Some thoughts below for your consideration: 

Agree this is a useful feature. Under our principle of [_fast, obvious, forgiving_](http://www.mattermost.org/design-principles/) this feature might not be obvious for all end users, so we probably want it possible, but off by default, so proposing implementation list for this includes: 

---- 
#### 1) Add Team Setting 

Add **Team Setting** > **Display** > **Advanced Message Display Options**

Title: Advanced Message Display Options 

Help text: Advanced options for message display 

[  ] Show count of clicks next to hyper links in messages.

#### 2) Implement feature as above

If zero clicks have been made on a link, show no indicator. 

---- 
Let us know your feedback and we can add a ticket to [**accepting-pull-requests**](https://mattermost.atlassian.net/issues/?filter=10101) list for this?

**Comment by it33** [comment]
Hi @blaskovicz, would you have any feedback on the proposed design?

**Comment by blaskovicz** [comment]
I think it sounds good. I might have the setting on by default, but that's just me.

**Comment by esethna** [comment]
Thanks @blaskovicz, APR ticket [here](https://mattermost.atlassian.net/browse/PLT-1287).

**Comment by it33** [comment]
Closing since this is tracked in Uservoice
