### ISSUE TITLE
Accepting Pull Requests: Allow search to match inside tokens (and highlight match in search result)

### ISSUE THREAD

**Issue by blaskovicz** [mattermost/platform#1070]
One essential feature for us in any chat solution is the ability to do a full-text search, historically.

If I match a full word in my search (ignoring the bug with urls I mentioned in #1069), results are shown (eg: `upgrade`):
![image](https://cloud.githubusercontent.com/assets/10687433/10515509/dc9df9c4-7321-11e5-9eeb-b039eb53f19f.png)

If I only enter a few characters of the word, for example, `upg`, no results are shown:
![image](https://cloud.githubusercontent.com/assets/10687433/10515545/fb373328-7321-11e5-9ddc-e3894a430499.png)

I would expect partial matches to be returned in the latter case.

Also (I can file a different feature request for this if necessary) I would like it if the match portion of the result text was highlighted somehow (like slack).

**Comment by florianorben** [comment]
Hey @blaskovicz ,

you could do a wildcard search with ````upg*````
Matched parts aren't highlighted that way though...

**Comment by it33** [comment]
Totally agree! [Ticket added for accepting pull requests here.](https://mattermost.atlassian.net/browse/PLT-747)

**Comment by girishso** [comment]
just sent a PR for this #1181

**Comment by girishso** [comment]
@it33 PR #1181 resolves this, I think the issue can be closed.
