### ISSUE TITLE
Accepting Pull Requests: Emoji autocomplete for messages

### ISSUE THREAD

**Issue by blaskovicz** [mattermost/platform#1071]
Similar to username `@mentions`, could `:emoji:` mentions autocomplete?

Right now it's hard to remember what we can use.

As a side note, there is no winky face!
![image](https://cloud.githubusercontent.com/assets/10687433/10517209/ccda7b18-7329-11e5-89f6-dd6c41a9f0a7.png)

**Comment by it33** [comment]
Thanks @blaskovicz! Agree, [accepting pull requests for this](https://mattermost.atlassian.net/browse/PLT-698)

Weird why winky face is not working, [issue filed](https://mattermost.atlassian.net/browse/PLT-699)

**Comment by blaskovicz** [comment]
I'll take a look at that if I have some time :smile: . I have angular and some golang experience, but no React yet.

**Comment by mprentic-harris** [comment]
This would indeed be a very helpful feature. GitLab does this so perhaps there is some useful code that you could refer to there.

**Comment by trashcan** [comment]
This is being added in pull #1582.
