### ISSUE TITLE
Too much rendered initially

### ISSUE THREAD

**Issue by apaatsio** [mattermost/platform#1086]
There is an architecture/performance issue regarding what is rendered on the initial page load.

For example, look at https://github.com/mattermost/platform/blob/master/web/react/pages/channel.jsx, you can see that it renders all the modals. I think the modals should be rendered on-demand, e.g. when they are opened.

I did some benchmarking on the render time. I removed all the modals from the initial render. This **improved the initial page render time ~100ms on average** on a high-end laptop. On a mobile device the improvement can possibly be multiple times that.

**Comment by it33** [comment]
Thanks @apaatsio! Yeah, we really need to start moving more modals to react-bootstrap. Pretty excited about how fast things could work if we made that change. Completely agree,

**Comment by it33** [comment]
Hi @apaatsio, if you look on master you should see that the number of modals rendered in initial load is significantly decreased, appreciate your feedback!
