### ISSUE TITLE
Which license is correct and where?

### ISSUE THREAD

**Issue by mattfarina** [mattermost/platform#1093]
There are two license files. One in the [build/ directory](https://github.com/mattermost/platform/blob/master/build/MIT-COMPILED-LICENSE.md) and [one in the top level](https://github.com/mattermost/platform/blob/master/LICENSE.txt) of the project. The one in the build directory is based on MIT. The top level one is dual licensed as AGPLv3 or commercial.

Can you explain the differences and how this applies in practice? Or, is the one in the build directory supposed to supersede the top level one?

**Comment by it33** [comment]
[FAQ here](https://forum.mattermost.org/t/mattermost-releases-under-mit-license-agpl-does-not-apply/273), the compiled version is MIT
