### ISSUE TITLE
3rd party integrations / extensive API planned?

### ISSUE THREAD

**Issue by JulianHH** [mattermost/platform#1106]
Hi there!

I really appreciate your work! :) I am about to give it a try.

But, have you planned an extensive API like Slack has?

Thanks and keep it up :)

- Julian

**Comment by coreyhulen** [comment]
Documentation of the APIs is still high on our list of todos. The web client does 99% of it's work via the RESTful JSON web-service. The last 1% is some extra error checking/setup the web server does, but isn't needed or has a similar API call. You can think of https://github.com/mattermost/platform/blob/master/web/react/utils/client.jsx as a javascript driver for the web-service. Also https://github.com/mattermost/platform/blob/master/model/client.go is a similar golang driver used by the unit tests.

**Comment by JulianHH** [comment]
Thanks :)

**Comment by it33** [comment]
@JulianHH, FYI, API page added here: https://github.com/mattermost/platform/blob/master/doc/developer/API.md

**Comment by JulianHH** [comment]
Thx! :)
