### ISSUE TITLE
"No such image" when running dev start command line

### ISSUE THREAD

**Issue by dandeezy** [mattermost/platform#1112]
Anyone have any idea why it can't find the image? Not too familiar with docker but it is installed and running in &bg. 

```sh 
$ sudo docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform
INFO[2686] POST /v1.19/containers/create?name=mattermost-dev
ERRO[2686] Handler for POST /containers/create returned error: No such image: mattermost/platform (tag: latest)
ERRO[2686] HTTP Error                                    err=No such image: mattermost/platform (tag: latest) statusCode=404
Unable to find image 'mattermost/platform:latest' locally
INFO[2686] POST /v1.19/images/create?fromImage=mattermost%2Fplatform&tag=latest
Pulling repository mattermost/platform
Get https://index.docker.io/v1/repositories/mattermost/platform/images: dial tcp 54.86.132.13:443: no route to host
```

Thanks,

**Comment by dandeezy** [comment]
More info: 
I am behind a proxy, but when I try from Chrome on my PC
the url `https://index.docker.io/v1/repositories/mattermost/platform/images` returns just a double bracket `[]`

**Comment by coreyhulen** [comment]
Hmm...not sure but I'm guessing it's a problem with your proxy.

You might try re-installing.  I would follow the directions at http://docs.mattermost.org/install/Docker-Single-Container/index.html at the bottom under `Upgrading Mattermost`

**Comment by dandeezy** [comment]
Ok thank you. Maybe it's a docker-vs-proxy problem. I was able to install it just fine though (docker that is) 

Relevant link to SO below if anybody else is debugging this. My Company moved on to HIPChat. We'll take another look at this in a year. The only reason we can't use slack is that we can't host it ourselves (companies have secrets still in an open source world) 

http://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy

**Comment by coreyhulen** [comment]
Thanks for the reply.   You can also install via https://github.com/mattermost/platform/blob/master/doc/install/Production-Ubuntu.md without docker.
