### ISSUE TITLE
emoji ":four_leaf_clover:" can not display

### ISSUE THREAD

**Issue by gwind** [mattermost/platform#1117]
input `:four_leaf_clover:` display :four_leaf_clover:

**Comment by trashcan** [comment]
From what I can tell Mattermost is using the `twemoji` library, based on the Twitter emoji set. It does not look like it has that particular one:

http://twitter.github.io/twemoji/preview.html

**Comment by gwind** [comment]
Yes, it has.

and in the path of self hosted mattermost platform, there is :four_leaf_clover: in https://YOURDOMAIN/static/images/emoji/

**Comment by trashcan** [comment]
Oh you're right, I see it in `react/utils/emoticons.jsx` as well. Investigating.

**Comment by coreyhulen** [comment]
Emojis with underscores do not render.  This is a know bug https://mattermost.atlassian.net/browse/PLT-521

**Comment by gwind** [comment]
indeed, it is

**Comment by trashcan** [comment]
@gwind I submitted a pull request for this that I think will fix it. https://github.com/mattermost/platform/pull/1135 Thanks for reporting this.

**Comment by hmhealey** [comment]
Thanks for the fix for that, @trashcan

**Comment by trashcan** [comment]
Glad it helped at least a little. This might be a good candidate for a test if there isn't one already.
