### ISSUE TITLE
Some users keep seeing 'someone'/'undefined' for longer than others when a new user joins

### ISSUE THREAD

**Issue by sumitag** [mattermost/platform#1118]
Some users keep seeing 'someone'/'undefined' for longer than others when a new user joins and posts to a channel

**Comment by coreyhulen** [comment]
What version of mattermost are you running?  In the  `... -> About Mattermost` you can get the build number.

**Comment by sumitag** [comment]
This was under 1.0.0, we are now running 1.1.0

**Comment by coreyhulen** [comment]
I think this is now fixed in master.  Should ship with 1.2
