### ISSUE TITLE
Does mattermost support markdown formatting?

### ISSUE THREAD

**Issue by PerfectCarl** [mattermost/platform#112]
If mattermost does support it, it should be advertized in a more prominent way...

**Comment by it33** [comment]
Hi @PerfectCarl, not yet, there's multiple rich-text options we've been considering. Would you be open to adding a feature request so the community can upvote on which format makes the most sense for them? http://mattermost.uservoice.com/forums/306457-general

**Comment by PerfectCarl** [comment]
[Done!](http://mattermost.uservoice.com/forums/306457-general/suggestions/8661160-add-markdown-support)

Thanks for your quick answers :)

> Note: I added Mattermost to my [slack alternative run down](http://softwarerecs.stackexchange.com/a/20792/12983).

**Comment by crspeller** [comment]
Closing because question has been answered. If you still have an question, feel free to continue the discussion at http://forum.mattermost.org/.

**Comment by PerfectCarl** [comment]
Sure!
