### ISSUE TITLE
Some go dependencies have updated URLs

### ISSUE THREAD

**Issue by trashcan** [mattermost/platform#1123]
If you use `go build` rather than `godep go build`, you get errors complaining that some packages like throttled have changed URLs. Is there any interest in updating these? It would take a little work as some of the repos have been recreated and the commit IDs may not correspond, but I'd be willing to dig in and make sure we get the exact same version or that the newest version works.

Or alternatively would it be better to save the dependencies with `godep save -r` so they are rewritten to be local?

The main reason I want to fix this is that it breaks the go integration in Atom which uses "go build" to compile after each save. 

Example:
```
pat@mbp ~/g/s/g/m/platform> # does not work go build
pat@mbp ~/g/s/g/m/platform> go build
api/server.go:12:2: code in directory /Users/pat/go/src/github.com/throttled/throttled expects import "gopkg.in/throttled/throttled.v2"
api/server.go:13:2: code in directory /Users/pat/go/src/github.com/throttled/throttled/store expects import "gopkg.in/throttled/throttled.v2/store"

pat@mbp ~/g/s/g/m/platform> # works with godep
pat@mbp ~/g/s/g/m/platform> godep go build
pat@mbp ~/g/s/g/m/platform>
```

**Comment by coreyhulen** [comment]
We do upgrade the libraries every so often and we probably need todo this again soon. We need the build machine (and all developers) to have reproducible results hence the dependency on Godep.  Godep is pretty standard, but we hope to move to vendoring with go1.5.  I suspect even vendoring will have issues with atom.

I think (?) all you need todo is run `godep restore` which copies our dependencies in mattermost/Godep into $GOPATH/src as if you ran `go get ...`.  Using restore should allow you to use `go build`.

`godep save -r` is the correct way todo this, if you want to update the mattermost/Godep dependencies dir, but this may have problems if libraries have radically changed.

**Comment by juRiii** [comment]
```
juriii@juRiii-NB ~/dev/go/src/github.com/mattermost/platform $ godep restore
can't load package: package github.com/throttled/throttled: code in directory /home/juriii/dev/go/src/github.com/throttled/throttled expects import "gopkg.in/throttled/throttled.v2"
godep: restore: exit status 1
```

though, `godep go build` is working. im using `rerun` so i would like to make sure, that `go build` is also working. ideas?

**Comment by it33** [comment]
Hi @trashcan, just wanted to circle back on this issue, still relevant?

**Comment by coreyhulen** [comment]
we've updated all these.
