### ISSUE TITLE
Support for default team?

### ISSUE THREAD

**Issue by trashcan** [mattermost/platform#1124]
Is there a way to set a default team? When I go to https://gitlab.mattermost.com/ for example I do not have an option to sign in. I have to use find my team, check my email, and then use that link to login. 

Would it be possible to either set a default team, or redirect to the first one?

**Comment by trashcan** [comment]
And to clarify I am using the github integration to login, that may make a difference.

**Comment by coreyhulen** [comment]
Thanks for the request.  A lot of people have asked for this and it's high in the priorities.  https://mattermost.atlassian.net/browse/PLT-340

**Comment by trashcan** [comment]
Ah OK. If its already in lira we can close this.

**Comment by timwood** [comment]
In looking at https://mattermost.atlassian.net/browse/PLT-340 I don't see any references on what version this was resolved in or how this was resolved or documentation on how to configure a single or default team.

The only related [MM documentation](https://docs.mattermost.com/administration/config-settings.html) I can find is [Enable Team Directory](https://docs.mattermost.com/administration/config-settings.html#enable-team-directory)

And the [Site URL](https://docs.mattermost.com/administration/config-settings.html#site-url) config explicitly says NOT to include team name in URL.

Thanks for any help!
