### ISSUE TITLE
Can't seem to replace notification sound

### ISSUE THREAD

**Issue by unquietwiki** [mattermost/platform#1128]
ding.mp3 in static/images : I tried to replace it with something less annoying, but the original ding still shines through. Trying to change the sound via js/bundle-2920.min.js also doesn't seem to work. Is the sound hardcoded into the binary? Any chance of making the sound user-selectable, since https://mattermost.atlassian.net/browse/PLT-15 is in limbo?

**Comment by coreyhulen** [comment]
Replacing the file in static/images should work.  It's not hard coded in the binary.  I suspect it was cached.  You might try a hard refresh on the page and/or clearing your browser cache.  The server will send back a 304 etag cache, but if it has been modified and has a more current timestamp it will send the new file.  I think you can just `touch -m ding.mp3` and that should update the file timestamp, but that should have happened when you re-named the file to ding.pm3 (I think).

**Comment by unquietwiki** [comment]
Hey, thank you for replying. Funny enough I had a report from a coworker a day or two ago saying the updated noise started working for him. So maybe it can take a week for some reason?

**Comment by it33** [comment]
Closing as this appears to be solved,
