### ISSUE TITLE
Accepting Pull Requests: Add a query re-writer to special case searches for IP addresses 

### ISSUE THREAD

**Issue by mbeynon** [mattermost/platform#1132]
Searching for an IP address such as:
    10.100.200.101
appears to search for:
    10 or 100 or 200 or 101

This returns results without the combined string, which is not expected and confusing.

Surrounding the search text with double quotes, such as: "10.100.200.101" appears to work.

Version: Current version is 1.0.0 (2467/Fri Oct 2 16:47:14 UTC 2015/a049b34dfb6b7c6251bcc0642284b6f4a0bff8ec)

**Comment by it33** [comment]
Hi @mbeynon, 

Appreciate the feedback, this is a special case that could be added in future on top of the full text search capabilities we're leveraging from Postgres and MySQL. We'll look into creating a ticket for it. 

Here is how the search currently works: https://github.com/mattermost/platform/blob/master/doc/help/Search.md

**Comment by it33** [comment]
Proposed ticket: 

Title: 
Accepting Pull Requests: Add a query re-writer to special case searches for IP addresses 

Add a query re-writer to special case searches for IP addresses and re-write them with quotes so they bring back results for IP addresses when using default full text search from database.

**Comment by lfbrock** [comment]
Thanks @mbeynon, 

We created a ticket [for accepting pull requests on this issue](https://mattermost.atlassian.net/browse/PLT-812). It's listed in [the Accepting Pull Requests issues list](https://mattermost.atlassian.net/browse/PLT-797?filter=10101). [Code Contribution Guidelines](https://github.com/mattermost/platform/blob/master/doc/developer/Code-Contribution-Guidelines.md) are available for anyone interested in contributing to this project.

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in Jira.
