### ISSUE TITLE
Unable to change notification settings

### ISSUE THREAD

**Issue by webflo** [mattermost/platform#1139]
Hi, 

i am unable to change the notifications settings in my user account. My user account is a LDAP/OAuth User from GitLab.

I get the following error. "Invalid user, password and auth data cannot both be set"

![notification-settings](https://cloud.githubusercontent.com/assets/123946/10665075/c2b4e6f6-78c8-11e5-925a-e9f5b36f6086.png)

**Comment by jwilander** [comment]
Hi @webflo, thanks for reporting this!

I've created a ticket to track this on our public Jira instance [here](https://mattermost.atlassian.net/browse/PLT-803). I'm going to take a look at this issue right now

**Comment by jwilander** [comment]
Which version of Mattermost are you running? Is it off master or one of our releases?

**Comment by it33** [comment]
Hi @webflo, 

1. Could we ask your help to look under the **About Mattermost** option in the main menu and let us know your build number? 

2. So we can repro, can you let us know key differences between your `config.json` file and [this one](https://github.com/mattermost/platform/blob/v1.1.1/config/config.json)?

**Comment by webflo** [comment]
Thanks for the quick response!

@it33 https://gist.github.com/webflo/e9b61e975df2e46c701b is my config.json, i replaced all secrets with ???.

```
Mattermost 1.1.0
Build Number:3116
Build Date:Tue Oct 20 17:10:31 UTC 2015
Build Hash:b8eb11a4393779bd3a04ee3b0f13cb3e00806761
```

**Comment by coreyhulen** [comment]
a fix has been submitted to master.

**Comment by jwilander** [comment]
Hi @webflo a fix has been submitted to master and will be available in the next release. If you'd like to fix the state of your current user you can do one of two things if you own the Mattermost instance:

1. Start from a fresh Mattermost instance with a clean database
2. I can give you some database commands to run if you feel comfortable doing that (note this is risky and could break your instance if done incorrectly)

**Comment by webflo** [comment]
@jwilander I'll start over again, i don't care about my data because i am still in evaluation phase. Thanks!

**Comment by jwilander** [comment]
Sounds good!
