### ISSUE TITLE
"Incoming Webhook" management page unusable if exsiting webhook belongs to deleted channel

### ISSUE THREAD

**Issue by anthonyarnone** [mattermost/platform#1144]
**Steps to reproduce:**
Create a Channel
Crate an incoming webhook associated with the channel
Delete the channel
Go to Account Settings -> Integrations -> Incoming Webhooks -> Edit
Notice "Loading ..." never goes away
Cannot add new webhooks

**Observed behavior:**
Go to Account Settings -> Integrations -> Incoming Webhooks -> Edit
Notice "Loading ..." never goes away
Cannot add new webhooks
Screenshot: ![broken_webhook_dialog](https://cloud.githubusercontent.com/assets/826400/10671384/83b3d1ae-78a7-11e5-9aff-b4196b2f59f3.jpg)

**Expected behavior:**
Webhook still exists, but is associated to an existing channel

**Possible fixes:**
Unknown

**Comment by jwilander** [comment]
Wow, nice catch @anthonyarnone. I've created a [ticket here](https://mattermost.atlassian.net/browse/PLT-808) on our public Jira instance. I'm working on fix for this right now

**Comment by coreyhulen** [comment]
this is fixed
