### ISSUE TITLE
Support `attachments` for Incoming Webhooks

### ISSUE THREAD

**Issue by inty** [mattermost/platform#1156]
It seems that any non-string value in the JSON payload breaks the parsing. If there is such a value (like for attachments in the GitLab Slack hook) you get the error message "No text specified" back.

Seemed to me like this would work given the "Slack compatible label" :)

**Comment by it33** [comment]
Thanks @inty!

Sorry, it looks like we missed the `attachments` features in v1.1. I think we had it on the list and it didn't get into our test scenarios. 

Propose for now using the [GitLab Integration Service for Mattermost](https://github.com/mattermost/mattermost-integration-gitlab)? 

You can see a working version of the service on [the GitLab Mattermost test server](https://gitlab.mattermost.com/signup_user_complete/?id=fqbr3mubzjg9ty7cks5xkxr3hh), example:

![image](https://cloud.githubusercontent.com/assets/177788/10695124/e6f0ece8-7956-11e5-883c-53bcc93176ab.png)

Updating the title of this issue to queue a fix, and adding description: 
```
- Support `attachments` in Mattermost incoming webhooks compatible with Slack's API: https://api.slack.com/docs/attachments
```

**Comment by lfbrock** [comment]
Thanks @inty, 

We created a ticket [for accepting pull requests on this issue](https://mattermost.atlassian.net/browse/PLT-857). It's listed in [the Accepting Pull Requests issues list](https://mattermost.atlassian.net/browse/PLT-797?filter=10101). [Code Contribution Guidelines](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md) are available for anyone interested in contributing to this project.

**Comment by inty** [comment]
This works now with 1.2.1, thanks!

**Comment by muddydixon** [comment]
Now we are using mattermost v1.3.0 and gitlab 8.2.2, but this "No text specified" problem occurs.
Will it resolve in next 1.4?

**Comment by CoolGoose** [comment]
Same with gitlab 8.6 and mattermost 2.1 :)
