### ISSUE TITLE
Accepting Pull Requests: Show usernames overridden by Incoming Webhooks in notification messages

### ISSUE THREAD

**Issue by Juburin** [mattermost/platform#1158]
When an incoming webhook uses overriding of the username, on the notification is the name of the person whose integration link was used.

**Comment by it33** [comment]
Thanks @Juburin, appreciate the report. certainly an issue.

We've updated the [Limitations](https://github.com/mattermost/platform/blob/master/doc/integrations/webhooks/Incoming-Webhooks.md#limitations) section in the documentation with a note here.

Welcoming pull requests for a fix for this,

**Comment by lfbrock** [comment]
Thanks @Juburin,  

We created a ticket [for accepting pull requests on this issue](https://mattermost.atlassian.net/browse/PLT-856). It's listed in [the Accepting Pull Requests issues list](https://mattermost.atlassian.net/browse/PLT-797?filter=10101). [Code Contribution Guidelines](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md) are available for anyone interested in contributing to this project.

**Comment by trashcan** [comment]
This looks to be resolved in pull #1236.
