### ISSUE TITLE
Invite team links issue

### ISSUE THREAD

**Issue by 0vermind** [mattermost/platform#1169]
When new people uses invite team link and register, if they log out  they cannot enter the team anymore.
The only way is to use the "find the team" link.
But is they cut the URL the system is able to recognize them again and they can enter again in the correct team. Seems a cookie problem to me.
We need to simplify the way people can join a project. http://mattermost.uservoice.com/forums/306457-general/suggestions/9982719-add-restricted-users

**Comment by it33** [comment]
Hi @0vermind, thanks for the issue report!

This should be fixed on master (with this PR: https://github.com/mattermost/platform/pull/1129) and ship 11/16 in Mattermost v1.2
