### ISSUE TITLE
Bug: Searching for "привет" won't work when using Postgres as a database

### ISSUE THREAD

**Issue by Glueon** [mattermost/platform#1180]
Tried to search some text in current chat entering some non-english text - shows no result even if the text exists. Search with english letters, symbols and numbers works ok.

I was trying the latest 1.1.1 release. Installed manually.

**Comment by it33** [comment]
Hi @Glueon, 

Appreciate the feedback, could you help share the non-English words that weren't working for you? 

Also, there's an open ticket to solve some issues with Chinese and Japanese search terms: https://mattermost.atlassian.net/browse/PLT-97

**Comment by Glueon** [comment]
As soon as I am from Russia non of the russian ones worked. For example "привет" which is "hello".
I thought that maybe it's urlencode related, so tried to manually trigger a search by accessing API URL - gives no result as well. So maybe somewhere you use a fulltext search which does not support anything other than english.

**Comment by it33** [comment]
Hi @Glueon, 

I just tried the below query on v1.1.1 and it works for me, can you help share your results?

![screenclip 3](https://cloud.githubusercontent.com/assets/177788/10729159/add6bd48-7ba4-11e5-9756-0c092b07d59c.png)

**Comment by Glueon** [comment]
Interesting. Well I was wrong about a version. I have 1.1.0. Should I try to upgrade and try?

**Comment by it33** [comment]
Hi @Glueon, 

There should be a difference between 1.1.0 and 1.1.1 for this feature. Can you try the search again and paste back an image of the results you get? 

I'm wondering if it might be the use of different character sets...

**Comment by Glueon** [comment]
So should I upgrade beforehand or not? If yes, then what is the procedure?
I get "NO RESULTS". Also I gave you a direct response from an API.

**Comment by Glueon** [comment]
I looked into code and tried to compose the search query by myself. Indeed it produces 0 results, because PostgreSQL drops all russian letters from a tquery. Maybe it's encoding related (i tried using both cp1251 and utf-8 in a psql) or maybe omitting query configuration i.e. using `simple` search type implicitly does not work with non-en languages.

I hope the result you showed me are from an MySQL installation because as far as I see you use simple `MATCH AGAINST` which should work out of the box with multiple languages. Not an expert though.

Also according to commit log the search part was slightly changed from version 1.1.0 to 1.1.1. Maybe it's corrected in 1.1.1 but I do not know how to upgrade.

**Comment by it33** [comment]
Hi @Glueon, sorry for the late response, here are the [upgrade instructions](https://github.com/mattermost/platform/blob/master/doc/install/Upgrade-Guide.md)

**Comment by it33** [comment]
Adding @esethna to try and repro the search issue mentioned here on an instance with Postgres

**Comment by thinhduckhoi** [comment]
Sorry but i'm absolutely to Mattermost. I read the README.md and didn't see anything related to postgresql or mysqld.... What do you mean by using wordpress as a database?

**Comment by thinhduckhoi** [comment]
The same here when searching for Japanese 日本語。Seems like we can only search using alphabet i think.

**Comment by it33** [comment]
Hi @thinhduckhoi, please see [documentation on database selection for Japanese language search](http://docs.mattermost.com/install/requirements.html#database-software) with a ngram Full-Text parser to support your requirements? 

@Glueon, if the upgrade instructions didn't solve your issue, could we have your help opening a new GitHub Issue with repro steps and the Mattermost version you're using to test? 

Closing this issue so future readers won't have so much to read if they do hit the same issue.
