### ISSUE TITLE
Resize inline images

### ISSUE THREAD

**Issue by justyns** [mattermost/platform#1188]
We noticed in-line images (from markdown) are not automatically resized.   For example, http://i.imgur.com/Jg1GTWB.jpg is 2000x1493 and tries to be that big when posted in chat.

Letting the browser resize the image should be fine, I think something just needs to automatically set the height/width tags if it exceeds a certain size.

**Comment by it33** [comment]
Thanks @justyns, this is fixed on master and should ship with v1.2 on 11/16

![screenclip 16](https://cloud.githubusercontent.com/assets/177788/10741485/4174ec9c-7be5-11e5-8bce-5beac31e76c2.png)

**Comment by justyns** [comment]
perfect!  I tested this on master just now and you're right, it does look correct.   Thanks
