### ISSUE TITLE
Enable option to replace [TEAM_NAME].[DOMAIN] with [IP ADDRESS]/[TEAM_NAME] for local installs

### ISSUE THREAD

**Issue by cloudtrends** [mattermost/platform#119]
hi team,

I am running mattermost on my local centos ,  I had not config the domain by using the IP address directly, such as below :

http://1.1.1.1:8065/

There are an input box on home page told me that " Enter your team's domain. " . 

When I click the " Sign up " button , the browser redirect to : http://www.1.1.1:8065 , which of course can not visit .

What my question is , how can I "Sign up" my own test domain for login ?

thanks

**Comment by it33** [comment]
Hi @cloudtrends, you can either use Docker and http://dockerhost:8065/, or map in a domain, direct use of an IP address is not supported in the first release. This is a known issue and you should see a pull request for it in a week or two to address this, and we'll have a new major release in about 4 weeks,

**Comment by cloudtrends** [comment]
hi @it33 ,

Following your guide, I map my IP to a domain , such as :  mm.com:8065

When I click the signup button , the browser redirect to : www.com:8065 

Is there exists any location for config a test domain by default ?

thanks

**Comment by crspeller** [comment]
In order for this to work you need to map a wildcard domain of the form "*.domain.tld". This will cause any subdomain to redirect to the same IP. Then you can visit www.domain.tld and it should work.

**Comment by it33** [comment]
There are several tickets relating to this and an approved Feature Request to make this easier: http://mattermost.uservoice.com/forums/306457-general/suggestions/8677084-add-ability-to-use-ip-address-team-instead-of-te

Queuing for our 0.6.0 release that should be around end of the month, and there may be a pull request for this feature by end of next week,

**Comment by cifvts** [comment]
Waiting for this issue to be solved, I'm eager to put the software on test

**Comment by crspeller** [comment]
#200 When merged will fix this.
