### ISSUE TITLE
Idea/Proposal to change channel layout

### ISSUE THREAD

**Issue by florianorben** [mattermost/platform#1207]
In the current channel view quite a lot if space is wasted with names and avatars (in full-width view).
I'd suggest to change the layout a little bit, to more resemble the narrow width one - this could probably also fix the issue with "grouping post that belong to the same user" (see screens).

I also submitted a quick and dirty pull request (nowhere near prod quality) so you can have a look at it.
(PR also lightens color of own-posts a little + only tested for light themes)

*Before*:
![diff_layout_before](https://cloud.githubusercontent.com/assets/1024005/10776714/1829a5a0-7d14-11e5-82c5-ccc3b7af70de.png)
*After*:
![diff_layout_after](https://cloud.githubusercontent.com/assets/1024005/10776717/1c538d30-7d14-11e5-9051-1a3be360fb91.png)

**Comment by it33** [comment]
Thanks @florianorben! 

Appreciate your thinking here. We've gone back and forth on the design of the center channel, 

Our principles for wide screens was: 

1. Make text as readable as possible
2. Offer as much reading area as we can

And in our minds we did give up some consistency and aesthetic value

Regarding 1) it meant keeping columns fixed width (as you have), so text is more easily scanned with the eye. 

Regarding 2) it meant maximizing the number of messages in a vertical space, by moving the usernames to the side.

The core team discussed changing the center channel recently and agree it can use improvement. Would you be interested some time in chatting about it on the our [daily build's server](https://pre-release.mattermost.com/signup_user_complete/?id=rcgiyftm7jyrxnma1osd8zswby) with us? 

There's automation bringing in feeds of PRs from GitHub into the [Community Heartbeat](https://pre-release.mattermost.com/core/channels/community-heartbeat) channel, which you can access if you accept the invite above. 

We have a number of core team members working on design there, as well as contributors there. The changes you bring up are more a group discussion (online hours are typically 9am to 2pm PST - UTC-07, but we keep up with discussions asynchronously)

For example: While I personally like the shade of grey you have for highlight for own-posts, we looked at all the variations in the past, and the current shade was a group decision (open to change I think).

PS: Really like you're grouping of messages from the same user. It was a [user requested feature](http://mattermost.uservoice.com/forums/306457-general/suggestions/8684005-unite-messages-of-the-same-user) for a while, but I think we forgot to file a ticket unfortunately...

**Comment by florianorben** [comment]
Hey @it33!

I understand, those decisions are always a little complicated, we also have those at the company I work at ;) - so I just tried it with a shot into the dark, to see if I could be of help :)

Sure, I'd really like to get some involvement/add some contribution , just tell me what to do, and I'll join a chat/discussion (9am-2pm PST is perfect, since I usually stop working at 2am PST ;) )!

Changing the grey tone was just since the default one felt a little too dark for my personal taste (and since I was messing with the code anyway, I played around with the color) - although something like this could also easily be changed via theme settings I guess, if it is important at all to allow a change there.

PS: That was the requested feature I was thinking about when I wrote the desciption, just didn't find a link to it (though I didn't really look for it more than just a few clicks here and there).

**Comment by it33** [comment]
Thanks @florianorben! Our day starts at 9am PST, so I may be in and out of meetings, but I'm going to start a thread on this in the Feature Ideas room, which you can join after you're in,

**Comment by fungos** [comment]
:+1:

**Comment by florianorben** [comment]
Closing, since the channel just has been redesigned, awesome work :+1:
