### ISSUE TITLE
Team Names that are less than four characters need to be validated

### ISSUE THREAD

**Issue by reach3r** [mattermost/platform#1215]
Version: release 1.1.0 
At the end of the creation of a new team one can get the error
> Name must be 4 or more lowercase alphanumeric characters

However this does neither refer to the user name nor to the team name, but apparently to the team URL.

When faced with it for the first time I was confused as hell, because it appears on the page where basically everything is done already and only the users password is asked.

I made a small screenshot story to illustrate:
![1teamname](https://cloud.githubusercontent.com/assets/15228867/10795346/a00079f6-7d99-11e5-9219-d9a7f607bff4.png)
![2teamurl](https://cloud.githubusercontent.com/assets/15228867/10795358/abae5e6c-7d99-11e5-96ad-70f1edcd4aa7.png)
![3username](https://cloud.githubusercontent.com/assets/15228867/10795357/abaa7ca2-7d99-11e5-8044-1cd5e9331069.png)
![4laststep](https://cloud.githubusercontent.com/assets/15228867/10795447/19790a6e-7d9a-11e5-87e3-16b9a5122f75.png)

Since I'm no programmer (not a professional one anyways) I cant't give relevant references to the code, with a simple search I found one result:
https://github.com/mattermost/platform/blob/release-1.1.0/model/team.go
line 135

**Comment by Glueon** [comment]
I agree. I  was confused as well.
In my case I entered a team name with a capital letter which is not allowed and I got the same error only at the end. While It should show an error while choosing a "Team name", not at the end.

**Comment by it33** [comment]
Hi @reach3r, @Glueon, thanks for the report! Agree this needs to be fixed, 

There's a [ticket for this accepting pull requests](https://mattermost.atlassian.net/browse/PLT-835) and we're hoping to have it resolved before the next release. 

We're looking for a community member who'd like to knock this out as a [good first contribution project](https://mattermost.atlassian.net/issues/?filter=10206), and if not, then it'll fall into the core team's priority queue, 

We try to balance providing opportunities for the community to participate with product quality,

**Comment by it33** [comment]
Just an update, this is turning out to be a significant issue for GitLab Mattermost users, so core team is queuing as a bug fix now: https://mattermost.atlassian.net/browse/PLT-835
