### ISSUE TITLE
Accepting Pull Requests: Add header to email notifications so non-US-ASCII emails can render

### ISSUE THREAD

**Issue by oerdnj** [mattermost/platform#1229]
The email headers are missing a charset declaration and thus the non-US-ASCII emails are broken in some email clients:

A very simple change from `Content-Type: text/html` to `Content-Type: text/html; charset=utf-8` should fix the issue.

**Comment by it33** [comment]
Thanks @oerdnj! 

Combining threads here: https://forum.mattermost.org/t/email-notifications-broken-email-content-encoding-and-empty-sender-field/440/2

Straight forward pull request for anyone who'd like to contribute (ideally by someone who uses an email client where this header impacts rendering, so it can be confirmed working).

**Comment by oerdnj** [comment]
Looks like it has been already fixed in 830c6b3f
