### ISSUE TITLE
Accepting Pull Requests: Upgrade github.com/disintegration/imaging to fix i386

### ISSUE THREAD

**Issue by NotSqrt** [mattermost/platform#1239]
Hi,

github.com/disintegration/imaging needs to be upgraded, to include a fix for i386 OS.

Commit https://github.com/disintegration/imaging/commit/abefa83ecf5cf460db695ee89bd16f21e0c58bcf does the fixing !

By manually upgrading it, I was able to build and use mattermost on a i386 ubuntu.

Thanks!

**Comment by it33** [comment]
Thanks @NotSqrt, appreciate the ticket!

Just curious, is there any special reason why you're running Mattermost on an i386?

**Comment by NotSqrt** [comment]
Old ubuntu server that required i386 at the time for some softwares.. Never took the time to switch it to 64 bits.

**Comment by it33** [comment]
Thanks @NotSqrt, sorry for the delay, [opening an APR](https://mattermost.atlassian.net/browse/PLT-1098). Unfortunately, now that we're into the stablization process, we're generally only fixing regressions, so this fix would need to go into master for the v1.3 release cycle. 

Apologies for not filing this sooner, our fault.

**Comment by NotSqrt** [comment]
Thanks @it33 

I've no idea how to handle the dependencies in go..
I've seen https://github.com/mattermost/platform/blob/master/Godeps/Godeps.json that references the hash of the libraries..

This change is probably one command away, you'll handle it much more easily than me !

**Comment by coreyhulen** [comment]
The lib has been updated in master.
