### ISSUE TITLE
Feature Idea: Search across attached files

### ISSUE THREAD

**Issue by sumitag** [mattermost/platform#1243]
search currently doesn't provide any results from attached files.

**Comment by it33** [comment]
Thanks @sumitag, appreciate the feedback, 

Agree this makes sense. This feature may require some detailed specification before tickets can be created. 

Could we have your help [contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be upvoted by the community and the item prioritized?

**Comment by lfbrock** [comment]
Closing issue, feature idea can be upvoted here: http://mattermost.uservoice.com/forums/306457-general/suggestions/10227054-search-should-include-filenames-of-attached-files

**Comment by sumitag** [comment]
Feature idea to upvote https://mattermost.uservoice.com/forums/306457-general/suggestions/10508949-search-text-of-attached-files
