### ISSUE TITLE
Feature idea: Blacklist temporarily domains in registration process

### ISSUE THREAD

**Issue by 0vermind** [mattermost/platform#1258]
Would be useful to block some temporary domains in the registration process. especially if  the guests access will be implemented.

**Comment by it33** [comment]
Thanks @0vermind, appreciate the feedback, 

Agree this makes sense. This feature may require some detailed specification before tickets can be created (e.g. does this go into team settings or System Console settings, both, error messages to user trying to sign-up, etc.)

Could we have your help [contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be upvoted by the community and the item prioritized?
