### ISSUE TITLE
Messages with /me get swallowed

### ISSUE THREAD

**Issue by yuvipanda** [mattermost/platform#1261]
If I type:

```/me waves```

I'd expect it to (hopefully) show up as an action or just appear with the /me. However right now they get swallowed. 

(I was going to file this on uservoice but apparently 'I have used all my existing votes and can not create new anything')

**Comment by it33** [comment]
Should be fixed by https://github.com/mattermost/platform/pull/1263

Also, having a `/` at the start of a message no longer causes message sending to fail on master,

**Comment by coreyhulen** [comment]
PR has been merged to master
