### ISSUE TITLE
Accepting Pull Requests: No visible scrollbar for scrolling through messages 

### ISSUE THREAD

**Issue by yuvipanda** [mattermost/platform#1262]
Scrolling with my scroll wheel works but there's no scrollbar to provide a visual indicator of how much there is to scroll.

**Comment by it33** [comment]
Tracking ticket on this: https://mattermost.atlassian.net/browse/PLT-199, the center channel was just refactored, not sure if this can make it into v1.2 since we're locking this week and there's a lot to do. 

We're taking another look on this one.

**Comment by it33** [comment]
Didn't make it into v1.2. Set the ticket to Accepting Pull Requests: https://mattermost.atlassian.net/browse/PLT-199

**Comment by coreyhulen** [comment]
this is fixed in master.
