### ISSUE TITLE
Change button color while uploading image

### ISSUE THREAD

**Issue by kracekumar** [mattermost/platform#1266]
While updating the image, `Select` and `Save` button have same color. This is confusing. Please change the colour of any one of the button.
![screen shot 2015-11-02 at 4 42 00 pm](https://cloud.githubusercontent.com/assets/311929/10880357/9ed0defa-8180-11e5-8ff6-fb8f7ad2a54a.png)

**Comment by it33** [comment]
Hi @kracekumar, 

Appreciate the feedback, we're thinking through this right now. Current thinking is that the layout of the controls needs updating, not necessarily just the button color,

**Comment by it33** [comment]
Hi @kracekumar, while this isn't [a regression or obvious error](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#github-issues), moving this to [a task to redesign this page](https://mattermost.atlassian.net/browse/PLT-1266)--we think more needs to be done than just a button color change.
