### ISSUE TITLE
Accepting Pull Requests: Vine URLs get treated as Youtube, and fail to preview

### ISSUE THREAD

**Issue by lloeki** [mattermost/platform#1280]
An example with: https://vine.co/v/eDeVgbFrt9L

![screenshot 2015-11-03 13 55 18](https://cloud.githubusercontent.com/assets/75445/10908480/93e8c996-8232-11e5-8f7a-bd9781917d59.png)

**Comment by it33** [comment]
Repro confirmed, Accepting Pull Requests to fix: https://mattermost.atlassian.net/browse/PLT-1049
