### ISSUE TITLE
Unable to run platform (panic: runtime error: invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by laurent149** [mattermost/platform#1295]
Hello,

I'm trying to deploy mattermost following as closely as possible the [Production-Ubuntu](https://github.com/mattermost/platform/blob/master/doc/install/Production-Ubuntu.md) instructions.
Now the reason I say "as closely as possible" is because my server imposes lots of constraints.
Here's the target infrastructure:
* CentOS 5.11 (2.6.18-406.el5 x86_64 GNU/Linux)
* mysql  Ver 14.12 Distrib 5.0.95, for redhat-linux-gnu (x86_64) using readline 5.1

I realize this is far from what you recommend and you'd have every reason to ignore this request but I hope you'll understand such constraints are unfortunately common in the IT world...

Because of the old MySQL version, I had to apply the workaround described by @stephenfin in [Issue 928](https://github.com/mattermost/platform/issues/928), which seemingly worked fine (I can see the 12 tables created).
I unzipped the *mattermost v1.1.0* archive and created the *data* folder as described, then I edited the *config.json* file as follows:

    "DriverName": "mysql",
    "DataSource": "<user>:<password>@tcp(localhost:3306)/mattermost?charset=utf8&allowOldPasswords=1",

But then when I try to run the server, it fails with following output:

    [fuseiss@bdiss0001ap bin]$ ./platform 
    [11/04/15 08:49:13] [INFO] Current version is 1.1.0 (2920/Wed Oct 14 19:29:00 UTC 2015/4ad9e0673ca8950597a290f10db10475b18b67cc)
    [11/04/15 08:49:13] [INFO] Current working directory is /fuseiss/forge/mattermost/bin
    [11/04/15 08:49:13] [INFO] Loaded config file from /fuseiss/forge/mattermost/config/config.json
    [11/04/15 08:49:13] [INFO] Server is initializing...
    [11/04/15 08:49:13] [INFO] Pinging sql master database
    [11/04/15 08:49:13] [INFO] Pinging sql replica-0 database
    [11/04/15 08:49:13] [DEBG] Initializing user api routes
    [11/04/15 08:49:13] [DEBG] Initializing team api routes
    [11/04/15 08:49:13] [DEBG] Initializing channel api routes
    [11/04/15 08:49:13] [DEBG] Initializing post api routes
    [11/04/15 08:49:13] [DEBG] Initializing web socket api routes
    [11/04/15 08:49:13] [DEBG] Initializing file api routes
    [11/04/15 08:49:13] [DEBG] Initializing command api routes
    [11/04/15 08:49:13] [DEBG] Initializing admin api routes
    [11/04/15 08:49:13] [DEBG] Initializing oauth api routes
    [11/04/15 08:49:13] [DEBG] Initializing webhook api routes
    [11/04/15 08:49:13] [DEBG] Parsing server templates at /fuseiss/forge/mattermost/api/templates/
    [11/04/15 08:49:13] [DEBG] Initializing web routes
    [11/04/15 08:49:13] [DEBG] Using static directory at /fuseiss/forge/mattermost/web/static/
    [11/04/15 08:49:13] [DEBG] Parsing templates at /fuseiss/forge/mattermost/web/templates/
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x38 pc=0x7aedff]
    
    goroutine 1 [running]:
    gopkg.in/fsnotify%2ev1.(*Watcher).isClosed(0x0, 0x28)
    	/home/travis/gopath/src/github.com/mattermost/platform/Godeps/_workspace/src/gopkg.in/fsnotify.v1/inotify.go:64 +0x1f
    gopkg.in/fsnotify%2ev1.(*Watcher).Add(0x0, 0xc208274270, 0x27, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/mattermost/platform/Godeps/_workspace/src/gopkg.in/fsnotify.v1/inotify.go:92 +0x83
    github.com/mattermost/platform/web.watchAndParseTemplates()
    	/home/travis/gopath/src/github.com/mattermost/platform/web/web.go:116 +0x5b6
    github.com/mattermost/platform/web.InitWeb()
    	/home/travis/gopath/src/github.com/mattermost/platform/web/web.go:83 +0x2462
    main.main()
    	/home/travis/gopath/src/github.com/mattermost/platform/mattermost.go:57 +0x4e2
    
    goroutine 10 [chan receive]:
    database/sql.(*DB).connectionOpener(0xc208059900)
    	/usr/local/go/src/database/sql/sql.go:589 +0x4c
    created by database/sql.Open
    	/usr/local/go/src/database/sql/sql.go:452 +0x31c
    
    goroutine 6 [syscall]:
    os/signal.loop()
    	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
    created by os/signal.init·1
    	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35
    
    goroutine 7 [runnable]:
    code.google.com/p/log4go.ConsoleLogWriter.run(0xc208056120, 0x2b17da2a7fc8, 0xc20802e008)
    	/home/travis/gopath/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:27 +0x7a
    created by code.google.com/p/log4go.NewConsoleLogWriter
    	/home/travis/gopath/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:19 +0x6b
    
    goroutine 8 [runnable]:
    code.google.com/p/log4go.func·002()
    	/home/travis/gopath/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/filelog.go:84 +0xa53
    created by code.google.com/p/log4go.NewFileLogWriter
    	/home/travis/gopath/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/filelog.go:116 +0x3da
    
    goroutine 9 [chan receive]:
    database/sql.(*DB).connectionOpener(0xc208059720)
    	/usr/local/go/src/database/sql/sql.go:589 +0x4c
    created by database/sql.Open
    	/usr/local/go/src/database/sql/sql.go:452 +0x31c
    
    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
    	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
    
    goroutine 11 [select]:
    github.com/mattermost/platform/api.func·028()
    	/home/travis/gopath/src/github.com/mattermost/platform/api/web_hub.go:66 +0x875
    created by github.com/mattermost/platform/api.(*Hub).Start
    	/home/travis/gopath/src/github.com/mattermost/platform/api/web_hub.go:96 +0x8c
    
    goroutine 49 [runnable]:
    github.com/mattermost/platform/web.func·001()
    	/home/travis/gopath/src/github.com/mattermost/platform/web/web.go:100
    created by github.com/mattermost/platform/web.watchAndParseTemplates
    	/home/travis/gopath/src/github.com/mattermost/platform/web/web.go:114 +0x595

I downloaded the sources and tried to interpret the stack myself but I'm really not fluent enough with Go :-(

Any idea what goes wrong?

Many many thanks in advance!

Laurent

**Comment by coreyhulen** [comment]
Looks like http://gopkg.in/fsnotify.v1 the 3rd party lib we use for file system notifications is failing to watch for file changes in a directory.

There is a small bug here when we fail to watch the dir we should return vs continuing.  But that wouldn't be much help to you since it's going to panic with "Failed to watch" vs a nil pointer.

I suspect it's probably something todo with the older version of CentOS and our 3rd party lib.

**Comment by laurent149** [comment]
Many thanks for your prompt and valuable feedback! :-)
I'll try to negotiate a more recent CentOS release and keep you posted on the outcome.

**Comment by laurent149** [comment]
I tried with a CentOS 6.7 and it worked :-)
Many many thanks again!
