### ISSUE TITLE
Notifications not working / Realtime messaging not working

### ISSUE THREAD

**Issue by fculpo** [mattermost/platform#1296]
Hi,

On an Omnibus Gitlab install, mattermost is working fine except this :
Even though i setup to enable desktop notifications and sounds, i do not receive any such notification when someone post, or even direct message me.

I have also to change channel and reenter the previous one to see updates, which is not the way it should work i guess :)

Any ideas, or debug file to provide ?

**Comment by fculpo** [comment]
I'm behind a reverse proxy (Citrix NetScaler) which route traffic like this : Internet---SSL---NetScaler---SSL---Gitlab/Mattermost

**Comment by fculpo** [comment]
Issue also opened in Omnibus tracker: https://gitlab.com/gitlab-org/omnibus-gitlab/issues/924

**Comment by coreyhulen** [comment]
@fculpo, It sounds like the websocket isn't connecting to the server.  What version of Mattermost are you running?  If you're version 1.0+ you should see a blue bar at the top with an error about connecting.

**...** > **About Mattermost** should give you the version.

You need to make sure your proxy server will allow a http:// connection to be upgraded to ws:// (or https to wss) on the port mattermost is running on.

You can verify by looking at the browser console.  You should see connection errors if it's the websocket.  **right click** on Mattermost webpage > **Inspect Element** > **Console**

**Comment by fculpo** [comment]
Hi @coreyhulen, here is my diag :

When connecting to Reverve Proxy on HTTPS, i see initial handshake in chrome, but not any websocket traffic after that.

If i connect to reverse proxy on HTTP (backend is still SSL), i see websocket traffic, and all is working.

**Comment by fculpo** [comment]
A client connected to HTTP receives notifications from messages sent from HTTPS client.

But HTTPS client to HTTPS client does not work

**Comment by fculpo** [comment]
Ok, so it seems to be related to this issue :

https://discussions.citrix.com/topic/371714-wss-sec-web-sock-site-on-the-unified-gateway-content-switch-not-working/

**Comment by fculpo** [comment]
Indeed after much testing, it is not possible with the setup i planned.
I ended up using nginx. Works fine now.
