### ISSUE TITLE
Mattermost Incoming Webhook Crash

### ISSUE THREAD

**Issue by RangerRick** [mattermost/platform#1300]
I configured the IRC webhook, and Mattermost is crashing every time it posts to Mattermost with errors like this: https://gist.github.com/RangerRick/d9cbb4c28dea78ae396f#file-mattermost-log

I just built a new snapshot this morning to see if it fixed it, but it's still happening: https://gist.github.com/RangerRick/0bd687d947952b298aff#file-mattermost-log

**Comment by coreyhulen** [comment]
I'm guessing this is from the surgery on the db.  I suspect you failed to delete a relationship in the ChannelMembers table.

**Comment by RangerRick** [comment]
Yup, it was.  Re-built my team (since I figure I'd have issues long-term with that surgery anyways) and all is good.  Sorry for the noise.
