### ISSUE TITLE
Desktop Client

### ISSUE THREAD

**Issue by Trozz** [mattermost/platform#1306]
Guys,

Can we get a repo created for a desktop client, it should be relatively easy to port the web code to a desktop client using something such as [Electron](https://github.com/atom/electron)

T

**Comment by coreyhulen** [comment]
I think there are some people from the community that have already created an Electron app.  See http://www.mattermost.org/community-applications/

**Comment by Trozz** [comment]
I see people have stolen my idea :smile:
