### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by Trozz** [mattermost/platform#1307]
There doesn't appear to an issue open for Packaging and doesn't appear to be anything in Jira.

Shall I look in to packaging Mattermost for DEB and possibly RPM systems?

This would provide people with a lower barrier to entry for usage of Mattermost

**Comment by coreyhulen** [comment]
We would love a deb package.  We have https://mattermost.atlassian.net/browse/PLT-675 but it keeps getting pushed :)

**Comment by Trozz** [comment]
fantastic, moving this to Jira
