### ISSUE TITLE
Accepting Pull Requests: Fix member list incorrectly decreasing when username changed

### ISSUE THREAD

**Issue by archen** [mattermost/platform#1322]
In version 1.1.0, when a user changes their username using the Account Settings > General menu, the member list drops them until a browser refresh is performed.

I'm using 1.1.0 deployed in the Gitlab CE Omnibus docker image
Build Number:3116
Build Date:Tue Oct 20 17:10:31 UTC 2015
Build Hash:b8eb11a4393779bd3a04ee3b0f13cb3e00806761

**Comment by it33** [comment]
Hi @archen, thanks for the bug report! 

Confirmed this repros on master and have opened [a ticket accepting pull requests](https://mattermost.atlassian.net/browse/PLT-1048)

Nice find!

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in [Jira](https://mattermost.atlassian.net/browse/PLT-1048)
