### ISSUE TITLE
WebHook for delete channel hangs Integrations panel

### ISSUE THREAD

**Issue by scbash** [mattermost/platform#1323]
After experimenting with a webhook, I deleted the channel I was experimenting on before removing the webhook from my Account Settings-->Integrations panel.  Now when I go to the Integrations panel, it gets stuck "Loading...", and I see the following error in the System Console:

`[2015/11/05 16:01:45 EST] [EROR] /api/v1/admin/log_client:client code=500 rid=ntzed1rtqbdfzgxpax93g6wc5y uid=m4ce4gh8yt86ufysmi3u97sity ip=10.101.201.108 msg: TypeError: null is not an object (evaluating 'a.name') row: 17 col: 39252 stack: undefined url: https://vulcan.example.com/static/js/react-with-addons-0.13.3.min.js [details: ]`

While waiting for a fix, is there a workaround?  Do I need to edit the database?

**Comment by scbash** [comment]
I was able to edit the database:
```sql
update incomingwebhooks set deleteat=1446586709230 where id='uo5rnxiwcf8p8kiokabffm7dyr';
```
and that at least made the Integrations panel usable again.

**Comment by it33** [comment]
Thanks @scbash!

Appreciate the feedback, sorry for the bug, fixed on master: https://github.com/mattermost/platform/pull/1149

**Comment by scbash** [comment]
Thanks!  Guess I should have searched the closed tickets more carefully...
