### ISSUE TITLE
Using Utils.getDisplayName() instead of profile.username in user_profile.jsx?

### ISSUE THREAD

**Issue by jdeng** [mattermost/platform#1343]
Something like below?

diff --git a/web/react/components/user_profile.jsx b/web/react/components/user_profile.jsx
index eb0a8f0..d0a54a6 100644
--- a/web/react/components/user_profile.jsx
+++ b/web/react/components/user_profile.jsx
@@ -54,7 +54,8 @@ export default class UserProfile extends React.Component {
         }
     }
     render() {
-        var name = this.state.profile.username;
+//        var name = this.state.profile.username;
+        var name = Utils.getDisplayName(this.state.profile);
         if (this.props.overwriteName) {
             name = this.props.overwriteName;
         }

**Comment by it33** [comment]
Thanks @jdeng, asking for @coreyhulen's help reviewing your thoughts here, there was a previous PR for this, but it caused some performance issues, I don't have all the details...

**Comment by coreyhulen** [comment]
this is scheduled for the net sprint. see https://mattermost.atlassian.net/browse/PLT-995

**Comment by it33** [comment]
Hi @jdeng, 

We'd love your help taking a shot at the above ticket if you're interested, 

Closing this issue for now, 

If you'd like to discuss this ticket further please join us on https://pre-release.mattermost.com/core/channels/tickets?

**Comment by coreyhulen** [comment]
I think this is being tracked in several different places

https://github.com/mattermost/platform/pull/1324
https://mattermost.atlassian.net/browse/PLT-995
