### ISSUE TITLE
Cannot rename Town Square and Off-Topic

### ISSUE THREAD

**Issue by jdhoek** [mattermost/platform#1356]
I cannot find a way to rename the default channels `Town Square` ~~and `Off-Topic`~~. These names are confusing in a non-English context.

Related to #1201, which was closed by the submitter for unknown reasons.

**Update:** Off-Topic can now be renamed.

**Comment by it33** [comment]
Hi @jdhoek, appreciate the feedback, you should be able to rename Off Topic in v1.2, and now opening a ticket for renaming [Town Square](https://mattermost.atlassian.net/browse/PLT-1086) to track this,

**Comment by kevgathuku** [comment]
@jdhoek @it33 I can confirm that the Off-Topic channel can be renamed. I just tried it.

**Comment by jdhoek** [comment]
@it33 @kevgathuku 
Ah yes! Off-Topic can indeed be renamed. Nice!

**Comment by mrbrazjava** [comment]
+1 for Town Square renaming

**Comment by stefuNz** [comment]
+1 for Town Square renaming

**Comment by baptistedonaux** [comment]
+1

**Comment by fungos** [comment]
+1

**Comment by it33** [comment]
PR merged: https://github.com/mattermost/platform/pull/1437

**Comment by alexdesalta** [comment]
Hello

I install Mattermost in VPS with Mysql DB.

I Just do this

mysql -u mmuser -p
use mattermost;
UPDATE Channels SET DisplayName = 'Whatever' WHERE DisplayName = 'Town Square';
also you can
UPDATE Channels SET DisplayName = 'Whatever II' WHERE DisplayName = 'Off-Topic';
exit

**Comment by jermanoid** [comment]
The suggestion from @alexdesalta worked for me on postgres as well
