### ISSUE TITLE
Cannot delete teams without manually modifying the database

### ISSUE THREAD

**Issue by jdhoek** [mattermost/platform#1357]
There is no way to delete teams without manually diving into the database.

See: http://forum.mattermost.org/t/how-can-i-delete-teams/220

This seems like a pretty crucial feature that will be implemented at some point. Is it planned or are there reasons not to include this functionality?

**Comment by coreyhulen** [comment]
This should be solved with https://mattermost.atlassian.net/browse/PLT-975

**Comment by it33** [comment]
Agree this is an issue, closing GitHub now that we have a tracking ticket that has a sprint and fix version assigned
