### ISSUE TITLE
Yellow tinge in text input fields makes text illegible in dark themes

### ISSUE THREAD

**Issue by jdhoek** [mattermost/platform#1358]
The yellow tinge indicating connection problems introduced in #159 is the same for all themes. With dark themes this makes the text typed in these fields illegible.

Please see attached screenshot for an example of what happens with one of the included dark themes (*Windows Dark*).

![yellow_input_field](https://cloud.githubusercontent.com/assets/683699/11022401/02bc354a-865e-11e5-80b7-f625d86b03bf.png)

**Comment by it33** [comment]
Thanks @jdhoek, will look into a solution for this,

**Comment by it33** [comment]
@esethna, can we have your help queuing for AM-LB and then circling back with response?

**Comment by esethna** [comment]
Hi @jdhoek, we discussed this in a team meeting, we're going to make the text color in the input box consistent across all themes if the browser hits connection problems.

Here is the [PR](https://github.com/mattermost/platform/pull/1383). The fix will be included in 1.2 shipping 11/16.

**Comment by jdhoek** [comment]
I don't see any commits in the PR, but I'll assume the text colour is darkened to complement the yellow. It's fine if this special case is not styled according to the theme, as long as the text colour and background are compatible. :+1:

**Comment by it33** [comment]
PR committed, please re-open if it's still hard to read, thanks again for the report!
