### ISSUE TITLE
Need sample Slack Import files to repro and fix issue with Slack users not importing

### ISSUE THREAD

**Issue by Cezarion** [mattermost/platform#1359]
Hi, 

Thank's a lot for this great work. 
I would like to migrate my team to mattermost. I have installed app without problem, but when I have import slack team, channels are created but not users. 

Do you have an idea ?

**Comment by coreyhulen** [comment]
Is there any error messages in the mattermost logs?  From the system console you can view the server logs, or from the file dir `logs` where mattermost is installed.

**Comment by npcode** [comment]
I have the same issue. There are no errors but a log of warnings.

Here is the log: https://gist.github.com/npcode/333ff5cd380d129b7ad0

**Comment by it33** [comment]
Hi @npcode, hi @Cezarion, appreciate your feedback. 

It's hard to debug without repro steps. Would either of you (or perhaps the community) be open to scrambling any private data in your Slack import files and sharing them so the community could help figure out what's happening?

Slack only exports data from public channels, so if what you're trying to import is from a Slack team that's public accessible anyway, then all you'd need to do is scramble the user data.

If you're Slack team isn't public, perhaps there is someone else monitoring this issue who might be open to contributing test data that would help us solve this.

**Comment by npcode** [comment]
I have linked two exported files from slack which inclue only users.json file. The first one works well but the second one does not work.

https://github.com/npcode/mattermost-import-from-slack-test/raw/master/slack-export-good.zip
https://github.com/npcode/mattermost-import-from-slack-test/raw/master/slack-export-bad.zip

I think my team was failed to be imported because of the same reason of the second one.

**Comment by it33** [comment]
Thanks @npcode!

@crspeller, just curious, anything you see from the `user.json` files below that would be obviously breaking Slack Import? 

I tested the files and got the same results

Good

```json
[
    {
        "id": "U0F3KNUH2",
        "team_id": "T0F3R27DF",
        "name": "eungjun.yi",
        "deleted": false,
        "status": null,
        "color": "4bbe2e",
        "real_name": "",
        "tz": "Asia\/Tokyo",
        "tz_label": "Japan Standard Time",
        "tz_offset": 32400,
        "profile": {
            "real_name": "",
            "real_name_normalized": "",
            "email": "eungjun.yi@blah.com",
            "image_24": "https:\/\/secure.gravatar.com\/avatar\/52da4b42a5770479cfdb119487485c55.jpg?s=24&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F66f9%2Fimg%2Favatars%2Fava_0006-24.png",
            "image_32": "https:\/\/secure.gravatar.com\/avatar\/52da4b42a5770479cfdb119487485c55.jpg?s=32&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F66f9%2Fimg%2Favatars%2Fava_0006-32.png",
            "image_48": "https:\/\/secure.gravatar.com\/avatar\/52da4b42a5770479cfdb119487485c55.jpg?s=48&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F66f9%2Fimg%2Favatars%2Fava_0006-48.png",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/52da4b42a5770479cfdb119487485c55.jpg?s=72&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F66f9%2Fimg%2Favatars%2Fava_0006-72.png",
            "image_192": "https:\/\/secure.gravatar.com\/avatar\/52da4b42a5770479cfdb119487485c55.jpg?s=192&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F7fa9%2Fimg%2Favatars%2Fava_0006-192.png",
            "image_512": "https:\/\/secure.gravatar.com\/avatar\/52da4b42a5770479cfdb119487485c55.jpg?s=512&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F7fa9%2Fimg%2Favatars%2Fava_0006-512.png",
            "fields": null
        },
        "is_admin": false,
        "is_owner": false,
        "is_primary_owner": false,
        "is_restricted": false,
        "is_ultra_restricted": false,
        "is_bot": false
    }
]
```

Bad
```json
[
    {
        "id": "U024PV5LU",
        "team_id": "T024PV5LS",
        "name": "eungjun.yi",
        "deleted": false,
        "status": null,
        "color": "9f69e7",
        "real_name": "EungJun Yi",
        "tz": "Asia\/Seoul",
        "tz_label": "Korea Standard Time",
        "tz_offset": 32400,
        "profile": {
            "first_name": "EungJun",
            "last_name": "Yi",
            "image_24": "https:\/\/avatars.slack-edge.com\/2015-02-25\/3837724570_49cfb2aee67ba71fff1f_24.jpg",
            "image_32": "https:\/\/avatars.slack-edge.com\/2015-02-25\/3837724570_49cfb2aee67ba71fff1f_32.jpg",
            "image_48": "https:\/\/avatars.slack-edge.com\/2015-02-25\/3837724570_49cfb2aee67ba71fff1f_48.jpg",
            "image_72": "https:\/\/avatars.slack-edge.com\/2015-02-25\/3837724570_49cfb2aee67ba71fff1f_72.jpg",
            "image_192": "https:\/\/avatars.slack-edge.com\/2015-02-25\/3837724570_49cfb2aee67ba71fff1f_192.jpg",
            "image_original": "https:\/\/avatars.slack-edge.com\/2015-02-25\/3837724570_49cfb2aee67ba71fff1f_original.jpg",
            "title": "Software engineer",
            "skype": "",
            "fields": {
                "Xf0D7C5VEY": {
                    "value": "",
                    "alt": ""
                }
            },
            "real_name": "EungJun Yi",
            "real_name_normalized": "EungJun Yi",
            "email": "eungjun.yi@blah.com"
        },
        "is_admin": true,
        "is_owner": true,
        "is_primary_owner": true,
        "is_restricted": false,
        "is_ultra_restricted": false,
        "is_bot": false
    }
]
```

**Comment by crspeller** [comment]
@it33 @npcode 
Investigating revealed that the culprit is:
```json
"fields": {
    "Xf0D7C5VEY": {
        "value": "",
        "alt": ""
    }
}
```
where the one that works has
```json
"fields": null
```

This seems to be breaking the golang json parser.

**Comment by npcode** [comment]
@crspeller Thanks for finding the culprit. I updated values of the fields in `users.json` to `null` then the exported data was imported successfully.

**Comment by Cezarion** [comment]
Hi ! 

Sorry for the long long time to give you a response. 
[slack-import.txt](https://github.com/mattermost/platform/files/45774/slack-import.txt)

I have no errors in my log import and no trace about users.

**Comment by philhq** [comment]
I have the same issue as @Cezarion

**Comment by it33** [comment]
[Adding ticket to track the fix for this issue](https://mattermost.atlassian.net/browse/PLT-2052)
