### ISSUE TITLE
Remove possibility of administrator lockout

### ISSUE THREAD

**Issue by brioscaibriste** [mattermost/platform#1379]
Version: 1.1.0

On initial setup, it's possible to lock yourself out of the systems administrator account by choosing your role as another. This will render the installation useless unless you have already created an admin user. 

This can be fixed by using the postgres command line if you are familiar enough with postgres/mysql to reset the admin account (to do this update the user that you have created in the mattermost database and set the user role to system_admin )

Please let me know if any further clarification is required.

**Comment by it33** [comment]
Hi @brioscaibriste, 

Appreciate the feedback, agree this is an issue, 

There's an [article on restoring system admin in the trouble shooting guide](https://github.com/mattermost/platform/blob/master/doc/install/Troubleshooting.md#lost-system-administrator-account),
