### ISSUE TITLE
Ability to remove Teams and remove members from Teams

### ISSUE THREAD

**Issue by sandywater** [mattermost/platform#1382]
This would be very helpful as I have many Team creation mistakes.  Also if we have a member leave the company it would be good to remove them from the Team in Mattermost.

You guys are doing AMAZING work!

**Comment by coreyhulen** [comment]
This should be solved with https://mattermost.atlassian.net/browse/PLT-975

**Comment by it33** [comment]
Thanks @sandywater! Hope to knock out 975 by v1.3 release, you can track the progress via the link above, so closing this ticket,
