### ISSUE TITLE
search is only finding exact matches

### ISSUE THREAD

**Issue by rompic** [mattermost/platform#1385]
I'm not sure if this is easy to fix, but I have the impression that the search function only comes up with exact matches which may not be what users expect (e.g. searching for vacation doesn't find vacations)

**Comment by rompic** [comment]
sorry, just found out about the * which helps. (no highlighting of the results though when using *)

**Comment by it33** [comment]
Thanks @rompic, appreciate the feedback, two tickets opened to track these: 

https://mattermost.atlassian.net/browse/PLT-1101
https://mattermost.atlassian.net/browse/PLT-1100
