### ISSUE TITLE
Team name beginning with 'team'

### ISSUE THREAD

**Issue by ibeardslee** [mattermost/platform#1387]
Trying to create a new team that has the word 'team' at the start of it.  Although I can understand why a team of just 'team' would be wanted to fail, other variations of the name should still succeed.

Eg  I have a team .. let's say it's called 'Team Awesome'*, because since the beginning of time that is how the group has been officially known to those involved.
The UI allows me to call the team 'Team Awesome',
But when I come to create the URL it tells me that the "URL is taken or contains a reserved word".
The url being offered is  http://localhost:8065/team-awesome.
Changing that to http://localhost:8065/teamawesome also fails.
http://localhost:8065/awesometeam succeeds.

I'd like to be able to have a url that reflects the 'official' name of the team.

Using the latest docker image.
* name changed for the example.

**Comment by coreyhulen** [comment]
You can disable the restricted name checks with
**System Console** > **Team Settings** > **Restrict Team Names:** == false

**Comment by coreyhulen** [comment]
This will ship with 1.2 in a few days.

**Comment by ibeardslee** [comment]
If this is coming in version 1.2, I'll close this now.  Thanks.
