### ISSUE TITLE
Earlier warning/rejection about the length of a team name

### ISSUE THREAD

**Issue by ibeardslee** [mattermost/platform#1388]
Rejecting the length of the team name in the url should happen at the point of suggesting the URL.

> Team Name
> Name your team in any language. Your team name shows in menus and headings.

I give it a name *Ian*

> Team URL
> http://localhost:8065/*ian*
> Choose the web address of your new team:
> Short and memorable is best
> Use lowercase letters, numbers and dashes
> Must start with a letter and can't end in a dash

It then allows me to go ahead and set my user name and password, when I click Finish, it then tells me

> Name must be 4 or more lowercase alphanumeric characters

* The process should reject the name (in the URL) before moving onto the user name and password.
* The requirements should also specify that the name has a minimum length instead of just *Short and memorable is best*

**Comment by coreyhulen** [comment]
This is fixed in master and will ship with 1.2 in a few days.  See https://mattermost.atlassian.net/browse/PLT-835

**Comment by ibeardslee** [comment]
In which case, we can close this issue.
