### ISSUE TITLE
Bug: "Go back to team site" link broken on "Sorry, we could not find this page" error page

### ISSUE THREAD

**Issue by rompic** [mattermost/platform#1394]
i just mistyped /admine_console and got the "... needs your help" page.
The go back to teamsite link links to the same wrong page /admine_console again

**Comment by it33** [comment]
Repro confirmed, ticket filed: https://mattermost.atlassian.net/browse/PLT-1129

**Comment by it33** [comment]
Closing since this is tracked in Jira ticket now
