### ISSUE TITLE
Notification number partially visible on small width

### ISSUE THREAD

**Issue by jason-riddle** [mattermost/platform#1397]
It looks like for notifications, if the width is small enough the notification number is only partially visible.

<img width="562" alt="screen shot 2015-11-11 at 11 34 31 am" src="https://cloud.githubusercontent.com/assets/2156866/11096483/52a81810-8868-11e5-8f7c-1186909c03ab.png">

**Comment by esethna** [comment]
Hi @jason-riddle

Thanks for the bug report, but I can't seem to repro this. Can you please provide your system info (ie browser, operating system)?

**Comment by jason-riddle** [comment]
It looks like this bug has already been fixed. I wasn't able to reproduce today.
