### ISSUE TITLE
Bug: Search bar disappears when clicking on search result of messages in current channel

### ISSUE THREAD

**Issue by jason-riddle** [mattermost/platform#1398]
## Bug

When using the search bar to search for a post, if you click on a post that is the same channel as your current channel, the search bar will disappear. So for example, if you are currently on the "Bugs" channel, and then you search for a keyword and click on the result post in the search window that belongs to the "Bugs" channel, will cause the search bar to dissappear.

## Steps to Reproduce:

1) Switch to the "Bugs" channel.
2) In the search bar, type in "notification".
3) In the results, click on any post that is in the "Bugs" channel.

<img width="952" alt="screen shot 2015-11-11 at 11 49 01 am" src="https://cloud.githubusercontent.com/assets/2156866/11097147/a1e36f94-886b-11e5-87f0-793da36c3956.png">

4) The search bar is gone.

<img width="952" alt="screen shot 2015-11-11 at 11 59 37 am" src="https://cloud.githubusercontent.com/assets/2156866/11097178/d37117be-886b-11e5-8286-2b1cef76d965.png">

5) To get the search bar to return, clear your cache.

**Comment by it33** [comment]
Hi @jason-riddle, 

Appreciate the bug report, sorry, having trouble reproducing it, 

It looks like you have a Chrome add-on, could you try to repro in incognito mode where the add-on would be disabled? 

Just want to remove the possibility it may be related,

**Comment by it33** [comment]
Oh, sorry, you're already in incognito mode. We should try to repro in that case...

**Comment by esethna** [comment]
Hi @jason-riddle,

Thanks for the bug report! I managed to reproduce the issue on Chrome by specifically clicking on the name, time-stamp or channel of a search when I use the in: search modifier. I found it was also possible to bring back the RHS and search bar by clicking on a comment thread, rather than clearing my cache.

I've filed the bug ticket in JIRA, thanks again,

**Comment by it33** [comment]
Thanks @esethna, would you have a link to the ticket?

**Comment by esethna** [comment]
Yep, https://mattermost.atlassian.net/browse/PLT-1124

**Comment by jason-riddle** [comment]
Cool thanks!
