### ISSUE TITLE
Bug: Safari 8 - Retry button doesn't show up on messages that fail to send when off-line after reconnecting

### ISSUE THREAD

**Issue by DschingisKahn** [mattermost/platform#1405]
The situation:
* Safari as browser
* I sent a message in my Town Square channel
* my internet connection was poor
* the message never got sent
* the message keeps popping up on the bottom of the screen, just above the input field, in the Town Square channel - showing a loading animation on the right side
* I cannot select the delete option (or any other option) to get rid of it

There is no sign of the message in the database and it does not show up in another browser (which makes sense of course). Clearing the cache brought no luck though.

When inspecting the element, I see that the data-reactid attribute ends with `$undefinedpostKey` and one of the nested div's has `id="undefined_message"`, `class="post-waiting"` and again a data-reactid attribute that contains `$undefinedpostKey` and `$undefined_message`.

The console throws the following warning: `Warning: flattenChildren(...): Encountered two children with the same key, '.1:$undefinedpostKey'. Child keys must be unique; when two children share a key, only the first child will be used.`

**Comment by it33** [comment]
Hi @DschingisKahn, appreciate the report, can you let us know which Mattermost version you're on and which version of Safari?

There is a known issue on Safari 8 in v1.2-RC1,

**Comment by it33** [comment]
This repros, ticket filed: https://mattermost.atlassian.net/browse/PLT-1154

**Comment by DschingisKahn** [comment]
Version 1.1.0 with Safari 8.0.7.

The linked ticket refers to another situation, where you are at least able to hit "retry". I added a screenshot for clarification purposes :-).

![screen shot 2015-11-13 at 09 22 37](https://cloud.githubusercontent.com/assets/1820125/11141774/ba0f69e6-89e8-11e5-8621-aff5b3c12f7a.png)

**Comment by it33** [comment]
Thanks @DschingisKahn

**Comment by DschingisKahn** [comment]
Will try!

**Comment by DschingisKahn** [comment]
Safari 8 is not supported by that version, it seems :-).

**Comment by it33** [comment]
Hi @DschingisKahn, sorry, I forgot that Safari 8 support had been removed. 

There were multiple issues with Safari 8 discovered close to the release of Mattermost v1.2, and given the technical cost of supporting it, and declining market share, we ended up giving up support. 

Just tested on Chrome/Win7 using throttle to toggle online/offline and the Retry button seems to be working. 

Just curious, could you help us understand more about why you're using Safari 8 and Safari 9? 

It was a back-and-forth decision on making Safari 9 the minimum requirement,

**Comment by DschingisKahn** [comment]
Thanks. It seems to be limited to Safari indeed (colleague had the same issue). I did not update yet to El Capitan, so that is why I am stuck with Safari 8 - no other reason.

Let's just not waste more time on this then (this feels a bit like good old IE times :-))

**Comment by it33** [comment]
Hi @DschingisKahn, 

I've been able to repro the issue on our nightly builds server in Chrome/Win7: 
![screenclip](https://cloud.githubusercontent.com/assets/177788/11434673/f9c2c8c0-9484-11e5-8d30-59b11d244faf.png)

Since it's not limited to Safari, I'm switch this ticket back to the original name. Sorry for the back and forth. 

I'm not yet able to get a consistent repro, but we know that it's not-browser specific. 

Thanks again for the report! This is something we need to fix.

**Comment by DschingisKahn** [comment]
Hi @it33,

Glad you could reproduce it, that's a start :). A few colleagues encountered it in the last days. It happens when our VPN connection drops at the same time a message is sent. Safari and Chrome indeed.

**Comment by lfbrock** [comment]
Closing this issue, it will tracked in [Jira](https://mattermost.atlassian.net/browse/PLT-1884)

**Comment by lfbrock** [comment]
Accepting pull request ticket here for adding the option to cancel sending a pending message: https://mattermost.atlassian.net/browse/PLT-1042
