### ISSUE TITLE
Delay after writing

### ISSUE THREAD

**Issue by faebser** [mattermost/platform#144]
## Actual
After writing something into the chat input and pressing enter there is a brief delay before anything happens.

## Expected
After writing something into the chat input and pressing enter, there is instant activity (either loading/spinner etc).

On Linux/Firefox 39.0 the delay is rather significant.
On Linux/Version 43.0.2357.130 (64-bit) is a bit shorter.

From my point of view this issue devalues the whole user experience highly and should be prioritized.
You could try to add the entered text directly to the post-list and show it as still sending.

**Comment by jwilander** [comment]
Hi faebser,

Thanks for the feedback!

This is a very good issue you bring up; any delay between a user action and a visible result is a bad experience for the user. We actually have an improvement ticket in our internal issue tracking system for this but I'll leave this issue open for public visibility on the issue.

**Comment by it33** [comment]
Hi @faebser, we originally had this filed as a feature request both internally and at: http://mattermost.uservoice.com/forums/306457-general/suggestions/8685295-make-message-sending-faster

However, you make a good point that it's more of a bug, given lack of response, which breaks our internal guidelines. Reclassifying this as a bug that we plan to fix.

**Comment by it33** [comment]
We ended up removing this from v0.6.0 as it added a bunch of corner cases and risk that needed more investment before we could release, queued for v0.7.0

**Comment by coreyhulen** [comment]
this is now fixed in master. https://github.com/mattermost/platform/pull/380

**Comment by faebser** [comment]
thanks alot
