### ISSUE TITLE
Copy link to attachment, can download without being logged in

### ISSUE THREAD

**Issue by stefuNz** [mattermost/platform#1441]
Hey,

when i copy the link to an attachment, i can open it without being logged in - Bug or on purpose?

**Comment by it33** [comment]
Hi @stefuNz, appreciate the question. 

If you copy the URL from the "Download" link, or right click on the image and copy it, you should not be able to view that link without being logged in. If you copy the link from the "Get Public Link" option, you should be able to view the image without being logged in. 

Are you seeing different behavior?

**Comment by stefuNz** [comment]
No i'm not seeing different behaviour - is it possible to deactivate the public link function though?
This is for internal use and files shouldn't be accessible from outside.

**Comment by stefuNz** [comment]
I'm sorry ... Just found the setting... Sorry for bugging you
