### ISSUE TITLE
Using HTTPS only is not possibly at all

### ISSUE THREAD

**Issue by forelabs** [mattermost/platform#1442]
## Summary

Dear all, we want to use mattermost at our office with https. Because the server only starts a http-service, I added a proxy to enable https. However, after login / sign-up / many other actions there will be a redirect to the http platform, not the https one. Because we do not allow this, page would not be loaded.

## Steps to reproduce

Install mattermost on ubuntu server, set up https proxy (apache2), **disable** http access

## Expected behavior

mattermost should work with https only

## Observed behavior

Adress not reachable (http redirect fails - should be https)

![image](https://cloud.githubusercontent.com/assets/3809644/11183502/4bd2bd7a-8c72-11e5-9c56-a84a2fdeafe7.png)

## Possible fixes

1. Add an option in the config to enable https service instead of http service
2. Do not change protocol on redirect

**Comment by forelabs** [comment]
It also calls **wss://proxy-pass.host.com/api....** which fails, because *proxy-pass.host.com* is only accessible via https

**Comment by coreyhulen** [comment]
You need to set the forwarded proto header.  In nginx you would add `proxy_set_header X-Forwarded-Proto $scheme;` into the configuration file.  I think in apache it's `RequestHeader set X-Forwarded-Proto "https"`.

https://mattermost.atlassian.net/browse/PLT-635 contains a sample of an apache config that's known to work.

I would also look at https://forum.mattermost.org/t/how-to-setup-a-simple-apache2-proxy-to-mattermost/495

**Comment by forelabs** [comment]
Thank you very much! There was this link in the forum posted, which has a working solution in the last comment: https://github.com/mattermost/platform/issues/872
