### ISSUE TITLE
The UI no longer shows if a user is online

### ISSUE THREAD

**Issue by sandywater** [mattermost/platform#1447]
Is that feature gone for good now?  It was really nice to have.

**Comment by sandywater** [comment]
I just noticed that if I sent a DM to someone then I can see their online status.  It might be nice to have it in the **More** modal window too?

**Comment by it33** [comment]
Hi @sandywater, 

Highly appreciate your interest improving Mattermost, and for your help reporting issues, 

There's [an existing ticket for adding online indicators to the More menu](https://mattermost.atlassian.net/browse/PLT-715). 

Closing this issue for now as duplicate. 

You can [read more about the process for filing issues on Mattermost here](http://www.mattermost.org/filing-issues/).
