### ISSUE TITLE
Feature idea: Add search to channels

### ISSUE THREAD

**Issue by fungos** [mattermost/platform#1477]
In the "Direct Messages" window we can do a search for members, but in the "More Channels" we can't.

Good:
![image](https://cloud.githubusercontent.com/assets/151544/11290944/11a30eb8-8f09-11e5-837d-b41f28981345.png)

Bad:
![image](https://cloud.githubusercontent.com/assets/151544/11290975/7a46548e-8f09-11e5-92ad-d8362dcaa6b9.png)

**Comment by it33** [comment]
Thanks @fungos, appreciate your feedback, 

Agree adding the ability to search for channels would be helpful, 

Could we have your help [contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be upvoted by the community and prioritized?
