### ISSUE TITLE
Make clean fails if some directory does not exist

### ISSUE THREAD

**Issue by vladikoff** [mattermost/platform#1483]
I wanted to clean my project but due to install issues I cannot fully clean the project

```
➜  platform git:(fxa) make clean
rm -Rf dist
make: /bin/godep: No such file or directory
make: *** [clean] Error 1
```
![](http://v14d.com/i/564f944f4d5ea.jpg)

**Comment by crspeller** [comment]
@vladikoff This should be fixed with the recent build system changes. Let me know if it's not!
