### ISSUE TITLE
Can't login after changing a setting

### ISSUE THREAD

**Issue by madchap** [mattermost/platform#1493]
Hi,

I deployed the latest docker container, and didn't want anyone coming to the link to have a "sign-up link".

I happened to untick some settings related to that. I logged out to try it out, and I do not have the possibility to login anymore. 
The username and password fields are simply not shown anymore on the login page of my team.

Thanks,
fred

**Comment by it33** [comment]
Hi @madchap,

Please consider comparing your `config.json` file with [the defaults](https://github.com/mattermost/platform/blob/master/config/config.json) and see if you can remember what you changed using the [configuration documentation](https://github.com/mattermost/platform/blob/master/doc/install/Configuration-Settings.md)?

If you accidentally removed yourself from the Sys Admin role, [please see this](https://github.com/mattermost/platform/blob/master/doc/install/Troubleshooting.md#lost-system-administrator-account). 

Also, this topic seems less like a regression or obvious error in the Mattermost system and more like an issue for the [Trouble Shooting Forum](https://forum.mattermost.org/t/about-the-trouble-shooting-category/150). 

Can we ask your help moving this issue there if it's not solved? 

Please see our [community systems documentation](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#community-systems) for an overview of how Mattermost uses GitHub Issues in coordination with other systems.

**Comment by madchap** [comment]
Hi,

Thanks for the quick response. So the culprit is this:

"EnableSignUpWithEmail": false

Changing it back to true made the login boxes re-appear again.

Is that the behavior one should expect? Nobody allowed to login if false? As an admin, I would expect existing users to still be able to login while not allowing anyone to sign up.

Thanks,
fred

**Comment by madchap** [comment]
So, I don't think that's troubleshooting, nor that this issue should be closed.

**Comment by it33** [comment]
This is the configuration documentation shared previously. Now that we know the specific setting, you can go [directly to the description](https://github.com/mattermost/platform/blob/master/doc/install/Configuration-Settings.md#signup).

Agree the naming of the setting is not clear, added as an item to upcoming refactoring work on the auth system: https://mattermost.atlassian.net/browse/PLT-1081
