### ISSUE TITLE
Feature idea: Away status

### ISSUE THREAD

**Issue by andro44** [mattermost/platform#1497]
It would be awesome if you could see if a contact is AFK. My coworker has his browser window open 24/7 and I have no way of knowing if he is actually reading my posts :smile:

**Comment by bjoernr-de** [comment]
Indeed a good idea :+1:

**Comment by lfbrock** [comment]
Away status will be in v1.5, and there are a few Jira tickets accepting pull requests for a [slash command] (https://mattermost.atlassian.net/browse/PLT-1527) and [UI dropdown option](https://mattermost.atlassian.net/browse/PLT-1341) to manually set yourself away.

**Comment by olivierlambert** [comment]
@lfbrock any (roughly) release date for 1.5?
