### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by p0w1nd** [mattermost/platform#1508]
In README.md, section "Prior to production installation, please review Mattermost system requirements.", the link for _Mattermost system requirements_ is broken.

**Comment by it33** [comment]
Thanks @p0w1nd! 

Sorry, my fault, trusted the link validator in the build system a little too much. 

Anyone from community interested in PR to fix?

**Comment by it33** [comment]
[Fixed, thanks!](https://github.com/mattermost/platform/blob/master/README.md#production-deployment)
