### ISSUE TITLE
mattermost local server storage files missing after apt-get upgrade to GitLab 8.2

### ISSUE THREAD

**Issue by tmuka** [mattermost/platform#1510]
after running `apt-get update && apt-get install gitlab-ce` I noticed avatars seem to be missing, then noticed uploaded pasted chat images were missing too.   

The Mattermost server log shows many lines like this...
```
[2015/11/23 17:14:50 EST] [EROR] readFile: Encountered an error reading from local server storage, open /var/opt/gitlab/mattermost/data/teams/1neo6rum8fy47gjqx3xhg3x74r/channels/33ooyd9t4p8m5ko7157wwgbp5a/users/hehh9t7ncbd7b8z6uyi54fmbqa/yopridm6fbbu8fo9fz8mqt6mah/Image Pasted at 2015-10-20 16-22_thumb.jpg: no such file or directory
[2015/11/23 17:14:50 EST] [EROR] /api/v1/files/get/33ooyd9t4p8m5ko7157wwgbp5a/6igydm7xsjgdjqxctzedt7y36r/3i7hxjqz3pdzpddyqgsra7drfy/Image Pasted at 2015-10-20 16-23_thumb.jpg:getFile code=404 rid=tbf7oyrhztyzfdtdgijnc4m16a uid=hehh9t7ncbd7b8z6uyi54fmbqa ip=10.150.17.17 Could not find file. [details: path=teams/1neo6rum8fy47gjqx3xhg3x74r/channels/33ooyd9t4p8m5ko7157wwgbp5a/users/6igydm7xsjgdjqxctzedt7y36r/3i7hxjqz3pdzpddyqgsra7drfy/Image Pasted at 2015-10-20 16-23_thumb.jpg]
```

It appears that maybe there was previously a typo in some path "mattermost/datateams" instead of "mattermost/data/teams". And some of it got copied to the right place when the upgrade happened, and some didn't?

```
root@git01kwd01:/var/opt/gitlab/mattermost# find `pwd` -name 'channels'
/var/opt/gitlab/mattermost/datateams/1neo6rum8fy47gjqx3xhg3x74r/channels
```

The user avatar files do still appear to exist on the filesystem, but interestingly there are two copies, one from Oct 23, and one from today...  

```
root@git01kwd01:/var/opt/gitlab/mattermost# ll
total 20
drwxr-xr-x  4 mattermost root       4096 Nov 23 16:58 ./
drwxr-xr-x 18 root       root       4096 Nov 23 16:58 ../
-rw-r--r--  1 mattermost root       3489 Nov 23 16:59 config.json
drwxr-xr-x  3 mattermost root       4096 Nov 23 16:58 data/
drwxr-xr--  5 mattermost mattermost 4096 Oct 23 12:06 datateams/
root@git01kwd01:/var/opt/gitlab/mattermost# find `pwd` -name profile.png | xargs ls -l
-rw-r--r-- 1 mattermost mattermost  1722 Nov 23 16:58 /var/opt/gitlab/mattermost/data/teams/1neo6rum8fy47gjqx3xhg3x74r/users/41s6iiy6pty4fb4x4ohenwn9jc/profile.png
-rw-r--r-- 1 mattermost mattermost  1722 Oct 23 15:54 /var/opt/gitlab/mattermost/datateams/1neo6rum8fy47gjqx3xhg3x74r/users/41s6iiy6pty4fb4x4ohenwn9jc/profile.png
-rw-r--r-- 1 mattermost mattermost  1509 Nov 23 16:58 /var/opt/gitlab/mattermost/data/teams/1neo6rum8fy47gjqx3xhg3x74r/users/467y4gowr3ymjxbtwqjca4daiw/profile.png
-rw-r--r-- 1 mattermost mattermost 24393 Oct 23 12:19 /var/opt/gitlab/mattermost/datateams/1neo6rum8fy47gjqx3xhg3x74r/users/467y4gowr3ymjxbtwqjca4daiw/profile.png
```

## To fix my missing uploaded channel images this worked.
`cp -Rfp /var/opt/gitlab/mattermost/datateams/1neo6rum8fy47gjqx3xhg3x74r/channels /var/opt/gitlab/mattermost/data/teams/1neo6rum8fy47gjqx3xhg3x74r/`

## I wasn't able to figure out how to fix the missing avatars
I suspect maybe a db migration or something else broke that user setting somehow. I'm happy to help troubleshoot this if somebody can point me in the right direction!

```
Mattermost 1.2.1
Build Number:4063
Build Date:Mon Nov 16 16:56:43 UTC 2015
Build Hash:49a459d696fc8fee0b508990fca571fb8d2f2654
```

This issue didn't start until the GitLab 8.2 update, I didn't change any configurations.

Hope this info helps somebody else!

*I also posted this in the GitLab Issues, since i'm not sure where bugs relating to the integration or packaging of Mattermost with GitLab might be worked. https://gitlab.com/gitlab-org/gitlab-ce/issues/3639*

**Comment by coreyhulen** [comment]
Looks like the field 
```
 "FileSettings": {
        "DriverName": "local",
        "Directory": "./data/",
```
 from mattermost's `config.json`  was changed mid-usage.

I would backup the data dirs first.  BUT you should be able to copy over 1 dir to the other and delete the old dir.  It looks like you should be able to copy over everything under `datateams` to `data/teams` based on the file timestamps, but I would verify by looking at `Directory` in `config.json`, which is where mattermost is loading images from, both posted images and profile images.

**Comment by tmuka** [comment]
Thanks, @coreyhulen , i really appreciate the help!

both `datateams` and `data/teams` already contained the profile.png, so some process copied those over during the apt-get upgrade/install.

here is an example of files that exist in both locations for one user hash who's avatar is still showing as unset. 
```
root@git01kwd01:/var/opt/gitlab/mattermost# locate 7j57u6pkw3rxfeh3j9jo97d1nh/profile.png | xargs ls -l
-rw-r--r-- 1 mattermost mattermost  1925 Nov 23 16:58 /var/opt/gitlab/mattermost/data/teams/1neo6rum8fy47gjqx3xhg3x74r/users/7j57u6pkw3rxfeh3j9jo97d1nh/profile.png
-rw-r--r-- 1 mattermost mattermost 33320 Oct 23 15:12 /var/opt/gitlab/mattermost/datateams/1neo6rum8fy47gjqx3xhg3x74r/users/7j57u6pkw3rxfeh3j9jo97d1nh/profile.png
```
I suspect that maybe the api that tries to grab the avatars in the frontend resets the user avatar setting the first time it tries to find a missing image with the url 
`https://mattermost.internal.example.org/api/v1/users/7j57u6pkw3rxfeh3j9jo97d1nh/image?time=1446755196539&session_token_index=0`

I've never updated the config.json file directly, i also wonder if in gitlab or mattermost something updated to fix a missing trailingslash in the Directory configuration...
```
root@git01kwd01:/var/opt/gitlab/mattermost# egrep -A3 FileSettings config.json
    "FileSettings": {
        "DriverName": "local",
        "Directory": "/var/opt/gitlab/mattermost/data/",
```

So even though the images appear to exist in the correct data directory now, the api is returning the default username letter image with color backgrounds.  

My users are slowly re-uploading their Avatars, but hopefully this info helps somebody!

**Comment by tmuka** [comment]
edit. OH.  just read the api code to learn that the api dynamically writes a new profile.png file for users when the avatar isn't found. So i missed that the filesize difference was important above for the "duplicate" but not duplicate files...  thanks @coreyhulen  !

**Comment by Slimmons** [comment]
Thanks, this helped me a lot.  Just an FYI if anyone else needs a little more hand holding 

https://forum.mattermost.org/t/gitlab-mattermost-broken-after-update-from-gitlab-8-1-3-to-8-2-2/585

**Comment by tmuka** [comment]
it's always nice to know we're not alone! Glad this thread helped you too, @slimmons
