### ISSUE TITLE
Feature Request: Sync with Slack

### ISSUE THREAD

**Issue by irthos** [mattermost/platform#1516]
This was mentioned in this issue https://github.com/mattermost/platform/issues/786 but don't think the poster set a feature request as suggested so here it is.

It'd be a great benefit to have slack two-way sync'd with mattermost so that slack down-times are irrelevant and we won't have to migrate existing groups to mattermost.

**Comment by it33** [comment]
Hi @irthos, [would you be open to upvoting this feature idea](http://mattermost.uservoice.com/forums/306457-general/suggestions/8589463-connect-mattermost-and-slack-channels-via-slacklin)?

**Comment by staabm** [comment]
for anyone finding this issue via google:

looks like https://github.com/42wim/matterbridge would fix this problem
