### ISSUE TITLE
slack import: members are not added into channels

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#1518]
I imported data from slack to mattermost. It works fine but members were not added into channels.

Here is an example exported from slack: https://github.com/npcode/mattermost-import-from-slack-test/raw/master/slack-export-channel-members-bad.zip

**Comment by esethna** [comment]
Thanks @npcode,

Sorry for the confusion, this is currently unsupported. I've created a [ticket](https://mattermost.atlassian.net/browse/PLT-1344) to add support for adding members to channels based on the slack import file. I've also [updated our documentation](https://github.com/mattermost/platform/pull/1552) to note this limitation.

Thanks for the find.

**Comment by lfbrock** [comment]
Closing issue, it will be tracked in Jira.
