### ISSUE TITLE
Allow multiple tabs with different teams

### ISSUE THREAD

**Issue by gsmet** [mattermost/platform#1519]
Hi,

First, thanks for Mattermost, very useful to us.

One problem we have is that we separated our people in different teams but it's not possible to be connected to multiple teams at once in different tabs of your browser. Once you get connected to another team in another tab, you are disconnected from the first one.

Is it something fixable? IMHO, it should be the expected behavior.

Thanks for your feedback!

**Comment by coreyhulen** [comment]
This is supported in the latest version 1.2.  I think it's also supported in 1.1.  What version are you running?

**Comment by gsmet** [comment]
1.1 at the moment. It's definitely not supported in 1.1.

I will upgrade my GitLab install very soon so if it's supported in 1.2, that's cool!

**Comment by it33** [comment]
Hi @gsmet, just tested on v1.2.1, which is in GitLab 8.2.1, multiple teams in multiple tabs seems to work.

**Comment by it33** [comment]
@gsmet, please let us know if this issue repros on GitLab 8.2.1 (with Mattermost v1.2.1)?

**Comment by gsmet** [comment]
Will do. Upgrade is planned on wednesday!

**Comment by gsmet** [comment]
I confirm this is fixed. Closing.
