### ISSUE TITLE
Accepting Pull Requests: Allow max upload file size to be a configuration setting

### ISSUE THREAD

**Issue by pwnsdx** [mattermost/platform#1523]
Hello,

I wonder why no one created issue about this, it looks like the max upload size is hardcoded to 50mb which is not suitable for everyone. I think MAX_FILE_SIZE should be available from the System Console.

Here is a quick search about the constant : https://github.com/mattermost/platform/search?utf8=%E2%9C%93&q=MAX_FILE_SIZE

Regards,

**Comment by esethna** [comment]
Hi @pwnsdx 

Totally agree, thanks for the suggestion! I've created an APR ticket [here](https://mattermost.atlassian.net/browse/PLT-1316). Let me know if this implementation is what you had in mind.

**Comment by pwnsdx** [comment]
Hello @esethna 

This is exactly what I have in mind, thanks for the APR ticket :)

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in [Jira](https://mattermost.atlassian.net/browse/PLT-1316)

**Comment by toogy** [comment]
Hi :smile: 

What's up with that one?

**Comment by lfbrock** [comment]
@toogy, someone from the community had started working on it but didn't end up submitting it, if someone else would like to work on it the ticket is here https://mattermost.atlassian.net/browse/PLT-1316
