### ISSUE TITLE
Running out of session storage in Firefox reloads page when typing in chat

### ISSUE THREAD

**Issue by antila** [mattermost/platform#1524]
Firefox have a fixed size for session storage that is shared between domains, not sub-domains. If this storage runs out then trying to write to it will throw the error "NS_ERROR_DOM_QUOTA_REACHED". This happens inside a try/catch that tries to solve session storage problems with emptying the storage and reloading. This results in a reload loop.

How to reproduce:
* Open a chat.
* Open about:config and change dom.storage.default_quota to 0.
* Type anything in the chat window.

How we ran into the bug:
The problem is that we run Mattermost at http://mattermost.company.tld, and have http://developerThingsThatFillsTheStorage.company.tld, and both of them share the same session storage in Firefox. Thus Mattermost is dependent on external factors, there might simply just not be any space left in the storage.

I don't know how this information should be presented to the user in a good way. The "solution" is to just tell the user to increase the storage in about:config, but this doesn't feel like nice UX.

Maybe the isLocalStorageSupported function should be updated to try to save a larger object to see if it works? In my case the "1" it trites to save fits, but the channel data doesn't. I haven't looked at how it's used so maybe that wont fix the problem. 

https://github.com/mattermost/platform/blob/178e30ecededae61eb727f30919b30358590e7f5/web/react/stores/browser_store.jsx#L74

**Comment by coreyhulen** [comment]
I think this might be fixed in master with a recent refactor of our Store objects.  @crspeller does your refactor fix this issues?

**Comment by crspeller** [comment]
This should be resolved.
