### ISSUE TITLE
Feedback - list

### ISSUE THREAD

**Issue by ninja-** [mattermost/platform#1545]
Hi, I am leaving this as a note of all the feedback made by me and my team during last week of testing...
I'll try to fix some of them and I want to make sure I don't forget about any of them.

I am coming mostly from Slack but there are also some great hipchat ideas to pick.

Features "missing"

- [x] emoji panel, emoji autocomplete
- [ ] reactions
- [x] the great EmojiOne emoji set, eventually a setting to switch between them
- [ ] better indexing of mentions so it doesn't fulltext search everytime
- [ ] archived channels disappear...they should show even after being deleted aka archived with an option to unarchive them as well
- [ ] option to archive the channel when adding new members
- [ ] timezones, online status
- [ ] offline mode support (no idea how it is on slack?)
- [ ] favourite channels !
- [ ] favourite messages
- [ ] ctrl+k quick jump menu

Tracking bugs:
- [x] recent mentions shows "undefined" in join messages
- [x] oembed broken on master
- [x]  some emoticons broken like : ) works and : ( not
- [x] direct message menu "more" hangs forever after opening message with anyone
- [x] creating private group fails with We couldn't find the existing channel
- [x] opening a direct message with someone via channel members menu will hang on "loading..." (same happens after new created channel is loaded)
- [x] memberlist on a channel sometimes broken
- [x] "load more messages" removes all the messages from the view instead...
- [ ] hosting on subpath still broken

Design:
- popup windows could be a little bit closer to the center...

Low priority ideas:
- steal the awesome message details panel for incoming integration messages to private hipchat-style details on that message if supported
- always visible left panel integrations hipchat-style, for example always keeping statuspage.io with you
![](https://statuspage-blog.s3.amazonaws.com/2015-11-03-leveling-up-our-hipchat-integration/hipchat_refactored.png)
- guest access
- slack message "actions" for integrarions

Marketing:
- the threaded conversations can be a nice "selling point" until slack decides to implement them.

Most of these bugs already have their tickets on bugtracker

**Comment by it33** [comment]
@ninja-, wonderful list, thank you for creating it! 

One request: Could you number the bullet points so it's easier to discuss in this thread?

**Comment by ninja-** [comment]
@it33 <3

I am going to number the points and change them to checkboxes as well :)

**Comment by ninja-** [comment]
Random note: the threaded thingy looks like a really awesome way to integrate customer support! It wouldn't be that nice on slack IMO

**Comment by hwinkel** [comment]
I'm really missing a favorite people view with presence/online status like we have in Skype etc.

**Comment by it33** [comment]
Closing this ticket as there's too many items here to process systematically, would welcome additions to the [feature idea forum](http://www.mattermost.org/feature-requests/) based on this list for discussion and upvoting

**Comment by PAX523** [comment]
There's an "emoji panel" in form of a list in the help system. But I'd like to access this list within the message text field, directly?
