### ISSUE TITLE
Improve development docs

### ISSUE THREAD

**Issue by vladikoff** [mattermost/platform#1549]
The dev machine setup docs are okay, but I cannot find any docs on how to debug or work on the project.

For instance I want to make changes to the Go server and not worry about JS. Currently I do

```
make stop && make run
```
which is ~30-40 seconds for every change I make to the server to debug something.

Thoughts?

**Comment by coreyhulen** [comment]
I think most debug via unit tests.  either via a plugin to run a specific test or with something like `go test -test.run="^TestServer$"`

**Comment by vladikoff** [comment]
What I did so far is, comment out the mattermost.go block in the makefile and run that file on my own, which made development easier:  
![](http://v14d.com/i/565cd04c7fa49.jpg)

**Comment by it33** [comment]
[Ticket created to track this](https://mattermost.atlassian.net/browse/PLT-2050)
