### ISSUE TITLE
Feature idea: Switch from "compass" to "node-sass + libsass"

### ISSUE THREAD

**Issue by vladikoff** [mattermost/platform#1550]
I wanted to file this issue to see if the project owners are interested in switching from "compass" to libsass ( + node-sass) , see https://github.com/sass/node-sass

## Good

* Drop Ruby and Gem dependency 
* Faster builds for CSS
* Integrates into existing node.js scripts

## Bad

* Some features of compass / sass might be missing
* Other? You tell me...

Thoughts?

**Comment by it33** [comment]
Thanks @vladikoff, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?
