### ISSUE TITLE
Feature idea: Support for multilines in cell in markdown tables

### ISSUE THREAD

**Issue by nothing-fr** [mattermost/platform#1557]
Is it possible to support multilines in table cell please ?

```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
| Like this <br> or like that <br> could be nice ! | |
```

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
| Like this <br> or like that <br> could be nice ! ||Really <br> nice <br>yeah !

It does not work right now :/

**Comment by it33** [comment]
Thanks @nothing-fr, appreciate the feedback, 

Could we have your help [contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be upvoted by the community and the item prioritized? 

This is a slippery slope change that opens up a question of how much HTML we support. It's opened up some bugs in GitHub markdown rendering--for example, if you write `http://<your-domain.com>/directory` it renders as http://<your-domain.com>/directory.

Agree it's a useful feature, and perhaps it can be hardcoded to `<br>` and `<pr>`, if someone is interesting in submitting a pull request and has thoughts on the right approach, we can discuss more. 

Text processing is complex already, don't want to add more complexity without thinking through things.

**Comment by lfbrock** [comment]
Closing issue, it can be upvoted here: https://mattermost.uservoice.com/forums/306457-general/suggestions/12286509-support-for-multilines-in-cell-in-markdown-tables
