### ISSUE TITLE
Bug: npm build and npm start

### ISSUE THREAD

**Issue by enahum** [mattermost/platform#1568]
For some reason that i can´t figure out and after I had to manually install babel-runtime which is not included in the package.json, I get an Uncaught TypeError: (0 , _typeof3.default) is not a function javascript error when running mattermost.

**Comment by enahum** [comment]
@it33 have u been able to figure this out?

**Comment by it33** [comment]
@enahum, please add repro steps: http://www.mattermost.org/filing-issues/

**Comment by coreyhulen** [comment]
I would try un-installing npm and re-installing.  Also some stuff like `babel-polyfill-6.1.18.min.js` is included directly in head.html

**Comment by enahum** [comment]
@coreyhulen thx for the suggestion I just installed node 4.23 with npm 2.14.7 from scratch, but when i run make build-client in the master branch I get the following error:

```
Error: Cannot find module 'babel-runtime/core-js/get-iterator' from '/Users/enahum/Projects/go/src/github.com/mattermost/platform/web/react/utils'
    at /Users/enahum/Projects/go/src/github.com/mattermost/platform/web/react/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/enahum/Projects/go/src/github.com/mattermost/platform/web/react/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/enahum/Projects/go/src/github.com/mattermost/platform/web/react/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/enahum/Projects/go/src/github.com/mattermost/platform/web/react/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/enahum/Projects/go/src/github.com/mattermost/platform/web/react/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/enahum/Projects/go/src/github.com/mattermost/platform/web/react/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
The code that you piped into exorcist contains no source map!
Therefore it was piped through as is and no external map file generated.
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '../static/js/inter.js.map'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/Users/enahum/Projects/go/src/github.com/mattermost/platform/web/react/node_modules/uglify-js/bin/uglifyjs:270:30)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/enahum/.nvm/versions/node/v4.2.3/bin/node" "/Users/enahum/.nvm/versions/node/v4.2.3/bin/npm" "run" "build"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! mattermost@0.0.1 build: `browserify -x crypto -x autolinker -x flux -x keymirror -x marked -x object-assign -x twemoji -d ./**/*.jsx | exorcist ../static/js/inter.js.map > ../static/js/tmp.js && uglifyjs ../static/js/tmp.js --in-source-map "../static/js/inter.js.map" --source-map "../static/js/bundle.min.js.map" --source-map-url "/static/js/bundle.min.js.map" -c -m --screw-ie8 > ../static/js/bundle.min.js && rm ../static/js/tmp.js && rm ../static/js/inter.js.map`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mattermost@0.0.1 build script 'browserify -x crypto -x autolinker -x flux -x keymirror -x marked -x object-assign -x twemoji -d ./**/*.jsx | exorcist ../static/js/inter.js.map > ../static/js/tmp.js && uglifyjs ../static/js/tmp.js --in-source-map "../static/js/inter.js.map" --source-map "../static/js/bundle.min.js.map" --source-map-url "/static/js/bundle.min.js.map" -c -m --screw-ie8 > ../static/js/bundle.min.js && rm ../static/js/tmp.js && rm ../static/js/inter.js.map'.
npm ERR! This is most likely a problem with the mattermost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -x crypto -x autolinker -x flux -x keymirror -x marked -x object-assign -x twemoji -d ./**/*.jsx | exorcist ../static/js/inter.js.map > ../static/js/tmp.js && uglifyjs ../static/js/tmp.js --in-source-map "../static/js/inter.js.map" --source-map "../static/js/bundle.min.js.map" --source-map-url "/static/js/bundle.min.js.map" -c -m --screw-ie8 > ../static/js/bundle.min.js && rm ../static/js/tmp.js && rm ../static/js/inter.js.map
npm ERR! You can get their info via:
npm ERR!     npm owner ls mattermost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/enahum/Projects/go/src/github.com/mattermost/platform/web/react/npm-debug.log
make: *** [build-client] Error 1
````

**Comment by enahum** [comment]
It seems to me that there are a few dependencies that aren't met, but as I said, so far I haven´t been able to identify them. any other suggestion to fix this?

**Comment by coreyhulen** [comment]
hmm...weird.  Are you on a mac?

did you add `ulimit -n 8096` to your `~/.bash_profile` ?

**Comment by enahum** [comment]
I did tried that, but as you can see the error says something about not being able to find module babel-runtime/core-js/get-iterator, if I go ahead and install babel-runtime npm it builds but then when I run it i get a runtime javascript error saying `Uncaught TypeError: (0 , _typeof3.default) is not a function` 
![screen shot 2015-12-09 at 11 51 02](https://cloud.githubusercontent.com/assets/6757047/11688421/506da222-9e6b-11e5-8baf-e36e3d7287db.png)

**Comment by coreyhulen** [comment]
Can you try a `make nuke` followed by a `make test`  ?

The travis build machine uses a clean install every time.  You can look at https://github.com/mattermost/builder/blob/master/Dockerfile to maybe find any differences.

**Comment by enahum** [comment]
make nuke and make test work as it should, everything passes.

after that I ran make build-client and IT WORKS!!!!

Thanks for your help, now I´ll try to build it again against our i18n branch

**Comment by enahum** [comment]
It seems to be babel related

![screen shot 2015-12-09 at 15 18 54](https://cloud.githubusercontent.com/assets/6757047/11694329/3d216cc2-9e88-11e5-9a5b-c55a80c0cac1.png)

**Comment by enahum** [comment]
Ok dude its official, the problem is running babel on mac, running it from ubuntu works without issues

**Comment by coreyhulen** [comment]
hmm...weird.  Most of the core team develops from mac and I don't think anyone has encountered that error.

**Comment by enahum** [comment]
Well then it beats me. Right now im building the bundle.js from within a VM with Ubuntu and it builds fine, in El Capitan it doesn't build as it should.

Thanks for you help

**Comment by coreyhulen** [comment]
here is what I have for my mac  

```
OSX Yosemite Version 10.10.5

$ node -v
v5.1.0
$ npm -version
3.3.12
$go version
1.5.1 darwin/amd64
```

**Comment by enahum** [comment]
@coreyhulen Great bro, with node v5.2.0 and npm 3.3.12 works perfectly.

Im gonna close this.

Much appreciated

**Comment by Ticki** [comment]
Can we reopen this? I'm running Ubuntu on our Mattermost server, and I get this exact error when I run `make build-client`.

**Comment by it33** [comment]
Hi @Ticki, could we have your help opening a new issue with repro steps for your configuration (e.g. Ubuntu version, any variations from instructions, etc)? 

You're welcome to reference this thread. 

You're welcome to reference this thread.
