### ISSUE TITLE
port conflicts of `make test`

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#1570]
`make test` seems to use 3306 and 8065 ports. But it is very common that the ports are already used because they are default ports of mysql and mattermost.

Why don't you use other uncommon ports for the test?

**Comment by coreyhulen** [comment]
the default config.json has `dockerhost:3306` so most map dockerhost to the vm.  As for mattermost, yea you need to `make stop` before you should run `make test`

**Comment by npcode** [comment]
Ah, the test uses `config/config.json` as its environment. I didn't know that. Changing ports in the config file helps to fix my problem.

**Comment by npcode** [comment]
Changing ports in config.json did not help me because the ports are [hardcoded in Makefile](https://github.com/mattermost/platform/blob/master/Makefile#L44) as follows:

`docker run --name mattermost-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mostest`
