### ISSUE TITLE
Bug: Regression - No members displayed by default under Direct Messages

### ISSUE THREAD

**Issue by gsmet** [mattermost/platform#1574]
Hi,

We have several small teams at my company and the behavior of Direct messages has changed in 1.2.1: members are not displayed anymore except if you explicitely use More to message them.

Would it be possible to bring back the old behavior with the list displayed by default? It was really more practical and user friendly!

Thanks!

-- 
Guillaume

**Comment by it33** [comment]
Hi @gsmet, there's [a ticket filed on this scheduled to be fixed in v1.3](https://mattermost.atlassian.net/browse/PLT-1319).

**Comment by esethna** [comment]
Hi @gsmet 

Thanks for the report. The [ticket](https://mattermost.atlassian.net/browse/PLT-1319) is now submitted and on master. The fix didn't make it for the V1.3 code complete date, but it will be available in V1.4.
