### ISSUE TITLE
Bug: System Console > Teams has unnecessary extra space around "Close" button for teams

### ISSUE THREAD

**Issue by gsmet** [mattermost/platform#1583]
Hi,

It's just a little detail but, in the system console, there is a lot of space lost in the Teams part (with Firefox at least):
![system-console-team-management](https://cloud.githubusercontent.com/assets/1279749/11538380/1dbf8a0a-9922-11e5-9d29-d654292593a8.png)

-- 
Guillaume

**Comment by it33** [comment]
Hi @gsmet, thanks for the bug report, agree this should be fixed. @esethna please queue in UX Design?

**Comment by it33** [comment]
Fixed in v1.4, sorry about not getting back to this earlier, 

![image](https://cloud.githubusercontent.com/assets/177788/13199824/2ec4df42-d7e5-11e5-8b25-9cb7594db1b4.png)
