### ISSUE TITLE
sticky messages

### ISSUE THREAD

**Issue by ftKnox** [mattermost/platform#1586]
Is there a way to have a message or messages be displayed when someone joins a channel, ala irc style? Possibly by marking a post "sticky" if you are a team/site admin? Then maybe being able to select its stickyness, like "stuck", "sticky", "gooey" whatever. Then those terms are lengths of times the message is stuck to the top of the channel feed.

Example use cases:
We use a public channel where we post mattermost native client download files, but I imagine it could be used for other purposes, like say there is a server problem and you need to notify everyone in a channel/private group and don't want to make people potentially scroll back through history to see if someone already posted about the issue

**Comment by ninja-** [comment]
Yes, slack-style pinned posts are on the roadmap along with favourite messages/channels. Pull requests welcome

**Comment by ftKnox** [comment]
10-4

**Comment by ninja-** [comment]
Hm?

**Comment by ftKnox** [comment]
"10-4

interjection

"message understood." Used in radio transmissions, e.g. CB radio, police radio."

**Comment by ninja-** [comment]
:D
