### ISSUE TITLE
Feature idea: iOS/Mobile usability suggestion

### ISSUE THREAD

**Issue by ebalsumgo** [mattermost/platform#1607]
Currently both the iOS app and the Mobile view of mattermost (my local install is the last travis-ci build from a week or so ago) when you bring up the input box you are presented with a Send icon, on top of a Done button along with a Return on the actual keyboard. This from a user perspective is super confusing and unintuitive. I would suggest either completely removing the Send icon, or removing the Done text and that whole extra bar that ends up being drawn just to have it there. Also if at all possible changing return to the normal iOS blue button Send (for at least the app) would make it a lot clearer as to what is going on. If you leave the return and only have the send Icon (no Done button), then make return actually act as a new line rather than send, right now as far as I can tell there is no way for me to add a new line inside something I want to send.

**Comment by ebalsumgo** [comment]
cc @coreyhulen

**Comment by it33** [comment]
Thanks @ebalsumgo, appreciate the feedback, 

Could we have your help [contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be upvoted by the community and the item prioritized?

This seems to require a custom keyboard and could create inconsistency across iOS and mobile web experiences, so it'll probably take some work.

**Comment by ebalsumgo** [comment]
sure i will move it there. i am not sure how you are doing the iOS implementation but I am not sure on the custom keyboard bit. examples apps would be: hangouts, facebook messenger, snapchat. They all have the feature I am talking about (thats the inspiration for the post to begin with)
