### ISSUE TITLE
Feature Request: Ability to delete a team

### ISSUE THREAD

**Issue by gsmet** [mattermost/platform#1618]
Hi!

It would be nice if we could have the ability to delete a team in the system console (with a confirmation).

It's useful when you have made a typo in the name of the team (or if you have chosen a name too short and the URL is an hash)

-- 
Guillaume

**Comment by ninja-** [comment]
I think you can do that with the command line via ./mattermost --delete-time-permanently, something near that

**Comment by it33** [comment]
Hi @gsmet, 

In Mattermost v1.3 you can delete a team using [Mattermost command line tools](https://github.com/mattermost/platform/blob/master/doc/install/Command-Line-Tools.md), which give warnings on the action. 

Does this cover your issue?

**Comment by gsmet** [comment]
Yes it does!

Thanks!
