### ISSUE TITLE
Bug: Team name too short causes the team URL to use an hash

### ISSUE THREAD

**Issue by gsmet** [mattermost/platform#1619]
Hi,

I read something about it and I thought it was fixed in 1.2.1 but it is not. When I create a team with a name of 3 characters or 4 characters, the URL is an hash.

I don't understand why there is a such an arbitrary limit?

Use case: each team in our company has an acronym of 3 or 4 letters.

-- 
Guillaume

**Comment by esethna** [comment]
Hi @gsmet,

The current behavior on master throws an error during the team creation if the team name or url are 3 characters or less. 4 character names and urls are supported. See image:
![image](https://cloud.githubusercontent.com/assets/14333569/11604453/70fc6f5a-9aa1-11e5-93d4-46408e5e7b69.png)

I think lowering the limit to three characters makes sense, I've filed a ticket [here](https://mattermost.atlassian.net/browse/PLT-1398)

**Comment by lfbrock** [comment]
Closing issue, it will be tracked in Jira.
