### ISSUE TITLE
Feature Request: Hide message contents in notification popups

### ISSUE THREAD

**Issue by sergekh42** [mattermost/platform#1632]
Not really important, but it would be nice if there was an option to hide the contents of a message when a notification popup occurs. Just show the channel and that there is a new message. To be able to keep it private if there is someone over your shoulder looking at your screen.

**Comment by ninja-** [comment]
also the part when it cuts the notification content with "..." ... drives me crazy

**Comment by it33** [comment]
Thanks @sergekh42, appreciate the feedback, 

Could we have your help [contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be upvoted by the community and the item prioritized?

**Comment by sergekh42** [comment]
@it33 no problem. I just posted it there, sorry I didn't know about that forum.

**Comment by it33** [comment]
Thanks @sergekh42! No worries, we want to hear from the community wherever they want to share thoughts.
