### ISSUE TITLE
Better 4k image handling

### ISSUE THREAD

**Issue by ambrosechua** [mattermost/platform#1634]
Images above 4k resolution do not get uploaded, despite being smaller than `MAX_FILE_SIZE`. This should be dealt with by skipping thumbnail generation, instead of [rejecting](/mattermost/platform/blob/master/api/file.go#L139) the file completely (similar to what Slack does), confusing users on why images are not being uploaded.

**Comment by it33** [comment]
Asking @esethna's help on this

**Comment by esethna** [comment]
Thanks @ambrosechua,

Agree this is a bug. I've filed a bug ticket [here](https://mattermost.atlassian.net/browse/PLT-1431) to allow images > MaxImageSize to upload as generic attachments without thumbnails.

I've filed a different improvement [ticket](https://mattermost.atlassian.net/browse/PLT-1432) to investigate increasing MaxImageSize so we can preview images of higher resolutions.

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in Jira
