### ISSUE TITLE
Bug: Team management modal: dropdown not visible if team too small

### ISSUE THREAD

**Issue by gsmet** [mattermost/platform#1638]
Hi,

In 1.2.1, when the team is small, the dropdown is not totally visible in the team management modal.

![screenshot from 2015-12-07 17 22 05](https://cloud.githubusercontent.com/assets/1279749/11632440/721e88ba-9d07-11e5-8e8a-ddfda4aea21b.png)

I think there should be a margin after the last member or maybe change the z-index of dropdowns compared to modal footer.

-- 
Guillaume

**Comment by esethna** [comment]
Thanks @gsmet

[Ticket](https://mattermost.atlassian.net/browse/PLT-1406) for this is filed and will be triaged today.
