### ISSUE TITLE
Feature Idea: Sending payload in application/json for outgoing webhooks

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#1649]
Ougoing webhooks seems to send payload in only application/x-www-form-urlencoded. If it supports also application/json, it may be possible to integrate with slack which requires incoming hooks to have application/json payload.

**Comment by it33** [comment]
Hi @npcode, 

To maintain compatibility with Slack there would probably need to be a UI switch in outgoing webhooks for different formats. 

This potentially adds complexity because everyone creating a webhook will need to make the decision as to which format to enable, and they'll have to understand the different options. 

Can you share more about the potential use cases for this?

**Comment by npcode** [comment]
My use case is to make a Slack channel to show what Mattermost users are talking about for Slack users who don't use Mattermost.

I thought the outgoing webhook of Slack sends data in json but it was not true. The incoming webhook accepts payload only in json but the outgoing webhook sends payload only in application/x-www-form-urlencoded. I don't know why Slack makes their webhooks incompatible each other...

> This potentially adds complexity because everyone creating a webhook will need to make the decision as to which format to enable, and they'll have to understand the different options.

I think they don't have to understand all of the options. Instead they have to implment Content-Negotiation: accepting the only supported payload and rejecting (with 415 Unsupported Media Type) the others.

**Comment by jwilander** [comment]
Hi @npcode, sorry for the incredibly delayed response. I'm not sure I understand how Content-Negotiation would work with outgoing webhooks to help with the format sent. Running through a use case, the server encounters a trigger word in a message and sends out an HTTP POST to the URL that was registered with the webhook. For the Content-Negotiation, do you mean that Mattermost should include an Accept header letting the third-party server know which formats we accept in the response body? I'm not sure how this affects your original issue of the format the outgoing webhook is in. I'm pretty sure that the user would still have to select the type when they are creating the webhook.

I do think, however, that this is something worth supporting and would be a great Accepting Pull Requests ticket.

Also incoming webhooks will accept two types of Content-Types:

`application/x-www-form-urlencoded` with a payload `payload={'text': 'some text'}` OR
`application/json` with a payload `{'text': 'some text'}`

We do this to be compatible with Slack, though I do concede that their design decision to not properly accept multiple types is a little weird.

**Comment by npcode** [comment]
> For the Content-Negotiation, do you mean that Mattermost should include an Accept header letting the third-party server know which formats we accept in the response body?

Well, I think it was my mistake. I misunderstood "everyone creating a webhook" as "everyone receiving a webhook".  What I want to say was that people who receive outgoing webhooks don't have to understand all of the options because they can just reject an outgoing webhook if the Content-Type is not acceptable.

**Comment by jwilander** [comment]
Yes, that makes sense. Would you be able to submit a feature request following the steps [here](https://www.mattermost.org/feature-requests/) and post a link back here when you've done that? We can possibly open this up as an APR (accepting-pull-requests) ticket if you or anyone is interested in making the change. Thanks!

**Comment by npcode** [comment]
I have interest in implementing  it but unfortunately I don't have enough time now. I will try it if no one take this issue a month later.

**Comment by lfbrock** [comment]
[Accepting pull requests ticket](https://mattermost.atlassian.net/browse/PLT-2170) created, closing this issue + will track it in Jira.

**Comment by tbalthazar** [comment]
@npcode Hi, I just wanted to let you know that I started working on this issue.
