### ISSUE TITLE
Looks like the SSL configuration example is cut off

### ISSUE THREAD

**Issue by ctron** [mattermost/platform#1682]
Looking at the SSL configuration snippet for nginx at [1], it looks as it got cut off in the middle.

[1] https://github.com/mattermost/platform/blob/master/doc/install/Production-Ubuntu.md

**Comment by hjf288** [comment]
The original example states that you should add the rest of the location block from the non-SSL example however I think this is confusing.

I have made a PR to correct this: https://github.com/mattermost/platform/pull/1788
