### ISSUE TITLE
make failure

### ISSUE THREAD

**Issue by jaijiv** [mattermost/platform#169]
I did a 
go get github.com/mattermost/platform

Doing a make -f Makefile gives me this error. Am i missing something ?

building for travis
rm -Rf dist
# github.com/mattermost/platform/api
api/server.go:29: undefined: manners.NewServer
api/server.go:42: too many arguments in call to Srv.Server.ListenAndServe
api/server.go:55: Srv.Server.Shutdown undefined (type *manners.GracefulServer has no field or method Shutdown)
api/team.go:221: undefined: "github.com/awslabs/aws-sdk-go/aws".Creds
api/team.go:222: cannot use "github.com/awslabs/aws-sdk-go/aws".DefaultConfig.Merge(&"github.com/awslabs/aws-sdk-go/aws".Config literal) (type *"github.com/awslabs/aws-sdk-go/aws".Config) as type *"github.com/aws/aws-sdk-go/aws".Config in argument to route53.New
api/team.go:251: undefined: "github.com/awslabs/aws-sdk-go/aws".Creds
api/team.go:252: cannot use "github.com/awslabs/aws-sdk-go/aws".DefaultConfig.Merge(&"github.com/awslabs/aws-sdk-go/aws".Config literal) (type *"github.com/awslabs/aws-sdk-go/aws".Config) as type *"github.com/aws/aws-sdk-go/aws".Config in argument to route53.New
make: *** [travis] Error 2

Regards

-jaijiv

**Comment by jwilander** [comment]
Hi @jaijiv 

You should be able to run the following commands to get the app running:

1. make install
2. make test (to make sure everything set up correctly)
3. make run

**Comment by coreyhulen** [comment]
Also take a look at https://github.com/mattermost/platform/blob/master/scripts/README_DEV.md

**Comment by jaijiv** [comment]
Worked now. Thanks for the help.

Regards

-jaijiv
