### ISSUE TITLE
Feature request: Move a message to another channel

### ISSUE THREAD

**Issue by tjosinga** [mattermost/platform#1691]
Sometimes a user posts his message in the wrong channel. Deleting the message and repost is a simple solution. However, sometimes the message already contains replies. Is it possible (to make) to move a message including its replies to another channel?

**Comment by esethna** [comment]
Thanks again for the feature idea @tjosinga. Can we ask that you please move it to the [Feature Idea Forum](http://www.mattermost.org/feature-requests/) to discuss with community and have others up vote? Typically we use [GitHub issues to report bugs](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#github-issues), and all feature ideas are [routed via the feature idea forum](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#feature-idea-forum).

**Comment by tjosinga** [comment]
Thanks. I have done so. I had searched for a feature request place, but strangely I hadn't found it. The info behind your link was quite clear.
