### ISSUE TITLE
Feature request: Channel modes

### ISSUE THREAD

**Issue by tjosinga** [mattermost/platform#1692]
We tend to use the channels in two different ways. Some channels are for chat; a stream of short messages. Other channels have more in-depth messages (like explanations, articles, meeting notes, etc.). In those latter channels, to communication is less a single stream, and focuses more on replies.

Currently Mattermost focuses on chat streams (chat mode), having replies as an option (literally on the side).

I want to suggest an extra mode: topic mode. It differs from the chat mode in the sense that:
- The main might only show the topics (first level messages), not the replies.
- The reply sidebar should be more wider, making it possible to focus better on the replies.
- The input fields for messages might be larger by default, since it will be used for larger texts.

**Comment by esethna** [comment]
Hi @tjosinga,

Appreciate the feature idea. Would mind routing it via the [Feature Idea Forum](http://www.mattermost.org/feature-requests/) so it can be discussed and up voted by the community?

**Comment by tjosinga** [comment]
Posted it there too.
