### ISSUE TITLE
How to upload a file using the API ?

### ISSUE THREAD

**Issue by stephane-martin** [mattermost/platform#1693]
Hello,

with the UI i can upload files as attachments of a message. I don't think it is possible to attach a file to an Incoming Message. Would it be possible to do it using the go client API ? Could you provide a simple example about how to do it ?

Thanks !

**Comment by coreyhulen** [comment]
You can see a javascript example at https://github.com/mattermost/platform/blob/master/web/react/utils/client.jsx#L1025

Also a golang example at https://github.com/mattermost/platform/blob/master/api/file_test.go#L70
