### ISSUE TITLE
Feature idea : lock chanels to use them as documentation / explanation topics

### ISSUE THREAD

**Issue by Zekdar** [mattermost/platform#1705]
**This post continues an ideas given by in issue #1692**

Thanks to Markdown, it is currently possible use Mattermost as a documentation / explanation repository. But the chat mode induces a vertical scrolling which is convenient to see the post at first sight.

In order to achieve that goal, would it be possible to lock chanels so that only the owner could add content to it ?

Another point would be to validate an answer as it is made on StackOverflow. That way, if the chanel is used to ask a question, it would be possible to see the right answer at first sight.

**Comment by esethna** [comment]
Hi @Zekdar 

Thanks again for the feature idea. I've asked the original poster of [#1692](https://github.com/mattermost/platform/issues/1692) to move the idea to the [feature idea forum](http://www.mattermost.org/feature-requests/) so please feel free to discuss it there. Thanks!

**Comment by lfbrock** [comment]
Closing issue, feature idea can be upvoted here: https://mattermost.uservoice.com/forums/306457-general/suggestions/11594328-allow-a-channel-to-be-locked
