### ISSUE TITLE
Feature idea : add a popup to display all available Emojis

### ISSUE THREAD

**Issue by Zekdar** [mattermost/platform#1706]
It would be nice if there was a popup referencing all emojis available as it is done on Slack :

![image](https://cloud.githubusercontent.com/assets/6300132/11746262/81e7a07e-a01d-11e5-91c1-bf635d95b367.png)

**Comment by esethna** [comment]
Hi @Zekdar,

Appreciate the feature idea! We have a [suggestion for this](https://mattermost.uservoice.com/forums/306457-general/suggestions/10335798-emoji-picker) on our feature idea forum. 

We typically ask that feature ideas be routed through the [Feature Idea Forum](http://www.mattermost.org/feature-requests/) so they can be discussed and upvoted by the community.

**Comment by lfbrock** [comment]
Closing issue, it can be upvoted here: https://mattermost.uservoice.com/forums/306457-general/suggestions/10335798-emoji-picker
