### ISSUE TITLE
API should allow CORS

### ISSUE THREAD

**Issue by nils-werner** [mattermost/platform#1721]
Currently I cannot push messages using JS from a different server because you're not setting `Access-Control-Allow-Origin` headers in the API.

**Comment by pedromorgan** [comment]
Maybe an option to allow CORS.

**Comment by hjf288** [comment]
If you are reverse proxying using nginx, you can add the CORS header using the `add_header` directive

**Comment by coreyhulen** [comment]
We're tracking this feature in Jira as https://mattermost.atlassian.net/browse/PLT-2112

**Comment by hsali** [comment]
This doesn't work. I am try to use it through javascript. CORS error happen.

**Comment by jasonblais** [comment]
@hsali what are your **System Console > Connections** settings set to?

Here's a link to the related documentation: https://docs.mattermost.com/administration/config-settings.html#connections

Please feel free to obfuscate the values so not to share confidential information, or you may also contact me on our demo instance at https://pre-release.mattermost.com/core (my username is `@jason`)
