### ISSUE TITLE
Web app icon not working

### ISSUE THREAD

**Issue by andrefreitas** [mattermost/platform#1722]
Hi,
When we add the page to the homescreen, Android doesn't load the Mattermost icon. I believe the manifest.json isn't right.

**Comment by esethna** [comment]
Hi @andrefreitas,

Thanks for the bug report. Manifest.json has an icon defined, but the size may be incorrect for your Android device. Can you let me know what device you're using so i can file a ticket? Can you also describe what icon does appear? Thanks!

**Comment by andrefreitas** [comment]
Hi,
My device is a Galaxy S4. The shortcut has no icon.

**Comment by dalenoe** [comment]
I just double checked as I have a S4. The shortcut includes no icon, and has a letter (if the shortcut name is Mattermost).. it shows a "M".

**Comment by esethna** [comment]
Thanks for the repro @andrefreitas and @dalenoe. I've filed a bug ticket [here](https://mattermost.atlassian.net/browse/PLT-1546)
