### ISSUE TITLE
what can I do with google js and css?

### ISSUE THREAD

**Issue by xuxiangyang** [mattermost/platform#173]
I am a Chinese, I can access google. so I need download those statics files on my server. I use your platform with docker, I do not know how to change your source file? I need rebuild docker image ??? 

I think you can add those static files.....

I need some help, thank you

**Comment by jwilander** [comment]
Hi @xuxiangyang ,

The static files for jquery and react-with-addons have been added to the master branch where you should be able to access them. Are there other static files that you don't have access too?

**Comment by xuxiangyang** [comment]
I use the image mattermost/platform:helium.

I need update that image?

**Comment by jwilander** [comment]
We don't currently have a major release docker image that contains the static files (that will becoming in a 2-3 weeks) but you can work off mattermost/platform:latest until then. It should have all the static files you need

**Comment by xuxiangyang** [comment]
rebuilding an image dose not work?

**Comment by xuxiangyang** [comment]
I rebuild on my server, but I can not access google because of GFW.....

**Comment by jwilander** [comment]
Try these steps:

1. docker stop mattermost-dev 
2. docker rm mattermost-dev 
3. docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform:latest 

That should get you running the latest which will have the static files for you.

**Comment by xuxiangyang** [comment]
thank you,
by the way, why you do not use docker-compose?

**Comment by jwilander** [comment]
We're currently just focused on building out the system itself but using stuff like docker-compose will probably come in the future as we have more time to spend on it
