### ISSUE TITLE
Feature idea: Comment on the posted IMG on specific elements. (For Design Teams like InVision) 

### ISSUE THREAD

**Issue by peach93** [mattermost/platform#1731]
My Feature Idea:
Open a Preview of the posted IMG and on specific elements. (For Design Teams like InVision) 
Example: Comment on the button on the left side because it looks too small.

Is there any idea how to integrate that feature or an existing feature that I don't recognized?
Thanks!

**Comment by esethna** [comment]
Hi @peach93,

Appreciate the feature idea! There are no existing features like the one you describe, but I can certainly see the appeal for design teams. Would mind routing your idea via the [Feature Idea Forum](http://www.mattermost.org/feature-requests/) so it can be discussed and up voted by the community?

**Comment by peach93** [comment]
thanks @esethna ! 
posted it here:
http://mattermost.uservoice.com/forums/306457-general/suggestions/11106189-comment-on-the-posted-img-on-specific-elements
...and hope to get a lot of votes :)

**Comment by lfbrock** [comment]
Closing issue, it can be upvoted here: http://mattermost.uservoice.com/forums/306457-general/suggestions/11106189-comment-on-the-posted-img-on-specific-elements
