### ISSUE TITLE
Feature idea: email log

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#1738]
It would be helpful if mattermost logs every time it sends an email.

It is very difficult to find out why emails are not sent because there are a lot of failure points while sending emails. (misconfiguration, firewall, spam filter, bug, ...)

**Comment by esethna** [comment]
Hi @npcode, appreciate the feature idea. Are you thinking of a log in account settings (user basis) or team settings (team basis) or system console (system basis)? We might have to be careful about what information is included in the logs or it may open up privacy issues if it were implemented in team settings or system console.

**Comment by dalenoe** [comment]
I could see this being useful for the system admin. Which would make the ideal spot in the system console. I can see a use for a team needing to be able to see the log (to verify).

**Comment by npcode** [comment]
@esethna I understand the privacy issue. I think new log file only for email is a possible option if the issue is very important.

**Comment by it33** [comment]
Ticket opened for this: https://mattermost.atlassian.net/browse/PLT-1607

**Comment by coreyhulen** [comment]
PR submitted https://github.com/mattermost/platform/pull/1816
