### ISSUE TITLE
Create team with gitlab account = 500 error

### ISSUE THREAD

**Issue by cmsimike** [mattermost/platform#1741]
Hi,

I decided to bring up Mattermost on my Gitlab Omnibus install, but no matter what I do, I seem to get a 500 server error when authenticating my gitlab account. Error from mattermost.log is as follows:

[2015/12/16 09:25:47 PST] [EROR] /signup/gitlab/complete:AuthorizeOAuthUser code=500 rid=[removed] uid= ip=[removed] Bad response from token request [details: ]

I'd love to debug this further but don't know how to proceed.

**Comment by beardedgeek** [comment]
Hi.

Did you get this working? I have the same error but not sure how to debug it

**Comment by cmsimike** [comment]
@beardedgeek my specific problem was that mattermost + gitlab were behind http auth, so mattermost would fail at the server to server handshake because of the http auth.

**Comment by bioinfornatics** [comment]
Hi @cmsimike I have exactly the same issue but I do not see wich opation I have to update into my gitlab.rb file as I put everywhere convert http to https to true and external url for each services used the https protocol

Thanks for your help
