### ISSUE TITLE
Server can only start from /opt/mattermost/bin/

### ISSUE THREAD

**Issue by sheepherd** [mattermost/platform#1752]
mattermost 1.3.0 on debian jessie.

./platform can only be run if pwd=/opt/mattermost/bin
If you run it from any other directory the server panics, see below.
cd ~/mattermost/bin && ./platform works.
The init script wont work like this, I couldn't figure out how to set it up yet

the installation worked like a charm on a single server, thanks.

/# /opt/mattermost/bin/platform
panic: Error opening config file=config.json, err=open config.json: no such file or directory

goroutine 1 [running]:
github.com/mattermost/platform/utils.LoadConfig(0xc10d60, 0xb)
	/go/src/github.com/mattermost/platform/utils/config.go:139 +0x16a
main.main()
	/go/src/github.com/mattermost/platform/mattermost.go:46 +0x43

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [runnable]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [runnable]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc820016180, 0x7fd4406901e8, 0xc820024010)
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:23
created by code.google.com/p/log4go.NewConsoleLogWriter
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:19 +0x6e

See also: http://forum.mattermost.org/t/where-can-i-find-config-json/51

**Comment by coreyhulen** [comment]
Thanks,  I think this is already reported as https://mattermost.atlassian.net/browse/PLT-1111.

**Comment by sheepherd** [comment]
Alright, you can close this issue if it's already tracked elsewhere.
