### ISSUE TITLE
mobile push notifications as separate option

### ISSUE THREAD

**Issue by ftKnox** [mattermost/platform#1761]
We have email notifications disabled so conversations snippets are not bleeding out onto off premise email servers. This however seems to disable mobile push notifications as well. Shouldn't the push notifications just be another global and or per channel notification option just like the desktop notifications? Having the mobile and desktop notifications happen together if they are both enabled.

**Comment by coreyhulen** [comment]
In 1.3 a new property was added to enable/disable push notifications.  See https://github.com/mattermost/platform/blob/master/config/config.json#L72

**Comment by ftKnox** [comment]
@coreyhulen right, but having email notifications enabled and working is a pre-requisite correct? What I am asking about is making them a separate option inside the account notification settings. Thereby allowing the mobile push notifications to work independently of the email notification settings.

**Comment by coreyhulen** [comment]
Sorry, I missed the request on per-channel.  Yea, I think it makes sense to add another option to the **Account Settings ** > **Notifications** section for mobile push notifications.

**Comment by coreyhulen** [comment]
@esethna can we add a tix to jira, thanks.

**Comment by esethna** [comment]
Thanks @ftKnox, ticket created [here](https://mattermost.atlassian.net/browse/PLT-1577) for account settings notification option.

**Comment by lfbrock** [comment]
Closing issue, it will be tracked in [Jira](https://mattermost.atlassian.net/browse/PLT-1577)

**Comment by sash85** [comment]
The issue should be fixed with version v2.2.0 [ 10502 ] but now it ist moved to v2.3.
Is v2.3 now fix or will it move again?
We really like to use mattermost, its a great tool and without this problem it would be perfect :-).

**Comment by lfbrock** [comment]
@sash85 this is fixed in the v3.1 release available June 16, sorry for the delay
