### ISSUE TITLE
Feature idea: Permissions for channel and private group creation via new manager role

### ISSUE THREAD

**Issue by kailashgajara** [mattermost/platform#1764]
Hi Guys,

First of all thank you so much for putting together the latest stable release...

Secondly I had few queries:
1. Can we create extra role? As of now I see Admin, Member.
2. All member by default after invited, can create channel, private groups etc.. how to stop this? Only admin should be able to create channels and private groups..
3. In above case, "manager" can create channels and private groups apart from activities that regular "member" role can do.

**Comment by it33** [comment]
Hi @kailashgajara, appreciate the feedback, 

1. Not yet, if you have ideas, please [share a feature idea](http://www.mattermost.org/feature-requests/) so it can be upvoted by the community? 
2. Similar to the ability to start internal email threads, currently any team member can start channels and private groups to discuss topics. Open to feature ideas for upvotes to change this. 
3. Also open to feature ideas for upvotes. 

Please link back to the feature idea posts to help others find them from this issue?

**Comment by kailashgajara** [comment]
1. http://mattermost.uservoice.com/forums/306457-general/suggestions/11205615-different-user-roles-to-configure
2. http://mattermost.uservoice.com/forums/306457-general/suggestions/11205624-only-admin-or-manager-should-be-able-to-create-cha
3. covered in above two points...

**Comment by thePanz** [comment]
Thumbs up for this feature!
It would be interesting to discuss other 'permission' and Channel related settings such as "lock user to this channel" to force, employees to stay up to date with important communications and avoiding them tu un-subscribe (that's just an example ;) )

**Comment by thePanz** [comment]
Should we open multiple issues by splitting this one?

**Comment by lfbrock** [comment]
Going to close this issue, please discuss on the feature idea forum so we can keep the discussion all in one place? 

http://mattermost.uservoice.com/forums/306457-general/suggestions/11205615-different-user-roles-to-configure
http://mattermost.uservoice.com/forums/306457-general/suggestions/11205624-only-admin-or-manager-should-be-able-to-create-cha
