### ISSUE TITLE
Markdown lists containing only one single element are not being rendered correctly.

### ISSUE THREAD

**Issue by jsepia** [mattermost/platform#1765]
From the [Gitlab markdown documentation](https://gitlab.com/gitlab-org/gitlab-ce/blob/6-4-stable/doc/markdown/markdown.md#toc_21), I expect lists containing a single element to still render as lists.

In other words, this markdown code

    * Item

Should yield a list, like this:

* Item

And this code:

    * Item 1
      * Item 1.1
    * Item 2

Should yield a list with two levels of nesting:

* Item 1
  * Item 1.1
* Item 2

But in Mattermost, lists are ignored unless they have two or more items:

![screenshot](https://cloud.githubusercontent.com/assets/102862/11965455/7377b1e8-a8a9-11e5-8700-f295c2e5efcb.png).

The example in the screenshot was generated using the following Markdown code:

    This should be a list with a single item. It is rendered as a paragraph:
    
    * Item 1
    
    Lists with two items are rendered correctly:
    
    * Item 1
    * Item 2
    
    Nesting lists work correctly as long as each sublist has at least two items:
    
    * Item 1
      * Item 1.1
      * Item 1.2
    * Item 2
    
    But if a nested list has only one item, it is treated as inline text:
    
    * Item 1
      * Item 1.1
    * Item 2

**Comment by it33** [comment]
Thanks @jsepia, appreciate the report, this should be fixed on master

![image](https://cloud.githubusercontent.com/assets/177788/12029355/d1bcd65e-ad9d-11e5-8cd6-1eaba68d829b.png)
