### ISSUE TITLE
Drag and drop file upload gives four copies of the file?

### ISSUE THREAD

**Issue by Timmmm** [mattermost/platform#1767]
I'm using Firefox and Mattermost 1.3.0. When I drag a file into the conversation window it uploads four copies of the file. If I use the paperclip icon to open the file instead it works correctly.

It seems like `FileUpload.handleDrop()` is called multiple times.

**Comment by esethna** [comment]
Thanks @Timmmm, Our team hit this issue as well but couldn't find exact repro steps. Does this happen for you everytime you use drag and drop with an image or are there certain file types or repro steps that cause it to happen?

I've created a ticket [here](https://mattermost.atlassian.net/browse/PLT-1578).
