### ISSUE TITLE
Improvement: Push notifications should display a snippet of the message.

### ISSUE THREAD

**Issue by hjf288** [mattermost/platform#1771]
It would be useful if when receiving a push notification, it gave you a snippet of the message that prompted the notification, i.e:

`@hjf288 Web server down, please check`

Whereas at the moment it just sends me an alert that gives me no indication of whether the reason for mentioning me was important:

`mentioned you in Town Square`

**Comment by it33** [comment]
Thanks @hjf288! [Ticket added to enable this](https://mattermost.atlassian.net/browse/PLT-2053)
