### ISSUE TITLE
Feature idea: Bullet field and [  ] Show Password option for SMTP password 

### ISSUE THREAD

**Issue by hvnsweeting** [mattermost/platform#1772]
should the text field changed to a bullet field to hide the password?

in ``ADDRESS/admin_console/email_settings/?session_token_index=0``

**Comment by it33** [comment]
Hi @hvnsweeting, appreciate your feedback, there's now [a ticket on this recommended for APR](https://mattermost.atlassian.net/browse/PLT-1585). 

For context, the System Console is just an editor for the `config.json` file. 

Adding a bullet field for the password only protects it to the extent that someone looking over the shoulder of the System Admin won't be able to see it, it's still stored in `config.json`, which the System Admin can view.

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in [Jira](https://mattermost.atlassian.net/browse/PLT-1585)
