### ISSUE TITLE
Feature idea: Add Ctrl-K like in slack

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1774]
Fuzzy search in the channels.

**Comment by it33** [comment]
Hi @Ticki, highly appreciate your feedback, 

Could we have your help [adding a feature idea](http://www.mattermost.org/feature-requests/) so this can be upvoted by the community?

**Comment by Ticki** [comment]
Will do. Thanks.

**Comment by oamado** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/10631094-hotkeys-keyboard-shortcuts
