### ISSUE TITLE
Feature idea: Add channel favorites

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1775]
Like in slack.

**Comment by it33** [comment]
Hi @Ticki, highly appreciate your feedback, 

Could we have your help [adding a feature idea](http://www.mattermost.org/feature-requests/) so this can be upvoted by the community?

**Comment by pedromorgan** [comment]
:+1:

**Comment by lfbrock** [comment]
Closing this issue, feature idea can be upvoted here: https://mattermost.uservoice.com/forums/306457-general/suggestions/11206080-add-channel-favorites
