### ISSUE TITLE
Feature idea: Switch to twemoji

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1776]
http://twitter.github.io/twemoji/preview.html  It's CC licensed.

**Comment by Ticki** [comment]
Actually, gemoji might be more fitting: https://github.com/github/gemoji

**Comment by Ticki** [comment]
Gemoji might be better:

https://github.com/github/gemoji/tree/master/images/emoji

**Comment by it33** [comment]
Hi @Ticki, highly appreciate your feedback, 

Could we have your help [adding a feature idea](http://www.mattermost.org/feature-requests/) so this can be upvoted by the community?

**Comment by Ticki** [comment]
I will close this. It is moved to feature idea forum.
