### ISSUE TITLE
Add ability to add custom emojis

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1777]
A feature handy in Slack.

**Comment by esethna** [comment]
Looks like [this idea](https://mattermost.uservoice.com/forums/306457-general/suggestions/11206074-add-ability-to-add-custom-emojis) is added on our feature idea forum. Please up vote it there and feel free to discuss with other community members in the comments section? 

Just an FYI, we generally use GitHub for bug reports and ask that all feature ideas be routed via the [feature idea forum](http://www.mattermost.org/feature-requests/). Thanks for your interest in Mattermost!

**Comment by Ticki** [comment]
Sorry for that. I'll close this issue.
