### ISSUE TITLE
Implement Emojione's ASCII conversions

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1780]
http://git.emojione.com/demos/2.0.0/ascii-smileys.html

**Comment by it33** [comment]
Thanks @Ticki, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?
