### ISSUE TITLE
Accepting Pull Requests: Enable emoji auto-complete to find emoji by alias

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1781]
http://git.emojione.com/demos/2.0.0/autocomplete.html

**Comment by it33** [comment]
Hi @Ticki, can you help us understand what's wrong with the existing emoji auto-complete?

**Comment by Ticki** [comment]
Yes, there's already a pretty cool autocompletion in mattermost, but emojione autocompletion contains aliases too, which I think would be a cool feature!

**Comment by it33** [comment]
Ah, thanks @Ticki! Makes sense, [ticket added for this](https://mattermost.atlassian.net/browse/PLT-1588). Updating title to make this more clear.

**Comment by it33** [comment]
Just curious, would you be interested in creating a pull request to add this?

**Comment by Ticki** [comment]
I'll look into it, though I'm not very experienced in Go (I'm a Rust and C programmer).

**Comment by it33** [comment]
Thanks @Ticki! Appreciate your the consideration,

**Comment by lfbrock** [comment]
Closing issue, it will be tracked in [Jira](https://mattermost.atlassian.net/browse/PLT-1588)
