### ISSUE TITLE
Bug: Slack comments in import file do not show up after importing into Mattermost

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1782]
It's unable to import messages.

**Comment by esethna** [comment]
Hi @Ticki,

Can you please help provide a little more information on what failed and repro steps if possible? We have some documentation on slack import [here](https://github.com/mattermost/platform/blob/master/doc/help/Team-Settings.md#import), let me know if this helps? There are currently some limitations with slack import that are outlined in the [Notes](https://github.com/mattermost/platform/blob/master/doc/help/Team-Settings.md#notes) section of the documentation.

**Comment by Ticki** [comment]
@esethna It suceedes without any errors, except that slack comments does not show up in the history, even though they're in the exported data.

**Comment by kirsty-gasston** [comment]
We've experienced the same issue today - the Slack channels imported but none of the messages

**Comment by esethna** [comment]
Thanks @Ticki and @kirsty-gasston , I've filed a [ticket](https://mattermost.atlassian.net/browse/PLT-1781) to track down this issue.

Any additional info on repro steps would be helpful. i.e did all channels fail to import messages?

**Comment by vcazan** [comment]
I experienced the same issue today on a clean Ubuntu 14.04 x64 server. Set up mattermost team and tried to import an export that I did today Jan29th from slack. 

Channels were created but non of the messages where imported, neither were any of the users.

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in Jira.
