### ISSUE TITLE
Invite links stay the same

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1789]
This is major security bug. The invite links do not change.

**Comment by it33** [comment]
Hi @Ticki, appreciate your reporting this, 

You can reset the invite link by going to **Team Settings** > **Invite Code** and click "Re-Generate" 

Does this help? 

@eric or @esethna, could you help [update the documentation for this](https://github.com/mattermost/platform/blob/master/doc/help/Team-Settings.md#invite-code)? 

What's in the documentation seems to be different than what's in the help text (regarding what happens when you click "Re-Generate" if you've checked "Allow anyone to sign-up from login page"). Maybe have your help to test it briefly and update as appropriate? 

I believe the invite code is used in both the "Get Invite Team Link" option from the main menu and when turning on the "Allow anyone to sign-up from login page" from the main page, and we just need to reflect this...

**Comment by Ticki** [comment]
Why isn't it regenerating by default?

**Comment by it33** [comment]
hi @Ticki, 

1) If you use "Invite New Member" to send an invite link by email, the assumption is that you want only that individual to join and the link expires in 48 hours

2) If you use "Get Team Invite Link" to share a link, the assumption is that you're sharing with people you want to join and don't want it disabled until you decide to disable it. 

3) This all said, it's the [`RestrictCreationToDomains`](https://github.com/mattermost/platform/blob/master/doc/install/Configuration-Settings.md#team-settings) option in the System Console that would be most effective in restricting user account creation to only verified email addresses from a set of domains that your team uses. While link expiry can reduce the chances of a link getting into the wrong hands, it won't help if either 1) or 2) are compromised, but 3) will,

**Comment by esethna** [comment]
Hi @Ticki @it33 

I've tested this and regardless of the setting for "Allow anyone to sign-up from login page" the invitation link in the "Invite New Member" email still works after regenerating the invite code. I've [updated the Team-Settings.md to reflect this](https://github.com/mattermost/platform/pull/1794/files) so the documentation should be accurate for current behavior. The "Get Team Invite Link" invalidates as expected when you regenerate the invite code.

**Comment by Ticki** [comment]
> The "Get Team Invite Link" invalidates as expected when you regenerate the invite code.

It does not for me. It yields the same link every time.

**Comment by esethna** [comment]
@Ticki just to verify, are you clicking save after regenerating the link? The behavior built into the modals is that if the modal is closed without the user clicking "save" then the changes are reverted.

**Comment by Ticki** [comment]
Yes I am. But ideally it should regenerate every time a new link is requested (also when save is clicked).

**Comment by esethna** [comment]
@Ticki I can't seem to reproduce this, it is working as expected for me. Do you mind providing more detailed repro steps, system/browser information, and account permissions? This would be good to track down, thanks for your help!

**Comment by it33** [comment]
Hi @Ticki, 

Just circling back on this, to recap: 

1) If you use "Invite New Member" to send an invite link by email, the assumption is that you want only that individual to join and the link expires in 48 hours. 

![image](https://cloud.githubusercontent.com/assets/177788/13200872/a2a6d5ee-d80f-11e5-9468-3ef39a87f9d4.png)

![image](https://cloud.githubusercontent.com/assets/177788/13200873/aa7f64a2-d80f-11e5-84c5-688d90fb7452.png)

2) If you use "Get Team Invite Link" to share a link, the assumption is that you're sharing with people you want to join and don't want it disabled until you decide to disable it from Team Settings > Invite Code

![image](https://cloud.githubusercontent.com/assets/177788/13200870/9ce9d11a-d80f-11e5-9e68-1db62e3b1ba7.png)

![image](https://cloud.githubusercontent.com/assets/177788/13200877/b472af0a-d80f-11e5-9a00-e966cde9653b.png)

There is no "Save" button. 

If "Get Team Invite Link" were to regenerate the link each time the menu item was selected, it would invalidate links previously shared to invite people. 

![image](https://cloud.githubusercontent.com/assets/177788/13200879/c2d0d3c4-d80f-11e5-9310-218dfa96a062.png)

Please let me know your thoughts?
