### ISSUE TITLE
ppt，word，excel file preview

### ISSUE THREAD

**Issue by roughsoft** [mattermost/platform#1793]

**Comment by esethna** [comment]
Hi @roughsoft,

Thanks for the feature suggestion! Agree that this would be useful. Can I ask that you please route this idea via the [feature idea forum](http://www.mattermost.org/feature-requests/) so it can be reviewed and up voted by the community?

**Comment by lfbrock** [comment]
Closing this issue, it can be upvoted here: https://mattermost.uservoice.com/forums/306457-general/suggestions/11723184-add-previews-for-ppt-word-and-excel-files
