### ISSUE TITLE
Desktop/mobile apps?

### ISSUE THREAD

**Issue by kflorence** [mattermost/platform#1796]
To even consider using mattermost at our company we'd need there to be at the least a desktop app that less tech savvy users can install and use. It can be a simple wrapper for the HTML 5 UI that already exists for the browser, so it shouldn't be too difficult to make.

**Comment by kflorence** [comment]
Just found http://mattermost.uservoice.com/forums/306457-general/suggestions/8867134-add-a-app-for-desktops which led me to http://www.mattermost.org/community-applications/#native -- this is a pretty non-intuitive place to find a native app. It would be nice to have some native apps endorsed by mattermost itself and added to the download page.

**Comment by hjf288** [comment]
The iOS app is awaiting approval so they can't link to the app store yet and the Android version is still in beta/not on the Google play store.

An official native app or endorsed/recommended native app for desktops on their download page is a good suggestion though :)

**Comment by walterheck** [comment]
@hjf288 can you tell me where I can find the beta android app's code? Would be very curious to take a look at it, but I can't find it here on github?

**Comment by hjf288** [comment]
@walterheck I don't think they have released the Android code yet

**Comment by walterheck** [comment]
@coreyhulen can you comment on this? I see the ios app is open source, what about the android app?

**Comment by coreyhulen** [comment]
@walterheck the code for android is still in active development.  Once we get it stable and the code cleaned up we will release it like iOS.

**Comment by jazzcrack** [comment]
Is it possible to test the beta version for Android?

**Comment by imval** [comment]
I'd like to join the beta test for the Android app too, if possible !

**Comment by hjf288** [comment]
The Mattermost team posted the APK in the pre-release Mattermost instance, so pop on and check it out :)

**Comment by imval** [comment]
Can't find it anywhere, can you give us some clues or link ? :-)

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in [Jira](https://mattermost.atlassian.net/browse/PLT-1684). Android app will likely be available late February.
