### ISSUE TITLE
Support AWS Authentication via Instance Role for S3 Files

### ISSUE THREAD

**Issue by mrburrito** [mattermost/platform#1797]
I'm deploying Mattermost on AWS using IAM Roles to provide temporary credentials to the instances. I was hoping it would work out of the box and, when it didn't, I created a script to retrieve the temporary credentials periodically and update the Mattermost config.json with the credentials so it can store files in S3. However, the config only supports AccessKeyId and SecretAccessKey. The temporary credentials require the inclusion of a Session Token as well.

I see two possible solutions to this:

The simple solution would be to add an optional `AmazonS3SessionToken` configuration option in the `FileSettings` and update the authentication to provide this value if it exists.

The better solution, in my mind, would be to have Mattermost natively support credential lookup for AWS instance roles, managing the token expiration and auth configuration internally so temporary credentials are not exposed in the System Console or config.json file. Not sure if `goamz` supports this natively or if it would be a solution like providing the role name in config.json and having Mattermost retrieve the credentials.

**Comment by it33** [comment]
Thanks @mrburrito, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?

**Comment by mrburrito** [comment]
Posted in feature idea forum: http://mattermost.uservoice.com/forums/306457-general/suggestions/12437100-add-iam-role-support-for-s3-authentication-on-aws
