### ISSUE TITLE
Bug: Embedded YouTube video from a channel automatically plays itself without intervention

### ISSUE THREAD

**Issue by stratact** [mattermost/platform#1798]
This is how happens in the following order:
1) A different user other than myself enters in a message in the channel which already has an embedded YouTube video from pasting a link. 
2) I view the channel where the user enters the message which has the embedded YouTube video.
3) I then look into any other channel and the YouTube video will automatically play itself at the beginning again, despite having already paused it multiple times and not originally playing the video.

**Comment by it33** [comment]
Thanks @stratact! Appreciate the report, fixed for v1.4: https://github.com/mattermost/platform/commit/5a2100547532c8026ee34bfa44b883de3a233fd9
