### ISSUE TITLE
Email notifications not working

### ISSUE THREAD

**Issue by hank** [mattermost/platform#1799]
I've set up my email to go to localhost:25, and the test email button works fine - I get each email I send with the test button.  However, when someone is mentioned in the channel and they aren't logged in, the email notifications are not going out.  How can I troubleshoot this?

**Comment by it33** [comment]
Hi @hank, thanks for your question. Could we have your help posting to the [troubleshooting forum](https://forum.mattermost.org/t/how-to-use-the-troubleshooting-forum/150)?

There's a ticket [to add more logging info](https://mattermost.atlassian.net/browse/PLT-1607)

**Comment by hank** [comment]
I got it working - thanks!
