### ISSUE TITLE
Inconsistent Emoji Shortname - feet/footprints/paw_prints

### ISSUE THREAD

**Issue by DavidJFelix** [mattermost/platform#1803]
There is currently a discussion about shortnames going on in the emojione tracker about shortname consistency. Mattermost seems to be using different shortnames than Github/Emojione for the following emoji:

:feet: :footprints:

Here's a link to the discussion. Ranks/emojione#182

**Comment by it33** [comment]
Thanks @DavidJFelix, we're open to improvements. Preference is to do things systematically, so if there's a standard that seems to be gaining acceptance on what text translates to which emoji, I don't see why we wouldn't change. 

Please let us know how you see things evolving?

**Comment by DavidJFelix** [comment]
@it33: @mikebe11 brought a few things to my attention in [this comment](https://github.com/Ranks/emojione/issues/182#issuecomment-168830639). I don't have any prior history with emojione and I feel like I've been reasonably sold that emojione is in pursuit of the most standard definition for shortname and openly moving toward that wherever possible. I think the desired result would be to match the emojione behavior, which also matches github. `:feet:` -> :feet: ; `:foot_prints:` -> :footprints: and an alias for `:feet:` exists as `:paw_prints:` -> :feet: 

This seems to be the most widely adopted way, as demonstrated in the above bug report table.

**Comment by lfbrock** [comment]
Closing this issue, an accepting pull requests [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1861) was created to update the emoji naming to match the emojione documentation.
