### ISSUE TITLE
Bug: Wrong "Content Security Policy" header

### ISSUE THREAD

**Issue by gsmet** [mattermost/platform#1811]
Hi,

In Firefox, when I enable the dev tools, I have the following error:
`Content Security Policy: Interpreting none as a hostname, not a keyword. If you intended this to be a keyword, use 'none' (wrapped in single quotes).`

Looks like none should be quoted here:
https://github.com/mattermost/platform/blob/4b3a3941e04803539f39c057a5c0d44cd30699be/api/context.go#L155

Any thoughts?

**Comment by coreyhulen** [comment]
Thanks for the report.  Looks like it should be
`Content-Security-Policy: frame-ancestors 'none'`

@esethna can we create a tix in JIRA.

**Comment by it33** [comment]
@esethna bump

**Comment by esethna** [comment]
Thanks, ticket created. Closing as it will be tracked in [Jira](https://mattermost.atlassian.net/browse/PLT-1858).
