### ISSUE TITLE
Implement more favicons

### ISSUE THREAD

**Issue by nils-werner** [mattermost/platform#1818]
Currently you are only showing the [absolute minimum for a favicon to render](https://github.com/mattermost/platform/blob/da6aba6e50d2571354b03b67bdd0b0b84f92ce9c/web/templates/head.html#L30). This has the effect that Android generates its own favicon from the domain name instead of showing the site favicon

To have mobile browsers show nicer favicons, especially when pinning Mattermost to your homescreen, you should implement many more favicon sizes, I usually go with

    <link rel="apple-touch-icon" sizes="57x57" href="/static/images/favicon/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/static/images/favicon/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/static/images/favicon/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/static/images/favicon/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/static/images/favicon/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/static/images/favicon/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/static/images/favicon/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/static/images/favicon/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/images/favicon/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/static/images/favicon/android-chrome-192x192.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/static/images/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="manifest.json">

and a `manifest.json` like

    {
    	"name": "<site name>",
    	"short_name": "<site name>",
        "display": "standalone",
        "theme_color": "<sidebar color for user here>",
        "background_color": "<background color for user>",
    	"icons": [{
    		"src": "/static/images/favicon/android-chrome-36x36.png",
    		"type": "image/png",
    		"sizes": "36x36"
    	}, {
    		"src": "/static/images/favicon/android-chrome-48x48.png",
    		"type": "image/png",
    		"sizes": "48x48"
    	}, {
    		"src": "/static/images/favicon/android-chrome-72x72.png",
    		"type": "image/png",
    		"sizes": "72x72"
    	}, {
    		"src": "/static/images/favicon/android-chrome-96x96.png",
    		"type": "image/png",
    		"sizes": "96x96"
    	}, {
    		"src": "/static/images/favicon/android-chrome-144x144.png",
    		"type": "image/png",
    		"sizes": "144x144"
    	}, {
    		"src": "/static/images/favicon/android-chrome-192x192.png",
    		"type": "image/png",
    		"sizes": "192x192"
    	}, {
    		"src": "/static/images/favicon/android-chrome-256x256.png",
    		"type": "image/png",
    		"sizes": "256x256"
    	}, {
    		"src": "/static/images/favicon/android-chrome-384x384.png",
    		"type": "image/png",
    		"sizes": "384x384"
    	}, {
    		"src": "/static/images/favicon/android-chrome-512x512.png",
    		"type": "image/png",
    		"sizes": "512x512"
    	}]
    }

**Comment by asaadmahmoodspin** [comment]
@nils-werner Thanks for pointing that out, I'll follow through.

**Comment by it33** [comment]
FYI, https://github.com/mattermost/platform/pull/1893/files
