### ISSUE TITLE
FR: add support for syslog output

### ISSUE THREAD

**Issue by MartinNowak** [mattermost/platform#1820]
It's a pain to deal with many scattered logfiles, so syslog support would be a welcome alternative.
The only extra configuration despite enabling it should be the syslog facility.

**Comment by it33** [comment]
Thanks @MartinNowak, we've been discussing this internally. Just curious, if we opened a ticket to accept pull requests on this, would you be interested in implementing it?

**Comment by MartinNowak** [comment]
> Just curious, if we opened a ticket to accept pull requests on this, would you be interested in implementing it?

I can have a try at it, not too fluent in go though.

**Comment by it33** [comment]
Hi @MartinNowak, thanks again for considering making a PR on this, 

If you're open to others contributing to this, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? 

   Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread? 

This will also bring the feature to the larger audience that's on the feature idea forum, and reduce duplication by having all feature ideas in one place.

**Comment by MartinNowak** [comment]
http://mattermost.uservoice.com/forums/306457-general/suggestions/12446994-add-support-for-syslog-output
