### ISSUE TITLE
iOS app - Returned to login page after logging in and seeing glimpse of Town Square

### ISSUE THREAD

**Issue by mls5181** [mattermost/platform#1825]
After logging in to iOS app downloaded from App Store, get booted back to login page immediately after logging in.  Doesn't seem like a credentials issue as I can login fine through web app and I do seem to get to the Town Square page quickly before getting booted.  Had setup MM team site through jelastic.

**Comment by it33** [comment]
Hi @mls5181, appreciate the report. Hmm... not sure how to repro. Anyone else from the community seeing something similar?

**Comment by mls5181** [comment]
Sorry for the delayed response.  All others on the team are having the same issue using the iOS app.

**Comment by mls5181** [comment]
Anything else I can do to troubleshoot?

**Comment by it33** [comment]
I'm wondering if it's an issue with Jelastic, could you try opening accounts on gitlab.mattermost.com/community with your iOS apps and see if they work? Also, please consider going to forum.mattermost.org and posting an issue in TroubleShooting category to see if community has seen this before, this is the first I have heard of this,

**Comment by it33** [comment]
[Discussion moved to troubleshooting forum trying to find other Jelastic users](https://forum.mattermost.org/t/booted-from-ios-app-immediately-after-logging-in-mattermost-deployed-on-jelastic/733)
