### ISSUE TITLE
Slack Webhooks from Taiga are apparently incompatible

### ISSUE THREAD

**Issue by drf** [mattermost/platform#1827]
Taiga.io's Slack integration appears not to work with mattermost (installed with gitlab-mattermost).

[2016/01/07 17:41:09 CET] [EROR] /hooks/6fuaia7qbpfzbjip6x9kukxzio:incomingWebhook code=500 rid=kdk7qaqohf8gdjewz47gwakjtr uid= ip=176.9.172.42 Unable to parse incoming data [details: ]

The very same hook works on Slack correctly. I understand there's not much detail in this error, I'd be happy to provide more with some guidance on how to do it.

Note: Incoming Slack webhooks from Gitlab are working correctly.

**Comment by it33** [comment]
Thanks @drf!

Definitely want to fix that, but without seeing what the payload looks like, it's tricky to narrow down the cause. 

There was a similar error with Team Foundation Services that [was recently fixed](https://github.com/mattermost/platform/pull/1817). Mattermost v1.4-RC1 should be available on Monday  from the [list of releases](https://github.com/mattermost/platform/releases) maybe see if the change fixes things?

**Comment by drf** [comment]
Hi @it33 

I'll definitely try the new release when it's out, thanks!

In the meanwhile, I dug a bit into Taiga - the hooks are generated from here: https://github.com/taigaio/taiga-contrib-slack/blob/master/back/taiga_contrib_slack/tasks.py . Maybe it rings a bell to you.

Is there a way to have mattermost print the incoming request from webhooks/Taiga, so I can provide you with further details for debugging?

Thanks, and congrats on Mattermost! Great tool.

**Comment by drf** [comment]
@it33 , found and solved: https://github.com/taigaio/taiga-contrib-slack/pull/38

Question remains: apparently Slack digests any content type and is not as strict as Mattermost when it comes to incoming webhooks. I think your choice is way more sensible than Slack's, but I'll leave the issue open so you can decide what to do with it.

**Comment by it33** [comment]
Thanks @drf! 

Our goal is to be "Slack compatible, not Slack limited", so anything that works in Slack should work in Mattermost--but we also support things that Slack does not, like rendering markdown passed in through webhooks. 

> Is there a way to have mattermost print the incoming request from webhooks/Taiga, so I can provide you with further details for debugging?

I don't believe this is supported yet, it would be really nice if we got a pull request from someone to have webhook payloads output to logs when logging is set to DEBUG mode in the System Console. 

That could help other pull requests to tweak Mattermost to support anything that Slack supports.

**Comment by it33** [comment]
Original issue solved. 

[Proposing an APR for better logging of webhooks in DEBUG mode](https://mattermost.atlassian.net/browse/PLT-2058)
