### ISSUE TITLE
 Failed to create index pq: column "inviteid" does not exist

### ISSUE THREAD

**Issue by ssbarnea** [mattermost/platform#1834]
This is happening on gitlab-omnibus release 8.3.2, preventing mattermost from starting. Initially I assumed that this was caused by failed upgrade of mattermost database but I changed the mattermost database name inside gitlab.rb, did reconfigure and hopped that the new and clean database will work. Still, the same error occurs even with the new mattermost database.

See https://gitlab.com/snippets/13007

**Comment by marcelocf** [comment]
Same issue here.

**Comment by marcelocf** [comment]
in my server changing the database worked

**Comment by it33** [comment]
Was anything in the Mattermost database manually manipulated?
