### ISSUE TITLE
Team directory has been disabled. Please ask a system admin to enable it.

### ISSUE THREAD

**Issue by ssbarnea** [mattermost/platform#1835]
It seems that the "Team directory has been disabled. Please ask a system admin to enable it." does not give any indication on how to enable this feature. The gitlab.rb files is missing any feature like this, please update the message to give meaningful information for people so they can enable it.

**Comment by it33** [comment]
@esethna, please help add to documentation?

**Comment by esethna** [comment]
Hi @ssbarnea , I've submitted a [PR](https://github.com/mattermost/platform/pull/1929) to update the in-app help text to be more direct on how to enable the team directory. It is a system console setting, in the team settings tab, called **Enable Team Directory**. 
![image](https://cloud.githubusercontent.com/assets/14333569/12457268/d87ca26a-bf60-11e5-8e15-096aece32241.png)
