### ISSUE TITLE
Unable to login with the web/mobile client if Mattermost is configured to use GitLab SSO

### ISSUE THREAD

**Issue by ssbarnea** [mattermost/platform#1837]
I configured Mattermost to use GitLab for authentication and I tried to uset the iOS application to login to it. I tried to login with email+password and it didn't work, I also tried with username and password, didn't work.

I tried a password reset, and I got a message telling me that "Cannot reset password for SSO accounts" which kinda make sense. Still, it seems that you cannot login at all using the client if you enabled SSO.

What's the correct way to enable users to login with their LDAP accounts? Note that GitLab is configured to allow anyone to login using LDAP only, which works very well.

**Comment by it33** [comment]
Hi @ssbarnea, thanks for the question. The first release of the iOS application does not yet support SSO, it's planned for future release, where the UI for SSO in iOS should match the UI for mobile web login. 

Sorry about missing it the first releases,

**Comment by yetzt** [comment]
+1

**Comment by gwelr** [comment]
+1

**Comment by shumushin** [comment]
+1, this is quite annoying, i cannot login to our mattermost server with gitlab auth enabled based on ldap

**Comment by GerDner** [comment]
+1

**Comment by karlvlam** [comment]
+1

**Comment by erikdao** [comment]
This issue still remains. Any plan to fix it?
