### ISSUE TITLE
Feature request: Changing how message logs are managed

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1847]
Currently the log is truncated in "chat mode". By looking at archives, you can see the whole log. The log should not be truncated in chat mode.

**Comment by it33** [comment]
Hi @Ticki, sorry, we need some help understanding the issue you're filing, is what you're experiencing different from [how logs are described to function the product documentation?](https://github.com/mattermost/platform/blob/master/doc/install/Configuration-Settings.md#log-file-settings)

**Comment by Ticki** [comment]
I'm not talking about debug logs. I'm talking about the chat logs.

**Comment by it33** [comment]
Thanks @Ticki, it sounds like this is a feature idea and [not an obvious error or regression](http://www.mattermost.org/filing-issues/), could we have your help moving this to the [feature idea forum where it can be upvoted?](http://www.mattermost.org/feature-requests/)
