### ISSUE TITLE
SMTP server without SSL support  cannot be used?

### ISSUE THREAD

**Issue by depay** [mattermost/platform#187]
Then I tried a SSL supported server, and it works.
I've seen some comments in util/mail.go like: ``go doesn't support plain auth`` . Does it have any relation with the problem?

**Comment by crspeller** [comment]
Correct. The go library we are using for smtp support does not allow credentials to be transmitted in cleartext. Therefore SMTP servers without SSL support can not be used.

**Comment by depay** [comment]
thanks! @crspeller
