### ISSUE TITLE
Accepting Pull Requests: Update messages automatically after reconnecting to network

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#1870]
When two users A and B are in a channel:

1. User A disconects wifi
2. User B sends a message
3. User A reconnects wifi

I want that A can see the message from B immediately and automatically.

**Comment by it33** [comment]
Thanks @npcode, proposing APR ticket: https://mattermost.atlassian.net/browse/PLT-1716

**Comment by it33** [comment]
Closing since we have a Jira ticket to track this
