### ISSUE TITLE
Accepting Pull Requests - Add support for .jpeg in Profile Pictures

### ISSUE THREAD

**Issue by okin** [mattermost/platform#1874]
I wanted to upload a .jp**e**g-file for my profile but I can only select .jpg files.

I'd be nice to be able to select **.jpeg* aswell.

**Comment by it33** [comment]
Thanks @okin, agree, accepting pull requests on this if anyone is interested in offering a fix here,

**Comment by esethna** [comment]
Thanks @okin, ticket created [here](https://mattermost.atlassian.net/browse/PLT-1805).

**Comment by it33** [comment]
Closing as we're tracking this in Jira now,

**Comment by MaxValue** [comment]
I am still seeing this error. Unfortunately I can't post on your Jira, so I hope I am heard here.
The real reason behind this is, is that you set the `accept` attribute of the `input` element for the picture upload to `.jpg,.png,.bmp` It should be `.jpg,.jpeg,.png,.bmp`.
From what I gathered from the feedback in the Jira ticket, some browsers probably interpolate `.jpg` to `.jpeg` and that is probably why only some people are seeing this across different platforms.

```text
Mattermost Version: 5.9.0
Database Schema Version: 5.9.0
Database: mysql
```
