### ISSUE TITLE
Download page is not providing link to compiled platform

### ISSUE THREAD

**Issue by renannprado** [mattermost/platform#1877]
I went to http://www.mattermost.org/download/ 
It seems to offer the compiled link, but actually: https://github.com/mattermost/platform/archive/v1.3.0.zip
It is providing zip file with source code instead.

**Comment by it33** [comment]
Thanks @renannprado! @lindsay, could you help take a look at this?

**Comment by lindsay** [comment]
@it33 thanks for the ping, can you clarify how I can be of help on this? It may be best delegated to our support team if its a technical issue within GitHub.

**Comment by it33** [comment]
Hi @lindsay, I'm sorry, my fault, I meant @lfbrock, apologies on the confusion,

**Comment by lfbrock** [comment]
Thanks for letting us know, it should be fixed now.
