### ISSUE TITLE
Issue integrating android push notifications

### ISSUE THREAD

**Issue by eshaanb** [mattermost/platform#1895]
So I am running the latest version of mattermost (1.4) on my ubuntu server and having some trouble getting my push proxy to get hit. Email notifications are going out fine, but I'm not seeing any traffic hitting my push proxy when it's expected to. I have enabled push notifications in my system console and directed it to my push proxy url/port. In my postgres db -> sessions table I have an entry with a device id (gcm regid) formatted like "android:xxxxxx" and still don't see anything hit my push-proxy. I can provide whatever other details are necessary in getting this resolved. I think the most straightforward way to fix this is to deploy mattermost, add a session with an android:xxx device id and then run push proxy and see why it isn't getting hit (with some logging or breakpoints).

**Comment by coreyhulen** [comment]
From the system console or config.json have you enabled `"SendPushNotifications": true` ?  you can also set the logger to `DEBUG` level and you can see if it's attempting to send push notifications.

**Comment by eshaanb** [comment]
Ya I have them enabled in the console and the push proxy url set. Log level is on debug but don't see any logs related to push.

**Comment by it33** [comment]
Can you let us know what build number you see in the About Dialog?

**Comment by eshaanb** [comment]
5232

**Comment by coreyhulen** [comment]
#5232 is 1.4 which doesn't have the `android:` stuff.  You can pull a daily build from master with https://s3.amazonaws.com/mattermost-travis-master/mattermost.tar.gz and try?

**Comment by eshaanb** [comment]
ah, interesting when I looked at which commits were included in 1.4 I thought I saw the android commit was included. Will try with the latest from there and see.

**Comment by eshaanb** [comment]
Seems to all be working well now! Thanks for the help!
