### ISSUE TITLE
Create the users or teams via the system console

### ISSUE THREAD

**Issue by gebv** [mattermost/platform#1896]
When to expect such a possibility?

**Comment by it33** [comment]
Thanks @gebv, thanks for your question, we need some more feedback from the community on the priority of adding this feature ahead of others. 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? 

   Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?
