### ISSUE TITLE
Does not update profile data from oauth

### ISSUE THREAD

**Issue by nils-werner** [mattermost/platform#1897]
When using GitLab Oauth I cannot change any of my details because

> Log in occurs through GitLab. Email cannot be updated.

However when I change my email address in GitLab that change is not reflected in mattermost.

**Comment by it33** [comment]
Looking at this for v1.5, workaround for now is to change back to email sign-in, change email, then turn SSO back on.

**Comment by lfbrock** [comment]
Jira ticket is here for reference: https://mattermost.atlassian.net/browse/PLT-1732

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in Jira.
