### ISSUE TITLE
Lowercasing usernames makes them less recognizable, no good workaround.  

### ISSUE THREAD

**Issue by homeworkprod** [mattermost/platform#1898]
My username got lowercased automatically (both on account creation from GitLab as well as on manual changes), but it is way harder to recognize that way compared to its original form.

This would be less of an issue if the alternative nickname I specified would be displayed by default if set, for everyone.

However:
* I have to activate it myself.
* That only affects my view, not the way it is displayed to others (despite the "show nickname" option being marked as "team default").
* The "Teammate Name Display" setting only provides the option "Show nickname if one exists, otherwise show first and last name" which falls back to the real name instead of the username (but not an option like "Show nickname if one exists, otherwise show username"). This results in my nickname being shown, but the real names of other users that did not provide a nickname, so nicknames and real names are mixed up which is really confusing in teams whose members mostly know each other by their handles.
* The [IRC bridge](https://github.com/42wim/matterbridge) only seems to pick up the username, extending the reduced recognizability of an original, case-sensitive handle to IRC as well. And that's something the bridge itself shouldn't deal with, so Mattermost should provide the output intended by the account owner.

**Comment by homeworkprod** [comment]
FTR: I consider the described behaviour as more of a bug (or multiple ones) than this issue being a feature request because Mattermost prevents others from automatically seeing my usual nickname/handle (of which case sensivity is an integral part).

**Comment by it33** [comment]
While I can see where you're coming from the documentation and error message explicitly define username as lowercase,

**Comment by homeworkprod** [comment]
@it33: Is there a part of your comment missing (it ends with a comma)?

I'm okay with usernames being lowercase.

I'm not okay, however, with not being able to optionally define a screen name to override it, and that screen name should be displayed to everyone instead, by default.

The whole point of the name display options should be to make clear who I am to the others, but currently it isn't (see my original post).

To rephrase, these are my suggested actions:

- Add a "Teammate Name Display" option "Show nickname if one exists, otherwise show username" (that never shows the real name).
- Check if the "team default" option is broken (see above). Maybe I just misunderstand it.

**Comment by it33** [comment]
Definitely appreciate the feedback. The [feature idea forum](http://www.mattermost.org/feature-requests/) is where community members who agree can upvote the change you're proposing. 

If you could find and aggregate feedback from others on the same topic, it would be helpful as well, 

Sometimes I end my sentences with commas. I don't know why,
