### ISSUE TITLE
Bug: react fails due to outdated babel-runtime (release-1.3)

### ISSUE THREAD

**Issue by DschingisKahn** [mattermost/platform#1900]
Hi,

Updated from 1.2 to 1.3 yesterday and could not access the web interface (page loaded, but without content). Turned out to be a babel problem (cannot find module 'babel-runtime'...). When you guys updated tot Babel 6, you removed babel-runtime from the dependencies. Other dependencies rely on an old version of babel-runtime, which leads to the error above. I have absolutely no clue why you did not just update the dependency.

Anyway, **I re-added babel-runtime ("babel-runtime": "6.3.19",)** to package.json, which fixed it for me after hours of puzzling. Please think twice before removing a dependency...

Thought I'd open an issue, just for documentation purposes. Maybe it helps someone else later on.

**Comment by it33** [comment]
Hi @DschingisKahn, thanks for your help reporting this. Just to narrow down the issue, could we ask your help in run to clean build and see if the issue still happens? 

Our Travis system runs from a clean build each time and seems to be working...

**Comment by enahum** [comment]
@DschingisKahn I had the same issue and the solution was updating node itself to version 5.2.0 and npm 3.3.12, and its working fine for me.

Note: I'll give it a go with the latest version of node 5.4.1 and let you know.

**Comment by DschingisKahn** [comment]
@it33 will try and report back. @enahum Thanks for that solution.

**Comment by lfbrock** [comment]
Closing this issue, if it reoccurs please reopen
