### ISSUE TITLE
Allow webhooks to see other webhooks posts

### ISSUE THREAD

**Issue by tamentis** [mattermost/platform#1901]
It looks like outgoing webhooks are not triggered by other webhooks posts. For example if bot_a posts "hello" on Town Square and bot_b is typically triggered by "hello", it will not be triggered.

**Comment by it33** [comment]
Hi @tamentis, not sure I understand your question, can you give an example of what you're trying to achieve?

**Comment by tamentis** [comment]
I updated the initial comment and the issue title, let me know if it makes more sense.

**Comment by tamentis** [comment]
So what I'd suggest is to turn the `false` below into a configurable option:
```go
	if _, err := CreatePost(c, post, false); err != nil {
		return nil, model.NewAppError("CreateWebhookPost", "Error creating post", "err="+err.Message)
	}
```
This is `CreateWebhookPost()` in `api/post.go`.

**Comment by it33** [comment]
Hi @tamentis, we discussed this internally, would you be interested in adding this? 

It sounds like a useful addition, the danger of course is creating cycles unintentionally

**Comment by tamentis** [comment]
Of course! How do you guys feel about a global `EnableCrossWebhookVisibility` setting?

In practice any Incoming Webhook post would propagate to all the Outgoing Webhooks. Outgoing Webhook responses would be propagated to all Outgoing Webhooks except the one that originated the post.

I agree that two misconfigured webhooks could cause cycles. Coming from IRC, it doesn't seem like a bit issue as long as Outgoing Webhooks do not receive their own responses.

Does it make sense?

**Comment by it33** [comment]
Thanks @tamentis!

Adding @jwilander and @lfbrock to discussion, 

@jwilander, what are your thoughts on `EnableCrossWebhookVisibility` as a name? 

@tamentis, could we have your help drafting the help text for the setting for the [Configuration Settings](https://github.com/mattermost/docs/blob/master/source/administration/config-settings.md) documentation and posting here (including warnings, and maybe an example)? 

We can discuss and finalize and then would love your help adding this,

**Comment by jwilander** [comment]
It's a hard one to name but I'd prefer something more along the lines of `EnableTriggeringByWebhook`.

**Comment by lfbrock** [comment]
Closing this issue, and created an [Accepting Pull Requests](https://mattermost.atlassian.net/browse/PLT-2171) ticket to track it in Jira.
