### ISSUE TITLE
Accepting Pull Requests: Bug: Fails to autocomplete a name when the line starts with a / command

### ISSUE THREAD

**Issue by tamentis** [mattermost/platform#1902]
How to reproduce:
- join a channel
- type `/me waves to @na[TAB]`

The `/me waves to ` is erased and only `@name` remains. I tried Firefox and Chrome.

**Comment by it33** [comment]
Can't seem to repro this, can you share which version you're using?

**Comment by tamentis** [comment]
We're using 1.3 release and multiple of our users are able to reproduce it.

**Comment by stefuNz** [comment]
I'm able to reproduce this as well.

**Comment by it33** [comment]
Thanks, hmm... now it's reproing for me on master and on https://gitlab.mattermost.com/community test server running v1.4 in a private channel, adding @esethna to confirm and open a Jira ticket to triage this,

**Comment by lfbrock** [comment]
I reproduced this one, Jira ticket here: https://mattermost.atlassian.net/browse/PLT-1758

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in Jira.
