### ISSUE TITLE
Bug: When searching for a person's username, the webhooks belonging to that user appears too, in the user's name and avatar.

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1905]

**Comment by lfbrock** [comment]
Can you let us know repro steps for this issue?

**Comment by Ticki** [comment]
1. Search for something a bot controlled by a webhook have said.

2. The name and avatar appears as the webhook's owner, and not the bot.

**Comment by esethna** [comment]
Hi @Ticki. Thanks for the bug report. Can you let us know what version of Mattermost you're testing on?

**Comment by it33** [comment]
Confirmed repro, @esethna, could you help open a Jira ticket to have this fixed? 

![image](https://cloud.githubusercontent.com/assets/177788/13199765/3fc6b920-d7e3-11e5-9ebf-0b3826ab992a.png)

![image](https://cloud.githubusercontent.com/assets/177788/13199767/4452efb8-d7e3-11e5-8f85-f10bfa7efbcb.png)

**Comment by it33** [comment]
Actually, I just [opened the tracking ticket myself](https://mattermost.atlassian.net/browse/PLT-2059) 

Thanks @Ticki!
