### ISSUE TITLE
iOS App crashes shortly after opening, on iOS 9.2 when accessing a non-pushed team website published by a firewall proxy

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1909]
Accessing the website within the browser is fully functional, except that Mattermost displays a blue-ribbon message, that connection should be checked because Mattermost would be unreachable.
Behavior shows on different phones accessing the same website (freshly setup today)

**Comment by lfbrock** [comment]
Do you have access to the server logs? If so, do they show any error message that corresponds to the time of the crash?

**Comment by finius** [comment]
Yes. But the server logs didn't show up anything beside a websocket problem that doesn't seem to be in relation to the time when using the app

**Comment by it33** [comment]
We're thinking now that your proxy server might be stripping off certain headers. Please [troubleshooting guide](http://docs.mattermost.com/install/troubleshooting.html?highlight=unreachable#please-check-connection-mattermost-unreachable-if-issue-persists-ask-administrator-to-check-websocket-port) and if you have issues please post to [troubleshooting forum](https://forum.mattermost.org/t/how-to-use-the-troubleshooting-forum/150) with repro steps, this seems to be a configuration issue not a bug in the product.
