### ISSUE TITLE
Accepting Pull Requests: System Admin can degrad itself to a less granted role which leeds to administrative lockout

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1910]
I had accidently clicked in "System Console" >> "TEAMS" >> within my team on my user (System Admin privileges), and made him to a Member. Without a warning I lost all my privileges and were not able to revert it back to System Admin role. So there is neither a token that saves the permission for my current session nor any kind of security check if I really, really wan't to degrade the last System Admin to member state. IMHO this has to be fixed very urgent!

**Comment by coreyhulen** [comment]
You can add back a system admin via the command line tools http://docs.mattermost.com/administration/command-line-tools.html

`platform -assign_role -team_name="name" -email="user@example.com" -role="system_admin"`

**Comment by finius** [comment]
Okay, that's an important to know way to fix this deadlock situation.
However, one should be protected to not accidently set this configuration.

**Comment by esethna** [comment]
Thanks @finius, ticket created [here](https://mattermost.atlassian.net/browse/PLT-1806)

**Comment by lfbrock** [comment]
Closing issue, it will be tracked in [Jira](https://mattermost.atlassian.net/browse/PLT-588)
