### ISSUE TITLE
Accepting Pull Requests: member invitation emails modifies any orginally secured HTTPs URL address string into a HTTP link with port appendix

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1912]
When a user accesses the teamsite using a secured public domain name (such as "https://www.your-accessed-public-domain-name.com/teamname") to invite a new user, the afterwards send invitation email contains a link to the teamsite, that is no longer the URL of the original HTTPS site. The URL string within the invitation email has now beeing transformed into a HTTP string with a port appendix. So "https://www.your-accessed-public-domain-name.com/teamname" becomes "http://www.your-accessed-public-domain-name.com:443/teamname" which leads to some firewall problems in proxies environments.

**Comment by esethna** [comment]
Thanks @finius, [ticket](https://mattermost.atlassian.net/browse/PLT-1790) created for this issue and sent to triage.

**Comment by esethna** [comment]
Closing as this will be tracked in [JIRA](https://mattermost.atlassian.net/browse/PLT-1790)
