### ISSUE TITLE
Accepting Pull Requests: Smileys ending with a letter at the end of a line are awkward

### ISSUE THREAD

**Issue by jovandeginste** [mattermost/platform#1918]
I have a tendency to end sentences with some smileys; some of end with a letter. Eg: `:o` and `:p`

However, the Mattermost input box will popup a "emoticon selector" when you type the letter. When you hit "enter" (because it was the end of the line), you will select the first emoticon in the list. For `:p`, this is `:accept:`. You will not send the line - you need to press enter again for this. The only fast workaround I found was typing space, then enter.

(This behaviour is present sinds 1.2.1, and I just upgraded to 1.4.0 to find it's still here)

**Comment by it33** [comment]
Agree should look into a fix for this, in the meantime, does using capital letters, `:P` and `:O`, work?

**Comment by esethna** [comment]
Thanks @jovandeginste, [ticket](https://mattermost.atlassian.net/browse/PLT-1782) created for this improvement.

**Comment by jovandeginste** [comment]
@it33 capitals behave as they should - funny I never use those :-)

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in Jira

**Comment by DeepSnowNeeL** [comment]
Please fix this, this is so frustrating

**Comment by lfbrock** [comment]
Hi @DeepSnowNeeL, this should be fixed in v3.2 (July 16th release date)

**Comment by DeepSnowNeeL** [comment]
Awesome thanks ! Keep up the good work :)

**Comment by jovandeginste** [comment]
I confirm this is fixed :-) (a little late to the party)
