### ISSUE TITLE
Accepting Pull Requests: <!channel> does not function as expected in incoming webhook

### ISSUE THREAD

**Issue by DivineOmega** [mattermost/platform#1919]
Summary: In Slack, if you send `<!channel>` at the start of an incoming webhook's payload text, the entire channel (all its members) will be notified.

Steps to reproduce: 

1. Setup an incoming webhook for a channel that several users are part of.
2. Send a POST to the webhook with the text part of the payload beginning with `<!channel>`.
3. Note that fact that channel members are not notified.

Expected behavior: All channel members should be notified of the message, as in Slack.

Details from Slack documentation:

> Bot messages
> 
> If you wish to trigger one of these notifications with a bot message, the message should contain <!channel> or <!everyone>.

Source: https://get.slack.help/hc/en-us/articles/202009646-Making-announcements

Observed behavior: In Mattermost, the literal text of `<!channel>` is just output as part of the message.

Possible fixes: Transform the `<!channel>` part of the payload to `@channel`

**Comment by esethna** [comment]
Thanks @DivineOmega, ticket created [here](https://mattermost.atlassian.net/browse/PLT-1807).

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in Jira
