### ISSUE TITLE
Support Websocket connections on ports other than 80 or 443

### ISSUE THREAD

**Issue by loafoe** [mattermost/platform#1923]
Our Mattermost setup does not work when deployed to Cloudfoundry on AWS. The reason is that secure websocket connections must be initiated on a different port than the standard `443`. There is no way to override this value  in Mattermost at this time. Working on a PR for this.

**Comment by esethna** [comment]
Thanks @loafoe , [ticket](https://mattermost.atlassian.net/browse/PLT-1783) created for this issue.

**Comment by loafoe** [comment]
@esethna created a PR #1924 for this and it was just merged. Yay!
