### ISSUE TITLE
Install fails centos 6.6: Failed to ping db err:pq: SSL is not enabled on the server

### ISSUE THREAD

**Issue by mcobb2105** [mattermost/platform#1925]
Installing the latest bit per doc's results in error cannot connect:

[01/19/16 16:41:57] [CRIT] Failed to ping db err:pq: SSL is not enabled on the server
panic: Failed to open sql connection pq: SSL is not enabled on the server

Has to be me..............what am i missing?

Both postgres .confs configured correctly.

Current config.json

{
    "ServiceSettings": {
        "ListenAddress": ":8065",
        "MaximumLoginAttempts": 10,
        "SegmentDeveloperKey": "",
        "GoogleDeveloperKey": "",
        "EnableOAuthServiceProvider": false,
        "EnableIncomingWebhooks": false,
        "EnableOutgoingWebhooks": false,
        "EnablePostUsernameOverride": false,
        "EnablePostIconOverride": false,
        "EnableTesting": false,
        "EnableSecurityFixAlert": true
    },
    "TeamSettings": {
        "SiteName": "Mattermost",
        "MaxUsersPerTeam": 50,
        "EnableTeamCreation": true,
        "EnableUserCreation": true,
        "RestrictCreationToDomains": "",
        "RestrictTeamNames": true,
        "EnableTeamListing": false
    },
    "SqlSettings": {
        "DriverName": "postgres",
        "DataSource": "postgres://mmuser:mmuser_password@192.168.0.24:5432/Hokett2105#?sslmode=disable&connect_timeout=10",
        "DataSourceReplicas": [],
        "MaxIdleConns": 10,
        "MaxOpenConns": 10,
        "Trace": false,
        "AtRestEncryptKey": "7rAh6iwQCkV4cA1Gsg3fgGOXJAQ43QVg"
    },
    "LogSettings": {
        "EnableConsole": true,
        "ConsoleLevel": "DEBUG",
        "EnableFile": true,
        "FileLevel": "INFO",
        "FileFormat": "",
        "FileLocation": ""
    },
    "FileSettings": {
        "DriverName": "local",
        "Directory": "./data/",
        "EnablePublicLink": true,
        "PublicLinkSalt": "A705AklYF8MFDOfcwh3I488G8vtLlVip",
        "ThumbnailWidth": 120,
        "ThumbnailHeight": 100,
        "PreviewWidth": 1024,
        "PreviewHeight": 0,
        "ProfileWidth": 128,
        "ProfileHeight": 128,
        "InitialFont": "luximbi.ttf",
        "AmazonS3AccessKeyId": "",
        "AmazonS3SecretAccessKey": "",
        "AmazonS3Bucket": "",
        "AmazonS3Region": ""
    },
    "EmailSettings": {
        "EnableSignUpWithEmail": true,
        "SendEmailNotifications": false,
        "RequireEmailVerification": false,
        "FeedbackName": "",
        "FeedbackEmail": "",
        "SMTPUsername": "",
        "SMTPPassword": "",
        "SMTPServer": "",
        "SMTPPort": "",
        "ConnectionSecurity": "",
        "InviteSalt": "bjlSR4QqkXFBr7TP4oDzlfZmcNuH9YoS",
        "PasswordResetSalt": "vZ4DcKyVVRlKHHJpexcuXzojkE5PZ5eL",
        "SendPushNotifications": false,
        "PushNotificationServer": ""
    },
    "RateLimitSettings": {
        "EnableRateLimiter": true,
        "PerSec": 10,
        "MemoryStoreSize": 10000,
        "VaryByRemoteAddr": true,
        "VaryByHeader": ""
    },
    "PrivacySettings": {
        "ShowEmailAddress": true,
        "ShowFullName": true
    },
    "GitLabSettings": {
        "Enable": false,
        "Secret": "",
        "Id": "",
        "Scope": "",
        "AuthEndpoint": "",
        "TokenEndpoint": "",
        "UserApiEndpoint": ""
    }
}

su mattermost
bash-4.1$ ./platform
[01/19/16 16:41:57] [INFO] Current version is 1.3.0 (4896/Mon Dec 14 23:57:09 UTC 2015/f51d45f6cba0e5a1249146afe4a1c78cf32b7598)
[01/19/16 16:41:57] [INFO] Current working directory is /opt/mattermost/bin
[01/19/16 16:41:57] [INFO] Loaded config file from /opt/mattermost/config/config.json
[01/19/16 16:41:57] [INFO] Server is initializing...
[01/19/16 16:41:57] [INFO] Pinging sql master database
[01/19/16 16:41:57] [CRIT] Failed to ping db err:pq: SSL is not enabled on the server
panic: Failed to open sql connection pq: SSL is not enabled on the server

goroutine 1 [running]:
github.com/mattermost/platform/store.setupConnection(0xbfe2e8, 0x6, 0xc8201be080, 0x8, 0xc8200dfa40, 0x62, 0xa, 0xa, 0xc82001cb00, 0x0)
	/go/src/github.com/mattermost/platform/store/sql_store.go:180 +0x5be
github.com/mattermost/platform/store.NewSqlStore(0x0, 0x0)
	/go/src/github.com/mattermost/platform/store/sql_store.go:59 +0x11c
github.com/mattermost/platform/api.NewServer()
	/go/src/github.com/mattermost/platform/api/server.go:31 +0xb5
main.main()
	/go/src/github.com/mattermost/platform/mattermost.go:57 +0x567

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [chan receive]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc82001cb40, 0x7ff88b6ec1e8, 0xc82002a010)
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:27 +0x80
created by code.google.com/p/log4go.NewConsoleLogWriter
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:19 +0x6e

goroutine 8 [select]:
code.google.com/p/log4go.NewFileLogWriter.func1(0xc8200727e0)
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/filelog.go:84 +0xabc
created by code.google.com/p/log4go.NewFileLogWriter
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/filelog.go:116 +0x380

goroutine 9 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820125a40)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

**Comment by coreyhulen** [comment]
Guessing, but maybe your db name of `Hokett2105#` is messing up the connection string because it looks like it's ignoring `sslmode=disable`

example of property
`"DataSource": "postgres://mmuser:mmuser_password@10.10.10.1:5432/mattermost?sslmode=disable&connect_timeout=10"`

**Comment by it33** [comment]
Thanks @mcobb2105 for your question, 

Because this seems to be more a troubleshooting discussion than a product defect, could we have your help posting this to the [Troubleshooting Forum](http://www.mattermost.org/troubleshoot/)? 

Please include repro steps, so members from the community will better be able to help solve your issue. Please add a link back to your new post from this ticket and close this ticket so it’s easier to keep track of issues?

**Comment by gabx** [comment]
Same issue here, and can't find in the Forum any follow up.

**Comment by fangying** [comment]
I followed the tutorial on https://docs.mattermost.com/install/prod-rhel-7.html
however I got the error msg, I still cannot figure it out.
[CRIT] Failed to ping db err:pq: SSL is not enabled on the server

**Comment by f0o** [comment]
Same here, I'd say it's a product defect.

```
[2017/03/22 17:00:07 UTC] [INFO] Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
[2017/03/22 17:00:07 UTC] [INFO] Current version is 3.7.0 (3.7.2/Fri Mar 17 19:07:10 UTC 2017/f4473cf312d09a53a57312745963aee334e251cb/c737afff891a25ee3b011c0d4b1392adc3dcc622)
[2017/03/22 17:00:07 UTC] [INFO] Enterprise Enabled: true
[2017/03/22 17:00:07 UTC] [INFO] Current working directory is /opt/mattermost/bin
[2017/03/22 17:00:07 UTC] [INFO] Loaded config file from /opt/mattermost/config/config.json
[2017/03/22 17:00:07 UTC] [INFO] Server is initializing...
[2017/03/22 17:00:07 UTC] [INFO] Pinging SQL master database
[2017/03/22 17:00:07 UTC] [CRIT] Failed to ping DB err:pq: SSL is not enabled on the server
```

**Comment by f0o** [comment]
Turns out having authnetication to ident for local connections is wrong, however documentation said it should be fine.

Anyways, trashed the ident and replaced it with md5 for localhost and it works fine
