### ISSUE TITLE
When packages are lost, no recovery happens

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#1928]
Parts of the log randomly miss out when reloading, if your server's package loss is high enough. I figured out the problem was because no proper recovery of package loss happens. No confirmation signal is sent back.

**Comment by it33** [comment]
Thanks @Ticki! Highly appreciate the report, 

Can you let us know if you're still seeing this on Mattermost 2.0? 

I thought this was fixed, per #1906 discussion

**Comment by lfbrock** [comment]
Closing this issue, @Ticki if it's still happening please re-open?

**Comment by Ticki** [comment]
It seem to be gone. I'll let you know if it happens again.

**Comment by Ticki** [comment]
This happens again, after updating to 2.1.0.

**Comment by enahum** [comment]
I think the problem here is in the `SocketStore initialize method` cause it return is `UserStore.getCurrentId()` is not set which in fact is the case, maybe running `initialize` on UserStore change is emitted on RECEIVE_ME?
