### ISSUE TITLE
missing part in ubuntu production dokumentation

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1941]
Step 12 of "Set up Database Server" is not working. Server needs at least a reboot to get the following step 13 to work. Issue reproduced several times with the same result.
Therefore I would suggest to add another step between Step 12 and 13 that explains the server to reboot using command "sudo reboot".

**Comment by it33** [comment]
This shouldn't require a reboot, if your issue persists, please see mattermost.org/troubleshooting

**Comment by finius** [comment]
Well, i did it several times and it always had to reboot to get to work. but anyway, may this be yet a hint for all those who are using GUI on ubuntu 14.04 lts (ubuntu-desktop) while setting up mattermost
