### ISSUE TITLE
website tells websocket port problem and "Mattermost unreachable" after fresh install, but in fact it is usable

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1942]
The website tells me with a blue ribbon on top of the page, that I should check connection because Mattermost would be unreachable. In fact I seem to be able to browse the whole page and use it normally. Is the error message a fault or a real problem. If it is, how can it be solved, because the seems to find nothing in the production documentation about this behaviour.

**Comment by it33** [comment]
Please see [troubleshooting guide](http://docs.mattermost.com/install/troubleshooting.html?highlight=unreachable#please-check-connection-mattermost-unreachable-if-issue-persists-ask-administrator-to-check-websocket-port). If your problem persists move to troubleshooting forum per mattermost.org/troubleshooting

**Comment by hsali** [comment]
will you give me simple javascript code to connect with mattermost.
