### ISSUE TITLE
iOS App: no auto scrolling of the chat history inside the channel (new posts aren't visible without scrolling)

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1943]
When having a channel open and recieving/sending a new post, this new post is inserted below the textbox. So it is unreadable/unseeable without scrolling the screen. With every new post one has to scroll to read the new entries (even the own), because it's inserted below the TextBox. 
One could say, that no auto scrolling of the chat history is currently available which is very hard in longer conversations on the mobile.

**Comment by fjarlq** [comment]
This issue might belong over on https://github.com/mattermost/ios

**Comment by finius** [comment]
moved:
https://github.com/mattermost/ios/issues/5
