### ISSUE TITLE
Website: recurring blue info ribbons pretend one over and over again to see the website details beyond it

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1944]
I would appreciate if the blue ribbon would be inserted if needed as a "first row/line" above (on top of) the website itself and not overlayed over the actual website. It's very annoying to have to always click away the reoccuring blue ribbon to completely see the important things on the website like "Search", channel name, etc.

**Comment by lfbrock** [comment]
We tried it like this previously but there were some issues on mobile and with the text input box being pushed off the screen.
