### ISSUE TITLE
Improovement: System Admin should be able to force displaying of users real name (prename and surname! not nickname or username!)

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1945]
In some environments it would be very usefull for the participants to be able to identify a user. This is not necessarily the case, if nicknames (or even usernames) are choosed to be displayed by the users. 
Therefore an administrator should be able to force the displayed name to display the prename and surname within the chat history window to minimize an users anonymity. This may be also related to a forced disclosure of prename and surname during the registration process.

**Comment by GhostLyrics** [comment]
I would welcome this preference for our installation.

**Comment by it33** [comment]
Thanks @finius, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? 

   Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?

**Comment by finius** [comment]
@it33 would very appreciate if this Feature could be priorized! Same for this issue: 
https://github.com/mattermost/platform/issues/2196#issuecomment-186365568

**Comment by finius** [comment]
http://mattermost.uservoice.com/forums/306457-general/suggestions/12432408-system-admin-should-be-able-to-force-displaying-of
