### ISSUE TITLE
Unable to remove failed message retry notification

### ISSUE THREAD

**Issue by alsoscotland** [mattermost/platform#1957]
When a message send fails (when offline as an example) the UI presents a notification that allows you to retry sending...
In my case, the message is now irrelevant and I do not wish to send it.

-This notification is always pushed just above the message input field (i.e. the position of the most recent message)
-The user is not given the ability to remove the retry notification. 

Could you possibly do one of two things?
- make the retry notification appear in a natural time sort order so it scrolls away over time
or
- give an option for removal

**Comment by alsoscotland** [comment]
Just FYI:
I get a SSL cert error (NET::ERR_CERT_AUTHORITY_INVALID) from the online form URL (https://spinpunch.wufoo.com/forms/r3z8zqm0ew6pcc)

**Comment by lfbrock** [comment]
Hi @alsoscotland, 

Here's a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1042) to add the ability to remove a message that failed to send.
