### ISSUE TITLE
Mattermost Integration with Phabricator

### ISSUE THREAD

**Issue by usmanarif** [mattermost/platform#1973]
I am trying to integrate Mattermost with Phabricator but even after googling it for hours, I have not get any documentation regarding that. Is it possible to integrate Phabricator with Mattermost? If so then is there any link present by using which I can start? 
I've found that Slack do support Phabricator and integration of Phabricator with Slack is possible.  Please check the below link:
https://github.com/maiki/ph-slack

Can this be done for the Mattermost as well?

**Comment by lfbrock** [comment]
I don't think anyone has built an integration for Phabricator yet (you can check the [Community Applications page](http://www.mattermost.org/community-applications/) for a list of integrations). I suggest contributing a [feature request](http://www.mattermost.org/feature-requests/) for it.

**Comment by rompic** [comment]
you could integrate it via hubot

**Comment by it33** [comment]
Thanks @usmanarif, appreciate your feedback, 

You should be able to adapt either the https://github.com/maiki/ph-slack integration you mentioned or one of the Mattermost Hubot clients to integrate with Mattermost, here's [docs on the Slack-compatible Mattermost API options.](http://docs.mattermost.com/developer/api.html) 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?
