### ISSUE TITLE
Configuration lost after gitlab update

### ISSUE THREAD

**Issue by ralgozino** [mattermost/platform#1975]
Hello,

 I've expirienced in the 3 last updates of gitlab-omnibus that after updating the gitlab version, the mattermost config is lost, and I have to re-edit the config.json file; for example we are using https for gitlab and I can't login.

Mattermost is looking great by the way!

Cheers!

**Comment by it33** [comment]
Here's [documentation on GitLab Mattermost upgrades to start](http://docs.mattermost.com/integrations/gitlab.html#upgrading-gitlab-mattermost), if you're still having issues, could we have your help posting repro steps to [troubleshooting forum?](https://forum.mattermost.org/t/how-to-use-the-troubleshooting-forum/150)

**Comment by ralgozino** [comment]
Hello!

My gitlab.rb was lacking all the comments with the mattermost example parameters. Using https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template I was able to setup in the gitlab.rb all the parameters I manually edited in the config.json.

I think this issues can be closed now.

Thanks!!
