### ISSUE TITLE
profile image UI can be improved a bit

### ISSUE THREAD

**Issue by Pomax** [mattermost/platform#1981]
Currently you have to click a button in order to select and image, and it has to be a rectangular image already. Instead, it makes sense to do things more like twitter or flickr, where you can either click-to-browse or just drag-and-drop an image onto the UI, and then the UI gives you the option to crop and scale, so you can pick any image and then just select the rectangular subsection you want to have act as your profile picture.

**Comment by it33** [comment]
Thanks @Pomax, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?

**Comment by Pomax** [comment]
http://mattermost.uservoice.com/forums/306457-general/suggestions/12418980-improve-profile-images-by-offering-arbitrary-size
