### ISSUE TITLE
way to turn off emoticons?

### ISSUE THREAD

**Issue by Pomax** [mattermost/platform#1982]
Skype etc. allow you to turn off emoticons, so that you get the raw text input instead of the converted smiley face. Not everyone appreciated chat filled with emoji, so it'd be a nice feature to have emoticon rendering a setting people can turn on or off

**Comment by it33** [comment]
Thanks @Pomax, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?

**Comment by Pomax** [comment]
http://mattermost.uservoice.com/forums/306457-general/suggestions/12419022-way-to-turn-off-emoticons

**Comment by szi-secunet** [comment]
This is so silly: https://imgur.com/gallery/EYn5ZUs

**Comment by stefanct** [comment]
Actually, this is not a feature request but a bug report. This autoconversion mangles messages that are not meant to be smileys etc. (and of course it is additionally just annoying for some users even if the autoconversion is "correct" but that's not the point, really. It is also a rather small change. Please open this up again and state if you would accept patches dealing with it.

**Comment by Pomax** [comment]
A few years later, but let me just add that even back when I filed this, this basically turned into "go post it somewhere that we're not going to ever look at so you feel like you're helping but really we just don't care and this will let us never have to look at it again".

So five years on, hopefully that changed.

Having said that, commenting on a closed issue is never a good plan, just file a new issue and crosslink to the old one (@szi-secunet. @stefanct, anyone else tempted to reply to this issue). Unless an issue is actively worked on a PR that closes it turns out to break prod, requiring rolling back, closed issues don't get reopened. New issues is where the power of engagement is.
