### ISSUE TITLE
allow per-user settings for showing links inline or not, ideally per content type

### ISSUE THREAD

**Issue by Pomax** [mattermost/platform#1983]
While it can be nice to have links to images, youtube videos, etc. that display inline autoexpand to the media that they link to, it would be extremely useful to have a way to turn that off, so that you just get a link instead of losing a massive amount of chat because of the inline media block.

**Comment by it33** [comment]
Thanks @Pomax, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?

**Comment by Pomax** [comment]
http://mattermost.uservoice.com/forums/306457-general/suggestions/12418995-allow-per-user-settings-for-showing-links-inline-o
