### ISSUE TITLE
[Help wanted] Brazilian Portuguese (pt_BR) translation and review

### ISSUE THREAD

**Issue by renannprado** [mattermost/platform#1994]
Just let me know through this issue. I'll be happy to help. :)

**Comment by it33** [comment]
Hi @renannprado, 

Highly appreciate your offer to help, 

We would need at least two volunteers from the Brazilian Portuguese-speaking Mattermost community to help review and collaborate on finding the most accurate translations in the PR, 

Any volunteers?

**Comment by rodrigocorsi2** [comment]
I'll be happy to help too.

**Comment by it33** [comment]
Highly appreciate the offers to help, the last of the Spanish language translation is finishing up and we're working on defining an appropriate translation review process for additional languages. Will circle back on this.

**Comment by it33** [comment]
We now have [a draft of proposed localization process](http://docs.mattermost.com/developer/localization.html) to create the initial pull request and to help test, review and improve translations prior to merging. 

Very open to feedback, the goal is to balance moving quickly and having high quality translations.

**Comment by leandrosferreira** [comment]
Hello @renannprado and @rodrigocorsi2 , are you working on that?

**Comment by rodrigocorsi2** [comment]
Oi @leandrosferreira, a tradução está completa você já pode usar na versão 2.1, mas é sempre bom alguém para ajudar na revisão e em novas frases. Estamos com um servidor temporário de tradução em http://186.202.167.109/projects/
Também existe um [canal para tradução](https://pre-release.mattermost.com/core/channels/localization)

**Comment by leandrosferreira** [comment]
Opa @rodrigocorsi2 vou verificar ambos e ver no que consigo ajudar ;)

**Comment by renannprado** [comment]
@rodrigocorsi2, @leandrosferreira and @it33 I'm sorry but I currently don't have the time help translating. Maybe I'll help to validate the translation later on.

**Comment by jasonblais** [comment]
Thank you everyone for the wonderful work!

Brazilian Portuguese was released earlier this year, and promoted from Beta to an official translation [in our August release](https://docs.mattermost.com/administration/changelog.html#languages).

Big thank you to @rodrigocorsi2 who is reviewing new and updated strings as new features are added to Mattermost over time.

If anyone else would like to help maintain the translations, please let us know on our [Brazilian Portuguese community channel](https://pre-release.mattermost.com/core/channels/i18n-portuguese) and join the [Mattermost Translation Server](http://translate.mattermost.com/pt_BR/mattermost/) to contribute.

**Comment by andremillet** [comment]
I can help too !
