### ISSUE TITLE
Support for Alpine Linux

### ISSUE THREAD

**Issue by JasonSwindle** [mattermost/platform#2000]
Howdy,

At the moment, MatterMost will not work on Alpine linux do to the way the Go is complied at the moment.

```bash
/mattermost/bin/platform: line 1: ELF: not found
/mattermost/bin/platform: line 2: syntax error: unexpected "("
```

and the dev version

```bash
platform: line 1: ELF: not found
platform: line 2: G: not found
platform: line 2: @#
                    @@@@@00��@�@��@�@88@@@@@�Lf�LfPfP�P�8�[8�[�:Q�t�e: not found
platform: line 2: ]: not found
platform: line 3: : not found
platform: line 4: syntax error: unexpected "("
~/bin $ platform: line 2: : not found
platform: line 2: : not found
platform: line 2: can't open O�Ⱒ�Y�?�?�c�?�?���: no such file
platform: line 2: fu: not found
```

It would be really awesome for MatterMost to support Alpine as it would allow the Docker container to come down in size greatly (216.2 MB for my current version). I'm currently re-working the Dockerfile[1] but this is a road-blocker for me as well. Unless I am just missing some package(s) that I need to install, but I cannot makes heads or tails of the error.

[1] https://gist.github.com/JasonSwindle/f610ea4cf18da1d300ae

**Comment by JasonSwindle** [comment]
Fast followup, I see platform needs:

```
	/lib64/ld-linux-x86-64.so.2 (0x55968a71b000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x55968a71b000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x55968a71b000)
```

**Comment by ipedrazas** [comment]
@JasonSwindle have you tried to build mattermost youself?

**Comment by JasonSwindle** [comment]
I have not personally tried to build MatterMost to support http://www.musl-libc.org/ , but I do need to look into it. I've gotten MatterMost into a `91.38 MB` container, and I still think I can get it smaller.

**Comment by JasonSwindle** [comment]
@ipedrazas 

I see you have a MatteMost Docker repo. I plan on doing a PR on this:

https://gist.github.com/JasonSwindle/f610ea4cf18da1d300ae

once Alpine is supported, and I work out a bit more of the logic. So far the total size is `91.38MB`. My overall goal is to have this container just have MatterMost, and leave the database part out. Let's join forces on this if you wish.

**Comment by ipedrazas** [comment]
:+1: I have to run Mattermost in Kubernetes, so small and different images are a must :)

**Comment by it33** [comment]
Thanks @JasonSwindle, @ipedrazas, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? 

2. Posting a link back from the feature idea forum to this thread?
