### ISSUE TITLE
Bug: Searching for variations of http:// can returns inconsistent results

### ISSUE THREAD

**Issue by ptersilie** [mattermost/platform#2012]
I was trying to search a url someone posted. However, when I search for `http://` Mattermost throws and error: `We encountered an error while searching for posts`.

Searching for `http` works, however the result doesn't list any links. For example searching for `http*` shows the sentence "Try using https to access the website" but not "Have you checked out https://github.com ?".

**Comment by it33** [comment]
@esethna, can we have your help adding this as a test case and filing a Jira ticket on the expected behavior?

**Comment by ptersilie** [comment]
I did some further testing and the problem essentially boils down to the search not returning partial matches. E.g. when I search for "diff" it won't return messages that contain "difference".

**Comment by esethna** [comment]
Thanks @ptersilie, are you using a postgres database? There is a known issue where wildcard searches on postgres databases do not return consistent results. You can track the ticket in Jira [here](https://mattermost.atlassian.net/browse/PLT-1687).

**Comment by ptersilie** [comment]
@esethna Yes. I am using a postgres database. Is this really a postgres problem then? So are other databases not affected by this?

**Comment by esethna** [comment]
@ptersilie In our tests it was only postgres databases that were affected. Thanks for reporting, I'm going to close this issue and it can be [tracked in JIRA](https://mattermost.atlassian.net/browse/PLT-1687).
