### ISSUE TITLE
Improve logging: print the path being created on fail

### ISSUE THREAD

**Issue by DmitryKuzmenko** [mattermost/platform#2019]
I run mattermost on Arch and found that it's unable to upload images. The log file contains this:
```
[2016/01/29 13:19:05 MSK] [EROR] /api/v1/users/epy6n5nzejdwfyd3wte5ufxixr/image:writeFile code=500 rid=cwszkf5b77gnjrqfa38cxhk6yw uid=epy6n5nzejdwfyd3wte5ufxixr ip=192.168.55.233 Encountered an error creating the directory for the new file [details: mkdir data: permission denied]
```
As you can see the message doesn't describe what dir I should allow it to write into.

**Comment by it33** [comment]
The path is printed `data` it's just not the full path, would anyone interested in helping improve this?

**Comment by it33** [comment]
[Adding Jira ticket to track this improvement](https://mattermost.atlassian.net/browse/PLT-2061)

**Comment by DmitryKuzmenko** [comment]
Sorry for long silence.
@it33 isn't it possible to just make something like this:
1. Make the message parametrized:
```go
  {
    "id": "api.file.write_file_locally.create_dir.app_error",
    "translation": "Encountered an error creating the directory '%s' for the new file"
  },
```
2. Print the full path with filepath.Abs()
```go
return model.NewLocAppError("writeFile", "api.file.write_file_locally.create_dir.app_error", filepath.Abs(path), err.Error())
```

**Comment by it33** [comment]
Thanks @DmitryKuzmenko, make sense, [would you be open to making a PR to add this?](http://docs.mattermost.com/developer/contribution-guide.html)

**Comment by DmitryKuzmenko** [comment]
No problem if I'll find a time. =)
