### ISSUE TITLE
[Help wanted] French (fr) translation and review

### ISSUE THREAD

**Issue by Shadosky** [mattermost/platform#2021]
Hi, first of all, great job on Mattermost, it appears to be a really helpful tool for all my team.

I saw some recent change to improve international translation so i've made a first draft for the french version.

Do you want me to open a pull request for adding the fr.json file? If not, i can just upload the file here in the next comment.

**Comment by it33** [comment]
Hi @Shadosky, 

Highly appreciate your offer to help, 

We would need at least two volunteers from the French-speaking Mattermost community to help review and collaborate on finding the most accurate translations in the PR, 

Any volunteers?

**Comment by kernicPanel** [comment]
I'll be glad to help on this :)

**Comment by clorichel** [comment]
Helping Mattermost just speaking french ? I'm in !

**Comment by it33** [comment]
Highly appreciate the offers to help, the last of the Spanish language translation is finishing up and we're working on defining an appropriate translation review process for additional languages. Will circle back on this.

**Comment by jlebleu** [comment]
Hello I can help too

**Comment by it33** [comment]
We now have [a draft of proposed localization process](http://docs.mattermost.com/developer/localization.html) to create the initial pull request and to help test, review and improve translations prior to merging. 

Very open to feedback, the goal is to balance moving quickly and having high quality translations.

**Comment by tbolon** [comment]
Hi, I am available to contribute, if necessary. I can setup the necessary repository and branches too.

@Shadosky do you have any fork we could contribute to ? Do you want me to create one ?

**Comment by Shadosky** [comment]
@tbolon i will try to push my work tomorow morning, feel free to create a repo if you want to manage it and i would open a merge request on it

**Comment by tbolon** [comment]
I have created [a fork with a translation-fr branch](https://github.com/tbolon/platform/tree/translation-fr). Feel free to submit a PR against it. I will certainly start my work based on yours.

**Comment by jblobel** [comment]
Hi everyone,
I would love to help with the translation.

**Comment by patoupatou** [comment]
@tbolon I submitted a PR on your branch, feel free to comment on it if there are some corrections you aren't sure of!

**Comment by it33** [comment]
Hi everyone, 

1. if this is your first time contributing, please do complete the [Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/) when you contribute to the branch that is eventually going to be checked in. Your GitHub username will be listed as an [approved contributor](https://docs.google.com/spreadsheets/u/1/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true).  

2. @tbolon, when you make your PR, please include the GitHub usernames of everyone who contributed so we can make sure to credit everyone's work? 

Thanks to everyone for your work here, very excited to see this working soon!

**Comment by tbolon** [comment]
Thanks @patoupatou, I have merged your PR. I also have some commits waiting for being pushed.

I have completed the CA, and will make sure all GitHub usernames are included with my PR.

**Comment by tbolon** [comment]
Sorry @patoupatou , I have merged you PR against the wrong branch master. I have reverted the PR then manually merged your commit into the transaction-fr branch. Feel free to continue submitting PR against my fork.

**Comment by tbolon** [comment]
@it33 should I submit a PR with the current state of the work, or you prefer to wait for something more polished ?

**Comment by tbolon** [comment]
I have started creating a new web/static/i18n/fr.json file. I will use [issues on my fork](https://github.com/tbolon/platform/issues) to help tracking progress.

**Comment by it33** [comment]
Thanks @tbolon, I'd propose waiting until the contributors on this thread feel that the translations is complete (ideally at the [beta quality bar](http://docs.mattermost.com/developer/localization.html#beta) and it can be added in a single PR?

**Comment by patoupatou** [comment]
@tbolon np and thank you!

I just signed the CA. I agree with waiting for more contributions from people in this thread :)

**Comment by pjgrizel** [comment]
Hi, I'm willing to help on the french translation.

**Comment by patoupatou** [comment]
I think the current course of action is to work on @tbolon's fork and submit PR's on his branch until we consider it to be releasable? If you want to help @pjgrizel you can start by reviewing what has been done so far in the fr.json file. It's pretty big though and I'm sure we could use more reviewers on this one.

**Comment by tbolon** [comment]
Yes, the main task for now is to help translate web/static/i18n/en.json : https://github.com/tbolon/platform/issues/3

You should fork my repository, then submit a PR against branch translation-fr (it will be automatically suggested by GitHub).

When this issue is closed, we will just have to handle all changes until now, then submit a PR against the main project.

**Comment by pjgrizel** [comment]
Thanks for your replies!
So from what I undestand, you guys do not use Mattermost' Pootle server?
French buddies, can we get in touch in https://pre-release.mattermost.com/core ? I've created a French Translation channel so we can talk about it. Thanks a lot!

**Comment by tbolon** [comment]
It seems that a [dedicated tool](http://186.202.167.109/fr/) has been deployed to group all translation efforts. Every newcomer should use this tool instead of my fork to contribute on the translation.

I am waiting for an official contributor from mattermost which could confirm this

**Comment by it33** [comment]
@tbolon that's correct, please join the [localization channel](https://pre-release.mattermost.com/core/channels/localization) to interact with the rest of the localization community and ask questions. 

I apologize, this link was in the documentation I initially sent, but I should have emphasized it. Also, we should probably update the documentation to include the new translation server...

**Comment by tbolon** [comment]
As suggested by @pjgrizel, people who wants to help or ask a question should join the [French Translation Room](https://pre-release.mattermost.com/core/channels/french-translation#).

**Comment by tbolon** [comment]
Just to mention that the initial PR #2536 has been merged. So it seems this issue could be closed when the next version will be released.

**Comment by lfbrock** [comment]
Closing this issue, French translation is available in v2.2. 

Anyone interested in helping keep French translations up to date in future releases can join the "French Localization" channel on our [pre-release site](https://pre-release.mattermost.com/core).
