### ISSUE TITLE
Pinned messages & files

### ISSUE THREAD

**Issue by GeekRapper** [mattermost/platform#2032]
I'd like to see pinned messages,
Like in the thing called Slack.
It should be coded pretty well,
And not done via a dirty hack.

Files also should be pinnable,
In the same kind of way.
And when a user scrolls their page,
In the right sidebar they should stay.

I've included a link all about,
Slack's own implementation.
You could use this to help test,
With your 'User Story' narration.

https://get.slack.help/hc/en-us/articles/205239997-Pinning-messages-and-files

Slack imposes a limit,
Of 100 pinned items per channel.
Perhaps this could be configurable,
Via the Mattermost control panel?

I hope this issue is all fine,
But if you need more information.
Pop me a message and I'll reply,
When I get back to my workstation.

**Comment by it33** [comment]
Thank you for the ticket
Many share your high hopes
[Pins request is duplicate](http://mattermost.uservoice.com/forums/306457-general/suggestions/10461081-pinned-posts)
Help us with an upvote?

**Comment by Jordan4385** [comment]
Also There should be an an option in the incoming web hook JSON to pin the message.
