### ISSUE TITLE
Cannot search CJK contents

### ISSUE THREAD

**Issue by evannook** [mattermost/platform#2033]
Hi,

I've downloaded docker image mattermost/platform:latest and ran it for testing purpose, and found that the current version of mattermost cannot search CJK contents.
![2016-02-01 09 07 22](https://cloud.githubusercontent.com/assets/7614738/12706633/17daf5da-c8c4-11e5-9ec3-33f7c7f08f8f.png)
![2016-02-01 09 07 43](https://cloud.githubusercontent.com/assets/7614738/12706634/17de2d72-c8c4-11e5-872f-867b9df97c99.png)

**Comment by it33** [comment]
Please try adding * after your search term and use at least 3 characters? Full text search in your database setup is probably set to English, there would probably need a setting for CJK, if anyone on the community has guidance it would be highly appreciated

**Comment by evannook** [comment]
I've found related discussions here: https://forum.mattermost.org/t/supporting-full-text-for-japanese-and-other-idiographic-languages/779

I'm willing to help solving this issue.

**Comment by it33** [comment]
Fantastic! We're open to ideas, which approach do you feel might be best?

**Comment by evannook** [comment]
IMHO, it's better if we can handle this issue in database layer. According to http://dev.mysql.com/doc/refman/5.7/en/fulltext-search.html, MySQL 5.7+ has built-in CJK full text search capability that can solve the issue. Keep to find out how to gracefully solve this issue with PostgreSQL...

**Comment by it33** [comment]
Hi @evannook, would you be open to testing the instructions and reporting back if they work? 

If so, they could be added to Mattermost documentation to help other CJK users

**Comment by it33** [comment]
Sorry, hit the wrong button, didn't meant to close,

**Comment by artiya4u** [comment]
I have a workaround with MySql 5.7, using full text index with ngram parser.
`DROP INDEX idx_posts_message_txt ON Posts;`
`CREATE FULLTEXT INDEX idx_posts_message_txt ON Posts (Message) WITH PARSER ngram;`

For more information see MySql document:
[ngram Full-Text Parser](https://dev.mysql.com/doc/refman/5.7/en/fulltext-search-ngram.html)

**Comment by it33** [comment]
Thanks @artiya4u! 

Really helpful, can anyone in the community verify this approach? 

If so, would love to add it to the documentation--and if anyone knows the equivalent for Postgres, please share as well?

**Comment by seikichi** [comment]
I tried the ngram parser approach. It works fine! Thanks @artiya4u! 

I uploaded the docker image to DockerHub, so you can try by the following command:

```bash
docker run --name mattermost-cjk -d --publish 8065:80 seikichi/mattermost
```

If you interested the Dockerfile see [this commit](https://github.com/seikichi/platform/commit/18c7656e99a5b69530e4ec9a9fff4e48ca16e036).

**Comment by it33** [comment]
Thanks to everyone for helping solve this issue with CJK search. A note has been added to the [database requirements documentation](http://docs.mattermost.com/install/requirements.html#database-software) referencing ngram parsing and this thread. 

Closing this thread for now. Please file a new issue if there's any further issue with CJK search.

**Comment by evannook** [comment]
Sorry for being so late, the solution provided by @artiya4u works for me, thank you all. :D

**Comment by schemacs** [comment]
Is there any way to do search CJK on PostgreSQL? Or any help on migration PostgreSQL database to MySQL?

**Comment by schemacs** [comment]
Found [the way to keep dancing on PostgreSQL](/mattermost/docs/pull/95).

**Comment by accordtsai** [comment]
I confirm the solution proposed by @artiya4u works on Mattermost 3.5 and MySQL 5.7 community for searching Tradiational Chinese characters.

Is it possible to include this as the default Mattermost behaviour (i.e. using the ngram parser if mysql 5.7+ is detected?)

**Comment by it33** [comment]
Hi @accordtsai, not sure, we're not really experts. Is this something you'd be interested in contributing to the community?

**Comment by rock0018** [comment]
@artiya4u ,search simple chinese  phase with mysql.5.7.16    also work .thanks a lot

**Comment by Sharuru** [comment]
Up vote for this, I think CJK text search issue should be considered for those PostgreSQL users while Mattermost is being used by more and more people nowadays. 😃

**Comment by intdev32** [comment]
> I tried the ngram parser approach. It works fine! Thanks @artiya4u!
> 
> I uploaded the docker image to DockerHub, so you can try by the following command:
> 
> ```shell
> docker run --name mattermost-cjk -d --publish 8065:80 seikichi/mattermost
> ```
> 
> If you interested the Dockerfile see [this commit](https://github.com/seikichi/platform/commit/18c7656e99a5b69530e4ec9a9fff4e48ca16e036).

Thank you!
I tried your image, and I confirmed Korean Full Text Search also works okay.

Now, I'll prepare MySQL-based MatterMost server environment.

**Comment by chendian520** [comment]
Hi, I am using mariaDB, not Mysql.   
This is the solution to Mysql :  DROP INDEX idx_posts_message_txt ON Posts;
CREATE FULLTEXT INDEX idx_posts_message_txt ON Posts (Message) WITH PARSER ngram;
But how to solve this problem when using mariaDB?   Does anyone has solved this problem?   Appreciate for your reply!
