### ISSUE TITLE
user should be able to define whether to send a message by just pushing ENTER or a <defined-key>+ENTER

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2036]
When writing a longer message in browser or desktop app, some users tend to push ENTER to do a wordwrap or to begin a new paragraph. Actually, in this cases, they accidently are sending their unfinisched message. It would be more appropriate if one could define if a message should be send by pushing ENTER or just to use ENTER for beginning a new paragraph. For this, a user should define a special key that is used to send messages in combination with ENTER instead if simply use ENTER to send a message.

**Comment by hmhealey** [comment]
Hi @finius, @florianorben actually added that feature for us a while ago. It's a bit hidden, but it's available under the Advanced Settings tab in the Account Settings menu.
![image](https://cloud.githubusercontent.com/assets/3277310/12719768/28ace4ee-c8c5-11e5-9625-74440a68b2f2.png)
