### ISSUE TITLE
Unaligned user when typing @ in chat and having a zoom > 100%

### ISSUE THREAD

**Issue by vincent-lhote** [mattermost/platform#2058]
I’ve set the text larger in my browser (iceweasel), and when I type @ the list of user is not right aligned.

I expect the icons and text to be aligned, as when the zoom is at 100% or below.

![capture d ecran de 2016-02-03 14 51 40](https://cloud.githubusercontent.com/assets/6304302/12784228/1c12d2ee-ca86-11e5-914a-0c31e136cefb.png)

**Comment by it33** [comment]
Iceweasel is [not a supported web client](http://docs.mattermost.com/install/requirements.html#web-client). Propose filing an issue with Iceweasel if it's rendering differently than Chrome and Firefox, as the issue would happen on other web apps as well

**Comment by vincent-lhote** [comment]
Iceweasel is the non trade mark name used by debian for firefox.

**Comment by it33** [comment]
Ah, thanks, forgot, I think there was another issue reported on this. Appreciate your taking the time to report this, it's just that Iceweasel isn't a supported browser

**Comment by vincent-lhote** [comment]
I also have the issue in Firefox ESR 45.2.0.

**Comment by vincent-lhote** [comment]
Apparently firefox on linux, or debian are not supported either.
