### ISSUE TITLE
Bug: [...] and action buttons misformat on IE11

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2067]
When opening Mattermost in IE 11, the function links (the little blue arrow and "...") for each post are unclickable because they are only displayed as long as you mouseover a specific post, but the position ist below that post. So, if you try to move your mouse there, the mouseover for the underlying post activates and the funtion links of the former post disapper and the ones for the new one appear - but again above the next underlying post, and so on. So, you can't reach them... (see Image attached)
![unbenannt3](https://cloud.githubusercontent.com/assets/5287181/12814294/4270b5f6-cb3e-11e5-8c60-5f366b063f19.jpg)

**Comment by it33** [comment]
Thanks @finius, confirmed, this is an issue on master, appreciate the report! 

![image](https://cloud.githubusercontent.com/assets/177788/12819436/ff94ccdc-cb0f-11e5-8de1-2ed17d4f165f.png)

**Comment by hmhealey** [comment]
The Jira ticket for this is https://mattermost.atlassian.net/browse/PLT-1886 and it's been fixed by https://github.com/mattermost/platform/pull/2062
