### ISSUE TITLE
[Mail] Text Form Of Invite Mail Misses Invite Link

### ISSUE THREAD

**Issue by forelabs** [mattermost/platform#2110]
The text version of the invite mail does not have the invite link.
It is used in a button in the html version,
but the text version only shows the text on the button, not the link.

That's annoying for developers, who only use console mail applications ;)

**Comment by it33** [comment]
Thanks @forelabs, appreciate the report? 

Anyone in community interested in helping with a pull request here?

**Comment by enahum** [comment]
@it33 a fix for this has been merged if i'm not mistaken.

**Comment by it33** [comment]
[Created a ticket to track this, would welcome a pull request to fix](https://mattermost.atlassian.net/browse/PLT-2055)
