### ISSUE TITLE
New messages not showing up in Safari on Mac

### ISSUE THREAD

**Issue by zzt4** [mattermost/platform#2124]
New messages are not showing up in Safari in channels or DM's until the website is refreshed, or I send a message in a channel or DM. Opened the developer console to see the following errors in the screenshot attached. This does not happen in Google Chrome. Using Mac OS X 10.11.3 and Safari 9.0.3. This also affects Safari on iOS, and also affects the Mattermost iOS client, as that uses a WebView.
<img width="863" alt="screen shot 2016-02-09 at 3 20 37 pm" src="https://cloud.githubusercontent.com/assets/805259/12930975/0868a470-cf41-11e5-860b-989a352d843f.png">

**Comment by remotevision** [comment]
:+1:

**Comment by geekytime** [comment]
It looks like this may also be a problem with the webview on the iOS client, at least for some of our users.

**Comment by it33** [comment]
Thanks @zzt4, @remotevision, @geekytime can we ask your help to see if this repros with Mattermost 2.0?

**Comment by remotevision** [comment]
@it33 absolutely.

**Comment by it33** [comment]
We're not able to repro this on master, changes went in to Mattermost 2.0 that may have fixed this. Asking help from community to open a new issue with repro steps of this still happens on Mattermost 2.0 and later?

**Comment by it33** [comment]
@remotevision, just to check, did you mean it repros or that you were going to confirm whether it would or not?
