### ISSUE TITLE
[Help wanted] Dutch (nl) translation and review 

### ISSUE THREAD

**Issue by woutervb** [mattermost/platform#2140]
Working on a Dutch (nl) translation on my own fork. If someone is interested in helping me, then I can push my Work in Progress to github.

**Comment by it33** [comment]
Thanks @woutervb! 

We now have [a draft of proposed localization process](http://docs.mattermost.com/developer/localization.html) to help test, review and improve translations prior to merging. 

Very open to feedback, the goal is to strike a balance between moving quickly and having high quality translations.

**Comment by it33** [comment]
Updating title so this issue is consistent with [other translation efforts](https://github.com/mattermost/platform/labels/Localization)

**Comment by wyleung** [comment]
(y) @woutervb I would like to help. Shall I fork from your repo?

**Comment by woutervb** [comment]
@wyleung I think that is the most convenient option. Please use the dedicated branch on my repo.

**Comment by remcoros** [comment]
After we upgrade to omnibus-gitlab 8.9 (which would include MM 3.1) next month, I plan on demo'íng mattermost in our organization.

I signed up on the translation server and started to contribute some translations. 

Any active dutch translaters still working on this?

**Comment by it33** [comment]
[terode](http://translate.mattermost.com/user/tetrode/) has [opened a channel for discussing Dutch translation](https://pre-release.mattermost.com/core/channels/i18n-dutch), but there hasn't been activity there so far. 

It looks like [Dutch is making good progress](http://translate.mattermost.com/nl/), just needs a little help: 

![image](https://cloud.githubusercontent.com/assets/177788/16084383/7b09eff8-32cd-11e6-8a25-69252f868804.png)

**Comment by wyleung** [comment]
@remcoros Not really, as I was away for a while. I'm actually surprised that a lot of translation was contributed already.

Should we coordinate on a integration check? E.g. certain translations are semantically okay, but don't fit in certain situations (modal windows, shorter text etc..)

**Comment by jasonblais** [comment]
Dutch was released [in our August release](https://docs.mattermost.com/administration/changelog.html#languages) - thank you everyone for the wonderful work!

Big thank you to @wyleung and @rononline who are reviewing new and updated strings as new features are added to Mattermost over time.

If anyone else would like to help maintain the translations, please let us know on our [Dutch community channel](https://pre-release.mattermost.com/core/channels/i18n-dutch) and join the [Mattermost Translation Server](http://translate.mattermost.com/nl/mattermost/) to contribute.
