### ISSUE TITLE
forum.mattermost.org - Forum Verification Failure

### ISSUE THREAD

**Issue by Beastie71** [mattermost/platform#2147]
When getting a verification email for a new login to your forum, you receive a link to your site.  The link is clickable and you are presented with a web page with a button to click to verify.  Upon clicking that button you are given a page with only the following:

['BAD CSRF']

And the account is still not validated.

I've tried to resend the verification email but it has the same code.

**Comment by lfbrock** [comment]
Hi @Beastie71, do you mean the forum at forum.mattermost.org? It seems to be working for me, can you try again and see if the issue is still there?

**Comment by Beastie71** [comment]
Yes sir, I do indeed.

Yeah I just clicked the link.  Got the page, and then click the button and got the same message

['BAD CSRF']

Not sure if its something with my specific verification link or what....

**Comment by it33** [comment]
Hi @Beastie71, appreciate your report, 

Just curious what email client, browser and operating system are you using? 

Also, is anyone else from the forum experiencing this?

**Comment by Beastie71** [comment]
Well taking your question I submitted another time via my phone and it
worked.   I had been using Windows 7 , 64bit and chrome.   It worked on my
nexus 6p using Chrome.

Thanks!

**Comment by it33** [comment]
Cool, thanks,

**Comment by chitter99** [comment]
I'm having the same problem.

**Comment by jasonblais** [comment]
What email client, browser and operating system are you using?

**Comment by chitter99** [comment]
@jasonblais I managed to create an account. I first tried it on google chrome v56.0.2924.87, didn't work. Same error message like Beastie71. Then a tried firefox and every thing worked like it should.

**Comment by jasonblais** [comment]
Thanks @chitter99 for reaching back, really helpful. I was able to reproduce it on Chrome as well.

We'll contact the vendor and get it sorted out. Glad you were able to sign up via firefox in the meantime.
