### ISSUE TITLE
Feature request: WebRTC audio&video chat

### ISSUE THREAD

**Issue by raduab** [mattermost/platform#2160]
Add the capability to direct call the users with WebRTC, similar to Firefox Hello service.

**Comment by enahum** [comment]
This feature would be awesome, also with support for creating a group call. no more hangouts, skype or whatever.

**Comment by ryanleesipes** [comment]
Agreed. This feature would be amazing for my team.

**Comment by it33** [comment]
Thanks @raduab, appreciate your feedback, and others on this thread 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?
