### ISSUE TITLE
Version 2.0 (jquery-1.11.1.min.js not found)

### ISSUE THREAD

**Issue by Kemyke** [mattermost/platform#2170]
Hey, i tried to install the new 2.0 version. I replaced the files with the new ones and after restarting mattermost and nginx i got the following errors. It is searching for js files on my server which are not exsit. Mattersmot tries to load: jquery-1.11.1.min.js, react-bootstrap-0.25.1.js

What can be the problem? Did i forget an upgrade step?

**Comment by it33** [comment]
Please post to http://www.mattermost.org/troubleshoot/ with repro steps? 

Did you use the compiled bits or compile from source? On what step of the upgrade instructions did you hit the error? Please post line from logs.
