### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by duncan-bayne** [mattermost/platform#2177]
I'd like to run Mattermost on a FreeBSD server, that is, without Docker or any of the Linux packages provided by the project.

The canonical way of doing this would be to create a [FreeBSD Port](https://www.freebsd.org/doc/en/books/porters-handbook/own-port.html), and then if it's of sufficient quality, [submitting it](https://www.freebsd.org/doc/en/books/porters-handbook/porting-submitting.html) for inclusion in the Ports tree.

I'd be happy to do this work (assuming I get the time!) but would like to check whether:

1. A FreeBSD port is not already in the pipeline for the project; no sense in duplicating work.
2. Anyone knows of any existing attempts to get Mattermost running on FreeBSD; it'd be good to see how other people have faired, problems they've encountered, etc.
3. There are any existing dependencies that might prevent a FreeBSD port; I know that Go is supported on FreeBSD but as a Go newbie I'm uncertain whether there are any showstoppers.

**Comment by it33** [comment]
Thanks @duncan-bayne, appreciate your feedback and offer to help, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? 

2. Posting a link back from the feature idea forum to this thread?

**Comment by tsgan** [comment]
http://mattermost.uservoice.com/forums/306457-general/suggestions/12413238-freebsd-support

**Comment by it33** [comment]
Thanks!
