### ISSUE TITLE
Invite link in README doesn't work

### ISSUE THREAD

**Issue by olalonde** [mattermost/platform#2178]
The [invite link](https://pre-release.mattermost.com/signup_user_complete/?id=rcgiyftm7jyrxnma1osd8zswby) in `README.md` for the daily builds server doesn't seem to work.

```
Mattermost needs your help:
We couldn't find the existing team
```

**Comment by it33** [comment]
Whoops! Thanks for the report, [fixed now](https://github.com/mattermost/platform/commit/3ef0f5ad37efbbbf6f6907b0b47fb8d8cffbbc6a)
