### ISSUE TITLE
Nickname autocompletion without the @ when pressing <tab>

### ISSUE THREAD

**Issue by patoupatou** [mattermost/platform#2185]
As long time irc users, that's one of the features our team miss a lot from irc. We really like mattermost but I feel like this could be a welcome addition.

We used Slack and Rocket.chat before and both supported this feature.

Thank you!

**Comment by it33** [comment]
Thanks @patoupatou, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?
