### ISSUE TITLE
Poor UX with OAuth SSO Integration, Public Team, and New User

### ISSUE THREAD

**Issue by AndrewFarley** [mattermost/platform#2187]
We're trying to gain corporate adoption of Gitlab and Mattermost, and we are struggling with the poor UX of first creating their account which should be fully automated but is not.  Since "Gitlab" is the account, and we're only using it for authentication purposes, a user doesn't inherently think they need to "create" an account on Mattermost.  Which really makes sense from a user POV when you think about it.  I realize from a systems point of view these are separate independent pieces of software, and have their own accounts.

We have setup Gitlab and Mattermost with a pre-created public team then disabled team creation.  User creation is of course still enabled.

First the user creates, or gets created an Gitlab account, which they are told also gives then a chat account, so they go to mattermost, and they see this screen.

![screen-shot-2016-02-18-at-12 07 33-pm 2](https://cloud.githubusercontent.com/assets/470163/13142074/1337f314-d63b-11e5-97fe-cfb2cde38516.png)

Our users, and even my first instinct, since I know this authenticates with Gitlab, is to press the huge obvious Gitlab button.  Which then leads to a poor error message...

![screen-shot-2016-02-18-at-12 07 57-pm 2](https://cloud.githubusercontent.com/assets/470163/13142101/3f847b86-d63b-11e5-8514-9ce61836ec3c.png)

At this point it should detect this user account hasn't been created and and will automatically be created and allow the user into the system immediately.  Or, worst-case, it should have a link on this page which says that you do not have an account, click here to create it and take you straight to creating an account.

Other similar SSO-based applications don't have two buttons on their site "Click here to login with facebook" and "Click here to create an account with facebook" and expect users know which one to click.  This is poor UX.  If there is some functional reason you aren't automatically creating an account, can you please make a config variable to satisfy this need?

**Comment by lfbrock** [comment]
Hi @AndrewFarley, 

That makes sense, made a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-2044) to create an account if someone hits the GitLab "Sign In" button and doesn't already have an account, instead of only allowing users to create an account through the "Create one now" link.

**Comment by AndrewFarley** [comment]
Thanks a lot, much appreciated @lfbrock we are really looking forward to this

**Comment by maximd** [comment]
+1!

**Comment by tpdownes** [comment]
:+1:

**Comment by remcoros** [comment]
Has this been fixed? Looking at https://github.com/mattermost/platform/pull/2669 it looks like the pull request was closed without merging.

If not fixed, can this issue be opened again?
