### ISSUE TITLE
"Or Create a Team" should not be displayed on root page when Team Creation is disabled

### ISSUE THREAD

**Issue by raduab** [mattermost/platform#2190]
On the login page, with the team creation disabled, beneath the team selection section, there is still a text displayed "Or Create a Team"

**Comment by lfbrock** [comment]
Thanks @raduab for the bug report, 

Can you help [add more information](http://www.mattermost.org/filing-issues/) so we can reproduce the issue?

**Comment by raduab** [comment]
When more than one team exist, which is displayed in the team directory, if you disable the team creation, when logging in the text "Or Create a Team" is still displayed. It shouldn't since the team creation is disabled. I have attached a screenshot.

![mattermost-bug](https://cloud.githubusercontent.com/assets/5840332/13160716/d9ca3b0c-d6a1-11e5-9163-22baa39eef15.png)

**Comment by it33** [comment]
Thanks! Repro confirmed. @lindy65, can we have your help adding a Jira ticket with proposed APR to address this?

**Comment by it33** [comment]
I just [opened a ticket to track this](https://mattermost.atlassian.net/browse/PLT-2062), @raduab thanks for the report!
