### ISSUE TITLE
Dead link in the readme.

### ISSUE THREAD

**Issue by timlyo** [mattermost/platform#2194]
The link in Readme.md on the line

> If you use Docker, you can install Mattermost in a single-container preview in one line.

Is leading to here `https://github.com/mattermost/platform/blob/master/doc/install/Docker-Single-Container.md#one-line-docker-install` which is giving me a 404.

**Comment by it33** [comment]
Thanks @timlyo! Here's the [link](http://docs.mattermost.com/install/docker-local-machine.html#one-line-docker-install), help us with a pull request to fix? If it's your first one for the project, [you get a mug](https://forum.mattermost.org/t/limited-edition-mattermost-mugs/143). :)

**Comment by timlyo** [comment]
Ok, pull request is submitted.

**Comment by it33** [comment]
https://github.com/mattermost/platform/pull/2198 merged, thanks @timlyo!
