### ISSUE TITLE
System Admin gets "Password Reset" option in System Console while LDAP is connected to Active Directory.

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2195]
Passwort resets to Active Directory accounts won't be possible. Therefore the app gives a "Cannot reset password for SSO accounts" hint, when trying to do so. So, the Option shouldn't be displayed, when using AD

**Comment by it33** [comment]
Thanks @finius, agree, [ticket](https://mattermost.atlassian.net/browse/PLT-2047) created for this issue.
