### ISSUE TITLE
System Admin is not able to change profile settings of a user

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2196]
An Administrator should be able to change the profile settings of an user (i.e. changing the user picture,user Name or first/last name)
Also, an administrator should be able to prevent users from being able to changing these options. (policies)

**Comment by it33** [comment]
Thanks @finius, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?

**Comment by finius** [comment]
http://mattermost.uservoice.com/forums/306457-general?query=Search%20filenames

**Comment by PSchwarck** [comment]
here is the proper link to the feature idea forum: http://mattermost.uservoice.com/forums/306457-general/suggestions/12414495-administrator-should-be-able-to-change-the-profile

**Comment by finius** [comment]
@it33 would very appreciate if this Feature could be priorized! Same for this issue: 
https://github.com/mattermost/platform/issues/1945#issuecomment-186744844
