### ISSUE TITLE
/me command is displaying the sender as "webhook", instead of the actual sender (since v2.0.0)

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#2200]
**Reproduction**: Go to an arbitrary channel. Type `/me test`. The message should appear as being send from a webhook, despite you clearly are able to edit and delete it.

**Expected behavior**: That the avatar and username of the invoker is given as the sender, for both yourself and other.

**Introduction**: This was introduced in v2.0.0, and have not been an issue before. The expected behavior described above was the result in previous versions.

**Extra information**: The system is using PostgreSQL as database, Nginx as static server. It is not installed inside a docker container. The system is Ubuntu.

**Comment by it33** [comment]
Thanks! [Ticket filed for tracking](https://mattermost.atlassian.net/browse/PLT-2039)

**Comment by Azenet** [comment]
"webhook" is still displayed as the sender in the notification when the message is received. (3.4.0)
