### ISSUE TITLE
You cannot invoke slash commands in threads, since v2.0.0

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#2201]
**Reproduction**: Open a subthread (reply to a comment). Invoke the `/shrugs` command, for example.

**Expected behavior**: The command should invoke similarly to when done in top level, but _in_ the thread.

**What happens**: The actual command is never executed and will just be send directly as a plain text message (i.e. `/command`) from the sender.

**Since**: 2.0.0. This issue was not there before 2.0.0.

**Comment by it33** [comment]
Thanks @Ticki, appreciate the report, [ticket tracking it now](https://mattermost.atlassian.net/browse/PLT-1598)
