### ISSUE TITLE
The command argument is expanded in autocomplete, since 2.0.0

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#2202]
**Reproduction**: Type `/shru<tab>`.

**Expected behavior**: This should expand to `/shrug ` (notice the space), so that the user can continue typing.

**What happens**: It expands with the documented argument, `[message]`:

```
/shrug [message]
```

**Since**: 2.0.0. This issue was not there before 2.0.0.

**Comment by it33** [comment]
Thanks @Ticki, agree this should be fixed, [opened APR to track this](https://mattermost.atlassian.net/browse/PLT-2064). Anyone welcome to submit a PR
