### ISSUE TITLE
#channel assumes that `channel` is a hashtag, instead of a channel.

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#2203]
**Reproduction**: Type `#channelname`.

**Expected behavior**: This should expand to a link to the channel, `channelname`.

**What happens**: It expands to a link to the hashtag, `#channelname`.

**Tested on**: 2.0.0 and v1.4.0.

**Comment by it33** [comment]
Opening [ticket to document use of hashtags vs. channels](https://mattermost.atlassian.net/browse/PLT-2065)

There's an [existing ticket](https://mattermost.atlassian.net/browse/PLT-1759) on adding support for referencing channels with a non-# character. 

@Ticki, would highly welcome your feedback on the [forum discussion](https://forum.mattermost.org/t/referencing-channels/762) for this topic if you'd like to join in. 

We were surprised more people weren't opinionated on the use of # given the size of the IRC community,

**Comment by ylluminate** [comment]
How do you reference TEAM+CHANNEL? `~TEAM_NAME#CHANNEL_NAME` would work nicely...
