### ISSUE TITLE
Microsoft Exchange requires "From" field instead of "Name" and "Email" fields

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#2205]
We're evaluating mattermost recently and found that mm use feedback email as From to send email, however, in our company, we use Microsoft exchange server which has been configured the From has to be the same as the real account which send the email, so below will fail.

```
        "FeedbackName": "The Team",
        "FeedbackEmail": "team-mailing-list@local.domain",
```

Because the FeedbackEmail is a mailing list which isn't the account which send the email notification.

I'm wondering if we can add another configurations such as:

```
        "From": "Name <email@local.domain>"
```

any thought?

**Comment by it33** [comment]
Thanks @chengweiv5, would this require an entirely new field or could there be a flag that combines `FeedbackName` and `FeedbackEmail` into the From field? 

This could be tricky to add because we'd need to set up an Exchange Server to test it. The first step is understanding the scope of the change needed to support this.

**Comment by chengweiv5** [comment]
I see `FeedbackName` and `FeedbackEmail` currently been used as both for `From` and `Reply(contact info)`, I'd like to split these into 3 configurations

```
FromName
FromEmail
FeedbackEmail
```

Should we have a `FeedbackName`? BTW, I'd like to help to test since we use exchange server.

**Comment by it33** [comment]
Thanks @chengweiv5, is there any documentation that you can share on the naming and use of these fields in Exchange? 

I'm not very familiar on the subject, if we can add something for Exchange that's not confusing for SMTP (or better yet, also supported by SMTP) that would be idea. I think it would be important to name them in a way that was obvious for how they should be used. 

If anyone else using Exchange or SMTP could comment, that would be appreciated as well.

**Comment by chengweiv5** [comment]
I think this subject got confused, In our condition, the SMTP server is microsoft exchange server which configured forbid a different email address in `From`  with the real email account.

for example:

if you have `SMTPUsername` is `mm-noreply`, and the real email address is `mm-noreply@local.domain`, you can not set `FeedbackEmail` to `mm-user@local.domain`.

However, currently, mattermost use `FeedbackEmail` as `From`, so it has to be `mm-noreply@local.domain` which used to send email in fact, one can not configure `FeedbackEmail` to `mm-user@local.domain` which in fact we want, since we'd like user send any feedback to a mailing list.

**Comment by lfbrock** [comment]
Hi @chengweiv5, 

I think this might actually be a bug. 

The names in the config file are a bit misleading right now, the `FeedbackEmail` is supposed to act as the "from" email for email notifications.

We have a second setting, `SupportEmail`, which acts more like the feedback email. It's currently used in the tutorial when asking for feedback, but it should also be used at the bottom of email notifications when asking for feedback. 

I've filed a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-2073) on this, would fixing this bug fix your issue? Or is there another issue with the FeedbackEmail?

**Comment by chengweiv5** [comment]
@lfbrock, yes, it is!

**Comment by stephaneeybert** [comment]
I have these settings at the moment, and am also faced by the message `Connection unsuccessful: Failed to add from email address` on our Exchange server.

        "FeedbackName": "Ne-Pas-Repondre",
        "FeedbackEmail": "nepasrepondre@aaaa.com",
        "FeedbackOrganization": "AAAA",
        "SMTPUsername": "nepasrepondre@aaaa.com",

I wonder what to have then for the Test Connection button to succeed.
