### ISSUE TITLE
Button "Remove Enterprise License and Downgrade Server" is disabled when license file is uploaded in MM 2.0 ENT-7

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2206]
The uploaded license file can't get deleted using the System Console

**Comment by jwilander** [comment]
Hi @finius, you must disable LDAP before you can remove a license file. As it's a pre-release version we don't quite have all the documentation complete but this will be a part of it when it's ready.

Please try disabling LDAP and seeing if the license can then be removed?

**Comment by it33** [comment]
Hi @finius, thanks for the report, instructions for [pre-release updated](http://docs.mattermost.com/process/pre-release.html)
