### ISSUE TITLE
mentions should also be configurable not only for first name but also for last name and a combination of both

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2207]
Within the notification settings, a user can choose to set his own mention triggers to "Your case sensitive first name "John"". It would be even more reasonable to trigger to a last name (because it's more unique then a prename). Furthermore case sensitivity should be an general, additional and optional selective checkbox for any of these settings.

**Comment by jwilander** [comment]
Hi @finius, appreciate the feature idea. Can you please add it to our feature request forums linked to in our process here https://www.mattermost.org/feature-requests/ ? Thanks!

**Comment by finius** [comment]
http://mattermost.uservoice.com/forums/306457-general/suggestions/12434868-mentions-should-be-configurable-not-only-for-first
