### ISSUE TITLE
Suggestion: Add feature to hide/unhide in-line images and media in chat

### ISSUE THREAD

**Issue by Endemoniada** [mattermost/platform#2209]
Possibly also have an option for default behavior when images or media is linked in-line in chat. You might not want to have animated gifs show by default, but rather when you choose to view them. At the very least, I'd very much like to hide the animated gif currently in my chat window :)

**Comment by jwilander** [comment]
Hi @Endemoniada, I think this should be covered by [PLT-1715](https://mattermost.atlassian.net/browse/PLT-1751) and there is already a pull request for it at #2027 that is currently being reviewed.

If that doesn't cover what you had in mind please feel free to follow our steps [here](https://www.mattermost.org/feature-requests/) to submit another feature request. Thanks!
