### ISSUE TITLE
Typo in doc: smultiple -> multiple

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#2219]
http://docs.mattermost.com/help/getting-started/creating-teams.html#user-roles-on-multiple-teams

> A System Admin with accounts on smultiple teams must grant all their accounts System Admin privileges from the System Console. 

smultiple above should be multiple I think.

**Comment by it33** [comment]
Thanks @chengweiv5! Would you be interested in helping with a pull request for this?

**Comment by chengweiv5** [comment]
I would like to help but I didn't find this line in this project

`git grep "smultiple"` yields nothing

**Comment by it33** [comment]
Ah, sorry, forgot we moved the docs to another repo: https://github.com/mattermost/docs/blob/master/source/help/getting-started/creating-teams.md

**Comment by chengweiv5** [comment]
@it33 , thanks, I'll submit a PR there.

**Comment by esethna** [comment]
Thanks @chengweiv5!
