### ISSUE TITLE
[Help wanted] German (de) translation and review

### ISSUE THREAD

**Issue by meilon** [mattermost/platform#2221]
I'd like to start translating Mattermost for my not so English savvy colleagues. Who’s in?

**Comment by medokin** [comment]
Count me in.

**Comment by PSchwarck** [comment]
Hi @meilon, hi @medokin , I asked @rodrigo to add german  to his pootle server. I would like to see MM in german as well ;D
I started to translate... a bit. : http://186.202.167.109/de/mattermost/

HOffentlich kriegen wir das schnell durch ;D

**Comment by medokin** [comment]
Sollen wir bei der Übersetzung "Du" oder "Sie" nutzen?

**Comment by PSchwarck** [comment]
Hmmm... gute Frage. ich umschreibe gerne mit "man " oder so. Du kann passen, Sie ist eigentlich immer Sicher. Windows "duzt" Dich ja auch nicht ;D

**Comment by medokin** [comment]
Wir brauchen dann noch Standards für manche Vokabeln. Hier meine Vorschläge:
- User = Benutzer
- Channel = Channel
- Team = Team
- Member = Mitglied (oder doch Teilnehmer?)
- join = beitreten (oder doch teilnehmen?)
- email = E-Mail (oder E-Mail-Adresse?) 

Technische Begriffe sind manchmal schwer zu Übersetzen, vor allem wenn der Kontext nicht klar ist.
- OAuth scope = OAuth scope
- local storage (Server) = Dateisystem
- local storage (Browser) = local storage
- OS = Betriebssystem

Dann lieber nochmal Diskutieren.

**Comment by meilon** [comment]
Ich wäre für eine direkte Übersetzung ins "Sie" Deutsch. Wenn das Original eine Persönlichkeitsform einsetzt, sollte "Sie" verwendet werden. Denn das ist in den meisten mir bekannten Business Produkten und deren Anleitungen der Fall.

Was die Standardvokabeln angeht, passen für mich soweit die Vorschläge von @medokin, außer aus Channel noch Kanal machen. Bei den technischen Vokabeln würde ich andererseits so viel Original lassen wie nur geht. Die bekommt zu 99% ein technischer Admin zu sehen und der weiß was das ist. Also alles was man als normaler User in MM findet, was er an Einstellungen hat etc., ins Deutsche übersetzen. Das hat denke ich erstmal Priorität. Solange die Dokumentation noch nicht übersetzt ist, hilft es auch, wenn man nach den original Fachbegriffen suchen kann.

Am Ende muss es eben einen Sinn ergeben und einheitlich sein. Wenn jetzt ein neuer Begriff dazu kommt, dann kann man ja nachsehen ob und wie den jemand schon übersetzt hat. Entweder man übernimmt ihn oder startet eine Diskussion.

Einer muss am Ende aber den Hut aufhaben und Entscheiden.

**Comment by PSchwarck** [comment]
Ich glaube, das man sehr viel passiv umschreiben kann. Die Liste der feststehenden Begriffe sollten wir schön weiter festhalten. Die Übersetzung soll ja schließlich stimmig sein. Aktuell gehe ich so vor, dass ich Text, bei denen ich mir unsicher bin, einfach stehen lasse und weiter mache. So sollten wir gemäß Pareto schnell durchkommen und die komplexen Übersetzungen zum schluss machen. Dies kann man auch gerne ich der Gruppe lösen. => Schwarmintelligenz  ;D
Zugegeben, der Nachteil bei pootle ist, das die Übersetzungen nicht immer thematisch zusammenhängen. So kann es zu Abweichungen kommen.

**Comment by PSchwarck** [comment]
Ah eins noch: Wirklich Kanäle? Wir reden von Usern (nicht Benutzer) und sprechen dann von Kanälen? Mir fällt ja auch nichts besseres ein... in der Firma versuche ich zumindest das Wort "Chat" zu vermeiden. Gruppe? Themengruppe? Thema?

**Comment by medokin** [comment]
Mit Kanal wäre ich einverstanden. @PSchwarck `Gruppe ` können wir nicht nutzen, weil es dem Begriff Team zu nahe steht. Und `Thema` passt nicht, weil ein Channel nicht unbedingt Themabezogen ist.

**Comment by medokin** [comment]
Ich habe mir die Freiheit genommen eine kleine Hilfe zu erstellen: https://gist.github.com/medokin/43e723dc186434ecff81
Updates willkommen.

**Comment by finius** [comment]
Tagchen, also MSS ist ein modernes Tool das auch von tendentiell eher jünheren und modernen Typen von Menschen benutzt wird. Daher würde ich "Sie" für entfremdend halten und das persönlichere und distanzsenkende "Du" verwenden.
Ich würde außerdem nicht alle Anglizismen eindeutschen. @PSchwarck Kanäle kann man machen, wobei ich dabei immer an Abwasser denke. @medokin Wie wären denn Räume?

**Comment by meilon** [comment]
Wir sind mittlerweile schon voll drin und ein Umschwenken finde ich jetzt zu spät. Ich gehöre sicher auch zu den noch "jüngeren und modernen Typen" und finde das "Sie" im Geschäftsbereich immer noch ein muss. Wie man mit den Kollegen spricht mag etwas anderes sein, aber Software soll mich nicht "duzen".
Und da ich meine Zeit schon mit dem Fehlermeldungen von Deutsch wieder ins Englische übersetzen verbracht habe finde ich es äußerst praktisch, wenn man direkt übersetzen kann. Außerdem heißt es im Original ja auch Channel und nicht Rooms.

**Comment by medokin** [comment]
Kann mir jemand den Workflow von diesem Übersetzung-Tool erklären? Immer wenn ich auf "Übersetzung fortsetzen" gehe, lande ich immer bei Item "April".

**Comment by PSchwarck** [comment]
Hi @medokin 

Ich mache das wiefolgt: 
1. Ich filtere auf "german", und "unvollständig" oder "nicht übersetzt"
2. "blättere" mit Satz hoch, Satz runter auf einen noch nicht übersetzten Text, bzw. wenn ich was finde, was mir nicht gefällt. Stelle ich einen neuen Vorschlag ein.

So. Für mich scheint das Pootle-System zu unterscheiden zwischen "Vorschlagen" und "Senden" (denke, das hieß mal "commit"). 

Wie gehts nun weiter? Ich schätze, jmd. dem man "vertraut", benötigt wohl noch die Berechtigung, die Texte anzupassen bzw. zu "Bestätigen".

Alternativ: Wir arbeiten ja quasi "nur" an einer Übersetzungsdatei, die wir uns extrahieren lassen können, und dann mittels dem Konvertier wieder zurück in das Mattermost-Format umbauen können. Diese Datei sollte sich dann auf einer Entwicklungsumgebung nutzen lassen können. 

Ab einem gewissen Reifegrad & ggf. Nacharbeiten, kann für diesen Issue hier, ein Pullrequest gezogen werden, in dem dann jmd. die übersetzte Datei committen kann. 

Wenn diese Sprachdatei etwas abgehangen ist, bzw. sich bewährt hat, kann diese in die Mattermost-Releases aufgenommen werden.

Korrigiert mich bitte, wenn ich hier falsch liege. ;O)
Viele Grüße


![2016-03-09 17_29_13-ubersetzen _ mattermost _ german _ mattermost translation server](https://cloud.githubusercontent.com/assets/16940971/13642370/829cae3e-e61c-11e5-8569-71c481e8a83f.png)

![2016-03-09 17_24_08-ubersetzen _ mattermost _ german _ mattermost translation server](https://cloud.githubusercontent.com/assets/16940971/13642339/58218cec-e61c-11e5-9982-5fd3634e9213.png)

**Comment by meilon** [comment]
Ich tippe immer alles selber, die Systemvorschläge sind häufig nicht so gut. Was auch sehr wichtig ist, dass man sich selbst einen Mattermost Server aufsetzt und die eigene Übersetzungen testet. Schließlich sind deutsche Wörter häufig länger und können das Design kaputt machen. Ich melde die Fehler dann im Localization Channel. 

Ich habe den Teil so gut wie komplett den der Endnutzer sieht, die Systemkonsole habe ich auch fast fertig. Ich werde das Repo forken und nen PR starten in den wir die Ergebnisse ständig nachliefern sobald wir irgendwann mal Beta sind

**Comment by K-Leon** [comment]
Hallo Zusammen,
Gibt es eine Möglichkeit den aktuellen Stand aus poodle zu exportieren, damit ich einen eigenen Server aufsetzen kann mit dem Stand der Dinge? ( Möglichst inklusive der Vorschläge - die Meisten sind ja korrekt soweit ich das sehen konnte und die Problemfälle bemerkt man auf der UI eh am schnellsten )

**Comment by meilon** [comment]
Klar: https://github.com/rodrigocorsi2/mattermosti18n

**Comment by K-Leon** [comment]
Vielen Dank!

Wenn ich den export speichere übernimmt er allerdings nicht die Vorschläge, sondern nur bereits akzeptierte Übersetzungen. Gibt es eine Möglichkeit automatisiert an eine .po mit den vorgeschlagenen Übersetzungen zu kommen?

Soweit ich es sehen kann haben da einige bereits ganze Arbeit geleistet.

**Comment by meilon** [comment]
Dafür musst du angemeldet sein und die beiden po Dateien über das Webinterface von Hand runterladen

**Comment by Perrylicious** [comment]
Hallo,

gibt es eine Möglichkeit, den momentanen Stand der deutschen Übersetzung in eine Ubuntu-Installation (von der Webseite) einzurollen? Ich habe bis vor 3.0 immer die default en.json gesichert, selbst übersetzt und überschrieben, aber die gibt es jetzt nicht mehr im /webapp/.

**Comment by meilon** [comment]
Hi @Perrylicious 
die umgebaute .json wird direkt in den Quelltext mit einbezogen und lässt sich im Endergebnis nicht mehr einfach austauschen.
Entweder noch 24 Tage bis zum Release von 3.2 warten (wenn es wieder mit dem 16. klappt) oder selber kompilieren.

**Comment by jasonblais** [comment]
German was released [with Mattermost v3.2 in July](https://docs.mattermost.com/administration/changelog.html#release-v3-2-0) - thank you everyone for the wonderful work!

Big thank you to @meilon who is reviewing new and updated strings as new features are added to Mattermost over time.

If anyone else would like to help maintain the translations, please let us know on our [German community channel](https://pre-release.mattermost.com/core/channels/i18n-german) and join the [Mattermost Translation Server](http://translate.mattermost.com/de/mattermost/) to contribute.
