### ISSUE TITLE
Search of cyrillic words with asterisk don't work

### ISSUE THREAD

**Issue by remnyov** [mattermost/platform#2228]
There are no search results when asterisk in added to cyrillic words.

**Comment by lfbrock** [comment]
Hi @remnyov, 

Would you mind moving this to troubleshooting forum (instructions above), and include what database your using?

Our search is based off of the default database search, I'm wondering if something additional may need to be done to set it up to work properly for cyrillic words. For example, we have some [documentation](http://docs.mattermost.com/install/requirements.html#database-software) suggesting extra steps for getting search to work in Chinese/Japanese/Korean.

**Comment by remnyov** [comment]
Please, excuse me for any inconvenience but I made some additional investigation and I think this is not the case.
At first I upgraded MySQL 5.5 to MariaDB 10.1 which is compatible with MySQL 5.6+ at most cases. But wildcard search still doesn't work after upgrade. Furthermore I tested wildcard search of english words and found that it doesn't work too! I think at first time I tested it incorrectly: I searched for dot-separated parts of URL instead of parts of normal word.
Then I looked at queries that mattermost made. And there are no asterisk in search terms:
`"...AND MATCH (Message) AGAINST ('someth' IN BOOLEAN MODE)".`
When I manually send queries like `"SELECT Message FROM Posts WHERE MATCH (Message) AGAINST ('someth*' IN BOOLEAN MODE)" ` the results are ok. That's why I think the problem is not in the database management system but in the code of mattermost which removes asterisk from query terms.
