### ISSUE TITLE
mentions that are added to a post subsequently do not lead to a notification

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2236]
When I submit a post without mentioning anyone (not using a "@" mention) and then edit this post and add a (i.e. @channel) mention, the channel members do not get informed after I submit the changed post containing the new @-mention

**Comment by lindy65** [comment]
Hi finius

Thank you for the report.  We'll track the issue in Jira from [this ticket](https://mattermost.atlassian.net/browse/PLT-2152)
