### ISSUE TITLE
in some cases the channel name is not shown properly in the top of the web ui main frame

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2237]
For testing purposes we created a channel "TechChannel". In the blue frame containing the channel list on the left, it is shown correctly (contains the finishing lower case "L" in the channel name). But in the white/grey frame on top of the "main" frame , the closing "l" of TechChannel is missing). However, if we try to rename the channel, we can see that the name is set correctly.

![unbenannt](https://cloud.githubusercontent.com/assets/5287181/13279881/e926c4b6-dada-11e5-8643-c5fbf1d05368.JPG)

**Comment by it33** [comment]
Thanks for filing this, I wasn't able to repro on master, 

Can anyone from the community repro this?

**Comment by finius** [comment]
I must confess, even I am not able to repro this. It was a single event and after changing the browser size and switching the channel the error was gone.

**Comment by it33** [comment]
Cool, thanks for reporting! Will close for now, please feel free to re-open if a repro is found,

**Comment by finius** [comment]
had the same issue today again using IE 11.
I could solve it my minimize the browser windows by drawing the corners of the windows together to a minimum and then resize it to normal size. Then the channelname was okay again, without reloading the page.
![unbenannt2](https://cloud.githubusercontent.com/assets/5287181/13465793/6a4e93d6-e097-11e5-8fef-2a5a9657da7d.JPG)

**Comment by lfbrock** [comment]
Thanks @finius, I filed a [bug](https://mattermost.atlassian.net/browse/PLT-2189) to look into this issue - if you do end up getting steps on how to reproduce the bug, it would be great if you could let us know

**Comment by finius** [comment]
I understand, but it just happens every now and then. I still wasn't able to see any regularity

**Comment by lfbrock** [comment]
No worries that's fine, we'll try and repro it on our end as well to see if we can figure it out
