### ISSUE TITLE
Not able to send Message in Preview message / Preview Markdown mode 

### ISSUE THREAD

**Issue by PSchwarck** [mattermost/platform#2244]
When I write a message, one can check the looks via the preview mode. I can not send the message, after i approved the preview, but need to return via "edit message" and then send the message. I would prefer a edit => preview => send message,  instead of edit => preview => edit message => send meesage one.

**Comment by lfbrock** [comment]
Hi @PSchwarck, 

Here's an [accepting pull requests ticket](https://mattermost.atlassian.net/browse/PLT-1992) for this issue.
