### ISSUE TITLE
A channel with that URL was previously created

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#2246]
I'd like to create a channel which was already deleted, however, seems mattermost prvent me from re-creating it, any story in behind?

**Comment by it33** [comment]
#### [Deleting a Channel](http://docs.mattermost.com/help/getting-started/organizing-conversations.html#deleting-a-channel)

When a channel is deleted it is removed from the user interface, but an archived copy exists on the server in case it is needed for audit reasons later. Because of this, the URL of a newly created channel cannot be the same URL name as a deleted channel.

**Comment by jdiehl** [comment]
I think this is a relevant issue. We have the situation that a team created a bunch of channels for testing purposes and deleted them afterwards. Now, they cannot use these names any more (unless they manually edit the url which can lead to some confusion).

**Comment by jdiehl** [comment]
Is there a way for an admin to delete the archived channel?

**Comment by ursweiss** [comment]
Modifying the DB directly only at the moment as far i see.
This is for Mattermost 3.0.2 and may changes in newer releases:
```
-- Find the ID of the channel you want to delete:
select DisplayName, Name, Id from Channels WHERE DisplayName <> '' ORDER BY DisplayName;

-- Save the channel ID in a variable:
SET @ChannelId='<ChannelId>';

-- Delete all data related to this channel ID:
DELETE from Posts where ChannelId=@ChannelId;
DELETE from IncommingWebhooks where ChannelId=@ChannelId;
DELETE from OutgoingWebhooks where ChannelId=@ChannelId;
DELETE from ChannelMembers where ChannelId=@ChannelId;
DELETE from Channels where Id=@ChannelId;
```
To get all tables where the column ChannelId exists (replace "mattermost" with your DB name if it's different):
```
SELECT DISTINCT TABLE_NAME 
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE COLUMN_NAME IN ('channelId')
        AND TABLE_SCHEMA='mattermost';
```

**Comment by jdiehl** [comment]
Awesome! Thanks!

**Comment by filipp** [comment]
Is this issue closed because a workaround was provided or because there is now (v 3.4.1) a way to delete channels? It would be nice if archival was optional - our team created some channels during testing and we want to delete them and create new ones moving into production.

**Comment by jasonblais** [comment]
@filipp If you'd like to see channel archives in Mattermost, please help upvote [the feature request for archives](https://mattermost.uservoice.com/forums/306457-general/suggestions/10960347-channel-archiving), so it can be discussed with the community and prioritized accordingly?

Each member gets 10 votes in the feature request channel, each influencing the future of Mattermost.
