### ISSUE TITLE
List teams of user in mattermost home page?

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#2248]
Is mattermost can list all *public* teams and teams of user has been joined in home page a good idea?

So that an user no need to remember every team he is a member but just the mattermost service address, it's much, much easier.

**Comment by it33** [comment]
Team admins can [choose to list their team in the "Team Directory" on the root page](http://docs.mattermost.com/help/settings/team-settings.html#include-this-team-in-the-team-directory) to support this. 

Does this help?

**Comment by chengweiv5** [comment]
I think "NO", list in "Team Directory" means make the team becomes **public**, everyone can join in, is that right?

**Comment by chengweiv5** [comment]
In fact, there is "Find my teams" in home page, why not just list my teams there? it's much simple and user friendly I think.

**Comment by it33** [comment]
Including the team in the directory means there's a link on the root page. It doesn't change restrictions on account creation. 

You're right, this feature could be helpful. Can we have your help opening a [feature idea](http://www.mattermost.org/feature-requests/) so it can be upvoted?

**Comment by chengweiv5** [comment]
> Including the team in the directory means there's a link on the root page. It doesn't change restrictions on account creation.

Thanks, @it33 , you're right.

I just posted my idea [here](https://mattermost.uservoice.com/forums/306457-general/suggestions/12469872-list-teams-of-user-in-mattermost-home-page)

**Comment by it33** [comment]
Thanks @chengweiv5!
