### ISSUE TITLE
Show the channel creator?

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#2262]
After have a channel created, user has joined can not see who created it, like below.

> This is the start of the docker-users channel, created on February 26, 2016. Any member can join and read this channel.

How about also display the channel creator here?

**Comment by lfbrock** [comment]
Hi @chengweiv5, 

There is an [accepting pull requests ticket](https://mattermost.atlassian.net/browse/PLT-599) to add the channel creator if anyone would like to work on that.
