### ISSUE TITLE
Android App 1.14 - Javascript error on login on Samsung Galaxy S6 edge+ running Android 5.1.1

### ISSUE THREAD

**Issue by it33** [mattermost/platform#2271]
Repro: 

1. Set Mattermost server to Developer Mode
2. Login using Mattermost Android App 1.14 on Samsung Galaxy S6 edge+ running Android 5.1.1

Expected: Normal mobile app operation 
Observed: JavaScript error appears in header in blue bar message

**Comment by lindy65** [comment]
Thanks it33, ticket to track the issue has been created here: https://mattermost.atlassian.net/browse/PLT-2215
