### ISSUE TITLE
Android App 1.14 on Oneplus One w/ 6.0.1 - Pressing the android back button from the Reply form quits the app

### ISSUE THREAD

**Issue by mtorromeo** [mattermost/platform#2272]
With the android app if I go to the reply form (by clicking reply on any message in a channel) and then I try to go back to the channel without posting a reply and using the device back button, the app quits to the android home screen instead of going back to the channel.

App version: 1.14
Device: Oneplus One (A0001)
Android: 6.0.1 (Cyanogenmod)

**Comment by imval** [comment]
I have the exact same issue with my OnePlus One with Android 6.0.1, App version 1.14, on my private server.

**Comment by lindy65** [comment]
Thanks mtorromeo and imval, ticket has been created here: https://mattermost.atlassian.net/browse/PLT-2214
