### ISSUE TITLE
Attempting to upload images that exceed maximum resolution should fail gracefully

### ISSUE THREAD

**Issue by TheElf** [mattermost/platform#2277]
**To clarify, this is not an Android only issue** 

**Expected Behavior:**
When a user uploads an image that exceeds the maximum allowable resolution, they should see a meaningful error message regarding the problem.

**Actual Behavior:**
In the above scenario, the only error message displayed reads:

![image](https://cloud.githubusercontent.com/assets/4720546/13374554/b4ba068c-dd4d-11e5-92dc-2a13a117a057.png)

The image appears to continue processing, and never disappears even though the upload has failed.

This appears on both the website and the android app.

**Suggested Fix:**
**Either**
Display a relevant error message to the user in the same way that it is displayed for files that are too large:

![image](https://cloud.githubusercontent.com/assets/4720546/13374565/0ebb44fc-dd4e-11e5-9c94-2f00a341d5dd.png)

**or**

host the image like a file without preview

**Additional Information:**
In the JavaScript console, we can see that the API returns a meaningful error message, it just needs to be displayed to the user.
![image](https://cloud.githubusercontent.com/assets/4720546/13374549/9661fc76-dd4d-11e5-80c6-b1de28853788.png)

**Comment by lfbrock** [comment]
Thanks for the report! Closing this issue, and will track it in [Jira](https://mattermost.atlassian.net/browse/PLT-2182).
