### ISSUE TITLE
Slack incompatibility - Multiline text throws Unable to parse incoming data

### ISSUE THREAD

**Issue by jlauro** [mattermost/platform#2278]
```
$ echo "$payload"
payload={"channel": "#jltest", "username": "testuser", "text": "whatever
test
123"}
$ curl --data-urlencode "${payload}" $url
{"id":"web.incoming_webhook.parse.app_error","message":"Unable to parse incoming data","detailed_error":"","request_id":"m4pa7hs8gf8mxpdgxdjjwschzw","status_code":500,"is_oauth":false}
```

Work around:  Use \n instead of true line breaks, but doesn't help slack compatibility...

Documentation at http://docs.mattermost.com/developer/webhooks-incoming.html implies that raw newlines should work (and do in slack).

**Comment by it33** [comment]
Thanks @jlauro!

Anyone in the community interested in helping with a pull request to help fix this?

**Comment by lfbrock** [comment]
Hi @jlauro, does this work using curl in Slack? 

It seems like it's the curl command corrupting the json payload, our APIs should support new lines like that.

**Comment by jlauro** [comment]
@lfbrock , The test payload and curl command works fine with Slack.

**Comment by lfbrock** [comment]
Okay, I've made an accepting pull requests ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-2188
