### ISSUE TITLE
Slack incompatibility - Two emoji with no space

### ISSUE THREAD

**Issue by jlauro** [mattermost/platform#2279]
Two emoji with no space are not displayed as images.
Works:  :eyes: :sheep:
Fail: :eyes::sheep:  (works in slack)

`Works:  :eyes: :sheep:`
`Fail: :eyes::sheep:  (works in slack)`

**Comment by lfbrock** [comment]
Thanks @jlauro, 

Made a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-2172) to track this. It's accepting pull requests if anyone would like to work on fixing this. 

Closing this issue + will track it in Jira.
