### ISSUE TITLE
Android App 1.14 on Oneplus One w/ 5.1.1 - Javascript error row 16 col 5304 during reply with voice

### ISSUE THREAD

**Issue by jlsjonas** [mattermost/platform#2280]
* reply to a message
* add file > pick "sound recorder"
* notice that it won't send you back, having to use the back button to return to app
* error generated

App version: 1.14
Device: Oneplus One (A0001)
Android: 5.1.1 (CyanogenOS)

**Comment by jlsjonas** [comment]
please note that the "Back" arrow (since button isn't support yet > bad ux) was also unresponsive, and I had to use the search function to get out of the blocked screen

**Comment by lindy65** [comment]
Thanks jlsjonas, a ticket for the issue has been created: https://mattermost.atlassian.net/browse/PLT-2213
