### ISSUE TITLE
 Android App 1.14 verified on Xiaomi Redmi Note 2 with Android 5.0.2

### ISSUE THREAD

**Issue by vcazan** [mattermost/platform#2284]
| Version | Device & OS | Issues | Tester | Date | 
|:--- |:--- |:--- |:--- |:--- |
| 1.14 | Xiaomi Redmi Note 2, Android 5.0.2 | | 2016-02-29 |

**Comment by it33** [comment]
Thanks @vcazan! Your device has been added [to verified devices list](https://github.com/mattermost/android/commit/c4b68c77cd5b38b7d537803393344bbbdfe23a31). Thanks for helping improve Mattermost for the whole community!
