### ISSUE TITLE
login attempt of an inactive user shows a non userfriendly and misunderstanding error message

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2285]
When an inactive ldap user tries to log in to Mattermost, he get's an information: "We received an unexpected status code from the server (200)".
This is misunderstanding and could make one think of a server problem. It would be more appropriate to say, that the user is currently inactive and an administrator has to be contacted, for example. This would help a bit finding the cause for the failed login attempt.

**Comment by lfbrock** [comment]
Thanks for the report, 

Created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-2178) to track this issue.
