### ISSUE TITLE
ldap can not be filtered to exclude particular users or groups from the currently bound Active Directory base DN, to log in to Mattermost, without having to reorganize the corporate OU structure.

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2286]
All users within the specified base DN are allowed to log in to Mattermost. It is currently impossible to exclude certain users without having to restructure all OUs within the base DN. In most cases for Enterprises it is essential to have to lock out some accounts from the base DN - for example some particular employees or guest accounts.

**Comment by lfbrock** [comment]
Thanks @finius, 

Here is a ticket in [Jira](https://mattermost.atlassian.net/browse/PLT-1532) to track this issue.
