### ISSUE TITLE
administrators are not able to moderate channels by relocating messages into another channel

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2287]
Users use to drop their messages sometimes without following the company guidelines how to publish messages. For this circumstance a administrator should be able to moderate/lead the public channels to funnel messages into the right places. This is important to keep a discussion in flow instead of deleting it or asking the users to relocate the entries by themselves.

**Comment by lfbrock** [comment]
Hi @finius, 

There's an existing [feature request](https://mattermost.uservoice.com/forums/306457-general/suggestions/11080068-move-a-message-to-another-channel) on this, can you upvote it/add your feedback there so it's all in one place?

**Comment by finius** [comment]
Sorry, didn't mind that. Thanks!
