### ISSUE TITLE
naming of the user status "inactive" is confusing because it means in fact "disabled"

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2288]
The problem of the current situation is, that an user account status "inactive" implifies, that the user is "paused" but not locked out. One would guess, that if he logs in again, he could reactive himself again. But in fact, he is locked out. So, it would be more appropriate to rename the status "inactive" to "disabled".

**Comment by finius** [comment]
also see https://mattermost.uservoice.com/forums/306457-general/suggestions/12518376-make-an-admin-be-able-to-differ-between-inactive-a

**Comment by lfbrock** [comment]
Thanks @finius, agree that makes more sense - made a ticket [here](https://mattermost.atlassian.net/browse/PLT-2181) for the change
