### ISSUE TITLE
a system administrator is not able to delete a user out of the system or rather delete his profile using the System Console

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2289]
In some cases it could happen that a profile is broken or an administrator wants to completely remoes a user completely from the system. (one example could be that an account was hacked an the system was fully spammed with senseless messages. Another example could be a test user and its messages). An administrator should therefore be able to completely remove all arrears of such a users from the system.

**Comment by lfbrock** [comment]
Hi @finius, 

This is currently only available from the [command line](http://docs.mattermost.com/administration/command-line-tools.html), if you need an option in the System Console UI for this can you help [file a feature request](http://www.mattermost.org/feature-requests/)?

**Comment by finius** [comment]
well, deleting users indeed is a rare administrative Task, however it would make live easier to have just one console to manage Mattermost - at least in Enterprise environments. 
It is more common that administrators should be able to manage a user profile in behalf of someone or disable notifications as an attendee. Also a use case could be the need to insert profile pictures to the member profiles.

**Comment by finius** [comment]
related to this: https://mattermost.uservoice.com/forums/306457-general/suggestions/12555744-extend-the-manage-members-console-to-delete-and

**Comment by lfbrock** [comment]
Thanks, makes sense! Will track it as a feature request.
