### ISSUE TITLE
administrators get no notification when new channels are added

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2290]
When users create new channels, there currently seems to be no notification emails send to administrators neither when a new channel is added nor who this channel added. This prevents administrators from being informed proactively about misbehaviours of users (i.e. if users create non corporate/private information exchanges on the system). A moderator feature would be very appreciated to help the IT securing itself and not having to explain the CEO why there is a public channel for exchanging illegal content, for example.

**Comment by lfbrock** [comment]
Hi @finius, 

Can I have your help moving this to feature ideas forum as per above instructions?

Would having a System Message posted to Town Square when someone creates a public channel address this issue?

**Comment by finius** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/12533661-make-administrators-get-a-notification-when-new-ch

**Comment by lfbrock** [comment]
Makes sense, thanks!
