### ISSUE TITLE
[Help wanted] Traditional Chineese(zh_TW) translation and review

### ISSUE THREAD

**Issue by williamwu0220** [mattermost/platform#2295]
My team and I will help to do the zh_TW translation. Anyone interested may drop me a line. :)

**Comment by enahum** [comment]
Please feel free to speak Chinese, [you can see other threads speaking non-English as well](https://github.com/mattermost/platform/issues/2221)

[Translation guide here](http://docs.mattermost.com/developer/localization.html). Please also [join the localization channel](https://pre-release.mattermost.com/core/channels/localization), as there are new tools being developed to make translation easier.

Theres also a translation for Chinese ongoing [for zh_CN here](http://186.202.167.109/zh_CN/mattermost/)

**Comment by williamwu0220** [comment]
Thanks @enahum. We are working on this at zh_TW branch of https://github.com/fosstp/platform, I'll also join the channes you mentioned above. :)

**Comment by williamwu0220** [comment]
Complete all translation. Step into testing phase.
完成所有正體中文翻譯，接下來進入測試階段

**Comment by it33** [comment]
Hi @williamwu0220, 

1. Just created a new discussion channel for [zh_TW translation](https://pre-release.mattermost.com/core/channels/i18n-chinese--zh_tw). Would welcome you to join, and bring in any other members from the zh_TW community.  
2. We now have a [Mattermost Translation server](http://translate.mattermost.com/zh_TW/) where [Kent Yeh](http://translate.mattermost.com/user/kent.yeh/) has been working on translations as well. 

Perhaps we could bring you two together to finish off zh_TW and get it shipped?

**Comment by williamwu0220** [comment]
Sorry for replying so late, I'm happy to invite other members to join the channel for zh_TW translation.

**Comment by mouson** [comment]
@williamwu0220  我也可以加入此計畫唷！

**Comment by jasonblais** [comment]
Thanks @mouson for your interest in helping!

zh_TW has in fact being fully translated, thanks to the efforts from [Chikei](http://translate.mattermost.com/user/Chikei/) and other contributors.

That being said, there are regular updates for translations as new features are added to Mattermost. If you'd like to help maintain it, please let us know and I'd encourage you to visit our [Mattermost Translation server](http://translate.mattermost.com/zh_TW/) for zh_TW.

Would also welcome you to join the [zh_TW translation](https://pre-release.mattermost.com/core/channels/i18n-chinese--zh_tw) discussion channel to join the rest of the zh_TW community.  Hope to see you there :)

**Comment by jasonblais** [comment]
Traditional Chinese (zh_TW) was released [in our August release](https://docs.mattermost.com/administration/changelog.html#languages) - thank you everyone for the wonderful work!

Big thank you to @chikei who is reviewing new and updated strings as new features are added to Mattermost over time.

If anyone else would like to help maintain the translations, please let us know on our [zh_TW community channel](https://pre-release.mattermost.com/core/channels/i18n-chinese--zh_tw) and join the [Mattermost Translation Server](http://translate.mattermost.com/zh_TW/mattermost/) to contribute.
