### ISSUE TITLE
Textinput field does not scroll do end of text, when more then 7 lines were written

### ISSUE THREAD

**Issue by PSchwarck** [mattermost/platform#2301]
Hi, 
when i type a rather lengthy text, i cannot see what i am writing when writing more then 7 lines, as the scrollbar stays on the top. When putting the cursor to the end, the scrollbar jumps to the top and I cannot see my text anymore. 
I dont't know if this got fixed yet, as the search for UI-Improvemnts did not mention that in particular.

My expected behavior would be, that the "focus" stays/scrolls on the position of the cursor, independent of the length of text.

**Comment by lfbrock** [comment]
Hi @PSchwarck, 

What version of Mattermost are you using, and what browser was this happening on?

**Comment by PSchwarck** [comment]
Hi @lfbrock, 
We are using Mattermost 2.0, Enterprise Edition, FireFox 42 + FireFox 43.0.1 . 
I could reproduce this error on pre-release.mattermost.com/core, too. 

Chrome 48.0.2564.116 and IE 11.0.9600.18204 work as expected.

**Comment by lfbrock** [comment]
Thanks! Filed a ticket in [Jira](https://mattermost.atlassian.net/browse/PLT-2190), and will track this there
