### ISSUE TITLE
Improve notification badge regarding unparticipated channels

### ISSUE THREAD

**Issue by frdmn** [mattermost/platform#2303]
Hi,

my coworker just asked me, what's the reason that he sees a red notification badge, even though none of his channel show new chat activity. 

After a couple of minutes he found out that under `More...` a new channel appeared, which another team member created, thus the notification in first place.

In my opinion he shouldn't even receive the notification if it's regarding a channel, that he isn't participating at the moment.

Thoughts?

**Comment by lfbrock** [comment]
Hi @frdmn, 

Do you know what browser this was on, or was it on a mobile client?

**Comment by frdmn** [comment]
Thanks for the quick reply @lfbrock 

As far as I know he is using the latest Safari (Desktop version, OS X 10.11.3)

**Comment by lfbrock** [comment]
Thanks @frdmn, I've been try to reproduce this but haven't been able to - if you coworker is still seeing this, can you see if he's able to find exact steps to reproduce it?

**Comment by frdmn** [comment]
@lfbrock We reinstalled our Mattermost instance yesterday and since then the problem didn't occured at all anymore. I'm going to close this issue and eventually reopen if we somehow can reproduce the problem again.
