### ISSUE TITLE
private chats have no ability to authorize users based on ldap groups

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2304]
In corporate Environments often closed discussions take place between persons whose users already exist within predefined ldap groups. For Mattermost it would make sense to authorize users for private channels using such existing ldap groups.

**Comment by finius** [comment]
tracked here: https://mattermost.uservoice.com/forums/306457-general/suggestions/12536070-make-private-chats-able-to-authorize-users-based-o

**Comment by lfbrock** [comment]
Thanks @finius, work on this is planned to begin next release ([ticket](https://mattermost.atlassian.net/browse/PLT-1076) for reference).
