### ISSUE TITLE
Not working permalink 

### ISSUE THREAD

**Issue by pwo-fg** [mattermost/platform#2309]
Hi, after select permalink at random post on random channel, I can see only : 
"The link below allows authorized users to see your post." but nothing after that ( only cancel ) 
using version 2.0.0. build : 5950

**Comment by lfbrock** [comment]
Hi @pwo-fg, 

What browser and OS are you seeing this on?

**Comment by lfbrock** [comment]
Closing this issue + will track in Jira: https://mattermost.atlassian.net/browse/PLT-2194
