### ISSUE TITLE
can't create direct message by incoming webhooks  when i add @

### ISSUE THREAD

**Issue by ChelinTsien** [mattermost/platform#2310]
can't create direct message by incoming webhooks  when i add @

**Comment by lfbrock** [comment]
Hi @ChelinTsien, 

Can you explain more about what you're looking for?

**Comment by lfbrock** [comment]
Closing this issue, @ChelinTsien if this is a feature request please contribute a [feature request](http://www.mattermost.org/feature-requests/)?
