### ISSUE TITLE
email notifications for new messages and for channel joins look alike and have a similar email notification subject

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2312]
This behaviour leads to that one could not see at first sight which type of message the notification was for, because the email subject is always "New Mention on...".
It would be more informating and appropriate to choose a email subject that makes clear at first sight which kind of mention the notification is about. (channel join, user disabling, mention, etc)
In my opinion a channel join is no mention in sense of a new message. There is a difference between a new message and other System activities and this should be clear withing the notification email.
Maybe ist reasonable to differ the email design a bit by choosing different colours for different notification types, so a user can see what the notification is about just based on the colours in the notification email.

**Comment by PSchwarck** [comment]
As a add on a customizable Email-Subject would be nice. Like[%team" "+"%Channel" "+"%sender"]

**Comment by lfbrock** [comment]
Hi @finius, we discussed this change and we're trying to decide between breaking out the subject lines to be more detailed, or combining them to use the same title so people will only have one Mattermost email thread per day. 

We see the benefit to both sides and weren't sure which way would be more popular with the community, so if you could help move this to the feature idea forum where it can get some more feedback that would be great.

**Comment by finius** [comment]
Thanks for the update!

**Comment by finius** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/12946581-email-notifications-for-new-messages-and-for-chann
