### ISSUE TITLE
Cannot delete team using command line tools

### ISSUE THREAD

**Issue by brioscaibriste** [mattermost/platform#2313]
In version 2.0 build 5950 I am trying to use the command line tools to delete a team with the following command

`sudo ./platform -permanent_delete_team -team_name="teamname"`

It prompts to verify that I have completed a database backup and appears to exit with a return code of 1. 

The team is still visible even after a restart of the server, fresh sign in and an icognito tab login. 

Nothing appears in the mattermost logs when they are set to debug mode.

**Comment by coreyhulen** [comment]
did you type `YES` in all caps in response to the prompt?

**Comment by lfbrock** [comment]
Closing issue, @brioscaibriste if you're still having issues please post to [troubleshooting forum](https://forum.mattermost.org/).

**Comment by brioscaibriste** [comment]
This was correct @coreyhulen I had to type yes in capital letters to get it to delete.
