### ISSUE TITLE
[Enhancement] Check for expected and correct amount of color variables while importing themes

### ISSUE THREAD

**Issue by frdmn** [mattermost/platform#2314]
One of my colleages just had the issue that he picked a nice theme from `http://slackthemes.net/`, and imported it in Mattermost. However, instead of "Import from Slack" he imported it as Mattermost format. Since the amount of passed color hex codes differ between Slack and Mattermost, importing a Slack theme as Mattermost one ends up in a pretty messed up design.

For example when I try to import `#4F2F4C,#452842,#8C5888,#FFFFFF,#3E313C,#FFFFFF,#00FFB7,#DE4C0D`, it should be obvious that this is not the proper Mattermost theme format (Mattermost has at least 20 different color codes instead of just 8) and not even possible for me to save this setting to prevent things like:

![bildschirmfoto 2016-03-02 um 11 32 51](https://cloud.githubusercontent.com/assets/944459/13457937/fd465f16-e06a-11e5-82cc-fa5f74c68ce2.png)
![bildschirmfoto 2016-03-02 um 11 31 35](https://cloud.githubusercontent.com/assets/944459/13457938/fd465502-e06a-11e5-9575-3802a9404b8c.png)

**Comment by lfbrock** [comment]
Thanks @frdmn, 

That makes a lot of sense - we have a ticket to [switch Mattermost themes to name value pairs](https://mattermost.atlassian.net/browse/PLT-2107) and move the Mattermost import box to a separate dialog so it acts more like the import from Slack. (There will be the a link "Share or import themes from Mattermost" above the link to "Import theme colors from Slack"). 

Hopefully this helps make the theme importing more obvious, if you have feedback about the planned design we would love to hear it!

**Comment by frdmn** [comment]
Sounds great! :+1:
