### ISSUE TITLE
permalinks doesn't work on messages

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2316]
currently permalinks doesn't seem to work. When opening the "Permalink" link in a side menu of a message this window pops off:
![bug](https://cloud.githubusercontent.com/assets/5287181/13468293/3e0c1054-e0a2-11e5-9822-871447f894ba.JPG)
Unfortunately without any permalink.

**Comment by lfbrock** [comment]
Hi @finius, what browser and OS are you seeing this on?

**Comment by finius** [comment]
Windows 10 Enterprise, IE 11
![ie](https://cloud.githubusercontent.com/assets/5287181/13469372/6982a6d0-e0a7-11e5-9134-f1341b1764f7.JPG)

**Comment by lfbrock** [comment]
Thanks, filed a [ticket](https://mattermost.atlassian.net/browse/PLT-2194) to fix this
