### ISSUE TITLE
Slash commands that change browser location do not clear post message text on execution

### ISSUE THREAD

**Issue by alanmoo** [mattermost/platform#2319]
Summary: Slash commands that change browser location do not clear post message text on execution

Steps to reproduce: 
  1. Use a slash command that changes browser location (right now it seems the only one is `/join`)
  2. Once location changes to the new channel, navigate back to the previous channel (where message was sent from) 

Expected behavior: Post input box should be clear, because the command has been executed

Observed behavior: The join message is still sitting in the input box.

Possible fixes: This seems like a race condition with the react life cycle or something to do with saving draft states. https://github.com/mattermost/platform/blob/master/web/react/components/create_post.jsx#L133-L138 is likely the problem, I'm hoping someone more familiar with that file can solve it faster than I can. I stumbled across this while implementing a `/msg` command.

**Comment by it33** [comment]
Confirm this is an existing bug with `/join`, propose adding an APR ticket

**Comment by alanmoo** [comment]
FWIW, I believe this is a regression from before the command refactor- I had the msg command working before then, but didn't get to submit a PR, and I didn't notice this issue.

**Comment by lindy65** [comment]
Hi @alanmoo 

Thanks for the report.  A Jira ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2227
