### ISSUE TITLE
Is there any way to remove an user from a channel or a private group?

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#2322]
As I see, Manage Members is a team-wide function so you can not use to manage channel/group members, so if I create a channel/group, especially a private group, but added a person by mistake, how can I remove it from this channel/group?

**Comment by chengweiv5** [comment]
oops, I found it there, in "Channel's Setting"

**Comment by BoonHean** [comment]
Where is the "Channel's Setting"? I've created some Private Groups but can't seems to remove a user from the group after adding them.

**Comment by amocrenco** [comment]
![image](https://user-images.githubusercontent.com/28516476/29360839-73bf237e-828d-11e7-8233-4f8b06c48e3f.png)
