### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by sheafferusa** [mattermost/platform#2323]
Guys, your license, specially the way you guys have presented it, is pretty confusing and misleading. I had known it to be MIT by looking at various places posted by mattermost, but after digging it further, I realized that the source code is actually under the AGPL. Only the pre compiled binary version is under 
MIT, which means, any changes done to the software at the source code level will make it AGPL. Is that correct? Specifically what this means is, that I cannot re-brand it and use it under the MIT license as it would actually trigger the AGPL license, correct? Well, if that's the case, then it's pretty much disappointing and for companies, people or startups who want to use it commercially, by linking it to their own private proprietary code, can no longer go forward, without being forced to give away the entire source code under the AGPL license. (Even companies Like Google, Facebook, Apple and pretty much everyone else have had the AGPL banned from the start.) All this indicates that for any developer who wants to integrate this with their own larger but proprietary projects, can't do so, because they would in turn be forced to release all of the project under AGPL. Moreover, my experience tells me that companies or developers would actually prefer to release the code as opensource under MIT out of their own willingness to do so, rather than being forced to do so under the AGPL license. AGPL seriously restricts the reach of a software to a big extent. You can't get an app that's under AGPL listed in Apple's App Store for iOS or Mac. The same is true for Windows App Store. Their license agreements strictly  forbid it. And   that's really sad for a software as good as mattermost. I am sure many would prefer slack itself, rather than mattermost, for this reason only. I am sorry to say this. Although, anyways your software looked great indeed. 

Thanks,
Anime.sh

**Comment by it33** [comment]
Hi @sheafferusa, thanks for your kind words, your interest and for your thoughtful feedback. Last year we adopted [an MIT license for Mattermost releases last year after an extended discussion](https://forum.mattermost.org/t/mattermost-releases-under-mit-license-agpl-does-not-apply/273). I'd invite you to also read [why we created Mattermost as an alternative to proprietary SaaS services.](http://www.mattermost.org/why-we-made-mattermost-an-open-source-slack-alternative/). If you'd like to discuss more please mail licensing@mattermost.com.
