### ISSUE TITLE
MySQL 5.7.11 still doesn't support full text search

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#2324]
Hi, I did learn that, to support Chinese full text search, I have to use MySQL 5.7.6+, refer to http://docs.mattermost.com/install/requirements.html#software

So I did setup MySQL 5.7.11 and gave a try.

I have below 2 statements:

- `测试中文搜索`
- `hello, this is a full text search test`

Did below search:

- `测试`, **nothing found**
- `测试中`, **nothing found**
- `测试中文`, **nothing found**
- `测试中文搜`, **nothing found**
- `测试中文搜索`, **found**
- `测试*`, **nothing found**
- `hell`, **nothing found**
- `hell*`, **nothing found**
- `"hell*"`, **nothing found**
- `hello`, **found**
- `full search`, **found**

So for me, it seems, `*` doesn't help anything, am I miss anything?

**Comment by it33** [comment]
Hi @chengweiv5, thank you for the report, to understand your setup, is the [ngram Full-text parser configuration](http://docs.mattermost.com/install/requirements.html#database-software) applied to your system?

**Comment by chengweiv5** [comment]
Thanks @it33 , apparently I didn't aware that I have configure full text search myself. :-), and it works after having setup ngram full text parser.
