### ISSUE TITLE
mattermost doesn't start anymore when running on a Ubuntu 14.04 LTS virtual machine and a Hyper-V replica test failover is performed

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2329]
Our Mattermost server runs virtually in our production environment on a Hyper-V 2012 R2 host. We are using Hyper-V Replica to keep a replica set on another Hyper-V 2012 R2 server to be able to script up a copy of the production environment as a test environment for development and testing purposes.
While Mattermost runs fine in the production environment, the Mattermost service (which is exactly same vm, with the same ips - beside its virtual network adapter runs in a different "test environment"-vlan, together with all other replicas of the production machines) does not came up anymore. When trying it manually we get the following console output:

> administrator@chat:/home/ubuntu/mattermost/bin$: sudo ./platform 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xb code=0x1 addr=0x0 pc=0x621aaf]
> 
> goroutine 1 [running]:
> github.com/mattermost/platform/utils.TestConnection(0xc820143400)
> 	/home/christopher/go/src/github.com/mattermost/platform/utils/mail.go:82 +0x9f
> github.com/mattermost/platform/utils.LoadConfig(0xc8200e55f0, 0x2a)
> 	/home/christopher/go/src/github.com/mattermost/platform/utils/config.go:171 +0xdbe
> main.main()
> 	/home/christopher/go/src/github.com/mattermost/platform/mattermost.go:57 +0x43
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
> 	/usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1
> 
> goroutine 5 [syscall]:
> os/signal.loop()
> 	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
> created by os/signal.init.1
> 	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
> 
> goroutine 7 [chan receive]:
> code.google.com/p/log4go.ConsoleLogWriter.run(0xc82001ac60, 0x7f490ae991e8, 0xc82002c010)
> 	/home/christopher/go/src/code.google.com/p/log4go/termlog.go:27 +0x80
> created by code.google.com/p/log4go.NewConsoleLogWriter
> 	/home/christopher/go/src/code.google.com/p/log4go/termlog.go:19 +0x6e
> 
> goroutine 18 [chan receive]:
> github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc8201fa000, 0x7f490ae991e8, 0xc82002c010)
> 	/home/christopher/go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/termlog.go:33 +0x69
> created by github.com/alecthomas/log4go.NewConsoleLogWriter
> 	/home/christopher/go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/termlog.go:26 +0xb5
> 
> goroutine 19 [select]:
> github.com/alecthomas/log4go.NewFileLogWriter.func1(0xc820204000)
> 	/home/christopher/go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:87 +0xabc
> created by github.com/alecthomas/log4go.NewFileLogWriter
> 	/home/christopher/go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:119 +0x38b

any clues why the exactly same machine with unchanged properties, doesn't work anymore when it's started as a "clone" of the original vm? 

By the way: It's a single server, so database and app server itself as well as nginx are running on the same machine. But this also works like a charm in production.

**Comment by hmhealey** [comment]
That first stack trace is almost identical to the one in https://github.com/mattermost/platform/issues/2238 so it sounds like your email settings are incorrect. There's a temporary workaround in the comments on that issue that will allow you to get Mattermost running so you can attempt to fix them.

**Comment by finius** [comment]
Indeed - setting "SendEmailNotifications" to "false"  in "../config/config.json" solved the problem.
Thanks for that high speed support - I really appreciate that!
