### ISSUE TITLE
Within the (file) preview, on chrome, an office 2010 file downloads as a zip file

### ISSUE THREAD

**Issue by PSchwarck** [mattermost/platform#2336]
I just put up a new MS Powerpoint 2010 slide show to our server with chrome. When i tried to download the file with chrome (49.0.2623.75 m)  via the preview ( click on the magnifier, then on download), the file gets converted/downloaded to a zip file. After the download finished, I could rename the file extension without any problems.
When i click in the filename directly, i'll get the proper file extension.
I could reproduce this behavior with pptx, xlsx und docx files.

My tests with firefox (v 44.0.2), IE 11 went smooth.

**Comment by lfbrock** [comment]
Does anyone from the community have Powerpoint 2010 to confirm this issue? 

We tested with 2011 and 2016 and everything seemed to work fine, so just want to confirm it's an issue with 2010 and also check if there are any other versions this affects.

**Comment by PSchwarck** [comment]
We tested this with office 2016 docs on chrome 48.0.2564.116 m as well with the same issue. 

To clear things up: this just goes wrong on chrome, when in file preview mode. Anything else works well.

**Comment by lfbrock** [comment]
@lindy65, I believe you tested on office 2016? Can you confirm what browser you tested on?

@PSchwarck, can you provide a screenshot of what it looks like when you upload and then download the file? Is the Mattermost preview showing a powerpoint icon on the file?

**Comment by lindy65** [comment]
@lfbrock Yes, I tested in Office 2016, Chrome v48.0.2564.116 m

**Comment by PSchwarck** [comment]
@lindy65  
I just re-checked upload/download of the files with chrome on our system (Enterprise Edition ET7), same issue. I tested with the pre-release.mattermost.com/core and couldn't re-produce this behavior.

![mm_fehler01](https://cloud.githubusercontent.com/assets/16940971/13636417/17568cb8-e602-11e5-9d8c-523372bf5e50.JPG)
![2016-03-09 14_16_25-zsandkiste - finius group flurfunk der finius group](https://cloud.githubusercontent.com/assets/16940971/13636432/2f77bae2-e602-11e5-8ff1-ba3d23220cc9.png)
![2016-03-09 14_16_47-speichern unter](https://cloud.githubusercontent.com/assets/16940971/13636442/3ca4c1ba-e602-11e5-9457-883089916820.png)

**Comment by PSchwarck** [comment]
Hi @lindy65  , 

i just double checked this issue with the rc1 server on http://rctesting.reddogsofwar.com/rc-210 und could not reproduce this behavior. So I assume... everything is fine with the new release and we can close this issue.

**Comment by lfbrock** [comment]
Thanks @PSchwarck, yes it looks like it was an issue with v2.0 that has since been fixed. If it shows up again after next release feel free to re-open this.
