### ISSUE TITLE
Unicode emojis expands in code blocks.

### ISSUE THREAD

**Issue by Ticki** [mattermost/platform#2337]
**Reproduction**: Write

```
`♥☺™®`
```

In any chat, top-level or sub-thread.

**Expected behavior**: This should not expand to Mattermost emojis, instead it should preserve its Unicode form.

**What happens**: It expands to a slightly modified (note that `♥` and `:heart:` expands to different emojis) Mattermost emoji.

**Tested on**: 2.0.0 and v1.4.0.

**Comment by lfbrock** [comment]
Thanks @Ticki, we have a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1818) to track this issue.
