### ISSUE TITLE
Android App 1.14 verified on Sony Xperia Z5 Compact with Android 5.1.1

### ISSUE THREAD

**Issue by reach3r** [mattermost/platform#2341]
| Version | Device & OS | Issues | Tester | Date | 
|:--- |:--- |:--- |:--- |:--- |
| 1.14 | Sony Xperia Z5 Compact, Android 5.1.1 |  | [@reach3r](https://github.com/reach3r) | 2016-03-07 |

**Comment by lfbrock** [comment]
Thanks for helping test!

**Comment by it33** [comment]
Device added https://github.com/mattermost/android/commit/5a6d810bde4607cc762f94e3c105355606b65764
