### ISSUE TITLE
Android: Demo (intro) can't be completed

### ISSUE THREAD

**Issue by SlavikCA** [mattermost/platform#2342]
STEPS TO REPRODUCE
- Install and open the app
- Click on the "flashing circles", which introduces you to the app
- Open Left side bar. Try to click on the "flashing circle" there (see screenshot)
- Defect: it is unclickable

MATTERMOST ANDROID APP VERSION
- Android app v1.14 

DEVICE TYPE
- Motorola Nexus 6 

ANDROID OPERATING SYSTEM VERSION
- Android 6.0.1

![screenshot_20160307-012432](https://cloud.githubusercontent.com/assets/6293679/13565361/7b137ebe-e404-11e5-9396-c4e791987b4b.png)

**Comment by lindy65** [comment]
Thanks for the report @SlavikCA 

Ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2248
