### ISSUE TITLE
"Unable to upload image file. File is too large." while file is way smaller than file size limit

### ISSUE THREAD

**Issue by frdmn** [mattermost/platform#2343]
Hello,

I'm using the latest Omnibus installation (version 2.0) and just ran into an issue while trying to upload an image via drag and drop. The image has a file size of about 9 MB while our our `MAX_FILE_SIZE` directive is set to default (50 MB):

![](http://up.frd.mn/pSA2kD1TML.png)

---

```javascript
Object
  detailed_error: "File exceeds max image size."
  id: "api.file.upload_file.large_image.app_error"
  is_oauth: falsemessage: "Unable to upload image file. File is too large."
  request_id: "cuo49n9uifdp3ynrgp5djwjt5w"
  status_code: 500
  __proto__: Object
    __defineGetter__: __defineGetter__()
    __defineSetter__: __defineSetter__()
    __lookupGetter__: __lookupGetter__()
    __lookupSetter__: __lookupSetter__()
    constructor: Object()
      hasOwnProperty: hasOwnProperty()
      isPrototypeOf: isPrototypeOf()
      propertyIsEnumerable: propertyIsEnumerable()
      toLocaleString: toLocaleString()
      toString: toString()
      valueOf: valueOf()
      get __proto__: get __proto__()
      set __proto__: set __proto__()
```

---

```shell
❯ ls -la /Users/jonas/Desktop/huge.png
-rw-r--r--@ 1 jonas  staff  9885013  5 Mär 14:25 /Users/jonas/Desktop/huge.png
```

I also found these related Jira tickets, but I am not sure if they report the same issue:

https://mattermost.atlassian.net/browse/PLT-1431
https://mattermost.atlassian.net/browse/PLT-1280

Thanks for any input :)

**Comment by lfbrock** [comment]
Hi @frdmn, 

Yes those tickets are talking about the same issue - the image height/width is too large, and that's what is causing the error. 

This [ticket](https://mattermost.atlassian.net/browse/PLT-2142) should increase the max image height/width size, and I also created a [ticket](https://mattermost.atlassian.net/browse/PLT-2242) to make the error message more clear since it's a little confusing right now.

**Comment by frdmn** [comment]
@lfbrock Thanks for the reply! :+1: 

So if I got you right, there is no manual workaround for this at the moment and I have to wait for an update from you guys?

**Comment by lfbrock** [comment]
You can try uploading the file as a zip file instead, but I don't think there's an easy way to upload the original file at the moment. We plan to have the maximum file dimensions updated for v2.2.
