### ISSUE TITLE
Do not treat end parenthesis as part of a URL in messages

### ISSUE THREAD

**Issue by maximd** [mattermost/platform#2361]
Hi,

There seems to be a bug with the URL parser that creates HTML links when a message is posted.

* Steps to reproduce: create a message with a URL between parenthesis, like
```
(see http://forum.mattermost.org/t/gitlab-sso-doesnt-work-when-joining-public-teams/898/12)
```
* Expected behavior: not having the end parenthesis part of the auto-generated href link
* Observed behavior: the end parenthesis is part of the auto-generated href link. This makes the link incorrect. The workaround is to edit the message to put a space between the last character of the URL and the end parenthesis

Version used: mattermost 2.0 build 5950 as shipped with gitlab 8.5.4

Thank you for your help!

**Comment by lindy65** [comment]
Thanks for the report @maximd 

Ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2247
