### ISSUE TITLE
User login with Gitlab SSO brings the wrong mattermost user

### ISSUE THREAD

**Issue by rudineirk** [mattermost/platform#2363]
We have a issue with the user being able to login in mattermost with a user other than his own (a random user, he can't choose). It happened when we tried to change the gitlab server mattermost was using as Single Sign On (SSO), which changed the `Gitlab > Secret` and `Gitlab > Id` configurations.

We installed the mattermost without using gitlab omnibus (mattermost installed independently). It was working perfectly before we tried to migrate to the other gitlab server.

The user can login as the correct user in gitlab, only in mattermost he shows (and posts) as the wrong user.

**Comment by lfbrock** [comment]
Hi @rudineirk, 

What version of Mattermost are you using?

**Comment by lfbrock** [comment]
Can you also double check that the endpoints listed in Mattermost under System Console > GitLab Settings are correct?

It should your gitlab URL followed by the following:
Auth Endpoint: /oauth/authorize
Token Endpoint: /oauth/token
User API Endpoint:  /api/v3/user

**Comment by rudineirk** [comment]
I'm using version 2.0.0, I checked the urls, they are correct (both on the new server and the old one)

I forgot to mention, when I switched back to the old server (with the old `Gitlab > Secret` and `Gitlab > Id` configs) the problem stopped

**Comment by rudineirk** [comment]
I made some new tests, revoking the application SSO keys (id and secret) on the original server works as it's supposed to, no problems with authentication.

**Comment by rudineirk** [comment]
I don't think it's related, but the original server was installed using the omnibus installation and it's on the 8.5.1 version.

The new server was installed using [sameersbn/gitlab](https://hub.docker.com/r/sameersbn/gitlab/) docker image, and it's on version 8.5.4

**Comment by rudineirk** [comment]
Upon better inspection I found something interesting, not all users were having the problem, only the ones in which changed the gitlab user numeric id (same username, different user id)

I think it's related to the way mattermost is using the gitlab user id, maybe [this field](https://github.com/mattermost/platform/blob/master/model/gitlab/gitlab.go#L23) should not exist, mattermost should only use the gitlab user name

**Comment by jwilander** [comment]
Hi @rudineirk, I understand your issue and I agree that it's something that we need to address. I've created a Jira ticket [here](https://mattermost.atlassian.net/browse/PLT-2393) to track and discuss this issue with core team.

**Comment by lfbrock** [comment]
Closing this issue, will track it in Jira
