### ISSUE TITLE
TypeError: e is null

### ISSUE THREAD

**Issue by tvld** [mattermost/platform#2378]
Ubuntu 14.04, Firefox 44.0.2 when using Mattermost 2.1 on https://pre-release.mattermost.com , whenever I drag / resize a FF window, I get:

![type-error](https://cloud.githubusercontent.com/assets/986182/13600679/db99df0e-e52a-11e5-8b04-bc6c1f228d45.png)

**Comment by lindy65** [comment]
Thanks for the report @tvld 

Ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2267
