### ISSUE TITLE
Anyone can change Channel Headers

### ISSUE THREAD

**Issue by tvld** [mattermost/platform#2381]
I don't own the Channel and am just a visitor... but I can change the Channel headers or all channels in MM 2.1 pre-release install... Is that intended behaviour?

![channel_header](https://cloud.githubusercontent.com/assets/986182/13602411/cbc25e92-e536-11e5-8838-cc744034dd4d.png)

**Comment by lfbrock** [comment]
Hi @tvld, 

That is intended behaviour at the moment, but we're considering adding more detailed permissions around channels so teams can choose who should have permission. 

Please add a feature suggestion as per above instructions if this is something you would like to see?

**Comment by urban-idler** [comment]
You guys need to lock down the channel headers.  these are functionally the data model for community discussion.... and no organization lets their data model be edited by anyone -- especially when the intent is for the channel to be open to the public.

Please allow users to lock the public channel name and headers.  There is no function to everyone in a public channel to be able to change the name of the channel
