### ISSUE TITLE
Join Channel Spam

### ISSUE THREAD

**Issue by tvld** [mattermost/platform#2382]
Not sure if you appreciate all my first-time-visitor-observations... but here is another one.. ;)

If I just have a glance at a channel, MM immediately states that I joined the channel. First, it is not true, I did not join, just had a peek. Second, with so many people peeking.... what are we peeking at ? ;))))

Maybe send that message only after I post my first message or so?  Or even, click on a "join" button?

![join-channel resized](https://cloud.githubusercontent.com/assets/986182/13603568/747f3314-e53e-11e5-918f-b84a2af307d1.png)

**Comment by lfbrock** [comment]
Hi @tvld, 

Thanks for the feedback, can you upvote this feature idea here?
https://mattermost.uservoice.com/forums/306457-general/suggestions/10529445-add-option-to-disable-join-messages

**Comment by tvld** [comment]
No... as I can only vote 3x and I have to save my votes ;)  Besides, this is more like a bug to me .. I really did not intend to join that channel ...

**Comment by it33** [comment]
Hi @tvld, your opinion is valued, we just ask your help to keep the feedback on feature ideas in one place so your feedback can have the greatest impact. Also, [there's another feature idea to allow the viewing of channels before joining](https://mattermost.uservoice.com/forums/306457-general/suggestions/12877668-ability-to-view-channels-without-joining)
