### ISSUE TITLE
performance: clicking on message permalink reloads entire page

### ISSUE THREAD

**Issue by fjarlq** [mattermost/platform#2393]
Browser client: Chrome 49.0.2623.75 on OS X 10.11.3
Mattermost version: both 2.0.0 and today's Mar 8 build (on pre-release.mattermost.com)

Steps to reproduce:
1. Scroll up and find some old message in a channel
2. Copy that message's permalink
3. Paste it into the channel
4. Click on the pasted message permalink

Expected behavior:
Mattermost should gracefully redraw only the channel pane to show the linked message and its context.

Observed behavior:
Mattermost (at least in Chrome) reloads the entire page from scratch, which is relatively slow (~2 seconds load time) and visually distracting.

**Comment by lfbrock** [comment]
Thanks @fjarlq, we have a ticket [here](https://mattermost.atlassian.net/browse/PLT-1236) to track this issue in Jira. 

If anyone would like to work on this, let us know and we'll consider it for accepting pull requests.
