### ISSUE TITLE
Dockerfile contains 404

### ISSUE THREAD

**Issue by peasead** [mattermost/platform#2395]
Line 37 of the Dockerfile contains:
```
ADD https://github.com/mattermost/platform/releases/download/v2.0.0-rc2/mattermost.tar.gz /
```
but it should be:
```
ADD https://github.com/mattermost/platform/releases/download/v2.0.0/mattermost.tar.gz /
```
Need to remove the ...-rc2 from the version number as -rc2 is a 404.

**Comment by lfbrock** [comment]
Thanks @peasead, if you'd like to contribute a fix we'd welcome a pull request on this

**Comment by peasead** [comment]
I can do that, I just wasn't sure if this was pull request material or if it'd just be easier to fix.

No worries at all, I'll submit a pull request.
