### ISSUE TITLE
Custom the default teammate name display

### ISSUE THREAD

**Issue by Lujeni** [mattermost/platform#2402]
Hello,

The default teammate name display is `username`.
There is a way to change this default settings ?

For example, use the `fullname` value for everyone.

Thanks

**Comment by lfbrock** [comment]
Hi @Lujeni, 

I think we want to add something like this at some point - we were thinking of adding a section to the System Console to let administrators set default display settings for their site. It would be useful to have this for teammate name display, theme colors, and language at the very least. 

In the meantime, if you want to contribute a feature idea on the topic so others can upvote it, you can do so via the instructions above.
