### ISSUE TITLE
Tapping "search" does not move focus into searchbox

### ISSUE THREAD

**Issue by jkuchar** [mattermost/platform#2421]
On mobile version (tested on iPhone and in Chrome dev tools) when I click on search icon focus, transition is made to second screen with search field and search results, however focus i nowhere. Should be in search field.

**Comment by lfbrock** [comment]
Thanks @jkuchar, would you be interested in working on an accepting pull requests ticket for this?

**Comment by jkuchar** [comment]
To be honest I do not have much experience with react so I do not know where and how to add event listener to fire focus method. It will probably take me ages to find right place.

Maybe if you guide me a little. :-)

**Comment by lfbrock** [comment]
No worries, I don't have any quick tips on this one (sometimes it even takes us a while to find the right place with the way the search stuff is now) but made a [ticket](https://mattermost.atlassian.net/browse/PLT-2347) to track the issue :)
