### ISSUE TITLE
by combining two ES6+ features – arrow functions and property initializers – opt-in binding to the component instance

### ISSUE THREAD

**Issue by roughsoft** [mattermost/platform#2423]
when we define components using the ES6+ class syntax, it would seem that we need to manually bind instance methods wherever we want this behavior:

// Manually bind, wherever you need to
class PostInfo extends React.Component {
  constructor(props) {
    super(props);
    // Manually bind this method to the component instance...
    this.handleOptionsButtonClick = this.handleOptionsButtonClick.bind(this);
  }
  handleOptionsButtonClick(e) {
    // ...to ensure that 'this' refers to the component instance here.
    this.setState({showOptionsModal: true});
  }
}
Luckily, by combining two ES6+ features – arrow functions and property initializers – opt-in binding to the component instance becomes a breeze:

class PostInfo extends React.Component {
  handleOptionsButtonClick = (e) => {
    this.setState({showOptionsModal: true});
  }
}
The body of ES6 arrow functions share the same lexical this as the code that surrounds them, which gets us the desired result because of the way that ES7 property initializers are scoped. 

https://babeljs.io/blog/2015/06/07/react-on-es6-plus

**Comment by crspeller** [comment]
Tat is cool! Thanks for pointing it out! However, when this problem is eventually solved we would need to edit every function to remove the cruft. With the current method all we have to do is delete a few lines from the constructor. It's not that hard to bind every function in the constructor anyway.

Thanks!
