### ISSUE TITLE
channel search isn't case-sensitive for hashtags but is for regular search requests

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2425]
When searching for a hashtag there seems to be no case sensitivity, which is good. But when searching for terms with upper case letters, the results can't be found if one was only entering lower case letters instead in the search box.

**Comment by lfbrock** [comment]
Hi @finius, what database are you searching on? 

It does not seem to be case sensitive for me:

<img width="400" alt="screenshot 2016-03-14 13 54 40" src="https://cloud.githubusercontent.com/assets/9354841/13754159/53deedb8-e9ec-11e5-89cc-78c5d99fbceb.png">

**Comment by PSchwarck** [comment]
Hi @lfbrock,
we are on Postgres, following the standard install procedure.

**Comment by lfbrock** [comment]
Hi @finius, 

I tested on both Postgres and MySQL and I couldn't reproduce the issue - maybe try copying this over to the troubleshooting forum as well to see if anyone there has had similar issues? 

If anyone else from the community is seeing this issue, please post here as well to let us know.

**Comment by finius** [comment]
Well, I must confess, I am also no able to reproduce this, as @PSchwarck reported this issue to me.
But anyway, the search behaves somekind of strange.
For example:
I just joined a channel in our local setup and choosed a message from patrick to search for the containing word "Gerüchteweise" as you can see in the screenshot attached. Therefore I tried several variations of incomplete search terms like **Ge** or **Ger*** or **ger** but none of them lead to a result.
Only when I complete the string to **Gerüchteweis** the message is found, but the string is not marked within the result. Not until the search string is fully matching the word, which is not very satisfying. 
<img width="1439" alt="bildschirmfoto 2016-03-15 um 19 02 43 kopie" src="https://cloud.githubusercontent.com/assets/5287181/13788975/5e585dbe-eae2-11e5-9e85-b6922fb47442.png">
I would strongly rely that even brackets of words would have been found. But I don't know if this is a bug or feature. Further I have no idea if umlauts are somekind of problematic. However, IMHO this is not that user friendly...
But even more strange is the following:
In the same channel i enter **a** as a search string and get many results. (Which seems to proove that even word-parts could be found?!). Same behaviour with the letters **s** and **d**. 
But when I search for the string **f** there is no entry found even though the letter f is used many times.

Any explainations on that?

**Comment by lfbrock** [comment]
Yes - there's some issues with search right now, it just uses the default database search. However I tested on postgres (v2.1) searching for Gerüchteweis with Ge* and Ger* and it seemed to work fine for me, so I'm not sure why it's not working properly in your case. It might have something to do with how your database encoding is set up. 

For searching for single letters - I believe the database search is supposed to require at least 3 letters so I'm surprised it's finding any results for those cases. 

You can read more about current search limitations in our [documentation](http://docs.mattermost.com/help/getting-started/searching.html#search-notes-and-known-issues). We also have a few tickets to try and improve search using the default database search, and we are considering adding advanced search in Enterprise version in the future.

**Comment by PSchwarck** [comment]
@lfbrock @finius 
Hi all,

i just retestet the following. results in the pictures. (remember we are on EE 2.0, myabe some stuff get "fixed" today ;D ).

![ff_bug_002](https://cloud.githubusercontent.com/assets/16940971/13810127/814dba94-eb6e-11e5-8e05-3883ed8e109e.jpg)
![ff_bug_003](https://cloud.githubusercontent.com/assets/16940971/13810129/83f7d18a-eb6e-11e5-951f-eb5e34bd13f0.jpg)
![ff_bug_004](https://cloud.githubusercontent.com/assets/16940971/13810133/85a2fd98-eb6e-11e5-9378-059acff9698e.jpg)

**Comment by lfbrock** [comment]
Thanks @PSchwarck, glad to see it seems to be working now :)

**Comment by PSchwarck** [comment]
Hi @lfbrock, 
well this is not what i wanted to say with those screenshots. 
Most searches should show almost the same messages. 
2nd & 3rd Pic should show the search of pic No. 1,or aat least the more recent ones. But it doesn't.
- search string with wildcard (*) shows different entries, than the full search
- sometimes th search IS case-sensitive, sometimes its not.

all in all... its pretty "weird". :-(

**Comment by lfbrock** [comment]
Ah I see, so the problem is that the Mar 16, 11:36 AM and the Mar 14, 5:14 PM message in screenshot 1 doesn't show up in screenshots 2 and 3?

Searching without wildcard * on Postgres is a little strange - it will only bring back words with certain endings. For example in English, if I search "test" on Postgres it would bring back results such as test, testing, and tested but not "testify". If I search for "test*", if would bring back all words regardless of the endings. So generally, searching with * will be more reliable. 

That being said, I'm not sure why your search results seem to be missing messages in screenshots 2 + 3 that should be there chronologically. I'm trying to reproduce this, but haven't had luck so far.
