### ISSUE TITLE
Keyword webhook action isn't triggered when a bot posts the keyword.

### ISSUE THREAD

**Issue by cyruslopez** [mattermost/platform#2428]
When an outgoing webhook is set up to trigger based on a keyword, it only is triggered when a human uses the keyword. When a bot makes a post that has the keyword, the webhook action isn't triggered. This limits automation possibilities.

Steps to Reproduce:
1. Set up an outgoing webhook with a keyword of your choice.
2. Have a bot post a message via an incoming webhook to your channel with the keyword that should trigger the outgoing webhook.
3. Nothing happens. :(

Expected Behavior:
Webhooks should be triggered regardless of what the source of the keyword is (human or bot).

**Comment by lfbrock** [comment]
Hi @cyruslopez, we're open to someone adding this and have an [accepting pull requests ticket](https://mattermost.atlassian.net/browse/PLT-2171) on it. 

There's a few things to think about if it is implemented, you can see the past discussion [here](https://github.com/mattermost/platform/issues/1901).
