### ISSUE TITLE
Unable to change my profile picture

### ISSUE THREAD

**Issue by khawerrind** [mattermost/platform#2434]
**Steps to reproduce:**
1. Login in to account
2. Go to account settings
3. Cick on edit profile picture

**Expected behavior:**
When clicking on edit profile picture the modal box of the account settings should have a scroll. But currently it does not have a scroll and the buttons for changing profile picture are hidden. 

![IMAGE]
(https://i.imgur.com/4NTG13l.png)

Chrome: Version 48.0.2564.109 (64-bit) 
Resolution: 1366 x 768
OS: Ubuntu 15.10 (Wily Werewolf)

**Comment by lfbrock** [comment]
HI @khawerrind, if I make an accepting pull requests ticket for this would you be interested in working on it? 

Ubuntu is not a [supported OS](http://docs.mattermost.com/install/requirements.html#software-requirements) at the moment, but if community members want to help work towards supporting it we would welcome the contributions.

**Comment by khawerrind** [comment]
I am bit confused. Are you talking about desktop application or web version? Because the issue which i have submitted is related to web version. The web version should run same in Chrome no matter if Chrome is installed in Ubuntu or Mac. 

In case if you are talking about web version then i will be happy to work on it.

**Comment by lfbrock** [comment]
I was talking about the web version - It should be the same, but I can't reproduce the issue on Chrome on Mac (48.0.2564.116 (64-bit)) so I suspect it might only be on Ubuntu (although I could be incorrect).

I made an [accepting pull requests ticket](https://mattermost.atlassian.net/browse/PLT-2360) if you'd like to look into it.

**Comment by vladimirprieto** [comment]
almost the same happened to me on Ubuntu 16.04.  the solution a found was:

[docs say](https://docs.mattermost.com/install/install-ubuntu-1604.html#configuring-mattermost-server):

> Click Files > Storage and change Local Storage Directory from ./data/ to /mattermost/data

but i did:

from ./data/ to /opt/mattermost/data

and it works!

BTW:

there's antoher typo on docs:

it say:

> sudo -u mattermost /.platform

and should be:

> sudo -u mattermost ./platform

;)

**Comment by Lc0rE** [comment]
Thumb up for @vladimirprieto. Came here for the same reason and it seems that correcting `/opt/mattermost/data` the issue is fixed (at least for us). Another thumb up for the `sudo -u mattermost ./platform`

**Comment by jasonblais** [comment]
Thanks @vladimirprieto and @Lc0rE,

would either of you like to make an update in our docs? On the top right corner, you can click "Edit", which lets you edit changes and submit them as a pull request.

![image](https://cloud.githubusercontent.com/assets/13119842/22371868/c60f9ee8-e467-11e6-854b-16287b7e505b.png)

**Comment by vladimirprieto** [comment]
didn't saw tha Edit link.

done.

;)

**Comment by jasonblais** [comment]
Thanks @vladimirprieto! 👍
