### ISSUE TITLE
Link to the latest version dead

### ISSUE THREAD

**Issue by Sathors** [mattermost/platform#2437]
I am currently following the guide to install in production, and I noticed that the link in the [download page](http://www.mattermost.org/download/) to download the latest binary is dead: [link](https://github.com/mattermost/platform/releases/download/v2.0.0/mattermost.tar.gz).

Running linkchecker on http://www.mattermost.org actually gives 72 errors 404.

Thanks for the good work!

**Comment by it33** [comment]
Whoops! Thanks @Sathors, looking into this,

**Comment by it33** [comment]
Fixed,

**Comment by Sathors** [comment]
Thanks @it33, but the link in the documentation is still pointing to the broken link.

Maybe in the documentation you could just redirect to the download page, so as not to have two copies of the same link, leading to inconsistencies.

Do you want me to open a new issue, or you will reopen this one?
