### ISSUE TITLE
Video play is triggered unexpectedly

### ISSUE THREAD

**Issue by mbats** [mattermost/platform#2438]
When a youtube video is integrated to a channel, sometimes the play action is triggered even if the video is not anymore visible on the screen.

**Comment by lfbrock** [comment]
Hi @mbats, can you check what version of Mattermost you're using? (You should be able to find it in "About Mattermost" in the main menu).

**Comment by mbats** [comment]
Mattermost 1.3.0
Build Number:4896
Build Date:Mon Dec 14 23:57:09 UTC 2015
Build Hash:f51d45f6cba0e5a1249146afe4a1c78cf32b7598

**Comment by lfbrock** [comment]
Thanks @mbats, I think this bug should be fixed if you upgrade to a newer version. It looks like it should be fixed in versions 1.4 and above.

**Comment by mbats** [comment]
Good news! Thanks for your quick feedback!
