### ISSUE TITLE
Option to disable direct messages

### ISSUE THREAD

**Issue by zsoca8711** [mattermost/platform#2440]
Hey All,

we are considering using mattermost but we look to disable direct messages completely. I've tried searching and (not surprisingly) there is no option to disable direct messages.
I'm not familiar with mattermost source code, neither with golang or react, but would be interested in this feature is something you consider worth adding (maybe as an admin option)?
Can someone estimate how long developing this may take?

We may end up developing this for ourselves, if we need to, but would be interested in opinions and an expert estimate on the complexity of the task.

**Comment by zsoca8711** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/12954666-disable-direct-messages

**Comment by zsoca8711** [comment]
Hello @mattermod 

I'm not looking to implement this feature until a business-decision is taken to use mattermost. But when that decision is taken, we will have to implement it ourselves if it is not implemented before.
Due to the fact mattermost is opensource, we are not looking at the lack of this feature as a blocker, but i cannot give you an estimate when we will get going with mattermost. It may be easily months.

However, if the decision is taken, i'll get back to this issue and see what happened. The purpose of the issue and the idea was to get the ball rolling - on way or the other :)

**Comment by lfbrock** [comment]
Thanks @zsoca8711, appreciate you bringing up the idea - I can think of a couple cases where people may want this. If there's enough interest from the community this seems like a feature we would consider adding or accepting pull requests on, so it's great to get a uservoice thread started on it.

**Comment by TheSeanBrady** [comment]
This is definitely something my client is interested in. Where would one start for a pull request here? If I get something started will the community help me out? I'm pretty new to Go in general.

**Comment by jasonblais** [comment]
Hey @TheSeanBrady, thanks for the feedback, appreciate it.

I'm curious to hear what your client is hoping to achieve by disabling direct message channels? Just want to make sure the the setting would address what they're looking for.

**Comment by TheSeanBrady** [comment]
Customer is a call center, doesn't want chit-chat between agents while
they're on the phone. They do want supervisor-to-agent communications,
agent to IT/HR communications, and most importantly bots. I believe that
customized bots will be a killer app in this environment, providing low
friction bot-based services to the agents. The first example would be a
break/lunch bot, notifying supervisors when they need to go to
breaks/lunch, etc.

**Comment by TheSeanBrady** [comment]
So out of curiosity, where would one go to get started on something like this. I'm still going over the code to figure out what does what...

**Comment by jasonblais** [comment]
> doesn't want chit-chat between agents while they're on the phone

It could make sense to disable direct messages for that case, but the agents could still create private groups to chit-chat with each other.. Unless you'd disable private group creation too?

**Comment by TheSeanBrady** [comment]
Right. Basically it would end up being a security layer, if that makes
sense. I could see some pretty granular permissions there.

**Comment by jamesquilty** [comment]
I have an Educational context where students should not be able to create private groups or direct messages. The current version of Mattermost allows me as Sys Admin to disable the creation of private groups. Direct messages are the same as private groups in out context and we'd like to disable those also.

This seems to have stalled on the feature idea forum despite a fair number of supporters, and there hasn't been the ticket accepting pull requests. Can we, at the very least, have the latter?

**Comment by harshilsharma63** [comment]
@zsoca8711 would this Mattermost plugin be of help - https://github.com/Brightscout/mattermost-plugin-disable-dm ?

**Comment by hairmare** [comment]
The disable-dm plugin only disables sending of DMs. It doesn't remove the user interface parts of direct messaging but it does deny all DMs. When a DM gets denied it looks like this:

![image](https://user-images.githubusercontent.com/116588/57690826-d8479600-7642-11e9-98dc-3f930c688796.png)

To make this viable for an educational context it probably needs some more polish. It does work as advertised in that it makes sending DMs impossible.

**Comment by jasonblais** [comment]
@hairmare Thank you for trying out the plugin and for the feedback, appreciate it! Would you be open to creating an issue at https://github.com/Brightscout/mattermost-plugin-disable-dm? That way we can keep track of bugs and improvements of the plugin in one place.

**Comment by hairmare** [comment]
@jasonblais I created https://github.com/Brightscout/mattermost-plugin-disable-dm/issues/5 about polishing the UI in the case of disabled DMs.
