### ISSUE TITLE
can not run with docker

### ISSUE THREAD

**Issue by chenxizhang** [mattermost/platform#2443]
Hi, buddy

when I run the command "docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform" , then I try to test with "http://localhost:8065", It does't work,why ?

thank you

**Comment by notxcain** [comment]
Confirmed `docker logs mattermost-dev` last line is 
```
starting platform
/docker-entry.sh: line 110: cd: /mattermost/bin: No such file or directory
```

**Comment by chenxizhang** [comment]
Yes, You are right

**Comment by crspeller** [comment]
Should be fixed now. Thanks!

**Comment by chenxizhang** [comment]
it's work, thanks
