### ISSUE TITLE
[Help Wanted] Japanese translation

### ISSUE THREAD

**Issue by it33** [mattermost/platform#2444]
If anyone is interested in working on a Japanese translation, please reply here? 

Please feel free to speak Japanese, [you can see other threads speaking non-English as well](https://github.com/mattermost/platform/issues/2221)

[Translation guide here](http://docs.mattermost.com/developer/localization.html). Please also join the [localization channel](https://pre-release.mattermost.com/core/channels/localization), as there are new tools being developed to make translation easier.

**Comment by Niklane** [comment]
do you have any plan for korean(ko) translation? not suitable for this thread(issue), i want to traslate mattermost to korean.

**Comment by it33** [comment]
@Niklane, a new thread has been created for [Korean translation](https://github.com/mattermost/platform/issues/2447)

**Comment by wolf-dog** [comment]
Hi, I'll be glad to help.

**Comment by ryoon** [comment]
I am creating ja.json files now.

**Comment by it33** [comment]
Thanks @ryoon! When you have time, I'd like to invite you to join the [Localization channel.](https://pre-release.mattermost.com/core/channels/localization) 

In that channel you can: 

1. Hear about the latest information on the localization process. 
2. See how other languages have been added
3. Ask questions about the process

Thank you so much for your help!

**Comment by ryoon** [comment]
How to join the localization channel?

**Comment by enahum** [comment]
Hi @ryoon click [here](https://pre-release.mattermost.com/core/channels/localization) to join the channel

**Comment by ryoon** [comment]
Hi, @enahum 
Thank you.
I have clicked 'Creste one now' link and gotten 'Loading...' like infinite loop.
Something goes wrong for me.
I have tested with latest MS Internet Explorer, MS Edge, Mozilla Firefox and Google Chrome.

**Comment by sebzur** [comment]
I've got similar problem.Your link (https://pre-release.mattermost.com/core/channels/localization) renders an empty page (only footer is visible).  

When I switched to `https://pre-release.mattermost.com/core/login` and selected 'Create one now' to sign up (which redirects to `https://pre-release.mattermost.com/signup_user_complete/?id=`) there's 
HTTP500 with `https://pre-release.mattermost.com/api/v1/teams/get_invite_info`.

**Comment by enahum** [comment]
Hey guys I've submitted a PR to fix the create account issue, lets wait until its reviewed and merged.

Thanks for bringing this up.

**Comment by ryoon** [comment]
Hi,
Now I can join to localization channel.
Thank you.

**Comment by terukizm** [comment]
Hi, I would like to join this project.

@ryoon 

私もお手伝いできれば嬉しいです。
(I hope I can help with your translation.)

**Comment by ryoon** [comment]
@terukizm Could you help me on Mattermost Pootle? The link is provided in localization channel.

**Comment by ubiko** [comment]
Hey, I want my company to use this but they won't until there's a japanese version. I'm available for full translation.

**Comment by ryoon** [comment]
@ubiko I had completed to translate all strings into Japanese on Mattermost Pootle yesterday. 
However I have not tested it yet with Mattermost program.
If you find my mistakes, could you fix my mistakes on Pootle?

**Comment by ryoon** [comment]
I have submitted pull request for Japanese translation at #2700. Could anyone review my strings?

**Comment by ryoon** [comment]
I have submitted pull request for updated tJapanese translation at #2714.
Could anyone review my strings?

**Comment by jasonblais** [comment]
Japanese was released [with Mattermost v3.0 in May](https://docs.mattermost.com/administration/changelog.html#release-v3-0-3) - thank you everyone for the wonderful work!

Big thank you to @ryoon who is reviewing new and updated strings as new features are added to Mattermost over time.

If anyone else would like to help maintain the translations, please let us know in our [Japanese community channel](https://pre-release.mattermost.com/core/channels/i18n-japanese) and join the [Mattermost Translation Server](http://translate.mattermost.com/ja/mattermost/) to contribute.
