### ISSUE TITLE
Android App 1.14 verified on Google Nexus 5X with Android 6.0.1

### ISSUE THREAD

**Issue by C0rn3rphr34k** [mattermost/platform#2445]
| Version | Device & OS | Issues | Tester | Date | 
|:--- |:--- |:--- |:--- |:--- |
| 1.14 | Google Nexus 5X, Android 6.0.1 | | [@C0rn3rphr34k](https://github.com/C0rn3rphr34k) | 2016-03-16 |

**Comment by lindy65** [comment]
Thanks @C0rn3rphr34k, results added to [Android repo](https://github.com/mattermost/android/blob/master/DEVICES.md)
