### ISSUE TITLE
[Help Wanted] Korean translation

### ISSUE THREAD

**Issue by it33** [mattermost/platform#2447]
If anyone is interested in working on a Korean translation, please reply here? 

Please feel free to speak Korean, [you can see other threads speaking non-English as well](https://github.com/mattermost/platform/issues/2221)

[Translation guide here](http://docs.mattermost.com/developer/localization.html). Please also join the [localization channel](https://pre-release.mattermost.com/core/channels/localization), as there are new tools being developed to make translation easier.

**Comment by Niklane** [comment]
i wanna help translation.

**Comment by enahum** [comment]
@Niklane you can start using this http://186.202.167.109/ko/mattermost/ to start translating to Korean.

Keep in mind that theres a really big chance that this server is going to change to another location soon but don't let that prevent you from moving forward in the meantime :)

**Comment by sappho192** [comment]
Count me in, please. I'm Korean and have experience with translation based on .po file.

**Comment by patriz** [comment]
Want to join Korean translation team if still available. Have been implementing super simple plugin for slack with golang (https://github.com/patriz/slack-eve) And pushing commits to Github everyday (actually as often as possible)

**Comment by imkimchi** [comment]
want to Join in this transition. I'm a native korean.

**Comment by Niklane** [comment]
@imkimchi you can use translation system with http://186.202.167.109/ko/mattermost/

**Comment by imkimchi** [comment]
@Niklane already working on it. thx!

**Comment by sngkyu** [comment]
would like to join in the trelation team, if not too late.

**Comment by jasonblais** [comment]
Korean was released [in our August release](https://docs.mattermost.com/administration/changelog.html#languages) - thank you everyone for the wonderful work!

Big thank you to @CometKim who is reviewing new and updated strings as new features are added to Mattermost over time.

If anyone else would like to help maintain the translations, please let us know on our [Korean community channel](https://pre-release.mattermost.com/core/channels/i18n-korean) and join the [Mattermost Translation Server](http://translate.mattermost.com/ko/mattermost/) to contribute.
