### ISSUE TITLE
Untappable download links in Android app on OnePlus X

### ISSUE THREAD

**Issue by lloeki** [mattermost/platform#2449]
Trying to download an attachment produces no reaction (either via right-side area or link within preview). Works under Chrome.

- Android app: 1.14
- Device: OnePlus X (E1003, onyx)
- Android: 6.0.1 (Cyanogenmod nightly 20160222)

**Comment by lfbrock** [comment]
Thanks @lloeki, we have a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-2324
