### ISSUE TITLE
Android App 1.14 verified on OnePlus X with Android 6.0.1

### ISSUE THREAD

**Issue by lloeki** [mattermost/platform#2450]
| Version | Device & OS | Issues | Tester | Date | 
|:--- |:--- |:--- |:--- |:--- |
| 1.14 | OnePlus X (E1003, onyx), Android 6.0.1 | [#2449](https://github.com/mattermost/platform/issues/2449) | [@lloeki](https://github.com/lloeki) | 2016-03-16 |

**Comment by lindy65** [comment]
Thanks @lloeki, results have been added to [Android repo](https://github.com/mattermost/android/blob/master/DEVICES.md)
