### ISSUE TITLE
API - Ping or Health Check

### ISSUE THREAD

**Issue by jw3** [mattermost/platform#2455]
I was looking for a simple health check, like a `/ping` or `/health`, but the best I ended up with is pointing to the root path.

Is there a suggested method in the API to use for health checks?  If not, what are the thoughts on requirements for this?  Perhaps it could be something as simple as returning a 200 while not requiring a token.

**Comment by lfbrock** [comment]
Hi @jw3, maybe including server version and server timestamp as a json document that's returned?

Would you be interested in working on this if I made an accepting pull request ticket?

**Comment by jw3** [comment]
That sounds good to me @lfbrock.

I would be interested in doing the work, and have been spending lots of time in your API lately so it should be doable even for a Go novice.

As for the location of the implementation [within the api](https://github.com/mattermost/platform/tree/master/api), I thought about that some and didn't see an obvious placement.  What is your preference; a new file added for health, or can it fit somewhere else?

thanks

**Comment by lfbrock** [comment]
Great! Made an [accepting pull requests ticket](https://mattermost.atlassian.net/browse/PLT-2377) for you, 

I think /api/v1/ping would be a good place.
