### ISSUE TITLE
Using mattermost backend architect for Go Restful API

### ISSUE THREAD

**Issue by RuniVN** [mattermost/platform#2460]
Hi, 
I decide to use mattermost for our next project backend. Is this affordable when there are a lot of concurrent users? Because I read code and see that the communication with database is quite complex. It uses channel, for example: 
```
if result := <-Srv.Store.Team().Get(user.TeamId); result.Err != nil {
	c.Err = result.Err
	return
} else {
	team = result.Data.(*model.Team)
}
```
I am wondering when something wrong with channel and it can not return the value, may be deadlock.
I appreciate all advices or corrections for my question, it's the first time I use Go as backend of big project.
Thanks.

**Comment by it33** [comment]
Hi @RuniVN, thanks for your question, please help move this to [Developer Discussion](https://forum.mattermost.org/c/dev) forum?
