### ISSUE TITLE
Open source for white labeling under commercial use possible?

### ISSUE THREAD

**Issue by kramer65** [mattermost/platform#2464]
In your rather confusing [LICENSE.txt](https://github.com/mattermost/platform/blob/master/LICENSE.txt) I read that the compiled versions are licensed under the MIT-license, but the source code is subject to the following:

1. Under the Free Software Foundation’s GNU AGPL v.3.0, **subject to the exceptions outlined in this policy**; or 
2. Under a commercial license available from Mattermost, Inc. by contacting commercial@mattermost.com 

I'm a programmer, not a lawyer, so reading your extensive license is out of my scope. My question is rather simple though:

Can I take the source code of the mattermost platform, integrate it into our own platform, adjust the labeling so that it shows our brand name instead of "mattermost", and sell it to customers?

**Comment by it33** [comment]
Removing Mattermost branding to sell the software under a different name is not recommended because it would put users at risk if Mattermost issues a security update and those users are unaware of the need to install it.

The Mattermost core team does not want encourage any efforts like this that could could put users at risk.

**Comment by kramer65** [comment]
This is not an answer to my question. I'm not asking what you encourage. I'm asking what your license legally permits. Since you closed this issue, I opened a [new issue here](https://github.com/mattermost/platform/issues/2467).

**Comment by corbolais** [comment]
@Mattermost, effectively you created a software no-one may use commercially except you. Despite the open source code drama you created. There are natural use cases - even with licenses - one is not covered. Sick software looks like this. Expressly made to not live as OSS.

You could remove any disambiguity in the legalese to prove your true OSS commitment.

FWIW, I won't use mattermost not at all, unfortunately. 

The licensing is such unclear and full of pitfalls and some patches are so dark as dark can be on the dark side. It seems purposefully designed to prohibit any non-internal use. And even then.. And regardless of your open source "commitment" and source code available or Team Edition. Commercial code in the open source code? Mandatory inclusion of specific ToS and licensing files? Using open source code under MIT license in this case, AGPL in that case? This is fabricated to trip everyone else when scrutinized.

Mattermost, nice software rendered broken by policy. Thank you, but no. *shudder*

You could prove me wrong, though..
