### ISSUE TITLE
[Help wanted]: guide for running a load-balanced mattermost setup

### ISSUE THREAD

**Issue by TwizzyDizzy** [mattermost/platform#2466]
Hi folks,

I wanted to evaluate on how one would go about scaling mattermost horizontally - that is: adding more frontends or more database backends.

In general I guess one would like to test how much influx a normal mattermost instance is roughly able to handle to establish a rough estimate of "If you're planning to go for 1000 / 10000 / 100000 users you may think about load-balancing mattermost". Sure, that depends on the hardware, of course, but a rough estimate on like two or three machines (including mentioning their full speccs) would be nice.

Therefore one would have to simulate traffic (normal chats, private chats, direct messages, inbound + outbound hooks) to first find the bottlenecks that lead to mattermost getting slow in the end on a single instance. Maybe one could replay real traffic in an amplified manner.

Just from thinking about it, I would guess that it would currently be no problem to add further mattermost frontends. As for the database backend: Maybe it was possible to implement some kind of read/write split to the database backends.

But yeah, that's pure speculation so far.

Any initial ideas?

(I'm on vacation for a week now, so don't expect any replies from me until in about one week - that is, if I am able to stay away from the keyboard ;)

Cheers
Thomas

**Comment by it33** [comment]
Mattermost [is not intended to serve as a proprietary SaaS offering](http://www.mattermost.org/why-we-made-mattermost-an-open-source-slack-alternative/) and the complexity of horizontal scaling for team communication does not meet [FOF criteria](http://docs.mattermost.com/developer/fx-guidelines.html?highlight=obvious#design-principles). That said, [a single server should still support thousands of users](http://docs.mattermost.com/install/requirements.html).

**Comment by TwizzyDizzy** [comment]
On a late note:

> Mattermost is not intended to serve as a proprietary SaaS offering

funny, I was not even talking about that. I'm thinking of rolling out mattermost in a big company and therefore need some king of loadbalancing.

> the complexity of horizontal scaling for team communication does not meet FOF criteria.

Interesting. Yet you will provide horizontal scaling as part of the [E20 edition of mattermost](https://about.mattermost.com/pricing/).

But don't get me wrong here: I don't judge you for doing that. I am grateful for mattermost Team Edition being Open Source and earning money is a must for your company.

The thing I don't like is, when I get obscure replies that don't openly communicate why you won't support any open source load balancing efforts. Because you want to capitalize on that, which is fine.

Cheers
Thomas
