### ISSUE TITLE
There appears to be a problem with your internet connection.

### ISSUE THREAD

**Issue by Vaelek** [mattermost/platform#2468]
After activating the email settings and the preview mode notice goes away, both the native app and the web interface instantly show "There appears to be a problem with your internet connection." upon loading, and it comes back after a minute when dismissing. In my log, I have an "invalid session token" error.

**Comment by lindy65** [comment]
Thanks @Vaelek, ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2399

**Comment by lfbrock** [comment]
Closing this issue, will be tracked in Jira.

**Comment by dvenske** [comment]
I know this was closed, but I can't comment on the JIRA ticket. What solved this for me @Vaelek was to logout and reset password via email. I think the reason this happens is that setting up email also sets up new salts for security tokens.

**Comment by sonjz** [comment]
Logout and login fixed it for me.
