### ISSUE TITLE
404 on incoming webhooks

### ISSUE THREAD

**Issue by Vaelek** [mattermost/platform#2469]
I created a webhook, and when testing it I receive a 404 error. If I test it with a GET I receive a 200 response.

**Comment by jwilander** [comment]
Hi @Vaelek, are you working off of `master` branch or are you running off one of our official releases (if so, please specify)?

**Comment by Vaelek** [comment]
@jwilander I used the one-line Docker install on Ubuntu Trusty

**Comment by enahum** [comment]
actually @jwilander I think @Vaelek means that `/hooks/{id:[A-Za-z0-9]+}` route no longer exists as it was removed from `web.go` with the change to `react-router` and actually I think it wasn't added anywhere.

It was actually there before the commit d7cdcf082fab6c0cb7c2fe4bed821bd1a8000e69 as you can see here https://github.com/mattermost/platform/blob/70eee522978333174c9e51b0f7505413a9a2b66c/web/web.go#L96

**Comment by crspeller** [comment]
This: https://github.com/mattermost/platform/pull/2492 Should do it.

**Comment by Kemyke** [comment]
I also tried to update our Mattermost 2.0 server to 2.1 and found the same issue. We use the official image from docker hub. First i noticed that the old hooks not working. Then i tried to create a new one,
it gave me the old format: mmserver.com\hooks\<hookid>

If i tried to GET this address or the new one (/api/v1/hooks), both was working: 200 status
If i tried to POST both addresses replied with 404 status. 

Should we rollback to 2.0 official image? Or can i configure a working incoming webhook with v2.1?

**Comment by kai23** [comment]
I have the same issue with the 3.1.0.

`POST` to `https://xxxxxxxx/api/v1/hooks/rckc886p57f6z8ndrpuw95geoe/new_event` give me a 200, but with this error : 

```json
{"id":"api.context.404.app_error","message":"Désolé, impossible de trouver cette page.","detailed_error":"There doesn't appear to be an api call for the url='/api/v1/hooks/rckc886p57f6z8ndrpuw95geoe/new_event'.  Typo? are you missing a team_id or user_id as part of the url?","request_id":"","status_code":404,"is_oauth":false}
```

And the logs give me that : 

`[2016/06/30 13:41:28 CEST] [EROR] /api/v1/hooks/rckc886p57f6z8ndrpuw95geoe/new_event: code=404 ip=xx.xx.xx.xx`

`POST` to `https://xxxxxxxx/hooks/rckc886p57f6z8ndrpuw95geoe/new_eventt` give me a 404 and 
`[2016/06/30 13:41:28 CEST] [EROR] /api/v1/hooks/rckc886p57f6z8ndrpuw95geoe/new_event: code=404 ip=xx.xx.xx.xx`

**Comment by crspeller** [comment]
@kai23 @Kemyke 

We have bumped the API version with 3.0. The api is now `v3`.
