### ISSUE TITLE
Unable to login using GitLab SSO on Android app

### ISSUE THREAD

**Issue by shantanuthatte** [mattermost/platform#2477]
**Summary:** Unable to sign-in using GitLab SSO using Android app

**Steps to reproduce:** 
 1. Account has been setup to login using GitLab SSO using the Android app.
 1. GitLab integration has been enabled using System Console.
 1. Clicking on login with GitLab button nothing happens. 

**Expected Behavior:** Should show the GitLab sign-in page.

**Observed Behavior:** Nothing happens. There is progress bar on top for a moment, but the page remains the same.

**Possible Fixes:** 
 - Any error message showing why it failed would be useful.
 - A way to convert a SSO account to using password or even both together.

**Comment by it33** [comment]
Hi @shantanuthatte, the Android app requires Mattermost server 2.1 and higher. Mattermost 2.1 releases with GitLab 8.6 on the 22nd. If you go to your team site on your deployment and select "About Mattermost" my guess is you're on a version other than 2.1?

**Comment by shantanuthatte** [comment]
Hi @it33, we have our own independent instance running v2.1. Here are the details:
```
Mattermost Team Edition
Version:2.1.0
Build Number:2.1.0
Build Date:Mon Mar 14 20:45:23 UTC 2016
Build Hash:f189bc2073cf800c5f4506a69bdb51d7065269bf
```
And the android app:
```
Mattermost
com.mattermost.mattermost
version 2.1.0
```

**Comment by it33** [comment]
Hi @shantanuthatte, 

We're not able to reproduce your issue. 

Can you confirm GitLab SSO is working via the web interface? 

Also, wondering if anyone else from the community is seeing this?

**Comment by shantanuthatte** [comment]
Hi @it33,

Yes, the GitLab SSO works on the browser (Chrome 49 On Windows 7). I am using OnePlus One running Android 5.1.1

I found the issue to be with SSL and passing intermediary certificate in my GitLab configuration. After adding it to the certificate to the chain, it started working. Strange that I never had such problems on my desktop.

Nevertheless, any error or toast regarding this would have been very helpful.

If required, you may close this issue.

**Comment by it33** [comment]
Thanks @shantanuthatte, glad it's fixed!
