### ISSUE TITLE
database error on from install

### ISSUE THREAD

**Issue by Moridinmhael** [mattermost/platform#2478]
as soon as I try creating/login for the first time on webpage, get 503, database logs displays this:

18/03/2016 13:48:51ERROR:  relation "systems" does not exist at character 19
18/03/2016 13:48:51STATEMENT:  SELECT Value FROM Systems WHERE Name='Version'
18/03/2016 13:48:54ERROR:  column "type" does not exist at character 40
18/03/2016 13:48:54STATEMENT:  UPDATE Preferences SET Type = $1 WHERE Type = $2
18/03/2016 13:48:54ERROR:  relation "idx_teams_name" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_teams_invite_id" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_channels_team_id" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_channels_name" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_channelmembers_channel_id" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_channelmembers_user_id" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_posts_update_at" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_posts_create_at" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_posts_channel_id" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_posts_root_id" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_posts_message_txt" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:54ERROR:  relation "idx_posts_hashtags_txt" does not exist
18/03/2016 13:48:54STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_users_team_id" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_users_email" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_audits_user_id" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_sessions_user_id" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_sessions_token" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_oauthapps_creator_id" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_oauthaccessdata_auth_code" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_oauthauthdata_client_id" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_incoming_webhook_user_id" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_incoming_webhook_team_id" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_outgoing_webhook_team_id" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_command_team_id" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_preferences_user_id" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:55ERROR:  relation "idx_preferences_category" does not exist
18/03/2016 13:48:55STATEMENT:  SELECT $1::regclass
18/03/2016 13:48:56ERROR:  relation "idx_preferences_name" does not exist
18/03/2016 13:48:56STATEMENT:  SELECT $1::regclass

**Comment by RustamGimadiev** [comment]
Same problem with postgres 9.5, mattermost release 2.1.0.

**Comment by lfbrock** [comment]
Hi @Moridinmhael, can you move this to the troubleshooting forums and include what version of postgres you're on? Seems like it might be a db version issue.

**Comment by lfbrock** [comment]
Actually we may have found the issue, PR here: https://github.com/mattermost/platform/pull/2496

**Comment by Moridinmhael** [comment]
Currently using postgres:9.3 - originally triedd using postgres:9.4 has same issue.
Downgraded to 9.3 for pgAdmin use so could try troubleshoot more.
