### ISSUE TITLE
broken link for docker install

### ISSUE THREAD

**Issue by vise890** [mattermost/platform#2479]
# Summary:
the docker install link on the homepage is  broken

# Steps to reproduce:
- go to [mattermost.org](http://mattermost.org)
- click on  `one-line Docker install` towards the end of the text

# Expected behavior:
I get to a rendered version of `https://github.com/mattermost/docs/blob/master/source/install/docker-local-machine.md`
# Observed behavior:
got a good old 404

**PS**: didn't really know where else to report this....

**Comment by it33** [comment]
Thanks @vise890! Fixed!
