### ISSUE TITLE
[web interface] Typing should always go to the chatbar

### ISSUE THREAD

**Issue by DanielHeath** [mattermost/platform#2488]
It's really easy to click away from the chatbar in the web interface. After that, any typing just goes nowhere.

E.g. slack keeps your cursor in the chat bar to avoid this - if I'm typing I mean it to go to the room I'm in.

**Comment by lfbrock** [comment]
Hi @DanielHeath, that makes a lot of sense - if I make an accepting pull requests ticket for this, is it something you would be interested in working on?

**Comment by DanielHeath** [comment]
Potentially - I'm just scoping out Mattermost at the moment. Would definitely be happy to fix if I were actively using it.

**Comment by lfbrock** [comment]
Fair enough, I made a ticket to track the issue in Jira: https://mattermost.atlassian.net/browse/PLT-2413

Thanks for the report!
