### ISSUE TITLE
Lato font unicode support

### ISSUE THREAD

**Issue by destronije** [mattermost/platform#2490]
Hello, first of all, thank you for great platform.

My team noticed that some fonts(haven't tested them all) other than default, like "Lato" don't seem to support unicode characters.
We noticed this long time ago, but thought we were not the first to notice, so never reported untill now. :)

**Comment by hmhealey** [comment]
Hi @destronije. Can you give us some examples of characters that don't work, possibly with screenshots?

**Comment by destronije** [comment]
Hi @hmhealey, thank you for fast response.

Here is the screenshot & written characters below in their respective order from screenshot.
![lato - unicode](https://cloud.githubusercontent.com/assets/1836461/13921819/1559db3c-ef7a-11e5-8af6-2b887583ec5e.png)

ČĆŽŠĐčćžšđ
ЧЋЖШЂЉЊЏчћжшђљњџ

Lato font was used in this example.

**Comment by hmhealey** [comment]
Thanks for the screenshots. I've created a [ticket in Jira](https://mattermost.atlassian.net/browse/PLT-2403) to track this issue.

**Comment by Quintasan** [comment]
>Propose closing this as won't fix, browser falls back to default font anyway

Hardly an argument. How about just using the full font? Take a gander an how your OS X application looks like now:
![image pasted at 2017-2-1 11-17](https://cloud.githubusercontent.com/assets/6539261/22503270/433b9cb6-e871-11e6-8a94-be148cb05649.png)

**Comment by jasonblais** [comment]
@Quintasan ,

Reopened the Jira ticket – we can consider adding full font, so that Cyrillic characters are supported.

Queued for triage to discuss whether it should be a feature request, help wanted or internal backlog ticket

**Comment by MrMAB** [comment]
Lato²³⁴ 

![image](https://user-images.githubusercontent.com/13866779/206900596-26803ad4-11d3-4ea5-9d9d-e80303562a10.jpeg)
