### ISSUE TITLE
Team statistics runs invalid query

### ISSUE THREAD

**Issue by msmithbbc** [mattermost/platform#2501]
**Summary:** Team statistics page runs invalid query

**Steps to reproduce:**
- Browse to statistics page for a team (eg https://mattermost-server/admin_console/team_analytics/eoejh3t8tb8tmj7mm71ubm8dry?session_token_index=0)

**Expected behavior:**
 - The counts for "Total Users", "Public Channels" etc. should be shown.

**Observed behavior:**
 - The counts for "Total Users", "Public Channels" etc. hang on Loading...
 - Blue bar appears with "We couldn't get the unique user count"
 - The following is seen in the MySQL process list (SHOW FULL PROCESSLIST;): 

   `| 4773 | usernamehere  | 99.99.99.99:49102 | mattermost | Execute | 1191 | Sending data       | SELECT COUNT(DISTINCT Email) FROM Users WHERE TeamId = ? |    0.000 |`
 - The query never completes, and running several seems to tie up the server.

**Comment by msmithbbc** [comment]
Enabling SQL tracing gives me this in the logs:

`sql-trace:16:11:27.818157 SELECT COUNT(DISTINCT Email) FROM Users WHERE TeamId = ? [1:"eoejh3t8tb8tmj7mm71ubm8dry"] (41.738905366s)`

**Comment by jwilander** [comment]
Hi @msmithbbc,

What version of Mattermost are you running? Also are you running as production or as developer?

I've tried to reproduce your issue on our `master` branch but it seems to be working there

**Comment by msmithbbc** [comment]
We're using the 2.1.0 release as production.

**Comment by msmithbbc** [comment]
After some research, it turns out that this was actually a problem with MariaDB, and has previously been with MySQL.  Upgrading from 10.1.12 to 10.1.13 has resolved the problem for me and hopefully it won't reappear.

See http://www.chriscalender.com/tag/select-countdistinct/ for reference of this occurring previously in MySQL.

**Comment by msmithbbc** [comment]
Fault was fixed under https://jira.mariadb.org/browse/MDEV-9667
