### ISSUE TITLE
android app: Sometimes I couldn't enter specific private group.

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#2502]
Sometimes I couldn't enter a specific, very active, private group in my mattermost deployment. When I touched the name of the group to enter it, the background color of the name turned to sky-blue but then nothing happened.

I could enter the group after restarting the android app.

**Comment by lfbrock** [comment]
Hi @npcode, how active was the channel you were trying to access? Do you think that was related to why it wouldn't open? 

Haven't been able to reproduce this, if anyone else from the community sees similar issues please let us know here so we can narrow down the issue.

**Comment by npcode** [comment]
@lfbrock 7 members and 100 posts a day. I don't think this causes performance problem but at that time the other channels were all fine.

> Haven't been able to reproduce this, if anyone else from the community sees similar issues please let us know here so we can narrow down the issue.

Sure, I will do it.

**Comment by lfbrock** [comment]
Hi @npcode, just wondering if you are still seeing this issue?

**Comment by npcode** [comment]
@lfbrock No, I've never seen this problem again. Feel free to close this. I'll comment here if I see this issue again.

**Comment by lfbrock** [comment]
Okay, thanks!
