### ISSUE TITLE
android app: Recovering from disconnection is quite slow.

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#2503]
When android app is disconnected form the mattermost server, it displays a dialog to ask me to refresh or logout. When I touched "refresh", the app showed me just white blank screen for a while. 

After about 30 seconds finally the app recovered the screen successfully. I think 30 seconds is too long to wait without any indicator (progress bar or loading animiation).

My android is Nexus 5 / Android 5.1.1

**Comment by lfbrock** [comment]
Hi @npcode, I think a loading indicator should be showing up - I made a [ticket](https://mattermost.atlassian.net/browse/PLT-2415) to go look into it. 

As for the loading time, this should improve somewhat after react router changes go in (in v2.2).

**Comment by npcode** [comment]
@lfbrock 

> I think a loading indicator should be showing up 

Yes, I saw it. But it was disappeared in just a few seconds.

**Comment by lfbrock** [comment]
Alright thanks, we'll look into it

**Comment by coreyhulen** [comment]
I cannot repo with master.

**Comment by VertigoRay** [comment]
I'm not actually sure why this is closed. A progress bar is one thing. The App appears to just be a web connection and **isn't useful as a chat client** from the phone with such a slow recovery time.

**Comment by lfbrock** [comment]
@VertigoRay we're building new native mobile apps - they're currently a work in progress and only support a subset of features, but they're available to beta test if you're interested. You can check out our repo here for more info: https://github.com/mattermost/mattermost-mobile

**Comment by VertigoRay** [comment]
Thanks, I will definitely test it.  I actually just stumbled across it in #5397 ... glad the link is here as well; for posterity.
