### ISSUE TITLE
Android app crash at login: Xiaomi Mi3TD, Cyanogenmod 13

### ISSUE THREAD

**Issue by hydrandt** [mattermost/platform#2504]
Hi there,

The Android app always crashes for me, the behavior is the same in both releases (1.14, 2.1). I can enter the team url, then username and password, then it loads for a while and crashes with bare "Unfortunately, Mattermost has stopped" (with my local server: no content is shown before the crash; with the pre-release.mattermost.com/core: it shows some content shortly (~3s, but maybe this is caused by connection speed, as I am in China).

This was happening in the original firmware from Xiaomi (MIUI), Android 4.4.4. Meanwhile, I switched to Cyanogenmod 13, but the behavior is exactly the same.

How can I help to debug?

* Phone: Xiaomi Mi3 TD (pisces architecture, nvidia tegra) 64GB
* Firmware: both Cyanogenmod 13 (Android 6) and MIUI 7.1.2.0.KXDMICK (Android 4.4.4), **without google play services** (I only use f-droid apps) -- could it be caused by the google play services framework absence? (I can imagine you use GCM)

**Comment by lfbrock** [comment]
Hi @hydrandt, are you able to connect to pre-release.mattermost.com/core and your local server from your mobile web browser instead of the app? (Trying to determine if it's an issue with the app itself or something else).

**Comment by hydrandt** [comment]
Yes, sure I am. Also a colleague with a HTC phone with Android 6 is able to use the app to access both the prerelase server and our server.

**Comment by it33** [comment]
Hi @hydrandt, are your colleagues who are connecting successfully using a similar setup without Google Play Services, or do they have Google Play Services?

**Comment by hydrandt** [comment]
I had two friends who use Xiaomi with the original Chinese firmware try it out. 

* Xiaomi 4c: After login, townsquare never loaded (I will have him try it one more time thou, maybe just his connection)
* Hongmi Note 3: Works fine.

I will read about how to get logs and dumps via adb and will try to provide these. Never debugged anything on Android before.

**Comment by hydrandt** [comment]
Now I am on Xiaomi Mi4 with Cyanogenmod 13, same behavior. A friend tried on Xiaomi Redmi with the Chinese firmware (no google apps), same behavior.

Logcat from Mi4, after entering credentials and submitting them: http://pastebin.com/QeCUKLCh

**Comment by hydrandt** [comment]
Let me know if I should provide any additional information.

**Comment by it33** [comment]
Hi @hydrandt, 

We're not familiar with the setup you're describing. We do use GCM, so if it's not available that might be causing the issues. 

We didn't realize there was an option to remove it and have now added Google Play Services as a requirement: https://github.com/mattermost/android/blob/master/README.md

Could you see if there's a configuration of Android 4.4.2+ with Google Play Services enabled that still results in the error you're seeing?

**Comment by hydrandt** [comment]
I see. The absence of Google Services Framework on my phones is intentional (I minimize the amount of proprietary software in my phone and the metadata collected by various companies). And GCM is blocked in China anyway.

Good to know the reason of the crash and that the requirement has been clarified. It would be nice if the absence of GSF resulted in absence of notifications rather than crash. But as the notifications are (so far) the only added value the app brings, I may just put a bookmark in the launcher. 

Unfortunately I don't have any other phone with GSF to test on.

Thanks for the answer!

**Comment by it33** [comment]
Thanks @hydrandt! 

We'll put a try-catch around the GCM service to prevent crashing if we can, but we're not planning on adding a non-GCM setup to our testing. 

Bookmark in launcher is probably a good idea and we'll probably support non-native push notifications at some point.
