### ISSUE TITLE
'About Mattermost' not showed on mobile website

### ISSUE THREAD

**Issue by OFmarting** [mattermost/platform#2505]
Don't know if it is a bug or a feature idea. 
The 'About Mattermost' option is not displayed on the mobile website. So there is no way to check the version. I'm using Mattermost V2.1.0.

**Comment by lfbrock** [comment]
Thanks @OFmarting, that's a bug - made a [ticket](https://mattermost.atlassian.net/browse/PLT-2416) to track the issue. 

If anyone would like to work on fixing this, would welcome pull requests for it.
