### ISSUE TITLE
Blank password error is displayed when login API is called using curl

### ISSUE THREAD

**Issue by krishnakumarcitrus** [mattermost/platform#2506]
Here is my curl command for trying login API: 

C:\Users\uesrName>curl -i -d '{"password":"pass123","name":"kakes-a
rmy","email":"myemailId@gmail.com"}' http://myHostedMattermost.com/api/v1/users/login

{"id":"api.user.login.blank_pwd.app_error","message":"Password field must not be
 blank","detailed_error":"","request_id":"xxxr1yhogtr5cdcr3hmd5rxxxxx","status_co
de":403,"is_oauth":false}

But the same login API works using POSTER.
Has any one got similar issues?

**Comment by haseebr** [comment]
have you tried using the -F option instead of -d ?

**Comment by acpower7** [comment]
I have the same issue.

I'm getting I am getting the error:

{"id":"api.user.login.blank_pwd.app_error","message":"**Password field must not be blank**","detailed_error":"","request_id":"i5kuq1rh6fg6fmdojte3n4k7oe","status_code":400,"is_oauth":false}

When following the instructions here: http://docs.mattermost.com/developer/web-service.html

**Comment by wolfnidh** [comment]
You need to group the request. It solved my issue.

request.AddBody(new { UserName = "username", Password = "pass" }); 

Please see: https://groups.google.com/forum/#!topic/restsharp/3NVVMridDJ0
