### ISSUE TITLE
"/me foo" is not different than using *foo*

### ISSUE THREAD

**Issue by artkrz** [mattermost/platform#2510]
/me command makes no sense at all since v2.1.0 as it's basically same as sending your message using _italic_.

This command should output something similiar to what HipChat does:

![image](https://cloud.githubusercontent.com/assets/209375/13980663/c23c6bea-f0d7-11e5-8b03-b1a5f1a900d0.png)

**Comment by lfbrock** [comment]
Hi @artkrz, thanks for bringing that up!

My understanding is that /me should be formatted like it is a system message. Our system message (for example, the messages triggered when joining a channel) used to be formatted with italics, but we recently updated them and didn't update the formatting for /me. 

I've created a [ticket](https://mattermost.atlassian.net/browse/PLT-2436) to track this issue in Jira - if anyone would like to work on it let me know and I can make it accepting pull requests?
