### ISSUE TITLE
Incoming Webhook "no text specified" v2.1.0

### ISSUE THREAD

**Issue by ajpaulson** [mattermost/platform#2511]
I've just set up a 2.1.0 mattermost server and I'm testing incoming webhooks from Atlassian Bitbucket - currently it hits a 500 error with "No text specified"

Is this an error with the Mattermost parsing the payload or is the Bitbucket json payload out of scope for the main project (thereby needing a custom integration)?

**Comment by jwilander** [comment]
Hi @ajpaulson,

Is there a feature in Atlassian Bitbucket to send events formatted either in the Mattermost or Slack format (since we are Slack-compatible)?

If not, then there needs to be some sort of intermediate application that will translate the outgoing webhooks from Atlassian Bitbucket into the format of Mattermost incoming webhooks which is described [here](http://docs.mattermost.com/developer/webhooks-incoming.html).

**Comment by ajpaulson** [comment]
I've had a look through all the Bitbucket options and there doesn't seem to be a mattermost or slack format option for services or webhooks - it seems that it will have to be an intermediate parser.

The format of the webhooks is valid JSON.

**Comment by ajpaulson** [comment]
As an additional: Slack parses the data without any 3rd party parser.

Could there be a possibility for Bitbucket support in some future Mattermost release?
Bitbucket is (after Github) a primary code hosting solution used by many businesses.

**Comment by jwilander** [comment]
If there's enough community support for it then it's likely that we'd add in-product Bitbucket integration into Mattermost sometime in the future. If you'd like to get the ball rolling on that then feel free to submit a feature request by following the process [here](https://www.mattermost.org/feature-requests/).

In the meantime, if you're code-savvy, you could write an intermediate application to convert Bitbucket's outgoing webhooks into Mattermost incoming webhooks. I did a quick google search and someone seems to have [written something similar](https://gist.github.com/six519/bdbb7ef2e468c8557e09) for Slack which looks like it could easily be used as an example for creating something similar for Mattermost.
