### ISSUE TITLE
email notification only after short delay

### ISSUE THREAD

**Issue by joernhees** [mattermost/platform#2521]
We use mattermost in our research group and email notifications are a great feature to help adoption (which is one of the reasons why we opted for mattermost).

That said, the email notifications can also become very very annoying. In the current state, they seem to be sent for each and every notification instantaneously, even if i react to a native client, an app or the browser tab within a few seconds. The result is that many of our users deactivate email notifications at some point and then aren't pulled back in anymore. This is the equivalent of a fire-alarm that triggers too often, resulting in people ignoring it even in case of a fire...

It would be great if you guys could quickfix this by only actually sending an email notification out if the person to notify doesn't react within 1 minute.

"Quickfix" as configurability, team default, team / admin override would obviously be nice features as well, but not as critical as fixing the broken fire-alarm.

**Comment by lfbrock** [comment]
Hi @joernhees, I think that makes a lot of sense + we should open a ticket on it. If I make it accepting pull requests, would you be interested in working on it?

**Comment by joernhees** [comment]
@lfbrock i fear my go-foo isn't good enough to actually make those changes myself :( ... it seems to be somewhere around [/api/post.go#L580](https://github.com/mattermost/platform/blob/bd225dca738400495a8ef8fea0fc81fd11d225c7/api/post.go#L580).

In other languages, i'd decouple the email sending with a queue per user and a single possible timed (async) email sending callback per user. If triggered by timeout the callback would simply send all of the content in the user's queue (optionally batched in a single email) via email and clear the whole queue. Each notification to the user would always append to the queue, but not override an already waiting callback (that way the email is sent after at max a minute (or some configured timeout), even if people keep messaging the user). All user activity (like read or write) would clear the user's notification queue and his/her waiting email callback.

**Comment by lindy65** [comment]
Thanks for the report @joernhees, ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2451
