### ISSUE TITLE
Notifications/sounds are sent even if window is in focus

### ISSUE THREAD

**Issue by Endemoniada** [mattermost/platform#2527]
Even when I'm actively writing in a private chat window, every reply I get is treated as a notification with accompanying sound alerts. If I switch away and back to the window, the next reply I receive gets a "New Messages" line marker as if I'm not actively watching the window.

It seems to me the focus-check is broken, and doesn't track which window I'm actively viewing. Instead it treats everything that comes in as background activity, and notifies me accordingly.

The problem occurs both in browser and electron-mattermost client, on both OS X and Windows. MatterMost is currently running version 2.1

**Comment by lfbrock** [comment]
Hi @Endemoniada, does this ticket cover your issue? https://mattermost.atlassian.net/browse/PLT-2361

Agreed, it makes sense to only show desktop notifications if the channel isn't currently open.

**Comment by Endemoniada** [comment]
Yeah, that seems to be exactly what I want.

Funny, I never noticed it behaving like that before, so I just figured it was a bug in the latest release. Seems like an obvious feature, to me, that alerts and notifications shouldn't be sent if the user is actively using the application already.

But yeah, feel free to close this if you want.
