### ISSUE TITLE
iOS/Android apps not working with Docker test package

### ISSUE THREAD

**Issue by uidzero** [mattermost/platform#2540]
I wanted to trial Mattermost so I ran the mattermost-dev image given in the docs. I tried to sign on to it with the mobile apps but I'm getting a blank screen as soon as I enter the URL. I also confirmed that I wasn't the only one with this issue.

**Comment by enahum** [comment]
There was a bug which got fixed this morning and is already on `master` branch

**Comment by uidzero** [comment]
Thanks -- marking this closed.
