### ISSUE TITLE
Feature request: channel moderators and DM/public muting

### ISSUE THREAD

**Issue by uidzero** [mattermost/platform#2541]
I feel that the chat experience is great in a professional setting, in the sense that people are going to take more pains to be respectful of each other. However, this doesn't translate to a social setting where tongues can be a little looser and tempers can be a little quicker. This happens to be exactly the use case I have in mind for Mattermost -- I would like to invite a few of my friends (no problems there...) and invite them to invite their friends (this is potentially where social issues come into play).

To this end I'd like to propose a few basic features:

- Moderators for each channel. Ideally this would be whoever creates it and then whoever they choose to grant elevated privileges in that channel to. The Server/Team admin account(s) should also be able to grant this to themselves, in case a moderator leaves or is removed from the team/site. This would be analogous to Channel Op status in IRC.

- The ability for a moderator to mute users in a channel, or to make a channel moderated and only allow certain people to speak (this would be useful for hosting a Q&A session with a large number of people). The latter is is analogous to the +v user mode and +m channel mode on IRC.

- The ability for a user to mute DMs from another user. Analogous to IRC /ignore. The user can choose to stop interacting with a problem user without having to abandon the overall chat completely.

- The ability for a moderator to issue permanent as well as timed bans from a channel. This is analogous to +b on IRC. I feel that this is key because it will allow for cooldown periods or to remove someone permanently as a more drastic measure.

- A Private Group setting (settable by a moderator) that allows only the moderator(s) to invite people rather than any member of the group. Server/Team admins should also be able to join even if they aren't moderators.

I know that this is a feature set which doesn't exist at all in Mattermost's current state, but I would like to put it forward because I feel it would go a long way towards enhancing the chat experience and encouraging people to adopt Mattermost.

**Comment by lfbrock** [comment]
Hi @uidzero, can I get your help adding these to the feature request forum as per above instructions?

I think the suggestion for [read/write permissions for channels](https://mattermost.uservoice.com/forums/306457-general/suggestions/12874797-add-read-write-permissions-for-channels)  is similar to your idea about only allowing certain users to speak, so it would be great if you could add any related feedback there.

**Comment by rolfchess** [comment]
I tink this feature request is not at all the same as read/write permissions. I have no uservoice account, so I'll put my response here: I think this feature request is still valid and useful.
