### ISSUE TITLE
Feature request: Extend customization options to include message bg

### ISSUE THREAD

**Issue by yuppity** [mattermost/platform#2549]
Mattermost highlights user's own messages with a gray background (the color changes depending on fg color) and these highlights are visually very prominent in the center channel. I personally find them a distraction, aesthetically (*clears throat*) displeasing, and a general disruption to the flow of the center channel. This is to say that, as a visual element, they're important yet the user has no way to easily turn them off.

Please consider adding such functionality to the customization menu.

**Comment by yuppity** [comment]
Thanks!

https://mattermost.uservoice.com/forums/306457-general/suggestions/13178862-extend-customization-options-to-include-message-bg

**Comment by lfbrock** [comment]
Thank you!
