### ISSUE TITLE
Clock display settings from Account Settings are not used in Search

### ISSUE THREAD

**Issue by johandalabacka** [mattermost/platform#2555]
I have selected 24 hour clock Account Settings > Display > Clock and still is time in search shown in 12 hour clock format. 

Mattermost 2.10

![Search result](https://cloud.githubusercontent.com/assets/9607173/14104207/2a6322f6-f5a4-11e5-8863-cd81c4474e1d.png)
![Clock setting](https://cloud.githubusercontent.com/assets/9607173/14104208/2a630c6c-f5a4-11e5-9efd-3b8220d91b59.png)

**Comment by lindy65** [comment]
Thanks @johandalabacka, ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2472
