### ISSUE TITLE
Login with gitlab does not work if there is a space after the e-mail address

### ISSUE THREAD

**Issue by robertselberg** [mattermost/platform#2557]
In the Mattermost mobile app: "Login with gitlab" does not work if there is a space after the e-mail address.

You must trim() the e-mail address before validating the login credentials.

**Comment by lindy65** [comment]
Thanks @robertselberg, ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2471

**Comment by lindy65** [comment]
Hi @robertselberg, this has been fixed on master.  Could we have your help testing on master to make sure it is fixed for you too?
