### ISSUE TITLE
Email address is now case-sensitive

### ISSUE THREAD

**Issue by gkhays** [mattermost/platform#2563]
Previously, email addresses were silently lower-cased on input. Now they are case-sensitive, which can lead to a confusing login experience.

![image](https://cloud.githubusercontent.com/assets/773981/14114636/44c916fc-f59d-11e5-932d-f74ed063c4ec.png)

Chrome version: Version 49.0.2623.108 m

![image](https://cloud.githubusercontent.com/assets/773981/14115341/34272e9e-f5a0-11e5-8fd9-f52af65ef2ed.png)

**Comment by lfbrock** [comment]
Hi @gkhays, 

We aren't able to reproduce this on v2.1 or on master - logging in with an email in all caps, with a mixture of lowercase and capital letters, or using all lowercase letters all worked successfully. 

Can you confirm that the email address actually matched an account on the site, and that you're not having any other log in issues?

**Comment by hoshposh** [comment]
Hi @lfbrock,

The email address is definitely stored as indicated. In our tests the user's email is registered with lowercase, but attempting to use any other case results in the error that @gkhays mentioned earlier.

In our installation we are using postgres, and I wonder if the following database search is operating in a case-sensitive manner:

```
func (s SqlTeamStore) GetTeamsForEmail(email string) StoreChannel {
	storeChannel := make(StoreChannel)

	go func() {
		result := StoreResult{}

		var data []*model.Team
		if _, err := s.GetReplica().Select(&data, "SELECT Teams.* FROM Teams, Users WHERE Teams.Id = Users.TeamId AND Users.Email = :Email", map[string]interface{}{"Email": email}); err != nil {
			result.Err = model.NewLocAppError("SqlTeamStore.GetTeamsForEmail", "store.sql_team.get_teams_for_email.app_error", nil, "email="+email+", "+err.Error())
		}

		for _, team := range data {
			if len(team.InviteId) == 0 {
				team.InviteId = team.Id
			}
		}

		result.Data = data

		storeChannel <- result
		close(storeChannel)
	}()

	return storeChannel
}
```

Cheers!

**Comment by lfbrock** [comment]
Ah that makes sense, it could be related to Postgres database - will look into this. Thanks!

**Comment by latrani** [comment]
I just ran into the same issue as above with a user; registered as First.Last@example.com, user list shows name as first.last@example.com, when they tried to log in using the original capitalization, they got the above error.

I'm using the AMI provided at http://www.mattermost.org/installation/ manually upgraded to 2.1

**Comment by lindy65** [comment]
Thanks @gkhays, ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2499
