### ISSUE TITLE
Channel 'View Info' modal gives invalid Channel URL

### ISSUE THREAD

**Issue by LordPov** [mattermost/platform#2571]
To reproduce:
1. Go to a channel
2. Click on channel name at top of channel page for menu dropdown
3. Choose 'View Info'
4. The 'Channel URL' displayed is invalid

The given URL has the form: https://myhost/myteam/mychannel
When it should be like: https://myhost/myteam/**channels**/mychannel

**Comment by BlueAnanas** [comment]
We should be aware of the fact, that the URL is shortened by ellipsis anyway if it doesn't fit in one line.

I see something like `https://ma...u/metateam01/komunikation-technik` as Channel URL and no `<a>` tag at all.

**Comment by lindy65** [comment]
Thanks @LordPov @BlueAnanas 

Ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2485
