### ISSUE TITLE
[Help Wanted] Italian translation 

### ISSUE THREAD

**Issue by it33** [mattermost/platform#2572]
If anyone is interested in working on this language please reply here? 

Please feel free to speak in this language, [you can see other threads speaking non-English as well](https://github.com/mattermost/platform/issues/2221)

[Translation guide here](http://docs.mattermost.com/developer/localization.html). Please also join the [localization channel](https://pre-release.mattermost.com/core/channels/localization), as there are new tools being developed to make translation easier.

**Comment by cifvts** [comment]
I can take this

**Comment by thePanz** [comment]
I already started working on this few months ago, feel free to continue :)

**Comment by jasonblais** [comment]
Italian translations are well in progress but need a bit more help to ship in Mattermost.

If anyone is interested in contributing, please join the [Mattermost Translation Server](http://translate.mattermost.com/it/mattermost/) to get involved, and our [Localization community channel](https://pre-release.mattermost.com/core/channels/localization) to meet other contributors.

![image](https://cloud.githubusercontent.com/assets/13119842/19077672/8728908c-8a1b-11e6-8e02-a18c4eb09cd7.png)

**Comment by jasonblais** [comment]
Thanks to everyone, Italian translations are now completed and available as Beta in Mattermost 4.0 (releases on July 16th)!
