### ISSUE TITLE
2.1.0-stable build broken

### ISSUE THREAD

**Issue by nickpelton** [mattermost/platform#2583]
Since 2.1.0 is the latest stable we're running that and we wanted to make some minor template updates. Turns out the 2.1.0 tag has a dependency called mattermost/mm-intl which no longer exists. 

Can someone restore that repo so the current stable version is build-able?

**Comment by nickpelton** [comment]
Temp fix is to use a copied version I found:

https://github.com/ZBoxApp/mm-intl

Update the package.json on line 12 to:
`"mm-intl": "ZBoxApp/mm-intl#6e30252474bd5f7e891addc79be7a853ef145bd9"`

**Comment by lfbrock** [comment]
Thanks @nickpelton, the repo should be added back now
