### ISSUE TITLE
Too many, too early Email Notification

### ISSUE THREAD

**Issue by sylvainbaronnet** [mattermost/platform#2586]
Hi,

We receive too many, too early email notification. 

For example 5 emails for 5 messages (lines) from the same person in the timelapse of 30 seconds is really annoying and not necessary. They should be grouped with a timelapse option.

Also, we receive notification for message that happend like a few minutes ago while Mattermost is opened but in background, sound notification and desktop notification are enough in this case, email is not necessary.

Thanks for your work

**Comment by lfbrock** [comment]
For the second issue you brought up, we have a ticket [here](https://mattermost.atlassian.net/browse/PLT-2451) to not send email notifications until 1 minute after the notification was triggered. It might make more sense to make this configurable, or to only send email notifications if the user is offline (currently they are sent if you are away and if you are online).

For the first issue, do you envision this as being grouped if the messages are sent within a certain timeframe? Maybe if we make the email notification delay configurable, we could group notifications triggered within that time frame. Would you be able to add this to the [feature request forum](https://mattermost.uservoice.com/forums/306457-general) so other users can give feedback as well?

**Comment by sylvainbaronnet** [comment]
thanks, I opened a suggestion : https://mattermost.uservoice.com/forums/306457-general/suggestions/13274793-group-email-notification-sent-within-a-certain-tim

**Comment by lfbrock** [comment]
Thanks!
