### ISSUE TITLE
"dev" tag is missing from Docker Hub

### ISSUE THREAD

**Issue by tomxtobin** [mattermost/platform#2591]
The `dev` tag [mentioned in the Mattermost documentation][docs] seems to be missing from Docker Hub. Attempts to pull it fail:

```
Pulling repository docker.io/mattermost/platform
Tag dev not found in repository docker.io/mattermost/platform
```

Docker Hub [only shows `2.0`, `2.1`, and `latest` at the moment][dk-tags], although [the "builds" tab at Docker Hub shows it in the history][dk-builds].

[dk-builds]: https://hub.docker.com/r/mattermost/platform/builds/
[dk-tags]: https://hub.docker.com/r/mattermost/platform/tags/
[docs]: http://docs.mattermost.com/install/docker-local-machine.html#additional-notes

**Comment by lfbrock** [comment]
Hi @tomxtobin, 

We removed the dev tag last week, sorry for the lack of notice - there's a post in forum with the reasoning if you'd like to discuss: https://forum.mattermost.org/t/fyi-no-longer-using-dev-tag-for-docker-images/1214

**Comment by tomxtobin** [comment]
Ah, okay. I can't say I understand the reasoning (isn't `latest` understood to be the convention for the latest stable image?), but oh well. Maybe the online docs can get updated to reflect this?

**Comment by lfbrock** [comment]
Yes thanks we should update the docs, @esethna can you take care of that?

**Comment by lfbrock** [comment]
PR to docs here for reference: https://github.com/mattermost/docs/pull/93
