### ISSUE TITLE
Quote characters come through to certain users encoded

### ISSUE THREAD

**Issue by espro** [mattermost/platform#2596]
We have an unusual issue where sometimes a person cannot view quote characters properly, they only come through to their client -- web, or desktop -- as encoded sequences (e.g., "\&\#39;"), sometimes out of order in the stream as well.

I've found that asking the user to change their full name will suddenly fix the problem for them.

Here is a screenshot of the conversation working properly: http://i.imgur.com/sCpXzF3.png
And from the problem user's perspective: http://i.imgur.com/FlewlpL.png

You'll see in the user's screenshot that sometimes the encoded sequence is incorrect, in the first line it shows up as "\&\#9;" with the "3" coming later on, before "the dock"

I should note that the problem user also didn't see full names properly for other users, just their nickname until they set their full name.

**Comment by lfbrock** [comment]
Hi @espro, thanks for the report, this will be fixed in v2.2.

As a temporary fix, you can try switching the language and then switching back to see if that fixes the issue.
