### ISSUE TITLE
2.1 docker image can not login another team in the same session

### ISSUE THREAD

**Issue by zhangguangtong** [mattermost/platform#2606]
Recently I have tried upgrade mattermost containter from version 2.0 to 2.1. The upgrade was success without any error message.

But after upgrade, we found we can only login to one team. If I try login another team by append team name to the mattermost server address, it will redirect me to the team that I have login after serval second.

Then I try start a clean container. After it finished initial setup, I created 2 teams for test.
The same issue happens:
1. Login to team1 http://localhost:8065/team1
2. Try login team2 http://localhost:8065/team2 in another tab.
3. Mattermost seems loading team2 login page, but soon it display team1 page, though the address bar still display http://localhost:8065/team2.
4. Try logout team1, both tab was logout.
5. Try login team2, both tab display team2 page.

We have rollout back to 2.0 by restore our database backup, switch between teams works fine now. But we'd like to upgrade mattermost. Please fix this.

**Comment by lfbrock** [comment]
Hi @zhangguangtong, can you post the information about what build you're on from the Main Menu > About Mattermost dialog?

**Comment by zhangguangtong** [comment]
@lfbrock, thank you for your reply. Here is 2.1 mattermost build info:

Mattermost Team Edition T0

Version:2.1.0
Build Number:6562
Build Date:Thu Mar 17 16:17:34 UTC 2016
Build Hash:2cd006474ec8a808b2ea2b0502a842f44cb0b127

Please let me know if you need more info. Thank you.

**Comment by lfbrock** [comment]
Thanks @zhangguangtong - I think this was an issue with the build you were on, the official v2.1 build has a date of Mar 14. After the v2.1 release, we added some large changes to master that introduced some bugs, and people with the build 6562 from Mar 17 had some of those bugs in the build.

**Comment by zhangguangtong** [comment]
@lfbrock, thank you for check this.

However, the mattermost docker images with tag 2.1 is the same as tag latest. We can not found the image build on Mar 14.
We need a stable build of v2.1, which need rebuild v2.1 image. Could you please rebuild the image or please provide the stable tar.gz file that allowed us build our own image.

Thank you very much.

**Comment by GuillaumeAmat** [comment]
@lfbrock I think I have some related issues (I use the same build) but I can't figure how to build my own dev docker image.
I mean, the _dev_ tag is not available on the Docker hub anymore and the amazon link doesn't work in `docker/dev/Dockerfile`.

Can you tell me how to achieve that?

**Comment by yexingok** [comment]
Not sure why 2.1 docker image was build from RC1 tar.gz: (And that download file is missing.)
https://github.com/mattermost/platform/blob/release-2.1/docker/2.1/Dockerfile#L37-40

I have a talk with @zhangguangtong, and we decide to quickly try the following step:

- Download the stable v2.1 source tag.gz from https://github.com/mattermost/platform/releases/download/v2.1.0/mattermost.tar.gz
- Modify Dockerfile to use the downloaded v2.1 stable tar.gz and build a docker image.
- Trial this 2.1 in a seperated env.

To try if the build have the same defects we ran into before. FYI @lfbrock @GuillaumeAmat

**Comment by zhangguangtong** [comment]
I successfully rebuild the docker image locally, start a clean containter and tried switch between teams. Switch between teams works again now.

Here is my build steps.

1. Clone mattermost code locally, switch to tag v2.1
```
git clone https://github.com/mattermost/platform.git
cd platform/
git checkout v2.1.0
```
2. Download mattermost release 2.1 tar.gz file to directory platform/docker/2.1/
```
cd docker/2.1/
wget https://github.com/mattermost/platform/releases/download/v2.1.0/mattermost.tar.gz
```
3. Update docker file to use local tar.gz file.
```
# Copyright (c) 2015 Mattermost, Inc. All Rights Reserved.
# See License.txt for license information.
FROM ubuntu:14.04

#
# Install SQL
#

ENV MYSQL_ROOT_PASSWORD=mostest
ENV MYSQL_USER=mmuser
ENV MYSQL_PASSWORD=mostest
ENV MYSQL_DATABASE=mattermost_test

RUN groupadd -r mysql && useradd -r -g mysql mysql

RUN apt-key adv --keyserver pool.sks-keyservers.net --recv-keys A4A9406876FCBD3C456770C88C718D3B5072E1F5

ENV MYSQL_MAJOR 5.6
ENV MYSQL_VERSION 5.6.25

RUN echo "deb http://repo.mysql.com/apt/debian/ wheezy mysql-${MYSQL_MAJOR}" > /etc/apt/sources.list.d/mysql.list

RUN apt-get update \
        && export DEBIAN_FRONTEND=noninteractive \
        && apt-get -y install perl wget mysql-server \
        && rm -rf /var/lib/apt/lists/* \
        && rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql

RUN sed -Ei 's/^(bind-address|log)/#&/' /etc/mysql/my.cnf

VOLUME /var/lib/mysql
# ---------------------------------------------------------------------------------------------------------------------

WORKDIR /mattermost

# Copy over files
ADD mattermost.tar.gz /
#RUN ls -l /mattermost.tar.gz && tar -zxvf /mattermost.tar.gz
ADD config_docker.json /
ADD docker-entry.sh /

RUN chmod +x /docker-entry.sh
ENTRYPOINT /docker-entry.sh

# Create default storage directory
RUN mkdir /mattermost-data/

# Ports
EXPOSE 80
```
4. Rebuild docker image.
` docker build -t mattermost/platform:2.1 . `
5. Start docker containter
` docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform:2.1 `

Here is the build info of the new build.:

Mattermost Team Edition

Version:2.1.0
Build Number:2.1.0
Build Date:Mon Mar 14 20:45:23 UTC 2016
Build Hash:f189bc2073cf800c5f4506a69bdb51d7065269bf

**Comment by GuillaumeAmat** [comment]
@yexingok @zhangguangtong 

When I test the steps from @zhangguangtong, the docker run/up tells me:
```
mattermost | starting platform
mattermost | /docker-entry.sh: line 110: cd: /mattermost/mattermost/bin: No such file or directory
mattermost exited with code 0
```

And the container stops...
Any clue?

Thanks!

**Comment by GuillaumeAmat** [comment]
It's all good! I figured it out :)
The Dockerfile line `ADD mattermost.tar.gz /` had to be `ADD mattermost.tar.gz /mattermost/`.

The new and shiny Mattermost 2.1 is up here, let's see if the issues are gone now.

**Comment by lfbrock** [comment]
Hi @zhangguangtong, yes that change was on purpose - we made some big changes on master after v2.1 and some routes got changed.

**Comment by lfbrock** [comment]
Closing this issue now that v2.2 is out
