### ISSUE TITLE
[Bug] Cannot remove "retry" failed comments

### ISSUE THREAD

**Issue by Endemoniada** [mattermost/platform#2607]
If I send a comment in a channel that fails, for example due to network issues, I get a "retry" link. However, if the comments are later obsolete, I cannot remove them without doing "retry" and sending those comments to the channel anyway. If I don't send them, they persist in the channel indefinitely, at the bottom of the feed.

Please either move failed comments to in-line with the chat history, OR give users an option to "cancel" the comment without sending it to the channel.

**Comment by lfbrock** [comment]
Hi @Endemoniada, thanks for the report - we have a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-1042. 

It's accepting pull requests if someone would like to contribute a fix for this.
