### ISSUE TITLE
wrong email for auth creates unclaimable account

### ISSUE THREAD

**Issue by hasuo** [mattermost/platform#2617]
So, 

currently checking out mattermost. First user that signed up managed to misspell his email. Users... *sigh*
I have email verification turned on. 
The user was immediately created, but now is not claimable nor deleteable (can only switch inactive). 
Later the gmail bounce notification came. 

Options would be a way to delete (before auth), the ability to delete users or the ability to change the email and resend auth mail.

**Comment by enahum** [comment]
you can delete the user using the CLI

**Comment by lfbrock** [comment]
Hi @hasuo, 

We plan to add the ability for the System Administrator to update email addresses - I created a ticket here to track the issue https://mattermost.atlassian.net/browse/PLT-2523.
