### ISSUE TITLE
GIN index does not work when searching posted messages on PostgreSQL

### ISSUE THREAD

**Issue by yukihane** [mattermost/platform#2622]
I guess that  when searching posted messages, [idx_posts_message_txt](https://github.com/mattermost/platform/blob/v2.1.0/store/sql_store.go#L444) index would be used.
>  ```"CREATE INDEX " + indexName + " ON " + tableName + " USING gin(to_tsvector('english', " + columnName + "))"```

However, because of [search query without 2-argument version to_tsvector](https://github.com/mattermost/platform/blob/v2.1.0/store/sql_post_store.go#L731), it does not work.
> ```AND **%s** @@  to_tsquery(:Terms)```

[PostgreSQL docs](http://www.postgresql.org/docs/9.5/static/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX):
> Chapter 12. Full Text Search
> 12.2.2. Creating Indexes
> Because the two-argument version of to_tsvector was used in the index above, only a query reference that uses the 2-argument version of to_tsvector with the same configuration name will use that index. That is, WHERE to_tsvector('english', body) @@ 'a & b' can use the index, but WHERE to_tsvector(body) @@ 'a & b' cannot.

----
I don't hope to fix this problem by putting 'english' on first-argument.
I want search other language, Japanese.

**Comment by it33** [comment]
Thanks @yukihane, 

There seem to be multiple steps required to better support Japanese language search in Postgres: 

1. Document, test and confirm the properly manual settings for better support Japanese searching Postgres. This probably means deleting the English index and rebuilding one that works better for Japanese. 

2. In future, create an install option to run automation that applies those manual settings. 

@yukihane, would you be interested in helping with 1)? 

There is a new page in the Mattermost documentation recently created to help the Japanese community add Japanese language documentation to Mattermost: https://github.com/mattermost/docs/blob/master/source/install/i18n.md

**Comment by yukihane** [comment]
Hi.
This issue is not dependent on Japanese language but on current SQL select query, as I have described above.
Index `idx_posts_message_txt` does not work also on English language searching.

> @yukihane, would you be interested in helping with 1)?

I have wrote one of how to setup, in #2159.
And, I will discuss about treating Japanese language, with @terukizm and others on [the forum](https://forum.mattermost.org/c/international/japanese).

**Comment by terukizm** [comment]
Hi, @it33.

My English is very very poor. I know.
But please let me do the supplementary explanation of that.

## Problems:

###  `idx_posts_message_txt` does not work now

[Create-FULLTEXT-Index-Query](https://github.com/mattermost/platform/blob/v1.2.1/store/sql_store.go#L410) have `'english'` option. 
But [Search-Query](https://github.com/mattermost/platform/blob/v1.2.1/store/sql_post_store.go#L648) dose not have `'english'` option.

I guess @yukihane want to say "This query will not be index-scan". 
His fix plan is:

### 1. Remove 'english' option from create-index-query

In this case, [default_text_search_config](http://www.postgresql.org/docs/9.4/static/runtime-config-client.html#GUC-DEFAULT-TEXT-SEARCH-CONFIG) will become effective.

e.g. 

postgres.conf

``` 
default_text_search_config = 'pg_catalog.english'
```

create index:

```
CREATE INDEX `idx_posts_message_txt` ON POSTSUSING gin(to_tsvector(MESSAGE))`
```

search query:

```
  to_tsquery(:Terms)
```

In this fix, `idx_posts_message_txt` will be valid index-scan.
But, This approach  influences other software to using postgresql.  (e.g. GitLab )

### 2. Add 'english' option to search-query

@yukihane guess this approach is more better.

create index:

```
CREATE INDEX `idx_posts_message_txt` ON POSTSUSING gin(to_tsvector('english', MESSAGE))
```

search query:

```
  to_tsquery('english', :Terms)
```

In this fix, `idx_posts_message_txt` will be valid index-scan.

#### 2.1 Move 'english' option to config file

This is my suggest.
This apporach based on 2, but It will be support [other language in postgresql.](http://www.postgresql.org/docs/9.4/static/textsearch-psql.html).

e.g. 

Add to config.json (ofcourse this is sample)

```
    "PostgresqlSettings": {
        "TextSearchConfig": "english"
    }
```

```
CREATE INDEX `idx_posts_message_txt` ON POSTSUSING gin(to_tsvector(utils.Cfg.PostgresqlSettings.TextSearchConfig, MESSAGE))
```

```
to_tsquery(utils.Cfg.PostgresqlSettings.TextSearchConfig, :Terms)
```

I'm sorry if I'm mistaken.

**Comment by it33** [comment]
Hi @terukizm, 

Sorry for the delay, it took us a while to understand the issue. We now agree it should be changed. 

We're opening a ticket Accepting Pull Requests for this to be added: https://mattermost.atlassian.net/browse/PLT-2808

Would anyone be interested in this?

**Comment by terukizm** [comment]
Hi @it33,

I'm sorry for my late reply, and thank you for your discussion!
I would like to try this.

@yukihane 
Could you help me?
I'll try your proposal.

**Comment by yukihane** [comment]
@terukizm
Yah! I will joyfully help if I can.
