### ISSUE TITLE
autoCorrect is explicitly marked as Off

### ISSUE THREAD

**Issue by Lixivial** [mattermost/platform#2623]
When using the mobile app or any software keyboard, the usability is reduced due to the fact that the React TextBox component explicitly marks autoCorrect as Off. 

Can this be made be set to 'On' in the TextBox component, or, at the very least, become a system-wide setting to re-enable?

**Comment by lfbrock** [comment]
Thanks @Lixivial, we have a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-98

I can make it accepting pull requests if someone is interested in submitting a fix for this?

**Comment by simonwex** [comment]
@Lixivial @lfbrock do you have any thoughts on the scope for the change? We've noticed the same issue when using a software keyboard, would there be any harm in removing the attribute altogether? It makes it a much easier PR.

**Comment by lfbrock** [comment]
Hi @simonwex, I think it would be fine to remove the attribute.

**Comment by Lixivial** [comment]
@simonwex @lfbrock Yeah, in our case, we simply flipped it to Off with no discernible effects. I, too, was concerned about the scope of the change, because I was uncertain of the intent. That's why I avoided doing a PR.

**Comment by lfbrock** [comment]
Closing this issue + will track it in Jira, it's accepting pull requests if anyone wants to take a look at it. 
https://mattermost.atlassian.net/browse/PLT-98
