### ISSUE TITLE
Changing username in webinterface causes certain text to be incorrectly rendered 

### ISSUE THREAD

**Issue by jamespthomas** [mattermost/platform#2632]
Using the web-ui, if you change your username after registration, certain characters within messages fails to render correctly

1) Signup and login
2) Say something in a channel (e.g "test string "one" 'two' > three <")
3) Text should render correctly
4) Change your username
5) Text instantly becomes "test string \&quot;one\&quot; \&#39;two\&#39; \&gt; three \&lt;"
6) Any further text, from anyone, containing this punctuation is now incorrectly rendered

Tested this with two different accounts

Edit: interestingly github parses my example in 5 correctly ;) Edited to escape it

**Comment by hmhealey** [comment]
Hi @jamespthomas. What version of Mattermost are you using? This bug will be fixed in 2.2, but I want to make sure you're not still having it occur on the latest release.

**Comment by jamespthomas** [comment]
Hi @hmhealey 

Thanks for the quick response, we're using

Version:
2.1.0
Build Number:
2.1.0

So I'll try upgrading to 2.2!

**Comment by hmhealey** [comment]
2.2 won't be out for another few weeks unfortunately, but in the meantime, you can have the affected users go into their notification settings (Account Settings > Notifications), click to edit their Words That Trigger Mentions, and then click save. There's some weirdness with the mention handling that's mangling those characters.

Thanks for the repro steps though! I added a quick fix for it which will be in 2.2, but I think I know what's actually causing the issue now.
