### ISSUE TITLE
Is idle and offline timeout configurable?

### ISSUE THREAD

**Issue by djchen** [mattermost/platform#2646]
I noticed that for notifications, it requires the user to be offline for 60 seconds or away for 5 minutes. Is this something thats configurable?

**Comment by lfbrock** [comment]
Hi @djchen, it's not configurable at the moment - what would you want to change it to? 

This might be a good thing to [open a feature request on](http://www.mattermost.org/feature-requests/).

**Comment by djchen** [comment]
Thanks for the info. I would like to see it reduced to 30 seconds for offline and configurable for away.
