### ISSUE TITLE
Google App authenticator not (fully) implemented

### ISSUE THREAD

**Issue by igmar** [mattermost/platform#2654]
Hi,

The 2.1 version gives me a GoogleSettings option. When used, the final step seems to fail : 

/signup/google/complete:LoginByOAuth code=500 rid=XXXXX uid= ip=92.109.33.90 google oauth not avlailable on this server [details: ]

The most relevant config data : 

"Scope": "profile email",
"AuthEndpoint": "https://accounts.google.com/o/oauth2/v2/auth",
"TokenEndpoint": "https://accounts.google.com/o/oauth2/token",
"UserApiEndpoint": "https://www.googleapis.com/plus/v1/people/me"

The last one is the issue : It returns a format that doesn't match the expected JSON : 

type GitLabUser struct {
        Id       int64  `json:"id"`
        Username string `json:"username"`
        Login    string `json:"login"`
        Email    string `json:"email"`
        Name     string `json:"name"`
}

While https://www.googleapis.com/plus/v1/people/me gives a whole different object back, that doesn't match. We can extract id, email and name directly. Username is usually equal to email (it's the address with type account).

We might get away using https://www.googleapis.com/plus/v1/people/me/openIdConnect, which gives the same in OpenID format. That's easier to parse.

Is a pull request acceptable for this to be resolved ?

(Disclamer : First time I ever looked at Go code).

**Comment by it33** [comment]
Hi @igmar, thanks for your question. Google App authenticator is a feature for Enterprise Edition and not supported in the open source Team Edition, so the current design is deliberate. The commercial version is designed to downgrade and upgrade smoothly with the open source edition to avoid data lock in. To provide that benefit, it means portions of the commercial code are contributed to the open source version, which can cause unintended confusion to people reading the code, like it is now. We are discussing how to improve communication of this approach in our code base. You can read more about the distinction between the open source Team Edition and commercial Enterprise Edition in the [manifesto](http://www.mattermost.org/manifesto/).

**Comment by igmar** [comment]
Since you can't buy the commercial version, it's a bad thing that these essential features are locked out, especially since the open source version has issue that are hard to fix (Mattermost -> Gitlab -> Google apps).
