### ISSUE TITLE
404 error from incoming web hook, v2.1.0

### ISSUE THREAD

**Issue by mrcaron** [mattermost/platform#2659]
I'm running the mattermost-dev docker image on a Docker engine hosted by RedHat Enterprise Linux 7.0 Hyper-V VM, forwarding port 8065 to 80 on my VM. I can connect and post messages and interact with the system. As you can see, here's the build information:

![image](https://cloud.githubusercontent.com/assets/72183/14357173/479d8d2e-fcad-11e5-8e53-6727f7aa0b1e.png)

I've setup Incoming WebHooks and entered * in __Allow Cross-origin Requests from__ field:
![image](https://cloud.githubusercontent.com/assets/72183/14357358/fc4b312c-fcad-11e5-8faa-5e07c43c89b0.png)

I have a hook for sending to the Off-Topic space:
![image](https://cloud.githubusercontent.com/assets/72183/14357421/461692ec-fcae-11e5-9e39-708fa2c8b501.png)

I've composed some POSTS from both CURL and Fiddler directly and I see the following in the log file: 

> [2016/04/07 15:17:56 UTC] [EROR] /hooks/n6aqc6yxgjd9ixy89g8skywyry: code=404 ip=10.122.21.128
> [2016/04/07 15:17:56 UTC] [EROR] Error rendering template error err=html/template:error.html:4:11: no such template "head"
> [2016/04/07 15:17:56 UTC] [EROR] Failed to create error page: html/template:error.html:4:11: no such template "head", Original error: Handle404: , 

I saw a post on the forums about this: http://forum.mattermost.org/t/incoming-webhook-throws-404-b-c-of-template-error/1134. Is there any known solution? Is this only because of Docker? Is the image incomplete?

**Comment by andreoav** [comment]
:+1:

**Comment by zhangguangtong** [comment]
I have tried run mattermost 2.1 docker image and got login issue.
https://github.com/mattermost/platform/issues/2606

There two build of mattermost 2.1, one is on Mar 14 and the other is Mar 17 (current images).
The docker images with tag 2.1 currently is problematic.

**Comment by mrcaron** [comment]
So I tried using 2.0; now I can get the web hooks working when I compose them manually, but I get 500s when sending from TFS :-1:

**Comment by mrcaron** [comment]
I noticed that what TFS is sending is this:

`Method: POST
URI: http://IPADDR:PORT/hooks/kd79o1ricbgoxm6faxp9x88xjh
HTTP Version: 1.1
Headers:
{
  Content-Type: application/json; charset=utf-8
}
Content:
{
  "subscriptionId": "00000000-0000-0000-0000-000000000000",
  "notificationId": 10,
  "id": "4a5d99d6-1c75-4e53-91b9-ee80057d4ce3",
  "eventType": "build.complete",
  "publisherId": "tfs",
  "message": {
    "markdown": "Build [ConsumerAddressModule_20150407.2](https://fabrikam-fiber-inc.visualstudio.com/web/build.aspx?pcguid=5023c10b-bef3-41c3-bf53-686c4e34ee9e&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f3) succeeded"
  },
  "detailedMessage": {
    "markdown": "Build [ConsumerAddressModule_20150407.2](https://fabrikam-fiber-inc.visualstudio.com/web/build.aspx?pcguid=5023c10b-bef3-41c3-bf53-686c4e34ee9e&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f3) succeeded"
  },
  "resource": null,
  "createdDate": "2016-04-11T16:15:48.2710536Z",
  "resourceVersion": null
}
`

There is certainly no Text element.

**Comment by fallenby** [comment]
I'm experiencing this issue too.
Freshly pulled docker instance, create incoming webhook.

`➜  ~ curl -X POST -i http://localhost:8065/hooks/ssjjipjn47bkigdyrwcipqrw8y        
HTTP/1.1 404 Not Found
X-Ratelimit-Limit: 10
X-Ratelimit-Remaining: 9
X-Ratelimit-Reset: 1
Date: Mon, 11 Apr 2016 20:29:16 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8`

**Comment by lfbrock** [comment]
Hi @mrcaron, it looks like you will need an intermediate translator to put the output from TFS in the correct format for Mattermost webhooks.

**Comment by lfbrock** [comment]
@fallenby, I think there's an issue with the docker image with the v2.1 tag if that's what you're using - the correct v2.1 should have a build date of Mar 14. There's some discussion [here](https://github.com/mattermost/platform/issues/2606) on how to get the correct build, or the docker image for v2.2 should be released in a couple days.

**Comment by lfbrock** [comment]
Closing this issue now that v2.2 is out
