### ISSUE TITLE
Display uploaded images inline

### ISSUE THREAD

**Issue by matthaias** [mattermost/platform#2665]
At the moment there is a small preview of an uploaded image. In my opinion it would be better, if the image is shown inline with the width from the chat or something like that. Maybe if the client is fullscreen it is not necessary to use the full width. Sometimes the image width is not higher then the chat width, so don't need to click the image. The behavior of the click on the image should be the same (maximize to the client size). I think this should be an option, so that the user can decide.

What do you think?

**Comment by lfbrock** [comment]
Hi @matthaias, 

I think that might make sense for single images, but would you have suggestions on how to handle multiple file uploads (some of which might be images, and some which might be other file types)?

**Comment by matthaias** [comment]
Hi @lfbrock,

thanks for your response and yes, I think you're right. I also think that only makes sense for single images. Until now i only uploaded single images, I didn't even know about the possibility to upload more images :). I think in all other cases it should be the same behavior as now.

**Comment by lfbrock** [comment]
Thanks, will track this issue in Jira: https://mattermost.atlassian.net/browse/PLT-831

**Comment by matthaias** [comment]
Thanks a lot!

**Comment by EvilBob01** [comment]
I was looking for a way to do this also. Thanks for working on it!

**Comment by jaguarondi** [comment]
If there was a way to get a link displayed when uploading an image, it would be possible to insert it inline in markdown. That would also work with multiple images.

**Comment by matthewbryancurtis** [comment]
+1
