### ISSUE TITLE
Mattermost protocol implementation for libpurple (pidgin)

### ISSUE THREAD

**Issue by ajsb85** [mattermost/platform#2668]
Mattermost protocol implementation for libpurple (pidgin)

**Comment by ajsb85** [comment]
Already added
https://mattermost.uservoice.com/forums/306457-general/suggestions/13393107-mattermost-protocol-implementation-for-libpurple

**Comment by lfbrock** [comment]
Thanks!

**Comment by djaswal** [comment]
@ajsb85 how is this exactly added? I wasn't able to find any resources on the subject.

**Comment by rosshadden** [comment]
He meant it was added to the suggestion website.  Hasn't been added in code yet.

**Comment by jtdaugherty** [comment]
For what it's worth, there is a terminal client for MatterMost now in case that will satisfy some of the stakeholders for this request: https://github.com/matterhorn-chat/matterhorn

**Comment by kaptoxic** [comment]
Pidgin plugin repo (tested and working well): https://github.com/EionRobb/purple-mattermost

**Comment by ajsb85** [comment]
Good job @EionRobb
