### ISSUE TITLE
feature request: docker image without MySQL

### ISSUE THREAD

**Issue by brunoqc** [mattermost/platform#2671]
I think it would be better to not run MySQL with mattermost inside the same container since it would allow people like me to use their own already running MySQL server and it's pretty simple to run a second linked container.

I can work on this if you guys agree this should be done.

**Comment by it33** [comment]
Hi @brunoqc, thanks for your offer to help! Would you be interested in joining the [Installers and Images channel](https://pre-release.mattermost.com/core/channels/installers) to discuss?
