### ISSUE TITLE
Error using and Adding Slash Commands

### ISSUE THREAD

**Issue by garethgreenaway** [mattermost/platform#2675]
When attempting to use Slash commands in any Mattermost client I see the following error in the client:
"We couldn't get the commands", 
In the mattermost logs I see the following:
[2016/04/10 02:39:30 UTC] [EROR] /api/v1/commands/list:SqlCommandStore.GetByTeam code=500 rid=rztt1f9muby88xqjhfcrf1wuye uid=355gbiuyxtng9bjyyjxum1cwjo ip=x.x.x.x We couldn't get the commands [details: teamId=nrj1egj3jjro8mg99gcn1z5xce, err=gorp: no fields [externalmanagement] in type Command]

When attempting to add Slash commands I see the same.  Using the latest Mattermost version 2.1 running inside a Docker container.

**Comment by lfbrock** [comment]
Hi @garethgreenaway, can you check the build information from Main Menu > About Mattermost? I think there was a problem with the last docker latest having the wrong build, (see the discussion [here](https://github.com/mattermost/platform/issues/2606)).

**Comment by garethgreenaway** [comment]
Build Date: Mon Mar 14 20:45:23 UTC 2016
Build Hash: f189bc2073cf800c5f4506a69bdb51d7065269bf

**Comment by hmhealey** [comment]
Did you downgrade your server from a newer version of Mattermost? That error message means that there's an extra column in the database. If you're comfortable editing the database directly, you can go in and drop the extra `ExternalManagement` column in the `Commands` table

**Comment by garethgreenaway** [comment]
I do not believe it has been downgraded from a newer version of Mattermost.  I'll go ahead and remove the column from the table and see it that helps.  Thanks!

**Comment by garethgreenaway** [comment]
Looks like that fixed it.  Thanks!

**Comment by MikaelCluseau** [comment]
FWIW I had the same error right after an upgrade to 3.0.
