### ISSUE TITLE
https://github.com/mattermost/platform/blob/8a65601db424d5969448b06ae4e3048a7f34bd94/web/react/utils/utils.jsx#L51

### ISSUE THREAD

**Issue by MarkYSA** [mattermost/platform#2677]
https://github.com/mattermost/platform/blob/8a65601db424d5969448b06ae4e3048a7f34bd94/web/react/utils/utils.jsx#L51

maybe should be something like (^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.) ?

**Comment by crspeller** [comment]
@MarkYSA Yup. It should be. Whoever implemented that whent with a quick solution instead of the correct one. Up for making a Pull Request?

**Comment by lfbrock** [comment]
Created a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-2789
