### ISSUE TITLE
Arrows are replaced with &gt; &lt;

### ISSUE THREAD

**Issue by OlegTar** [mattermost/platform#2682]
there is double encoding of arrows and quotes

**Comment by gitthismoney** [comment]
i have a similar issue that i can reproduce is all major web browser and the desktop/IOS clients with double and single quotes. 

![screen shot 2016-04-11 at 08 51 31](https://cloud.githubusercontent.com/assets/404807/14433397/0e529834-ffc3-11e5-9052-efac73cd8aca.png)

**Comment by lfbrock** [comment]
This should be fixed by https://github.com/mattermost/platform/pull/2424 in v2.2 (releasing April 16)

**Comment by OlegTar** [comment]
@lfbrock thank you. I'll close the issue
