### ISSUE TITLE
Installation without Docker

### ISSUE THREAD

**Issue by djoker** [mattermost/platform#2683]
In the company I work we are not allowed to use Docker. Is there a guideline for installations without it or from source? Thanks for the work

**Comment by lfbrock** [comment]
Hi @djoker, we have a list of [Install Guides](http://www.mattermost.org/installation/) you can take a look at. You can install a production instance without using docker, or there might be something else there that works for you.

**Comment by djoker** [comment]
Thanks! I will try

==============================================
There are only 10 types of people in the world
Those who understand binary, and those who
don't
==============================================
          Elvis is dead. Deal with it
==============================================
