### ISSUE TITLE
LDAP creating of teams

### ISSUE THREAD

**Issue by norganna** [mattermost/platform#2687]
When creating teams as an LDAP user, the following error appears.

![screen shot 2016-04-12 at 5 46 15 pm](https://cloud.githubusercontent.com/assets/694366/14453250/07a0ec06-00d7-11e6-9271-f2ec0e48c041.png)

Even though the LDAP user has an email address, the "username" isn't an email address.

**Comment by lindy65** [comment]
Thanks @norganna, ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2584
