### ISSUE TITLE
Webhooks are not triggered when the trigger word is followed by a newline..

### ISSUE THREAD

**Issue by ticki** [mattermost/platform#2688]
**Expected behavior**: A trigger word followed by a whitespace other than space should also trigger webhooks.

**Current behavior**: The word _must_ be followed by a space, it is invalid to do e.g.

    playbot:

    ```
    2 + 3
    ```

since `playbot:` is registered as trigger word, but it is not followed by a space, but instead a newline (which creates confusion).

**Comment by lfbrock** [comment]
Hi @ticki, I just tested this with our giphy integration, and using new lines seemed to work fine. Do you have it set to send messages on Ctrl + Enter?

**Comment by ticki** [comment]
> Do you have it set to send messages on Ctrl + Enter?

Nope.

**Comment by lindy65** [comment]
Thanks @ticki, ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2583
