### ISSUE TITLE
Realtime messaging not working

### ISSUE THREAD

**Issue by gravufo** [mattermost/platform#2695]
Hi,

I am using the docker version of mattermost 2.1 (latest) behind a reverse-proxy docker (nginx + nginx-gen) using https (lets-encrypt). The proxy and mattermost communicate in http, though (only client to proxy is SSL).

I am connecting to the web chat client from work and I don't seem to be getting realtime messages (have to refresh before getting new messages). I don't see any websocket error on the webpage nor in the web browser console.

Any ideas?

Thanks

**Comment by gravufo** [comment]
Sorry, turns out it was a misconfiguration on my nginx (nginx-gen doesn't add the necessary config for websockets).

I followed this to fix it: https://gitlab.com/gitlab-org/omnibus-gitlab/issues/740

Thanks

**Comment by gravufo** [comment]
Well, I'm back. It only worked intermittently. Something is definitely wrong and I kinda don't think it's an nginx config issue since I have other services running behind the reverse proxy with the same config (autogenerated by nginx-gen docker) and websockets seem to work just fine.

I can provide nginx config if necessary.

**Comment by lfbrock** [comment]
Hi @gravufo, can you try posting on the forums (instructions above) to track down whether this is a bug or a set up issue, and if it's a bug what the repro steps are?
