### ISSUE TITLE
Cannot reply "as user" from slash command if overriding is enabled.

### ISSUE THREAD

**Issue by norganna** [mattermost/platform#2698]
If there is no username or icon specified in slash command config, the command comes from "webhook" instead of the user that typed the command, but if "reply as user / icon" is set to false in the config the command comes from the invoking user's name / icon.

Also the slash command is inconsistent in that you are not allowed to specify a username/icon in the reply from the handler unlike with the webhooks. If I were able to specify those fields this would be a non-issue as I could just parrot back the requesting user's name / icon in the response JSON.

**Comment by lfbrock** [comment]
Thanks @norganna, I made a ticket for allowing Slash Commands to specify username/icon in the reply: https://mattermost.atlassian.net/browse/PLT-2610

**Comment by lfbrock** [comment]
Closing this issue and will track in Jira, also made it accepting pull requests if someone would like to work on this.
