### ISSUE TITLE
Trace Option

### ISSUE THREAD

**Issue by Beastie71** [mattermost/platform#2705]
We've got an issue where in the last 24 hours mattermost has started crashing every few minutes, sometimes not even lasting a minute, other times lasting for longer.  Unfortunately the debug information that is generated has not been useful in tracking down whats actually happening.  Most of the time it appears a call to a specific channel, but not all the time.

There needs to be a way to get a deeper trace of what is actually happening, possibly a Trace log level instead of just Debug.  Possibly getting deep enough into the SQL calls so that you can try to isolate issues like this.  

FYI, we've even done an strace on the PID to figure out whats going on and thats been totally unhelpful in resolving things.

**Comment by lfbrock** [comment]
Hi @Beastie71, can you try posting this in the troubleshooting forums about your issue?

I agree that a more detailed level of logging may be helpful for this, would you be open to suggesting a [feature idea](https://mattermost.uservoice.com) on that with what information you would like to see, so others can add their thoughts as well?

**Comment by Beastie71** [comment]
mattermod - will do, thanks.

lfbrock - doh, thats what this should have been, no problem, thanks!  And Done!

**Comment by lfbrock** [comment]
Thanks!
