### ISSUE TITLE
EnableCustomBrand in team_settings requires existence check

### ISSUE THREAD

**Issue by norganna** [mattermost/platform#2710]
https://github.com/mattermost/platform/blob/master/webapp/components/admin_console/team_settings.jsx#L105

In order to work with non-Enterprise licensed edition, needs wrapping like such:

``` go
        if (this.refs.EnableCustomBrand) {
            config.TeamSettings.EnableCustomBrand = this.refs.EnableCustomBrand.checked;
        }
```

**Comment by hmhealey** [comment]
Thanks for the heads up on this! We're currently in the process of reorganizing those settings so I'll make sure to fix that when I get to that page

**Comment by lfbrock** [comment]
@hmhealey, this might already be fixed on master

**Comment by hmhealey** [comment]
@jwilander Fixed this with some of his other changes
