### ISSUE TITLE
"There appears to be a problem with your internet connection" should disappear when connection comes back

### ISSUE THREAD

**Issue by nicolas-raoul** [mattermost/platform#2711]
The message stays forever until I dismiss it manually. It should disappear automatically when Internet is back.

Since my connection seems to micro-cut at least every hour, closing it every time takes time. If I could leave it there I would, but it occupies some screen estate, prevents me from seeing the name of the channel, and blocks access to some important menus and other information.

This is different from #2468 and https://mattermost.atlassian.net/browse/PLT-2399 which are about email settings with the bar coming back every minute (here it is not that bad).

**Comment by lfbrock** [comment]
Hi @nicolas-raoul - thanks for the report, I made a ticket to track this issue here: https://mattermost.atlassian.net/browse/PLT-2399

**Comment by lfbrock** [comment]
Closing this issue + will track in Jira

**Comment by nicolas-raoul** [comment]
@lfbrock Oh I understand now, thanks :-) I removed my now irrelevant comment at PLT-2399.

For anyone finding this, the bug is now tracked at https://mattermost.atlassian.net/browse/PLT-2607

Cheers!
