### ISSUE TITLE
Fallback for window.requestAnimationFrame

### ISSUE THREAD

**Issue by PaveLiArcH** [mattermost/platform#2721]
Can we have fallback for requestAnimationFrame for old browsers? It will be useful mostly for old IE and old android browsers (see http://caniuse.com/#feat=requestanimationframe)

Sample of such fallback solution can be found here: http://codepen.io/alexandredees/pen/CaEIK
```javascript
(function(){
  var lastTime = 0;
  var vendors = ['ms', 'moz', 'webkit', 'o'];
  for(var x = 0; x < vendors.length && !window.requestAnimationFrame; ++x) {
    window.requestAnimationFrame = window[vendors[x]+'RequestAnimationFrame'];
    window.cancelAnimationFrame = window[vendors[x]+'CancelAnimationFrame'] || window[vendors[x]+'CancelRequestAnimationFrame'];
  }
  
  if (!window.requestAnimationFrame){
    window.requestAnimationFrame = function(callback, element){
      var currTime = new Date().getTime();
      var timeToCall = Math.max(0, 16 - (currTime - lastTime));
      var id = window.setTimeout(function(){ callback(currTime + timeToCall); }, timeToCall);
    lastTime = currTime + timeToCall;
      return id;
    };
  }

  if (!window.cancelAnimationFrame){
    window.cancelAnimationFrame = function(id){
      clearTimeout(id);
    };
  }
}());
```
Yes, it's weird, but it's better than nothing

**Comment by it33** [comment]
Thanks @PaveLiArcH, 

Appreciate your feedback, will queue this for discussion in the [UX design channel.](https://pre-release.mattermost.com/core/channels/ux-design). If the change were approved, would you be interested in helping add this?

**Comment by PaveLiArcH** [comment]
@it33, as I said at UX channel, i can implement this and provide as pull request

**Comment by lfbrock** [comment]
Hi @PaveLiArcH, we discussed the change and because we don't officially support Android browsers lower than 4.4 we're not able to accept the change you're proposing. Specifically, we don't want to confuse the community by reviewing and testing improvements to unsupported platforms, when that energy needs to go into supported platforms.
