### ISSUE TITLE
Experimental windows/osx dist builds don't build natively anymore on windows/osx

### ISSUE THREAD

**Issue by norganna** [mattermost/platform#2727]
Specifically there is an assumption made in the makefile that you're cross-compiling from linux to windows/osx and that at https://github.com/mattermost/platform/commit/b23eeff4fc48ef89670dbbb1c809d938c8cbd6f8#diff-b67911656ef5d18c4ae36cb6741b7965R183 :

The linux binary will be in $(GOPATH)/bin/platform
The windows binary will be in $(GOPATH)/bin/windows_amd64/platform
The osx binary will be in $(GOPATH)/bin/darwin_amd64/platform

This is true when building on linux, however not when you're building on OSX (and I assume Windows).

When building on OSX, the bin/platform is the darwin_amd64 version and the linux version is in bin/linux_amd64/platform

**Comment by crspeller** [comment]
See my comments here: https://github.com/mattermost/platform/pull/2718
