### ISSUE TITLE
Support Attachments for Outgoing Webhooks

### ISSUE THREAD

**Issue by johnnyleitrim** [mattermost/platform#2728]
We would like our server (which we have configured as the endpoint for mattermost outgoing webhook) to receive attachment information for messages.

At present, if someone sends a mattermost message, we receive a notification through the webhook, but there is no information about any attachments that the message may have.

I see that incoming webhooks had specify attachments, so it seems that outgoing messages should support attachments for outgoing webhooks too.

Alternatively, sending the file names in the webhook (so that we can use the API to retrieve the files ourselves) would also be useful.

**Comment by lfbrock** [comment]
Hi @johnnyleitrim, 

The attachments in incoming webhoooks are actually not file attachments in Mattermost, they refer to functionality that was added to be compatible with [Slack APIs](https://api.slack.com/docs/attachments). 

I can see how adding information about file attachments could be useful though - if the team decides this is something we'd accept pull requests on, would you be interested in working on it?

**Comment by johnnyleitrim** [comment]
Sure.  We've already got a "fix" in our local code base, so we'd make a pull request if it was open.

**Comment by lfbrock** [comment]
Thanks @johnnyleitrim, we were discussing this and wondered if it would be more useful to send the team ID and post ID so any information about the post can be looked up with the APIs?

Any thoughts on this?

**Comment by lfbrock** [comment]
Made an accepting pull request ticket if someone would like to work on this: https://mattermost.atlassian.net/browse/PLT-2650
