### ISSUE TITLE
[Feature] allow answering on any message

### ISSUE THREAD

**Issue by samogot** [mattermost/platform#2732]
It would be great if it would be possible to answer on any message in chain, not only for chain at all

![now](https://cloud.githubusercontent.com/assets/11226228/14590336/682a722c-0500-11e6-8595-e1860d597d31.png)

hierarchical comment chains would be great, but if it very hard - ability only to cite or mark parent comment with link to jump to it would be enough. for example something like this:
![what I want](https://cloud.githubusercontent.com/assets/11226228/14590387/a7aac5ae-0501-11e6-8431-54d5069d1cc6.png)

**Comment by lfbrock** [comment]
Hi @samogot, can you help me understand more about your use case? Are you finding conversations in comment threads get too complicated to follow the way it is now? 

I think it would be hard to show hierarchical comment threads in the current UI, but it would be great if you could [open a feature idea](http://www.mattermost.org/feature-requests/) on it. If it's something that's very popular we might consider it in the future. 

As for the "commented on" messages, you're suggesting it would say "Commented on:" followed by a summary of the message the user initially clicked "reply" on? 

I can see how that might be useful, but I'm not sure if it would get confusing - people might click reply on a message, and then read the comment thread, and end up responding to something someone else said within the comment thread. Any thoughts on this?

**Comment by samogot** [comment]
Yes, i think that some times, not very often, conversation may be more complicated, than comment threads can serve now. Especially in off-topic channel with a lot of members.
But when I think about in again I consider, that fully hierarchical comment threads is overkill, so I wouldn't open a feature idea about it.

As for the "commented on" messages - yes, that was an initial idea. I am agree that it is something confusing, especially for people who is accustomed with current comment threads functionality. I have 2 different ideas about it.

The first idea is to divide reply button into two functionalities - reply message and reply thread. by examples:

On non-threaded messages you only can start new comment thread
![single non-thead message](https://cloud.githubusercontent.com/assets/11226228/14671224/6b65dc1a-06f9-11e6-9984-5d52fa7fd2dd.png)
But on threads you also can reply on this particular message
![message in thread](https://cloud.githubusercontent.com/assets/11226228/14671299/bb15ac0e-06f9-11e6-8024-6e6cafdd9c9a.png)
While replying on particular message this is explicitly shown, also there is a way to dismiss replying message, so it will be default comment to thread at all.
![image](https://cloud.githubusercontent.com/assets/11226228/14671487/b2e94e4a-06fa-11e6-9933-70307749802d.png)
Moreover there are any Reply message button on each message in comment thread window


The second idea is pure new mechanism - citation. Something like this:

Cite a full message
![cite full message](https://cloud.githubusercontent.com/assets/11226228/14670991/39d69190-06f8-11e6-8461-9207f37102e7.png)
Cite selected text only, when something is selected
![cite selected text only](https://cloud.githubusercontent.com/assets/11226228/14670945/fa246cc0-06f7-11e6-82a2-89a3be701fd6.png)
That result in this 
![result](https://cloud.githubusercontent.com/assets/11226228/14670797/4714ffb4-06f7-11e6-957e-5d484de938ac.png)
_clicking on date link will jump to the message_

Advantage of citation is that we can reply on several messages at once. for example to mark a context if that messages initially wasn't a comment thread. Also it is more common functionality for users migrating from classical messengers, like skype

Disadvantage is a fact that user can make one similar action (reply on single non comment thread message) in several ways, which is conflicted with each other

**Comment by lfbrock** [comment]
Thanks @samogot, the UX team is planning to look at ways to improve the usability of replies + threaded messaging, I've added your ideas as something to consider to this ticket: https://mattermost.atlassian.net/browse/PLT-2637

**Comment by samogot** [comment]
@lfbrock One more available option of citation is forwarding. Cite a message from one channel into another. Like in Telegram
