### ISSUE TITLE
[Feature] marking posts as read on viewing, not all in channel at once 

### ISSUE THREAD

**Issue by samogot** [mattermost/platform#2733]
For example I have off-topic channel with 1000 unread messages. I want to read them all, but it takes 15 minutes or more. I start reading, read about 200 messages, but at that time I receive very important direct message, or mention in other channel. I switch to that channel, do what I need, but when I come back to off-topic channel, i have all messages marked as read. moreover - I instantly jump to the end of a channel, not to place where i stop reading. 

Also even if channel is opened, but i am reading something in past (not only last unread messages), new messages in this channel must`t instantly become marked as read until I really scroll to them

**Comment by samogot** [comment]
https://mattermost.uservoice.com/forums/306457/suggestions/13496355
yes, i can implement this, if it would be approved

**Comment by lfbrock** [comment]
Thanks @samogot, just curious - for the first case, would being able to manually set the position of the New Messages indicator work for this? I'm just thinking it would be hard to know the exact position of where someone stopped reading, so maybe letting users pick a place to set the indicator would be better.

**Comment by samogot** [comment]
I do not think it's worth it. Allowing the user to specify the location where he completed is a great complexity both in terms of development and in terms of interface. Messages that were on the screen are marked as read. Even if there are a few extra unread messages - to find a place from which you want to continue reading in the range of the screen should not be a problem.

**Comment by lfbrock** [comment]
Thanks @samogot, we'll have to think about this a little bit more. If we do implement it, I think we would also need to add the ability to mark the entire channel as read, for cases where people don't want to have to scroll through all the messages in a channel (for example if a lot of messages stack up in a channel someone doesn't visit often, they might not want to read them all to mark the channel as read).

If anyone else from the community has feedback on this, please add it in to the [feature suggestion](https://mattermost.uservoice.com/forums/306457/suggestions/13496355) - if the idea is popular enough, we might add this in.

**Comment by samogot** [comment]
Thanks @lfbrock, notify me if it will become APR Ticket

**Comment by lfbrock** [comment]
Will do, thanks

**Comment by burka** [comment]
You could mark any message above the last message seen as read. That way you won't loose the scrolling position and if you jump to the end all would get marked read.
