### ISSUE TITLE
Difference in API behavior when upgrading from 2.0 to 2.2

### ISSUE THREAD

**Issue by jw3** [mattermost/platform#2749]
Any insight as to what may be causing me to see different behavior in the following example after upgrading from 2.0 to 2.2?

At 2.0 the following curl would create a message in the specified channel
```plain
curl -d '{"message":"test","channel_id":"9tmskijgsprq8nbuzqh5dp69bh"}' --cookie "MMTOKEN=w1i956pwhbrn5crqhzbpz3fnxc" mattermost:8080/api/v1/channels/9tmskijgsprq8nbuzqh5dp69bh/create
```

At 2.2 I get the following error
```
{"id":"api.context.session_expired.app_error","message":"Invalid or expired session, please login again.","detailed_error":"token=w1i956pwhbrn5crqhzbpz3fnxc","request_id":"kd3h4y496jf5mc8q3gw5wyouea","status_code":500,"is_oauth":false}
```

The token being used works through the web UI.

I have been looking over the changes to the API, nothing stands out as obvious to my novice eye.  I do not have the 2.1 image available to test against.

Thanks

**Comment by jw3** [comment]
I see some changes between [2.0](https://github.com/mattermost/platform/blob/release-2.0/api/context.go) and [2.2](https://github.com/mattermost/platform/blob/release-2.2/api/context.go) in [api/context.go](https://github.com/mattermost/platform/blob/release-2.2/api/context.go) which look related.

Not sure I have my head wrapped around what exactly changed there, perhaps in `ApiUserRequired`

**Comment by coreyhulen** [comment]
Try passing the session id via a header vs a cookie.  Something like

`--header "Authorization: BEARER w1i956pwhbrn5crqhzbpz3fnxc"`

**Comment by jw3** [comment]
@coreyhulen your suggestion did the trick.  Appreciate it.
