### ISSUE TITLE
Creating the same direct channel twice renders verbatim database server error

### ISSUE THREAD

**Issue by fallenby** [mattermost/platform#2750]
Attempting to create a direct channel twice via `/api/v1/channels/create_direct` will render an error with detail straight from the database server.

The request:

> POST /api/v1/channels/create_direct HTTP/1.1
> Host: XXXX
> User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
> Accept: application/json, text/javascript, */*; q=0.01
> Accept-Language: en
> Accept-Encoding: gzip, deflate, br
> Content-Type: application/json
> X-MM-TokenIndex: 0
> X-Requested-With: XMLHttpRequest
> Content-Length: 40
> Cookie: MMTOKEN=XXXX
> Connection: close

> {"user_id":"XXXX"}

The response:

> {"id":"store.sql_channel.save_channel.exists.app_error","message":"A channel with that URL already exists","detailed_error":"id=XXXX, pq: duplicate key value violates unique constraint \"channels_name_teamid_key\"","request_id":"XXXX","status_code":500,"is_oauth":false}

This leaks a little bit of info straight from the DB. Maybe it would be best to remove the `detailed_error` from the JSON object entirely? Unless it has a purpose that is used elsewhere.

**Comment by jwilander** [comment]
Hi @fallenby, you're right that there really isn't any reason to return the detailed error to the client. Originally we planned to not return it to the client but it was so useful for debugging that we had left it in but not we should probably turn it off. It'll still be the in the server logs so the system administrator can make use of them and as we develop we can seem them there for debugging purposes.

I've created a [ticket here](https://mattermost.atlassian.net/browse/PLT-2647) to track and get the process started on removing detailed_error from the client error responses.

Thanks for your help!
