### ISSUE TITLE
/join always returns 'We couldn't find the channel'

### ISSUE THREAD

**Issue by JohnnyFlash** [mattermost/platform#2764]
**Summary:** When attempting to use the /join command to switch channels, the only message ever returned is "We couldn't find the channel'

**Steps to reproduce:** type /join off-topic in any channel
**Expected behavior:** Expect to switch to the Off-Topic channel
**Observed behavior:** Error message from System - We couldn't find the channel

**Comment by lfbrock** [comment]
Thanks @JohnnyFlash, I think there's an issue where /join only works for joining new channels you aren't yet. @lindy65 please file a ticket on this?

**Comment by lindy65** [comment]
Thanks @JohnnyFlash @lfbrock Ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2652
