### ISSUE TITLE
[Feature] Drag channels in sidebar to reorder them.

### ISSUE THREAD

**Issue by norganna** [mattermost/platform#2765]
In HipChat we can drag our channels in the sidebar to a user-preferred order which allows us to put our most commonly accessed channels all together at the top, instead of a fixed alphabetical order.

I believe such a feature in Mattermost would be beneficial also.

**Comment by grexe** [comment]
why was this very useful feature request closed without reason?
See also https://mattermost.uservoice.com/forums/306457-general/suggestions/18655189-reorder-channels

**Comment by norganna** [comment]
Can't remember. I think I was told not to put feature requests in the issue tracker. To be honest it's so long and so many projects ago that I have difficulties recalling.
