### ISSUE TITLE
Increasing message limit?

### ISSUE THREAD

**Issue by hany** [mattermost/platform#2769]
Seems the platform has a hardcoded limit of 4000 characters per message. Is there any reasoning for this? Can it be bumped up or made configurable? We have legitimate use cases where individual messages can be larger than this limit.

**Comment by lfbrock** [comment]
That might be possible, how often are your users hitting the limit on message length? Can you explain a little more about the use case?

**Comment by kuuji** [comment]
@lfbrock our hubot sends us some alerts that are longer than 4000 characters. Same thing for hubot help command. It doesn't work when you have few hubot scripts installed.

**Comment by hany** [comment]
We actually just switched over to Mattermost yesterday, and have run up against the limit almost hourly. Our monitoring system sends us a lot of diagnostic information with each alert, and this regularly hits the limit.

**Comment by lfbrock** [comment]
Thanks for the feedback, do you have an estimate of what max message length you would need to not hit the limit regularly?

**Comment by hany** [comment]
@lfbrock likely double or triple the value (8000 or 12000).

**Comment by hany** [comment]
@lfbrock if we wanted to temporarily compile a custom Mattermost build with a new max message size (to address our immediate concern), where should we look to make these changes?

**Comment by contolini** [comment]
We have a couple hubot scripts hitting the limit. We circumvent it by posting large messages to [anonymous GitHub gists](https://github.com/cfpb/hubot-eavesdrop/blob/4dd76fe26521a610621edc6404a765e5612e9d22/src/eavesdrop.coffee#L72-L77). It would be ideal if the character limit was configurable via the System Console.

**Comment by lfbrock** [comment]
Would someone be willing to open a [feature request](http://www.mattermost.org/feature-requests/) on this? 

We discussed it, and currently 4000 characters is the maximum limit for the type of database column we're using. If we were to change it to something that can support longer messages, there was some concern there could be a performance hit on the application. 

Because of this, we don't plan on making any changes at this point in time, but if more people start hitting this issue it may be addressed in future.

**Comment by hany** [comment]
The problem with the way it's handled currently is clients silently fail. You don't even realize that messages are not coming through unless you check the logs. 

Is there a way to chunk responses up perhaps to address the performance concerns?

**Comment by it33** [comment]
Opening [a thread on the forums to discuss approaches and best practices for automation that posts messages longer than 4000 characters.](https://forum.mattermost.org/t/recommendations-for-handling-automation-that-wants-to-post-messages-longer-than-4000-characters-per-message/1393)

Closing this issue since since we have an answer.

**Comment by mjasion** [comment]
Hi @lfbrock 
Did you try `text` type instead ? 

Postgres documentations says, that:
>"there is no performance difference among these three types" 

https://www.postgresql.org/docs/9.2/static/datatype-character.html

---
We had this problem when we tried to send some stack trace...

**Comment by coreyhulen** [comment]
That may be true for Postgres, but for other database types `Text` vs `Varchar` may have performance differences.

**Comment by vladislav121** [comment]
Please increase the limit more than 4000 characters in future versions.
When is it possible to expect ?

**Comment by rascalcmos** [comment]
4000 chars limit is definitely not enough when sending formatted charts with images and other items using markdowns. My table takes about half a page and is already at the limit.

**Comment by dkpeall** [comment]
Man this is so annoying! how hard could it possibly be...

**Comment by fibbs** [comment]
I am also getting a lot of complaints of my users. Our developers use Mattermost to discuss problems, and they frequently tell me they are not able to post stacktraces due to the message size limit.

**Comment by it33** [comment]
@rascalcmos @dkpeall, @fibbs appreciate your feedback, 

We have a ticket here discussing the options: https://mattermost.atlassian.net/browse/PLT-5929

Does the ability to automatically split text over 4K into multiple messages in 3.7.1 help, or do you need other options mentioned in the ticket? 

PS: GitHub issues is for bug reports, this is more a feature proposal and typically would go into [the feature proposal forum](https://www.mattermost.org/feature-ideas/), then into [Jira](https://mattermost.atlassian.net/issues/?filter=13501), where it is now.

**Comment by it33** [comment]
Also, @rascalcmos @dkpeall, @fibbs, if what's there doesn't meet yet meet all your needs, would any of you, or people on your team, be interested in helping implement any of the solutions mentioned? 

Would be a great help for the community, and you'd influence its design.

**Comment by fibbs** [comment]
The link mentioned above says the automatic splitting of longer messages into several posts is included in 3.7.1. I am on 3.7.2 but it's not splitting messages. Am I missing something or has it been pushed forward? How can I get access to the pre-release link also mentioned in the above mentioned link of the ticket?

**Comment by knirch** [comment]
To clarify, the linked issue is for INTEGRATIONS, not for people.
