### ISSUE TITLE
Cleartext Database Password is not safe!

### ISSUE THREAD

**Issue by aabergaa** [mattermost/platform#2770]
The configuration json stores the database password in **plain text**. For some organizations, this is not allowed, and passwords must be hashed. Is there a way of converting the sql database string in the config.json to allow a hashed version of the password instead of a plain text? 
I would consider this to be a **major** **security** issue.

**Comment by lfbrock** [comment]
Hi @aabergaa, what kind of installation are you referring to?

If it's the docker preview install, that is only meant for previewing Mattermost and is [not meant for production](http://docs.mattermost.com/install/docker-local-machine.html#local-machine-setup-and-upgrade). There is a [new production docker image](https://github.com/mattermost/mattermost-docker) you should use for production installs, or there are other install instructions listed [here](http://www.mattermost.org/installation/). 

Also in future, if you suspect something is a security issue we ask people to report them via security@mattermost.com.

**Comment by aabergaa** [comment]
HI @lfbrock, I am doing a production install following the docs.mattermost.com guide for rhel7. 
Taken explicitly from this site, section 6:

> Configure Mattermost Server by editing the config.json file at` /opt/mattermost/config`
    `cd /opt/mattermost/config`
    Edit the file by typing:
    `sudo vi config.json`
    replace DriverName": "mysql" with DriverName": "postgres"
    replace "DataSource": "mmuser:mostest@tcp(dockerhost:3306)/mattermost_test?charset=utf8mb4,utf8" with "DataSource": "postgres://**mmuser:_mmuser_password_**@10.10.10.1:5432/mattermost?sslmode=disable&connect_timeout=10"
    Optionally you may continue to edit configuration settings in config.json or use the System Console described in a later section to finish the configuration.

It clearly states to insert the clear-text password into a configuration file on the machine (i.e. mmuser:mmuser_password under the "DataSource" string. This is not running in a docker container, but on the mattermost host itself. Looking at the puppet scripts to do an install does not change anything either, the password will still be present.

**Comment by lfbrock** [comment]
Ah I see, thanks @aabergaa. Spoke to the team about this, and the feeling was that this isn't uncommon in other products (eg Wordpress), but we would be able to encrypt that part of the config file. 

I made a ticket here for the issue, it's also accepting pull requests if anyone wants to work on it.
https://mattermost.atlassian.net/browse/PLT-2667
