### ISSUE TITLE
[Feature] shortcuts

### ISSUE THREAD

**Issue by kuuji** [mattermost/platform#2771]
Hey guys,

Do you plan to add more shortcuts to mattermost ?
eg. ctrl + k to switch channel, tab name without @ to mention, etc.

cheers

**Comment by lfbrock** [comment]
Hi @kuuji, yes we do plan on adding shortcuts - we have a [spec](https://forum.mattermost.org/t/accepting-pull-requests-keyboard-shortcuts/1184) available on the forums for the ones that are initially planned, which includes ctrl + k for channel switching. 

Would you be interested in helping out with any of them? Anything listed in the spec is open for accepting pull requests, and if there's something not in the spec you're interested in we would be happy discuss that as well.

**Comment by kuuji** [comment]
Hey thanks for your quick response @lfbrock. 
I'll check this out 😃
