### ISSUE TITLE
When creating a new channel the Chinese example name is inappropriate

### ISSUE THREAD

**Issue by jasonpeacock** [mattermost/platform#2773]
One of my users reported this - not good when you're installing MM at work.

It is written in Chinese, and it means “office affairs/romance" (see screenshot):

![Imgur](http://i.imgur.com/7PDtxN6.png)

Can we remove or change it?

**Comment by lfbrock** [comment]
Thanks @jasonpeacock, pull request here to fix the issue: https://github.com/mattermost/platform/pull/2784

**Comment by jasonpeacock** [comment]
Thanks!
