### ISSUE TITLE
Internal server error when trying to register a user

### ISSUE THREAD

**Issue by patoupatou** [mattermost/platform#2781]
Hi!

We're using the latest release version of mattermost provided by Docker, since we upgraded to the latest dockerfile version, we have a problem where there is an infinite loading screen when trying to register a new user. See the image below : 

http://i.imgur.com/e1igN4P.png

The current url is hostname:port/signup_user_complete/?id=

Any hints on how we should be debugging this? Right now this is a total blocker, nobody can create accounts and we do not know how to do it via other means (database access, API, etc.).

Thank you!

**Comment by lfbrock** [comment]
Hi @patoupatou, can you go to the main menu and "About Mattermost" and let us know what version number you see there?

**Comment by patoupatou** [comment]
Hi @lfbrock,

Mattermost Team Edition T0

Version:2.1.0
Build Number:6562
Build Date:Thu Mar 17 16:17:34 UTC 2016
Build Hash:2cd006474ec8a808b2ea2b0502a842f44cb0b127

**Comment by lfbrock** [comment]
Hi @patoupatou, I think there was an issue with that build (actual v2.1 build was on Mar 14). v2.2 should be available now though, so if you update to that the issue should be taken care of.

**Comment by patoupatou** [comment]
Ok I'll get back to this thread if it works.

Thanks
