### ISSUE TITLE
User status is set to idle/away even while active

### ISSUE THREAD

**Issue by Stof25** [mattermost/platform#2791]
It seems that idle detection only takes into account when you are actively using the Mattermost windows (browser tab/desktop application) and not if the user is actually using his computer.

Would it be possible to detect idle status no matter what is currently in focus instead?

**Comment by jwilander** [comment]
Hi @Stof25, I think we're already tracking a bug [here](https://mattermost.atlassian.net/browse/PLT-2357). Does that sound like your issue?

When running Mattermost inside your browser, we're kind of at the mercy of the browser as to whether we can report events to the server or not but I'm pretty sure in most cases it keeps the WebSocket alive with PING/PONG messages which should keep the status as away and not offline at least.

**Comment by Stof25** [comment]
Well no it's not the same. I can also say that I don't think we have that offline issue at all since we had someone away for a couple days leaving their computer turned on and they were still online. Although it'd be nice if there was some kind of "extended away" status for those cases but I digress.

In our case, it's purely that people still using their computers are flagged as away until they put in focus and use the browsing window or the desktop application. If the browsers cannot be convinced to give that info, maybe it could just be done as an improvement in the desktop application? Still I filled the issue here because it's not specific to the application.


I forgot to put some info on our setup. We are using Mattermost 2.1.0 (soon updated to 2.2.0) installed through the Gitlab Omnibus package. The most common client configuration is the Mattermost-desktop application version 1.1.0 or 1.1.1 but the issue was also reported with Firefox.

**Comment by jwilander** [comment]
Oh, I see what you mean. With our current structure for statuses it's hard to do that in the browser, but yes it is possible to do this with the desktop app where we have more control. 

I actually have a [ticket](https://mattermost.atlassian.net/browse/PLT-2241) to refactor our status code to be more performant/flexible and I'll keep this in mind when I'm doing it.

In the meantime, would you be able to submit a [feature request](https://www.mattermost.org/feature-requests/) for this to see if other community members agree with how you'd like statuses to work?

Also feel free to join us over on our daily-built [Mattermost instance](https://pre-release.mattermost.com/signup_user_complete/?id=b8230f359369ed80c46ecb8696901b3e) where the core team and community members work together and discuss many aspects of the product. Starting a discussion about this in the _UX Design_ channel will help bring this to the attention of the designers.
