### ISSUE TITLE
Possibility to edit exsisting Slash Commands

### ISSUE THREAD

**Issue by mackelito** [mattermost/platform#2809]
Right now there is only options to add new or remove old.. not to edit.
It would be a great addon!

**Comment by lfbrock** [comment]
Thanks @mackelito, definitely agree. We plan on adding the ability to edit both webhooks and slash commands - tickets to track this are here: 
https://mattermost.atlassian.net/browse/PLT-2497
https://mattermost.atlassian.net/browse/PLT-2496
