### ISSUE TITLE
Force Real Name

### ISSUE THREAD

**Issue by mackelito** [mattermost/platform#2811]
We dont want the users to use Nicknames and not the possibility to change @handler is that possible?

**Comment by lfbrock** [comment]
Hi @mackelito, to clarify - you mean add an option to disable the ability to set a Nickname, and disable the ability to change the `@username`?

It's not possible right now, but you can open a [feature request](http://www.mattermost.org/feature-requests/) on it. It would help if you could also include some background information on why you need the feature.

**Comment by mackelito** [comment]
Yes you are correct! 👍 

Found this and it seems to be a similar request.
https://mattermost.uservoice.com/forums/306457-general/suggestions/12432408-system-admin-should-be-able-to-force-displaying-of
