### ISSUE TITLE
Original Mattermost Android app crashes on Samsung Galaxy S3 on start.

### ISSUE THREAD

**Issue by demonru** [mattermost/platform#2812]
**Summary:** Original Mattermost Androidapp crashes on Samsung Galaxy S3 on start.
**Steps to reproduce:** Take Samsung Galaxy S3 GT-I9300 32Gb (Android 4.3). Install app from Google play (https://play.google.com/store/apps/details?id=com.mattermost.mattermost&hl=en). Launch application.
**Expected behavior:** Application starts
**Observed behavior:** Application crashes, popup appers to submit a crash report. 
**Possible fixes:** No idea.

**Comment by marboxvel** [comment]
I have Samsung Galaxy tab 3 and the android app doesn't even start. Whenever I open the app, all I get is a white screen. I installed both versions (2.1 & 1.14) to no avail. My android version is 4.2.2

**Comment by marboxvel** [comment]
It worked after I flashed android 4.4.2 ROM.

**Comment by it33** [comment]
Thanks @demonru, thanks @marboxvel, 

Looks like there's a bug in the Google Play store, the minimum version should be [4.4.2 per the product documentation](http://docs.mattermost.com/install/requirements.html#mobile-app-experience), but it's somehow appears as 4.2. We need to fix this. 

![image](https://cloud.githubusercontent.com/assets/177788/14905955/05e63614-0d6b-11e6-9298-3e711ae7c143.png)

**Comment by demonru** [comment]
Thanks. Now I see that it's not compatible with Android 4.3. I'll close the issue.
