### ISSUE TITLE
the license file refers to files that do not exist any more

### ISSUE THREAD

**Issue by mabuse** [mattermost/platform#2813]
Written in the LICENSE.txt we can read the following:

You are licensed to use the source code in Admin Tools and Configuration Files (api/templates/, config/, model/, web/react/utils/, web/static/, web/templates/ and all subdirectories thereof) under the Apache License v2.0.

However, these files or folders do not exist any more and the license should be updated to match the current source version.

**Comment by it33** [comment]
Updated, thanks!
