### ISSUE TITLE
How to write in Latex?

### ISSUE THREAD

**Issue by terpinter** [mattermost/platform#2857]
I tried several way to display latex, in the text, do you have any idea? Thank you :D

**Comment by lfbrock** [comment]
Hi @terpinter, you should be able to display latex by adding "latex" beside the first word in a code block. The screenshot shows how to type it in the textbox, and above shows how it looks when it's posted. It was implemented by a community member and I think it might only work properly for equations right now, but we would be open to improvements if someone else wants to work on it. 

<img width="780" alt="screenshot 2016-05-03 09 40 16" src="https://cloud.githubusercontent.com/assets/9354841/14984939/41d33784-1113-11e6-8038-227be66b189b.png">

**Comment by terpinter** [comment]
thank you, i'll look into it what can i do. Seems it uses KaTeX? Maybe I can help further...

**Comment by lfbrock** [comment]
Thanks, that would be great :)
