### ISSUE TITLE
[Firefox] Multiline messages hidden by overflow in input area

### ISSUE THREAD

**Issue by jdhoek** [mattermost/platform#2858]
In Mattermost 2.2.0 (installed as part of GitLab's 8.7.1 omnibus release) I am having a problem with entering multiline messages in Firefox. As soon as the number of lines exceeds the height of the input area, a scrollbar appears (as expected), but whenever any text is typed **anywhere** in the message, the scroll position is reset to the top, effectively hiding anything below the first six or seven lines.

This was not an issue in Mattermost 1.4.0; I do not know if the issue existed in 2.0.0 and 2.1.0.

## Reproduction

* In Firefox;
* enter more than seven lines of text in the input area, separated by linebreaks;
* type anything on a line below the seventh, see how the input area jumps to the top.

Reproducible in Firefox on Linux, Mac OS X, and Windows. Webkit-based browser do not appear to be affected.

*In this screenshot I've placed the cursor on the ninth line and typed something. The scroll position was immediately reset to the top.*

![multiline](https://cloud.githubusercontent.com/assets/683699/14982899/2675f860-113a-11e6-88fe-dffcdc672f72.png)

**Comment by lfbrock** [comment]
Hi @jdhoek, I think this has [already been fixed on master](https://mattermost.atlassian.net/browse/PLT-2190) so the fix will be in the v3.0 release May 16th.

**Comment by jdhoek** [comment]
Looks like the same issue. Sorry for the duplicate; this one was a bit hard to search for in the issue list.

**Comment by lfbrock** [comment]
No worries, thanks for bringing it up :)
