### ISSUE TITLE
Deleteing posts is now very non-user friendly

### ISSUE THREAD

**Issue by aabergaa** [mattermost/platform#2859]
If serveral posts are made by an individual user in a time frame close enough that they show up in a grouping of messages, it is impossibly difficult to get the mouse over the [...] to select delete unless you start at the last one in the grouping and work your way up. This is not usable. One used to be able to hover over individual messages in a grouping and the [...] would be direclty accessible in the highlighted line - it now shows up down a couple lines (due to the now huge arrow that opens the sidebar for commenting, and unfortunately this is the only way to get at deleteing the message )
Additionally, if the message occurs before a Date separation line, it is even harder to get to the option.

 Steps to reproduce: Every theme available by default and channel has the same issue in version 2.2.0

Expected behavior: Be able to delete individual messages with [...] next to the message rather than down several lines

**Comment by lfbrock** [comment]
Hi @aabergaa, what browser are you using, and can you provide screenshots?

**Comment by aabergaa** [comment]
I am using firefox.

I seem to be having issues uploading screenshots - it says Something went really wrong and we can't process that file.

**Comment by lfbrock** [comment]
How large a window size are you using? And is this effect limited to a certain window size, or does it happen no matter how large/small you make the window? 

If you can get a screenshot to upload, maybe by saving it as a file and uploading it as a file that would be ideal, we're having a hard time reproducing this issue.

**Comment by aabergaa** [comment]
I am trying to upload a file, and the window size doesn't matter one bit. When I try in internet exploere, the [...] shows up even lower and makes it even more difficult to click.

**Comment by lfbrock** [comment]
That's strange, here's what it looks like for me (the [...] appears beside the message on hover).

<img width="741" alt="screenshot 2016-05-03 09 59 01" src="https://cloud.githubusercontent.com/assets/9354841/14985494/af37941c-1115-11e6-8b40-4afd80bea6f0.png">

**Comment by aabergaa** [comment]
I recall that's what it was like for me until I upgraded to 2.2.0.

**Comment by aabergaa** [comment]
finally got it to upload:
![bug report -mattermost](https://cloud.githubusercontent.com/assets/12056816/14987082/2f9a6a6e-1114-11e6-95e4-9ec669a9c14c.jpg)

**Comment by lfbrock** [comment]
@aabergaa, can you go to Main Menu > About and copy the information you see there?

**Comment by aabergaa** [comment]
I assume the About Mattermost item, as there is no simple "about". Here it is:

Mattermost Team Edition
Version:
2.2.0
Build Number:
6671
Build Date:
Fri Apr 15 18:40:19 UTC 2016
Build Hash:
8e883ad2f516820942cc0131241268c1ea909ff3

**Comment by lfbrock** [comment]
And can you let us know what operating system you're on, and the version of the operating system as well as the version of firefox?

**Comment by aabergaa** [comment]
firefox 45.0.1
IE 11.0.9600.18282CO (also has same issue)
Running on Windows 7 Enterprise SP1

Also to note, I just checked inside a VM X-forward of Firefox from a minimal Centos7.2 install and it looks as it should, with [...] and the arrow a lot small right next to the message I highlight, so this is a windows OS targeted issue.

**Comment by asaadmahmoodspin** [comment]
I feel like either it's cache or something else. If possible can you inspect the reply icon and see if the svg has the width/height set.
I just tested it out on Windows 7 firefox 44 (browserstack).

![screen shot 2016-05-03 at 11 52 12 pm](https://cloud.githubusercontent.com/assets/11034289/14994600/227deb8c-118a-11e6-9e34-50a2f1a0dbcb.png)

**Comment by aabergaa** [comment]
Inspecting in firefox I had no width or height variables. I added them in the css sectoin and it looks as it should. However, do note that prior to noticing this issue I had not used IE to do any testing of it and it defaulted to the overly large sizes that made things not appear correctly. And a refresh of the firefox will not keep the manully entered variables (widht/height) from the inspect feature, so there has to be some sort of fix for this in the base code.

**Comment by aabergaa** [comment]
Oddly restarting firefox and IE seem to have fixed the issue, but I'm not sure why it would have shown as it did to begin with if I had never viewed it in IE prior to testing after discovering a problem in firefox. 
I'll close the issue.

**Comment by asaadmahmoodspin** [comment]
Glad it's resolved. 👍🏻
