### ISSUE TITLE
Unable to start and run application on ubuntu

### ISSUE THREAD

**Issue by mayurkadu9** [mattermost/platform#286]
Hello All,

I have followed all the instructions:
1.
Follow the instructions at https://docs.docker.com/installation/ubuntulinux/ or use the summary below.

sudo apt-get update
sudo apt-get install wget
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker <username>
sudo service docker start
newgrp docker

2.
Run  docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform:helium 

3.When docker is done fetching the image, open http://localhost:8065/ in your browser

and trying to access the application from my local machine using http://xx.xx.xxx.xxx:8065/ but nothing is working. hello-world image is running fine on my machine.
NOTE: xx.xx.xxx.xxx is ip of my ubuntu vritual machine.

Please let me know if i am missing anything. I just followed the simple instructions and expected it to be working 

Thank you

**Comment by it33** [comment]
Hi @mayurkadu9, I believe the subdomain setup you're using using supported in the helium release (0.5.0): http://forum.mattermost.org/t/why-wont-sub-sub-domains-e-g-www-corp-mydomain-com-not-work/13

If you just want to see how things work, perhaps try running step 2 off master, which will give you the latest dev build. v0.6.0 is shipping end of next week and the bits right now are going into stablization, so pulling the latest dev build might give you a significantly improved install experience, though it won't be as smooth as the v0.6.0 release coming out end of next week. 

Does this help?

**Comment by mayurkadu9** [comment]
@it33 Thanks. below are the content of my hosts file on ubuntu vm
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1       localhost localhost.localdomain localhost6 localhost6.localdomain6
xx.xx.xxx.xxx       xyz-aaaaaa.abc.klh.something.com       xyz-aaaaaa.
Note:xx.xx.xxx.xxx is ip mapped above in host file.

unfortunately, this did not help. When i try to access  http://xx.xx.xxx.xxx:8065 in my brower on local machine to access the application(mattermost) running on  http://xx.xx.xxx.xxx and port 8065, i get no results on webpage.

I ping xx.xx.xxx.xxx and i am getting response. Can you please suggest what i am missing in installation. Ideally, i have very fews to install and then run the image using docker. I am exactly following the instructions for ubuntu. but is not running anything on browser

Thanks

**Comment by it33** [comment]
Hi @mayurkadu9, the build your'e on is over a month old, we have RC2 of our v0.6.0 release available now: https://github.com/mattermost/platform/tree/v0.6.0-rc2

It might be faster to use the new bits, which be a different configuration (domain.com/team instead of the old team.domain.com) and I believe it'll not only solve your problem, but you'll get a bunch of new bonus features as well.

We'd love to hear your feedback and learn about any issues you might hit, particularly before we release the final bits this coming Friday.

**Comment by mayurkadu9** [comment]
Thanks i will try with this version @it33 .To install this i just need to follow below instructions like mentioned or is there any other way to pull this latest code? If any please guide how to get this latest one releasing on friday
Follow the instructions at https://docs.docker.com/installation/ubuntulinux/ or use the summary below.

sudo apt-get update
sudo apt-get install wget
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker <username>
sudo service docker start
newgrp docker
Run docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform:helium

When docker is done fetching the image, open http://localhost:8065/ in your browser

**Comment by coreyhulen** [comment]
This is fixed with 0.6.0 https://github.com/mattermost/platform/releases/tag/v0.6.0

You can now access your team via domain.com/team
