### ISSUE TITLE
Issue while running test case

### ISSUE THREAD

**Issue by usmanarif** [mattermost/platform#2874]
Hello all,

While running the test case for Post API i.e. the file **"api/post_test.go" **  using command  **"go test post_test.go"** I am getting the below error:

>  go test post_test.go
> command-line-arguments
> package command-line-arguments (test)
>  imports github.com/mattermost/platform/model
> 	imports github.com/alecthomas/log4go: cannot find package "github.com/alecthomas/log4go" in any of:
> 	/home/arif/go/src/vendor/github.com/alecthomas/log4go (vendor tree)
> 	/home/arif/go/src/github.com/alecthomas/log4go (from $GOROOT)
> 	/home/arif/go/src/github.com/mattermost/platform/src/github.com/alecthomas/log4go (from $GOPATH)
> FAIL	command-line-arguments [setup failed]

Also on running the **make test** command, I am getting below error:

> make test
> Starting docker containers
> Ldap test user test.one
> Running tests
> ../mattermost/platform/bin/godep go test  -run=. -test.v -test.timeout=240s ./api || exit 1
> godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
> === RUN   TestGetLogs
> --- FAIL: TestGetLogs (0.08s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xb code=0x1 addr=0x0 pc=0x765f1f]
> 
> goroutine 7 [running]:
> panic(0xd2b2c0, 0xc82000e120)
> 	/home/arif/go/src/runtime/panic.go:481 +0x3e6
> testing.tRunner.func1(0xc820075560)
> 	/home/arif/go/src/testing/testing.go:467 +0x192
> panic(0xd2b2c0, 0xc82000e120)
> 	/home/arif/go/src/runtime/panic.go:443 +0x4e9

I am compiling the code using "make run" and the application is running fine. Just getting the error while running the test case. 
Any suggestion is highly appreciated.

**Comment by lfbrock** [comment]
Hi @usmanarif, can you help move this to https://forum.mattermost.org/ so more people can see it?
