### ISSUE TITLE
403 Forbidden on http://docs.mattermost.com/install/upgrade-guide.html

### ISSUE THREAD

**Issue by nszceta** [mattermost/platform#2878]
http://docs.mattermost.com/install/upgrade-guide.html
403 Forbidden

Code: AccessDenied
Message: Access Denied
RequestId: 999A06FD06AC60FF
HostId: RCZqEUGvb+AH3DW8+8I0Ideg9aLqzJtdVK9utLn7BoJ2LnWmFFVN4P+wvA6KEc2T
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: AccessDenied
Message: Access Denied

**Comment by lfbrock** [comment]
Hi @nszceta, I think that link might be out of date - where did you find it? 

Updated upgrade guide is here: 
http://docs.mattermost.com/administration/upgrade.html

**Comment by nszceta** [comment]
http://www.mattermost.org/download/

Upgrade Guides

Upgrade guide for *upgrading versions*

**Comment by enahum** [comment]
@nszceta http://docs.mattermost.com is back online

**Comment by nszceta** [comment]
I'm not sure what that means because the issue persists.

**Comment by enahum** [comment]
@nszceta have you tried this [link](http://docs.mattermost.com/administration/upgrade.html)

**Comment by nszceta** [comment]
Yes, the link works. The website is still broken.

**Comment by enahum** [comment]
Thanks for reporting @nszceta will fix that shortly
