### ISSUE TITLE
Add Error Message if no SMTP Server is given

### ISSUE THREAD

**Issue by Germanunkol** [mattermost/platform#2916]
Minor issue:
If _System Console > Email Settings > SMTP Server_
is left blank, and then "Test Connection" is clicked, the system reports "No errors were reported while sending an email. Please check your inbox to make sure."

I don't believe an email can actually be sent this way, so maybe an error message would be more appropriate?

**Comment by enahum** [comment]
Thanks for your suggestion @Germanunkol we'll be looking into this as soon as we can. if you're interested can you submit a PR?

**Comment by Germanunkol** [comment]
Thanks for the quick reply!
I'm very busy atm and have no experience with Go/React. But if this is still open in a few weeks, I might be able to look into it.

**Comment by lfbrock** [comment]
Ticket is here for reference: https://mattermost.atlassian.net/browse/PLT-2976

Closing this issue + will track it in Jira
