### ISSUE TITLE
[Help Wanted] Chinese translation (zh-cn) 

### ISSUE THREAD

**Issue by ttllyy** [mattermost/platform#2920]
MM support chinese translation (zh-cn) Localization now?
Thanks!

**Comment by enahum** [comment]
Hi @ttllyy theres a translation effort for chinese.

you can join our [Localization](https://pre-release.mattermost.com/core/channels/localization) Channel and the [Chinese Localization Channel](https://pre-release.mattermost.com/core/channels/china) if you want.

in the [Localization Channel](https://pre-release.mattermost.com/core/channels/localization) header you'll find links to the translation server where you can contribute.

Thanks for your interest and help.

**Comment by jasonblais** [comment]
Simplified Chinese (zh_CN) was released [in our August release](https://docs.mattermost.com/administration/changelog.html#languages) - thank you everyone for the wonderful work!

Big thank you to @aeomin who is reviewing new and updated strings as new features are added to Mattermost over time.

If anyone else would like to help maintain the translations, please let us know on our [zh_CN community channel](https://pre-release.mattermost.com/core/channels/china) and join the [Mattermost Translation Server](http://translate.mattermost.com/zh_CN/mattermost/) to contribute.
