### ISSUE TITLE
Run make all success, but created files(in webapp dist dir) are different of download of release tar.gz?

### ISSUE THREAD

**Issue by ttllyy** [mattermost/platform#2921]
git clone source code
cd platform  and run make all success. 
In webapp dist dir:
├── 1.bundle.js
├── 1.bundle.js.map
├── bundle-dev.js
├── bundle.js.map
├── emoji
├── files
├── i18n
├── images
└── root.html

Download release 2.2,
In web dir:
├── static
│   ├── config
│   ├── css
│   ├── fonts
│   ├── help
│   ├── i18n
│   ├── images
│   └── js
└── templates
    ├── admin_console.html
    ├── authorize.html
    ├── channel.html
    ├── claim_account.html
    ├── docs.html
    ├── find_team.html
    ├── footer.html
    ├── head.html
    ├── home.html
    ├── login.html
    ├── password_reset.html
    ├── signup_team_complete.html
    ├── signup_team_confirm.html
    ├── signup_team.html
    ├── signup_user_complete.html
    └── verify.html

If I make all success, How can I create files and dirs(in webapp dist dir)  tree is same as download of release version?

**Comment by enahum** [comment]
Hi @ttllyy 

You are building from our master branch which is our active develop branch, the files from `release versions` aren't the latest ones but they are the latest stable version.

To generate the release files you should run `make build` also you can learn more about running Mattermost as a dev [here](http://docs.mattermost.com/developer/running-mattermost.html).

**Comment by ttllyy** [comment]
Hi @enahum 
I build master branch and make build and build client.  
In webapp dist dir:
├── 1.bundle.js
├── 1.bundle.js.map
├── bundle-dev.js
├── bundle.js.map
├── emoji
├── files
├── i18n
├── images
└── root.html
Many js and css file is in node_module dir.

Download release version 2.2.0:
wget https://releases.mattermost.com/2.2.0/mattermost-team-2.2.0-linux-amd64.tar.gz
In web dir, contains all dependence static files.

**Comment by enahum** [comment]
Oh @ttllyy Im sorry it took me so long to see this. does this happen to you with version 3.0.2?

**Comment by lfbrock** [comment]
Hi @ttllyy, I'm going to close this issue - if it's still happening for you on v3.0.2 please re-open or post on the [troubleshooting forums](https://forum.mattermost.org/)?
