### ISSUE TITLE
Incoming Webhooks Can't DM Users

### ISSUE THREAD

**Issue by nnewman** [mattermost/platform#2928]
According to [this](http://docs.mattermost.com/developer/webhooks-incoming.html), when using an incoming webhook, specifying the channel as `@username` will send a DM to that specified user. However, when I use this property, I receive an error with the following response body (from Python requests):

```python
{u'detailed_error': u'err=', u'status_code': 500, u'is_oauth': False, u'request_id': u'REDACTED', u'message': u"Couldn't find the channel", u'id': u'web.incoming_webhook.channel.app_error'}
```

If I specify a non-existing user, I see a different error. Based on the code, it looks like the error gets thrown [here](https://github.com/mattermost/platform/blob/2e5617c29be69637acd384e85f795a0b343bec8d/api/webhook.go#L422).

Is the documentation correct for this method of using DMs and incoming webhooks?

**Comment by nnewman** [comment]
**UPDATE** This seems to be very conditional. When I create an incoming webhook token as my user with a system admin role, I cannot use the webhook to DM myself. I can DM my 2 other test users. When I create a webhook as one of those two test users, I cannot DM anyone.

**Comment by lfbrock** [comment]
Closing this issue as duplicate, and will discuss on https://github.com/mattermost/platform/issues/3021
