### ISSUE TITLE
Remove restriction that SMTP auth requires TLS

### ISSUE THREAD

**Issue by gramakri** [mattermost/platform#2929]
mattermost does not set auth if TLS/Starttls is disabled. It was mentioned in https://github.com/mattermost/platform/issues/187 that this is a Go library limitation.

I am wondering if this is indeed the case. There was a discussion about this in https://groups.google.com/forum/#!topic/golang-nuts/VjJC2BjmU2E and it resulted in  https://github.com/golang/go/commit/ca24f9ec00c65f8e75e38ad33d1b0b3bb287e2a3.

**Comment by gramakri** [comment]
For context, on the Cloudron, we use a local mail server with auth. This doesn't work well with mattermost because of the tls restriction. In addition. mattermost also requires a valid cert (a self-signed doesn't seem to suffice).

**Comment by lfbrock** [comment]
Thanks @gramakri - Closing this issue, and we will accept the PR after the small changes are made.

**Comment by gramakri** [comment]
@lfbrock I have been tied with other things now :-( I will get to this, thanks for the feedback.
