### ISSUE TITLE
Need Api that returns user id via email address.

### ISSUE THREAD

**Issue by rosunshrestha** [mattermost/platform#2934]
With authorization token, i need a api that returns id of a user with respect to the email or username params that we send while calling api. If email isn't present , then it should return empty or null. I need this to ensure creation of user if it doesn't exist else process some step with respect to current user.

**Comment by lfbrock** [comment]
Hi @rosunshrestha, please move this to the [feature ideas forum](http://www.mattermost.org/feature-requests/)?
