### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by MichielBijl** [mattermost/platform#2946]
Is there a plan to make mattermost accessible? A colleague and I did a short test and came up with the following issues:

- Attachment button can't be reached via keyboard
- Focus indicator not clear in most cases
- Skip link doesn't work in Safari
- Text in sidebar channel list doesn't have enough contrast (3.8:1, #7A7A7A, #F0F0F0)
- Message timestamp text doesn't have enough contrast (2.8:1, #9A9A9A, #FFF)
- Search tooltip not linked to search field
- NVDA causes flickers in member list

A full test would be needed to find all issues.

**Comment by it33** [comment]
Duplicate. [Cross posted to existing discussion](https://mattermost.uservoice.com/forums/306457-general/suggestions/13036146-improve-web-accessibility).

**Comment by MichielBijl** [comment]
This is not something that should need up votes. Please consider re-opening.
