### ISSUE TITLE
Feature Request: Face palm emoji

### ISSUE THREAD

**Issue by mschilt** [mattermost/platform#2947]
Mattermost lacks a face palm emoji. 
Nowadays that emoji is used often to express the feelings of current events or circumstances. 
Official Unicode: http://unicode.org/emoji/charts/emoji-candidates.html#1f926

Here is what emoji.json could be extended to: 
, {
    "emoji": "🤦"
  , "description": "face palm"
  , "aliases": [
      "facepalm"
    ]
  , "tags": [
    ]
  }

... there should be some facepalm emoji whith an open license that could be included.

**Comment by lfbrock** [comment]
Hi @mschilt, our emoji set is based off of Apple's emoji set at the moment - so we probably won't add a face palm emoji in until it's added in there. I think it's in the list for [unicode 9.0](http://emojipedia.org/unicode-9.0/) so it will hopefully be available soon. 

We also plan on adding the ability for users to add custom emojis within the next few releases.

**Comment by it33** [comment]
Custom emoji now available, you can add any face palm you would like
