### ISSUE TITLE
Links in webhook attachment fields are not parsed correclty

### ISSUE THREAD

**Issue by thoemy** [mattermost/platform#2958]
Incoming webhooks don't parse the links in attachment fields correctly. A request with the following payload
```json
{
    "attachments": [{
        "fields": [{
            "title": "Field with link",
            "value": "<http://example.com|Link>"
        }]
    }]
}
```
is rendered as
> **Field with link**
> [<http://example.com|Link>](http://example.com%7Clink/)

instead of 
> **Field with link**
> [Link](http://example.com)

Together with autolinking this results in weird links leading to nowhere.

**Comment by jwilander** [comment]
Issue confirmed fixed. Thanks @thoemy !
