### ISSUE TITLE
More Channels Dialog Closes after first click

### ISSUE THREAD

**Issue by ginkgomzd** [mattermost/platform#2968]
To Reproduce:
 - Join a community on mattermost
 - Click on "More..." under Channels in the left-nav
 - Click any of the "Join" buttons displayed in the modal.

Symptoms: Expected behaviour is that clicking a "Join" button would give visual confirmation in-place that the channel has been joined. Indeed, the button is transformed into a progress throbber, but it never reaches a success state. Instead, modal is closed and user is turned into a point-and-click monkey, condemned to repeat the same task over and over and over.

**Comment by lfbrock** [comment]
Hi @ginkgomzd, would you be open to submitting a [feature request](http://www.mattermost.org/feature-requests/) on this? 

We discussed this and agree it would be useful for when people first join a team, but after that it seems as though the more common use case would be people joining channels one at a time. It would be useful to get more input from the community on the feature request. 

We were thinking a better solution might be to allow users to pick what channels to join when they first sign up, any thoughts on this?

**Comment by ginkgomzd** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/14094849-make-it-easier-to-join-multiple-channels

You seem to agree with me. I think the simple solution is to change this use-case. It sounds like you are arguing for a more complex solution that meets the need identified but without disrupting the single-channel-join use-case. I suggest you implement my suggestion, and when you get around to it, create a new UX for first-time joins in a separate location.

**Comment by zdam** [comment]
What is the process to try and progress a change in this area since this issue has been closed? I think perhaps a simple check to see how many channels a user belongs to when they initiate a 'join channel' user flow, if none (or whatever the default new user amount is), then alter the join channel behaviour to not close the dialog. I made a similar comment made in the related uservoice post: https://mattermost.uservoice.com/forums/306457-general/suggestions/14094849-make-it-easier-to-join-multiple-channels

**Comment by lfbrock** [comment]
Hi @zdam, just replied on the uservoice thread - would adding a step during or after the tutorial to select which channels to join be an acceptable solution for the issue for you?

**Comment by zdam** [comment]
Hi, also from uservoice thread:

Personally, I skipped the tutorial and therefore a new tutorial step wouldn't have solved this in my own circumstance - maybe others do use the tutorial?

Additionally, I would want a streamlined multi-channel selection whenever I join a new mattermost 'team', not just once.

**Comment by ginkgomzd** [comment]
Agreed, the tutorial is not the answer here. I was looking at the UI and thinking that a magnifying glass icon next to the plus-sign to add a channel would be a good place for a Quick-Add feature as a new location for the existing use-case. It could just display a text box and suggest auto-completions. Then the current feature could be changed in the way we are discussing.
