### ISSUE TITLE
displayname vs name and the URL

### ISSUE THREAD

**Issue by aabergaa** [mattermost/platform#2982]
When changing the name of a mattermost team, the team name will update on the web display interface, but the url remains the same and does not update. 

The only way I have found to change the url value is the modify teams.name in the database for that entry, which is very inconvient and I would assume the name change in the ui would be better fit to change both display and name, as the typcial user is not going to have psql knowledge and think to lookinto the database itself... 
Further, is there really and need to have both a displayname and a name?

**Comment by lfbrock** [comment]
Hi @aabergaa, we have a display name so it can be different than the url name - for example, if people want their display name in a non-latin language. 

We do want to add the option to change the team URL - there's a ticket [here](https://mattermost.atlassian.net/browse/PLT-1163) to track it. It's been sitting in the backlog for a while, so I'd recommend [opening a feature suggestion](http://www.mattermost.org/feature-requests/) on it so other people can upvote it. 

If you're interested in building this feature, I can also check and see if it's something we'd accept pull requests on.
