### ISSUE TITLE
What are the exact database privileges needed to run mattermost

### ISSUE THREAD

**Issue by TwizzyDizzy** [mattermost/platform#2998]
Hi folks,

the documentation on installing mattermost states, that on should `GRANT ALL PRIVILEGES`. Since I think this is a bit broad, I would like to know what actual privileges are needed so I can then send a pull request for the documentation in order to improve it in that regard.

Thanks in advance
Thomas

**Comment by it33** [comment]
Hi @TwizzyDizzy, 

Appreciate your thoughts, feedback and offer to help. 

Right now, the documentation recommends the Mattermost server having privileges to work with its dedicated database (just to note, this is the database only, not the database server). While there are probably granular restrictions that could be applied, those could complicate future automation for upgrading the database and therefore we don't plan on including them in official documentation. 

If community members would like to share recommendations based on their own analysis as an advanced topic, that conversation would be welcome in the [forums](https://forum.mattermost.org/).
