### ISSUE TITLE
Problems  with API requests after upgrade to 3.0

### ISSUE THREAD

**Issue by TwizzyDizzy** [mattermost/platform#2999]
Hi folks,

I just upgraded to mattermost 3.0 (from 2.2) and now there seems to be a problem in the administration interface ("system console") - clicking on any menu option doesn't do anything but yields some error like: (from browser console)

    client.js:964 GET https://my.host.name/api/v3/admin/config 500 (Internal Server Error)

This actually is expected, since there was the API upgrade from v1 to v3.

So what I want to establish is a thourough listing of 

* what API paths need the websocket upgrade
* what API paths need the reverse-proxy-ing to the websocket API locahost:8065

Here's my apache2 (2.4) configuration that worked flawlessly with APIv1 on mattermost 2.2 with the following setup:

* Mattermost is running on 127.0.0.1:8065
* Apache2 serves mattermost using reverse proxy

```
RewriteEngine On
ProxyPreserveHost On

RewriteCond %{REQUEST_URI}  ^/api/v1/websocket    [NC,OR]
RewriteCond %{HTTP:UPGRADE} ^WebSocket$           [NC,OR]
RewriteCond %{HTTP:CONNECTION} ^Upgrade$          [NC]
RewriteRule .* ws://127.0.0.1:8065%{REQUEST_URI}  [P,QSA]

RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
RewriteRule .* http://127.0.0.1:8065%{REQUEST_URI} [P,QSA]

RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-SSL on
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
Header always set X-Xss-Protection "1; mode=block"
Header always set X-Content-Type-Options "nosniff"
Header always append X-Frame-Options SAMEORIGIN

RequestHeader unset If-Modified-Since
RequestHeader unset If-None-Match

<Location /api/v1/websocket>
        Require all granted
        ProxyPassReverse ws://127.0.0.1:8065/api/vi/websocket
        ProxyPassReverseCookieDomain 127.0.0.1 my.host.name
</Location>

<Location />
        Require all granted
        ProxyPassReverse http://127.0.0.1:8065/
        ProxyPassReverseCookieDomain 127.0.0.1 my.host.name
</Location>
```

Cheers & thanks in advance
Thomas

**Comment by joshmn** [comment]
@TwizzyDizzy do you experience an issue when going to "Account Settings" > "Display" as well? I also experience the bug you reported. Just trying to tie these two together.

**Comment by joshmn** [comment]
My trace;

http://i.imgur.com/CgNc6R5.png

**Comment by joshmn** [comment]
Bam bam, pop! Try this:

1. Turn off Mattermost
2. mv config.json config.original.json 
3. curl https://raw.githubusercontent.com/mattermost/platform/v3.0.0/config/config.json > config.json
4. Replace the SqlSettings>DriverName and SqlSettings>DataSource per your config.original.json, and the ServiceSettings>ListenAddress as well if you run on a non-standard port. 
5. (do this for the other really obvious necessary changes to get it working)
6. Start up Mattermost! 
7. Good to go.

**Comment by enahum** [comment]
@joshmn so the problem seems to be with the config file?

just to know, did you follow the steps in the [upgrade guide](http://docs.mattermost.com/administration/upgrade.html)?

**Comment by TwizzyDizzy** [comment]
Hi @joshmn,

nope, sorry, I did not have a problem with the "Account Settings" > "Display" dialogue. In fact, what you're doing there - if I get that correctly - is letting mattermost create a updated default config and then replace your DB / Listen settings. Fair enough, but the upgrade guide states:

> Opening the System Console and saving a change will upgrade your config.json schema to the latest version using default values for any new settings added.

... and that's exactly what is not happening in my case.

Cheers
Thomas

**Comment by joshmn** [comment]
@enahum I did! Step for step.

**Comment by enahum** [comment]
I couldn't repro.. upgrade its working fine for me

**Comment by TwizzyDizzy** [comment]
@enahum well do you even use mattermost behind a reverse proxy? If not it is pretty obvious you wouldn't run into these issues. If you are running mattermost behind an apache reverse proxy I would be interested in your vHost configuration.

Cheers
Thomas

**Comment by enahum** [comment]
Thomas, ill try to reproduce it apache reverse proxy. Im using nginx.

**Comment by TwizzyDizzy** [comment]
Well even your nginx config might help me out on that... abstracting from that should be no big deal. But thanks so far for you involvement :)

**Comment by qraynaud** [comment]
@TwizzyDizzy : I have the same issue and I am using the official nginx reverse proxy configuration. I think this is not caused by the proxy. I looked in the log of nginx and the request is properly sent to mattermost which is the one answering 500 for me.

**Comment by TwizzyDizzy** [comment]
Could you post the exact URL that is throwing the 500 error? Thanks!

**Comment by qraynaud** [comment]
It is `https://chat.freelance.academy/api/v3/admin/config`

**Comment by TwizzyDizzy** [comment]
Alright, thanks. I just wanted to establish that we are indeed talking of at least a similar issue.

**Comment by qraynaud** [comment]
I believe we have the exact same issue.

**Comment by enahum** [comment]
Guys just to clarify you made te upgrade from 2.2 to 3.0 right?

**Comment by TwizzyDizzy** [comment]
For me, this is true. I upgraded from 2.2 to 3.0, yes.

**Comment by qraynaud** [comment]
Yes, same here.

**Comment by qraynaud** [comment]
There is nothing in logs/mattermost.log that is relevant to the error.

**Comment by enahum** [comment]
OK I have replicated the problem, we'll check it out theres a version 3.0.1 scheduled to release this week, I'll make sure to include a fix for this issue

**Comment by TwizzyDizzy** [comment]
Splendid! :) I'll wait for that release then and test it, as soon as it's out.

On a different note: I'd still like to come up with some official default reverse proxy configuration that we could add to the documentation - like we currently have it for nginx only. But one thing after the other.

**Comment by qraynaud** [comment]
@enahum: is there some workaround we can use for now to get it working because it's problematic to be locked out of the console ?

**Comment by enahum** [comment]
@qraynaud theres a PR that should fix it, in the meantime you could download a copy of the configuration file from [here](https://github.com/mattermost/platform/blob/master/config/config.json) and that should make it work

**Comment by qraynaud** [comment]
Ok, after looking at your PR and the file you mentioned, I just changed LDAPSettings Bindpassword from nul to "" and it fixed the issue.

**Comment by TwizzyDizzy** [comment]
@enahum I introduced all new config options to `config.json` and now it works.

I would like to know, what the following new config options are about, they don't seem to be included in the documentation, yet.

* `"ServiceSettings" > "WebserverMode"`
* `"TeamSettings" > "RestrictDirectMessage"`
* `"ComplianceSettings"` > no information on the whole thingee available

Cheers
Thomas

**Comment by enahum** [comment]
@TwizzyDizzy first of all I'm glad that it worked for you :), and thanks for letting us know about this issue so we could fix it.

About the settings that you're asking If im not mistaken they are:
* `"ServiceSettings" > "WebserverMode"` it's not working yet
* `"TeamSettings" > "RestrictDirectMessage"` is for letting people from the same team or people from the whole server DM one another
* ComplianceSettings are for the Enterprise Edition and with that you're be able to get compliance reports.

I hope I was able to answer your questions

**Comment by lfbrock** [comment]
Just added "RestrictDirectMessage" under http://docs.mattermost.com/administration/config-settings.html#team-settings/.

Compliance settings are documented here for reference: http://docs.mattermost.com/administration/config-settings.html#compliance-settings-enterprise

**Comment by mackelito** [comment]
Hmmm... I have found several settings missing in the config.json file... will update with the new values and see if it works...

**Comment by mackelito** [comment]
No luck... I tried the url in the browser "www.myserver.com/admin_console" and that gives me:
www.myserver.com/api/v3/admin/config
Request Method:GET
Status Code:500 Internal Server Error

**Comment by TwizzyDizzy** [comment]
@enahum & @lfbrock: Thanks for your explanation and your effort!

@mackelito do make sure you don't forget that every line needs to have a `,` in the end, except the last one in one "hash" (for example "Service Settings"). It's easy to fuck that up when adding the missing configuration options.

Cheers
Thomas

**Comment by mackelito** [comment]
@TwizzyDizzy The json format is valid and no missing "," ;) 
Will the platform even startup with broken json?

**Comment by TwizzyDizzy** [comment]
Alright, just wanted to rule out the obvious. :) Would you mind upping your config as a gist (of course with modified Salts/Keys/Credentials)?

**Comment by mackelito** [comment]
https://gist.github.com/mackelito/12449a380ef7954fed470b4b643b1b7f

**Comment by TwizzyDizzy** [comment]
Well it looks like you ran into the same error as @qraynaud in https://github.com/mattermost/platform/issues/2999#issuecomment-219449929: You should replace all occurrences of `null` as value with a `""` (two double quotes).

Cheers
Thomas

**Comment by mackelito** [comment]
Damit!... sorry for missing that one!... works like a charm now! ;) 👍

**Comment by TwizzyDizzy** [comment]
Glad we got you fixed up, too :)

**Comment by mackelito** [comment]
Hmm.. still seams to be some issues.. I still have the possibility to create new teams even thu the settings says othervise?
 
Enable Team Creation: false

**Comment by enahum** [comment]
Hi @mackelito are you a System Admin on the server?

cause you'll be able to create teams if you are a System Admin regardless if the EnableTeamCreation is set to `false`

**Comment by mackelito** [comment]
Yes I am... before the update I had to enable to feature to see it. So I guess that has changed.. well then.. guess that´s fine.. :)
