### ISSUE TITLE
Account Settings > Display fails on user_settings_display.jsx:536 after upgrade to v3

### ISSUE THREAD

**Issue by joshmn** [mattermost/platform#3001]
I have a strong feeling it might relate to #2999

**Comment by joshmn** [comment]
Nope, unrelated.

**Comment by lfbrock** [comment]
Hi @joshmn, can you add some more details about this issue? We haven't hit this problem when testing the upgrade, so wondering if you can provide some more details to help us reproduce it.

**Comment by lfbrock** [comment]
@joshmn - going to close this issue, if you're still hitting problems please re-open and add repro steps and information about your set up?
