### ISSUE TITLE
Unable to login using GitLab after upgrade to 3.0

### ISSUE THREAD

**Issue by guyguy333** [mattermost/platform#3014]
Hi,

I upgraded Mattermost 2.2 to 3.0. I got issue #2999 that I solved upgrading manually the configuration file. However, I'm no more able to login using GitLab. There are no errors in the log file and no errors in the javascript console. According to Apache log, the returned code is 500. The callback get "called" ([2016/05/16 23:13:43 CEST] [DEBG] /signup/gitlab/complete) but I have a blank page after login on GitLab on this url : "https://mattermost.greensocs.com/signup/gitlab/complete?code=[...]". I use GitLab 8.7.0.

Thank you

**Comment by it33** [comment]
Thanks @guyguy333, there was a bug in the GitLab SSO, could you try upgrading to 3.0.1 to see if it works? http://www.mattermost.org/download/

**Comment by guyguy333** [comment]
Thank you @lt33, it solves this issue after upgrading but now when I login (always using GitLab) I have this error : "An existing user is already attached to your gitlab account"

**Comment by coreyhulen** [comment]
It appears you are trying to create a user account that already exists for the given email.  Can you trying maybe resetting the password to login via email/password then from ... > Security > Switch to Gitlab SSO to re-link it to gitlab.

**Comment by pkolaric** [comment]
I had a similar problem after upgrade to 3.0.0 for some users.  You can fix it by updating the mattermost database users table changing the authservice to gitlab and linking the gitlab users.id to mattermot users.authdata for that user.  The problematic users at my site had authservice email and authdata blank (after 2.2 -> 3.0 upgrade)

**Comment by guyguy333** [comment]
@coreyhulen I can't switch to GitLab SSO, the option is not available in Security even after resetting my password to login.
@pkolaric Thanks, it solved the issue fixing manually the database.

**Comment by schemacs** [comment]
update users set authservice = 'gitlab', authdata = 'your-gitlab-id' where email = 'xxx' ;

**Comment by alerque** [comment]
I think this bug report should be re-opened, it shouldn't be necessary to hack on the database manually to gain access to logins. See also [my forum question about this issue](https://forum.mattermost.org/t/unable-to-login-via-gitlab-after-3-0-upgrade/1576).

**Comment by l3m** [comment]
@alerque I agree, this should be done via web interface.
