### ISSUE TITLE
Cannot access System Console after upgrade to version 3

### ISSUE THREAD

**Issue by olegburca** [mattermost/platform#3015]
Hi,

I have an Mattermost instance and upgraded it from version 2.1 to version 3.0.
Now I cannot access System Console, only the text "Loading ..." appears and nothing else happen.
Changed logging level to "DEBUG", but still nothing in logs.

If I check the components that the site loads - I see an error 500:
![image](https://cloud.githubusercontent.com/assets/1935169/15306302/04d20210-1bd2-11e6-903e-be8518708729.png)

Also catched an error (but I'm not sure if it is related to the problem):
{"id":"api.context.session_expired.app_error","message":"Invalid or expired session, please login again.","detailed_error":"token=5rfwhjn6bpg98rrnbrj4rxshsh Appears to bea CSRF attempt","request_id":"ons1ibtr1pfimnfut7w65rrzhw","status_code":500,"is_oauth":false}

i can access the other teams with updated login credentials.

Please advise me how this problem can be solved.
If any other details are required - I will provide them.

Thank you!

**Comment by olegburca** [comment]
Just found the same error already reported.
Please delete this ticket.

**Comment by enahum** [comment]
Hi @olegburca please review this ticket #2999
