### ISSUE TITLE
Users signing in with Gitlab don't get redirected to the team after 3.0.x upgrade

### ISSUE THREAD

**Issue by pkolaric** [mattermost/platform#3020]
#### Summary
After upgrade to 3.0.1 users who're signing in with GitLab don't get redirected to the requested team but to https://mattermost.example.com/select_team where they have to select the team.
It's probably also the reason why the 3.0.0 Android client doesn't work.

#### Steps to reproduce
- connect to your teams URL via browser https://mattermost.example.com/myteam
- click GitLab
- sign on
you'll be redirected to https://mattermost.example.com/select_team  

#### Expected behavior
user should be redirected to their team (https://mattermost.example.com/myteam)

**Comment by lfbrock** [comment]
Hi @pkolaric - do you know if this happens with email sign in as well? I think we may just need to automatically direct users to their team if they only belong to one team.

For the Android client, what about it isn't working? Can you try entering the server URL (eg https://mattermost.example.com) instead of the team URL (https://mattermost.example.com/myteam) if you haven't already?

**Comment by pkolaric** [comment]
Hi, haven't tried email sign in (all my users are authenticated via gitlab), but i do have only one team defined.

I haven't tried just bare server URL for android client (will do that and report back).
The sign on on android currently looks like that:
- the sign-on html window opens, i get redirected to gitlab, sign-on and then i'm redirected back to "select team" (all that happens in a browser) after i select the team mattermost app loads (in a browser) and i never get redirected back to the android mattermost app.

**Comment by lfbrock** [comment]
Thanks @pkolaric - Can you check what version of the Android app you have? We might have a newer one releasing soon that fixes the issue.

I filed a ticket here to track the other issue: https://mattermost.atlassian.net/browse/PLT-2977

**Comment by pkolaric** [comment]
I tested on branch-3.0 branch. I also tried with base URL instead of direct team URL and the behavior is the same.

**Comment by lfbrock** [comment]
@pkolaric, was that with the v3.0 Android app or v3.0 Mattermost? Can you try it with the app found here if you haven't already? https://github.com/mattermost/android/releases

**Comment by pkolaric** [comment]
It was with mattermost 3.0.1 (binary release) and android release 3.0 github branch (self built).

**Comment by lfbrock** [comment]
Hi @pkolaric, thanks - I think we have a fix for this now, release is here and I believe it will be released in the play store tomorrow https://github.com/mattermost/android/releases/tag/v3.0.6

**Comment by pkolaric** [comment]
Confirming it's working.
