### ISSUE TITLE
Unable to create Teams when using only GitLab authentication

### ISSUE THREAD

**Issue by simojenki** [mattermost/platform#3024]
#### Summary
I want to restrict signing up & login to only users within my GitLab install.  I have disabled sign up with email, sign in with email, and sign in with username.  When I configure mattermost like this I am unable to create new teams.  I get an error telling me that 'Team sign-up with email is disabled.', however I expected to be able to create a new Team using the GitLab credentials.

#### Steps to reproduce
mattermost 3.0.1, fresh installation

Configure the following settings (not all will be relevant, but I'm going to document for completeness):
ListenAddress: 8099
EnableIncomingWebhooks: true
EnableOutgoingWebhooks: true
EnableCommands: true
MaxUsersPerTeam: 500
EnableOpenServer: true
RestrictTeamNames: false
DriverName: postgres
DataSource: ...............
EnableSignUpWithEmail: false
EnableSignInWithEmail: false
EnableSignInWithUsername: false

GitLabSettings:
Enable: true
Secret: ...........
Id: ............
AuthEndpoint: ....
TokenEndpoint: ... 
UserApiEndpoint ....

- Go to mattermost in browser
- Login with GitLab
- Create a new team
- Enter a team name
- Accept the Team URL

At this point it fails with 'Team sign-up with email is disabled.'  

#### Expected behavior
I should still be able to create teams with the GitLab authentication enabled.

#### Observed behavior
I got an error because sign up with email is disabled.  

If I set EnableSignUpWithEmail: true, then I can create Teams even though I have authenticated using GitLab.   However this also results in the email address signup process being enable, which I would like to avoid.

**Comment by lfbrock** [comment]
Thanks @simojenki, ticket filed here on this issue: https://mattermost.atlassian.net/browse/PLT-2975

**Comment by lfbrock** [comment]
Closing issue, this is fixed in v3.0.2
