### ISSUE TITLE
Tweaking CSS some

### ISSUE THREAD

**Issue by qraynaud** [mattermost/platform#3027]
I played some with the mattermost CSS. I wanted to get a design as good as the one we have today but make it a little more efficient. My goals were:
- keep good readability
- allow for more messages in one go

Here is was I got after some trial and error:
![slack](https://cloud.githubusercontent.com/assets/65991/15327993/b335d95e-1c53-11e6-9de6-b8a244e1eac3.png)

Because I did not wanted to build mattermost myself each time to tryout those changes, I wrote a small script to patch a current bundle.js file. You can try out the result by using it:

```bash
#!/bin/bash

declare -i exit_code=0
declare FILE=$(basename "$1").patched
cp "$1" "$FILE"

GREEN="$(tput setaf 2)"
RED="$(tput setaf 1)"
RESET="$(tput sgr0)"

function patch_one() {
  declare code="$1"
  declare from="$2"
  declare to="$3"

  echo -n "Patching $code… "
  sed -i'' "/$from/{s//$to/g;h};"'$'"{x;/./{x;q0};x;q1}" "$FILE"

  if [ $? -ne 0 ]; then
    exit_code=1
    echo "${RED}FAILED!${RESET}"
  else
    echo "${GREEN}SUCCESS${RESET}"
  fi
}

patch_one global-font-size 14px 15px
patch_one message-font-size .97em 1em
patch_one message-line-height line-height:1.6em line-height:1em
patch_one message-margin-bottom margin-bottom:.5em margin-bottom:0
patch_one message-reply-button-pos __reply{top:6px __reply{top:0
patch_one message-time-font-size '0;font-size:11px' '0;font-size:12px'
patch_one message-time-pos 'auto;top:-2px' 'auto;top:-8px'
patch_one message-first-reply-pos top:30px top:19px
patch_one global-line-height 'serif;font-size:15px;line-height:1.42857143' 'serif;font-size:15px;line-height:1'

exit $exit_code
```

Just call the script on your bundle-3.0.x.js file. It wil create a bundle-3.0.x.js.patched file in your cwd. Replace the original with the patched one if everything is green. You are ready to go!

Hope you like it. If so, I'm sure making the necessary changes in the sass files won't be too hard.

**Comment by qraynaud** [comment]
The menubar is maybe a little too much spaced now, there are some small tweaks here & there to do. But it's more to start a discussion / get you feeling about this.

**Comment by asaadmahmoodspin** [comment]
Hey @qraynaud, we've already added a compact view, it will soon be up on pre-release, so I think we can look forward to that for users who would prefer a much more compact view.

Also you're welcome to provide feedback on that once you get a chance to play around with it a bit.

![screencapture-bladekick-com-adal-channels-off-topic-1463583164449](https://cloud.githubusercontent.com/assets/11034289/15363484/4edcc438-1d32-11e6-9bfd-8f6be8b12d31.png)

**Comment by qraynaud** [comment]
Yeah, I knew. I should not have used the "compact" word because it is misleading.

I meant "more efficient". In a compact view you try to make a tradeoff by decreasing the font size, lessening the readability some & making the design less present to get more info on the screen.

I did not really do that. My users were reluctant to switch to mattermost because they found that the design was not efficient enough. They talked a lot about lost space everywhere.

My version is not meaning to replace the compact view like the one you just put on a screenshot here. It is very cool and a lot of users like that kind of IRC look&feel better. The users that I'm targeting with those changes are not using the compact view on Slack either.

I even increased the font size on my version if you look at the screenshots. The message font size is 0.97em of 14px on the current design. On my screenshot font size is 15px. This increase readability and thus helps users to read faster. To make for an even faster read, I lessened line height (lots of studies showed that readability is better with a small line height) and removed the small margin between messages because I couldn't find a user that cared about knowing exactly where a specific message ends at any time. They can already find that out by getting their mouse over the messages with the :hover style.

Looking at the above compact view screenshot, I also think that you could apply some of the same ideas to it. BIgger font & less line height. You can have more messages still on screen & better readability through bigger characters.

**Comment by asaadmahmoodspin** [comment]
Thanks for the script, I'll have a look and see how it feels. Will give it a shot, we have images and markdown stuff aswell, so will probably see if it all looks good there too.

**Comment by qraynaud** [comment]
Bottom menus where too high for the new sizing. Add this line to the script to fix this:

```bash
patch_one menu-bottom-pos {bottom:25px {bottom:15px
```

You can reapply the script on an already patched file, in this case all other patch will show as failed, this is normal.

**Comment by lfbrock** [comment]
Thanks @qraynaud, closing this issue now - if you're interested in discussing Mattermost UI more feel free to join the UX channel on the Core team at https://pre-release.mattermost.com.
