### ISSUE TITLE
Android notifications are played as music not notification type

### ISSUE THREAD

**Issue by mcfedr** [mattermost/platform#3032]
#### Summary

The android app plays sounds as music type, this means that music playing in another gets paused. This is for sounds whilst the app is open, I'm not sure about GCM notifications 

#### Steps to reproduce

1. Play some music
2. Open mattermost, get a message
3. Your music just paused

#### Expected behaviour

It doesn't pause, also the notifications volume is used

#### Possible fixes

Going to need to hook into the WebView here https://github.com/mattermost/android/blob/master/app/src/main/java/com/mattermost/mattermost/WebViewActivity.java

**Comment by lfbrock** [comment]
Hi @mcfedr, thanks for reporting - would you be open to making a pull request for this issue?

**Comment by mcfedr** [comment]
I'm quite interested why it was decided not to use something like phonegap for building the native app? it would facilitate in accessing these native functions and provide a solid place to start working, rather than duplicating work

**Comment by lfbrock** [comment]
@mcfedr - We had originally worked with a third party to build the android app, but ended up having to take over from them after things didn't work out. We eventually plan to build a more native app. 

Going to close this issue and will track it in a Jira ticket: https://mattermost.atlassian.net/browse/PLT-3021
