### ISSUE TITLE
Mattermost 3.0.2: Page blank when French as Chrome first display language

### ISSUE THREAD

**Issue by lemieuxl** [mattermost/platform#3042]
#### Summary
In *mattermost* 3.0.2, when web browser (at least chrome) is set to French, the page is blank.

```
Version: 3.0.0
Build Number: 3.0.2
Build Date: Tue May 17 21:26:28 UTC 2016
Build Hash: ac509b114df1c1b4b841eded74fb797805e0162d
Build Enterprise Ready: false
```

#### Steps to reproduce
Open Chrome and go to setting and Languages. Set the first language to French, and refresh the *mattermost* page.

![screenshot from 2016-05-18 09-45-41](https://cloud.githubusercontent.com/assets/6589489/15361282/d3fe6ab2-1cde-11e6-95a5-bb5adc195a6d.png)

#### Expected behavior
The *mattermost* page should always display, even if French is set as first language.

#### Observed behavior
The *mattermost* page is blank.

![screenshot from 2016-05-18 09-46-19](https://cloud.githubusercontent.com/assets/6589489/15361351/0ca0db8e-1cdf-11e6-99d8-2616d313d56f.png)

**Comment by rtripault** [comment]
Same behavior here.
This also is not occurring on the enterprise edition (at least on https://pre-release.mattermost.com/login), if that matters.

**Comment by s7b4** [comment]
Same behavior on signup_user_complete page with a fresh install (the en locale is ok, not the fr)

`Current version is 3.0.0 (3.0.2/Tue May 17 21:26:28 UTC 2016/ac509b114df1c1b4b841eded74fb797805e0162d)`

Regards,

**Comment by mijime** [comment]
I am also the same problem in the Japanese has occurred.

I think because the content type is different.

static/i18n/*.json responsed `Content-Type:text/plain; charset=utf-8`.
But superagent is parsed */json only.

Why https://pre-release.mattermost.com is respond application/json ?

Reading the code, it looks like doing anything special.

https://github.com/mattermost/platform/blob/2e5617c29be69637acd384e85f795a0b343bec8d/web/web.go#L28
https://golang.org/src/net/http/fs.go#L147
https://golang.org/src/mime/type.go#L35

**Comment by komanezumi** [comment]
I'm also the same (or similar) the same issue in Japanese environment.
I got the following error:

[2016/05/19 15:02:05 JST] [EROR] /api/v1/admin/log_client:client code=0 rid=xxxxx uid=xxxxx ip=xxx.xxx.xxx.xxx msg: Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch. row: 7 col: 25589 stack: Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch. url: https://xx.xxxxxxx.co.jp/static/js/libs-ent-7.min.js [details: ]

**Comment by enahum** [comment]
Hi guys,

Thanks for pointing out this bug.

I'm working on a fix for this issue and for https://github.com/mattermost/platform/issues/3057 that are related.

**Comment by enahum** [comment]
Hi guys,

Doing a little bit of research we think it may be related to Encoding.

Can you please check that your Chrome is using UTF-8 like in the attached screenshot

![screen shot 2016-05-19 at 13 17 34](https://cloud.githubusercontent.com/assets/6757047/15402991/3339b092-1dcd-11e6-84e5-d30e176c8cad.png)

Also if you can please send us a screenshot of your javascript console when you hit the problem, that might be very helpfull too.

Thanks.

**Comment by s7b4** [comment]
Hi,
The problem appears in firefox too. Encoding is set to Unicode, there is no javacript errors.

fr, fr-fr locale : 
![fr-locale](https://cloud.githubusercontent.com/assets/5158891/15403814/fdfd84de-1dfa-11e6-9cb3-bbb333f648ea.png)

en, en-us :
![en-locale](https://cloud.githubusercontent.com/assets/5158891/15403853/323dd6ae-1dfb-11e6-9ecb-d85561ca4381.png)

Hope this helps.

**Comment by enahum** [comment]
Hi @s7b4 can you please attach the response for the `fr.json` request?

Thanks.

**Comment by s7b4** [comment]
Here is the file.
[fr.json.zip](https://github.com/mattermost/platform/files/273165/fr.json.zip)
Regards.

**Comment by lemieuxl** [comment]
Encoding is also set to Unicode, and there are no errors in the console.

![screenshot from 2016-05-19 14-26-20](https://cloud.githubusercontent.com/assets/6589489/15405046/45a06630-1dce-11e6-8f3f-8c061b5ffbce.png)

The problem also appears in mobile browsers (tested on Android with Chrome, and iOS with Chrome and Safari).

**Comment by enahum** [comment]
Hey guys,

could you please [try this build on linux](https://releases.mattermost.com/mattermost-platform/PLT-3030/mattermost-team-linux-amd64.tar.gz) to see if that fixes the problem for you? 

Much appreciate it.

Thanks

**Comment by mijime** [comment]
Thanks, enahum.

I tried it, but it does not seem to have been changed.
It is a guess, lemieuxl and s7b4 will also be the same way.

komanezumi might is improved.

my mattermost logs.
```
[00:11:57 UTC 2016/05/25] [INFO] (github.com/mattermost/platform/utils.GetTranslationsBySystemLocale:56) Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
[2016/05/25 00:11:57 UTC] [INFO] Current version is 3.0.0 (1/Tue May 24 22:18:52 UTC 2016/b2f1c96bf38eb05533b5b9aa9c98840222332b0c)
[2016/05/25 00:11:57 UTC] [INFO] Enterprise Enabled: false
[2016/05/25 00:11:57 UTC] [INFO] Current working directory is /opt/mattermost
[2016/05/25 00:11:57 UTC] [INFO] Loaded config file from /opt/mattermost/config/config.json
[2016/05/25 00:11:57 UTC] [INFO] Server is initializing...
[2016/05/25 00:11:57 UTC] [INFO] Pinging sql master database
[2016/05/25 00:11:57 UTC] [INFO] Pinging sql replica-0 database
[2016/05/25 00:11:57 UTC] [DEBG] Deleting any unused pre-release features
[2016/05/25 00:11:57 UTC] [DEBG] Initializing user api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing team api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing channel api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing post api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing web socket api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing file api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing command api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing admin api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing oauth api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing webhook api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing preference api routes
[2016/05/25 00:11:57 UTC] [DEBG] Initializing license api routes
[2016/05/25 00:11:57 UTC] [DEBG] Parsing server templates at /opt/mattermost/templates/
[2016/05/25 00:11:57 UTC] [DEBG] Initializing web routes
[2016/05/25 00:11:57 UTC] [DEBG] Using client directory at /opt/mattermost/webapp/dist/
[2016/05/25 00:11:57 UTC] [INFO] Starting Server...
[2016/05/25 00:11:57 UTC] [INFO] Server is listening on :8065
[2016/05/25 00:11:57 UTC] [INFO] RateLimiter is enabled
[2016/05/25 00:12:03 UTC] [DEBG] /signup_user_complete
[2016/05/25 00:12:04 UTC] [DEBG] /api/v3/users/initial_load
```
failed-ja
![failed-ja](https://cloud.githubusercontent.com/assets/4719974/15524263/d876771a-225b-11e6-8b8d-f9751de703b5.png)

success-en
![success-en](https://cloud.githubusercontent.com/assets/4719974/15524264/d878e4f0-225b-11e6-92e6-750fbbd5611d.png)

use-nginx-to-direct-static
![use-nginx-to-direct-static](https://cloud.githubusercontent.com/assets/4719974/15524265/d87a984a-225b-11e6-88b6-b7ecb38c1bb9.png)

**Comment by enahum** [comment]
Can you please share your deployment configuration so i can try to repro
the issue?

Does it get fixed using the nginx to direct static?

Thx mijime.

**Comment by mijime** [comment]
Sorry ... I was rewriting my post. Update the image, it has been added to my dockerfile.

**Comment by enahum** [comment]
would you be so kind to copy your nginx config?

**Comment by mijime** [comment]
oops, sorry...

nginx/conf.d/default.conf
``` nginx 
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;

server {
  server_name _;
  listen 80 ;
  access_log /var/log/nginx/access.log vhost;

  location / {
    proxy_pass http://mattermost:8065;
  }

  location /static {
    alias /opt/mattermost/webapp/dist;
  }
}
```

**Comment by lemieuxl** [comment]
I see the same behaviour with the build provided by @enahum. I installed it on a fresh CentOS 7 virtual machine (following the official documentation [Production Install on RHEL 7.1+](http://docs.mattermost.com/install/prod-rhel-7.html)), and browsed directly to mattermost (skipping nginx entirely).

![screenshot from 2016-05-25 08-45-22](https://cloud.githubusercontent.com/assets/6589489/15540413/38d9e544-2255-11e6-97dd-7793c5358135.png)

**Comment by enahum** [comment]
Ok I can work with this, lets hope I'll find a fix soon

**Comment by mijime** [comment]
:+1:

If my fixes also accustomed to reference, I am happy.
https://github.com/mijime/platform/commit/66a99728e95afd89af38b4fff0d296de3b66bfd3

**Comment by s7b4** [comment]
Hi, same problem here.
The only difference i see is that nginx is sending "Content-Type: application/json" in response header.
Regards.

**Comment by enahum** [comment]
can you try again using the same build?

**Comment by lemieuxl** [comment]
It looks like it works now (with French settings, at least).
Thanks!

![screenshot from 2016-05-25 10-16-57](https://cloud.githubusercontent.com/assets/6589489/15543178/e639db2a-2261-11e6-8620-718db717dae8.png)

**Comment by enahum** [comment]
awesome, @mijime can you also confirm?

**Comment by s7b4** [comment]
It's ok for me too (French locale).
Thanks.

![ok-fr](https://cloud.githubusercontent.com/assets/5158891/15543346/cbb39fec-2294-11e6-8f3e-3f5725a53cac.png)

**Comment by mijime** [comment]
Cool !! It works for me too. (ja)
Thanks enahum. 👍

**Comment by enahum** [comment]
Great!!

Thanks guys for helping me by testing this.

I'm going to close this issue then.

Cheers
