### ISSUE TITLE
Mattermost 3.0.2 - Android application unable to login using Gitlab

### ISSUE THREAD

**Issue by rtripault** [mattermost/platform#3044]
#### Summary

(Mattermost 3.0.2 Team Edition)

On Android 6 (Cyanogenmod 13), when trying to login using Gitlab, the default browser is opened instead of trying to login "inside the application".

#### Steps to reproduce

* launch the android application
* fill your Mattermost server URL
* try to login using Gitlab
* notice your browser get launched

#### Expected behavior

Gitlab login form is displayed within the application, allowing you to log in

**Comment by lfbrock** [comment]
Hi @rtripault, can you check what version of the Android app you're on? 

We recently released a new version that I think this might be fixed on, you can find it here: https://github.com/mattermost/android/releases

**Comment by rtripault** [comment]
Oh, sorry for not providing that information, i assumed Mattermost v3 needed the newest Android application... so i'm indeed using mattermost-304.apk

**Comment by it33** [comment]
@rtripault could we ask your help to connect your Android app to a 3.0.2 test server with GitLab SSO (https://gitlab.mattermost.com/) to help narrow down the possible issue?

**Comment by rtripault** [comment]
Sure thing

**Comment by it33** [comment]
Thanks @rtripault please let us know if the test server works? If it did, it might be an issue with how either your Mattermost or your GitLab server is set up. If it doesn't work, it could be an issue with the app?

**Comment by rtripault** [comment]
Well, experiencing the same behavior (Android browser being opened).

Happy to provide additional information/tests if needed, just let me know.

**Comment by coreyhulen** [comment]
Hi @rtripault,

I think we identified and fixed the issue.  Could you try with https://github.com/mattermost/android/releases/download/v3.0.6/mattermost-android-3.0.6.apk  on gitlab.mattermost.com to see if the issue is solved.

**Comment by rtripault** [comment]
Hi @coreyhulen, confirming it is now working as expected.

So closing the issue.
Many thanks
