### ISSUE TITLE
link to information on update in log file not found

### ISSUE THREAD

**Issue by rompic** [mattermost/platform#3051]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
the url http://www.mattermost.org/upgrade-to-3-0/ is not available

#### Steps to reproduce
update to 3.0
start without running command line tool platform -upgrade_db_30
open mattermost log

#### Expected behavior
link should be available online

#### Observed behavior
Please see 'http://www.mattermost.org/upgrade-to-3-0/' for more information on how to upgrade.

#### Possible fixes
change link to http://www.mattermost.org/upgrading-to-mattermost-3-0/
If you can, link to the line of code that might be responsible for the problem

**Comment by rompic** [comment]
added to https://github.com/mattermost/platform/pull/3052

**Comment by asaadmahmoodspin** [comment]
I've added a redirect. Now http://www.mattermost.org/upgrading-to-mattermost-3-0/ takes you to http://www.mattermost.org/upgrade-to-3-0/
