### ISSUE TITLE
Mattermost 3.02 web client language always Spanish

### ISSUE THREAD

**Issue by rodobodolfo** [mattermost/platform#3057]
### Summary
Mattermost 3.02 web client seems to default to OS/Browser language.

### Steps to Reproduce
The browser/OS is in spanish. If I check the language of the profile it is set as english. If I reset it to english language it changes the language.
On a new session the language would be spanish again.

### Expected behavior
It should stay as last language set up.

![image](https://cloud.githubusercontent.com/assets/12578313/15400053/73e40d84-1dc0-11e6-96a8-ebf2ab34e1ae.png)

Thanks!

**Comment by enahum** [comment]
Hi @rodobodolfo thanks for submitting this issue, I'm actually evaluating whats causing this and another issue related to this and have it fix as soon as possible.

**Comment by enahum** [comment]
There's a PR #3076 to fix this
