### ISSUE TITLE
Cannot connect from Android nor iOS

### ISSUE THREAD

**Issue by raspbeguy** [mattermost/platform#3060]
#### Summary
It is impossible to connect to Mattermost from Android app nor iOS app.

#### Steps to reproduce
In the URL form on the first screen of the mobile app, enter the full URL of the Mattermost instance.
Did try with and without the team name in the URL.
Version of Mattermost instance : 3.0.2, zipped release version, downloaded this morning (2016-05-19)
Version of mobile client : newest available on Google Play and Apple App Store.

#### Expected behavior
Being able to connect to my instance.

#### Observed behavior
The message "The address does not appear to be a Mattermost server" occurs. Did checked the logs, the error corresponds to this entry:

    [2016/05/19 19:45:07 CEST] [EROR] /api/v1/teams/find_team_by_name: code=404

#### Possible fixes
Maybe the API v1 support has been dropped and the mobile clients weren't updated?

**Comment by lfbrock** [comment]
Thanks @raspbeguy - We should have announced this better, I think the new apps aren't releasing until tomorrow. 

Android one can be found here in the meantime: https://github.com/mattermost/android/releases/tag/v3.0.6

**Comment by raspbeguy** [comment]
Ok, thanks. Sorry if is was written somewhere, I just didn't get the info.

**Comment by lfbrock** [comment]
No worries - I think it was buried in the blog post announce/changelog, we should have put it at the top and maybe on the releases page.
