### ISSUE TITLE
Email at Login case sensitive

### ISSUE THREAD

**Issue by rompic** [mattermost/platform#3062]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Login with roman@example.com works, Roman@example.com does not.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Try to Login. I noticed this on my Android Phone which changed the first letter of my email to upper case

#### Expected behavior
Email case insensitive

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
See above

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by lfbrock** [comment]
Hi @rompic - I made a ticket to turn off the autocapitalization on mobile as a fix for this: https://mattermost.atlassian.net/browse/PLT-3002. 

I think the local mailbox part of the email address can technically be case sensitive (although most email services make it case insensitive).

**Comment by rompic** [comment]
thanks for the update. learned something today (also see http://stackoverflow.com/a/9808332 which points to RFC 5321, section-2.3.11)

**Comment by arnauldvm** [comment]
@lfbrock Shouldnt the system handle the email address given in the login screen in a case-insensitive manner? (Independently from the device used.)
