### ISSUE TITLE
Links to attachments are linked to the wrong Team after upgrade & remove Team

### ISSUE THREAD

**Issue by tistjendop** [mattermost/platform#3063]
#### Summary
Attachment links are incorrect after upgrade to MM 3.0.1, change of primary team and removal of other team. 

#### Steps to reproduce
Starting from Mattermost 2.2.0 with 2 teams (A and B) on Ubuntu 14.04
1. upgrade Mattermost to 3.0.2
2. upgrade to Ubuntu 16.04 (do not forget to create systemd unit file)
3. Choose Team B as primary team
4. Remove Team A

#### Expected behavior
Attached images in posts remain intact, even after upgrade of mattermost, change of primary team and removal of another team.

#### Observed behavior
Links to attached images (in the only remaining team, B) show the hash of (removed) team A in stead of the hash of team B.
So the attachments are unreachable. The attachments still exist in the data folder.
The hashes are the folder names as observed in /opt/mattermost/data/teams in the original MM 2.2.0 installation.

#### Possible fixes
no idea

**Comment by lfbrock** [comment]
Hi @tistjendop - I think this is an issue with removing teams, can you try deleting the folder /data/teams/xxxxxxxxxxxxx where xxxxxxxxxxxxx is the team ID of the team you deleted?

**Comment by tistjendop** [comment]
I seem to have forgotten to copy the data folder after all.
Consider this a bogus bug report please. My excuses.
