### ISSUE TITLE
webhook_icon.jpg is missing in team tar file for version 3.0.2

### ISSUE THREAD

**Issue by woutervb** [mattermost/platform#3064]
#### Summary
Icon is missing in distibution

#### Steps to reproduce
Watching old messages produced by a webhook will display missing icon. Developertools in de webbrowser wil confirm with a 404

#### Expected behavior
icon is included

#### Possible fixes
Include the icon the distribution at the static location

**Comment by lfbrock** [comment]
Thansk @woutervb, we have a ticket here tracking the issue https://mattermost.atlassian.net/browse/PLT-2939
