### ISSUE TITLE
Editing code for mattermost

### ISSUE THREAD

**Issue by mayurkadu9** [mattermost/platform#308]
Hello,

I am new to mattermost , but i am really liking it. I want to make some code changes in configurations to enable s3 bucket for file sharing. 

Can you please you provide me some detailes instructions as to how to edit the files. I am not understanding how to edit the files on the fly here using docker and mattermost/platform:helium image maybe

NOTE: I am running docker on my windows7 machine.
Here is what i am following : 

1.docker run -d --name=mattermost-tmp mattermost/platform:helium
2.docker cp mattermost-tmp:/go/src/github.com/mattermost/platform/config/config_docker.json .
3.docker rm -f mattermost-tmp
4..... edit config file in host  using vim config_docker.json
5. Put necessary aws s3 details and save file
6.docker run --name mattermost-dev -d --publish 8065:80 -v $(pwd)/config_docker.json:/go/src/github.com/mattermost/platform/config/config_docker.json mattermost/platform:helium

but now i am getting below error after step 6
invalid value "c:\\Users\\t_kadum\\config_docker.json;C:\\Program Files (x86)\\G
it\\go\\src\\github.com\\mattermost\\platform\\config\\config_docker.json" for f
lag -v: \Users\t_kadum\config_docker.json;C:\Program Files (x86)\Git\go\src\gith
ub.com\mattermost\platform\config\config_docker.json is not an absolute path
See 'c:\Program Files\Boot2Docker for Windows\docker.exe run --help'.

Please suggest how to resolve this .

Thanks

**Comment by coreyhulen** [comment]
It appears it cannot find the config_docker.json file.  Can you confirm that mattermost works via a plain vanilla install before editing the config.

It also looks like the path to the config file tries to point to 2 different files, one in t_kadum and another in program files.  It should only point to 1 inside the container.  You should be editing the config file in the container and should not need to modify the -v flag.

**Comment by mayurkadu9** [comment]
Thanks @coreyhulen  For reply. I would like to know how to edit the config file in container.It would be really great if i could get sample instructions as i am running it on my windows7.

Also while editing do i need to keep applicattion running or i can just edit the config file on the fly when it is already running. I want to edit config file and put my aws s3 parameters to enable file upload or sharing in mattermost/

Thanks in advance

**Comment by coreyhulen** [comment]
Here's a snippet of some documentation steps we are working on.  The steps below do not address your specific issue, but it outlines how to edit the config.json file in the docker container.

1. If you're running Mattermost on Amazon Beanstalk you can shell into the instance with the following commands
2. `ssh ec2-user@[domain for the docker instance]`
3. `sudo gpasswd -a ec2-user docker`
4. Retrieve the name of the container with `sudo docker ps`
5. `sudo docker exec -ti container_name /bin/bash`
6. Edit the config file `vi /config_docker.json` with the settings you captured from the step above. 

7. Restart Mattermost
8. Find the process id with `ps -A` and look for the process named `platform`
9. Kill the process `kill pid`
10. The service should restart automatically. Verify the Mattermost service is running with `ps -A`
11. Current logged in users will not be affected, but upon logging out or session expiration users will be required to verify their email address.

**Comment by mayurkadu9** [comment]
thanks . This is working now
