### ISSUE TITLE
Regression: Android - @mention window displaying contacts on the same line

### ISSUE THREAD

**Issue by irfaneitw** [mattermost/platform#3084]
#### Summary
@mention window is broken

#### Steps to reproduce

For Android:
1. Open v3.0.6
2. In any room type "@"
3. Notice the window

On a desktop:

1. Open the Mattermost web app (3.0.2)
2. Resize the window to simulate a smartphone screen size
3. In any room, type "@"
4. Notice the window

#### Observed behavior

- I'm seeing multiple contacts on the same line
- If I choose one contact it selects the contact beside it

<img width="422" alt="__pablo_-_it_werks_inc__it_werks_inc__and_franz" src="https://cloud.githubusercontent.com/assets/19347435/15473240/13ba43be-20cd-11e6-8b88-b65ff8573d8a.png">

#### Expected behavior
- Each contact should be on a separate line

**Comment by lindy65** [comment]
Thanks for the report @irfaneitw, a [ticket](https://mattermost.atlassian.net/browse/PLT-3018) has been opened to fix the issue.
