### ISSUE TITLE
Regression: iOS - Blank screen on load

### ISSUE THREAD

**Issue by irfaneitw** [mattermost/platform#3085]
#### Summary
When you open the iOS app you'll see a blank screen. Only happens on the iOS app

#### Steps to reproduce

1. Log into the iOS v3.0 app which is connected to a v3.0.2 server
2. Close the app
3. Open the app

#### Observed behavior

- You'll see the room contents show but then disappear (so now a white screen)
- Tap on the screen and the room contents will now show

#### Expected behavior

- When I open the app I should see all the contents of the room

**Comment by lfbrock** [comment]
Thanks @irfaneitw, made a ticket here tracking the [issue](https://mattermost.atlassian.net/browse/PLT-3017). If you're interested in submitting a fix for it, let us know and we can make it accepting pull requests.
