### ISSUE TITLE
message replies are rendered without the "Commented on user's message: ..." citation

### ISSUE THREAD

**Issue by fjarlq** [mattermost/platform#3087]
#### Summary
Sometimes, message replies are rendered without the "Commented on user's message: ..." citation that describes the parent post of the reply.

#### Steps to reproduce
1. Have two users log into Mattermost 3.0.2 using any up-to-date client.
2. Have one user reply to several old posts while the other user monitors the channel.
3. Wait for one of the replies to be rendered incompletely. The problem doesn't reproduce every time. It seems to happen more often when replying to older posts. On https://pre-release.mattermost.com/ in the justtesting channel, I searched for the keyword "test" to find some old posts, and the problem reproduced on the third try. (pre-release.mattermost.com was running Mattermost 3.0.2 at the time.)
4. Notice that upon reloading the page, the rendering is always done correctly.

#### Expected behavior
I expect every message reply to be rendered with the "Commented on user's message: ..." citation. Otherwise users will not understand the context of reply posts.

#### Observed behavior
Sometimes, message replies lack the expected context description. For example, the "testguy" reply in this screenshot of the iOS Mattermost 3.0 app:
![reply bug screenshot](https://cloud.githubusercontent.com/assets/441483/15491989/910b36a0-2133-11e6-8676-af5547529090.png)

#### Possible fixes
I used Chrome's Inspect feature to look at a reply post that lacked context. For that post, there was no `<div className='post__link'> ...` section like there should be.

It is as if `parentPost` was false when this line in `post_body.jsx` was executed, such that `comment` remained set to the empty string:
https://github.com/mattermost/platform/blob/ac509b114df1c1b4b841eded74fb797805e0162d/webapp/components/post_body.jsx#L46

**Comment by asaadmahmoodspin** [comment]
That should certainly be a bug, I'll file a bug if I'm able to reproduce it.

**Comment by asaadmahmoodspin** [comment]
I was able to reproduce this, we'll add it as a bug and prioritise it accordingly.

**Comment by lfbrock** [comment]
Ticker is here for reference: https://mattermost.atlassian.net/browse/PLT-3176

If anyone from the community figures out concrete repro steps, or is interested in working on a fix for this, please post here

**Comment by fjarlq** [comment]
@lfbrock I can view PLT-3175 but not PLT-3176.. it says it may have been deleted or I don't have permission to view. So, I'll add my observation here on github... maybe that's what you meant anyway by "please post here".

I've been trying to puzzle out how this bug sometimes occurs when rendering the reply-post initially, but always goes away after reloading the page. I've made some progress, but I'm stuck on questions about how it is supposed to function....

When my Mattermost web client is looking at a channel and I reload the page, I notice the client makes this sort of request:

`GET /api/v3/teams/[team_id]/channels/[channel_id]/posts/page/0/60`

and the response to that request includes certain posts which are parents of other posts. I think it's returning posts which are parents of any of the requested 60 posts from offset 0. Looks like that's being done in `sql_post_store.go` by the `GetPosts` method when it calls `getParentsPosts` here:

https://github.com/mattermost/platform/blob/release-3.0/store/sql_post_store.go#L337

So that explains how the parents of old posts are being delivered to the client upon reload. But when clients are monitoring a channel and someone replies to an old post that those clients have not already loaded, how does the parent post get delivered to all the active sessions so that it can be cited when rendering the new reply?

When creating the new reply, I see (via packet trace) the server receives this sort of request:

`POST /api/v3/teams/[team_id]/channels/[channel_id]/posts/create`

And in the body of the request it correctly specifies the `parent_id` of the new post. Then in the packet trace I immediately see an `"action": "posted"` event get sent out to all the active sessions, and it contains the new reply-post along with the correct `parent_id`, but the contents of that parent are not included.

I've looked through the code that handles the `/posts/create` request, and as far as I can tell after some digging, there is not any code to return the parent post content. So it seems the "Commented on users's message: ..." citation only works correctly when the client incidentally already has the parent post's content. Or, is the client supposed to go out of its way to request `parent_id` content when it encounters an unloaded post?

**Comment by lfbrock** [comment]
Thanks @fjarlq that's helpful, I think we've got better repro steps now. I also fixed the ticket so it's visible
