### ISSUE TITLE
input lag in web client after loading many posts

### ISSUE THREAD

**Issue by fjarlq** [mattermost/platform#3088]
#### Summary
Typing becomes significantly laggy as more messages are loaded -- especially when hitting enter to send a new post.

#### Steps to reproduce
1. log into Mattermost 3.0.2 using Chrome 50 on a mid-2014 MacBook Pro
2. open the Chrome Task Manager, sort by CPU, and select the Mattermost webapp tab
3. join a channel that contains many messages
4. set the keyboard focus to the "Write a message..." input box
5. observe ~40% CPU usage of the webapp tab when holding down the `-` key on the keyboard
6. observe no lag when hitting enter to post a new message
7. repeat this 10 times: scroll up and click "Load more messages"
8. observe ~100% CPU usage of the webapp tab when holding down the `-` key as before
9. observe noticeable lag (~1 second) when hitting enter to post a new message
10. observe that as you repeat further, the lag gets worse

#### Expected behavior
Keyboard input should remain responsive regardless of how many posts are loaded.

#### Observed behavior
Significant input lag proportional to the number of posts loaded. A friend of mine using Chrome on Windows 10 on a Core i7 observed the same laggy behavior.

#### Possible fixes
Using Chrome's Inspect tool, I collected a JavaScript CPU Profile while holding down the `-` key after having loaded 20 pages of messages. The largest user by far, in the Self time column, was the function `d.value` found at `TextareaAutosize.js:193`. Its parent, labelled function `a`, is at `calculateNodeHeight.js:22`.

I'm not sure how Mattermost is loading that code... I didn't immediately find it in the platform project. But I browsed the source code in Chrome and `TextareaAutosize.js:193` appears to correspond with the `_resizeComponent` function here:
https://github.com/andreypopp/react-textarea-autosize/blob/af9124ade58e85bf415a5b6d41848009f1975ac8/src/TextareaAutosize.js#L143

While `calculateNodeHeight.js:22` corresponds with the `calculateNodeHeight` function here:
https://github.com/andreypopp/react-textarea-autosize/blob/af9124ade58e85bf415a5b6d41848009f1975ac8/src/calculateNodeHeight.js#L38

**Comment by jwilander** [comment]
Hi @fjarlq,

Great write-up, thanks for this!

We've recently started to focus more on webapp performance and this should be of some good help to us. I've made a Jira ticket [here](https://mattermost.atlassian.net/browse/PLT-3067) for investigating this more deeply and to find a solution that let's us retain any functionality we need as well as increase performance of the app.

Please follow the Jira ticket if you'd like to stay up-to-date on the status of the issue.
