### ISSUE TITLE
Integration with password vaults doesn't work when the vault lets you select a username+password first

### ISSUE THREAD

**Issue by jovandeginste** [mattermost/platform#3089]
#### Summary
When logging in via the web UI, the form does not work nicely with autofill tools like Chrome's password vault (when you have more than one username/password for the domain) or 3rd party plugins like the one for Keepass (same as Chrome, or when you don't let it automatically fill on page load).

In both cases, you need to select a username (+password) from a list. While the form is then filled in, the "Sign in"-button remains unclickable until you "manually" change one or the other field. (However, when doing so, sometimes the other field is reset to blank.)

#### Steps to reproduce
Save your Mattermost credentials in Chome when logging in. Log out. Try to log back in using Chrome's password manager.

#### Expected behavior
I should be able click to "Sign in" when the username and password are filled in.

#### Observed behavior
The "Sign in" button remains unclickable after selecting a username and password from the list.

#### Possible fixes
Let the "Sign in"-button check valid input via JavaScript when clicked, or change the way it listens the input fields (but this I know nothing about)

**Comment by lfbrock** [comment]
Thanks @jovandeginste, would you be interested in contributing a fix for this?

**Comment by lfbrock** [comment]
Created a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-3020

**Comment by jovandeginste** [comment]
Sorry for late answer; I would not mind contributing, however I'm not really a frontend developer so I would more likely make it worse ...

**Comment by lfbrock** [comment]
No worries, we'll get someone to fix it. Thanks for the report!
