### ISSUE TITLE
window.setup_root' is undefined

### ISSUE THREAD

**Issue by lswen** [mattermost/platform#3094]
3.0.2 open page

global code — whochat.yunfancdn.com:1:2248TypeError: window.setup_root is not a function. (In 'window.setup_root()', 'window.setup_root' is undefined)

**Comment by jwilander** [comment]
Hi @lswen,

Are you running in a production environment? If so, can you give me any information about the machine running your server?

Can you try deleting your browser cache and trying again? If that doesn't work try restarting the Mattermost service on your server to see if that fixes the issue.

**Comment by lfbrock** [comment]
Hi @lswen, going to close this issue - if you're still having trouble, please re-open or post on https://forum.mattermost.org/ for troubleshooting help?
