### ISSUE TITLE
Cannot hide "Terms" link in the top page

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#3103]
#### Summary

"Terms" link in the top page is not hidden even if I tried to leave  "Terms of Service Link" blank in System Console.

#### Steps to reproduce

1. Go System Console > Legal and Support Settings
2. Leave "Terms of Service Link" blank
3. Click Save button

#### Expected behavior

In the top page "Terms" link is hidden.

#### Observed behavior

In the top page "Terms" link is not hidden and the "Terms of Service Link" input box is not empty.

**Comment by lfbrock** [comment]
Thanks @npcode, made a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-3037

It's also accepting pull requests if anyone from the community is interested in submitting a fix.
