### ISSUE TITLE
Edit dialog does not directly take focus

### ISSUE THREAD

**Issue by kumpelblase2** [mattermost/platform#3105]
#### Summary
Input in edit dialog does not directly take focus when using shortcut (Up-Arrow).

#### Steps to reproduce
1. Post a message in a channel/private group/direct messages
2. Press up arrow to bring up the edit modal
3. Directly type `test`, minimal/no delay between this and the previous step

Version 2.2.0 Build 6671 (GitLab Mattermost via GitLab Omnibus)

#### Expected behavior
`test` being appended to the currently edited message.

#### Observed behavior
`test` ends up in the input for a new message.

#### Possible fixes
https://github.com/mattermost/platform/blob/master/webapp/components/edit_post_modal.jsx#L134 This should probably be called on `show.bs.modal`.

**Comment by lfbrock** [comment]
Thanks @kumpelblase2, made a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-3041

If anyone in the community is interested in making a pull request to address this issue we would welcome the contribution!
