### ISSUE TITLE
Web - Single comment "shows up twice"

### ISSUE THREAD

**Issue by irfaneitw** [mattermost/platform#3114]
#### Summary
Sometimes when I type a comment, I'll see it twice even though I sent it once, but the second instance looks like it's trying to be sent.

#### Steps to reproduce
Hard to reproduce but here's how I got it today:

1. With Mattermost open in your browser, put your computer to sleep for a couple mins
2. Wake up your computer and go back to tab with Mattermost
3. Go to different channels to see any updates (MM has connected and is displaying new channel updates)
4. Type a comment

#### Observed behavior
You see your comment twice, once in a sending mode and once in a sent mode

<img width="1119" alt="pablo_-_it_werks_inc__it_werks_inc_" src="https://cloud.githubusercontent.com/assets/19347435/15552872/7b7aa05c-228a-11e6-9857-d8f6c118c087.png">

#### Expected behavior
You should see your comment once and sent

**Comment by irfaneitw** [comment]
Looks like that "unsent" comment will appear at the bottom and will disappear if you refresh the browser

<img width="1045" alt="pablo_-_it_werks_inc__it_werks_inc_" src="https://cloud.githubusercontent.com/assets/19347435/15552931/bf0685e8-228a-11e6-9329-69208d4d0513.png">

**Comment by lfbrock** [comment]
Hi @irfaneitw, we have a ticket here about a similar issue: https://mattermost.atlassian.net/browse/PLT-3035

I think they may be related, we're going to look into this.

**Comment by irfaneitw** [comment]
Hi @lfbrock,

Yep, looks like the same bug! We can close this bug and update that bug to show it's both web + iOS

**Comment by lfbrock** [comment]
Thanks, updated it :)

**Comment by dmullenaux** [comment]
Can we reopen this issue? We are having the same problem. 

Refreshing the browser or the desktop client does clear them out, but they start to stack up again as you message back and forth.

root@mattermost:/opt/mattermost/bin
# ./platform --version
Version: 3.1.0
Build Number: 3.1.0
Build Date: Mon Jun 13 19:08:00 UTC 2016
Build Hash: 974238231b9cdbd39a825ec8e9299fbb0b51f6b8
Build Enterprise Ready: false
DB Version: 3.1.0



![image](https://cloud.githubusercontent.com/assets/20480951/16884168/c1c211d4-4a7c-11e6-9772-a310703d0315.png)
