### ISSUE TITLE
"About Mattermost" menu item mostly obscured

### ISSUE THREAD

**Issue by fjarlq** [mattermost/platform#3118]
#### Summary
The "About Mattermost" menu item is mostly not visible due to the improperly-sized menu.

#### Steps to reproduce
1. install Mattermost 3.0.2
2. using Chrome 50, log into the system administrator role (I didn't try other browsers)
3. it might also be necessary for the system administrator to be a member of more than one team
4. select the menu in the upper-left corner

#### Expected behavior
I expect to always be able to clearly see the menu items.

#### Observed behavior
The "About Mattermost" item is mostly obscured because the menu is too short:
![menubug](https://cloud.githubusercontent.com/assets/441483/15559351/9bf13ada-229e-11e6-8eaa-880332bdb495.png)

**Comment by it33** [comment]
Thanks @fjarlq, appreciate the report, I believe this is fixed on master, should come out with 3.1

![image](https://cloud.githubusercontent.com/assets/177788/15560084/eed7aef2-229c-11e6-80b9-0dfa469fec9b.png)
