### ISSUE TITLE
"#hashtag" in Markdown link title unexpectedly produces link to Mattermost hashtag

### ISSUE THREAD

**Issue by fjarlq** [mattermost/platform#3119]
#### Summary
When the text "#hashtag" is used in a Markdown link title, the result is rendered as a link to a Mattermost hashtag search and not to the URL specified by the Markdown link.

#### Steps to reproduce
1. log into Mattermost 3.0.2
2. enter: `[#TheWalkingDead tweets on Twitter](https://twitter.com/hashtag/TheWalkingDead)`
3. examine how Mattermost renders the link

#### Expected behavior
I expect a link to https://twitter.com/hashtag/TheWalkingDead with the clickable title "#TheWalkingDead tweets on Twitter".

#### Observed behavior
Mattermost renders a link to https://example.com/teamname/channels/channelname# with the clickable title "#TheWalkingDead" followed by the nonclickable words " tweets on Twitter".

**Comment by lfbrock** [comment]
Thanks @fjarlq, created a ticket to track the issue here: https://mattermost.atlassian.net/browse/PLT-3066

If anyone from the community is interested in doing a pull request for this, please comment and let us know
