### ISSUE TITLE
Android application autocomplete not working.

### ISSUE THREAD

**Issue by plumpNation** [mattermost/platform#3123]
#### Summary
Mention no longer autocompletes.

#### Steps to reproduce
Galaxy Note 3
Mattermost android client 3.0.2

Open a channel.
type the "@" character
the members list will open
start typing a name

#### Expected behavior
List should filter based on input.

#### Observed behavior
List is not filtered as you type.

#### Possible fixes
If you type @ and a few letters of a name, then space, then place the cursor back at the end of the partially typed name, the list is filtered. This may provide a clue for a fix.

**Comment by lindy65** [comment]
Thanks for the report @plumpNation.  We've created a [ticket](https://mattermost.atlassian.net/browse/PLT-3069) to fix the issue.

**Comment by plumpNation** [comment]
:+1:
