### ISSUE TITLE
Put MYSQL, Redis and the app in 3 separate containers

### ISSUE THREAD

**Issue by veggiemonk** [mattermost/platform#314]
Hi everyone,

By looking at the Dockerfile, everything is installed in a single container. Is it on purpose?
Wouldn't it be better to separate those app and use docker-compose to run them?
A good example would be https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml

What do you think?

**Comment by coreyhulen** [comment]
Thanks for the request.

this is a duplicate of https://github.com/mattermost/platform/issues/63

**Comment by veggiemonk** [comment]
Sorry for the dups. I did reach that far back.
