### ISSUE TITLE
FD leak because http response body doesn't get closed in various functions

### ISSUE THREAD

**Issue by 42wim** [mattermost/platform#3145]
#### Summary
http response body doesn't get read completely and closed in ```model/client.go``` (and ```api/*.go```) functions 

#### Steps to reproduce
see https://github.com/42wim/matterircd/issues/48

#### Expected behavior
http response body get reads completely and gets closed, no file descriptor leaks

#### Observed behavior
file descriptor leaks
(http://stackoverflow.com/questions/33238518/what-could-happen-if-i-dont-close-response-body-in-golang)

#### Possible fixes
Every function that reads r.Body should be fixed (Almost every function of client.go)
E.g GetChannels
```
func (c *Client) GetChannels(etag string) (*Result, *AppError) {
	if r, err := c.DoApiGet(c.GetTeamRoute()+"/channels/", "", etag); err != nil {
		return nil, err
	} else {
		return &Result{r.Header.Get(HEADER_REQUEST_ID),
			r.Header.Get(HEADER_ETAG_SERVER), ChannelListFromJson(r.Body)}, nil
	}
}
```

Possible fixes
```
func (c *Client) GetChannels(etag string) (*Result, *AppError) {
     if r, err := c.DoApiGet(c.GetTeamRoute()+"/channels/", "", etag); err != nil {
         return nil, err
     } else {
        defer func() {
              ioutil.ReadAll(r.Body)
              r.Body.Close()
        }()
        return &Result{r.Header.Get(HEADER_REQUEST_ID),
            r.Header.Get(HEADER_ETAG_SERVER), ChannelListFromJson(r.Body)}, nil
    }
 }
```

Or more idiomatic (without the extra else)
```
func (c *Client) GetChannels(etag string) (*Result, *AppError) {
     r, err := c.DoApiGet(c.GetTeamRoute()+"/channels/", "", etag)
     if err != nil {
         return nil, err
     } 
     defer func() {
           ioutil.ReadAll(r.Body)
           r.Body.Close()
      }()
     return &Result{r.Header.Get(HEADER_REQUEST_ID),
            r.Header.Get(HEADER_ETAG_SERVER), ChannelListFromJson(r.Body)}, nil
}
```

**Comment by jwilander** [comment]
Hi @42wim, thanks for reporting this!

I've created a Jira ticket [here](https://mattermost.atlassian.net/browse/PLT-3165) to get this fixed.

One question, in your defer function you're also performing a `ioutil.ReadAll(r.Body)`, is this necessary before closing the body?

**Comment by 42wim** [comment]
Yes, it's necessary. I implemented it first without reading the complete body. The FD's didn't close (and weren't reused). I reimplemented it with reading the full body and then closing, and it worked fine. Other user of matterircd also reported success.

Also see http://stackoverflow.com/questions/17948827/reusing-http-connections-in-golang
