### ISSUE TITLE
Add `crossorigin="anonymous"` to embedded images

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/platform#3157]
Currently hotlinking an image that is behind HTTP authentication results in everyone (at least Firefox users) getting an ugly HTTP auth prompt. This could probably be used for phishing if your users are gullible enough.

Apparently `crossorigin="anonymous"` on the `img` tag prevents this so it'd be a good idea if all img tags that are created by users (e.g. from markdown `![](url)`) had this attribute. Another option would be to proxy-load them and serve them via MM (that would also avoid mixed content when MM runs on https but the linked image is on http)

**Comment by hmhealey** [comment]
Hi @ThiefMaster,

Thanks for the idea. I didn't know about the `crossorigin` parameter before and thought our only option to fix it was to proxy them, so this seems like a much better solution for the time being. I've created a ticket on Jira to track this: https://mattermost.atlassian.net/browse/PLT-3181
