### ISSUE TITLE
Files send in private chat to non team member are not accessible

### ISSUE THREAD

**Issue by egnerfl** [mattermost/platform#3158]
Hey!

When sending a file to a non team member via the global users feature from 3.0 the other user can`t download the file. 
The file is visible for the user and downloadable but always has 0 bytes (screenshot attached)

![screen shot 2016-05-30 at 15 51 14](https://cloud.githubusercontent.com/assets/4058299/15651212/6680fcd0-267e-11e6-9f4a-ae4522f97bd0.png)

If you create a public link everything works just fine!

Relevant Settings:

```
  "FileSettings": {
        "DriverName": "local",
        "Directory": "/data/mattermost_data/",
        "EnablePublicLink": true,
        "PublicLinkSalt": "<PublicLinkSalt>",
        "ThumbnailWidth": 120,
        "ThumbnailHeight": 100,
        "PreviewWidth": 1024,
        "PreviewHeight": 0,
        "ProfileWidth": 128,
        "ProfileHeight": 128,
        "InitialFont": "luximbi.ttf",
        "AmazonS3AccessKeyId": "",
        "AmazonS3SecretAccessKey": "",
        "AmazonS3Bucket": "",
        "AmazonS3Region": "",
        "AmazonS3Endpoint": "",
        "AmazonS3BucketEndpoint": "",
        "AmazonS3LocationConstraint": false,
        "AmazonS3LowercaseBucket": false
    }
```

In our test case we used a `.txt` file. The issue does not occur in the private chat with team members.

Best
Florian

**Comment by lindy65** [comment]
Thanks @egnerfl 

I've filed a [ticket](https://mattermost.atlassian.net/browse/PLT-3105) to track the issue.
