### ISSUE TITLE
Monokai Custom Theme Examples: barely visible links

### ISSUE THREAD

**Issue by danifr** [mattermost/platform#3211]
Applying the custom theme `Monokai` from http://docs.mattermost.com/help/settings/theme-colors.html#custom-theme-examples results on white colored links on a white background.

Possible fix:

```diff
@@ -1 +1 @@
-#262626,#ffffff,#363636,#ffffff,#cccccc,#525252,#7e9949,#ffffff,#99cb3f,#b8b884,#7e9949,#ffffff,#ffffff,#444444,#90ad58,#54850c,#90ad58,#ffffff,#90ad58,#ffffff,monokai
+#262626,#ffffff,#363636,#ffffff,#cccccc,#525252,#7e9949,#ffffff,#99cb3f,#b8b884,#7e9949,#ffffff,#ffffff,#444444,#90ad58,#54850c,#90ad58,#262626,#90ad58,#ffffff,monokai
```

**Comment by asaadmahmoodspin** [comment]
Filed a ticket on it:
https://mattermost.atlassian.net/browse/PLT-3177

I think a better fix would be is to reorder the theme elements since the other vectors are broken too, I think they got messed up somehow. Here's the fix: https://github.com/mattermost/platform/pull/3226.
