### ISSUE TITLE
Remove debug information from release builds

### ISSUE THREAD

**Issue by ston1th** [mattermost/platform#3212]
#### Summary
Reduce binary file size by stripping debug information in release builds.

#### Observed behavior
Reduced file size by approximately 5-6 MB.

#### Possible fixes
`go build -ldflags "-s -w" .`

**Comment by lfbrock** [comment]
Thanks @ston1th, the team discussed this but in the end decided to keep the debug information in the build because it makes it easier for us to find issues reported by users.
