### ISSUE TITLE
createIndexIfNotExists causing an sql error  with postgres driver

### ISSUE THREAD

**Issue by houssemFat** [mattermost/platform#3259]
#### Summary
createIndexIfNotExists causing an sql error 

#### Steps to reproduce
At the launch, i'm using  ubuntu 14.04 with postgres  9.4.5

#### Expected behavior
Normal run, the call for `createIndexIfNotExists` store/sql_store.go will create indexes for columns.

#### Observed behavior
crash with sql error  `relation "users" does not exist`

#### Possible fixes
* Adding quote on tableName and column name in function `createIndexIfNotExists`  (store/sql_store.go , L 486) fixes this issue.

```
if indexType == INDEX_TYPE_FULL_TEXT {
			query = "CREATE INDEX " + indexName + " ON \"" + tableName + "\" USING gin(to_tsvector('english', \"" + columnName + "\"))"
		} else {
			query = "CREATE " + uniqueStr + "INDEX " + indexName + " ON \"" + tableName + "\" (\"" + columnName + "\")"
		}
```

**Comment by lfbrock** [comment]
Hi @houssemFat, thanks for the report - I've filed a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-3274
