### ISSUE TITLE
CLI: invite user by email - missing siteURL in email

### ISSUE THREAD

**Issue by tbalthazar** [mattermost/platform#3291]
#### Summary
When inviting a user via the CLI, the email body is missing the `siteURL`, making the "Join Team" button useless.

#### Steps to reproduce
Run:
`go run mattermost.go -invite_user -team_name="byrecords" -email="roger8@example.com"`

#### Expected behavior
Roger receives an email containing a "Join Team" link that looks like:
`https://mattermost.example.com/signup_user_complete/?d=%7B%22display_name%22%3A%22byrecords%22%2C%22email%22%3A%22roger8%40example.com%22%2C%22id%22%3A%22pbpkz5iwdfdsjxx95p7nhw8rbc%22%2C%22name%22%3A%22byrecords%22%2C%22time%22%3A%221465400177786%22%7D&h=%242a%2410%24M0U4%2F4tSn0orOvSduHFP7.sKiQGejRECn03Ei20jaMolOmHWB35rG`

#### Observed behavior
The "Join Team" is missing the siteURL and looks like:
`/signup_user_complete/?d=%7B%22display_name%22%3A%22byrecords%22%2C%22email%22%3A%22roger8%40example.com%22%2C%22id%22%3A%22pbpkz5iwdfdsjxx95p7nhw8rbc%22%2C%22name%22%3A%22byrecords%22%2C%22time%22%3A%221465400177786%22%7D&h=%242a%2410%24M0U4%2F4tSn0orOvSduHFP7.sKiQGejRECn03Ei20jaMolOmHWB35rG`

#### Possible fixes
The `cmdInviteUser` function [creates a mock context](https://github.com/mattermost/platform/blob/master/mattermost.go#L843) but the [siteURL field of the Context struct is not exported](https://github.com/mattermost/platform/blob/master/api/context.go#L41) so it cannot be modified.
An easy fix would be to make the `siteURL` field exported, add a mandatory `-site_url` flag to the `invite_user` command and pass the value of this new flag to the mock context.

Please let me know what you think. I can work on something if that helps.

**Comment by lfbrock** [comment]
Hi @tbalthazar, thanks for the report, I've filed a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-3275

If anyone from the community would like to submit a contribution for this, I can set it to accepting pull requests

**Comment by tbalthazar** [comment]
@lfbrock Sure, I'll try to submit a patch tomorrow.
