### ISSUE TITLE
3.1.0-rc2 EE: LDAP authentication fails without firstname/lastname attributes set

### ISSUE THREAD

**Issue by hjf288** [mattermost/platform#3294]
#### Summary
LDAP logins fail when first name and last name attributes are not set.

#### Steps to reproduce
Version: 3.1.0-rc2

Configure LDAP authentication but leave the first name and last name attributes unset.

#### Expected behavior
The help text below the attributes should state that these are required fields and there should be validation that would stop the user from enabling LDAP without these fields being set.

#### Observed behavior
User receives error 500 status code when attempting to login using valid credentials.

Stack trace added below:

http://pastebin.com/VXGaBh8q

#### Possible fixes
- Add a (Required) to the help description
- Add validation to prevent the user from enabling LDAP without setting these fields.

**OR**

- Allow these fields to be blank

**Comment by jasonblais** [comment]
Thank you for the report! I've filed [a ticket](https://mattermost.atlassian.net/browse/PLT-3276).

We'll fix it so that firstname/lastname attributes can be left blank
