### ISSUE TITLE
Cannot access S3 due to problems with signatureVersion

### ISSUE THREAD

**Issue by exolab** [mattermost/platform#3308]
#### Summary
Cannot use an S3 bucket in eu-central-1, as this region only supports signatureVersion v4.

#### Steps to reproduce
1. Set up an S3 bucket in eu-central-1 (Frankfurt) and make it accessible.
2. Change configuration for files to use this bucket.
3. Upload a file.

#### Expected behavior
File is uploaded.

#### Observed behavior
An error happens. Here is an excerpt from the log file:

Encountered an error writing to S3 [details: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.]

#### Possible fixes
Change signature version to v4.

**Comment by it33** [comment]
Thanks @exolab, appreciate the report,

Anyone else from the community able to repro this issue? Also, if this repros, would anyone be open to helping with a PR to address this?

**Comment by it33** [comment]
Hi @exolab we have a ticket tracking the fix for this now, to update to latest AWS drivers: https://mattermost.atlassian.net/browse/PLT-2164

Closing so we can track there.
