### ISSUE TITLE
Text snippet in attachment doesn't show properly when collapsed

### ISSUE THREAD

**Issue by GMoustacky** [mattermost/platform#3310]
Hi guys,

I've came across an issue when posting a text snippet in an attachment.

#### Summary
If an attachment is too long, it is collapsed. It breaks text snippets.

#### Steps to reproduce

    $ curl -i -X POST -d 'payload={ "attachments":[{"title":"Hello World","text":```\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n```"}], "channel": "#town-square"}' http://example.com
    HTTP/1.1 200 OK
    Content-Security-Policy: frame-ancestors 'none'
    Content-Type: text/plain
    X-Frame-Options: DENY
    X-Ratelimit-Limit: 10
    X-Ratelimit-Remaining: 9
    X-Ratelimit-Reset: 1
    X-Request-Id: [hidden]
    X-Version-Id: 3.0.0.1465478567
    Date: Fri, 10 Jun 2016 15:43:57 GMT
    Content-Length: 2
    ok%
    $ 

#### Expected behavior
![screen shot 2016-06-10 at 17 40 05](https://cloud.githubusercontent.com/assets/7372622/15970064/0814d9a6-2f33-11e6-865a-a0a0402b985a.png)

#### Observed behavior
![screen shot 2016-06-10 at 17 39 55](https://cloud.githubusercontent.com/assets/7372622/15970065/0d6e3de8-2f33-11e6-8146-4deef4b3b39e.png)

Hope it's clear enough ! I'm using the docker preview, let met know if it has been resolved and the docker isn't up-to-date.
Thanks for the ready-to-use container.

**Comment by lfbrock** [comment]
Thanks for the report @GMoustacky, it was very clear! I tested it out with the example attachment and it looks like it's still an issue on master.

Would anyone from the community be interested in working on a pull request for this?

**Comment by esethna** [comment]
Thanks for the great report @GMoustacky! I've created a ticket [here](https://mattermost.atlassian.net/browse/PLT-3340) where this issue can be tracked in Jira. Closing this ticket.
