### ISSUE TITLE
Email address "allowed domains" check appears to be case-sensitive

### ISSUE THREAD

**Issue by thiyagaraj** [mattermost/platform#3349]
#### Summary
When a new user tries to sign up via an email invite, the "v3/users/create" API path appears to do a case-sensitive comparison of the email address's domain name entered by the inviter against the domains listed in "Restrict Creation To Domains" Team setting, resulting in a valid email address being blocked from completing sign-up.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
v3.0.3
1. Add a domain restriction in "Team settings" by updating the "Restrict Creation To Domains:" setting. Eg: gmail.com
2. Invite a new user, but modify the case of the invite email address's domain name, eg: example@**G**mail.com
3. The email gets sent out without any issue
4. When the user tries creating a new userid, on submission, he gets an error saying that the email address is not from an allowed domain name(it appears to do a case-sensitive comparison of the domain name section in the invite vs. the setting in team settings)

#### Expected behavior
User should be able to sign up as the email address's domain name is whitelisted, irrespective of the character case that users may type in the email address field when they invite others

#### Observed behavior
Error on new user creation indicating that the email address is not from an allowed domain

#### Possible fixes
Case sensitive comparison should be changed to case-insensitive
https://github.com/mattermost/platform/blob/master/api/user.go#L193

**Comment by esethna** [comment]
Hi @thiyagaraj, thanks for submitting the PR on this! Agree with you're expected. Closing this issue and will follow up on the PR.
