### ISSUE TITLE
Hitting <enter> does'nt send messages anymore

### ISSUE THREAD

**Issue by tbalthazar** [mattermost/platform#3352]
#### Summary
Hitting `<enter>` does'nt send messages anymore

#### Steps to reproduce
- checkout from master
- make run
- type a message and hit `<enter>`

#### Expected behavior
- message should be sent to the channel

#### Observed behavior
- message is not sent, `<enter>` is ignored

#### Possible fixes
- looks like [this commit](https://github.com/mattermost/platform/commit/7d9f066728c7a02c493585542fb7a77bc0ed3f3e) might cause the issue. If I checkout [this commit](https://github.com/mattermost/platform/commit/7114d33a06009cb78276262deb733cb6ed71dd8c), the issue disappears.

**Comment by it33** [comment]
@DavidLu1997?

**Comment by DavidLu1997** [comment]
@it33 fixed with https://github.com/mattermost/platform/pull/3356

**Comment by it33** [comment]
Thanks @DavidLu1997

**Comment by enahum** [comment]
@tbalthazar closing this as it is reported as fixed.

In case this still repro for you, please reopen this ticket.

Thanks.
