### ISSUE TITLE
Stop sniffing the browser's User-Agent string

### ISSUE THREAD

**Issue by aperezdc** [mattermost/platform#3353]
#### Summary
The Mattermost web interface uses the User-Agent of the browser, which is [a bad idea](http://stackoverflow.com/questions/661213/why-is-browser-sniffing-not-a-recommended-practice) because browsers can (and do) anyway lie about which browser they are.

#### Steps to reproduce
Try to access a Mattermost instance using [GNOME Web](https://wiki.gnome.org/Apps/Web/) (also known as Epiphany).

#### Expected behavior
The Mattermost web interface loads and works. GNOME Web uses WebKitGTK, which is the same rendering engine used by Safari — whatever works in Safari should work in GNOME Web.

#### Observed behavior
Mattermost returns a “Your current browser is unsupported” message.

#### Possible fixes
Note that this is a nasty workaround: changing the User-Agent string that GNOME Web uses makes Mattermost work just fine. This can be done with:

```sh
gsettings set org.gnome.Epiphany user-agent \
 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36'
```

**Comment by jasonblais** [comment]
Thanks @aperezdc for the report,

GNOME Web isn't currently supported - here is a [list of software requirements](http://docs.mattermost.com/install/requirements.html#software-requirements), including the browser versions we support

**Comment by aperezdc** [comment]
@jasonblais: That is all nice and so, but I want to remind you again that GNOME Web uses WebKitGTK+, which provides the same feature set as Safari — if you support Safari, you are supporting GNOME Web. The fact that changing the reported `User-Agent` makes the web interface work *flawlessly* shows that sniffing its value it's not just pointless, but also a cause of frustration for users of non-Safari, WebKit-based browsers.

I am not asking that you claim in your list of supported browsers that GNOME Web works —you can leave it as-is— but that Mattermost won't sniff the `User-Agent` string. And, if it does, the most it would do is suggesting a list of recommended browsers, but that it does not prevent using others after warning the user that their browser is unsupported.

**Comment by jasonblais** [comment]
Hi @aperezdc, while I can see where you're coming from, the intended behavior is to show an error message when an unsupported browser is used. Therefore, per the GitHub issues template for the project, this isn't a fit for a bug report.

You're welcome to nominate the proposed change [as a feature idea](http://www.mattermost.org/feature-ideas/) so it can be discussed and upvoted.

**Comment by aperezdc** [comment]
Submitted: https://mattermost.uservoice.com/forums/306457-general/suggestions/15011652-stop-sniffing-the-user-agent-use-feature-detectio

**Comment by mcatanzaro** [comment]
Hey @aperezdc, if this is for an internal site you're testing, you must of course patch the mattermost deployment, but if it's for a public site, you can submit a patch to add a quirk in Source/WebCore/platform/gtk/UserAgentGtk.cpp. Our policy is to use user agent quirks whenever required to make sites work. I already have a request to do this for framateam.org.

**Comment by mcatanzaro** [comment]
(Actually I forgot I had already noted in #3542, we just need to bump our Safari version in the UA up to 9, so we don't need a quirk for this at all.)
