### ISSUE TITLE
DeviceId is not set when login through SSO (GitLab)

### ISSUE THREAD

**Issue by guyguy333** [mattermost/platform#3355]
#### Summary
When I login on my iOS device with a "normal" account (!= GitLab account), I get notifications on my iOS device and "DeviceId" field is set in the database.
However, when I login on my iOS device using my GitLab account, I don't have notifications. Looking in the database, "DeviceId" column is left empty.

#### Steps to reproduce
Mattermost 3.1.0 (same issue with Lattermost 3.0.3)
Login on your iOS device using a GitLab account. "DeviceId" field is not set and notifications doesn't work.

#### Expected behavior
 "DeviceId" field is set and notifications work in case I login with a GitLab account.

#### Observed behaviour
No specific errors as the field "DeviceId" is left empty, notifications are not sent.

**Comment by esethna** [comment]
Thanks for this report @guyguy333, closing this issue to [track in JIRA](https://mattermost.atlassian.net/browse/PLT-3386).
