### ISSUE TITLE
Feature list link in sidebar leads to 404

### ISSUE THREAD

**Issue by bkaes** [mattermost/platform#336]
*Note:* This is a front page bug, not a platform bug, but I couldn't find separate instructions for those.

----

In the navigation of mattermost.org, the current "Feature list" link in the section "About mattermost" leads to a 404. The URL http://www.mattermost.org/70-2/ should get replaced by http://www.mattermost.org/features/.

**Comment by it33** [comment]
Thanks @bkaes, fixed!
