### ISSUE TITLE
Two Tabs opened: Channel list gets filled up with channels/private groups from both

### ISSUE THREAD

**Issue by ppakdev** [mattermost/platform#3376]
#### Steps to reproduce
Have webapp opened in two tabs (this happened in Chrome and the desktop client) for two different teams. Start clicking into channels or private groups. 

#### Expected behavior
Not to see channels/private groups from Team A show up in the list on the tab for the other Team B.

#### Observed behavior
Channels and private groups from Team A show up in the tab that's open for Team B. Then when trying to click the Team A channel from the Team B tab, you get a 403 status code and `You do not have the appropriate permissions` flash message and it disappears from the list.

**Comment by jasonblais** [comment]
Thanks @ppakdev for the report,

On which operating system is the error reproducing for you? If you haven't yet, you may also try upgrading to [Mattermost v3.1](http://www.mattermost.org/mattermost-3-1-apple-watch-notification-upgrades-shortcuts-compact-view-openshift-and-more/), to see if it reproduces on the most recent release.

**Comment by TwizzyDizzy** [comment]
Hi folks,

same issue here on Mattermost Team Edition 3.1.0.

Cheers
Thomas

**Comment by jnugh** [comment]
Same issue on 3.1 running inside the official production docker container.
Chrome & Mattermost Desktop: same this behavior.

A channel C from team A pops up in team B after switching from viewing C to another channel.
Can reproduce this consistently.

My user role is "system admin".

**Comment by jasonblais** [comment]
Thanks @TwizzyDizzy and @jnugh for the confirmation,

We indeed have a [pull request](https://github.com/mattermost/platform/pull/3329), which will fix the issue for our next release

Highly appreciate your reports!
