### ISSUE TITLE
Port Mattermost team's internal issue tracker into a publicly visible system

### ISSUE THREAD

**Issue by it33** [mattermost/platform#339]
Transparency will help everyone. 

The internal Mattermost issue tracker is currently shared with our video games business and it'll take some time to port into a public workflow. We just need to carve out time to do it.

**Comment by ralder** [comment]
+1 till then, author of pull request may copy text of internal issue to description of github PR

**Comment by it33** [comment]
Mattermost internal issue tracker now moved to public instance at: https://mattermost.atlassian.net/secure/Dashboard.jspa

Note: Public instance has a mix of public and private tickets. An internal triage process is used to determine if tickets are sufficiently clear and devoid of private information before they are set to be publicly viewable.
