### ISSUE TITLE
Mattermost 3.1 crashes when I send a message in a specific channel

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#3394]
#### Summary

Mattermost 3.1 crashes with a runtime error "invalid memory address or nil pointer dereference" from `github.com/mattermost/platform/api.sendNotifications`, when I send a message in a specific public channel.

#### Steps to reproduce

1. Install Mattermost 3.1.
2. Send some messages.

#### Expected behavior

Mattermost doesn't crash.

#### Observed behavior

Mattermost sometimes crashes in a specific public channel with this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xd8 pc=0x6046bb]

goroutine 1232 [running]:
panic(0xccaca0, 0xc82000a0a0)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/mattermost/platform/api.sendNotifications(0xc8209bdc20, 0xc8204416c0, 0xc820436be0, 0xc82068e210, 0xc82081fad0, 0xc820b40000, 0x80, 0x80)
        /home/nori/go/src/github.com/mattermost/platform/api/post.go:504 +0x1f3b
created by github.com/mattermost/platform/api.handlePostEvents
        /home/nori/go/src/github.com/mattermost/platform/api/post.go:282 +0x121d
```

This error occured two times (10:10am KST and 10:15am KST) today.

**Comment by it33** [comment]
Hi @npcode, we're not able to repro this. 

Did you manually remove users from the database, without using the command line tool?

**Comment by it33** [comment]
If you have removed the user manually in the database, the associated channel objects also need to be removed. This is probably what's causing the crash. 

There's [a PR to prevent crashing from this database inconsistency in future](https://github.com/mattermost/platform/pull/3395), but it shouldn't be an issue unless there's a specific manual update issue.

**Comment by npcode** [comment]
@it33 You're right. That was the reason of my problem. I have resolved it by removing the "ghost" members from the channels. Thanks for the quick fix!

**Comment by it33** [comment]
Glad to hear, we've added an extra check to avoid the error in 3.2 just to be extra safe: https://github.com/mattermost/platform/pull/3395

Thanks for the report!

**Comment by npcode** [comment]
Just out of curiosity: Why don't you use foriegn key to prevent this kind of violation of referential integrity?
