### ISSUE TITLE
SVG attachments are not rendered

### ISSUE THREAD

**Issue by akhmerov** [mattermost/platform#3428]
#### Summary
attaching an SVG file does not trigger the render of the image

#### Steps to reproduce
Attach an SVG file.

#### Expected behavior
SVG is supported by all modern browsers, so the image should be immediately rendered similar to what happens in attaching JPG or PNG.

#### Observed behavior
The render does not happen.

**Comment by lfbrock** [comment]
Hi @akhmerov, SVG previews are not supported at this time - you can [open a feature request](http://www.mattermost.org/feature-ideas/) on the idea, or if anyone from the community is interested in working on this feature we can consider opening an accepting pull requests ticket on it.

**Comment by akhmerov** [comment]
Understood; here's the feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/15018105-add-svg-attachment-rendering
