### ISSUE TITLE
mattermost consumes more memory day by day

### ISSUE THREAD

**Issue by hvnsweeting** [mattermost/platform#3447]
#### Summary
memleak in mattermost

#### Steps to reproduce
Version: 3.0.0 (3.0.3)
But we suffer this issue since old version (2.1.0)

```
$ lsb_release -d; uname -r; free -m
Description:	Ubuntu 14.04.4 LTS
3.13.0-68-generic
             total       used       free     shared    buffers     cached
Mem:           490        478         12         29         20        173
-/+ buffers/cache:        283        206
Swap:            0          0          0
```

#### Expected behavior
memory is stable

#### Observed behavior
platform consumes more and more memory until it's killed by kernel (OOM)

![mm_mem](https://cloud.githubusercontent.com/assets/1000665/16440653/2deec168-3dee-11e6-9201-154dec864e33.png)

Is this a know issue or just because I wrongly config mattermost?

**Comment by lfbrock** [comment]
Hi @hvnsweeting, I suspect it's an issue with your set up as we haven't seen any other similar reports. Can you try posting on the [troubleshooting forums](https://forum.mattermost.org/) with more information about your set up?
