### ISSUE TITLE
Team admins can't give "team admin" privilege to members

### ISSUE THREAD

**Issue by ldidry** [mattermost/platform#3454]
#### Summary
Since migration to version 3.1.0, team admins with no "system admin" privilege can't give "team admin" privilege to members of their teams

#### Steps to reproduce
Version: 3.1.0
Installed with Gitlab Omnibus installation
Personally tested with Firefox 48 in private mode, users reported the bug with Firefox and Chromium.

#### Expected behavior
Team admins should be able to give "team admin" privileges to members.

#### Observed behavior
Mattermost says `The system admin role is needed for this action` and this is the output of the javascript console:

```
method=updateRoles msg=The system admin role is needed for this action detail= rid=hzi58ydbnt8durkppbifbzn58o       bundle-3.1.0.js:63:3234
  f</<.value()                               bundle-3.1.0.js:63
  f.prototype.callback()                     bundle-3.1.0.js:36
  f/<()                                      bundle-3.1.0.js:36
  a.prototype.emit()                         bundle-3.1.0.js:78
  f.prototype.end/n.onreadystatechange()     bundle-3.1.0.js:36

Object { id: "api.user.update_roles.system_admin_…", message: "The system admin role is needed for…", detailed_error: "", request_id: "hzi58ydbnt8durkppbifbzn58o", status_code: 403, is_oauth: false }     bundle-3.1.0.js:63:3251
  f</<.value()                               bundle-3.1.0.js:63
  f.prototype.callback()                     bundle-3.1.0.js:36
  f/<()                                      bundle-3.1.0.js:36
  a.prototype.emit()                         bundle-3.1.0.js:78
  f.prototype.end/n.onreadystatechange()     bundle-3.1.0.js:36
```

#### Possible fixes
Sorry, no idea :frowning:

**Comment by esethna** [comment]
Thanks for the report! Closing this issue to [track in JIRA](https://mattermost.atlassian.net/browse/PLT-3502)
