### ISSUE TITLE
Andoird didn't cache bundle.js 

### ISSUE THREAD

**Issue by shenyangECQ** [mattermost/platform#3455]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Andoird didn't cache bundle.js 

#### Steps to reproduce
1. launch Mattermost Android
2. Switch few channels 
3. click 'home' button, let Mattermost run in backend
4. click recent 'Recents' button, remove Mattermost
5. launch Mattermost Android again 
6. check server access log, found Mattermost download bundle.js again.(http code 200 OK)

#### Expected behavior
Describe your issue in detail
Except bundle.js should not been download so frequent,
If monitor the  network, the http code should be 304 or 200(cache)

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
when monitor the  network, the http code is 200(ok)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

This might be a websocket bug in Android, rest platform are ok. 
so in shouldInterceptRequest of MainActivity, add below, use default http cache to manage bundle.js

                if (url.endsWith(".js") || url.endsWith(".woff2")){
                    HttpURLConnection connection = null;
                    try {
                        connection = (HttpURLConnection) new URL(url).openConnection();
                        connection.connect();
                        final String content_type = connection.getContentType();
                        final String separator = "; charset=";
                        final int pos = content_type.indexOf(separator); 
                        final String mime_type = pos >= 0 ? content_type.substring(0, pos) : content_type;
                        final String encoding = pos >= 0 ? content_type.substring(pos + separator.length()) : "UTF-8";
                        return new WebResourceResponse(mime_type, encoding, connection.getInputStream());
                    } catch (final MalformedURLException e) {
                        e.printStackTrace(); return null;
                    } catch (final IOException e) {
                        e.printStackTrace(); return null;
                    }
                }

**Comment by lfbrock** [comment]
Hi @shenyangECQ, we have a ticket here that will involve setting up the cacheing properly, so this issue should be fixed once it is completed. 

https://mattermost.atlassian.net/browse/PLT-2396
