### ISSUE TITLE
If the last member of a group is not an admin, he/she is not allowed to leave the group

### ISSUE THREAD

**Issue by Endemoniada** [mattermost/platform#3456]
#### Summary
I remained as the last user in a group, but because I am not an admin in the team, I was not allowed to leave the group or delete it.

#### Steps to reproduce
Make a private group
Invite users
Have all admins and other users leave
Try to leave or delete the group

#### Expected behavior
A user should be able to leave a group even when they're the last user and not an admin. Logically that group would then "self-destruct" and close. Possibly it could remain visible for admin users to close and/or add users to.

**Comment by esethna** [comment]
Thanks for the report! This issue will be fixed by [this PR](https://github.com/mattermost/platform/pull/3453) submitted for v3.2, expected to release July 16, 2016.
