### ISSUE TITLE
Push notifications sent to mobile even when desktop app is open

### ISSUE THREAD

**Issue by jakespencer** [mattermost/platform#3482]
If you enable mobile notifications and then have a for example direct message conversation with another user on the web/desktop app your mobile will get flooded with notifications.

It would be great to have a setup similar to Slack for example where they only send you a push notification if you have not read the message within n minutes. An alternative easier solution would be if you are active on the web or desktop app don't send a push notification, this is what HipChat does.

Currently we have users just turning off their mobile notifications because it is too disruptive which is not ideal at all.

**Comment by esethna** [comment]
Thanks @jakespencer. Agreed. We have a [ticket](https://mattermost.atlassian.net/browse/PLT-3461) to trigger push notifications dependent on your online status. Closing this issue to track in JIRA.
