### ISSUE TITLE
semicolon bug

### ISSUE THREAD

**Issue by TheFamousPG** [mattermost/platform#3502]
#### Summary
I can't send semicolon(;) character.
Error return : Unable to parse incoming data.

#### Steps to reproduce
`curl -i -X POST -d 'payload={"text":";"}' https://chat.my_domain/hooks/my_hook_id`

**Comment by jasonblais** [comment]
Thanks @TheFamousPG for the report!

May I ask which operating system are you using? And which version of the Mattermost server are you running (from Main Menu > About Mattermost)?

**Comment by TheFamousPG** [comment]
Of course ;) Mattermost is on ubuntu 14.04
https://i.gyazo.com/3e9838f71576b2885714176384169acd.png

**Comment by jasonblais** [comment]
Thanks @TheFamousPG! 

Anyone else from the community able to repro this issue? Also, if it does, would anyone be open to helping with a PR to address this?

**Comment by johnjamesjacoby** [comment]
Unable to duplicate:

<img width="1205" alt="screen shot 2016-07-13 at 18 38 03" src="https://cloud.githubusercontent.com/assets/88951/16823341/0c88bd4e-4929-11e6-850e-4cd3650bca5d.png">
<img width="262" alt="screen shot 2016-07-13 at 18 38 36" src="https://cloud.githubusercontent.com/assets/88951/16823342/0c986b90-4929-11e6-8578-f9ef322cc919.png">

**Comment by jasonblais** [comment]
Hey @TheFamousPG, thanks again for your report, and big thanks @johnjamesjacoby for attempting to duplicate the error.

If you're still experiencing this issue, you're welcome to post this to the [Troubleshooting Forum](http://www.mattermost.org/troubleshoot/) for a faster response. 

If you do, please include complete steps to reproduce the issue so a community member can follow them as they're trying to reproduce it.

**Comment by bastbnl** [comment]
In case you're interested in a way to reproduce:
`curl -i -X POST -d 'payload={"text": "; :tada:"}' -H 'Content-Type: application/json' <webhook-url>`

It does not happen when posting using, since that message is accepted and visible in the channel:
`curl -i -X POST -d '{"text": "; :tada:"}' -H 'Content-Type: application/json' <webhook-url>` 

However, this is accepted (as in: 200, with a message in the channel)
`curl -i -X POST -d 'payload={"text": "Hello, this is some text\nThis is more text. :tada:"}' <webhook-url>`

**Comment by walquis** [comment]
I am also seeing exactly this.

**Comment by walquis** [comment]
MM seems to have the same issue with ampersand.   If I URL-encode them (e.g. %26 for ampersand and %3B for semicolon), they go through.  Any others...?

**Comment by jwilander** [comment]
This one is an incorrect request
`curl -i -X POST -d 'payload={"text": "; :tada:"}' -H 'Content-Type: application/json' <webhook-url>`

You're supplying a body of `payload={"text": "; :tada:"}` which is the `application/x-www-form-urlencoded` content type but you're specifying the content type of `application/json`

The correct request would be this (like posted above)
`curl -i -X POST -d 'payload={"text": "Hello, this is some text\nThis is more text. :tada:"}' `

Or
`curl -i -X POST -d 'payload={"text": "Hello, this is some text\nThis is more text. :tada:"}' -H 'Content-Type: application/x-www-form-urlencoded'  `

**Comment by bastbnl** [comment]
You're absolutely right when it comes to the `payload` key in the - well, ehm - payload. I'd prefer mattermost ignoring the message instead of partially accepting it.
