### ISSUE TITLE
[Solved] Desktop app can't use multi-select in file upload dialog

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/platform#3522]
#### Summary
Desktop app can't use multi-select in file upload dialog.

#### Steps to reproduce
Mattermost server 3.1.0
Mattermost desktop 1.2.1 on Windows 10

1. Click the button to attach files.
2. File select dialog opens.
3. Try to select multiple files in the dialog.

#### Expected behavior
Desktop app can select multiple files in the dialog.

#### Observed behavior
`multiple` attribute is missing in `<input>` of the button to attach files.

#### Possible fixes
https://github.com/mattermost/platform/blob/v3.2.0-rc1/webapp/utils/utils.jsx#L69

The UserAgent of the app is like `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Mattermost/1.2.1 Chrome/49.0.2623.75 Electron/0.37.8 Safari/537.36`, so now it seems that `isMobileApp()` returns `true`. This should be `false`.

As the result, [`multiple` will be `true`](https://github.com/mattermost/platform/blob/v3.2.0-rc1/webapp/components/file_upload.jsx#L305).

#### Reference
- [Win7 x64 desktop: Allow multi-select in file upload dialog – Mattermost Feature Request Forum](https://mattermost.uservoice.com/forums/306457-general/suggestions/13092408-win7-x64-desktop-allow-multi-select-in-file-uploa)
- mattermost/desktop#190

**Comment by lfbrock** [comment]
Thanks @yuya-oc, I created a ticket to go investigate this. https://mattermost.atlassian.net/browse/PLT-3683

If anyone is interested in making a pull request for this, let us know.

**Comment by jasonblais** [comment]
[Pull request has been merged](https://github.com/mattermost/platform/pull/3654) and issue verified fixed on Windows.

Thanks @yuya-oc for the report! Closing issue as resolved.
