### ISSUE TITLE
[Android] Back Button + Menu Open Backs Content as Well as Closing Menu

### ISSUE THREAD

**Issue by starlightknight** [mattermost/platform#3527]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
I use a phone with a hardware back button. When the menu is open, pressing the back button closes the menu. This is also how it behaves in Slack, and what I would expect. However, in Mattermost Android, it also triggers a back on the content, which switches me to the last channel i was on, or if I was still in the default channel, out of the team. This is very confusing.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

Gitlab+Mattermost, Android -> 3.1.0 3.10

Sign in, change channels a few times, open the menu, press the back button. Repeat several times and watch your actions rewind as the menu closes.

#### Expected behavior
Describe your issue in detail

Back button with the menu open should only close the menu, like in Slack

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

Also went back on the content along with closing the menu.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

Not sure

**Comment by lindy65** [comment]
@starlightknight Thank you for your issue report.  We'll be tracking it with this ticket: https://mattermost.atlassian.net/browse/PLT-3632
