### ISSUE TITLE
Settings screen not appearing

### ISSUE THREAD

**Issue by prakashprabhakar** [mattermost/platform#3528]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Settings screen not appearing

#### Steps to reproduce
I am using mattermost desktop 1.2.1 on Ubuntu. Below are the steps to reproduce.

1) Login into 2 team
2) And then click on File --> Settings

#### Expected behavior
Setting screen should be shown.

#### Observed behavior
Screen was blank.
Note: Out of 10 times, I have observed this happening 5+ times

**Comment by jasonblais** [comment]
Thanks @prakashprabhakar for the report, 

I have cross-posted your issue to the [\desktop](https://github.com/mattermost/desktop/issues/196) repository for feedback from our Desktop App community.

I will close this issue, so we can continue discussing it in [the desktop repo](https://github.com/mattermost/desktop/issues/196) instead.
