### ISSUE TITLE
Wrong link to manifest.json in <head>

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3541]
#### Summary
The URL to manifest.json in `<head>` is wrong.

#### Steps to reproduce
* Look at Mattermost HTML code:
```html
<link rel=manifest href=/static/config/manifest.json>
```
* Try to load https://team.example.com/static/config/manifest.json.

#### Expected behavior
The manifest should load.

#### Observed behavior

> 404 page not found

#### Possible fixes
The correct file seems to be here: https://github.com/mattermost/platform/blob/master/webapp/config/manifest.json

**Comment by jasonblais** [comment]
Thanks @Rudloff for the report! Nice find,

Would anyone be open to submitting a pull request to fix the issue? The change would be replacing the link [here](https://github.com/mattermost/platform/blob/9e07f4b021b28a3e301359a48cf950298f3e552e/webapp/root.html#L32) with [this page](https://github.com/mattermost/platform/blob/master/webapp/config/manifest.json) instead.

An excellent opportunity for a first contribution as well

**Comment by Rudloff** [comment]
I can submit a pull request.
It could be an opportunity to add some missing fields (e.g. `display`) to the manifest too.

**Comment by jasonblais** [comment]
Huge thanks @Rudloff again both for the report and submitting a fix for it!

[Given your pull request has been merged](https://github.com/mattermost/platform/pull/3582), closing this issue.
