### ISSUE TITLE
Umlauts ignored at the end of tags

### ISSUE THREAD

**Issue by dkunzler** [mattermost/platform#3543]
#### Summary
If you use a german umlaut at the end of a hashtag (#testü) the umlaut will get ignored for the "linkification".

#### Steps to reproduce
Write a tag in a conversation that ends with an umlaut (ä,ö,ü) or ß. Like #testü.

#### Expected behavior
The complete tag is a link to search for messages with the same tag.

#### Observed behavior
Link is only done for the characters before the umlaut, hence the search after clicking does not find the relevant results. It works if the umlaut is within the tag, like #testütest

**Comment by dirvo** [comment]
This might be related to https://github.com/mattermost/platform/pull/1710

Related issue: There is also a minimum length of 3 for hashtags. For example #UX is not recognized as a hash tag. I'd expect that there is no lower limit on the length of hashtags and that even a single-character hashtag works.

**Comment by jasonblais** [comment]
Thanks @dkunzler for the report! 

I have opened [a ticket in Jira](https://mattermost.atlassian.net/browse/PLT-3621) to track the issue. If someone from the community is interested in submitting a fix for this, please let us know.

**Comment by jasonblais** [comment]
We also have another ticket to investigate this issue in general https://mattermost.atlassian.net/browse/PLT-1539
