### ISSUE TITLE
Creating Accounts

### ISSUE THREAD

**Issue by sosvatics** [mattermost/platform#355]
Hello, I am trying to access mattermost from mattermost.ourdomain.com and it works but I cannot sign up from that page. When I click "Sign up Now", it redirects me to ourdomain.com. Furthermore, if I access the page from loclhost:8065, I can sign up and log in but I cannot go back to mattermost.ourdomain.com using the same credentials to login. I noticed this is a current issue so I followed the recommended fixes and the lines of code are already changed but still not working. How do I check which version of mattermost I am running and how do I update mattermost? Thank you

**Comment by crspeller** [comment]
If your using the docker image you can upgrade to the latest version 0.6.0 by running: 
`docker pull mattermost/platform`

Let me know if this fixes your issue.

**Comment by crspeller** [comment]
Closing because question has been answered.
