### ISSUE TITLE
Direct messages: usernames not shown due to different teams

### ISSUE THREAD

**Issue by phrix32** [mattermost/platform#3561]
#### Summary
In direct messages the username of the other one is not shown in the sidebar if he is not in your currently selected team.

#### Steps to reproduce
1. Create 2 users (User A and User B)
2. Create 2 teams (Team A and Team B)
3. User A joins Team A and B
4. User B joins **only** Team A
5. User A selects Team A (where both users are part of)
6. User A direct messages User B
7. User A switches to Team B (where User B **is not** part of)

#### Expected behavior
Users should see usernames of direct messages even if the other one is not part of the currently selected team.

#### Observed behavior
User A can't see username of User B under direct messages in the sidebar until he switches back to a team where both users are part of. In the picture below you can see, that the username of User B isn't shown to User A, if User A is part of a team in which User B isn't.
![mattermost_direct_messages_different_team_bug](https://cloud.githubusercontent.com/assets/4717455/16775785/94a67030-4862-11e6-88f2-05d746aaf99f.png)

#### Possible fixes
https://github.com/mattermost/platform/blob/5f7cb8cfbf879aa0b0d43a7b7068688368fda9fc/webapp/components/sidebar.jsx#L126

**Comment by jasonblais** [comment]
Thanks @phrix32 for the report! We have an [open Jira ticket to track the issue](https://mattermost.atlassian.net/browse/PLT-3547), if you're interested in submitting a fix, please let us know.

**Comment by jasonblais** [comment]
@phrix32 Pull request has been submitted to `master`, which should help fix the issue: #3567 

Thanks again for the report!
