### ISSUE TITLE
Attachments don't work with outgoing webhooks

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3572]
#### Summary
Mattermost 3.1.0 ignores the attachments returned by my webhook.

#### Steps to reproduce
Create an outgoing webhook that returns an attachment payload.
Example:
```json
{"attachments":[{"text":"foo","title":"bar","fallback":"baz"}]}
```
Post a message that triggers the hook.

#### Expected behavior
Mattermost displays the attachment.

#### Observed behavior
Nothing is displayed.

I can confirm the hook itself is working because if I return simple text/markdown JSON, it works perfectly.

**Comment by lfbrock** [comment]
Hi @Rudloff, 

Are you meaning that the message gets posted successfully but nothing is displayed? 

We fixed an issue for v3.2 where [message attachments were following the /collapse and /expand setting](https://mattermost.atlassian.net/browse/PLT-3212), is that what you're seeing?

Or if the message isn't being posted at all with the message attachments, can you confirm the message attachment JSON you are using is valid using something like this site: http://jsonlint.com/

**Comment by Rudloff** [comment]
The message isn't posted at all. I confirm the JSON is valid.

This works:
```json
{
	"text": "**[Nos 20 ans : on fait le bilan ! - Animafac](https:\/\/www.animafac.net\/actualites\/20-ans\/)**\nEn 2016, Animafac a f\u00eat\u00e9 ses 20 ans. Voil\u00e0 comment."
}
```

This does not work:
```json
{
	"attachments": [{
		"text": "En 2016, Animafac a f\u00eat\u00e9 ses 20 ans. Voil\u00e0 comment.",
		"fallback": "En 2016, Animafac a f\u00eat\u00e9 ses 20 ans. Voil\u00e0 comment.",
		"title": "Nos 20 ans : on fait le bilan ! - Animafac",
		"title_link": "https:\/\/www.animafac.net\/actualites\/20-ans\/"
	}]
}
```

**Comment by lfbrock** [comment]
Hi @Rudloff, sorry about that - it looks like message attachments are only working for incoming webhooks currently. 

I created a new ticket here for the issue: https://mattermost.atlassian.net/browse/PLT-3658

And also updated the [outgoing webhooks](http://docs.mattermost.com/developer/webhooks-outgoing.html) documentation to add it as a known issue.

Is there anyone from the community who would be interested in adding support for this?

**Comment by esethna** [comment]
Closing to track in JIRA. Please comment on the ticket there if anyone is interested in working on this!
