### ISSUE TITLE
Trigger outgoing webhook on URLs

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3574]
#### Summary
I can't add a rule that triggers an outgoing webhook on URLs.

#### Steps to reproduce
I have an outgoing webhook that needs to be triggered when an user posts only an URL.
I tried to add `http` as trigger.

#### Expected behavior
The hook is triggered when the post starts with `http`.

#### Observed behavior
The hook is not triggered.

#### Possible fixes
A workaround could be to have an option to enable outgoing webhooks on all public channels.

**Comment by jasonblais** [comment]
Thanks @Rudloff for the report! Sorry for the delay in responding here,

I believe there needs to be a space after the trigger word `http` -- can you try if posts starting with the word `http` trigger correctly?

Also, you can enable outgoing webhooks on all public channels by leaving the channel field blank. [Our documentation](http://docs.mattermost.com/developer/webhooks-outgoing.html#set-up-an-outgoing-webhook) has been updated to clarify this

**Comment by Rudloff** [comment]
Yes, it works if I post "http foo" but that won't cover my use case with URLs.

It seems I can't create an outgoing webhook on all public channels with no keyword, the interface forces me to choose either a keyword or a channel.

**Comment by jasonblais** [comment]
Thanks @Rudloff,

At the moment, the word needs to exactly match the 'trigger word' specified in the outgoing webhook, and they don't support a case where the word only contains or starts with the 'trigger word'.

If encourage you to contribute [this in the Feature Idea forum](https://www.mattermost.org/feature-ideas/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.  

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
And for your second point, that's correct. If you have a trigger word, then outgoing webhooks can be enabled on all public channels.

**Comment by Rudloff** [comment]
I will have a look at the code and try to submit a patch ☺
