### ISSUE TITLE
team admin can make system admin a member

### ISSUE THREAD

**Issue by prakashprabhakar** [mattermost/platform#3588]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
team admin can make system admin a member

#### Steps to reproduce
1) Login to mattermost as Team Admin
2) Try to change privilege of system admin to a member

#### Expected behavior
This should never be allowed. The option itself should be grayed out

#### Observed behavior
The team is allowed to make system admin a member.
Note: I did not do it, because there was only one sysadmin. But I received the option which ideally should have been restricted

#### Possible fixes

![selection_084](https://cloud.githubusercontent.com/assets/13349934/16838766/ae97fa68-49e8-11e6-9ec2-9719692b6761.png)

**Comment by jasonblais** [comment]
Thanks @prakashprabhakar for the report! 

We have [recently submitted a pull request](https://github.com/mattermost/platform/pull/3550) and this issue will be fixed in v3.3
