### ISSUE TITLE
[Important] Notification comes as a streak of line when having direct conversation

### ISSUE THREAD

**Issue by prakashprabhakar** [mattermost/platform#3589]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Notification comes as a streak of line when having direct conversation

#### Steps to reproduce
1) Login to application (Ubuntu - 64 Bit)
2) Try sending receiving a notification from a user (One to One conversation)

#### Expected behavior
A clear notification (toast) should be displayed on the right top corner of the screen

#### Observed behavior
A notification appears but as a streak of line. Pic attached.

**Note**: 
1) It works properly when on web 
2) Even on app the group notification are clear

#### Possible fixes
NA

![workspace 1_086](https://cloud.githubusercontent.com/assets/13349934/16839112/e602864c-49ea-11e6-9018-26350c7e91b5.png)

**Comment by jasonblais** [comment]
Thanks @prakashprabhakar for the report,

It sounds like this is not in fact a bug, but rather a feature request for Mattermost Desktop App (Ubuntu - 64 Bit) to add a notification on the top right corner of the screen.

May I have your help nominating your suggestion in our [Feature Idea forum](http://www.mattermost.org/feature-ideas/) so it can be discussed and upvoted? 

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by prakashprabhakar** [comment]
@jasonblais OK I will be more clear. Let's say Person A is sending a direct message to Person B (One  to one chat) and Person B is on the Ubuntu app, then he can just see a line sliding out from the right hand side of the screen.

But if the same Person B is on the web app and not on the Ubuntu app, then he receives a clear notification on the the right hand side of the screen.

Also what works perfectly are the notifications received if the person is on the group irrespective of whether he is on the app or on the web. So it's a bug.

**Comment by jasonblais** [comment]
Thanks again @prakashprabhakar!

Got it, so this only happens on messages posted in the direct message channels.

I'll check with our desktop community on this. Thanks again for filing the issue

**Comment by prakashprabhakar** [comment]
@jasonblais Yes That's correct. Thanks for the response.

**Comment by jasonblais** [comment]
Thanks again @prakashprabhakar for the report!

I have submitted a PR to add this as a known issue in the [desktop changelog](https://github.com/mattermost/desktop/pull/206)
