### ISSUE TITLE
Delay email notification

### ISSUE THREAD

**Issue by bspinner** [mattermost/platform#3590]
Currently email notifications are sent instantly on every new relevant message. That's really annoying if you're talking to someone via direct messages.

They should be delayed and send when relevant messages aren't read after x seconds/minutes only (maybe you should take into account whether a user is connected or not).

**Comment by jasonblais** [comment]
Thanks @bspinner for the report! 

We have an existing [feature idea forum post](https://mattermost.uservoice.com/forums/306457-general/suggestions/12903204-allow-email-batching-limiting) on this topic. 

If you'd like, you may add your feedback to the forum post and upvote the feature idea. 

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Thanks @bspinner again for the report,

Closing the issue for now - I encourage you to participate in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general/suggestions/12903204-allow-email-batching-limiting) discussion and upvoting the feature if you'd like.
