### ISSUE TITLE
javascript code style inconsistency

### ISSUE THREAD

**Issue by ralder** [mattermost/platform#361]
there is link in https://github.com/mattermost/platform/blob/master/STYLE-GUIDE.md#react-jsx to airbnb style guide jsx components and it proposes to use dobule quotes for jsx attributes of components and single quotes for all other JS https://github.com/airbnb/javascript/tree/master/react#quotes. But currently all PR's changes dobule to single quotes in thouse attributes

**Comment by crspeller** [comment]
Thanks for pointing this out. I will fix the inconsistency. We will stick with single quotes for everything. This is the easiest thing to do with ESLint.
