### ISSUE TITLE
distracting flickering in web UI messages pane when posting new messages

### ISSUE THREAD

**Issue by fjarlq** [mattermost/platform#3610]
#### Summary
When a user is entering new messages into the web UI, the messages pane flickers almost every time that a new message is posted into the messages pane, as the profile picture, username, and message timestamp are displayed for a split-second and then undisplayed.

#### Steps to reproduce
1. Connect to a Mattermost 3.2.0 server using Chrome 51.0.2704.106 on OS X 10.11.5.
2. Join a channel.
3. Post a series of new messages while observing the messages pane.

#### Expected behavior
I expect the new messages to appear in the messages pane without any flickering. The existing messages should scroll up, and my new message should be added at the bottom without anything else being displayed even for a split-second.

#### Observed behavior
In the messages pane, my profile picture, username, and the new message timestamp are displayed for a split-second, after which they are undisplayed, resulting in both a flicker and needless vertical movement of the text within the messages pane.

Realtime animated gif of the problem:
![mmbug2](https://cloud.githubusercontent.com/assets/441483/16899106/e4d0d2d0-4bb4-11e6-98ad-602216c8b3fe.gif)

Same gif animated at quarter-speed:
![mmbug2slomo](https://cloud.githubusercontent.com/assets/441483/16899108/f79f45ea-4bb4-11e6-95cc-676f4bb4c541.gif)

**Comment by lfbrock** [comment]
Thanks @fjarlq, I've filed a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-3682

If anyone is interested in working on this, please let us know.

**Comment by lfbrock** [comment]
Closing this issue and will track in Jira
