### ISSUE TITLE
Processing icon takes a long time to vanish

### ISSUE THREAD

**Issue by prakashprabhakar** [mattermost/platform#3622]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Processing icon takes a long time to vanish

#### Steps to reproduce
1) To address a particular person in the group use @<name>, enter the msg and send it.

#### Expected behavior
It should be immediately processed.

#### Observed behavior
It's not getting immediately processed. In fact if a plain text msg is sent after the above msg, the latter appears first as the first msg is still seen processing.

Refer the attached screenshot.

#### Possible fixes
![selection_110](https://cloud.githubusercontent.com/assets/13349934/16939179/ccb9bbb4-4d9c-11e6-98ba-6cce46f3c262.png)

**Comment by lfbrock** [comment]
Hi @prakashprabhakar, is this with the desktop app? Can you check if it also reproduces on a web browser? 

It seemed to send at around the same speed as other messages for me. 

Would you also be able to check the developer console to see if you're getting any errors?

**Comment by prakashprabhakar** [comment]
@lfbrock No it was not happening on the web, rather it was a problem with the desktop app.

Now after upgrading to server version 3.2.0 and app version 1.3.0 it's not reproducing.

Thanks for the help.

**Comment by lfbrock** [comment]
Okay thanks, glad to hear it's fixed!
