### ISSUE TITLE
Android app is entirely reloaded everytime

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3623]
#### Summary
Every time I open the Android app (3.0.6 on Android 5.1), the webview is entirely reloaded.

#### Steps to reproduce
1. Open the app
1. Go back to the homescreen
1. Touch app icon again

#### Expected behavior
It goes back to where I left the app. (This works perfectly if I use the [overview screen](https://developer.android.com/guide/components/recents.html) instead of the homescreen to get back to the app).

#### Observed behavior
I get the "Loading..." popup and the web content is reloaded.

**Comment by lfbrock** [comment]
Thanks @Rudloff, we have a ticket here to look into the issue: https://mattermost.atlassian.net/browse/PLT-3656

**Comment by Rudloff** [comment]
For some reason it seems to work better since the 3.2 update. The app is not reloaded everytime.

**Comment by lfbrock** [comment]
That's good, glad to hear it - I'll close this issue and we'll still investigate when someone takes a look at the Jira ticket.
