### ISSUE TITLE
[Important & Urgent] App Options not working on Ubuntu Linux

### ISSUE THREAD

**Issue by prakashprabhakar** [mattermost/platform#3626]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
App Options not working on Ubuntu Linux
Operating System: Ubuntu 14.04
App version: 1.3.0

#### Steps to reproduce

1) Select the below options and save the application
* Show icon on menu bar (Need to restart the application)
* Change team from Light to Dark.
* Leave app running in notification area when the window is closed (available on next restart)

2) Close and Re-open the application.

#### Expected behavior
1) Icon should be present in the menu bar
2) Theme should have changed.

#### Observed behavior
None of the above things happen. I can't notice the icons, theme is not changed.

2 other things are noticed:
a) From the Menu bar of Ubuntu, the application cannot be quit (Although there is an option. The user has to go to File --> Settings --> Exit to close the app.

b) While opening tthe applilcation from terminal I noticed the below error:

==================
prakashp@BLRSOFT-106:~/mattermost$ ./Mattermost 
{ Error: ENOENT: no such file or directory, open '/home/prakashp/.config/Mattermost/certificate.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:426:29)
    at new CertificateStore (/home/prakashp/mattermost/resources/app/main.js:3771:32)
    at Object.load (/home/prakashp/mattermost/resources/app/main.js:3801:13)
    at Object.<anonymous> (/home/prakashp/mattermost/resources/app/main.js:85:49)
    at __webpack_require__ (/home/prakashp/mattermost/resources/app/main.js:20:30)
    at __webpack_require__.app.app (/home/prakashp/mattermost/resources/app/main.js:40:18)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/prakashp/.config/Mattermost/certificate.json' }
==================

**Comment by lfbrock** [comment]
Hi @prakashprabhakar, just to confirm, this is with the new v1.3 desktop app running Mattermost v3.2? 

Does the theme issue repro on a browser for you, or only on the desktop app?

**Comment by jasonblais** [comment]
Thanks @prakashprabhakar for the report,

1) [libappindicator1 package is required on Ubuntu for the icon to show in the taskbar](https://github.com/mattermost/desktop/blob/master/CHANGELOG.md#linux)
2] Quitting the application from the icon currently minimizes the app, that is correct. I will add it as a known issue to the changelog.

For issues with changing themes, and error messages on the terminal, would I have your help creating a new issue in [our desktop repo](https://github.com/mattermost/desktop/issues), given they are specific to the desktop app?

**Comment by prakashprabhakar** [comment]
@lfbrock yes I have installed the Mattermost v3.2

**Comment by prakashprabhakar** [comment]
@jasonblais I have installed  libappindicator1 package. But I don't get the icons.

Also I will raise those issues on Desktop repo

**Comment by jasonblais** [comment]
Thanks @prakashprabhakar for reporting it in [the desktop repo](https://github.com/mattermost/desktop/issues/208). I'll close this issue and we can continue our conversation there.
