### ISSUE TITLE
Channel header edit box is cleared when a message is received

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3633]
#### Summary
When I try to edit a channel header and I receive a notification, the textarea I'm currently writing in is emptied. This is very annoying.

#### Steps to reproduce
1. Click on _Set Channel Header_.
1. Receive a notification

#### Expected behavior
Nothing special happens.

#### Observed behavior
The textarea is emptied.

**Comment by hmhealey** [comment]
Hi @Rudloff, what version of Mattermost are you on? This should be fixed in 3.2

**Comment by Rudloff** [comment]
I'm running 3.1, I didn't see there was a new release, I will try with 3.2.

**Comment by Rudloff** [comment]
You're right, this is fixed in 3.2. Sorry for wasting your time.
