### ISSUE TITLE
":D" should render ":smile:" instead of ":grinning:"

### ISSUE THREAD

**Issue by sn0w** [mattermost/platform#3640]
The `:D` shortcut produces a  `:smile:` (😄 )  in Slack (and Discord).
In Mattermost it produces a `:grinning:` (😀 ).

It's a little bug and maybe a design decision, but `:smile:` doesn't fit into a `:D` context most of the time.

If you're not going to replace the alias you should at least make it configurable.

**Comment by lfbrock** [comment]
Hi @sn0w, is this something you would be interested in making a pull request to fix?

**Comment by esethna** [comment]
Closing to track in [JIRA](https://mattermost.atlassian.net/browse/PLT-3742).
