### ISSUE TITLE
Link previews are not generated on supported sites (wikipedia, github,...)

### ISSUE THREAD

**Issue by raphael0202** [mattermost/platform#3650]
#### Summary
Link previews are not generated on supported sites (wikipedia, github,...)

#### Steps to reproduce
Using last version of Mattermost (3.2.0). Create several new messages on a public channel with the following content:
`https://en.wikipedia.org/wiki/ISO_8601` or
`https://github.com/leedo/noembed/commit/87fc1b3a439d9ccd724b331e32223cad289eb6a1`

#### Expected behavior
A preview of the link should be generated thanks to https://noembed.com/, as this pull request https://github.com/mattermost/platform/pull/1352 was merged into master

#### Observed behavior
No preview is generated.

**Comment by lfbrock** [comment]
Hi @raphael0202, can you go to Account Settings > Advanced > Preview Pre-release features, and check that "Show experimental previews of link content, when available" is enabled? 

The link previews for websites have some issues so they're not turned on by default. We have a ticket here to update how they work: https://mattermost.atlassian.net/browse/PLT-1835

**Comment by jasonblais** [comment]
Thanks again @raphael0202 for the report -- the link preview should appear after going to **Account Settings > Advanced > Preview Pre-release features**, and enabling "Show experimental previews of link content, when available".

Closing, given link previews aren't enabled by default as described above. 

However, if you find they don't work after enabling, please reopen the issue.

**Comment by raphael0202** [comment]
Thanks for your responses, enabling link previews in settings does the trick.

**Comment by marcocevoli** [comment]
I have "Show experimental previews of link content, when available" enabled but links (Wikipedia) are not shown. I only see an empty box under the link.

**Comment by jasonblais** [comment]
Thanks @marcocevoli, the current implementation supports websites that use Open Graph data.

I believe Wikipedia doesn't use it, which would be why the link preview isn't generated.

**Comment by marcocevoli** [comment]
Thanks, jasonblais. Then, it would make more sense that no box appeared, like with other links. This is what I get, instead: http://i.imgur.com/cyL4Ghv.png

**Comment by jasonblais** [comment]
Ah, that issue was fixed in Mattermost v3.7 and later. You can upgrade Mattermost to the latest version here: https://about.mattermost.com/download/

**Comment by gokceneraslan** [comment]
That's not working in my mmost instance (v4.2) and there is no experimental option about it either. Any comments?

**Comment by gokceneraslan** [comment]
Ah ok it needs to be enabled in System console as well.
