### ISSUE TITLE
Hashtag containing dash followed only by digits does not show up in search

### ISSUE THREAD

**Issue by gertmenke** [mattermost/platform#3657]
#### Summary
Adding a hashtag containing a dash followed only by digits to a post will turn the hashtag into a link, but clicking it does not show any search results. However, if there is a non-digit character, it does work.
Examples:
* #foo-123 _does not work_
* #foo-123x _works okay_
* #foo-x123 _works okay_
* #foo-123-bar _does not work_
* #foo-1x3-bar _works okay_

#### Steps to reproduce
Create post with hashtag "#foo-123"
Click on link

#### Expected behavior
Search should show all posts containing "#foo-123"

#### Observed behavior
"No results found. Try again?"

**Comment by gertmenke** [comment]
Might be related to https://mattermost.atlassian.net/browse/PLT-3699

**Comment by esethna** [comment]
Thanks @gertmenke, yes they are related. I've added a note to the ticket to look into dashes and underscores as well. Closing to track in [JIRA](https://mattermost.atlassian.net/browse/PLT-3699).
