### ISSUE TITLE
Large teams

### ISSUE THREAD

**Issue by thw0rted** [mattermost/platform#3664]
#### Summary
Large teams cause client-side performance problems when sending a direct message.

#### Steps to reproduce
This is on version 3.2.0, but it doesn't look like there's any plan to fix it in more-current releases.

1. Create a team with a very large number of members (1000+)
2. Under "DIRECT MESSAGES" in the menu, click "More..." to choose a user to message
3. Wait 10+ seconds as your browser loads the entire membership list then adds a corresponding number of elements to an enormous list

#### Expected behavior
Interface should cap the maximum number of records loaded at once.

#### Observed behavior
Loading the complete user list takes time that scales linearly with team size, and creates a similar burden on browser performance / memory usage.

#### Possible fixes
Paginate the team-member list or remove it and rely on autocomplete (search) for addressing team members.

**Comment by esethna** [comment]
Thanks for the report @thw0rted. Does this load time happen everytime you open the "More..." menu or just the first time? We had a [PR](https://github.com/mattermost/platform/pull/3485) go into v3.2 to not completely reload on every open.

**Comment by thw0rted** [comment]
I just ran a rough estimate, it was about 30 seconds total on the first try, then just over 10 seconds subsequently.  I think a lot of the time is just spent manipulating the DOM and waiting for hundreds and hundreds of elements to render.

I've seen libraries that dynamically load and unload elements from the DOM as you scroll, which would probably help, or maybe simple pagination when there's more than ~50 users.

**Comment by esethna** [comment]
Thanks for the info! We have a ticket [here](https://mattermost.atlassian.net/browse/PLT-2304) to add paging for improved performance. Closing this issue to track in JIRA.

**Comment by aliasaria** [comment]
I was unable to click the Atlassian link -- is there an an update to the status on this issue? Thanks so much!

**Comment by lfbrock** [comment]
@aliasaria sorry about that, the work has been done for this and is currently being tested. It should be in the next release.
