### ISSUE TITLE
Message syntax "Help" link location is not configurable

### ISSUE THREAD

**Issue by thw0rted** [mattermost/platform#3665]
#### Summary
The "Help" link under the message input box is hard-coded to point to `docs.mattermost.com`.

#### Steps to reproduce
1. Open any channel and find the "Write a message..." box
2. Look at the "Help" link just below, to the right.

#### Expected behavior
This link should point to a locally-hosted copy of the syntax documentation, or at least be configurable to point to other site-specific documentation.

#### Observed behavior
There are no configuration options to change where this link points.

#### Possible fixes
Ideally, allow installations of Mattermost to also host all user-facing documentation, then automatically direct links to the local copy.  At the very least, don't assume Internet-facing URLs will work when installations could be running on an isolated (corporate/lab) network.

**Comment by esethna** [comment]
Thanks for the report. We have a [ticket to track](https://mattermost.atlassian.net/browse/PLT-2345) this in JIRA. Closing this issue.

**Comment by thw0rted** [comment]
Thanks.  In case it comes up in the team discussion on JIRA, the instance I was using wasn't connected to the Internet so the link wouldn't work.  I'm not sure if this is a common case or not, but it'd be great if you could support it.
