### ISSUE TITLE
"Compact" layout totally ignores sizing

### ISSUE THREAD

**Issue by thw0rted** [mattermost/platform#3667]
#### Summary
All text is identically sized in "compact" layout

#### Steps to reproduce
1. Post some messages that use different font sizes, specifically different header levels (`### blah`, etc).  Throw some emoji in there, too.
2. Observe how these headers are differentiated from each other visually, and how they differ from plain bold text (`**bold**`, etc).
3. Switch to Compact Display under Account Settings --> Display
3. Observe how same messages now are indistinguishable both from each other, as well as from normal bolded text.

#### Expected behavior
Regardless of display setting, users should be able to tell heading text apart from non-heading text.  It should also be possible to cause emoji to be displayed at higher resolution than the default.

#### Observed behavior
It is not possible to change the displayed size of text or emoji using any available markup.  If the content poster is not using compact layout, they will have no idea that some users will lose this semantic information.  If the content poster is using compact layout, they may have no idea why their markup won't cause their content to get larger or smaller as expected.  Likewise, they may accidentally use markup that causes size changes; in this case their display will not show different sizes, but the size will vary for users with Standard layout.  This can be a particular problem for new or inexperienced users who are not intimately familiar with Markdown.

#### Possible fixes
Update the CSS for Compact layout to allow (slight) changes in text size based on heading levels.

**Comment by esethna** [comment]
Thanks. I've Q'd this to [talk about in UX design meeting](https://pre-release.mattermost.com/core/pl/q599k8fpm3did8ps4uhw4diedc). Will report back when we've discussed this?

**Comment by esethna** [comment]
Hi @thw0rted, we discussed this in UX meeting today. We agree that having a slight change in text size for headings makes sense. The corner case we'd need to think about is when you have heading markdown as the first line of a message. Here would be the cases:

1. If heading markdown is used in the first line of a message, bump it to it to a new line below the username.
2. If heading markdown is not used in the first line of a message, keep in the same line as the username (as done currently)

Would you be interested in submitting a PR for this?

**Comment by thw0rted** [comment]
Sorry to take so long getting back, I haven't had a chance to set up a dev environment since I'm moving right now.  I could look at it but it might be a month or so before I got around to it.  If somebody else has spare cycles to work on it, that would definitely be quicker.

**Comment by esethna** [comment]
Cool, there is a ticket [here](https://mattermost.atlassian.net/browse/PLT-3769). Please comment on it in JIRA if you decide to take this on. Thanks!
