### ISSUE TITLE
Migrating Data from Slack

### ISSUE THREAD

**Issue by itgrow-FilipeLopes** [mattermost/platform#3673]
#### Summary
Cannot import most of slack chat to Mattermost

#### Steps to reproduce

Create channel on slack 2.1.0 and have several users chat on it.
follow the [tutorial](https://docs.mattermost.com/help/settings/team-settings.html)

> 1. Generate a Slack “Export” file from Slack > Team Settings > Import/Export Data > Export > Start Export.
2. In Mattermost go to Team Settings > Import > Import from Slack. Team Administrator or System Administrator role is required to access this menu option.
3. Click Select file to upload Slack export file and click Import.

We did this twice, (with the same slack team, but different mattermost teams), and got different results in both.

#### Expected behavior
All channels and users should appear on Mattermost, as well as every chat entry.

#### Observed behavior

On the first try only one user messages were imported (the primary owner).

![image](https://cloud.githubusercontent.com/assets/20644543/17106867/d9cb01d6-5284-11e6-9dfb-fcf6d40d9197.png)

We then create a test channel on slack, a new team was created on Mattermost, and the process was repeated, but this time no messages were imported (only the channels as blank)

![image](https://cloud.githubusercontent.com/assets/20644543/17107397/ea723ac0-5286-11e6-9984-096ec670c74f.png)

**Comment by contradude** [comment]
![image](https://cloud.githubusercontent.com/assets/15931102/17110186/96a4db2c-5250-11e6-9686-79b68d8c4067.png)

I have also experienced issues importing from Slack into Mattermost 3.2.0. the import completes successfully but only about half of my users are imported. their posts are still there and the initial of the user's name is there but not their name. I've used multiple deployment methods (docker, native 14.04 ubuntu install) and the same issue occurs. I've also re-exported from slack several times to make sure that I did not have a corrupt export.

**Comment by jasonblais** [comment]
Thanks @itgrow-FilipeLopes and @contradude for the reports!

And very sorry for the long delay in response.

We do have some issues with Slack import, I will create a ticket for us to track. 

To help investigate and fixing the problem, could I have your help answering the following questions?

@itgrow-FilipeLopes 
1) Do any of the messages appear after a hard refresh? How about after logging out and then back in?
2) Do any of the messages appear if the users join the open channels?
3) Which database type is your server running (under **Main Menu > About Mattermost**)
4) Does the `MattermostImportSummary.txt` provide any useful feedback? For instance, does it tell users couldn't be added, or users couldn't be added to channels, etc.?
5) Are the two `MattermostImportSummary.txt` files different for your two imports?

@contradude: Similar questions for you
1) Which database type is your server running (under **Main Menu > About Mattermost**)
2) Does the `MattermostImportSummary.txt` provide any useful feedback? For instance, does it tell users couldn't be added, or users couldn't be added to channels, etc.?

**Comment by contradude** [comment]
I was able to go back to 3.0.3 and import (still received error) and it successfully imported all of the messages. I then performed an upgrade install to 3.2.0. to answer your questions:

1). mysql 5.6.31
2). the import files are attached but they don't seem to give me anything of value.
[MattermostImportSummary (1).txt](https://github.com/mattermost/platform/files/400146/MattermostImportSummary.1.txt)
[MattermostImportSummary.txt](https://github.com/mattermost/platform/files/400145/MattermostImportSummary.txt)

**Comment by jasonblais** [comment]
Perfect thanks @contradude!

I see, so this is a problem potentially introduced with v3.2.

Wondering if you'd have access to test it on Chrome as well to see if you experience the same problem? That would pin-point if the problem is browser-specific somehow.

**Comment by contradude** [comment]
I had tried to upload in IE and Chrome with the same outcome.

**Comment by jasonblais** [comment]
Thanks @contradude!

I have filed a ticket for it [in Jira to track](https://mattermost.atlassian.net/browse/PLT-3803), with a link to this thread as well

Thanks @contradude and @itgrow-FilipeLopes for all the feedback above
