### ISSUE TITLE
Display > Link Previews > incorrect behavior

### ISSUE THREAD

**Issue by jarbro** [mattermost/platform#3690]
#### Summary
Turning link preview to off - causes all link to auto load.  Enabling collapses all link previews. 

#### Steps to reproduce
Go to user settings > Display > Link Previews and toggle preview on and off
Tested in Chrome and Firefox with same result.

#### Expected behavior
With Link Previews On you should see the expanded link automatically, however this does not happen.  You have to disable link preview in order for this to work.

#### Observed behavior
![chrome_2016-07-27_14-56-08](https://cloud.githubusercontent.com/assets/3271673/17188310/769a8b86-540a-11e6-85fd-aa15d6dccb28.png)
![chrome_2016-07-27_14-57-08](https://cloud.githubusercontent.com/assets/3271673/17188311/76a4553a-540a-11e6-8ebd-aff806935a53.png)

#### System Details
Ubuntu 16.04
GitLab SSO only
Mattermost v 3.2.0
Postgres

#### Possible fixes
Turn off link preview

**Comment by esethna** [comment]
Thanks for the report. [This issue should be fixed](https://mattermost.atlassian.net/browse/PLT-3644) in v3.3 expected to release August 16.
