### ISSUE TITLE
Cannot type backtick anymore after updating from 2.x to 3.2

### ISSUE THREAD

**Issue by ghidosoft** [mattermost/platform#3696]
#### Summary
After updating from 2.x to 3.2 I cannot type the backtick ` anymore.

#### Steps to reproduce
I'm using Mattermost 3.2 and using Keyboard layout 142.
Open a chat.
Type the backtick (altgr-ù for this keyboard layout) .

#### Expected behavior
A backtick ` should be typed.

#### Observed behavior
I see instead the Keyboard Shortcuts panel and the backtick does not appear.

**Comment by thundo** [comment]
I can confirm this unexpected behaviour in 3.1 too.

**Comment by jasonblais** [comment]
Thanks @ghidosoft and @thundo for the report!

And sorry for the delayed response here -- would anyone be interested in submitting a fix for it?

**Comment by jasonblais** [comment]
Ticket added to [Jira for us to track](https://mattermost.atlassian.net/browse/PLT-3826).

If anyone would like to help submit a fix, let us know!
