### ISSUE TITLE
Custom emoji loading issue

### ISSUE THREAD

**Issue by Happy-Ferret** [mattermost/platform#3700]
#### Summary
Upon login, custom emojis are not loaded immediately.

#### Steps to reproduce
1. Log into a Mattermost instance/group with a custom emoji (alternatively, add one beforehand).
2. Type :<nameOfCustomEmoji>
3. Custom emoji is not listed and existing custom emojis are rendered as text only representation.
4. Upon navigating to the "Add Custom Emoji" submenu and back, all custom emoji are rendered properly again.

#### Expected behavior
Upon login, all custom emoji should be loaded and added to the emoji shortcuts.

#### Observed behavior
Custom emojis are only being displayed after navigating to the "Add Custom Emoji" submenu first.

**Comment by cgandelli** [comment]
Same issue here. Icons are rendered properly again in chat and in list even after a page refresh, without going back and forth to the custom emoji page.

**Comment by jasonblais** [comment]
Thanks @Happy-Ferret and @cgandelli for the report,

Does this occur on the Mattermost Desktop App (if so, which version and operating system)? Or have you noticed this also on the web browser?

There is an issue filed in the `desktop` repo to help investigate the problem https://github.com/mattermost/desktop/issues/209

**Comment by Happy-Ferret** [comment]
Haven't gotten the chance to try this inside the desktop client. As I'm on vacation now, I won't be able to test the client but it definitely occurred in the browser version for me.

**Comment by jasonblais** [comment]
Thanks for the reply @Happy-Ferret! 

We were only aware of this happening on the client thus far, so thank you for the report. Can you help answer the following questions:
  1) Which browser version are you using?
  2) Which database type is used in your Mattermost instance (from Main Menu > About Mattermost) 
  3) Does this occur each time you logout, and log back in?

@cgandelli If you'd like to share similar information, that would be great

**Comment by Happy-Ferret** [comment]
Hi there, @jasonblais.

No problem. Always happy to help. Particularly as Mattermost is becoming an integral part of my employer's workflow.

To answer your questions:

**``1) Which browser version are you using?``**`

Google Chrome 51

**``2) Which database type is used in your Mattermost instance (from Main Menu > About Mattermost)``**

PostgreSQL

**``3) Does this occur each time you logout, and log back in?``**

I just retried it. It actually doesn't happen on a login/logout but rather it happens whenever I access a Mattermost group from within the main menu (the "group picker" that is normally show after logging in). 

If I access the group directly (i e via a group link), all emojis are properly instantiated.

**Comment by cgandelli** [comment]
Sure @jasonblais, I'll be back on monday to check all the version numbers you're asking. For now, however, I'm pretty sure the problem is very the same of @Happy-Ferret, I'm using Chrome (not the desktop client) and I get the issue coming from the Group menu after login, then after the page reload (so accessing the Group directly) all is ok.

**Comment by Happy-Ferret** [comment]
@cgandelli 

Strangely enough, it also works if you log out and use the group link to log in and access the page directly.
The issue must be somewhere in that first page (the one where you choose a group).

**Comment by cgandelli** [comment]
@jasonblais I'm using Google Chrome 52 and Postgres

**Comment by jasonblais** [comment]
Thanks again @Happy-Ferret and @cgandelli for the report!

I've been trying to reproduce the issue on Chrome without success (I was able to repro it sometimes on the client). 

I think I might not have the correct repro steps - I've included them below, would you be able to help update?

1. Log into a Mattermost server with a custom emoji and enter a team.
2. Access another team from the **Main Menu**
3. Type `:` and observe that custom emoji is not listed and existing custom emojis are rendered as text only representation.
4. Upon navigating to the "Add Custom Emoji" submenu and back, all custom emoji are rendered properly again.

What is the 'group menu after login' you're referring to? The team selection page attached below?

![image](https://cloud.githubusercontent.com/assets/13119842/17318009/03e8ed08-5851-11e6-9af2-0463107b318f.png)

**Comment by Happy-Ferret** [comment]
Hi there, @jasonblais 
Yes. That's the page I was referring to.

No need to enter another team. The error should occur on the first team already.

**Comment by jasonblais** [comment]
I'm unfortunately having trouble reproducing this issue consistently, but I will create a ticket for us to investigate. It did seem to appear at one point, and we have heard a couple of other reports with a similar issue.

I will also remove the second step from these repro steps.

Thanks both @Happy-Ferret and @cgandelli for the information here, much appreciated!

**Comment by jasonblais** [comment]
Added a ticket in [Jira to track](https://mattermost.atlassian.net/browse/PLT-3805), thanks again @Happy-Ferret and @cgandelli for the reports!

**Comment by Nokel81** [comment]
I don't know if this is still relevant but this is still happening on the macOS desktop version with the same steps to reproduce and "fix"

**Comment by hmhealey** [comment]
Hi @Nokel81,

What versions of the Mattermost server are you using? This issue should've been fixed with the 3.4 release.
