### ISSUE TITLE
[Important] File Size limit is increased, but can't upload

### ISSUE THREAD

**Issue by prakashprabhakar** [mattermost/platform#3701]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
[Important] File Size limit is increased, but can't upload

Mattermost Server: 3.2.0

#### Steps to reproduce
1) Increase the default file size from 50 to 100.
2) Re-login and try to upload a file of size greater than 50 MB.

#### Expected behavior
The file should be uploaded successfully

#### Observed behavior
The server throws an error as "We received an unexpected status code from the server. (413)"

**Comment by IshwarKanse** [comment]
@prakashprabhakar I think you'll also need to set client_max_body_size 100M; in your nginx conf.

**Comment by esethna** [comment]
Thanks @IshwarKanse! @prakashprabhaka, can you confirm if this solved your issue? If so, we should update the documentation on this feature so others don't hit the same issue.

**Comment by prakashprabhakar** [comment]
@IshwarKanse @esethna Thanks ... It worked...
