### ISSUE TITLE
Make close icons text-shadow color dependent on theme settings

### ISSUE THREAD

**Issue by phrix32** [mattermost/platform#3717]
#### Summary
The text shadow of close icon, stays white (#fff) regardless of icon color. It should change corresponding to chosen "Sidebar Header Text" or one should be able to change its color in a custom theme. Actually it looks really ugly if one decides on a dark "Sidebar Header Text" and therefore icon color, due to the white shadow around a dark colored icon.

#### Steps to reproduce
1. Open "Account Settings"->"Display"->"Theme"
2. Select "Custom Theme"
3. Open up "Sidebar Styles"
4. Enter dark color code (e.g. #000) into "Sidebar Header Text"

#### Expected behavior
The text shadow of close icon should be configurable or change corresponding to chosen "Sidebar Header Text"

#### Observed behavior
The close icons text shadow stays white.

#### Possible fixes
https://github.com/mattermost/platform/pull/391

**Comment by jasonblais** [comment]
Hey @phrix32, thanks for the report! We discussed this in the UX team and removing the shadow from the close icon seems the best option here.

Would you be interested in submitting a fix for it? Would be a good opportunity for a first contribution.

**Comment by jasonblais** [comment]
I've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3838) to track the issue -- if anyone in the community would like to work on it, please let us know 
