### ISSUE TITLE
A way to make the primary account can access all data related with non-primary acounts

### ISSUE THREAD

**Issue by xiaodot** [mattermost/platform#3726]
#### Summary
How to use the primary account to access all data related with non-primary accounts.

#### Detailed description
When upgrade from v2.2 to v3.0, we meet a big trouble. Since we login to Mattermost only with Gitlab SSO, we cannot use non-primary accounts. In this situation, we actually don't need to reserve those non-primary accounts, but rather to access their data with the primary account. 

#### Our solution
Maybe, we can solve this problem by simply modifying the database. For example, if we want to access a private channel which is joined by some non-primary account, we can replace `<non-primary-account>.Id` with `<primary-account>.Id` in table `ChannelMembers`.

#### Question
Is there any side effects if we modify the database in the way above?

**Comment by jasonblais** [comment]
Closing the issue for now - @xiaodot if you have further questions, please let us know at the [Troubleshooting Forum](http://www.mattermost.org/troubleshoot/)
