### ISSUE TITLE
GitLab SSO with SAML incorrectly opens new browser window on Android

### ISSUE THREAD

**Issue by gillespiec** [mattermost/platform#3733]
The behavior documented here does not appear to exist on desktop platforms or iOS. When logging in to Mattermost using GitLab SSO on a GitLab instance federated to an ADFS SAML 2.0 IDp, Mattermost correctly redirects to GitLab. Subsequent redirects to the SAML IDp are directed to a new browser window where successful authentication to the IDp results in an open GitLab session in the browser and no Mattermost session in the client.

I'm using the current (3.2) release of the Android client connecting to Mattermost Team Edition 3.2. The behavior that I expect is like that of the desktop client, where the IDp logon form is shown within the Mattermost client window. Opening a browser isn't problematic so long as it leads to successful establishment of a Mattermost session.

I suspect that additional overrides such as those for gitlab itself, around line 198 of
>> android/app/src/main/java/com/mattermost/mattermost/MainActivity.java

would eliminate the call to an external browser, but I am unsure if that will fully resolve the logon issue.

**Comment by jasonblais** [comment]
Thanks for the report @gillespiec 

Using GitLab SSO to connect to SAML login may not work as it requires multiple redirects on login, which is not supported.

If you would like to add it as a feature request in [our Feature Idea forum](https://mattermost.uservoice.com/forums/306457-general), I encourage you to do so.

This way it can be discussed, upvoted and prioritized for a review.
