### ISSUE TITLE
Specific hyperlink in post caused clients to hang

### ISSUE THREAD

**Issue by grubbins** [mattermost/platform#3745]
#### Summary
Posting a specific hyperlink in a message in a channel causes the client to hang.

#### Steps to reproduce
Using mattermost 3.1.0, and a Chrome browser client or the desktop client 1.2.1 on OSX:
 + post the hyperlink below
 + channel will hang with 100% CPU usage
 + any other user who tries to browse that channel will experience the same

Normal service can be restored by:
 + manually marking the post as deleted in the database
 + full refresh in the client

Users using Safari seem unaffected.

The offending link:

`https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createTempDirectory(java.lang.String,%20java.nio.file.attribute.FileAttribute...)`

**Comment by grubbins** [comment]
Just upgraded to 3.2.0 and it appears to be fixed. Users are still affected until they do a full refresh of their client.

**Comment by hmhealey** [comment]
Thanks for the report. Good to know it's already fixed by the changes made in 3.2.

Also, I've edited the bad URL out of your post just because it could be used for a DOS attack, but I've kept track of it internally so we can make sure this doesn't happen again
