### ISSUE TITLE
Updating to 3.3.0 RC 1 requires cache purge in native apps

### ISSUE THREAD

**Issue by johnjamesjacoby** [mattermost/platform#3749]
#### Summary
Updating to 3.3.0 RC1 causes native apps to stop working.

#### Steps to reproduce
* Install Mattermost 3.2.0
* Install native app and point it to your Mattermost install
* Confirm that everything is working
* Update to Mattermost 3.3.0
* Reboot server/restart Mattermost/Do whatever you need to do
* Native apps will be in some type of broken state (white screen, partial assets, etc...)

#### Expected behavior
Existing native apps to work after update

#### Observed behavior
I'm seeing lots of these entries in the `mattermost.log` file:

```
/error:CheckBrowserCompatability code=500 rid=8oa8pn43p3dwbp3k4cfo5qtywr uid= ip=%%%%, %%%% Your current browser is not supported, please upgrade to one of the following browsers: Google Chrome 21 or higher, Internet Explorer 11 or higher, FireFox 14 or higher, Safari 9 or higher [details: ]
```

#### Possible fixes
There might be 2 issues here:
* Version checks for Safari 9 vs 10 might be failing?
* Mattermost should announce to native apps that new assets exist, to empty local storage

**Comment by johnjamesjacoby** [comment]
Android screenshot, to confirm version:
![screenshot_2016-08-05-11-13-58](https://cloud.githubusercontent.com/assets/88951/17445889/68794a7a-5b0c-11e6-9b5a-8a7ba9ba5caa.jpg)

Safari 10 screenshot (for macOS app):
<img width="396" alt="screen shot 2016-08-05 at 13 00 33" src="https://cloud.githubusercontent.com/assets/88951/17445935/9e63a5e0-5b0c-11e6-8506-a70f50ff7ecc.png">

**Comment by johnjamesjacoby** [comment]
Confirmed with @cgsmith that reinstalling the Android native application made it work again.

**Comment by cgsmith** [comment]
It is working fine for me now.  I'd like to request a feature to handle the error so at least it is not a white screen.

**Comment by jasonblais** [comment]
Thank you for the report @johnjamesjacoby, and for your feedback @cgsmith! 

I've created a ticket for us to track the issue in Jira: https://mattermost.atlassian.net/browse/PLT-3839

Our [desktop community has been working on re-validating cache upon load to prevent this issue in the future](https://github.com/mattermost/desktop/pull/219). If you'd like, you can [download the test version for Mac](https://511-43964563-gh.circle-artifacts.com/0//tmp/circle-artifacts.MnNx76o/mattermost-desktop-osx.tar.gz) to see if the issue reproduces with the changes.

**Comment by cgsmith** [comment]
@jasonblais can you also note this down for the developers? It seems like the following might indicate a high priority on the issue.

For Android and Linux desktop (Ubuntu 16.04.1 LTS xenial - MatterMost Desktop 1.2.1) the app is pretty unresponsive. I cleared the cache and reloaded on the desktop application. Reloading the page is the only way to get new messages to come through from team members.

On the phone, I get push notifications with direct messages, but I do not see them come through on the phone. I have to reload the page in order to see it as well. v3.2 worked much better and we might move back to it if possible.

Seems like the cache issues or other issues are very broken in this release.

Anything I can do for testing or to help troubleshooting on your end?

**Comment by cgsmith** [comment]
@jasonblais perhaps this is related to socket rules? Here are console:

![imgur-2016_08_08-15 51 08](https://cloud.githubusercontent.com/assets/570018/17495778/014c7e28-5d80-11e6-8f04-59ab3f13656b.png)

This could be a red herring as well :/

**Comment by johnjamesjacoby** [comment]
In the process of diff'ing the `config.json' I somehow omitted/removed the `SiteURL` setting. I'm not sure if that would cause all of this, but my guess is Mattermost not knowing what it's own URL is will have all sorts of strange consequences.

Also probably unhelpful, after updating to RC2, I think everything else is working OK after a cache purge & refresh.

**Comment by johnjamesjacoby** [comment]
I just saw #3764 and now I don't know what is real life anymore. ¯\_(ツ)_/¯

**Comment by enahum** [comment]
This issue may be related, so I encourage you to wait a couple of days until RC3 is cut and then you can test it back and post your findings :)

**Comment by jasonblais** [comment]
Thanks again for the report @johnjamesjacoby and  @cgsmith ! 

[We just cut RC3](https://github.com/mattermost/platform/issues/3702#issuecomment-238720045) where this issue should be fixed.

Please let us know if the issue still occurs?

**Comment by johnjamesjacoby** [comment]
Thanks @jasonblais. I'll try RC3 and report back my findings either way.

**Comment by jasonblais** [comment]
Quick update @johnjamesjacoby , we're about to cut RC5, which should fix the problem. I'll give an update once it's been done.

Thanks again for the report!

**Comment by jasonblais** [comment]
RC5 has been cut -- feel free to let us know if you notice anything.

A huge thanks to you and @cgsmith for reporting the issue!

**Comment by johnjamesjacoby** [comment]
Thanks @jasonblais. No issues with either 3 or 4. I'll report back if 5 gives us any grief.

**Comment by cgsmith** [comment]
This is what open source is for! Thanks for making a great product!

**Comment by johnjamesjacoby** [comment]
RC5 humming along A-OK.

**Comment by jasonblais** [comment]
Great to hear! 

Thanks @johnjamesjacoby and @cgsmith for making a difference in v3.3! Love it

**Comment by johnjamesjacoby** [comment]
Happy to, @jasonblais! We're just getting started. 💜
