### ISSUE TITLE
Incorrect label text for "Add Slash Command".

### ISSUE THREAD

**Issue by kaakaa** [mattermost/platform#3754]
#### Summary
`Response Icon` labe textl displayed in "Add Slash Command" menu is incorrect.
(Relate to [Mattermost v3\.3\.0\-rc1 · Issue \#3702 · mattermost/platform](https://github.com/mattermost/platform/issues/3702))

#### Steps to reproduce
MainMenu > Integrations > Slash Commands > Add Slash Command

#### Expected behavior
The second `Response Icon` should be `Autocomplete`.

#### Observed behavior
![mattermost_3 3rc1_bug](https://cloud.githubusercontent.com/assets/20734695/17461008/2335bf9a-5cb8-11e6-85a7-b9bbdea50971.png)

#### Possible fixes
[platform/add\_command\.jsx at ea027c8de44d44b6ac4e66ab802e675d315b0be5 · mattermost/platform](https://github.com/mattermost/platform/blob/ea027c8de44d44b6ac4e66ab802e675d315b0be5/webapp/components/integrations/components/add_command.jsx#L554)

I think that the bellow code is correct.

```
                                <FormattedMessage
                                    id='add_command.autocomplete'
                                    defaultMessage='Autocomplete'
                                />
```

**Comment by enahum** [comment]
Thanks for reporting this, I have submitted a PR with the fix.

I'm going to close this, if you would like to keep track on the issue please follow the PR
