### ISSUE TITLE
Encoding issue in email titles

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3767]
When using the French locale, dates are not displayed correctly in email titles:
![capture d ecran_2016-08-09_17-06-17](https://cloud.githubusercontent.com/assets/840125/17521430/9a8addfe-5e53-11e6-8308-9c28f42b5213.png)
(It should be "9 Août 2016" at the end.)

The same date is displayed correctly in the email's body.

#### Summary
French dates are not displayed correctly in email titles

#### Steps to reproduce
1. Use the French locale.
1. Receive an email notification.

#### Expected behavior
The date should be displayed correctly.

#### Observed behavior
Mojibake is displayed instead of diacritics in the date.
This seem specific to the date, other diacritics are displayed correctly.

**Comment by hmhealey** [comment]
Hi @Rudloff,

Thanks for the report. This has actually been fixed by another community member for our upcoming 3.3 release that you'll be able to get next week.
