### ISSUE TITLE
can't search certain chinese words

### ISSUE THREAD

**Issue by helphi** [mattermost/platform#3775]
#### Summary
can't search certain chinese words.

#### Steps to reproduce
version3.2.0, someone send a messsage "具体情况就需要分析了，之前抓的严，大家都会去执行，我就看了下近期的大版本，执行的少" in a channel, and when i search with "具体情况" return no result.

#### Observed behavior

![image](https://cloud.githubusercontent.com/assets/6457416/17538405/a523512c-5ed7-11e6-9c7f-e08284cdc374.png)

**Comment by jasonblais** [comment]
Thanks for the report @helphi! 

Please see [our documentation for supporting Chinese, Korean & Japanese search on Mattermost](https://docs.mattermost.com/install/i18n.html)
