### ISSUE TITLE
Error then run “make test”

### ISSUE THREAD

**Issue by nguyenalm** [mattermost/platform#3791]
exit status 2
FAIL    github.com/mattermost/platform/api      440.065s
Makefile:157: recipe for target 'test-server' failed
make: *** [test-server] Error 1

docker version
Client:
Version: 1.12.0
API version: 1.24
Go version: go1.6.3
Git commit: 8eab29e
Built: Thu Jul 28 22:11:10 2016
OS/Arch: linux/amd64

go version
go version go1.6.2 linux/amd64
Log
https://www.dropbox.com/s/8b7ou8x01jgknif/mattermost.log?dl=0

Please help me !

**Comment by lfbrock** [comment]
This issue is being tracked here: http://forum.mattermost.org/t/error-then-run-make-test/2050/5
