### ISSUE TITLE
RHS "Recent mentions" incorrectly returns results for (at)all

### ISSUE THREAD

**Issue by shieldsjared** [mattermost/platform#3810]
#### Summary
After selecting "recent mentions", messages are returned that include the word "all" instead of the mention "@all".

#### Steps to reproduce
Reproduced by selecting "Recent Mentions" on the main menu of the demo instance of v3.3.0 at pre-release.mattermost.org.

#### Expected behavior
Messages are returned that match the search keywords/criteria provided. In the case of "recent mentions", the keywords are "{username} @{username} @all". Any message including these terms mentioned should be included.

#### Observed behavior
The search returns the expected results as well as any message including the word "all".
![image](https://cloud.githubusercontent.com/assets/600643/17682934/f9e06e68-631c-11e6-96b1-8c6249728b5d.png)

I actually searched for any term prefixed with @ to see if it would return only mentions, but it appears the @ is being ignored entirely....if this is the intended behavior, then it degrades the quality of the "recent mentions" feature by relying on "@all".  So I'm not entirely sure what it should and shouldn't do, but something feels amiss. Worth discussing at least?

**Comment by lfbrock** [comment]
@lindy65, can you see if this repros for you? I don't seem to have `@all` in my recent mentions list, I don't think it should be there.  

You're correct about the "@" being ignored, right now it just does a normal search and I think that ignores the `@`.  Search is something we're going to look at improving in the future, right now there are a couple issues like this because it's just doing a simple database search.

**Comment by shieldsjared** [comment]
@lfbrock Interesting, now that I'm at a desktop - I tried it through the windows desktop-client, and it works as expected (and also doesn't include @all).  The report was (as seen above) from IOS/Safari.  I checked this morning and it appears to be happening from both chrome and safari on my mobile device.  Sounds like this is mobile specific.

**Comment by shieldsjared** [comment]
OK, I reviewed the logic and it looks like the `channel_header.jsx` component which is seen while in a large media format and the 'sidebar_right_menu.jsx` which is seen while in a smaller media format have varied implementations of what happens when you select "Recent Mentions".  I've copied the excerpts below convenience:

File: [platform / webapp / components / sidebar_right_menu.jsx](https://github.com/mattermost/platform/blob/0184d6059bb1943fb74bf33d1d200a423c5bf5e6/webapp/components/sidebar_right_menu.jsx)
```` typescript
    searchMentions(e) {
        e.preventDefault();

        const user = this.state.currentUser;

        let terms = '';
        if (user.notify_props && user.notify_props.mention_keys) {
            const termKeys = UserStore.getMentionKeys(user.id);

            if (user.notify_props.all === 'true' && termKeys.indexOf('@all') !== -1) {
                termKeys.splice(termKeys.indexOf('@all'), 1);
            }

            if (user.notify_props.channel === 'true' && termKeys.indexOf('@channel') !== -1) {
                termKeys.splice(termKeys.indexOf('@channel'), 1);
            }
            terms = termKeys.join(' ');
        }

        this.hideSidebars();

        AppDispatcher.handleServerAction({
            type: ActionTypes.RECEIVED_SEARCH_TERM,
            term: terms,
            do_search: true,
            is_mention_search: true
        });
    }
````

File: [platform / webapp / components / channel_header.jsx ](https://github.com/mattermost/platform/blob/415145d62fd5195fc03759b5b4ed42c255529d7b/webapp/components/channel_header.jsx)
```` typescript
    searchMentions(e) {
        e.preventDefault();

        const user = this.state.currentUser;

        let terms = '';
        if (user.notify_props && user.notify_props.mention_keys) {
            const termKeys = UserStore.getMentionKeys(user.id);

            if (termKeys.indexOf('@channel') !== -1) {
                termKeys[termKeys.indexOf('@channel')] = '';
            }

            if (termKeys.indexOf('@all') !== -1) {
                termKeys[termKeys.indexOf('@all')] = '';
            }

            terms = termKeys.join(' ');
        }

        AppDispatcher.handleServerAction({
            type: ActionTypes.RECEIVED_SEARCH_TERM,
            term: terms,
            do_search: true,
            is_mention_search: true
        });
    }
````
The key difference is that the sidebar implementation is _adding_ the @channel and @all terms to the search if you have selected to be notified on those; while the channel header implementation is actually _removing_ them from the search terms.

**Comment by shieldsjared** [comment]
Issue originally addressed on channel_header.jsx through PR #3497

**Comment by lfbrock** [comment]
Thanks @shieldsjared for tracking that down, I've opened a ticket here on the issue: https://mattermost.atlassian.net/browse/PLT-3941

If you're interested in working on a fix, please feel free!

**Comment by jasonblais** [comment]
Thanks @shieldsjared for starting the work on this!

Please let us know if you have any questions along the way,
