### ISSUE TITLE
Can't send message without clicking on the button in mobile view

### ISSUE THREAD

**Issue by Juburin** [mattermost/platform#3816]
Usually I have the app open in a part of my screen and therefore see the mobile view.
Since the last update I can't send message with Enter, or CTRL + Enter.
I understand if the changes where an optimization for the mobile apps, but it would be great if at least CTRL + Enter worked.

**Comment by lfbrock** [comment]
Hi @Juburin, is this something you would be interested in submitting a pull request for?

**Comment by gelim** [comment]
+1
This is a regression from 3.2.0. Behavior changed by applying security update 3.3.0.

**Comment by yurikhan** [comment]
+1 It’s a regression, please revert the change that caused it.

Mobile users cannot solve their mobile problem by checking the “Send messages on Ctrl + Enter” in their profile settings. Meanwhile, we desktop users can’t send messages at all (except by reaching for the mouse).

**Comment by yurikhan** [comment]
As a stopgap measure, the following Greasemonkey script helps:

```js
// ==UserScript==
// @name        Mattermost: Send messages on Enter
// @namespace   http://yurikhan.github.io/
// @include     **customize according to your setup**
// @version     1
// @grant       none
// ==/UserScript==

document.body.addEventListener('keydown', function (event) {
  if (event.shiftKey || event.ctrlKey || event.altKey
      || event.target.id !== 'post_textbox'
      || event.keyCode != 13)
  { return; }
  document.querySelector('.send-button').click();
  event.stopPropagation();
  event.preventDefault();
}, true);
```

**Comment by lfbrock** [comment]
This is fixed on master and will be in the next release (September 16)

**Comment by Juburin** [comment]
We updated today to 3.3.0 and the problem still exists.

**Comment by lfbrock** [comment]
@Juburin, sorry I think something changed before the final release was cut - in v3.4, it should work if you turn on Account Settings > Advanced Settings > Send Messages on Ctrl + Enter. 

Ticket here to fix it for "Enter" as well https://mattermost.atlassian.net/browse/PLT-4158
