### ISSUE TITLE
Mattermost Client Package for RDS (Remote Desktop Service)

### ISSUE THREAD

**Issue by schoolph** [mattermost/platform#3851]
Hi,

#### Summary
Unable to publish Mattermost application on VDI infrastructure. ( VMware Horizon 7) (RDS)

#### Steps to reproduce
Version: Mattermost Team Edition Server v3.3.0 
Client: Application installed on Windows 7 and Server 2008 R2 Server

We noticed that the application doesn't get installed in Program Files Folder once it's loaded in Windows OS. 

VDI Platform is not able to share the application to other VDI users and failed to publish it as an application

#### Expected behavior
Mattermost application can be ran as published Apps from launcher of horizon.

#### Observed behavior
VDI Platform is not able to share the application to other VDI users and failed to publish it as an application

#### Possible fixes
have mattermost be compatible with RDS deployment. (Windows Platform)

Regards,
schoolph

**Comment by esethna** [comment]
Thanks! This is something we currently do not support, I'd encourage you to [contribute a feature idea](https://www.mattermost.org/feature-ideas/) so others can discuss and up vote.
