### ISSUE TITLE
Username in outgoing webhook payload is ignored

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3859]
#### Summary
Mattermost 3.3.0 ignores the `username` parameter in outgoing webhooks payloads.

#### Steps to reproduce
Create a webhook that returns this simple playload:
```json
{"text":"**[Example Domain](http:\/\/example.com)**","username":"test"}
```
(The test username does exist.)

#### Expected behavior
The message is posted by the test username.

#### Observed behavior
The message is posted by the user who created the webhook.

**Comment by lfbrock** [comment]
Hi @Rudloff - can you confirm that your Mattermost instance is set to [allow webhooks to override usernames](https://docs.mattermost.com/administration/config-settings.html#enable-webhooks-and-slash-commands-to-override-usernames)? Is it working properly for incoming webhooks?

**Comment by Rudloff** [comment]
Yes, EnablePostUsernameOverride is set to true.
I don't have any incoming webhook, si I can't test them.

**Comment by Rudloff** [comment]
Sorry, it seems I forgot to restart Mattermost after I changed the setting.
It does work now.
