### ISSUE TITLE
Autologin via oauth

### ISSUE THREAD

**Issue by niedakh** [mattermost/platform#3860]
Hello,

I'm implementing an oauth plugin for Mattermost and I'm having trouble setting up autologon. If I click the button - login works, but what I want is to have no login screen at all.

I'm trying: 
```
diff --git a/webapp/components/root.jsx b/webapp/components/root.jsx
index 9bb7d29..b261b5b 100644
--- a/webapp/components/root.jsx
+++ b/webapp/components/root.jsx
@@ -48,11 +48,11 @@ export default class Root extends React.Component {
     redirectIfNecessary(props) {
         if (props.location.pathname === '/') {
             if (UserStore.getNoAccounts()) {
-                browserHistory.push('/signup_user_complete');
+                browserHistory.push('/api/v3/oauth/engine/signup');
             } else if (UserStore.getCurrentUser()) {
                 browserHistory.push('/select_team');
             } else {
-                browserHistory.push('/login');
+                browserHistory.push('/api/v3/oauth/engine/login');
             }
         }
     }
```

But every so often - and I can't nail it down to a reason - I'm getting redirected to: http://HOST/api/v3/oauth/engine/error?link=%2F&linkmessage=Back+to+Mattermost&message=The+page+you+were+trying+to+reach+does+not+exist&title=Page+not+found

instead of 

http://HOST/api/v3/oauth/engine/login

If I go and input /api/v3/oauth/engine/login by hand, it then properly logs me in and everything works. Does anyone have an idea how to fix it? I've spent a reasonable amount of time trying to find a cause at least but nothing brough me closer to fixing it.

**Comment by enahum** [comment]
Hi @niedakh 

It seems that you're hitting the error page cause React Router cannot find a suitable route, so you should use `window.location.href` instead of `browserHistory.push` that way React router won't try and find a suitable route.

Hope that helps

**Comment by esethna** [comment]
Thanks @niedakh, thanks @enahum. If you're still having issues I'd recommend posting on the [peer-to-peer developer forum](https://forum.mattermost.org/c/dev) since this is actually outside the scope of our platform.
