### ISSUE TITLE
Can't post from TFS using Slack webhook via HTTP

### ISSUE THREAD

**Issue by jdshkolnik** [mattermost/platform#3869]
#### Summary
Attempting to post a message to a Mattermost channel from TFS 2015 Update 3 via HTTP results in an error stating HTTPS is required.

#### Steps to reproduce
TFS 2015 Update 3 & Mattermost Team Edition v3.2.0. Both are in the same domain.

#### Expected behavior
Describe your issue in detail

#### Observed behavior
![image](https://cloud.githubusercontent.com/assets/2047520/17921902/38c21b98-69aa-11e6-88a6-24c43d0df097.png)

**Comment by it33** [comment]
Hi @jdshkolnik, 

I could be reading this wrong, but it looks like it's TFS that's requiring HTTPS. 

My guess is Slack is always HTTPS, so TFS never implemented support for HTTP. 

Maybe use Let's Encrypt to setup HTTPS for Mattermost to get past the TFS error?

**Comment by shieldsjared** [comment]
@jdshkolnik - take at look at this plugin for TFS. It may be more lenient with SSL as a requirement: https://github.com/kria/TfsNotificationRelay

**Comment by jdshkolnik** [comment]
@shieldsjared I will check it out. Thank you.
