### ISSUE TITLE
Custom emoticon not working "sometimes"

### ISSUE THREAD

**Issue by TheFamousPG** [mattermost/platform#3870]
#### Summary
Custom emoticon not working "sometimes".
I have a bot who check some information and I created some emoticons : 
https://gyazo.com/8967b1587ef1b0d096c1fc4c0b19551a

And **sometimes**, when the bot display the msg (every day at 10:00 am) emoticons won't appear.
I have to refresh manually the page to display it correctly.
https://gyazo.com/a02b6dc80c52d3b6886d9e22a5f575c6

#### Steps to reproduce
I don't know when. Just an incoming webhook who display custom emoticon and sometimes the emoticon don't work...

**Comment by esethna** [comment]
Thanks for the report! We have an [open issue](https://mattermost.atlassian.net/browse/PLT-3711) to fix the manual refresh with custom emoji. Closing to track in JIRA.
