### ISSUE TITLE
switching off Email notification resets the theme

### ISSUE THREAD

**Issue by DeltaLikeM** [mattermost/platform#3879]
#### Summary
Switching off the email notification as a user in the account settings will reset your theme

#### Expected behavior
I expected the theme to stay the same

#### Observed behavior
the theme switched to the default mattermost theme from mattermost dark

**Comment by hmhealey** [comment]
Hi @DeltaLikeM,

Thanks for the report! What version of Mattermost are you using (as shown in the main menu > About Mattermost)? And if you open the Javascript console on Chrome (by hitting F12), are any errors being printed?

**Comment by jasonblais** [comment]
Hi @DeltaLikeM, we haven't received an update for more than 7 days so we will assume that the
problem is fixed or is no longer valid. 

If you still experience the same problem try upgrading to the latest version. 

If the issue persists, you may reopen this issue and we'd be glad to help you out.
