### ISSUE TITLE
IncomingRequest produces => err=model.post.is_valid.props.app_error

### ISSUE THREAD

**Issue by Freshwood** [mattermost/platform#3880]
#### Incoming request produces error => err=model.post.is_valid.props.app_error
Hello everybody!
I was working on an integration for slack and mattermost. You can see the tool here:
https://github.com/Freshwood/matterbridge

The slash commands from the other integrations just working fine, but I have massive problems with the message attachments in Mattermost.
We are using the newsriver integration. The above mentioned service is looking for the latest news. If something is found then the service post the content via a IncomingResponse payload to the mattermost or slack (look to the configuration).
In the slack there is no problem. ;)

Anyway I looked to the golang code here but I don't found out what the o.props field stands for?

```
	if utf8.RuneCountInString(StringInterfaceToJson(o.Props)) > 8000 {
		return NewLocAppError("Post.IsValid", "model.post.is_valid.props.app_error", nil, "id="+o.Id)
	}
```

#### Steps to reproduce
Alternative number 1
* Use the matterbridge service
* Configure a incoming token for newsriver
* Start the service and send x-www-form-urlencoded data like:
command: news
text: searchText
user_name: blup
Then you will see exception in the mattermost log

Alternative number 2
*  Download the attached sample data.json. This json is the exact json from the service.
Please, keep in mind that this json does super work with slack.

#### Expected behavior
Message Attachments are displayed nicely :)

#### Observed behavior
A mattermost error message

#### Possible fixes
- Try to use the data.json and reproduce this
- Maybe golang is checking the json for RFC standard?

INFO: I' am using the latest mattermost version v. 3.3

[data.zip](https://github.com/mattermost/platform/files/437127/data.zip)

**Comment by jasonblais** [comment]
Thanks @Freshwood for the report (and love the work you've done with [matterbridge](https://github.com/Freshwood/matterbridge)!). Sorry for the delayed response here,

We currently don't support message attachments of outgoing webhooks - we have a ticket to fix the issue [here](https://mattermost.atlassian.net/browse/PLT-3658), and a list of known Slack comptability issues [here](https://docs.mattermost.com/developer/webhooks-outgoing.html#known-slack-compatibility-issues).

If you'd like to work [supporting attachments with outgoing webhooks](https://mattermost.atlassian.net/browse/PLT-3658), let us know. Help would be much appreciated :)

**Comment by Freshwood** [comment]
Hi jasonblais,
thank you for your friendly response. :+1: 
I already know the issue about the missing message attachment functionality for outgoing webhooks and slash commands. ;)
But in my case the service is sending a complete new request via (IncomingRequest) to the mattermost instance.

Current Workflow:
* User send a slash command from **mattermost** to _matterbridge_
* The _matterbridge_ service is looking for some news
* After that the user get a short message back (ephemeral: Hey I found 10 articels )
(UNTIL HERE THE FIRST REQUEST IS DONE)
* In the meanwhile the _matterbridge_ service need a bit time to process the messages
* After processing is done. The _matterbridge_ service send the information as IncomingRequest (with a configured token) to the **mattermost** service as message attachments.

That's why I put for this szenario the json payload from the service to this ticket :)

Best regards,
Freshwood

**Comment by jwilander** [comment]
Hi @Freshwood,

The `Props` field you see is our property bag on the Post struct for holding miscellaneous data about the post. We have a cap on the size of it to be 8000 characters when converted to JSON. When Mattermost receives an incoming webhook request, it puts the attachment field into the Props of the post. So it looks like your attachment is considered too long.

It's probably fine for us to increase that limit (or remove it) considering Slack allows larger attachments. Right now it's a soft limit on servers using MySQL since the database column is `text` but PostgreSQL would require an upgrade since the column is `character varying(8000)`.

I'll take with the rest of the dev team and make a ticket for this.

If you want to get it working in the meantime, you can try splitting your attachments into different messages.

**Comment by Freshwood** [comment]
Hi @jwilander,

thanks for your technical feedback.
In the meanwhile I testing the workaround with the splitting messages.
I'll give you a feedback!

Greetz,
Freshwood

**Comment by jasonblais** [comment]
Hey @Freshwood, just wanted to circle back that we have [opened a ticket in Jira](https://mattermost.atlassian.net/browse/PLT-4062) for us to track the issue.

Thanks again for reporting it and please let us know if splitting messages hasn't be successful.

**Comment by Freshwood** [comment]
Hi @jasonblais,
thank you for your feedback.
Yep, splitting the messages in small pieces was successful.
Greetz,
Freshwood

**Comment by jasonblais** [comment]
Great to hear! Closing the issue
