### ISSUE TITLE
Text containing dash followed by digits does not show up in search

### ISSUE THREAD

**Issue by ar-dia** [mattermost/platform#3882]
#### Summary
A text containing a dash followed by digits (such as found e.g. in JIRA issues) cannot be found during search.

#### Steps to reproduce
Create the following 3 posts:
- https://mattermost.atlassian.net/browse/PLT-3699
- PLT-3699
- [PLT-3699](https://mattermost.atlassian.net/browse/PLT-3699)

Then search for PLT-3699 (or "PLT-3699" or "PLT-3699*" or "*-3699" does not matter).

#### Expected behavior
Search should show all posts containing PLT-3699.

#### Observed behavior
No results found. Try again?

#### Probably related
The following issues are probably related:
https://github.com/mattermost/platform/issues/3657
https://mattermost.atlassian.net/browse/PLT-3699

I still filed a new bug because the scope is different (normal text vs. hashtag).
So you might want to adjust known issues accordingly until it's fixed.

#### Possible workarounds
It works as for issue #3657 when using underscore (or space) instead of dash, so using post:
[PLT_3699](https://mattermost.atlassian.net/browse/PLT-3699)
one can now find it even when searching for PLT-3699.
Another alternative workaround would be to add hashtags with underscore instead of dash.
Both workarounds however require more work from users, so it's likely to be forgotten.

#### Another search-related problem
I just found it while reporting this bug.
Posts containing:
- https://github.com/mattermost/platform/issues/3657
- issues/test3657
cannot be found either when just searching for 3657 (or *3657) or correspondingly test3657 (or *test3657 or */test3657),
so in that case it is not related to a dash, but a slash.

**Comment by jasonblais** [comment]
Thanks for the report @ar-dia!

Which Mattermost server are you using? I was testing it out on Mattermost 3.3 (Windows 10, Chrome), and the search results seem to come up correctly. We've 

![image](https://cloud.githubusercontent.com/assets/13119842/18111392/55a4464e-6eed-11e6-92a0-1544d3857fb9.png)

![image](https://cloud.githubusercontent.com/assets/13119842/18111399/5f610ff0-6eed-11e6-9c66-65c62d9f2c43.png)

**Comment by ar-dia** [comment]
Before I posted, I actually was unsure what version we use (I knew that we used version 3.0 a couple of months ago) and looked in https://docs.mattermost.com/administration/changelog.html for "search" and did not find anything, so I posted the report.
But now I checked and we indeed use version 3.3.0 with the default PostgreSQL DB. I tested with Electron and Chrome on Windows 7.
![mattermost-screenshot](https://cloud.githubusercontent.com/assets/7671146/18127008/228d9dd2-6f7e-11e6-8ca7-1f44f1201da7.png)

**Comment by jasonblais** [comment]
Great, thank you @ar-dia! I was able to reproduce this on Postgres, have created a ticket for us to track in Jira https://mattermost.atlassian.net/browse/PLT-4060

**Comment by lechuckcaptain** [comment]
Is it the issue considered closed as won't fix? Or will it be resolve in a future version?

Let me contribute with a couple of more screenshots with steps to reproduce the issue.

![image](https://cloud.githubusercontent.com/assets/341895/21897240/4aacc69c-d8e9-11e6-8c9a-0a9d507e92c4.png)

![image](https://cloud.githubusercontent.com/assets/341895/21897250/4f891af8-d8e9-11e6-954b-15c5181ea9b9.png)

**Comment by jasonblais** [comment]
Hey @lechuckcaptain, thanks for reporting this!

Terms containing a dash return incorrect results on PostgreSQL as dashes are ignored in the current search engine.

It is currently [considered as a known search issue](https://docs.mattermost.com/help/getting-started/searching.html#differences-between-mysql-and-postgres-search) - if you'd like to discuss potential solutions for it, let us know in the [Mattermost Developers community channel](https://pre-release.mattermost.com/core/channels/developers)

**Comment by lechuckcaptain** [comment]
Hey @jasonblais, thank you very much for the answer. I already read the know search issue page. The strange thing is that the [PLT-4060](https://mattermost.atlassian.net/browse/PLT-4060) is marked as closed (Won't Fix). My question was if you plan to solve in the future or you just accept the issue and consider it closed?

**Comment by jasonblais** [comment]
Thanks @lechuckcaptain for the reply! Would you be interested helping with a fix for the issue?

It's currently considered to be a known search issue -- we're scoping search improvements in the future at which point we'll re-consider it (probably later this year), but the fix isn't scheduled in the short term

**Comment by lechuckcaptain** [comment]
Thank you for the explanation @jasonblais. I might try to troubleshoot and fix the issue in the coming weeks (I need some time to go deeper in the Mattermost codebase). However it would be nice to have a open issue to track the progress of the problem.

**Comment by jasonblais** [comment]
@lechuckcaptain we created a [new epic for Full-Text Search](https://mattermost.atlassian.net/browse/PLT-5472). I reopened [PLT-4060](https://mattermost.atlassian.net/browse/PLT-4060) and added it to that epic so we can track its progress.


We're investigating how we might be able to improve full-text search despite some of the limitations in MySQL and PostgreSQL.

**Comment by muriloht** [comment]
the PLT-4060 should be reviewed since the anouncement 

_"From Mattermost v8.0, PostgreSQL is our database of choice for Mattermost to enhance the platform’s performance and capabilities. Recognizing the importance of supporting the community members who are interested in migrating from a MySQL database, we have taken proactive measures to provide guidance and best practices."_

i did all the migration steps from mysql to postgresql and the version upgrade from 7x version to 9.0.0 end averything is good, but the problem when searching terms as described in PLT-4060 is unnaceptable
