### ISSUE TITLE
Push Notifications should dismiss/disappear when read on another device.

### ISSUE THREAD

**Issue by jsg2021** [mattermost/platform#3884]
Sorry if this is a duplicate. I searched for something similar and couldn't find.

Mattermost Server 3.3

#### Summary
Push Notifications should dismiss when read on another device.

#### Steps to reproduce
Have notifications on your phone
Read your messages on the desktop.
the notifications do not go away automatically.

They should go away if you read your messages on other devices. (like other communication app,m such as Hangouts)

**Comment by jasonblais** [comment]
Thanks @jsg2021 for the report!

We've actually got a PR submitted to improve this behaviour where push notifications are cleared after viewing the channel https://github.com/mattermost/platform/pull/3834

It is currently undergoing testing, and is a potential candidate for Mattermost 3.4. If you'd like to [test the PR](https://github.com/mattermost/platform/pull/3834#issuecomment-242487253), that would be wonderful as feedback is always welcome.

**Comment by jasonblais** [comment]
Circling back,

In v3.4, push notifications should now clear on the Android app if you read messages on the desktop.

This won't however work yet in iOS. There's some functionality we'll need in the upcoming iOS 10 release for it to work properly, but we're considering to work on it once a stable version of iOS 10 is out.

Closing the issue for now, thanks for reaching out @jsg2021!
