### ISSUE TITLE
Inconsistent Channel-info order

### ISSUE THREAD

**Issue by cybershambles** [mattermost/platform#3892]
#### Summary
"Set a Header" & "Invite others to this channel" are swapped on new channels vs town-square.

#### Steps to reproduce
Create new channel.
compare the channel-info header.
invite is the primary on town-square...

#### Expected behavior
Same layout on all templates/channels.

**Comment by cybershambles** [comment]
<img width="354" alt="screen shot 2016-08-29 at 5 52 44 pm" src="https://cloud.githubusercontent.com/assets/7995198/18044479/720b76a4-6e11-11e6-8f85-dd0be9a333f3.png">
<img width="364" alt="screen shot 2016-08-29 at 10 10 37 am" src="https://cloud.githubusercontent.com/assets/7995198/18044481/7572664a-6e11-11e6-82a1-1c9e04128a36.png">

**Comment by cybershambles** [comment]
The "invite into team" vs "invite into channel" is the logically difference.

but the requirement for an invite others to this team being in a weird place is also just a UX choice.

**Comment by jasonblais** [comment]
Thanks for the report @cybershambles! 

I've [queued this for an upcoming UX meeting](https://pre-release.mattermost.com/core/pl/tjdx3hxjufba88dwmrf5nrkoga) - if you'd like to add any further feedback, you're welcome to join the `UX Design` channel in our [daily built Mattermost instance](https://pre-release.mattermost.com/signup_user_complete/?id=b8230f359369ed80c46ecb8696901b3e).

There's other related design discussion that goes on, so would love to see you join if you'd like (and haven't already).

**Comment by jasonblais** [comment]
Hey @cybershambles, we've added a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4042) to track it, please let us know if you'd like to work on it :)

**Comment by cybershambles** [comment]
Thanks @jasonblais.. https://github.com/mattermost/platform/pull/3935
