### ISSUE TITLE
While in chat is in compact mode Enter does not send

### ISSUE THREAD

**Issue by MaxBG92** [mattermost/platform#3902]
#### Summary
While in compact mode Enter does not send a message regardless of settings.

#### Steps to reproduce
![screen shot 2016-08-30 at 11 01 15 am](https://cloud.githubusercontent.com/assets/11785259/18081234/c540e580-6ea1-11e6-88b0-384a51fc5f60.png)
Version: 3.3.0
Open any channel or direct message thread.
Reduce the window's width until the sidebar gets hidden (this is what I refer to as compact mode)
Enter inserts a new line instead of sending a message
Ctrl+Enter does the same
Alt+Enter does the same
Command+Enter does the same

#### Expected behavior
Enter sends the message

#### Observed behavior
Enter inserts a new line

#### Possible fixes
Exciting compact mode fixes it

**Comment by jasonblais** [comment]
Thanks @MaxBG92 for the report! 

@R-Wang97 helped fix the issue with a [recent pull request](https://github.com/mattermost/platform/pull/3833) and it should be fixed with Mattermost v3.4
