### ISSUE TITLE
rtl/native direction support

### ISSUE THREAD

**Issue by gfgqtmakia** [mattermost/platform#3903]
While writing in rtl languages (e.g hebrew, arabic) the text is aligned to the left, which is ok i guess, but if you combine hebrew and english then it is all printed backwards.

Is it possible to auto detect the writing direction (like gmail) or enable toggling rtl/ltr direction and alignment (like MS word)? 

THX!

**Comment by jasonblais** [comment]
Thanks @gfgqtmakia for the feedback!

We have an existing feature request to [implement automatic right-to-left (RTL)](https://mattermost.uservoice.com/forums/306457-general/suggestions/15008277-implement-automatic-right-to-left-rtl).

I encourage you to upvote the feature, and add your feedback as well, so it can be discussed by the community and prioritized against other feature requests.

**Comment by jasonblais** [comment]
Closing the issue, if others have further feedback, feel free to add your notes to the [feature idea post](https://mattermost.uservoice.com/forums/306457-general/suggestions/15008277-implement-automatic-right-to-left-rtl).

**Comment by dc0d** [comment]
This is closed (though I've failed to find support for RTL languages) I should add that when adding RTL support, there is a need for adding alternative calendars too (Persian Calendar or Lunar Calendar).

Actually we need to provide a presentation layer - a formater - at the UI. We do not need it at other places & we just save Gregorian (default) Date. We just need to convert to/from other calendars at UI.

**Comment by assafmo** [comment]
This is very disappointing. Maybe you can recommend another chat app? because the current eyate is unbearable.

**Comment by assafmo** [comment]
This is very disappointing. Maybe you can recommend another chat app? The current state is unbearable.

**Comment by gfgqtmakia** [comment]
This is very disappointing. Maybe you can recommend another chat app? The current state is unbearable.

**Comment by dc0d** [comment]
Actually I would say MatterMost is one software with least hassle in it's category (not hassle-free) and it's written in Go (a big plus for me) and it just works as it claims (though I've a ton of ideas which might need a huge pile of resource & man-hour and it's codebase might get much much bigger!). I like it very much!

I think adding just the support for RTL languages would need a bit of work. But adding a special representation form for dates might need more work. On the other hand, having a framework for separating a value representation from the value itself, brings interesting opportunities in general (for example treating hashtag phrases in a specific way in a specific context (channel/team) by writing plugins or endpoints - I do not know how to extend mattermost yet).

**Comment by hadifarnoud** [comment]
@gfgqtmakia Rocket Chat supports proper RTL

**Comment by amir-khalili** [comment]
Hey Guys! 
Any progress? 
@mattermost-build

**Comment by amir-khalili** [comment]
Unfortunately, the new mobile client will messed up the RTL languages like Persian!

**Comment by dc0d** [comment]
Any updates on the issue?

**Comment by amir-khalili** [comment]
No yet buddy!
