### ISSUE TITLE
HTML entities in e-mail title

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3906]
#### Summary
I get HTML entities when there is `&` in an e-mail title:
![capture d ecran_2016-08-30_15-00-16](https://cloud.githubusercontent.com/assets/840125/18089917/7de4df2c-6ec2-11e6-913c-1567dfaaeeaf.png)

#### Steps to reproduce
1. Create a team with `&` in the title.
1. Send a notification.

#### Expected behavior
`&` is displayed correctly.

#### Observed behavior
`&` is displayed as `&amp;`

**Comment by lfbrock** [comment]
Hi @Rudloff, [this was brought up before](https://mattermost.atlassian.net/browse/PLT-1717) but it didn't look like an easy fix - if you (or anyone else) can figure out how to fix it, please let us know!

**Comment by Rudloff** [comment]
This seems to be enough to fix it:
```diff
diff --git a/api/post.go b/api/post.go
index d32d1c6..bbbc5f1 100644
--- a/api/post.go
+++ b/api/post.go
@@ -17,6 +17,7 @@ import (
        "strconv"
        "strings"
        "time"
+       "html"
 
        l4g "github.com/alecthomas/log4go"
        "github.com/gorilla/mux"
@@ -797,7 +798,7 @@ func sendNotificationEmail(c *Context, post *model.Post, user *model.User, chann
                        map[string]interface{}{"Prefix": attachmentPrefix, "Filenames": filenamesString})
        }
 
-       if err := utils.SendMail(user.Email, subjectPage.Render(), bodyPage.Render()); err != nil {
+       if err := utils.SendMail(user.Email, html.UnescapeString(subjectPage.Render()), bodyPage.Render()); err != nil {
                l4g.Error(utils.T("api.post.send_notifications_and_forget.send.error"), user.Email, err)
        }
 }
```

**Comment by shieldsjared** [comment]
@Rudloff I was about to issue concern about converting to UTF-8 character set, but after looking at the [SendMail routine](https://github.com/mattermost/platform/blob/master/utils/mail.go#L116), it looks like it's already setup to handle the B64 encoding required to handle UTF-8 in the subject line. Looks like the fix above would be sufficient, indeed!  

+1

@lfbrock - When this was previously looked at, is it possible that the ``encodeRFC2047Word`` implementation hadn't been done yet?  I don't foresee any other issues, barring anything found during manual testing.

**Comment by lfbrock** [comment]
@sheildsjared, I'm not sure - I think it was originally looked at a while ago so it's possible, I was just going off of what was written when the ticket was closed. I've reopened the ticket and included a link to this post, if anyone is interested in working on a fix please feel free!
