### ISSUE TITLE
Switching tabs in Account Settings causes ECMAscript errors

### ISSUE THREAD

**Issue by blackdruid** [mattermost/platform#3928]
When clicking on "Display" or "Layout" tabs under Account Settings a Javascript exception is raised:

> Uncaught TypeError: Cannot read property 'name' of undefined

After exception occurs none of the tabs work (_li_ elements under _settings-links_ div). This occurs regardless of browser used (tested on IE 11 and Chrome v48), even reproducable in Windows client. Issue is reproducable on latest 3.3.0 release and latest unstable.

## Reproduction steps:
1. Install Mattermost (in our case Debian 8.5.0 is used with PostgreSQL backend)
2. Run ./platform
3. Create team and account and login
4. Click on three dots next to your handle and choose **Account Settings** from the list
5. (5 sections are displayed: _General_, _Security_, _Notifications_, _Display_, _Advanced_)
6. Click on **Display** or **Advanced**

## Result:
Nothing happens. Opening developer tools (or having developer mode enabled) reveals that there is a Javscript error.

**Comment by jasonblais** [comment]
Hello @blackdruid, we're having trouble reproducing the issue you've described.

We have a community site for a daily built Mattermost instance. Wondering if you'd be able to sign up there and see if the issue reproduces?

**Comment by blackdruid** [comment]
Hi @jasonblais, I've created an account at [daily built Mattermost instance](https://pre-release.mattermost.com). Unfortunately I was not able to reproduce the issue.

Our Mattermost instance is running inside a VirtualBox instance of Debian 8.5.0 in a Windows 7 host. Your guide available [here ](https://docs.mattermost.com/install/prod-debian.html) was used to get it running. Port 8065 is forwarded to port 8080 using VirtualBox network routing so anyone on network can access it. The daemon is running by directly issuing `./platform`, no nginx as proxy is being used. Any ideas what could be wrong or how we can look deeper into the issue?

**Comment by mizhgan** [comment]
Hello.
I can confirm this issue.
In my case mattermost latest 3.3.0 release runs on barebone debian server through nginx proxy.
And behavior is the same as submitter says:
1. After loading the mattermost web gui in Chrome - Uncaught TypeError: Cannot read property 'url' of undefined exception in the cosole
2. After clicking on Account Settings and click on Display - Uncaught TypeError: Cannot read property 'name' of undefined
3. After that gui stop responding to any actions
4. After if i click on any menu items - Uncaught TypeError: Cannot read property 'getHostNode' of null

**Comment by esethna** [comment]
Thanks for the report and repro, I've [filed a ticket](https://mattermost.atlassian.net/browse/PLT-4184) so this can be tracked in JIRA moving forward.

**Comment by esethna** [comment]
Hi @blackdruid and @mizhgan, would you be able to confirm of this is still an issue in the latest release, [v3.4](https://www.mattermost.org/download/)?

**Comment by mizhgan** [comment]
Hello!
I will try v3.4 soon and report about this issue here ASAP.

2016-09-19 19:35 GMT+03:00 Eric Sethna <notifications@github.com>:

**Comment by mizhgan** [comment]
It`s still the same
http://i.imgur.com/qYI4OJA.png

**Comment by blackdruid** [comment]
Version 3.4.0, **issue not reproducible**.

**Comment by esethna** [comment]
Great, thanks for investigating, closing as resolved.
