### ISSUE TITLE
inserting code blocks using keyboards without backtick key

### ISSUE THREAD

**Issue by marco-a-itl** [mattermost/platform#3929]
#### Summary
For users having keyboard without backtick key (ASCII 96) inserting code blocks (which have to be sorrounded by ```) is really uncomfortable, since you have to type ALT-96 multiple times. A "insert code" button (in addition to markdown characters) would be very helpful. For consistency, the same could be applied to the rest of formatting options: bold, italic, strike, inline code, preformatted, quote.

#### Possible fixes
The help strings appearing below message text box:
\*\*bold\*\*\_italic\_\~\~strike\~\~ \`inline code\`\`\`\`preformatted\`\`\`\>quote
could be made clickable. Clicking on them could trigger insert in the text box of the corresponding markdown prefix and suffix.

**Comment by jasonblais** [comment]
Thanks for the feedback @marco-a-itl! 

We have an [existing feature request](https://mattermost.uservoice.com/forums/306457-general/suggestions/10672527-advanced-message-rich-text-editor) to add an advanced message text editor -- I encourage you to participate in the discussion and upvote the feature.

**Comment by marco-a-itl** [comment]
Ok, thanks. That would solve my problem. I've voted the feature.

**Comment by jasonblais** [comment]
Awesome, thanks @marco-a-itl!
