### ISSUE TITLE
Edit post interface eats leading spaces

### ISSUE THREAD

**Issue by NilSet** [mattermost/platform#3939]
When editing a post, any leading spaces will be removed. This is a problem when trying to escape markdown.

#### Steps to reproduce
version 3.3.0
1\. Post the following
````
    ```latex
    test
    ```
````
2\. Edit the post to the following
````
    ```latex
    fail
    ```
````

#### Expected behavior
Both versions display as code blocks showing the raw markdown due to the indentation

#### Observed behavior
After editing, it renders as a latex expression because the initial 4 spaces are removed.

#### Possible fixes
Don't trim whitespace on edits when you wouldn't trim whitespace on initial posting.

**Comment by lfbrock** [comment]
Thanks @NilSet - I've created a Jira ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-4079

If anyone is interested in submitting a fix for this, please let us know!

**Comment by lfbrock** [comment]
Closing this issue + will track in Jira
