### ISSUE TITLE
Empty page when JavaScript is disabled

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3953]
#### Summary
When JavaScript is disabled, Mattermost returns an empty HTML page.

#### Steps to reproduce
Browse to your Mattermost team with a browser that does not support JavaScript (e.g. Lynx).

#### Expected behavior
It would be nice to at least have a message explaining that Mattermost needs JavaScript in order to work correctly.

#### Observed behavior
A totally blank page.

#### Possible fixes
A simple `<noscript>` tag with a message is probably enough.

**Comment by lfbrock** [comment]
Hi @Rudloff, is this something you would be interested in submitting a fix for?

**Comment by Rudloff** [comment]
Yes, I can submit a pull request for this.
