### ISSUE TITLE
filter out offensive words

### ISSUE THREAD

**Issue by Eng3l** [mattermost/platform#3956]
Maybe this is a feature request but I need to filter out offensive words and replace those words for others like &$$@*!!.
The thing is that I have this platform in my company and we want to avoid all kind of awkward situations generated by those words.

**Comment by lfbrock** [comment]
Hi @Eng3l - can you add that as a [feature request](https://www.mattermost.org/feature-ideas/) so we can track it with the rest of our feature ideas?

**Comment by lfbrock** [comment]
Closing this issue + will track in uservoice: https://mattermost.uservoice.com/forums/306457-general/suggestions/15944848-offensive-words-filter
