### ISSUE TITLE
Can not create default profile image

### ISSUE THREAD

**Issue by jlebleu** [mattermost/platform#396]
{"message":"Could not create default profile image font","detailed_error":"read /go/src/github.com/mattermost/platform/web/static/fonts/: is a directory","request_id":"i1kkow5z5ffy3ne6oduc8uptwy","status_code":500}

Image is broken on new user creation

**Comment by coreyhulen** [comment]
I think you're missing the InitialFont property from the config.json file.

https://github.com/mattermost/platform/blob/master/config/config.json#L69

**Comment by jlebleu** [comment]
Thank you, it works now, forgot to update the config file on upgrade
