### ISSUE TITLE
Links to public channels sometimes break the client.

### ISSUE THREAD

**Issue by grundleborg** [mattermost/platform#3973]
This one is a bit hard to reproduce consistently, but I think I have figured out steps that work - see below.

If I paste a link to a public channel in chat, e.g. https://pre-release.mattermost.com/core/channels/public-test-channel and then someone who is not a member of that channel (could be me, could be someone else) clicks on it, sometimes it takes out the client with javascript errors rather than joining and loading that channel.

Steps to Reproduce
--------------------------------

The problem only seems to happen if, for the channel you are pasting into, this is the first time you have clicked on a link to another channel there. So, join a new channel (let's call it !new-one), then paste a link to another channel you aren't a member of (!new-two), then click the link. You should hopefully see the error case.

Sample Console Output
--------------------------------------
```
method=getPosts msg=You do not have the appropriate permissions detail=userId=rx34qymts7b5588s4arp8x7o8e rid=gg3tqzoz4p8dteiz5cuc5eeoxc main.4a1d125331f215838a15.js:27:21408

Object { id: "api.context.permissions.app_error", message: "You do not have the appropriate per…", detailed_error: "userId=rx34qymts7b5588s4arp8x7o8e", request_id: "gg3tqzoz4p8dteiz5cuc5eeoxc", status_code: 403 } main.4a1d125331f215838a15.js:27:21425

method=getChannelExtraInfo msg=No channel member found for that user id and channel id detail=channel_id=oskh61hufj8e5rde9ryi9edxsauser_id=rx34qymts7b5588s4arp8x7o8e,sql: no rows in result set rid=z1dcx3w59ffhxcpgx5fs7jhg3w main.4a1d125331f215838a15.js:27:21408

Object { id: "store.sql_channel.get_member.missin…", message: "No channel member found for that us…", detailed_error: "channel_id=oskh61hufj8e5rde9ryi9edx…", request_id: "z1dcx3w59ffhxcpgx5fs7jhg3w", status_code: 500 } main.4a1d125331f215838a15.js:27:21425
```

**Comment by lfbrock** [comment]
Ticket here to track this issue: https://mattermost.atlassian.net/browse/PLT-4135
