### ISSUE TITLE
Emote messages do not support Markdown due to implicit formatting

### ISSUE THREAD

**Issue by jtdaugherty** [mattermost/platform#3987]
#### Summary
Emote messages (`/me`) are delivered to the client with an implicit `*...*` wrapping, meaning that users cannot use `*...*` or other syntax in emotes without also accounting for the enclosing `*...*`.

#### Steps to reproduce
On receiving an emote message, note that the text has been embellished with `*...*`.

#### Expected behavior
The expected behavior is that the formatting of an emote is a purely client-side decision.  Thus it would be helpful if the emote message had a prop stating that it was an emote, rather than having to look at the icon URL prop and notice that the message text has `*...*` added.

#### Possible fixes
A possible fix is to add a prop to emotes and to defer the formatting of emotes to the client rather than adding `*...*` on the server. As best I can tell that occurs here:
https://github.com/mattermost/platform/blob/7a25f2a78bc3afdaa7c55be5da66f3afa0fc965d/api/command_me.go#L36
The primary motivation for this is that I'm developing a MatterMost client and we need a more reliable way of detecting emotes *and* taking the approach suggested above would permit clients to support markdown in emote messages.

CC @aisamanra @dagit

**Comment by lfbrock** [comment]
Hi @jtdaugherty, 

We do have a ticket to [update the formatting of /me messages](https://mattermost.atlassian.net/browse/PLT-2436) to make them look more like System Messages (which are faded our and grey, like the example below). 

<img width="288" alt="screenshot 2016-09-08 11 17 00" src="https://cloud.githubusercontent.com/assets/9354841/18355023/d40009b4-75b5-11e6-9ae2-46ecd9217666.png">

I think this may fix the issue? 

If so, if anybody from the community would like to work on a PR for the issue, please feel free

**Comment by jtdaugherty** [comment]
@lfbrock Interesting. While that change might coincidentally help, it depends on how it's implemented. My ticket is about requesting that any formatting of `/me` messages is done *client-side only* rather than server-side as is done right now.  The ticket you mention doesn't say anything about the server-side behavior, just the message presentation.  If the formatting is done client-side only, clients (such as my terminal client) can format as appropriate without having to strip off the `*...*` that the server currently sends.  One way to do this would be to add a prop to the message saying that it's a `/me`-type message. Does that make sense? Thanks!

**Comment by jtdaugherty** [comment]
(Unless "creating a new post type" means doing what I'm proposing; I'm not sure, though.)

**Comment by hmhealey** [comment]
Yep, what you're proposing would be creating a new post type like we have for [system messages and other special posts](https://github.com/mattermost/platform/blob/master/model/post.go#L12). I've been wanting to make that change for a while now, and being able to better control the formatting of those posts (as the ticket wants done) is one of the reasons for that.

**Comment by jtdaugherty** [comment]
Fantastic!

**Comment by jtdaugherty** [comment]
I noticed that the mentioned ticket is low-priority and not scheduled for any particular release. Would it be possible to get this targeted for an upcoming release?

**Comment by lfbrock** [comment]
It's not priority at the moment, but if someone from the community would like to work on it then it may get done faster.

**Comment by esethna** [comment]
Closing this to track in [JIRA](https://mattermost.atlassian.net/browse/PLT-2436). The ticket is marked as `accepting-pull-requests`, so if anyone from the community would like to work on this then please comment in JIRA. Thanks!
