### ISSUE TITLE
email addresses should not end in comma

### ISSUE THREAD

**Issue by oetiker** [mattermost/platform#4018]
#### Summary
The email address `user@domain.com,` is accepted and works

#### Steps to reproduce
Create a user with email `user@domain.com,`

#### Expected behavior
It should not be possible to create such users.

#### Observed behavior
Mail is sent to `user@domain.com` while the internal user has the address `user@domain.com,`

#### Possible fixes
Email addresses should be validated more strictly

**Comment by esethna** [comment]
Thanks @oetiker! I have created a ticket for this, it can be tracked in [JIRA](https://mattermost.atlassian.net/browse/PLT-4183).
