### ISSUE TITLE
Feature Request: Add support for high availability

### ISSUE THREAD

**Issue by titanous** [mattermost/platform#402]
Does Mattermost support more than one instance of the API server? It looks like as of 246d12aaf23fa3a2c23225b33a333effff76253b Redis is no longer used, and fan-out was switched to in-process fan-out using Go channels. Is this assessment correct? Are there any plans to support multiple redundant/stateless server instances?

**Comment by jwilander** [comment]
Hey @titanous 

You're right, currently we only support one instance of the API server. We do, however, plan to support multiple server instances down the road, very likely before our 1.0 release where we will give our blessing for the use of Mattermost in a production environment.

**Comment by titanous** [comment]
Great, do you currently have a plan for how that will be implemented?

**Comment by jwilander** [comment]
Not yet, but once we do we will make it public for every one to see.

**Comment by coreyhulen** [comment]
More than likely it will be similar to the redis implementation we removed.  Internally we supported sharding for a previous incarnation of the product, but it was heavily coupled to Amazon services like Route53, etc.

**Comment by jdassonvil** [comment]
Any news on that topic ? I've checked the release notes and didn't read anything about high availability setup.

**Comment by it33** [comment]
Hi @jdassonvil, no change since August. Could we have someone's help opening a [feature idea](http://www.mattermost.org/feature-requests/) so this can be upvoted?

We're doing a sweep to close out old feature request tickets given the [new organization of community systems](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#community-systems).

**Comment by titanous** [comment]
Feature idea opened: https://mattermost.uservoice.com/forums/306457-general/suggestions/12455799-support-high-availability
