### ISSUE TITLE
Issue while posting the message

### ISSUE THREAD

**Issue by laitkor** [mattermost/platform#4029]
I have updated the API code and getting the issue while posting the message:
`api.web_socket_router.log.error%!(EXTRA int64=0, string=8w51cok1wfdq3qq33nq3sqimka, string=api.web_socket_router.bad_seq.app_error, string=)`

Message get posted in the db successfully but the chat didn't get updated until and unless the other person refresh the window.

**Comment by rkopplin** [comment]
how did you solve it?
