### ISSUE TITLE
[Help Wanted] Pinned Posts

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4035]
Pinned posts is one of the [top voted feature on UserVoice](https://mattermost.uservoice.com/forums/306457-general/suggestions/10461081-pinned-posts) by the community. 

We have [created a specification for pinned posts here](https://docs.google.com/document/d/1U29VQGEFEI7JDaTBjvk5xm59MvJD-JMI4TQv1erjnrU/edit#) and are looking for anyone interested in helping out implementing the feature.

If you are interested, please reply here? 

You may also join our [UX Design channel to discuss further details](https://pre-release.mattermost.com/core/channels/ux-design) about the feature, if you'd like.

![image](https://cloud.githubusercontent.com/assets/13119842/18637501/9e7aa0ee-7e5a-11e6-8287-473c2ad4ff4d.png)

_Above: Screenshot of [design specification for pinned posts](https://docs.google.com/document/d/1U29VQGEFEI7JDaTBjvk5xm59MvJD-JMI4TQv1erjnrU/edit#)_

**Comment by Zhouzi** [comment]
I am interested in implementing this feature. I've set myself up and signed the CLA so will start working on it 😃

**Comment by jasonblais** [comment]
That's awesome, many thanks @Zhouzi!! Highly appreciated!

If you're not a member yet, consider [joining our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets), where you can discuss questions with community members and the Mattermost core team.

**Comment by jasonblais** [comment]
Closed by #4217, thanks @Zhouzi!!
