### ISSUE TITLE
[Help Wanted] Screens to edit Slash Commands

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4036]
Custom slash commands are popular and many in the community have asked for the ability to edit existing slash commands more easily, instead of creating a new command each time.

Below are details on how we can accomplish this, by creating screens to edit slash commands.

If anyone would be interested in helping out, please reply here?

You may also join our [UX Design channel to discuss further details](https://pre-release.mattermost.com/core/channels/ux-design) about the feature, if you'd like.

---

#### Details:

1 - Add an "Edit" button for slash commands that offers an Edit screen (similar to the create screen) that saves back changes.

![image](https://cloud.githubusercontent.com/assets/13119842/18633979/f1fdc84e-7e4c-11e6-85df-18c4a476e8c1.png)
_Above: Add "Edit" button between regenerating the token and deleting the command_

![image](https://cloud.githubusercontent.com/assets/13119842/18633994/02c41cc8-7e4d-11e6-967b-44980215877c.png)
_Above: Edit screen that opens after clicking "Edit" in the previous screenshot_

2 - If it's a change that will break existing integrations (one of trigger word, request URL or request method), add a confirmation dialog notifying the user of the consequences of the update.

Text should read `Your changes may break the existing slash command. Are you sure you would like to update it?`

![image](https://cloud.githubusercontent.com/assets/13119842/18619983/3a542e42-7dd7-11e6-8d2a-6097bfe22a56.png)
_Above: Confirmation dialog if changes break an existing integration_

**Comment by bolecki** [comment]
I would like to give this one a shot!  I already signed the CLA and joined the community channel.  I look forward to helping out!

**Comment by jasonblais** [comment]
Awesome, thanks @bolecki for your interest! Highly appreciated!

Many in the community have been waiting for this improvement :)

**Comment by jasonblais** [comment]
Hey @bolecki, thank you for working on this improvement, highly appreciated!

Just wanted to give you a heads up about upcoming dates for our 3.5 release that are relevant to this issue improvement:
 - Mon 10/31: last date community pull requests should be submitted for testing and review
 - Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4. Large pull requests may require an earlier merge date.

If you'd like to work on getting the edit screens for 3.5, those would be the dates to meet -- just wanted to let you know so it doesn't come as a surprise if you were aiming for the 3.5 release.

Once again, big thanks for your wonderful work, really excited for this improvement!

**Comment by bolecki** [comment]
Thank you for the update, I should be able to submit the pull request tomorrow!

**Comment by jasonblais** [comment]
Closed via #4335, thanks @bolecki!
