### ISSUE TITLE
[Help Wanted] HTML entities in error page title

### ISSUE THREAD

**Issue by ebuildy** [mattermost/platform#4049]
#### Summary

There are HTML entities in title HTML tag for some error page.
#### Steps to reproduce

Display the error page.
#### Expected behavior

Title HTML tag should never contain HTML entities.
#### Observed behavior

In page HTML source, I can see: `<title>&lt;span class='fa fa-chevron-left'>&lt;/span>Back - Error</title>`
#### Possible fixes

HTML entities must be removed from title HTML tag.

**Comment by jasonblais** [comment]
Thanks @ebuildy for the note,

Would you have a sample error page where you saw this occurring? Just so that we can more easily pinpoint the error.

Also, if you're interested in submitting a fix for it, we'd be glad to take it.

**Comment by ebuildy** [comment]
Hello, it was an error with Gitlab authentication, not so easy to replicate :/ 

Yeah, soon I have some time, I will dig on your code source with pleasure.

**Comment by jasonblais** [comment]
Perfect, thanks @ebuildy! Much appreciated :)

**Comment by jasonblais** [comment]
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with reproduction steps to help us identify the bug.
