### ISSUE TITLE
Email as field as input type email

### ISSUE THREAD

**Issue by lucianosousa** [mattermost/platform#4050]
Today is a input text field.

UX will be better, especially in mobile app

**Comment by jasonblais** [comment]
Thanks @lucianosousa for the feedback!

Would you mean changing the email field on the Mattermost sign in page?

**Comment by lucianosousa** [comment]
@jasonblais Exactly.
I'm not sure if is this input here:
https://github.com/mattermost/platform/blob/master/webapp/components/login/login_controller.jsx#L359

But you got the idea.

**Comment by jasonblais** [comment]
Thanks @lucianosousa for the quick reply,

The input field on the sign in page is also used to log in with Mattermost username (if enabled on the server), and LDAP username (if enabled on the server).

Keeping the input type as text was used to better support these alternate sign in methods.

**Comment by lucianosousa** [comment]
I see. I think you can do some research in that case. ask for users. I mean, looks better an email field in that case.

**Comment by jasonblais** [comment]
Thanks again @lucianosousa,

Our UX team discussed this case and agree that it would make sense to change the field to an email type on mobile.

Would you be interested in submitting a pull request for a fix?

The fix would involve using the mobile email keyboard for the username/email field on the sign in page if
 1. Mattermost is on mobile view, AND
 2. Mattermost is not on desktop or browser

**Comment by lucianosousa** [comment]
@jasonblais I'm still trying figure out this project. I'm not good enough to to this right now.
feel free to keep working on it. :)

**Comment by jasonblais** [comment]
Sounds good, thanks again @lucianosousa! 

I've created a [ticket in Jira for us to track](https://mattermost.atlassian.net/browse/PLT-4295), if anyone in the community would like to take it, please let us know
