### ISSUE TITLE
Documentation Website Down

### ISSUE THREAD

**Issue by mitrick2** [mattermost/platform#4055]
#### Summary
Clicking on documentation link on main website leads to error:

#### Steps to reproduce
Go to https://docs.mattermost.com/

#### Expected behavior
Documentation is displayed to browser

#### Observed behavior
Instead of the page loading, I get:
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9FC01B31B9BFD2D0</RequestId>
<HostId>
pteNkvJ0MnnjSgvWmIousxA0ZNEKHUnsTrqY+w0K/FtXOL5TbiobLrNnKzhR4pL9ZhZFg46+Jmo=
</HostId>
</Error>

#### Possible fixes
Suggest looking at your AWS config and permissions

**Comment by jasonblais** [comment]
Thanks @mitrick2 for the report! 

We recently pushed an update to the site and you might have tried accessing the page during that update. 

Are you still experiencing an `AccessDenied` error or has the issue cleared?

**Comment by mitrick2** [comment]
Doc site works as expected, so all set here!  Thanks for the insight, and excited to get started with it!

**Comment by jasonblais** [comment]
Thanks for your interest @mitrick2!
