### ISSUE TITLE
Embed single chat channel to external application

### ISSUE THREAD

**Issue by istvano** [mattermost/platform#4070]
#### Summary
I need to see if I can integrate mattermost chat channel to an other reactjs based app

We are in the process of developing an application which needs social IM features as an addition. Inside our app which is a reactjs app we have a side pane on which we need to show IM. I was thinking about integrating something like mattermost instead of rolling our own version.

We do not need all the features of mattermost but it looks absolitelly amazing and probably would fit our requrements.

I have 2 questions.

1, is it possible to embed only a single mattermost channel into our app? Any ideas how to go about it
2, Does the licence allow me to actually integrate mattermost into our app like that ?

Kind Regards,

**Comment by lfbrock** [comment]
Hi @istvano, I think it would be possible to build with our drivers if that's something you're interested in: https://docs.mattermost.com/developer/api.html#mattermost-drivers

There's a feature request here for something similar, but it's not something we've built yet. 
https://mattermost.uservoice.com/forums/306457-general/suggestions/8810731-implement-a-site-chat-feature

**Comment by istvano** [comment]
Hi, 

Thanks for the info. It looks good. I will check it out.
