### ISSUE TITLE
TeamMember.IsTeamAdmin implementation return always true!

### ISSUE THREAD

**Issue by loic-fejoz** [mattermost/platform#4073]
#### Summary
Golang API does not implement TeamMember.IsTeamAdmin().

#### Steps to reproduce
Read line 72 of model/team_member.go

#### Expected behavior
Return true only if field Roles contains the admin role.

#### Observed behavior
Obvious

#### Possible fixes
The patch in attachment. It was almost there!
NB: it does not work if blank are allowed in name of roles.
[0001-Implements-Team_Member.IsTeamAdmin.patch](https://github.com/mattermost/platform/files/487689/0001-Implements-Team_Member.IsTeamAdmin.patch.txt)

**Comment by jasonblais** [comment]
Thanks @loic-fejoz! 

Would you like to submit your find as a pull request, and our developers would be happy to review it?

**Comment by jasonblais** [comment]
Thanks again @loic-fejoz ,

Looks like the TeamMember.IsTeamAdmin() function was removed with https://github.com/mattermost/platform/pull/4090 and that you were guided to use the [ROLE_TEAM_USER](https://github.com/mattermost/platform/blob/master/model/authorization.go#L278) function instead.

Does that help resolve your issue?

**Comment by loic-fejoz** [comment]
Hi @jasonblais 
It helps solve my issue but the conclusion is neither satisfying for me, nor the other potential user.

Indeed, the goal of interface is to hide implementation details, esp. for API. And assuming testing that a user a role Team Admin, we shall provide such a thing, and knowing that the implementation has changed from version 3.3 to 3.4, we shall provide something.

And even if you think that having a method is not worth having, then at least the documentation shall be updated to make it clear what and where roles are declared.

For me for the bug to be closed the minimum shall be to keep the method TeamMember.hasRole(string role): bool  AND update the API documentation... :-/

Thanks for asking.

**Comment by jasonblais** [comment]
Thanks @loic-fejoz and sorry for the late response.

We're planning to document API changes in our release notes, [you can see an example here](https://docs.mattermost.com/administration/changelog.html#api-changes-from-v3-3-to-v3-4).

We also have a [work in progress documentation of the Mattermost APIs](https://api.mattermost.com) -- all help is appreciated if you'd like to make any updates!
