### ISSUE TITLE
New websocket "hello" event type is not mentioned in release notes

### ISSUE THREAD

**Issue by jtdaugherty** [mattermost/platform#4074]
#### Summary
The 3.4 release added the websocket event type "hello" but it was not mentioned in the release notes as far as I can tell, breaking the [Matterhorn](https://github.com/aisamanra/matterhorn) third-party client once we deployed 3.4.  I checked these sources for the change and didn't see it listed:

* https://www.mattermost.org/category/releases/
* https://docs.mattermost.com/administration/changelog.html

Is there some place this was mentioned that we could have checked instead?

CC @dwest-galois @aisamanra @dagit

**Comment by jasonblais** [comment]
Thanks @jtdaugherty for the feedback

We haven't been including changes to WebSocket events in the past, but we will add it to our changelogs in the future. A pull request submitted to update our release process checklist https://github.com/mattermost/docs/pull/517

**Comment by jtdaugherty** [comment]
Wonderful. Thanks! Anything that is going to affect third-party client developers will be extremely useful there (JSON payload formats, new request endpoints, websocket event types, etc). Even better, having those changes called out together in a "Client protocol" section would make them really easy to spot when we're checking on whether we need to update our client.
