### ISSUE TITLE
No parse markdown in Mattermost WebHook from a GitLab issue

### ISSUE THREAD

**Issue by ajsb85** [mattermost/platform#4084]

**Comment by jasonblais** [comment]
Thanks @ajsb85 for the report, 

Output from GitLab webhooks can't render embedded images because of relative links, and we have [opened an issue in GitLab](https://gitlab.com/gitlab-org/gitlab-ce/issues/22531).

Would this cover the issue you experienced?

**Comment by jasonblais** [comment]
We haven't received an update so we will assume that the problem can be covered by the [open issue in GitLab](https://gitlab.com/gitlab-org/gitlab-ce/issues/22531).

If the issue persists, please reopen this issue with the relevant information.
