### ISSUE TITLE
[Help Wanted] Channel header change message does not provide enough information

### ISSUE THREAD

**Issue by jtdaugherty** [mattermost/platform#4087]
#### Summary
When someone changes a channel header, the resulting post message contains the new header string in a form that must be parsed by the client. This is a case of confusing presentation with metadata. It requires client developers to implement hacks to obtain the channel header strings at best, or query the server for a refresh of channel metadata at worst.

#### Expected behavior and Fix
The expected behavior (well, the more helpful behavior anyway) would be to provide the new channel header string as an additional field in the JSON object rather than requiring the client to parse `updated the channel header from: ... to: ...` to update the local application's state.

CC @aisamanra @dagit

**Comment by lfbrock** [comment]
Hi @jtdaugherty, in this case I think it might be easiest to use the system message as a trigger, but then to use the [APIs to get the channel](https://api.mattermost.com/#tag/channels%2Fpaths%2F~1teams~1%7Bteam_id%7D~1channels~1%7Bchannel_id%7D%2Fget) for the header information. 

Let me know if that documentation helps?

**Comment by jtdaugherty** [comment]
I propose an alternative, which is to divorce presentation from representation. If the message included the new and old channel header strings as properties, the client could still render it however is appropriate *and* update its state *without* an extra request to the server.

**Comment by lfbrock** [comment]
The system message was added with the intention of being a UI feature and not for triggering updates off of, but feel free to come discuss in the [Developers channel](https://pre-release.mattermost.com/core/channels/developers) on our [daily build server](https://pre-release.mattermost.com/signup_user_complete/?id=b8230f359369ed80c46ecb8696901b3e) if you're interested in updating them.

**Comment by jtdaugherty** [comment]
Are these tickets not a sufficient place to have such a discussion?

**Comment by jtdaugherty** [comment]
For continuity: the discussion in the Developers channel concluded that while there's support from the Mattermost developers for this change, it isn't a priority for them. Although they offered to consider pull requests I am not in a position to provide one. We (being the developers of https://github.com/aisamanra/matterhorn) still need this change made so either someone else with Go expertise will need to write up a patch or it will need to become a priority for the core developers.

**Comment by jasonblais** [comment]
#4209 should close this issue, highly appreciated @alsma!
