### ISSUE TITLE
Custom emoji do not maintain their original aspect ratio

### ISSUE THREAD

**Issue by alexbarrett** [mattermost/platform#4093]
#### Summary
Custom emoji do not maintain their aspect ratio when used in messages.

#### Steps to reproduce
Upload a non-square custom emoji and use it in a message.

Version: 3.4.0
Build Hash: 57f25fa59c71821cc38fd220b133aa6a40815e12

#### Expected behavior
The aspect ratio of custom emojis' images is maintained when used.

#### Observed behavior
The custom emoji is always displayed as a square.

#### Possible fixes
1. Remove the width declaration from [_emoticons.scss:8](https://github.com/mattermost/platform/blob/57f25fa59c71821cc38fd220b133aa6a40815e12/webapp/sass/components/_emoticons.scss#L8). Browsers would automatically scale emojis to the correct height while maintaining their aspect ratio.

2. Display emoji as background images on square containers and use `background-size: contain` to display them at the correct aspect ratio. This is what Slack does.

**Comment by lfbrock** [comment]
Hi @alexbarrett thanks for the report - would you be interested in submitting a fix for this? 

I filed a Jira ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-4300

**Comment by lfbrock** [comment]
Closing this issue + will track in Jira
