### ISSUE TITLE
[Help Wanted] Favorite/Starred Channels 

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4095]
We're looking for anyone interested in helping contribute Favorite Channels, if you're interested please comment here or come [join our daily builds server](https://pre-release.mattermost.com/signup_user_complete/?id=b8230f359369ed80c46ecb8696901b3e) where you can discuss questions with our core team developers (Developers channel) and product managers (UX Design channel). 

## Favorite Channels

**On Desktop/Browser:**

1. Add a star icon to the channel header in all channels, private groups, and direct messages

2. Clicking on the star:
  - Fills in the star with the mention highlight color
  - Adds the channel to a “Favorites” section at the top of the sidebar
<img width="417" alt="screenshot 2016-09-26 11 55 38" src="https://cloud.githubusercontent.com/assets/9354841/18847751/3aa6b3ec-83e0-11e6-95ef-5cf3d9471a46.png">

3. Clicking on the star again:
  - Removes the color from the star
  - Removes the channel from the “Favorites” section of the sidebar. If there are no other favorite channels listed, then the “Favorites” header is hidden from the sidebar.
<img width="429" alt="screenshot 2016-09-26 11 55 47" src="https://cloud.githubusercontent.com/assets/9354841/18847755/3d458bc8-83e0-11e6-927c-00cf8e001f13.png">

**On Mobile View:**

1. In Mobile View, the star icon is hidden from the channel header
2. Instead, in the channel dropdown list, add an option:
  - “Add to Favorites” for channels not in the “Favorites” list
  - “Remove from Favorites” for channels already in the “Favorites” list
<img width="252" alt="screenshot 2016-09-26 11 56 01" src="https://cloud.githubusercontent.com/assets/9354841/18847765/4603ebba-83e0-11e6-9e36-c8f5ec97378c.png">

**Comment by alsma** [comment]
I'm on it

**Comment by jasonblais** [comment]
@alsma, you're awesome!!
