### ISSUE TITLE
Youtube mobil-link dont expand player

### ISSUE THREAD

**Issue by psyc0** [mattermost/platform#4096]
haven´t seen a fix for this in the changelog for 3.4 (currently running 3.3).

mobile versions posted from youtube dont expand the thumbnail/player,
ie. m.youtube.com/#
youtu.be seems to work fine though

**Comment by lfbrock** [comment]
Thanks for the report @psyc0, is this something you'd be interested in submitting a fix for? I created a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-4304
