### ISSUE TITLE
push notifications of read messages do not clear the notification

### ISSUE THREAD

**Issue by Screndt** [mattermost/platform#4103]
#### Summary
When a message is read on the desktop app, a push notification is sent to mobile app, but that does not clear the mobile notification.

#### Steps to reproduce
0) I will mention the versions/OSes I use this on, but I am unsure if this affects all versions.
1) Install the desktop app on Windows
2) Install the mobile app on Android.
3) Get a message on the desktop while not in the channel on which you get the message.
4) Notice that you got a push notification to your mobile.
5) Read the message on the desktop.
6) Notice that you get another notification on your mobile.

#### Expected behavior
@6 Notification on your mobile is removed and the mobile does not make the notification sound.

**Comment by lfbrock** [comment]
Hi @Screndt, 

Can you check the version of Mattermost from the three dot Main Menu > About Mattermost, and also try downloading the [latest Android app](https://play.google.com/store/apps/details?id=com.mattermost.mattermost&hl=en)? 

I think this should have been fixed for Android devices in the last release (server version 3.4). 

There is a ticket here to [fix it for iOS devices](https://mattermost.atlassian.net/browse/PLT-4178).

**Comment by Screndt** [comment]
Versions across the board (server, desktop, and Android app) are 3.4.0.

**Comment by Screndt** [comment]
My mistake.  Server and desktop versions are 3.4.0.  Android app is 3.2.0.

Might I also suggest that the "About" selection on the mobile app show either the version of the app or the version of both the app and the server.  It's misleading to open the app and choose about and have it show the server version.

**Comment by lfbrock** [comment]
@Screndt does the issue reproduce for you on the [v3.4 Android App](https://play.google.com/store/apps/details?id=com.mattermost.mattermost&hl=en)?

We're working on building new native mobile apps, so updating the About menu is something we may be able to look at after they are built.

**Comment by lfbrock** [comment]
Hi @Screndt - I'm going to close this issue, I believe it should be fixed if you install the latest version of the android app. If you're still having issues, please re-open!
