### ISSUE TITLE
Mobile push notification definition of "away" should be "idle" instead of "not currently in the channel"

### ISSUE THREAD

**Issue by Screndt** [mattermost/platform#4104]
#### Summary
Mobile push notification definition of "away" should be "idle" instead of "not currently in the channel"

#### Steps to reproduce
1) Install the desktop app.
2) Install the mobile app.
3) Change the configuration under "Notifications -> Mobile push notifications -> Trigger push notifications when" to "Away or offline"
4) Get a message that would cause a mobile notification on a channel you currently have active.
5) Change channels.
6) Get a message that would cause a mobile notification on the channel you moved away from.
7) Return to the channel you got the notification on.
8) Take focus away from the Mattermost app.
9) Get a message that would cause a mobile notification on any channel.
10) Return to the app
11) Leave the desktop app until you are considered idle (not sure about the terminology here; but when your icon moves from green to yellow)
12) Get a message that would cause a mobile notification on a channel you currently have active.

#### Expected behavior
@4 No notification is sent.
@6 No notification is sent.
@7 No notification is sent (issue #4103).
@9 No notification is sent.
@10 No notification is sent (issue #4103).
@12 A notification is sent.

#### Observed behavior
@4 No notification is sent.
@6 A notification is sent.
@7 A notification is sent (issue #4103).
@9 A notification is sent.
@10 A notification is sent (issue #4103).
@12 A notification is sent.

**Comment by jasonblais** [comment]
Thanks @Screndt for the suggestion,

We have an open [forum post where we're looking for community's feedback](https://forum.mattermost.org/t/marking-users-away-from-mattermost-vs-away-from-computer/2173) on when a user should be set away (idle from Mattermost vs. idle from the computer).

Would you like to [share your suggestion on that thread](https://forum.mattermost.org/t/marking-users-away-from-mattermost-vs-away-from-computer/2173) as well? This way we can get everyone's feedback in one place.

One thing to note is that if we changed the behaviour on the desktop and mobile apps, the experience would be inconsistent with the browser (there isn't an easy way to differentiate who is away from Mattermost vs. from their computer on the browser).

**Comment by Screndt** [comment]
Commented there (and got some more ideas from reading that thread.  I'll leave this issue open in case they want to use this issue to work on it.

**Comment by jasonblais** [comment]
Thanks again @Screndt! I'll close this issue for now so we can concentrate [discussion on the forum thread](https://forum.mattermost.org/t/marking-users-away-from-mattermost-vs-away-from-computer/2173).

Appreciate the feedback, and hoping to hear more thoughts from the community.
