### ISSUE TITLE
clicking on desktop notification does not bring focus to the channel shown

### ISSUE THREAD

**Issue by Screndt** [mattermost/platform#4105]
#### Summary
clicking on a desktop notification brings focus to the app, but not the channel that the notification displayed

#### Steps to reproduce
1) Have the desktop app running.
2) Give focus to channel "foo".
3) Move focus away from the Mattermost app to any other window.
4) Get a desktop notification on channel "bar".
5) Click on the desktop notification.
6) Notice where focus is

#### Expected behavior
@6 Focus is given to the Mattermost app and channel "bar" is in focus.

#### Observed behavior
@6 Focus is given to the Mattermost app and channel "foo" is still in focus.

The same kind of auto-channel focus should apply for the mobile app, too.

**Comment by lfbrock** [comment]
Hi @Screndt, can you check what version of the desktop app you're running? The latest version is v1.4.0. 

If it's an issue in the latest version, can you report it in our desktop repo and let them know if it's on Windows or Mac? https://github.com/mattermost/desktop

**Comment by Screndt** [comment]
Thanks for sending me to the right place to report the issue.  It has already been reported there (it is apparently a known issue on Windows 7).
