### ISSUE TITLE
Content-Type incorrectly stated when downloading Microsoft Office file

### ISSUE THREAD

**Issue by MickaelWalter** [mattermost/platform#4108]
Note: this issue seems similar to #2336

#### Summary
When downloading an xslx file, the Content-Type header was set by the server to "ZIP File" resulting in a bad application choice from the navigator to open it (see attachments, sorry my system language is french).

#### Steps to reproduce
The issue happened with Mattermost v3.4.0 under Debian Jessie when downloading an uploaded xlsx file with preview activated under Firefox 49.0.1.

* Activate file previews
* Post a message with an xlsx file attached
* Download the file and observe the resulting file type

#### Expected behavior
Browser should state that an xlsx file has to be open.

#### Observed behavior
Browser states a compressed ZIP file has to be open.

#### Possible fixes
I'm not a Mattermost developper but it seems that a file command is issued and incorrectly returns ZIP file type (which is correct but inaccurrate). It may be possible to identify Office file when file type is ZIP and file extension is one of the followings (not explicit) : xlsx, docx, pptx. See this link to identify Office file types : https://support.office.com/en-us/article/Introduction-to-new-file-name-extensions-ECA81DCB-5626-4E5B-8362-524D13AE4EC1

![mattermostdlzipcontenttype](https://cloud.githubusercontent.com/assets/8983311/18914983/a6630fbc-858f-11e6-8338-2fc0354f7735.png)
![mattermostdlzip](https://cloud.githubusercontent.com/assets/8983311/18914985/a7cd4994-858f-11e6-9b5d-48ea08106533.png)

**Comment by lfbrock** [comment]
We're trying to reproduce this but having some trouble. If anyone else from the community is seeing this, please comment here and let us know? 

@MickaelWalter - when you say "Activate file previews", can you clarify what you mean? Are you talking about a setting in Mattermost, or somewhere else?

**Comment by MickaelWalter** [comment]
@lfbrock My bad for the "Activate file previews" option. In fact it is the "Link preview" option in the account advanced parameters. It should not affect this case.

Should the Mattermost global configuration be useful to you ?
My Mattermost server is behind a nginx proxy but I could reproduce by directly accessing the Mattermost listening port. The installation was recently upgraded from v3.2.0

**Comment by lfbrock** [comment]
Alright thanks @MickaelWalter, I took a look around and my guess is it's similar to the issue described here: https://blogs.msdn.microsoft.com/asiatech/2012/03/28/office-documents-will-be-recognized-as-zip-file-when-downloading-from-ie/

I've created a ticket for someone to look into fixing this, thanks for the report!
https://mattermost.atlassian.net/browse/PLT-4347

**Comment by jasonblais** [comment]
[We'll track in Jira](https://mattermost.atlassian.net/browse/PLT-4347) -- if anyone is interesting in helping submit a fix, please let us know.
