### ISSUE TITLE
Cross team notification

### ISSUE THREAD

**Issue by St-Ex** [mattermost/platform#4116]
#### Summary
Receiving notification from another team on the same server.

#### Steps to reproduce
1. Creates 2 team **foo**, **bar** on the same mattermost server 3.4
2. Open team **foo** on firefox/chrome
3. Send a message to a channel of team **bar** (from another user or from webhook)
4. You will receive a notification of message on team **foo** tab

#### Expected behavior
No notification from channels outside of displayed team

#### Observed behavior
Notification from channels/group outside of displayed team are fired
Moreover, it bypass channel notification preferences and always appears.

#### Possible fixes
Around, platform/api/post.go sendNotifications verify if on which team user is connected before alert

**Comment by lfbrock** [comment]
Hi @St-Ex, we're thinking of adding a teams sidebar for people who belong to multiple teams:

<img width="279" alt="screenshot 2016-09-30 11 44 32" src="https://cloud.githubusercontent.com/assets/9354841/19002942/5ae7187e-8703-11e6-87bf-1b99421ef959.png">

We would probably still keep the desktop notifications showing, but it would make it easier to see which team they're coming from. Wondering if this would solve your problem, or if you would also rather have a setting or command of some sort that prevents the cross-team desktop notifications from showing up?

The bypassing channel notifications sounds like a bug, I've asked if @esethna can try and repro/file a bug on it.

**Comment by St-Ex** [comment]
I'll take your ***or*** as inclusive one :smile: 
* This feature would be really. Yes, it would solve our problem on mattermost/desktop. There would be no need for multiple tab.
* I'm also in favor for a kind of setting to prevent cross-team notification. It gives you a way to focus on one team when you need (Ex: multi-project context, you don't want to leave/change setting of all your channel when your switching activities)

**Comment by lfbrock** [comment]
Haha yes, an inclusive or. Makes sense, I can see how a setting like that would be useful

**Comment by esethna** [comment]
Hi @St-Ex, I can confirm the repro on the bug ignoring channel notification preferences. I've created a ticket here: https://mattermost.atlassian.net/browse/PLT-4334

Agree with the setting for preventing cross-team notifications. Will include when we plan notification improvements.

Closing this ticket to track in JIRA.
