### ISSUE TITLE
Edit Message and Displayed Message Don't Correspond in Layout

### ISSUE THREAD

**Issue by alallier** [mattermost/platform#4121]
#### Summary
Edit message and displayed message don't correspond in the same layout resulting in confusing UI.

#### Steps to reproduce
Look at a message sent by you, then edit that  same message. Since the area that the edited message is displayed in is smaller than the original chat window word wrapping takes place. Therefore more lines will be present in the edit message dialog than the original message in the chat window. So if you notice an error on line 3 of a message in a particular place and want to change it, it's not necessarily in the same place when going to edit it. Thus making it not intuitive or quick to edit a message without re-reading and finding the new position of the text in the message.

Original message:

![originalmessage](https://cloud.githubusercontent.com/assets/13004518/18969737/699b7a74-865c-11e6-86d0-e3e8f13b2058.PNG)

Editing that same message:

![editamessage](https://cloud.githubusercontent.com/assets/13004518/18969756/76a7bafc-865c-11e6-902e-4829d6042b66.PNG)

#### Requested Expected behavior
The edit window should be an exact representation of the original message.

#### Possible fixes
1. The edit window should be an exact representation of the original chat
2. Have the message turn into a dialog box and allow editing
![editingamessage](https://cloud.githubusercontent.com/assets/13004518/18969773/86c736f6-865c-11e6-9453-8c015f941e5b.PNG)

**Comment by lfbrock** [comment]
Hi @alallier, I made a ticket here to look at increasing the width as a starting point: https://mattermost.atlassian.net/browse/PLT-4326

We have a longer term item here to spec in-line editing, but it's not priority for us right now.
https://mattermost.atlassian.net/browse/PLT-752

**Comment by jasonblais** [comment]
Thanks again @alallier for the feedback, we'll track the issue through the Jira tickets referenced above

**Comment by alallier** [comment]
Thank you
