### ISSUE TITLE
Slack import: "View Summary" downloads as txt rather than html.

### ISSUE THREAD

**Issue by arnuschky** [mattermost/platform#4125]
#### Summary
"View Summary" in import dialog downloads as txt rather than html.

#### Steps to reproduce
In 0.3.4, import a slack export. Then click on "View Summary". 
Using chrome version 53.0.2785.116 (64-bit)

#### Expected behavior
A new dialog box or window opens that displays some readable summary.

#### Observed behavior
Browser downloads a txt file, which contains html code.

#### Possible fixes
Seems to be a content-type issue.

**Comment by jasonblais** [comment]
@grundleborg would you have any thoughts on the reported issue?

**Comment by grundleborg** [comment]
I tried this out and agree that it downloads a TXT file, but I can't see any HTML in there when I test it, so I think this behaviour is correct. @arnuschky are you able to provide an example of the HTML code present in the summary file?

**Comment by lfbrock** [comment]
Going to close this issue, as I think it currently downloads as a TXT file intentionally - @arnuschky if you'd like to submit a [feature request](https://www.mattermost.org/feature-ideas/) to change this to an HTML page please feel free.

**Comment by arnuschky** [comment]
Apologies, I didn't manage to reply before (needed to redact the output files). 

It appears that I was getting an HTML output when the import was reported as failed. Hence my confusion. Here is the output:
[MattermostImportSummary.txt](https://github.com/mattermost/platform/files/531323/MattermostImportSummary.txt)

 When the import was reported as successful (but didn't do anything due to pre-existing users, see other issue), it indeed produced a TXT file:
[MattermostImportSummary2.txt](https://github.com/mattermost/platform/files/531322/MattermostImportSummary2.txt)
