### ISSUE TITLE
Inviting a user from another team

### ISSUE THREAD

**Issue by arnuschky** [mattermost/platform#4127]
Not sure if this is a feature or a bug, sorry if misplaced.

#### Summary
Inviting a new user into a team should offer the choice of users already present in other teams.

#### Steps to reproduce
In 0.3.4, create two teams. Invite and create user to team 1. Try to invite same user to team 2.
Using chrome version 53.0.2785.116 (64-bit)

#### Expected behavior
Mattermost should allow me to invite user already existing on team 1 to team 2. It doesn't make sense to invite someone from scratch every time when asking them to join another team (as long as said user already has an account on the server).

#### Observed behavior
I have to invite a user from scratch by sending an email.

#### Possible fixes
Preset a search box that allows to search among all users on all teams. Or selection box that shows all users on all teams (who aren't in current team, obviously).

**Comment by lfbrock** [comment]
Hi @arnuschky, would probably count this as a feature but definitely agree this is something we should add. I've queued it for our UX meeting Monday to discuss, is this something you would be interested on a PR for? 

As a workaround, you can use the "Get Team Invite Link" option to get a link to share with the person and direct message it to the person, and if they're logged in to the server and click the link they'll automatically be added to the team.

**Comment by arnuschky** [comment]
Thanks for the reply and for taking on this issue. I can't contribute a PR at this point, I suck in Javascript and my Go is nonexistant - sorry.

The workaround works fine!

**Comment by lfbrock** [comment]
No worries, glad the workaround helps!

**Comment by whyfrycek** [comment]
Hey there, the workaround works and obviously it is not the end of the world to add people one by one otherwise, but I ran into this again today and was thinking "I would love this feature", maybe you'll find time for this? I unfortunately don't have the skills to do it. In any case, thanks for creating Mattermost, we really love it :)

**Comment by UgoCloutier** [comment]
I don't have the skills to help but I just wanted to +1 this feature.
It would be awesome to simply have a second "section" when inviting new members: being able to select existing users in the db so they simply get added to the newly created team.
Most of our users have installed the app on their computer and phones, therefore when they get the link, most of the time they are not logged in, therefore the workaround does work, but it's not perfect.

**Comment by mateusmedeiros** [comment]
This is very essential IMO, and should be reopened.
The workaround may work, but it is only that, a workaround. As @UgoCloutier said, it's not perfect.

**Comment by jasonblais** [comment]
Thanks @whyfrycek @UgoCloutier @mateusmedeiros for the additional feedback!

We're in fact planning to make it easier to add users to a team with Mattermost 3.8 (released April 16th). You can take a look at the specification here, if you're interested: https://docs.google.com/document/d/16loc5SoOe0xWxpAS9XIKckOsoCWFyjFoXPjjpmPjVF4/edit

**Comment by mateusmedeiros** [comment]
@jasonblais That looks promising! I'll be patiently waiting for 3.8, then. :grin:
