### ISSUE TITLE
Data Folder setting inconsistent on CentOS7

### ISSUE THREAD

**Issue by InterHmai** [mattermost/platform#4133]
#### Summary
Migrated MM from Ubuntu 14 to CentOS7.

After the migration uploaded profile pictures, attachments didn't show up at all. 

Logs showed it couldn't access `./data/teams/wahteverlocationandfile`

#### Steps to reproduce
Ubuntu 14.04.4 and Mattermost 3.4.0 migrated to CentOS7 and Mattermost 3.4.0

#### Expected behavior
Uploaded profile pictures, attachments should show appropriately after migration.

#### Observed behavior
Mattermost was unable to read uploaded profile pictures or attachments after migration.

Error:
`[EROR] /api/v3/teams/randomteam/files/get/randomletters/randomletters/randomletters/somepicture.jpg:writeFileResponse code=404 rid=randomrid uid=randomuid ip=123.456.7.89 Could not find file. [details: path=teams/randomteam/channels/randomletters/users/randomletters/randomletters/somepicture.jpg`

#### Possible fixes
Relative location of data folder doesn't seem to work right for attachments after the migration.

Workarounds:
You can symlink `/mattermost/bin/data` to `/mattermost/data`

Another workaround is to use an absolute path to the data folder in your config.json instead of relative path.

**Comment by hmhealey** [comment]
Hi @InterHmai,

What is the `FileSettings.Directory` set to in your config.json? We had another user report permissions issues, but they had it set to `/data/` so it was trying to save files outside of the Mattermost folder.

**Comment by InterHmai** [comment]
Just the default setting

`"Directory": "./data/",`

**Comment by hmhealey** [comment]
Okay, so it's not that. Have you changed where you're running Mattermost from? I'm not familiar with CentOS, but our production install guides all involve cding into `.../mattermost` and then running it as `bin/mattermost` so the data directory is relative to `.../mattermost`.

**Comment by InterHmai** [comment]
Hey. I just checked on a separate installation on CentOS7 + Mattermost 3.3.0, fresh install no migrations, using the RHEL7+ production install guide with some CentOS7 tweaks (PostgreSQL 9.5 for CentOS, etc)

Looks like in that case too, with the default data directory settings, the data folder is created as `/mattermost/bin/data` instead of `/mattermost/data`

**Comment by jasonblais** [comment]
Thanks again @InterHmai and sorry for the delay in responding

We've [submitted a change to the RHEL 7 installation guides](https://github.com/mattermost/docs/pull/592) - wondering if we could have your help reviewing whether the change is sufficient in resolving the issue you reported?

**Comment by InterHmai** [comment]
Tested it out and the fix looks good to me. Thanks!

**Comment by jasonblais** [comment]
Thanks @InterHmai! Appreciate it!
