### ISSUE TITLE
[Help Wanted] After uploading a file with (CTRL+U) keyboard shortcut, set focus back to the text box

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4137]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

-----

#### Improvement: After uploading a file with (CTRL+U) keyboard shortcut, set focus back to the text box

**Current behaviour:**
1. Upload file using CMD or CTRL + U
2. Choose file with keyboard + hit enter to select
3. Hit enter to send the message

**Observed:**
Enter to send does not work, because the cursor is no longer in the message input box.

**Expected:**
Cursor should be in message input box after selecting the file.

**Comment by alsma** [comment]
I'm going to work on this

**Comment by jasonblais** [comment]
Thanks @alsma for letting us know that the issue has been fixed / doesn't reproduce.

Also tested on Windows 10 Chrome and Desktop App.
