### ISSUE TITLE
[Help Wanted] Bring up profile popover after clicking on a profile picture in a channel

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4138]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

-----

#### Improvement: Bring up profile popover after clicking on a profile picture in a channel

**Current behaviour:**
Currently you need to click on a person's name in center channel or the right hand sidebar to bring up a popover with more information as shown.

![image](https://cloud.githubusercontent.com/assets/13119842/19018576/7eda52f4-8835-11e6-817e-6af74c4c5357.png)

**Proposed change:**
Add an improvement where clicking on a person's profile picture in center channel or right hand sidebar brings up a profile popover.

**Comment by karuppiah7890** [comment]
So, you want an additional feature where in clicking a profile picture "also" brings up a profile popover ?

**Comment by brendanbowidas** [comment]
I'd like to take a stab at this, just sent a PR.

**Comment by jasonblais** [comment]
Fixed by #4144, thanks again @brendanbowidas!
