### ISSUE TITLE
[Help Wanted] Make channel limits configurable in the System Console

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4139]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

-----

#### Improvement: Make channel limits configurable in the System Console

Required changes:

1) Add a new field in [config.json > TeamSettings](https://github.com/mattermost/platform/blob/master/config/config.json#L31), which allows the maximum number of channels per team be configured by the system administrator

 - **Field setting**: MaxChannelsPerTeam
 - **Default value**: 2000

2) Add this setting to **System Console > General > Users and Teams** of the Mattermost user interface, below **Max Users per Team**, with

 - **Title**: Max Channels Per Team
 - **Default value**: 2000
 - **Help Text**: Maximum total number of channels per team, including both active and deleted channels.

![image](https://cloud.githubusercontent.com/assets/13119842/19018602/da7fdc18-8836-11e6-8269-db7a0c1a8c3b.png)

**Comment by rico042002** [comment]
I'm willing to contribute and help. Im a beginner, I started coding in July but I understand JS and JSON. The first bug seems like I can handle it fine, but that second seems a little tricky.

**Comment by jasonblais** [comment]
Awesome, thank you @rico042002 for your interest!

@DavidLu1997, would you be able to help with the second part, perhaps guide to that part of code where the setting would be added in the System Console?

**Comment by DavidLu1997** [comment]
Hello there @rico042002, you would have to modify a few things:

On the server side, you have to add it to the model, validate it, and set a default:
- [ ] Add the setting itself to the model in `model/config.go`, inside the `TeamSettings` struct [here](https://github.com/mattermost/platform/blob/master/model/config.go#L202).
- [ ] Add the default for it in `SetDefaults` also in `model/config.go` around [here](https://github.com/mattermost/platform/blob/master/model/config.go#L492)
- [ ] Check if the setting is valid in `IsValid` [here](https://github.com/mattermost/platform/blob/master/model/config.go#L935). I would not accept values < 1 (Town Square), but perhaps @jasonblais can offer more input on that.

On the client side, you have to create the setting, modify the state, and return it to the server
- [ ] Add the setting client-side in `webapp/components/admin_console/users_and_teams_settings.jsx` as a `TextSetting` (we're working on changing it to a `NumberSetting`), similar to [this](https://github.com/mattermost/platform/blob/master/webapp/components/admin_console/users_and_teams_settings.jsx#L98)
- [ ] Add it to `getConfigFromState` [here](https://github.com/mattermost/platform/blob/master/webapp/components/admin_console/users_and_teams_settings.jsx#L31) to return it to the server. You can set a constant in `webapp/utils/constants.jsx` and use `this.parseIntNonZero` with the constant as a default.
- [ ] Add it to `getStateFromConfig` [here](https://github.com/mattermost/platform/blob/master/webapp/components/admin_console/users_and_teams_settings.jsx#L39) to get it from the server

Lastly, you need to add it to `config.json` :+1: 

Remember to run `ESLint` and `gofmt`. Feel free to comment here or ping me `@david` on [Pre-Release](https://pre-release.mattermost.com/select_team) if you need anything :smile:

**Comment by rico042002** [comment]
Did not know the project was in C++. Im only a few months into the Tri-Force of the web! So sorry guys, do you have any assignments in HTML/CSS/JS?

**Comment by S4KH** [comment]
Willing to work on it. Need test user to login to the system.

**Comment by jasonblais** [comment]
@rico042002:

Not a problem at all! If you're looking for JavaScript, please check our open issues on the [Desktop Application](https://github.com/mattermost/desktop/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest) repository, which primarily involves JS.

If you're looking for something with HTML, would any of the issues in [our Docs repo](https://github.com/mattermost/docs/issues) sound interesting?

Really appreciate your interest in contributing! If you don't find anything interesting on the two repos, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) where we regularly post new tickets available for community contributions, including JS.

----

@S4KH:

Highly appreciated, thank you! 

> Need test user to login to the system.

We have a few [command line tools](https://docs.mattermost.com/administration/command-line-tools.html) available for user and team creation, would any of those be useful?

Let me know if you have any further questions

**Comment by S4KH** [comment]
@jasonblais:

When I create a new user it does not have access to **System console** (System console link is not shown). How can I get/create a user that can access to **System Console**?

**Comment by DavidLu1997** [comment]
@S4KH:
If you're running it locally for development, try doing a `make clean-docker`, then `make run`. Navigate to `localhost:8065` and you will be prompted to create an account, that account will have System Administrator privileges.

I hope this helps

**Comment by S4KH** [comment]
Followed steps above plus few extra things and finished. Now it seems saving `maxChannelsPerTeam` and shows saved value when reloaded. Is that a success criteria for the issue?

**Comment by DavidLu1997** [comment]
I'm not sure what you mean by that. The `maxChannelsPerTeam` setting should save as expected. When the page is reloaded after saving, the new setting should be displayed.

**Comment by S4KH** [comment]
I was just asking about the success criteria for the issue. 
Now it saves maxChannelsPerTeam and shows saved value when reloaded.

**Comment by DavidLu1997** [comment]
Oh yeah, that's it. You've got it 💯

**Comment by jasonblais** [comment]
Closing per #4154, big thanks @S4KH!!
