### ISSUE TITLE
[Help Wanted] Only show desktop notifications for channels you are not actively in

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4141]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

#### Improvement: Only show desktop notifications for channels you are not actively in

**Current Behavior**: Currently desktop notifications show up even if Mattermost is active and you are viewing the channel where notifications are coming from.

**Proposed Behavior**: If you're actively viewing a channel, do not show a desktop notification for messages posted in the channel.

**Comment by pepf** [comment]
I can do this 👍

**Comment by jasonblais** [comment]
Sweet, thanks @pepf!!

You're awesome :)

**Comment by pepf** [comment]
Question:
The user is currently active in say, "town square", but the window is not focused, or the browser is not showing the mattermost tab. If a message enters the town square channel, should the user be notified?

**Comment by jasonblais** [comment]
@pepf That's correct, if the window (or Mattermost browser tab) isn't in focus, a desktop notification should be sent when a user receives a message on that channel.

One concern that came to mind is that if a user has scrolled up the channel and receives a message, there won't be any indication that a new message was received. Any thoughts on that?

We had an old ticket that I reopened, which adds a [new message indicator](https://mattermost.atlassian.net/browse/PLT-1917), wondering if we would need to tie that ticket with here.

**Comment by pepf** [comment]
Ah thanks for the response, I already send a PR for the first part (which was quite easy), but Ill adjust it to incorporate the window/tab focus part as well.

And about the message indicator.. I have no experience with it, but there's a similar indicator in the left menu, perhaps this could be reused as a new message indicator?

**Comment by jasonblais** [comment]
Thanks @pepf! We'll test your PR, have queued it for review.

As for the message indicator, it could look something like this

![image](https://cloud.githubusercontent.com/assets/13119842/19363150/52384244-9157-11e6-99d6-6a1c16e77cd7.png)

Would that be something you'd be interested incorporating? We'd be happy to spec it out.

If not no worries, just something that I thought about.

**Comment by pepf** [comment]
Sure thing, sounds like a useful feature 👍

**Comment by jasonblais** [comment]
That would be awesome @pepf!!

I created a new Hacktoberfest issue for it, if you're still interested https://github.com/mattermost/platform/issues/4250

**Comment by jasonblais** [comment]
Closed via #4216
