### ISSUE TITLE
[Help Wanted] Reduce minimum length of team name from 4 to 2 characters

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4146]
Currently the team name must be a minimum of 4 characters, we want to reduce this to 2.

**Comment by jatinrajani** [comment]
@lfbrock 
I would love to contribute.Please guide me

**Comment by lfbrock** [comment]
Hi @jatinrajani, you can check out our [contribution guide](https://docs.mattermost.com/developer/contribution-guide.html#install-mattermost-and-set-up-a-fork) as a starting point, which includes a link to the [developer setup guide](https://docs.mattermost.com/developer/developer-setup.html). 

If you have questions about this specific ticket, feel free to [sign up to our Mattermost site](https://pre-release.mattermost.com/signup_user_complete/?id=b8230f359369ed80c46ecb8696901b3e) and ask questions in the Contributors channel?

**Comment by S4KH** [comment]
Working on this. Changed MIN_TEAMNAME_LENGTH from 4 to 2 in constants.jsx. And changed the error message 'Name must be **4** or more characters up to a maximum of 15' to **2**. 

One issue I am currently facing is one test failed. 

Here is the screenshot:
![selection_002](https://cloud.githubusercontent.com/assets/15072209/19060177/500c2b52-8a18-11e6-8217-04c9297258d0.png)

**Comment by S4KH** [comment]
Can somebody tell me where is the localization file? I looked to the stores/localization_store.jsx and I think purpose of the file is different what I am looking for?

**Comment by jasonblais** [comment]
Thanks for working on this @S4KH! We'll be testing your pull request shortly

You can find our localization files at [platform/i18n](https://github.com/mattermost/platform/tree/master/i18n) and at [platform/webapp/i18n](https://github.com/mattermost/platform/tree/master/webapp/i18n).

**Comment by jasonblais** [comment]
Closing per @4149, thanks @S4KH  for the pull request!
