### ISSUE TITLE
any plan to joing appconfig.org

### ISSUE THREAD

**Issue by jimiatworking** [mattermost/platform#4155]
Hi, I would like to know that does there any plan to make mattermost support AppConfig (http://appconfig.org/) that we could configu for Enterprises use. e.g: EMM support.

**Comment by jasonblais** [comment]
Thanks @jimiatworking, appreciate the feedback.

There are no plans at the moment - would you like to contribute this idea in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.  

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Closing the issue for now -- if you haven't yet, please help add your suggestion to the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general)

Thanks again @jimiatworking!
