### ISSUE TITLE
[Help Wanted] Slack import tool does not sometimes have debug messages indicating this is related to Slack

### ISSUE THREAD

**Issue by wget** [mattermost/platform#4161]
#### Summary

The Slack import tool does not sometimes have debug messages indicating this is related to Slack. 

For instance:  `"Failed to add user to channel: {{.Username}}\r\n"`
if a sysadmin reads this in the logs, he might think this is simply related to Mattermost not being able to add an user to a channel (security accesses not met, database issues, etc.), while is is just related to the Slack import tool.

Also, `"Merged user with existing account: {{.Email}}, {{.Username}}\r\n"`, are the email and username the user of Mattermost or the user of Slack? Not easy to understand for a sysadmin.

How are these logs appearing in the console? On a linux, are these logs stored in the systemd-journal? Or any custom made .log file in `/var/log/`.

If the logs are in the form (for example)
`Sep 12 04:04:09 myComputer Mattermost Slack Import[974]: Unable to merge user`
that's enough as there is in that case a `Mattermost Slack Import` statement indicating in which part of Mattermost the error happened.
#### Steps to reproduce

Importing users and channels from Slack where the import simply fails due to an error.
#### Expected behavior

Know the issue comes from the Slack import tool.
#### Observed behavior

N/A
#### Possible fixes

Simply rephrase the error/debug messages.

**Comment by jasonblais** [comment]
Hey @grundleborg, just confirming with you:

Are the log messages referenced above included in the Slack Import Summary.txt file or would they appear elsewhere in the console, such as in server logs?

**Comment by grundleborg** [comment]
I think the messages being referred to here go in the general mattermost logs (or in the console when doing a Slack import through the CLI).

Given that they can be mixed in with the other log messages, I think this is a good point, and we should ensure it's clear that all these messages are triggered by the Slack importer. 

@wget I'd be happy to do a pass through the Slack importer code and make sure all the messages are clarified, for you to review if that would be helpful?

**Comment by wget** [comment]
@grundleborg Actually like I said to @jason, I can do it myself, I have already digged to the code, being myself a dev.
What I just need is to reach a consensus.
Can I prefix all debug messages with a statement like `Mattermost Slack Import:` and follow it by the current (slightly modified error messages)? But I'm not stopping you to do it by yourself, if you want to :-)

**Comment by grundleborg** [comment]
@wget sounds good. Prefix should just be `Slack Import:` though, as the Mattermost bit is redundant given the message is going to go in the `mattermost.log` file anyway. Please can you tag me in the PR for this when you have completed it, so I can review the other modifications.

**Comment by wget** [comment]
@grundleborg As promised some times ago. Here you are.
