### ISSUE TITLE
Slack Importer fails silently to import a team with a purpose over 128 chars long.

### ISSUE THREAD

**Issue by grundleborg** [mattermost/platform#4168]
**Update**: There's multiple things going wrong here. Repurposing this bug to be the one for the purpose being too long in #random causing the channel to fail to import.

<hr>

**Original Report**
#### Summary

Slack Importer fails silently to import a team with a channel called Off-Topic (with key `offtopic`). There's no error in the logs or import summary. The channel just isn't there. It used to work fine but at some point in the last few weeks it's stopped working.
#### Steps to reproduce

Try and import a Slack team with a channel called Off-Topic (name: `offtopic`).
#### Expected behavior

The channel will be there in the team.
#### Observed behavior

The channel is not there.
#### Possible fixes

I think I recall there being some change that made channel display names unique (or something like that). Seems like it might be related to that, since there is already a channel called Off-Topic by default in a MM team.

Need to dig into it a bit more though to find out what's really going on, as I would at least expect an error to be logged to do with that channel. Not a silent failure.

**Comment by yangchen1** [comment]
Hey @grundleborg, I'm able to repro this on Chrome, although the name on the Slack channel has to specific be "Off-Topic" with the dash, and the failure is not silent for me. It seems like if there's any channel that is deleted before importing, and then imported with the exact same name, it will fail.

On a separate but potentially related note, random always fails to import for me for some reason, do you find that too?

Here's the ticket https://mattermost.atlassian.net/browse/PLT-4378

**Comment by grundleborg** [comment]
Urgh.

On further investigation, the issue here appears to be the length of the "channel purpose". Mattermost limits it to 128 chars, whereas the default random/off-topic purpose in Slack is more like 180 chars long. This causes the channel validity check to fail.

I'll take this to UX to discuss whether to a) increase the limit, or b) truncate the value imported from Slack.
