### ISSUE TITLE
Changing mattermost username from gitlab provider.

### ISSUE THREAD

**Issue by hackfanatic** [mattermost/platform#4171]
#### Summary

Changing gitlab username after a fresh gitlab-omnibus installation (working SSO) does not change the username in mattermost.
#### Steps to reproduce
1. My original username is User1
2. Change account username to user2 in gitlab.
#### Expected behavior
1. Username also changes to user2 in the mattermost instance.
#### Observed behavior
1. Username remains the same in mattermost (user1), white both username and user URL have been updated in gitlab.
2. Trying to change it within mattermost gives you the following message

```
This field is handled through your login provider. If you want to change it, you need to do so through your login provider.
```
#### Possible fixes

If you can, link to the line of code that might be responsible for the problem

Wondering if it's an incorrect setup here or there's anyone else facing the same issue.

Thanks!

**Comment by jasonblais** [comment]
@hackfanatic Thanks for the report!

Does the username get updated if you log out from Mattermost, then log back in?

**Comment by jasonblais** [comment]
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try [upgrading to the latest version](https://about.mattermost.com/download/). 

If the issue persists, please reopen this issue with the relevant information and we'd be happy to investigate it further.

**Comment by hackfanatic** [comment]
Hi @jasonblais , Sorry I missed the notifications to these messages.

Updated to latest gitlab omnibus package, 
- Logged out in both mattermost and gitlab instances
- Logged into gitlab, changed username
- Logged into mattermost and still have my original username from the initial setup moment.

Though think the mattermost version in the omnibus package though isn't the latest one so I'll revisit this ticket and let you know if this persists after the next update.

Thanks for writing 👍

**Comment by halberom** [comment]
I've hit this, currently using gitlab omnibus 8.13.3.  Change the username in gitlab, log out and back in (to both) has no change.

**Comment by oppin** [comment]
+1 Also experiencing this issue on latest GitLab Omnibus CE.

**Comment by jasonblais** [comment]
Sorry for my incredibly long delay here.

Created a Jira ticket here, which will be triaged on Monday.  https://mattermost.atlassian.net/browse/PLT-4844
 
Reopened this GitHub issue in the meantime

**Comment by TylerRick** [comment]
Ran into this with Omnibus GitLab 8.14.1 as well

**Comment by jasonblais** [comment]
We triaged the issue last week. You can track the status in Jira: https://mattermost.atlassian.net/browse/PLT-4844

Thanks everyone for the reports!
