### ISSUE TITLE
Mattermost keeps refreshing when SiteURL is set

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#4180]
#### Summary
When SiteURL is not empty, Mattermost keeps refreshing

#### Steps to reproduce
Set something in SiteURL (in our case https://team.animafac.net/).
(We also use an Apache reverse-proxy but I don't know if it has something to do with it.)

#### Expected behavior
Everything should keep working correctly

#### Observed behavior
The page keeps refreshing and I get this message in the browser console:
```
Detected version update refreshing the page
```

**Comment by jasonblais** [comment]
Thanks @Rudloff for the report. Have you upgraded to the latest version yet (v3.4)?

Also, how frequently does the page refresh? Which browser versions (Chrome/Firefox/IE11) and operating system (Windows/Mac/Linux) has this reproduced?

**Comment by Rudloff** [comment]
Yes, I am using 3.4.0.
It refreshes every few seconds.
I can reproduce with the desktop app and Firefox on Linux.

**Comment by Rudloff** [comment]
I tried again just now and I can't reproduce anymore so I'm closing this issue.
I will reopen if it happens again.

**Comment by jasonblais** [comment]
Thanks @Rudloff! We'll keep an eye out for this as well.

**Comment by pf-curtis-mitchell** [comment]
I experienced this issue too. Wondering if it has anything to do with load-balancing and a mismatch between the configured SiteURL and actual url?
