### ISSUE TITLE
[Help Wanted] When creating a new team, incorrect error displayed when trying a team URL with one character

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4184]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

----

When creating a new team, incorrect error displayed when trying a team URL with one character.

Repro:
1. Set System Console > Users and Teams > Enable Team Creation = True
2. Go to Main Menu > Create a New Team
3. Input team name "a new team"
4. Enter team URL "a"

Expected message: "URL must be X or more characters up to a maximum of 15"

Observed message: "Use only lower case letters, numbers and dashes. Must start with a letter and can't end in a dash."

![image](https://cloud.githubusercontent.com/assets/13119842/19222309/45bc1c70-8e23-11e6-94dd-6dc82b1b6360.png)

**Comment by fraziern** [comment]
I'm taking a look at this.

**Comment by jasonblais** [comment]
Thanks @fraziern for your interest! Highly appreciated!

**Comment by jasonblais** [comment]
Thanks again @fraziern, works great!

----

Tested on Windows 10, Chrome:
 1) Creating a team with less than 4 or more than 15 characters gives error message: `Name must be 4 or more characters up to a maximum of 15`
 2) Creating a team with special characters causes no issues
 3) Requirements for URL are met (use lowercase letters, numbers and dashes; must start with a letter and can't end in a dash; between 4 and 15 characters)

**Comment by jasonblais** [comment]
Closing issue by #4223, big thanks @fraziern!
