### ISSUE TITLE
[Help Wanted] If a webhook is sent to a Direct Message channel that has not been created yet, create the channel

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4185]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

----

Repro: Send an incoming webhook message to a direct message channel, with a user you have never direct messaged before.

Observed: Get a channel not found error.

Expected: Webhook should create the channel.

**Comment by alsma** [comment]
I've added possible fix in PR #4206

**Comment by jasonblais** [comment]
Closing by #4206, huge thanks @alsma!!
