### ISSUE TITLE
[Help Wanted] Render SVG files in file preview

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4186]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

We render JPG, GIF, PNG today, adding SVG would be nice.

**Comment by faiyaz26** [comment]
hey, I want to work on this issue. Found the way to solve it already. Will be sending PR in next few days. :)

**Comment by jasonblais** [comment]
Awesome, thanks @faiyaz26 for your interest! Highly appreciated!

**Comment by jasonblais** [comment]
Hey @faiyaz26, any updates? Just touching base to see if you're still working on the improvement.

**Comment by jasonblais** [comment]
Hey @faiyaz26 , thank you for working on this improvement, highly appreciated!

Just wanted to give you a heads up about upcoming dates for our 3.5 release that are relevant to this improvement:
 - Mon 10/31: last date community pull requests should be submitted for testing and review
 - Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4. Large pull requests may require an earlier merge date.

If you'd like to work on getting the SVG previews for 3.5, those would be the dates to meet -- just wanted to let you know so it doesn't come as a surprise if you were aiming for the 3.5 release.

Once again, big thanks for your help, really excited for this improvement!

**Comment by faiyaz26** [comment]
@jasonblais  Hey, It took quite some time to understand the codebase, initially I thought it won't be that hard. But now It seems that it is quite complex. So far, I have understood that mattermost converts any image type except svg to jpg. Currently if I am not wrong, there are no good golang library for doing that. What should I do now ?

**Comment by jasonblais** [comment]
Good question @faiyaz26 -- wondering if you'd like to join our [Developers community channel](https://pre-release.mattermost.com/core/channels/developers) where you can ask from other community members and the Mattermost core team?

They would be able to guide you better than myself,

Highly appreciate your interest for working on the improvement!

**Comment by jasonblais** [comment]
Hey @faiyaz26 

A couple of our team members [gave answers here](https://pre-release.mattermost.com/core/pl/3kion9ru63gafqymeknumus39e).

Were they useful? Anything else we can help with or investigate on our end?

**Comment by faiyaz26** [comment]
thanks. I will again dig into it. If I can't solve the issue, I think I have to leave the responsibility of this issue to others.

**Comment by jasonblais** [comment]
Thanks @faiyaz26, much appreciated! Would be glad to answer any further questions you might have along the way.

**Comment by faiyaz26** [comment]
Hello, I think I have to leave this issue for others.

**Comment by jasonblais** [comment]
Thanks @faiyaz26 for circling back, and for looking into it. Really appreciate it!

If you're interested, we have added [new issues open for contributions](https://github.com/mattermost/platform/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22Help%20Wanted%22).

**Comment by jasonblais** [comment]
Closed by #6045 by @kaakaa :)
