### ISSUE TITLE
[Help Wanted] Turn off [...] menu for System Messages

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4187]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

----

Currently System Messages do not allow replies, but still have a [...] menu containing Permalink/Delete.

![image](https://cloud.githubusercontent.com/assets/13119842/19222373/c5aab09e-8e24-11e6-9959-aa687df8c422.png)
*Above: A system message is posted after updating channel header. A [...] menu is available containing Permalink and Delete options*

We should remove the [...] menu completely, to prevent people from deleting System Messages and because permalinking to a System Message isn't necessary.

**Comment by alsma** [comment]
Hi! I would like to work on this.

**Comment by jasonblais** [comment]
Thanks @alsma for your interest! Great to hear :)

**Comment by Aka4Code** [comment]
Please if you can, make option to this, I use this menu also with system messages.

**Comment by jasonblais** [comment]
Hey @Aka4Code, thanks for the feedback!

Do you use the permalink option, or do you delete system messages?

**Comment by Aka4Code** [comment]
I delete system messages, it's useful sometimes.

**Comment by jasonblais** [comment]
Closing by #4198, huge thanks @alsma!!

@Aka4Code If you'd like to discuss it further, I encourage you to join our [Mattermost UX design channel](https://pre-release.mattermost.com/core/channels/ux-design) and offer your thoughts with other community members and the Mattermost team.

**Comment by jasonblais** [comment]
@Aka4Code we've reinstated the delete option for system messages https://github.com/mattermost/platform/pull/5113

It'll be available in Mattermost 3.7, with release on March 16th
