### ISSUE TITLE
[Help Wanted] Add a "Position" field to Account Settings and profile popover

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4188]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

There are three parts to this improvement:

1) Add **Position** setting in the general tab under **Main Menu > Account Settings > General**, so users can add information about their job title or position at the company.

The revised order they should be listed in is: Full Name, Username, Nickname, Position, Email, Profile Picture.

![image](https://cloud.githubusercontent.com/assets/13119842/19578036/dd7ae812-96e7-11e6-8306-9817092eb754.png)

2) When clicking **Edit** next to the **Position** setting, an input box should appear with help text `Tell your teammates what you do.`

![image](https://cloud.githubusercontent.com/assets/13119842/19578045/eba966d4-96e7-11e6-8804-e32c7f24f1f6.png)

3) If a user has specified their **Position** in **Main Menu > Account Settings > General > Position**, it should appear in the profile popover. If the user has specified their full name, the position should appear below it.

The profile popover appears when clicking on the user's profile picture either in center channel of right hand sidebar when replying to a message.

**Comment by enahum** [comment]
Maybe the"role" should be replace by another word to prevent confusion with
the permission roles

**Comment by andela-rsadiq** [comment]
Has this been issue been taken already? I would like to work on it.

**Comment by jasonblais** [comment]
Not yet @andela-rsadiq, please go ahead!

Highly appreciated!

**Comment by andela-rsadiq** [comment]
Great, I am on it already!

**Comment by yangchen1** [comment]
Hey @andela-rsadiq, just letting you know we've decided to change the name of the role field from "Role" to "Position", so we don't confuse it with permission roles! I'll update the screenshots and the ticket.

**Comment by andela-rsadiq** [comment]
noted! @yangchen1

**Comment by jasonblais** [comment]
Hey @andela-rsadiq , thank you for working on this improvement, highly appreciated!

Just wanted to give you a heads up about upcoming dates for our 3.5 release that are relevant to this improvement:
 - Mon 10/31: last date community pull requests should be submitted for testing and review
 - Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4. Large pull requests may require an earlier merge date.

If you'd like to work on getting the position field added for 3.5, those would be the dates to meet -- just wanted to let you know so it doesn't come as a surprise if you were aiming for the 3.5 release.

Once again, big thanks for your help, really excited for this improvement!

**Comment by jasonblais** [comment]
Hey @andela-rsadiq, just checking how you're doing here -- let us know if there's any tips we can provide?

**Comment by jasonblais** [comment]
A PR has been submitted and is undergoing dev review. https://github.com/mattermost/platform/pull/4632

@andela-rsadiq you're welcome to check our [other open Help Wanted issues](https://github.com/mattermost/platform/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22Help%20Wanted%22) if you're interested.

Would love to have you also [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can meet community members and the Mattermost core team.
