### ISSUE TITLE
Android keyboard is dismissed after sending message

### ISSUE THREAD

**Issue by rdbell** [mattermost/platform#4189]
#### Summary
Android keyboard dismisses after sending message

#### Steps to reproduce
Send a message in a DM/channel while on mobile layout in Android OS (may also occur on iOS)

#### Expected behavior
Keyboard should stay active, as is common with most messaging apps

#### Observed behavior
Keyboard is dismissed

#### Possible fixes
`$('.send-button').click(function() { $('#post_textbox').focus(); }`

This might dismiss/reactivate the keyboard back & forth. I'm not sure.

or...

Make the send button an `input type=text` that is styled to look like a button. Use JS to send focus back to `#post_textbox` after it's clicked. This most likely wouldn't ever dismiss the keyboard.

**Comment by lfbrock** [comment]
Hi @rdbell, agree that makes sense - made a ticket here to track the issue: 
https://mattermost.atlassian.net/browse/PLT-4376

Is this something you'd be interested in working on?

**Comment by lfbrock** [comment]
Going to close this issue and will track it in Jira.
