### ISSUE TITLE
[Help Wanted] React Native Mattermost mobile apps with Redux

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4190]
Our open source framework for new official React Native mobile apps is shipping after October 31. 

We wanted to [share our plans early](http://forum.mattermost.org/t/react-native-roadmap/2339) and invite anyone interested in helping with React Native to discuss here, so we can work together in future. 

If there's community members with Redux and React experience who want an early preview, please let us know. 

You can also join our [Mattermost Native Apps discussion channel.](https://pre-release.mattermost.com/core/channels/native-mobile-apps)

PS: Since we're not planning to start community work until after October 31, no Hacktoberfest label on this ticket.

**Comment by joepsz** [comment]
I have experience with Redux and React. Would like to invest some spare time in helping out with the Native app.

**Comment by lfbrock** [comment]
Hi @joepsz - thanks for your interest! We're still working on getting the basic framework done, 
we'll make another announcement when it's ready for community contributions. 

The initial work is being done in this repo if you want to check it out: https://github.com/mattermost/mattermost-mobile

**Comment by ivernus** [comment]
Can this be closed?

**Comment by csduarte** [comment]
The apps have been released. 

Contribute to their growth at https://github.com/mattermost/mattermost-mobile 
Download at [Android Play Store](https://play.google.com/store/apps/details?id=com.mattermost.rn) or [Apple store](https://itunes.apple.com/us/app/mattermost/id1257222717?mt=8)
