### ISSUE TITLE
Setup session without Oauth or mock user

### ISSUE THREAD

**Issue by ZJvandeWeg** [mattermost/platform#4191]
#### Summary
For API access for actions another application or system wants to perform there is no good mechanism at this time to get a session token.

For example: with SSO enabled for GitLab there is no way for GitLab to perform actions without knowing the plaintext password of a user or this user having to go through OAuth actions and perform operations as this (mock) user.

I'd be great if there would be mechanism to get a session for another system, without the need for a mock user or the like.

#### Steps to reproduce
SSO with GitLab, and we're investigating how to set up a session to use the API endpoints Mattermost provides. Without the need for a mock user, or an OAuth dance (UX wise we'd like to skip this)

#### Possible fixes
Not really sure, a magic token seems not really elegant, but should work.

Please let me know if you need anything else from me. :)

**Comment by ZJvandeWeg** [comment]
cc @ayufan

**Comment by lfbrock** [comment]
Hi @ZJvandeWeg, 

So you'd like to be able to get a generated API key and use that to access our APIs? 

A couple of options would be: 

1. We could add a page to the Integrations section that lets any user grab an API key that they can give to third party systems to access APIs on their behalf
2. We could add a tab to the System Console that only lets the System Admin grab that API key, which will let the third party basically do whatever it wants

Would either of those be what you're looking for?

**Comment by ZJvandeWeg** [comment]
Thanks for the reply @lfbrock, I think both would work. Although a million ❤️  if its available to obtain without going through the UI.

So by CLI would be awesome, although as a start I could certainly live with having the admin copy-pasting a token. This would probably be more reusable for the rest of the community.

**Comment by lfbrock** [comment]
Alright @ZJvandeWeg I made a [ticket to track this](https://mattermost.atlassian.net/browse/PLT-4386), it will be discussed further in the Developer Meeting next Wednesday - feel free to join the Developers channel on our [daily builds site](http://pre-release.mattermost.com).

**Comment by ZJvandeWeg** [comment]
Thanks, Ill try to join that. 

I am registered at your server already though 😉

**Comment by lfbrock** [comment]
great glad to hear it! :)

**Comment by ZJvandeWeg** [comment]
@lfbrock Could you tell me why this is closed? The workaround is far from ideal and leaves a plaintext for admin access on the Mattermost instance, which should IMO be avoided?

What is your take on this?

**Comment by lfbrock** [comment]
Hi @ZJvandeWeg - I wasn't in the meeting, but my understanding was that this was discussed in the developers meeting last week and it was decided it was a security issue? 

If the work around isn't sufficient, it's probably easiest to discuss it in the developers channel what other options are and we can make a new ticket based on the results of the discussion,

**Comment by Analect** [comment]
@ZJvandeWeg 
Did you ever manage to get a solution to be able to access the mattermost API as a logged-in user via Gitlab SSO?

**Comment by ZJvandeWeg** [comment]
@Analect Yes I was, hope you can read Ruby :)

https://github.com/gitlabhq/gitlabhq/blob/master/lib/mattermost/session.rb#L10

**Comment by Analect** [comment]
@ZJvandeWeg 
Thanks!  My Ruby skills are non-existent.
I can see this is in master, do you know if it has been folded into any recent released versions of gitlab?

Your code snippet references `/api/v3/oauth/gitlab/login` which appears to be same thing that's getting called against the mattermost API, when logging in to mattermost using gitlab (see below).

![image](https://cloud.githubusercontent.com/assets/4063815/22506511/bf5e1f4c-e878-11e6-83a1-947c70d077b5.png)

Is this a valid endpoint against the gitlab API or the mattermost API? ...  

I tried a POST request against both:
`https://gitlab.mydomain.com/api/v3/oauth/gitlab/login` and `https://mattermost.mydomain.com/api/v3/oauth/gitlab/login`
 with a JSON payload of `{"login_id": "gitlab_username", "password": "gitlab_password"}`, hoping to get back a token in the header ... but no joy.

How does this work? Thanks.

**Comment by Analect** [comment]
@ZJvandeWeg .... am I right in thinking your session.rb is included in [8.17-pre](https://github.com/gitlabhq/gitlabhq/releases/tag/v8.17.0.pre) ... and does this expose an endpoint on the gitlab API to get a session token for mattermost API?  Thanks.

**Comment by ZJvandeWeg** [comment]
@Analect We don't expose anything to other consumers. If you have an interesting use case you could open an issue on GitLab.com, but this might have security implications, so we should discuss it thoroughly.

**Comment by Analect** [comment]
@ZJvandeWeg 
I've added a thread to an [issue](https://gitlab.com/gitlab-org/kubernetes-gitlab-demo/issues/14#note_22585884) back in the kubernetes-gitlab-demo to see if they have a better sense if your code can potentially expose a session token to work against the mattermost API that perhaps can be passed to a 'secret' variable in the context of a kubernetes cluster and then potentially be levered by apps in the cluster that need to access the mattermost API.
