### ISSUE TITLE
Auto focus on text input doesn't work correctly

### ISSUE THREAD

**Issue by Grazfather** [mattermost/platform#4202]
Saw that it was a FR that was apparently done [here](https://mattermost.uservoice.com/forums/306457-general/suggestions/10190166-auto-focus-cursor-to-message-typing)

It doesn't work quite often.

#### Summary
Once focus from the text input is lost (e.g. to click a link), typing does not refocus it.

#### Steps to reproduce
Click in chat window, start typing.

#### Expected behavior
Focus moves to text input so that I can enter text. Running latest public.

#### Observed behavior
Nothing

**Comment by lfbrock** [comment]
Hi @Grazfather - we have a [Help Wanted] GitHub issue here if you'd like to join the discussion on how best to do this: https://github.com/mattermost/platform/issues/4142

**Comment by Grazfather** [comment]
@lfbrock Perfect thanks.
