### ISSUE TITLE
Is the LDAP integration code closed source?

### ISSUE THREAD

**Issue by kevinlong206** [mattermost/platform#4205]
Sorry if this is the wrong forum, but just wondering.

I know mattermost has the enterprise edition packages + support etc.

I'm looking to roll my own w/LDAP, wondering if this is possible.

Thanks!

**Comment by it33** [comment]
LDAP isn't part of open source Team Edition, as it's considered a corporate feature and part of the commercial extension. 

You're welcome to fork the Mattermost server and use it under its open source license. If you're offering it to other people just make sure to remove the Mattermost logos and mentions of the Mattermost name per the [trademark guidelines.](https://www.mattermost.org/trademark-standards-of-use/)
