### ISSUE TITLE
[Help Wanted] Update the browser tab title when in the System Console

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4218]
Looking for help fixing a bug where the browser tab title doesn't update properly.

Repro Steps: 
1. Sign in to a Mattermost team and open a channel
2. Go to the three dot Main Menu, and select System Console

Observed: The browser tab title doesn't update, and still says the name of the last channel you were on. 
<img width="317" alt="screenshot 2016-10-13 18 28 58" src="https://cloud.githubusercontent.com/assets/9354841/19369373/f26a5b88-9172-11e6-8412-f277e92f1625.png">

Expected: Update the browser tab title to be "System Console - " followed by the site name. The "System Console" portion should be localizable.

**Comment by aszx87410** [comment]
I can work on this.

**Comment by jasonblais** [comment]
Closing by #4221, huge thanks @aszx87410!!
