### ISSUE TITLE
User name becomes lower-case on signup

### ISSUE THREAD

**Issue by hko-gh** [mattermost/platform#4220]
Dear all,
During signup I chose a user name with first character upper case. Afterwards I was unable to log in with that same user name and I found, after logging in with my e-mail address, that the user name became all lower-case.
Either that should be avoided or stated or enforced appropriately at the signup page.
Best regards

**Comment by lfbrock** [comment]
Hi @hko-gh - we have a ticket here to fix the login so it will work if you enter the username/email in upper case or lower case letters. 
https://mattermost.atlassian.net/browse/PLT-4313

I think automatically lowercasing the username on the sign up page was a [design decision](https://mattermost.atlassian.net/browse/PLT-41) based on the principle that we want to be "forgiving", but fixing the log in page to allow upper or lowercase letters should fix your issue.
