### ISSUE TITLE
Replace hardcoded numbers in error strings with constants

### ISSUE THREAD

**Issue by fraziern** [mattermost/platform#4224]
#### Summary

Occurred to me while working on #4223 - new team names are tested against constants for length limits, but the error strings have the current value of those constants hardcoded in. 
#### Possible fixes

Should the error strings use template strings or some other way to remove the hard-coding?

**Comment by jasonblais** [comment]
Sorry for the late reply @fraziern,

What do you mean by template strings?

Removing the hard-coding and moving to constants or the use of {variables} would be better, agreed

**Comment by lfbrock** [comment]
Hi @fraziern - going to close this issue, please re-open if you'd like to discuss further?

**Comment by fraziern** [comment]
@lfbrock @jasonblais sorry for *my* late reply - see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals 

Point being, I'm happy to look at putting together a PR for this, since it sounds like there's some interest.

**Comment by hmhealey** [comment]
Thanks for your interest in this, @fraziern. JS template literals won't work with [react-intl](https://github.com/yahoo/react-intl), but it supports its own templating.

If you replace the call to `Utils.localizeMessage` with a react-intl `FormattedMessage` ([example](https://github.com/mattermost/platform/blob/master/webapp/components/emoji/components/add_emoji.jsx#L79)), you can then specify a values property like this:
```jsx
this.setState({nameError: (
    <FormattedMessage
        id='create_team.team_url.charLength'
        message='Name must be {minimum, number} or more characters up to a maximum of {maximum, number}'
        values={{
            minimum: 4,
            maximum: 15
        }}
    />
)});
```

**Comment by fraziern** [comment]
Nice, thanks for pointing me in the right direction @hmhealey, I'll take a look at this.

**Comment by jasonblais** [comment]
Thanks @fraziern, many thanks!
