### ISSUE TITLE
Emojis are too small

### ISSUE THREAD

**Issue by erikpi** [mattermost/platform#4233]
#### Summary
Custom emoji restrictions are too small, both in filesize and resolution.

#### Steps to reproduce
Its because of the following code in https://github.com/mattermost/platform/blob/master/api/emoji.go

const (
	MaxEmojiFileSize = 64 * 1024 // 64 KB
	MaxEmojiWidth    = 128
	MaxEmojiHeight   = 128

#### Expected behavior
Please increase to something that is more proper for gifs and stuff in the year 2016

**Comment by lfbrock** [comment]
@erikpi - is this for custom emoji or all emoji? We designed the custom emoji to be the same size as our other emoji. 

If you think these should be larger, can you file a [feature request](https://www.mattermost.org/feature-ideas/) on it? 

I think the options in my mind would be to: 

1. Make all emojis slightly larger
2. If you make a post containing only emoji, make the emojis a larger size (we would then be able to make them larger than the text in a post, without having to worry about the spacing between lines being affected)

**Comment by erikpi** [comment]
Hey,

This is for custom emojis, i think the standard-ones are a good size and need no change. 
What is want is to be able to upload bigger, custom emojis, this is specifically for gifs, because gifs at 128x128 pix with 1024 kb limit is very small / short

Real world case, if we want to make [this ](http://devopsreactions.tumblr.com/post/151281670953/trying-the-first-prototype-good-enough) into a emoji, we can't. because it's both bigger in resolution and filesize than the current restictions.

1. Not needed, it looks good as it is.
2. Is is possible to control the emoji-size a bit, by prefixing the message with # -> #### (h1 -> h4) 

I think the code mentioned above only controls what you can upload and use as custom emojis, it should not affect current emoji-sizes :)

**Comment by jasonblais** [comment]
Thanks @erikpi, we just added a Hacktoberfest issue that would allow users to upload custom emojis larger than 64kb, but scales them down to the appropriate size: https://github.com/mattermost/platform/issues/4235

Would this cover your request? And would you be interested in submitting a pull request for it?

**Comment by erikpi** [comment]
Hello! Sounds awesome!! 👯 You can close this one and i will keep track of #4235

**Comment by jasonblais** [comment]
Awesome! Sounds good, thanks again @erikpi

**Comment by andersaamodt** [comment]
Can we add an option to increase the size of emoji reactions please? My team has been uploading memes and pictures of our faces to use as emojis, so if they were a tiny bit bigger they would be much more legible. Could be a personal setting or a serverwide setting.
