### ISSUE TITLE
[Help Wanted] Allow custom emojis larger than 64kb, and scale them down to the appropriate size

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4235]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.
## 

Currently custom emojis have a very small size limit (64 KB, 128x128 pixels). 

For improved usability, allow users to 
- upload larger images, and
- scale the size down to match other system-default emoji

([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4277))
## 

Some tips for anyone who would like to work on this:

You can use the code for creating file thumbnails as a reference point for this. Some additional things to consider though are:
- Instead of manually calculating the aspect ratio and figuring out which dimensions need to change when resizing the image like we do there, you might be able to use `resize.Thumbnail` to do it for you.
- To resize an animated gif, you'll need to resize each individual frame separately and recombine them back into a single gif. Once you detect that the file is an animated gif, you can then use `gif.DecodeAll` to get the individual frames, resize them down, and then put them back together using `gif.EncodeAll`.

**Comment by iraquitan** [comment]
Hi, I'd like to give it a try.

**Comment by jasonblais** [comment]
Sweet, highly appreciated @iraquitan!

**Comment by erikpi** [comment]
Hello, please also make sure this works for gifs! :) <3

**Comment by jasonblais** [comment]
Hey @iraquitan, thank you for working on this improvement, highly appreciated!

Just wanted to give you a heads up about upcoming dates for our 3.5 release that are relevant to this improvement:
 - Mon 10/31: last date community pull requests should be submitted for testing and review
 - Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4. Large pull requests may require an earlier merge date.

If you'd like to work on getting the proper custom emoji scaling added for 3.5, those would be the dates to meet -- just wanted to let you know so it doesn't come as a surprise if you were aiming for the 3.5 release.

Once again, big thanks for your help, really excited for this improvement!

**Comment by jasonblais** [comment]
Hey @iraquitan , just checking how you're doing here -- let us know if there's any tips we can provide?

**Comment by iraquitan** [comment]
Hi @jasonblais, sorry the delay, I was kinda busy. Yes, you can provide me some tips. I think I misunderstood how this should work. I was trying to resize the image on the fly, so I was finding some difficulty in decoding the image bytes into the Image object itself so I can use in a function like in `generateThumbnailImage` function. But I think the correct way to do this is to first upload the image and then get and resize the image to store again. Am I wrong? Also, what `MaxEmojiFileSize` should I use?

**Comment by hmhealey** [comment]
Hi @iraquitan,

I'd expect the file to be resized when it's saved to the server in [uploadEmojiImage](https://github.com/mattermost/platform/blob/master/api/emoji.go#L136). Once it's loaded into `buf`, you can copy it into a `[]byte` by calling `buf.Bytes()` and then do whatever you need with the raw bytes. In this case, you'll be getting the image dimensions from `image.DecodeConfig` and then if it's between the current max dimensions and the [`MaxImageSize`](https://github.com/mattermost/platform/blob/master/api/file.go#L58), you'll use [`image.Decode`](https://golang.org/pkg/image/#Decode) to get it into a format that the [image resizing library](https://github.com/nfnt/resize) can deal with. You'll still need that special handling of animated gifs as mentioned above, but it'll be a similar process.

If you've got any questions about this, feel free to let me know

**Comment by knalb** [comment]
What about the ability to not scale down to system-default size as well? I'm all for uniformity of emoji size, but I like the idea of having some "huge" ones as well.

**Comment by jasonblais** [comment]
@knalb You can use existing markdown formatting to display larger images in messages.

Example:

![image](https://cloud.githubusercontent.com/assets/13119842/20025054/394468be-a2c1-11e6-9750-0ee159fbfb71.png)

**Comment by knalb** [comment]
I am aware of that markdown functionality.  I was actually thinking of the
ability to have the emoji displayed in the native resolution for the image,
whatever that is.  For example, if I upload a 550x850 image of
RANDOM_THING, I'd like that to be displayed without resizing at all,
similar to how the image preview works now when you paste in a url.  I
imagine this as an option available at the time of creation/upload of the
emoji, to differentiate it from "normal" size.

**Comment by jasonblais** [comment]
Thanks @knalb, appreciate your feedback.  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Closed via #4447
