### ISSUE TITLE
[Help Wanted] Add a progress bar for file uploads

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4236]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

Add a progress bar for file uploads ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4276))

![image](https://cloud.githubusercontent.com/assets/13119842/19439827/9108ee3a-944d-11e6-8534-5d97b2211909.png)

**Comment by tudorgergely** [comment]
Hi, I'd like to work on this. Anything special I have to do before starting working? I joined the community channel a few minutes ago but I am a little lost :). Thanks

**Comment by jasonblais** [comment]
That's great to hear @tudorgergely, thanks for your interest!!

As a first step, you can review our [Contribution guidelines](https://docs.mattermost.com/developer/contribution-guide.html) to help set up your environment and review a few steps to submit a pull request

**Comment by dhruvdutt** [comment]
You would like to try this one.

**Comment by pan-feng** [comment]
look for #5123  I had pull request

**Comment by lfbrock** [comment]
Closing this for now, we're looking at redesigning file uploads and may redesign this as well + reopen

**Comment by Temeez** [comment]
Something like this is definitely needed. Currently there is no way to know if the file is actually being uploaded or not (I do not trust the "file is being uploaded" animation box"). Either a percentage or upload speed bar should be added.
