### ISSUE TITLE
[Help Wanted] Do Not Disturb mode

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#4241]
If you're interested in contributing this feature, please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.
### Functionality

When Do Not Disturb is on, 
1. Desktop, push and email notifications for the team are not sent.
2. Unread channels in the left-hand-side still bold and show mention jewels as normal.

When Do Not Disturb is turned off, notification preferences for desktop, email and push return to the state they were in before.
### User Interface

Add an online indicator to the profile picture in the header. The online indicator shows the current online status of the account on the team. 

EDIT: Currently the profile picture is hidden from the top left if it hasn't been manually set yet. Change it so the profile picture is always shown in the top left, even if it is the default generated profile picture.

![image](https://cloud.githubusercontent.com/assets/14333569/19451377/45aa768a-946a-11e6-87a0-4cb608328d48.png)

Clicking the status icon or the profile picture offers a dropdown menu to select a status or go into DND mode.
1. First dropdown opens the options for "Online", "Away", "Offline", "Do Not Disturb >".
2. Hovering over "Do Not Disturb" opens a secondary dropdown with the options: "1 hour, "2 hours", "4 hours" "8 hours", "24 hours", "Indefinitely".

![image](https://cloud.githubusercontent.com/assets/14333569/19451390/549fe936-946a-11e6-88df-3e20029f1007.png)

When Do Not Disturb mode is on, the status icon is overlayed with a "z" (see mock-up) in the team header and in the direct message list on the left-hand-side.

![image](https://cloud.githubusercontent.com/assets/14333569/19451406/615d1446-946a-11e6-8ec4-698cc1994a03.png)
### Slash Command
1. "/dnd" will silence notifications for the whole team by turning on DND mode. 
   - System message: "You will not receive notifications for this team until Do Not Disturb is turned off ."
2. "/dnd X" will silence notifications for the whole team for a specified number of hours, X.
   - System Message: "You will not receive notifications for this team for X hours or until Do Not Disturb is turned off."

DND mode is turned off by changing your status to anything other than "Do Not Disturb". This can be done using the user interface dropdown or the slash commands `/online`, `/away`, `/offline`

**Comment by alsma** [comment]
I'm going to work on this

**Comment by esethna** [comment]
Updated the spec on how to turn off DND. 

![image](https://cloud.githubusercontent.com/assets/14333569/19495995/cd95e902-9542-11e6-9c27-f7b79406d558.png)

**Comment by jasonblais** [comment]
Hey @alsma, thank you for working on this improvement, highly appreciated!

Just wanted to give you a heads up about upcoming dates for our 3.5 release that are relevant to this PR, as outlined [in our release process](https://docs.mattermost.com/process/release-process.html):
 - Wed 10/26: last date to submit a pull request for major features
 - Mon 10/31: last date any major features will be merged for 3.5 release [assuming the pull request was submitted by the 26th]

If you'd like to work on getting "Do Not Disturb" in for 3.5, those would be the dates to meet -- just wanted to let you know so it doesn't come as a surprise if you were aiming for the 3.5 release.

Once again, big thanks for your wonderful work, really excited for this feature!

**Comment by jasonblais** [comment]
Hey @alsma, wondering how you're doing? Looks like you had a great start earlier: https://github.com/alsma/platform/commit/d852a441c1e28a873ce32da1b2456362a268f297

Anything I can help you with?

**Comment by jasonblais** [comment]
re-created here https://github.com/mattermost/platform/issues/5905
