### ISSUE TITLE
[Help Wanted] Channel Mute

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#4242]
This ticket is for offering an option to turn off all notifications from a channel and only show unread if the user has been mentioned. 

If you're interested in contributing this feature, please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

### Functionality

When a channel is muted:
1. "Mute Channel" in channel notification preferences is set to "On" - all other channel notification preferences are hidden.
2. Desktop notifications are not sent for the channel.
3. The channel is only marked unread if the user is mentioned.
4. Push and Email Notifications are not sent for the channel.
5. Channel opacity in the left-hand-side and channel header is decreased.
6. Muted channels are sorted below non-muted channels in the left-hand side (secondary sorting of muted channels is done alphabetically)

When a channel is unmuted:
1. "Mute Channel" is set to "Off" - all other channel notification preferences are shown. 
2. "Send Desktop Notifications" and "Mark Channel Unread" settings return to the state they were in before muting. 
3. Push and Email Notifications are sent according to the Account settings defaults.
4. Opacity of the channel name is increased to normal in the left-hand-side and channel header
5. Channel is resorted among the non-muted channels alphabetically.

![image](https://cloud.githubusercontent.com/assets/14333569/19452381/0d64cdd0-946e-11e6-9735-1a95e00e45fa.png)

### Slash Command
1. "/mute" mutes the current channel
   - System message: "You will not receive notifications for [Channel UI Name] until Channel Mute is turned off."
2. "/mute" when the current channel is already muted will unmute the current channel
   - System message: "[Channel UI Name] is no longer muted."
3. "/mute !channel-handle" mutes the channel listed
   - System message: "You will not receive notifications for [Channel UI Name] until Channel Mute is turned off."
4. "/mute !channel-handle" when the listed channel is already muted will unmute the listed channel.
   - System message: "[Channel UI Name] is no longer muted."

NOTE: Slash command refers to Mattermost slash commands: https://docs.mattermost.com/developer/slash-commands.html

### User Interface
1. Add a setting to Channel > Notification Preferences, at the top. When "On", all other channel notification preferences are hidden. 
   
    "Mute Channel"
    [ ] On
    [ x ] Off
   
    Help Text: Muting turns off desktop, email and mobile push notifications for this channel. The channel will not be marked as unread unless you're mentioned.
2. When a channel is muted, a clickable icon appears next to the channel name in the channel header (see mock-up). 
   - on-hover text: "Unmute"
   - Clicking the icon unmutes the channel and the icon disappears.

![image](https://cloud.githubusercontent.com/assets/14333569/19452061/b4306108-946c-11e6-85ff-4563c1663876.png)

**Comment by esethna** [comment]
Reviewing design, will reopen a new ticket for this after design is approved

**Comment by slechta** [comment]
Is there any progress? Thanks.

**Comment by jasonblais** [comment]
Hey @slechta - channel mute was released in Mattermost v4.9! :)
