### ISSUE TITLE
[Help Wanted] Group Messaging

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4247]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Current Behavior**: Currently if you want to have a group conversation with multiple people, you need to create a Private Group. This means the channel sidebar can start to get filled with many Private Groups that were only used for one quick conversation. 

**Proposed Behavior**: Add a new Group Messaging feature, so people can create direct message channels with multiple users for quick group conversations. 

Detailed spec: https://docs.google.com/a/mattermost.com/document/d/1tjXYgaV37oLZOptkq3v3dXAghO810HQxzhU9cE4k9oM/edit?usp=sharing

<img width="558" alt="screenshot 2016-10-17 19 41 49" src="https://cloud.githubusercontent.com/assets/9354841/19459547/c9783ace-94a1-11e6-9be4-92c5023e4454.png">

**Comment by JrPribs** [comment]
I'm interested in creating this feature. I've requested access to the detailed spec if you could provide access, thanks!

**Comment by lfbrock** [comment]
sorry about that, @JrPribs you should be able to see it now

**Comment by richa-coder** [comment]
I want to contribute to it.

**Comment by jasonblais** [comment]
@JrPribs @richa-coder Wondering if you wanted to join our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to discuss the feature further?

This is a fairly large pull request, so having an easy channel to ask questions either about the design or the development itself with others might be useful. I'd be happy to connect you with the product manager owning the feature, and one our core devs.

Many thanks for both of your interest, hugely appreciated!

**Comment by JrPribs** [comment]
@jasonblais definitely I actually tried to join it but it required an invite. If you can send the invite that'd be great I know it'll be helpful since this is my first time in this codebase

**Comment by jasonblais** [comment]
Really sorry about that, there was an error with the signup links, which has now been fixed. You should be able to create an account now.

@JrPribs and @richa-coder please let me know if you've joined the [community channel](https://pre-release.mattermost.com/core/channels/tickets) and I'll connect you with our product manager owning the feature. You can simply mention me by including `@jason` in your message.

It'll also be an excellent place to ask questions from the Mattermost core developers.

**Comment by richa-coder** [comment]
Ya sure,I would love to join the channel.
When logging in,i am getting this error;

The invite link was invalid. Please speak with your Administrator to
receive an invitation.




[image: --]

Richa Singh
[image: https://]about.me/richa-singh
<https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by jasonblais** [comment]
Thanks @richa-coder for your interest! 

We fixed this error over the weekend, you should be able to join the site again.

**Comment by jasonblais** [comment]
Hey @JrPribs and @richa-coder, did you manage to join the [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets)? Any further issues in the sign up process?
