### ISSUE TITLE
[Help Wanted] Add support for Slash Commands in right hand side

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4249]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

Currently slash commands (e.g. `/shrug`) only work in the center channel, and not in the right hand sidebar.

This issue is to add support for slash commands also on the right hand sidebar ([link to Jira ticket](https://mattermost.atlassian.net/browse/PLT-1598)).

Note: Right hand sidebar can be opened by clicking on the [...] menu next to a message and choosing "Reply"

**Comment by kaakaa** [comment]
I'd like to work on this!

**Comment by jasonblais** [comment]
Sweet!! Many thans @kaakaa, you're great!

**Comment by jasonblais** [comment]
Hey @kaakaa, thank you for working on this improvement, highly appreciated!

Just wanted to give you a heads up about upcoming dates for our 3.5 release that are relevant to this improvement:
 - Mon 10/31: last date community pull requests should be submitted for testing and review
 - Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4. Large pull requests may require an earlier merge date.

If you'd like to work on getting the improvement added for 3.5, those would be the dates to meet -- just wanted to let you know so it doesn't come as a surprise if you were aiming for the 3.5 release.

Once again, big thanks for your help!

**Comment by kaakaa** [comment]
Hi @jasonblais!
Thank you for notifying release schedules.

* * *

I work this issue now.
Now, most slash commands work in RHS.

But `/shrug` and `/echo` commands don't reply to the root and parent post.
Is it better for `/shrug` and `/echo` to reply to root/parent post?

I think that `/echo` is difficult for me...([platform/api/command_echo.go](https://github.com/mattermost/platform/blob/master/api/command_echo.go#L84))

**Comment by jasonblais** [comment]
Thanks @kaakaa, great work! I take it works for custom slash commands as well?

What happens then when a user posts `/echo` and `/shrug` in the RHS?

**Comment by kaakaa** [comment]
![mattermost](https://cloud.githubusercontent.com/assets/1453749/19677605/0204c568-9ad5-11e6-8cae-4b921513fb8a.jpg)
When posting `/shrug` in RHS, the result is just a post, isn't a reply for root post,
Which is acceptable to be a reply or just a post?

And, custom slash command looks like working properly in RHS, but is same as `shrug` about replying.

**Comment by jasonblais** [comment]
Hmm, I see -- if I were to use any of the three slash commands (`/shrug`, `/echo` or a custom one), I would expect it to reply to the root post and be part of the comment thread.

**Comment by kaakaa** [comment]
okay, I'll try it, and make a new PR!
Thank you @jasonblais !

**Comment by jasonblais** [comment]
Closed by #4367, huge thanks @kaakaa!
