### ISSUE TITLE
some c/c++ reserved words are not syntax Highlighted using ``` cpp ```

### ISSUE THREAD

**Issue by Twoflower2** [mattermost/platform#4251]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Issue using markup ``` cpp ``` that all c++ syntax is not Syntax Highlighted.

#### Steps to reproduce
On latest MM version:
``` c++
//! handle the client authentication
void SshSessionService::HandleUserAuthResponse(Manager &manager)
{
    string::size_type pos;
    assert(m_bWriteReadPending);
    LOGMESSAGE(LOG_INFO_VERBOSE) "%s: Received response for USERAUTH request for %s, method %s, state %d (remaining methods: '%s')",
        GetSessionId(), m_username.c_str(), m_lastMethod.c_str(), m_state, m_methodsRemaining.c_str());
    switch (m_state)
    {
    case SUCCESS:
        LOGMESSAGE(LOG_WARNING) "%s: Authentication of %s succeeded" , GetSessionId(), m_username.c_str());
        setServiceState(SESSION_ESTABLISHED);
        break;
```

#### Expected behavior
All c/c++ reserved words are syntax Highlighted

#### Observed behavior
some c/c++ reserved words are not syntax Highlighted

#### Possible fixes
Make place available where I can add to list of reserved c/c++ reserved words for syntax Highlighting and tweak if colours are bad.

**Comment by esethna** [comment]
Thanks @Twoflower2, do you have a list of which reserved words are not highlighting?

**Comment by jasonblais** [comment]
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information.

**Comment by Twoflower2** [comment]
@esethna no I do not have a list, I now and then find some, but where is the list stored in the MM code that are highlighted? Where do you get this from?

**Comment by lfbrock** [comment]
@Twoflower2 - I think we use this library for syntax highlighting: https://github.com/isagalaev/highlight.js

It might be easiest to report the issue directly to their GitHub repo
