### ISSUE TITLE
Do not allow personal invite link sharing

### ISSUE THREAD

**Issue by andre82hh** [mattermost/platform#4252]
#### Summary
Do not allow personal invite link sharing

#### Steps to reproduce
pre-condition: 
- use gitlab as oauth provider
- no mail sign up allowd

click 3 dots -> Invite New member -> enter mail -> send Invitation -> when receive mail, grap the invite link -> share this link with anybody, can join team.  

#### Expected behavior
personal invite link is only useable by one person.

#### Observed behavior
other people with that link can join the team.

#### Possible fixes
restrict link to mail or invalid link, after using it.

**Comment by esethna** [comment]
Agree @andre82hh, thanks for the report! I've created a [ticket, closing this issue so it can be tracked in JIRA](https://mattermost.atlassian.net/browse/PLT-4411).
