### ISSUE TITLE
Failing to retrieve data from PostgreSQL database cluster

### ISSUE THREAD

**Issue by syamgk** [mattermost/platform#4254]
#### Summary

Failing to retrieve system console data while using the pgpool setup for database 
#### Steps to reproduce

[Deploying on openshift](https://gitlab.com/sgk/mattermost)
or
[Deploying on docker](https://gitlab.com/sgk/mattermost-docker)
after deploying, do a signup and go to system console 
#### Expected behavior

While trying to run mattermost on openshift.
It's working successfully with a single postgresql instance.

and while tries to run the same with postgresql cluster setup(for scaling)
It is failing to connect database at some specific points and
throwing the below error.
#### Observed behavior

[EROR] Failed to retrieve user profiles
team_id=5esim8ypjpbdub75hy693nwfny, err=SqlUserStore.GetProfiles:
store.sql_user.get_profiles.app_error, read tcp
10.1.0.10:49766->172.30.90.146:5432: i/o timeout
#### Possible fixes

suspecting [GetReplica](https://github.com/mattermost/platform/blob/8a0e649f989a824bb3bbfd1900a5b8e5383b47e1/store/sql_store.go#L566) function might be the issue

Ref:[mattermost forum](http://forum.mattermost.org/t/mattermost-fails-connecting-to-pgpool/2369)
Ref:[crunchy issue](https://github.com/CrunchyData/crunchy-containers/issues/24)

**Comment by jasonblais** [comment]
Very sorry @syamgk, this GitHub issue slipped our sights.

Are you still having trouble retrieving data? If so, please help add any updates to the [original forum issue you posted](https://forum.mattermost.org/t/mattermost-fails-connecting-to-pgpool/2369) and I'll ping our community to help.

**Comment by syamgk** [comment]
thanks @jasonblais 
yes, still facing this issue
currently we are running our mattermost with single PostgreSQL instance 
And you can easily reproduce the issue as mentioned in previous post.

**Comment by it33** [comment]
Hi @syamgk, 

Mattermost Team Edition is intended for self-hosted team communication, it's not intended to be used at a scale where you'd need a database cluster. To officially support such a configuration would be too much of a tax on the open source community to setup such an environment and to test, document and support it properly, even if a change was submitted. 

There's a commercial extension, [Mattermost Enterprise Edition](https://about.mattermost.com/pricing/), intended for large organizations that supports DB clusters (along with advanced access controls, compliance reporting, corporate directory integration and other features needed for advanced organizations beyond what teams need). 

If you're at an enterprise needing secure, modern messaging, it's an excellent value. If you're a non-profit or academic institution there's steep discounts available. 

You're also welcome to fork the open source version and modify it as you wish--and many organizations do. 

DB clustering is just out-of-scope for the Team Edition.

**Comment by it33** [comment]
@syamgk Please let us know if this makes sense?

**Comment by jasonblais** [comment]
Hey @syamgk, let us know if you have further questions?

Closing the ticket on GitHub given it's not a product issue, happy to continue conversation [on the forum thread](https://forum.mattermost.org/t/mattermost-fails-connecting-to-pgpool/2369) if you any thoughts or questions about it.
