### ISSUE TITLE
Api headers are not exposed or accepted when mattermost dev server

### ISSUE THREAD

**Issue by keithgallant** [mattermost/platform#4255]
We are currently trying to use the Dev server setup to work on implementation (https://docs.mattermost.com/developer/developer-setup.html). The Mattermost instance is running successfully when browsing to http://localhost:8065. However, when consuming the api through http://localhost:8065/api/v3 from our Angular app then Token header is not exposed when posting to users/login and the get calls to the api are not accepting our Authorization header. There does not seem to be any setting for support to Enable Headers to allow the Token header to be accessible to javascript nor does there seem to be suport for Allow Headers? 

Can someone please direct me to what I might be missing here? 

Thank you.

**Comment by esethna** [comment]
Hi @keithgallant, thanks for your interest in Mattermost! You may have more discussion on this topic if you post to the [Mattermost developer forums](https://forum.mattermost.org/c/dev). We try to generally reserve GitHub issues for product bugs.
