### ISSUE TITLE
[Help Wanted] Website Link Previews

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4257]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Current Behaviour:** We have link previews for images (GIF, PNG, JPEG, and BMP) that work well, and links for website previews that don't work as well. 

**Proposed Solution:** Remove broken website previews, and make new website previews for all websites that have open graph metadata.

---
### Part 1: Remove broken website previews

Remove the [old link previews](https://github.com/mattermost/platform/blob/master/webapp/components/post_view/components/providers.json). (These are the ones that must be turned on from Account Settings > Advanced > Preview pre-release features > Show experimental previews of link content).
### Part 2: Add new website previews for websites with open graph metadata

If a link posted has an open graph **description** in the web page metadata, show a preview containing: 
1. Open Graph Website Name (if available) - "og:sitename"
2. Open Graph Page Title (if available) - "og:title"
3. Open Graph Page URL (if available), as the link for the title - "og:url"
4. Open Graph Website Description - "og:description"
5. Open Graph Image (if available) - "og:image" 
   - Display with a maximum height and width set to 150px

If there is **no description** on the web page, do not create a link preview.

When creating a link preview:
1. Set a maximum length of 300 characters
2. If the description exceeds the maximum length, truncate it using "..."

After a post containing a website link is posted, the website previews should always show up at the bottom of the post, no matter where the link is in the post body.

Please make sure that: 
1. The website preview is visible after posting (ie it does not show up below the text box)
2. When the window width changes or the RHS opens, the link preview text should adjust width as well to stay within the preview. If the adjusted text exceeds the max height, it should truncate at the proper point using "...".
3. The website previews do not cause issues with the scroll position jumping when channels load.
### Part 3: Make images in website previews collapsable

If the website preview contains an image, make **only the image** portion of the website preview collapsable. 

Show the collapse icon beside the description.
### Example

For this [webpage](http://www.cbc.ca/news/canada/toronto/blue-jays-game-4-setup-1.3809587), the website preview would look something like this:

<img width="756" alt="screenshot 2016-10-18 11 37 40" src="https://cloud.githubusercontent.com/assets/9354841/19484951/720b4980-9527-11e6-99bd-3a43a77e0e07.png">

**Comment by shahbaz17** [comment]
I would like to work on this. Can anyone guide me ?

**Comment by jasonblais** [comment]
Thanks @shahbaz17 for your interest!

You can come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss the feature and ask questions.

You can also review our [Contribution guidelines](https://docs.mattermost.com/developer/contribution-guide.html) to help set up your environment and review a few tips.

**Comment by jasonblais** [comment]
@shahbaz17 there was a bug with the sign up link to the Contributors community channel -- it's now fixed, so you should be able to create an account if you're still interested.

**Comment by jasonblais** [comment]
Hey @shahbaz17 , just checking how you're doing - let us know if there's any tips we can provide?

**Comment by jasonblais** [comment]
Hey @shahbaz17, did you manage to join the [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets)? Any issues in the sign up process?

**Comment by debanshuk** [comment]
I am interested in working on the issue and am starting on it.

**Comment by jasonblais** [comment]
Awesome, thanks @debanshuk! 

This is an involved ticket, so please don't hesitate to ask questions in our [Contributors community channel](https://pre-release.mattermost.com/code/channels/tickets). For technical advice or support, the [Developers channel](https://pre-release.mattermost.com/code/channels/developers) is an excellent resource.

**Comment by debanshuk** [comment]
Hi @jasonblais, 

As I understand currently in the experimental website preview feature Noembed service (https://noembed.com) is being used to scrape metadata from sites which have oEmbed metadata and are supported by Noembed service. And scraping and preview generation is happening completely at the front-end without any involvement of the backend, such that everything time a a message with a previewable link is rendered, meta-data for that link is fetched fron Noembed and the preview is generated.

Now in the new feature when we use Open Graph metadata instead of oEmbed, we would need either a similar service like Noembed which support Open Graph (were would again be limited to the websites supported by the service, though I don't no of any such free service) or we would have to do the scraping at the backend. For backend scraping, following are two approaches:

1. **Store OG meta data of in DB**: In this approach we would only scrape a link once and would store it's OG meta-data in our DB and file-storage (we also choose to store only link of images or download images, generate their thumbnails and store the thumbnails). Whenever a client would fetch that message we would return all the meta-data needed for rendering preview from the message API itself.

2. **Create a service link Noembed (no data would be stored in DB)**: Second option could be to create a API which would scrape and return OG meta-data for any given website link. In this approach we would simple use our own API instead of a their party service like Noembed to get OG meta-data for a link. No data would be stored with a message and this service would be used every time preview generation is needed for a message (Though we may choose to cache OG meta-data in the service).

I believe the second approach would require less code changes than first one for implementation and would also not use space in DB and file storage, but would hit the a website link every time it's preview is rendered. Also, previews may change over time in this approach if the content of website changes (eg, font page of a new website). Which approach would be preferred by you?

**Comment by enahum** [comment]
Hi @debanshuk
I think the second option makes more sense

**Comment by debanshuk** [comment]
@enahum, Sure, I would continue the second approach.

**Comment by debanshuk** [comment]
@lfbrock, In part 2 the issue first says "Set a maximum length of 300 characters" and "If the description exceeds the maximum length, truncate it using "..."". But in the the "Please make sure that:" section (in part 2 itself), it says, "When the window width changes or the RHS opens, the link preview text should adjust width as well to stay within the preview. If the adjusted text exceeds the max height, it should truncate at the proper point using "..."."

So, should the truncation be done on the basis of max number of character in description or max height of preview area?

cc: @enahum @jasonblais

**Comment by debanshuk** [comment]
@lfbrock, I have used 300 char limit to truncate description and aren't doing any further truncation if the width of window reduces. Instead the height of preview is dynamic and increase the compensate the reduction is width. Let me know if you want the behaviour to be some different.

**Comment by jasonblais** [comment]
Closed via #4257, thanks @debanshuk!

**Comment by jasonblais** [comment]
Hey @debanshuk, we noticed `http://www.wsj.com/` results in a blank image. Wondering if this is expected (is it another case where the OG image tag isn't correct)

![image](https://cloud.githubusercontent.com/assets/13119842/22218554/65bd1d8a-e175-11e6-9ee3-3b0a688fdf54.png)

**Comment by debanshuk** [comment]
Hi @jasonblais, I checked and found that following URL is present in the image og tag or `http://www.wsj.com/`:
```
//ore.wsj.net/fp/cdn/fp/assets/images/ico/WSJ_facebook.png
```

Which doesn't have a scheme (http: or https:), which is required by the OG standard. Though it would still have worked as the scheme of the current page (mattermost post list page) would have been used by the browser as no scheme is present in the URL, but this URL doesn't return a image with http: or https: scheme. It returns following error message:

URL: http://ore.wsj.net/fp/cdn/fp/assets/images/ico/WSJ_facebook.png or https://ore.wsj.net/fp/cdn/fp/assets/images/ico/WSJ_facebook.png
<img width="1223" alt="screen shot 2017-01-24 at 10 28 45 pm" src="https://cloud.githubusercontent.com/assets/2102907/22257759/05b989f8-e285-11e6-932b-c5a54feff6f2.png">

**Comment by jasonblais** [comment]
Thanks @debanshuk for the quick response.

We've been testing out the link previews further and are proposing to turn the image previews off for now (still keeping the text previews as-is).

I think we'll want to approach creating an image preview from a more strategic point of view where the image is actually useful to the user. E.g. all GitHub issues show a large profile picture as the preview, which is not beneficial and takes up a lot of whitespace.

Your implementation is correct, it's just something we'd want to re-visit in the future.

Is that something you'd have time to do (remove image previews from the website link previews)?

**Comment by debanshuk** [comment]
@jasonblais, Yes sure, I can work on that too (remove image previews from the website link previews).

**Comment by debanshuk** [comment]
@jasonblais, Shall I do the above mentioned change in this issue itself?

**Comment by jasonblais** [comment]
Hey @debanshuk, sorry for the delay, was away for that last couple of hours.

I'll reach out to you on https://pre-release.mattermost.com soon: I think we reached a better alternative that should be relatively easy to implement, but let's us keep the images with the link previews.

**Comment by awgeorge** [comment]
Hello - This is great work, can you change it so it won't show a preview for sites returning a 403 status code? Maybe just show the preview with a 200 status code.

Every time I paste a link to our Gitlab instance, it shows the login description.

<img width="803" alt="screen shot 2017-04-10 at 17 20 11" src="https://cloud.githubusercontent.com/assets/1777444/24883240/1302572a-1e12-11e7-9e79-848d1c6f89d1.png">

**Comment by jasonblais** [comment]
@debanshuk what do you think?

**Comment by jasonblais** [comment]
And thanks @awgeorge! Glad you like them :)

**Comment by jlsjonas** [comment]
ping @debanshuk @jasonblais (your last message seems to have gotten lost/forgotten through time)

**Comment by jasonblais** [comment]
@jlsjonas Do you know if this is easy to fix given we use Open Graph data to populate the preview? We fixed it in v5.2 so it redirects to the correct link, at the very least.

No worries if you're not familiar with it :)

**Comment by jlsjonas** [comment]
Not sure how I got to that ping; however the gitlab login page preview is still quite an issue. every link we share just creates a non-useful "sign in" description block.

On Gitlab's side it doesn't make sense to remove it for SEO purposes, ideally mattermost (ESPECIALLY with the Gitlab-omnibus installation) should have a way to poke for the private info (maybe using the SSO session if available?; or alternatively using a defined api key/something)

**Comment by jasonblais** [comment]
@jlsjonas I investigated this further and there is no way that we know of where Mattermost can identify whether a redirect is to a login page vs. an ordinary use of a redirect. Thus, there’s unfortunately no easy way to avoid the preview of the login page.

That said, we fix an issue where clicking the URL of the link preview redirected to the wrong page. This was shipped in Mattermost v5.2 (coming in GitLab v11.3 this month).

**Comment by jlsjonas** [comment]
Aha, that's indeed a different issue. I understand that there's no way to know what kind of redirect it used.
However, mitigating the issue by providing a configurable API key to get that info (similar to the Google API Key for youtube videos) would go a long way.
And -especially for a _unified_ installation- is kind-of expected.

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback @jlsjonas.   

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](http://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub Issue.

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Thanks @jlsjonas!
