### ISSUE TITLE
Restrict team creation

### ISSUE THREAD

**Issue by stanhu** [mattermost/platform#426]
I just enabled GitLab Mattermost, but I don't see a way to restrict team creation so that only specific people can do this. I scanned the `config.json` but didn't see anything obvious. Is there a way to do this?

**Comment by it33** [comment]
Hi @stanhu, there isn't a setting right now to restrict team creation to certain roles. We're working on the design of the admin console, where we could probably include this as a default option across the site: http://forum.mattermost.org/t/early-designs-of-admin-console/120

We'd welcome you to join the spec discussion on the forum (would you prefer team creation restricted by a) email, by b) shared link, or c) perhaps only allow creation by authenticated users?). 

Also would welcome a feature idea (http://www.mattermost.org/feature-requests/) on the topic?

**Comment by stanhu** [comment]
The admin console looks good. For now, restricting by domain name in the e-mail would suffice. I think options b and c are also useful.

Even if the admin console isn't ready, I think even a hard-coded setting in `config.json` would be a big help. I think this is a must-have feature to prevent GitLab users enabling Mattermost from opening up the site to unwanted users.

**Comment by it33** [comment]
Thanks @stanhu! Restricting sign-ups by domain name is a really good idea, let me see what we can do on that one. I've included it in a broader spec here: http://forum.mattermost.org/t/your-feedback-requested-restricting-creation-of-teams/142

**Comment by coreyhulen** [comment]
This is fixed with PR https://github.com/mattermost/platform/pull/474 and will ship with 0.7

**Comment by stanhu** [comment]
Awesome, thanks!

**Comment by rompic** [comment]
maybe it may also make sense to restrict users to a given domain?

**Comment by pdomineaux** [comment]
I agree with @rompic , allow user's authentication to a specific domain sounds great. Or an option that allows only the team administrator to create account.

**Comment by lfbrock** [comment]
You can restrict team creation to a specific domain from the System Console, and I added a [ticket](https://mattermost.atlassian.net/browse/PLT-1703) to be able to restrict user creation to a specific domain as well. 

There is also a ticket to add an option to [restrict the ability to send invitations to administrators](https://mattermost.atlassian.net/browse/PLT-2144).

**Comment by pdomineaux** [comment]
Perfect, this is all that I need to go on production. Thanks. I've already enable the team creation restriction, but it is useless in my case. We have 1 team and many channels.
Thanks a lot for the ticket and for all the work to make this awesome tool available for the community.

**Comment by 212blackjack212** [comment]
Hi there. Is there a way to limit the privileges each role type has. We are trying to limit the ability to add and remove members from channels (public and private) to only Channel admins, Team admins, or System Admins.

Members should have only the cability to read and write in channels.

Any help is appreaciated.
