### ISSUE TITLE
Push notification on Android 6.0

### ISSUE THREAD

**Issue by mmarif4u** [mattermost/platform#4272]
Hi,

Push notification on Android 6.0.x does not work using TPNS.
Mattermost v 3.4.1

Currently testing Mattermost within our team with different mobile phones they have.
The following are the findings so far.
**Works:**
- iPhone 6s, iOS 9.3.5
- Samsung A7 android 5.1.1
- iPhone 6s , iOS 10.0.2

**Does not work:**
- Oneplus X  android 6.0.1
- Samsung S7 Edge,  android 6.0.1
- Sony Xperia X , android 6.0.1

From above results we concluded that android 6.x.x does not receive any notifications.
Is there anything i enable/disable for this to work OR is it a known issue.

**Comment by esethna** [comment]
Thanks for the report, I will check with other members of our team with Android devices to attempt to repro. We've had a few reports push notification issues on Android 6.0.1.

Can you please attempt to change some of the notification settings in Account Settings > Notifications > Push Notifications to see if they could be causing an issue. Also, can you please make sure push notifications for the Mattermost app are enabled in your device settings and can appear in the notification drawer?

**Comment by mmarif4u** [comment]
Thanks @esethna

I have changed the notification settings and tested on another Samsung S6 mobile having Android 5.1.1(it still have sound notification though, but no notification in notification drawer).
Still no luck on Android 6.x.x phones, also noticed there is the loading circle on Android 6.x.x phones stuck there in the center all the time.
Yes, push notifications are enabled for Mattermost in the phone settings.

**Comment by esethna** [comment]
Thanks for the follow-up, can you also please attempt to uninstall and reinstall the Mattermost app from the play store?

**Comment by mmarif4u** [comment]
Removed the app, installed again and still the same. Changed the notifications with different setup and no luck.

**Comment by mmarif4u** [comment]
This morning i reinstalled on Samsung A7, and it break the notifications. The red circle now showing up here too which was not there before.

**Comment by grundleborg** [comment]
Seeing both of these issues too on Android 7.0 / Nexus 5X. Only installed the app for the first time, last week, and have had both issues right from the start.

**Comment by Keensit** [comment]
Hi,
I have the same problem on two other device with android 6.x.x:
-OnePlus A001 (one)
-Huawei P8 light

The issue seems the same: push notification not working with TPNS and a little red circle on the center of the screen. Tried with an old samsung with Android 5.0.1: the notification started working (only inside of the app, but this is another problem) and I understand that the red circle is the loading gif.

**Comment by mmarif4u** [comment]
@Keensit yes thats gif/png loader but annoying.

**Comment by Keensit** [comment]
@mmarif4u  
![2016-10-25_16-51-55](https://cloud.githubusercontent.com/assets/23052598/19691227/d15dec6a-9ad3-11e6-910f-c117be16b3da.png)

Yes, especially when you don't understand what is it...

**Comment by esethna** [comment]
Hi all, for those not receiving notifications on Android 6.0.1, please also try the following steps:

1. Make sure the app is set as a prioritized app in priority mode in device settings.
2. Check to see if the app is being silenced by Doze mode in device settings. Check to see if any other volume-manipulating apps are running.

**Comment by mmarif4u** [comment]
Done that and still the same. This is tested on Android 5.1.x(reinstalled the app) and 6.0.x. No notifications for both. Android 5.1.x(samsung A7) issue started after reinstalling the app. It was fine before that.

**Comment by esethna** [comment]
Hi all, just an update,

We have opened a ticket for the red circle issue and it's currently in progress for the next version of the Andriod app: https://mattermost.atlassian.net/browse/PLT-4561

Regarding missing notifications, we have some devs looking into it as a potential hot fix for v3.5, being released on the 16th. Hopefully these issues should be resolved after upgrading.

**Comment by esethna** [comment]
@mmarif4u @Keensit @grundleborg we've updated the Play Store app after being able to repro some of these push notifications issues. Please update and try again? Hopefully your issues should be solved.

**Comment by lfbrock** [comment]
Closing this issue, if anyone is still having issues in v3.5 please re-open?
