### ISSUE TITLE
Missing Unicode 9.0 emoji

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#4281]
#### Summary
Mattermost is missing emoji from the Unicode 9.0 spec (e.g. 🤢)

#### Steps to reproduce
On Mattermost 3.4.0, post a message containing the 🤢 character.

#### Expected behavior
It is replaced by the Apple emoji and displayed correctly.

#### Observed behavior
As I don't have an emoji font, mojibake is displayed:
![capture d ecran - 20102016 - 16 24 09](https://cloud.githubusercontent.com/assets/840125/19563893/f439dab4-96e1-11e6-8903-799e4716763f.png)

#### Possible fixes
The complete list of new emoji can be found here: http://emojipedia.org/unicode-9.0/

**Comment by esethna** [comment]
Thanks @Rudloff, closing to track this in [a JIRA ticket](https://mattermost.atlassian.net/browse/PLT-4440).
