### ISSUE TITLE
Room full on invite should show proper message, now displays invalid invite.

### ISSUE THREAD

**Issue by riemers** [mattermost/platform#4283]
#### Summary
When a person uses a invite link and the room is full (50 people) the user only gets the message "invalid invite link" which is not the real error.

#### Steps to reproduce
Use an invite link, when the room has 50 people in it and the max of the channel is set to 50.

#### Expected behavior
Report back an error to the client saying "Room is full, contact the administrator" or something.

#### Observed behavior
Seeing "invalid invite link"

**Comment by jasonblais** [comment]
Thanks @riemers for the report!

We have an open Jira ticket for it, would you be interested in helping with a fix? https://mattermost.atlassian.net/browse/PLT-4391

**Comment by lfbrock** [comment]
Closing this issue as a duplicate of: https://github.com/mattermost/platform/issues/4305
