### ISSUE TITLE
Messages that begin with a slash (that aren't valid slash commands) should just be treated as messages

### ISSUE THREAD

**Issue by dale-c-anderson** [mattermost/platform#4287]
#### Summary

When writing a message that begins with a slash, it is always treated as a command, and the message is never displayed. I understand that this is probably by design, but it's annoying anyway.
#### Steps to reproduce

Write anything that begins with a slash and isn't a command
#### Expected behavior

I would expect commands to do what they're supposed to. I would expect everything that isn't a command just to behave as a message. As a developer, a lot of my responses to questions are the name of a file or a path. Let the folks in the channel shame the user into typing correct commands, instead of making it the platform's responsibility. :-)
#### Observed behavior

All that happens is mattermost gives me a red error message, and discards my message.  The message has to be prefixed with a backtick, or a space, or some other character in order to be sent.
#### Possible fixes

Instead of discarding the non-command, display it as a message, but still present the error to the person. Or build an option to change the behaviour.

**Comment by esethna** [comment]
Thanks for the suggestion @dale-c-anderson. I investigated some other messaging software and it seems that it is common behavior that invalid slash commands do not send as a message. This also follows the Mattermost principle of being forgiving if a user mistypes a slash command by accident. It is possible to just preface the slash command with a space if you want to send the text as a message.
