### ISSUE TITLE
Race condition when creating image thumbnails during Slack CLI export

### ISSUE THREAD

**Issue by grundleborg** [mattermost/platform#4288]
There is a race condition between handleImages and the main thread exiting when importing a Slack import with uploads via CLI.

Discussion and proposed solution here: https://pre-release.mattermost.com/core/pl/k8388osbkpbo9xn4kd9ygg6dro

I am intending to fix this issue myself, but logging it here to ensure it doesn't get forgotten about.

**Comment by esethna** [comment]
Thanks @grundleborg, adding @yangchen1 to help create a ticket and follow-up on the fix.

**Comment by yangchen1** [comment]
@grundleborg: the ticket for your reference is [here](https://mattermost.atlassian.net/browse/PLT-4442), thanks!
