### ISSUE TITLE
[Help Wanted] Help fix Korean input on IE11

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4296]
Repro steps: 
1. Type Korean characters with a Korean keyboard into Mattermost messages on IE11

Observed: 
- Characters typed do not appear. 
---

It's been difficult to reproduce the reported issue, though people who see the issue can reproduce it consistently on their setups. 

We could really use help from the community who might have Korean keyboards and operating systems. 

Here is a configuration where it does not reproduce: 

```
Test Environment
OS : Windows 10 Pro (Build 14393)
IE version : 11.321.14393.0
IE update version : 11.0.36
```

**Comment by lfbrock** [comment]
Closing this issue, we figured out how to reproduce it and are working on a fix for it.
