### ISSUE TITLE
[Help Wanted] Support swipe gesture in mobile web UI

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4297]
We've had many requests for supporting the swipe gesture in the mobile web UI. We found a library that lets us scroll up and down really well, but could use help on left and right swipe to bring up the left and right menus

Anyone have suggestions or ideas, or interest in a PR to add this? 

![image](https://cloud.githubusercontent.com/assets/177788/19609522/91dee57a-978c-11e6-8d30-dfbd947a09cc.png)

**Comment by jasonblais** [comment]
Closing given our focus on next-generation mobile apps which now supports this feature

https://github.com/mattermost/mattermost-mobile
