### ISSUE TITLE
[Help Wanted] Unable to update channel purpose more than once without a refresh

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4301]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details**

Unable to update channel purpose twice without a refresh

Repro steps (Windows 10, Chrome):
1) In a test channel, click "v" next to the channel name, then select `Set Channel Purpose...`
2) Update the text, then click "Save"
3) Repeat steps 1. and 2. in any channel

Observed: The "Save" button is disabled and I'm unable to save the channel purpose for any channel. A hard refresh is required for me to update the purpose.

Expected: The "Save" button is not disabled.
---

**Note**

If you want the fix to be considered for Mattermost 3.5, here are some dates to keep in mind:
- Mon 10/31: last date community pull requests should be submitted for testing and review
- Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4. Large pull requests may require an earlier merge date.

Note that meeting the above dates isn't a guarantee the pull request would be included in the release. If the dates are met, we'll do our best effort to review the pull request swiftly so it can be considered.

**Comment by digitaltoad** [comment]
I'll take this on if that is alright.

**Comment by lindy65** [comment]
@jasonblais @digitaltoad 

I've just retested this issue and am not able to reproduce so am closing this thread.

Thank you for your offer to help @digitaltoad !  We hope you can find something else you'd like to work on :)

**Comment by jasonblais** [comment]
It is still reproducing for me on Windows 10, Chrome.. I'll check if anyone else is able to reproduce it

**Comment by lfbrock** [comment]
@jasonblais it looks like it might only be reproducing for channel purpose and not header?

**Comment by jasonblais** [comment]
Updated ticket, just realized it too. Thanks @lfbrock

@digitaltoad If you're still interested in submitting a fix, this is up for grabs

**Comment by digitaltoad** [comment]
Sure I'll take a look. Thank you!

**Comment by jasonblais** [comment]
Closing via #4400, thanks @digitaltoad!
