### ISSUE TITLE
[Help Wanted] IE11: "Write a message..." help text missing when message box is in focus

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4303]
"Write a message..." help text missing in IE11 when message box is in focus ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-3857))

If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Note**

If you want the fix to be considered for Mattermost 3.5, here are some dates to keep in mind:
- Mon 10/31: last date community pull requests should be submitted for testing and review
- Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4. Large pull requests may require an earlier merge date.

Note that meeting the above dates isn't a guarantee the pull request would be included in the release. If the dates are met, we'll do our best effort to review the pull request swiftly so it can be considered.

**Comment by digitaltoad** [comment]
I'll take this on if that is alright.

**Comment by jasonblais** [comment]
You're awesome @digitaltoad, thank you!

**Comment by digitaltoad** [comment]
This is actually a bug in IE 10+ that is apparently on the radar. I can be fixed with a polyfill but I'm not sure you guys want to go that route or not.

**Comment by digitaltoad** [comment]
Guess I should give a reference for this: http://stackoverflow.com/questions/14445891/keep-placeholder-on-focus-in-ie10/16138480#16138480

**Comment by jasonblais** [comment]
Thanks @digitaltoad ! 

I'll forward your question to the core developers in our [Mattermost Developers channel](pre-release.mattermost.com/core/channels/developers) tomorrow.

**Comment by jasonblais** [comment]
Actually, given the complexity we would add relative to its benefit.

It's a relatively minor corner case, so let's not fix it with a polyfill.

I'll close the issue and add a note on the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3857).

Thanks again @digitaltoad, much appreciated!

**Comment by digitaltoad** [comment]
Not a problem. Glad I could help.
