### ISSUE TITLE
[Help Wanted] After opening a new direct message channel, my cursor is not put in the text input box

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4304]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.
---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4275))

After opening a new direct message channel, my cursor is not put in the text input box

Repro: 
1. Open DM "More" menu
2. Click "message" beside someone's name

Observed: Your cursor is not put in the text input box. 

Expected: Cursor should be in the text input box.
---

**Note**

If you want the fix to be considered for Mattermost 3.5, here are some dates to keep in mind:
- Mon 10/31: last date community pull requests should be submitted for testing and review
- Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4. Large pull requests may require an earlier merge date.

Note that meeting the above dates isn't a guarantee the pull request would be included in the release. If the dates are met, we'll do our best effort to review the pull request swiftly so it can be considered.

**Comment by digitaltoad** [comment]
I wouldn't mind tackling this if that is ok.

**Comment by jasonblais** [comment]
Awesome, thanks @digitaltoad!

**Comment by jasonblais** [comment]
Closed per #4336, thanks @digitaltoad!
