### ISSUE TITLE
[Help Wanted] Team error message doesn't display actual error message when max users per team reached

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4305]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

----

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4391))

Team error message doesn't display actual error message when max users per team reached

Repro [UPDATED]:
1) **Set System Console > General > Users and Teams > Max Users per Team** to 10
2) **Set System Console > Security > Sign Up > Enable Open Server** to True
3) Have at least 10 members join a team on the server
4) Create a new account from the "Create one now?" link on the sign in page
5) Attempt to join the team from step 3

Observed: Error message "The invite link was invalid. Please speak with your Administrator to receive an invitation."

Expected: Error message "This team has reached the maximum number of allowed accounts. Contact your system administrator to set a higher limit."

----

**Note**

If you want the fix to be considered for Mattermost 3.5, here are some dates to keep in mind:

 - Mon 10/31: last date community pull requests should be submitted for testing and review
 - Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4. Large pull requests may require an earlier merge date.

Note that meeting the above dates isn't a guarantee the pull request would be included in the release. If the dates are met, we'll do our best effort to review the pull request swiftly so it can be considered.

**Comment by S4KH** [comment]
Will work on this, related to what I have already done.

**Comment by jasonblais** [comment]
Thanks @S4KH!

**Comment by S4KH** [comment]
Isn't this showing the correct message when user signs up with invite link? 
http://localhost:8065/signup_email?id=6griiq961pfybxbn9hgs6ip7yh
![image](https://cloud.githubusercontent.com/assets/15072209/19633267/263cba42-99e2-11e6-9670-cf678e5f4ece.png)

**Comment by jasonblais** [comment]
Hmm, you're right, it seems to be correct if you use the team invite link.

I just tried and was able to reproduce it with the following steps however:

Repro:
1) **Set System Console > General > Users and Teams** to 10
2) **Set System Console > Sign Up > Enable Open Server** to True
3) Have at least 10 members join a team on the server
4) Create a new account from the "Create one now?" link on the sign in page
5) Attempt to join the team from step 3

Observed:
![image](https://cloud.githubusercontent.com/assets/13119842/19633664/0c736116-9982-11e6-8ec8-d1fe1a4d11a6.png)
