### ISSUE TITLE
Notifications from other teams

### ISSUE THREAD

**Issue by akhmerov** [mattermost/platform#4307]
#### Summary
Notifications from other teams don't respect channel notification settings in v3.4.0.

#### Steps to reproduce
1. Create a mattermost server, let user A join team 1 and team 2, user B join team 1.
2. Set notification preferences for user A team 1 town square to "never".
3. Log in user A into team 2, send a message from user B to the town square in team 1.

#### Expected behavior
User A receives no notification

#### Observed behavior
User A receives a message notification

**Comment by jasonblais** [comment]
Thanks @akhmerov! Ticket created here: https://mattermost.atlassian.net/browse/PLT-4538

Would anyone in the community be interested in submitting a fix?

**Comment by jasonblais** [comment]
Closing for now to track in Jira -- if anyone is interested helping submit a fix, please let us know or comment on the [corresponding Jira ticket](https://mattermost.atlassian.net/browse/PLT-4334).

Thanks again @akhmerov for the report!
