### ISSUE TITLE
Red Circle in the middle of the screen

### ISSUE THREAD

**Issue by datkinson** [mattermost/platform#4311]
#### Summary
There is a red circle in the middle of the screen which stays on top of all content

#### Steps to reproduce
- Install the app
- Open the app

#### Expected behavior
That there are no icons hovering over the top of content.

#### Observed behavior
There are no error messages but sometimes the circle is a solid ring and over times it has a secion missing.

When the section is missing it sometimes spins liek a loading spinner.

If it is a loading spinner it stays even after all content has been loaded.

The Device is a Nexus 5 running Android 6.0.1

![screenshot_20161024-145544](https://cloud.githubusercontent.com/assets/2528682/19648560/51212546-99fa-11e6-9ca2-b8aaf607cbf5.png)

**Comment by jasonblais** [comment]
Thanks @datkinson for the report, that's interesting..

Which Mattermost Server version and Android App version do you have?

Has anyone else in the community seeing something similar?

**Comment by danjw** [comment]
Yes.s7 edge the same problem with a remarkable lag on key input

**Comment by jasonblais** [comment]
Thanks for the reports, ticket created in Jira to track and fix the issue https://mattermost.atlassian.net/browse/PLT-4561

@danjw We're planning on building an open source framework for new official React Native mobile apps that should help with performance. You [can read more about it here](https://github.com/mattermost/platform/issues/4190), and if you're interested in contributing, consider joining our [Native Mobile Apps channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps) to discuss the future of the project.
