### ISSUE TITLE
[Help Wanted] In channel switcher [CTRL+K] search input only matches from the start of channel names

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4319]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.
---

**Details**

This improvement adds support so that channel switcher autocomplete search results work for any portion of the channel name, not just the beginning. The channel switcher is displayed when pressing `CTRL+K` in Mattermost.

Currently, you have to type the beginning of the channel name to bring search results in the channel switcher. However, if you type 'bugs', you'd expect to see both 'bugs' and 'confidential bugs' in autocomplete results.

Note: This should work similar to emoji autocomplete, where if you type "bu", 
1) channels that start with "bu" show first on the list, in alphabetical order, then
2) channels containing "bu" show next on the list, in alphabetical order

![image](https://cloud.githubusercontent.com/assets/13119842/19671427/aeb0cdd2-9a3c-11e6-9b77-0d962674e759.png)
---

**Note**

If you want the fix to be considered for Mattermost 3.5, here are some dates to keep in mind:
- Mon 10/31: last date community pull requests should be submitted for testing and review
- Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4. Large pull requests may require an earlier merge date.

Note that meeting the above dates isn't a guarantee the pull request would be included in the release. If the dates are met, we'll do our best effort to review the pull request swiftly so it can be considered.

**Comment by jokeyrhyme** [comment]
I'm looking at the pre-release site: https://pre-release.mattermost.com/core/channels/town-square

In the left sidebar, under CHANNELS, I click "More..."

In the "Search channels" , I try a few inputs, like "uth", "nt", and "b".

It would seem that the items in this channel list already are sorted as desired in this Issue.

Am I looking at the correct "channel switcher autocomplete search results"? Or is this found in a different place?

**Comment by jasonblais** [comment]
Sorry for the confusion @jokeyrhyme, the channel switcher appears after you press `CTRL+K` on the keyboard.

It's a keyboard shortcut that allows you to quickly switch channels.

Issue updated to clarify that point

**Comment by digitaltoad** [comment]
I have a naive fix for this that is literally just replacing the `startsWith` with a `match` but I'm wondering that since names are queried from the server, for consistencies sake should matching be done in one place or the other?

**Comment by jasonblais** [comment]
Thanks @digitaltoad! 

Since the channel switcher is used to query names and handles (URLs) of public/private channels *you currently belong to*, doing it on the client works and using `match` should be fine.

(Of course it's also used for direct message channels, but that should also work on the client)

**Comment by digitaltoad** [comment]
That is what I'm referring to. DM is queried/matched on the server where channel is matched on the client. If my naive fix is ok, I'll submit a PR.

**Comment by digitaltoad** [comment]
There doesn't seem to be a JIRA ticket for this. Is a PR still ok?

**Comment by jasonblais** [comment]
Sorry for the delay in response, was talking to devs to confirm

What we can accept for now is that the channel switcher autocomplete search works for
 - any part of channel name/handle for public and private channels
 - only start of name for DMs (that is, no change)

Our devs had a specific way to extend the code to allow modify the search function for DMs, so we can leave that for now.

Here's the Jira ticket, meant to include it in the GitHub issue https://mattermost.atlassian.net/browse/PLT-4395

Many thanks for working on this!

**Comment by jasonblais** [comment]
Thanks again for your interest!

Let me know if you have any other questions here @digitaltoad.

**Comment by digitaltoad** [comment]
@jasonblais After taking a look at this further, I feel like anything that I do client side is going to be half baked due to how DM channels are looked up on the server side. Even the display of the channels for the autocomplete is confusing because the DM channels are being matched by `Username, FirstName, LastName, Nickname` where the other channels are being matched on the client by `DisplayName, Name`. So when sorting comes into play, some channels may end up at a higher position but may not actually match the query from the users perspective. I wouldn't want you to accept a PR for the sake of accepting a PR especially when it sounds like a real fix is planned.

**Comment by jasonblais** [comment]
Thanks @digitaltoad, that makes a lot of sense. Thank you for taking it into consideration.

I've assigned this ticket to one of our devs, so closing the Help Wanted issue.

Thanks once more for your help here and for submitting #4336 and #4344 PRs.

Also, let us know if you need any tips to guide you with #4301 or #4303.
