### ISSUE TITLE
Scrolling bug on mobile after SuggestionList gets closed

### ISSUE THREAD

**Issue by NDKYHhJbsbFCmkAS2sHq9BVwTdrEK2e9** [mattermost/platform#4323]
Steps to reproduce:
1.- Open the emoji list and send an emoji https://s.put.re/3PDGmWD.png
2.- After the emoji list closes the modal-open class doesn't get removed: https://s.put.re/zCTdMmK.png
3.- Since the class doesn't get removed scrolling doesn't work anymore on the message list.

https://github.com/mattermost/platform/blob/master/webapp/components/suggestion/suggestion_box.jsx#L63

Most likely adding "$('body').removeClass('modal-open');" to componentWillUnmount() { will fix the problem.

After checking the bug tracker looks like this has been already reported: https://mattermost.atlassian.net/browse/PLT-4459

**Comment by jasonblais** [comment]
Thanks @NDKYHhJbsbFCmkAS2sHq9BVwTdrEK2e9 for the report!

Your description is very useful and we'll look investigate a fix for Mattermost 3.5 with https://mattermost.atlassian.net/browse/PLT-4459

Much appreciated!
