### ISSUE TITLE
Android app cannot connect (using browser works)

### ISSUE THREAD

**Issue by kaefert** [mattermost/platform#4332]
#### Summary

I cannot connect to a mattermost server running on a non-public ip-address on a non-standard port (8443) using the android app. Entering the same URL on the same android device in a browser it works fine.
#### Steps to reproduce

I've installed gitlab-ce 8.13.0 including mattermost on a centos6 system by using the repository from https://about.gitlab.com/downloads/#centos6
Since this server intentionally is not directly connected to the web, and does not have any public DNS entry, instead of using two different DNS entries for gitlab & mattermost, I've used two seperate ports for those two (gitlab 443, mattermost 8443). After a bit of Thumbling I managed to generate a self-signed-certificate that the server trusts to enable mattermost to trust the gitlab server running on the same server.

With this setup mattermost work when using a browser and also in the linux desktop app, but not with the android app. I've tried the releases 3.4.1 and 3.3.0 from https://github.com/mattermost/android/releases and I tried the version published to google play store (also 3.4.1 it seems).
#### Expected behavior

The app should work just as it works in the browser
#### Observed behavior

The android app shows the error:
"We could not connect to the Mattermost server or the server is running an incompatible version."
#### Possible fixes

I suspect the issue to be related to either the self-signed https certificate or the non default port.

**Comment by kaefert** [comment]
I've tried creating an account on this forum, but the confirmation link in the mail I got does not work.
Error: "['BAD CSRF']"

**Comment by jasonblais** [comment]
Sorry for the late reply -- I just tried and it was working okay..can you try re-sending the confirmation email to your account?

If the error continues, let us know

**Comment by kaefert** [comment]
Hello. I just tried again.

Using the [activation link I got 3 days ago](http://forum.mattermost.org/users/activate-account/1de78018c3250d64c8a92179383d372e)
I still get the same result as back then, I get a page with a button that reads "Click here to activate your account" and when I click it, I get a completely white page that reads "['BAD CSRF']" in the top left corner.

Trying to login with my non-activated account to get to the resend activiation link button doesn't work this time, I get "Unknown error" when clicking the "Log in" button.

**Comment by jasonblais** [comment]
We activated your account from the administration panel, can you try if you can log in now?

**Comment by kaefert** [comment]
no, I get an "Unknown error" when clicking the "Log in" button.

**Comment by jasonblais** [comment]
Awesome, great to hear @kaefert! Glad it works :)

**Comment by jasonblais** [comment]
Closing this issue, we'll follow the thread here instead: https://forum.mattermost.org/t/android-app-connect-to-mattermost-team-link/1417/25?u=jasonblais

Thanks again @kaefert!

**Comment by kaefert** [comment]
just for reference, I have now described my problem and asked for help in the forum in this post which seems to be already about the same problem:
http://forum.mattermost.org/t/android-app-connect-to-mattermost-team-link/1417/25
