### ISSUE TITLE
Crash when sending a direct message to a user that is not in any team

### ISSUE THREAD

**Issue by char101** [mattermost/platform#4334]
#### Summary

Crash when sending a direct message to a user that is not in any team
#### Steps to reproduce

Send a direct message to a user that is not a member of any team.

The failing code: https://github.com/mattermost/platform/blob/master/api/post.go#L782

Likely the same issue as #4163
#### Expected behavior

Message should be sent
#### Observed behavior

Mattermost crash

```
goroutine 9309 [running]:
panic(0xd30ea0, 0xc82000a030)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/mattermost/platform/api.sendNotificationEmail(0xc8205dc900, 0xc820e12540, 0xc8206917a0, 0xc820b57550, 0xc82087a460, 0xc820b0e029, 0x7, 0xc8205dd440)
        /var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/api/post.go:815 +0x3099
github.com/mattermost/platform/api.sendNotifications(0xc8205dc900, 0xc820e12540, 0xc82087a460, 0xc820b57550)
        /var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/api/post.go:689 +0x39f2
created by github.com/mattermost/platform/api.handlePostEvents
        /var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/api/post.go:262 +0x710
```
#### Possible fixes

Check the size of the `teams` slice.

**Comment by jasonblais** [comment]
Thanks @char101! 

Would you be interested in submitting a fix?

I just tried and for me it didn't crash, but it was failing to send the direct message with the following JavaScript error

![image](https://cloud.githubusercontent.com/assets/13119842/19727372/203a8922-9b5d-11e6-8c1c-f051dc9bce7c.png)

**Comment by char101** [comment]
Thanks for the info. I forget to mention that I use the 3.4.0 version. Maybe it doesn't crash in the master branch.

I could submit a pull request but reading the contribution guide I feel it's a bit too complex for a 3 lines fix ;)

https://github.com/mattermost/platform/compare/master...char101:bugfix/notification-no-team

**Comment by jasonblais** [comment]
We try to be comprehensive, as we've found this helps smooth out the process in the long run :) 

That being said, we do say towards the beginning, `It’s okay to submit PRs to fix obvious bugs or add small improvements,` so feel free to submit your PR, we'd love to review and take it if it looks good.

You can check a list of steps [to submit a PR here](https://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request), of which points 1, 3, 8 and 9 would apply to this case.

**Comment by jasonblais** [comment]
Hey @char101, would you be interested in submitting a pull request to fix the issue? We'd love to take it for review

Looking at your commit you referenced above, if you [sign the Contributor License Agreement](https://www.mattermost.org/mattermost-contributor-agreement/), I think you should be good for submitting a pull request for it.

**Comment by jasonblais** [comment]
EDIT: We're actually looking at a fix for the issue on our end, here's a ticket in our internal Jira system: https://mattermost.atlassian.net/browse/PLT-4636

Thanks again for the original report!

**Comment by char101** [comment]
Hi Jason,

Thanks for the update. Sorry I haven't touch mattermost again since I have other tasks right now. For the cause of the crash you can look at the diff of my branch above.

**Comment by jasonblais** [comment]
Thanks again @char101, much appreciated!
