### ISSUE TITLE
Attachment in direct message does not work when viewed from different team

### ISSUE THREAD

**Issue by char101** [mattermost/platform#4337]
#### Summary
Attachment in direct message only works when both the sender and the receiver log on to the same team.

#### Steps to reproduce
Create two users that belongs to different teams. Send a direct message containing an attachment from one user to the other.

#### Expected behavior
Attachment can be downloaded.

#### Observed behavior
File not found error.

**Comment by jasonblais** [comment]
Thanks @char101 for the report! This issue should be fixed with https://github.com/mattermost/platform/pull/4134 and included in our next release November 16

**Comment by char101** [comment]
Is it the same problem with #4134? 

IMO the problem is that attachments are organized by team while DM has not specific team (instead it looks at the currently selected team). Therefore if the team where the attachment was stored is different with the team where the attachment is viewed, a path mismatch will occur.

I think the solution is to append the team id in the `filenames` array.

**Comment by jasonblais** [comment]
#4134 fixed [this Jira issue](https://mattermost.atlassian.net/browse/PLT-3105) which sounded like it would be the same as what you experienced.

Let me know if I misunderstood your report,
