### ISSUE TITLE
trying to create simple slash command - AnonoChat

### ISSUE THREAD

**Issue by zguithues** [mattermost/platform#4341]
I'm trying to create a slash command that will create a conference room with AnonoChat.com

Here are the API instructions.
https://www.anonochat.com/#api

It's just a simple GET request sent to a URL, and the response includes the number, pin, & expiration.

however, it seems that the slash commands in mattermost are more complicated, and cannot handle sending a get request without including a token.  when i try my /anonochat command, it says
`Command with a trigger of 'anonochat' returned response 403 Forbidden`

There is an app for slack and hipchat that can be installed directly from their website
https://www.anonochat.com/#slack

It looks like it would be possible to setup a web server to respond to the request, but that seems like overkill for this kind of integration.

Any thoughts/help?

**Comment by jasonblais** [comment]
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information.
