### ISSUE TITLE
Message Box unreachable when zoomed out and resized

### ISSUE THREAD

**Issue by klandaika** [mattermost/platform#4342]
#### Summary
After setting zoom to < 100%, if application window is resized the "Write a message..." box  (and other controls) go off screen and cannot be reached by scrolling. To get them back must reset to "Actual Size" and then resize the window again.

Observed in *Windows* application
In *Chrome* browser same issue could not be reproduced.

#### Steps to reproduce
Version 3.4.1

1. Join any channel
2. In menu click **View->Zoom Out** at least once
3. Resize the window

#### Expected behavior
The *Search*, *Recent Mentions*, *Flagged Posts*, and *Write a message* box should remain on the screen.

#### Observed behavior
The above mentioned controls are gone, and cannot be reached by scrolling. Also the end of the conversation cannot be reached by scrolling.

### Screenshots
Zoomed out before resize:
![image](https://cloud.githubusercontent.com/assets/6818055/19741982/0883b27a-9b91-11e6-830e-f0e3804f433e.png)

After resize by a few pixels:
![image](https://cloud.githubusercontent.com/assets/6818055/19742068/6cd972e6-9b91-11e6-8c9c-63a9596a46a8.png)

**Comment by jasonblais** [comment]
Thanks @klandaika for the report!

This is indeed a known issue on the desktop app -- we have a partial fix scheduled for the next release, but the proper fix is tracked on [our desktop repo](https://github.com/mattermost/desktop/issues/334). Will close this issue report and we can track it there.

**Comment by klandaika** [comment]
@jasonblais, sorry, I didn't realize there is separate repo for desktop apps. Thanks.
