### ISSUE TITLE
[Help Wanted] Add focus to center text area when creating a new public/private channel

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4343]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details**

This improvement is to put the cursor focus in the center text area when creating a new public/private channel.

**Comment by goelrohan6** [comment]
@lfbrock can you tell me which file should I navigate to, to make the changes ?

**Comment by jasonblais** [comment]
Thanks for your interest @goelrohan6! 

@digitaltoad already submitted a [fix for the issue](https://github.com/mattermost/platform/pull/4344), but please feel free to take a look at our other [open 'Help Wanted' GitHub issues](https://github.com/mattermost/platform/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20Help%20Wanted).

**Comment by jasonblais** [comment]
Closed via #4344
