### ISSUE TITLE
make package fails

### ISSUE THREAD

**Issue by gabx** [mattermost/platform#4346]
#### Summary
Running `$ make package` fails

#### Environment

    Linux 4.7.6-1-hortensia
    argv "/usr/bin/node" "/developement/node_modules/bin/npm" "run" "build"
    node v6.8.0
    npm  v3.10.8
    code ELIFECYCLE
    mattermost-webapp@0.0.1 build: NODE_ENV=production webpack

#### Steps to reproduce

    $ mkdir ~/go
    $ export GOPATH=$HOME/go
    $ export PATH=$PATH:$GOPATH/bin
    $ ulimit -n 8096
    $ cd ~/go
    $ mkdir -p src/github.com/mattermost
    $ cd src/github.com/mattermost
    $ git clone https://github.com/mattermost/platform.git
    $ cd platform
    $ cd src/github.com/mattermost
    $ make package

#### Expected behavior
successful build

#### Observed behavior
    ERROR in ./components/rename_channel_modal.jsx
    Module build failed: SyntaxError: /developement/build/platform-release-3.4/src/github.com/mattermost/platform/webapp/components/rename_channel_modal.jsx: Only one default export allowed per module. (311:0)

#### Possible fixes
You can not use more than one export default in a file. If you need to export multiple things you need to use named export

**Comment by gabx** [comment]
I managed to build successfully  with removing `default` from the declaration `export default class ...` from 3 files (the ones which make the build fail): 

- webapp/components/error_bar.jsx
- webapp/components/edit_channel_purpose_modal.jsx 
- webapp/components/rename_channel_modal.jsx

Now I have no idea if this fix did break something else, thus the reason why I don't write a PR.

**Comment by coreyhulen** [comment]
Can you make sure you have the latest version of the repo?  The issues you described are already fixed on master.  For example https://github.com/mattermost/platform/blob/master/webapp/components/rename_channel_modal.jsx#L47 doesn't have `export default class RenameChannelModal extends React.Component`

**Comment by gabx** [comment]
I worked with 3.4.0, and this version has the issue.
Master does not have this issue, right. But as I am building a .rpm package for my distro (Fedora), best would be to work with versions, and in my case the last one is 3.4.0. 
Maybe a 3.4.1 with this issue corrected?

I close this issue as it no longer exists.
