### ISSUE TITLE
MM app for Mac auth trough GitLab with Google auth

### ISSUE THREAD

**Issue by kdeyko** [mattermost/platform#4347]
#### Summary
Impossible to sign in to Mattermost through GitLab OAuth with Google auth

#### Steps to reproduce
1) Open latest version of Mattermost for Mac app (3.4.1)
2) Fill the fields with your team settings
3) Click "Sing in with Gitlab" button (it should be set up before, in my case gitlab is on another server)
4) On Gitlab login page click "Sing in with Google" button (it should be set up before).
5) On Google login page type your email and click "Next" button

#### Expected behavior
After the step 5 it should ask for a password and then redirect to MM already authenticated.
I know it MUST work because it does in MM app for iPhone.

#### Observed behavior
But when you click the "Next" button in step 5 it just become not active and nothing happen then.
If you open the Developer Tools (option+cmd+I) there are some errors in console:

[team] Uncaught Error: Sorry, Mattermost does not support window.eval() for security reasons.webview.addEventListener.e @ index.js:529
index.js:529 [team] Uncaught ReferenceError: botguard is not definedwebview.addEventListener.e @ index.js:529
index.js:529 [team] Uncaught Error: Invalid JSON string: {"photo_url":"","name":"","email":"name@example.com","shadow_email":"","encoded_profile_information":"APMTqunHHxZjx45SRtd9jxUD6TzvgYPitm43p2yo3Fe9VDxjNN94o6o5UQ0tpQoScfEKyw84HtEzJaz3XxTDNEmUqjOui2Jct9CJ8UkM5pSXQF4hnG3cGbXaR_78h95iuotL_B3fHt","recovery_url":"https://accounts.google.com/signin/recovery?continue\u003dhttps%3A%2F%2Facc…6Email\u003dname%40example.com\u0026ignoreShadow\u003d0\u0026hl\u003den","should_redirect_in_browser_drivefs":false,"action":"ASK_PASSWORD"}webview.addEventListener.e @ index.js:529

![2016-10-27 11 47 56](https://cloud.githubusercontent.com/assets/23095354/19760750/c56999ea-9c3b-11e6-8d67-36f53b98edd7.png)

**Comment by it33** [comment]
Per documentation, "double SSO" (chaining GitLab SSO to another SSO provider) [is not supported](https://docs.mattermost.com/deployment/sso-gitlab.html#notes). 

It may work in some cases, but it's beyond the scope of the project to set up the infrastructure to test and validate double SSO on all the different clients. 

You're welcome to fork the Android app to adjust it for your specific needs, we just can't set the expectation of support as an official feature. 

When the Mattermost projects officially supports a feature, we need to commit to high quality documentation, testing and community support. This means we need to be very deliberate about our scope.
