### ISSUE TITLE
API create post ignores create_at parameter

### ISSUE THREAD

**Issue by rwillmer** [mattermost/platform#4349]
#### Summary

I create a post using the API which includes a 'create_at' parameter for an old date (I'm importing some old data into a channel and want to keep the original posting dates). This date is ignored and the post is created with the current time.
#### Steps to reproduce

Version: 3.4.0

$ curl --request POST \
  --url <HOST>/api/v3/teams/<team_id>/channels/<channel_id>/posts/create \
  --header 'authorization: Bearer <token>' \
  --data '{ "create_at": 1463076386000, "channel_id": "<channel_id>" , "message": "i am an old msg"}'
#### Expected behaviour

I would expect the post to be created with a date back in May 2016. 
#### Observed behaviour

I see a post created with a date of today.
#### Possible fixes

https://github.com/mattermost/platform/blob/master/api/post.go#L135

I think this line should take note of any 'create_at' param included in the API call, rather than always setting create_at = 0

**Comment by jasonblais** [comment]
Thanks for the report @rwillmer! I created a [Jira ticket for us to track it](https://mattermost.atlassian.net/browse/PLT-4574). 

I'm going to check with our developers on Monday to confirm whether we're setting the `create_at` parameter to 0 for a reason. I'll get back to you here with the information.

If there isn't a reason to set `create_at` to 0, would you be interested in submitting a fix for it? Looks like you've already identified where the fix might be done.

**Comment by rwillmer** [comment]
It's unlikely I'd be able to submit a fix anytime soon; I'm not a Go programmer (yet). 

I did get as far as following the dev instructions for setting up a branch, but then hit a problem when I searched for instructions for how to debug a Go program, and came across all the posts saying this was really hard. So I do intend to learn how to program Go, but I'm not sure server-side code is a good place to start.

If someone could fix this for me (I'm hopeful that it would be quick for someone who knows what they're doing), I'd be more than happy to contribute back some time in documentation, testing, etc.

**Comment by rwillmer** [comment]
It turns out your test harness makes it quite easy to get started; testing a fix now.

**Comment by jwilander** [comment]
This is done on purpose because we do not want to trust the client. If we did trust the client on the `CreateAt` field then any one of your users to make posts appear before they were actually created, which will disrupt the correct history of posts and is a security flaw.

If you're trying to migrate data, I'd suggest doing it using a script to insert what you need into the database as we don't currently have API support for migrating from one Mattermost instance to another.

**Comment by rwillmer** [comment]
What is the purpose of the CreateAt field in the API call then?

I understand your point about security; but in this instance, I'm the SuperUser, so shouldn't my use of the client be trusted?

**Comment by jwilander** [comment]
The API call just accepts a post object to create but you don't need to specify every field on the post, just the ones you care about.

I would be OK with allowing the system admin to specify the `CreateAt` field, can't see a reason not to. @jasonblais would you be able to modify the ticket you created above to be an improvement and to only allow the setting of the `CreateAt` field on posts if the user is a system admin?

**Comment by jasonblais** [comment]
@jwilander Ticket updated

**Comment by rwillmer** [comment]
OK, I'll rework my PR. Thanks.

**Comment by rwillmer** [comment]
If a non-system-admin user includes this CreateAt field, then which behaviour would you prefer?

1. silently ignore it, as now
2. raise an error, to let them know they don't have the right credentials to make that call

**Comment by jwilander** [comment]
Let's just silently ignore it like we're doing now

**Comment by jasonblais** [comment]
Closed via #4409, thanks @rwillmer!
