### ISSUE TITLE
[Help Wanted] Slash command: goto_location not working as expected

### ISSUE THREAD

**Issue by nelfer** [mattermost/platform#4359]
#### Summary

Element `goto_location` does not open external URLs (as described in documentation)
#### Steps to reproduce

In order to reproduce, you will need a server/service that returns the expected mattermost JSON payload. Then create a slash command that uses that endpoint. In this payload if goto_location contains an external URL, the user only gets redirected to the team selection page (instead of the URL)
#### Expected behavior

The `goto_location` when present, should open the URL specified in a new tab (in case of browser interface) and in the browser in case of the desktop/mobile app.
The URL should be handled in a way that it supports any custom protocol that the user has configured in their computer (meaning, not just http/https, but URL could be ftp:// or ssh://, mailto://, etc. If the user has the correct associations, URL should open the proper program)
#### Observed behavior

It seems like the current code is using React `browserHistory.push()` which probably only opens relative URLs.
#### Possible fixes

Using `window.open()` could probably solve this. The code might need to identify if URL is relative (if it starts with `/` then it's probably relative) to use current `browserHistory.push` but otherwise use `window.open`
File `create_post.jsx`
Line `141`
https://github.com/svrcekmichal/mattermost-platform/blob/master/webapp/components/create_post.jsx

**Comment by jasonblais** [comment]
Thanks @nelfer for the report!

[Jira ticket created here](https://mattermost.atlassian.net/browse/PLT-4585), would you be interested in submitting a fix?

**Comment by cpanato** [comment]
@jasonblais how can I reproduce that? I dont know how to create those steps, can you help me ?
thanks

**Comment by jasonblais** [comment]
@nelfer would you have more concrete repro steps for the issue you had?

**Comment by nelfer** [comment]
Hi @jasonblais & @cpanato 
This requires a slash command setup and a server that outputs the JSON as specified here in the documentation:
https://docs.mattermost.com/developer/slash-commands.html

I was doing a quick http://appear.in integration, the slash command /appear would generate a random name and give the URL http://appear.in/<randomname>

The idea was to put this URL also in the property goto_location so that it will open the browser automatically. But based on source code observation, that's only for relative path URLs.

I guess a relatively easy way to test it is to create a JSON file with the expected message format, put it in a website, point a slash command to that URL and see the behavior.

**Comment by nelfer** [comment]
Maybe I should ask, what's available in your development environment? IIS? node? Apache?
I believe creating a simple file with the format and posting it to a web server should be enough. The JSON format should be something like this:

```
{
  "response_type": "in_channel",
  "text": "The URL http://appear.in/mattermost-debug",
  "username": "robot",
  "goto_location": "http://appear.in/mattermost-debug"
}
```

Drop this file as command.json into your web server root and then create a slash command pointing to it (assuming you are testing locally): `http://localhost/command.json`
When you run the slash command, it will output the text, but then it will redirect you to the team selection page.

**Comment by jasonblais** [comment]
Fixed by @5507, thanks @cpanato, @nelfer!
