### ISSUE TITLE
[Help Wanted] Update introduction message at top of channel/private groups

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4361]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-599))

Update pre-amble at top of channel/private groups

For channels, change the message to:
"This is the start of the [CHANNEL UI NAME] channel created by [username] on [CREATION DATE, in the format October 27, 2015]. Any member can join and read this channel."

If the channel purpose is set, also show: "This channel's purpose is: [CHANNEL PURPOSE]"

If it's a private group, change the message to:
"This is the start of the [CHANNEL UI NAME] channel created by [username] on [CREATION DATE]. Only invited members can see this private group."

If the group's purpose is set, also show: "This channel's purpose is: [CHANNEL PURPOSE]"

**Comment by cpanato** [comment]
Can I take this ticket?

**Comment by cpanato** [comment]
working on that

**Comment by cpanato** [comment]
https://github.com/mattermost/platform/pull/4508

**Comment by jasonblais** [comment]
Closed via #4508
