### ISSUE TITLE
[Help Wanted] Add an active state for recent mentions and flagged posts icons

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4363]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4374))

The "@" and "flag" icons next to the search bar do not have a distinct default and active state, which is against the [Mattermost UX guidelines](https://docs.mattermost.com/developer/fx-guidelines.html#button-states).

This issue adds three states for the "@" and "flag" icons:
- an active state, when a user is viewing a list of recent mentions ("@" icon is active) or flagged posts ("flag" icon is active). The color should be the same as is currently used for the hover effect
- on hover effect, when a user is hovering over the "@" or "flag" icons. The color should be the same as is currently used for the hover effect, **with opacity = 0.5**
- default state when neither of the above occurs. The colour should be the same as is used now.

![image](https://cloud.githubusercontent.com/assets/13119842/19788753/3a4ca8b0-9c78-11e6-8137-ce71ed1e6471.png)

**Comment by kulak-at** [comment]
I can work on it.

**Comment by jasonblais** [comment]
Awesome!! 👍

**Comment by jasonblais** [comment]
Thanks @kulak-at! Resolved
