### ISSUE TITLE
[Help Wanted] Cannot use the System Console when a server has no teams

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4364]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4372))

On a clean system before creating a team, the System Admin should have the option to use the System Console.

**Comment by cpanato** [comment]
I tested this using the current master and I was able to access the system console without any team

![screen shot 2016-12-22 at 16 13 19](https://cloud.githubusercontent.com/assets/4115580/21430042/bd9d1460-c861-11e6-8ca0-86708d5eaf1b.png)

**Comment by lfbrock** [comment]
Thanks @cpanato, I'll send this back to triage to see if it reproduces for anyone else or if we can close the issue.
