### ISSUE TITLE
[Help Wanted] Update browser tab title when switching to Integrations or Custom Emoji pages

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4365]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.
---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4414))

[Help Wanted] Update browser tab title when switching to Integrations or Custom Emoji pages.

This is a follow-up to previous Hacktoberfest pull request: https://github.com/mattermost/platform/pull/4221

**Comment by bolecki** [comment]
Hey @jasonblais, I would like to work on this one!

**Comment by jasonblais** [comment]
Closed via #4379, thanks @bolecki!
