### ISSUE TITLE
[Help Wanted] Change default help link to https://docs.mattermost.com/guides/user.html

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4366]
Help link is out-of-date after docs change--should point to User'a Guide, not main menu

**Comment by bolecki** [comment]
Hi @it33!  Is this something we can do directly from the config file?  If so, I can submit a PR for this.  It looks like most of the links are currently redirects from about.mattermost.com.

**Comment by it33** [comment]
Hi @bolecki, I totally forgot, we don't need a code change to do this. The [`config.json`](https://github.com/mattermost/platform/blob/master/config/config.json#L141) points to `https://about.mattermost.com/default-help/` and we set that up as a redirect so we can change the URL destination without code changes. 

I've just updated the redirect and now it's pointing to the right place. 

Thanks for offering the PR, my mistake that it's not needed :)
