### ISSUE TITLE
Broken login with gitlab+cas and android app

### ISSUE THREAD

**Issue by lalmeras** [mattermost/platform#4376]
#### Summary

During login phase on android app (master branch) on a gitlab+cas mattermost instance, login fails because gitlab and cas validation triggers third-party browser (url identified as external) in place of the app browser view.
#### Steps to reproduce

Connect with android app on a gitlab+cas mattermost instance. I don't test further, but this bug should also trigger on a gitlab mattermost instance as 
#### Expected behavior

Login page is opened in app browser (in place of system browser) and login can be done successfully.
#### Observed behavior

As login page is opened in system browser, authentication is not handled by app. It is impossible to log in in mattermost android application.
#### Possible fixes

I'll post a PR.

**Comment by lalmeras** [comment]
Added PR : https://github.com/mattermost/android/pull/41

**Comment by esethna** [comment]
Closing with comments made in [PR](https://github.com/mattermost/android/pull/41).

**Comment by lalmeras** [comment]
Hi, if anyone follows this issue or visit this ticket, the issue is fixed with mattermost android client 1.1.0.
