### ISSUE TITLE
Faulty and inconsistent translations in German translation

### ISSUE THREAD

**Issue by ulfklose** [mattermost/platform#4383]
#### Summary
I found some faulty and inconsistent translations in the German translation.

#### Steps to reproduce
N/A

#### Expected behavior
N/A

#### Observed behavior
N/A

#### Possible fixes
I corrected the faulty translations and corrected them in a fork I created.

**Comment by jasonblais** [comment]
Thanks @ulfklose for the updates!

Our translations are managed in the [Mattermost Translation Server](http://translate.mattermost.com/de/mattermost/) from which changes are submitted to the `master` branch each week.

This means that any of your changes here will unfortunately be overwritten by the next pull request pulled from the Translation Server.

Could we have your help submitting your updates [in the Translation Server instead](http://translate.mattermost.com/de/mattermost/)? We wouldn't want to lose the great work you've done here.

**Comment by jasonblais** [comment]
Hey @ulfklose, would love to have your changes reflected on the product.

If you're interested, please consider joining our [Mattermost German community channel](https://pre-release.mattermost.com/core/channels/i18n-german), which is open to everyone

**Comment by jasonblais** [comment]
Thanks for joining the channel and helping with translation updates! 

Closing the issue,
