### ISSUE TITLE
[Help Wanted] Enable iCloud file uploads from iOS app

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4386]
Using mobile web experience in Safari on iOS allows you to upload iCloud files, however the [Mattermost iOS application](https://github.com/mattermost/ios) does not support this (it does support DropBox, Photos and other apps, just not iCloud). 

This ticket is to figure out why iCloud isn't supported in the iOS app and submit a patch to add support. 

[Link to community request for this](http://forum.mattermost.org/t/possible-attach-a-file-in-icloud-to-a-channel-message/2430).

**Comment by senk** [comment]
iCloud Works in iOS Simulator. Cannot test it on hardware because i have no developer subscription.
![](http://i.imgur.com/rJkGJZP.png)

**Comment by jasonblais** [comment]
This works for me on the first generation iOS app as well.

Given the first generations apps are in maintenance mode and iCloud is supported at least on selected devices such as iPHone 5s, closing this issue.
