### ISSUE TITLE
[Help Wanted] API for creating direct message channels returns empty channel for existing channels

### ISSUE THREAD

**Issue by jwilander** [mattermost/platform#4395]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory (new to codebase)

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-3736))
The API is intended to return the created channel object or the existing channel object if that direct message channel was already created. Right now, if the channel exists an empty channel object is returned, this should be fixed.

**Files you'll likely need to look at and/or modify**:
- https://github.com/mattermost/platform/blob/master/api/channel.go#L156 
- https://github.com/mattermost/platform/blob/master/store/sql_channel_store.go

**Comment by rwillmer** [comment]
I'll take a look at this.

**Comment by jwilander** [comment]
Awesome, thanks @rwillmer!

**Comment by cpanato** [comment]
@jwilander can you check if this is already fixed?

I saw this test:

```
func TestCreateDirectChannel(t *testing.T) {
	th := Setup().InitBasic()
	Client := th.BasicClient
	user := th.BasicUser
	user2 := th.BasicUser2

	var channel *model.Channel
	if result, err := Client.CreateDirectChannel(th.BasicUser2.Id); err != nil {
		t.Fatal(err)
	} else {
		channel = result.Data.(*model.Channel)
	}

	channelName := ""
	if user2.Id > user.Id {
		channelName = user.Id + "__" + user2.Id
	} else {
		channelName = user2.Id + "__" + user.Id
	}

	if channel.Name != channelName {
		t.Fatal("channel name didn't match")
	}

	if channel.Type != model.CHANNEL_DIRECT {
		t.Fatal("channel type was not direct")
	}

	// Don't fail on direct channels already existing and return the original channel again
	if result, err := Client.CreateDirectChannel(th.BasicUser2.Id); err != nil {
		t.Fatal(err)
	} else if result.Data.(*model.Channel).Id != channel.Id {
		t.Fatal("didn't return original direct channel when saving a duplicate")
	}

	if _, err := Client.CreateDirectChannel("junk"); err == nil {
		t.Fatal("should have failed with bad user id")
	}

	if _, err := Client.CreateDirectChannel("12345678901234567890123456"); err == nil {
		t.Fatal("should have failed with non-existent user")
	}
}
```
on part says: `Don't fail on direct channels already existing and return the original channel again`

**Comment by jwilander** [comment]
Yes, this is fixed. Thanks for pointing that out @cpanato !
