### ISSUE TITLE
[Help Wanted] Move instances of Client.updateTeam() in components to an action

### ISSUE THREAD

**Issue by jwilander** [mattermost/platform#4397]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory (new to codebase)

**Details**: ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4593))
To be [Flux](https://facebook.github.io/flux/docs/actions-and-the-dispatcher.html)-compliant our web utilities should be separate from our views and UI components. Views should use re-usable actions instead of directly interacting with the web utilities (specifically Client/client.jsx in our case).

Move any instances of `Client.updateTeam()` inside of the [components directory](https://github.com/mattermost/platform/tree/master/webapp/components) into an action inside of [webapp/actions/team_actions.jsx](https://github.com/mattermost/platform/blob/master/webapp/actions/team_actions.jsx) and use the new action in place of where the `Client.updateTeam()` invocations were.

Please see other actions inside of [webapp/actions/team_actions.jsx](https://github.com/mattermost/platform/blob/master/webapp/actions/team_actions.jsx) for examples.

A quick grep at the time of creation of this ticket shows `Client.updateTeam()` being used in:
- https://github.com/mattermost/platform/tree/master/webapp/components/team_general_tab.jsx

**Comment by cpanato** [comment]
I will take care this one

**Comment by jasonblais** [comment]
Closed via #4574, thanks @cpanato!
