### ISSUE TITLE
[Help Wanted] System Admins can create channels with invalid team IDs

### ISSUE THREAD

**Issue by jwilander** [mattermost/platform#4398]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory (new to codebase)

**Details**: ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4302))
By submitting an API request with an incorrect or random team ID, orphaned channels that have no team can be created.

To remedy the issue, we should add a check to make sure the team exists in `createChannel()` in [api/channel.go](https://github.com/mattermost/platform/blob/master/api/channel.go) before checking permissions. Only need to check the team exists if it's provided by the client (aka the length of the channel.TeamId is greater than zero).

Files you should need to look at or modify:
- https://github.com/mattermost/platform/blob/master/api/channel.go

**Comment by foggy1** [comment]
I'll take a crack at this issue

**Comment by jwilander** [comment]
Awesome, much appreciated!

**Comment by foggy1** [comment]
@jwilander The most relevant line appears to be line 55.,
`if len(channel.TeamId) == 0 {
		channel.TeamId = c.TeamId
	}`
First off, should this check be altered, or should there simply be another conditional before it?  I'm not sure what c's value is when this function is called via POST requests to /create.

Second, in the issue, it's said that we can just check for channel.TeamId's length to be greater than zero to verify if it exists.  But couldn't channel.TeamId simply have a non-existent TeamId (making its length > 0) that would be equally problematic?

**Comment by jwilander** [comment]
Actually I was originally thinking you'd need to hit the database to see if the team exists but it makes more sense to just reject the request and error out if `c.TeamId != channel.TeamId && len(channel.TeamId) > 0` . `c.TeamId` will always be set in this context so you don't need to worry about it being blank.

The other option is to just quietly set `channel.TeamId = c.TeamId` but that could be confusing to the user if they're expecting the channel to be created for another team.

**Comment by cpanato** [comment]
this I think is fixed, I tested in the PR I submitted.

can you guys confirm? thanks!

**Comment by lfbrock** [comment]
Thanks @cpanato - I resolved the related Jira ticket so someone will go test + confirm the fix, will close this issue as well. Thanks!
