### ISSUE TITLE
Windows desktop: switching next/previous channel using keyboard (ALT-UP / ALT-DWN) does not work sometimes

### ISSUE THREAD

**Issue by ewirch** [mattermost/platform#4401]
After some uptime the desktop app stops responding to switching prev/next channel keyboard shortcuts. Other shortcuts (like CTRL-M or ALT-LEFT/RIGHT) do still work. Restarting the app fixes the problem. It's not possible to reproduce the problem reliably. It simply appears eventually.

**Comment by jasonblais** [comment]
Thanks @ewirch for the report!

Can you help answer the following questions about your environment, so we can better pinpoint the issue?
 1) Mattermost Server version (from the three dot menu > About Mattermost)
 2) Mattermost Desktop version (from menu bar at the top of the app > Help)
 3) Operating System (Windows / Mac / Linux)

And a couple additional questions:
 
 4) Have others on your team noticed the same issue? If so, has anyone used Mattermost on the browser and noticed the same issue?
 5) Does the issue clear after reloading the app (pressing `CTRL+R` on your keyboard reloads the app)
 6) If the answer to 5. is no, does the issue resolve after clearing cache and reloading the app (pressing `CTRL+SHIFT+R` on your keyboard clears cache + reloads the app)

**Comment by ewirch** [comment]
1) Server version: 3.4.0
2) App version: 3.4.1
3) OS: Windows
4) I'm the only one using the shortcuts until now. 
5) CTRL-R: fixes the problem

By testing for this comment, I discovered how to trigger the problem. Press ALT-SHIFT-UP/-DWN if there are no unread channels. Action will do noting, which is fine. But following ALT-UP/-DWN invocations will not do anything as well. No errors in developer tools console.

**Comment by jasonblais** [comment]
Thanks @ewirch! Very helpful, I see the problem now.

We in fact have fixed this issue on the `master` branch (PR here for reference: https://github.com/mattermost/platform/pull/4042). 

The fix will be available on Mattermost 3.5, which will release on November 16th. The release candidates will be available for testing on November 4th.
