### ISSUE TITLE
Notifications still sounding and popping even when disabled

### ISSUE THREAD

**Issue by madchap** [mattermost/platform#4403]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
When setting "Send desktop notifications" to "Only for mentions" or "Never", I still receive notifications with sound and pop-up.

It happens both when using the Desktop and when using the webapp directly with Google Chrome.

Originally posted on mattermost/desktop (https://github.com/mattermost/desktop/issues/356)

#### Steps to reproduce
* Operating System: Mac OSX or Linux Ubuntu 16.04
* Mattermost Desktop App version (See Help > Version Number): 3.4.1
* Mattermost Server version : 3.4.0 Team Edition.
* Clear steps to reproduce the issue: Just be part of a channel with monitoring alerts popping at an alarming rate, set your notifications to never, and enjoy the storm :)

#### Expected behavior
If set to "never", I should never be notified.
If set to "Only for notifications", my alias should be on the line.

#### Observed behavior
The setting doesn't take effect.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by esethna** [comment]
Hi @madchap, are you a part of multiple teams? We have a known issue where desktop notifications are disregarding the channel notification preference when using multiple teams. Jira issue [here](https://mattermost.atlassian.net/browse/PLT-4334)

**Comment by madchap** [comment]
Indeed, I am.

Do you think this is also related to the fact that, when you receive a private message or a mention, you get that one notification for all teams (and when you read it in one, it doesn't mark it read for the others?)

Thank you.
Best.
fred

**Comment by esethna** [comment]
That could be a possible cause. As part of the roadmap for v3.6, we are going to spend some time thinking through how notifications should work across multiple teams. The ticket will be addressed with that spec. Closing this issue to [track in JIRA](https://mattermost.atlassian.net/browse/PLT-4334).
