### ISSUE TITLE
Regression: channel linking and channel auto-complete only work for channels you are currently in

### ISSUE THREAD

**Issue by grundleborg** [mattermost/platform#4432]
#### Summary
Channel linking and autocomplete seem to only include channels you are already a member of.

#### Steps to reproduce
Type ! (soon to be ~) to get the autocompleter to appear. Notice only channels you are a member of are shown.

Try writing ~channel-name into a message for a channel you aren't in. It won't be autolinked.

#### Expected behavior
All channels are found.

#### Observed behavior
Only the ones you are currently in are found.

#### Possible fixes
I suspect this is something that was broken as a side effect of some of the recent performance improvements.

**Comment by lfbrock** [comment]
Thanks @grundleborg - I made a ticket here: https://mattermost.atlassian.net/browse/PLT-4621

Is this something you would be able to take a look at?

**Comment by grundleborg** [comment]
@lfbrock I'm happy to take a look at it, but I have fairly limited time at the moment, so if it needs addressing urgently then it might be better to assign it to someone else.

**Comment by lfbrock** [comment]
Found someone else to take a look at it, I think we should be able to get it fixed for v3.5

**Comment by lfbrock** [comment]
We looked into this + it's a larger issue to get it to work due to the performance changes that are made, so we've decided to wait until next release to fix it and will add a known issue in the changelog.

**Comment by jasonblais** [comment]
We'll track the issue in Jira as it's a larger change: https://github.com/mattermost/platform/issues/4432
