### ISSUE TITLE
[Help Wanted] Support all unicode letters in hashtags

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4461]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

Currently hashtags only work for alphanumeric characters. This improvement is to make them work for all unicode characters, so they work for other languages (eg for accented characters, Asian languages, etc). We need to be able to link hashtags containing these characters, and make sure that searching for these hashtags works properly.

@hmhealey has done some research into this already and added some details in this [Jira ticket](https://mattermost.atlassian.net/browse/PLT-2077), so if you're interested in working on this you can mention him on this ticket or message "harrison" on our Mattermost site https://pre-release.mattermost.com.

**Comment by jasonblais** [comment]
Closed via https://github.com/mattermost/platform/pull/4555, thanks @CometKim!
