### ISSUE TITLE
[Help Wanted] Auto-scroll Server Logs to bottom of logs in System Console

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4490]
By default in System Console > Reporting > Server Logs, the UI shows the top of the server logs, and the Admin needs to manually scroll to the bottom to see the latest messages. 

This ticket is to automatically scroll to the bottom of the server logs on load and when the "Reload" button is pressed.

**Comment by jasonblais** [comment]
[Jira ticket can be found here](https://mattermost.atlassian.net/browse/PLT-2060)

**Comment by cpanato** [comment]
working on that

**Comment by jasonblais** [comment]
Closed via #4527
