### ISSUE TITLE
[Help Wanted] Set focus to server log control in System Console when loading panel

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4491]
Repro: 

- Go to System Console > Reporting > Logs

Expected: 

- Logs control has focus and pressing UP/DOWN or PgUp/PgDn would scroll the logs

Observed: 

- Logs control DOES NOT have focus and pressing UP/DOWN or PgUp/PgDn does not scroll the logs until the user clicks into the control.

**Comment by jasonblais** [comment]
The associated Jira ticket is here: https://mattermost.atlassian.net/browse/PLT-4663

**Comment by cpanato** [comment]
@jasonblais PR submitted

**Comment by esethna** [comment]
Hi @cpanato, thanks for another PR! 

Just letting you know again, there may be a delay in reviewing and merging this PR as we are locking down feature and improvement contributions for the v3.6 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.6` on January 4th.

**Comment by jasonblais** [comment]
Closed via #4912, thanks @cpanato!
