### ISSUE TITLE
[Help Wanted] Disable file attachment icon after the maximum number of files is uploaded

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4495]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-137))

If maximum number of files is reached (i.e. 5 files), then the file attachment icon should be disabled until more files can be uploaded (that is, after at least 1 file removed so we're no longer at maximum).

When clicked on, it should show the existing maximum file error message ("Uploads limited to 5 files maximum. Please use additional posts for more files."), so users know why they can't upload more files.

**Comment by mikaoelitiana** [comment]
I want to work on this feature
