### ISSUE TITLE
[Help Wanted] Update error message when image exceeds max height/width

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4496]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-2242))

Update error message when image exceeds max height/width

Observed: Currently the error message says "Unable to upload image file. File is too large." which is confusing, since users expect this to mean the file is larger than the max file size of 50 MB.

Expected: Change the error message to "File above maximum dimensions could not be uploaded: [FILE_NAME]"

**Comment by raphael0202** [comment]
Hi! I'm working on it

**Comment by jasonblais** [comment]
Thanks @raphael0202!

**Comment by raphael0202** [comment]
I've just submitted a PR: https://github.com/mattermost/platform/pull/4535

**Comment by jasonblais** [comment]
Closed via #4535, thanks @raphael0202!
