### ISSUE TITLE
[Help Wanted] Clicking on @mention of a user in a post should show the profile popover.

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4498]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-1031))

Clicking on @mention of a user in a post should show the profile popover.

Repro:
1) Post a message `hey @username`
2) Click on the mention, `@username`

Observed: Currently clicking on an @mention searches for the user's name.

Proposed change: Clicking on an @mention opens the "profile popover". (This should be the same popover that shows up when clicking on a person's name beside their profile picture in the center channel - see screenshot for an example).

![image](https://cloud.githubusercontent.com/assets/13119842/20106443/2891d13e-a5a3-11e6-967f-45fd6e789460.png)

**Comment by S4KH** [comment]
Working on it. :peace_symbol:

**Comment by cpanato** [comment]
this is still valid? today when you click it open the contact popover. what other information do you guys want on that?

**Comment by jwilander** [comment]
@jasonblais can correct me if I'm wrong, but I think it means when you click on @ mention of someone. For example, in MM if someone mentions me in a post with `@joram`, clicking on `@joram` should show the contact popover as well

**Comment by cpanato** [comment]
ahh, in the post.

**Comment by jwilander** [comment]
I also updated this to intermediate difficulty since I think it'll be a bit more involved than originally thought

**Comment by jasonblais** [comment]
That's correct, I updated the title and description to clarify this a bit more @cpanato

**Comment by jasonblais** [comment]
Re-posted here to get community's attention: https://github.com/mattermost/platform/issues/5915
