### ISSUE TITLE
Mattermost v3.5.0 - RC6

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#4502]
This is a meta issue for v3.5.0 release updates. The final release will be available November 16. 

Please link to issues you believe may warrant a patch (please do not post issue here). It is the responsibility of the release manager assigned to this issue to decide whether or not to merge a patch for the final release.

See the [Draft Changelog](https://github.com/mattermost/docs/pull/518/files) for details on what's new.

After each new release candidate is cut, the download link and test server will be posted here, along with approved patches for the next release candidate.

**Comment by esethna** [comment]
## RC3 has been cut!

**Testing Links**

Test Server: http://rctesting.reddogsofwar.com/
Team Invite: http://rctesting.reddogsofwar.com/signup_user_complete/?id=5d13z7mks3rgdrm1y3pqiasujy

If you find any issues, please link to them in the comments here. 

**Approved issues to fix for RC4:**

**Comment by esethna** [comment]
## RC3 has been cut!

**Testing Links**

Test Server: http://rctesting.reddogsofwar.com/
Team Invite: http://rctesting.reddogsofwar.com/signup_user_complete/?id=p9irmoaaz7da98uxu8arqzinqo

If you find any issues, please link to them in the comments here. 

**Approved issues to fix for RC5:**
1. [Promoting member to a team admin gives no feedback to user](https://mattermost.atlassian.net/browse/PLT-4668?filter=12500): PR submitted
2. ["New Messages" line doesn't always disappear upon switching channels](https://mattermost.atlassian.net/browse/PLT-4666?filter=12500): @christopher in progress
3. [At mention autocomplete sometimes stays open after you've completed the word](https://mattermost.atlassian.net/browse/PLT-4600?filter=12500): ES to check in with @harrison
4. [WebRTC: Video/Audio not working on Windows Desktop App](https://mattermost.atlassian.net/browse/PLT-4732?filter=12500): @elias
5. [Mobile: The "more..." channels modal uses only half of the available screen](https://mattermost.atlassian.net/browse/PLT-4609?filter=12500): @asaad fix doesn't seem to be working

**Comment by fjarlq** [comment]
The link above to the Draft Changelog is for the wrong version (3.4.0).

I think this is the correct (3.5.0) link: https://github.com/mattermost/docs/pull/518/files

**Comment by esethna** [comment]
Thanks! updated.

**Comment by esethna** [comment]
## RC5 has been cut!

**Testing Links**

Test Server: http://rctesting.reddogsofwar.com/
Team Invite: http://rctesting.reddogsofwar.com/signup_user_complete/?id=t479bp7s3jd73n5eafujj63bgy

If you find any issues, please link to them in the comments here. 

**Approved issues to fix for RC6:**
1. [iOS app: UI breaks after clicking [...] menu and scrolling up and down the channel](https://mattermost.atlassian.net/browse/PLT-4754?filter=12500)
2. [Message draft is transferred to different channels](https://mattermost.atlassian.net/browse/PLT-4753?filter=12500)
3. [Stuck in a redirect loop after logging out of iOS app](https://mattermost.atlassian.net/browse/PLT-4746?filter=12500)
4. We are also investigating some Android push notification issues

**Comment by esethna** [comment]
## RC6 has been cut!

**Testing Links**

Test Server: http://rctesting.reddogsofwar.com/
Team Invite: http://rctesting.reddogsofwar.com/signup_user_complete/?id=a5c5frayz38ebrxqt595m6f9dh

If you find any issues, please link to them in the comments here. 

**Approved issues to fix for RC6:**

**Comment by esethna** [comment]
The final release build was cut from RC6. Closing this meta issue.
