### ISSUE TITLE
[Help Wanted] Increase unit test coverage of api/user.go

### ISSUE THREAD

**Issue by jwilander** [mattermost/platform#4503]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory (some unit tests might be more difficult to write)

**Details**:
In an effort to increase our unit test coverage, we're looking for some help writing some tests.

For example, in `api/user.go` the function `CheckUserDomain(user *model.User, domains string) bool` could use some increased coverage. The function's purpose is to check if a user's email domain matches a list of space-delimited domains provided as a string. If the domain matches, true is return otherwise false is returned. A test that covers all the possible inputs for this function would be added to `api/user_test.go`.

**If you would like to help, feel free to comment with which function(s) you'd like to increase coverage for.**

A non-exhaustive list of functions in api/user.go that are good candidates for increased coverage:
* ~CheckUserDomain~
* ~IsUsernameTaken~
* oauthToEmail
* emailToOAuth
* sendEmailChangeUsername
* SendEmailChangeVerifyEmail
* sendEmailChangeEmail
* PermanentDeleteAllUsers
* updateUser
* getInitialLoad
* RevokeAllSession
* SendVerifyEmail
* CreateOAuthUser
* IsVerifyHashRequired

Please add and modify all unit tests inside `api/user_test.go`. See the [instructions here](https://docs.mattermost.com/developer/developer-setup.html#running-only-specific-unit-tests) for how to run a specific unit test.

**Comment by raphael0202** [comment]
I'm currently working on adding tests to CheckUserDomain

**Comment by raphael0202** [comment]
I've submitted a PR for CheckUserDomain and IsUsernameTaken functions

**Comment by jwilander** [comment]
Much appreciated! I can review it tomorrow morning
