### ISSUE TITLE
[Help Wanted] Change auto selection behaviour of emoji to be more UX/Type friendly

### ISSUE THREAD

**Issue by milouse** [mattermost/platform#4510]
#### Summary

In some languages, like in french, typography rules require colons to be prefixed with a space, like this:

> Blablabla : toto tata

Currently, typing a lone colon directly open emoji selection popin and doing a Shift + enter (to create a new line to begin a list for exemple) auto-select the first emoji, what is very troublesome.

This issue is directly inspired by this one for gitlab : https://gitlab.com/gitlab-org/gitlab-ce/issues/22058

#### Steps to reproduce

Type some text in the chat box ; then, to introduce a list, I want to type ":" then press "shift+enter" to begin to enumerate my list.

#### Expected behavior

> Blablabla : 
>  1. first item
>  2. second item

#### Observed behavior

> Blablabla :angry: 
> 1. first item
> 2. second item

Saw this gif from the gitlab related bug : 

![](https://gitlab.com/gitlab-org/gitlab-ce/uploads/3bcdcae47a6e8146c7f0b7c8d6899863/2016-10-21_15.45.56.gif)

#### Possible fixes

- Still spawn popup immediately at just a colon :
- Remove instant selection of first item.
- Select is possible with "press down arrow or right arrow"
- If one emoji is selected "enter" would summon the selection
- When you are 1 character into an emoji like: :c it will begin to automatically select the top row item as it does right now even without a single character.

**Comment by jasonblais** [comment]
Thanks for the note @milouse! 

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by milouse** [comment]
I'm sorry but I don't think it is a feature request: if we cannot write proper french, it's not a feature problem, it's a bug!

And I'm sorry too I'll not have time to work on this any time soon. Thus if every one else want to take it, feel free to do it.

**Comment by jasonblais** [comment]
Thanks @milouse, 

We discussed it in a UX meeting and this makes sense. Wondering if someone would be interested in helping update the autoselection behaviour?

----

Below is more details of the specification:

After typing `:`, propose removing instant selection of the first item on emoji autocomplete list so that the first entry is not selected unless
 - up/down arrows are used to navigate through autocomplete results
 - any letter is typed following a ":", e.g. `:b`
 - user hits [TAB]
 - user hits [ENTER] and **Account Settings > Advanced > Send messages on CTRL + ENTER** is off
 - user selects the first emoji with a mouse or by tapping on touch screen

We should continue showing the popup with emoji autocomplete though after typing `:`, the first item just isn't instantly selected, unless one of the above cases has occurred.

**Comment by milouse** [comment]
Thank you very much for your understanding of this issue. Also, after having read again my previous message, I'd say sorry for my over-angry tone. You've done an awesome product and can understand you've other priorities than dealing with angry froggies. Anyway, thanks again. I hope you'll find someone to take this soon.

I've just a little concern with the line

> user hits [ENTER] and Account Settings > Advanced > Send messages on CTRL + ENTER is off

Be aware to well differentiate a **pure** `[ENTER]` hit and a `shift+[ENTER]` hit. Because today, a `shift enter` also auto-select the first item and do the cariage return. Then, I'm ok with this spec, only if you replace this line by : 

user hits `[ENTER]` and user is **not** currently holding the `shift` key (thus he's doing a `Shift+Enter`) or Account Settings > Advanced > Send messages on CTRL + ENTER is **off**

Cheers

**Comment by jasonblais** [comment]
Thanks for the note, updated in the description! 

We value everyone's feedback and our practice is to share feature requests or improvements in the [Feature Idea forum](https://mattermost.uservoice.com/forums/306457-general/) to hear others' feedback in the community too. 

However the design here made sense and we'd love to have a contribution that improves the user experience for our users.

Thank you for using Mattermost! Would love to see you also join our [daily built instance of Mattermost, open to everyone in the community](pre-release.mattermost.com/core/channels/town-square), where you can participate in design discussions and stay updated on latest features.

**Comment by lfbrock** [comment]
Closing - no longer an issue since we switched emoji autocomplete to only open after typing two characters after the colon
