### ISSUE TITLE
[Help Wanted] Add API call to get a user by their username

### ISSUE THREAD

**Issue by hmhealey** [mattermost/platform#4513]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Ticket Link**: https://mattermost.atlassian.net/browse/PLT-3762

**Difficulty**: Intermediate

**Details**:

We want to add some simple APIs to make it easier for integrations to use Mattermost. We occasionally get questions about how to get a specific user/channel/team from the server, and our current solution of "get everything and then look for the one you want" isn't very good. This is one of a set of new APIs to get a single user/channel/team by a unique identifier other than its `Id` field.

Unit tests and [documentation](https://github.com/mattermost/mattermost-api-reference) will also need to be added.

**HTTP Method**: GET
**Description**: Gets a sanitized User object with the given [username](https://github.com/mattermost/platform/blob/master/model/user.go#L31). See the [`getUser` function in `api/file.go`](https://github.com/mattermost/platform/blob/master/api/user.go#L939) for an example of how to sanitize it.
**Route**: `/api/v3/users/name/{username:[A-Za-z0-9_\-.]+}`

**Comment by cpanato** [comment]
I can try this one, to see if i can move to intermediate tickets :)

**Comment by cpanato** [comment]
@hmhealey the point here is use the getuser code to sanitize the object, but we first need test if the user exist right?
and who can get the user information? anyone logged?

**Comment by cpanato** [comment]
this new api should also go to the user.go ?

**Comment by jwilander** [comment]
Hi @cpanato, so to add an API there's a few things you need to do:

1. In `api/user.go` add the route definition at the top. You can see what the Route prefixes are by looking in `api/api.go`
2. In `api/user.go` add the function to handle the new route you added. In here you can hit the database and perform any logic you need to satisfy the API
3. Once that is done, you'll need to add a driver function in `model/client.go` and then use that in a unit test in `api/user_test.go` to make sure your new API works correctly
4. You'll also need to add a function to the JavaScript driver  in `webapp/client/client.jsx` and a simple client unit test in `webapp/tests/client_user.test.jsx`
5. Submit your PR to the platform repo and then finally submit the API documentation to https://github.com/mattermost/mattermost-api-reference

Take a look at https://github.com/mattermost/platform/blob/master/api/user.go#L75 and other APIs for an example. That route will get a single user and should have a lot in common with what you're trying to do with this API

**Comment by jwilander** [comment]
Wonderful work on this @cpanato
