### ISSUE TITLE
[Help Wanted] Add API call to get a channel by its name

### ISSUE THREAD

**Issue by hmhealey** [mattermost/platform#4515]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Ticket Link**: https://mattermost.atlassian.net/browse/PLT-3762

**Difficulty**: Intermediate

**Details**:

We want to add some simple APIs to make it easier for integrations to use Mattermost. We occasionally get questions about how to get a specific user/channel/team from the server, and our current solution of "get everything and then look for the one you want" isn't very good. This is one of a set of new APIs to get a single user/channel/team by a unique identifier other than its `Id` field.

Unit tests and [documentation](https://github.com/mattermost/mattermost-api-reference) will also need to be added.

**HTTP Method**: GET
**Description**: Gets the Channel object with the given [name](https://github.com/mattermost/platform/blob/master/model/channel.go#L31) on the given team 
**Route**: `/api/v3/teams/{team_id}/channels/name/{channel_name:[A-Za-z0-9_-]+}`

**Comment by cpanato** [comment]
I can work on this

**Comment by cpanato** [comment]
this ticket can be closed :) @jasonblais

**Comment by jasonblais** [comment]
Thanks @cpanato, great work! :)
