### ISSUE TITLE
[Help Wanted] Remove autocomplete on team creation text box

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4528]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory

**Details**: https://mattermost.atlassian.net/browse/PLT-4719

On Edge, the browser autocomplete shows up on the team creation screen: 

<img width="506" alt="screenshot 2016-11-10 13 10 07" src="https://cloud.githubusercontent.com/assets/9354841/20188509/f6620cce-a746-11e6-8b7a-7de38321cbfa.png">

This ticket is to turn autocomplete off for that field, so it doesn't show up.

**Comment by cpanato** [comment]
Is to remove when using edge or remove completely the functionality?

**Comment by lfbrock** [comment]
Hi @cpanato - It's to completely turn off the browser autocomplete for that field. It's just that it is only visible on Edge for some reason.

**Comment by cpanato** [comment]
ok, cool, will work on that :)

**Comment by cpanato** [comment]
I tested the current master on a microsoft edge and I didnt see any autocomplete.

there are any steps to reproduce that?

thanks

**Comment by lfbrock** [comment]
@esethna - does this still reproduce for you on master?

**Comment by esethna** [comment]
@cpanato and @lfbrock, yes this still repros for me on master. Repro steps would be:

1. Main menu > Create a New Team
2. Type a Team Name, Next
3. On the Team URL page, select and backspace the automatically suggested team URL
4. The autocomplete pops up

**Comment by cpanato** [comment]
I will try thanks @esethna

**Comment by cpanato** [comment]
I tried in MS Edge using the master branch and no autocomple appears to me.
There are any live server that I can use to check?
@esethna @lfbrock 

thanks

**Comment by lfbrock** [comment]
Hi @cpanato - let me check and see if anyone else can repro (sorry I don't have Edge myself). 

I think it would be the browser autocomplete, but some input boxes you can put a setting that turns it off. However it could just be Edge in this case, I'm not sure. 

If no one else can reproduce it I think we can just close this as can't reproduce.

**Comment by cpanato** [comment]
ok, I tried in the latest MS Edge and the server was running on my mac.

**Comment by esethna** [comment]
Okay thanks @cpanato, we can probably close as can't reproduce.
