### ISSUE TITLE
[Help Wanted] Documenting APIs for Mattermost 3.5

### ISSUE THREAD

**Issue by jwilander** [mattermost/platform#4534]
We're looking for help with documenting the Mattermost APIs available in 3.5!

At Mattermost we use the [OpenAPI specification](https://www.openapis.org/) for documenting our APIs.

If you're interested in helping out, please head over to the [issues page on our mattermost/mattermost-api-reference repository](https://github.com/mattermost/mattermost-api-reference/issues) and feel to grab any issue labelled `Help Wanted`.

Any documentation you add will be hosted on our official API reference at https://api.mattermost.com.

**Comment by jasonblais** [comment]
No longer applicable given the new APIv4 endpoints: https://forum.mattermost.org/t/mattermost-moving-to-api-version-4/2830
