### ISSUE TITLE
We encounted an error finding the channel

### ISSUE THREAD

**Issue by jlebleu** [mattermost/platform#454]
Did not had time to investigate, but last upgrade this message is always display :+1: 
We encounted an error finding the channel

In the logs : 

/api/v1/channels/mqwh9sh18ffify68sf69y634pc/:SqlChannelStore.Get code=500 rid=5uyjesspbjfw9eix3kf33o5oby uid=t896iku65f8hppm9s9s3zm991h ip=192.168.51.12 We encounted an error finding the channel [details: id=mqwh9sh18ffify68sf69y634pc, pq: column "creatorid" does not exist]

Hope this will help

**Comment by coreyhulen** [comment]
Looks like it failed to create the column on upgrade.  We're working on better support for upgrades, but for now if it's data you care about you can create the column "CreatorId varchar(26)" after "ExtraUpdateAt" column on the Channel table.

**Comment by jlebleu** [comment]
thanks for the answer, in fact unfortunately upgrade when using postgres is not supported. CreateColumnIfNotExists never create any column on postgres (sql_store.go line 155).

Would be a good idea to put a warning in the readme.

**Comment by coreyhulen** [comment]
Thanks, we'll put a note in the readme.  Postgres was first introduced in 0.6 so there shouldn't be any need to upgrade the db unless you're running daily builds (or maybe an old release candidate).

**Comment by jlebleu** [comment]
yes we are running almost daily builds ...

**Comment by coreyhulen** [comment]
This issue will be fixed by https://github.com/mattermost/platform/pull/511
