### ISSUE TITLE
Black screen on Mac and Windows client

### ISSUE THREAD

**Issue by KasperJanssens** [mattermost/platform#4544]
**Summary**
When sending a message through the command line api (/msg) I get a black screen.

**Steps to reproducte**
To reproduce, just open a new private chat by typing '/msg user test'. The screen will go black and will not redraw. The message does get sent it seems, but the screen is black and the application is not usable anymore until a restart or sometimes also until opening one of the menus.

**Expected behavior**
Send a normal message and shows it

**Observed behavior**
Messages gets sent but application doesn't redraw the screen, screen goes black.

**Possible fixes**
NA

**Comment by jasonblais** [comment]
Hey @KasperJanssens, thanks for the report,

1) Are you able to reproduce this on the browser?

If not, can you help file a new issue report in our [desktop repo](https://github.com/mattermost/desktop) with your report here, and the additional information below:

2) What is your Mattermost Desktop App version (See **Help > Version Number**) ?
3) What is your Mattermost Server version (See **Mattermost Menu > About Mattermost**, where **Mattermost Menu** can be accessed by clicking on three dots next to your profile picture)?

**Comment by KasperJanssens** [comment]
I don't have it on the browser, I'll log a new ticket in the desktop repo

**Comment by jasonblais** [comment]
Thanks! Closing and we can track it there: https://github.com/mattermost/desktop/issues/363
