### ISSUE TITLE
[Help Wanted] Switch theme colors to name value pairs

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4553]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Intermediate

**Details**: Currently, the theme colors for Mattermost are a list of hex values: 

<img width="565" alt="screenshot 2016-11-14 16 40 18" src="https://cloud.githubusercontent.com/assets/9354841/20283901/fa202f54-aa88-11e6-8fe6-a8e361b4d37f.png">

**Proposed Change**: We would like to switch them to be name value pairs, to make things easier if we add new theme colors.

**Comment by pan-feng** [comment]
I would like to work on this.

**Comment by jasonblais** [comment]
Go for it @pan-feng!  Thank you :)

**Comment by pan-feng** [comment]
i have some question， if change the input  box to be name value pairs, how to keep sharing ...

**Comment by pan-feng** [comment]
just create a theme name and keep the input box on it ？

**Comment by jasonblais** [comment]
Hey @pan-feng, can you help me understand your question better? 

If the input box is changed to name value pairs, I think the default themes will follow that format too.

**Comment by jasonblais** [comment]
By the way, I just heard that the theme may already be stored like a name-value pair on the backend. That could be helpful to know,

**Comment by jasonblais** [comment]
Thanks @pan-feng! Closed via #5301
