### ISSUE TITLE
[Help Wanted] Mobile View: Don't close the Left Hand Sidebar after removing an open Direct Message Channel

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4558]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Intermediate

**Details**: https://mattermost.atlassian.net/browse/PLT-4748

In mobile view: 
1) Open a Direct Message channel
2) Open the channel list in the left hand sidebar
3) Close the Direct Message channel you just opened by clicking the "x" beside the name

**Observed:** You are redirected to Town Square, but this closes the left hand sidebar. 

**Expected:** You are redirected to Town Square, but the lefthand sidebar stays open.

**Comment by fraziern** [comment]
I can take a look at this.

**Comment by lfbrock** [comment]
Thanks @fraziern for fixing this!
