### ISSUE TITLE
Login form could use a progress indicator

### ISSUE THREAD

**Issue by filipp** [mattermost/platform#4559]
#### Summary
The login form may sometimes take longer to process (eg with AD/LDAP logins) during which Mattermost seems frozen. Since the request is handled async., the user doesn't even get the usual feedback from the browser. As a result, more impatient users may resubmit the form multiple times.

#### Steps to reproduce
Try to log into an AD/LDAP site.

#### Expected behavior
The user should see a progress indicator immediately after clicking Sign In.

#### Observed behavior
Nothing happens. In our environment the login screen just stays there for about 6 seconds, after which they are successfully logged in.

**Comment by jasonblais** [comment]
Thanks @filipp for the report!

We discussed in our UX meeting and agree that we should have immediate feedback after clicking the "Sign In" buttong.

I created a ticket for adding a spinnerso the user knows that the sign in process has initiated: https://mattermost.atlassian.net/browse/PLT-4784

If you or anyone in the community is interested adding it, please let us know!
