### ISSUE TITLE
Need some help getting this running in windows

### ISSUE THREAD

**Issue by leram84** [mattermost/platform#4561]
Using this link: https://releases.mattermost.com/3.5.0/mattermost-enterprise-3.5.0-windows-amd64.tar.gz (replacing `linux` with `windows`) As instructed [here](https://mattermost.uservoice.com/forums/306457-general/suggestions/11486772-support-for-running-server-on-windows) I'm trying to run MM platform on a win10 machine, but when i launch "platform.exe" i get this:

    [CRIT] Failed to ping db err:dial tcp: lookup dockerhost: getaddrinfow: No such host is known

I have mysql, python3.4 and go installed, but im trying to do this without docker. From that support doc, this seems completely doable, and my requirements for MM are incredibly basic, so i was hoping to play around with it on a dev win10 box to see if it meets my needs, but i can't seem to get it running. Any ideas?

**Comment by enahum** [comment]
@leram84 did you try editing the config.json and changing the connection string to point to your database server?

**Comment by leram84** [comment]
can you give a little more detail? I'm a fast learner but still pretty nooby with most of this... first time even installing mysql. Anyway, after scanning the config file im assuming this is the block you are referring to?

        "SqlSettings": {
            "DriverName": "mysql",
            "DataSource": "mmuser:mostest@tcp(dockerhost:3306)/mattermost_test?charset=utf8mb4,utf8",
            "DataSourceReplicas": [],
            "MaxIdleConns": 10,
            "MaxOpenConns": 10,
            "Trace": false,
            "AtRestEncryptKey": "********************************"
        },


Could you tell me what i need to edit? I'm not even sure of the location of the database server. I'm assuming its in one of these folders?

`C:\Program Files\MySQL`
`C:\Program Files (x86)\MySQL`
`C:\Program Files (x86)\Microsoft SQL Server`
or `C:\Program Files (x86)\Microsoft SQL Server Compact Edition`

**Comment by leram84** [comment]
any ideas? I'm pretty lost. Not sure if its a syntax issue, but i'v tried editing that block in several ways with no success. i had thought something like:

    "SqlSettings": {
        "DriverName": "wordpress",
        "DataSource":  "lrwordpress@tcp(127.0.0.1:3306)/mattermost_test?charset=utf8mb4,utf8",
        "DataSourceReplicas": [],
        "MaxIdleConns": 10,
        "MaxOpenConns": 10,
        "Trace": false,
        "AtRestEncryptKey": "********************************"
    },

would work (I had mysql already configured for wordpress, but haven't setup wp yet, so was using those credentials) But every variation of that syntax doesn't seem to work... the only difference is when i launch `platform.exe` after editing the config, the terminal that pops up disappears too fast for me to read anything at all on it (before i had a few seconds, that i was able to get that original error msg)

**Comment by jasonblais** [comment]
Thanks @leram84 for your report,  

Mattermost doesn't officially support running servers on Windows. 

We have an open issue on our docs repo where we hope to get community's help test and provide feedback on Windows installation guides recently prepared by a community member: https://github.com/mattermost/docs/issues/360.

Wondering if you'd like to run through the installation steps on the guide, and report issues there? https://github.com/mattermost/docs/issues/360

**Comment by leram84** [comment]
YES! Jesus christ, i don't know how i never found that post. Yeah, ill definitely be working on this. Just scanning it now, and the answer to the above is clearly outlined... with pictures lol. And i already see 2 other things that would have sent me down the google rabbit hole! Thank you very much for pointing me in the right direction... i guess i know what im doing this weekend :)

**Comment by jasonblais** [comment]
Glad to hear, and thanks for trying it out! :) 

Please let us know in the docs repo how the deployment went, would be glad to hear if there's anything to update: https://github.com/mattermost/docs/issues/360

Closing the issue here, as it's tracked here https://github.com/mattermost/docs/issues/360
