### ISSUE TITLE
error when downloading files

### ISSUE THREAD

**Issue by kristianunger** [mattermost/platform#4563]
Files shared within a conversation cannot be downloaded.

#### Steps to reproduce
Upload a file by drag and drop and the receiver tries to download the file.

Version: 3.2.0
Build Number: 3.2.0
Build Date: Thu Jul 14 16:27:27 UTC 2016
Build Hash: ab52700aaa76a5623de23cd0156f5dbd9a24e264
Build Enterprise Ready: false
DB Version: 3.2.0

#### Expected behavior
When upload a file by drag and drop within a chat it should be available to the chat partner by download or preview.

#### Observed behavior
The download does not work for chat partner. Error message:
{"id":"api.file.get_file.not_found.app_error","message":"Datei konnte nicht gefunden werden.","detailed_error":"path=teams/be5mxf8r13bhfezgi5oi7g68pr/channels/rqp34j5f5bnyxk6bc59ehj1hhw/users/86io8y4u3jdu7cxgrdzs6ifhxw/3uugg1xpyjgbzmsh6marmgyxer/Fig_1_161116.pdf","request_id":"3m4jxdeaw7dxtbty6mim3se5iw","status_code":404,"is_oauth":false}

#### Possible fixes
No idea for possible fix. Seems to be a permission problem.

**Comment by jasonblais** [comment]
Thanks @kristianunger for the report,

We had an [existing issue](https://mattermost.atlassian.net/browse/PLT-3105) where files sent in direct message channels couldn't be downloaded if the member didn't belong to the same team.

Sounds like this might be the same issue you're experiencing?

This issue [was fixed for Mattermost 3.5](https://github.com/mattermost/platform/pull/4134), so I recommend [upgrading to the latest version](https://about.mattermost.com/download).

**Comment by kristianunger** [comment]
Thank you! That is exactly the issue!

**Comment by jasonblais** [comment]
Glad to hear :)
