### ISSUE TITLE
[Help Wanted] Push Notifications and Email Notifications should follow "Teammate Name Display" setting

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#4575]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory

**Details**: https://mattermost.atlassian.net/browse/PLT-4760

Currently, the push notifications and email body don't follow the **Teammate Name Display** setting in Account Settings. This ticket is to update them to follow the setting.

For example, if the **Teammate Name Display** is set to "Full Name", the email body and push notification text would show the users' full name instead of username (see screenshots).

**Email Notification:**
![image](https://cloud.githubusercontent.com/assets/14333569/20401514/6575997c-acb6-11e6-8962-6088ed26da81.png)

**Push Notification:**
![image](https://cloud.githubusercontent.com/assets/14333569/20401540/7d7a1570-acb6-11e6-986f-90c579c0d643.png)

**Comment by cpanato** [comment]
I will try this one

**Comment by esethna** [comment]
PR was merged, great work! Many thanks @cpanato, closing as done.

https://github.com/mattermost/platform/pull/4660
