### ISSUE TITLE
[Help Wanted] Adding Team Description

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#4576]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Intermediate

**Details**: https://mattermost.atlassian.net/browse/PLT-4328

[Community feedback that 15 character limit is too short](https://twitter.com/0x76796f/status/781888624077963264) for Team Name. That said, we need that limit so we don't truncate team names in the left-hand sidebar - but we should have some longer option so people can put in longer names or descriptions.

1. On Create a Team > Team Name dialog change error message from "Name must be 2 or more characters up to a maximum of 15" to "Name must be 2 or more characters up to a maximum of 15. You can add a longer team description later."

2. On Team Settings menu add a field for "Team Description" below the "Team Name" field.

   **Team Description:** [        ]
   Help Text: "Team description provides additional information to help users select the right team. Maximum of 50 characters."

3. On /select_team dialog add an info icon next to the team name that shows a tooltip of the team description when clicked.

![image](https://cloud.githubusercontent.com/assets/14333569/20401988/261eae2e-acb8-11e6-93d7-88b6e2d2a736.png)

4. Replace Team Name tooltip in lefthand sidebar with team description tooltip when hovering on desktop

    ![image](https://cloud.githubusercontent.com/assets/14333569/20402009/3cf75a6a-acb8-11e6-96d2-880fe03dfbb9.png)

**Comment by cpanato** [comment]
I can try this one

**Comment by jasonblais** [comment]
Awesome, thanks @cpanato!

**Comment by cpanato** [comment]
just to check @jasonblais @esethna 
The Team Description on step 2 should be in this menu? right?
![screen shot 2016-11-24 at 09 13 52](https://cloud.githubusercontent.com/assets/4115580/20590986/8200a120-b226-11e6-8635-a488049c08bb.png)

**Comment by jwilander** [comment]
Really well done @cpanato
