### ISSUE TITLE
Mobile notifications from incoming webhook are displayed on behalf of the user who created the webhook

### ISSUE THREAD

**Issue by recycled-bin** [mattermost/platform#4577]
#### Summary
Mobile notifications via incoming webhook are displayed on behalf of the user who created the webhook instead of the specified bot user (works correctly in web)

#### Steps to reproduce
Mattermost Server (v.3.5)
Android mobile client
1. Set up incoming webhook
2. Set up notifications for mobile
3. Send a message into a channel on behalf of a bot user

#### Expected behavior
Whenever a message is sent to the channel via webhook, mobile notification should be the same as the web one, i.e. message should originate from the specified bot user

#### Observed behavior
Mobile notification message originates from the user who created the webhook

#### Possible fixes
N/A

**Comment by jasonblais** [comment]
Thanks @recycled-bin for the report.

We just tried it on both the iOS and Android devices and the username was overwritten for us.

What webhook payload / message are you sending to the channel? Can you provide exact repro steps for a sample message so we can try reproducing the issue?

Also, which Android device is it reproducing?

**Comment by recycled-bin** [comment]
Apologies, seems like the issue has been fixed with the latest release!

However, I still see a side effect of it: 
If you search for user's messages, e.g. "from: <username> in: <channel>", it shows those bot messages though they do not originate from <username>.

**Comment by jasonblais** [comment]
Thanks @recycled-bin! Created a ticket for the second issue you found, and queued for our upcoming UX meeting to confirm the expected behaviour. https://mattermost.atlassian.net/browse/PLT-4857
