### ISSUE TITLE
[Help Wanted] API Get channels for a user returns users' dm channels on 3.5 with blank team ID

### ISSUE THREAD

**Issue by Judokus** [mattermost/platform#4583]
#### Summary
Calling `api/v3/teams/{team_id}/channels/` only returns the users' dm channels.

#### Expected behavior
API call returns all the users' channels that it is part of. Not only dm channels.

**Comment by Judokus** [comment]
Apparantly this only happens when a non-existent team_id is supplied.

**Comment by jasonblais** [comment]
Thanks @Judokus - which channels would you expect the API call to return if the team_id is nonexistent?

**Comment by thePanz** [comment]
Shouldn't this API call return a "Not Found (404)" as the `team_id` is not valid?

**Comment by jwilander** [comment]
If the team ID is non-existent, missing or erroneous an app error explaining the issue and the status code `Bad Request (400)` should be returned.

I've created a [ticket here](https://mattermost.atlassian.net/browse/PLT-4873) to remedy the issue for 3.6. Thanks for the report!

**Comment by jasonblais** [comment]
Anyone interested helping with a fix?

**Comment by cpanato** [comment]
I can take it

**Comment by lfbrock** [comment]
Thanks @cpanato for fixing this!
