### ISSUE TITLE
[Help Wanted] Move instances of Client.createPost() in components to an action

### ISSUE THREAD

**Issue by jwilander** [mattermost/platform#4589]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Difficulty**: Introductory (new to codebase)

**Details**:
To be [Flux](https://facebook.github.io/flux/docs/actions-and-the-dispatcher.html)-compliant our web utilities should be separate from our views and UI components. Views should use re-usable actions instead of directly interacting with the web utilities (specifically Client/client.jsx in our case).

Move any instances of `Client.createPost()` inside of the [components directory](https://github.com/mattermost/platform/tree/master/webapp/components) into an action inside of [webapp/actions/post_actions.jsx](https://github.com/mattermost/platform/blob/master/webapp/actions/post_actions.jsx) and use the new action in place of where the `Client.createPost()` invocations were.

Any common functionality should be performed in the action where possible, for example event dispatches through `AppDispatcher`.

Please see other actions inside of [webapp/actions/post_actions.jsx](https://github.com/mattermost/platform/blob/master/webapp/actions/post_actions.jsx) for examples.

A quick grep at the time of creation of this ticket shows `Client.createPost()` being used in:
- https://github.com/mattermost/platform/tree/master/webapp/components/create_comment.jsx
- https://github.com/mattermost/platform/tree/master/webapp/components/create_post.jsx
- https://github.com/mattermost/platform/tree/master/webapp/components/post_view/components/pending_post_options.jsx

**Comment by cpanato** [comment]
I can take this one

**Comment by cpanato** [comment]
@jwilander I'm little lost on this one, for create_comment and create_post looks like the same code, however for the pending_post_option is another, should I create another action for this or add a parameter to say this is a pending post? 
how i can proceed with that? what is the best approach?
thanks

**Comment by jwilander** [comment]
Hi @cpanato, I just took a look at the pending post code and I'm not sure why it has all the channel store logic. I think you can try removing that and use the same action as for create_post and create_comment and see it if it still works as expected (I think it will). As for the `loadPosts()` invocation there, I think you can add an option to the action, called maybe `doLoadPosts`, that will invoke that function if set to true

How's that sound?

**Comment by cpanato** [comment]
I tested using the "normal" create_post and it works. I tested making offline and clicking on the retry and make it online again and click on retry, all work.

I will add the ```doLoadPosts``` and send out the PR for review if is not good we can change later  :)

**Comment by jasonblais** [comment]
Closed by #4639
