### ISSUE TITLE
[Help Wanted] In channel member list, have the "..." redirect user to Manage/View Members modal when clicked

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4591]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory

**Details**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4532)

Currently,  clicking "..." in channel member lists does nothing. 

![image](https://cloud.githubusercontent.com/assets/13119842/20456553/c1fa6222-ae46-11e6-9fdf-090fbf1112ad.png)

**Proposed Change**:
When a user clicks on '...' in channel member lists, the channel "Manage/View Members" modal opens depending on channel management permissions.

Note: The "Manage Members" and "View Members" modal is the same that opens when you  
 1) Click the channel name
 2) Choose "Manage Members" or "View Members" on the drop down list

![image](https://cloud.githubusercontent.com/assets/13119842/20456589/7e414824-ae47-11e6-8c86-8f9ae94b0771.png)

**Comment by CrEaK** [comment]
I'm interested :) I will submit a pull request

**Comment by grundleborg** [comment]
PR Merged. Many thanks for the contribution @CrEaK
