### ISSUE TITLE
[Help Wanted] Move instances of Client.updateUserRoles() in components to an action

### ISSUE THREAD

**Issue by jwilander** [mattermost/platform#4592]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Difficulty**: Introductory (new to codebase)

**Details**:
To be [Flux](https://facebook.github.io/flux/docs/actions-and-the-dispatcher.html)-compliant our web utilities should be separate from our views and UI components. Views should use re-usable actions instead of directly interacting with the web utilities (specifically Client/client.jsx in our case).

Move any instances of `Client.updateUserRoles()` inside of the [components directory](https://github.com/mattermost/platform/tree/master/webapp/components) into an action inside of [webapp/actions/user_actions.jsx](https://github.com/mattermost/platform/blob/master/webapp/actions/user_actions.jsx) and use the new action in place of where the `Client.updateUserRoles()` invocations were.

Any common functionality should be performed in the action where possible, for example event dispatches through `AppDispatcher`.

Please see other actions inside of [webapp/actions/user_actions.jsx](https://github.com/mattermost/platform/blob/master/webapp/actions/user_actions.jsx) for examples.

A quick grep at the time of creation of this ticket shows `Client.updateUserRoles()` being used in:
- https://github.com/mattermost/platform/tree/master/webapp/components/admin_console/admin_team_members_dropdown.jsx

**Comment by fraziern** [comment]
I can work on this.
