### ISSUE TITLE
[Help Wanted] Enter to Submit does not work on the Import Theme Colors from Slack modal

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4595]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory

**Details**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4191)

Repro: 
1. Go to Account Settings > Display > Theme > Edit
2. Click the link "Import theme colors from Slack" 
3. Paste in some values
4. Press Enter

Observed: The theme color setting collapses behind the modal.

Expected: Enter should act on Submit button on the Import from Slack modal.

**Comment by cpanato** [comment]
there is one problem on that to fix as well, when you open the "import theme colors from slack" the focus still in the modal behind and if you press enter will close the previous modal and the "import theme" will still be opened.

**Comment by cpanato** [comment]
the enter is working, however it trigger first the first modal which is behind the import theme modal
@jasonblais can you help me on that?

![sguwynelg4](https://cloud.githubusercontent.com/assets/4115580/22031583/5619ff1c-dce1-11e6-8162-90a8621ce506.gif)

**Comment by jasonblais** [comment]
Hey @cpanato, would it be possible to set focus to the "Import Slack Theme" dialog that opens on top of the Account Settings modal?

That way when you press Enter, it should act on the Submit button.

**Comment by jasonblais** [comment]
By the way, there's an agenda item queued for today's (Wednesday) public developer meeting [to discuss a related issue](https://pre-release.mattermost.com/core/pl/1fcbegifgf8s3mkchpffmfgm3a). It's about the settings event handlers attached directly to DOM, which is the root cause for this issue.

**Comment by cpanato** [comment]
per discussion on the developer channel this will be handle internally.

**Comment by jasonblais** [comment]
Thanks! Sounds good, I'll close the issue as @grundleborg has it in progress https://mattermost.atlassian.net/browse/PLT-4191
