### ISSUE TITLE
[Help Wanted] "No Channels Found" should appear without pressing Enter in Channel Switcher (CTRL/CMD+K)

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4596]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory

**Details**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4150)

**Repro Steps**:
1. Open Channel Switcher (CTRL/CMD+K)
2. Type something that doesn't exist as a channel.
3. Press Enter.

**Observed**:
Step 2: No feedback after searching for something that doesn't exist.

![image](https://cloud.githubusercontent.com/assets/13119842/20456758/e5c7e75c-ae4a-11e6-9d90-d78c0fd073d6.png)

Step 3: Error message `No matches found.` in red colour.

![image](https://cloud.githubusercontent.com/assets/13119842/20456759/ebbddc70-ae4a-11e6-8de4-5fbaf600ca12.png)

**Proposed Changes**:
Step 2: 

1) Feedback should appear if no channels are found (ie search results are blank) immediately if at least one character is typed.

2) Moreover, the error message should not be red. It should use the same colour when searching for members in "Manage/View Members" list with no results (see screenshot below)

Note: The "Manage/View Members" list can be found from the three-dotted Mattermost Main Menu next to your username and profile picture in the top left corner.

![image](https://cloud.githubusercontent.com/assets/13119842/20456787/87ccd8b4-ae4b-11e6-8cc2-5e39cb2c1462.png)

Step 3: The message should persist if ENTER is pressed, i.e. no change from step 2.

**Comment by kulak-at** [comment]
I can work on this one.

**Comment by jasonblais** [comment]
You're awesome!! 👍

**Comment by jasonblais** [comment]
Closing the ticket -- will re-open with new screenshots that match the updated channel switcher UI
