### ISSUE TITLE
[Help Wanted] Change URLs of Direct Messages to usernames

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4598]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Advanced

**Details**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-91)

Cosmetically change URLs of Private Message channels to be usernames instead of the concatenation of two user GUIDs

Specifically, the URL should be of the form ".../[TEAM NAME]/messages/[USERNAME]" where [USERNAME] is the username of the person you're talking to

If username is updated, the URL should cosmetically update to that new username.

**NOTE**: Internal name of the channel in the database should still be id1__id2

**Comment by pan-feng** [comment]
I want to try this one.

**Comment by CometKim** [comment]
I'd like to do this one. I have a same request from my business

@pan-feng Can I do this if you have not started yet?

**Comment by jasonblais** [comment]
@CometKim Thanks! I'm wondering how it should work with group message channels, which currently generate a random id (`.../[TEAM NAME]/messages/[ID]`)

**Comment by CometKim** [comment]
Hello @jasonblais,

If the group messaging is for temporary use that is enough. but we need to change the ID format to distinguish it from any username.

ID seems to sha1 hash of members id, not a random value. And username can be same.

**Comment by jasonblais** [comment]
> if the group messaging is for temporary use

I think the plan is that you can close the group message channel but find it in the "More Direct Messages" list. So it would become a permanent channel in that case

> but we need to change the ID format to distinguish it from any username.

To confirm - you're planning to change it to sha1 hash of the member usernames?

**Comment by CometKim** [comment]
No. currently id of group messaging channel is sha1 hash that always 40 character. I was wrong because username cannot be 40 chars.

**Comment by CometKim** [comment]
@jasonblais, It seems the GM route has moved to under `/channels`.
DM route still need to move to under `/messages`?

**Comment by jasonblais** [comment]
Sorry, my mistake. DM route is `/channels/id1_id2`, GM route is `/channels/id`

**Comment by jasonblais** [comment]
@CometKim Couple of other notes:

 1 - We've received requests to be able to link to channels based on channel_id, not just the channel_url. The channel_id is static and never changes, so you can permanently link to it. We created a help wanted ticket for it here: https://github.com/mattermost/platform/issues/5912

So when we're implementing this feature, we should continue supporting `/channels/id1_id2` for DMs and `/channels/id` for GMs, but which can redirect to the new URL of the form `/messages/username`.

 2 - For group messages, would something of this form work: `/messages/username1-username2-username3`?

It would be good to ask for other's opinions too on the best way to approach the channel URL for GMs

**Comment by jasonblais** [comment]
Re-opened: https://github.com/mattermost/platform/issues/7186
