### ISSUE TITLE
[Help Wanted] "Add/Manage Members" and "More public channels" modals don't auto-focus on search bar

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4599]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory

**Details**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4783)

Add/Manage members modals don't auto-focus on search bar. This is against UX guidelines

Repro: Open any of the following modals:
1) Main Menu > Manage Members
2) Channel drop down menu > Add Members
3) "More..." at the bottom of your public channel list

Observed: Focus not set to search bar

Expected: Focus set to search bar

Note: Focus is set automatically to search bar if you go to
1) Channel drop down menu > Manage Members (to remove members)
2) "More..." at the bottom of your direct message list

**Comment by fraziern** [comment]
Working on this...

**Comment by jasonblais** [comment]
Closed via #4610, thanks @fraziern!
