### ISSUE TITLE
[Help Wanted] Resize server logs table vertically based on browser window screen size

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4600]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory

**Details**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4740)

The server logs table is automatically scrolled to the bottom, as [implemented in this pull request](https://github.com/mattermost/platform/pull/4527).

However, given the server logs table doesn't resize vertically based on the window size, you cannot actually see the latest server log messages (see screenshot).

![image](https://cloud.githubusercontent.com/assets/13119842/20456921/711e203e-ae4e-11e6-903b-cbf981e46702.png)

Proposed change: 

Have the server logs table resize based on window size similar to the User Activity Logs table in **System Console > Other > Compliance and Auditing** section. This will remove the need to have a scrollbar on the page itself.

**Comment by cpanato** [comment]
@jasonblais I tested using current master and on chrome this not happen, it resize automatic

**Comment by jasonblais** [comment]
thanks @cpanato, I think they donèt resize vertically, as shown in the above screenshot. Have updated title + description to specify that.

**Comment by cpanato** [comment]
I tested doing horizontal and vertical resize and all resized well

**Comment by jasonblais** [comment]
Oh, you're correct, it looks like it's been fixed on `master`. I was testing on the 3.5 version earlier.

Thanks @cpanato, I'll close this issue since it's been resolved.
