### ISSUE TITLE
[Help Wanted] Update error message when an invitation link is invalid

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4602]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory

**Details**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3576)

Repro: 
1. Go to Main Menu > Get Team Invite Link and copy the link
2. Go to Team Settings > Invite Code and regenerate it
3. Load the old invite link

The error message is unclear (see screenshot).

![image](https://cloud.githubusercontent.com/assets/13119842/20456929/c0ae7e00-ae4e-11e6-82cd-1d4a16c1e74b.png)

Proposed Change: 

1) Update the error message to say "This invitation link is invalid. Please request a new one from the person who invited you."

2) Hide the "Aready have an account? Click here to sign in" when the link is invalid.

**Comment by cpanato** [comment]
@jasonblais I tried the steps described and this is what I saw using the current master

![screen shot 2016-11-22 at 12 55 53](https://cloud.githubusercontent.com/assets/4115580/20522959/1f55f63e-b0b3-11e6-8f92-d594a4ccd6ce.png)

**Comment by jasonblais** [comment]
Aah -- looks like this is fixed on `master` too.

The existing error message looks good.

Sorry about it, will be a little more careful next time and make sure I've got the latest changes from `master` when testing.
