### ISSUE TITLE
Need some nginx support for a windows build

### ISSUE THREAD

**Issue by leram84** [mattermost/platform#4607]
I'm currently testing MM server on a win10 box running all three components on that one device. MM is running smoothly locally, but i am attempting to integrate it into my existing nginx reverse proxy that i use for a plex media server and related services. I'm still relatively new to nginx however and most of my setup was done using guides, so im hoping someone can help me a little. Here is my current config: http://pastebin.com/rQ5wKcFZ

As you can see, im not forwarding http to https (i dont even have port 80 open). So theres no need for any kind of redirect code. I just want to be able to go to https://www.leram84.com/mattermost and connect. Can someone assist with the correct location block for this? This was the example i found in the linux docs, but did not work

    location / {
      gzip off;
      proxy_set_header X-Forwarded-Ssl on;
      client_max_body_size 50M;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Frame-Options SAMEORIGIN;
      proxy_pass http://127.0.0.1:8065;
    }

So ive tried trial and erroring through several variations of that with no luck. (the MM location block in the pastebin is the last config i tried. When i go to the address `https://www.leram84.com/mattermost` I just get a blank page BUT the tab does say Mattermost, so i know it is connecting... just not configured properly. Once this is set properly, i also need to know what to put for `Site URL` and `Listen Address` in `Console Settings > General > Configuration`

Also, this is unrelated, but that `proxy_set_header X-Frame-Options SAMEORIGIN;` line in the example config is extremely troubling. Please tell me it is something i can just comment out, because my whole plan here was to iframe MM in another page (literally the entire reason im doing all this instead of just using slack).

**Comment by lfbrock** [comment]
Hi @leram84 - I'm not sure about the windows install issues, (maybe @shieldsjared has some ideas?) but it's not possible to iframe Mattermost into another site unless it's inside the same origin. 

We do this for security reasons, if you want to embed into another site we would recommend using our [javascript driver](https://docs.mattermost.com/developer/web-service.html#extended-web-service-api-examples) to build that functionality. The other alternative would be to modify the go code to change the security policy, but we don't recommend doing that.

**Comment by leram84** [comment]
hmmm... ok, well when you put it like that... the site is from the same origin (i think). Its not really a site, its a program called [idashboard](https://github.com/causefx/iDashboard-PHP) that lets me sort a bunch of media apps on my server into a bunch of iframe tabs on one page. I was looking for a hosted chat app (starting with slack) that could be iframed into one tab, but they all had xheaders set to same origin which prevented me.... but since MM is running on the same machine/nginx server as idashboard... that shouldn't be a problem... right?

....guess im in a little over my head here, but i feel like im just a few conf edits from making this all work!

**Comment by leram84** [comment]
Any ideas about this? If no one has an answer to the nginx issue, does anyone have an answer to the other question: what to put in the `site url` and `listen address` in case those settings might be getting in the way of a successful trial and error test. (several of the other services required me to set a "base url" in the app before they could be configured in nginx, so im afraid that might be the case for MM as well)

**Comment by shieldsjared** [comment]
I wish I had good feedback for you @leram84, but I don't know much about nginx. That's a bit beyond the scope of the guide.... so if you're looking for feedback on that, I think you'll reach a wider audience on [the forums](https://forum.mattermost.org) and likely help the next guy out that has the same issue :) I sincerely appreciate all of your feedback on the guide!!

**Comment by shieldsjared** [comment]
I wish I had something insightful to add but I don't know much (read: nothing) about nginx! Sorry

**Comment by leram84** [comment]
ok, you guys can close this, its not going to work for me. I just found out that [MM can't run from a subdirectory](https://mattermost.atlassian.net/browse/PLT-200), and setting up a second virtual host is beyond my skill level. Thanks anyway.

**Comment by yangchen1** [comment]
Hey @leram84, I'm so sorry for our delay in response - I can confirm we currently do not run from a subdirectory, but there is a [Uservoice feature request for it!](https://mattermost.uservoice.com/forums/306457-general/suggestions/12468372-install-mattermost-in-a-subdirectory) We welcome any community members who may be interested in working on it.

**Comment by jasonblais** [comment]
Thanks everyone! I'll close this issue and we can track the feature request in Uservoice: https://mattermost.uservoice.com/forums/306457-general/suggestions/12468372-install-mattermost-in-a-subdirectory
