### ISSUE TITLE
Hardcoded port 8443 when using secure websocket?

### ISSUE THREAD

**Issue by kohenkatz** [mattermost/platform#461]
In [web/react/stores/socket_store.jsx](https://github.com/mattermost/platform/blob/532be141bae8ff2ea03de4fa54affd6e72dab9ea/web/react/stores/socket_store.jsx#L31), the server port is hard-coded to `8443` when the page is detected to have been loaded over a secure connection.  However, I am not running on port 8443, and I assume that many other people aren't either.  Instead of being hard-coded, I would think that this should be the same as the port that the site itself was loaded from, in the same way as when it is loaded over a non-secure connection.

**Comment by coreyhulen** [comment]
Thanks for pointing that out.  It's an artifact of our legacy product and we'll correct it.

**Comment by coreyhulen** [comment]
PR submitted https://github.com/mattermost/platform/pull/467

**Comment by coreyhulen** [comment]
If you want to run 0.6 + SSL you'll need something like Nginx or AmazonELB to terminate the SSL connection.  You'll also need to port forward 8443 -> 8065.

**Comment by kohenkatz** [comment]
@coreyhulen my problem is that I'm already using that port for a different service. Instead, I manually removed that part from the JavaScript of my local installation for now. (I am using nginx as a proxy, but on 4443 instead of 8443.)

**Comment by coreyhulen** [comment]
Great, glad you found a workaround.  This should be fixed in master soon and will ship with 0.7.  Thanks again.

**Comment by coreyhulen** [comment]
This is fixed in master
