### ISSUE TITLE
Copy link button does not copy link in Windows desktop client version 3.4.1

### ISSUE THREAD

**Issue by hannu78** [mattermost/platform#4613]
#### Summary
Copy link button does not copy selected link in Windows desktop client version 3.4.1 in Windows 10.

#### Steps to reproduce
Post a link to a channel or find a posted link from a channel, right-click on the link and select "Copy Link". Go to message writing box on the same or on different channel and right-click to Paste or use CTRL+V. 

#### Expected behavior
Link should be copied to clipboard and then be possible to be pasted elsewhere.

#### Observed behavior
Paste is disabled when trying to paste via right-click and nothing is pasted with CTRL+V.

#### Possible fixes
N/A

**Comment by lfbrock** [comment]
Hi @hannu78 - would you be able to file this issue in the [Desktop App](https://github.com/mattermost/desktop) repo? There's a pretty active community there that can help look into this issue

**Comment by hannu78** [comment]
Yes, I did so. Sorry about posting this to platform side, newbie error.

**Comment by jasonblais** [comment]
Thanks @hannu78! We'll track the issue in the desktop repo: https://github.com/mattermost/desktop/issues/367
