### ISSUE TITLE
support for .jpeg extensions

### ISSUE THREAD

**Issue by mathiasfriman** [mattermost/platform#462]
Hi,

Noticed when doing a docker install of Mattermost that inserting a URL with **.png** and **.jpg** file extensions it renders a visible image in a channel, but when the extension is **.jpeg**, it does not. 

Probably/hopefully a simple thing to fix.

**Comment by coreyhulen** [comment]
Thanks, this is already in master with https://github.com/mattermost/platform/pull/368, and will be included in 0.7
