### ISSUE TITLE
[Help Wanted] Add unit test for post.getPermalinkTmp()

### ISSUE THREAD

**Issue by jwilander** [mattermost/platform#4636]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Difficulty**: Introductory

**Details**:
In an effort to increase our unit test coverage, we're looking for some help writing some tests.

The API function `getPermalinkTmp(c *Context, w http.ResponseWriter, r *http.Request)` in [api/post.go](https://github.com/mattermost/platform/blob/master/api/post.go#L1318) could use some increased coverage. The function's purpose is to generate a permanent link to a post that can be given to other users. The test for this API function should be written in `api/post_test.go`.

You'll need to add a function [similar to this one](https://github.com/mattermost/platform/blob/master/model/client.go#L1356) to the Go driver except it will be called `GetPermalink()`.

For an example [see the unit test for getting posts](https://github.com/mattermost/platform/blob/master/api/post_test.go#L756).

**Comment by cpanato** [comment]
trying this one

**Comment by jwilander** [comment]
Thanks for your work on this @cpanato!!
