### ISSUE TITLE
Displaying of @-mentions should follow "Teammate Name Display" setting

### ISSUE THREAD

**Issue by netmikey** [mattermost/platform#4640]
#### Summary
The displaying of @-mentions should follow "Teammate Name Display" setting

#### Steps to reproduce
- In Account Settings > Display > Teammate Name Display, make sure to chose "Show nickname if one exists, otherwise show first and last name" or "Show first and last name"
- Go to a channel, type an @ and start typing their name
- Once the correct team member is highlighted, press enter to select him/her. His/her user-id will be inserted into your message.
- Once you send the message, it's still the user-id that's being displayed instead of the name
- When someone else mentions a team member, you'll also see the mentioned member's user-id instead of their name

#### Expected behavior
Once the message is posted, the displaying of the mention should follow the Teammate Name Display setting. So instead of `Hi, @usr523`, we should see `Hi, @Bob`.

#### Observed behavior
We have a GitLab-Linked Mattermost Instance but our user database is an LDAP directory with alphanumeric keys as User-IDs. We cannot change our User IDs. While I know my user-id, I don't know anybody else's (and they don't know mine), so we get lost in conversations where people are mentioning alphanumeric user-ids back and forth.

#### Feature Discussion Cross-Reference
https://mattermost.uservoice.com/forums/306457-general/suggestions/17239631-the-displaying-of-mentions-should-follow-teamma

**Comment by lfbrock** [comment]
Hi @netmikey - would you be able to submit a [feature request](https://www.mattermost.org/feature-ideas/) on this and post the link back here for others to upvote?

**Comment by netmikey** [comment]
Sure! Done :)

**Comment by jasonblais** [comment]
Thanks @netmikey! 

Anyone else who would like to see this feature, please upvote the request here: https://mattermost.uservoice.com/forums/306457-general/suggestions/17239631-the-displaying-of-mentions-should-follow-teamma

**Comment by philippe-granet** [comment]
**Mattermost announce "Plugin Support in Beta" :** 
_New plugins allow IT admins to deeply customize your experience by overriding key parts of the Mattermost user interface and server functions._ 
https://about.mattermost.com/blog/mattermost-4-4/ 

**If someone can make a plugin and replace this line :** 
https://github.com/mattermost/mattermost-webapp/blob/master/components/at_mention/at_mention.jsx#L96 
```html
<a className='mention-link'>{'@' + user.username}</a>
```
by something like :
```html
<a className='mention-link'>{'@' + user.username}</a>{'(' + user.first_name + ' ' + user.last_name + ')'}
```
I think it can do the job :)

**Comment by jasonblais** [comment]
@philippe-granet We also have a help wanted ticket for doing the change directly in the code, if you're interested helping with it :) 

https://github.com/mattermost/mattermost-server/issues/7562
