### ISSUE TITLE
Syntax highlighting for `js` and `jsx` not working

### ISSUE THREAD

**Issue by erikmueller** [mattermost/platform#4641]
#### Summary
Highlighting a code block with either `js` or `jsx` does not work

#### Steps to reproduce
enter
````
```jsx
import React from 'react'

class Foo extends React.Component {
  handleClick = () => {}
  render() {
    return <div onClick={this.handleClick} />
  }
}
``` 
````
using `js` yields the same result (only `javascript` works)
#### Expected behavior
should be highlighted

#### Observed behavior
renders as if no language was provided

#### Possible fixes
As Mattermosts help lists `jsx` and `js` (but interestingly not `javascript`) as possible options, it might be a usage problem on my side.

Running Mattermost `3.4.1` on Mac, also happening in the browser.

**Comment by lfbrock** [comment]
Hi @erikmueller - I think that documentation may be incorrect, the supported languages can be found here: https://github.com/mattermost/platform/blob/master/webapp/utils/syntax_highlighting.jsx

It looks like [jsx isn't currently supported](https://github.com/isagalaev/highlight.js/issues/931) by the library we're using. 

Sorry about the confusion, we'll update the documentation to fix the incorrect code types.

**Comment by erikmueller** [comment]
Ok, I thought Mattermost was using GitLab markdown (`rouge`). Thanks for clarifying (and for pointing me to the code ;)

**Comment by lfbrock** [comment]
Pull request here to docs repo: https://github.com/mattermost/docs/pull/678

**Comment by jazzzz** [comment]
It's a pity that `js` does not work for syntax highlighting. Here we are using Mattermost with GitLab, and `js` works for Javascript syntax highlighting in GitLab, so we have to remember to use `javascript`in Mattermost and `js`in GitLab.
