### ISSUE TITLE
Cannot scroll with keyboard in minimal mode after typing "@"

### ISSUE THREAD

**Issue by sc250024** [mattermost/platform#4654]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
If the browser window is shrunk to the smallest size that MatterMost allows for, typing "@" and then trying to type someone's name or "channel" does not allow scrolling with the keyboard. When the window is full sized, it allows keyboard scrolling after typing "@" and receiving a list of users.

#### Steps to reproduce
Using:
- MatterMost Enterprise 3.5.1
- Chrome 54.0.2840.98
- macOS Sierra 10.12.1

1. Log in to Mattermost, and go to any team.
2. In a team, go to any public / private channel.
3. Scale down the browser window horizontally until the point where the CSS no longer adjusts; the user / channel on the left should disappear completely at this point.
4. Type "@" into the text area to get a list of users in that channel. Try using the up and down keys on your keyboard. You will see that you will not be able to scroll up and down.
5. Resize the browser window again to largest size, and repeat step 4. You will see that you *are* allowed to scroll.

#### Expected behavior
Keyboard scrolling after typing "@" should work regardless of window size.

#### Observed behavior
Keyboard scrolling after typing "@" *does not* work when the window size is the smallest allowable.

**Comment by jasonblais** [comment]
Has anyone else in the community noticed the issue?

@sc250024 does this only reproduce for you on small screen size on the desktop browser, and not on mobile (either iOS or Android) browser?

**Comment by sc250024** [comment]
@jasonblais Desktop only, in a browser. Did not test in the desktop app / mobile version.

**Comment by esethna** [comment]
Thanks for the report, I am able to repro this issue, created a ticket [here](https://mattermost.atlassian.net/browse/PLT-4930). Closing to track in JIRA.
