### ISSUE TITLE
Channel not read

### ISSUE THREAD

**Issue by S6066** [mattermost/platform#4655]
When launching MM, then changing channel, the previous channel is still unread
(MM entreprise 3.5.1)

**Comment by jasonblais** [comment]
Thanks @S6066 for the report.

We're investigating the issue and we suspect it could be a race condition of some type, but haven't pinpointed the problem yet.

You can monitor the progress in Jira: https://mattermost.atlassian.net/browse/PLT-4840

**Comment by jasonblais** [comment]
I'll close the issue here -- you can monitor the progress in Jira: https://mattermost.atlassian.net/browse/PLT-4840
