### ISSUE TITLE
[Help Wanted] Show profile popover when clicking on username or profile picture at top of Direct Message channel 

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4658]
Repro: 

- Click on the profile picture or username at the top of Direct Message channel (see image below)

![image](https://cloud.githubusercontent.com/assets/177788/20651866/5ea42f70-b4a2-11e6-841b-3718831073e4.png)

Expected: 

- Clicking on profile picture or username at top of Direct Message channel should display profile info, similar to clicking on username or profile picture in center channel conversation. 

Observed: 

- Clicking on profile picture or username at top of Direct Message channel has no effect.

**Comment by jasonblais** [comment]
@brendanbowidas Curious if you'd be interested about this GitHub issue?

It's similar to the improvement you added where a profile popover is shown when a user clicks on the profile picture in center channel:  https://github.com/mattermost/platform/pull/4144

**Comment by brendanbowidas** [comment]
@jasonblais sure, I'll take a stab at it when I get some free time.

**Comment by jasonblais** [comment]
Thanks @brendanbowidas! That would be awesome! :)

**Comment by jasonblais** [comment]
Thanks again @brendanbowidas! Closed via #4705
