### ISSUE TITLE
Flagged posts, search, etc toolbar isn't shown for direct messages

### ISSUE THREAD

**Issue by CGenie** [mattermost/platform#4659]
#### Summary
The toolbar with flagged posts, search, etc is shown for public chats but not for direct messages.

#### Steps to reproduce
Go to public chat -- the toolbar is there. Not so for direct messages.

#### Expected behavior
Have this in direct messages too, I think it was there in 3.4.x. Especially that for example, flagged posts persist when you open them on public chat and go to private one. You can close the panel in private chat and then are not able to reopen it.

#### Observed behavior
As described above. I'm using Mattermost server 3.5.0.

**Comment by jasonblais** [comment]
Hi @CGenie, the issue was fixed with https://github.com/mattermost/platform/pull/4584 and included in our security update in 3.5.1.

You can download the latest release here: http://about.mattermost.com/download/
