### ISSUE TITLE
User status icon overlays gone after 3.5 update

### ISSUE THREAD

**Issue by Liquidmantis** [mattermost/platform#4661]
#### Summary
Users' current statuses are no longer indicated in the channel user list.

#### Steps to reproduce
Click on channel member "bust" icon.

#### Expected behavior
Prior to 3.5.0 users had a small dot overlay indicating if they were online and active.

#### Observed behavior
Updated to 3.5.0 and lost the icon overlay.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by jasonblais** [comment]
Hey @Liquidmantis, appreciate your feedback. 

It was removed as it was loading the status of all users displayed on the channel member list reducing performance. We're evaluating options to add it back.

In the meantime, would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
