### ISSUE TITLE
[Helped Wanted] Fix typos in error message

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4663]
![image](https://cloud.githubusercontent.com/assets/177788/20677772/24e2851e-b549-11e6-9912-615fd2cc96c5.png)

"javascript" should be "JavaScript" and "occured" should be "occurred"

Bonus: 
- Replace "javascript" with "JavaScript" throughout the error messages 
- Run spell check on all the English strings
   - [i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json)
   - [webapp/i18n/en.json](https://github.com/mattermost/platform/blob/master/webapp/i18n/en.json)

**Comment by Rudloff** [comment]
Hello,
I'm not a native English speaker but I would like to submit a PR for this if that's OK.

**Comment by jasonblais** [comment]
Please go ahead! All yours, thanks @Rudloff! :)
