### ISSUE TITLE
[Help Wanted] Emoji Picker 

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4665]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Goal:** This ticket is to create an Emoji Picker that can be used to select emojis more easily. 

**Note:** There's unfinished code for an emoji picker available in [unfinished-emoji-picker](https://github.com/mattermost/platform/tree/unfinished-emoji-picker) branch. Contact @hmhealey (`@harrison` on https://pre-release.mattermost.com) if you have any questions about this code

---

1. Add an icon next to the attachments icon that opens an emoji picker:
    <img width="419" alt="screenshot 2016-07-12 15 02 33" src="https://cloud.githubusercontent.com/assets/9354841/20686525/180948da-b587-11e6-81f0-c658dd436f74.png">

2. The emoji picker should have the list of emoji divided into standard categories. This data is available in`webapp/utils/emoji.jsx`, but you can also look at http://emojipedia.org/ for a more comprehensive list. These headings are:
    - People
    - Nature
    - Food & Drink
    - Activity
    - Travel & Places
    - Objects
    - Symbols
    - Flags
    - Custom
3. It should include a search filter that filters on emoji names. Typing filters the emoji, with the first entry selected and it is possible to navigate through with the keyboard arrows.
4. It should include a header bar containing icons that act as shortcuts. When clicked on, the emoji picker view jumps to the corresponding heading
5. When hovering over an emoji, the emoji image and the name should appear on the bottom footer
    <img width="357" alt="screenshot 2016-07-12 15 02 55" src="https://cloud.githubusercontent.com/assets/9354841/20686505/fb7ebdd0-b586-11e6-97a7-0b1ecf602eb7.png">

**Comment by jasonblais** [comment]
Thanks @jfml for the feedback - we're not supporting switching emoji styles at the moment, would you be interested submitting a feature request for it in [our Feature Ideas forum](https://mattermost.uservoice.com/forums/306457-general)?

**Comment by jfml** [comment]
@jasonblais Sure,w thanks for the tip and keep up the good work!

**Comment by jasonblais** [comment]
Hey @bjoernr-de, looks like you've got the emoji picker started - awesome!

Are there any questions that you have? Anything we can help with?

**Comment by bjoernr-de** [comment]
@jasonblais Well, there's already a lot of work done in `unfinished-emoji-picker` branch by @hmhealey 
I just picked things up and took a look and thought it might be useful to commit my changes. Anyway, this still needs a little more love 😛 

I might work on this further but as some private things are changing at this time I can't say that I take fully care of this issue.
I probably should add a PR to get my changes merged into the `unfinished-emoji-picker` branch so everybody else can work on that, too :) What do you think @jasonblais ?

**Comment by jasonblais** [comment]
Thanks @bjoernr-de! What kinds of changes did you add? Just so we know?

**Comment by bjoernr-de** [comment]
More or less only style changes:
* Added Smilie icon next to the attachment icon in message box
* Added relevant classes to utils `applyTheme()` function
* Small cosmetics so it looks more like the screenshots above
* Added Emoji click handle: Emoji Alias (:foo:) is now being added to the message box

Once I got a little more time I will work further on this. But as said I can't tell when, so anyone else is more than welcome to help on this :)

**Comment by jasonblais** [comment]
Hey @bjoernr-de - thank you again for working on the changes, that's great!

We were thinking that creating a second branch might be easiest -- that way someone from the community can pick up from where you left off, while still preserving the original code prepared by @hmhealey (harrison). 

Would you like to message Harrison (`@harrison` on https://pre-release.mattermost.com) and he can create the branch with your changes? Since you probably won't have the ability to create a branch on the platform repo.

**Comment by bonespiked** [comment]
I'm helping out with this, and wanted a question answered for the UX side - in the category list, if more than one category is visible (particulary at the end of the list ) - Highlighting a single category doesn't make visual sense.  I propose that the categories be highlighted based on what categories are visible on screen, so more than one may be highlighted.  Note the current display:
![image](https://cloud.githubusercontent.com/assets/7880453/22039106/ec6f7aac-dccb-11e6-9030-092455a075c6.png)

my suggestion would cause the last three to be highlighted, as multiple categories are visible onscreen.

**Comment by bonespiked** [comment]
Between @harrison @bjoernr-de and myself, we have finished this feature.  We are doing a quick team review before creating a PR.

**Comment by jasonblais** [comment]
Awesome! Thanks to all of you! 👍

**Comment by Aka4Code** [comment]
When do you plan to publish this with release?

**Comment by jasonblais** [comment]
@Aka4Code The picker is now merged to `master` and scheduled for Mattermost 3.8 release!

You can try it out on our daily build server at https://pre-release.mattermost.com (it needs to be enabled from Account Settings > Advanced > Preview pre-release features first)

Thanks everyone involved for making this feature happen!
