### ISSUE TITLE
Replies to integrations fail in 3.5

### ISSUE THREAD

**Issue by hjc1710** [mattermost/platform#4672]
#### Summary

After 3.5, replies made to messages created by integrations (such as the wonderful [Jenkins integration](https://github.com/jenkinsci/mattermost-plugin)) do not appear work. They make it to the channel, but for the posting user it appears they failed.

#### Steps to reproduce

1. Install an integration such as the Jenkins or GitHub one.
2. Get it to post into the channel.
3. Reply to the message made by the integration and you should see a "Retry" and "Cancel" link, as if the message failed.
    * Sometimes it actually works, but it seems to fail more often when doing this in a Favorited channel.
4. Press "Reply". You will notice it instantly reappears.
5. Refresh the page, you will see your original message and a duplicate made by pressing "Retry".

#### Expected behavior

Messages made in reply to integrations should complete on the first attempt and should not erroneously ask me to Retry them.

#### Observed behavior

After 3.5, any reply you make to a message made by an integration does not properly finish. Instead of seeing the message complete and post, it does not appear in your chat history and you are given the option to "Retry" or "Cancel". For other users, it will show this message. Refreshing the page will show this message. Unfortunately, pressing "Retry" will repost the message, which will appear to fail in the same fashion for the posting user, but will make it to the channel.

The end result is people press "Retry" over and over again and you get:

![screenshot from 2016-11-18 16 43 41](https://cloud.githubusercontent.com/assets/1062500/20716235/8f6b3120-b61f-11e6-8b20-0b96ec93ae1a.png)

#### Possible fixes

I'm not familiar enough with the codebase to find an error, but I can tell you that we are hitting this route: `api/v3/teams/nrj1egj3jjro8mg99gcn1z5xce/channels/1hz79jjo1bfo5fp6j8j4gg93ty/posts/create` with this payload:

```json
{
    "file_ids": [],
    "message": "FAIL IT BABY!",
    "channel_id": "1hz79jjo1bfo5fp6j8j4gg93ty",
    "root_id": "n9ien84mwf88mdanauzqjy41co",
    "parent_id": "n9ien84mwf88mdanauzqjy41co",
    "pending_post_id": "of36ddrjipnx58q4trs9tip1no:1480434127233",
    "user_id": "of36ddrjipnx58q4trs9tip1no",
    "create_at": 1480434127233
}
```

And we don't get ANY content back in the response, only a 500.

If I go into the server and look at docker logs, here's your stack trace:

```
2016/11/29 15:44:12 runtime error: invalid memory address or nil pointer dereference
goroutine 92309 [running]:
runtime/debug.Stack(0x7aacec, 0xc420010190, 0x2)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/mattermost/platform/vendor/github.com/gorilla/handlers.recoveryHandler.log(0xfc45c0, 0xc420130b60, 0x0, 0xc4217be001, 0xb92a00, 0xc420012060)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/gorilla/handlers/recovery.go:84 +0x9b
github.com/mattermost/platform/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0xfcbe80, 0xc420b148f0, 0xfc45c0, 0xc420130b60, 0x0, 0x918d01)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/gorilla/handlers/recovery.go:69 +0xae
panic(0xb92a00, 0xc420012060)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/mattermost/platform/api.sendNotifications(0xc420c16d80, 0xc42175bc20, 0xc420f09040, 0xc420893b80, 0xc4214975a0, 0x43d2fa, 0xcd39e0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/api/post.go:587 +0x4d6
github.com/mattermost/platform/api.handlePostEvents(0xc420c16d80, 0xc42175bc20, 0xc421497701)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/api/post.go:253 +0x267
github.com/mattermost/platform/api.CreatePost(0xc420c16d80, 0xc42175bc20, 0xc421497901, 0xc42098cbd0, 0xc421642401)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/api/post.go:157 +0x3b0
github.com/mattermost/platform/api.createPost(0xc420c16d80, 0xfcbe80, 0xc420b148f0, 0xc42175bb30)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/api/post.go:84 +0x3f4
github.com/mattermost/platform/api.handler.ServeHTTP(0xcd19e8, 0x1010001, 0xfcbe80, 0xc420b148f0, 0xc42175bb30)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/api/context.go:213 +0xa12
github.com/mattermost/platform/api.(*handler).ServeHTTP(0xc420684660, 0xfcbe80, 0xc420b148f0, 0xc42175bb30)
	<autogenerated>:1 +0x70
github.com/mattermost/platform/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4205b75e0, 0xfcbe80, 0xc420b148f0, 0xc42175bb30)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/mattermost/platform/api.(*CorsWrapper).ServeHTTP(0xc420130b60, 0xfcbe80, 0xc420b148f0, 0xc42175bb30)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/api/context.go:263 +0x164
github.com/mattermost/platform/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0xfc45c0, 0xc420130b60, 0x0, 0xa60000c420952d01, 0xfcbe80, 0xc420b148f0, 0xc42175bb30)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/gorilla/handlers/recovery.go:73 +0xae
github.com/mattermost/platform/vendor/github.com/gorilla/handlers.(*recoveryHandler).ServeHTTP(0xc42076fd80, 0xfcbe80, 0xc420b148f0, 0xc42175bb30)
	<autogenerated>:52 +0x8a
net/http.serverHandler.ServeHTTP(0xc4205b5e00, 0xfcbe80, 0xc420b148f0, 0xc42175bb30)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420dfa100, 0xfcc800, 0xc4216423c0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by jasonblais** [comment]
Thanks again @hjc1710 - just to confirm, the replies do not fail on a regular message, only when you try to reply to an integration?

**Comment by jasonblais** [comment]
Please also let me know the 
 - server database (and version if you know)
 - the browsers / clients where you've had the problem reproducing

This information helps us in figuring out what's causing the issue.

Many thanks in advance for an excellent bug report.

**Comment by hjc1710** [comment]
@jasonblais -

Yes, you are correct, this has NEVER happened on a reply to a regular message, on a reply to an integration.

For the other information:

Clients Experiencing This:

* Mattermost Desktop: 3.4.1
* Google Chrome: 51.0.2704.106 (64-bit)
* Google Chrome: 35.0.1916.153 (64-bit)

Database Information:

* RDBMS: MySQL
* Version: 5.6

I have full system admin access, so please let me know if you need other information.

My pleasure! Can't wait for the fix =D.

**Comment by grundleborg** [comment]
Thanks very much for reporting this issue with so much detail. I've been able to reproduce it and have made a ticket on the Mattermost JIRA to track the issue: https://mattermost.atlassian.net/browse/PLT-4906

**Comment by hjc1710** [comment]
Yes! That is awesome news! Thanks so much, all!

**Comment by jasonblais** [comment]
Thanks again @hjc1710 for the report! Really loved the detail here and it helped with reproducing the issue.

I'll close this and we can track the issue in Jira: https://mattermost.atlassian.net/browse/PLT-4906
