### ISSUE TITLE
Don't autocomplete smiley once one is available

### ISSUE THREAD

**Issue by bagage** [mattermost/platform#4682]
For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Currently when one types `:p` the emoji selection pops up and the first choice is not `:p` (it's `:pacman:` instead.). This issue might share similarities with #4510 but I think this one is a specific/easier case to solve.

#### Steps to reproduce
1. Type `:`. The emoji selection pops up (OK).
2. Type `p`. The emoji selection popup automatically goes for `:p` emojis completion (OK), starting with `:pacman:`. (NOK)
3. Hit enter

Testing with Linux desktop version 3.4.1 as well as the website directly.

#### Expected behavior
You expect `:p` to be sent.

#### Observed behavior
It actually autocompletes to `:pacman:` and no message is sent at all (which is OK though because it's how the autocompletion thing should work).

#### Possible fixes
It would be better, in the case of current input being an actual emoji (which `:p` is), to make it appear *first* in the autocomplete list.
This has still an inconvenient of requiring *2* Enter keystroke to be actually sent, but I don't know how to solve that.

**Comment by jasonblais** [comment]
Thanks @bagage for the report,

We have an improvement ticket where the emoji autocomplete will open only after two characters are typed. This avoid the user experience where Enter key has to be hit twice

https://mattermost.atlassian.net/browse/PLT-4950

Sounds like this would cover your use case?

**Comment by bagage** [comment]
@jasonblais If "simple" smileys are single characters long it should be enough yes. But there is still some issue with emoji orders in any case:

1. Type `:p`. `:pacman:` is the first in the list.
2. Type `:pa`. `:pacman:` goes second in the list, and `:package:` goes first. 

## Expected behavior

When user types and while it still matches the first entry of the list, list order should not be changed.

## Observed behavior

Emojis list is reordered at every keystroke, somehow looking random.

**Comment by jasonblais** [comment]
I think that sounds like a bug. I assume `:pacman:` and `:cocktail:` are custom emoji?

Also, does the list sorting change if you type `:pac:`?

**Comment by bagage** [comment]
I could not find any letter where order changed again after 2 typed characters and only a few ones where it does after one character (namely `c, `p`, `m` and possibly 2 I forgot).

**Comment by jasonblais** [comment]
I checked back with our developers and we currently limit the number of emojis we display before sorting the list, for performance.

However, when we change the emoji autocomplete to display only after two characters are typed, this bug will be resolved (ticket link here https://mattermost.atlassian.net/browse/PLT-4950).

**Comment by jasonblais** [comment]
Closing the issue, and we can track the issue in JIRA: https://mattermost.atlassian.net/browse/PLT-4950
