### ISSUE TITLE
MatterMost crashed when sending a DM to someone who left the team

### ISSUE THREAD

**Issue by bartdeslagmulder** [mattermost/platform#4688]
Hi MatterMost,

#### Summary
MatterMost CE is crashing when sending a Direct Message to someone who left the team and is not part of another team.

#### Steps to reproduce
A user left our company yesterday and I guess he removed himself from the team via the top left menu (...) > "Leave Team" option. This morning (the day after) I see a separator in my Direct Messages with the text "Outside this team". I click his name and send him a "test" message. As a result our MatterMost instance crashed.

Didn't reproduce myself but here's a good guess:

- Using the free v3.4.0 (mysql).
- User A & User B are part of the same team. We only have 1 team.
- User A & User B send each other a Direct Message.
- User A clicks the top left menu (...) and selects "Leave Team".
- User B sees in his Direct Messages list a new separator with the text "Outside this team".
- User B clicks User A's name and sends a message.
- MatterMost instance crashed with a `panic: runtime error: index out of range`. See below.

#### Expected behavior
A notification should appear for User B saying that User A has left the team and that he won't receive the message.

#### Observed behavior
> Dec  1 07:54:08 mattermostw01 platform: panic: runtime error: index out of range
Dec  1 07:54:08 mattermostw01 platform: goroutine 692169 [running]:
Dec  1 07:54:08 mattermostw01 platform: panic(0xdae740, 0xc82000a050)
Dec  1 07:54:08 mattermostw01 platform: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Dec  1 07:54:08 mattermostw01 platform: github.com/mattermost/platform/api.sendNotificationEmail(0xc8232317a0, 0xc8238b3880, 0xc824f23200, 0xc824d0efd0, 0xc824fa7180, 0xc824dfb378, 0x4, 0xc823346a20)
Dec  1 07:54:08 mattermostw01 platform: /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/api/post.go:815 +0x3099
Dec  1 07:54:08 mattermostw01 platform: github.com/mattermost/platform/api.sendNotifications(0xc8232317a0, 0xc8238b3880, 0xc824fa7180, 0xc824d0efd0)
Dec  1 07:54:08 mattermostw01 platform: /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/api/post.go:689 +0x39f2
Dec  1 07:54:08 mattermostw01 platform: created by github.com/mattermost/platform/api.handlePostEvents
Dec  1 07:54:08 mattermostw01 platform: /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/api/post.go:262 +0x710
Dec  1 07:54:08 mattermostw01 systemd: mattermost.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec  1 07:54:08 mattermostw01 systemd: Unit mattermost.service entered failed state.
Dec  1 07:54:08 mattermostw01 systemd: mattermost.service failed.

**Comment by coreyhulen** [comment]
Thanks, I believe this is the same issue as https://mattermost.atlassian.net/browse/PLT-4636 which is fixed in master.

**Comment by bartdeslagmulder** [comment]
👍
