### ISSUE TITLE
[Help Wanted] Move instances of Client.getChannel() in components to an action

### ISSUE THREAD

**Issue by jwilander** [mattermost/platform#4696]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Difficulty**: Introductory (new to codebase)

**Details**:
To be [Flux](https://facebook.github.io/flux/docs/actions-and-the-dispatcher.html)-compliant our web utilities should be separate from our views and UI components. Views should use re-usable actions instead of directly interacting with the web utilities (specifically Client/client.jsx in our case).

Move any instances of `Client.getChannel()` inside of the [components directory](https://github.com/mattermost/platform/tree/master/webapp/components) into an action inside of [webapp/actions/channel_actions.jsx](https://github.com/mattermost/platform/blob/master/webapp/actions/channel_actions.jsx) and use the new action in place of where the `Client.getChannel()` invocations were.

Any common functionality should be performed in the action where possible, for example event dispatches through `AppDispatcher`.

Please see other actions inside of [webapp/actions/channel_actions.jsx](https://github.com/mattermost/platform/blob/master/webapp/actions/channel_actions.jsx) for examples.

A quick grep at the time of creation of this ticket shows `Client.getChannel()` being used in:
- https://github.com/mattermost/platform/tree/master/webapp/components/new_channel_flow.jsx

**Comment by bjoernr-de** [comment]
Also taking care of this one

**Comment by jwilander** [comment]
Hi @bjoernr-de, did you have a chance to get to this ticket yet?

**Comment by bjoernr-de** [comment]
Oops, sure will take a look tomorrow!

**Comment by bjoernr-de** [comment]
@jwilander there is no usage of `Client.getChannel()` anymore in components. Previous usage in `new_channel_flow.jsx` has already been addressed in https://github.com/mattermost/platform/commit/8a92908dad4f74ac3373d65a361594acb95cf1a0 so I think this ticket can be closed?

**Comment by jwilander** [comment]
Looks like you're right, thanks @bjoernr-de !
