### ISSUE TITLE
Your Own User Should Never be the Top Mention Auto-Complete Result

### ISSUE THREAD

**Issue by hjc1710** [mattermost/platform#4702]
#### Summary

Ever since 3.5, every time I attempt type `@channel`, I am the first result in the mention auto-complete because my last name begins with `Ch`. I don't think your own user should EVER be the top result in the mention auto-complete.

#### Steps to reproduce

1. Make your last name or user name have a `ch` in it.
2. Begin typing `@ch` for `@channel`.
3. You are the first result and not the auto-complete for `@channel`.

#### Expected behavior

I expect myself to be the final result in the mention auto-complete menu. Having it in the menu is useful, but the odds that I want to mention myself are slim.

#### Observed behavior

When I begin typing `@channel`, my own user is the first result in the auto-complete and not the channel itself.

#### Possible fixes

N/A due to codebase familiarity.

**Comment by jasonblais** [comment]
Hm, wondering if there would be instances where this could cause confusion?

For instance, if we had it at the bottom of the autocomplete list, your username wouldn't appear on the "channel members" section. I wouldn't expect to find it at the bottom of the "not in channel" section, which would be the case here.

Thoughts?

**Comment by hjc1710** [comment]
Hmmmm.. that is a really good point. Does your username really need to be in the auto-complete list would be my next question?

I know I never need to mention myself, but is there some workflow I'm not thinking of where mentioning yourself is required or makes sense? I think removing it entirely is the best fit.

I really hate this idea, but maybe a setting to remove yourself from the auto-complete list? I hate setting bloat, but I also hate this bug.

I think those are my only options and opinions. Let me know your thoughts and if this isn't something we can get done due to creative differences, I'll happily forget about it =).

**Comment by jasonblais** [comment]
Yes, I had a similar thought on having yourself on the autocomplete list - [I've posted a question on our UX channel to discuss, which you're welcome to participate in](https://pre-release.mattermost.com/core/pl/b66utazkejfa8k3pq7rdtbpdse).

**Comment by jasonblais** [comment]
Hey @hjc1710, I've created a ticket for [removing your own username from (at)-mention autocomplete](https://mattermost.atlassian.net/browse/PLT-5027).

It was discussed and I agree that it's quite rare to (at)-mention yourself in a conversation.

Would you or someone you know be interested submitting an improvement for it? It would get counted [towards our Hackfest event](https://about.mattermost.com/hackfest) where four PRs wins you an exclusive Mattermost shirt :)

**Comment by hjc1710** [comment]
@jasonblais - I'm not much of a React guy myself, but if there's something you could do to point me in the right direction of where to start, I think I'd be willing to take a crack at it over my Christmas break (12/23-1/3).

If not, I'll see how some of our frontend team members feel tackling this =).

I'm really glad that we agreed that the self-(at)-mention is rare. This is a great approach! Thanks all!

**Comment by jasonblais** [comment]
Would you like to join our [Developers community channel](https://pre-release.mattermost.com/core/channels/tickets)?

That's an excellent place to ask questions and both our community members and core developers are happy to point you in the right direction :)

**Comment by jasonblais** [comment]
Thanks for your interest taking a look at it!

**Comment by hjc1710** [comment]
Just joined the channel! I'll try my hand at this over the weekend and keep all questions to there.

**Comment by hjc1710** [comment]
Pleased to say that initial setup for this went fine and I'm quite positive I've got this entirely solved!

I just need to cross a few t's and dot some i's (looking at you CLA and co.), so this PR should be opened sometime tomorrow.

**Comment by hjc1710** [comment]
PR opened as #4916!

Had a good time doing this =).
