### ISSUE TITLE
Users Imported From Slack Cannot Initiate Direct Messages

### ISSUE THREAD

**Issue by chakatz** [mattermost/platform#4707]
#### Summary
Users imported from Slack cannot initiate Direct Messages.

#### Steps to reproduce
- mattermost-enterprise-3.5.0-linux-amd64.tar.gz (without enterprise license)
- PostgreSQL 9.6.1

We have 75 users in our team. The first attempted import from Slack produced errors because the default maximum number of users per team is 50.
- Raised the limit per-team to 200
- Deleted the team and tried the import again. This produced errors because the users already existed.
- Executed `platform -reset_database` to remove existing users and start clean before import.
- Imported users and history from Slack and users completed the "Forgot Password" procedure to activate their account and join the team.
- "**_Enable users to open Direct Message channels with:_**" is set to '**_Any user on the Mattermost server_**'
- Upgrade to MM 3.5.1 did not resolve this problem.

#### Expected behavior
All users should be able to initiate Direct Messages

#### Observed behavior
- Users can send and receive messages in the Channels with no problem.
- The System Admin user and users who were created manually are able to initiate Direct messages with anyone.
- Users imported from Slack can communicate in Direct Message sessions opened by other users.
- **Users who were imported from Slack are not able to initiate direct messages.**

This is found in the logs for all failed attempts:
[2016/12/02 12:39:55 UTC] [EROR] /api/v3/teams/uuzqjjrzyifbddwhz68iuhcc5h/channels/create_direct:HasPermissionToContext code=403 rid=1wx63qt34fgh5q4epaodrgexcr uid=7zj7bztp7if7j8e59n7dmpqg1w ip=xxx.xxx.xxx.xxx You do not have the appropriate permissions [details: userId=7zj7bztp7if7j8e59n7dmpqg1w, teamId=uuzqjjrzyifbddwhz68iuhcc5h permission=create_direct_channel [<NO ROLES>]]
[2016/12/02 12:39:55 UTC] [EROR] /api/v3/teams/uuzqjjrzyifbddwhz68iuhcc5h/channels/name/7zj7bztp7if7j8e59n7dmpqg1w__qi1gspgb3jd53xtu8jcq5c4h1a/join:SqlChannelStore.GetByName code=403 rid=bxdeoxnu4fftfbr4bbdn4n9boe uid=7zj7bztp7if7j8e59n7dmpqg1w ip=xxx.xxx.xxx.xxx Channel does not exist [details: teamId=uuzqjjrzyifbddwhz68iuhcc5h, name=7zj7bztp7if7j8e59n7dmpqg1w__qi1gspgb3jd53xtu8jcq5c4h1a, sql: no rows in result set]

#### Possible fixes
Seems that either there is a problem with the import from Slack, or multiple attempted imports messed something up and `platform -reset_database` doesn't do what is expected.
Perhaps actually deleting the DB and doing a fresh install will help?

**Comment by dadaxr** [comment]
Exact same wrong behavior on our side...

**Comment by imunic** [comment]
I investigated this a couple of days ago and didn't get to reporting it, basically the users that can't send direct messages are missing the "system_user" role. 

The import procedure does not seem to add that role in any way and it is required for direct messaging and probably other things. If the role is missing when trying to initiate a direct message there is a 403 http error logged.

The fix is to add the role via the database directly.

**Comment by yangchen1** [comment]
Thanks for the report @chakatz, and @dadaxr @imunic for looking into it. I've created a [ticket](https://mattermost.atlassian.net/browse/PLT-4955) for this. Are any of you (or anyone else, if you're reading this) interested in contributing a fix?

**Comment by dadaxr** [comment]
Sadly not enough time in a near future to do that :(

**Comment by jasonblais** [comment]
No worries @dadaxr, appreciate your help participating in troubleshooting the issue.

If anyone in the community was interested helping out, please let us know. 

JIRA ticket can be tracked here: https://mattermost.atlassian.net/browse/PLT-4955

**Comment by coreyman** [comment]
https://mattermost.atlassian.net/browse/PLT-4955

I just upgraded to 3.6.1 and the database upgraded to 3.6.0 schema. I am still having this issue. Previous version 3.5. Users imported from slack are not able to start a direct message. I tried fixing the issue by adding all users the 'system_user' role in postgres when I was on 3.5 but that didn't do anything either.

**Comment by grundleborg** [comment]
@coreyman were the users imported before you upgraded to 3.6.1 or after?
