### ISSUE TITLE
[Help Wanted] Emoji reactions overlap the following post when they wrap to two lines

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4708]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details**: ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4855))

Repro steps:
1) Make a new post
2) Add enough reactions to that post using `+:+1:`, `+:-1:`, `+:100:`, `+:angry:`, `+:taco:`, etc so that the reactions wrap to a second line. Making the window smaller horizontally will make this easier
3) Make another post

Observed: The reactions which wrapped onto a second line will overlap the following post

![image](https://cloud.githubusercontent.com/assets/13119842/20867899/a8831c80-ba1c-11e6-87ce-38d99f2c516a.png)

Expected: Enough space should be provided for the reactions so that they don't overlap the next post.

**Comment by bjoernr-de** [comment]
I can take care of this issue in the evening :)

**Comment by bjoernr-de** [comment]
Hi @jasonblais 

quick one to fix the overlapping emoji reactions. Anyway, IMHO there could be still some small design adaptions for multi-line emoji reactions - especially on mobile.
<img width="778" alt="screen shot 2016-12-12 at 21 23 37" src="https://cloud.githubusercontent.com/assets/2854699/21115490/c274109a-c0b1-11e6-827f-7f01e8029fe4.png">
<img width="322" alt="screen shot 2016-12-12 at 21 22 57" src="https://cloud.githubusercontent.com/assets/2854699/21115497/cbca02c6-c0b1-11e6-9569-badc4c6398b3.png">

Not sure if those improvements should also be covered by this issue.
I'd suggest the following:

<img width="777" alt="screen shot 2016-12-12 at 21 32 09" src="https://cloud.githubusercontent.com/assets/2854699/21115667/a7c5bcd4-c0b2-11e6-985d-cf6d2a7050fe.png">
<img width="321" alt="screen shot 2016-12-12 at 21 32 22" src="https://cloud.githubusercontent.com/assets/2854699/21115670/addc379c-c0b2-11e6-9136-258df6baf128.png">

What do you think? 😃

**Comment by jasonblais** [comment]
We'd love to take the improvement for multi-line emoji reactions that you suggested! I think that looks great!

**Comment by esethna** [comment]
Closing as solved, thanks @bjoernr-de, much appreciated!!
