### ISSUE TITLE
[Help Wanted] Sort teams alphabetically by Display Name on Team Selection Page

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4713]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-4907))

Currently, the teams aren't ordered in a logical way (see screenshot). Proposed solution is to change the ordering to be alphabetical by the Team Display Name. 

<img width="480" alt="screenshot 2016-12-02 14 08 32" src="https://cloud.githubusercontent.com/assets/9354841/20898685/4ce0f512-baf5-11e6-8905-852e9d26d60b.png">

**Comment by debanshuk** [comment]
I am interested in working on this ticket. Have added a comment on JIRA issue too.

**Comment by hmhealey** [comment]
@debanshuk Awesome to hear! We're looking forward to it :)

**Comment by jasonblais** [comment]
Thanks @debanshuk! Closing via #4757
