### ISSUE TITLE
Massive memory and bandwidth usage if there is a lot of images/gifs linked in chat

### ISSUE THREAD

**Issue by XANi** [mattermost/platform#4724]
#### Summary
There is no lazy loading pf medida (gifs/etc) linked in chat ( via `![image](address)` ) so certain usage patterns cause very bad performance or experience

#### Steps to reproduce
Post this:

    ![t](http://i.imgur.com/zPg20WM.gif)
    ![t](http://i.imgur.com/ZPQGptf.gif)
    ![t](http://i.imgur.com/Zq6e3KV.gif)
    ![t](http://i.imgur.com/zqUn0zw.gif)
    ![t](http://i.imgur.com/ZuqqFk1.gif)
    ![t](http://i.imgur.com/ZVRyk9F.gif)
    ![t](http://i.imgur.com/zXGI11p.gif)
    ![t](http://i.imgur.com/ZY69mXy.gif)
    ![t](http://i.imgur.com/zYOCpJj.gif)
    ![t](http://i.imgur.com/ZYTlGjj.gif)

And then try to enter site from mobile or other bandwidth-limited devices.

In our case it happened because in some conversations on off-topic channels people linked a bunch of gifs, but (to a smaller extent) there is a similar problem with "normal" images.

Trying to open channel causes traffic spikes like that: 

![zaznaczenie_2016-12-06_001](https://cloud.githubusercontent.com/assets/147394/20927381/a1fc33fa-bbc1-11e6-9c1d-2ad9913d871d.png) on desktop (>100Mbit for more than 20s) and much worse (and, more importantly it eats thru mobile bandwidth) on mobile.

It also significantly hampers mobile performance, even pasting one gif can "kill it" for weaker phones

#### Expected behavior

There should be an option to either:

* disable preview **per-device** (so mobile users wont eat thru their data plan just because someone linked a big gif, but normal desktop still works as before). So basically make image links "normal" links on demand
* load only images that user is currently looking at (currently it just displays all images in channel history)
* block animated gifs from playing/downloading (is that even possible ?)

or some/all of above

**Comment by jasonblais** [comment]
Sorry @XANi for the delayed response here,

This is an excellent note and I love the details you provided! [I've posted a snippet of your report in our Developers:Performance community channel](https://pre-release.mattermost.com/core/pl/7ewd3tb8cbd7ify14aq7z38air). You're welcome to join and participate in the discussion.

**Comment by jasonblais** [comment]
Hey @XANi, we currently only load the images and GIFs that are currently visible for the user on the channel (i.e. the last 60).

Disabling previews by device, e.g. for mobiles, is something we could consider in the future - 
would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

Other suggestions are also welcome
