### ISSUE TITLE
config.json type mistmatches are hard (impossible) to troubleshoot

### ISSUE THREAD

**Issue by anlutro** [mattermost/platform#4727]
#### Summary
Mattermost expects config.json different values to be of certain types. If this type is wrong, you have no way of figuring out what the problem is.

#### Steps to reproduce
I'm using Mattermost 3.5.1, but probably applicable to other versions. Create a config.json with the wrong type of some value:

```
$ cat config/config_test.json 
{"FileSettings": {"Directory": 123}}
```

#### Expected behavior
I get an error message telling me which configuration value is of the wrong type so I can fix it.

#### Observed behavior
```
$ ./bin/platform -config=config/config_test.json
[22:09:04 CET 2016/12/06] [EROR] (main.main:107) Unable to load mattermost configuration file:  Error decoding config file=/path/to/config/config_test.json, err=json: cannot unmarshal number into Go value of type string
```

**Comment by esethna** [comment]
Thanks @anlutro, have you taken a look at our [documentation for the configuration settings](https://docs.mattermost.com/administration/config-settings.html)? The input options and formatting is described in detail for each setting.

**Comment by anlutro** [comment]
I managed to figure out which value was causing the crash, but only by brute force trial and error. I *now* know that the email SMTP port should be a string, but the error message should be telling me that so I don't have to spend 30 minutes trying to guess what's causing the error.

**Comment by esethna** [comment]
Thanks @anlutro, makes sense, [ticket created to track in JIRA](https://mattermost.atlassian.net/browse/PLT-4974).
