### ISSUE TITLE
Window going black

### ISSUE THREAD

**Issue by S6066** [mattermost/platform#4730]
Windows 10 x64, MM Entreprise 3.5.1 (MM client)  
Sometimes, after my laptop wakes up from sleep, the MM app window is totally black.  
I can't close the app, so I usually restart MM with the tray icon.  
I don't have a screen and didn't tried anything, I'll try as soon as possible.

**Comment by esethna** [comment]
There is a new release of the Desktop app scheduled for December 14th. Could you please attempt to reproduce using the latest release candidate: https://releases.mattermost.com/desktop/3.5.0-rc3/mattermost-desktop-3.5.0-rc3-win64.zip

If this does not solve your issue please submit the issue to the [Desktop](https://github.com/mattermost/desktop) repo as it sounds like a potential issue with the widows desktop application.

**Comment by jasonblais** [comment]
@S6066 

Does the black screen appear with any other apps or just Mattermost? Do you use any video drivers like Optimus?

**Comment by S6066** [comment]
Hm, I don't have the bug even without the RC3 app  
@jasonblais It was just MatterMost, and I don't think I use Optimus

**Comment by jasonblais** [comment]
Thanks for reaching back!

Just to confirm: are you no longer able to see the bug?

**Comment by S6066** [comment]
Yeah, I can't see the bug now.

**Comment by jasonblais** [comment]
Thanks! Closing as resolved

**Comment by S6066** [comment]
I have the bug again, on MM PC Client 3.5.0, and MM 3.6.1 Enterprise Edition.
It occurs when I lock windows, and when it occurs, the windows is in the taskbar even if I closed it before.
The window is of course black, and I can't make it appear or close it.  
It also occurs when the PC is sleeping for too long, maybe because I'm using wifi and windows deactivate for power saving purposes ?

**Comment by jasonblais** [comment]
Hey @S6066! Does any of the troubleshooting steps under [Desktop App window is black and doesn’t load the page](https://docs.mattermost.com/install/desktop.html#troubleshooting) help resolve it?

> It occurs when I lock windows, and when it occurs, the MM window is in the taskbar even if I closed it before.

When you say close, do you press the "X" to close the app window or do you quit the app?

**Comment by S6066** [comment]
1) Yeah, as I said, when I quit the app (right click on the tray icon > Exit) and re-start it, I don't have the bug.
2) I press the "X"
