### ISSUE TITLE
Notifications don't respect Team Member display settings

### ISSUE THREAD

**Issue by spockz** [mattermost/platform#4747]
#### Summary
Notifications always use the username to identify the user instead of using the preference set in Team Member display.

#### Steps to reproduce
Enable notifications. Switch display preference to First+Lastname. Notifications still show the username. (Mattermost mac: 3.4.0 and 3.4.1; Mattermost team edition web: 3.5.0)

#### Expected behaviour
I expect to see the same name in the notification as in the channel, as configured in the settings.

#### Observed behaviour
I always see the username.

#### Possible fixes
n/a

**Comment by spockz** [comment]
This same issue also holds for join/leave notifications in the channel chat history itself.

**Comment by esethna** [comment]
Thanks @spockz, there was a recent pull request merged from the community to get email and push notifications to follow the Teammate name display setting. This will be available in the January 16th release of v3.6. 

https://github.com/mattermost/platform/pull/4660
