### ISSUE TITLE
[Help Wanted] Don't show (message deleted) placeholder to the user that deleted the message

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4749]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-3960))

Repro steps:
1) Post a message
2) Delete that message

Observed: All users see `(message deleted)` placeholder and can remove it by clicking the X button or refreshing the page.
Expected: The message immediately disappears for the user that deleted the message. Other users should still see the `(message deleted)` placeholder.

**Comment by khawerrind** [comment]
I am working on this ticket

**Comment by khawerrind** [comment]
Here is the PR for this ticket. https://github.com/mattermost/platform/pull/4839

**Comment by mikaoelitiana** [comment]
This one can be closed I think

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana, you're right

@khawerrind big thanks for your contribution!
