### ISSUE TITLE
[Help Wanted] Add [...] menu to search results list

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4750]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-4562))

Currently there's no [...] menu in the search results list, so you need to open the post to access it. 

Proposed Change: Have the [...] menu show in the search results lists. Screenshot of the UI attached, and where the [...] menu would appear.

NOTE:
 - On desktop, the [...] menu should only show when hovering over the post, similar to the reply arrow 
 - On mobile app and mobile browser, the [...] menu should always show (similar to the reply arrow) as there is no hover effect on mobile

![image](https://cloud.githubusercontent.com/assets/13119842/21036392/92777790-bd93-11e6-9241-d6ef6ad0a115.png)

**Comment by VeraLyu** [comment]
I'm currently working on this one.Thanks.
