### ISSUE TITLE
[Help Wanted] Add "(Edited)" indicator if a message has been edited

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4751]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-135))

Currently there is no indication after a message has been edited. 

This improvement adds an `(Edited)` indicator if a message has been edited. A screenshot of the UI included below.

Note: The timestamp of the message should not change after it's edited - the timestamp should be the original posting time.

**Comment by debanshuk** [comment]
I am working on this issue. Also added a comment on JIRA ticket.

**Comment by debanshuk** [comment]
I am working on this issue. Also added a comment on JIRA ticket.

**Comment by jasonblais** [comment]
Thanks @debanshuk!

**Comment by jasonblais** [comment]
Closed via #4923, fantastic work @debanshuk!
