### ISSUE TITLE
[Help Wanted] Create screens to edit incoming and outgoing webhooks

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4753]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-2496))

**Tip:** Before getting started, take a look at how [edit screens for slash commands were created](https://github.com/mattermost/platform/issues/4335) by @bolecki.

It's also a good idea to test the edit screens so you can see how they work for slash commands.

1 - Add an "Edit" button for incoming and outgoing webhooks that offers an Edit screen (similar to the create screen) that saves back changes.

![image](https://cloud.githubusercontent.com/assets/13119842/21037833/e750a790-bd9e-11e6-8d0d-8b5f81610082.png)
_Above: For incoming webhooks, add "Edit" button left of the "Delete" option. For outgoing webhooks, add it between regenerating the token and deleting options_

![image](https://cloud.githubusercontent.com/assets/13119842/21037888/55ad4252-bd9f-11e6-848e-b11dd923236c.png)
_Above: Edit screen that opens after clicking "Edit" in the previous screenshot for incoming webhooks. Similarly for outgoing webhooks_

2 - For outgoing webhooks, if it's a change that will break existing integrations (one of content type, trigger words, or callback URLs), add a confirmation dialog notifying the user of the consequences of the update.

The dialog has two buttons, where "Cancel" brings the user back to the edit screen, and "Update" updates the outgoing webhook.

Text should read `Your changes may break the existing outgoing webhook. Are you sure you would like to update it?`

Below: Sample confirmation dialog for slash commads
![image](https://cloud.githubusercontent.com/assets/13119842/21038001/3ce1c09e-bda0-11e6-8dc5-c720ba4eb547.png)

**Comment by mpoornima** [comment]
@jasonblais, I'm interested in working on this issue. I've already started working on this and have almost completed the edit incoming webhook flow. As I'm contributing for the first time, can you please let me know the procedure to follow to get the issue assigned to me. 

Thanks
Poornima

**Comment by jasonblais** [comment]
That's fantastic, thanks @mpoornima! 

To prepare and submit a pull request, you can follow our [contribution guidelines in our Mattermost documentation](https://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request).

Looking forward to the improvement!

**Comment by jasonblais** [comment]
Closed via #5272, big thanks @mpoornima!
