### ISSUE TITLE
[Help Wanted] Add a direct message link to profile popover

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4754]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-3132))

When clicking on a username or profile picture in a conversation channel, a profile popover appears showing information about the person. 

This improvement adds a new button to this popover, "Send Message". Clicking on this button should open the direct message channel with that user. 

Attached is a screenshot of the UI. The icon used is "fa-paper-plane".

![image](https://cloud.githubusercontent.com/assets/13119842/21051070/7f84c238-bdec-11e6-96cd-0906a4511569.png)

**Comment by khawerrind** [comment]
Working on it

**Comment by khawerrind** [comment]
Here is the PR https://github.com/mattermost/platform/pull/4853

**Comment by jasonblais** [comment]
You're awesome @khawerrind!

**Comment by jasonblais** [comment]
Hey @khawerrind, we found a corner case with this feature:

```
Repro steps:
1. Login to the Android app
2. Click reply on a message posted by someone you've never DMed before
3. Click on the profile pic in the RHS and click "Send Message"

Observed: Channel switches in background but RHS doesn't close
Expected: Channel switches and RHS closes so I can see the channel
```

Would you be interested submitting a fix for it? https://mattermost.atlassian.net/browse/PLT-5174

**Comment by khawerrind** [comment]
@jasonblais here is the PR for the above mentioned issue https://github.com/mattermost/platform/pull/5017

**Comment by jasonblais** [comment]
Awesome, thanks @khawerrind!
