### ISSUE TITLE
[Help Wanted] Unarchive channel 

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4756]
People need to be able to unarchive channels and private groups

Create a new pane: **Team Settings > Administration** and add the following: 

Title: 
- Archived Channels 

Control: 
- [Selectable scrolling list of archived channels and private groups shorted alphabetically by Channel Name, 3 entries high in format `[ICON] CHANNEL_UI_NAME (CHANNEL_HANDLE_NAME)`]
- [Button: `Unarchive`]

Help text: 
- Click "Unarchive" to restore any archived private group to which you have access or any public channel. 

Note:
- Any user can access this interface. There's no special privileges for System Admin or Team Admin (e.g. to see private groups to which they are not a member). 
- If we do this ticket, there needs to a corresponding control under SYSTEM CONSOLE > POLICY to restrict who can use this interface.

**Comment by jwilander** [comment]
Closing until this is thought out more

**Comment by it33** [comment]
@jwilander can you share what's not thought out?

**Comment by jwilander** [comment]
Discussion here: https://pre-release.mattermost.com/core/pl/13rfii69uidxi8mk5c46be4she

**Comment by wpayne** [comment]
Or, in MySQL..
update Channels set DeleteAt = 0 where Name='<channel url>';
