### ISSUE TITLE
[Help Wanted] Add System Message feedback for /expand and /collapse

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4759]
Repro: 

- Type `/expand ENTER` or `/collapse ENTER`

![image](https://cloud.githubusercontent.com/assets/177788/21070824/0c5128d6-be43-11e6-9496-fc797522dcba.png)

Expected:  

- System Message with either `Image links now expand by default` or `Image links now collapse by default`

Observed: 

- No System Message

**Comment by kaakaa** [comment]
I would like to do this.
But I have a question.

When user types `/expand foo ENTER`, which message should system return?
* `Image links now expand by default`
* `Image links now expand by default foo`

**Comment by it33** [comment]
Thanks @kaakaa! In this case `foo` should just be ignored.
