### ISSUE TITLE
[Help Wanted] "We couldn't get the post" error on emoji reactions when posting to multiple deleted posts 

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4760]
#### Summary
"We couldn't get the post" error on emoji reactions when posting to multiple deleted posts 

#### Steps to reproduce
1. Post a message, "adsf", then two replies, and delete the replies so the screen shows two "(message deleted)" posts. 
2. Attempt to add an emoji reaction with `+:+1:`

![image](https://cloud.githubusercontent.com/assets/177788/21075475/1b46f0f2-bec8-11e6-8f3a-ad50000e4d80.png)

#### Expected behavior

Emoji reaction is added to "adsf" message

#### Observed behavior
Emoji reaction is added to "adsf" message but an error appears in JS console.

![image](https://cloud.githubusercontent.com/assets/13119842/25088327/8f911d72-2343-11e7-8fa6-d3f8e4154a20.png)

**Comment by jasonblais** [comment]
Reproduced consistently. Updated ticket to reflect and change to Help Wanted.

Also changed expected behaviour to be `Emoji reaction is added to "adsf" message`

**Comment by jasonblais** [comment]
This is resolved, I'm no longer able to reproduce the issue.

**Comment by esethna** [comment]
No longer repros, closing as resolved.
