### ISSUE TITLE
[Help Wanted] Editing a message doesn't update reference in reply

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4765]
Repro: 

1. Post message "Blah", then a new message "Bleh", the a reply on "Blah" with "Bloo"
2. Edit "Blah to "Blah - Not updating"

Observed:

In reply message, reference still shows "Blah", it should be "Blah - Not updating" 

![image](https://cloud.githubusercontent.com/assets/177788/21084799/9e40a278-bfbd-11e6-8d65-ded76979af8d.png)

If I click [...] on the "Bloo" reply, then it updates "Blah" to "Blah - Not updating" 

![image](https://cloud.githubusercontent.com/assets/177788/21084835/df015a78-bfbd-11e6-9ddf-a7f7ff91bcde.png)

**Comment by jasonblais** [comment]
Thanks for finding this!

I will close this issue however and create a JIRA ticket to discuss in triage.

The reference is updated, but after a refresh. Devs are avoiding real-time updates to limit impact on performance, unless they're essential for the user experience and I'm not sure this qualifies as one.
