### ISSUE TITLE
[Help Wanted] Sort teams on System Console alphabetically by Team Display Name

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4775]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-4977))

Currently, the teams aren't ordered in a logical way (see screenshot). Proposed solution is to change the ordering to be alphabetical by the Team Display Name, following previous work from here https://github.com/mattermost/platform/pull/4757

![image](https://cloud.githubusercontent.com/assets/13119842/21122577/efb475b0-c0a0-11e6-9ed1-904336ff4dd2.png)
*Above: Team list when clicking on the three-dotted menu in System Console*

![image](https://cloud.githubusercontent.com/assets/13119842/21122692/d3ed8cda-c0a1-11e6-817f-c75266385b41.png)
*Above: Team list when clicking the "+" button next to "TEAMS" in System Console*

**Comment by debanshuk** [comment]
I am working on this issue.

**Comment by jasonblais** [comment]
Thanks @debanshuk :)
