### ISSUE TITLE
Add support for rendering emoji codes as emoji images

### ISSUE THREAD

**Issue by aminehmida** [mattermost/platform#479]
This is a feature request: can you please add support for emoji. This is an extensive list of [emojis](http://www.emoji-cheat-sheet.com/) and supported sites.
![one just](https://i.imgflip.com/q35zw.jpg)

:smiley:

**Comment by Aldarone** [comment]
+1

**Comment by it33** [comment]
Hi @aminehmida, @Aldarone, agree this makes sense, we've filed a ticket and are accepting pull requests on this: https://mattermost.atlassian.net/browse/PL-40

Emoji can be entered, e.g. from iOS devices, Mattermost just doesn't support the text codes yet.

**Comment by it33** [comment]
Emojis code support now on master: https://github.com/mattermost/platform
