### ISSUE TITLE
[Help Wanted] Ability to crop a profile pic instead of squeezing or stretching

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4790]
#### Summary
Ability to crop a profile pic instead of squeezing or stretching

#### Steps to reproduce

Go to Account Settings > General > Profile Picture and upload a photo that is not square: 

![image](https://cloud.githubusercontent.com/assets/177788/21168452/ee446168-c168-11e6-8186-68a9e754cb35.png)

#### Observed behavior

Image is scaled into a square, distorting proportions: 

![image](https://cloud.githubusercontent.com/assets/177788/21168458/f89bf586-c168-11e6-85ae-3c6048983532.png)

#### Expected behavior

Image is not distorted.

#### Possible fixes

Picture's shortest side is scaled to 128x, then the image is cropped on the left and right to fix into a square. This essentially cuts a square in the center of a non-square image. 

The cropping should be done from the center of the image (i.e. the image should br cropped from the sides).

**Comment by tudorgergely** [comment]
I would work on this. Why not make the cropping selection user defined? I mean he could choose the zoom or at least the side which is cropped.

If you want to keep thing as simple as possible then I understand the automatic cropping of the middle of the picture

**Comment by jasonblais** [comment]
Thanks @tudorgergely, good feedback

I think letting the user to scale and crop a photo to fit the square size would be nice - but it would need a more complete spec, including UI.

I'd consider that as a second phase for improving the profile picture upload experience.

**Comment by tudorgergely** [comment]
good then. I will finish this with direct crop of the center. Also I am almost done with modifications for progress bar. sorry for the long wait

**Comment by jasonblais** [comment]
Closed via #5653, thanks @tudorgergely!
