### ISSUE TITLE
[Help Wanted] Don't move the "@" sign and flag icon to the left of search bar when opening the right hand sidebar

### ISSUE THREAD

**Issue by yangchen1** [mattermost/platform#4794]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

Details: ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-3782))

Repro steps:
Click on the @ or Flag icon at the top, right-hand side of the app.

Observed:
The @ and Flag icon jump to the left side of the search bar.

Expected:
The @ and Flag icon should stay on the right side of the search bar.

**Comment by khawerrind** [comment]
I am working on it

**Comment by khawerrind** [comment]
Here is the PR https://github.com/mattermost/platform/pull/4850

**Comment by jasonblais** [comment]
Awesome, thanks @khawerrind!
