### ISSUE TITLE
Can't download or view a .png file from another user if they uploaded it from the Mac OS X MatterMost app

### ISSUE THREAD

**Issue by rriitanosri** [mattermost/platform#4798]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Can't download or view a .png file from another user if they uploaded it from the Mac OS X MatterMost app

#### Steps to reproduce
To reproduce the issue, ask a user to send you a .png file from  the Mac OS X mattermost app version:3.4.0, and notice that the .png file will be stuck at 100% when attempting to view it and attempting to download it will result in a file not found error. This will happen if you try to download the .png from the Mattermost web app or from the desktop app. 

#### Expected behavior
If a user uses the Mac OS X Mattermost application Version: 3.4.0 (not sure if the issue exists in other versions) attempts to upload a .png file and send it through a direct message to another user, the other user will not be able to view or download the .png file. If the other user opens mattermost in Firefox (version 50.0.2), Chrome (version 55.0.2883.87 (64-bit)), or Safari (10.0.1) they will still be unable to view or open the file. The version of OS X the issue was observed in was OS X El Capitan. If the user uploads a .png file from the mattermost website rather than the desktop app, the .png will upload correctly and the other user will be able to view it.

#### Observed behavior
Attempting to view the .png results in a loading hang up at 100%:
<img width="379" alt="screen shot 2016-12-14 at 10 33 52 am" src="https://cloud.githubusercontent.com/assets/24551122/21203719/fe3826b0-c210-11e6-9be0-90a164885e0a.png">

Attempting to download the .png from the desktop app does nothing. When attempting to download the .png from the browser, the user is taken to a file not found page or receives a file not found error. 

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by jasonblais** [comment]
Thanks for the detailed report @rriitanosri! 

We just released a new version of the Desktop App, [would you like to download it and see if the issue still reproduces](https://about.mattermost.com/download/#mattermostApps)? 

Also, which Mattermost server do you have? (you can find this by clicking the three-dotted Mattermost menu next to your profile picture, then "About Mattermost")

**Comment by rriitanosri** [comment]
Hi,

Sorry for not getting back to you sooner. I updated the app to the new version and it fixed the issue with uploading screenshots.

I noticed a small thing when I clicked the three-dotted Mattermost menu to check what server I had. The about page information wasn’t updated to the new information. The about page says the application’s version is 3.4.0, but when I inspect the app installed on my machine, it shows the version is 3.5.0. See the following screenshots:

[cid:image001.png@01D25B6A.A40A86E0][cid:image002.png@01D25B6A.A40A86E0]

It looks like someone forgot to update the about page information when the new version was released, but I wasn’t positive if it is something about the way I updated the app my machine. I’m using a Mac and I am not that familiar with them, so I thought I would let you know anyways.

Thanks,
Rachel

**Comment by jasonblais** [comment]
Thanks @rriitanosri for the reply,

The desktop app release cycle is different from the Mattermost server and actually use different numbering.

So in your case, you'd have two different numbers:

1 - Mattermost Server, which you can find from the three-dotted Mattermost menu > About Mattermost

![image](https://cloud.githubusercontent.com/assets/13119842/21572458/00d700ce-cea7-11e6-9e70-0f7a43d83553.png)

2 - Mattermost Destkop App, which you can find from the destkop app menu bar, under "Help"

![image](https://cloud.githubusercontent.com/assets/13119842/21572454/f7bb8a14-cea6-11e6-940f-1fa613a8722e.png)

**Comment by jasonblais** [comment]
Hence, in your case you saw 3.4 as the Mattermost server was still probably on 3.4.

Note that [Mattermost 3.5.1 contains multiple security updates](https://docs.mattermost.com/administration/changelog.html#security-update), so upgrading to the latest Mattermost server version is recommended. 

[You can find our upgrade guide here](https://docs.mattermost.com/administration/upgrade.html#upgrade-team-edition-to-3-1-x-and-later).
