### ISSUE TITLE
[Help Wanted] Image preview does not work if URL contains a query

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#4816]
#### Summary
When posting an image URL that contains a query, the image preview does not work.
![capture d ecran - 16122016 - 12 30 27](https://cloud.githubusercontent.com/assets/840125/21261427/9b8ce916-c38b-11e6-8490-e0e03b035fb7.png)

#### Steps to reproduce
1. Post `https://about.mattermost.com/wp-content/uploads/2016/01/logo.png` inside a channel.

#### Expected behavior
An image preview should be displayed.

#### Observed behavior
No preview is displayed.

**Comment by lfbrock** [comment]
Thanks @Rudloff - I made a Jira ticket here for the issue: https://mattermost.atlassian.net/browse/PLT-5057

**Comment by khawerrind** [comment]
I am working on it

**Comment by khawerrind** [comment]
Here is the PR https://github.com/mattermost/platform/pull/4869

**Comment by cpanato** [comment]
this ticket can be closed

**Comment by jasonblais** [comment]
Closed via #4869, thanks @khawerrind!
