### ISSUE TITLE
[Help Wanted] File upload isn't aligned with the message box in tablet or mobile view

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4817]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-5000))

File upload isn't aligned with the message box in tablet or mobile view.

![image](https://cloud.githubusercontent.com/assets/13119842/21267652/411cb2e8-c379-11e6-9022-c730599cf124.png)

Note about our different views:
 - **mobile view**, which is shown if the Mattermost window is shrinked to a size similar to mobile.
 - **tablet view**,  which is shown if the Mattermost window is shrinked to a size similar to a tablet (e.g. iPad)
 - **desktop view**, which is matching the experience in full screen mode (or anything bigger than a tablet).

**Comment by bjoernr-de** [comment]
Hi @jasonblais 

I will take care of this issue 😃

**Comment by bjoernr-de** [comment]
<img width="322" alt="screen shot 2016-12-16 at 23 10 33" src="https://cloud.githubusercontent.com/assets/2854699/21280341/b65666dc-c3e5-11e6-9713-88c548476af6.png">

<img width="770" alt="screen shot 2016-12-16 at 23 19 29" src="https://cloud.githubusercontent.com/assets/2854699/21280421/24a8ca3a-c3e6-11e6-92bf-4c3acc0694dc.png">
