### ISSUE TITLE
Submitting a post > 4000 chars is not blocked after a page refresh

### ISSUE THREAD

**Issue by fraziern** [mattermost/platform#4818]
#### Summary
Refreshing the page while drafting a post over 4000 chars resets the max-length error, and posting is not blocked.

#### Repro:

1. Draft a post > 4000 chars without submitting
2. Refresh page (the draft will still be there but the warning is gone)
3. Submit post

#### Observed:
Post is created without error.

#### Expected:
Error should appear and post submission should be blocked.

**Comment by fraziern** [comment]
Taking a look at this.

**Comment by lfbrock** [comment]
Thanks @fraziern for the fix!
