### ISSUE TITLE
[Help Wanted] Emoji Reactions: Always show the usernames who reacted in the tooltip

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#4824]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-5035))

**Observed:** Sometimes the list of users who reacted to a message shows "user" instead of the username. 

<img width="265" alt="screenshot 2016-12-15 10 49 15" src="https://cloud.githubusercontent.com/assets/9354841/21277355/efa59fa8-c3a3-11e6-8b1c-9952e01a81a5.png">

**Expected:** When the tooltip is requested, fetch the usernames so the username can be shown instead of "user".

**Comment by jasonblais** [comment]
@bjoernr-de Wondering if this is something you'd be interested taking a look, given your previous work on emoji reactions?

**Comment by bjoernr-de** [comment]
Thanks @jasonblais - Something I can take a look at but probably not before next month :(

**Comment by jasonblais** [comment]
No worries! Thanks @bjoernr-de!

**Comment by jasonblais** [comment]
Resolved by #5887
