### ISSUE TITLE
"Switch Channels" modal only matches on the channel's leading characters

### ISSUE THREAD

**Issue by benreic** [mattermost/platform#4825]
#### Summary
The "Switch Channels" modal (CMD+K) doesn't do leading wildcard matching on channel names.

#### Steps to reproduce
1. Create a channel named "foo bar".
2. Press CMD+K to open the "Switch Channels" modal.
3. Type "bar" in the modal.
4. Press Enter.

#### Expected behavior
The channel "foo bar" should be listed in the list of channels.

#### Observed behavior
The channel "foo bar" is NOT listed in the list of channels.

#### Possible fixes
Search the entire string for the search term, not just the leading characters of the channel name. This should also apply to Direct Messages as well.

**Comment by lfbrock** [comment]
Hi @benreic - can you check and see what version of Mattermost your server is, by going to the three dots by your profile pic to open the main menu, and clicking "About Mattermost"?

I just tried on v3.5 and on master, and it seems to be working on the set ups I tested with: 
<img width="611" alt="screenshot 2016-12-19 17 56 19" src="https://cloud.githubusercontent.com/assets/9354841/21332115/5cf8a83a-c614-11e6-8f6a-fb121eb7ad57.png">

**Comment by benreic** [comment]
Yep, we're using 3.1, I'll try to get us to upgrade, thanks!
