### ISSUE TITLE
Default channel selected is not the most recently viewed channel

### ISSUE THREAD

**Issue by benreic** [mattermost/platform#4834]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
On startup, the app should take you to the last channel/DM you were most recently in upon last exit.

#### Steps to reproduce
1. Open the app/website.
2. Navigate to a channel that is not the default
3. Close the app/website.
4. Open the app/website, observe that you are not in the most recently viewed channel

#### Expected behavior
I should be taken to the last channel I was viewing in my previous session

#### Observed behavior
There is a default channel that you are taken to upon login each time.

#### Possible fixes
The web app redirects me to a specific channel each time, I suspect it is the first channel that I added when joining my team. The redirect should instead look at a user setting that tracks the most recently viewed channel.

**Comment by lfbrock** [comment]
Hi @benreic - thanks for the report! I think this issue may be fixed by https://github.com/mattermost/platform/pull/4851, will wait to confirm before closing this issue.

**Comment by jasonblais** [comment]
Hi @benreic, when you say "close the app/website" do you mean 1) closing the browser tab or 2) logging out of the site?

If it's 1), what URL do you use to re-open the app?

**Comment by benreic** [comment]
@jasonblais I'm using the desktop app, so in this case I mean quitting the app with CMD+Q. If using the website, I would guess that is analogous to closing the browser tab.

Because I'm using the desktop app I don't use a url to open the app again, I just open the app and select the Mattermost team from the dropdown (I'm only on one team).

**Comment by jasonblais** [comment]
Got it, thanks @benreic! 

In Mattermost 3.6 if you close the app and then re-open it, it will load the team/channel you previously had open. If you sign out before closing the app, then it'll go to Town Square as we don't save that property upon logout.

Closing as completed,
