### ISSUE TITLE
User search does not always return expected results

### ISSUE THREAD

**Issue by Morthy** [mattermost/platform#4847]
#### Summary
When searching for a user by username, the results returned are not always what you would intuitively expect

#### Steps to reproduce
Firstly, create an account called "in.my.control" using a Mattermost instance with a MySQL backend.

Then click on "More" below "Direct messages" in the left navigation bar. 

1. Attempt to search for: "in.my.co"
2. Attempt to search for: "in.my.con"
3. Attempt to search for: "in.my.control"

#### Expected behavior
All searches should return the "in.my.control" user near or close to the top of the results.

#### Observed behavior
1. All users are returned, sorted alphabetically
2. No users are returned
3. No users are returned

#### Possible fixes
At the very least, guarantee that an exact match for username search returns the user. This is especially important for integrations, as without that there is no way for an integration to fetch a user by username via API.

**Comment by lfbrock** [comment]
Hi @Morthy - I think this may need two letter search for MySQL set up to work. Can you try s[etting the minimum search length to 2](https://docs.mattermost.com/install/requirements.html#database-software) on your MySQL database and see if that helps?

**Comment by Morthy** [comment]
Thanks @lfbrock, that did indeed fix the issue :)
