### ISSUE TITLE
[Help Wanted] Replying to a message with >4000 characters should be same behaviour as sending a >4000 message

### ISSUE THREAD

**Issue by yangchen1** [mattermost/platform#4856]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

Details: ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-4976))

Repro:
1. Click the reply button to any message
2. Reply to the message that is over 4000 characters long.
3. Hit Enter, or click "Add Comment"

Observed:
Error message "Comment length must be less than 4000 characters."

Expected:
Comment thread should replicate behaviour when a draft is >4000 characters when sending a message. (display character count when it's >4000 characters, do not allow "save", etc.) See [ticket](https://mattermost.atlassian.net/browse/PLT-4318).

**Comment by fraziern** [comment]
I can take a look.

**Comment by yangchen1** [comment]
Thanks @fraziern :)

**Comment by jwilander** [comment]
Thanks for your help on this @fraziern !!
