### ISSUE TITLE
Change "X new messages below" to "X new messages, including below" 

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4873]
Propose "Help Wanted" 

#### Summary
Change "X new messages below" to "X new messages, including below" 

#### Steps to reproduce
1. Go into a channel that has messages posted since you were last in the channel

![image](https://cloud.githubusercontent.com/assets/177788/21418501/867b352e-c7d6-11e6-9cef-2bde73fd5fae.png)

#### Expected behavior
- Propose using the text ""X new messages, including below" 

#### Observed behavior
- Notice the text "X new messages below" is incorrect, because X refers to total new messages in channel since you last viewed it, not only the messages below

#### Possible fixes
- Propose using the text ""X new messages, including below"

**Comment by lfbrock** [comment]
Closing this, will be addressed by https://github.com/mattermost/platform/pull/4763
