### ISSUE TITLE
Search options does not hide if the search input looses focus

### ISSUE THREAD

**Issue by khawerrind** [mattermost/platform#4882]
**Steps to reproduce:**
Focus the search input then click outside search input

**Observed:**
Search options does not hide

**Expected:**
Search options popover should hide if the search input looses focus

![video](https://cloud.githubusercontent.com/assets/1758838/21450883/70f38570-c91c-11e6-827f-3c2b913c5f4e.gif)

**Comment by esethna** [comment]
Thanks for the report @khawerrind, we have filed a [bug ticket](https://mattermost.atlassian.net/browse/PLT-4984). Closing this to follow on JIRA.
