### ISSUE TITLE
UserAgent.IsMobileApp() applies only to iOS app.

### ISSUE THREAD

**Issue by CometKim** [mattermost/platform#4891]
#### Summary
UserAgent.IsMobileApp() applies only to iOS app. not Android app.

https://github.com/mattermost/platform/blob/master/webapp/utils/user_agent.jsx#L84-L86

#### Expected behavior
It should applies also to Android app.

#### Observed behavior
It applies only IOS app.
So, android app shows download native app link on RHS.

**Comment by esethna** [comment]
Thanks @CometKim, [bug report filed](https://mattermost.atlassian.net/browse/PLT-5094). Closing to track in JIRA.
