### ISSUE TITLE
Code preview block hides "retry" button when the message fails to send

### ISSUE THREAD

**Issue by felko** [mattermost/platform#4902]
#### Summary

Retry button is displayed under the code block when the message fails to be sent.

#### Steps to reproduce

- Send a message with a code (between triple backticks)
- Disconnect your computer from the internet before the message can be sent
- Wait a few seconds until the retry button appears

#### Expected behavior

The button to resend the message should be over the code block.

#### Observed behavior

![](http://i.imgur.com/luFcFEJ.png)

#### Possible fixes

Maybe specify a higher z-index for the retry button.

**Comment by esethna** [comment]
Thanks @felko! [Bug report filed](https://mattermost.atlassian.net/browse/PLT-5095), closing to trackin JIRA.
