### ISSUE TITLE
[Help Wanted] Emoji auto-complete broken on master

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4904]
#### Summary
Emoji auto-complete broken on master

#### Steps to reproduce
Type `:`

#### Expected behavior
Auto-complete for emoji appears

#### Observed behavior
Auto-complete for emoji DOES NOT appear

#### Possible fixes
If I type `:sm` auto-complete does appear, so perhaps an auto-complete PR was merged with poor testing. 

![image](https://cloud.githubusercontent.com/assets/177788/21512093/c81704f0-cc5d-11e6-9ae3-f376013558ae.png)

**Comment by jwilander** [comment]
This is not a bug, it was an intentional decision. https://mattermost.atlassian.net/browse/PLT-4950
