### ISSUE TITLE
Bad view when replay markdown message

### ISSUE THREAD

**Issue by mrash14** [mattermost/platform#4955]
![screenshot from 2017-01-04 18-10-05](https://cloud.githubusercontent.com/assets/6044543/21646103/0e57e89c-d2aa-11e6-8967-42253af69697.png)

#### Summary
I can see '```' sign when I replay markdown message

#### Steps to reproduce
I write code in message and use ``` to markdown it. then I replay it. As you can see in preview of message markdown sign is visible.

**Comment by jasonblais** [comment]
Thanks! Agree the current implementation isn't ideal.

We have an existing ticket to [hide markdown in the "Commented on ...." text](https://mattermost.atlassian.net/browse/PLT-2459). 

Would you or someone you know be interested submitting a fix for it? 

Note that there are some corner cases to consider, such as how headings are considered, or emojis and images. Some suggestions are given [in the JIRA ticket](https://mattermost.atlassian.net/browse/PLT-2459).
