### ISSUE TITLE
[Help Wanted] Editing post, after jumping to it from search sidebar, throws exception.

### ISSUE THREAD

**Issue by debanshuk** [mattermost/platform#4967]
#### Summary
If a post is edited after jumping to it from search sidebar, changes done to the post aren't reflected immediately in the post. 

Found this bug during testing of PR 4923. Refer comment: https://github.com/mattermost/platform/pull/4923#issuecomment-269958189

#### Steps to reproduce
1. Search a post using the search box top right corner.
2. In the search result click on 'Jump' link, so that the post is highlighted in the post list.
3. Edit that post and save the edits.

#### Expected behaviour
Change done in the post should be reflected immediately. 

#### Observed behaviour
Following exception is logged in console and changes done by the edit aren't be reflected in the view.

```
edit_post_modal.jsx:183 Uncaught TypeError: Cannot read property 'focus' of undefined
    at http://i-06b85e16e68fd429f.spinmint.com:8065/static/6.fdb0f4a37cb3b3b35c49.js:3:2799
```
Though the changes are visible after a page refresh.

**Comment by jasonblais** [comment]
Awesome, thanks! Changed this to a Help Wanted issue and created a Jira ticket for it https://mattermost.atlassian.net/browse/PLT-5141

**Comment by debanshuk** [comment]
I am working on this issue.

**Comment by jwilander** [comment]
Thanks for your help on this @debanshuk !
