### ISSUE TITLE
[Help Wanted] Add a spinner to login page after you've clicked the "Sign In" button

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4973]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details**: ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4784))

Repro:

1) Go to the sign in page with email sign in enabled
2) Enter your email and password credentials
3) Click the "Sign In" button

Observed: No feedback to the user, to indicate the sign in process is on-going, which is [against Mattermost UX guidelines](https://docs.mattermost.com/developer/fx-guidelines.html#input-validation).

Proposed Change:

After the user clicks the "Sign In" button, the button
 - text changes to "Sign In ..."
 - a loading spinner is places left of the "Sign In..." text

See example below when System Console configuration settings are changed, where the "Save" button changes to "Saving Config ..." with a loading spinner on the left side.

![image](https://cloud.githubusercontent.com/assets/13119842/21661138/a3774c6a-d2a0-11e6-9f38-2e8b4f59b3ae.png)

**Comment by mikaoelitiana** [comment]
I am willing to work on this one
