### ISSUE TITLE
[Help Wanted] Mark channels unread using ALT-click (resets "New Messages" indicator)

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4992]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: 
 - [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4420)
 - [PR with original implementation](https://github.com/mattermost/platform/pull/3374)

Slack allows you to mark messages as unread by holding down the `ALT` key and clicking on a message.

Useful and could solve use cases such as 
a) [marking messages as read on viewing](https://mattermost.uservoice.com/forums/306457-general/suggestions/13496355-marking-posts-as-read-on-viewing-not-all-in-chann) and 
b) scanning a long thread while getting messages in other channels.

**Details:**
When a user holds down the ALT key and clicks on a message (either posted by the user or another team member),
1) a new messages indicator appears on top of the message
2) the channel name is bolded on the left hand side.
3) there is NO indication/counter of mentions (this feature is strictly for adding an indicator for new messages and we might consider a special case for mentions later)

Finally, if the user navigates to another channel, the new message indicator behaves as usual. That is, all messages will be marked as read after the user navigates back to the channel.

**Special cases:**
When a user holds down the ALT key and clicks on their own message or a system message, labeled [user_message],
1) If no other member has made a post in the channel, no new message indicator appears
2) If other team members have only made a post before [user_message], the new message indicator appears above the latest post from another user, before [user_message]

**Nice-to-have:**
If the user hits [ESC], the new message indicator disappears from the channel. 
1) If the user has a modal open (such as account settings), [ESC] should only close that modal, not the new message indicator. 
2) If the autocomplete list for emojis or mentions is open, either on the center channel or on the right hand side, [ESC] should only close the autocomplete list, not the new message indicator.

**Comment by esethna** [comment]
Reposted
