### ISSUE TITLE
[Help Wanted] `~~` should only show channel autocomplete if a channel name starts with `~`

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4994]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Details**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5341)

#### Summary
`~~` should only show channel autocomplete if a channel name starts with "~"

#### Steps to reproduce
1. Type `~~` 

This is the start of strikethrough formatting in markdown, e.g. `~~strikethrough~~` renders as ~~strikethrough~~

#### Expected behavior
No auto-complete, unless a channel name starts with `~` 

#### Observed behavior
Auto-complete incorrectly displays as follows: 

![image](https://cloud.githubusercontent.com/assets/177788/21708195/d71aaa54-d38a-11e6-958c-ff110f691df1.png)

#### Possible fixes
Require `~` to be at the start of a message or have a space prior before triggering auto-complete

**Comment by bfontaine** [comment]
What if you want to striketrough a channel name? Right now `~~~foo~~` renders as ~\~foo~ but `~~ ~foo ~~` renders as ~\~ ~foo ~\~ (i.e. there’s no striketrough).

(I’m not sure it’s a common need though)

**Comment by lfbrock** [comment]
Fixed in v3.10
