### ISSUE TITLE
Channel search results lag behind search query

### ISSUE THREAD

**Issue by leyanlo** [mattermost/platform#4995]
When searching channels, the search results take a while to populate after typing in the field, which can lead to cases where results are out of sync with the input.

For example, just type a bunch of letters and then quickly delete them. You will see the search result "No more channels to join", when in fact the search field is empty. See GIF:
![no more channels](https://cloud.githubusercontent.com/assets/1285326/21714952/8248c372-d3b6-11e6-92d0-cf6f26425072.gif)

**Comment by jasonblais** [comment]
Thanks for the report! Reproduced on `master` and created a ticket to track: https://mattermost.atlassian.net/browse/PLT-5160

Anyone in the community interested helping investigate a fix?

**Comment by jasonblais** [comment]
Closing the issue to track in JIRA: https://mattermost.atlassian.net/browse/PLT-5160
