### ISSUE TITLE
[Help Wanted] Add a loading screen while switching teams via the teams sidebar

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4997]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5140)

The same loading screen that appears when you open up a team, should appear while switching to another team as the center channel and left-hand sidebar loads.

See attached example

![image](https://cloud.githubusercontent.com/assets/13119842/21719178/3fb3d7ca-d3ea-11e6-884a-f9aae86b5bae.png)

**Comment by mikaoelitiana** [comment]
I want to try this one.

**Comment by jasonblais** [comment]
Yay!! That would be awesome @mikaoelitiana

**Comment by jasonblais** [comment]
Hey @mikaoelitiana, let us know if you need any help.

I would personally love to have this improvement as the experience switching between teams isn't great without the loading screens.

**Comment by mikaoelitiana** [comment]
thanks @jasonblais, I will let you know if I encounter difficulties

2017-01-26 17:19 UTC+03:00, Jason Blais <notifications@github.com>:
> Hey @mikaoelitiana, let us know if you need any help.
>
> I would personally love to have this improvement as the experience switching
> between teams isn't great without the loading screens.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mattermost/platform/issues/4997#issuecomment-275398762


-- 
Mika ANDRIANARIJAONA
mikaoelitiana@gmail.com
+261 33 11 15699
@mikaoelitiana

**Comment by andreistanciu24** [comment]
@jasonblais I took a look at this issue and from my point of view everything is ok. The loading screen appears when you switch teams, it's just too fast sometimes to observe. I attached a print screen while in debugging. 

![image](https://cloud.githubusercontent.com/assets/11387264/22509725/ee207f54-e897-11e6-8e12-549296199a5b.png)

After the channels are loaded for the first time they will be cached, and then the loading screen will not appear because everything loads instantly. When the posts are updated, the loading appears again as per this piece of code from post_view_controller.jsx: 

onPostsChange() {
        const loading = PostStore.getLatestPostFromPageTime(this.state.channel.id) === 0;

Please let me know if it's really an issue

**Comment by jasonblais** [comment]
Thanks @andreistanciu24 for looking into it! This is the flow of screens for me

1. First screen before team switching
![image](https://cloud.githubusercontent.com/assets/13119842/22510123/bc9dbf2a-e85e-11e6-8c9c-01e5ac33cfcb.png)

2. After clicking team icon, team name changes and channel header disappears. Old content appears in center channel. Channels aren't updated in sidebar.
![image](https://cloud.githubusercontent.com/assets/13119842/22510140/ca735a9c-e85e-11e6-844b-79cd532b5e93.png)

(Channels update fast as you said but on larger teams it can take a long time before the channel sidebar is updated)

3. Loading screen appears while channels have updated in the sidebar
![image](https://cloud.githubusercontent.com/assets/13119842/22510277/601423e2-e85f-11e6-82e7-e70ad6b275ae.png)

4. Team has loaded
![image](https://cloud.githubusercontent.com/assets/13119842/22511140/a5753310-e862-11e6-8da1-02715f81cdd7.png)

---------------

Instead, what I basically envision is skipping the second screen and instead immediately clear the channel sidebar and center channel when you click the team icon and the page is loading.

After clicking team icon:
 1. Team name in top left corner updates as it does now; loading screen appears in the center channel clearing the content; channel sidebar cleared 
 2. Channels appear in the sidebar after being loaded
 3. Center channel content (including channel header, search bar, etc.) appears after page has loaded

**Comment by andreistanciu24** [comment]
Alright, I got it now. Thanks for clearing that up

**Comment by jasonblais** [comment]
Sure thing! Thanks for taking a look at this @andreistanciu24!

**Comment by mikaoelitiana** [comment]
@jasonblais what do you think is the best approach for that? I am thinking of editing the `onClick` function when `TeamButton` link is clicked and there I will see how to set postList to `null`. This should make the loading appear.

**Comment by mikaoelitiana** [comment]
I have made a pull request. I hope this is a correct way to solve this. Here is what it looks like : 

![fevr -07-2017 17-41-05](https://cloud.githubusercontent.com/assets/674667/22695836/3f584252-ed5d-11e6-90cb-3c63e22c4e27.gif)

**Comment by jasonblais** [comment]
That looks pretty good! I'll check it out with #5325 +:1:

**Comment by mikaoelitiana** [comment]
This issue should be reopened after revert. Can someone do that please?

**Comment by jasonblais** [comment]
Reopened :)

**Comment by mikaoelitiana** [comment]
thanks @jasonblais, I will re-work on this
