### ISSUE TITLE
slash command replies should indicate private visibility

### ISSUE THREAD

**Issue by joernhees** [mattermost/platform#4998]
#### Summary
Currently, with (custom) slash commands it's not obvious to me who can see the results...

#### Steps to reproduce
- type `/shortcuts`
- type `/shrug`

Custom slash command example: With gitlab slash command integration
- type `/gitlab help`
- type `/gitlab issue show 1`

#### Expected behavior
A clear indication who can see the reply message...

#### Observed behavior
Currently, i struggle to immediately find out who sees what message. For most builtins, i guess that `System` messages aren't seen by others, but messages in my name are... With custom slash commands however, it's way less obvious who sees what.

#### Possible fixes
For messages that only i can see, add a small textual assurance like `Only you can see this` in the message header (e.g., between name and timestamp).

**Comment by jasonblais** [comment]
Thanks @joernhees, that's a good point  -- [queued for our UX team to discuss](https://pre-release.mattermost.com/core/pl/ymo66dzjcpd9dpi5wpb6csgiqe).

You're welcome to join and participate in the discussion.

**Comment by jasonblais** [comment]
Hey @joernhees, we created a [JIRA ticket to track this](https://mattermost.atlassian.net/browse/PLT-5256).

Our UI designer will help created mock ups of adding `Only visible to you` message when it's only you who can see it. 

The next steps is to try a few designs to see which one works best across all platforms (desktop, tablet, mobile).
