### ISSUE TITLE
[Help Wanted]: In mobile web view, the send icon should show as disabled until there is a valid message in the input box

### ISSUE THREAD

**Issue by it33** [mattermost/platform#5006]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

#### Summary
On mobile web view send icon (airplane) should show as disabled until there is a valid message in the input box that can be sent. 

#### Steps to reproduce
View channel on mobile web with no input in input box

#### Expected behavior
Send button disabled (greyed out), since it can't be used.

#### Observed behavior
Send button is enabled, even if it can't be used. 

![image](https://cloud.githubusercontent.com/assets/177788/21733854/6f8ef5b2-d415-11e6-8dd5-9c6bff3fd723.png)

**Comment by jasonblais** [comment]
Closed via #5214, thanks @saturninoabril!
