### ISSUE TITLE
People get logged out on their PCs and can't login, login using Android app is still possible

### ISSUE THREAD

**Issue by Lehmax** [mattermost/platform#5009]
#### Summary
Two people of my team got logged out on their PCs without a warning. When they try to login again, they get the following message: "We couldn't find an existing account matching your credentials."

#### Steps to reproduce
I have no idea, I have not figured out a pattern yet. They are trying to log in through their browsers, not the app. Our server is running team mode Enterprise Edition 3.5.1 with postgres.

#### Expected behavior
People should not get logged out randomly and should be able to sign in if it happens.

#### Observed behavior
 I get the following error in the log:
`[EROR] /api/v3/users/login:SqlUserStore.GetForLogin code=400 rid=hbfnkeo8p3bm5ntiwz5r6jcbky uid= ip=[their IP] We couldn't find an existing account matching your credentials. This team may require an invite from the team owner to join. [details: ]`

They can temporarily fix it by creating a new account with a new email, but after a few days they were logged out again. On the Android app they were still logged-in.

**Comment by jasonblais** [comment]
Thanks @Lehmax for the report,

may I ask a few questions about your configuration to help us troubleshoot the issue and see if we can find any patterns?

1) In **System Console > Security > Sessions**, what are the values for 
   - Session length AD/LDAP and email (days):
   - Session length mobile (days):
   - Session length SSO (days):
   - Session Cache (minutes):

2) What authentication method are the two accounts using? Sounds like email/password?
3) Which browsers are the two users on?
4) Would you be able to say if the number of days between account creation and being logged out was the same for the users?
5) Are either one imported from Slack?

**Comment by Lehmax** [comment]
1. 
- 30
- 30
- 30
- 10

2. Email/password.

3. They're using Firefox 50.1.0 and have also tried Internet Explorer 11. I told them to try Chrome, but I doubt it'll be any different.

4. I'm can't say it for sure, but it seems like it.

5. I haven't imported anything from Slack.

**Comment by Lehmax** [comment]
After updating the server to 3.6.1 one person can login again without problems. I haven't heard from the other user yet. 
But now a new person can't log in on PC and gets the same message. He can't confirm if he's logged in on the Android app because he never used it.

**Comment by jasonblais** [comment]
Hmm, that's interesting.

Can you try the following:

1) Go to System Console > TEAMS
2) Click the "+" icon next to TEAMS on the left-hand sidebar and from the **Select Team** dialog, choose the team your user(s) belong to
3) A new section for that team should appear on the left-hand side below "TEAMS" heading. Click "Users"

![image](https://cloud.githubusercontent.com/assets/13119842/22176922/5972094e-dfe2-11e6-8ba4-d1b7107e0330.png)


4) Find the user who is unable to login, and confirm that their **Sign-in Method** is Email
5) From the dropdown menu next to the user, choose "Reset Password"

![image](https://cloud.githubusercontent.com/assets/13119842/22176932/915bc796-dfe2-11e6-83ad-b394a5b2e9cf.png)


6) Ask the user(s) to try and log in with the new password

After the above steps, is the user able to log back in to Mattermost from their PC? If not, can they try both Firefox and Chrome just so we can eliminate browser-related issues.

**Comment by Lehmax** [comment]
It's working for him now, thanks for the help.

**Comment by jasonblais** [comment]
Glad to hear!
