### ISSUE TITLE
Create channel name should accept non-English characters for URL.

### ISSUE THREAD

**Issue by andrewwutw** [mattermost/platform#5010]
Mattermost version : 3.5.1

When I use "Create new channel" function, English characters in name field can be auto converted into URL name, but non-English characters (e.g. : "é") can't not be converted into URL and will be skipped.

If I input "Résumé" in the channel name, the URL will be "/rsum", and "é" is skipped.

![new-channel](https://cloud.githubusercontent.com/assets/4443713/21749341/0a7003f0-d5d8-11e6-9fb3-5eaafe68c8c3.png)

I wish those non-English characters can be included in URL, like how Wikipedia does. Wikipedia supports non-English character title pages by encoding them in UTF-8.

E.g. : URL of  Résumé page in Wikipedia is : https://en.wikipedia.org/wiki/R%C3%A9sum%C3%A9

("é" is encoded into %C3%A9)

![wikipedia](https://cloud.githubusercontent.com/assets/4443713/21749346/1b27df2e-d5d8-11e6-88d3-6413387075f2.png)

There is a online URL encode/decode tool : http://www.url-encode-decode.com/

This function is important for non-English users. If a Chinese language user wants to create a channel name in Chinese, all Chinese characters will be skipped, and URL will become empty. The user has to edit URL manually, translate Chinese channel name into English, which is very troublesome.

**Comment by DrLynix** [comment]
I think this is a bad idea as channel id should remain readable.

A better solution, I think, would be to strip accents automatically, thus giving "resume" in this case.

**Comment by andrewwutw** [comment]
But many languages, like Chinese/Japanese/Korean/Russian, can't be supported by only stripping accents.

I believe most modern web browser can auto recognize percent-encoded UTF-8 URLs and display them correctly in address bar and status line. So they are at least still readable in browsers.

Address bar :

![addr-bar](https://cloud.githubusercontent.com/assets/4443713/21751059/99798d14-d5fb-11e6-81a8-afb87d11b695.png)

Status line :

![status-bar](https://cloud.githubusercontent.com/assets/4443713/21751060/9d956d96-d5fb-11e6-9c72-1da0c5d1babe.png)

But, of course, if you copy those URLs and paste into other non-browser program, like email clients, then the URLs will become ugly. 😔

Or, I have another idea. When a user is inputting a new channel name, which contains any "invalid" character, mattermost can failback to generate URL name in non-repetitive sequential numbers, like /00001, /00002, and so on.

**Comment by jasonblais** [comment]
Thanks @andrewwutw , appreciate your feedback.  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by andrewwutw** [comment]
@jasonblais OK, I posted the request in https://mattermost.uservoice.com/forums/306457-general/suggestions/17694802-channel-url-should-be-percent-encoded-in-utf-8-for

**Comment by jasonblais** [comment]
Thanks @andrewwutw!
