### ISSUE TITLE
Members view bug on mobile

### ISSUE THREAD

**Issue by S6066** [mattermost/platform#5011]
http://i.imgur.com/WLvFtpM.jpg
MM 3.6.0-rc2, Team Edition on Android 5.1 (Lollipop)  
I have this bug when checking members and scrolling down.  
Also, why is there 2 scrollbars ?

**Comment by jasonblais** [comment]
Thanks @S6066, can you help provide the exact reproduction steps to help us with the invesigation?

For instance, which channel member list does this reproduce (all of them or only certain ones)?

Also, which Android App version are you using?

**Comment by S6066** [comment]
I have to click the three dots  at the upper right corner then click view members  It happens on every channels  I use the lastest version I found on the play storeLe 9 janv. 2017 06:55, Jason Blais <notifications@github.com> a écrit :Thanks @S6066, can you help provide the exact reproduction steps to help us with the invesigation?
For instance, which channel member list does this reproduce (all of them or only certain ones)?
Also, which Android App version are you using?

**Comment by jasonblais** [comment]
Thanks! Reproduced on Safari and IE11 as well, bug report here: https://mattermost.atlassian.net/browse/PLT-5191

**Comment by jasonblais** [comment]
Thanks again @S6066 for the report! This is now resolved for 3.6
