### ISSUE TITLE
[MM 3.6 RC2] Emoji size 

### ISSUE THREAD

**Issue by DrLynix** [mattermost/platform#5012]
#### Summary
I recently switched my team Mattermost to the 3.6 RC2 version (great job by the way) and the only drawback we noticed is the emoji size in messages, which decreased from 3.5.  
(I'm on Mattermost Desktop 3.5 by the way, but it is the same on a web browser).

#### Steps to reproduce
Simply post a message containing emoji.

#### Expected behavior
Emoji size is big enough to be pleasant.

#### Observed behavior
It is not (look at the "mouth" of the sad emoji).  
![image](https://cloud.githubusercontent.com/assets/3002461/21749688/f86cd496-d5a3-11e6-9a35-28f33ea881e3.png)

**Comment by jasonblais** [comment]
Thanks @DrLynix for the feedback!!

Would you be interested joining our public [Mattermost community instance](https://pre-release.mattermost.com/core) and join our UX design channel? A note was just posted related to this and would love to have you participate in the discussion - [here would be a link to the discussion thread](https://pre-release.mattermost.com/core/pl/gx1pdouwftd4iytkubdu5botbr).

**Comment by DrLynix** [comment]
Thanks for the invite, I'm part of the discussion now :)

**Comment by jasonblais** [comment]
Hey @DrLynix, we created a ticket in JIRA to track: https://mattermost.atlassian.net/browse/PLT-5220

**Comment by jasonblais** [comment]
@asaadmahmood has started progress on it and an update will soon be submitted to the `master` branch.

The improvement should be available in Mattermost 3.7.

Thanks all!
