### ISSUE TITLE
[MM 3.6 RC2] Emoji autocomplete failure

### ISSUE THREAD

**Issue by DrLynix** [mattermost/platform#5014]
#### Summary
When typing an emoji with +: or :, some emoji are not in the list.

#### Steps to reproduce
Try to type some emoji as `:squirrel:` or `:tshirt:`
 
#### Expected behavior
Emoji autocompletion proposes to complete those emoji.

#### Observed behavior
It doesn't, for only some emoji though.

**Comment by jasonblais** [comment]
That is interesting, created a JIRA ticket for it. Thanks! https://mattermost.atlassian.net/browse/PLT-5203
