### ISSUE TITLE
Email should include plain text MIME part

### ISSUE THREAD

**Issue by bgamari** [mattermost/platform#5016]
#### Summary
Email notifications only appear to include a `text/html` part, which are unreadable in some mail clients.

#### Steps to reproduce
1. Enable email notifications for your account
2. Receive a Mattermost message
3. Check email in non-HTML supporting mail client (I'm using `notmuch` in `emacs` here)

#### Expected behavior
The mail message contains a readable, plain text message.

#### Observed behavior
Emacs will attempt to render the HTML, but do so badly, resulting in very unreadable content.

#### Possible fixes
Include a legible plain text MIME part in notification messages alongside the existing HTML part.

**Comment by jasonblais** [comment]
We have an existing ticket [marked for accepting pull requests](https://mattermost.atlassian.net/browse/PLT-1015).

I agree Mattermost should support plain text versions for emails -- not sure if anyone in the community was interested to work with us on it?

**Comment by jasonblais** [comment]
Closing for now and we can track in Jira https://mattermost.atlassian.net/browse/PLT-1015

If anyone is interested helping out, let us know!

**Comment by alexthemitchell** [comment]
+1: I wouldn't have commented, but I cannot see your progress in JIRA so I wanted to make clear that this is a desired feature.

**Comment by jasonblais** [comment]
Thanks @alexthemitchell! Unfortunately our JIRA project is down, but this PR was actually merged a few days ago and available in Mattermost v4.2 (release date Sept 16th): https://github.com/mattermost/platform/pull/5698
