### ISSUE TITLE
Support Slack buttons format in Mattermost webhooks

### ISSUE THREAD

**Issue by it33** [mattermost/platform#5020]
Request from community on action button for "Slack compatibility". Typically we have a [feature ideas](https://www.mattermost.org/feature-ideas/) process, but there's a point of view here we're breaking compatibility (Slack added this feature not too long ago). 

Is anyone from the community interested in implementing this if we created a "Help Wanted" ticket? 

Since Mattermost supports markdown, you can create a button already by doing an image with a hyper link: e.g. clicking on below image goes to defined URL: 

```
[![button](http://www.presentationpro.com/images/product/medium/slide/PPP_CGENE_LT3_Presentation-PowerPoint-Slide-Graphic_Push_Button_Up.jpg)](https://mattermost.com)
```

[![button](http://www.presentationpro.com/images/product/medium/slide/PPP_CGENE_LT3_Presentation-PowerPoint-Slide-Graphic_Push_Button_Up.jpg)](https://mattermost.com)

But if you were to point a pre-existing Slack integration at Mattermost it doesn't work yet. 

Original feedback: 

https://twitter.com/ehrnst/status/818440569177460736

![image](https://cloud.githubusercontent.com/assets/177788/21771233/53921056-d63b-11e6-97d6-78a58b93622b.png)

Note: We should document how to create a button in markdown, it's easy but non-obvious: https://github.com/mattermost/docs/issues/771

**Comment by cpanato** [comment]
I tried this on the current test server and the button didnt appear to me.

**Comment by it33** [comment]
Realizing what's requested is more than a clickable image, closing this ticket and requesting a feature idea be posted so it can be discussed, upvoted and prioritized: https://twitter.com/mattermosthq/status/818500648694063104

PS: We're at [99 feature ideas from community that have been implemented](https://mattermost.uservoice.com/forums/306457-general/status/1588363). Looking forward to exceeding 100 :)
