### ISSUE TITLE
Wrong Emoji Substitution

### ISSUE THREAD

**Issue by jeanetienne** [mattermost/platform#5030]
#### Summary
When typing some emojis with a generic (nonhuman) appearance, the image displayed is using a specific human skin tone. 

This can have far reaching interpretation: 
- When typing a 👍, in the chat window, a 👍🏻 is actually displayed. Does that mean that the default "thumbs up" is a light skinned person?
- When typing a 👳, in the chat window, a 👳🏽 is actually displayed. Does that mean that the default "person wearing turban" is a medium skinned person?
- When typing a 👸, in the chat window, a 👸🏼 is actually displayed. Does that mean that the default "princess" is a medium light skinned person?

This can lead to polemical and controversial interpretation of this piece of software behavior.

#### Steps to reproduce
Using Mattermost 3.5.0  (dev)
Build Date: Fri 18 Nov 2016 00:15:08 UTC
Build Hash: 3f19ccf1b1a6efdcc990cf8a0270ec4ffc0c6e22
Running on MacBook Pro (Retina, 15-inch, Mid 2015) - OS X El Capitan 10.11.6 (15G1212)
Running in Safari 10.0.2 (11602.3.12.0.1)

In a chat window type in 👍, the actual image shown is 👍🏻.

#### Expected behavior
As recommended by the Unicode:
> General-purpose emoji for people and body parts should also not be given overly specific images: the general recommendation is to be as neutral as possible regarding race, ethnicity, and gender. Thus for the character U+1F777 CONSTRUCTION WORKER, the recommendation is to use a neutral graphic (with an orange skin tone) instead of an overly specific image (with a light skin tone).

Here: http://www.unicode.org/reports/tr51/#Design_Guidelines

An emoji, like any other character, shouldn't be replaced by another, even if it's considered a variant of said character.

#### Observed behavior
Some emoji characters are replaced with a different skin tone variant.

#### Possible fixes
- Not try to replace emojis with images, and let the OS of the running platform handle the rendering of the character
- Be exhaustive and replace all emojis, and honour the skin tone modifiers as well as the lack of said modifier.

**Comment by andyboyd** [comment]
Github does it right. The reaction thumbs up is yellow!

**Comment by jasonblais** [comment]
Thanks @jeanetienne and @andyboyd for the feedback! 

I've queud this item for our [Mattermost UX design channel to discuss](https://pre-release.mattermost.com/core/pl/rmb4pjmyrjbai8uhge9xndbnmw) -- the site is public and everyone can join, if you're interested :)

**Comment by jeanetienne** [comment]
Thanks @jasonblais !

**Comment by jasonblais** [comment]
Hey @andyboyd and @jeanetienne -- we discussed and agree we should be using neutral emoji.

As for the possible fixes, we'd recommend not going with emojis specified by the OS as that can sometimes cause rendering issues. So we're looking at doing an exhaustive replace of the emojis.

I'm wondering if you had already compiled a list of emojis that should be changed, or whether the ones you referenced were just examples?

**Comment by jeanetienne** [comment]
@jasonblais No, unfortunately I haven't compiled an exhaustive list of emojis. But it seems to come from the folder `/static/emoji/`, which I couldn't find on the repo, so I assume it's generated during some sort of install script? It appears that instead of writing the actual character, an image is used instead (for example for 👸), and it comes from the aforementioned folder.

More surprisingly, in the case of 👍, it is not replaced by an image, but by the "white skin color tone" emoji, so in this case there's definitely some code somewhere that decided that the neutral emoji should be replaced by the "white skin color tone" one?!?

It's easy to investigate, in a random channel just type 👍 or 👸 and then use your browser's "inspect element" kind of dev tool to see what is actually shown in the channel.

Hope this helps!

**Comment by jasonblais** [comment]
Thanks for the help @jeanetienne! I'll take a look and create a ticket to change this so we use neutral emoji instead

**Comment by jasonblais** [comment]
@jeanetienne JIRA ticket is here to track: https://mattermost.atlassian.net/browse/PLT-5316

If anyone in the community is interested helping with an update, let us know!
