### ISSUE TITLE
Channel does not auto-refresh for alerts to webhook if webhook creator leaves the team

### ISSUE THREAD

**Issue by rantheman** [mattermost/platform#5033]
#### Summary
If the user who created the webhook leaves the channel and team, the subsequent alerts sent to this webhook will only be visible after manual refresh/switching to another channel and back. (tested both in browser and with application)

#### Steps to reproduce
* Create a webhook for a channel
* Leave the channel and team
* Send alerts to this webhook
Mattermost Webhook Related Settings
----------------
        "EnableIncomingWebhooks": true,
        "EnableOutgoingWebhooks": false,
        "EnableCommands": true,
        "EnableOnlyAdminIntegrations": false,
        "EnablePostUsernameOverride": true,
        "EnablePostIconOverride": true,
----------------

#### Expected behavior
* Channel should auto-refresh and the new alert should be automatically visible

#### Observed behavior
* The newly sent alert is not visible until the channel is manually refreshed or until we switch to another channel and back
* Mattermost writes the following lines to its log for such alerts
[EROR] Post user_id not returned by GetProfiles user_id=XXXXXXX

**Comment by jasonblais** [comment]
Thanks @rantheman for the report! I created a bug report for us to track: https://mattermost.atlassian.net/browse/PLT-5284

Would anyone in the community be interested helping with a fix?

**Comment by jasonblais** [comment]
Fix submitted here: https://github.com/mattermost/platform/pull/5119

**Comment by jasonblais** [comment]
Thanks @rantheman for the report!
