### ISSUE TITLE
Code block hide first line

### ISSUE THREAD

**Issue by T3rm1** [mattermost/platform#5060]
Text on the same line after the first three backticks is not shown in chat. Only second line and onwards are shown.

Version 3.6.0

**Comment by jasonblais** [comment]
Thanks @T3rm1 for the report,

can you help
1) give the sample text you tried to post
2) screenshot of what was posted
3 browser (e.g. Chrome, Firefox, ...) and operating system (Windows, Mac, Linux) you reproduced it?

**Comment by T3rm1** [comment]
This is not browser related.
http://prnt.sc/dv5kxm

**Comment by jasonblais** [comment]
Thanks @T3rm1, that's helpful!

We support syntax highlighting for specific programming languages by allowing users to type the language after the ``` at the beginning of the code block.

For example, to highlight Go, one can type

```
``` go
package main
import "fmt"
func main() {
    fmt.Println("Hello, 世界")
}
`` `
```

which will output
![image](https://cloud.githubusercontent.com/assets/13119842/21933735/99d33644-d974-11e6-9705-90128e6fe273.png)

We could consider making an improvement where if the text included in the first line following a backtick isn't a supported language, then it's also shown in chat.

**Comment by T3rm1** [comment]
Ah, I see. Thanks for the fast response.
