### ISSUE TITLE
Remove background color behind your own messages

### ISSUE THREAD

**Issue by leyanlo** [mattermost/platform#5072]
Proposed Help Wanted

#### Summary
Background color behind your own messages provides no value and should be removed.

#### Steps to reproduce
Send a message in a channel

#### Expected behavior
Message sent with format matching all other messages in channel

#### Observed behavior
Message has background of #E9EBEE

![image](https://cloud.githubusercontent.com/assets/1285326/21979380/87940d70-db93-11e6-92d3-e543a3ff16ea.png)

#### Possible fixes
Remove background

**Comment by esethna** [comment]
@leyanlo the background color is intended to help you scan a channel for your own messages, since you have additional controls (Edit, Delete) on messages you send versus messages sent by others.

I did notice that there is an inconsistencey where the background color does not appear in the right-hand side when viewing a comment thread. I will queue for our UX meeting to discuss this and the value of the background.

**Comment by esethna** [comment]
Hi @leyanlo, we've [disucssed in the UX meeting](https://pre-release.mattermost.com/core/pl/bgnj4oft67femk6siwwpqtf9hr) and think that keeping the background color to differentiate your own messages is consistent with other platforms such as Skype, WhatsApp and Facebook. The inconsistency of not having the background in the RHS is [something we are going to look into](https://mattermost.atlassian.net/browse/PLT-5377).

**Comment by wintah** [comment]
I realize this is closed, but as I was trying to theme my Mattermost client to a bit prettier look, I failed, as changing the background color of your own messages is not one of the options. At least the option is not visible. If it was, changing the background color would allow the user to a) pick a nice color (or mimic a chat client such as Skyper with same colors user is used to) b) if really wanted, set the color to the same value as the "centerChannelBg", which would solve the request here, for the users that prefer more ascetic view.

**Comment by andrewleith** [comment]
I also see no value in having my own messages highlighted.  If I need to find my own messages, I will look for my username/profile pic.  My team and I find this quite distracting.  

+1 on removing the shading entirely.

**Comment by siddhanathan** [comment]
FWIW, I hate this feature. Would be nice if I had the option to disable this.

**Comment by arjitc** [comment]
+1 an option to change the colour under the themes option would be very good.

**Comment by samholst** [comment]
This feature is really distracting and destroy the UX look of the app. There should be a option to turn it off because the grey is quite ugly and unneeded.

**Comment by terjanq** [comment]
I agree, this is awful

**Comment by lfbrock** [comment]
Hi @samholst and @terjanq - we are planning on working on overhauling the Mattermost UI later this year and will take this into consideration. 

(Timeframe is starting on the design phase over the next couple months, and implementation phase near the end of the year).

**Comment by acataluddi** [comment]
A quick fix to remove the gray background from your own messages (thanks to [Jānis Rozefelds](https://mattermost.uservoice.com/forums/306457-general/suggestions/16635304-disable-highlighting-of-own-messages)):

1. Open the file `/opt/mattermost/client/root.html` and add inside the `<style>...</style>` block, at the end:
```css
.current--user .post__content .post__body {
background-color: transparent !important;
}
```
2. Save and enjoy.

Keep note of this modification as you'll need to apply again after a server update.

Regards,
Adriano

**Comment by Tragen** [comment]
You forgot to do it with image uploads also
`
.file-view--single
{
    background-color: transparent !important;
}
`

If you want to have a line separator between users like in Discord, you can add
`
.post.other--root
{
    border-top-style: solid !important;
    border-top-width: 1px !important;
    border-top-color: rgb( 77, 77, 77 ) !important;
}
`

and if the color of the scrollbar disturbs you also, use this (with your own colors)
`
.post-list-holder-by-time
{
    scrollbar-width: thin !important;
    scrollbar-color: rgb(111,111,111) rgb(77,77,77) !important;
}
`

**Comment by omaximenco** [comment]
@acataluddi @Tragen thank you guys, this background color makes the whole application ugly, pretty much to the point of switching to Slack :)

**Comment by Djyp** [comment]
The last comment from a member of the mattermost team is more than a year old.
Today I installed a fresh Mattermost server and almost decided to swtich to Rocket Chat because of this feature (and a few tiny others, like read-only channels, and the ordering in the sidebar).
Saying that other services do it is not an argument, it is as silly as any argument saying others are doing something. When you have the same UI as whatsapp or facebook messenger the background difference is great but not with the current UI of Mattermost.

Are you planning to add an option to de/activate this feature ?
Are you planning on having the themes decide to implement this feature ?

**Comment by cadavre** [comment]
Mattermost, maybe just add it to custom theme params, so simple to do.

**Comment by khurshidindia3-arch** [comment]
![Image](https://github.com/user-attachments/assets/7e3335ac-cf9a-4c73-aef5-7d064496b195)

**Comment by khurshidindia3-arch** [comment]
![Image](https://github.com/user-attachments/assets/b2125f6e-a6bb-4a9d-bc2b-4107902b5f94)

**Comment by khurshidindia3-arch** [comment]
![Image](https://github.com/user-attachments/assets/1cf0e51d-ede7-4ae5-ae4a-200846b54df7)remove the colour
