### ISSUE TITLE
Timestamps should be permalinks

### ISSUE THREAD

**Issue by leyanlo** [mattermost/platform#5073]
Proposed Help Wanted

#### Summary
Timestamps on messages should be permalinks, and permalink should be removed from the ellipsis menu.

#### Steps to reproduce
View any message in a channel

#### Expected behavior
Timestamp should be behave like a <a> hyperlink, which changes the cursor to pointer and underlines on hover. It could also reveal a popover with help text to inform users of the permalink as Slack does. Also, Permalink should not be in the ellipsis menu.

#### Observed behavior
Timestamp behaves like plain text.

![image](https://cloud.githubusercontent.com/assets/1285326/21979615/8fd4a78c-db94-11e6-9406-ed3fcd09e4e7.png)

#### Possible fixes
Change to <a> tag and remove Permalink from ellipsis menu (which may make ellipsis menu obsolete in some cases). Extra credit for the popover with help text.

**Comment by esethna** [comment]
Hi @leyanlo, I may be misunderstanding but it looks like the slack link on the timestamp opens the message in the archive view rather than opening a pop-over with the link. The "Copy link" option is also available from the ellipse menu in Slack. Given that we are trying to be slack compatible I think this is functionality we retain in the ellipse menu.

**Comment by leyanlo** [comment]
Ah ok didn't realize Slack also had a copy link option in their dropdown.

Still would like the timestamp to also be a hyperlink to the permalink, as it is with Slack, Facebook, and Twitter. It's a very common pattern and strange that Mattermost does not behave the same way.

**Comment by esethna** [comment]
Hi @leyanlo, can you please help me understand the value of making the timestamp link to the archive view? I'm just trying to think through the use case in which this would be helpful.

**Comment by leyanlo** [comment]
The value is that it saves time for users who expect this functionality--they can access the permalink in one click instead of two. This UX pattern is in many apps. Even this GitHub thread follows the same pattern.

![image](https://cloud.githubusercontent.com/assets/1285326/22128470/99e8d7de-de55-11e6-942f-a2a81eb8fd6d.png)

**Comment by it33** [comment]
Having timestamp as some form of permalink is common in developer-centered apps, like GitHub, Slack and Discourse. 

For non-developers, I think it might make sense to keep the permalink option from the [...] menu to meet our "fast, obvious, forgiving" principle. 

Propose focusing this change on just adding the same permalink we have now to timestamp? 

@esethna if UX is okay with this, propose opening a new Help Wanted ticket so contributor doesn't get lost in this thread?

**Comment by esethna** [comment]
Thanks @leyanlo, I've [queued this for our UX meeting](https://pre-release.mattermost.com/core/pl/exdnn8jeqjrz3fb6w7jfagpsph) and I will circle back to create a help wanted ticket if approved. Thanks!

**Comment by esethna** [comment]
Hi @leyanlo, UX team discussed and we agree with the change. I'm going to close this issue as I've opened a new help wanted issue here: https://github.com/mattermost/platform/issues/5183
