### ISSUE TITLE
[Help Wanted]: Remove redundant mobile web search hint popover 

### ISSUE THREAD

**Issue by leyanlo** [mattermost/platform#5074]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

#### Summary
On mobile web, in the search page there is a popover with help text that is redundant with the help text underneath that says the same thing.

#### Expected behavior
Remove the "Search options" popover when the help text is diplayed underneath on the search page. The help text appears when the user is in the center channel and presses the search icon.

Note: the popover should not be removed when a comment thread is opened and the user clicks in the search bar.

![mobile web search hint popup](https://cloud.githubusercontent.com/assets/1285326/21979798/635a1cf4-db95-11e6-881c-47939eb17b30.png)

**Comment by esethna** [comment]
Thanks @leyanlo! Help wanted issue created, please let us know if you'd like to work on this.

**Comment by cpanato** [comment]
pr: https://github.com/mattermost/platform/pull/5137
