### ISSUE TITLE
Mobile web info pages are redundant

### ISSUE THREAD

**Issue by leyanlo** [mattermost/platform#5075]
Proposed Help Wanted

#### Summary
There are two info pages that appear on mobile web that are redundant.

#### Steps to reproduce
On mobile web, to see the dark info page, tap the (i) on the top right of the page:
![image](https://cloud.githubusercontent.com/assets/1285326/21979951/faa8eeaa-db95-11e6-8a3b-a719c84bf135.png)

To see the light info page, tap the name of the channel and tap View Info:
![image](https://cloud.githubusercontent.com/assets/1285326/21980001/3a5a78ac-db96-11e6-8bbc-61f81d0ff42c.png)

#### Expected behavior
These two paths should lead to the same page. Probably the light info page since that seems more complete than the dark version

#### Observed behavior
Saw two different pages.

#### Possible fixes
Consolidate pages.

**Comment by esethna** [comment]
Thanks @leyanlo, I've [queued for discussion](https://pre-release.mattermost.com/core/pl/oiuc96jy4prnxkg55oe7noro3a) in our UX meeting. I will circle back with the decision.

**Comment by esethna** [comment]
Thanks @leyanlo, we've discussed this and the decision is to remove the info icon as you can see the header in the View Info modal. Space in the channel header is limited and we don't believe the info icon is useful on mobile. 

We have been woking on a new react native mobile app and it will not include the info icon. Thanks for the suggestion!
