### ISSUE TITLE
Download file should default to last used directory

### ISSUE THREAD

**Issue by fmp777** [mattermost/platform#5081]
Every time you download a file from a chat, it defaults to the root directory (as in highest level dir).  All operating systems actually have a default Download folder that could be used when no other is known, but then after a download to a user specified directory, the next download should default there as well.

Either way, shouldn't default to the root directory, since NOBODY ever wants to save files there.

**Comment by esethna** [comment]
Sorry @fmp777, I'm not able to reproduce this. What browser are you using, it may be a browser setting? When I download a file from Mattermost on Chrome it saves the file in my downloads folder, see browser setting:

![image](https://cloud.githubusercontent.com/assets/14333569/22081465/e9a7131a-dd80-11e6-98ef-cde5e7a78033.png)

**Comment by fmp777** [comment]
sorry i dont use browser-based mattermost - maybe i'm in the wrong place?  this was tested on mac app  (which is little more than a browser wrapped app)

**Comment by esethna** [comment]
Thanks for the clarification, yes you can report this on the [desktop repo](https://github.com/mattermost/desktop/issues)
