### ISSUE TITLE
Re-send messages in correct order

### ISSUE THREAD

**Issue by DeepSnowNeeL** [mattermost/platform#5089]
#### Summary
When you send messages and you have problems with your internet connection, the messages are queued up to be re-send but they re-send in the incorrect order.

#### Steps to reproduce
Just send messages, get lags or disconnect your ethernet cable for few seconds.
My way to reproduce it is to use a vpn inside my company proxy so.. Maybe something like Network Link Conditioner or Dummynet

#### Expected behavior
That the messages are being sent in the correct order

#### Observed behavior
The messages are sent in random order, I guess they all retry and the first one to pass is sent.

#### Possible fixes
No time to look your codebase sorry :) 

Thanks for fixing that in future versions !

PS Version: 3.5.0

**Comment by esethna** [comment]
Sorry @DeepSnowNeeL, I'm not sure how to repro your issue. If i disconnect from the internet the messages appear with the options "Retry - Cancel" and you must manually select "Retry" to send the messages once you reconnect.

![image](https://cloud.githubusercontent.com/assets/14333569/22127988/adb3c23c-de5b-11e6-89d8-83bb18556284.png)

**Comment by DeepSnowNeeL** [comment]
I had the same connexion problems with 3.6.0 and as you said I need to manually re-send them now. I guess you changed this between 3.5 and 3.6 ? :) Or maybe it's just more network problems going on..

**Comment by esethna** [comment]
I don't believe this behavior has changed in 3.6. If Mattermost is not connected to the internet then messages must be retried manually after the connection resumes. 

We haven't heard any other reports of connection problems, however I would recommend upgrading to v3.6.1 as there is a fix for re-establishing the connection after waking a computer from sleep.

**Comment by DeepSnowNeeL** [comment]
I will upgrade, I guess the thing was the connexion sometimes allowing mm to send the messages and sometimes not.. Thanks for your time and your awesome tool :)
