### ISSUE TITLE
Emoji picker no longer working for single-character emoji in 3.6

### ISSUE THREAD

**Issue by timrsmith** [mattermost/platform#5103]
#### Summary
Emoji picker no longer working for single-character emoji in 3.6

#### Steps to reproduce
- Create a custom emoji with a single-character name e.g. `:y:`
- Try to use that emoji, e.g. `:y`
- The picker does not appear

#### Expected behavior
The picker should appear as soon a letter is typed after the `:`. This is no longer the case.

#### Observed behavior
We have a custom thumbs-up emoji :y:
<img width="209" alt="screen shot 2016-11-11 at 11 01 26 am" src="https://cloud.githubusercontent.com/assets/1857984/20226835/952cef74-a7fe-11e6-979e-5b858d55a7fb.png">

previously, when typing `:y` the emoji picker would appear just fine.
<img width="182" alt="screen shot 2016-11-11 at 11 05 48 am" src="https://cloud.githubusercontent.com/assets/1857984/20226918/f67d3bc6-a7fe-11e6-9d6c-6cef647b0a50.png">

Now, it looks as though the picker only appears on the second character, so single character emojis cannot show in picker.
<img width="83" alt="screen shot 2017-01-17 at 10 25 37 am" src="https://cloud.githubusercontent.com/assets/1857984/22033942/65561e9e-dc9f-11e6-9951-4dcc934b380a.png">

On typing a second character, the picker does appear. This appears to be the new picker behavior which leaves single character emoji out.
<img width="244" alt="screen shot 2017-01-17 at 10 26 00 am" src="https://cloud.githubusercontent.com/assets/1857984/22033972/7c730dd0-dc9f-11e6-8c16-849d14bf7f77.png">

**Comment by esethna** [comment]
@timrsmith this is an improvement in v3.6, where the emoji autocomplete does not appear unless the user types two characters. This is to allow users to type single character smileys, for example `:)` `:p` without being bothered by the autocomplete pop up.

**Comment by timrsmith** [comment]
I, for one, don't consider it an improvement. I'd much rather see the picker intelligently handle emoji such as :) rather than turn off the picker for everything else until two characters.

**Comment by jasonblais** [comment]
Hey @timrsmith, if we included `:p` in emoji autocomplete list, then the side effect would be that the user would have to press twice in order to post a `:p` message:

1) Type `:p`
2) Hit enter to select the emoji [not really necessary]
3) Hit enter to choose the emoji

Moreover, we're working on adding an emoji picker (#4665), which can be used to add emoji (and emoji reactions) more easily --> this will also have custom emoji on the list, such as `:y:`

**Comment by timrsmith** [comment]
I was thinking, rather, that emoticons would not trigger the picker, but emoji should.

So `)`, `(`, `p`, and other reserved emoticon characters when typed after `:` would not trigger the emoji picker, but anything else would -- effectively separating emoticon functionality from emoji functionality.

**Comment by dmke** [comment]
FYI, typing `:th` opens the picker, but it doesn't show suggestions for `:thumbsup:` (despite it beeing a valid emoji).

**Typing `:th`**
> ![image](https://cloud.githubusercontent.com/assets/327411/22252422/68d169b6-e24e-11e6-8a7a-b78070036740.png)

**Typing another `u`**
> ![image](https://cloud.githubusercontent.com/assets/327411/22252438/75c90b7e-e24e-11e6-84f2-8df355099005.png)

**Submitting `thumbsup`**
> ![image](https://cloud.githubusercontent.com/assets/327411/22252473/9e5127fc-e24e-11e6-9511-d4d50ff93ff1.png)

**Comment by jasonblais** [comment]
Hey @timrsmith, if you're interested, I encourage you to join our public UX design channel and offer your feedback there too. The channel is viewed by more people (both by community and core team), so you'll get a better discussion there.

We really value feedback, so I appreciate you sharing it.

@dmke That's a bug that should now be fixed on `master`, thanks for letting us know! (JIRA ticket here https://mattermost.atlassian.net/browse/PLT-5203)

**Comment by dmke** [comment]
@jasonblais Thanks!
