### ISSUE TITLE
Enable support for S3 VPC endpoints

### ISSUE THREAD

**Issue by woooooopwop** [mattermost/platform#5104]
Looking at https://github.com/mattermost/platform/blob/f02620b291b988848392c455a7719699f6b5c00f/vendor/github.com/minio/minio-go/s3-endpoints.go 

`

var awsS3EndpointMap = map[string]string{
	"us-east-1":      "s3.amazonaws.com",
	"us-west-2":      "s3-us-west-2.amazonaws.com",
	"us-west-1":      "s3-us-west-1.amazonaws.com",
	"eu-west-1":      "s3-eu-west-1.amazonaws.com",
	"eu-central-1":   "s3-eu-central-1.amazonaws.com",
	"ap-south-1":     "s3-ap-south-1.amazonaws.com",
	"ap-southeast-1": "s3-ap-southeast-1.amazonaws.com",
	"ap-southeast-2": "s3-ap-southeast-2.amazonaws.com",
	"ap-northeast-1": "s3-ap-northeast-1.amazonaws.com",
	"ap-northeast-2": "s3-ap-northeast-2.amazonaws.com",
	"sa-east-1":      "s3-sa-east-1.amazonaws.com",
	"cn-north-1":     "s3.cn-north-1.amazonaws.com.cn",
}
`

It seems that Mattermost only supports public endpoints for S3 as of today. However, I do have a specific use case which requires utilization of my VPC endpoint (http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints-s3.html). As you can imagine, security is one big deal for my implementation and I'd like to make sure all trafic stay within my VPC as much as possible.

Private endpoints use the following syntax:  com.amazonaws.<region>.<service>. (eg: com.amazonaws.us-west-2.s3)

It seems that just adding the new k:v for each region make the trick. 

Since I'm fairly new with this software, I'd like to know what's the process to implement new features as well as the release timeline.

Thanks - 

Thanks

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback @woooooopwop!  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

[Learn more about our process for contributing feature ideas here](https://www.mattermost.org/feature-ideas/)

**Comment by cpanato** [comment]
looks like you will need to add other endpoints, but this is in another project that mattermost uses.

maybe can post here the issue and see: https://github.com/minio/minio-go

**Comment by cpanato** [comment]
or did you try to setup this entry in the config.json? 
```
        "AmazonS3Endpoint": "s3.amazonaws.com",
```

**Comment by jasonblais** [comment]
Thanks @woooooopwop and @cpanato, discussed with the team and created a Help Wanted issue here: https://github.com/mattermost/platform/issues/5173
