### ISSUE TITLE
RestrictCreationToDomains not working with multiple domains (in GitLab Mattermost)

### ISSUE THREAD

**Issue by tofi86** [mattermost/platform#5105]
#### Summary
Setting `"RestrictCreationToDomains": "domain1.tld, domain2.tld"` still let's you invite users with `*@domain3.tld`

#### Steps to reproduce

Setting `mattermost['team_restrict_creation_to_domains'] = "domain1.tld, domain2.tld"` in GitLab (latest version) which expands to ` "RestrictCreationToDomains": "domain1.tld, domain2.tld"` after gitlab reconfigure.

Inviting a new user with `*@domain3.tld` does not fail.

#### Expected behavior
Inviting a new user with `*@domain3.tld` should fail.

#### Observed behavior
Invitiation mail was sent but shouldn't.

**Comment by esethna** [comment]
Hi @tofi86, is account creation successful with an incorrect domain? The invitation will be sent but the user should hit an error when they attempt to click "Create account".

**Comment by tofi86** [comment]
Oh okay, account creation fails when trying to click on "Create Account". But this is really a bit confusing for Team Admins and Invitees...

Shouldn't the invite be restricted as well?

**Comment by tofi86** [comment]
And what happens if you accept an invitation with creating an OAuth account (e.g. via GitLab) – does it validate the OAuth email address?

**Comment by esethna** [comment]
Thanks @tofi86, the domain restrictions only apply to email sign up as we have no way of accessing or verifying if email addresses outside the specified domain may actually belong to LDAP or SAML.

Please see [this ticket](https://mattermost.atlassian.net/browse/PLT-3183) and the ticket comments for details on why it was resolved as won't fix.
