### ISSUE TITLE
[Help Wanted] Add machine-readable date and time to timestamps

### ISSUE THREAD

**Issue by yurikhan** [mattermost/platform#5108]
#### Summary

Add machine-readable date and time to the message timestamps.

#### Steps to reproduce

1. Join a channel.
2. Send a message.
3. In the web browser’s developer tools, inspect the timestamp.

#### Expected behavior

The timestamp should be a `<time>` element with content formatted according to the user’s preferences and time zone, and with the machine-readable ISO 8601 date and time in the `datetime` attribute. Example: `<time class="post__time" datetime="2017-01-18T05:14Z">12:14</time>` for a user in the UTC+7 time zone.

The presence of a machine-readable date and time is important for accessibility and will permit display format customization via userscripts.

#### Observed behavior
The timestamp is a `<time>` element with content formatted to the user’s preferences, but without a machine-readable date and time. Example: `<time class="post__time">12:14</time>`.

#### Possible fixes
Here are [all places in code where `post__time` is referenced](https://github.com/mattermost/platform/search?l=JSX&q=post__time&type=Code&utf8=%E2%9C%93). In all three, the `datetime` attribute should be added.

**Comment by lfbrock** [comment]
Thanks @yurikhan! I'm going to update the title to turn this into a [Help Wanted] issue, if it's something you're interested in working please feel free to submit a fix!

**Comment by jasonblais** [comment]
Thanks @bjoernr-de! Closing as resolved
