### ISSUE TITLE
Installing the latest Mattermost JS Driver with npm

### ISSUE THREAD

**Issue by ReDnAxE** [mattermost/platform#5109]
#### Summary
`npm install mattermost` does not install the latest version of the [mattermost/mattermost-driver-javascript](https://github.com/mattermost/mattermost-driver-javascript) github repository

#### Steps to reproduce
I'm currently developing a bridge api in NodeJs to cover our internal needs with Mattermost, and I would like to add it in my package.json dependencies list like `"mattermost": "^3.6.0"`
But here is the response:
`npm ERR! notarget No compatible version found: mattermost@^3.6.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 3.4.0, 3.0.3, 3.0.2, 3.0.1`

#### Observed behavior
Unfortunatly when I try this configuration `"mattermost": "git+https://git@github.com/mattermost/mattermost-driver-javascript.git#master"`, I do not retrieve all files, especially webpack.config.js file in order to build myself the sources.

#### Expected behavior
Is there something to do for my part, or could you update the [npm repository](https://www.npmjs.com/package/mattermost) in order to retrieve the latest JS driver version (3.6.0) ?

**Comment by lfbrock** [comment]
@ReDnAxE I think we just need to update it, @crspeller is going to look at automating the process. Thanks for filing the issue!

**Comment by tobika** [comment]
Yes it's possible to build the current version with webpack and it works fine when used later.

There were just 2 problems :
- the package 'babel core' is missing `npm install babel-core`
- and there was quite a strange webpack error which is solved by installing `npm i -D -E babel-preset-es2015@6.9.0`

**Comment by jasonblais** [comment]
Thanks everyone! I've created a ticket to update to the latest version and we'll look at automating the process as well.

https://mattermost.atlassian.net/browse/PLT-5432

**Comment by mtriff** [comment]
FYI, I also needed to install the `babel-plugin-transform-object-assign` plugin to successfully run webpack on the latest version of `Client.jsx` in the repository.
