### ISSUE TITLE
Edited posts must be denoted with "(edited)"

### ISSUE THREAD

**Issue by gokceneraslan** [mattermost/platform#5111]
Edited messages must have the `(edited)` remark, or something similar:
![image](https://cloud.githubusercontent.com/assets/1140359/22060599/bb3e77b6-dd71-11e6-89c9-8df66518b4b2.png)

Now, the timestamp of the post becomes invalid and misleading when it's edited.

**Comment by esethna** [comment]
Thanks @gokceneraslan this was added by a community member recently: https://github.com/mattermost/platform/pull/4923

The feature will be available in our next release, v3.7.
