### ISSUE TITLE
Message beginning with "[MISSING] : " does not display correctly

### ISSUE THREAD

**Issue by MattMattV** [mattermost/platform#5112]
#### Summary
If the message start with string `[MISSING]:` it does not display

#### Steps to reproduce
Send a message containing : `[MISSING]: message` 

#### Expected behavior
The message should display [MISSING]: message

#### Observed behavior
See the grey thin line : 
![image](https://cloud.githubusercontent.com/assets/6715182/22061134/ea5bd956-dd73-11e6-8505-f195cca1ea8f.png)

**Comment by esethna** [comment]
Thanks @MattMattV, I was able to reproduce this strange issue, thanks for the report! Closing this issue to track on JIRA:  https://mattermost.atlassian.net/browse/PLT-5332
