### ISSUE TITLE
[Help Wanted] Updating Channel Purpose should post a System Message in the channel

### ISSUE THREAD

**Issue by it33** [mattermost/platform#5116]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

If you change the name of a channel or its heading there's a System Message posted in the channel to all users, but not for changing Channel Purpose. 

Expected: 
When a user changes the channel purpose, post a system message visible to all users saying "[username] updated channel purpose from: [OLD] to: [NEW]" similar to message when channel header or channel name is changed.

Channel header example:
![image](https://cloud.githubusercontent.com/assets/14333569/22081788/42e32d50-dd82-11e6-849e-1d77197aa381.png)

**Comment by cpanato** [comment]
@it33 I tested this on current master and when you change the channel purpose it post a update message for the users in the channel:

![screen shot 2017-01-19 at 09 35 47](https://cloud.githubusercontent.com/assets/4115580/22099274/fadce060-de2a-11e6-84e4-e9114a392132.png)

**Comment by grundleborg** [comment]
Well spotted. Looks like this was already fixed in another ticket.
