### ISSUE TITLE
[Help Wanted]: Emoji reactions show beside image thumbnail rather than below

### ISSUE THREAD

**Issue by it33** [mattermost/platform#5117]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

JIRA ticket: https://mattermost.atlassian.net/browse/PLT-4898

#### Summary
Emoji reaction doesn't show properly under image thumbnail--shows to the side

#### Steps to reproduce
Add an emoji reaction on a message with an image file, e.g. type +:+1: under a message with an image attachment

#### Expected behavior
Emoji reaction shows below the image thumbnail 

#### Observed behavior
Emoji reaction shows to the RIGHT of the image thumbnail 

![image](https://cloud.githubusercontent.com/assets/177788/22072166/517fc0c0-dd56-11e6-9aae-7f457f749e67.png)

**Comment by jasonblais** [comment]
Closed via #5194, thanks @bjoernr-de!
