### ISSUE TITLE
[Help Wanted] Markdown Rendering Unit Tests for Images

### ISSUE THREAD

**Issue by grundleborg** [mattermost/platform#5118]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5321)

This ticket is to create `webapp/tests/formatting_images.test.jsx` containing automated unit tests for markdown images that appear when the user makes a post containing text like `![alt text for image](http://example.com/image)`. 

These tests should cover all the functionality listed [in our docs](https://github.com/mattermost/docs/blob/v3.7-documentation/source/help/messaging/formatting-text.rst#in-line-images).

**Comment by VeraLyu** [comment]
Hi, Can I help on this one?

**Comment by jasonblais** [comment]
That would be awesome! You can take this one @VeraLyu

**Comment by jasonblais** [comment]
Resolved -- huge thanks @VeraLyu!
