### ISSUE TITLE
The post_subject template is not being used.

### ISSUE THREAD

**Issue by CometKim** [mattermost/platform#5134]
#### Summary
The post_subject template is not being used.
https://github.com/mattermost/platform/blob/master/app/notification.go#L385

It was used on v3.5.
https://github.com/mattermost/platform/blob/v3.5.1/api/post.go#L845-L847

#### Expected behavior
Exist template shoud be used.

**Comment by lfbrock** [comment]
@CometKim - is this causing issues with the email subject somewhere? 

Can you add some more details about what's happening when the post_subject is not being used, and I can file a bug for it?

**Comment by jasonblais** [comment]
Hey @CometKim, 

we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you have any more details about the observed behaviour when the post_subject template is not used, please let us know and we can file a bug for it.
