### ISSUE TITLE
E-mail notifications contain content

### ISSUE THREAD

**Issue by jmn** [mattermost/platform#5136]
#### Summary
E-mail notifications sends message content and sender information onto unsecure E-mail.

#### Steps to reproduce
Enable E-mail notifications, send a DM to offline user.

#### Expected behavior
Mattermost should only send "You have a new new message in Mattermost", nothing else.

#### Observed behavior
People sending DMs in Mattermost expect their messages to be somewhat secure. They do not expect them to get sent as unsecure E-mail on the Internet.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem
```

if userAllowsEmails && status.Status != model.STATUS_ONLINE && profileMap[id].DeleteAt == 0 {
				sendNotificationEmail(post, profileMap[id], channel, team, senderName[id], sender)
}
```
https://github.com/mattermost/platform/blob/d3a285e64d051aa8d5c4c9854597dfbcce107675/app/notification.go

**Comment by cpanato** [comment]
I can work on that if need

**Comment by jasonblais** [comment]
Thanks @jmn for the feedback!

[We've got an open JIRA ticket here](https://mattermost.atlassian.net/browse/PLT-3992) and an [open feature request here](https://mattermost.uservoice.com/forums/306457-general/suggestions/15425175-enable-omission-of-message-snippets-in-email-notif).

Both have on-going discussions, would you like to participate and share your feedback there as well?

**Comment by cpanato** [comment]
@jasonblais there is a ticket to work on that?

**Comment by jasonblais** [comment]
Hey @cpanato, I don't think I saw your response for some reason, or at least missed it :/ 

There's a JIRA ticket here: https://mattermost.atlassian.net/browse/PLT-3992

The option to configure email notification contents is intended to meet regulations for enterprises.

**Comment by jasonblais** [comment]
Closing for now to track in Jira: https://mattermost.atlassian.net/browse/PLT-3992

Thanks everyone!

**Comment by Roy-Orbison** [comment]
So you guys are just leaving it as as insecure by default for Team Edition?
