### ISSUE TITLE
[Help Wanted] System Message indicating a user who is mentioned is not in the channel, should appear below the message

### ISSUE THREAD

**Issue by lindy65** [mattermost/platform#5153]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

#### Summary
System Message indicating a user who is mentioned is not in the channel, should appear below the message

#### Steps to reproduce
1. Reply to a message from the center channel
2. This will open the right-hand side
3. With the right-hand side still open, type another message in the center channel at-mentioning a user who is not a member of the channel

#### Expected behavior
System message indicating the user is not in the channel should appear below the message you've just typed

#### Observed behavior
System message indicating the user is not in the channel appears above the message you've just typed

![image](https://cloud.githubusercontent.com/assets/13020833/22177144/23bffefc-e021-11e6-8d2b-75bd2af1c6b9.png)

**Comment by Lulucmy** [comment]
Hello,

I tried on 2 different Mattermost, and the bug never reappeared.
The two screenshots : 
![screen shot 2017-01-22 at 14 03 58](https://cloud.githubusercontent.com/assets/20552095/22182759/a2a9a5b0-e0ad-11e6-96f8-2c14173f3607.png)
![screen shot 2017-01-22 at 14 14 21](https://cloud.githubusercontent.com/assets/20552095/22182760/a2b01dbe-e0ad-11e6-906e-74ff46dcd4d4.png)
Where have you tried ?

Lulucmy

**Comment by enahum** [comment]
@lindy65 is this happening on master?

**Comment by lindy65** [comment]
![image](https://cloud.githubusercontent.com/assets/13020833/22184730/fc945434-e0e0-11e6-9bbc-3aa2feecc24e.png)

@enahum it was happening on master but I've just retested and now it seems the issue is fixed!  Perhaps some other PR fixed the issue? 

The issue does repro on pre-release but if you switch out of the channel and then back to it, the system message switches order and is in the correct place below the message.

**Comment by jasonblais** [comment]
Thanks @Lulucmy for looking into it!

It looks like it has been fixed on `master`, so closing the issue as completed.

Thanks all!
