### ISSUE TITLE
[Help Wanted] Use consistent Display Name sorting code throughout the webapp

### ISSUE THREAD

**Issue by grundleborg** [mattermost/platform#5159]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5320)

There are many places in the Mattermost WebApp codebase where Teams and Channels are sorted by their Display Name. However, in many of these places the comparator function is implemented separately each time. 

Instead, we should have two functions that are used everywhere they are applicable: 
* `sortTeamsByDisplayName()` (in `webapp/utils/utils.jsx`) - use [this function](https://github.com/mattermost/platform/blob/master/webapp/utils/utils.jsx#L1098) as a starting point.
* `sortChannelsByDisplayName()` (in `webapp/utils/channel_utils.jsx`) [this function](https://github.com/mattermost/platform/blob/master/webapp/utils/channel_utils.jsx#L90) as a starting point.

When comparing strings, the sort functions should use `localeCompare()` with the locale set in the `LocaleStore`. (See [here](https://github.com/mattermost/platform/blob/master/webapp/utils/channel_utils.jsx#L90) for an example).

You can search for places where sorting is currently used by running the following command:

    $ git grep sort webapp

Be careful to only update places where Channels and Teams are being sorted, and check that the sort used in each case is a normal one and not a specialised alternative one before changing it. If you are in any doubt about a particular case, please ask here or on the [Developers Channel](https://pre-release.mattermost.com/core/channels/developers) of pre-release.mattermost.com.

**Comment by jasonblais** [comment]
Closed via #5159, thanks @saturninoabril!
