### ISSUE TITLE
[Help Wanted] Add unread indicator on mobile web view

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#5179]
Since 16c3915d1afafa6b1a9120150977711a4f3c8345, the notification jewel on mobile only shows up when you have new mentions. I consider this a regression.
Our users were using it to quickly see when a new message was posted in any of the channel. Now they have to open the left pane to see if a channel name is in bold so they are complaning.

#### Summary
There isn't a way to see that a new message has been posted on mobile anymore.

#### Steps to reproduce
With account A, post a new message in a channel that account B can read.
With account B, check the notification jewel on mobile.

#### Expected behavior
There should be some kind of way to see that a new message has been posted.

#### Observed behavior
The notification jewel does not appear so, unless you open the left pane, you have no way to know that a new message has been posted.

#### Possible fixes
We could either:
 * Add an option allowing users to choose if they want to display the jewel for all messages or only for mentions.
* Add another visual indicator (which was discussed in #4590 apparently).

**Comment by lfbrock** [comment]
Hi @Rudloff, thanks for bringing this up, I'll queue it for discussion with the UX Team. 

Maybe we can do something similar to desktop app where a dot without a counter is shown for unreads.

**Comment by lfbrock** [comment]
@Rudloff made a ticket here for this issue: https://mattermost.atlassian.net/browse/PLT-5401

If it's something you're interested in working on, let us know!

**Comment by jasonblais** [comment]
Closed via #5234, thanks @Rudloff!
