### ISSUE TITLE
[Help Wanted] Add permalink to timestamp

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5183]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5376)

#### Summary
Timestamps on messages should be permalinks

![image](https://cloud.githubusercontent.com/assets/14333569/22273134/dcde7562-e25b-11e6-929c-cb838c7df864.png)

#### Implementation
Clicking on the timestamp should:
- Web: Open the permalink of the message in a new tab
- Desktop Apps: Open the permalink view of the message in a new browser tab (it should not open in the desktop app)
- Mobile: Timestamps should not link on mobile to simplify the mobile UI.

Note: Keep the permalink option from the [...] menu to meet our "fast, obvious, forgiving" principle.

**Comment by jasonblais** [comment]
Closed via #5206, thanks @andreistanciu24!
