### ISSUE TITLE
Add several Team Site Main Menu options to the System Console Main Menu

### ISSUE THREAD

**Issue by it33** [mattermost/platform#5190]
Proposed Help Wanted 

System Console Main Menu lacks some basic controls available in Team Site Main Menu. This ticket is to improve the experience 

Currently, System Console Main Menu shows: 

```
Switch to [TEAM]
----
Logout 
```

![image](https://cloud.githubusercontent.com/assets/177788/22297375/ec175fb4-e2d1-11e6-8f2b-58d127ec9b95.png)

Propose we update System Console Main Menu to: 
```
Switch to [TEAM]
----
Administrator's Guide
Troubleshooting Forum
Commercial Support 
About Mattermost 
----
Logout 
```

##### Details on links: 

1. `Administrator's Guide` - link to: https://about.mattermost.com/administrators-guide/
2. `Troubleshooting Forum` - link to: https://about.mattermost.com/troubleshooting-forum/
3. `Commercial Support` - link to: https://about.mattermost.com/commercial-support/
4. `About Mattermost` - brings up About Mattermost dialog

**Comment by jasonblais** [comment]
Ticket here, queued for help-wanted approval in the next triage meeting: https://mattermost.atlassian.net/browse/PLT-5440

**Comment by jasonblais** [comment]
help wanted: https://github.com/mattermost/platform/issues/5355
