### ISSUE TITLE
REGRESSION: Line break appears before pre-formatted text inconsistently 

### ISSUE THREAD

**Issue by it33** [mattermost/platform#5215]
#### Summary
REGRESSION: Line break appears before pre-formatted text inconsistently 

#### Steps to reproduce
Post the following messages into `master` branch on pre-release.mattermost.com (Left image below) and then in Mattermost 3.6 on demo.mattermost.com (Right image below). 

![image](https://cloud.githubusercontent.com/assets/177788/22397768/c234f95a-e52d-11e6-9d70-0f7069cfc72d.png)

![image](https://cloud.githubusercontent.com/assets/177788/22397790/318e086e-e52e-11e6-8371-532d0ddb6d56.png)

#### Expected behavior
`master` behaves the same as 3.6

#### Observed behavior
Line break appears inconsistently before pre-formatted text: 

![image](https://cloud.githubusercontent.com/assets/177788/22397786/27c6983c-e52e-11e6-9147-78f48402359b.png)

#### Possible fixes
Revert to 3.6 CSS and disable (edited) until the CSS for the feature can be implemented without regressions.

**Comment by jasonblais** [comment]
Resolved by #5217, Jira ticket here: https://mattermost.atlassian.net/browse/PLT-5356
