### ISSUE TITLE
Add load_test for finding line break inconsistencies in markdown rendering

### ISSUE THREAD

**Issue by it33** [mattermost/platform#5216]
Proposed Help Wanted

Add a [/loadtest option](https://github.com/mattermost/platform/blob/master/tests/README.md) to https://github.com/mattermost/platform/blob/master/tests/test-markdown-lists.md that checkes for line breaks ahead of pre-formatted text in different configurations: 
https://github.com/mattermost/platform/issues/5215

Note: This is difficult because we give our instructions in pre-formatted text. Not sure what to do here, maybe we need RST file for load tests, rather than .md?

**Comment by jasonblais** [comment]
We have a process to add new release tests for each PR merged to platform repo (when applicable) with markdown tests added to load_test.

Here's the spreadsheet for 3.7 PRs: https://docs.google.com/spreadsheets/d/1QIK50dHbBBOrAzQ6Bffb6YxXIcNLX9LzNW20spMapdY/edit#gid=0
