### ISSUE TITLE
How to use mattermost api?

### ISSUE THREAD

**Issue by altafhussian** [mattermost/platform#5219]
I have installed mattermost server successfully. Please guide me to proceed, how to use api. I haven't find any api folder in my setup.

I have downloaded linux binary from [https://about.mattermost.com/download/](this)

**Comment by jasonblais** [comment]
Thanks @altafhussian! We've got our API documentation available at https://github.com/mattermost/mattermost-api-reference

Would this be helpful to get you started?

**Comment by jasonblais** [comment]
Hey @altafhussian, looks like you found help in our [Integrations and Apps channel](https://pre-release.mattermost.com/core/channels/integrations)

If you have any further questions, don't hesitate to ask them in that channel. Thanks for using Mattermost!
