### ISSUE TITLE
[Help Wanted] Failed slash command should show input

### ISSUE THREAD

**Issue by ZJvandeWeg** [mattermost/platform#5224]
#### Summary
On Slack, when a slash commands fails for any reason, the input (slash command and its parameters) are shown back to the user. Would love to have this in Mattermost too as now a timeout, or IO error might mean a lot of retyping.

#### Steps to reproduce
Create a slash commands which times out. And trigger it.

#### Expected behavior
Feedback it failed, and slash command in the typing section.

#### Observed behavior
Feedback, but lost my input.

NOTE: Slash command refers to Mattermost slash commands: https://docs.mattermost.com/developer/slash-commands.html

**Comment by jasonblais** [comment]
Thanks @ZJvandeWeg! I created a Jira ticket and it will be discussed on Wednesday's triage meeting: https://mattermost.atlassian.net/browse/PLT-5412

We'll likely turn this into a help wanted issue, so if you or someone else in the community is interested helping implement it, let us know!

**Comment by jasonblais** [comment]
I updated this into a Help Wanted issue if someone would like to take a look?

----

If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

Jira ticket: https://mattermost.atlassian.net/browse/PLT-5412

**Comment by lfbrock** [comment]
Closing this one + replacing with: https://github.com/mattermost/platform/issues/6659
