### ISSUE TITLE
[Help Wanted] Update error message and add link

### ISSUE THREAD

**Issue by it33** [mattermost/platform#5227]
Help Wanted 

People are struggling with the error message: 

- [“Please check connection, Mattermost unreachable. If issue persists, ask administrator to check WebSocket port.”](https://pre-release.mattermost.com/core/pl/scxb4c5y4jbz9qfeihzabp5u1y)

Propose 

1. Rename message to `Server unreachable, check network connection. If issue persists, ask administrator to [troubleshoot](https://about.mattermost.com/default-websocket-port-help/)` 
2. Update [troubleshooting documentation](https://docs.mattermost.com/install/troubleshooting.html?highlight=unreachable#please-check-connection-mattermost-unreachable-if-issue-persists-ask-administrator-to-check-websocket-port), including a post to troubleshooting forum

Opening ticket to see if there is interest from community on discussing how we can make this error flow easier for new users.

**Comment by twalk6** [comment]
To add to documentation: The combination of the Safari browser, websockets, and a self-signed cert can cause a broken cert chain. "WebSocket network error: OSStatus Error -9807: Invalid certificate chain". I don't see this issue with anything else.

**Comment by lfbrock** [comment]
Replaced with: https://github.com/mattermost/platform/issues/6422
