### ISSUE TITLE
Remove config.json from versioning

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#5235]
Would it be possible to add the config.json file to `.gitignore`?
I get conflicts everytime I switch branch because I have a modified config file.
And it makes it way too easy to accidentally commit a database password.

**Comment by jasonblais** [comment]
Thanks @Rudloff! This is queued for [Wednesday's Developers meeting](https://pre-release.mattermost.com/core/pl/q5m1piyj77rzjbg6eewbkxk88y).

The meeting is open for public and starts at 10am San Francisco time on Wednesday, in case you'd like to attend :)

**Comment by jasonblais** [comment]
Hey @Rudloff, we'll add config.json to `.gitignore` for now: https://github.com/mattermost/platform/pull/5276

We'll investigate a better long-term plan later, but it should at least be a sufficient temporary solution.

Thanks for bringing it to our attention :)

**Comment by Rudloff** [comment]
This is not enough. Git will still track changes on this file as long as it is in the repository.

**Comment by jasonblais** [comment]
Thanks @Rudloff, we've got a ticket to [investigate a proper long-term solution for modifying config.json](https://mattermost.atlassian.net/browse/PLT-5439)

**Comment by jasonblais** [comment]
@Rudloff wondering if you'd be interested helping investigate potential solutions for the issue?

Would love to get some help and suggestions from the community on this topic.

Ticket is here for reference: https://mattermost.atlassian.net/browse/PLT-5439

**Comment by Rudloff** [comment]
Most software I use have a `config.example.json` file that you copy during install.
The config file is not versioned but the example is versioned.
Then if an option is not defined in the `config.json` file, it takes the default value. This is to prevent any issue when an update adds new options.

**Comment by jasonblais** [comment]
@jwilander would you have thoughts on this proposal?

**Comment by jwilander** [comment]
I think that's a good solution 👍

**Comment by jasonblais** [comment]
@Rudloff would you be interested submitting a PR for your suggestion?

**Comment by Rudloff** [comment]
I will be pretty busy next week but I can submit a PR the week after.

**Comment by jasonblais** [comment]
Next week works great, thanks @Rudloff!

**Comment by jasonblais** [comment]
I also reopened this issue for us to track

**Comment by lindy65** [comment]
Hi @Rudloff 

Just wanted to say a big thank you from the Mattermost team.  Your contribution is much appreciated!  It's a real pleasure having contributors such as yourself working with us :)

**Comment by jasonblais** [comment]
Thanks again @Rudloff for your help.

We have a ticket to track it here, and are planning to submit a fix for Mattermost v3.9: https://mattermost.atlassian.net/browse/PLT-5439
