### ISSUE TITLE
cannot manage users without team?

### ISSUE THREAD

**Issue by joernhees** [mattermost/platform#5251]
as an admin i don't have any way to see all users on a server, do i?

i managed to drop a user out of its last team and now can't deactivate it / reset password :-/

**Comment by jasonblais** [comment]
Hey @joernhees,

This is something we're looking at improving, so you can manage all your users easily through the System Console.

In the meantime, we have available commands that you can use, for instance:
  - [resetting user's password](https://docs.mattermost.com/administration/command-line-tools.html#platform-user-password)
  - [deactivating a user](https://docs.mattermost.com/administration/command-line-tools.html#platform-user-deactivate)

**Comment by joernhees** [comment]
thanks. we have a gitlab omnibus, so in case anyone else wonders: [this](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1015#note_22576761) is how you actually invoke the `platform` command:
```
sudo -u mattermost /opt/gitlab/embedded/bin/mattermost --config=/var/opt/gitlab/mattermost/config.json
```

so you can just do:
```
alias platform='sudo -u mattermost /opt/gitlab/embedded/bin/mattermost --config=/var/opt/gitlab/mattermost/config.json'
```
