### ISSUE TITLE
update user-email from oauth

### ISSUE THREAD

**Issue by joernhees** [mattermost/platform#5252]
Administering an internal gitlab and mattermost for many students, we frequently run into the problem that a student's email address changes. We then simply update it on gitlab, but the email notification from mattermost end up on the old address and ultimately bounce.

It seems mattermost doesn't update the email address from the oauth provider. In #1897 a workaround is mentioned. However, we weren't able to reproduce it, especially not admin side only.

Wouldn't it be possible to check if the email address changed on login? If it doesn't match with the internal one, it would be great if it was updated "automagically".

If that's too complicated, would it be possible to provide a "refresh from oauth" option in the admin interface next to the user?

**Comment by lfbrock** [comment]
Hi @joernhees - this is something we need to fix, we have a ticket here tracking it: https://mattermost.atlassian.net/browse/PLT-3751

Is it something you would be interested in working on?

**Comment by joernhees** [comment]
would love to, but i'm afraid i'm not go savvy enough to actually be of any help :-/

**Comment by jasonblais** [comment]
Thanks @joernhees, turned the Jira ticket into a help wanted issue here: https://github.com/mattermost/platform/issues/5288

**Comment by jasonblais** [comment]
If anyone in the community would like to work on it, please comment on the ticket #5288!
