### ISSUE TITLE
Speed up channel switcher (CTRL+K) 

### ISSUE THREAD

**Issue by it33** [mattermost/platform#5255]
Proposed Help Wanted

Discussed with JW: 

Re-write the channel switcher component that is brought up with the CTRL+K shortcut

De-couple channel switching logic from auto-complete so user can type in channel name and hit ENTER quickly, without waiting for auto-complete to finish. 

Generally minimize the number of key-pressed needed--implement channels switcher first and add autocomplete functionality after.

**Comment by jasonblais** [comment]
Added to channel switcher V2 spec: https://docs.google.com/document/d/1DLqgHuu14xxtLkZf3-6G0dpFm52--asaQC5puLcaOqs/edit#bookmark=id.9hbcha8xidw3

Will keep the issue open until spec finalized and queued for review

**Comment by jasonblais** [comment]
Early spec here, which incorporates the suggested changes: https://docs.google.com/presentation/d/15T3xH2kqHXN5kHrVWVJjR_vjfawRviaT5DPfr9tlaKc/edit#slide=id.g1f1004cd07_0_32

A new ticket will be created after the design is finalized
