### ISSUE TITLE
commandline channel list "Error: cli.license.critical"

### ISSUE THREAD

**Issue by joernhees** [mattermost/platform#5257]
on a current gitlab omnibus install i can't list the channels of our team:
```
# alias platform='sudo -u mattermost /opt/gitlab/embedded/bin/mattermost --config=/var/opt/gitlab/mattermost/config.json'
# platform version
Version: 3.6.0
Build Number: 3.6.1
Build Date: Thu Jan 19 20:03:23 UTC 2017
Build Hash: 0d8bb03b...
Build Enterprise Ready: false
DB Version: 3.6.0
# platform channel list <redacted_teamname>
Error: cli.license.critical
Usage:
  platform channel list [teams] [flags]

Examples:
  channel list myteam

Global Flags:
  -c, --config string   Configuration file to use. (default "config.json")

```

**Comment by joernhees** [comment]
hah, i just noticed that this is an "enterprise feature"... are you kidding?

given that as an admin i want to find out which channel eats up all my disk-space and their folders are using their ids, this is a basic feature...

anyhow, here's a simple command for other admins:
```
sudo -u gitlab-psql -- /opt/gitlab/embedded/bin/psql -h /var/opt/gitlab/postgresql mattermost_production -P pager=off -c \
"select c.id, t.displayname, c.displayname, c.type, c.totalmsgcount
from channels c inner join teams t on (c.teamid = t.id)
where c.deleteat = 0 and c.type <> 'D';"
```

seems you get all "direct" message channel ids as well if remove the `and c.type <> 'D'`

**Comment by it33** [comment]
Hi @joernhees, sorry for the late reply here, we were going back and forth internally on how to answer, then ended up not replying, which is a fail on me personally as I had the ball. It's not that your question isn't important, it's that it's caused so much discussion we haven't replied. 

Here's my personal thoughts, mixed in with other discussions: 

1. A listing of Private Groups isn't available in the UI for the System Admin. This helps teammates feel like private discussions aren't easily monitored, e.g. as an innocuous case, teammates could create a System Admin Surprise Party" and not worry about spoiling a surprise. 

2. On the other hand, the DB admin can see all, as you've noted. But the same way the admin of an email system doesn't have info on private conversations of the users in the system, the system limits what a non-DB admin can see. 

3. The CLI tool is a grey area between the UI and the DB and we're trying to balance the right options. Right now it's off for Team Edition (more privacy) and available for Enterprise Edition (more policy/monitoring).

4. The error it gives here isn't super clear. We should fix that--per your ticket. 

5. There's a higher level question of how we handle CLI tool for TE vs EE features--e.g. when someone tried to call LDAP sync via CLI from TE, what should happen? 

We'd welcome your thoughts here, 

Again, sorry for the delay, you can see lots we've been discussing.

**Comment by zinic** [comment]
I think it's a little silly to say that this is an enterprise feature. It feels like the MM team is trying hard to monetize the platform, great, but don't ruin the experience for those of us looking for an OSS solution.

You'll only encourage people to write their own tools that talk directly to the DB. Don't make my life as sysadmin harder.

**Comment by joernhees** [comment]
I agree... basic debugging considerations shouldn't be enterprise features. One of these is "what is this folder causing problems". I'm not asking for an easy way for admins to drop in on private conversations.

Also, unless you have end-to-end encryption, users will have to absolutely trust their server admin. If you're in doubt about your admin's code of honor, you have bigger issues.

I think this is a situation comparable to email services, all of which allow basic debugging.
