### ISSUE TITLE
running team add <teamname> <username> from commandline leads to weird chat message

### ISSUE THREAD

**Issue by joernhees** [mattermost/platform#5258]
<img width="470" alt="screen shot 2017-02-01 at 20 52 59" src="https://cloud.githubusercontent.com/assets/464192/22527727/860fd26e-e8d0-11e6-976c-d8aca9bb43b5.png">

(username redacted)

**Comment by hmhealey** [comment]
Hi @joernhees,

What version of Mattermost are you using?

**Comment by joernhees** [comment]
```
$ gitlab-mattermost.sh version
Version: 3.6.0
Build Number: 3.6.1
Build Date: Thu Jan 19 20:03:23 UTC 2017
Build Hash: 0d8bb03b5773923cf52f4d8cb2711131caae105c
Build Enterprise Ready: false
DB Version: 3.6.0
```

**Comment by jasonblais** [comment]
Thanks @joernhees! 

Can you help give the exact command line that you ran? You can of course change the actual team and username for privacy. 

In which channel did this message post? Did the user successfully join the team?

**Comment by joernhees** [comment]
the command was equivalent to `platform team add ourteam thatuser`
more complete, as this is gitlab, it was:

```
sudo -u mattermost /opt/gitlab/embedded/bin/mattermost --config=/var/opt/gitlab/mattermost/config.json team add ourteam thatuser
```

`thatuser` was the username, not its email.

the message appeared in #general, the user entered the team successfully, it seems.

was it wrong to use the username instead of its email?

**Comment by jasonblais** [comment]
Thanks @joernhees for the report! I created a Jira ticket here, we'll track the issue there https://mattermost.atlassian.net/browse/PLT-5570
