### ISSUE TITLE
[Help Wanted] [PLT-1412] Update search buttons on mobile

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5261]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1412)

In mobile view, after clicking on the search icon in center channel: 

1. Always show the "Back" button 
2. Move the "Cancel" button to be an "x" button inside the search text box, that appears only after text has been entered. Clicking the "x" button should always clear the text inside the search box.

NOTE: Ensure the "x" button is easy to click on mobile.

**Comment by jasonblais** [comment]
Fixed via #5306, thanks @saturninoabril!
