### ISSUE TITLE
[Help Wanted] [PLT-3206] Dragging and dropping a file in the left-hand sidebar should upload the file in center channel

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5263]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3206)

Dragging and dropping a file in the left-hand sidebar doesn't upload the file in center channel

Repro: Drag a file onto the left-hand sidebar

Expected: No action.
Observed: Window refreshes with a URL to the local file path

Reproduced on Windows 10, Chrome

Here's start of a PR to help you get started: https://github.com/mattermost/platform/pull/5311

**Comment by pan-feng** [comment]
I try to do this one,    like this ?
![image](https://cloud.githubusercontent.com/assets/24997742/22617384/ded0aa38-eafe-11e6-8fe2-1e785e732d14.png)

**Comment by pan-feng** [comment]
I had fix this

**Comment by pan-feng** [comment]
![20170206_105313](https://cloud.githubusercontent.com/assets/24997742/22633605/e45cbd60-ec5d-11e6-9a3b-a4d0ce1c6ddf.gif)

**Comment by jasonblais** [comment]
PR here: https://github.com/mattermost/platform/pull/6315
