### ISSUE TITLE
[Help Wanted] [PLT-3355] Replace the handle field and label with url

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5264]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3355)

Repro:
Click the down arrow dropdown next to a channel/group name, then "rename channel (group)".

Observed:
"Handle" field does not have the preceding URL.

Expected:
The handle field and the label in the rename channel modal should be replaced by the URL fields as shown in the screenshot below, similar to how it is in the New channel > edit > Change url modal.

![image](https://cloud.githubusercontent.com/assets/13119842/22703766/4bb68344-ed33-11e6-8677-4af99dfffc42.png)

**Comment by pan-feng** [comment]
I had pull request #5322 , but I had some question for the URL. 
the correct url is   http://xxxxxx/[team name]/[channels]/[channel name],    are we lost "channels"  path part ? 
![image](https://cloud.githubusercontent.com/assets/24997742/22681047/42d2c040-ed46-11e6-96b0-94950efb1e24.png)

**Comment by jasonblais** [comment]
hey @pan-feng, that's a good point.

Updated the screenshot to include `channels/`

**Comment by pan-feng** [comment]
@jasonblais   I had add channels  #5322

**Comment by jasonblais** [comment]
Thanks @pan-feng! 👍

**Comment by jasonblais** [comment]
Closed by #5322, thanks @pan-feng!
