### ISSUE TITLE
[Help Wanted] [PLT-3214] Mobile Web: Auto-focus cursor in the search box and open keyboard when the search icon is tapped

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5266]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3214)

Currently tapping search icon in mobile web opens the RHS but doesn't focus the cursor or open the keyboard, so an additional tap is required to perform a search.

**Comment by jasonblais** [comment]
Closed by #5284, thanks @saturninoabril!
