### ISSUE TITLE
Failing Commands Send Malformed JSON Response

### ISSUE THREAD

**Issue by aisamanra** [mattermost/platform#5282]
#### Summary

The `/api/v3/teams/{team id}/commands/execute` endpoint will send invalid JSON if an error occurs.

#### Steps to reproduce

Craft a malformed command request—for example, by omitting the `channel_id` field in the request JSON object—and post it to the `/api/v3/teams/{team id}/commands/execute` endpoint. The response will be invalid JSON of the form described below. We discovered this using our own alternate API bindings, but this can be easily tested using a browser's web developerment tools: run a command like `/me foo` in a channel, find the corresponding POST request in the 'network' tab of the web developer tools, edit the request to omit the `channel_id` field, and resend the request.

#### Expected behavior

A failing command should return a valid JSON object that describes the error.

#### Observed behavior

When a command fails with an `api.command.execute_command.save.app_error`, the response from the server contains two JSON objects appended, one that represents a successful command execution, and one that represents the error that actually happened:

```
{"response_type":"in_channel","text":"*foo*","username":"","icon_url":"","goto_location":"","attachments":null}{"id":"api.command.execute_command.save.app_error","message":"An error while saving the command response to the channel","detailed_error":"","request_id":"jsaacpkby3yg7rqhcw48d6yhwy","status_code":500}
```

The server appears to be writing the first part regardless of whether an error has happened, and then writing the error without having realized that other data has been written on the response socket.

#### Possible fixes
It looks like the `CreateCommandPost` function defined in `api/post.go` signals an error by setting the `Err` field of the provided context, but the `handleResponse` function in `api/command.go` doesn't check this error value before writing the response to the socket. Simple `if c.Err != nil` at the end of the `handleResponse` function might suffice to avoid this bug.

**Comment by jasonblais** [comment]
Thanks @aisamanra for the report! Created a Jira bug ticket here: https://mattermost.atlassian.net/browse/PLT-5437

**Comment by jasonblais** [comment]
Closing - we'll track the issue in Jira: https://mattermost.atlassian.net/browse/PLT-5437

If anyone is interested helping with a fix, please let us know!
