### ISSUE TITLE
Channel links are not rendered in channel header

### ISSUE THREAD

**Issue by akhmerov** [mattermost/platform#5286]
#### Summary
Channel links (`~channel`) are not rendered when a part of a channel header.

#### Steps to reproduce
Install mattermost 3.6.2, create a channel, edit its header, create a `~`-link, e.g. `~town-square`.

#### Expected behavior
A link to the channel is rendered

#### Observed behavior
Isn't rendered.

**Comment by jasonblais** [comment]
That's a nice catch. Created a Jira ticket here: https://mattermost.atlassian.net/browse/PLT-5436

@akhmerov we'll likely turn this into a Help Wanted issue, would you be interested helping with a fix?

**Comment by akhmerov** [comment]
@jasonblais I'd be happy to, but it isn't my expertise and therefore the time investment would be unreasonably high.

**Comment by jasonblais** [comment]
No worries! :) 

We'll see if someone else takes it, thanks for bringing this to our attention

**Comment by jasonblais** [comment]
Created a help wanted ticket here: https://github.com/mattermost/platform/issues/5289
