### ISSUE TITLE
After upgrading to 3.6.2, `platform version` still shows 3.6.0

### ISSUE THREAD

**Issue by joshaidan** [mattermost/platform#5287]
#### Summary
I noticed after upgrading to 3.6.2, when I do a `platform version` the output still shows 3.6.0.

#### Steps to reproduce
I am using version 3.6.2. To reproduce the issue type `platform version`.

#### Expected behavior
It should report version 3.6.2.

#### Observed behavior
```
Version: 3.6.0
Build Number: dev
Build Date: Thu Feb  2 17:20:34 UTC 2017
Build Hash: 1a9891f0f5671551d28be54a99155b907480cc5c
Build Enterprise Ready: false
DB Version: 3.6.0
```

#### Possible fixes
I believe the problem is here, in model/version.go:
```golang
var versions = []string{
	"3.6.0",
	"3.5.0",
	"3.4.0",
	"3.3.0",
...
}
```
I imagine it could be fixed by adding "3.6.2" to the top of the slice. If this is the case, then I can submit a PR for it if you like. I figured I'd ask first because I wasn't sure if there was some other reason "3.6.2" was not added to this slice, i.e. database versioning or something. Although, I guess if this was updated then you'd probably have to do a new release, i.e. 3.6.3.

**Comment by jasonblais** [comment]
Hey @joshaidan! I believe that represents the major version release, but I've asked our team to confirm,

**Comment by kallama** [comment]
It looks like they wanted to keep the Version value for major versions and the build number for minor. This is what mine looks like:

```
Version: 3.6.0
Build Number: 3.6.2
Build Date: Tue Jan 31 21:02:59 UTC 2017
Build Hash: 1a9891f0f5671551d28be54a99155b907480cc5c
Build Enterprise Ready: true
DB Version: 3.6.0
```

**Comment by joshaidan** [comment]
Oh okay, I see. Since I was building from source `Build Number` was showing up as `dev`, which was why I didn't see it. I dunno if it's worth somehow incorporating the minor version number somehow in source builds. Otherwise I guess this isn't a huge issue.

**Comment by jasonblais** [comment]
Thanks @joshaidan and @kallama, that's correct.

We currently use the `version` to represent major version releases, and then the `build number` for each individual release.

We might change this convention in the future however, we've been discussing about it given a few other community members have brought this up.

I'll close this issue for now though, since it's not a product defect.
