### ISSUE TITLE
[Help Wanted] [PLT-3751] Update GitLab user attributes on log in

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5288]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3751)

This ticket is to address https://github.com/mattermost/platform/issues/4171

Proposed changes:

1. When a user with GitLab SSO authentication changes their username or email in GitLab, and re-logins to Mattermost, the Mattermost username and email should update to the new GitLab username and email.

2. If the new GitLab username or email collides with an existing Mattermost username on the server, the update should use the original name.

3. Document the behavior of 1 and 2 in https://docs.mattermost.com/deployment/sso-gitlab.html

**Comment by mpoornima** [comment]
@esethna I would like to work on this. Can you please assign this to me. 

Thanks

**Comment by jasonblais** [comment]
Thanks @mpoornima, go for it! 👍

**Comment by jasonblais** [comment]
Closed via #5324, big thanks @mpoornima!
