### ISSUE TITLE
[Help Wanted] [PLT-5436] Render channel links in the channel header

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5289]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5436)

Repro:
1) Click a channel name
2) From the drop down menu, select "Edit Channel Header"
3) Paste the following: ~town-square

Observed: Header rendered as ~town-square
Expected: Header rendered as ~Town Square, which works as a channel link.

Here's start of a PR to help you get started: https://github.com/mattermost/platform/pull/5334

**Comment by pan-feng** [comment]
Want to possession of this.

**Comment by jasonblais** [comment]
Go for it! Thanks @pan-feng for your help!

**Comment by pan-feng** [comment]
link #5334

**Comment by esethna** [comment]
Reposted as a new help wanted issue (7257)
