### ISSUE TITLE
[Help Wanted] [PLT-4606] Add date separators to the right hand side to prevent dates overlapping the '...' menu on mobile right hand sidebar

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5291]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4606)

Add date separators to the right hand side (like in the center channel).

![image](https://cloud.githubusercontent.com/assets/13119842/22602734/599e7cb0-ea12-11e6-91ae-57e5d6c61fde.png)

The first date separator should appear below the channel name given at the top of right hand sidebar. Other date separators would appear if the date changes in the thread.

This prevents issues where the date can overlap with the '...' menu on mobile right hand sidebar (see below).

![image](https://cloud.githubusercontent.com/assets/13119842/22602727/525bb6b6-ea12-11e6-9dca-fff6d782d112.png)

**Comment by mikaoelitiana** [comment]
I want to work on this feature

**Comment by jasonblais** [comment]
Awesome, thanks @mikaoelitiana! Go for it 👍

**Comment by mikaoelitiana** [comment]
I came up with something like this: 

<img width="343" alt="capture d ecran 2017-02-09 a 20 08 58" src="https://cloud.githubusercontent.com/assets/674667/22794285/b7818af2-ef03-11e6-91af-89645ce8cda9.png">

**Comment by mikaoelitiana** [comment]
PR created
