### ISSUE TITLE
[Help Wanted] [PLT-1383] Infinite scroll

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5292]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1383)

When scrolling to the top of a channel, automatically load the previous messages instead of showing "Load more messages" link.

This essentially auto-clicks the link when the scroll gets close to the top of the channel.

Expected behaviour:
1. Scroll up to see previous messages
2. Text `Loading more messages...` appears
3. Text disappears and messages are loaded

See this PR to help you get started: https://github.com/mattermost/platform/pull/5303

**Comment by pan-feng** [comment]
I had do this one.

**Comment by pan-feng** [comment]
#5303

**Comment by VeraLyu** [comment]
Since there hasn't been any update on related PR, I would like to take this one if no one else is working on it.

**Comment by jasonblais** [comment]
Thanks @VeraLyu! 👍

**Comment by VeraLyu** [comment]
Hi, @jasonblais,
1. do we want to change previous animated scroll icon to string?
2. Despite "Load more messages" link on top, we still have "Load more messages" link at bottom, I suppose we want that one also get fixed in this issue, right?

**Comment by jasonblais** [comment]
Hey @VeraLyu! 

1 - That's correct -- the PR #5303 had a loading animation but propose we have a text `Loading more messages...` appears for now. It might be difficult to get the loading animation working smoothly on slow connections.
2 - Do you mean the "Load more messages" link that appears in permalink/archived view? If it's not too much work, then yes it would be good to fix it at the same time. Good catch.
