### ISSUE TITLE
[Help Wanted] Error when installing

### ISSUE THREAD

**Issue by Purplee** [mattermost/platform#5293]
Hi everybody !

I try installing mattermost with : https://docs.mattermost.com/install/prod-debian.html#production-install-on-debian-jessie and I have this error when I come to 7.Test the Mattermost Server : 

`sudo -u mattermost ./platform
./platform: 1: ./platform:ELF: not found
./platform: 2: ./platform: Syntax error: "(" unexpected
`
I'm running on debian wheezy with a i686 processor

Thank you in advance for your answer !

**Comment by Purplee** [comment]
Ohhh sorry

I posted on the forum !

**Comment by jasonblais** [comment]
No worries! :) 

Thanks for posting in the forums 👍
