### ISSUE TITLE
Feature Request: Admin Console to change settings after system is launched and deployed

### ISSUE THREAD

**Issue by benoitc** [mattermost/platform#530]
It seems that even in dev mode we need to go in the docker shell to edit the file. Would be cool if we can set it up before like discourse does.

**Comment by it33** [comment]
Hi @benoitc, the upcoming Admin Console is designed to let you change config settings after the system is deployed: https://mattermost.atlassian.net/browse/PLT-10. Would this address your issue?

**Comment by benoitc** [comment]
@it33 :+1: it should definitely fix the issue :)

**Comment by coreyhulen** [comment]
This is in master and will be part of 0.8 (https://github.com/mattermost/platform/pull/752).  FYI, the config file has changed significantly.
