### ISSUE TITLE
Channel posts won't load, error in logs `no fields [editat] in type Post`

### ISSUE THREAD

**Issue by aparcar** [mattermost/platform#5312]
#### Summary
Channel posts won't load, error in logs `no fields [editat] in type Post`

#### Steps to reproduce
Using Mattermost 3.6.2 with Postgresql

#### Expected behavior
Loading any channel results in infinite showing "Loading ..." without any progress. 
Log says 
```
[2017/02/06 16:03:48 CET] [EROR] /api/v3/teams/xyz/channels/xzy/posts/page/0/60:SqlPostStore.GetLinearPosts code=500 rid=foo uid=bar ip=139.xxx, 192.xxx Die Nachrichten für den Kanal konnten nicht abgerufen werden [Details: channelId=xyz: no fields [editat] in type Post]
```
#### Possible fixes
It worked for about a week, maybe a re-installation would fix the issue but I don't want to delete all chat logs.

**Comment by aparcar** [comment]
editat seems to be in the `mattermost` database, even tho the value is for every entry `0`

**Comment by aparcar** [comment]
the `channelId=` is different from the channel id in the api requests, is that correct?

**Comment by hmhealey** [comment]
Hi @aparcar, were you running off the master branch at any point? That `EditAt` column shouldn't exist in 3.6, so you're safe to delete the column by connecting to the database and running `ALTER TABLE posts DROP COLUMN editat`. After it's gone, your issue should be fixed.

**Comment by aparcar** [comment]
Indeed I did build `platform` but did a regular master pull, not using any other branch.
However, the command fixed the issue, thank you so much!
