### ISSUE TITLE
BUG: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by senk** [mattermost/platform#5323]
#### Summary
Problems when using `platform`-Commands in Gitlab-Mattermost
#### Steps to reproduce
Gitlab-Mattermost:
```
root@mattermost:~# sudo gitlab-rake gitlab:env:info


System information
System:
Current User:	git
Using RVM:	no
Ruby Version:	2.3.3p222
Gem Version:	2.6.6
Bundler Version:1.13.7
Rake Version:	10.5.0
Sidekiq Version:4.2.7

GitLab information
Version:	8.16.3
Revision:	d225908
Directory:	/opt/gitlab/embedded/service/gitlab-rails
DB Adapter:	postgresql
URL:		http://mattermost.fh-muenster.de
HTTP Clone URL:	http://mattermost.fh-muenster.de/some-group/some-project.git
SSH Clone URL:	git@mattermost.fh-muenster.de:some-group/some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	4.1.1
Repository storage paths:
- default: 	/var/opt/gitlab/git-data/repositories
Hooks:		/opt/gitlab/embedded/service/gitlab-shell/hooks/
Git:		/opt/gitlab/embedded/bin/git
```
Debian 8:
`Linux mattermost 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux`

To Reproduce:
`sudo -u mattermost ./mattermost -config=/var/opt/gitlab/mattermost/config.json version`
#### Expected behavior
Version Info without seg violation
#### Observed behavior
```
root@mattermost:/opt/gitlab/embedded/bin# sudo -u mattermost ./mattermost -config=/var/opt/gitlab/mattermost/config.json version
Version: 3.6.0
Build Number: 3.6.1
Build Date: Thu Jan 19 20:03:23 UTC 2017
Build Hash: 0d8bb03b5773923cf52f4d8cb2711131caae105c
Build Enterprise Ready: false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41a6c8]
```
#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by lindy65** [comment]
Hi @senk 

Thank you for the report!

Please try upgrading to the latest version of the omnibus package as it contains the 3.6.2 update, and circle back to let us know whether that solved your issue?

Thanks :)

**Comment by ulab** [comment]
Updated the debian gitlab-ce package, still get the runtime error:

```
root@mattermost:/opt/gitlab/embedded/bin# sudo -u mattermost ./mattermost -config=/var/opt/gitlab/mattermost/config.json version
Version: 3.6.0
Build Number: 3.6.2
Build Date: Tue Jan 31 21:01:44 UTC 2017
Build Hash: 1a9891f0f5671551d28be54a99155b907480cc5c
Build Enterprise Ready: false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41a6e8]

goroutine 1 [running]:
panic(0xbde860, 0xc420016090)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.printVersion()
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/version.go:29 +0x428
main.versionCmdF(0x106d4c0, 0xc4200c4750, 0x0, 0x1)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/version.go:20 +0x30
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0x106d4c0, 0xc4200c46f0, 0x1, 0x1, 0x106d4c0, 0xc4200c46f0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:636 +0x443
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200c2240, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200c2240, 0xc4200c4490, 0xb)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/mattermost.go:50 +0x49f
```

**Comment by bjorges** [comment]
I also see this problem. I use the tar-install, not omnibus.

# sudo -u mattermost /opt/mattermost/bin/platform version
Version: 3.6.0
Build Number: 3.6.2
Build Date: Tue Jan 31 21:02:59 UTC 2017
Build Hash: 1a9891f0f5671551d28be54a99155b907480cc5c
Build Enterprise Ready: true
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41a6e8]

goroutine 1 [running]:
panic(0xc9dae0, 0xc42000e0b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.printVersion()
        /home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/cmd/platform/version.go:29 +0x428
main.versionCmdF(0x119f020, 0x11c5cb0, 0x0, 0x0)
        /home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/cmd/platform/version.go:20 +0x30
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0x119f020, 0x11c5cb0, 0x0, 0x0, 0x119f020, 0x11c5cb0)
        /home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:636 +0x443
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420808480, 0x0, 0x0, 0x0)
        /home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420808480, 0xc4201336b0, 0xb)
        /home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
        /home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/cmd/platform/mattermost.go:50 +0x49f

**Comment by jasonblais** [comment]
Thanks everyone! We've created a bug ticket here to investigate: https://mattermost.atlassian.net/browse/PLT-5682

**Comment by jasonblais** [comment]
@senk @ulab @bjorges 

Actually, one of our developers responded back, saying the platform command needs to be started from the mattermost directory. So the command should look like `./bin/platform`. Can you try running the command like that?

We have an on-going conversation here to clarify it in our CLI documentation [link to GitHub thread](https://github.com/mattermost/docs/pull/949/files/b14b9a210291b5834eed8583cdac5532865d7c3b#r104254041)

**Comment by ulab** [comment]
The thread mentioned that you need to add the path like we did above `... ./mattermost ...`. We also used sudo to switch to the mattermost user.

Ok, I did an update to gitlab-ce (8.17.2-ce.0) from (8.17.1-ce.2) today and tried again with `... ./bin/mattermost ...` and I got similar results:

````
root@mattermost:/opt/gitlab/embedded# sudo -u mattermost ./bin/mattermost -config=/var/opt/gitlab/mattermost/config.json version
Version: 3.6.0
Build Number: 3.6.2
Build Date: Tue Jan 31 21:01:44 UTC 2017
Build Hash: 1a9891f0f5671551d28be54a99155b907480cc5c
Build Enterprise Ready: false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41a6e8]

goroutine 1 [running]:
panic(0xbde860, 0xc420016090)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.printVersion()
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/version.go:29 +0x428
main.versionCmdF(0x106d4c0, 0xc4200c0750, 0x0, 0x1)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/version.go:20 +0x30
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0x106d4c0, 0xc4200c06f0, 0x1, 0x1, 0x106d4c0, 0xc4200c06f0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:636 +0x443
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200fa240, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200fa240, 0xc4200c0490, 0xb)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/mattermost.go:50 +0x49f
root@mattermost:/opt/gitlab/embedded# ls -l bin/mattermost 
-rwxr-xr-x 1 root root 20953831 Mar  1 13:55 bin/mattermost
root@mattermost:/opt/gitlab/embedded# ls -l /var/opt/gitlab/mattermost/config.json 
-rw-r--r-- 1 mattermost root 5430 Feb 23 10:48 /var/opt/gitlab/mattermost/config.json
````

**Comment by jasonblais** [comment]
@ulab For those on GitLab omnibus, [this](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1015#note_22576761) is how you actually invoke the `platform` command. Example:

```
sudo -u mattermost /opt/gitlab/embedded/bin/mattermost --config=/var/opt/gitlab/mattermost/config.json
```

We really should make this more clear in our docs, I'll take care of that with https://github.com/mattermost/docs/pull/949

**Comment by jasonblais** [comment]
Let me know if that doesn't work?

**Comment by ulab** [comment]
That's better :)

```
# sudo -u mattermost /opt/gitlab/embedded/bin/mattermost --config=/var/opt/gitlab/mattermost/config.json version
Version: 3.6.0
Build Number: 3.6.2
Build Date: Tue Jan 31 21:01:44 UTC 2017
Build Hash: 1a9891f0f5671551d28be54a99155b907480cc5c
Build Enterprise Ready: false
DB Version: 3.6.0
```

Unless you forget the "version" command at the end, which results in (a different issue) :):
```
# sudo -u mattermost /opt/gitlab/embedded/bin/mattermost --config=/var/opt/gitlab/mattermost/config.json 
panic: Failed to load system translations for 'en'

goroutine 1 [running]:
panic(0xba53e0, 0xc42080edf0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mattermost/platform/utils.GetTranslationsBySystemLocale(0x26)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/utils/i18n.go:50 +0x374
github.com/mattermost/platform/utils.InitTranslations(0xc4200c1b40, 0xc4200c1b60, 0xc4200c1b70)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/utils/i18n.go:27 +0x54
main.runServer(0x7ffe88c7086c, 0x26)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/server.go:56 +0x92
main.runServerCmd(0xc4200fa240, 0xc4200c0710, 0x0, 0x1, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/server.go:46 +0x8c
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200fa240, 0xc42000c1d0, 0x1, 0x1, 0xc4200fa240, 0xc42000c1d0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:632 +0x23e
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200fa240, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200fa240, 0xc4200c0490, 0xb)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/mattermost.go:50 +0x49f
```

**Comment by jasonblais** [comment]
Ah sorry -- yes, if you want to invoke the `platform version` command, you'll need the `version` at the end.. That'll be the same for the other CLI commands

Glad that worked @ulab

**Comment by jasonblais** [comment]
Thanks all! We've updated our docs to be more specific on how to run the platform commands: https://docs.mattermost.com/administration/command-line-tools.html#mattermost-3-6-and-later

This includes a note on how to run them on GitLab omnibus

![image](https://cloud.githubusercontent.com/assets/13119842/23997370/7926e182-0a27-11e7-9d67-608f34f92f5f.png)
