### ISSUE TITLE
Backspace returns to previous page when focus is not in the input field

### ISSUE THREAD

**Issue by oerdnj** [mattermost/platform#533]
MM-0.6.0 (GitLab Mattermost)

Pressing backspace will invoke a browse back in the browser history when the focus is not in the input field.

How to reproduce:
1. click elsewhere in the page to lose focus from the input box
2. press Backspace
3. default browser behavior is executed

The fix should probably be more generic (inspired by Slack) - anything you type on the page (excluding shortcuts) should go straight into input field instead of losing that typed text.

**Comment by it33** [comment]
Thanks @oerdnj, queued for fix: https://mattermost.atlassian.net/browse/PLT-43

**Comment by coreyhulen** [comment]
Fix in master and will ship with 0.8 (https://github.com/mattermost/platform/pull/778)
