### ISSUE TITLE
Unable to find team for deletion

### ISSUE THREAD

**Issue by tejasbubane** [mattermost/platform#5336]
#### Summary
`platform` CLI cannot find team for deletion although it can be seen in System Console.

#### Steps to reproduce
I am using [mattermost-docker](https://github.com/mattermost/mattermost-docker) (using docker-compose). Run the following command:

```shell
docker-compose exec app "bash"
```

This will attach to the running container and open up a prompt:

```shell
root@0e397e3cb03c:/mattermost# cd mattermost

root@0e397e3cb03c:/mattermost# ls bin
platform

root@0e397e3cb03c:/mattermost# bin/platform --version
---------------------------------------------------------------------------------------------
DEPRECATED! All previous commands are now deprecated. Run: platform help to see the new ones.
---------------------------------------------------------------------------------------------
Version: 3.6.0
Build Number: 3.6.2
Build Date: Tue Jan 31 21:01:44 UTC 2017
Build Hash: 1a9891f0f5671551d28be54a99155b907480cc5c
Build Enterprise Ready: false
DB Version: 3.6.0
```

#### Expected behavior
The team is visible in the System Console. So CLI should be able to delete it.

![screen shot 2017-02-08 at 1 20 31 pm](https://cloud.githubusercontent.com/assets/980783/22727963/82e9de5a-ee01-11e6-91ea-06052384e3f2.png)

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

```
root@0e397e3cb03c:/mattermost# bin/platform team delete 2SPD
Have you performed a database backup? (YES/NO):
YES
Are you sure you want to delete the teams specified?  All data will be permanently deleted? (YES/NO):
YES
Unable to find team '2SPD'
```

#### Possible fixes
---

**Comment by jasonblais** [comment]
@tejasbubane 

1. Does it reproduce for other teams as well? If you don't want to delete another existing team, you can create a test team and try deleting that one.

2. What is the team URL for the team? What happens if you do `platform team delete {team_url}` where {team_url} is the URL for 2SPD.?

**Comment by lfbrock** [comment]
I made an issue in docs repo to document this better, I think using the team name doesn't work and you need to use the team portion of the URL or the team ID.

**Comment by tejasbubane** [comment]
![screen shot 2017-02-20 at 10 36 29 pm](https://cloud.githubusercontent.com/assets/980783/23135111/4c9619d4-f7bd-11e6-89c4-56242c9d1f1d.png)

This is what I saw in the system console, I am not sure which of these is ID since I did not create this team. Using `2spd` for delete command did not work but `s2pd` did work.

**Comment by jasonblais** [comment]
Ah yes, "2spd" is the team name but "s2pd" is the team URL. We'll update the docs + we're looking into updating the team pages in System Console to make them easier to use for System Admins.

I'll close this issue for now,
