### ISSUE TITLE
Team Members are able to delete Channels

### ISSUE THREAD

**Issue by senk** [mattermost/platform#5338]
#### Summary
In current Master f1c9ae5
Team Members are able to delete Channels which
* are not created by them
* have active users

without the appropriate rights

#### Steps to reproduce
1. Start Server
2. Create Admin-User
3. Create new channel as Admin
4. Retrieve Team Invitation Link via Menu
5. Open Incognito-Tab with Link 
6. Create User
7. Delete newly created Channel while admin still in it
#### Expected behavior
Team member is not able to delete channel with users in it, not created by him, without admin rights
#### Observed behavior
Team member is able to delete channel

**Comment by it33** [comment]
The intended design is for Team Edition is that any team member to archive a channel and any team member to restore an archived channel, the problem is there was a set back in the UI design: https://github.com/mattermost/platform/issues/4756
