### ISSUE TITLE
RestrictCreationToDomains not applied when using Google OAuth for login

### ISSUE THREAD

**Issue by donjuma** [mattermost/platform#5339]
#### Summary
Using Mattermost EE for Google OAuth login, it does not respect the restricted domain. Anyone using any email can still create an account. Even setting "EnableUserCreations" to false still allows anyone with a gmail account to create an account and login. It should only work for the given domain name.

#### Steps to reproduce
Mattermost Enterprise Edition Version 3.6
Enable Google OAuth for login.
In system console, enter "example.com" as value for RestrictCreationToDomains.
Set "Enable Account Creation" to false.

Visit mattermost from another machine that is logged into a personal gmail account (example@gmail.com)
Press "Sign in with Google"
An account will be created for your email and you will be authenticated.

#### Expected behavior
The expected behavior is that when you press "Sign in with Google", if you are attempting to authentication from a domain other than the whitelisted one, it should fail. It should not create an account for you, nor log you into the system.
Further, if "Enable Account Creation" is set to false, it should not allow any new accounts to be created, regardless of domain.

#### Observed behavior
Our Mattermost instance is open to the web but behind Google OAuth. We observed a random account that joined our team and it was associated with a personal gmail account. Not with a domain whitelisted account.
Upon disabling all account creation, we were still able to get in using a personal email account by pressing "Sign in with Google"

**Comment by lfbrock** [comment]
Hi @donjuma, thanks for bringing this up - we have a ticket here to add restricting sign ups from SSO domains: https://mattermost.atlassian.net/browse/PLT-3744

I just made it into a help wanted ticket to see if we can find someone to work on it. 

The Enable Account Creation sounds like a bug, @lindalu can you reproduce the issue and file a Jira ticket for it?

**Comment by lindalu** [comment]
Thanks, @lfbrock, I reproduced the issue and filed ticket https://mattermost.atlassian.net/browse/PLT-5473.

**Comment by jasonblais** [comment]
Thanks all! We'll track the issues here:
 - restricting sign ups from SSO domains: #5356 
 - enable account creation bug: https://mattermost.atlassian.net/browse/PLT-5473.
