### ISSUE TITLE
Referencing user with lowercased full name doesn't work

### ISSUE THREAD

**Issue by jmayday** [mattermost/platform#5350]
#### Summary
Referencing user with lowercased full name doesn't work

#### Steps to reproduce
Let's assume that you have buddy with name "Bruce Lee" with login @bl7000.
Try to reference him:
@bl (works - user appears on dropdown list)
@bruce (also works)
@Bruce (doesn't work)

#### Expected behavior
Expected is that autosuggestion works also for @Bruce

#### Observed behavior
Screenshots below
![by_login](https://cloud.githubusercontent.com/assets/10167533/22782275/92526aea-eec6-11e6-8c2a-199c762080ed.png)
![by_name_capitalized](https://cloud.githubusercontent.com/assets/10167533/22782274/924f0fa8-eec6-11e6-865e-ffa33a8b9d1e.png)
![by_name_lowercased](https://cloud.githubusercontent.com/assets/10167533/22782273/924cfb8c-eec6-11e6-938a-d5cb27f02abb.png)

#### Possible fixes
I believe lowercasing should take place on both names of users and text appearing after '@' sign when searching and suggesting items on list.

**Comment by jasonblais** [comment]
Thanks @jmayday! Which Mattermost server version do you have?

You can find this information from Mattermost Main Menu > About Mattermost

![image](https://cloud.githubusercontent.com/assets/13119842/22790802/637d6000-eeb5-11e6-8a04-d05f9a9fc492.png)
![image](https://cloud.githubusercontent.com/assets/13119842/22790813/6c291258-eeb5-11e6-91cf-125feddf7990.png)

**Comment by jmayday** [comment]
Version: 3.5.0  (3.5.1)

**Comment by jasonblais** [comment]
Ah yes, this was an issue with our v3.5.0 release.

In Mattermost v3.6.2, auto-complete works for both upper and lowercase letters.

You can download the latest version here: https://about.mattermost.com/download/

**Comment by jmayday** [comment]
@jasonblais - confirmed! there's nothing more from my side.

**Comment by jasonblais** [comment]
Glad to hear! 👍
