### ISSUE TITLE
[Help Wanted] [PLT-5445] Mobile view: Set focus back to message box after uploading a file

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5354]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5445)

Repro: 

1) In Mattermost, upload a file attachment in mobile view
2) Hit Enter

Observed: No action
Expected: After uploading the file, focus is set back to the message box (as it does on desktop view) and hitting Enter posts the message.

**Comment by saturninoabril** [comment]
#5360
