### ISSUE TITLE
[Help Wanted] [PLT-5440] Add several Team Site Main Menu options to the System Console Main Menu

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5355]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5440)

System Console Main Menu lacks some basic controls available in Team Site Main Menu. This ticket is to improve the experience 

Currently, System Console Main Menu shows: 

```
Switch to [TEAM]
----
Logout 
```

![image](https://cloud.githubusercontent.com/assets/177788/22297375/ec175fb4-e2d1-11e6-8f2b-58d127ec9b95.png)

Propose we update System Console Main Menu to: 
```
Switch to [TEAM]
----
Administrator's Guide
Troubleshooting Forum
Commercial Support 
About Mattermost 
----
Logout 
```

DETAILS ON LINKS:

1. `Administrator's Guide` - link to: https://about.mattermost.com/administrators-guide/
2. `Troubleshooting Forum` - link to: https://about.mattermost.com/troubleshooting-forum/
3. `Commercial Support` - link to: https://about.mattermost.com/commercial-support/
4. `About Mattermost` - brings up About Mattermost dialog

**Comment by R-Wang97** [comment]
I can take a look at this!

**Comment by jasonblais** [comment]
Thanks @R-Wang97! This is now resolved,
