### ISSUE TITLE
[Help Wanted] [PLT-3744] Restrict user creation via OAuth (GitLab/Google/Office365) to accepted domains

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5356]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3744)

Current situation:

If a domain is specified in *System Console > Users and Teams > Restrict account creation to specified email domains*, this restriction only applies to emails.

Example: if an admin sets a restricted domain to be "mattermost.com",
  - a user creating an account with email/password can only created it for an account in the "mattermost.com" domain
  - a user creating an account with GitLab/Google/Office365 has no restriction and can create it for any domain

Proposed change: 

Apply the *Restrict account creation to specified email domains* setting for GitLab/Google/Office365 SSO. If the restricted domain is set to "mattermost.com" then a user must have a GitLab/Google/Office365 account pointing to that domain when creating an account.

NOTE: Propose not to apply this setting for LDAP/SAML auth. No other place allows you to restrict login to specific email domains if LDAP or SAML is enabled. Also, the user must belong to the AD or SAML IDP organizations for the auth to be successful, so the admin already has control who has access to their instance.

**Comment by ccbrown** [comment]
I'll take this one.

**Comment by ivernus** [comment]
Can this be closed?

**Comment by jasonblais** [comment]
Yep! This is resolved thanks to @ccbrown
