### ISSUE TITLE
[Help Wanted] [PLT-3193] Add channel notification preferences for push notifications

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5357]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3193)

Currently channel notification settings only apply to desktop notifications. 

Expected: Add push channel notification settings.

Add a setting for: 

Title: **Send mobile push notifications**

[ x ] Global default ([whatever_is_set_in_account_settings])
[ ] For all activity
[ ] Only for mentions
[ ] Never

Help text: Selecting an option other than "Global default" will override the global notification settings for mobile push notifications in account settings. Push notifications must be enabled by the System Admin.

**Comment by jasonblais** [comment]
This feature is now added and will be available in 3.7
