### ISSUE TITLE
[Help Wanted] [PLT-5467] Add a CLI tool for validating the config.json file

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5358]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5467)

Add a CLI tool `platform check` that verifies the config file:
- is valid json
- has attributes of the correct type (eg bool, int, str)
- makes sure all entries are valid (eg checks that entries are below the max length)

NOTE: The CLI tool is referring to the Mattermost command line tool https://docs.mattermost.com/administration/command-line-tools.html

**Comment by simon0191** [comment]
@grundleborg @esethna what do you think about using JSON schema to validate the config file?
This library can be used: https://github.com/xeipuuv/gojsonschema. The upside is that JSON schema is perfectly suited for this problem, the downside is that including this library may increase considerably the size of the binary.

**Comment by jasonblais** [comment]
Thanks @simon0191 for the suggestion -- when you say `may increase considerably`, how much might it increase?

**Comment by grundleborg** [comment]
@simon0191this sounds like it could be a good idea. I think it's worth getting some feedback from others on the core team before we commit to this approach though, so I've queued it to discuss at the next public developer meeting (Wednesday at 10am San Francisco time). If you'd like to join us at the meeting, you can see the agenda and the link to the Hangout on our Mattermost instance [here](https://pre-release.mattermost.com/core/channels/developers-meeting). If not, don't worry - I'll add a comment to this ticket after the discussion.

**Comment by simon0191** [comment]
@jasonblais @grundleborg I did a quick implementation to see how much would increase the binary size. Here's the implementation with a sample `config.schema.json`: https://github.com/simon0191/platform/commit/c9405496ab67b94d5a0e79826aef01af20eec14c

I built the project before and after adding the gojsonschema dependency and the size increased almost 1M:

- platform_before: 21882572B or 21M
- platform_after: 22544908B or 22M

What do you think?

**Comment by grundleborg** [comment]
@simon0191 thanks very much for investigating that so thoroughly. I'll add that to the item we're going to discuss at Wednesday's dev meeting, but I doubt the extra megabyte will be a big deal.

**Comment by grundleborg** [comment]
Hi @simon0191 . Thanks very much for your efforts so far looking into this ticket! We discussed using JSON schema in the meeting today, but we weren't really sure that it added anything over just hooking the proposed CLI command into the [existing config validation code](https://github.com/mattermost/platform/blob/master/model/config.go#L1164), and in some places it might not be able to replicate the existing validation logic where it spans multiple fields.

Does this make sense, or are we missing something important it can offer in this situation? If you'd like to discuss this more you can find us in the `Developers` channel on our [Mattermost Instance](https://pre-release.mattermost.com/core/channels/developers) - you are very welcome to come and join us there!

**Comment by simon0191** [comment]
@grundleborg It makes sense, I wasn't aware of the existing config validation code.

**Comment by jasonblais** [comment]
Resolved by @simon0191 via #6041. Big thanks! 👍
