### ISSUE TITLE
i18n: french translation issue for the invitation email

### ISSUE THREAD

**Issue by tuxayo** [mattermost/platform#5364]
https://github.com/mattermost/platform/blob/e47918e8cabe0bd6a391b043f494633b6317e241/i18n/fr.json#L2084

The current phrasing is:

> L'équipe membre Jane Doe, vous a invité à rejoindre team_name.

- saying "L'équipe membre" is incorrect.

- a linking word would be necessary between "rejoindre" and team_name which would depend on team_name...

A correct but still enhanceable phrasing is:

> Jane Doe, membre de l'équipe team_name vous invite à rejoindre son équipe.

It's a bit redundant but it's correct and is correct regardless of the team name and the gender of the member sending the invitation (a less redundant phrasing would end with;: "to join her/him").

**Comment by jasonblais** [comment]
@wget any thoughts on this suggestion?

**Comment by wget** [comment]
@tuxayo Thanks for the hint. Actually the French translation has still a lot of issues when checked in context. This is sometimes related to variables in translation strings I don't know to what they are referring (actually the issue for this current bug).
But this is now corrected. :) Merci.
![screenshot_20170211_175543](https://cloud.githubusercontent.com/assets/2997662/22855599/7a0dcc7c-f083-11e6-8ac2-018f7ad67b65.png)

**Comment by wget** [comment]
@jasonblais You can now close the issue :)

**Comment by jasonblais** [comment]
Thanks @tuxayo and @wget!

**Comment by tuxayo** [comment]
@wget great, it seems that you found a better wording! Thanks! :)

**Comment by wget** [comment]
@tuxayo If you do find other spelling or context translation mistakes, don't hesitate to ping us :)
