### ISSUE TITLE
use the languages defined in the browser preferences

### ISSUE THREAD

**Issue by klischka** [mattermost/platform#5365]
#### Summary
When I send the link for team registration for the Mattermost installation on https://framateam.org/ my users see the site in French. The speak German.

#### Steps to reproduce
Version: 3.6.0  (3.6.1)
Datenbank: postgres

#### Expected behavior
Users should see the German or English translation. This are the languages my future users in the group use. The majority of users on framateam.org speaks French though.

#### Observed behavior
No error, it is the normal behaviour of Mattermost I suppose - but this is not a very good solution. The problem is that the default language is defined on the server configuration file for everyone.

#### Possible fixes
Use the languages defined in the browser preferences to show pages in that language.

**Comment by lindy65** [comment]
Hi @klischka 

Thank you for the report :)

Agree that languages can be frustrating and we're working towards a solution.  Could I ask your help to take a look at this [feature suggestion](https://mattermost.uservoice.com/forums/306457-general/suggestions/16821181-add-option-to-set-multi-team-team-or-server-wide-d) where you can discuss and add your thoughts on default team languages?  

Others can up-vote the suggestion and the more popular a feature becomes, the better chance it has of being added to the roadmap and becoming a feature in Mattermost.

Appreciate your contribution and interest!
