### ISSUE TITLE
[Help Wanted] [PLT-5342] Move "Start Video Call" option to the bottom of the profile popover

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5367]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5342)

When clicking on the profile picture in center channel or right-hand sidebar, a profile popover opens.

Current situation: A small video icon is displayed on the top right corner of the popover
 - it's small and hard to identify
 - it can overlap with a long username

Proposed change: Add a new "Start Video Call" option below "Send Message" at the bottom of the profile popover. See screenshot for an example.

![image](https://cloud.githubusercontent.com/assets/13119842/22858089/a60ef5be-f081-11e6-81bb-e68ffc91c79c.png)

Attached [in the Jira ticket you can also find a file for the design](https://mattermost.atlassian.net/browse/PLT-5342), called "popover.afdesign"

**Comment by jasonblais** [comment]
Closed via #5853, thanks @Rudloff!
