### ISSUE TITLE
[Help Wanted] [PLT-5267] After posting a message containing an image link, only show the link and add the image preview once it has fully loaded, if one is available

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5368]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5267)

As shown on the attached GIF, having an image preview can be problematic - when there's no image to load, the placeholder initially appears, then collapses afterwards. It's confusing to the end user and not a great experience. 

https://cloud.githubusercontent.com/assets/14333569/21528850/99948dba-ccf2-11e6-9692-1a953e3d0fb3.gif

Proposed change:

After posting a message containing an image link, only show the link and add the image preview once it has fully loaded, if one is available, and do not use a placeholder for the preview.

If the user is at the bottom of the channel, the user should stay there after the image preview has loaded on the channel.

**Note from a developer**:

To keep the channel scrolled to the bottom, we need some way to call the PostList.updateScrolling method whenever a markdown image is loaded.

The `markdownImageLoaded` function in markdown.jsx is called whenever an image is loaded, but we have no way for it to call back to the PostList when that happens. We need to figure out a way to do this, hopefully without a global function like the one that we currently have.

**Comment by VeraLyu** [comment]
Hi, may I take this one?

**Comment by jasonblais** [comment]
Absolutely! That would be awesome 👍
