### ISSUE TITLE
Blank page displayed instead of error message if Mattermost can't set cookies

### ISSUE THREAD

**Issue by graphiclunarkid** [mattermost/platform#5374]
#### Summary

Users who don't allow http://gitlab.mattermost.com to set a cookie see a blank page instead of the intended error message. The message that is supposed to appear refers to Private Browsing however users should see a message telling them to allow cookies for the domain instead.

- Mattermost version: 3.6.0  (3.6.2)
- Build Hash: 1a9891f0f5671551d28be54a99155b907480cc5c
- EE Build Hash: none
- Build Date: Tue Jan 31 21:01:44 UTC 2017

#### Steps to reproduce

1. Disable cookies for gitlab.mattermost.com
2. Visit http://demo.mattermost.com/

#### Expected behavior

Browser redirects to https://gitlab.mattermost.com/error?title=Browser%20not%20supported&message=Private%20browsing%20is%20not%20supported and shows the following page:

![screenshot from 2017-02-12 18-26-37](https://cloud.githubusercontent.com/assets/433456/22864379/b4877916-f150-11e6-9eb1-f184a2e09692.png)

#### Observed behavior

The URL bar reflects the redirect however the browser displays a blank page.

The message that's intended to be displayed is "Private browsing is not supported" however this isn't accurate. Although Mattermost doesn't work in a Firefox Private Window it seems to work fine in Chrome's Incognito mode.

Observed using Ubuntu 16.04 in:

- Firefox 51.0.1 (64-bit)
- Chrome 55.0.2883.87 (64-bit)

#### Possible fixes

The error message should (a) display, and (b) instruct users to allow the domain to set cookies.

[Error message location](https://github.com/mattermost/platform/blob/a6d6880d998724028ff644754a1ccce91c77ed2c/webapp/stores/browser_store.jsx#L9)

**Comment by lfbrock** [comment]
Hi @graphiclunarkid - thanks for the report! 

It looks like disabling cookies also disables localStorage and sessionStorage, which the site needs to run (we originally noticed this with private browsing on Safari, which is why the error page text refers to private browsing). 

We'll figure out some better text for that error page since the current text is inaccurate. I'll post back here with a ticket/PR once it's figured out.

**Comment by lfbrock** [comment]
Ended up making a Jira ticket to create a new error page there: https://mattermost.atlassian.net/browse/PLT-5702

Closing this + will track in Jira
