### ISSUE TITLE
[Help Wanted] [PLT-4066] Account settings has blank space when switching settings

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5388]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4066)

Repro: 

1. Go to: Account Settings > Notifications > Desktop notifications 
2. Scroll down and click "Email notifications

Observed: 

Video from wget reproducing the bug: https://youtu.be/Hy96zQrvUJ0

![image](https://cloud.githubusercontent.com/assets/13119842/22894947/bee245ec-f1e8-11e6-8efc-abed34d5656e.png)

NOTE: Please use react rather than jquery when implementing the fix. This might involve some refactoring as well.

**Comment by jasonblais** [comment]
We're planning to redesign the Account Settings modal so not worth fixing this issue at the moment
