### ISSUE TITLE
Android App Performance Slow

### ISSUE THREAD

**Issue by realrolfje** [mattermost/platform#5397]
**Summary:**
The Android app has a longer load time and is more sluggish than opening Mattermost in a web browser on the same device. This is particularly painful when receiving a push notification, since this opens the app and not the web browser.

**Steps to reproduce:**
1. Install the Mattermost reference implementation App from the Google Play store on a Samsung Galaxy S3 or S7.
2. Configure the app to connect to an existing Mattermost installation
3. Close the app and lock the phone.
4. Recieve a push notification.

**Expected Behavior:**
Upon swiping the push notification, the Mattermost App on Android should show a usable userinterface in less than 2 seconds.

**Observed Behavior:**
Opening the app from the Push notification takes more than 10 seconds to load on an S3. On an S7 more than 5 seconds.

Compare with browser login:
- Opening the same Mattermost server in a webbrowser shows a usable interface in less than 3 seconds.
- Opening the same Mattermost server in the iOS app takes less than 3 seconds.
- It also seems that the Android App does not stay "resident", it restarts each time the application is loaded.

**Possible fixes:**
I am guessing that the performance can be caused by one or more of the following:
The Android app does not seem to stay resident.
The Android app does not cache static resources efficiently.
The Android app uses a different javascript/rendering engine than the built-in browser on the phone.

**Comment by lfbrock** [comment]
Hi @realrolfje - We're working on building a [new Android app](https://github.com/mattermost/mattermost-mobile) to improve performance. 

It's a work in progress and only has basic features so far, but anyone who would like to help test is welcome to follow the instructions here: https://github.com/mattermost/mattermost-mobile#testing

**Comment by realrolfje** [comment]
Thanks! I've forwarded your comment to our Android users, you may get some extra testers the coming week.
