### ISSUE TITLE
[Help Wanted] APIv4: GET /teams/name/{name}

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5414]
If you're interested please comment here and come [join our "APIv4" community channel](https://pre-release.mattermost.com/core/channels/apiv4) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [APIv4 contribution process](https://docs.mattermost.com/developer/api4.html) to help get you started.

----

**Difficulty**: Introductory

**Details**:

[Mattermost is moving to APIv4 in the next server release](https://forum.mattermost.org/t/mattermost-moving-to-api-version-4/2830) and we're looking for contributors to code server endpoints, build drivers and write documentation. [You can find the detailed APIv4 specification here](https://docs.google.com/document/d/197JwEBMnK8okFilTfGSpbsrXPY5RZOJ4gG2DXwcbwYE/edit).

This Help Wanted issue is to add a new APIv4 endpoint for `GET /teams/name/{name}`, which gets a team by name. The `response` should be `Team` and `permission` should be `Team type is open, or have "view_team"`.

Before submitting the pull request, make sure it has proper documentation [as described here](https://docs.mattermost.com/developer/api4.html#documenting-the-endpoint). For sample pull requests for adding team APIv4 endpoints, see https://github.com/mattermost/platform/pull/5220 and https://github.com/mattermost/platform/pull/5296.

Please also come [join our "APIv4" community channel](https://pre-release.mattermost.com/core/channels/apiv4), where you can discuss questions or suggest other APIv4 endpoints for Mattermost.

**Comment by mikaoelitiana** [comment]
I want to try this one. It would be my first one working on the Go side of the project.

**Comment by mikaoelitiana** [comment]
Oh I didn't see it was already PRed.

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana! If you're interested in helping with other APIv4 endpoints, I encourage you to join our public [APIv4 channel](https://pre-release.mattermost.com/core/channels/apiv4). 

We've prepared a [contribution process for APIv4](https://docs.mattermost.com/developer/api4.html) and a [progress tracker for new APIv4 enpoints](https://docs.google.com/spreadsheets/d/1nPoLgwh_9zRFECpqRUZAKIWihCmX27pnDtFGLtG_WnY/edit#gid=0) to help you get started.

Would love to have your help and guide you through it 👍 

@jason and I created two resources to help make it easier to contribute to APIv4:
An APIv4 Contribution Process doc that should have everything you need to get started and,
A progress spreadsheet to track which endpoints need implementation and which are complete

**Comment by jasonblais** [comment]
Closed by #5473, thanks @saturninoabril!
