### ISSUE TITLE
[Help Wanted] [PLT-5322] Add more flag emojis

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5422]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5322)

To fix a weird case in the upcoming emoji picker where more than two categories of emoji are visible at once, we should add enough additional country flags so that we'll never have three categories of emoji visible at once.

These changes should be made in the emoji.json of https://github.com/hmhealey/emoji once that's made public. Then that script can be used to generate a new emoji.jsx file.

You can talk to @hmhealey on GitHub (@harrison on pre-release) for help generating emoji.jsx.

**Comment by Hanzei** [comment]
Fixed with #7001?

**Comment by jasonblais** [comment]
Thanks! You're correct 👍
