### ISSUE TITLE
[Help Wanted] [PLT-5316] Use neutral skin tones for all system emoji

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5423]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5316)

Some of the system emoji use a specific skin tone instead of the neutral, yellow tone. Since we don't support skin tone variations, we should use the yellow tone wherever possible.

List of emojis that use a specific skin tone:

```
  - :santa: :swimmer: :surfer: 
  - :+1: :thumbsup: :-1: :thumbsdown: :ok_hand: :punch: :facepunch: :fist: :v: :wave: :hand: :raised_hand: :open_hands: :point_up: :point_down: :point_left: :point_right: :raised_hands: :pray: :point_up_2: :clap: :muscle: :metal: :fu: :runner: :running: :couple: :family: :two_men_holding_hands: :two_women_holding_hands: :dancer: :dancers: :ok_woman: :no_good: :information_desk_person: :raising_hand: :bride_with_veil: :person_with_pouting_face: :person_frowning: :bow: :couplekiss: :couple_with_heart: :massage: :haircut: :nail_care: :boy: :girl: :woman: :man: :baby: :older_woman: :older_man: :person_with_blond_hair: :man_with_gua_pi_mao: :man_with_turban: :construction_worker: :cop: :angel: :princess: :guardsman: :ear: :nose:
 
List of emojis that may need to be replaced (?)
  - :mountain_bicyclist: :bicyclist: :horse_racing: :snowboarder: :doll:
```

The others seem fine / are objects and hence don't have skin tone

**Comment by jasonblais** [comment]
This is done in Mattermost 4.1
