### ISSUE TITLE
[Help Wanted] [PLT-5516] Add help text for "Words that trigger mentions"

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5424]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5516)

Repro:
1. Go to Account Settings > Notifications > Words that Trigger mentions
2. Unselect all options
3. Save

Observed: Help text when the section is collapsed says "No words configured". This is not correct, since mentioning @username will still trigger mentions.

![image](https://cloud.githubusercontent.com/assets/13119842/22986542/ec6d128e-f379-11e6-9a50-6e01f7327adf.png)

Expected:

1) In the collapsed help text, always include "@username" as part of the listed words.

2) When the setting is expanded, add help text that says "Mentions trigger when someone sends a message that includes your username (@lf.brock) or any of the options selected above." 

![image](https://cloud.githubusercontent.com/assets/13119842/22986549/f5d0de0a-f379-11e6-8507-e787d9139257.png)

**Comment by joannekoong** [comment]
Should the second option "Your non-case sensitive username" be removed as an option as well since "@username" is now automatically included?

**Comment by jasonblais** [comment]
Closed via #5459, thanks @joannekoong!
