### ISSUE TITLE
[Help Wanted] [PLT-5490] Add machine-readable timestamps for search results

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5425]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5490)

See original community PR that added datetime attribute to <time> elements for center channel and comment threads: https://github.com/mattermost/platform/pull/5199

This is an improvement to add it for timestamps in search results as well.

SUMMARY

Add machine-readable date and time to the message timestamps.

STEPS TO REPRODUCE

1. Join a channel.
2. Send a message.
3. Search for that message
4. In the web browser’s developer tools, inspect the timestamp.

EXPECTED BEHAVIOUR

The timestamp should be a `<time>` element with content formatted according to the user’s preferences and time zone, and with the machine-readable ISO 8601 date and time in the `datetime` attribute. Example: `<time class="post__time" datetime="2017-01-18T05:14Z">12:14</time>` for a user in the UTC+7 time zone.

The presence of a machine-readable date and time is important for accessibility and will permit display format customization via userscripts.

OBSERVED BEHAVIOUR
The timestamp is a `<time>` element with content formatted to the user’s preferences, but without a machine-readable date and time. Example: `<time class="post__time">12:14</time>`.

**Comment by jasonblais** [comment]
Closed by #5564, thanks @aautio!
