### ISSUE TITLE
[Help Wanted] [PLT-5482] Update CLI platform version command to include the build number

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5426]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5482)

Observed: Currently platform version only prints the major version number, which is confusing when people have just installed a dot release (report here: https://pre-release.mattermost.com/core/pl/rnz9a1zzjbgsmn6azowqp3t77w). 

Proposed Change: Include the following in ./platform version command
 - Version: The real version number including the dot release, e.g 3.6.0 or 3.6.2
 - Build Number: The real build number, e.g. 1582 in the attached screenshot
 - DB: The schema version of the database, e.g. 3.5.0 or 3.6.0

![image](https://cloud.githubusercontent.com/assets/13119842/23580999/2bd59410-00da-11e7-9eb2-6d1061e8cb40.png)

**Comment by jgoos** [comment]
As far as I can see the build number is already included?
```
# ./platform version
Version: 3.6.0
Build Number: 3.6.2
Build Date: Tue Jan 31 21:02:59 UTC 2017
Build Hash: 1a9891f0f5671551d28be54a99155b907480cc5c
Build Enterprise Ready: true
DB Version: 3.6.0
```

**Comment by cpanato** [comment]
yep its already there:

```
func printVersion() {
	CommandPrintln("Version: " + model.CurrentVersion)
	CommandPrintln("Build Number: " + model.BuildNumber)
	CommandPrintln("Build Date: " + model.BuildDate)
	CommandPrintln("Build Hash: " + model.BuildHash)
	CommandPrintln("Build Enterprise Ready: " + model.BuildEnterpriseReady)
	CommandPrintln("DB Version: " + app.Srv.Store.(*store.SqlStore).SchemaVersion)
}
```

**Comment by jasonblais** [comment]
That's a good point @jgoos and @cpanato 

We've queued to discuss in the dev meeting whether `Version` should contain the actual release number (e.g. 3.6.2)

**Comment by jgoos** [comment]
@jasonblais yes the current versioning is confusing.
Build number is more internal for the development team, and Version number for the actual release imo.

**Comment by jasonblais** [comment]
Thanks @jgoos and @cpanato, I've updated the description following our discussion:

Include the following in ./platform version command
 - Version: The real version number including the dot release, e.g 3.6.0 or 3.6.2
 - Build Number: The real build number, e.g. 1582 in the attached screenshots
 - DB: The schema version of the database, e.g. 3.5.0 or 3.6.0

**Comment by jasonblais** [comment]
We'll be doing release process updates for 3.8, and at the same time resolve the issue described here.
