### ISSUE TITLE
Create New Group: Able to change URL using 2 chars

### ISSUE THREAD

**Issue by jdub80** [mattermost/platform#5432]
#### Summary
The user is able to change the URL to a value with only 2 characters.

#### Steps to reproduce
Browser: Safari (10.0.3)
Version: 3.6.0 (3.6.2)

1. Click the icon to create a new private group.
2. Select the Edit link to change the URL.
3. Enter 2 characters in the URL text field.
4. Click Change URL button.

#### Expected behavior
The following error message displays, "Must be longer than two characters"

#### Observed behavior
The Change URL modal dialog closes.  The New Group modal dialog displays the URL with only 2 chars.
![errormessage](https://cloud.githubusercontent.com/assets/25757529/22997317/fce1f660-f375-11e6-9267-77ad2d90f7b1.jpg)
![2charurl](https://cloud.githubusercontent.com/assets/25757529/22997328/01b3139a-f376-11e6-9cfb-f8cd03311561.jpg)

**Comment by esethna** [comment]
Thanks @jdub80! I've filed a ticket [here](https://mattermost.atlassian.net/browse/PLT-5571), this is actually just an incorrect error message as the URL should accept two characters. Would you be interested in working on the fix?

**Comment by jdub80** [comment]
Yes.

**Comment by esethna** [comment]
Thanks @jdub80! I'm going to close this issue so it can be tracked as a help wanted issue: https://github.com/mattermost/platform/issues/5456. Please comment there if you start work on it.
