### ISSUE TITLE
Slash Commands can't send any request to server outside the proxy

### ISSUE THREAD

**Issue by kaakaa** [mattermost/platform#5447]
#### Summary
Hi all.
Our Mattermost is set up inside my company's proxy. And I made custom slash command that send request to server outside the proxy.
When executing that command, the request by command is failed.

#### Steps to reproduce
1. Set up Mattermost inside company's proxy.
2. Set up a custom slash command requesting to server outside the proxy
3. Execute that command

#### Expected behavior
* The custom slash command finish successfully
* Posting message of `text` field in response from server if response is formatted as json

#### Observed behavior
* Requests by the command is failed and Mattermost output the following log message 

```
[2017/02/17 02:21:09 UTC] [EROR] /api/v3/teams/tttttttttttttttttttttttttt/commands/execute:command code=500 rid=aaaaaaaaaaaaaaaaaaaaaaaaaa uid=bbbbbbbbbbbbbbbbbbbbbbbbbb ip=XXX.XXX.XXX.XXX Command with a trigger of 'test_slash_command' failed [details: Get https://host.example.com/test.json: dial tcp: lookup host.example.com on 127.0.0.11:53: no such host]
```

#### Possible fixes
Add `Proxy: ProxyFromEnvironment` to `http.Transport` in api/command.go just like [golang's DefaultTransport](https://github.com/golang/go/blob/1fe3933920eda140a75f87268a6d75260ba41823/src/net/http/transport.go#L33).

Example: 
```
tr := &http.Transport{
    Proxy: Proxy: ProxyFromEnvironment,
    TLSClientConfig: &tls.Config{InsecureSkipVerify: *utils.Cfg.ServiceSettings.EnableInsecureOutgoingConnections},
}
```
[platform/command\.go at e9c9688b343049c6d461260bd15fff3486238f92 · mattermost/platform](https://github.com/mattermost/platform/blob/e9c9688b343049c6d461260bd15fff3486238f92/api/command.go#L183)

It may be better to do the same with the part using `http.Transport`
* [platform/oauth\.go](https://github.com/mattermost/platform/blob/c01d9ad6cf3f8bb2ad4145441816598d8ffa2d9e/api/oauth.go#L748)
* [platform/notification\.go](https://github.com/mattermost/platform/blob/4149e82455d2645d7bc5c910f72c7e311d2a5920/app/notification.go#L533)
* [platform/webrtc\.go](https://github.com/mattermost/platform/blob/d245b29f82a03f1aff966a2fb2100a5703d82f32/api/webrtc.go#L85)
* [platform/webhook\.go](https://github.com/mattermost/platform/blob/2a9c1afd444ef00693860b732c901466682e253c/app/webhook.go#L88)
* [platform/webtrc\.go](https://github.com/mattermost/platform/blob/0e2b321e6f5ab5983bc3428aa455dac7012c36ee/app/webtrc.go#L28)

**Comment by lindy65** [comment]
Hi @kaakaa 

Thank you for your issue report.

For a general fix, we have [this ticket](https://mattermost.atlassian.net/browse/PLT-5705) to track the issue.

Would you be interested in submitting a fix for slash commands?

**Comment by jasonblais** [comment]
Thanks again @kaakaa! We'll track the issue with this ticket, but if you're interested submitting a fix for slash commands, let us know. Would be happy to guide you through it

https://mattermost.atlassian.net/browse/PLT-5705
