### ISSUE TITLE
[Help Wanted] [PLT-5571] Update error messages when entering an invalid URL in channel creation window

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5456]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5571)

Summary
Update error messages when entering an invalid URL in channel creation window.

This involves updating four error messages in https://github.com/mattermost/platform/blob/master/webapp/components/change_url_modal.jsx#L46 and the subsequent translation files in https://github.com/mattermost/platform/blob/master/webapp/i18n/en.json

MESSAGE  1:

1. Open the "New Channel" modal
2. Click "Edit" next to the URL
3. Enter one characters in the URL text field.
4. Click Change URL button.

Observed behavior
Error message "Must be longer than two characters"

Expected behavior
The error message displays, "URL must be two or more characters."

MESSAGE 2:

1. Open the "New Channel" modal
2. Click "Edit" next to the URL
3. Enter a URL that doesn't start with a letter or number
4. Click Change URL button

Observed behavior
Error message "Must start with a letter or number"

Expected behavior
The error message displays, "URL must start with a letter or number."

MESSAGE 3:

1. Open the "New Channel" modal
2. Click "Edit" next to the URL
3. Enter a URL that doesn't end with a letter or number
4. Click Change URL button

Observed behavior
Error message "Must end with a letter or number"

Expected behavior
The error message displays, "URL must end with a letter or number."

MESSAGE 4:

1. Open the "New Channel" modal
2. Click "Edit" next to the URL
3. Enter a URL that contains two underscores in a row
4. Click Change URL button.

Observed behavior
Error message "Can not contain two underscores in a row."

Expected behavior
The error message displays, "URL can not contain two underscores in a row."

**Comment by vielmetti** [comment]
https://github.com/mattermost/platform/blob/b3afe9fb16523415f3bceafde9bb80b4d229e2b2/webapp/components/change_url_modal.jsx#L53 is where the code is that matches this message.

**Comment by jasonblais** [comment]
Thanks @vielmetti,  that's a good point, I've updated the ticket accordingly
