### ISSUE TITLE
Switching between team requires to re-authenticate

### ISSUE THREAD

**Issue by benoitc** [mattermost/platform#546]
right now we can't be logged to two teams at the same time like it's possible under slack. Switching to a team ask us to re-authenticate and we don't get any more the notifications from the other team.

**Comment by it33** [comment]
Thanks @benoitc, ticket queued for this: https://mattermost.atlassian.net/browse/PLT-44

**Comment by apaatsio** [comment]
I see from Jira that this task is planned for the current sprint which ends 09 Oct. Do you think it will be done by then? Or do you have some other estimate when it might be done?

**Comment by coreyhulen** [comment]
yup...that's the plan :)

**Comment by coreyhulen** [comment]
A partial fix for this problem is submitted as https://github.com/mattermost/platform/pull/903.  You can now switch teams without re-auth'ing, but you cannot have multiple tabs opened with different teams.

**Comment by coreyhulen** [comment]
PR https://github.com/mattermost/platform/pull/1129 submitted

**Comment by coreyhulen** [comment]
This is now in master.
