### ISSUE TITLE
[Help Wanted] Cannot open Account Settings modal if available languages in config.json doesn't contain the default client language

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5462]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5548)

There's a bug where **Account Settings > Display** menu won't open if the `AvailableLocales` config setting doesn't contain the default client language.

Repro:

1) Set the following config settings

```
 - DefaultServerLocale: en
 - DefaultClientLocale: en
 - AvailableLocales: zh-CN
```

2) Restart the server
3) Sign in and go to **Account Settings > Display**

Observed: JavaScript error, menu doesn't open. The reason is that `AvailableLocales` in step 1 doesn't contain the language set in `DefaultClientLanguage`.

Proposed change: In step 2 when you try to run the server, provide the following error message:

`Unable to load mattermost configuration file:  AvailableLocales must include DefaultClientLocale.`

**Comment by jasonblais** [comment]
Completed by https://github.com/mattermost/platform/pull/5532

Sorry @aautio for the duplication, appreciate your help looking into it

**Comment by aautio** [comment]
@jasonblais I think you have another similar bug that can occur due to corrupt configuration of `DefaultClientLocale`. Described here: https://github.com/mattermost/platform/pull/5532#discussion_r103109056

**Comment by jasonblais** [comment]
That's a really nice catch @aautio, thanks for sharing this with us. Looks like a fix was incorporated to cover that case as well
