### ISSUE TITLE
[Help Wanted] [PLT-5269] Remove the extra blue bar from link previews

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5466]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5269)

Remove the extra blue bar from link previews.

It is currently confusing with the reply bar, and unnecessary since we have a box around link previews.

![image](https://cloud.githubusercontent.com/assets/13119842/23094810/99052fea-f5cd-11e6-97d6-73947eb58718.png)

NOTE: We should still keep the bar for webhook Slack attachments, see example

![image](https://cloud.githubusercontent.com/assets/13119842/23094815/a1d1bbe8-f5cd-11e6-869c-2863ab63977a.png)

**Comment by R-Wang97** [comment]
I can take a look at this issue.

**Comment by aautio** [comment]
@R-Wang97 👍  I'd suggest two edits to achieve this:

1: Add `&.attachment__container--opengraph { border-left-color: transparent; }` to `_webhooks.scss`, inside the `.post .attachment .attachment__container` ... as there are many similar rules over there. 

2: Add `attachment__container--opengraph` as an additional class to the `div` with classes `clearfix attachment__container` post_attachment_opengraph.jsx

(I had just looked 30 minutes ago how to fix this, then came back here and found out that you were also checking this :) )

**Comment by R-Wang97** [comment]
@aautio Thanks, will check it out 😄

**Comment by jasonblais** [comment]
Closed via #5673, thanks @R-Wang97!
