### ISSUE TITLE
[Help Wanted] [PLT-5268] Always show link previews on comment threads in right-hand sidebar

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5467]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5268)

Right now if you are viewing a thread on the right-hand sidebar, the link previews are only shown for the parent post, not for comments. 

Proposed change: Always show link previews on comment threads in right-hand sidebar.

NOTE: Search results (including flagged posts and recent mentions) should not show the link preview.

**Comment by jasonblais** [comment]
Re-opened here: https://github.com/mattermost/platform/issues/7188
