### ISSUE TITLE
[Help Wanted] [PLT-5281] Update error message text on team creation URL screen

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5468]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5281)

Repro:
1) Set **System Console > Users and Teams > Enable Team Creation** to true
2) Go back to Mattermost
3) Go to Main Menu > Create a New Team
4) Enter a team name, such as "testing"
5) Enter a URL "admin"

Observed: URL is taken or contains a reserved word
Expected: This URL starts with a reserved word. Please try another.

where "starts with a reserved word" is a clickable link which opens https://docs.mattermost.com/help/getting-started/creating-teams.html#team-url in a new browser tab.

Note: Start of a PR here, but the "starts with a reserved word" text wasn't clickable: https://github.com/mattermost/platform/pull/4952

**Comment by jasonblais** [comment]
Resolved by #5530, thanks @aautio!
