### ISSUE TITLE
[Help Wanted] [PLT-5337] Can't change team sidebar colour

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5479]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5337)

Right now the team sidebar picks a colour offset from the sidebar header colour. This should be independent. 

Note: Theme colours are now switched to name value pairs, which should help this PR https://github.com/mattermost/platform/pull/5301

**Comment by pan-feng** [comment]
I want do it ！

**Comment by jasonblais** [comment]
Awesome! Please go ahead @pan-feng!

**Comment by jasonblais** [comment]
Jira ticket was closed as "won't fix"

Reasons:
 - Haven't heard any users or customers asking for this yet
 - Most themes look okay with the current sidebar
 - People with new accounts can pick colors that look good together when they first set up a custom theme

**Comment by jasonblais** [comment]
@pan-feng if you're interested helping with another help wanted issue, please let us know! Would love to work with you
