### ISSUE TITLE
Encoding issue with link preview

### ISSUE THREAD

**Issue by jostyee** [mattermost/platform#5484]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Team Version: 3.6.0  (3.6.2), link preview shows wrong characters
<img width="423" alt="screen shot 2017-02-21 at 12 39 45 pm" src="https://cloud.githubusercontent.com/assets/88564/23151947/76fc112a-f839-11e6-9565-54495207afc3.png">

#### Steps to reproduce
Send post with url e.g.: https://twitter.com/icablenews/status/833896561071435776

#### Expected behavior
Shows correct CJK characters

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by jasonblais** [comment]
Thanks @jostyee for the report - this will be improved in Mattermost 3.7 with updated website link previews.

Here's a snapshot of what the link preview will look like instead

![image](https://cloud.githubusercontent.com/assets/13119842/23152467/49ae1ede-f7d0-11e6-9d2d-ba52f7eaf1ce.png)

**Comment by jostyee** [comment]
thx @jasonblais
