### ISSUE TITLE
[Help Wanted] [PLT-1015] Make all Mattermost system emails Multi-Part, with both a HTML and Plain Text version.

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5486]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1015)

Currently all emails sent by the Mattermost server are in HTML only. This ticket is to change them to be multi-part, including both an HTML and Plain Text version of the email.

Steps involved:
1. Identify a suitable golang library for constructing multi-part emails (please discuss the chosen library with us before starting implementation to ensure there are no issues with the license).
2. Migrate the existing code sending emails to use that library.
3. Implement a plain-text version of all the emails, and combine that in multi-part messages with the existing HTML messages.

**Comment by cpanato** [comment]
possible library to use
* https://github.com/mohamedattahri/mail

**Comment by grundleborg** [comment]
Hey @cpanato - are you taking on implementing this ticket? I'm wondering if we should check that the licensing on that library is OK, or if you are just posting an idea for someone else when they come to this ticket.

**Comment by cpanato** [comment]
@grundleborg I can try to work on that.
Who can check the license? I'm not the best with licenses :/ 

Also, the changes will be around the mail.go right?

**Comment by grundleborg** [comment]
@cpanato for the license, I will ask Mattermost Inc people to review it and check it is OK for us to depend on it.

The changes, I think, will mostly be in https://github.com/mattermost/platform/blob/master/app/email.go .

At the moment, it is building emails from HTML templates. To complete this PR, it will need to build them both using HTML and Plain Text templates, and then combine both in a multi-part email.

**Comment by cpanato** [comment]
@grundleborg got it, I will wait to the license stuff and then will start the work on that :)

**Comment by grundleborg** [comment]
@cpanato the license is OK for that library, so you can start hacking whenever you like :)

**Comment by cpanato** [comment]
@grundleborg sounds good. I will read about sending email in two formats and play around in the code.

thanks!!

**Comment by cpanato** [comment]
@grundleborg hello, how are you doing?

I tried the above library. however, it not work as expected and the project looks like its abandoned.

I'm working using this one https://github.com/go-gomail/gomail/tree/v2 which is working :) 

we just need to check if fit the license. The repo says it is under MIT. Can you confirm if we can use that?

thanks

**Comment by jasonblais** [comment]
License for https://github.com/go-gomail/gomail/tree/v2 looks good 👍

**Comment by cpanato** [comment]
Also what do you guys think to use this lib to convert the html to plain text? https://github.com/jaytaylor/html2text

or we get the templates and adjust that for plain text? 


this one sample output using this two libraries

plain text

<img width="848" alt="screen shot 2017-03-08 at 00 06 26" src="https://cloud.githubusercontent.com/assets/4115580/23682270/2d99b6c6-0393-11e7-8e0d-32137ffd10c3.png">


HTML

<img width="682" alt="screen shot 2017-03-08 at 00 06 42" src="https://cloud.githubusercontent.com/assets/4115580/23682279/343dc85a-0393-11e7-997a-0ac395de0c16.png">

**Comment by grundleborg** [comment]
I think we'd probably be better making custom templates for HTML & Plain Text, rather than relying on some library to convert them. @jasonblais can confirm though.

**Comment by cpanato** [comment]
ok, then I will need to work a little more on the templates.
ok, will wait for @jasonblais

**Comment by jasonblais** [comment]
Hey @cpanato, chatted with @grundleborg 

Building our own custom templates will allow us to have more control on how the emails look like. It also doesn't force us to reply that the library always converts the HTML templates correctly.

Since we won't change the email templates very often, this option would be better in the long term.

Let me know what you think about this suggestion? For the workflow, we can either design the templates on how they look or we can tweak them during the review process.

**Comment by cpanato** [comment]
@jasonblais 
my understanding is:
today all the templates are ready for HTML. We will need create new for text correct? or somehow (which I dont know now) adjust the current ones to support both html/text.

ps. this library just convert the html generated by mattermost templates to plain text.

**Comment by jasonblais** [comment]
Yes, that's correct. So creating a template for plain text version.

Even if the library generated the plain text version, we would rely on it forever (if something breaks, there isn't much we could do about it).
