### ISSUE TITLE
API docs not rendering in MS Edge

### ISSUE THREAD

**Issue by lllama** [mattermost/platform#5488]
Browsing to api.mattermost.com in Edge gives the following error:

![image](https://cloud.githubusercontent.com/assets/598411/23170410/f6739eca-f846-11e6-81b0-f03217e2f15e.png)

**Comment by lindy65** [comment]
Hi @lllama 

Thank you for your report :)  We've reproduced the issue and have created a ticket to track it [here](https://mattermost.atlassian.net/browse/PLT-5665)

Thanks for helping improve our docs!

**Comment by jasonblais** [comment]
Thanks @lllama ! We'll track the issue in Jira: https://mattermost.atlassian.net/browse/PLT-5665
