### ISSUE TITLE
mattermost does not send email infomation when security level 'plain'

### ISSUE THREAD

**Issue by darkrasid** [mattermost/platform#5493]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Email what I send from mattermost, dose not include vaild infomation.

#### Steps to reproduce
mattermost version info => 
Version: 3.6.0
Build Number: 3.6.2
Build Date: Tue Jan 31 21:02:59 UTC 2017
Build Hash: 1a9891f0f5671551d28be54a99155b907480cc5c
Build Enterprise Ready: true
DB Version: 3.6.0

#### Expected behavior
I set email config (eg. smtp setting) on mattermost. I use Connection Security level 'plain' . 
However mattermost only send data below
```
EHLO localhost
QUIT
```
So my smtp server disconnect from client. 

When I use Connection Security level 'none' instead of 'plain'.
Mattermost sends more infomation somehing like below. 
```
EHLO localhost
MAIL FROM:<>
RCPT TO:<myemail@domain.com>
DATA
```
Of course, my smtp sever dose not accept 'NONE' so there is an exception. However I think when I set 'plain', mattermost should send similar form data to smtp. 

I already use this smtp server on production. And other services what I operate on production (eg. discourse, gitlab) use same smtp server. They work well.

That's why I guess there are some problem on my mattermost config. 

Is there any idea or hint that I can handle this issue?

**Comment by lindy65** [comment]
Hi @darkrasid 

Thank you for your report and apologies for the delay in responding.  We were working on trying to reproduce the issue but haven't had much luck yet.

Could you help by providing the following information?:
1) Did you follow our [SMTP Email Setup guide](https://docs.mattermost.com/install/smtp-email-setup.html) 
2) Which SMTP server are you using (e.g. Amazon SES, Hotmail)
3) Do you see anything in the server logs (from System Console > Logs)

Thanks!

**Comment by darkrasid** [comment]
Thank you for answering @lindy65 

  1. Did you follow our SMTP Email Setup guide => yes
  2. Which SMTP server are you using (e.g. Amazon SES, Hotmail) => I use my own smtp server made from [here](https://github.com/4commerce-technologies-AG/midi-smtp-server)
  3. Do you see anything in the server logs (from System Console > Logs)
```
[2017/03/03 07:04:04 UTC] [EROR] /api/v3/admin/test_email:SendMail code=500 rid=oett3w4eopypfyhk3crt6gdcha uid=4g14xftb5ibidfmcnaxaxtm3uc ip=my_ip Failed to authenticate on SMTP server [details: unencrypted connection]
```
And smtp server log is here (actually same as upper)
```
EHLO localhost
QUIT
```
There is no Authentication infomation so smtp server disconnected from mattermost. 

If you need any other infomation, please notify me. 

Thanks.

**Comment by lindy65** [comment]
Hello @darkrasid 

Thank you for the additional information.  We've created a [ticket](https://mattermost.atlassian.net/browse/PLT-5835) to investigate your issue.

**Comment by jasonblais** [comment]
Hey @darkrasid, have you tried to run the Mattermost server over an encrypted connection?

If you use NGINX, here's instructions on how to do that: https://docs.mattermost.com/install/config-ssl-http2-nginx.html?highlight=encrypt#configuring-nginx-with-ssl-and-http-2

**Comment by ovizii** [comment]
Having the exact same problem although I run mattermost from the docker isntallation and am trying to talk to an Exchange 2013 server. I can successfully send emails if I set security to NONE.

When using plain I get:
`[2017/03/20 12:06:28 CET] [EROR] /api/v3/admin/test_email:SendMail code=500 rid=rqnny1fq7if4zenf8i8gwr4uhw uid=zxkr6prtsfb8jmqu5f7mqi4wde ip=192.168.200.111, 192.168.200.1 Fehler beim Authentifizieren am SMTP Server [Details: unencrypted connection]`

When I change to i.e. 465 and try TLS and then STARTTLS I get:
```
[2017/03/20 12:10:49 CET] [EROR] /api/v3/admin/test_email:SendMail code=500 rid=85kbhq4wmbge8puft1kdhhuxxy uid=zxkr6prtsfb8jmqu5f7mqi4wde ip=192.168.200.111, 192.168.200.1 Fehler beim Öffnen der TLS Verbindung [Details: tls: first record does not look like a TLS handshake] 
and 
[2017/03/20 12:11:23 CET] [EROR] /api/v3/admin/test_email:SendMail code=500 rid=mkqi5iz5r3rttpxsmoccrunhso uid=zxkr6prtsfb8jmqu5f7mqi4wde ip=192.168.200.111, 192.168.200.1 Fehler beim Authentifizieren am SMTP Server [Details: 504 5.7.4 Unrecognized authentication type]
```

**Comment by lindy65** [comment]
Thanks @ovizii for the report, really appreciate your detailed description to describe the issue

Also, I'm personally sorry for the delay, there has been some discussion internally about supporting the Exchange server [following the proposal here](https://github.com/mattermost/docs/issues/994#issuecomment-293091616), and we ended up forgetting to come back to you.

We received steps to configure Microsoft Exchange to Mattermost. These were from a community member and I'm curious to hear if you used similar steps to configure your server: https://github.com/mattermost/docs/issues/994#issuecomment-293091616

If they differ, would you be able to point the areas where it does?

Thanks again,

**Comment by ovizii** [comment]
hey, don't worry, this was not urgent and btw. we have decided to limit the use of mattermost accounts to our internal domain so sending emails out is no longer necessary which also means I can keep sending emails through mattermost directly to exchange without authentication as the target domain is internal.

I've read through the comment you linked me to and its a workaround only by adding postfix between mattermost and exchange so mattermost doesn't talk directly to exchange. I could of course do that but I'd rather find out what the root cause is when mattermost talks directly to exchange.

**Comment by lindy65** [comment]
Thanks for your note @ovizii !

Glad you have a solution in the meantime :)  I'll close this issue off for now but feel free to re-open it or create a new issue at any time.

**Comment by artem-sidorenko** [comment]
I've the same problem:
 - SMTP relay configured with STARTTLS or even PLAIN
 - no authentication configured / enabled

mattermost is not sending the mail out and I see following error message
```
[2017/06/20 10:00:52 CEST] [EROR] /api/v3/admin/test_email:SendMail code=500 rid=[CENSORED] uid=[CENSORED] ip=[CENSORED], [CENSORED] Failed to authenticate on SMTP server [details: unencrypted connection]
```

Using wireshark I see following SMTP communication:
```
220 hostname ESMTP Postfix
> EHLO localhost
250 hostname | 250 PIPELINING | 250 SIZE ... | 250 VRFY ....
> QUIT
221 2.0.0 Bye
```

**Comment by jasonblais** [comment]
@artem-sidorenko Currently either option requires authentication (if your SMTP relay doesn't have authentication configured, it doesn't work).

We have a PR here that should address the issue: https://github.com/mattermost/platform/pull/6639

**Comment by TomFreudenberg** [comment]
Hi @darkrasid 

we added functions for authentication and encryption to [MidiSmtpServer](https://github.com/4commerce-technologies-AG/midi-smtp-server). If you are using already a 2.x release, your source may use the latest gem (2.2.4) without any compatibility issues.

You may set options `tls_mode: TLS_OPTIONAL` as well  as `auth_mode: :AUTH_OPTIONAL` to enable both features.

Just try a simple __allow all authentication__ with (not for production but for test purposes):

```ruby
def on_auth_event(ctx, authorization_id, authentication_id, authentication)
    return authentication_id
end
```

Would be interesting if mattermost will run with that.

Cheers
Tom

**Comment by ahmadalli** [comment]
so we're not able to use an unsecured smtp server that requires authentication?

**Comment by jasonblais** [comment]
@ahmadalli In Mattermost 4.1 and later, we have two settings in System Console > Notifications > Email

1. Enable SMTP Authentication - choose whether authentication to SMTP required
2. Connection Security - choose between unsecured, TLS and STARTTLS options

https://docs.mattermost.com/administration/config-settings.html#enable-smtp-authentication
https://docs.mattermost.com/administration/config-settings.html#email-tls

You can use any combination of the above settings in your system, including unsecured SMTP server with authentication.

**Comment by ahmadalli** [comment]
@jasonblais The problem is I'm getting `unsecured authentication` error

**Comment by jasonblais** [comment]
Ah, I see. @ahmadalli Would you be open to opening a new troubleshooting issue on our forums and our community or support team will help assist? 

https://forum.mattermost.org/t/how-to-use-the-troubleshooting-forum/150

You can use your GitHub credentials to open the issue.
