### ISSUE TITLE
CTRL+K and CTRL+U should not trigger on AltGr+K and AltGr+U

### ISSUE THREAD

**Issue by lafriks** [mattermost/platform#5495]
#### Summary
CTRL+K and CTRL+U should not trigger on AltGr+K and AltGr+U

#### Steps to reproduce
Press AltGr+K or AltGr+U

#### Expected behavior
AltGr in some languages are used to input special characters with umlauts

#### Observed behavior
When keyboard layout is Latvian pressing AltGr+K or AltGr+U instead of getting "Ķ" or "Ū" in input box I get either upload or channel switch dialog and there is no way to workaround it

**Comment by lindy65** [comment]
Hi @lafriks 

Thank you for your report!

You bring up a good point :)  Is this perhaps something you'd be interested in submitting a pull request for?

If you'd like to help, you can find our Code Contribution Guidelines  [here](https://docs.mattermost.com/developer/contribution-guide.html#code-contribution-guidelines).

Let us know if you have any questions!

**Comment by lafriks** [comment]
I debbuged a little bit and found out that on Windows with keyboard that AltGr (right Alt key) is set for alternate letters in key press event object it has all properties same as for left Ctrl key so I don't know how to detect in JS when each of them is pressed

**Comment by lafriks** [comment]
Pull request submitted ;)

**Comment by lindy65** [comment]
Hi @lafriks 

Awesome!  Thanks so much :)  Really great having contributors such as yourself work with us!

**Comment by jasonblais** [comment]
Closed, thanks @lafriks!
