### ISSUE TITLE
[Help Wanted] [PLT-5615] Update platform version command to output stdout instead of stderr

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5501]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5615)

Currently, when platform version command is used the version information it output as stderr. 

Update the command to have a stdout output instead.

**Comment by cpanato** [comment]
hello

you mean when you run the 
```
go run ./cmd/platform/*.go version
```
if yes I ran that based on master and ran using this to check the stderr and stdout

`go run ./cmd/platform/*.go version > version.stdout  2> version.stderr`

and there was nothing on the stderr and the output was in the stdout

```
$ cat version.stdout 
Version: 3.6.0
Build Number: 
Build Date: 
Build Hash: 
Build Enterprise Ready: 
DB Version: 3.6.0
```

**Comment by jasonblais** [comment]
@grundleborg any thoughts?

**Comment by grundleborg** [comment]
@jasonblais I agree with @cpanato - there doesn't currently appear to be anything getting printed to stderr - it's all going to stdout. Maybe this has already been fixed, or maybe we misunderstood the original bug report?

**Comment by jasonblais** [comment]
I've closed the issue as `cannot reproduce`
