### ISSUE TITLE
Username defaults to lower case

### ISSUE THREAD

**Issue by MaverickAdams** [mattermost/platform#5504]
#### Summary
Issue in one concise sentence
Upon creating my profile the username defaults to lowercase without telling me

#### Steps to reproduce
Create an account and make the username start with a capital letter. Try to log in afterwards.

#### Expected behavior
Create account with username starting with a capital letter. Login with said username. Be logged in.

#### Observed behavior
Created account with username starting with a capital letter. Login with said username. "We couldn't match your credentials"

**Comment by lindy65** [comment]
Hi @MaverickAdams 

Thank you for your report!  We've reproduced the issue and have created a [ticket](https://mattermost.atlassian.net/browse/PLT-5667) to track it.

Your help is appreciated :)

**Comment by jasonblais** [comment]
Thanks @MaverickAdams! We have a community member who has submitted a pull request to fix it here https://github.com/mattermost/platform/pull/5613

We'll track the issue through the corresponding help wanted issue: https://github.com/mattermost/platform/issues/5585
