### ISSUE TITLE
PLEASE HELP.

### ISSUE THREAD

**Issue by catbadger** [mattermost/platform#5511]
#### Summary
I can't find the data in the docker image. I simply want to permanent the db it with a --volume flag and just can't figure it out. it doesnt seem to be documented anywhere. Can someone guide me here please?

**Comment by CometKim** [comment]
You can figure out the volume path using this command,
`docker inspect {container} | grep volume`

**Comment by jasonblais** [comment]
@catbadger was the above command provided by @CometKim  helpful?

**Comment by catbadger** [comment]
no, but it was due to my own misunderstanding of the problem. I've since solved this and moved on to other stuff. :)
