### ISSUE TITLE
Allow link preview requests through separate proxy

### ISSUE THREAD

**Issue by jostyee** [mattermost/platform#5522]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Just found that Mattermost 3.7 has changed its link preview behavior from client request to server `/api/v3/get_opengraph_metadata` parses.

we migrated from Slack 'cause we live in China mainland and the connections with overseas servers have lots of difficulties. Mattermost 3.7 parses link previews from server and some websites we cannot visit directly, so this new feature wouldn't be functional for us most of the time.

and of course asking all requests sends through proxy is not efficient, so please make this API requests configurable via proxy separately, or consider it a separate little app?

**Comment by jostyee** [comment]
hey Mattermost stuffs, can I send a PR to support proxy to this API?

**Comment by jasonblais** [comment]
Thanks @jostyee, let me check with our developers

**Comment by jasonblais** [comment]
@jostyee please feel free to submit a PR and our devs will take a look at it

**Comment by jostyee** [comment]
@jasonblais I'll commit the PR asap.

another related issue, across the whole project we use stdlib default http client, which w/o any custom transport settings, this behavior is strongly anti-pattern. https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779

Have you ever considered maintain some global http clients, e.g.: switch on/off tlsverify; respect http_proxy env; configure timeout, etc.
