### ISSUE TITLE
0 byte (empty) upload in direct message

### ISSUE THREAD

**Issue by clintfred** [mattermost/platform#5523]
#### Summary
When uploading a file to someone via direct message, the file will appear as 0 bytes (and empty) if you are signed into a team that the other user is not a member of.

#### Steps to reproduce
Version: Mattermost Enterprise Edition - 3.4.0

1. Have a server with at least two teams. Have at least two users. 
2. Put one user in both teams and the other user only in one.
3. Have the "both teams" user log in to the team that the other user is not a member of.
4. As the "both teams" user, open a direct message (under "Outside this team") with the other user. 
5. Notice that you can send text just fine. 
6. Try sharing a screenshot (png) to the other user. The upload appears as 0 bytes. The other sees something similar. 

#### Expected behavior
File uploads should work in direct messages regardless if the users are both logged into a shared team or not.

#### Possible fixes
None identified.

#### Possibly related
https://github.com/meetfranz/plugins/issues/35

![screen shot 2017-02-24 at 9 38 30 am](https://cloud.githubusercontent.com/assets/19213143/23311941/10eb9566-fa75-11e6-875c-cf3b7fafba64.png)

**Comment by clintfred** [comment]
I should add that if both users switch to the same team the file uploads appear correctly for both users. If one switches teams again, the files will go back to showing as 0 bytes.

**Comment by lindy65** [comment]
Hi @clintfred

Thanks for your issue report!

I believe the issue you describe was fixed when v3.5.0 was shipped.  Please try updating to the [latest version](https://about.mattermost.com/download) of Mattermost and let us know whether the issue still reproduces for you?

Thanks!

**Comment by RubenDZ** [comment]
I am running v3.6.0 and receiving files from people outside my teams at both v3.4.0 and v3.5.0 show up as 0B files.  Files from members of the same team do show up.

@lindy65 , can you confirm it has been fixed as part of v3.5.0?

**Comment by hmhealey** [comment]
@RubenDZ Yes, it was fixed in the 3.5.0 version of the server. The client version would have no effect on this issue.

**Comment by clintfred** [comment]
I can confirm that with 
```
Version: 3.7.0  (3.7.2)
Database: postgres
```

the issue seems to be resolved. Thanks!

**Comment by lindy65** [comment]
Thanks @clintfred and @RubenDZ !  

Glad the issue is resolved by installing the latest server version of Mattermost!
