### ISSUE TITLE
Reporting Uncaught TypeError: e.replace is not a function

### ISSUE THREAD

**Issue by hardysim** [mattermost/platform#5538]
#### Summary
Mattermost channel does not open, fails with the following log:

> [2017/02/27 09:05:03 CET] [DEBG] /api/v3/general/log_client:client code=0 rid=xxx uid=xxx ip=172.16.x.x msg: Uncaught TypeError: e.replace is not a function
Please report this to https://github.com/chjj/marked. row: 52 col: 30991 stack: TypeError: e.replace is not a function
Please report this to https://github.com/chjj/marked. url: https://...

#### Steps to reproduce
I'm using the bundled mattermost of a omnibus-gitlab-installation. It started failing after enabling slash-commands (and tried using one, which resulted in no response but failure of the whole channel).

Mattermost Version: 3.6.0  (3.6.2)
GitLab Version 8.17.0

#### Expected behavior
The channel should open normally (and maybe just ignore the slash-command when it's not working). Currently I'm not able to use the whole channel (and 1:1 chats as well). I cannot delete and re-create a channel as well (not supported I think).

#### Observed behavior
After re-loading the whole mattermost-page and trying to open a channel or a 1:1 chat it just shows "Loading...". In the log on the system-console I found the above entry.

#### Possible fixes
No idea.

**Comment by hardysim** [comment]
Maybe related: https://github.com/chjj/marked/issues/802

**Comment by jostyee** [comment]
I had reported once before: https://github.com/mattermost/platform/issues/5520 w/o reponse.

**Comment by hardysim** [comment]
Yep, exactly the same problem.

I've opened another bug on the gitlab-side (but made it private because the log-output contains sensible data). When they'll respond, I'll post it on #5520.

---

Closing here in favor of #5520.
