### ISSUE TITLE
There is a misspelling for one message.

### ISSUE THREAD

**Issue by CometKim** [mattermost/platform#5557]
![image](https://cloud.githubusercontent.com/assets/9696352/23387760/efff7824-fda1-11e6-9579-ab12d21235fa.png)

Maybe this spelling is wrong. Right?

#### Expected
`api.templates.signin_change_email.subject`

#### Observed
`api.templates.singin_change_email.subject`

**Comment by lindy65** [comment]
Hi @cometkim 

Thanks for the report!  I believe you are correct :)

We've created a [ticket](https://mattermost.atlassian.net/browse/PLT-5670) to fix the mistake.

Would you or someone in the community be interested helping with a fix? We'll likely turn this into a help wanted ticket.

**Comment by R-Wang97** [comment]
Hi @lindy65, I'd be interested in submitting a fix!

**Comment by lindy65** [comment]
Hi @R-Wang97 

Thank you so much!  That was speedy :)

Your help is very much appreciated!

**Comment by jasonblais** [comment]
Closed via #5569, thanks @R-Wang97!
