### ISSUE TITLE
Group message doesn't support `cmd+shift+k` hotkey

### ISSUE THREAD

**Issue by jostyee** [mattermost/platform#5609]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
glad to see https://github.com/mattermost/platform/pull/5489 has been merged, it's a big step to get closer to Slack, but w/o a hotkey to trigger it.
Using Slack, `cmd+k` is a global hotkey to create/enter public/private channel/dm/group message, hoping that Mattermost could match up with it.

#### Steps to reproduce
click `cmd+k`, input multiple contacts, press Enter

#### Expected behavior
user can create group message/enter one that already existed directly.

#### Observed behavior
get an error that match not found.

**Comment by jasonblais** [comment]
Hey @jostyee, at the moment `CTRL/CMD+K` can be used to open existing channels, not create new ones. I think that's how Slack's quick channel switcher works at the moment too?

We're looking to improve that shortcut in the near term though, with potentially introducing `CTRL+SHIFT+K` for creating new DM/group messages

**Comment by jostyee** [comment]
Slack shortcuts for reference.
<img width="631" alt="screen shot 2017-03-03 at 1 29 02 pm" src="https://cloud.githubusercontent.com/assets/88564/23539318/799c1c34-0015-11e7-8229-a62ad37006ae.png">

**Comment by jasonblais** [comment]
Thanks @jostyee! Looks like the quick switcher is for switching channels? But for creating group messages, you'd need to use CTRL/CMD+SHIFT+K?

**Comment by jostyee** [comment]
@jasonblais yes, my bad to remember it wrongly.

**Comment by jasonblais** [comment]
No worries! I completely empathize with you on the quick switcher and being able to quickly create direct/group messages. This should be made easier.

We have a ticket to refactor CTRL/CMD+K and as part of that fix many of the issues it has: https://mattermost.atlassian.net/browse/PLT-5699
