### ISSUE TITLE
First name and Last name is not updated from OAuth provider (GitLab)

### ISSUE THREAD

**Issue by huksley** [mattermost/platform#5611]
#### Summary
Full name (First name and last name) is not updated on every login to OAuth provider.

#### Steps to reproduce
1.  Register using OAuth (for example GitLab). 
2.  Update in GitLab first name and last name. 
3.  Relogin to Mattermost
4.  First name and last name in Mattermost is not updated.

#### Expected behavior
First name and last name must be updated on every login. 
Mattermost does not have means of editing First name and last name.

#### Possible fixes
Direct update to database is possible (update Users set FirstName = '', LastName = '' where Username = '') but somehow not effective (name is not updating).

**Comment by jasonblais** [comment]
@huksley I think this PR will fix the issue: https://github.com/mattermost/platform/pull/5324 It updates user attributes for GitLab on login.

It will be available on Mattermost 3.7 on March 16th

**Comment by huksley** [comment]
Thanks! Mattermost is awesome!
