### ISSUE TITLE
Disappearing channel navigation panel scrollbar

### ISSUE THREAD

**Issue by fishbike** [mattermost/platform#5614]
#### Summary
Scrollbar disappearing intermittently when switching away from/back to long channel list

#### Steps to reproduce
On 3.6.0 desktop / 3.6.2 server, Windows 10 on a laptop (1366x768 resolution)

#### Expected behavior
When starting the application, on the team navigation bar on the left, in a team with 20+ channels, I see the scrollbar in the navigation panel (so I can get to offscreen channels).

#### Observed behavior
Switching between teams, and then back to the team in question, the scrollbar has disappeared, making my only option to browse all channels altering application zoom.

**Comment by jasonblais** [comment]
Thanks @fishbike for the report! Couple of questions to help investigate the issue

1) Are the repro steps as follows?

1 - Switch to team B
2 - Switch back to team A
Observed: No scrollbar on the channel sidebar

2) Does this reproduce on the browser, or only on the desktop app?
3) How long has the problem been occurring?
 - Did you recently install or begin using Mattermost for the first time?
 - Did the feature work until some point and then start to fail?

**Comment by fishbike** [comment]
1, Yes
2. Not quite--on the browser (Firefox current, at least), it's a little worse/more random. Looks like (and I'm not spot diagnosing, just describing) there's some "smart" around scrollbar appearance that is too smart/doesn't cover all cases.
3. Can't say but to your a and b: a) no, we've been using it for ~6 months, and b) yes, or I wouldn't have waited to post because it's hard to use, but I cannot say more than "in recent weeks", "probably after a shift from ~3.5 public to ~3.6.x enterprise".

**Comment by jasonblais** [comment]
Thanks for the information, that's very useful. I'm able to reproduce it and have filed a ticket here. https://mattermost.atlassian.net/browse/PLT-5731

It looks like the mouse scrollwheel still works on the sidebar, even when the scrollbar is not visible. Hopefully that can help mitigate the impact without forcing you to alter the application zoom each time.

**Comment by jasonblais** [comment]
Thanks again! We'll track the issue in Jira https://mattermost.atlassian.net/browse/PLT-5731

If someone is interested helping with a fix, please let us know!

**Comment by fishbike** [comment]
Hi, sorry for a slow response, and thank you for follow-through. The mousewheel workaround is confirmed (and would seem, under better resolution/different machine, to bring back the scrollbar?), but leaving this here for future searches: if you're on a laptop with no mousewheel, you won't be finding that fix. Which is how I got to the bug in the first place.
