### ISSUE TITLE
[Help Wanted] [PLT-5669] In Account Settings > Security > Access History, in the Timestamp column add a new line after the date and remove "-"

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5625]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5669)

Proposed Help Wanted ticket. 

Time displayed should not carriage return in the middle: 

![image](https://cloud.githubusercontent.com/assets/13119842/23558536/0844709e-0002-11e7-8959-8c500ca3b5bf.png)

Proposed change: 

Account Settings > Security > Access History, in the Timestamp column add a new line after the date and remove "-"

**Comment by VeraLyu** [comment]
Hi,
    May I take this one? Thanks!

**Comment by jasonblais** [comment]
Absolutely @VeraLyu! Please let us know if you have any questions.
