### ISSUE TITLE
[Help Wanted] [PLT-5715] Add a CLI command to search for users

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5627]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5715)

- Need a command that searches for users based on username, email, or user ID
- Should be an exact search, and only return users who are an exact match 
- Should output information about the user

**Comment by simon0191** [comment]
I would like to work on this issue

**Comment by jasonblais** [comment]
Thanks @simon0191! This was is resolved by #5918
