### ISSUE TITLE
Image links not ending in .gif, .jpg, etc do not auto-expand

### ISSUE THREAD

**Issue by law** [mattermost/platform#5634]
#### Summary
Issue in one concise sentence
While Mattermost's image expansion works as expected when the URL ends in .gif, .jpg, etc, image-based links that Slack would expand automatically are not expanded by Mattermost.
#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Post links like the following to a Mattermost channel or DM: 
http://media.riffsy.com/images/41a79faf658c913d77bfe36b8a231244/raw 
http://gph.is/2lQfDuj
http://imgur.com/gallery/83mmP

etc, and note that they do not expand, requiring a user to click on them to view in a new browser tab.  
#### Expected behavior
Have the images auto-expand in-line.

**Comment by lindy65** [comment]
Hi @law 

Thank you for your report!

Please see the [documentation](https://docs.mattermost.com/help/messaging/attaching-files.html?#supported-media-types) for media types that are currently supported in Mattermost.

Perhaps we could have your help adding a [feature suggestion](https://mattermost.uservoice.com/forums/306457-general) for media types you'd like supported that are not yet on the list?  You and others on the forum can up-vote the suggestions - the more votes a suggestion has, the better chance it has of getting onto the road-map and into the product.  You can vote up to 10 times :)
