### ISSUE TITLE
Error thrown when tab is returned to after some time and `option + downArrow` is pressed

### ISSUE THREAD

**Issue by morenoh149** [mattermost/platform#5668]
#### Summary
Error thrown when tab is returned to after some time and `option + downArrow` is pressed to switch teams.

#### Steps to reproduce
Open mattermost. open some channel. Leave computer for ~1 hours. Return to computer and press `option + downArrow`. An error banner will be shown if on the contributors mattermost.

#### Expected behavior
Expected next channel to go into focus.

#### Observed behavior
A red banner is displayed. 

![screen shot 2017-03-03 at 4 04 59 pm](https://cloud.githubusercontent.com/assets/587438/23632830/6e919b9c-0291-11e7-9d2f-ee7da8935b4c.png)

**Comment by lindy65** [comment]
Hi @morenoh149 

Thank you for your report!

We experienced the same issue you've reported and have fixed it with [this ticket](https://mattermost.atlassian.net/browse/PLT-5732).

The fix will be in v3.7.0 release on March 16th.  Let us know if it's fixed for you once you have the new version installed!

Thanks!

**Comment by morenoh149** [comment]
ah if it's fixed I'll just close for now
