### ISSUE TITLE
[Help Wanted] [PLT-5628] Confirmation Dialog when Deleting Entry in the Custom Emoji List

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5669]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5628)

For a related PR, see https://github.com/mattermost/platform/pull/5529

Repro:
1) Go to System Console > Custom Emoji and set it to enabled.
2) Go to Main Menu > Custom Emoji
3) Add an emoji
4) Fill in the information and save
5) Hit "Delete" next to the newly-added emoji.

Observed: Emoji deleted with no confirmation.

Expected: Confirmation dialog shown to the user. Otherwise you might accidentally delete an existing emoji by accident.

-------------------------------

Proposed change: 

1) When the user hits "Delete" for an existing custom emoji, a confirmation dialog is shown to the user (see attached) with text: 

"This action permanently deletes the custom emoji. Are you sure you want to delete it?"

![image](https://cloud.githubusercontent.com/assets/13119842/23633099/5d68f6e8-0292-11e7-8023-c3f86d5167a0.png)

Please note that the implementation of this is very similar to https://github.com/mattermost/platform/pull/5529 and should reuse components from that.

**Comment by VeraLyu** [comment]
Hi, may I take this one?

**Comment by jasonblais** [comment]
Absolutely! Thanks @VeraLyu!

**Comment by jasonblais** [comment]
Closed via #5740, thanks @VeraLyu!
