### ISSUE TITLE
Unable to create LDAP user.

### ISSUE THREAD

**Issue by bebald** [mattermost/platform#5684]
So we've started to use our mattermost server with LDAP setup recently. 
63/250 users had no problems whatsoever, but some get the following error message: 

> Unable to create LDAP user.

LDAP synch via system console works fine, whereas the command ./plattform ldap sync ends up with the following errors:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x633675]
goroutine 1 [running]:
panic(0xc9dae0, 0xc4200100d0)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mattermost/platform/enterprise/ldap.(*LdapInterfaceImpl).Syncronize(0x11c5cb0, 0x0)
/home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/enterprise/ldap/ldap.go:197 +0x45
main.ldapSyncCmdF(0x119b8e0, 0x11c5cb0, 0x0, 0x0, 0x0, 0x0)
/home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/cmd/platform/ldap.go:31 +0x60
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0x119b8e0, 0x11c5cb0, 0x0, 0x0, 0x119b8e0, 0x11c5cb0)
/home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:632 +0x23e
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42008ab40, 0x0, 0x0, 0x0)
/home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42008ab40, 0xc4200c7230, 0xb)
/home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
/home/ubuntu/workspace/msr/enterprise-release/src/github.com/mattermost/platform/cmd/platform/mattermost.go:50 +0x49f

Any ideas?

**Comment by jasonblais** [comment]
The platform command actually needs to be started from the mattermost directory. So the command should look like `./bin/platform`. Can you try running the command like that?

**Comment by bebald** [comment]
![mattermost_errormsg](https://cloud.githubusercontent.com/assets/26271611/23705954/66b06d0a-040c-11e7-9c15-71a705cda912.PNG)

Same error message.

**Comment by mschulzPED** [comment]
working in the same company as @bebald . we also have this error in mattermost.log

```
Couldn't save the user err=User.IsValid: model.user.is_valid.position.app_error, user_id=athoxgrqxffudf9ib6yue3idzo
```

which is defined in https://github.com/mattermost/platform/blob/master/model/user.go

```
if utf8.RuneCountInString(u.Position) > USER_POSITION_MAX_RUNES {
        return NewAppError("User.IsValid", "model.user.is_valid.position.app_error", nil, "user_id="+u.Id, http.StatusBadRequest)
    }
```
but only on some usernames.

**Comment by cpanato** [comment]
and for those usernames what is the value for the Position ? is bigger than 35 chars ?

**Comment by bebald** [comment]
What Position do you mean?

**Comment by mschulzPED** [comment]
I know that you mean the const USER_POSITION_MAX_RUNES=35, but what position do you mean.

**Comment by bebald** [comment]
exactly, what does USER_POSITION_MAX_RUNES=35 refer to?

**Comment by cpanato** [comment]
the position means the Role/title of the user.

like: Software engineer, sales team....

**Comment by bebald** [comment]
will check that...

**Comment by bebald** [comment]
yeb, I guess that's our problem ;)

**Comment by mschulzPED** [comment]
looks better, but the ./bin/platform ldap sync command throws exactly the same error, so that might be another problem.

**Comment by cpanato** [comment]
i will take a quick look on the dump and try to check the code

**Comment by mrjester888** [comment]
I have the same issue.  How do you override the max length?

**Comment by hmhealey** [comment]
I've created a ticket to have someone go increase the length of that field to 64 characters to match the other fields that come from LDAP (username, first/last name, etc). You can track that ticket here: https://mattermost.atlassian.net/browse/PLT-6102

In the mean time, you could work around this by disabling syncing of the position field from by setting `LdapSettings.PositionAttribute` to be empty.

**Comment by esethna** [comment]
Thanks for the responses. Closing this ticket to [track in JIRA](https://mattermost.atlassian.net/browse/PLT-6102).
