### ISSUE TITLE
[Help Wanted] Channel name can be only one character long but channel URL must be at least two characters

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5690]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5764)

Repro:
1. Click "+" to the right of "CHANNELS" at the top of the LHS
2. Type "a" in the Name field and click "Create Channel"

Observed: 
 1) Blue bar with text "Name must be 2 or more lowercase alphanumeric characters" appears.
 2) I'm brought to a new "Set URL" modal with error message "Channel URL must be 2 or more lowercase alphanumeric characters"
 3) Entering a URL of at least two characters allows me to create the channel

Expected:
 1) User remains on the channel creation modal with error text "Channel name must be 2 or more characters" (see attached)

![image](https://cloud.githubusercontent.com/assets/13119842/23726719/4e1855de-0423-11e7-959d-a520414e9347.png)

**Comment by jasonblais** [comment]
@ruzette would this be something you're interested taking a look? You fixed a potentially related issue here: https://github.com/mattermost/platform/pull/5570

**Comment by ruzette** [comment]
@jasonblais certainly! taking a look now. :)

**Comment by ruzette** [comment]
Hi @jasonblais, 

How should the localization string for the `Channel name must be 2 or more characters` error be approached? 

I can change the formatted string message from `This field is required` to  `Channel name must be 2 or more characters` but I'm not sure how to do it for all localization strings in the i18n folder. 

Below the actual error message from the channel modal when the channel name length is less than 2 characters. 
<img width="698" alt="screen shot 2017-03-08 at 10 44 16 pm" src="https://cloud.githubusercontent.com/assets/2659849/23735043/3864d040-0451-11e7-8b9d-b0c3c5de9a5c.png">

The error message is located in this line [new_channel_model.jsx#L107](https://github.com/mattermost/platform/blob/master/webapp/components/new_channel_modal.jsx#L107)

**Comment by jasonblais** [comment]
Thanks @ruzette, you only have to change the string in the `en.json` file, the other language files will be updated by our translators in https://translate.mattermost.com

**Comment by ruzette** [comment]
thanks @jasonblais! WIP has been removed from PR and is ready for review. https://github.com/mattermost/platform/issues/5693

**Comment by jasonblais** [comment]
Closed by #5693, thanks @ruzette! :)
