### ISSUE TITLE
[Help Wanted] Mobile iOS: Keyboard does not collapse after search is executed and keyboard focus is not removed from the search box

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5691]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5761)

Mobile iOS: Keyboard does not collapse after search is executed and keyboard focus is not removed from the search box

RC-testing (Search, line 4)

Repro:
1. Type "hello" in the search bar, then execute the search

Observed:
Keyboard does not collapse after search is executed and keyboard focus is not removed from the search box

Expected:
Keyboard should collapse after search is executed since the keyboard focus is removed from the search box

**Comment by jasonblais** [comment]
@saturninoabril Would you be interested taking a look?

This is related to your PR here https://github.com/mattermost/platform/pull/5360, but which was partially reverted by https://github.com/mattermost/platform/pull/5601

**Comment by saturninoabril** [comment]
@jasonblais sure, I'll take a look on this. thanks

**Comment by jasonblais** [comment]
Awesome, thanks @saturninoabril!
