### ISSUE TITLE
VIDEO

### ISSUE THREAD

**Issue by rahulchandyok** [mattermost/platform#5692]
Hello All,

I 'm trying to setup "Enable Mattermost WebRTC", not understand much

Like couldn't found parameter "GatewayWebsocketUrl"
Gateway Admin URL can setup on same server

Can I found any step by step configuration to setup VIDEO in matter-most.

Regards,
Rahul Chandyok

**REFERENCES*
https://docs.mattermost.com/administration/config-settings.html#webrtc-beta

For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Issue in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by lindy65** [comment]
Hi @rahulchandyok 

Thank you for your question!

There is [this post](http://forum.mattermost.org/t/how-to-enable-video/3007) on our forum which might be the information you're looking for?

Let us know if you need any further assistance!

**Comment by nikhils09ece** [comment]
Hi 
i have configured this thing as per  your instructions 
after checking the logs i found out this.
[2017/03/27 17:42:37 UTC] [EROR] /api/v3/webrtc/token:WebRTC.Token code=500 rid=7ekk778trif5tnk8sbtamse9uo uid=w47fa6ug5jnh9njnjzgb6xq1ro ip=112.196.181.162, 162.158.46.47 We encountered an error while connecting to the server [details: Post https://52.221.123.14:7089/admin: dial tcp 52.221.123.14:7089: getsockopt: connection timed out]

after going through this post request i found out this can you please what i have missed with
{"janus":"error","error":{"code":454,"reason":"Request payload missing"}}
