### ISSUE TITLE
Incorrect error message when duplicated channel urls are created

### ISSUE THREAD

**Issue by ruzette** [mattermost/platform#5694]
#### Steps to reproduce
1. Click "+" to the right of "CHANNELS" at the top of the LHS
2. Type "aaa" in the Name field and click "Create Channel"
3. Click "+" to the right of "CHANNELS" at the top of the LHS again 
4. Type "bbb" in the Name field 
5. Click on "(Edit)" beside the URL field.
6. Type "aaa" on the URL field and click "Change URL"
7. Click "Create New Channel"

#### Expected behavior
It should be `A channel with that URL already exists on the same team` 

#### Observed behavior
The error message shows as `A channel with that name already exists on the same team` even though the channel's display name does not exist in the team channels. The channel's url, however, exists for different display name. 

<img width="1277" alt="screen shot 2017-03-08 at 10 15 04 pm" src="https://cloud.githubusercontent.com/assets/2659849/23735681/1ae3a056-0455-11e7-978e-2d287dc46672.png">

**Comment by lindy65** [comment]
Hi @ruzette 

Thank you for your report!  We have reproduced the issue and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-5863) to fix it.

**Comment by jasonblais** [comment]
Thanks again! We'll track the issue in Jira: https://mattermost.atlassian.net/browse/PLT-5863
