### ISSUE TITLE
Send a different notification message for channel-wide mentions versus individual mention

### ISSUE THREAD

**Issue by jedfonner** [mattermost/platform#5715]
#### Summary
It's not possible to differentiate "@all" mentions from username mentions in a push notification

#### Steps to reproduce
1. Mention a user by typing @user.name in a room, notice the push notification message says "[username] mentioned you in [room name]"
1. Mention a user by typing @all in a room - notice the push notification message says "[username] mentioned you in [room name]" <-- same as above

#### Expected behavior
1. When a user types @user.name in a room, the push notification message should say "[username] mentioned you in [room name]"
1. When a user types @all or @channel in a room, the push notification message should say "[username] mentioned **everyone** in [room name]"

![2017-03-09_17-31-44](https://cloud.githubusercontent.com/assets/344481/23773799/d2791e00-04ee-11e7-8992-f99b1b92a4b2.png)

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback @jedfonner! 

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Actually, looks like you might have already upvoted the feature: https://mattermost.uservoice.com/forums/306457-general/suggestions/13494636-change-wording-in-app-notifications-that-are-chan
