### ISSUE TITLE
[Help Wanted] Team Name setting should let you save the same team name without throwing an error

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5722]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5815)

Repro: 
1. Team Settings > Team Name > Edit
2. Don't change anything
3. Press Enter

Observed: Error message "Please choose a new name for your team"

![image](https://cloud.githubusercontent.com/assets/13119842/23811059/4eb5b740-05a2-11e7-9ead-f41d362042e2.png)

Expected: No error message, it should just collapse the setting and leave the name as is like the Account Settings fields do.

**Comment by R-Wang97** [comment]
@jasonblais I can take a look at this!
