### ISSUE TITLE
Messages about contacts coming online/offline/idle ?

### ISSUE THREAD

**Issue by sokoow** [mattermost/platform#5724]
#### Summary
Is there an option to see messages about contacts coming online/offline/idle?

#### Steps to reproduce
Just use mattermost

#### Expected behavior
It'd be nice upon people leaving/joining the system, to be able to see a message on the channel about that. It's quite hard to keep track of who's currently online in mattermost.

#### Observed behavior
It's quite hard to keep track of who's currently online in mattermost.

**Comment by lindy65** [comment]
Thanks, appreciate your feedback @sokoow.  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
