### ISSUE TITLE
[Help Wanted] Update push notification text when a message contains only attachments

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#5730]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3901)

Repro: Send a message with file attachment(s) but no text. 

Observed: Push notification says `@username:`
<img width="360" alt="screenshot 2017-03-10 15 18 03" src="https://cloud.githubusercontent.com/assets/9354841/23818434/e239717a-05c8-11e7-90b7-013f23b194fa.png">

Expected: Push notification should say `@username: Uploaded one or more files.`

**Comment by jasonblais** [comment]
Fixed in Mattermost v4.0
