### ISSUE TITLE
[Help Wanted] Favorite channels should be sorted alphabetically regardless of channel type

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5737]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5770)

Observed:
Currently favorite channels are ordered with public channels first (alphabetically), then private channels (alphabetically). 

![image](https://cloud.githubusercontent.com/assets/13119842/23826444/4bd48ee8-066a-11e7-9c5b-daa8694a71eb.png)

Expected:
Favorite channels should be sorted alphabetically regardless of channel type.

**Comment by R-Wang97** [comment]
@jasonblais I can take a look at this 😄

**Comment by jasonblais** [comment]
Awesome! 👍

**Comment by jasonblais** [comment]
Closed via #5379, thanks @R-Wang97!

**Comment by FeanorsCurse** [comment]
Well, I'd prefer the exact opposite - have channels sorted by type (users, other channels) and then alphabetically (google search lead me here actually). Would it be possible to have a setting for users to be able to choose?
