### ISSUE TITLE
iOS white strip with dark theme

### ISSUE THREAD

**Issue by jkopriva** [mattermost/platform#5769]
#### Summary
On iPhone 6S plus with iOS 10.2.1 is a white strip in notifications area when using Mattermost Dark Theme - its ok, when you use default theme, but not with dark theme.

Mattermost Team Edition
Version 3.6.0 (3.6.2)
Database: postgres

#### Steps to reproduce
Just set Matterhost dark scheme - you will see it right away.
![img_2097](https://cloud.githubusercontent.com/assets/17871936/23941879/c33d8414-096a-11e7-9b96-3c14098d0440.PNG)

#### Expected behavior
To have also dark strip in notifications area.

**Comment by lindy65** [comment]
Hello @jkopriva 

Thank you for your issue report!

We think this might be fixed in the [latest version (v3.7.3)](https://about.mattermost.com/download/) release March 16th.

Could you check whether this issue is fixed for you once you've upgraded and let us know?

Thanks!

**Comment by jkopriva** [comment]
Hi @lindy65 ,

Thanks for reply, I will let you know if it is fixed, when updated version will be available on App Store.

Cheers

**Comment by lindy65** [comment]
Perfect!  Thanks @jkopriva :)

**Comment by lindy65** [comment]
Hi @jkopriva,

Just checking back on whether upgrading to the latest version helped solve your issue?

**Comment by jkopriva** [comment]
Hi @lindy65, 

I have now on iPhone version 3.7.0 (3.7.3), but the white strip still exist:(

Cheers

**Comment by lindy65** [comment]
Thanks @jkopriva,

I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-6318) to investigate the issue

**Comment by jasonblais** [comment]
Thanks @jkopriva! Are you referring to the white strip at the top?

![image](https://cloud.githubusercontent.com/assets/13119842/25257311/397c3e7a-2605-11e7-8aba-1263f70d3356.png)

**Comment by jkopriva** [comment]
Hi @jasonblais , exactly:)

**Comment by jasonblais** [comment]
Ah, we can't control that strip with the existing app from the App Store.

It's fixed in the next-generation mobile apps we're working on for iOS and Android, which will be production-ready soon! You can find out here if you want to try them out https://about.mattermost.com/mattermost-3-8/#ios-and-android-apps
