### ISSUE TITLE
[Help Wanted] Posts in search results should show thumbnails of attached files and images

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#5776]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1658)

**Observed:** It's currently not possible to see if a search result has any attachments on the post

**Expected:** Show thumbnails for search results with attachments (see screenshot). Clicking on the thumbnail should open the file previewer, and clicking the download icon should download the file (same behaviour as in posts).

**Out of scope:** This ticket does not add searching for files based on their name, that will be done separately.

<img width="403" alt="screenshot 2017-03-13 11 53 19" src="https://cloud.githubusercontent.com/assets/9354841/23971314/d96f04cc-09a3-11e7-89e9-2cf91a41ed2b.png">

**Comment by VeraLyu** [comment]
Hi, may I take this one?

**Comment by jasonblais** [comment]
Absolutely 👍 Thanks for being so active across our project!
