### ISSUE TITLE
Search does not find words in URL's

### ISSUE THREAD

**Issue by zeronickname** [mattermost/platform#5786]
#### Summary
Searching for word patterns (with or without wildcards) does not find matches from URL's

#### Steps to reproduce
Send a message in a channel with any text that mattermost converts into a URL. eg: `www.google.co.uk/qwerty4`
Now type in `qwerty4` (or `*qwerty4*`) in the search box and hit enter
![search_fail](https://cloud.githubusercontent.com/assets/538117/24004269/c3014e1a-0a5d-11e7-8897-a4198d8d6dcc.png)
#### Expected behavior
The message with the URL is found

#### Observed behavior
The search result does not find the message

**Comment by lindy65** [comment]
Hi @zeronickname 

Thanks for your report!  I haven't managed to reproduce your issue and searching for "qwerty4" in the string "http://www.google.co.uk/qwerty4" is working for me.

You don't say whether your deployment is using a Postgres database?  If it is, searching for websites and emails does not work properly.  You can view the known issues that references this [here](https://docs.mattermost.com/administration/changelog.html#release-v3-1-0)

If your deployment is not using a Postgres database, please get back to us and we'll investigate.

Thanks!

**Comment by zeronickname** [comment]
Ah, yes, we are using postgres. I missed that issue with the postgres database. Sorry about that!

Thanks!

**Comment by lindy65** [comment]
No worries @zeronickname :)

**Comment by scadu** [comment]
Is there any chance to investigate this issue that occurs on Postgres?
For example, trying to search `https://github.com/mattermost/platform/issues/5786` does not work with `5786`, nor `*5786*`. We use 4.0.0 (4.0.1).

**Comment by chmielas** [comment]
If there is a plan to fix this issue ? I`m using  5.2.0  on postgres and I have still this problem. What is current solution/ workaround  ? I need to provide possbilty to search URL for all my users.

**Comment by lohfu** [comment]
2 years later it still not possible to search for URLs... are there any updates on this?

**Comment by lohfu** [comment]
@lindy65 the URL you posted, https://docs.mattermost.com/administration/changelog.html#release-v3-1-0, does not seem to have anything to do with the discussed issue.

**Comment by lindy65** [comment]
Hi @lohfu - the relevant information is under 'Known Issues' here: https://docs.mattermost.com/administration/changelog.html#id621

>On Postgres databases, searching for websites and emails does not work properly and hashtags which end with an inverted questionmark aren’t properly highlighted.

`zeronickname` posted above:
> Ah, yes, we are using postgres. I missed that issue with the postgres database. Sorry about that!

**Comment by lohfu** [comment]
@lindy65 yes i have figured out that only installations using postgres have these problems. from what i understand there are no plans on fixing this, is this correct? if this is so, it should be much clearer in the documentation that this bug exists and that it will never be fixed. for many people this is a very serious issue.

for example, under https://docs.mattermost.com/install/requirements.html#database-software there is no mention that you cannot search for parts of URLs when using postgres. it only mentions emails. preferably include an example, eg making clear that searching for github.com or reddit.com will never return any results.

**Comment by lindy65** [comment]
Thanks for your feedback @lohfu, appreciated! I'm going to pass this on to the product team and ask them to clarify in the relevant documentation. 👍

**Comment by lohfu** [comment]
@lindy65 nice, but i still havent gotten an answer: are there any plans on attempting to fix this?

**Comment by lindy65** [comment]
Hi @lohfu :) 

One of our product team folk will respond to you as soon as possible.  👍

**Comment by ethervoid** [comment]
@lohfu there is a ticket to fix this issue: https://mattermost.atlassian.net/browse/MM-7779

**Comment by mr-gosh** [comment]
The Problem is still present on our deployment on MM 7.1.3
