### ISSUE TITLE
When an emoji reaction is removed, it leaves a blank space in the message area

### ISSUE THREAD

**Issue by S6066** [mattermost/platform#5787]
Mattermost 3.7 Enterprise edition.
Mattermost client 3.5
http://i.imgur.com/nuXcQlj.gif

**Comment by lindy65** [comment]
Hi @S6066,

Thanks for your report!

We've repro'd your issue (on the browser version too) and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-5941) to track it.

**Comment by jasonblais** [comment]
A PR has been merged here and should be resolved in Mattermost v3.8: https://github.com/mattermost/platform/pull/5879

Thanks @S6066 for the report :)
