### ISSUE TITLE
[Proposal]Add a pinned_posts table, remove corresponding IsPinned column in Posts

### ISSUE THREAD

**Issue by jostyee** [mattermost/platform#5792]
#### Summary
Glad to find that https://github.com/mattermost/platform/pull/4217 has been merged, but IMHO alter current `Posts` table is not a best choice for the implementation. It affects all existed posts data in all teams, creates a index with much higher costs if the table is relatively huge(e.g. gophers.slack.com has more than 2 million messages by now).

#### Possible fixes
Create a pinned_posts table:

| id | channel_id(idx) | post_id |
|----|------------|---------|
|    |            |         |

Then a simple join query could match the need, lightweight.
@Zhouzi @grundleborg

**Comment by Zhouzi** [comment]
Makes sense! I don't see any drawbacks so we could work on that. Depends on the calendar though. Don't know if it could delay something the core team had scheduled?

**Comment by jasonblais** [comment]
@jostyee thanks for the suggestion! Would this be something you'd like to help submit a pull request for?

**Comment by jostyee** [comment]
@jasonblais Unfortunately I won't be available until late next month, but if there's no one else willing to implement, I can work on it then.

**Comment by jasonblais** [comment]
Thanks @jostyee! No worries, completely understand :)

I actually talked to one of our developers and he mentioned that you would still need a field on the object that tells you to do the join query. For pinned posts, the only thing we need is a YES or NO. So it makes sense to just have it on the object for now. 

We might be doing an attribute table in the future for users and teams, and it might make sense to do one for posts at that point.

**Comment by jostyee** [comment]
@jasonblais Thank you for explanation, close this issue for now.
