### ISSUE TITLE
Dockerless installation

### ISSUE THREAD

**Issue by saschalalala** [mattermost/platform#58]
I'd like to test mattermost, but I do not want to install it with docker. Could you please provide an installation method that does not need docker? Or can I just clone and run it?

**Comment by ondraknezour** [comment]
+1

**Comment by obersterhirte** [comment]
Have a look at  https://github.com/mattermost/platform/blob/master/Dockerfile. It's all the documentation you need for setting up your non-docker ubuntu box ;)

**Comment by ChicagoDave** [comment]
Seriously. Why is docker necessary? Why is there no package install?

**Comment by it33** [comment]
Hi @ChicagoDave, @saschalalala, @ondraknezour, package install instructions is something we definitely want to add. I've added a feature request personally and upvoted it at: https://mattermost.zendesk.com/hc/communities/public/questions/204330815-Package-install-instructions

@obersterhirte thanks for the doc mention. You're correct, and hopefully we can improve guidance from the starting point there.
