### ISSUE TITLE
3.7.1 behavior does not match changelog

### ISSUE THREAD

**Issue by jtdaugherty** [mattermost/platform#5800]
The release notes for 3.7.1 at https://docs.mattermost.com/administration/changelog.html state:

```
Removed routes (APIv3):

* GET at /channels/more (replaced by /channels/more/{offset}/{limit})
```
But in testing against an installation of 3.7.1, it appears that this is not the case. The old endpoint of `/api/v3/teams/(teamid)/channels/more` is still responsive, and attempts to use `/api/v3/teams/(teamid)/channels/more/(limit)/(offset)` result in a `404 Not Found` response.

CC @aisamanra @dagit @dwest-galois

**Comment by jasonblais** [comment]
Looks like we didn't remove it in v3.7, I have updated this entry in the changelog. We'll remove it in v3.8 instead, ticket here: https://mattermost.atlassian.net/browse/PLT-5948

For the new endpoint, we tried and it seems to be working. Would the [documentation here help](https://api.mattermost.com/master/#tag/channels%2Fpaths%2F~1teams~1%7Bteam_id%7D~1channels~1more%2Fget)? 

![image](https://cloud.githubusercontent.com/assets/13119842/24054921/6be262c4-0b14-11e7-82fd-12c55e7be69b.png)

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, let us know and we'd be happy to help @jtdaugherty

**Comment by jtdaugherty** [comment]
Since this has been confirmed as moved to 3.8, that works for me. Thank you!
