### ISSUE TITLE
display bug when using Exo 2 font

### ISSUE THREAD

**Issue by blazer2x** [mattermost/platform#5801]
#### Summary
When using Exo 2 font it doesn't show ``` (consecutive tilders correctly) instead it shows a single ` character where each consecutive ` stacks on top of.

#### Steps to reproduce
Simply set the font to Exo 2, use either the web version, windows or android app and type ``` into the message input box

#### Expected behavior
Each ` character is suppose to show up next to each other like ``` not as a single `

#### Observed behavior
When the tilders are pressed they all overlap over each other in the message input box

#### Possible fixes
Using a different font resolves the issue

**Comment by lindy65** [comment]
Hi @blazer2x 

Thanks for the report!  We've reproduced the error and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-6029) to fix the issue.

**Comment by lindy65** [comment]
Hi @blazer2x 

We've discovered the issue is with the font itself, not with our code so we've closed the ticket off for now. There are some plans to consider removing custom fonts for issues like this and to improve performance.
