### ISSUE TITLE
Outgoing Webhooks management stuck loading

### ISSUE THREAD

**Issue by fjarlq** [mattermost/platform#5805]
#### Summary
After creating an outgoing webhook, the Outgoing Webhooks management pane becomes forever stuck loading. 

#### Steps to reproduce
1. Be running Mattermost 3.1.0 (July 2016) with Postgres
2. Upgrade to Mattermost 3.3.0-rc2 (August 2016)
3. Upgrade to Mattermost 3.7.1
4. Create an outgoing webhook
5. Reload the Outgoing Webhooks management pane and notice it becomes stuck loading

#### Expected behavior
This was my first time ever creating an outgoing webhook, so I was just experimenting. I expected that I would not get it right the first time, but I also expected that I could at least edit or delete my broken webhook as needed.

#### Observed behavior
Mattermost reports "We couldn't get the webhooks" in the blue bar along the top, and when I try to visit the Outgoing Webhooks management pane at `/teamname/integrations/outgoing_webhooks` it gets forever stuck loading.

Reloading the page doesn't help. Restarting the Mattermost server and NGINX doesn't help.

Error message (with possibly-private info obscured) in `mattermost.log`:
`[2017/03/18 22:33:10 PDT] [EROR] /api/v3/teams/za3ybtxxxxxxxxxxxxxxxxxxxx/hooks/outgoing/list:SqlWebhookStore.GetOutgoingByTeam code=500 rid=f7xixxxxxxxxxxxxxxxxxxxxx uid=3hftgnxxxxxxxxxxxxxxxxxxxx ip=2601:681:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx We couldn't get the webhooks [details: teamId=za3ybtxxxxxxxxxxxxxxxxxxxx, err=sql: Scan error on column index 13: converting driver.Value type bool ("false") to a int: invalid syntax]`

So, I cannot delete the broken webhook. Screenshot:

![outgoing-webhooks](https://cloud.githubusercontent.com/assets/441483/24077886/ba34c274-0c21-11e7-9f62-70d9ff96d976.png)

**Comment by fjarlq** [comment]
Here's a dump of the `outgoingwebhooks` row (with possibly-private info obscured):

`id,token,createat,updateat,deleteat,creatorid,channelid,teamid,triggerwords,callbackurls,displayname,description,contenttype,triggerwhen`
`kkd69qxxxxxxxxxxxxxxxxxxxx,g34cyxxxxxxxxxxxxxxxxxxxxxx,1489889015360,1489889015360,0,3hftgnxxxxxxxxxxxxxxxxxxxx,"",za3ybt1fxxxxxxxxxxxxxxxxxx,"[""foobar""]","[""http://127.0.0.1/webhook/foobar""]",foobar,Foobar blah hey,application/json,f`

**Comment by fjarlq** [comment]
The only column in `outgoingwebhooks` that is type bool is `triggerwhen`.

**Comment by fjarlq** [comment]
Hmm, but according to `UpgradeDatabaseToVersion33()`, `triggerwhen` should be type integer:

https://github.com/mattermost/platform/blob/3ada7a41a7fb13abef19dd63dc56b720900dbaa9/store/sql_upgrade.go#L182

So did my server not perform that database upgrade? According to `mattermost.log` it *did* perform that upgrade:

```
[2016/08/08 17:57:44 PDT] [WARN] The database schema version of 3.2.0 appears to be out of date
[2016/08/08 17:57:44 PDT] [WARN] Attempting to upgrade the database schema version to 3.3.0
[2016/08/08 17:57:44 PDT] [DEBG] Deleting any unused pre-release features
[2016/08/08 17:57:44 PDT] [WARN] The database schema has been upgraded to version 3.3.0
```

As well as the upgrades for 3.4.0, 3.5.0, 3.6.0, and 3.7.0.

**Comment by fjarlq** [comment]
Immediately after creating the outgoing webhook, the management pane did show display the information about the webhook. I'm sure about that because I remember looking it over and copying the token. It was only when I later tried to load the outgoing webhooks management pane that it became stuck loading.

**Comment by fjarlq** [comment]
Looks like this problem is due to the fact that on August 8, 2016 I upgraded from Mattermost 3.1.0 to Mattermost 3.2.0-rc2.

On August 2 `triggerwhen` had been changed to type boolean: https://github.com/mattermost/platform/pull/3716/files

Then on August 9 it was changed back to type integer: https://github.com/mattermost/platform/pull/3770/files

Looks like I wasn't the only person to get tripped up by this: https://mattermost.atlassian.net/browse/PLT-3870

**Comment by fjarlq** [comment]
So, one potential cause of the "stuck loading" problem was fixed months ago. I will manually fix my database and move on.

But I wonder if the Outgoing Webhooks management pane could be strengthened so that it doesn't get stuck loading when something goes wrong internally. I realize that might be too much to ask for. I'll leave this issue open so that the right people might consider that possibility. Thanks!

**Comment by jasonblais** [comment]
Really sorry about the slow response @fjarlq,

Yes, unfortunately there was an issue that was subsequently fixed -- glad to hear you got it resolved.

We're considering redesigning some of our integrations screens, so we'll consider revisiting the loading issue at that time. But given it'll be a rare case, it's probably not a priority for now.

Thanks again for the initial report!
