### ISSUE TITLE
mattermost-push-proxy: which Apple program to enroll into?

### ISSUE THREAD

**Issue by Fonata** [mattermost/platform#5807]
Question for Apple experts: We use the free Mattermost version and it works wonderfully. I am tasked to implement the [mattermost-push-proxy](https://github.com/mattermost/mattermost-push-proxy) for our company's iPhones. I need to obtain a push certificate from Apple. 

My question: for generating an APNS push certificate, do I need to enroll 
- ``Apple Developer Program`` or 
- ``Apple Developer Enterprise Program``?

Thank you in advance!

**Comment by Fonata** [comment]
For my own reference: I just learned that the page I need to generate the certificate is [Certificates, Identifiers & Profiles](https://developer.apple.com/account/ios/certificate)

**Comment by coreyhulen** [comment]
Most enroll in Apple Developer Enterprise Program to push the app into their own enterprise app store.

If you have a small number of users you might be able to use Apple Developer Program and never release the apps into the public app store and just sign everyone up as a beta user.  You would need todo your own investigation to see if this would work for you.

**Comment by Fonata** [comment]
Thanks, coreyhulen. This issue is not about getting apps installed but rather notifications about new messages to reach devices.

Here is what Apple wrote a few hours ago:
> Christian, before I continue, please let me inform you that we have different services. One is Apple Push Notification Service, this is for the company program. More information on this can be found here: > https://developer.apple.com/notifications/
> To speed up the process, you are welcome to send me your enrollment ID once you have it. I would be more than happy to assist you and minimize your waiting time. I included the enrollment links for you below:
> Company: https://developer.apple.com/programs/enroll/ 

So appearently Company = Organization = $ 99 per year.

I'll close this issue once I've got APNS working.

**Comment by lindy65** [comment]
Hi @Fonata,

Has your issue been sorted?  Is it okay for us to close this issue off?

**Comment by Fonata** [comment]
I haven't completed to wire it all together. We can close the issue now and I'll document my findings here once I know more.

**Comment by lindy65** [comment]
Thanks @Fonata :)
