### ISSUE TITLE
[Help Wanted] Renaming a Channel: System Message is posted immediately, but channel name is not updated until refresh

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5834]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5988)

Repro: User A updates Channel Display Name

Observed: User B sees a System Message post saying the channel name was updated, but the channel name is still the same. 

Expected: Channel name should update.

NOTE: Reproduces similarly for other fields such as channel header.

**Comment by cpanato** [comment]
I will take this one asap this https://github.com/mattermost/platform/pull/6566 is merged :)

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6677
