### ISSUE TITLE
Missing translation in invitation link on Off-topic

### ISSUE THREAD

**Issue by robert843** [mattermost/platform#5847]
![bug1](https://cloud.githubusercontent.com/assets/7444209/24223390/3a261492-0f56-11e7-974a-6eb332297011.png)

#### Possible fixes
Patch:
[patch.zip](https://github.com/mattermost/platform/files/863079/patch.zip)

**Comment by jasonblais** [comment]
Thanks @robert843! And sorry for the delayed response,

Your patch looks good! Would you open to submitting a pull request for it? Make sure to include it in the relevant `en.json` file, either at 
 - https://github.com/mattermost/platform/blob/master/webapp/i18n/en.json 
or 
 - https://github.com/mattermost/platform/blob/master/i18n/en.json

PS: Huge thanks for your help with Polish translations 👍

**Comment by jasonblais** [comment]
Thanks again @robert843! I've submitted a PR based on your batch: https://github.com/mattermost/platform/pull/6130

Thanks for the contribution, much appreciated
