### ISSUE TITLE
Newbie: Which IDE to be used for developing Mattermost

### ISSUE THREAD

**Issue by tejassawai** [mattermost/platform#5848]
I am new to golang, my simple question is : Which IDE to be used for developing Mattermost?
Thanks

**Comment by jasonblais** [comment]
Hey @tejassawai, sorry, can you help describe what you're trying to accomplish?

Are you setting up a development environment? If so, we have some developer machine setup guides here: https://docs.mattermost.com/developer/developer-setup.html

Does that help?

**Comment by tejassawai** [comment]
No, I don't want full development environment. I just want to open mattermost project in some IDE. So that I can modify,build and run on it.

**Comment by namedrisk** [comment]
well if you're building on Linux but want to edit on windows, I would suggest you vs code which comes with git with it so you can simple commit your changes to a branch and then make build or make run on your Linux machine to test it.

But to give you a better answer we would need to know more about what is your case... do you want to edit on windows and compile on windows or how it is?

**Comment by josephGuo** [comment]
liteide/vscode/idea... Whatever you choose is ok

**Comment by lindy65** [comment]
Hi @tejassawai 

Just circling back to check whether you have managed to resolve your IDE issue?

**Comment by lindy65** [comment]
Hi @tejassawai,

I'm going to close this issue off for now.  If you still have questions, please feel free to re-open the issue and we'll be glad to help!
