### ISSUE TITLE
User 'props' attributes should be visible

### ISSUE THREAD

**Issue by BRH-Enrian** [mattermost/platform#5855]
#### Summary
According to v3 REST API, fetching a User should reveal any 'props' it has.

#### Steps to reproduce
v3.7.3

#### Expected behavior
If I have added one or more custom 'props' key/values to a user, I would expect to be able to see those keys/values when I receive the JSON representing the user.

#### Observed behavior
The JSON has no 'props' attributes for any users after a GET request.

#### Possible fixes
The problem is due to User.ClearNonProfileFields method in user.go. This is from a patch I will be submitting to resolve the issue in a configurable way that retains current behavior unless overridden in a Mattermost configuration setting:

```
@@ -325,7 +335,6 @@ func (u *User) ClearNonProfileFields() {
 	u.MfaSecret = ""
 	u.EmailVerified = false
 	u.AllowMarketing = false
-	u.Props = StringMap{}
 	u.NotifyProps = StringMap{}
 	u.LastPasswordUpdate = 0
 	u.LastPictureUpdate = 0
```

**Comment by lindy65** [comment]
Hi @BRH-Enrian, 

I'm going to close this issue off for now based on your discussion with `hmhealey` in the issue referenced above.
