### ISSUE TITLE
Total Posts for System and Team are not the same for single Team setup

### ISSUE THREAD

**Issue by realrolfje** [mattermost/platform#5875]
#### Summary
In a Mattermost 3.7.3 system with one Team, the Total Posts counter on the System Statistics page is not equal to the Total Posts on the Team Statistics page.

#### Steps to reproduce
Installed Mattermost 3.6.0, create team, generate public posts, private channel posts, and direct messages between users. Upgrade to 3.7.2. Open the "System Console" menu and add the team in the new TEAMS menu on the left. Compare Total Posts numbers. 

#### Expected behavior
When having just one Team, I expect the Total Posts for the system to be equal to the Total Posts for the Team.

#### Observed behavior
In our system, the Total Posts on the System Statistics page shows 9596 posts, but the Total Posts on the Team Statistics page shows 8647 posts. Where/what are the other 949 posts?

#### Possible fixes
I suspect that the query for the Team Statistics excludes either deleted posts, or posts by bots, whereas the System Statistics page just counts total rows in the posts table regardless of state or type.

<img width="833" alt="screen shot 2017-03-25 at 22 29 47" src="https://cloud.githubusercontent.com/assets/3617571/24326334/40f0f56e-11ac-11e7-9fa0-e2d4e0d73d7f.png">

<img width="833" alt="screen shot 2017-03-25 at 22 29 58" src="https://cloud.githubusercontent.com/assets/3617571/24326338/47768782-11ac-11e7-8ee6-b50a8f98f825.png">

**Comment by jasonblais** [comment]
That's a good question. 

It's likely direct messages between users -- since direct message conversations aren't tied to a team, they wouldn't be included in the post count in your team statistics page.

**Comment by realrolfje** [comment]
I probably can compere the SQL used to build the two numbers to see if this is indeed the case, but maybe it is better to split the number on the System Statistics page into posts tied to teams and posts not related to teams so the numbers add up. Making that change would require the dev to check that code anyway.

**Comment by jasonblais** [comment]
Thanks @realrolfje! I've submitted a change to our docs on the definition of "total posts" for team statistics: https://github.com/mattermost/docs/pull/1091

I've actually got a ticket to update System Console statistics here: https://mattermost.atlassian.net/browse/PLT-2099

I'd love to hear feedback on what types of metrics you'd like to see as a System Administrator. One potential improvement is to separate the Site Statistics Posts to 'team posts' and 'direct message posts'

**Comment by realrolfje** [comment]
Hi Jason,

I can see https://mattermost.atlassian.net/secure/Dashboard.jspa <https://mattermost.atlassian.net/secure/Dashboard.jspa>, but I can’t access ticket PLT-2099, I think I don’t have permissions to see that ticket.

I think the statistics can be a bit higher resolution, maybe it’s a good idea to take a look at Kibana or Grafana for graphing ideas. In my setup, I use Munin and some PSQL queries to generate statistics so I can correlate them with CPU load and Network traffic.

Attached to this mail are our ”Active Sessions” graph, and "number of posts per minute" graph. These are relatively expensive to run on the database, I think it would use less resources if the API would provide these or similar numbers, but that needs some careful design to prevent a volatile API.

The title of our ”active sessions” graph is misleading; it is actually active unique users. There are many more sessions, most users have an average of 6 sessions in the databaase.

Kind regards,
Rolf

**Comment by jasonblais** [comment]
Ah sorry, I've updated the ticket to be public: https://mattermost.atlassian.net/browse/PLT-2099

Thanks for the feedback, very helpful!

**Comment by realrolfje** [comment]
I see the graphs in the mail did not show in this issue. Here they are: 
<img width="497" alt="mattermost_posts-day" src="https://cloud.githubusercontent.com/assets/3617571/25169218/807cc526-24e6-11e7-9ae1-9dae7dc502b9.png">
![mattermost_sessions-day](https://cloud.githubusercontent.com/assets/3617571/25169223/864e350c-24e6-11e7-8e5f-1b62e04c5e3c.png)

**Comment by jasonblais** [comment]
That looks great @realrolfje! 

Would you be open to [sharing your work with the Mattermost community](https://www.mattermost.org/share-your-mattermost-projects/)?

Many others in the community might be interested in your work, and we'd be happy to promote it.

**Comment by realrolfje** [comment]
It is just 3 plugins for Munin (simple shell scripts querying the database) which are part of a bunch of other munin plugins I user for system monitoring. It is a [public github repository](https://github.com/realrolfje/munin-plugins), people are free to use it.

I am not sure this qualifies as an "installer" or "integration" as mentioned in your forms :-)

**Comment by jasonblais** [comment]
Haha cool, thanks @realrolfje :)

Let me know if there's anything else you'd like to cover in this issue?

**Comment by realrolfje** [comment]
Hi Jason, no the original issue is solved in 3.8.2, please close this one, I'll be happy to report a new issue if something comes up (keeps the discussions nice and separated). Thanks for the great support!

**Comment by jasonblais** [comment]
Anytime! :)
