### ISSUE TITLE
Nicer output from make check-server-style

### ISSUE THREAD

**Issue by bradhowes** [mattermost/platform#5876]
#### Summary
The output from make check-server-style is not easy to read when there are formatting issues.

#### Steps to reproduce
v3.7.3
Edit a *.go file, move to a non-empty line and insert a space at the beginning of it. Save and run make check-server-style.

#### Expected behavior
If there are differences between format of a source file and what gofmt command generates, then make check-server-style spits out the deltas between the source and the ideal. The deltas should clearly show the files and line numbers where the differences reside.

#### Observed behavior
The output does appear if there are differences between source and ideal, but the output shown by Make has no line endings, making the output very difficult to parse.

#### Possible fixes
I'd like to replace the check-server-style target in Makefile to be:

```
@gofmt -d -s api/ model/ store/ utils/ manualtesting/ einterfaces/ cmd/platform/ 2>&1 > gofmt_output.log
@if test -s gofmt_output.log; then \
    cat gofmt_output.log; \
    echo "gofmt failure"; \
    exit 1; \
else \
    echo "gofmt success"; \
    rm gofmt_output.log; \
fi
```

This preserves the formatting from the gofmt command, and IMO there is less cumbersome Make parsing involved.

**Comment by lindy65** [comment]
Hi @bradhowes,

Hope you're well?

I see our PR reviewers have asked for your action on [this PR](https://github.com/mattermost/platform/pull/5877) so if we could have your help taking a look that would be awesome!

Thanks!

**Comment by lindy65** [comment]
Hi @bradhowes, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
