### ISSUE TITLE
[Help Wanted] Do Not Disturb mode

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5905]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4341)

### Functionality

When Do Not Disturb is on, 
1. Desktop, push and email notifications for the Mattermost instance are not sent.
2. Unread channels in the left-hand side still bold and show mention jewels as normal.

When Do Not Disturb is turned off, notification preferences for desktop, email and push return to the state they were in before.
### User Interface

Add an online indicator to the profile picture in the header. The online indicator shows the current online status of the account. 

EDIT: Currently the profile picture is hidden from the top left if it hasn't been manually set yet. Change it so the profile picture is always shown in the top left, even if it is the default generated profile picture.

![image](https://cloud.githubusercontent.com/assets/14333569/19451377/45aa768a-946a-11e6-87a0-4cb608328d48.png)

Clicking the status icon or the profile picture offers a dropdown menu to select a status or go into DND mode.
1. First dropdown opens the options for "Online", "Away", "Offline", "Do Not Disturb >".
2. Hovering over "Do Not Disturb" opens a secondary dropdown with the options: "1 hour, "2 hours", "4 hours" "8 hours", "24 hours", "Indefinitely".

![image](https://cloud.githubusercontent.com/assets/14333569/19451390/549fe936-946a-11e6-88df-3e20029f1007.png)

When Do Not Disturb mode is on, the status icon is overlayed with a "z" (see mock-up) in the team header and in the direct message list on the left-hand-side.

![image](https://cloud.githubusercontent.com/assets/14333569/19451406/615d1446-946a-11e6-8ec4-698cc1994a03.png)
### Slash Command
1. "/dnd" will silence notifications for all teams by turning on DND mode. 
   - System message: "You will not receive notifications for your teams until Do Not Disturb is turned off ."
2. "/dnd X" will silence notifications for all teams for a specified number of hours, X.
   - System Message: "You will not receive notifications for your teams for X hours or until Do Not Disturb is turned off."

DND mode is turned off by changing your status to anything other than "Do Not Disturb". This can be done using the user interface dropdown or the slash commands `/online`, `/away`, `/offline`

**Comment by esethna** [comment]
Closing this ticket for now to discuss some design options.

**Comment by theCroh** [comment]
Any progress on this issue? This is a showstopper for our sales team since they need to be able to easily mute notifications when having customer meetings.

**Comment by samtuke** [comment]
We'd also love to see this released. Use case: different sysadmins on duty, many automated monitoring notifications arrive 24/7, and they need to sleep (as in human sleep)!

**Comment by tyronx** [comment]
This is indeed quite the showstoper being unable to temporarily disable notifications

**Comment by sokratisg** [comment]
Any progress on this one?

**Comment by esethna** [comment]
Hi all, FYI we've reopened this ticket with a modified design if anyone is interested in working on it: https://github.com/mattermost/mattermost-server/issues/7633

Thanks for your interest! @theCroh @samtuke @tyronx @sokratisg

**Comment by tyronx** [comment]
Yay! :-)

**Comment by schmidt-fu** [comment]
Most appreciated. Keep up the good work :-)
