### ISSUE TITLE
Paste snapshot from clipboard disfunctioning

### ISSUE THREAD

**Issue by jostyee** [mattermost/platform#5910]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Can't paste a snap from clipboard if enabling emoji picker on macOS

#### Steps to reproduce
1. Run the HEAD version on server.
2. `Account Settings` -> `Advanced` -> `Preview pre-release features`, choose `Enable emoji picker in message input box`
3. `⌘+Shift+4` to take a snapshot, then try `⌘+v` in message input area

#### Expected behavior
Paste images normally.

#### Observed behavior
nothing happens, disabling the emoji picker feature makes this working again.

#### Possible fixes
https://github.com/mattermost/platform/pull/5157 may has some issues with this problem.

**Comment by jasonblais** [comment]
Yeah -- enabling the emoji picker changes the text box to a different one that has some issues: https://mattermost.atlassian.net/browse/PLT-5985

If anyone in the community was interested taking a look, that would be awesome! :)

**Comment by jasonblais** [comment]
Fix included in this PR: https://github.com/mattermost/platform/pull/5904

Thanks again for the report!

**Comment by jostyee** [comment]
@jasonblais I'm sorry but no, #5904 doesn't fix this problem.

**Comment by jasonblais** [comment]
Sorry @jostyee  you're correct -- I had misunderstood the original PR

We'll continue tracking it here, aiming to fix prior to the next release: https://mattermost.atlassian.net/browse/PLT-5985
