### ISSUE TITLE
[Help Wanted] Increase max length of User.Position field to 64 characters to match other fields

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5913]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6102)

Some customers have reported that their LDAP sync fails because the user's position field is not able to be set because it is too long. We should increase the size of the Position field to 64 characters to match other fields (username, nickname, etc)

Reported on GitHub: https://github.com/mattermost/platform/issues/5684

**Comment by S4KH** [comment]
Can somebody where the Position field is located? It is not inside models and stores files.

**Comment by cpanato** [comment]
I can take it

**Comment by cpanato** [comment]
this is the PR https://github.com/mattermost/platform/pull/6044

**Comment by jasonblais** [comment]
Resolved by @gstraube via #6044. Big thanks!
