### ISSUE TITLE
Mattermost Password Error incorrect

### ISSUE THREAD

**Issue by VertigoRay** [mattermost/platform#5929]
#### Summary

[Mattermost registration](https://pre-release.mattermost.com/signup_email) gives me an incorrect password criteria error.

#### Steps to reproduce

Password was generated by LastPass. Here's the 100 character string that was generated:

```
uGJSdZCi32aIhk8aFlvIa6zs!xjiD7W%Tpid%w*IH%1jcLoElOgQI%P%u5oJRK%BaIFUs3Za@VXCo*kcc0Bth0yb$BRn1eCvk2my
```

#### Expected behavior

- **Expect it to not restrict me to a maximum length.**
- Expect it to give me a valid error message with the maximum length expected.

#### Observed behavior

![image](https://cloud.githubusercontent.com/assets/792482/24559014/d316a5c4-1602-11e7-8918-bcd830022ed5.png)

**Comment by VertigoRay** [comment]
FYI, changed to 50 characters and it worked fine.

**Comment by jasonblais** [comment]
We currently have a maximum password length of 64 -- here's a few reasons why password length is restricted: https://www.malwaretech.com/2014/05/the-reason-for-maximum-password-lengths.html

**Comment by jasonblais** [comment]
@VertigoRay ticket here: https://mattermost.atlassian.net/browse/PLT-6159

Would you be interested submitting a fix for it?

**Comment by VertigoRay** [comment]
From what I can tell (from just a quick search) it's a matter of changing this one line:

https://github.com/mattermost/platform/blob/d39947f53933ee4beb4ed8ab614324edc36fba2d/webapp/i18n/en.json#L2313

```json
    "user.settings.security.passwordError": "Your password must contain between {min} and {max} characters.",
```

However, the class doesn't look like it's built to supply `max` to that string. I'm not familiar enough with `.jsx` to make the change.

**Comment by jasonblais** [comment]
Thanks, I've included that line in the ticket.

And no worries if you're not able to fix it - we'll prioritize it next week. Thanks again for the report 👍 

Closing to track in Jira https://mattermost.atlassian.net/browse/PLT-6159
