### ISSUE TITLE
Deactivating user missing feedback

### ISSUE THREAD

**Issue by realrolfje** [mattermost/platform#5934]
#### Summary
When marking a User "inactive" in the System Console -> Teams -> Users menu, the system does not give expected feedback.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
1) Deactivating a user is a destructive action.  But the same menu also enables you to make the user admin. Mis-clicks can have big consequences in this screen. The deactivate button should have a more separated location or at least an "are you sure" dialog. 
2) When the user is deactivated, the channels the user was in should report "user X has left the channel".

#### Observed behavior
Users can be accidentally deleted when trying to upgrade them to admin.
Users are not reported to have left the channel(s) they're in, confusing other channel members.

#### Possible fixes
Move the "deactivate" menu option to a place which is further away from radically different actions, such that mis-clicks are less likely to happen.
Add "are you sure" dialog on the deactivate screen.
Remove the user from all teams/channels before deactivating so that other users are informed that the user has left the channel(s). ("user X has left the channel").

**Comment by jasonblais** [comment]
Thanks for the feedback @realrolfje! I've queud an item for our upcoming UX meeting to discuss https://pre-release.mattermost.com/core/pl/8rq3dim5p3r7byqdb9uy8ps6ce

**Comment by jasonblais** [comment]
Thanks @realrolfje, we discussed and created a ticket to add a confirmation dialog for deactivating someone. This should help prevent accidental deactivation. https://mattermost.atlassian.net/browse/PLT-6258

We're hesitant to add a system message to channels, as it would be a performance hit at large deployments (you might be sending a system message to hundreds of channels)

**Comment by realrolfje** [comment]
If hundreds of teams and channels is the target, the user management interfaces do not scale very well. We have a 200+ user deployment (free version) with 30 channels in which we already need to write scripts to manage things. I hope to contribute more suggestions based on our experience.

**Comment by jasonblais** [comment]
Thanks @realrolfje, appreciate the feedback.

What type of user management are you looking for in your deployment? The new user management interface is the first step, @esethna is working on further designs to improve it. Would love to hear feedback about it

**Comment by realrolfje** [comment]
Not sure if this is the place to report it, if you want me to make separate issues please let me know. I've numbered the list so you can tell me which ones to report separately. 

We are running Mattermost since February this year. My short list of things we need are:

1. Admin approval for new users. There is no middle ground between "open system" and "invite only". We were opening it to interested people, and are now weeding out fake accounts manually. This could be prevented if we had an "approve new user" button for system admin. If you have tips on how you do that for your Demo mattermost I'd like to hear them ;-)
2. End all sessions for a user. Some of our users have between 4 and 14 running sessions because they have multiple tabs open, or are logged in on multiple devices. When they leave a channel on device 1, and reload on device 2, they are back in the channel. In order to prevent these multi-session problems when helping a user, I'd like admins to be able to force logout for a user, so we know he only has 1 session when talking to us.
3. When deactivating a user, he/she is still part of the team(s). We'd like a confirmation window with "are you sure" and a checkbox "also remove from teams"
4. System-wide deactivation of users is done in the "TEAMS" section of the System Admin. This is very confusing.
5. Users which are deactivated and removed from the team are still reported as "active session" (green icon) in my Direct Message list. Sessions aren't removed on deactivation.
6. Related to 5: Some users actually got back on the system with an existig session (was in Mattermost 3.6, haven't seen it in 3.7.2 yet)

Thanks for the fast responses and hard work, we are enjoying Mattermost.

**Comment by jasonblais** [comment]
Thanks @realrolfje! Great feedback

1. Interesting suggestion. Couple of questions:
 - Have you hit issues with fake accounts?
 - If we added the "admin approval" feature, would you be able to tell which users are "real" vs "fake"
2. Would this ticket cover what you're looking for (view and revoke sessions from the admin console): https://mattermost.atlassian.net/browse/PLT-2101
3. We're in the process of adding a confirmation dialog when deactivating a user: https://github.com/mattermost/platform/pull/6119. Deactivation should remove them from all the teams and channels however. Does this not happen for you?
4. Yeah, this has been changed in Mattermost 3.8, which adds a [system-wide user list in the System Console](https://about.mattermost.com/mattermost-3-8/#user-list) where you can manage users more easily, including deactivation.
5. Hm, this sounds like a bug. Their status should change to offline (grey icon). Does this reproduce each time? Do you know if they had an active session on mobile?
6. Definitely a bug if this reproduces. Once deactivated, all the user's sessions should be revoked. Were they able to sign in on desktop or mobile, do you know?

**Comment by realrolfje** [comment]
Hi Jason, no problem, trying to help make things better, thanks for taking the time.

1. Yes, we had to delete a couple of accounts. We are an amateur radio special interest group, and fairly localized. Although I can not check 100%, I can safely assume that `haxor@botnet.ru` is not sharing our interests.
2. Yes, PLT-2101 addresses this issue, although I can not open the screenshots in that issue. We are getting more hints about Android clients/sessions causing problems because the phone reloads pages in the background when unlocking the phone. I have described this problem in a [separate issue](https://github.com/mattermost/platform/issues/6152) to prevent this discussion from derailing.
3. As an admin, it seems that deactivated users are still part of a team. This can also be caused by the UI not always being consistent wether it's displaying team stuff or system stuff. I've registered a [separate issue](https://github.com/mattermost/platform/issues/6154) for this problem.
4. Nice! Happy to hear that.
5. Yes, querying the database for these users shows that they often have a mobile session. We suspect Android sessions to be more prone to this problem, see answer nr. 2 and the issue linked there. We also suspect some users leaving browser tabs open, which is quite common.
6. I can not reach the users I've deactivated (it's partly the reason why I've deactivated them). The direct message I've started with them shows them as "active" (green icon), even after I deactivated them. I've creates a [separate issue for this](https://github.com/mattermost/platform/issues/6155)

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback. 

For 1,  would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](http://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. You get **10** votes in the feature idea forum, and each one influences the future of the project.

For 2, 3, 5 and 6, thanks for creating separate issues for them!

**Comment by realrolfje** [comment]
Contributed to the idea forum as [suggestion 18995998](https://mattermost.uservoice.com/forums/306457-general/suggestions/18995998-create-a-new-user-approval-process).

Another idea would be to consolidate the JIRA, GitHub and Uservoice systems. Having me jump around between 3 different systems and logins does help me find issues which may already have been reported, and makes it a bit harder to report meaningful issues without generating noise for you guys.

**Comment by jasonblais** [comment]
> Another idea would be to consolidate the JIRA, GitHub and Uservoice systems. Having me jump around between 3 different systems and logins does help me find issues which may already have been reported, and makes it a bit harder to report meaningful issues without generating noise for you guys.

Yes, you're not the first person mentioning that..and I agree. We should figure something out, I've created a ticket for myself to think about this https://mattermost.atlassian.net/browse/PLT-6378

**Comment by lindy65** [comment]
Thanks @realrolfje !

Seems everything has been taken care of, either with tickets or ideas being posted to the feature proposal forum.

Is there anything else you're needing resolved at the moment or can I close this issue off?

**Comment by realrolfje** [comment]
Closing is fine, thanks!
