### ISSUE TITLE
about.mattermost.com/default-report-a-problem wants me to know absurd things about my install

### ISSUE THREAD

**Issue by filbo** [mattermost/platform#5955]
#### Summary
"Report a Problem" UI leads to [https://about.mattermost.com/default-report-a-problem/](https://about.mattermost.com/default-report-a-problem/) which wants me to know Team Edition vs. Enterprise Edition E10, Enterprise Edition E20, Enterprise Edition with Premier support, or Core Access.

#### Steps to reproduce
1. Click on "Report a Problem"
2. Boggle

#### Expected behavior
At the very least, if you're going to confront the end user with a list of absurdities that only his IT department would likely know, give him a link to loop back to his own server to **ASK** it which crazy support class he's using.  For users without an IT department, I suppose it would be useful to know which (if any) of that list is the "open access" edition.  "Core Access" sounds sort of promising, until you notice it's under the "Premier support" heading.  So maybe "Team Edition"; but really there is nothing in that phrase to inform the reader.

#### Observed behavior
"Report a Problem" leads to a dead-end brain coredump.

**Comment by jasonblais** [comment]
Thanks @filbo for the report, you raise a good point here.

Redirecting traffic to https://forum.mattermost.org/t/welcome-to-the-mattermost-general-forum/ might be more user-friendly (people are familiar with forums + the text is more approachable for users)

I've queued this for our upcoming meeting to discuss with others.

**Comment by jasonblais** [comment]
Thanks again for the report -- we're tracking the issue in Jira here: https://mattermost.atlassian.net/browse/PLT-5383
