### ISSUE TITLE
"Commands have been disabled" eats my input buffer

### ISSUE THREAD

**Issue by filbo** [mattermost/platform#5957]
#### Summary
"Commands have been disabled" eats my input buffer

#### Steps to reproduce

0. (Outside my ken: )  Contrive for your mattermost server to be configured to reject '/' commands

1. Write a long message to your colleagues about how /usr/foo/bar has wrong contents; start the message with that leading slash, i.e. "/usr/foo/bar has the following problems ... [3-4 paragraphs]"

2. Send

3. Observe "Commands have been disabled by the system admin.   [x]" bar at the top of screen

4. Rage

5. Try to up-arrow or other methods which might retrieve that large input buffer

6. Fail

7. Rage

8. Rage

9. Rage

#### Expected behavior
If you're going to reject an arbitrarily large input buffer for a single forbidden leading character:

1. _EITHER_ on attempted submit, display the rejection message without actually eating the buffer (leave the user in editing-input-buffer state);

2. _OR_ display a dynamic alert **_AS SOON AS THAT CHARACTER IS ENTERED_** (including sneaky cases like going back and inserting a slash in front of an existing buffer; or deleting chars which had been in front of a slash);

3. _OR_ (as a crummy distant third choice) allow the user to retrieve the eaten buffer using some sort of up-arrow or whatever.

4. Whatever the choice, this should be applied to all possible cases where an input buffer might be rejected; in case there are any others besides the leading-'/' case.  Does something similar happen if the server is down, or network I/O, or phase of moon is wrong?  **Fix it**.

#### Observed behavior
Buffer is irretrievably eaten

#### Possible fixes
# _**Ne pas manger le buffer**_

**Comment by jasonblais** [comment]
Thanks @filbo for the report, really sorry about that. I can definitely see this was a frustrating experience for you

We have a help wanted ticket to keep the slash command (and its input) in the typing section if the slash command fails for any reason: https://github.com/mattermost/platform/issues/5224

Wondering if anyone in the community would be interested helping with a fix?

**Comment by lindy65** [comment]
Closing this issue as there is a [help wanted ticket](https://github.com/mattermost/platform/issues/5224) if anyone on the community would like to help with a fix.
