### ISSUE TITLE
Mattermost v3.8.0 - RC5

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5962]
This is a meta issue for v3.8.0 release updates.

You can find key dates for v3.8.0 release below, with links to testing servers, release candidate and changelog added retrospectively.

### April 4 (T-8): Code Complete

Release candidate is cut. After this date, only bugs can be committed to the release branch.

The following information will be updated after release candidate is cut:
- Download link to release candidate
- Testing server
- Changelog

### April 5 (T-7): Release candidate testing begins.

Please link to issues you believe may warrant a patch (please do not post issue here).

It is the responsibility of the release manager assigned to this issue to decide whether or not to merge a patch for the final release, and to list approved patches below.

### April 12 (T-2): Release Build Cut

The final release is cut.

### April 17 (T-0): Release Day

Mattermost v3.8.0 is released.

If an urgent and important issue needs to be addressed between major releases, a bug fix release (e.g. 3.8.1) may be created.

**Comment by esethna** [comment]
### RC1 has been cut

The latest Mattermost release candidate is available here:
`https://releases.mattermost.com/3.8.0-rc1/mattermost-team-3.8.0-rc1-linux-amd64.tar.gz`

You may also test the release candidate on our [testing server](https://rctesting.reddogsofwar.com/login). Please link to issues you believe may warrant a patch (please do not post issue here).

Potential patches to be applied prior to final release will be added to this thread.

### Approved fixes for RC2

**Comment by jasonblais** [comment]
### RC2 has been cut 

The latest Mattermost release candidate is available here:
`https://releases.mattermost.com/3.8.0-rc2/mattermost-team-3.8.0-rc2-linux-amd64.tar.gz`

You may also test the release candidate on our [testing server](https://rctesting.reddogsofwar.com/login). Please link to issues you believe may warrant a patch (please do not post issue here).

Potential patches to be applied prior to final release will be added to this thread.

______

### Approved fixes for RC3
- [Team Admin Can Demote Themselves to Team Member](https://mattermost.atlassian.net/browse/PLT-6253)
- [LDAP login: Full name not editable if first/last name attributes not set in System Console > LDAP](https://mattermost.atlassian.net/browse/PLT-6285)
- [Post textarea does not scroll IOS](https://mattermost.atlassian.net/browse/PLT-6280)
- [Collapsable menus not opening in iOS](https://mattermost.atlassian.net/browse/PLT-6278)
- [Entering MFA code gives 'invalid token' error if MFA is enforced](https://mattermost.atlassian.net/browse/PLT-6275)
- [Unable to remove "Report a Problem" and "Help" links from Mattermost main menu](https://mattermost.atlassian.net/browse/PLT-6260)
- [Office 365 Bad request](https://mattermost.atlassian.net/browse/PLT-6257)
- [Translations PR](https://github.com/mattermost/platform/pull/6031)
- [Adding race detection into the hub into 3.8](https://github.com/mattermost/platform/pull/6028)

**Comment by mmlb** [comment]
@jasonblais Is release day really in August or is that a typo?

**Comment by jasonblais** [comment]
@mmlb Looks like that was a typo - updated to April :) 

Good catch!

**Comment by mmlb** [comment]
:+1:

**Comment by esethna** [comment]
### RC3 has been cut

The latest Mattermost release candidate is available here:
`https://releases.mattermost.com/3.8.0-rc3/mattermost-3.8.0-rc3-linux-amd64.tar.gz`

You may also test the release candidate on our [testing server](https://rctesting.reddogsofwar.com/login). Please link to issues you believe may warrant a patch (please do not post issue here).

Potential patches to be applied prior to final release will be added to this thread.

____

### Approved fixes for RC4

- [Flag missing from the center pane](https://mattermost.atlassian.net/browse/PLT-6300)
- [Regression: Scroll to Bottom arrows on old iOS app don't do anything when clicked](https://mattermost.atlassian.net/browse/PLT-6294)
- [Adding race detection into the hub into 3.8](https://github.com/mattermost/platform/pull/6028)

**Comment by esethna** [comment]
### RC5 has been cut

The latest Mattermost release candidate is available here:
`https://releases.mattermost.com/3.8.0-rc5/mattermost-3.8.0-rc5-linux-amd64.tar.gz`

You may also test the release candidate on our [testing server](https://rctesting.reddogsofwar.com/login). Please link to issues you believe may warrant a patch (please do not post issue here).

Potential patches to be applied prior to final release will be added to this thread.

____

### Approved fixes for RC5

- [Flag missing from the center pane](https://mattermost.atlassian.net/browse/PLT-6300)
- [Regression: Scroll to Bottom arrows on old iOS app don't do anything when clicked](https://mattermost.atlassian.net/browse/PLT-6294)

**Comment by esethna** [comment]
Final has been cut from RC5.

**Note:** v3.8.1 will be cut next week due to an issue with GitLab login and a security fix.
