### ISSUE TITLE
disk space considerations

### ISSUE THREAD

**Issue by joernhees** [mattermost/platform#5975]
Running an internal mattermost server, i'm worried about the ever-growing amounts of disk space it's using.

I'd like to suggest two things:
- admin view of disk space by user (to notify them)
- when a user deletes a file in the chat, it should also be removed from the server's file system (currently doesn't seem to happen)

related #5257

**Comment by it33** [comment]
Feature proposals are very welcome, [over a 100 proposals from the community have been added to Mattermost.](https://mattermost.uservoice.com/forums/306457-general/status/1588363) 

We just need your help to follow [our documented policies](https://about.mattermost.com/help/) and, like hundreds of other users, to share and discuss ideas in the [feature proposal forum](https://www.mattermost.org/feature-ideas/). 

Per our documentation [GitHub issues is for filing bug reports](https://www.mattermost.org/filing-issues/)
