### ISSUE TITLE
[Help Wanted] Setting a password longer than 64 characters gives incorrect error message

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5979]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).a

----

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-6159))

Community report: https://github.com/mattermost/platform/issues/5929

1) Go to https://pre-release.mattermost.com/signup_email
2) Set your username and password
3) Enter "uGJSdZCi32aIhk8aFlvIa6zs!xjiD7W%Tpid%w*IH%1jcLoElOgQI%P%u5oJRK%BaIFUs3Za@VXCo*kcc0Bth0yb$BRn1eCvk2my" as your password

Observed: Error message "Your password must contain at least {min} characters."
Expected: Error message "Your password must contain between {min} and {max} characters."

Notes:
 1. Propose using {min} (for 5), {max} (for 64) to avoid hard-coding UI strings
 2. We should update the error message to be "Your password must contain between {min} and {max} characters." if you enter a password less than 5 characters long.
 3. Looks like it's controlled by this line of code: https://github.com/mattermost/platform/blob/d39947f53933ee4beb4ed8ab614324edc36fba2d/webapp/i18n/en.json#L2313

**Comment by tejasbubane** [comment]
I think this can be closed.

**Comment by lfbrock** [comment]
Yes, thanks @tejasbubane!
