### ISSUE TITLE
[Help Wanted] Pinning in center channel should add badge in right-hand sidebar in search results

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5981]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).a

----

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-6155))

Pinning or un-pinning a post in the center channel should also add or remove the pinned badge in the right-hand sidebar. This works right now for reply threads and for flagged posts, but not for search or @ mentions.

1. Open right-hand sidebar via a search or the @ icon (not via pinned or flagged posts)
2. View a message in center channel that you can see in right-hand sidebar (okay to use Jump; behavior is the same)
3. In the center channel, click [...] > Pin to channel

Observed: The pinned badge appears on message in center channel, but does not appear on message in right-hand sidebar (same is true with un-pinning)

Expected: Pinning and un-pinning in center adds and removes pinned badge in right-hand sidebar.

**Comment by VeraLyu** [comment]
Hi, Can I take this one?

**Comment by jasonblais** [comment]
Sure thing, thanks @VeraLyu!
