### ISSUE TITLE
[Help Wanted] Pinning post in center channel changes list but not title of pinned posts in RHS

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5996]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).a

----

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-6142))

If I view pinned posts in RHS, then change center channel to a different channel and pin a post, the RHS changes the list of pinned posts displayed, but does not update the channel name in the title.

1. While in Channel1, click the pin icon to display pinned posts in RHS
2. Click in LHS to view a different channel (Channel2) (center shows Channel2; RHS continues to display pinned posts from Channel1)
3. Pin a message in center channel (Channel2)

Observed:
Title of RHS does not change, so it still says "Pinned Posts in Channel1", but pinned post list changes to display pinned posts from Channel2.

![image](https://cloud.githubusercontent.com/assets/13119842/24715623/192f950c-19fa-11e7-8cc5-2a6d4a0a7adb.png)

Expected:
List and title both continue to display Channel1

Overall feature ticket: https://mattermost.atlassian.net/browse/PLT-4176
PR: https://github.com/mattermost/platform/pull/4217
Spec: https://docs.google.com/document/d/1U29VQGEFEI7JDaTBjvk5xm59MvJD-JMI4TQv1erjnrU/edit#heading=h.t0sspm76bzpq

**Comment by VeraLyu** [comment]
I would like to take this one, thanks!

**Comment by VeraLyu** [comment]
@jasonblais I'm not authorized to open the spec, just want to clarify:
do we expect even when we switch to Channel 2, RHS still displays Channel 1's pin posts? then how does user want to view pin posts of Channel 2?

**Comment by jasonblais** [comment]
@VeraLyu Thanks!

That is correct - when we switch to Channel 2, the RHS should continue to display Channel 1's pinned posts. This is consistent with all other information we have in the RHS which doesn't change when switching channels. People might also want to view pinned posts for Channel 1 while switching channels.

Sorry about the access, I made the spec public.

**Comment by VeraLyu** [comment]
Add a note for PR testcase:
1. When viewing flagged posts in RHS, switching channel then add a flag to post in center channel will reflect in RHS.
2. When viewing search results in RHS, switching channel will not change search result.
3. When viewing pinned post in RHS, switching channel then pin a post in center channel will not change results in RHS.

**Comment by jasonblais** [comment]
Closed by #6038, thanks @VeraLyu!
