### ISSUE TITLE
[Help Wanted] No back button to pinned posts list after hitting the reply arrow

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5998]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).a

----

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-6209))

1. Click pin icon to open pinned posts list
2. Click reply on a pinned post

Observed: No back button to pinned posts list
Expected: Back button to get back to the list

**Comment by R-Wang97** [comment]
I'll take a look at this!

**Comment by jasonblais** [comment]
Hey @R-Wang97, just checking whether you're still working on this issue?

**Comment by R-Wang97** [comment]
@jasonblais Still am, just haven't figured out a fix just yet.

**Comment by jasonblais** [comment]
No worries, just wanted to touch base :)

Let us know if we can help in any way.

Really appreciate your involvement across the Mattermost project.
