### ISSUE TITLE
Wrong signup redirection on ubuntu 14.04 VPS

### ISSUE THREAD

**Issue by qoyaqa** [mattermost/platform#60]
Hi, I installed  the beta version of Mattermost on a ubuntu 14.04 VPS with public IP. I followed the intallation tutorial for ubuntu in your readme.md, but when I try to signup, I'm redirected to www.xx.xx.xx with Xs being my incomplete public IP. 

This is what the html tag look like with first IP numer missing : 

```<a href="http://www.xxx.xx.xx" class="signup-team-login" data-reactid=".0.1.9.0.2">Sign up now</a>```

Wrong routing ?

**Comment by ciuncan** [comment]
+1

**Comment by it33** [comment]
Sorry for the late reply, cross-posting from other threadL 

If you're running locally as a developer then the system will work with just localhost or dockerhost if mapped in your /etc/hosts file. If you deployed via beanstalk then for now you must have a valid domain that is accessed via www.mydomain.com. Currently you cannot have sub-sub-domains so stuff like www.corp.mydomain.com will not work. It's a known issue we're working on to fix.

**Comment by qoyaqa** [comment]
I supposed it will be fixed in v 1.0. I'll try to write a nice CentOS installation script when it's released. Thanks for doing this, an open source tool like this is definitely missing.

**Comment by it33** [comment]
Thanks @qoyaqa, FAQ added on this at http://discourse.mattermost.org/t/sub-sub-domains-not-yet-supported/13

We'll keep working at it, hope to make you proud :)
