### ISSUE TITLE
Refreshing or relogging will make links to channel turn into text

### ISSUE THREAD

**Issue by prixone** [mattermost/platform#6003]
#### Summary
Linking channel turn into plain-text...

#### Steps to reproduce

1. Enter any channel
2. Send a message linking to any channel, where the channel name will have dash on it using `~channel-name-with-dash`
3. Refresh the browser or relog into mattermost
4. The link is now not click-able and in plain-text

This was observed on https://pre-release.mattermost.com/ not sure what version it currently uses or if its a internal build.

#### Expected behavior

The link remains click-able for people to click and enter that linked channel. Just like it happens with names that do not have space or dash in it.

#### Observed behavior

![2017-04-06_08-01-49](https://cloud.githubusercontent.com/assets/13369829/24751351/a0243cca-1a9f-11e7-9e9c-0011510b7b09.gif)

**Comment by jasonblais** [comment]
Thanks @prixone!

Do you belong to the Public Test Channel? We have an open ticket where channel links don't render properly when you don't belong to them: https://mattermost.atlassian.net/browse/PLT-5458

**Comment by prixone** [comment]
@jasonblais good point I was not a member of it but will check that again.
