### ISSUE TITLE
Refreshing the page after sending / receiving messages causes them to disappear

### ISSUE THREAD

**Issue by AmuletOfNight** [mattermost/platform#6006]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
I'm so sorry, please delete this bug - I forgot to sync our hardware clock on our server so when I rebooted earlier today it caused a 5 hour rollback and Mattermost would flipping out about the timestamps - Correcting and syncing the server time allows messages to stay where they are. You can close this.

#### Steps to reproduce
I'm so sorry, please delete this bug - I forgot to sync our hardware clock on our server so when I rebooted earlier today it caused a 5 hour rollback and Mattermost would flipping out about the timestamps - Correcting and syncing the server time allows messages to stay where they are. You can close this.

#### Expected behavior
I'm so sorry, please delete this bug - I forgot to sync our hardware clock on our server so when I rebooted earlier today it caused a 5 hour rollback and Mattermost would flipping out about the timestamps - Correcting and syncing the server time allows messages to stay where they are. You can close this.

#### Observed behavior
I'm so sorry, please delete this bug - I forgot to sync our hardware clock on our server so when I rebooted earlier today it caused a 5 hour rollback and Mattermost would flipping out about the timestamps - Correcting and syncing the server time allows messages to stay where they are. You can close this.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

I'm so sorry, please delete this bug - I forgot to sync our hardware clock on our server so when I rebooted earlier today it caused a 5 hour rollback and Mattermost would flipping out about the timestamps - Correcting and syncing the server time allows messages to stay where they are. You can close this.

**Comment by AmuletOfNight** [comment]
I'm so sorry, please delete this bug - I forgot to sync our hardware clock on our server so when I rebooted earlier today it caused a 5 hour rollback and Mattermost would flipping out about the timestamps - Correcting and syncing the server time allows messages to stay where they are. You can close this.

**Comment by jasonblais** [comment]
Thanks @AmuletOfNight! Glad you figured out what the issue is

**Comment by thomasf** [comment]
I connected to mattermost instance with my computers clock set a couple of hours back (because windows/linux utc) and it might have "deleted" most messages from that day in a channel.. I'm not sure though.
