### ISSUE TITLE
Notifications are not generated for user names in message attachments

### ISSUE THREAD

**Issue by mkbaldwin** [mattermost/platform#6029]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Notifications are not being generated for user names in message attachments (n my case specifically in fields) that are generated via a webhook.

I am not sure if this behavior was not implemented intentionally, or if it it really a bug. To me it feels like a bug and not a new feature request.

#### Steps to reproduce
Create a new message containing attachments/fields via a web hook. Include the name of the user in the attachment field. The name will not be recognized and tagged.

#### Expected behavior
Mattermost would recognize a user's name, as defined in their notification preferences, when mentioned in a message that has an attachment/fields. Notifications would be generated for the user the same as if they are mentioned in a regular message.

#### Observed behavior
Messages with attachments are created via the web hook, but notifications are not generated for users when their names are mentioned in an attachment field.

#### Possible fixes
N/A

**Comment by jasonblais** [comment]
Thanks @mkbaldwin for the report!

Would you be able to share an example payload so we can replicate it?

**Comment by mkbaldwin** [comment]
I don't have a good way to get an actual example from our environment due to policies of my employer. However, based on the API I believe the following contrived example should trigger the issue. Also note that we have our users' notification settings set to generate notifications for their first and last names. Which is the piece not working. I have not tried using `@username` to trigger them as the messages are generated by a plugin to another application and it does not have the mattermost usernames.

```javascript
 {
  "attachments": [
    {
      "title": "Example Attachment",
      "fields": [
        {
          "short": true,
          "title":"Assignee",
          "value":"FirstName LastName"
        }
      ]
    }
  ]
}
```

Let me know if there is anything else I can do to help!

**Comment by jasonblais** [comment]
Hey @mkbaldwin, really appreciate the input, 

I was able to reproduce it. Message attachments indeed don't support mentions and [don't appear in search results](https://docs.mattermost.com/developer/message-attachments.html#known-issues) yet.

Wondering if this would be something you'd be interested contributing? Would love to work with you to add it.

**Comment by mkbaldwin** [comment]
@jasonblais, no problem. I wouldn't mind taking a look at it, but I might not have time to get to it right away. 

I will have to take a look what all I need to setup a dev environment for the app. I've never worked with Go before, so that could be interesting.

**Comment by jasonblais** [comment]
Thanks again @mkbaldwin, 

I chatted with some engineers on our end and this change would be a little more involved than I originally anticipated. Searching for mentions from within message attachments might pose a performance concern in large deployments where they are commonly used.

As a result, I've created a feature proposal to discuss it with the community at large first: https://mattermost.uservoice.com/forums/306457-general/suggestions/19061098-allow-message-attachments-to-generate-mentions

Let me know if there are any further questions,
