### ISSUE TITLE
Feature request: Paste images

### ISSUE THREAD

**Issue by larsemil** [mattermost/platform#603]
Would love the ability to paste copied image directly from buffer to upload like in slack.

**Comment by it33** [comment]
Hi @larsemil, 

You're in luck! 

Pasting images directly into Mattermost is now supported in the latest release of Mattermost (v0.7.0) along with drag and drop: https://github.com/mattermost/platform/tree/v0.7.0

Please let us know if you have any issues,

**Comment by vance** [comment]
aaaaand they show as an attachment. that's ridiculous.

**Comment by mariusk** [comment]
So did this stop working with later versions, a regression perhaps?
