### ISSUE TITLE
Flash crashing / Move away from flash

### ISSUE THREAD

**Issue by larsemil** [mattermost/platform#604]
Using Firefox 42.0(developer edition) flash plugin crashes each time upon using mattermost. Same on all views. 

For what is flash used, and is it possible to move away from flash?

**Comment by it33** [comment]
Hi @larsemil, we're not aware of any use of Flash in Mattermost. Are you finding the Flash plugin crashing on sites other than Mattermost?

**Comment by larsemil** [comment]
Only on mattermost.

**Comment by DimShadoWWW** [comment]
Mattermost uses flash from  ZeroClipboard.swf to access the clipboard
it's in web/static/flash
