### ISSUE TITLE
Joining a team using invite link does not update open sessions

### ISSUE THREAD

**Issue by jnugh** [mattermost/platform#6043]
#### Summary
When clicking on a team invite link while having another session on the same server the team is not added to the open sessions.

#### Steps to reproduce
Tested on 3.7.3, master:
1. Create two accounts
2. Create a new team with account 1
3. Paste invite Link to Some channel in default team
4. Switch to account 2
5. Click on the invite link
6. A new Tab will open showing the new team in the sidebar, the old tab does not show the new team

+ When you add the user to a new channel in the new team while keeping the old session open, the add user to team event will trigger a JS error because the reducers rely on the team being there.

#### Expected behavior
Team sidebar should be updated in all open sessions.

#### Observed behavior
It does not update :(

#### Possible fixes
I tried to add
```go
message := model.NewWebSocketEvent(model.WEBSOCKET_EVENT_ADDED_TO_TEAM, "", "", user.Id, nil)
message.Add("team_id", team.Id)
message.Add("user_id", user.Id)
Publish(message)
```
to `joinUserToTeam` which triggers the event, and worked multiple times. But this triggers a 
```
method=getTeam msg=You do not have the appropriate permissions detail= rid=***
```
sometimes.

**Comment by lindy65** [comment]
Hi @jnugh,

Apologies for the late response!

I've reproduced your issue in v3,8 and have created a [ticket](https://mattermost.atlassian.net/browse/PLT-6380) to track the fix.

I didn't get a JS error as you commented about here:
> When you add the user to a new channel in the new team while keeping the old session open, the add user to team event will trigger a JS error because the reducers rely on the team being there.

**Comment by lindy65** [comment]
Hi @jnugh 

Thanks again for the report! I'll close this issue off for now as we have created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6380) to track it. If you're interested helping with a pull request, please let us know.
