### ISSUE TITLE
Gitlab integration - SSO not working

### ISSUE THREAD

**Issue by larsemil** [mattermost/platform#606]
We are using the mattermost package shipping with Gitlab. 

And we cannot use our gitlab accounts. we get the error:

## GitLab Mattermost needs your help:

We couldn't find the existing account

-----------
no errors in log

**Comment by it33** [comment]
Hi @larsemil, appreciate the issue report, this issue is fixed in the next release of GitLab, which should be out around Sept 22: https://gitlab.com/gitlab-org/omnibus-gitlab/issues/758

**Comment by larsemil** [comment]
I love this! You are awesome! :) No more issues for now. :dancers:
