### ISSUE TITLE
[Help Wanted] [PLT-6288] Don't force file downloads in APIv4

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6061]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6288)

Needs a bit of investigation into the correct solution, but ideally should be able to get a link to a Mattermost file and view it in the web browser instead of having it download automatically.

This might involve removing some headers from the response on the GET /files/{file_id} endpoint and for the public file endpoint as well.

This should only change for the v4 endpoints inside the api4 package.

If you have questions or need help, ask in the APIv4 channel on the community Mattermost instance: https://pre-release.mattermost.com/core/channels/apiv4

**Comment by cpanato** [comment]
I can take a look into

**Comment by cpanato** [comment]
should we send a parameter to say we want to download or just visualize ?
