### ISSUE TITLE
Message not translated

### ISSUE THREAD

**Issue by kaakaa** [mattermost/platform#6068]
#### Summary
Tested in 3.8.0-rc3.
Some messages aren't translated.

![issue](https://cloud.githubusercontent.com/assets/1453749/24899634/f643fcd6-1edb-11e7-9914-914d337dd70f.png)

#### Steps to reproduce
1. Choose "日本語" as language setting in account settings.
2. Open `channel menu` > `通知の設定 ("Notification Preferences" in English)`

#### Expected behavior
`Send mobile push notifications` is translated in Japanese.

#### Observed behavior
That message isn't translated, is displayed in English.

#### Possible fixes

I had fixed message id in [this PR](https://github.com/mattermost/platform/pull/5902/files#diff-48187f065420cda8aa0582d6c6cc4b2cR1140), but it seemed be back to incorrect id again by [this PR](https://github.com/mattermost/platform/pull/5964/files#diff-48187f065420cda8aa0582d6c6cc4b2cR1137).

[Change to `webapp/i18n/en.json`](https://github.com/mattermost/platform/pull/5902/files#diff-48187f065420cda8aa0582d6c6cc4b2cR1140) seems be reverted, so it should be applyed again.

**Comment by jasonblais** [comment]
Ah --- can you help re-submit the PR? Sorry, I think there might have been an issue where the ID change wasn't merged before the new translations PR was submitted, which then overwrote the change

**Comment by kaakaa** [comment]
Sure!
I'll send the PR soon.

**Comment by jasonblais** [comment]
Closed by #6069, thanks @kaakaa :)
