### ISSUE TITLE
[Help Wanted] [PLT-3711] Add websocket event for creating a custom emoji

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6071]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3711)

When one user creates a custom emoji, other users don't see it until they refresh the page. We can use websockets to get the new emoji without the user needing to refresh. 

This new websocket event will need to contain the emoji json (but not the image) as part of the payload so that the client doesn't immediately contact the server for any information

**Comment by VeraLyu** [comment]
I like this one, pls assign it to me.

**Comment by jasonblais** [comment]
Sure thing, thanks @VeraLyu  :)

**Comment by jasonblais** [comment]
Added in Mattermost 4.0, thanks @VeraLyu!
