### ISSUE TITLE
[Help Wanted] [PLT-6258] Add a confirmation dialog to confirm deactivation, since it's a desctructive action

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6072]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6258)

Add a confirmation dialog to confirm deactivation, since it's a desctructive action

Title: Deactivate [username]
Text: This action deactivates [username]. They will be logged out and not have access to any teams or channels on this system. Are you sure you want to deactivate [username]?
Buttons: Cancel / Deactivate

**Comment by R-Wang97** [comment]
I can take a look at this!
