### ISSUE TITLE
[Help Wanted] [PLT-6096] In desktop web app, remove unnecessary steps for copying permalink

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6073]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6096)

1) Click [...] next to a message
2) Choose "Permalink"

Observed: A separate dialog appears where you can click the "Copy Link" button to copy the permalink.

Proposed change:

 1) Change "Permalink" menu option in [...] to "Copy Link"

 2) Once you click "Copy Link", the permalink is copied to the clipboard. The [...] remains open but the "Copy Link" term changes to "(/) Copied"

![image](https://cloud.githubusercontent.com/assets/13119842/24919761/b5913aec-1eb2-11e7-8a03-299d4f35ee18.png)

NOTE: If the browser doesn't allow you to directly copy to the clipboard (e.g. mobile browser), then show the "Copy Link" popup as before

![image](https://cloud.githubusercontent.com/assets/13119842/24919770/b97bd6a8-1eb2-11e7-9fb9-c21ec2682ca3.png)

**Comment by kulak-at** [comment]
I can take this one.

**Comment by jasonblais** [comment]
Fantastic! Thank you @kulak-at! 

Don't hesitate to let us know if you have any questions

**Comment by kulak-at** [comment]
I've found very similliar code to display [...] menu and handle clicked actions in post_info.jsx but also in rhs_comment.jsx and rhs_root_post.jsx (for the sidebar menus). This code is very simple and I believe it could be unified. How would you like to handle that, unify these dropdowns, copy-paste solution to different modules (and adjust the solution as they have slightly different behavior) or implement the solution just for the post_info.jsx component?

**Comment by jasonblais** [comment]
Thanks @kulak-at! I've posted your question to engineers in our public [Developers channel](https://pre-release.mattermost.com/core/pl/rg7r6w41e3rjde41z3j79xgm6h).

**Comment by hmhealey** [comment]
@kulak-at I've wanted to unify that code for some time now, but I don't think we need to do all that at once. What you might be able to do is make a `CopyPermalinkMenuItem` component that implements all necessary behaviour (showing the "Permalink" button, trying to copy the text, opening the dialogue if that doesn't work) and then just use the same component in all 3 places. That'll cut down on the duplicate code, but won't require changing everything else

**Comment by kulak-at** [comment]
@hmhealey Great idea, will do that!

**Comment by jasonblais** [comment]
Closing to review the design. We'll reopen afterwards
