### ISSUE TITLE
[Help Wanted] [PLT-6269] Enter to submit does not work on Leave Team modal

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6074]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6269)

Repro: 
1. Go to Main Menu 
2. Select "Leave Team"
3. Press Enter

Expected: Enter should submit the modal as yes
Observed: Enter does not work

**Comment by R-Wang97** [comment]
I can a look at this.
