### ISSUE TITLE
[Help Wanted] [PLT-2181] Change wording for deactivating a user from "Make Inactive" to "Deactivate"

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6075]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-2181)

From: https://github.com/mattermost/platform/issues/2288

Currently we use "inactive" to describe deactivating a user. This is a little confusing because it could refer to users who have not logged in recently, and thus are inactive on the site but do not have a deactivated account. 

To make this clearer, update the wording in the "Manage Members" dialog and in the System Console to say "Deactivate" instead of "Make Inactive".  Update the error message when a deactivated user tries to log in to say "Your account has been deactivated" instead of "Your account has been made inactive".

**Comment by cpanato** [comment]
I can take this one

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6106

**Comment by jasonblais** [comment]
Thanks!
