### ISSUE TITLE
[Help Wanted] [PLT-2780] Re-add login redirect

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6076]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-2780)

Prior to 3.0, if you went to a URL such as example.mm/team/channels/public-channel when you weren't logged in, you would be sent to the login screen, but once you logged in, you would be directed back to example.mm/team/channels/public-channel. We want to re-add this feature.

When this gets re-added, make sure to test to make sure that you can only be redirected to a web page and not a javascript link. Previously, the login link would be something like example.mm/login?redirect=LINK which would allow a link such as example.mm/login?redirect=javascript:alert('hax') to run arbitrary javascript

**Comment by lfbrock** [comment]
@dmeza is working on this

**Comment by lfbrock** [comment]
This is fixed
