### ISSUE TITLE
[Help Wanted] No feedback when promoting a channel member to a channel admin

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#6081]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6284)

1) Sign in as a System Admin
2) Go to a public channel, click the name and choose "Manage members"
3) Promote a "channel member" to a "channel admin"

Observed: Dropdown menu closes. Member is promoted but UI still shows him as a "channel member" until refresh
Expected: Dropdown menu closes, role updates to "channel admin" without requiring a refresh

**Comment by cpanato** [comment]
@jasonblais I just tested in the current master and this behavior does not exist.

Attached you can check
![znbjmbfb1b](https://cloud.githubusercontent.com/assets/4115580/25012095/c1568652-206f-11e7-96d1-036214eea298.gif)

**Comment by jasonblais** [comment]
Hm, you're correct. This does seem to work afterall.

Thanks @cpanato, I'll resolve this issue
