### ISSUE TITLE
[Help Wanted] Confirm before sending (at)all, (at)channel message

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#6082]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6246)

Opening ticket based on volunteer contributor. https://mattermost.uservoice.com/forums/306457-general/suggestions/18607111-confirm-with-ping-warning-before-sending-all-eve

Propose when sending a message containing (at) all or (at) channel create a pop-up dialog with confirmation: 

TITLE: 
```
Confirm sending notifications to entire channel 
```
TEXT: 
```
By using @all or @channel you are about to send notifications to XXX people. Are you sure you want to do this?
```

BUTTONS

Cancel // Confirm

NOTE

You may use the same pop-up dialog, which appears when attempting to delete a message

![image](https://cloud.githubusercontent.com/assets/13119842/24932245/a39e32be-1ede-11e7-8da5-903b1eee858c.png)

**Comment by cpanato** [comment]
let me see if I can handle this one. since I'm still learning react

**Comment by jasonblais** [comment]
you're awesome.. :)

Let us know if you have any questions!

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6250

**Comment by tiagodj** [comment]
how do I disable this? this is very annoying. my team is small (8 people) and we are very careful on using @all, so this warning message does more harm than good.

**Comment by jasonblais** [comment]
Thanks for the feedback! Queued for UX meeting to discuss: https://pre-release.mattermost.com/core/pl/zqchr7zuj7gpp85fy4ms3xseno

**Comment by jsha** [comment]
Hi! I have a similar issue on my instance; one channel is very small, and they use @channel a lot, and don't want to get a pop-up. However, the "everyone" channel is very big, and using @channel there is more disruptive.

Here's a proposed refinement: Rather than an instance-wide enable/disable, there could be an instance-wide "always / first time each day / once / never" option.

**Comment by jasonblais** [comment]
@tiagodj There is now a [config.json setting](https://docs.mattermost.com/administration/config-settings.html#show-channel-and-all-confirmation-dialog) to disable the at-all and at-channel confirmation dialog.

@jsha How would the proposed refinement cover the case for the large channel?

**Comment by jsha** [comment]
The goal is: For the majority of novice users in the large channel, provide a warning, while also allowing the users of the small channel, who are more experienced, to use @-channel without constant warnings. We would choose either the "first time each day" or the "once" option to achieve that.

**Comment by jasonblais** [comment]
Thanks, really appreciate your feedback @jsha.

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](http://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jsha** [comment]
@jasonblais Thanks! Posted at https://mattermost.uservoice.com/forums/306457-general/suggestions/32656438-improve-channel-notification-warning.
