### ISSUE TITLE
[Help Wanted] Add unit tests to APIv4 for creating users with hashes and invite ids

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#6083]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6286)

In api4/user_test.go need to add tests for creating users with hashes and with invite ids. See the api/user_test.go for examples of how it was done in v3.

Might need to add more `model/client4.go` functions as well.

If you have questions or need help, ask in the APIv4 channel on the community Mattermost instance: https://pre-release.mattermost.com/core/channels/apiv4

**Comment by cpanato** [comment]
i will take this one

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6363
