### ISSUE TITLE
My login does not work but exists

### ISSUE THREAD

**Issue by anniemichelia** [mattermost/platform#6085]
For feature requests, please see: http://www.mattermost.org/feature-requests/.
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format:

#### Summary
Issue in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem
[mattermost-issues.docx](https://github.com/mattermost/platform/files/937636/mattermost-issues.docx)

Attached doc has the screen shots.

**Comment by anniemichelia** [comment]
I am able to login but no screens appears except blank.

**Comment by lindy65** [comment]
Hi @anniemichelia,

Thanks for your note,

Can you share a little more about the issue so we can help?  For instance -
1. What version of Mattermost did you install?
2. Do you see any error messages or console log errors?
3. Could you send us a screenshot of what the screen looks like once you have logged in?

Thanks!

**Comment by anniemichelia** [comment]
Hi Lindy


1.       I upgraded to 3.7.3 Team Edition this past weekend.


2.       Errors



[cid:image003.png@01D2B376.E88EA120]

3.       It is spinning on Signing In….




[cid:image004.jpg@01D2B376.E88EA120]


But when I try another user it logins perfectly.

[cid:image005.jpg@01D2B376.E88EA120]

Annie Michelia | DBA, Technology Solutions and Services | Broadridge Financial Solutions, Inc.
2 Journal Square Plaza | Jersey City, NJ 07306 | USA | p +1 201-714-3522
broadridge.com<http://www.broadridge.com/>

**Comment by lindy65** [comment]
Hi @anniemichelia,

Thanks for your message...

Would you be able to attach the images again please?  They didn't come through with your message so I'm unable to see the errors you are getting...

Also, are you using the browser version, the Desktop app or mobile browser?

**Comment by anniemichelia** [comment]
Please find attached.

Annie Michelia | DBA, Technology Solutions and Services | Broadridge Financial Solutions, Inc.
2 Journal Square Plaza | Jersey City, NJ 07306 | USA | p +1 201-714-3522
broadridge.com<http://www.broadridge.com/>

**Comment by lindy65** [comment]
Hi @anniemichelia,

I'm so sorry but no images were attached.

Perhaps you'd like to join our pre-release server where you can connect
directly with me via direct message and we can try to resolve the issue?

You can sign up here:
https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676


Once you have signed up, you can join the [Peer-to-peer Help channel](
https://pre-release.mattermost.com/core/channels/peer-to-peer-help) and at
mention me or feel free to direct message me too.

**Comment by lindy65** [comment]
Hi @anniemichelia 

Just circling back to check whether you've managed to resolve your login issue?

**Comment by anniemichelia** [comment]
Hi Lindy – I did not receive any resolution steps after this email. Can you please look into this? I am still unable to login.

Annie Michelia | DBA, Technology Solutions and Services | Broadridge Financial Solutions, Inc.
2 Journal Square Plaza | Jersey City, NJ 07306 | USA | p +1 201-714-3522
broadridge.com<http://www.broadridge.com/>

From: Michelia, Annie x23522
Sent: Wednesday, April 12, 2017 1:26 PM
To: 'mattermost/platform' <reply@reply.github.com>; mattermost/platform <platform@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [mattermost/platform] My login does not work but exists (#6085)

Please find attached.

Annie Michelia | DBA, Technology Solutions and Services | Broadridge Financial Solutions, Inc.
2 Journal Square Plaza | Jersey City, NJ 07306 | USA | p +1 201-714-3522
broadridge.com<http://www.broadridge.com/>

**Comment by lindy65** [comment]
Hi @anniemichelia,

I'm sorry to hear that your issue is still not resolved.

Could we ask your help to attach the images to the GitHub issue that you opened (https://github.com/mattermost/platform/issues/6085) rather than attaching them to an email where they don't seem to be coming through?

Thanks!

**Comment by anniemichelia** [comment]
[mattermost-issues.docx](https://github.com/mattermost/platform/files/937645/mattermost-issues.docx)

**Comment by anniemichelia** [comment]
Attached the document which has the screen shots

**Comment by anniemichelia** [comment]
I attached as a word document with the screen shots to the GitHub. Thanks.

Annie Michelia | DBA, Technology Solutions and Services | Broadridge Financial Solutions, Inc.
2 Journal Square Plaza | Jersey City, NJ 07306 | USA | p +1 201-714-3522
broadridge.com<http://www.broadridge.com/>

**Comment by lindy65** [comment]
Thanks @anniemichelia,

From the screenshots you have sent, it seems you might be logged in to your other account (the one that shows online when you log in as the other sys admin account) via another browser or perhaps on a mobile device?

I'm not totally sure so I'm going to pass the log file screenshot on to our devs to interpret and will get back to you soon.

Please respond here, [in the GitHub issue](https://github.com/mattermost/platform/issues/6085) because when you reply via email it is attaching your email signature which shows all your personal information ;)

Thanks!

**Comment by anniemichelia** [comment]
I deleted the user and recreated.

**Comment by lindy65** [comment]
Thanks for the feedback @anniemichelia :)
