### ISSUE TITLE
Default websocket address set to be localhost making ws unaccessible

### ISSUE THREAD

**Issue by VeraLyu** [mattermost/platform#6097]
For feature requests, please see: http://www.mattermost.org/feature-requests/.
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format:

#### Summary
When I run a mattermost server from another machine in my LAN, and access it through
ip (hostname not configured in mattermost), websocket connection is unreachable because address is hard-coded to localhost. Instead of being hard-coded to localhost, it makes more sense to use same ip with http connection in default use case. This improves out of box experience.

#### Steps to reproduce
1. "make run" mattermost server on another machine in your LAN
2. access it through IP address

#### Expected behavior
ws connection should work out of box

#### Observed behavior
ws connection unavailable
![default](https://cloud.githubusercontent.com/assets/12692639/24988094/3dd2d486-2036-11e7-8db1-42742634555f.PNG)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by hmhealey** [comment]
Hi @VeraLyu,

Are you seeing this on a pre-compiled version of Mattermost or are you running it from source using the Makefile?

**Comment by hmhealey** [comment]
Oh sorry, I see your note now that this is using the Makefile. I'm not sure what the best fix for this would be since we need that to be manually set now to fix a security issue.

We could consider returning it to the old behaviour when you're running it from the Makefile since you're unlikely to try to hack yourself, or we might be able to just switch the websocket to use `window.location.origin` instead of the SiteURL since I'm not sure of any use cases where it wouldn't be accessed through the same address the user is viewing Mattermost from.

I'll ask in the Developers channel on https://pre-release.mattermost.com to see if anyone else has any thoughts

**Comment by jasonblais** [comment]
Hey @VeraLyu, just letting you know that this has been queued for Wednesday's developer meeting to discuss: https://pre-release.mattermost.com/core/pl/3dgcnxtpgffhuj586o7cp5p4dr

![image](https://cloud.githubusercontent.com/assets/13119842/25092028/eee65c68-2359-11e7-8407-c554ba451e96.png)

**Comment by ruzette** [comment]
@hmhealey -- I can confirm this happens on a pre-compiled version as well. Visible since 3.5.1. :)

**Comment by hmhealey** [comment]
@VeraLyu I've filed a ticket to go change the websocket back to using `global.location.origin` like it used to before the SiteURL setting was added. I'll try to get to it in the next few days, but feel free to take it if you want it sooner.

https://mattermost.atlassian.net/browse/PLT-6368

**Comment by hmhealey** [comment]
FYI, we're also having reports of this affecting people in production environments, so we're going to move this up and do it as a hotfix release for 3.8

**Comment by lindy65** [comment]
Hi @VeraLyu, 

This has been fixed with [this ticket](https://mattermost.atlassian.net/browse/PLT-6368) so I'm closing this issue off for now.  Thanks again for your report!
