### ISSUE TITLE
Domain should not have '.' restrictions

### ISSUE THREAD

**Issue by poelzi** [mattermost/platform#61]
There seems to be very hard restrictions how many '.' are allowed in the domain which will always cause problems.

for testing I setup a instance:
dev.example.com, with www.dev.example.com and some other aliases.

when creating the team, the url is configured as
[INPUT] .dev.example

Also the redirect is then to the cut domain. Some TLD only allow second level domains. example.co.uk, also causing problem when running the service as a subdomain.

**Comment by it33** [comment]
If you're running locally as a developer then the system will work with just localhost or dockerhost if mapped in your /etc/hosts file.  If you deployed via beanstalk then for now you must have a valid domain that is accessed via www.mydomain.com.  Currently you cannot have sub-sub-domains so stuff like www.corp.mydomain.com will not work.  It's a know issue we're working on to fix.

**Comment by acaranta** [comment]
I agree ... to first test this amazing product, and/or to use it internally it won't be used on a "root" domain but instead on a sub/sub domain, with a wildcard .... therefore the DNS restrictions are not really compatible currently ;)

I would prefer if mattermost could only use the first left part as the "wildcard" DNS part ;)

**Comment by wedtm** [comment]
It appears that TLD's longer than 3 characters are also invalid. I tried `example.ninja` and when going to the main URL, and trying to create a team, it redirects me to `www.ninja`

**Comment by coreyhulen** [comment]
Our plan is to make it work with any number of sub-sub-domains.  This is a known limitation that we plan to address soon.  Currently, you must have a domain that looks like sub.domain.tld or *.example.com.  The system also has a special case when it sees the host as localhost or dockerhost it will work in a developer/tester mode.

@wedtm there shouldn't be any limitation of only allowing 3 characters on the tld.  You should access the site at www.example.ninja then once you create a team you can access the team directly at myteamname.example.ninja.

**Comment by devopsbrett** [comment]
I've just submitted a pull request with the changes I needed to make in order to support sub-sub domains. Even if not merged, it may still serve as a template to make your own modifications to get working sub-sub-domains

**Comment by faebser** [comment]
+1
Also please make the all the domain related stuff configurable and work with sane defaults ( ex: no subdomains for teams).

**Comment by crspeller** [comment]
#200 Will fix this.
