### ISSUE TITLE
[Help Wanted] CTRL+K: Enable channel selection with hitting ENTER or TAB only once

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#6111]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5235)

Currently the channel switcher (CTRL+K) requires hitting ENTER twice before switching to a channel.

**Comment by crspeller** [comment]
https://github.com/mattermost/platform/pull/6208
