### ISSUE TITLE
API v3: logout does not work

### ISSUE THREAD

**Issue by realrolfje** [mattermost/platform#6112]
#### Summary
Calling `https://your-mattermost-url.com/api/v3/users/logout` as per the [api documentation](https://api.mattermost.com/) always returns a 404 in Mattermost 3.7.2.

#### Steps to reproduce
```
curl -i -d '{"login_id":"testuser","password":"***"}' https://mattermost.***/api/v3/users/login
```

Returns HTTP/1.1 200 OK with a MMAUTHTOKEN. Using this token to access the API works:

```
curl -i -H 'Authorization: Bearer mi8dc9wg*******wahin3a1m4y' https://mattermost.***/api/v3/users/me
```

Returns HTTP/1.1 200 OK with the JSON user object.

```
curl -i -H 'Authorization: Bearer mi8dc9wg*******wahin3a1m4y' https://mattermost.***/api/v3/users/logout
```
Always returns this error:

```
HTTP/1.1 404 Not Found
Server: nginx/1.6.2
Date: Thu, 13 Apr 2017 19:11:17 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 256
Connection: keep-alive

{"id":"api.context.404.app_error","message":"Sorry, we could not find the 
page.","detailed_error":"There doesn't appear to be an api call for the url='/api/v3/users/logout'. 
Typo? are you missing a team_id or user_id as part of the url?","status_code":404}%                                                                                                                                                     
```

#### Expected behavior
Users can logout and session is invalidated as described in the API.

#### Observed behavior
Calling `/api/v3/users/logout` with a valid token always retuns a 404.

#### Possible fixes
There may be a typo in the documentation and/or the mattermost client code, because logging out from the mattermost clients (browser, desktop app, phone apps).

**Comment by cpanato** [comment]
hello @realrolfje the issue here is that you are calling the wrong verb for logout. Instead of GET you should use POST

```
curl --request POST \
  --url http://localhost:8065/api/v3/users/logout \
  --header 'authorization: Bearer heuohejjxoxoxooxoxsgpge' \
  --header 'content-type: application/json' \
  --data '{}'
```

**Comment by realrolfje** [comment]
Thank you @cpanato, that works for logging out, and in the database I even see that the sessions are gone. However, in the client the user still seems to be reported as "active".

Reproduction:
1. Log in with user A
2. Log in with user B
3. B starts a Direct Message to A and keeps the screen open.
4. Use the tokens in the session table and curl to force logout user A.
5. All sessions for A are now gone from the database (as expected)
6. The screen for user B still shows A as active. Reloading the screen with Cmd-R in the Mattermost App for user B still shows A as active (green icon).

So although on the server it looks like the sessions are indeed gone, the clients still see eachother as Active (green icon).

**Comment by cpanato** [comment]
I will take a look in the code and follow your steps to reproduce. 

In meanwhile i guess @jasonblais can confirm if this is expected or not

Thanks

**Comment by jasonblais** [comment]
@realrolfje @cpanato We have an open ticket for a similar report here, where the status gets stuck online for a long time after quitting the desktop app or closing the entire browser window. 

https://mattermost.atlassian.net/browse/PLT-6333

So this might be a related issue.

**Comment by realrolfje** [comment]
That issue could be related indeed, if Admin A deactivates User B, then User B can not log in to hit the logout API call, keeping User B's session stuck.

**Comment by lindy65** [comment]
Hi everyone, I'm going to close this issue off for now as there is a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6333) tracking the issue scheduled for v3.10.
