### ISSUE TITLE
`Group direct message` text is empty on quick channel switcher

### ISSUE THREAD

**Issue by dmeza** [mattermost/platform#6115]
#### Summary
Bug: `Group direct message` text is empty on quick channel switcher. On 3.8 and 3.7

#### Steps to reproduce
1) create a group direct message
2) do quick channel switcher it appears fine
3) remove the group direct message
4) refresh the page
5) do quick channel switcher, it appears empty.

#### Expected behavior
Display the name of the group channel

**Comment by lindy65** [comment]
Thanks @dmeza, I've created a [Jira ticket](Thanks @dmeza, I've created a Jira ticket for the issue) for the issue

**Comment by lindy65** [comment]
@dmeza, closing this issue here as there is a Jira ticket to track and fix for v3.9
