### ISSUE TITLE
[Help Wanted] [PLT-5059] Add unit tests for markdown rendering

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6124]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5059)

We could use automated unit tests for various parts of the markdown parsing and text formatting library including images. There's some examples of how these tests would look in [webapp/tests/utils/formatting_*.test.jsx](https://github.com/mattermost/platform/tree/master/webapp/tests/utils).

**Comment by justinwyer** [comment]
I'm interested in taking this on

**Comment by jasonblais** [comment]
Awesome! Thanks @justinwyer 👍

**Comment by lfbrock** [comment]
We have markdown unit tests in the markdown library, so closing this one
