### ISSUE TITLE
[Help Wanted] [PLT-4118] Help text on "Private Channel --> Set Channel Purpose" is incorrect

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6128]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4118)

Help text on "Private Channel --> Edit Channel Purpose" is incorrect

Repro:
1. In the LHS, click on the name of the private channel
2. Click on the “v” to the right of the channel name at the top of the center panel
3. Click on “Edit Channel Purpose”

Observed:
Help text reads: "Describe how this channel should be used. This text appears in the channel list in the "More..." menu and helps others decide whether to join."

Expected:
Help text reads: "Describe how this channel should be used. This text appears in the "View Info" modal of the private channel."

**Comment by cpanato** [comment]
I can take this.
Make a comment in Jira.

**Comment by jasonblais** [comment]
@cpanato  The change is needed only for private channels: for public channels the help text "This text appears in the channel list in the "More..." menu and helps others decide whether to join." is correct, as the purpose does appear in the "More..." menu.

However, private channels don't have the "More..." menu at the moment.

**Comment by jasonblais** [comment]
And thanks for your interest on the issue!

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6144

**Comment by jasonblais** [comment]
Resolved by #6144!
