### ISSUE TITLE
[Help Wanted] [PLT-6326] JavaScript error after creating a team when user doesn't belong to any other teams

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6146]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6326)

1) Enable team creation from System Console > Users and Teams
2) Leave all teams
 -- user redirected to team selection page
3) Click "Create New Team"
4) Complete the team creation flow until team creation is successful

Observed: JavaScript errors after team creation (see attached)

![image](https://cloud.githubusercontent.com/assets/13119842/25152147/1a6a8c5e-2456-11e7-89d0-cefd1cd56611.png)

Expected: No errors

Note: Doesn't reproduce if you already belonged to at  least one team

**Comment by cpanato** [comment]
waiting for https://github.com/mattermost/mattermost-redux/pull/107 to reproduce this

**Comment by jasonblais** [comment]
Can no longer reproduce
