### ISSUE TITLE
Peek Channel before Joining

### ISSUE THREAD

**Issue by realrolfje** [mattermost/platform#6153]
Users should be able to peek at a public channels content before joining to prevent extranous join/leave system messages when people (or admins) are just there to check things out.

Going to a channel URL should show the channel contents, with a "join" button instead of a reply box. After pressing "join", the user is reported as joining the channel, and the user will get a box to type messages in.

This would also solve issue [6152, Users can not leave a channel](https://github.com/mattermost/platform/issues/6152)

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback!  

[We have an existing feature proposal here](https://mattermost.uservoice.com/forums/306457-general/suggestions/12877668-ability-to-view-channels-without-joining). Would you like to contribute to the discussion and upvote it?

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Thanks again for all the feedback! We can track the feature proposal here: https://mattermost.uservoice.com/forums/306457-general/suggestions/12877668-ability-to-view-channels-without-joining
