### ISSUE TITLE
Deactivated user shown in Team "Manage Members" screen.

### ISSUE THREAD

**Issue by realrolfje** [mattermost/platform#6154]
#### Summary
System Admins see deactivated users as part of a Team.

#### Steps to reproduce
As a System Administrator: 
1. Click on the three dots in the left menu.
2. Click on "System Console"
3. Click on "Teams" and on "Users" in a team menu.
4. Deactivate the top user in the list (needs to be alphabetical top user) with the dropdown menu in the user row.
5. Click on the three dots in the left menu and switch back to the team.
6. With the town-square for the team open, Click on the three dots, and click "Manage Members"
7. If you do NOT search for users, you will see the deactivated user in your screen. When you try to search for the deactivated user by typing in the search box, the user will dissapear.

#### Expected behavior
System-wide deactivated users should never be visible in any Team Administration related screens.

#### Observed behavior
See point 7 of the reproduction steps.

#### Possible fixes
This seems like a bug during the initial loading of the "Manage Members" screen. It feels like initial load is being done in System Admin context, but searching Team members is being done in Team Admin context.

**Comment by enahum** [comment]
Thanks for the report @realrolfje I created a ticket with the bug report for you to track https://mattermost.atlassian.net/browse/PLT-6365

**Comment by realrolfje** [comment]
I noticed this problem still present in 3.8.2, and is also present in the API. When sending a DM on the iPhone Beta App, the app shows all users, even the deactivated ones.

**Comment by esethna** [comment]
Hi @realrolfje, the ticket has been completed to address this issue. It will ship with Mattemost v3.9 on May 16th.

**Comment by realrolfje** [comment]
Nice! Thanks!
