### ISSUE TITLE
Editing channel header not updated for other users until reload

### ISSUE THREAD

**Issue by johandalabacka** [mattermost/platform#6157]
#### Summary
If I update channel header will other users not see this until reload of page/client

#### Steps to reproduce
Change the channel header. 

#### Expected behavior
Other users should both get message: XXX updated the channel header from: AAA to BBB and also see the new header at the top

#### Observed behavior
Header is not changed for other users than the user doing the change.

**Comment by johandalabacka** [comment]
On Mattermost 3.8

**Comment by lindy65** [comment]
Hi @johandalabacka,

Thanks for your report!  I'm not able to reproduce the issue on Mattermost 3.8.1 - I see the message: "XXX updated the channel header from: AAA to BBB" and I also see the new header at the top straight away.

Could you share more about which browser you're using?  You could also try [updating to v3.8.1](https://about.mattermost.com/download/) which was released yesterday.  

Let us know if this helps?

**Comment by johandalabacka** [comment]
I see the new header right away but other persons on the same channel doesn't. I also tried being logged in both in client and on webpage and if I update the channel header for example in the client will the webpage not be updated but I have to reload to see the change. I also tried updating to 3.8.1 but it didn't make any difference.

**Comment by lindy65** [comment]
Hi @johandalabacka, 

Thanks for the additional information...  Are you using the Mattermost Desktop App?  Sorry, I did not check the issue there and see it does reproduce when using the Desktop App.  

@jasonblais, is this a known issue or should I create a bug ticket?

**Comment by johandalabacka** [comment]
Hi @lindy65  I have tried both the webpage and the client (mac os x)

**Comment by jasonblais** [comment]
We have a help wanted ticket for a similar issue for renaming a channel, which doesn't update for other users until reload. 

https://github.com/mattermost/platform/issues/5834

It's probably a related issue, so I included a note that it reproduces for a channel header too.

Anyone in the community interested to help with a fix for this issue?

**Comment by lindy65** [comment]
Thanks for your feedback @johandalabacka ...  I think the note that @jasonblais has added to #5834 will solve the issue with the channel header as well.

**Comment by johandalabacka** [comment]
It seems to be the same issue. Thanks slot.
