### ISSUE TITLE
"Message Display compact" ignores "Default appearance of image link previews"

### ISSUE THREAD

**Issue by johandalabacka** [mattermost/platform#6158]
#### Summary
Using compact message display ignores setting for image link previews

#### Steps to reproduce
Select Account Settings > Message Display > Compact

#### Expected behavior
Image previews should show expanded or collapsed depending on setting or /expand /collapse command

#### Observed behavior
Image previews are always collapsed and the command /expand does nothing.

**Comment by johandalabacka** [comment]
On Mattermost 3.8

**Comment by jasonblais** [comment]
Hey @johandalabacka,

It seems to work for me

*collapsed*
![image](https://cloud.githubusercontent.com/assets/13119842/25277599/61fbbe8a-266d-11e7-8e41-dfb19d2590b1.png)

*expanded*
![image](https://cloud.githubusercontent.com/assets/13119842/25277624/72af5b38-266d-11e7-8f97-fe87ed4023ac.png)

Can you help share the image link previews that are not showing up for you?

**Comment by johandalabacka** [comment]
Hi. I missunderstod. I thought this also should affect how uploaded images was displayed. 
![Collapsed](https://cloud.githubusercontent.com/assets/9607173/25281245/04512b22-26ad-11e7-8b82-ed7bf509b9e9.png)
![Expanded](https://cloud.githubusercontent.com/assets/9607173/25281244/0441ab20-26ad-11e7-9e3d-452be02fa58c.png)

**Comment by trash-anger** [comment]
Hi,

I reopen this discussion ! ;)

But it would be great that it also apply to the uploaded images ! No ?

**Comment by jasonblais** [comment]
Thanks! Agree, we actually created a ticket and have started to consider the user experience around this https://mattermost.atlassian.net/browse/MM-9741
