### ISSUE TITLE
Problem with oauth

### ISSUE THREAD

**Issue by federicolucca** [mattermost/platform#6162]
Hi,

I'm trying https://github.com/enahum/mattermost-oauth2-client-sample and i have,i create the app and i have the client id and secret key correctly.

This is the response

{"id":"api.context.404.app_error","message":"Sorry, we could not find the page.","detailed_error":"There doesn't appear to be an api call for the url='/api/v3/oauth/authorize'.  Typo? are you missing a team_id or user_id as part of the url?","status_code":404}

Federico

**Comment by jasonblais** [comment]
Thanks @federicolucca,

Can you post a screenshot of the information you added in Integrations > OAuth 2.0 Applications page?

**Comment by esethna** [comment]
Hi @federicolucca, just checking if your issue has been resolved? If not, can you please help provide the following information,

1. What version of Mattermost are you running?
2. Have you set the Site URL setting in the system console?
3. Can you post a screenshot of the information you added in Integrations > OAuth 2.0 Applications page?

**Comment by lindy65** [comment]
I'll close this issue off due to inactivity but feel free to reopen it if you're still experiencing issues @federicolucca
