### ISSUE TITLE
[Help Wanted] [PLT-6368] Switch websocket to use `window.location.origin` instead of SiteURL

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6164]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6368)

Since we force the user to set a SiteURL now, the default dev config may have an incorrect SiteURL set which breaks the websocket while developing. Until we figure out locally overriding the config without dirtying the git repo, we can switch it back to use window.location.origin like regular client calls use.

GitHub issue: https://github.com/mattermost/platform/issues/6097

**Comment by lindy65** [comment]
This has been fixed with [this ticket](https://mattermost.atlassian.net/browse/PLT-6368) so closing for now.
