### ISSUE TITLE
Report more specific reason when upload big emoji img fails

### ISSUE THREAD

**Issue by VeraLyu** [mattermost/platform#6169]
For feature requests, please see: http://www.mattermost.org/feature-requests/.
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format:

#### Summary
We need to report more specific reason when upload big emoji img fails

#### Steps to reproduce
Add a custom emoji picture which is more than 1M.
Click 'save'.

#### Expected behavior
Report we only accept emoji img which is less than 1M.

#### Observed behavior
We reported "There appears to be a problem with your internet connection." on dashboard.
and when checking server log,I found:
"[2017/04/20 01:35:51 PDT] [EROR] /api/v3/emoji/create:createEmoji code=413 rid=i1dscihfx3n4x8qt441pnpefwy uid=kf8a44ks7t8sdgjzpiczgba4ic ip=192.168.23.1 Unable to create emoji. Image must be less than 1 MB in size."

**Comment by enahum** [comment]
@VeraLyu this is working fine for me, do you have a reverse proxy in front of Mattermost? maybe the issue is with the reverse proxy not waiting enough or some other related issue

**Comment by lindy65** [comment]
Hi @VeraLyu, just circling back to see whether you have resolved the issue?
