### ISSUE TITLE
[Help Wanted] [PLT-6376] Button for "Add Members to Team" modal should say "Add", not "Go"

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6171]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6376)

![image](https://cloud.githubusercontent.com/assets/13119842/25241687/e311ab14-25c4-11e7-9408-c2b9ca31393d.png)

**Comment by cpanato** [comment]
i can take it

**Comment by jasonblais** [comment]
Thanks!

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6185
