### ISSUE TITLE
[Help Wanted] [PLT-4113] Blank FileSettings.Directory setting should act as default

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6173]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4113)

If the FileSettings.Directory is set to blank in either the System Console or directly in the config.json itself, the default "./data/" should be used in it's place.

The UI in the System Console should show "./data/" as the placeholder if the field is left blank and the server should load that as the default.

**Comment by justinwyer** [comment]
I'll take a look at this

**Comment by jasonblais** [comment]
Resolved, thanks @justinwyer! 🎉
