### ISSUE TITLE
[Help Wanted] [PLT-4539] Add confirm dialog before leaving private group

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6175]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4539)

Repro:
1. In private group, go to channel menu and click "Leave group"

Observed:
2. You leave the private group and it is no longer visible on LHS

Expected:
A confirm dialog:

Header: Leave Private Channel [Channel Name]
Body: Are you sure you wish to leave the private channel [Channel Name in Bold]? You must be re-invited in order to re-join this channel in the future.
Buttons: [Cancel] [Yes, leave group]

![image](https://cloud.githubusercontent.com/assets/13119842/25245279/e07ba73a-25d1-11e7-802a-4438a3c044a1.png)
^*note: "private group" has since been renamed to "private channel". The change has been reflected in the help text above the screenshot*

**Comment by R-Wang97** [comment]
I can take a look at this!
