### ISSUE TITLE
[Help Wanted] [PLT-4208] Move Current Email to a separate field in Account Settings > Email > Edit

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6176]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4208)

Change the interface in Account Settings > Email > Edit to:
1) Move the current email into its own section so it's always visible
2) Update the labels for the fields to match the following screenshot:

![image](https://cloud.githubusercontent.com/assets/13119842/25246662/5a6b12d4-25d6-11e7-9686-ddaadd9e8856.png)

**Comment by R-Wang97** [comment]
I can take this as well.

**Comment by jasonblais** [comment]
Thanks @R-Wang97! Resolved by #6197
