### ISSUE TITLE
[Help Wanted] [PLT-4149] Add "Already have an account? Click here to sign in" to the sign up page

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6177]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4149)

Repro: Go to https://pre-release.mattermost.com/signup_user_complete

Observed: There is no option to sign in on the main sign up page.

Expected: Add "Already have an account? Click here to sign in." below the buttons similar to the email signup page here https://pre-release.mattermost.com/signup_email

![image](https://cloud.githubusercontent.com/assets/13119842/25246715/7e7beb44-25d6-11e7-940c-abe84790714c.png)

**Comment by cpanato** [comment]
I can take it
