### ISSUE TITLE
websocket uses wrong domain

### ISSUE THREAD

**Issue by hank** [mattermost/platform#6183]
#### Summary
When making requests, the websocket URL doesn't use the base domain given in the URL bar.

#### Steps to reproduce
1. Create a CNAME for a mattermost instance that doesn't match the configured base URL in the site settings (eg. b.mydomain.com instead of a.mydomain.com)
1. Configure a virtualhost in apache to forward requests to b.domain.com into the mattermost instance on 127.0.0.1.
1. Log in and observe the websocket requests still going to the original domain (a.mydomain.com in this example).

#### Expected behavior
I would expect ALL requests to go to the domain specified by the user unless overridden in the settings (perhaps have a setting to specify the websocket base domain name).

#### Observed behavior
![capture](https://cloud.githubusercontent.com/assets/8534/25263037/b6fb2f30-262a-11e7-9417-eab891b7bcf6.PNG)
The 403 errors are because my main mattermost domain uses SSL client certificates, which your Windows and Android apps do not support. This has forced me to create a completely different domain name that does not require client certificate authentication.

#### Possible fixes
I haven't gone through the code, but I could if it would help - it should be pretty easy to find this. An alternative fix would be to support SSL client certificates in both the Android app and the Windows app - that would prevent me from having to have this second domain exclusively for those platforms.

**Comment by hank** [comment]
Here's the developer console from the Windows app when trying to access the websocket:
![capture2](https://cloud.githubusercontent.com/assets/8534/25263163/9322c284-262b-11e7-8635-5e73582d1bcd.PNG)

**Comment by enahum** [comment]
Hi @hank there is a ticket to make the websocket in the webapp to use the current origin https://mattermost.atlassian.net/browse/PLT-6368

**Comment by hank** [comment]
Thanks I've voted for it and watched it.

**Comment by hmhealey** [comment]
@hank We've had enough reports of this that we're actually going to do this in a 3.8.2 release. Stay tuned for that

**Comment by hank** [comment]
Great! If at some point you're working on supporting SSL client certificates in the Windows and Mobile apps, that would greatly benefit me. I require client certs for security from all my employees, and the above is just a workaround for the apps (albeit imperfect). Thanks for the quick response!

**Comment by ohlookemus** [comment]
Any word when this will be released? I upgraded from 3.7.x and now I can't downgrade.

**Comment by ohlookemus** [comment]
FYI, I built the 3.8.2 tag (not quite sure if I built it correctly but...)

I'm still seeing web socket issues related to origin. Not sure if it's the same as this issue.

[2017/04/21 14:13:44 PDT] [EROR] websocket connect err: websocket: origin not allowed

**Comment by jasonblais** [comment]
@hank Mattermost 3.8.2 is available for download here: http://about.mattermost.com/download/

The dot release should fix the WebSocket connection issues you've described. 

Please let us know if you hit any further issues, and thank you for the report!

**Comment by esethna** [comment]
Thanks everyone, closing this issue as solved. Feel free to re-open if your issue is not fixed after upgrading to v3.8.2.
