### ISSUE TITLE
Pasting of Theme Colors is disabled

### ISSUE THREAD

**Issue by Wegi** [mattermost/platform#6184]
#### Summary
The field for pasting theme data is read-only.

#### Steps to reproduce
Version: 3.7.0  (3.7.3)
Database: postgres

#### Expected behavior
According to several documentation the field should be read-write not read-only.

#### Observed behavior
The field ist read-only.

#### Possible fixes
--

**Comment by lindy65** [comment]
Hi @Wegi,

Thanks for your issue report!

Could we have your help upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost and seeing if the issue still reproduces for you?

**Comment by Wegi** [comment]
I'm gonna try it out and report as soon, as our System is up-to-date. (I have no control over the updates.)

**Comment by lindy65** [comment]
Thanks @Wegi, let us know how it goes!

**Comment by esethna** [comment]
Hi @Wegi, to clarify, are you able to copy and paste an entire theme vector into the text box? For example,  copy this vector, click in the text box and Ctrl/Cmd-V to paste.

```
{"sidebarBg":"#171717","sidebarText":"#fff","sidebarUnreadText":"#fff","sidebarTextHoverBg":"#302e30","sidebarTextActiveBorder":"#196CAF","sidebarTextActiveColor":"#FFFFFF","sidebarHeaderBg":"#1f1f1f","sidebarHeaderTextColor":"#FFFFFF","onlineIndicator":"#399fff","awayIndicator":"#c1b966","mentionBj":"#0177e7","mentionColor":"#FFFFFF","centerChannelBg":"#1F1F1F","centerChannelColor":"#DDDDDD","newMessageSeparator":"#CC992D","linkColor":"#0D93FF","buttonBg":"#0177e7","buttonColor":"#FFFFFF","errorTextColor":"#ff6461","mentionHighlightBg":"#784098","mentionHighlightLink":"#A4FFEB","codeTheme":"monokai"}
```

The text box does not allow you to edit a theme vector by text, but it should allow you to copy and paste entire theme vectors.

**Comment by lindy65** [comment]
Hi @Wegi,

Just circling back to check whether you still have this issue after your system update?

**Comment by Wegi** [comment]
Hi lindy65,

esethnas comment clarified, that I was using the box wrongly. Since it was read-only I was under the impression that you can not paste anything there. Maybe it could be made more intuitive in future versions. :) Im gonna close this issue, since it was a misunderstanding.

**Comment by lindy65** [comment]
Thanks @Wegi,

Here is the documentation on theme colors so you have a reference:
https://docs.mattermost.com/help/settings/theme-colors.html#theme-colors
