### ISSUE TITLE
Puzzling admin error message: Failed to add from email address

### ISSUE THREAD

**Issue by stephaneeybert** [mattermost/platform#6189]
#### Summary
Make the message "Failed to add from email address" more explicit

#### Steps to reproduce
Open the ./admin_console/notifications/notifications_email page.
Type in correct email server connection settings (security none).
Click on the "Test Connection" button.

#### Expected behavior
A more explicit message, giving more details.

#### Observed behavior
I saw the message: "Connection unsuccessful: Failed to add from email address"

#### Possible fixes
The message is sent in the utils/mail.go file at line 139

**Comment by lindy65** [comment]
Thanks for your issue report @stephaneeybert,

We agree that this would be a good improvement and have created a [ticket](https://mattermost.atlassian.net/browse/PLT-6392) to track the issue.

We'll most probably make it a [HELP WANTED] ticket.  Is there anyone in the community who is interested in submitting a PR for this?

**Comment by esethna** [comment]
Closing this issue to track in [JIRA](https://mattermost.atlassian.net/browse/PLT-6392)
