### ISSUE TITLE
MySQL init process failed.

### ISSUE THREAD

**Issue by astropanic** [mattermost/platform#619]
When I run the software via the Docker Image from [Docker Hub](https://hub.docker.com/r/mattermost/platform/) like this:

```docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform```

the container exits after few seconds with exit code 1

```docker logs``` shows

~~~
--- cut ---
MySQL init process in progress...
MySQL init process in progress...
MySQL init process in progress...
MySQL init process failed.
~~~

I tried the tags dev, 0.7 and latest

Docker version 1.8.0

**Comment by Salzig** [comment]
can`t reproduce on
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

using

```
REPOSITORY             TAG                 IMAGE ID
mattermost/platform    latest              1ce868eaaa76
```

**Comment by astropanic** [comment]
strange, the bug occurs on Docker v1.8.0.

The container runs fine on v1.8.1
