### ISSUE TITLE
Upgrade type and failure to mention backing op ./data/ directory

### ISSUE THREAD

**Issue by realrolfje** [mattermost/platform#6199]
#### Summary
The mattermost upgrade manual misses a few detais for upgrading to version 3.8.2

#### Possible fixes

1. The second title says "Upgrade Team Edition to 3.1.x and later", which shoud be "Upgrade Team Edition to 3.8.x and later"
2. In the bullet "3. Backup your data", there should be instructions to backup the default ./data/ directory. In our case this maps to /opt/mattermost/data, which may get lost when things go wrong in the upgrade.
3. The bullet "4. Install new version" does not mention in which location the tar file should be unpacked, and as which user. In our case, that's `cd /opt/mattermost; sudo tar -xzf ...`.

I would love to update the documentation but I think you guys will get this done quicker, helping more people eager to upgrade to 3.8.2.

**Comment by JeffSchering** [comment]
Hi @realrolfje here's a first draft of a new upgrade doc: [Reworked upgrade and legacy upgrade guides #1121](https://github.com/mattermost/docs/pull/1121)

It's a first draft and open to change, so please leave comments on that PR if you think anything needs updating. Thanks!

**Comment by lindy65** [comment]
Thanks @realrolfje and @JeffSchering,

As we have a PR to track this issue, I'll close it off for now and we can track through the PR.
