### ISSUE TITLE
Login with gitlab say no account found

### ISSUE THREAD

**Issue by netroby** [mattermost/platform#620]
I register one account using the same email address register gitlab, but while i try to login mattermost with gitlab oauth , the login hang up with message: 

GitLab Mattermost needs your help:
We couldn't find the existing account

How doese mattermost identify account. Not just by email address ?

**Comment by netroby** [comment]
http://**.**.**/login/gitlab/complete?team=deyi&code=6eb887a854bf4b7d3f941087014a42b44357bf0dc2016d2753885930781426e7&state=%242a%2410%24iZe5HaxhCPcKhvkkA%2FgzU.RSp0xNtCAKYvNuD0rSbAjTzjZkw4yx.

the url address seems like this

**Comment by it33** [comment]
Hi @netroby, please see forum post: http://forum.mattermost.org/t/gitlab-mattermost-needs-your-help-we-couldnt-find-the-existsing-account/185

We'll be updating error message to make this more clear in GitLab 8.0
