### ISSUE TITLE
[Help Wanted] [PLT-4922] Change Channel Picker and At Mention autocomplete to prioritize entries where the username/display_name starts with the search string

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6200]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4922)

For the at mention autocomplete, it should sort users based on their username, but any user with their username starting with the search string should go first. For the channel switcher, it should sort the same way, but it should be based off of the channel's display name for non-DM channels and the other user's username for DM channels.

To give some context, if you search for "t" in the channel switcher right now, it'll show like:
- Analytics (analytics)
- Dave Thomas (dthomas)
- Town Square (town-square)

But the emoji autocomplete prioritizes entries that start with the search string so searching for "t" gives:
- :tree:
- :hat:
- :out:

**Comment by jasonblais** [comment]
This is fixed for the channel switcher. Separate ticket for at-mention autocomplete here: https://mattermost.atlassian.net/browse/PLT-6871
