### ISSUE TITLE
[Help Wanted] [PLT-4843] Add CLI tool for deleting channels

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6201]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4843)

We have one for archiving channels, we need to add one for permanently deleting from the database.

Proposed changes:
 1. rename existing CLI command `platform channel delete` to `platform channel archive` to reflect what it does (delete the channel from UI but leave it in the database). 
 2. create a new CLI command `platform channel delete` which permanently deletes a channel from the database (we have one for users and teams)

Channels can be specified by {team}:{channel} using the team and channel names or IDs.

Format: `platform channel delete {channels}`

Example: `sudo ./platform channel delete myteam:mychannel`

See related doc for archiving a channel from the CLI: https://docs.mattermost.com/administration/command-line-tools.html#platform-channel-delete
See a PR that added a CLI command for searching for users: https://github.com/mattermost/platform/pull/5918

**Comment by cpanato** [comment]
I will take this one :)

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6430

**Comment by jasonblais** [comment]
Thanks! 👍
