### ISSUE TITLE
[Help Wanted] [PLT-4643] Remove system messages from right hand sidebar after you close the comment thread

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6202]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4643)

Remove system messages from right hand sidebar after you close the comment thread

Example: if I set myself away using the command "/away", a message gets posted both on the right hand sidebar and center channel, which I would expect.

However, if I close then reopen the right hand sidebar (which could be much later), I wouldn't expect the system message to be part of the comment thread anymore.

**Comment by kulak-at** [comment]
I can take care of this one :)

**Comment by jasonblais** [comment]
Thanks @kulak-at!!
