### ISSUE TITLE
[Help Wanted] [PLT-2606] Allow sending of invites from "Send Email Invite" with empty rows

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6203]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-2606)

Repro steps:
1) Click on the Main Menu and select "Send Email Invite"
2) Enter an email address, "test@test.com"
3) Click "Add another" on the modal to add an extra row
4) Click save

Observed: An error message is shown and the user is not allowed to save because there's empty fields
Expected: Ignore completely empty rows when the user goes to save, assuming at least one user has been added.

**Comment by cpanato** [comment]
I can try this one

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6238

**Comment by jasonblais** [comment]
Thanks @cpanato! Resolved
