### ISSUE TITLE
[Help Wanted] [PLT-1444] Team and Channel URLs generated based on Team Name and Channel Name should replace accented letters with ASCII equivalents

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6204]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1444)

From Community Issue: https://github.com/mattermost/platform/issues/1624

For example,

Observed:
"Dév Spé" becomes "dv-sp" when the url is generated

Expected:
"Dév Spé" -> "dev-spe"

**Comment by chrismatteson** [comment]
I think I can take this on.

**Comment by chrismatteson** [comment]
Created pull request: https://github.com/mattermost/platform/pull/6273

**Comment by jasonblais** [comment]
Thanks @chrismatteson!
