### ISSUE TITLE
Markdown escape not working.

### ISSUE THREAD

**Issue by luckydonald** [mattermost/platform#6210]
#### Summary
>```md
>*\*something\**
>```

the markdown above should produce

> <i>\*something\*</i>

But did instead results in

> \\something\*\*

#### Steps to reproduce

Build Hash: 30974533941e73f102505d07badf538cfdbbf3fc
EE Build Hash: none
Build Datum: Thu Apr 13 11:03:18 UTC 2017

#### Expected behavior
According to https://daringfireball.net/projects/markdown/syntax#backslash
I should be able to escape the inner asterisks correctly

#### Observed behavior
It broke formatting, the escape slash is even visible.
![image](https://cloud.githubusercontent.com/assets/2737108/25332161/cd07bf38-28e5-11e7-9592-932a128220c7.png)

**Comment by lindy65** [comment]
Hi @luckydonald 

Thank you for your issue report!

I've reproduced on our nightly build server and have created a [ticket](https://mattermost.atlassian.net/browse/PLT-6405) to track.

**Comment by luckydonald** [comment]
As a quick note, your summary in the other ticket system is incorrect, as the markdown code actually get's rendered.
(Maybe click the edit button on my original post, and copy the source?)

**Comment by hmhealey** [comment]
Thanks @luckydonald, I added that to the ticket

**Comment by lindy65** [comment]
Hi @luckydonald 

The [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6405) is scheduled for next release on May 16th so I'll close this issue off for now.

 If you're interested helping with a pull request, please let us know.

**Comment by atamazov** [comment]
It is 2026 and bug still exists. Will this be done before I retire?
