### ISSUE TITLE
[Help Wanted] [PLT-4440] Investigate updating emoji list to support Unicode 9.0 Emoji

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6217]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4440)

Community report: https://github.com/mattermost/platform/issues/4281

We are missing emoji from the new Unicode 9.0 emoji list: http://emojipedia.org/unicode-9.0/

These changes should be made in the emoji.json of https://github.com/hmhealey/emoji once that's made public. Then that script can be used to generate a new emoji.jsx file.

You can talk to @hmhealey on GitHub (@harrison on pre-release) for help generating emoji.jsx.

**Comment by ccbrown** [comment]
This was taken care of by https://github.com/mattermost/platform/pull/7001.
