### ISSUE TITLE
menu point "Report a problem" throws 404

### ISSUE THREAD

**Issue by D-LABS-GmbH** [mattermost/platform#6225]
#### Summary
menu point "Report a problem" on a local installation throws 404 - page not found

#### Steps to reproduce
GitLab CE  v9.1.0
Mattermost v3.7.3
menu point "Report a problem" links to URL/static/help/report_problem.html but there's not static page available

#### Expected behavior
either a static HTML page with information about reporting a problem or a link to the mattermost project page (like menu point "help" does)

#### Observed behavior
URL/static/help/report_problem.html throws 404 - page not found

**Comment by lindy65** [comment]
Hi @D-LABS-GmbH,

Thanks for your issue report.  This is not reproducing for me on Mattermost 3.8.2.  Could I have your help upgrading to the [latest version](https://about.mattermost.com/download/) to see if you still see the error?

**Comment by D-LABS-GmbH** [comment]
Mattermost has not yet been updated to v3.8.2 in the GitLab Omnibus package, thats unfortunate

**Comment by D-LABS-GmbH** [comment]
Well I've seem to lost access to the Mattermost system console as the "admin" account doesnt seem to be an system_admin anymore. And the command line tools in the omnibus package throws an null pointer exception ..

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbfbbd8]

**Comment by grundleborg** [comment]
@D-LABS-GmbH can you please paste the full command you are running as well as the full output it produces for that segfault?

**Comment by D-LABS-GmbH** [comment]
sudo ./mattermost roles system_admin username

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbfbbd8]

goroutine 1 [running]:
main.getUserFromUserArg(0x7fff31a3089d, 0x4, 0x1)
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/cmd/platform/userargs.go:21 +0x28
main.getUsersFromUserArgs(0xc4200159b0, 0x1, 0x1, 0xc420da5c18, 0xae6e74, 0xc420d82fc0)
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/cmd/platform/userargs.go:13 +0xa2
main.makeSystemAdminCmdF(0x11a2b00, 0xc4200159b0, 0x1, 0x1, 0x0, 0x0)
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/cmd/platform/roles.go:46 +0xdc
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0x11a2b00, 0xc420015940, 0x1, 0x1, 0x11a2b00, 0xc420015940)
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:643 +0x3ef
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200a46c0, 0x0, 0x0, 0x0)
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200a46c0, 0xc4200158c0, 0xb)
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:692 +0x2b
main.main()
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/cmd/platform/mattermost.go:50 +0x4b2

**Comment by grundleborg** [comment]
What happens if you do `sudo ./mattermost version`?

**Comment by D-LABS-GmbH** [comment]
Version: 3.7.0
Build Number: 3.7.3
Build Date: Wed Mar 22 23:31:00 UTC 2017
Build Hash: 8ec37570742b67fd640bb3434ea226c655dbf408
Build Enterprise Ready: false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbfc2c6]

goroutine 1 [running]:
main.printVersion()
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/cmd/platform/version.go:29 +0x3f6
main.versionCmdF(0x11a57a0, 0x11cb830, 0x0, 0x0)
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/cmd/platform/version.go:20 +0x30
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0x11a57a0, 0x11cb830, 0x0, 0x0, 0x11a57a0, 0x11cb830)
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:647 +0x231
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200a46c0, 0x0, 0x0, 0x0)
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200a46c0, 0xc420134ac0, 0xb)
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:692 +0x2b
main.main()
        /home/ubuntu/workspace/msr/d/platform-release/src/github.com/mattermost/platform/cmd/platform/mattermost.go:50 +0x4b2

**Comment by grundleborg** [comment]
Could you try going up a directory and running `sudo ./bin/mattermost version`? It seems like it might not be finding the database connection config file for some reason.

**Comment by D-LABS-GmbH** [comment]
same result/output as above

**Comment by grundleborg** [comment]
I can reproduce this CLI problem exactly as you described on a clean install of Gitlab Omnibus 9.1.0. I've [filed an issue](https://mattermost.atlassian.net/browse/PLT-6397) on Mattermost JIRA to look into this - currently, we think it may be a bug with how Gitlab Omnibus is packaging the Mattermost CLI.

**Comment by D-LABS-GmbH** [comment]
Ok, thank you!

**Comment by esethna** [comment]
Thanks everyone, closing this issue to track in [JIRA](https://mattermost.atlassian.net/browse/PLT-6397)
