### ISSUE TITLE
[Help Wanted] [PLT-6383] Add "CAUTION" to @-all auto-complete

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6229]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6383)

People are getting spammed by @all and it's preventable. We should prevent it. 

Change help text in @all auto-complete to "CAUTION: This mentions everyone in channel" until someone implements a warning message for @all: https://github.com/mattermost/platform/issues/6082

Right now the help text for @all in auto-complete is useless and doesn't warn you that you're about to spam 500+ people: 

![image](https://cloud.githubusercontent.com/assets/13119842/25412861/e8ddb816-29f3-11e7-8a0f-da036d6f5a96.png)

"Notify" isn't clear enough, both unreads and mentions are notifications, you are MENTIONING EVERYONE.

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6240
