### ISSUE TITLE
[Help Wanted] [PLT-5562] Profile picture of other users doesn't update until logout/login

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6239]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5562)

Repro:

1) User A uploads new profile picture
2) User B clicks on User A's username in center channel

Observed: 

User A's profile picture hasn't changed, even after a refresh. Login/logout is required, although in at least one case, a full clearing of cache was required until the profile picture was visible to other users.

Expected: 

User A's profile picture updates after User B starts a new session such as after refresh. The behaviour should match when User A updates their username or full name (which User B sees reflected after refresh).

Note: When investigating a fix, make sure it's using the user update timestamp properly. There might be a bug where we're using the old timestamp for profile pictures, causing it not to update for other users.

**Comment by knif3** [comment]
I noticed that other user have the same timestamp as my profile.
My guess is that there's no user in props or it's last_picture_update is null:

webapp/components/post_view/components/post.jsx:211
```
let timestamp = 0;
if (!this.props.user || this.props.user.last_picture_update == null) {
    timestamp = this.props.currentUser.last_picture_update;
} else {
    timestamp = this.props.user.last_picture_update;
}
```

**Comment by jasonblais** [comment]
Thanks @knif3 for your help looking into this, really appreciated.

Would you be interested helping with a fix for it? We'd be happy to help -- we'll also review the pull request and share feedback if any.

**Comment by esethna** [comment]
Closing as fixed with: https://github.com/mattermost/platform/pull/6661
