### ISSUE TITLE
[Help Wanted] [PLT-4257] Prompt user when status is manually set /away or /offline upon login

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6248]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4257)

When your status is manually set to away/offline, prompt user through a dialog (similar to attachment) to set themselves back online if they 
 - close or exit the Desktop App, then re-open it
 - close the browser tab, then re-open it
 - log out / quit, and then log back in
 - wake computer from sleep, then get re-focus on Mattermost

Repro:
1. Set yourself as /away or /offline using slash commands.
2. Log out then log back in

Observed:
Nothing happens. (poor awareness of status/situation)

![image](https://cloud.githubusercontent.com/assets/13119842/25449916/4e5601c0-2a8b-11e7-8f37-a41b09199b13.png)

Expected:
Dialog prompt to set yourself as online.

Note: If the user selects "Do not ask me again" before clicking "No" or "Yes", the prompt will not be displayed to that user again.

**Comment by jasonblais** [comment]
This issue is now in progress by Joram
