### ISSUE TITLE
Non admin users can add and remove members of public and private groups

### ISSUE THREAD

**Issue by nabeeldesai** [mattermost/platform#6249]
#### Summary
All users can remove another member from any group, public or private.

#### Steps to reproduce

1. Login to Mattermost as a non-admin user
2. Select any group
3. Select the members of group icon along the header
4. Scroll to the bottom of the Member list
5. Select 'Manage Members'
6. Verify the controls for the member list on the group Member List

#### Expected behavior
[Remove Member] button is not displayed

#### Observed behavior
[Remove Member] button displayed and active. Selecting to remove a member completes the removal

**Comment by lindy65** [comment]
Hi @nabeeldesai,

Thanks for your issue report...

Could you clarify whether you are seeing this on the Team or Enterprise edition?

You can read about the [Policy](https://docs.mattermost.com/administration/config-settings.html#policy) settings which are available in Enterprise Edition E10 and higher.

Let me know if this helps?

**Comment by nabeeldesai** [comment]
Hi @lindy65 
We have the Enterprise, non-paid version. I'll have our admin check out the policies and settings. Thanks!

**Comment by nabeeldesai** [comment]
That covered it - apologies for the invalid bug

**Comment by lindy65** [comment]
No worries at all @nabeeldesai! 

Let us know if there's anything else we can help with!
