### ISSUE TITLE
Animated images not retaining transparency

### ISSUE THREAD

**Issue by prixone** [mattermost/platform#6270]
#### Summary
Animated images not retaining transparency when uploaded for emoji and possible other ends...

#### Steps to reproduce
Version: pre-release.mattermost.com

1. Custom Emoji > Add Custom Emoji
2. Save the image to your computer https://i.imgur.com/pmIfMVG.gif
![img](https://i.imgur.com/pmIfMVG.gif)
3. On the modal that was open from step 1 use the saved GIF from step 2
4. On the text preview in that page before clicking SAVE, it properly shows with transparency
5. After its saved and upload the background goes black, on the emoji
6. Using this emoji on any where will have its background black instead of transparent

SIDE NOTE: I've created it under the name :monkey-want: if u want to test it on pre-release.mattermost.com
#### Expected behavior
The GIF will retain its transparency, like the original above.

#### Observed behavior
The uploaded GIF had its background changed from transparent to black

#### Possible fixes
Unhappily this goes out of my knowledge field, all I have notice is that, the issue is/seems to be related to the `palette.Plan9` which doesn't have transparency maybe.

**Comment by lindy65** [comment]
Hi @prixone 

Thanks for the report!  I've reproduced on pre-release and master and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-6455) to track the issue.

**Comment by prixone** [comment]
@lindy65 its not just emoji it seems, also profile pictures lose their transparency it seems, so maybe even a global issue for any uploaded image that goes thru Plan9 palette.

**Comment by lindy65** [comment]
Thanks @prixone, I've added this note to the ticket...

**Comment by lindy65** [comment]
Hi @prixone, 
We have created a [Help Wanted issue here](https://github.com/mattermost/platform/issues/6299) and are looking for community's help. Would you be interested helping with a pull request?
