### ISSUE TITLE
[Help Wanted] [PLT-5671] Remove jQuery usage in emoji picker

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6281]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5671)

We need to remove the usage of jQuery in the emoji picker and replace it with plain JS. Most of the uses of jQuery were removed during the first PR for emoji picker but some cases of removing jQuery were too time-consuming to remove at the time.

To complete this, any imports of jQuery into any emoji picker files should be removed and any code that was using jQuery in those files should be replaced with the equivalent plain JS or refactored to perform the same task in a different way.

See https://github.com/mattermost/platform/pull/5157 which added the emoji picker. 
See https://github.com/mattermost/platform/pull/5904 which added the emoji picker for reactions.

**Comment by drojas** [comment]
I've been looking at this issue today. I can see only one function in _components/emoji_picker/emoji_picker.jsx_ that is using jQuery in _master_ so I have already ported it to vanilla javascript. After doing that I noticed the Jira ticket says this is now part of a bug fix. I was wondering what should I do with the changes I've made to my local code to remove jQuery usage from _emoji_picker.jsx_.

**Comment by hmhealey** [comment]
@drojas That note is actually incorrect now since it didn't end up getting done with that other ticket, so we'd gladly still take your PR. Your changes may conflict with [the ones made for that other ticket](https://github.com/mattermost/platform/pull/6352) since it touches the same code, but we can deal with that if it becomes a problem.

**Comment by jasonblais** [comment]
Sorry about that @drojas, I've removed the comment from the ticket

**Comment by jasonblais** [comment]
Thanks @drojas!
