### ISSUE TITLE
[Help Wanted] [PLT-5575] Review ordering of emoji on the picker

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6282]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5575)

Current emoji on the picker isn't perfect, as some similar emoji aren't grouped together (see examples).

![image](https://cloud.githubusercontent.com/assets/13119842/25580828/e325e968-2e51-11e7-8a7b-9a11c3bce044.png)
![image](https://cloud.githubusercontent.com/assets/13119842/25580834/e600d954-2e51-11e7-96b6-a7fc6f5e6e6e.png)

This is a ticket to review the order of emoji. These changes should be made in the emoji.json of https://github.com/hmhealey/emoji once that's made public. Then that script can be used to generate a new emoji.jsx file.

See https://github.com/mattermost/platform/pull/5157 which added the emoji picker. 
See https://github.com/mattermost/platform/pull/5904 which added the emoji picker for reactions.

If you have any questions, at-mention `hmhealey` or `jasonblais` .

**Comment by Hanzei** [comment]
Fixed with #7001?

**Comment by jasonblais** [comment]
Thanks again @Hanzei!
