### ISSUE TITLE
Mails should set HELO with FQDN

### ISSUE THREAD

**Issue by nevesnunes** [mattermost/platform#6288]
#### Summary
When delivering SMTP mail, the HELO message defaults to `localhost`, activating spam filters (`FSL_HELO_NON_FQDN_1` and `HELO_LOCALHOST`).

#### Steps to reproduce
Use any function that sends an email. For example `Password Reset`.

#### Expected behavior
The mail's HELO message is set to the local server's FQDN, thus not triggering spam filters.

#### Observed behavior
SMTP traffic was inspected in my server with the following command:
```
tcpdump -vvv -x -X -s 1500 -i eth0 'port 25'
```
Where the field `EHLO` can be found.

#### Possible fixes
I can confirm that the code in [go-fqdn](https://github.com/Showmax/go-fqdn) works as expected. It can be easily added to the function `SendMailUsingConfig()` in `utils/mail.go`:

```go
...

defer c.Quit()
defer c.Close()

if err := c.Hello(fqdn.Get()); err != nil {
    return model.NewLocAppError("SendMail", "utils.mail.send_mail.hello.app_error", nil, err.Error())
}

...

```

**Comment by hmhealey** [comment]
Hi @nevesnunes,

Thanks for the report. I've filed [a ticket for this on Jira](https://mattermost.atlassian.net/browse/PLT-6469) so that someone will take a look at it. If you'd like to work on it yourself, we'd gladly accept a pull request for it.

**Comment by lindy65** [comment]
Hi @nevesnunes,

I'll close this issue off as the [ticket](https://mattermost.atlassian.net/browse/PLT-6469) is done and closed and should ship with the next version of Mattermost.
