### ISSUE TITLE
Feature Request: Containerize services separately

### ISSUE THREAD

**Issue by stuartpb** [mattermost/platform#63]
https://github.com/mattermost/platform/blob/master/Dockerfile installs Postfix, MySQL, *and* Redis into the app container. This largely nullifies the advantages of containerization (having your cluster components independent and able to span any server topology); the only thing inside the container should be the application server, with the overall service structure specified through a mechanism like [Docker Compose](https://docs.docker.com/compose/) or [Kubernetes](http://kubernetes.io/) pods.

**Comment by so0k** [comment]
+1

**Comment by greigdp** [comment]
I made a quick attempt at this in a branch on my local fork - https://github.com/greigdp/platform/commit/445d213a4825867743d2b0d2259ad97d98332668

It's not perfect yet, nor designed for deployment (emails are sunk to a local webpage to allow for testing without a proper mail configuration). There is a docker-compose.yml as well, which seems to work OK for me.

Main improvements needed (that I can think of) would be
- put attachments/uploads into a data volume (to ensure all data is separated fully from the application, and can be backed up and restored/migrated). 
- figure out why the hostname of the installation shows wrongly (when picking the service name) - my guess is that it's simply a missed configuration setting for now.

Either way, this should be a starting point for anyone wanting to do a modular containerization, or even just spin it up and have a play. (NB for now I am running the web interface on port 8000, and port 8001 is a web UI to allow access to the mail that mattermost sends).

**Comment by acaranta** [comment]
Agreed ... was planning on doing it myself ... I'll check @greigdp work asap ;) thx

**Comment by eduherraiz** [comment]
+1

**Comment by jdassonvil** [comment]
It looks the container from [lazyfrosch](https://hub.docker.com/r/lazyfrosch/mattermost/) does the job pretty well

**Comment by it33** [comment]
Closing this issue since there's an implementation available, 

@acaranta, @eduherraiz @jdassonvil @stuartpb, @so0k, @greigdp please consider contributing to or opening an issue with https://github.com/lazyfrosch/docker-mattermost for an upgrade?

Upgrade instructions here: https://github.com/mattermost/platform/blob/master/doc/install/Upgrade-Guide.md

Also, there's many more installer options available since this ticket was opened: http://www.mattermost.org/installation/

**Comment by shuoli84** [comment]
Seems the issue closed too soon. Last checkin for docker-mattermost is 3 months old. And the version is pretty old. 

Create a compose file which able to deploy with swarm is a better idea?

**Comment by mfburnett** [comment]
Has any work been done on this, recently?
