### ISSUE TITLE
[Help Wanted] [PLT-6441] Not able to scroll down in message preview mode when using Markdown headings

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6302]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6441)

Not able to scroll down in message preview mode when using Markdown headings (see screenshots for repro).

Possible fix: 
 - Have a div inside the preview div, 
 - Check that div width, and 
 - If that div is higher than the max-height, then add the `.scroll` class like we normally do to the `.post-create` div.

![image](https://cloud.githubusercontent.com/assets/13119842/25904806/4ef03856-356e-11e7-9b56-c0030d3b57e5.png)

![image](https://cloud.githubusercontent.com/assets/13119842/25904811/52613ae4-356e-11e7-9fe0-42353ef3daab.png)

![image](https://cloud.githubusercontent.com/assets/13119842/25904816/55987006-356e-11e7-8885-d195bde97197.png)

**Comment by sudheerDev** [comment]
@jasonblais I can take this up but can someone tell me how to enable preview mode in text area?

**Comment by jasonblais** [comment]
Hey @sudheerDev! Thanks for your interest :) 

You can enable the preview mode from Account Settings > Advanced > Preview pre-release features, and selecting `Show markdown preview option in message input box`

**Comment by sudheerDev** [comment]
@jasonblais yes selecting it enabled it!

In edit mode, if the text is long enough to have a scrollbar then even in preview scrollbar exists.
But if its just say like three sentences then no scrollbar in edit mode and causes an issue in preview mode. 
![screen shot 2017-08-13 at 12 22 15 am](https://user-images.githubusercontent.com/4973621/29243502-14bdf7dc-7fbe-11e7-8f75-7473bfe7a0c8.png)
![screen shot 2017-08-13 at 12 22 38 am](https://user-images.githubusercontent.com/4973621/29243507-216a288e-7fbe-11e7-91f1-714ada290dab.png)

Possible fix suggested above confused me a little. 
By adding one line of css this adds a scrollbar to preview mode but with the same height as edit mode. Have a look at the screenshot below, Is this the desired behaviour?

![screen shot 2017-08-13 at 12 28 03 am](https://user-images.githubusercontent.com/4973621/29243522-5147fe1e-7fbe-11e7-8922-f70844790878.png)

**Comment by jasonblais** [comment]
Thanks @sudheerDev! We'll test the PR you submitted (https://github.com/mattermost/platform/pull/7194) but in the screenshot it looks okay.
