### ISSUE TITLE
Mattermost v3.9.0 RC3

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#6308]
This is a meta issue for v3.9.0 release updates. 

Release candidates will be posted here for testing on May 4th. 

The final release will be available May 16th. 

See the [changelog](https://github.com/mattermost/docs/blob/c2b58d0ac117457258b5b780178b6938bb01adc5/source/administration/changelog.md#release-v390) for details about the release.

**Comment by esethna** [comment]
#### v3.9.0 RC1 is cut

Test server: http://rctesting.reddogsofwar.com/
Download link: https://releases.mattermost.com/3.9.0-rc1/mattermost-3.9.0-rc1-linux-amd64.tar.gz 

**Tickets approved for RC2:**
-

**Comment by jasonblais** [comment]
### v3.9.0 RC2 is cut

Test server: http://rctesting.reddogsofwar.com/
Download link: https://releases.mattermost.com/3.9.0-rc2/mattermost-3.9.0-rc2-linux-amd64.tar.gz 

### Approved fixes for RC3

 - [Regression: Emoji size is no longer relative to text size](https://mattermost.atlassian.net/browse/PLT-6562)
 - [System Console: Compliance and Auditing tab causes console error](https://mattermost.atlassian.net/browse/PLT-6561)
 - Investigate - [System Console: Cannot restrict custom emoji creation to only team and system admins](https://mattermost.atlassian.net/browse/PLT-6565)
 - [Investigate: Message always shows Retry/Cancel when replying to a specific post](https://mattermost.atlassian.net/browse/PLT-6523)
 - [System Console: Terms of Service missing from login page if setting left blank](https://mattermost.atlassian.net/browse/PLT-6566)
 - [Policy setting for deleting channels is not properly hiding UI elements](https://mattermost.atlassian.net/browse/PLT-6556)
 - [Channels re-appear unread after minimizing, then reopening browser window](https://mattermost.atlassian.net/browse/PLT-6567)
 - [Only a few members can be found in "Add Members to Team" dialog](https://mattermost.atlassian.net/browse/PLT-6563)

**Comment by jasonblais** [comment]
### v3.9.0 RC3 is cut

Test server: http://rctesting.reddogsofwar.com/
Download link: https://releases.mattermost.com/3.9.0-rc3/mattermost-3.9.0-rc3-linux-amd64.tar.gz

**Comment by jasonblais** [comment]
### Approved fixes for RC5

 1. [Mention count for DMs increases while you're viewing the channel (only disappears after you switch away from it)](https://mattermost.atlassian.net/browse/PLT-6584)
 2. [Should not automatically rejoin public/private channels when rejoining a team](https://mattermost.atlassian.net/browse/PLT-6585)
 3. [RHS UI broken in compact view](https://mattermost.atlassian.net/browse/PLT-6583)

**Comment by jasonblais** [comment]
3.9.0 is now cut!

Download links available here: https://pre-release.mattermost.com/core/pl/pymemo4xiigimy1hqnp6e9y1wr

They will also be updated in our downloads page shortly https://about.mattermost.com/download
