### ISSUE TITLE
[Help Wanted] [PLT-6537] When at-mentioning someone in a GM who is not in the channel, warning shouldn't appear

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6364]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6537)

At mention someone in a group message channel which they are *not* a member of. 

You should not get a warning about them not receiving the mention because they are not in the group message channel. However, such a warning *is* shown.

**Comment by cpanato** [comment]
the server side generate this and send out an ephemeral post to the client, should we not send that from the server or should we block in the client this?

**Comment by jasonblais** [comment]
@cpanato how is this handled for direct message channels, do you know?

**Comment by cpanato** [comment]
@jasonblais I will check

**Comment by cpanato** [comment]
for the GM message the code is here: https://github.com/mattermost/platform/blob/master/app/notification.go#L101

**Comment by jasonblais** [comment]
For direct message channels, no warning is sent.

![image](https://cloud.githubusercontent.com/assets/13119842/26059593/4f4b1722-3950-11e7-9082-fe9023b84032.png)

So we can probably mimic how this is handled for direct messages (e.g. not sent from the server or blocked by the client).

You can also ask in the Developers channel, as my technical knowledge is limited,

**Comment by cpanato** [comment]
ok, will make the change :)

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6412
