### ISSUE TITLE
Mail: No way to use no Auth

### ISSUE THREAD

**Issue by piec** [mattermost/platform#6366]
#### Summary
Some SMTP servers require no Auth at all (eg. smtp-relay.gmail.com).
This is different from empty Username and Password (Username="", Password="")
There is no way in the UI to do that

#### Observed behavior
smtp-relay refuses to send emails 

#### Possible fixes
Add a way to have no auth in the UI (not just empty username / password)
This would set `auth` to `nil` in call to smtp.SendMail

**Comment by piec** [comment]
I got it working this way
https://github.com/piec/platform/commit/a9ba386fecca21e70549a99ed2aad18176583ef2

**Comment by esethna** [comment]
Glad you got it working. Closing this issue, feel free to re-open if you have any more problems.

**Comment by moonmeister** [comment]
This seems like a some what major issue. I can't relay mail through smtp-relay.gmail.com. Which is how I do everything. I'm not really interested in editing the code every-time there's an update. Is this something that is going to get fixed in the code base? thanks

**Comment by moonmeister** [comment]
I'm not sure if I need a help wanted ticket for this but I'm working on adding a boolean option to enable/disable auth.
