### ISSUE TITLE
Trying to Add mixpanel integration

### ISSUE THREAD

**Issue by Luismi74** [mattermost/platform#6369]
- deployed successfully with Heroku

- Modified all the .HTML files with the mixpanel scripts

- Used a custom wesbsite and DNS domain

- Used mattermost-heroku (i could add the script to the JSON file but dont know how)

- suggestions please?

**Comment by jasonblais** [comment]
Thanks @Luismi74, 

Would you open to posting this in our [Mattermost forums](forum.mattermost.org)? It has more visitors and therefore you'll have a better chance of receiving a response from the community.

You can propose an integration [in our feature idea forums](https://mattermost.uservoice.com/forums/306457-general/category/202591-integrations).

**Comment by Luismi74** [comment]
ok thanks!
