### ISSUE TITLE
status indicator not display

### ISSUE THREAD

**Issue by helphi** [mattermost/platform#6377]
#### Summary
status indicator not display

#### Steps to reproduce
click the `members` icon in any channel

#### Expected behavior
There is a status indicator for every member in the members list before, but it is not display now.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
![image](https://cloud.githubusercontent.com/assets/6457416/25889229/a92a4348-359b-11e7-9503-c0c939c3414b.png)

**Comment by lindy65** [comment]
Hi @helphi,

Thanks for your report.  We've created [this Jira ticket](https://mattermost.atlassian.net/browse/PLT-6576) for an improvement to include status indicators in the Channel Members list.  We'll most probably make this a `Help Wanted` ticket.

Would you, or anyone in the community, be interested in working on this?

**Comment by helphi** [comment]
ooo... I don't think it's a `improvement` bug a `bug`, because the indicator works well in `mattermost 3.4`.
![image](https://cloud.githubusercontent.com/assets/6457416/25978646/2491d388-36f6-11e7-8901-c6fff002963b.png)
Maybe someone changed some code cause this.

**Comment by jasonblais** [comment]
hey @helphi, we had a big refactoring of the code base for performance improvements in Mattermost 3.5. At that time, some of the status indicators were removed from the UI and the community is helping add them back, here's an example: https://github.com/mattermost/platform/pull/6341

**Comment by lindy65** [comment]
Thanks @jasonblais and @helphi 

I'll close this issue off for now as we have the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6576) to add the indicators back in to a future release.
