### ISSUE TITLE
[Help Wanted] [PLT-6522] "Unknown prop align on tag" warning from EmojiPicker

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6385]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6522)

Repro steps:
1) Enable the Emoji Picker in Account Settings > Advanced > Pre-release features
2) Refresh the page
3) Click on the :) by the post textbox to open the emoji picker

![image](https://cloud.githubusercontent.com/assets/13119842/25915794/9425377e-3590-11e7-9acf-4aa98ba39739.png)

**Comment by cpanato** [comment]
on that

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6391
