### ISSUE TITLE
Feature Request: Separate SMTP host and port into separate configuration fields

### ISSUE THREAD

**Issue by maxlazio** [mattermost/platform#642]
Hi all,

is it possible to separate port from `SMTPServer` config into `SMTPPort`, eg,

```
    "EmailSettings": {
        "SMTPServer": "smtp.example.com",
        "SMTPPort": "456"
   }
```

Port is usually a separate config option and you always have to specify it.

**Comment by coreyhulen** [comment]
You can specify the port in the SMTPServer setting like

 "SMTPServer": "email-smtp.us-east-1.amazonaws.com:465",

**Comment by maxlazio** [comment]
@coreyhulen I am aware of that, I am asking if it is possible to separate it into 2 options?

**Comment by coreyhulen** [comment]
ahh...don't see why not.  I've created https://mattermost.atlassian.net/browse/PLT-201to track this issue.

**Comment by it33** [comment]
Hi @maxlazio, I've tagged this one "GitLab" and it'll appear in the GitLab Mattermost query: https://mattermost.atlassian.net/issues/?filter=10001

Our next release is Oct 2, so this would most likely come for GitLab 8.1.

**Comment by maxlazio** [comment]
:+1:

**Comment by coreyhulen** [comment]
This is in master and will be part of 0.8 (https://github.com/mattermost/platform/pull/752).  FYI, the config file has changed significantly.
