### ISSUE TITLE
Outgoing webhooks not triggered by file uploads

### ISSUE THREAD

**Issue by jkae** [mattermost/platform#6420]
#### Summary
When submitting a post with no text content, such as a file upload without accompanying message, webhooks set with no trigger words do not fire.

#### Steps to reproduce
3.8.2 
1. Create outgoing webhook for Town Square to some external API, no trigger words, either trigger condition
2. Submit message in Town Square with any text (webhook fires)
3. Submit message in Town Square with any text + file (webhook fires)
4. Submit message in Town Square with no text + file (webhook does not fire)

#### Expected behavior
As file uploads create posts, and the webhooks are set to not have trigger words, one would expect that the webhooks fire even without text.

#### Observed behavior
I have noticed that trigger-wordless webhooks use the first string of text separated by whitespace as their trigger word. It might be possible that that behavior is causing the issue, as there is no text in a file-only post.

**Comment by lindy65** [comment]
Hi @jkae,

Thank you for your issue report!

Mattermost v3.9.0 shipped on May 16th.  Could we have your help upgrading to the [latest version](https://about.mattermost.com/download/) to see whether this issue still reproduces for you?

Thanks!

**Comment by jkae** [comment]
I've updated to v3.9.0 and can confirm that the behavior is reproducible in this version as well.

The API my webhooks hit simply logs payloads to the console:
```
-- post "test" --

INFO  [2017-05-22 13:05:48,793] test.TestResource: MMOutgoingWebhookPayload{teamId=sgg63kxq5ibptg96mf6aimgi5e, teamDomain=test, channelId=qsho38otdj8kje5b87wqd7a88o, channelName=town-square, timestamp=1495443946523, userId=ixpxx5z8a38m8crrw45j1sopgo, userName=admin, postId=cjyokoi39tya3r86hdq9fuowqh, text=test, triggerWord=test}

-- post an image, nothing happens --

-- post "test" --

INFO  [2017-05-22 13:06:03,921] test.TestResource: MMOutgoingWebhookPayload{teamId=sgg63kxq5ibptg96mf6aimgi5e, teamDomain=test, channelId=qsho38otdj8kje5b87wqd7a88o, channelName=town-square, timestamp=1495443961793, userId=ixpxx5z8a38m8crrw45j1sopgo, userName=admin, postId=1az4dtq6ui8wmeyqugdpgwwfby, text=test, triggerWord=test}

-- post "tst" with image attachment --

INFO  [2017-05-22 13:10:53,842] test.TestResource: MMOutgoingWebhookPayload{teamId=sgg63kxq5ibptg96mf6aimgi5e, teamDomain=test, channelId=qsho38otdj8kje5b87wqd7a88o, channelName=town-square, timestamp=1495444251726, userId=ixpxx5z8a38m8crrw45j1sopgo, userName=admin, postId=wqbf5au3oibw7b7zugj763z8dh, text=tst, triggerWord=tst}
```

**Comment by lindy65** [comment]
Hi @jkae, 

Thanks for upgrading and for your feedback,

I'll ask one of our product managers to post back here with what's expected if no trigger words are used.  As you mentioned, it seems that the webhook should fire with no trigger word specified but looking at the help text, this might be `optional if channel is selected'.

![image](https://cloud.githubusercontent.com/assets/13020833/26320547/6d9fc1fe-3f23-11e7-8e1a-852f7de8b09a.png)

**Comment by esethna** [comment]
Thanks @jkae,
This sounds like a bug, thanks for the report. I've [filed a ticket in JIRA](https://mattermost.atlassian.net/browse/PLT-6676), would you be interested in contributing the bug fix?

CC @lindy65

**Comment by lindy65** [comment]
Thanks @esethna!

**Comment by jkae** [comment]
@esethna I would be interested and I'll try to work on it.

**Comment by esethna** [comment]
Thanks @jkae, the [ticket](https://mattermost.atlassian.net/browse/PLT-6676) is actually already in progress by one of our core devs. But please feel free to take a look at any other [[Help Wanted] issues](https://github.com/mattermost/platform/issues) you can contribute.

**Comment by esethna** [comment]
Closing this issue so the progress can be [tracked in JIRA](https://mattermost.atlassian.net/browse/PLT-6676).
