### ISSUE TITLE
[Help Wanted] [PLT-6599] Add link to check Websocket port error message

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6422]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6599)

We get a lot of questions about the error message: 

“Please check connection, Mattermost unreachable. If issue persists, ask administrator to check WebSocket port.”

Proposed change: 

Link the text "check WebSocket port." to `https://about.mattermost.com/default-websocket-port-help/`

**Comment by lfbrock** [comment]
@kulak-at - is this one you might be interested in working on?

**Comment by kulak-at** [comment]
@lfbrock Sure, I can work on that!

**Comment by jasonblais** [comment]
@cpanato  We had a PR here https://github.com/mattermost/platform/pull/6444 but it got closed due to inactivity.. 

Would you be interested helping with this one?

**Comment by cpanato** [comment]
@jasonblais PR: https://github.com/mattermost/platform/pull/6743
