### ISSUE TITLE
Can't send emails

### ISSUE THREAD

**Issue by jostyee** [mattermost/platform#6425]
Asked on https://pre-release.mattermost.com/ several days before, nobody responded.

#### Summary
After upgrading to 3.9.0, we can't send emails with same smtp configurations any longer, test connection returns:
`Connection unsuccessful: Failed to set HELO`

<img width="463" alt="screen shot 2017-05-17 at 12 01 41 pm" src="https://cloud.githubusercontent.com/assets/88564/26138006/a0c9d238-3af8-11e7-8307-dcfd1d08d487.png">

console error logs:
`[EROR] Failed to to set the HELO to SMTP server smtp: Hello called after other methods`

#### Steps to reproduce
Deploy Mattermost 3.9.0
System console -> Notification -> Email -> Test Connection

#### Expected behavior
Sending mail successfully.

#### Observed behavior
failure

#### Possible fixes
Revert https://github.com/mattermost/platform/commit/0df61d161f98183069494cc349d18f01d8783453

**Comment by cpanato** [comment]
How is your hostaname and the Siteurl looks like?

**Comment by jostyee** [comment]
@cpanato 

Siteurl: https://im.company.com

What is `hostaname` you mean?

**Comment by jostyee** [comment]
`git revert 0df61d1` and then things back to work.

**Comment by cpanato** [comment]
To get the Hostaname you need access your server and then type hostname in the bash

**Comment by jostyee** [comment]
@cpanato `mattermost-0`

**Comment by jasonblais** [comment]
@jostyee Are you running the latest `master` branch?

That error message is not in the 3.9 release build (but is in the `master` branch as a related PR was submitted last week)

We are aware of an issue caused by https://github.com/mattermost/platform/pull/6322 and are currently fixing it in the `master` branch.

**Comment by hmhealey** [comment]
This should be fixed on master once https://github.com/mattermost/platform/pull/6464 is tested and merged

**Comment by jostyee** [comment]
@jasonblais yes, I built docker image based on master branch.
@hmhealey thanks for helping.

**Comment by cpanato** [comment]
@jostyee when the PR is merged can you try again please?

**Comment by jostyee** [comment]
@cpanato I'll test it by Monday, thanks for your effort.

**Comment by jostyee** [comment]
Backs to normal now, thanks again.
