### ISSUE TITLE
Feature Request: Enable relative paths to statics in HTML

### ISSUE THREAD

**Issue by cristicbz** [mattermost/platform#643]
This means if I configure nginx to serve mattermost at a particular route (like https://example.com/chat), while the html is sent correctly, when the browser tries to grab all the static resources at '/static/...` they fail with 404. The paths should be relative to allow mattermost to be served from any route.

**Comment by coreyhulen** [comment]
Hi @cristicbz unfortunately this is a bigger issue and there are other places in the code where the app assumes to be at the root.  Fixing the static dir is just one of the problems.

I've filed https://mattermost.atlassian.net/browse/PLT-200 to track this issue.

Thanks.

**Comment by it33** [comment]
Hi @cristicbz, we're still trying to prioritize adding this functionality 

Could we interest you in adding this to the [Mattermost feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be upvoted? 

Through the feature idea forum you'll be able to discuss the feature with other interested users, and receive notifications as the feature moves from an idea to [planned](https://mattermost.uservoice.com/forums/306457-general/status/1588357), as implementation is [started](https://mattermost.uservoice.com/forums/306457-general/status/1588360) and implementation its [completed](https://mattermost.uservoice.com/forums/306457-general/status/1588363). 

Alternatively, some features ideas may be set to [accepting pull requests](https://mattermost.uservoice.com/forums/306457-general/status/1588438) from the community for completion, and you'll receive alerts on that as well.

**Comment by it33** [comment]
Hi @cristicbz, closing this issue since there's a tracking ticket for it now. 

Would you be open to [filing a feature idea in the feature idea forum](http://www.mattermost.org/feature-requests/) so this change could be upvoted by the community? 

The work here is substantial, and having more community members showing interest would help raise its priority.

**Comment by rteusner** [comment]
That would also help us also a lot.

**Comment by carlj** [comment]
+1

**Comment by nouyang** [comment]
+1

**Comment by Hunga1** [comment]
+1

**Comment by florianbachmann** [comment]
+1

**Comment by fangying** [comment]
+1

**Comment by sonicyang** [comment]
+1

**Comment by philstephenson** [comment]
+1

**Comment by grisuthedragon** [comment]
+1

**Comment by kentyeh** [comment]
+1

**Comment by nmatelot** [comment]
+1

**Comment by ambimanus** [comment]
+1

**Comment by araujojohnny** [comment]
+1 I'm under apache2 proxy and getting 404 for /static/main.598ce99103ba6aaf3db4.js.

**Comment by mmelcot** [comment]
+1

**Comment by theriverman** [comment]
+1

**Comment by seanvree** [comment]
has this not been implemented yet?

**Comment by d3k4z** [comment]
+1

**Comment by dbwelch** [comment]
+1

**Comment by gutosurrex** [comment]
+1 our ngo is giving up on mattermost in favor of rocket.chat because of this issue... I will keep tracking the ticket, though.

**Comment by it33** [comment]
@coreyhulen sorry to bug you over the holidays, just wondering what the result was of the Dec 5, 2017 triage meeting where this ticket came up?
 https://mattermost.atlassian.net/browse/PLT-200
 
Looks like there was work in progress and someone got stuck? https://github.com/mattermost/mattermost-server/issues/7490#issuecomment-338641064

**Comment by coreyhulen** [comment]
@it33 we were waiting to queue this item until after the performance push.  We'll get it assigned to one of the feature teams in the new year.

**Comment by cessor** [comment]
+1 Am I missing something or is this feature still not available?

**Comment by lieut-data** [comment]
@cessor, we just demoed it internally and anticipate shipping the feature in the next release. Keep your eye on the release notes! :)
