### ISSUE TITLE
Mute Specific User/Integration?

### ISSUE THREAD

**Issue by annerajb** [mattermost/platform#6438]
I would like a way to mute integrations/users per channel is there something in the works for this?
Use case: we have a bot that post commit messages and says the users name every time we commit we get a email from the bot saying that we committed (making email notifications useless since i am not getting what really interest me)

**Comment by lindy65** [comment]
Hi @annerajb,

Thanks for your question!

You can mute notifications per channel by clicking on the `v` to the right of the channel name, clicking on `Notification Preferences`, selecting `Mobile push notifications` and setting to `Never`.

If this is not useful, please help create a suggestion on our [forum](https://mattermost.uservoice.com/forums/306457-general) where you, and others, can up-vote the suggestion up to 10 times.

There are also these existing suggestions you can up-vote if they match your use-case:
1. https://mattermost.uservoice.com/forums/306457-general/suggestions/16788097-temporary-mute-disable-channels
2. https://mattermost.uservoice.com/forums/306457-general/suggestions/12844593-mute-individual-users
3. https://mattermost.uservoice.com/forums/306457-general/suggestions/15097446-mute-specific-channels-in-app-more-granular-cont

Hope this helps?

**Comment by annerajb** [comment]
@lindy65 number two fits my suggestion better thanks.

**Comment by lindy65** [comment]
Awesome!  Thanks @annerajb :)

Hope you up-voted number two then ;)

I'll close this issue off as we have a feature suggestion for it.
