### ISSUE TITLE
[Help Wanted] [PLT-6548] Mobile Web View: Add "Leave Team" option to main menu

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6460]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6548)

In Mobile view, add "Leave Team" option the main menu.

It should be located below "Join Another Team", so the order is: 

——————————
Team Settings
Manage / View Members
Join Another Team 
Leave Team 
——————————

**Comment by cpanato** [comment]
what should be the icon? @jasonblais @esethna 
![screen shot 2017-05-19 at 16 20 41](https://cloud.githubusercontent.com/assets/4115580/26251918/25f5f9de-3caf-11e7-93c9-a0b06a532591.png)

**Comment by cpanato** [comment]
this:
![screen shot 2017-05-19 at 16 29 20](https://cloud.githubusercontent.com/assets/4115580/26252438/7e313b1c-3cb0-11e7-8f49-6a8746453b09.png)

or this:

![screen shot 2017-05-19 at 16 31 11](https://cloud.githubusercontent.com/assets/4115580/26252503/a351a81e-3cb0-11e7-8c87-a9c16658d32f.png)

**Comment by jasonblais** [comment]
Good question -- @asaadmahmood any thoughts on this one?

**Comment by jasonblais** [comment]
Hey @cpanato , I shared the SVG icon on pre-release that we can use

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6472
