### ISSUE TITLE
[Help Wanted] [PLT-3038] Update notification for webhooks sending attachments

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6465]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3038)

Repro: 
1. Set up an incoming webhook
2. Send the following as a payload: 
```
{
    "attachments": [
        {
            "title": "Title",
            "pretext": "Pretext _supports_ mrkdwn",
            "text": "Testing *right now!*",
            "mrkdwn_in": ["text", "pretext"]
        }
    ]
}
```

Observed: The notification triggered says "webhook did something new"

Expected: Notification should follow the normal format (for example, "webhook wrote:"), and use the following priority for the body of the notification (for example, if fallback text is present use that as the body, but if not, use pre-text):
1) fallback text 
2) pre-text 
3) text 
4) "posted an image" if there is an image URL
5) "did something new"

**Comment by megos** [comment]
I'll take this one.
