### ISSUE TITLE
Outgoing WebHooks on Slack don't show the app's name on mobile app

### ISSUE THREAD

**Issue by skinsshark** [mattermost/platform#6466]
For feature requests, please see: http://www.mattermost.org/feature-requests/.
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format:

#### Summary
On the Slack **mobile** app, after correctly integrating the WebHook, the customized name does not appear in the app. (see screenshots in behavior sections)

#### Steps to reproduce
1. Set up a working Outgoing WebHook integration on Slack
2. Choose a Customized Name
3. Trigger the WebHook with trigger words on mobile Slack app
4. See the name of the service not appear

#### Expected behavior
Name of WebHook should appear: 
![image](https://cloud.githubusercontent.com/assets/13009769/26262878/374fe560-3c8b-11e7-8b70-8bc93ac67e22.png)

#### Observed behavior
Name of WebHook does not appear:
![image](https://cloud.githubusercontent.com/assets/13009769/26262886/4068d922-3c8b-11e7-85c3-540045186fc9.png)
(occurred in iOS)

**Comment by lindy65** [comment]
Hi @skinsshark,

Thanks for your feedback.

Could you share which version of Mattermost server you have installed?

**Comment by lindy65** [comment]
Hello @skinsshark,

Has your issue been resolved?

**Comment by lindy65** [comment]
Hi @skinsshark, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by skinsshark** [comment]
Hi @lindy65,

I missed these messages but I don't think I have a Mattermost server installed. It is simply on the Slack mobile app itself. The SlackBot is utilizing the [Outgoing WebHook](https://slack.com/apps/A0F7VRG6Q-outgoing-webhooks).
