### ISSUE TITLE
If the user signs in with a link to a specific POST, they will be redirected to the correct post after a successful login

### ISSUE THREAD

**Issue by Geetika12345** [mattermost/platform#6468]
With reference to issue postedon the mattermost forum on 7 May by Geetika dwivedi under title "Navigation to explicit post in the Mattermost from external application" , I am raising the help wanted ticket as suggested.

#### Summary
Navigation to explicit post in the Mattermost from external application.

#### Expected behavior
If the user signs in with a link to a specific POST, they will be redirected to the correct post after a successful login.
User should be able to navigate to the correct post provided a link from external application.
Thanks.

**Comment by jasonblais** [comment]
Thanks @Geetika12345! 

I'll queue this for approval for our next UX meeting on Tuesday, after which we'll most likely make this a help wanted ticket.

**Comment by Geetika12345** [comment]
Thanks Jasonblais. Any updates on the request raised?

**Comment by jasonblais** [comment]
Hey @Geetika12345! Thanks for following up,

One of the open pull requests has actually been updated to incorporate this request: https://github.com/mattermost/platform/pull/6304

Once the above pull request is merged, the user is redirected to the correct channel and/or post after login, depending on which URL they entered in their web browser.

**Comment by lindy65** [comment]
Hi @Geetika12345,

The [pull request](https://github.com/mattermost/platform/pull/6304) has been merged.  Please let us know if you are still experiencing the issue.

**Comment by Geetika12345** [comment]
Hi Lindy65,

Thanks for the update.

Hi Jasonblias,

Thank you for picking up the request.

I was trying to implement the same in my application,

I wanted to land up to the explicit post in mattermost from my application.
I used
mm/login?redirect=javascript:alert('/postid')
It dint work i.e.  , can you please point out if i am using it wrongly.

Can you please explain how should i form the url for landing up on the same post .
Any help will be much appreciated.

**Comment by Geetika12345** [comment]
Hi Jasonblais,

Can you please confirm in which version of mattermost these changes has been incorporated , so that we can upgrade the mattermost to the specific version , we are currently using 3.9.0 version.

Thanks.

**Comment by lindy65** [comment]
Hi @geetika12345,

These changes should be in the next release, v3.10, on June 16th.

**Comment by jasonblais** [comment]
@Geetika12345 @lindy65 That is correct, it will be available on June 16th release.

If you're interested, you may also download a release candidate to test it out beforehand. The download links will be posted here this week: https://github.com/mattermost/platform/issues/6562
