### ISSUE TITLE
Unable to login for new ldap users

### ISSUE THREAD

**Issue by ilvolodel** [mattermost/platform#6477]
#### Version

Version: 3.9.0
Build Number: 3.9.0
Build Date: Mon May 15 20:26:34 UTC 2017
Build Hash: ae3a62ef95e22ff67236e8addb1e4ca005307443
Build Enterprise Ready: true
DB Version: 3.9.0

#### Summary
When a new user is added to AD is not able to login to mattermost.

#### Steps to reproduce
Add new user to AD and try to login

#### Expected behavior
The issue is related to ldap syncronization, because all users exept new ones can login well on mattermost. 

#### Observed behavior
I have tried to do a manual sync via platform command but I receive this error:
root@polluce:/opt/mattermost/bin# sudo -u mattermost ./platform ldap sync
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xce50e5]

goroutine 1 [running]:
github.com/mattermost/platform/enterprise/ldap.(*LdapInterfaceImpl).Syncronize(0x14708c0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/enterprise/ldap/ldap.go:197 +0x45
main.ldapSyncCmdF(0x1445fc0, 0x14708c0, 0x0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/cmd/platform/ldap.go:31 +0x60
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0x1445fc0, 0x14708c0, 0x0, 0x0, 0x1445fc0, 0x14708c0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:617 +0x3f8
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1446680, 0x1449380, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:696 +0x339
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0x1446680, 0xc4200001a0, 0xc4200001a0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:655 +0x2b
main.main()
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/cmd/platform/mattermost.go:26 +0x2d
root@polluce:/opt/mattermost/bin# 

Same think without "sudo" command

**Comment by lindy65** [comment]
Hi @ilvolodel,

Thanks for your feedback,

Could you help us by letting us know what your LDAP configuration is?

Also, have you tried using the 'sync' button in the system console?

Thanks!

**Comment by ilvolodel** [comment]
Has I told to your colleague Alice I have tried to sync via console and nothing happens, I got a 200 status in web browser console .
My AD is windows active directory 2012.

**Comment by lindy65** [comment]
Thanks @ilvolodel,

Could you send us your config.json file so our devs can take a look and help debug?

**Comment by lindy65** [comment]
Hi @ilvolodel, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
