### ISSUE TITLE
[Help Wanted] [PLT-1649] Support Slack-compatible delayed slash commands

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6478]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1649)

Support Slack-compatible delayed slash commands

Slack supports a response_url field for slash commands, which lets you post additional messages to a channel for a period of time after a command is triggered. Response URLs can be used to send five additional messages within a thirty minute window from the original command invocation

Any request that are made to the response URL should support either a plain text or JSON-encoded body.

You can find more information about the delayed responses below
 - https://api.slack.com/slash-commands
 - https://api.slack.com/tutorials/slash-commands-style-guide

For an example use case, see https://claudiajs.com/tutorials/slack-delayed-responses.html

**Comment by ccbrown** [comment]
I'll take this one.

**Comment by coreyhulen** [comment]
Yup...have at it.

**Comment by jasonblais** [comment]
Closing as PR has been submitted, scheduled for Mattermost v4.2
