### ISSUE TITLE
[Help Wanted] [PLT-6392] Make the message "Failed to add from email address" more explicit

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6479]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6392)

Make the message "Failed to add from email address" more explicit

From this GitHub issue: https://github.com/mattermost/platform/issues/6189

Steps to reproduce
1. Open the ./admin_console/notifications/notifications_email page.
2. Type in correct email server connection settings (security none).
3. Click on the "Test Connection" button.

Expected behavior
Message "Connection unsuccessful: Notification From Address setting is missing or invalid."

Observed behavior
I saw the message: "Connection unsuccessful: Failed to add from email address"

Possible fixes
The message is sent in the utils/mail.go file at line 139

**Comment by cpanato** [comment]
made a comment in `Jira`

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6481
