### ISSUE TITLE
Mattermost Code taking too long to build on EC2 server ubuntu 16.04

### ISSUE THREAD

**Issue by ahsan-AJ** [mattermost/platform#6485]
I have uploaded the code to an Amazon ec2 ubuntu 16.04 server and upon starting make run, it starts installing dependencies installing yarn etc. But when it start webpack watching files, it gets stuck and sometimes it crashes the server so I have to restart it again. 
How do I solve this issue.?

**Comment by hmhealey** [comment]
Hi @ahsan-AJ,

What size of EC2 instance are you running? It's possible you're using too small of an instance and it's running out of memory.

**Comment by ahsan-AJ** [comment]
@hmhealey I am using ec2 micro instance free tier with 8gb storage.

**Comment by cpanato** [comment]
If you are using the T2.micro it just have 1 gb of memory you might need to increase the machine type

**Comment by jasonblais** [comment]
@ahsan-AJ Please see hardware sizing requirements here: https://docs.mattermost.com/install/requirements.html#hardware-requirements

We are currently working on a [load test framework](https://docs.mattermost.com/install/requirements.html#mattermost-load-test-framework) and have made lots of performance improvements in the past few months, so some of the requirements may be reduced after more testing.

**Comment by ahsan-AJ** [comment]
@cpanato @jasonblais  how much minimum memory and storage size required to run this development code on ec2 server, and please advise which ec2 instance you guys recommend should I use ?

**Comment by hmhealey** [comment]
@ahsan-AJ Our test instances run on t2.small instances with 2 GBs of ram, so that should be large enough

**Comment by ahsan-AJ** [comment]
@hmhealey  @cpanato @jasonblais . It is now working on bigger instance than t2 micro.
Thankyou all for the help :)

**Comment by jasonblais** [comment]
No problem! Closing the issue as resolved :)
