### ISSUE TITLE
[Help Wanted] [PLT-3470] Update formatting of user lists to include both full name and nickname

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6491]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3470)

Update the user list formatting in the Direct Messages "More" Menu, Channel Add Members and Channel Manage Members, Team Manage Members and System Console users pages to include both nickname and full name.

The format should be as follows (see screenshot): 
@username - full_name (nickname)
email address

If full name isn't filled out but nickname is, the format should be: 
@username - nickname
email address

![image](https://cloud.githubusercontent.com/assets/13119842/26429417/bf62a672-40b4-11e7-8d69-4eef5fb871d4.png)

**Comment by jsfeb26** [comment]
I'll work on this

**Comment by esethna** [comment]
Closing as done.
