### ISSUE TITLE
[Help Wanted] Create local mysql server without docker mattermost-mysql image.

### ISSUE THREAD

**Issue by ahsan-AJ** [mattermost/platform#6492]
I want to run mattermost code on local system with the developer's code from mattermost/platform. With this, I want to use my own mySQL database set up on my machine so that I can view tables and data as well. How could I do this ?

**Comment by cpanato** [comment]
You need to set the mysql config in the config file to use your local db

**Comment by ahsan-AJ** [comment]
I have changed the following settings in config.json file for the mySQL connection 

 "SqlSettings": {
        "DriverName": "mysql",
        "DataSource": "username:password@localhost:3306/mattermost?   charset=utf8mb4,utf8\u0026readTimeout=30s\u0026writeTimeout=30s",
        "DataSourceReplicas": [],
        "DataSourceSearchReplicas": [],
        "MaxIdleConns": 20,
        "MaxOpenConns": 300,
        "Trace": false,
        "AtRestEncryptKey": "popnpf6g4geertocf1suc7rqyk6xdafg"
    }

It is still not connecting to database.

**Comment by cpanato** [comment]
You might need to set the username and the password as well you will need to create the database and give it a name and set that in the connection string

**Comment by ahsan-AJ** [comment]
@cpanato 

I already did I have given username and password and also that database name and it is giving the following error.

[2017/05/25 13:56:49 PKT] [INFO] Pinging SQL master database
[2017/05/25 13:56:49 PKT] [CRIT] Failed to ping DB err:default addr for network 'localhost:3306' unknown

**Comment by ahsan-AJ** [comment]
It is working now on an aws ec2 instance (I installed mysql using apt-get) but when I start mysql server and then execute command 'make run' it gives the following error: 

Starting docker containers
restarting mattermost-mysql
Error response from daemon: driver failed programming external connectivity on endpoint mattermost-mysql (16885a060bc28d777827d6230e8fa04300763877c964a065221a38c4ba918d2f): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
Error: failed to start containers: mattermost-mysql
Makefile:73: recipe for target 'start-docker' failed
make: *** [start-docker] Error 1

How do I solve this issue ?

**Comment by ahsan-AJ** [comment]
It is fixed, by chanhing the port of Docker image, local mysql is running now. Thankyou :)

**Comment by imrajkirpalsinh** [comment]
Hi aj160 ,
Can you specify the sequence of steps to follows to run the mattermost on local windows machine ?
