### ISSUE TITLE
Incorrect task and publisher name in Windows 10 startup task list.

### ISSUE THREAD

**Issue by lvictorino** [mattermost/platform#6493]
When Mattermost App is set to be launched at startup, the task manager displays an incorrect name or publisher name that can be very confusing for users.

#### Steps to reproduce

1. Set Mattermost Windows App to start with Windows.
2. Launch Windows Task Manager (CTRL+ALT+SUPRR)
3. Select Startup Tab
4. Mattermost App is under a group named Update(X) and the Publisher is GitHub

![capture2](https://cloud.githubusercontent.com/assets/18822/26450271/de5ee4bc-4156-11e7-9b11-f2e2ff5fe3d9.PNG)

#### Expected behavior
Instead of Update the name of the process should be Mattermost (about the publisher name I don't know how you guys deal with it, but I would expect Mattermost in there too).

**Comment by jasonblais** [comment]
Thanks @lvictorino! I've submitted an issue in the desktop app repo: https://github.com/mattermost/desktop/issues/542
