### ISSUE TITLE
[Help Wanted] [PLT-6400] Add link to docs in config.json readme file

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6496]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6400)

It's not clear which settings in config.json are in which edition, which is causing confusion: https://github.com/mattermost/platform/issues/5935#issuecomment-296772223

Propose including a short README file in the config directory. It's a minimalist solution with limited code changes, yet provides necessary resources for an admin to find it out (comments cannot be included within a config.json file).

Below is the text we can include in the README.

```
# CONFIG.JSON

This is the system configuration file for your Mattermost server. Settings are specific to different editions of Mattermost. Please read the documentation before making changes: https://about.mattermost.com/default-config-docs/
```

**Comment by R-Wang97** [comment]
I can get this done!
