### ISSUE TITLE
IRC support

### ISSUE THREAD

**Issue by queeno** [mattermost/platform#650]
Mattermost is an amazing platform, but it'd be even more amazing if it supported IRC!

**Comment by ryanleesipes** [comment]
Agreed, this is a top priority as my company ( https://mycroft.ai ) explores using this as our primary chat with the community.

**Comment by it33** [comment]
Thanks @queeno, thanks @ryanleesipes, 

The steps to getting to an IRC bridge are discussed in the feature request forum: http://mattermost.uservoice.com/forums/306457-general/suggestions/9425586-irc-bridge

Please add your upvote as you feel appropriate?

**Comment by it33** [comment]
Closing for now since this is duplicated in the feature request forum
