### ISSUE TITLE
getting error on firefox 45.0.2

### ISSUE THREAD

**Issue by Eng3l** [mattermost/platform#6510]
Recently I've update from version 3.6.0 to 3.9.0 and one of my users got this error using firefox 45.0.2.

```
Unhandled promise rejection TypeError: e.window.mm_config is undefined
Stack trace:
F@http://10.0.200.103:8065/static/main.1cd8c6923c736e775ad5.js:1:238642
D@http://10.0.200.103:8065/static/main.1cd8c6923c736e775ad5.js:1:238621
o/<@http://10.0.200.103:8065/static/main.1cd8c6923c736e775ad5.js:1:260630
P/</i@http://10.0.200.103:8065/static/main.1cd8c6923c736e775ad5.js:1:2155950
P/<@http://10.0.200.103:8065/static/main.1cd8c6923c736e775ad5.js:1:2156072
e.exports/u@http://10.0.200.103:8065/static/main.1cd8c6923c736e775ad5.js:1:589980
```

I'm using firefox 49 and it works ok.

**Comment by jasonblais** [comment]
Thanks @Eng3l, Firefox 45 is no longer officially supported by Mozilla and we propose upgrading to a newer version. Firefox ESR 45 also has its end-of-life scheduled for June 13, 2017: https://en.wikipedia.org/wiki/Firefox_version_history

We officially [support Firefox v52 and later](https://docs.mattermost.com/install/requirements.html#pc-web-experience) although previous version of Firefox are known to work, such as Firefox 49 in your case.

**Comment by Eng3l** [comment]
Thanks for your reply.
