### ISSUE TITLE
hi，when i run make，i got this "...node-sass: spawn ENOMEM"

### ISSUE THREAD

**Issue by af913337456** [mattermost/platform#6516]
[root@iZ2ze9eb5azhksl90ygrdsZ platform]# make
Checking client style
cd ./webapp && make check-style
make[1]: Entering directory `/root/mattermost/platform/webapp'
Getting dependencies using yarn
yarn cache clean
yarn cache v0.24.5
success Cleared cache.
Done in 0.07s.
yarn install --pure-lockfile
yarn install v0.24.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/8] ⠁ mattermost-redux: > babel src --out-dir .
[2/8] ⠁ gifsicle
[3/8] ⠂ mozjpeg: ℹ compiling from source
[6/8] ⠂ node-sass
error An unexpected error occurred: "/root/mattermost/platform/webapp/node_modules/node-sass: spawn ENOMEM".
info If you think this is a bug, please open a bug report with the information provided in "/root/mattermost/platform/webapp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make[1]: *** [.yarninstall] Error 1
make[1]: Leaving directory `/root/mattermost/platform/webapp'
make: *** [check-client-style] Error 2

os： linux centos

**Comment by cpanato** [comment]
I think it is memory related. how much memory to you have in this machine?

**Comment by af913337456** [comment]
[root@iZ2ze9eb5azhksl90ygrdsZ ~]# cat /proc/meminfo
MemTotal:        1014984 kB
MemFree:          273336 kB
MemAvailable:     247268 kB
Buffers:            4048 kB
Cached:            70476 kB
SwapCached:            0 kB
Active:           607844 kB
Inactive:          67888 kB
Active(anon):     601488 kB
Inactive(anon):      168 kB
Active(file):       6356 kB
Inactive(file):    67720 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               456 kB
Writeback:             0 kB
AnonPages:        601256 kB
Mapped:            13512 kB
Shmem:               432 kB
Slab:              32264 kB
SReclaimable:      16724 kB
SUnreclaim:        15540 kB
KernelStack:        4720 kB
PageTables:         7728 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      507492 kB
Committed_AS:    2373444 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       11284 kB
VmallocChunk:   34359717628 kB
HardwareCorrupted:     0 kB
AnonHugePages:    524288 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       61440 kB
DirectMap2M:      987136 kB

**Comment by af913337456** [comment]
Is that enough?

**Comment by cpanato** [comment]
this `MemTotal: 1014984 kB` is 1GB i think you need more. try to add at least 3GB

**Comment by af913337456** [comment]
ok thanks alot
