### ISSUE TITLE
[Help Wanted] [PLT-6452] Remove edit button on mobile, and have the edit icon beside the value, and the value as a link

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6520]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6452)

See a sample screenshot below.

The change should be applied to all account and team setting options.

![image](https://cloud.githubusercontent.com/assets/13119842/26594706/abc65d12-4536-11e7-968c-23219b8bae87.png)

**Comment by cpanato** [comment]
on that

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6565
