### ISSUE TITLE
[Help Wanted] [PLT-6695] Mobile web view: Add "Create Team" option to main menu

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6522]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6695)

**Comment by cpanato** [comment]
I can take this one

**Comment by cpanato** [comment]
@esethna what will be the icon for this one?

**Comment by lfbrock** [comment]
@cpanato we were discussing in this thread here: https://pre-release.mattermost.com/core/pl/esoepzsxjirb9e1dyfqqiod3dy

I think we might just use the same + button as join teams for now, unless @asaadmahmood proposes a different icon

**Comment by cpanato** [comment]
ok thanks @lfbrock

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6524

I can change the icon if needed
