### ISSUE TITLE
"Make Channel Admin" option incorrectly displayed 

### ISSUE THREAD

**Issue by it33** [mattermost/platform#6531]
#### Summary

[Per documentation](https://docs.mattermost.com/administration/config-settings.html#policy) policy controls are part of E10, and a non-functional "Make Channel Admin" option that's part of policy incorrectly displays in TE. 

#### Steps to reproduce
Go to Channel Header > Manage Members > Channel Member 

#### Expected behavior
Only Remove Member as an option 

#### Observed behavior
Make Channel Admin is an option, but it doesn't do anything since policy controls are part of E10 

#### Possible fixes
Remove Make Channel Admin option in TE, leave it available in E10.

There is [a thread started in the Mattermost community server in the feature proposal channel](https://pre-release.mattermost.com/core/pl/s4uun7fum3yo9pxxowkru3effh) on what policy is appropriate for TE vs EE.

**Comment by esethna** [comment]
Attaching JIRA ticket: https://mattermost.atlassian.net/browse/PLT-6724
