### ISSUE TITLE
About the api doc

### ISSUE THREAD

**Issue by af913337456** [mattermost/platform#6541]
hi~~~，i have saw this , [https://api.mattermost.com/#tag/WebSocket](https://api.mattermost.com/#tag/WebSocket) ，but i found that it just show one websocket example about the event (hello). Now I'm trying to rewrite the client interface by using JAVA, so I need all of them. Is there any way I can see all the EVENTS examples?

**Comment by af913337456** [comment]
@cpanato hi~，sorry to disturb you again , will you like to help me for this.

**Comment by canhlinh** [comment]
@af913337456 You can check here https://github.com/mattermost/platform/blob/master/model/websocket_message.go

**Comment by cpanato** [comment]
in the code that @canhlinh point out and also you can take a look in the tests

**Comment by af913337456** [comment]
@canhlinh thanks

**Comment by lindy65** [comment]
Hi @af913337456,

It seems your issue is solved so I'll close this off.  Please feel free to reopen it if you still experience problems.

**Comment by af913337456** [comment]
@lindy65 anyway
