### ISSUE TITLE
[Help Wanted] [PLT-6717] Add duplicate /open command for joining a new channel

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6545]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6717)

Add duplicate /open command for joining a new channel. The /open command should perform the same action as /join.

The autocomplete entry for this command is:

```
/open [channel-name]
Join the open channel
```

**Comment by ccbrown** [comment]
I'll take this one.

**Comment by jasonblais** [comment]
Thanks @ccbrown!
