### ISSUE TITLE
[Help Wanted] [PLT-6716] s/misspelled word/corrected word: Command to correct a typo

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6546]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6716)

s/misspelled word/corrected word: Command to correct a typo

In HipChat you can use s/misspelled/corrected command to correct a misspelled word. It is a popular request from HipChat users migrating to Mattermost.

Example:
1. Post a message: "This is a mesage"
2. Post "s/mesage/message"
Observed: "This is a message" in the channel with "(edited)" indicator

This command won't show up in autocomplete, since it doesn't start with a slash.

**Comment by jasonblais** [comment]
Closing for now. This scenario is specific to HipChat where editing a message is not easily supported.

If anyone wants to see this feature supported, please consider opening a feature proposal for it: https://mattermost.uservoice.com/forums/306457-general/filters/top
