### ISSUE TITLE
We have issues with PLT-5705

### ISSUE THREAD

**Issue by jostyee** [mattermost/platform#6551]
#### Summary
https://github.com/mattermost/platform/pull/6503 creates a global client to deal with http requests, which would make trouble for us in China.

- Many websites are blocked here, so I opened a PR before to specify a http_proxy, which allows the requests fetching OpenGraph data via a server overseas.
- For other http connections, most of them are between intranet servers of ourselves, that shouldn't/can't connect via a proxy(e.g.: GitLab auth server), we don't set http_proxy param for the client.

Since this PR has been merged, we have no way but modify the codes to make mm working again.

#### Possible fixes
If you agree, I can commit a PR again to use a separate httpClient to handle the `GetOpenGraphMetadata` func.

@jasonblais @tjuerge @crspeller @hmhealey

**Comment by tjuerge** [comment]
Ah, that explains why only `app/post.go` got some internet proxy support in #5571.

@jostyee Is the env var [no_proxy](https://www.w3.org/Daemon/User/Proxies/ProxyClients.html) of any help here? It could be used to exclude your intranet servers from proxy and only let requests to the OpenGraph data server go through the proxy.

The method [http.transport.useProxy()](https://golang.org/src/net/http/transport.go) provides the go-lang-specific implementation of the `no_proxy` handling.

**Comment by jostyee** [comment]
Yes, https://github.com/mattermost/platform/pull/5571 was to satisfy our own needs, https://github.com/mattermost/platform/pull/6503 is refactoring to go httpClient usage.

Thank you @tjuerge to point out `no_proxy` env var, I almost forgot it. Certainly I'll add our domains to docker-compose config file, thanks again for helping.
