### ISSUE TITLE
[Help Wanted] [PLT-6715] /help slash command: Open the Mattermost help page

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6554]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6715)

/help slash command: Open the Mattermost help page

Notes:
1. Opens the Help page set in config.json. https://docs.mattermost.com/administration/config-settings.html#help-link. If the field is blank, open the default page (currently https://about.mattermost.com/default-help/)

2. Autocomplete: 
```
/help
Open the Mattermost help page
```

**Comment by cpanato** [comment]
there is PR for this : https://github.com/mattermost/platform/pull/6650 from @kkamdooong

**Comment by jasonblais** [comment]
Thanks @kkamdooong! Closing as resolved
