### ISSUE TITLE
[Help Wanted] [PLT-6714] /settings slash command: Open the Account Settings dialog

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6555]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6714)

/settings slash command: Open the Account Settings dialog

Notes:
1. Autocomplete: 
```
/settings
Open the Account Settings dialog
```

**Comment by ccbrown** [comment]
I'll take this one.

**Comment by coreyhulen** [comment]
Yup @ccbrown it's all yours.
