### ISSUE TITLE
[Help Wanted] [PLT-6713] /search [text] slash command: Search text in messages

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6556]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6713)

/search [text] slash command: Search text in messages

Notes:
1. /search [text] will set focus to the search bar, auto-fill it with [text] and perform the search.

2. Autocomplete: 
```
/search [text] 
Search text in messages
```

**Comment by ccbrown** [comment]
I'll take this one.

**Comment by coreyhulen** [comment]
Yup @ccbrown it's all yours.

**Comment by esethna** [comment]
Thanks @ccbrown! After testing I noticed an issue where if a "/search" is performed in the center pane with the right-hand sidebar closed, the following console error is output:

![image](https://user-images.githubusercontent.com/14333569/27555438-f751d534-5a6e-11e7-8128-f7b8a75612e8.png)

Other than that it looks great!
