### ISSUE TITLE
For posts urls with nested paranthesis do not work

### ISSUE THREAD

**Issue by pjangam** [mattermost/platform#6567]
#### Summary
Urls with nested brackets do not work.
I'm trying to create mattermost post with link to kibana dashboard. Kibana urls do have multiple nested brackets inside it.
For nested bracket hyperlink takes upto first closing bracket inside multipe opening brackets

#### Steps to reproduce
Create a post with nested brackets in it.
e.g.  https://sample_elasticSearch_deployment/app/kibana#/dashboard/test?_g=(time:(from:'2017-09-17T09:33:35.355Z',mode:absolute,to:'2017-09-17T09:43:35.355Z'))

#### Expected behavior
Hyperlink should point to correct url

#### Observed behavior
Broken hyperlink.

#### Possible fixes
I've seen part of this been fixed in https://mattermost.atlassian.net/browse/PLT-2359.
Please check if it can be extended to support this scenario as well.

**Comment by lfbrock** [comment]
Hi @pjangam - what version of Mattermost are you on? 

I think this seems to work for me on master with the example you gave: 
<img width="431" alt="screenshot 2017-06-06 16 01 57" src="https://user-images.githubusercontent.com/9354841/26849281-89c2da7e-4ad1-11e7-9574-6a8ec4fa3ded.png">

**Comment by lindy65** [comment]
Hi @pjangam, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
