### ISSUE TITLE
An error when i run "make run"

### ISSUE THREAD

**Issue by af913337456** [mattermost/platform#6571]
The message below.

[2017/06/04 22:46:32 CST] [DEBG] Cleaning up token store.
[2017/06/04 22:47:02 CST] [DEBG] Cleaning up token store.
[mysql] 2017/06/04 22:48:28 packets.go:33: read tcp 127.0.0.1:40010->127.0.0.1:3306: i/o timeout
[2017/06/04 22:48:34 CST] [EROR] Unable to cleanup token store.
[mysql] 2017/06/04 22:49:09 packets.go:33: read tcp 127.0.0.1:40014->127.0.0.1:3306: i/o timeout
[2017/06/04 22:49:17 CST] [EROR] Unable to cleanup token store.

**Comment by af913337456** [comment]
i did it with that [https://docs.mattermost.com/developer/dev-setup-ubuntu-1604.html](https://docs.mattermost.com/developer/dev-setup-ubuntu-1604.html)

i need your help @cpanato，big deal

**Comment by af913337456** [comment]
i can always see those log below，but when i access ':8065'，i saw this “dial tcp 47.93.197.90:8065: i/o timeout”

[2017/06/04 23:34:14 CST] [INFO] Starting Server...
[2017/06/04 23:34:14 CST] [INFO] Server is listening on :8065
[2017/06/04 23:34:14 CST] [INFO] Starting jobs
[2017/06/04 23:34:14 CST] [DEBG] Cleaning up token stHash: 33dcf205c6ff89f13537                                                                 
Version: webpack 2.5.1
Time: 158642ms
PublicPath: /static/
    + 2614 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
This can impact web performance.
Assets: 
  files/21151ed5a67066748c31b65c85406c7c.png (959 kB)
  i18n/ja.6f7082e96fd9a3347db3ca9462719a73.json (268 kB)
  i18n/ru.b1cc1acdf81a5fcad34d264e1f5b603e.json (309 kB)
  0.213eecbc3952ade8fedf.js (3.66 MB)
  1.cd22933823fca7c5145a.js (1.6 MB)
  2.895cb4d416b2d7b781ff.js (397 kB)
  5.8a80b61bfac36977c2d8.js (7.6 MB)
  6.302655694eee2baa391a.js (9.82 MB)
  7.38ccf496ecd7b6d2f101.js (6.71 MB)
  8.21f512ad1e9f9633c6fa.js (6.46 MB)
  9.5c6d9b0752ef493afbdd.js (2.27 MB)
  10.cc91a34ac4971e1e314c.js (2.01 MB)
  11.687ee4aab7e064d6677b.js (1.99 MB)
  12.13ef13a205e050149345.js (1.98 MB)
  13.42a69ac8d0cff4d8cf4d.js (2.16 MB)
  14.309c05a85d33e49c6832.js (1.94 MB)
  15.2a269df847da61ac4a32.js (1.93 MB)
  16.25e60b4e5da4cc2f20ac.js (1.71 MB)
  17.19db06751390ab4ea29a.js (1.7 MB)
  18.5d36349d9c686a970399.js (1.6 MB)
  19.2eaffef07df763a76d33.js (3.4 MB)
  20.927bd0e5338ea6518ced.js (2.95 MB)
  21.8b83c1040d86dbf4c027.js (2.96 MB)
  22.bdcf51ca53974536fcea.js (2.97 MB)
  23.7e80d2c4751be32be793.js (2.95 MB)
  24.a25e7064a396d3e05fc4.js (2.95 MB)
  25.4a78421614cdf4ea91b5.js (2.96 MB)
  26.b906b15814110d428fa1.js (2.96 MB)
  27.34e631a4e1c2bde7cf80.js (596 kB)
  28.2f501f3ef08a6bd96484.js (428 kB)
  29.e7def13c8f264abefdff.js (361 kB)
  30.24ad21e227f6515cf326.js (320 kB)
  31.33b34edac0c08648f409.js (321 kB)
  32.bda3e44dc54d4dad6160.js (1.27 MB)
  39.2a86430cb98dbc6caa61.js (257 kB)
  53.cde26af843ea10da5164.js (3.39 MB)
  main.33dcf205c6ff89f13537.js (13.6 MB)
  emoji/emojilarge.png (4.25 MB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
Entrypoints:
  main (13.6 MB)
      main.33dcf205c6ff89f13537.js

Child html-webpack-plugin for "root.html":
    PublicPath: /static/
        + 13 hidden modules

**Comment by af913337456** [comment]
@canhlinh

**Comment by jasonblais** [comment]
@af913337456 can you first read these troubleshooting notes in the developer machine setup guide? https://docs.mattermost.com/developer/dev-setup-troubleshooting.html

**Comment by af913337456** [comment]
@jasonblais  hi，I've tried it on your way. Is that normal ?

root@iZ2zedkbtajgf3c8o91wy0Z:~/go/src/github.com/mattermost/platform# make run-server
Starting docker containers
restarting mattermost-mysql
restarting mattermost-postgres
restarting mattermost-inbucket
Running mattermost for development
mkdir -p ./webapp/dist/files
go run  -ldflags "-X github.com/mattermost/platform/model.BuildNumber=dev -X 'github.com/mattermost/platform/model.BuildDate=Mon Jun  5 03:35:29 UTC 2017' -X github.com/mattermost/platform/model.BuildHash=14f47f569fdc00124913a7ea513ebea684393396 -X github.com/mattermost/platform/model.BuildHashEnterprise=none -X github.com/mattermost/platform/model.BuildEnterpriseReady=false" ./cmd/platform/*.go --disableconfigwatch &
root@iZ2zedkbtajgf3c8o91wy0Z:~/go/src/github.com/mattermost/platform#

**Comment by af913337456** [comment]
root@iZ2zedkbtajgf3c8o91wy0Z:/go/src/github.com/mattermost/platform# make run-server
Starting docker containers
restarting mattermost-mysql
restarting mattermost-postgres
restarting mattermost-inbucket
Running mattermost for development
mkdir -p ./webapp/dist/files
go run -ldflags "-X github.com/mattermost/platform/model.BuildNumber=dev -X 'github.com/mattermost/platform/model.BuildDate=Mon Jun 5 03:35:29 UTC 2017' -X github.com/mattermost/platform/model.BuildHash=14f47f569fdc00124913a7ea513ebea684393396 -X github.com/mattermost/platform/model.BuildHashEnterprise=none -X github.com/mattermost/platform/model.BuildEnterpriseReady=false" ./cmd/platform/*.go --disableconfigwatch &
root@iZ2zedkbtajgf3c8o91wy0Z:/go/src/github.com/mattermost/platform#

**Comment by af913337456** [comment]
@jasonblais the message above，please do me a favour.

**Comment by lindy65** [comment]
Hi @af913337456, 

Could you help clarify whether you have followed the [Developer Machine Setup Guide](https://docs.mattermost.com/developer/dev-setup.html#developer-machine-setup)?  If so, is your issue not resolved by checking the [troubleshooting guide](https://docs.mattermost.com/developer/dev-setup-troubleshooting.html)?

**Comment by af913337456** [comment]
@lindy65  ‘ troubleshooting guide ’. i did，but it doesn't work for me.

**Comment by af913337456** [comment]
@jasonblais

**Comment by cpanato** [comment]
try to set in your bashrc or zshrc or other the `ulimit -n 8096` and then restart your terminal and try again

**Comment by af913337456** [comment]
@cpanato  when i input the 'ulimit -n' 

root@iZ2zedkbtajgf3c8o91wy0Z:~# ulimit -n
8096

it that OK ?  I haven't entered yet

**Comment by cpanato** [comment]
yes

**Comment by af913337456** [comment]
@cpanato  the error still exist , i still can not access ':8065'，for example，when i access this 'myServerId:8065/api/v4/users/login'，it tells me ‘ERR_CONNECTION_TIMED_OUT’.

**Comment by cpanato** [comment]
try:
make stop
make clean
make run


but before all sync your repo with latest master

**Comment by af913337456** [comment]
@cpanato  i did it all，the last output information for the screen below. but i still can not access ':8065'，the same result above 'ERR_CONNECTION_TIMED_OUT' .

[2017/06/06 18:14:15 CST] [DEBG] Initializing system WebSocket API routes
[2017/06/06 18:14:15 CST] [DEBG] Initializing status WebSocket API routes
[2017/06/06 18:14:15 CST] [DEBG] wsapi.webtrc.init.debug
[2017/06/06 18:14:15 CST] [INFO] Starting 2 websocket hubs
[2017/06/06 18:14:15 CST] [DEBG] Initializing web routes
[2017/06/06 18:14:15 CST] [DEBG] Using client directory at /root/go/src/github.com/mattermost/platform/webapp/dist/
[2017/06/06 18:14:15 CST] [DEBG] Hub for index 0 is starting with goroutine 1993
[2017/06/06 18:14:15 CST] [DEBG] Hub for index 1 is starting with goroutine 1994
[2017/06/06 18:14:15 CST] [INFO] Starting Server...
[2017/06/06 18:14:15 CST] [INFO] Server is listening on :8065
[2017/06/06 18:14:15 CST] [INFO] Starting jobs
[2017/06/06 18:14:15 CST] [DEBG] Cleaning up token store.

**Comment by af913337456** [comment]
@cpanato  I'm afraid I'm going to be fired by my boss. I was originally a Android developer.

**Comment by af913337456** [comment]
@cpanato Is there any other way?

**Comment by cpanato** [comment]
what happens if you open the browser and go to localhost:8065 ?

**Comment by af913337456** [comment]
![qq 20170606203018](https://cloud.githubusercontent.com/assets/10436277/26829174/0c8668ca-4af7-11e7-8fe2-b55a25d33692.png)

@cpanato

**Comment by af913337456** [comment]
![qq 20170606203018](https://cloud.githubusercontent.com/assets/10436277/26829244/5a410804-4af7-11e7-8cd9-9f88277ffaf9.png)

@cpanato   it means time out

**Comment by cpanato** [comment]
Are you running the server on another machine or in your local? if you are running in another machine check the firewall (or if is on AWS check the security groups)

I cannot help much since I don't have enough information about your environment.

**Comment by af913337456** [comment]
I run it on Aliyun server, which can be accessed by public network. i have shut down the firewall by use 'ufw'，and make '8065' accessible，but nothing change . 

my linux server os info below：
Linux iZ2zedkbtajgf3c8o91wy0Z 4.4.0-63-generic #84-Ubuntu SMP Wed Feb 1 17:20:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linu

**Comment by af913337456** [comment]
@cpanato

**Comment by af913337456** [comment]
@cpanato  I've tried those golang code below，when i access 'ip:8889'，i got a same result ---- access timeout

```go
package main

import (
	"fmt"
	"github.com/gorilla/mux"
	"net/http"
)

func test(w http.ResponseWriter, req *http.Request) {
	fmt.Print(w, "hello")
}

func getRouter() *mux.Router {
	r := mux.NewRouter()
	r.HandleFunc("/a", test)
	return r
}

func listenHttp(port string, r *mux.Router) {
	fmt.Println(http.ListenAndServe(port, r))
}

func main() {
	listenHttp(":8889", getRouter())
}

```

**Comment by af913337456** [comment]
@cpanato  i do also use this cmd 'iptables -I INPUT -p tcp --dport 8889 -j ACCEPT'，nothing change.

**Comment by af913337456** [comment]
@cpanato thank you so much! I just fix this

**Comment by cpanato** [comment]
I did nothing.
glad that works
