### ISSUE TITLE
[Help Wanted] [PLT-3379] "Commented on" username should respect the teammate name display

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6573]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3379)

"Commented on" username should respect the teammate name display set in Account Settings > Display > Teammate Name Display, similar to elsewhere in the UI. 

Sometimes the usernames and first/lastname or nickname are not very similar leading to confusion. 

![image](https://cloud.githubusercontent.com/assets/13119842/26765693/4aa48a64-494f-11e7-99bf-edad2b47116f.png)

![image](https://cloud.githubusercontent.com/assets/13119842/26765696/4fa4c560-494f-11e7-8581-3202afed4ebb.png)

NOTE: Post view has a major refactoring of the code base here: https://github.com/mattermost/platform/pull/6501. It's recommended to base new changes to that branch or wait until the pull request is merged.

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6684
