### ISSUE TITLE
[Help Wanted] [PLT-5747] Fix UI on-hover, tooltip, and active state inconsistency for buttons

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6591]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5747)

Propose fixing [inconsistent On-Hover Highlight, Tooltip, and Active State UI buttons, in particular

1 - LHS Team Sidebar

![image](https://cloud.githubusercontent.com/assets/13119842/26831812/6ee8d3e2-4a9b-11e7-82e1-18975f18890f.png)

Current: Tooltip only
Expected: On-hover highlight

2 - LHS Main Menu

![image](https://cloud.githubusercontent.com/assets/13119842/26831820/78f12a42-4a9b-11e7-8437-8c335cd6cc75.png)

Current: The whole top left area is an active state. However, there is no tooltip when hovering over the three-dotted menu
Expected: Tooltip "Main Menu" when hovering over the three dots.

3 - Channel Heading Channel Menu

![image](https://cloud.githubusercontent.com/assets/13119842/26831876/a47f43ec-4a9b-11e7-9248-f43f42bbfdfc.png)

Current: No active state
Expected: On-hover highlight and active state when clicked

4 - Channel Heading Favorite Button

![image](https://cloud.githubusercontent.com/assets/13119842/26831892/b286b4ca-4a9b-11e7-8b2b-e010571839e1.png)

Current: Tooltip only
Expected: On-hover highlight (similar to flag icon on the right side) with the tooltip.

5 - Channel member icon

![image](https://cloud.githubusercontent.com/assets/13119842/26831920/c2eb6130-4a9b-11e7-803f-f06740c0ce97.png)

Current: No active state
Expected: On-hover highlight (similar to flag icon on the right side), tooltip `Channel Members` and active state when clicked (similar to flag icon on the right side).

6 - Theme Template

![image](https://cloud.githubusercontent.com/assets/13119842/26831940/db8bf93e-4a9b-11e7-8ac8-74be65bde916.png)

Current: No active state
Expected: On-hover effect when hovering over the default themes with your mouse.

7 - Invite New Member Add Button

![image](https://cloud.githubusercontent.com/assets/13119842/26831964/f204e234-4a9b-11e7-8c88-cb90632e46dc.png)

Current: No active state
Expected: On-hover effect with an underline, similar to a link

![image](https://cloud.githubusercontent.com/assets/13119842/26831982/fdf25b12-4a9b-11e7-8b67-fbd9156dba95.png)

**Comment by jasonblais** [comment]
@cpanato this could be an interesting project for you - I think you were looking for some introductory React tickets around the UI.

**Comment by sudheerDev** [comment]
Is this issue up for grabs?.

**Comment by jasonblais** [comment]
It is! Would love your help @sudheerDev, let us know if there are any questions.

**Comment by sudheerDev** [comment]
@jasonblais Sounds Great!. will get on it right away.
