### ISSUE TITLE
[Help Wanted] [PLT-6744] Add "Only visible to you" note for ephemeral messages

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6594]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6744)

Add "Only visible to you" note at the end of ephemeral messages,.

See screenshot for an example of the ephemeral message that would be posted after "/away"

![image](https://user-images.githubusercontent.com/13119842/26844664-2f465846-4ac2-11e7-8c6f-3baac15714e5.png)

**Comment by cpanato** [comment]
will try that.

**Comment by cpanato** [comment]
I think this can be closed
