### ISSUE TITLE
Why add the source code of modules js in production?

### ISSUE THREAD

**Issue by jostyee** [mattermost/platform#6613]
For feature requests, please see: http://www.mattermost.org/feature-requests/.
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format:

#### Summary
https://github.com/mattermost/platform/blob/master/webapp/webpack.config.js#L288

I removed source bundled & rebuilt my Docker image, the file size reduced from 267MB to 151MB, and your Mattermost releases don't include them neither.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by lindy65** [comment]
Hi @jostyee,

Thank you for your feedback,

Am I understanding correctly that you don't want source maps included so you can save space?

Source maps are not retrieved by the client unless the dev tools are open.

**Comment by jostyee** [comment]
@lindy65 So why ppl debug in production mode? According to the Makefile, it already defines a dev mode to do this work.

The problem is these files doubles the size of the packed image, which is unnecessarily wasting disk space and slowing down release phase.

**Comment by lindy65** [comment]
Hi @jostyee,

In answer to your question, from one of our devs, we debug in production so when people come to us for support we can give them better answers. It does not slow down the released version at all. 

Does that help?

**Comment by jostyee** [comment]
Nope, when I said slow down I didn't mean users' browser performance, & I don't agree with your debugging way in production.
I've modified the Makefile by myself locally to workaround it.
