### ISSUE TITLE
Mattermost v3.9.0 doesn't work in old browsers (Firefox ESR 45)

### ISSUE THREAD

**Issue by tohn** [mattermost/platform#6641]
#### Summary
Mattermost v3.9.0 doesn't work in old browsers, for example [Firefox ESR 45.9.0](https://www.mozilla.org/en-US/firefox/organizations/all/). It just shows three loading dots.

#### Steps to reproduce
* Install Firefox ESR 45.9.0 (operating system doesn't matter, we tested on macOS 10.6, macOS 10.8, Windows 8.1 and Arch Linux)
* Open Mattermost in this browser (Version should be 3.9.0 behind a nginx with the breaking change `location ~ /api/v[0-9]+/(users/)?websocket$ {` already included)

#### Expected behavior
Mattermost should work as before with Version 3.8.3 and without the line change in nginx.

#### Observed behavior
We see only three loading dots in the browser. In the console of Firefox ESR we can see this:
```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create main.8df02c283d1e91c670ac.js:1:2853852
jQuery.Deferred exception: window.mm_config is null n@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:1401171
E._constructComponentWithoutOwner@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2740152
E._constructComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2740014
E.mountComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2739189
o<.mountComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:449351
E.performInitialMount@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2740972
E.mountComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2739855
o<.mountComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:449351
E.performInitialMount@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2740972
E.mountComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2739855
o<.mountComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:449351
E.performInitialMount@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2740972
E.mountComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2739855
o<.mountComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:449351
E.performInitialMount@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2740972
E.mountComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2739855
o<.mountComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:449351
i@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:1001684
o.perform@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:547649
s@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:1001905
o.perform@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:547649
p.batchedUpdates@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:2765851
o@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:358858
j._renderNewRootComponent@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:1003183
j._renderSubtreeIntoContainer@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:1004168
j.render@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:1004295
o@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:1074462
n/<@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:1073280
ve.Callbacks/l@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:42265
ve.Callbacks/u.fireWith@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:43036
o/</u@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:44292
o/</c<@https://mattermost.example.org/static/main.8df02c283d1e91c670ac.js:1:44339
 undefined main.8df02c283d1e91c670ac.js:1:45617
```

#### Possible fixes
Despite updating the software, is there maybe a workaround in nginx or is the problem in platform itself?

**Comment by lindy65** [comment]
Hi @tohn,

Thanks for your report,

We have a [ticket](https://mattermost.atlassian.net/browse/PLT-6650) open to investigate this.

You can also take a look at [this conversation](https://github.com/mattermost/platform/issues/6428) about ESR 45.

**Comment by tohn** [comment]
Thanks a lot, I didn't find this ticket as I searched for similar issues ..
Since the bug is fixed in 3.10, I'll close this issue here, thanks :)

**Comment by tohn** [comment]
Ok, I didn't see, that there was just an adjustment of the requirements ...
Is there another solution to this? Maybe even the nginx line?
Otherwise: could you also include this to the known list of bugs or the breaking change? Maybe it will help others to wait for a fix before upgrading ...

**Comment by jasonblais** [comment]
@tohn Firefox ESR 45 had an [end-of-life scheduled for June 13](https://en.wikipedia.org/wiki/Firefox_version_history), so we're recommending to upgrade to Firefox ESR 52, which is the next version.

Do you have plans to migrate over to Firefox 52 ESR or will this continue to be an issue for your users?

PS: I 100% agree this should have been noted in the changelog. This is our fault, and I've submitted an update here: https://github.com/mattermost/docs/pull/1262. Sorry for the inconvenience.

**Comment by lindy65** [comment]
Hi @tohn,

The PR that @jasonblais did has been merged so the docs have been updated to reflect the update.

I'll close this issue off for now.
