### ISSUE TITLE
Unable to create users through API as admin if server is closed

### ISSUE THREAD

**Issue by jkae** [mattermost/platform#6644]
#### Summary
Admin users are not able to sign other users up in a closed Mattermost server via the API in **3.9.0**

#### Steps to reproduce
1. Navigate to `/admin_console/security/sign_up` and ensure `Enable Open Server` is false
2. Log in as admin user through the api through `/api/v3/users/login`
3. Create a new user account with `/api/v3/users/create` using admin token as authorization
4. Attempt to log in as new user
5. Ensure `Enable Open Server` is true
6. Repeat 2-4

#### Expected behavior
One would expect that an admin user is able to create new users through the API. After all, they are able to generate invites in the first place.

#### Observed behavior
After creating a new user through the API, I was unable to log in with the login/password I provided. I checked the users table inside the database, and noted that a new user was not actually created.

#### Possible fixes
`api/user.go:87-93` indicates 3 modes of creation: hash, invite ID, and self-signup. This is potentially a situation where creation-with-hash is assumed, but the API documentation does not indicate how this would be achieved. If not, perhaps check if an admin user is auth'd for the call?

**Comment by jasonblais** [comment]
@jkae if you navigate to `.../admin_console/general/users_and_teams`, what is the `Enable Account Creation` set to?

**Comment by jkae** [comment]
It is set to `true`.

**Comment by saturninoabril** [comment]
The observed behavior is expected at the moment.
Yes, there are 3 modes in creating a user. In your case, if there's no hash or invite id, then it will go thru `CreateUserFromSignup` where `EnableSignUpWithEmail`, `EnableUserCreation` and `EnableOpenServer` are required to be all true. You should receive an error whenever user creation failed.
Hash and invite id are generated from Mattermost server using admin credential. However, API call with these generated links do not require admin credential itself.

**Comment by jkae** [comment]
Thank you for the update. Is there any consideration for this feature? Possibly with E10 if not Team Edition? It would be useful for integrating Mattermost into other applications.

To note, I had some initial confusion about this because -- if `EnableOpenServer` is `false` but all other required options are `true` -- Mattermost responds with User JSON as if the creation was successful. I'm going off my memory here, but I can test it again.

**Comment by saturninoabril** [comment]
I missed to mention that it is the implementation at v3 API. Please try again your steps with v4 API where we give System Admins more power and let us know your observation.
See v4 API at https://api.mattermost.com/v4/#tag/users%2Fpaths%2F~1users%2Fpost

**Comment by lindy65** [comment]
Hi @jkae, have you resolved your issue with v4 API?

**Comment by lindy65** [comment]
Hi @jkae, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by jkae** [comment]
Sorry, I was unable to test this until now. I will get back to you soon and report whether or not the issue still exists.

**Comment by lindy65** [comment]
Glad to hear it @jkae :)  Thanks for letting us know!
