### ISSUE TITLE
[Help Wanted] [PLT-6842] User's role does not update in their client until the page is refreshed

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6645]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6842)

Repro: 
1. User A makes User B team admin (or switched to any other role, eg demote from Team Admin to Member)
2. Observe User B's Main menu 

Observed: 
User B's menu options do not update to show Team Settings until after refresh. 

If it's the reverse and User B is switched from Team Admin to member, they still see the Team Settings until refresh but get a permissions error if they try to change anything. 

Expected: 
User B should see updated menu options / permissions when the role gets changed (pushes a websocket event)

**Comment by fraziern** [comment]
I can take a look at this.

**Comment by jasonblais** [comment]
Thanks @fraziern! Glad to still have you around :)
