### ISSUE TITLE
Incomming webhook containing url with parameters gives 400 response

### ISSUE THREAD

**Issue by computerlove** [mattermost/platform#6652]
#### Summary
When posting to a webhook with a message containing a url with `&` query parameters the response is 400.

#### Steps to reproduce
Post the following message to a `webhook:`
`{"attachments": [{"fallback":"fallback","title":"webhook","text":"this is a url: http://www.domain.no/a/b/105?egenskap=asda&fylke=12\nHTTP[500] Error[Code=(5001)"}], "username": "PROD"}`

#### Expected behavior
The webhook content appears in it's channel.

#### Observed behavior
The log says:

> app_1  | [2017/06/15 11:17:54 CEST] [DEBG] /hooks/kcaruoo17fgn8g8zgu8jddq5be
> app_1  | [2017/06/15 11:17:54 CEST] [DEBG] Incoming webhook received. Content={"attachments": [{"fallback":"fallback","title":"webhook","text":"this is a url: http://www.domain.no/a/b/105?egenskap=asda
> app_1  | [2017/06/15 11:17:54 CEST] [EROR] /hooks/kcaruoo17fgn8g8zgu8jddq5be:HandleIncomingWebhook code=400 rid=dfyqq81satb1td4t45n7fjq8je uid= ip=172.21.0.1 Unable to parse incoming data [details: ]

#### Possible fixes
Is this something in `decodeIncomingWebhookRequest` or json decoding, or should I escape something?

**Comment by enahum** [comment]
Hey @computerlove can you share your server version? cause this is working for me on a 3.8+ server

**Comment by computerlove** [comment]
The server is 3.9.0.

**Comment by enahum** [comment]
have you set the `Content-type` to `application/json` in the header?

as you can see in the attached image is working just fine for me
![image](https://user-images.githubusercontent.com/6757047/27186736-3d98c068-51b7-11e7-859e-f956d3099b77.png)

**Comment by computerlove** [comment]
Sorry, my reproduction step was wrong. I was using `payload=JSONPAYLOADHERE` and `x-www-form-urlencoded`. 

When posting the just json as `application/json` it works.

**Comment by lindy65** [comment]
Thanks @computerlove, 

Glad your issue is solved.  I'll close this off for now...
