### ISSUE TITLE
Getting issue "You do not have appropriate permissions"  when a member is sending a new private message to anyone in team.

### ISSUE THREAD

**Issue by kailashverma2402** [mattermost/platform#6653]
#### Summary
Getting issue "You do not have appropriate permissions"  when a member is sending a new private message to anyone in team.

#### Steps to reproduce
using version 3.5.1

#### Mattermost setup details : using matermost in docker, deployed this in ECS cluster. System admin is able to access everything and send messages, but other members are getting this issue frequently.

screenshot mentioned below : 
![image](https://user-images.githubusercontent.com/21259290/27175753-d35e33be-51dd-11e7-8246-0a7e3adaa631.png)

**Comment by lindy65** [comment]
Hi @kailashverma2402,

Thanks for your feedback,

Could we have your help upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost to see whether the issue still persists?

**Comment by kailashverma2402** [comment]
@lindy65 Have upgraded the mattermost, will monitor this for some time. 
I am still getting few issues like :  Messages are not getting delivered, we have to refresh desktop application to get the new messages, whereas on mobile i am not getting any issues. 
The version of Application is : 3.7.0

**Comment by lindy65** [comment]
Hi @kailashverma2402,

Thank you for your feedback,

Regarding the "You do not have the appropriate permissions" error, can you let me know what your System Console > Users and Teams > Restrict Direct Messages to is set to? 

For the missing messages, can you try the [troubleshooting docs for WebSocket connections](https://docs.mattermost.com/install/troubleshooting.html#please-check-connection-mattermost-unreachable-if-issue-persists-ask-administrator-to-check-websocket-port)? Even though you don't get a blue bar message about it, it sounds like it might be WebSocket-related. 

Thanks!

**Comment by lindy65** [comment]
Hi @kailashverma2402,

It seems your issue is resolved or no longer reproduces for you.  I'll close this off for now but feel free to reopen if you still experience problems.

Thanks!
