### ISSUE TITLE
email api fails silently

### ISSUE THREAD

**Issue by funkyfuture** [mattermost/platform#6658]
#### Summary
though i posted this [as a support request](https://forum.mattermost.org/t/sending-a-verification-email-fails-silently/3400), i realized that silently failing when trying to send an email is a bug.

this affects at least Mattermost 3.9.0 and 3.10.0.

#### Steps to reproduce
- configure a nonsense smtp host name
- trigger the sending of an email

#### Expected behavior
- a message at error level that explains that sending an email failed and why that happened

#### Observed behavior
currently Mattermost logs the following:

```
[2017/06/14 14:52:51 UTC] [EROR] /api/v4/users/login:Login code=401 rid=x5xx7745r7druy9qcwqtpxfxca uid= ip=1.2.3.4 Login failed because email address has not been verified [details: user_id=jkef95yhginwx84yajduk6ywza]
[2017/06/14 14:52:53 UTC] [DEBG] POST - /api/v4/users/email/verify/send
```

while the proxy also logs no error:
```
1.2.3.4 - - [14/Jun/2017:16:52:53 +0200] "POST /api/v4/users/email/verify/send HTTP/1.1" 200 421 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36"
```

furthermore the `platform user invite` command's output is something that i hope an intern placed there:

    Invites may or may not have been sent.

in my case this hinders me to troubleshoot a problem that emails are not send, and thus to deploy Mattermost for the folks.

**Comment by esethna** [comment]
Thanks @funkyfuture, totally agree with you, I've created a ticket to [track in JIRA](https://mattermost.atlassian.net/browse/PLT-6910).

**Comment by funkyfuture** [comment]
```
[2017/07/26 15:40:46 UTC] [DEBG] POST - /api/v4/users/email/verify/send
[2017/07/26 15:40:46 UTC] [DEBG] /should_verify_email
[2017/07/26 15:40:46 UTC] [DEBG] GET - /api/v4/config/client
[2017/07/26 15:40:47 UTC] [DEBG] GET - /api/v4/license/client
```

is still get no useful output (as above) when i define a nonsense imap host with release 4.0.1 and hit the "Resend Email" button in the application's frontend:

```
Version: 4.0.0
Build Number: 4.0.1
Build Date: Wed Jul 26 13:45:57 UTC 2017
Build Hash: a350f4dc0754e1aeabb64bd712ce05f7c59cfa60
Build Enterprise Ready: false
DB Version: 4.0.0
```

also, i get the same reply as noted initially when using the cli.

i would appreciate if the communication would be more transparent, eg. by referencing the solving coomit when closing an issue.

at the moment i feel somewhat ridiculed, but hey, probably this is agile at its best - meaning it may rather be caused a systemic issue.
