### ISSUE TITLE
[Help Wanted] [PLT-6847] If a message starts with a / but is not a slash command, put the text back in the input box when it fails to send

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6659]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6847)

Repro: 
1. Send a message "/path/to/directory and a nice message" 

Observed: You get an error saying it's not a slash command, and the message disappears. (Very bad experience for the user since they lose everything they just typed). 

Proposed change: 

1. Change the error message to say: Command with a trigger of 'path/to/directory' not found. To send a message beginning with "/", try adding an empty space at the beginning of the message."

2. Put the message back in the text box after it fails to send, so the user doesn't lose everything they've typed

Report: https://github.com/mattermost/platform/issues/6646

**Comment by cpanato** [comment]
@lfbrock 
one question, what should be the message when the user try to run a slash command but it not exists?
this case you mentioned is ok, but if the user tries to run a `/myslash` and it does not exist the message should be the existing one, right? 

how to differentiate those?

thanks

**Comment by charles-passille-smartnets** [comment]
@cpanato 
I have two suggestions:

1. Return the `/myslash` to the input field and then you have to delete the invalid command, this is preferable in the case where `/myslash` *exists* but you accidently typed `/myslahs` . You can just fix the typo instead of retyping everything.

2. Alternatively, you could have the input field return empty as it is the case right now, but add a "Copy to clipboard" button on the blue notification when your command is invalid (in the case where you typed a long message and it got deleted...

**Comment by jasonblais** [comment]
@cpanato I think `Command with a trigger of 'path/to/directory' not found. To send a message beginning with "/", try adding an empty space at the beginning of the message.` works for that case too?

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6695
