### ISSUE TITLE
Town-square channel view member info GUI bug

### ISSUE THREAD

**Issue by fasterforward** [mattermost/platform#6668]
#### Summary
Town-square channel - view members screen renders an empty option list when clicking on Channel Member option

#### Steps to reproduce
As a System Administrator:

1. Click on the town-square channel
2. Navigate to the View Members
3. Click on Channel Member option at one of the added members

#### Observed behavior
![image](https://user-images.githubusercontent.com/10937975/27229451-f3fe3e06-52ab-11e7-8a34-ed8c09d8f4d6.png)

**Comment by jasonblais** [comment]
Thanks @fasterforward for the report! I've created a bug ticket here: https://mattermost.atlassian.net/browse/PLT-6865

**Comment by lindy65** [comment]
Hi @fasterforward, 

I'll close this off now as the fix in the above ticket has been merged.
