### ISSUE TITLE
PLT-41 Automatically convert uppercase letters to lowercase in username input box

### ISSUE THREAD

**Issue by Trozz** [mattermost/platform#667]
_This is for a discussion on the best method to proceed with this change._

Currently Mattermost prompts with an error if users enter a username with uppercase letters, this is checked in the [model/user.go](https://github.com/mattermost/platform/blob/5f1bd7e9acf3bce3cffbc2263caa4ca8f39f6c6a/model/user.go#L345-361) file.

There are two methods I can imagine implimenting this change
 - Sliently changing the username to lowercase and proceeding to next page (create password)

 -  Update the username visually for the user while remaining on the page but inform them that the user name has been changed to lowercase (assuming no other issues)

This would mean that we can ultimately remove the lowercase enforcement from the users view.

Opinions wanted :thought_balloon:

**Comment by it33** [comment]
Good question, per the "forgiving" principle (http://www.mattermost.org/design-principles/) I'd propose silently converting the username to lowercase and proceeding, and also removing lowercase enforcement from users view. 

When the user sees their name in lowercase after sign-up, it would be obvious that a conversion happened.

In my mind, this approach seems better than other options--such as validating with an error and doing the conversion there (gives user unnecessary work), or dynamically transforming uppercase letters to lower case letters as the user typed (chance of causing user confusion).

**Comment by Trozz** [comment]
PR #674
