### ISSUE TITLE
Channel header textarea in popup does not refresh when editing by clicking the link "Set a Header" 

### ISSUE THREAD

**Issue by fasterforward** [mattermost/platform#6674]
#### Summary
Old channel header text does not refresh when editing a channel header by clicking the link "Set a Header" 

#### Steps to reproduce
As a system administrator

1) Click on a channel with an existing header and scroll to the very beginning of the channel (or just create a new channel)
2) Click on the option "Set a Header" (at the start of the channel, where it was created)
3) Edit the header to e.g. from "Support to "Development"
4) Header refreshes
5) Click again on the option "Set a Header"
6) The textarea shows the old value "Support" where there should have been the new value "Development" 

Note: This behavior does not occur when you edit the header through the option "Edit channel header" 

#### Expected behavior
The expected result in step 6 is that the textarea shows the text that was set in step 3

#### Observed behavior (that appears unintentional) 
The header popup textarea does not "refresh" when clicking on the option "Set a Header"

**Comment by lindy65** [comment]
Hi @fasterforward,

Thank you for your feedback,

Could you tell me what version of Mattermost you have installed? 

I am not able to reproduce your issue on the latest master.  If you haven't already, could we have your help upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost?

**Comment by fasterforward** [comment]
We're using version 3.10.0

**Comment by lindy65** [comment]
Ah, I see it now, thanks @fasterforward!  I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-6881) to fix the issue.

**Comment by lindy65** [comment]
Hi @fasterforward,  

FYI, this issue doesn't repro on our nightly build server so it seems the issue is fixed and will ship with v4.0 on July 16th.
