### ISSUE TITLE
3.10.0 - reset_password_complete?code=xxx fails with "Invalid code parameter"

### ISSUE THREAD

**Issue by SjonHortensius** [mattermost/platform#6689]
#### Summary
Reset password fails with "Invalid code parameter".

#### Steps to reproduce
Request password reset; attempt to submit new password. This seems to work in Chrome, but not in Firefox (54.0).

#### Possible fixes
Might be caused by https://github.com/mattermost/platform/blob/2bbedd9def2a782f370fb5280994ea0ecbf8a7c7/webapp/components/password_reset_form.jsx#L48 using `this.props.location.query.token`; the submitted POST contains only  a `new_password` property; no `code` or `token` in the json.

If I change the URL to `?token=xxx` the `code` will get sent but the backend still rejects it with the same error

**Comment by cpanato** [comment]
I did the flow to reset the password using the current `master` and did not have any issues.

**Comment by SjonHortensius** [comment]
Right; I should have included a version.

**Comment by cpanato** [comment]
can you clarify better the steps to reproduce?

**Comment by SjonHortensius** [comment]
Yes; it might be Firefox specific as it seems to work in Chrome.

**Comment by SjonHortensius** [comment]
This was caused by a reset-mail send from 3.9 (which uses `?code`) to an installation that switched to 3.10 (which uses `?token`)

Fixed
