### ISSUE TITLE
Search doesn't work with the content of gitlab integrations comment

### ISSUE THREAD

**Issue by philjak** [mattermost/platform#6692]
#### Summary
Search on channel doesn't work with the content of gitlab comments, which will be posted into a channel via internal webhook.

#### Steps to reproduce
- Create a gitlab integration to a channel
- Create a issue/comment
- Search for a word within this comment

#### Expected behavior
Search should show also gitlab integration posts, that contain the searched word.

#### Observed behavior (that appears unintentional) 
Search doesn't show a specific gitlab integration post, that contains the searched word.

Thanks!

**Comment by lindy65** [comment]
Hi @philjak,

Could you tell me which version of Mattermost you are using?

**Comment by philjak** [comment]
Hi @lindy65,

we're using Mattermost Enterprise 3.10. 

Thanks.

**Comment by lindy65** [comment]
Thanks @philjak,

There are a couple of tickets open where search fails when the database is a Postgres one - not sure what database you have?
https://mattermost.atlassian.net/browse/PLT-5390
https://mattermost.atlassian.net/browse/PLT-5471

If that is not the issue, we are working on improving search and you can track the epic ticket [here](https://mattermost.atlassian.net/browse/PLT-5472)

**Comment by philjak** [comment]
Hi @lindy65,

for your information: We're using postgresql as well.

But it's not exact the same problem like the other postgresql bugs, because the search doesn't show any results no matter what you search (even a single word).

Thanks for looking into this!

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track it with the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6908)
