### ISSUE TITLE
[Help Wanted] [PLT-6882] Incorrect feedback message when using slash command "/invite people" and "enable account creation" is set to "false"

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6698]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6882)

Incorrect feedback message when using slash command "/invite people" and "enable account creation" is set to "false".

See this forum issue: https://forum.mattermost.org/t/enableusercreation-false-disables-user-invites-for-all-roles/3414

Repro:
1) Go to System Console > Users and Teams, and set `Enable Account Creation` to `false`
2) Go back to a Mattermost team
3) Post `/invite_people test@test.com`

Observed: Email invite sent. User then tries to create an account but gets an error because account creation is disabled.
![image](https://user-images.githubusercontent.com/13119842/27355812-51f880e4-55da-11e7-9bd2-00287ae9128e.png)

Expected: `User creation has been disabled on this server. Please speak to your administrator.` ephemeral message is posted (system message that only you see). Email invite not sent.

**Comment by moonmeister** [comment]
@jasonblais I'll take this.

**Comment by jasonblais** [comment]
Thanks @moonmeister! Closing
