### ISSUE TITLE
Certain uses of API can result in anomalous flagged post list

### ISSUE THREAD

**Issue by aisamanra** [mattermost/platform#6715]
#### Summary
It is possible (via direct usage of the API) to have a post which does not appear to be flagged (i.e. which lacks the blue flag icon) but nonetheless appears in the flagged post list.

#### Steps to reproduce
Reproduced on both v3.8 and v3.9 with a POST request to `/api/v3/preferences/save` as described below.

#### Expected behavior
Posts are flagged using the `/api/v3/preferences/save` endpoint, where the preference in question is a JSON object of the form

```
{ "user_id": [my user id],
  "category": "flagged_post",
  "name": [post id],
  "value": "true" }
```

I would probably expect that setting the `"value"` field to the field `"false"` and saving the same setting would un-flag the post in question, removing the blue flag icon from the web UI and removing it from the list of flagged posts. Alternately, I might expect that the `"value"` field is ignored entirely, and that only deleting the preference itself can un-flag the post. Either way, I would expect the treatment of the `"value"` field to be consistent between different parts of the web UI.

#### Observed behavior (that appears unintentional) 

If we instead set the `"value"` field to `"false"` and post to `/api/v3/preferences/save`, then the web UI will exhibit anomalous behaviour: the post referenced by the `"name"` field will not be marked as flagged (i.e. there will not be a blue flag icon next to it) but it _will_ appear in the list of flagged posts. This is surprising anomalous behaviour, and it appears to be because one part of the web UI considers the `"value"` field to represent a boolean, while the other ignores it.

#### Possible fixes

It's possible to avoid this problem by only ever setting `"flagged_post"` preferences with `"true"`, but that is undocumented in the API (which does not delve into the semantics of the preference system). Nevertheless, that's probably not an optimal choice: it might be better to have the API prevent this anomalous state entirely, possibly by allowing the `/api/v3/preferences/save` endpoint to treat any `"flagged_post"` field that contains `"value": "false"` as though we requested to delete that preference instead.

Alternately, the web UI could treat the `"value"` field uniformly, either by:
- Ignoring the `"value"` field for the purposes of determining whether or not a post is flagged, and treating its presence or absence in the user's preferences as the sole determiner
- Only listing flagged posts that whose `"value"` is set to `"true"` and ignoring any flagged post preferences whose `"value"` is `"false"`

**Comment by lindy65** [comment]
Hi @aisamanra, 

Thank you for your feedback,

Could we have your help upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost to see whether this issue still reproduces for you?

Thanks!

**Comment by lindy65** [comment]
Hi @aisamanra,

Did you resolve your issue by upgrading to the latest version of Mattermost?

**Comment by aisamanra** [comment]
I just confirmed that this issue is still present on version 3.10 of Mattermost. I've attached a screenshot of our testing server, showing how this behavior manifests:

![anomalous-flagging-behaviour](https://user-images.githubusercontent.com/49535/28193795-5dc38ff0-67f4-11e7-894c-5be3c24509c8.png)

In this view, I have two flagged messages visible in the "Flagged Posts" pane to the right, one from July 12th, and one from July 13th; both of these posts are also visible in the chat window to the left. The one from July 12th was flagged using the web client, and thus has a flag icon next to it; however, the one from July 13th lacks a flag icon, and thus does not appear to be "flagged" when viewed in the chat channel, but nonetheless does appear alongside the other flagged messages in the sidebar.

**Comment by aisamanra** [comment]
I should also note that this isn't a blocking bug for me: it's possible to use the API in a way so that this behavior never manifests, and we have started using that correct behavior for our Matterhorn client. However, the proper use of the API for flagging is (as far as I can tell) not documented anywhere, and the behavior arising from incorrect use of the API is confusing enough that I thought it would be worthwhile pointing out that this confusing state is possible.

**Comment by lindy65** [comment]
Hi @aisamanra,

Thank you for the detailed feedback.  I've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7137) to fix the bug.
