### ISSUE TITLE
Bulk reaction fetching API endpoint

### ISSUE THREAD

**Issue by jtdaugherty** [mattermost/platform#6740]
Right now it seems that there is only one way to get reactions for a post, which is to use `/api/v3/teams/{team_id}/channels/{channel_id}/posts/{post_id}/reactions`. This means that when I make a request for posts in a channel, I have to make one request for each post to get the reaction data.

Is there a better way to do this? Is there bulk reaction data available somewhere, either already packaged with the post data, or available using a bulk API endpoint? I'd love to be able to make a single request with a set of post IDs to get all the reaction data in one request.

CC @aisamanra @kquick @dagit

**Comment by jwilander** [comment]
There is no current API endpoint for requesting reactions in bulk but I think it makes a lot of sense to add one to v4.

We already have bulk resource selecting with endpoints like `POST /api/v4/users/ids` which provide a list of user IDs to select in the request body. For reactions we could do something similar, such as `/api/v4/posts/ids/reactions`. In the request body there could be a list of post IDs and the response could contain a JSON object mapping post ID to reactions

Thoughts?

**Comment by jtdaugherty** [comment]
That sounds great to me!

**Comment by jwilander** [comment]
Awesome, I've added a ticket here https://mattermost.atlassian.net/browse/PLT-6950 for it. We'll probably mark it as help wanted, so if you or another community member wants to work on it go for it

**Comment by jtdaugherty** [comment]
Thanks!

**Comment by lindy65** [comment]
I'll close off this issue for now and we can track it via the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6950)
