### ISSUE TITLE
WebRTC call cannot be started on narrow windows

### ISSUE THREAD

**Issue by pieterlexis** [mattermost/platform#6750]
#### Summary
On narrow(er) screens, the WebRTC button is not shown, making it impossible to initiate a call.

#### Steps to reproduce

To replicate

 - Open a mattermost instance with WebRTC enabled 
 - Shrink the window so the layout changes to the narrow layout (< 720 works for this purpose)
 - See the WebRTC icon disappear and have no way to initiate the call

Environment tested:

- Mattermost Team version 3.10.0
- Android App, Firefox, Chrome and Linux desktop app tested

#### Expected behavior
I expected to be able to initiate the call in some way in this layout.

#### Observed behavior (that appears unintentional) 
There is not button or menu item to initiate a call to the user.

#### Possible fixes
Having a button in the top menubar, the pop-up menu (when clicking the user's name) or near the text inputfield to initiate the call would be neat.

**note**: Receiving a call works fine in this layout.

**Comment by lindy65** [comment]
Hi @pieterlexis,

Thanks for the report!  I've created [a ticket](https://mattermost.atlassian.net/browse/PLT-6940) to track the issue.

**Comment by pieterlexis** [comment]
small update, I can start a call in a private chat on a narrow window by first clicking on the user's name in the messages window (I found this out from reading the docs), which is very un-intuitive.

**Comment by lindy65** [comment]
Thanks @pieterlexis,

I've referenced this issue in the ticket so will defer to the product team for a solution :)

**Comment by lindy65** [comment]
I'll close off this issue for now and we can track via the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6940).
