### ISSUE TITLE
It's not possible to sign in to Mattermost iPhone app using "log in with GitLab"

### ISSUE THREAD

**Issue by Synchro** [mattermost/platform#6778]
#### Summary
It's not possible to sign in to Mattermost iPhone app using "log in with GitLab"

#### Steps to reproduce
Launch the mattermost app
add a server
Tap log in with gitlab
Login page is launched in browser, not app
Sign in
You're logged in in the browser, but app still shows login page. 
If you already signed in via the browser, you're taken directly to mattermost, with no opportunity to go back to the app.
Signing out from the web browser doesn't help.

#### Expected behavior
You sign in through the app and are left in the app

#### Observed behavior (that appears unintentional) 
Net result is that it's not possible to sign in to the app, you're always left in the browser.

#### Possible fixes
Obviously this is a bug in the iPhone app which isn't in this repo, but I don't know how to report bugs in that.

**Comment by lindy65** [comment]
Hi @Synchro,

Thanks for your feedback,

I take it you're talking about the iOS app and not the newer React Native app?  FYI, the iOS repo is [here](https://github.com/mattermost/ios/issues).

I've reproduced your issue and have created [a ticket](https://mattermost.atlassian.net/browse/PLT-6952) to track.

We're working on a new React Native app and you can join the discussion on our production server [here](https://pre-release.mattermost.com/core/channels/native-mobile-apps).  Signing in via GitLab SSO is one of the features in the pipeline at the moment.

**Comment by lindy65** [comment]
Hi @Synchro,

Chatting to a colleague about this issue and she mentioned being able to log in fine via GitLab within the iOS app.  I did a fresh install of the app from the app store and am now able to log in fine via GitLab within the app.

Could you try a fresh install of Mattermost from the app store and see if it fixes the issue for you?

**Comment by Synchro** [comment]
Yes! That did work, thanks for the suggestion. I guess this can be closed, especially if you've got an alternative app in the works.

**Comment by lindy65** [comment]
Thanks @Synchro!

Glad your issue is sorted :)  I'll close off the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6952) as resolved by a new installation from the app store.

If you'd like to keep up-to-date with the react native mobile app, you can join our production server [here](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and join the [Native Mobile Apps Channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps)

**Comment by plef** [comment]
Fresh install does not work for me (I even installed for the very first time). After tapping "Sign in with GitLab", I am left with empty screen with blue top bar (entitled "Single Sign-On") and hourglass icon swirling in the middle of the screen.
