### ISSUE TITLE
New direct message channel creation does not generate join event

### ISSUE THREAD

**Issue by jtdaugherty** [mattermost/platform#6797]
As of 3.10 (but probably earlier), I'm noticing that the creation of new direct message channels does not generate a `user_added` websocket event. This means that when direct messages arrive from users with whom I've never chatted before, my client doesn't know it needs to go fetch channel metadata for the new direct message channel.

I don't know how the web client handles this -- I haven't dug into that yet -- but in Matterhorn the problem arises like this:

To reproduce:
* Create users A and B.
* Log both A and B in.
* Have A send B a direct message.
* B's client will not receive a `user_added` websocket event.

We've been depending on the `user_added` event on other channel joins as an indication that we should go get channel metadata for channels that we get added to after startup. Since we don't get that for direct message channels, the asymmetry means we have to do something like this:

* On getting a new post, check whether we know about the channel. If we don't, go fetch the metadata.

So this ticket is a request for server-side creation of new direct message channels to produce the same `user_added` websocket event as channel joins for other channels so there is symmetry in channel handling.

CC @kquick @aisamanra @dagit

**Comment by enahum** [comment]
Hi @jtdaugherty 

What you describe is true, you won't receive a `user_added` websocket event but when `A` sends `B` a direct message `B` will receive a websocket `posted` event, in that event handler you can verify if you need to make the direct channel visible like we do in the webapp, you can take a look at https://github.com/mattermost/mattermost-redux/blob/master/src/actions/websocket.js#L224

**Comment by jtdaugherty** [comment]
@enahum - thanks for the reply. Your suggestion doesn't really address the request I made, though; what you're suggesting has more to do with *presentation* and what I'm requesting has more to do with the protocol.

For the code you mentioned, how does that client come to know the channel ID of the direct channel associated with the incoming post when that channel ID was not already known?

Here's how this currently works in my client, and why I'm requesting this change to the protocol:

* User A logs in. A's client fetches the list of channels of which A is a member. This list also includes any direct channels that have already been created.
* User B sends A a message for the first time ever. At this point A receives a `posted` event, but A's client doesn't know about the Channel ID associated with that post, because when B sent this message, the server created the channel and assigned it an ID. When A receives the message it has not yet had a chance to fetch the channel metadata for the channel, because it was never told it joined a new channel.

It's true that we could implement a workaround by always checking the channel ID of incoming posts and fetching channel metadata if it's missing, but that strikes me as a compensating hack to deal with the lack of symmetry in the server protocol. That's why I'm asking for this change here, rather than working around the situation in our client.

Right now the server's promise is: "Whenever you are added to a channel, you will be sent a `user_added` event at that time, except if the channel is a direct channel." What would be helpful is if we could get that "except..." removed so that direct channels behave like other kinds of channels.

**Comment by enahum** [comment]
Hi @jtdaugherty 

I've created a ticket https://mattermost.atlassian.net/browse/PLT-7122 with your request and I'm going to queue it up for discussion in our next [dev meeting](https://pre-release.mattermost.com/core/channels/developers-meeting) that you can join as is open to the public (we have one every week) I would highly recommend that you join us to discuss this topic

**Comment by jwilander** [comment]
I think there is a "direct_added" that should get sent to both users when the DM is created. That might be of use to you

**Comment by jtdaugherty** [comment]
Oh, indeed, we don't have a handler for that event and didn't know what it was for. Thanks! In that case, I'll close this assuming that's what we need and will investigate. Thanks!
