### ISSUE TITLE
Enable local server storage as alternative to setting up S3

### ISSUE THREAD

**Issue by guycalledseven** [mattermost/platform#68]
Hi
I've just tested out docker image on ubuntu 14.04 and I am unable to upload any files. 
```Unable to upload file. Amazon S3 not configured. k6n481j5fbggzmdie8qh6p6poy501```

How/where can this be configured? I am sorry if I missed it, but If it's not yet implemented it would be completely ok to use local server storage instead of s3 :)

**Comment by it33** [comment]
Hi guycalledseven, 

If you have your own S3 account you can configure it in the config/config.json file. You should just need to go to the AWSSettings section and fill in the follow fields: 

"S3AccessKeyId": "", 
"S3SecretAccessKey": "", 
"S3Bucket": "", 
"S3Region": "", 

Once those are configured properly you should be able to start uploading/downloading images and files to your S3 bucket through your Mattermost instance. (Make sure to restart your server after filling these in). 

As it is now we don't have any way to allow you to configure local server storage, but this is something that's on our roadmap of things to do so look out for it in the nearish future! :)

**Comment by mancvso** [comment]
Looking forward to local server uploads.

**Comment by snapple42** [comment]
Looking forward to local uploads... Also another thing to consider is Openstack Object Store Containers

**Comment by it33** [comment]
Updating title of ticket to reference issue to add local server storage. Also added FAQ on the S3 error message: http://discourse.mattermost.org/t/error-unable-to-upload-file-amazon-s3-not-configured/22

**Comment by it33** [comment]
Thanks to fanbin for opening a feature request on this issue, http://mattermost.uservoice.com/forums/306457-general/suggestions/8617639-local-storage-of-files-and-photos

Closing this ticket per http://forum.mattermost.org/t/why-is-my-github-issue-being-closed-without-a-pull-request/36
