### ISSUE TITLE
[website] Can't register to security Bulletin

### ISSUE THREAD

**Issue by piec** [mattermost/platform#6821]
#### Summary
When I register to the "Security Bulletin mailing list" I never receive the confirmation email (although the email is correct)
[Link to register](http://eepurl.com/cAl5Rv) found here:
* https://about.mattermost.com/security-updates/

I tried several times, last time I tried was 1 month ago I think

#### Steps to reproduce
* Open https://about.mattermost.com/security-updates/
* Click [mailing list](http://eepurl.com/cAl5Rv)
* Enter email / name / ...
* Submit 
* See a message "almost finished [...] please click the link in the email we just sent you [...]"

#### Expected behavior
I should receive a confirmation email

#### Observed behavior (that appears unintentional) 
I don't receive a confirmation email

**Comment by lindy65** [comment]
Thanks for the report @piec,

I did not receive a confirmation email either, nor did it go to my spam inbox.  Just checking that no email was delivered to your spam either?

I've created a [ticket](https://mattermost.atlassian.net/browse/PLT-6977) to fix the issue.

**Comment by piec** [comment]
Thanks

No, not in spam either

**Comment by lindy65** [comment]
Thanks for your feedback @piec,

We can track this via the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6977)
