### ISSUE TITLE
Sending html including large-size image in IE

### ISSUE THREAD

**Issue by agape824** [mattermost/platform#6826]
I have a job to sending html including large-size image to server while embedding web editor in Mattermost.
I succeded it by increasing maximum both the size of post message from 4KB to 10MB
and the size of DB table's column.

It works well on Chrome browser, but not on Internet Explorer.
IE cannot even connect to the Mattermost site, producing Javascript error.
Error occurs in PersistStore(StorePersist?) of mattermost-redux node-module.

Is there any solution without prohibiting using IE?

===================================================================
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Bug report in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by enahum** [comment]
Hi @agape824 this has been fixed with https://github.com/mattermost/platform/pull/6832 and it will be available in the next release.

Hope this helps
