### ISSUE TITLE
Immediate email notifications

### ISSUE THREAD

**Issue by k9k** [mattermost/platform#6849]
#### Steps to reproduce
1. leave Mattermost on different screen or minimized 
2. receive a new message
3. email notification is sent immediately

This issue was mentioned in [Michael Magill's comment](https://mattermost.atlassian.net/browse/PLT-2451?focusedCommentId=36245&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-36245), but I'm afraid it's been ignored as it was added to a ticket that had been closed. Please check his comment for a good explanation.

**Comment by esethna** [comment]
Thanks @k9k. The comment makes sense and we are definitely aware of the issue. We are still thinking about some options to address email notifications being sent when undesired. Some options include:

1. Removing the immediate email option and sending emails only every 15 minutes (so if you've seen the message then it won't be included in the email batch)
2. Adding a setting for when to receive email notifications depending on status (similar to push notifications - so you could set it to send only when fully offline)
3. Adding a delay so the user has time to check the desktop notification before the email sends (as the ticket describes)
4. Improving the ability of statuses to detect if the user is at their computer (only possible on the desktop app, not the browser)

Is there an option you'd lean towards?

**Comment by k9k** [comment]
@esethna thank you for the response. 

For me number 3. seems to be the best option but combined with an option that when user is logged out from `Mattermost` there should be an immediate notification on mention/direct message.

**Comment by esethna** [comment]
Okay thanks for your feedback @k9k! This design is high priority for us. I expect we will have a solution for this shipping with v4.1 August 16th. I'm going to close this ticket, but feel free to reopen the discussion if you have other feedback on this.

**Comment by edannenberg** [comment]
We are still having issues with this in 4.1. Having the ability to only send notifications when in a certain status (i.e. offline only) would be nice.
