### ISSUE TITLE
Making a SSO tool for Mattermost (eg. GitLab, Google..)

### ISSUE THREAD

**Issue by agape824** [mattermost/platform#6859]
I want to use company's specific website as SSO to sign in Mattermost.
I know that GitLab, Google can be such SSO tool for Mattermost, using OAuth.
Can I make another SSO tool (company's website) for Mattermost like GitLab?
I wanna know if it's possible or not.

=================================================================
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Bug report in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by esethna** [comment]
Hi @agape824, thanks for the suggestion. Currently Mattermost does not support generic OAuth for SSO authentication. I would recommend [adding support](https://mattermost.uservoice.com/forums/306457-general/suggestions/10096884-ee-oauth2-for-generic-identity-provider) to the idea on our feature idea forum and starting any related discussions in the comments. Every vote helps shape the future of Mattermost.
