### ISSUE TITLE
Code format block trims leading and trailing white space

### ISSUE THREAD

**Issue by alallier** [mattermost/platform#6865]
#### Summary
Mattermost trims leading and trailing white space in the code formatting block.

Note: Mattermost does not trim leading white space if a character occurs in that line, but it will still trim the trailing white space

Examples:

Typed Message:

```
   
  ssdfsdf   
                 aa   
```

Becomes:

```

  ssdfsdf   
                 aa
```

#### Steps to reproduce
Try highlighting the above message to notice the white space and sending the above message over Mattermost

#### Expected behavior
I would expect the spacing to remain the same when sent. This is important in a code block as usually you want to preserve formatting when sending code blocks to people.

#### Observed behavior (that appears unintentional) 
Mattermost strips the leading/trailing white space.

**Comment by hmhealey** [comment]
Hi @alallier,

Thanks for the report. I've filed [a ticket](https://mattermost.atlassian.net/browse/PLT-7032) on our Jira instance to correspond with this issue. It may be difficult to fix with the markdown library that we're currently using in the web app, but I have plans to replace it eventually with the one we're using in our mobile app once that reaches feature parity

**Comment by lindy65** [comment]
A PR to fix this issue has been submitted for release with v4.1 so I'll close this issue off.

**Comment by alallier** [comment]
Link to the PR?

**Comment by lindy65** [comment]
Sorry @alallier!  Very remiss of me...  Here is the PR: https://github.com/mattermost/platform/pull/7015

**Comment by alallier** [comment]
No worries @lindy65, thanks for the link.
