### ISSUE TITLE
Tfs pull-request message results in html error 500

### ISSUE THREAD

**Issue by a13x59** [mattermost/platform#6873]
#### Summary
A specific Tfs message to an incoming mattermost webhook results in an html error 500

#### Steps to reproduce
Mattermost Enterprise Edition
Version: 3.9.0
Database: postgres

Send this message to a webhook URI:

`{
   "attachments":[
      {
         "fields":[
            {
               "title":"Source",
               "value":"`refs/heads/feature/12345`",
               "short":true
            },
            {
               "title":"Target",
               "value":"`refs/heads/dev`",
               "short":true
            },
            {
               "title":"Status",
               "value":"`active`",
               "short":true
            },
            {
               "title":"Merge Status",
               "value":"`succeeded`",
               "short":true
            },
            {
               "title":"Description",
               "value":"-Merge remote-tracking branch 'remotes/origin/dev' into feature/12345\r\n-Merge branch 'dev' into feature/12345\r\n-Task #12345 - Some usefull work",
               "short":false
            },
            null
         ],
         "mrkdwn_in":[
            "pretext",
            "fields"
         ],
         "pretext":"Hartnett, Jamal. created <https://tfs.contoso.com/tfs/contoso/year-17/_git/project/pullrequest/1234#view=discussion|pull request 1234> (Task #12345 - Some usefull work) in <https://tfs.contoso.com/tfs/contoso/year-17/_git/project/|project>",
         "fallback":"Hartnett, Jamal. created pull request 1234 (Task #12345 - Some usefull work) in project\r\nhttps://tfs.contoso.com/tfs/contoso/year-17/_git/project/\r\n-Merge remote-tracking branch 'remotes/origin/dev' into feature/12345\r\r\n\r\n-Merge branch 'dev' into feature/12345\r\r\n\r\n-Task #12345 - Some usefull work\r\n"
      }
   ]
}`

curl request below:
[incorrect_message_500_error.txt](https://github.com/mattermost/platform/files/1130859/incorrect_message_500_error.txt)

#### Expected behavior
Error does not occurs

#### Observed behavior (that appears unintentional) 
This is the pull-request message used by the Visual Studio Online (Version 14.102.25423.0) when setting up an integration via Slack messages.

Status Code: 500
Reason Phrase: Internal Server Error
HTTP Version: 1.1
Headers:
{
  Connection: keep-alive
  X-Cluster-Id: 
  X-Request-Id: fdu1a7dgj7di3mojtdcjybgwho
  X-Version-Id: 3.9.0.3.9.0.357079b401a4267fef6aaf31ca0f7500.false
  Date: Mon, 03 Jul 2017 08:35:01 GMT
  Server: nginx/1.10.0
  Server: (Ubuntu)
  Content-Length: 0
  Content-Type: application/json
}

#### Possible fixes
Looks like the "null" param is not handled correctly ("Reviewers" field in this case). Without this null param everything is ok.

**Comment by lfbrock** [comment]
Thanks @a13x59 - looks like that's a bug, filed a Jira ticket here for it: https://mattermost.atlassian.net/browse/PLT-7077

If anyone would like to contribute a fix, please let us know!

**Comment by lindy65** [comment]
Thanks everyone, I'll close this issue off now as the fix has been merged.
