### ISSUE TITLE
Update NPM version of Javascript driver

### ISSUE THREAD

**Issue by BorigTheDwarf** [mattermost/platform#6888]
The version of mattermost-driver-javascript available via NPM is not the latest. Please could this be updated?

**Comment by BorigTheDwarf** [comment]
Hi @lfbrock thanks for that. Looks like it has been neglected for awhile - would it be possible to get the NPM version updated without the automation? The driver hasn't been modified for several months but the version on NPM is ancient and many of the APIs are missing or no longer work.

**Comment by lfbrock** [comment]
@BorigTheDwarf yes perhaps - I'll find someone to get this updated hopefully next week or the week after (just a bit busy finalizing things for the July release at the moment).

**Comment by hmhealey** [comment]
We've filed a ticket to update this and point it at the Javascript client's new location in the https://github.com/mattermost/mattermost-redux repository. If you'd like to track it, the ticket is https://mattermost.atlassian.net/browse/PLT-5432

**Comment by lindy65** [comment]
As we can track this issue via the Jira ticket, I'll close it off here...
