### ISSUE TITLE
iOS media button does nothing

### ISSUE THREAD

**Issue by mikeerickson** [mattermost/platform#6894]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Clicking the paperclip icon has no effect on iOS

#### Steps to reproduce
Create a new message, click the paperclip icon

#### Expected behavior
I am thinking this should allow selection of media attachment

#### Observed behavior (that appears unintentional) 
All the time

**Comment by lfbrock** [comment]
Hi @mikeerickson - would you be able to check which version of the app this is on? 

I created a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-7087

**Comment by mikeerickson** [comment]
i have seen it for a few versions back so far as I can remember.  But I am not using Mattermost Classic on iOS v3.8.0 (dev)

**Comment by lindy65** [comment]
This has been fixed and was released with v4.0 on July 16th.

**Comment by mikeerickson** [comment]
@lindy65 I am assuming this is not yet in the App Store as my version is 3.10.1

**Comment by lfbrock** [comment]
@mikeerickson I think this should be fixed in v3.10.1 - can you check if you have permissions for accessing files turned on for the app? Maybe delete + reinstall the app as well

**Comment by mikeerickson** [comment]
@lfbrock I switch to Mattermost Team Edition and this interface works (using the + icon to add assets)
