### ISSUE TITLE
Broken links on System Console Mobile Push settings page

### ISSUE THREAD

**Issue by JeffSchering** [mattermost/platform#6940]
#### Summary
A couple of broken links into the Mobile Applications Guide from **System Console > Notifications > Mobile Push**

#### Steps to reproduce
1. Go to **System Console > Notifications > Mobile Push**.
1. In the *Enable Push Notifications* field, select **Do not send push notifications**.
1. Click **documentation on push notifications**.
1. In the  *Enable Push Notificationis* field, select **Use iOS and Android apps on iTunes and Google Play with TPNS**.
1. Click **TPNS**.

#### Expected behavior
1. For the first link, expected to go to https://docs.mattermost.com/deployment/push.html#push-notifications-and-mobile-devices but the \#push-notifications-and-mobile-devices anchor doesn't exist in the doc.
1. The second link, http://docs.mattermost.com/deployment/push.html#test-push-notifications-service-tpns, doesn't exist either.

It looks like the doc was rewritten at some point, and the anchor targets no longer exist. Furthermore, in the case of the link to TPNS info, there doesn't seem to be much extra info on that page about TPNS other than "for testing only, don't rely on it too much".

**Comment by hmhealey** [comment]
Thanks for the report. I've filed a ticket on Jira to get those fixed.
https://mattermost.atlassian.net/browse/PLT-7235

**Comment by lindy65** [comment]
The PR has been merged and ticket closed so I'll close off this issue.
