### ISSUE TITLE
[RFC] Isolate teams from each other

### ISSUE THREAD

**Issue by Ppjet6** [mattermost/platform#6941]
#### Summary
This is a feature request.

UserA in teamA can see userB in teamB, and can talk to them, I would like to be able to prevent this from happening.

#### Steps to reproduce
Using version 4.0

- Create teamA
- Create teamB
- Create userA and join teamA
- Create userB and join teamB
- Login as userA and click the "More" button under "Direct Messages"

#### Expected behavior
As userA, being able to see only people in teamA when only added to teamA, and in teamB as well if added to teamB.

#### Observed behavior
UserA is able to see userB in the user list, and even talk to them.

#### Possible fixes

Maybe this can be proposed as a system option: "Allow teams to talk to each other".
- Users would be able to see/talk only to users in the same teams they are in.
- Channels from other teams would not be accessible.

#### Misc

We want to use this to use internally in the company, and also propose this to customers to use. We don't want customerA to know the existence of customerB.

We (I) are going to implement the feature, and it would be nice if this could get into the community edition. We would use the patches locally regardless of the outcome.

Please tell me if I am missing anything, or if there is anything I should know wrt. implementing this.

EDIT: cleaned up "Steps to reproduce"

**Comment by Ppjet6** [comment]
Hmm, I should have done my research a bit better, there seem to be such a feature already in the System Console under Users and Teams / Enable users to open Direct Message channels with: Any member of the team.

I had a little chat with @jasonblais though, and apparently the feature is not complete yet. I guess we can expand on this and try to find the last corner cases.

**Comment by lindy65** [comment]
We can track this issue via the PR above so I'll close it off for now.
