### ISSUE TITLE
Why not have HMR in webpack?

### ISSUE THREAD

**Issue by abzfarah** [mattermost/platform#6949]
Is there any reason why this project doesn't use hot module replacement? Do you have to manually refresh after every edit?

I'm trying to set up  a project with a go sever to use hmr, I wasn't able to do it so I came here hoping to see how it could be done. The webpack-hot-middleware plugin docs says it could be used for any sever to use receive live updates but I haven't seen any examples of it.

**Comment by hmhealey** [comment]
Hi @abzfarah,

Yes, we have to refresh after every edit. I don't think there was any particular reason for us not to support hot reloading, but it may have had to do with the fact that it requires webpack-dev-server and we use our own web server which used to be much more involved than just serving up precompiled HTML like it mostly does now.
