### ISSUE TITLE
Minor cosmetic problem in System Statistics when system language is German

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/platform#6950]
#### Summary
Lower Row of numbers not properly aligned (Mattermost 4.0.0)

#### Steps to reproduce
Turn mattermost to german.

![2017-07-16 11_59_43-systemkonsole - iron](https://user-images.githubusercontent.com/8283684/28246620-c2009d92-6a1e-11e7-967e-7f5d460da47e.png)

**Comment by lindy65** [comment]
Thanks @Twilek-de,

I've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7144) to fix the issue.

**Comment by lindy65** [comment]
A PR has been submitted which will fix the issue in the next release, 4.1, on August 16th.
