### ISSUE TITLE
Link preview shouldn't appear

### ISSUE THREAD

**Issue by S6066** [mattermost/platform#6952]
["Links"](https://user-images.githubusercontent.com/14875962/28248142-c1d16b28-6a3f-11e7-8caa-bb8141712cc7.png) should not appear when hovering:
- Channels, including buttons to add or join new channels
- Time of messages
- Messages's flag button
- User's infos/settings
- Channel infos/settings

It would be good too to add a setting to disable links, it's really annoying to see them appear, disappear, appear, etc. when moving the cursor

(Mattermost Desktop, v4.0)

**Comment by jasonblais** [comment]
@S6066 Thanks for the feedback, and I agree

We do in fact have a ticket for it here, https://mattermost.atlassian.net/browse/PLT-6828.

**Comment by lindy65** [comment]
I'll close this issue off as we have a ticket to track the issue for the v4.1 release in August.
