### ISSUE TITLE
[UI Improvement] Mattermost 4.0.0 sidebar sections in white are distracting

### ISSUE THREAD

**Issue by gravufo** [mattermost/platform#6958]
The sidebar in Mattermost 4.0.0 now has its sections highlighted in popping white as opposed to whatever was there before. This has the unfortunate effect of making people think that they have an unread message since channels with unread messages get highlighted the same way.

See here:
![mattermost sections](https://user-images.githubusercontent.com/475807/28288988-1667ccac-6b0f-11e7-8b06-93b2c61117c8.png)

Thanks

**Comment by lfbrock** [comment]
Hi @gravufo thanks for pointing this out, I think it makes sense to change that - created a ticket here for it: https://mattermost.atlassian.net/browse/PLT-7181

**Comment by epatpol** [comment]
Thanks @lfbrock! Otherwise nice update :)

**Comment by gravufo** [comment]
Thanks a lot! Should we close this issue or leave it open?

**Comment by lfbrock** [comment]
We can close it and track in Jira, thanks everyone!
