### ISSUE TITLE
[Help Wanted] [PLT-7171] Kubernetes: Writeup documentation for using kubes/helm for developers running minikube

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6960]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7171)

**Comment by fraziern** [comment]
Willing to give this a shot (full disclosure, I'm a total beginner with Kubernetes, but definitely interested).

**Comment by coreyhulen** [comment]
@fraziern I think someone already started working on this.  I'll find out and circle back next week.

**Comment by escardin** [comment]
I'm working on this. Sorry for the delay in marking it.

**Comment by fraziern** [comment]
no worries
