### ISSUE TITLE
[Help Wanted] [PLT-7176] Kubernetes: Support Minio for file storage

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6963]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7176)

Add https://github.com/kubernetes/charts/tree/master/stable/minio as a sub-chart and support Minio for HA file storage.
The goal of the Kubernetes repo at https://github.com/mattermost/mattermost-kubernetes has 2 objectives.
1) An easy to setup highly available reference implementation for running the load tests.
2) The longer term goal is a highly available production ready implementation.

**Comment by jasonblais** [comment]
In progress by Mattermost staff.
