### ISSUE TITLE
strange behavior of the "time link" on each message

### ISSUE THREAD

**Issue by giabao** [mattermost/platform#6967]
#### Summary
Clicking to the "time link" on the message open new desktop app instance (on desktop) / new tab (on browser) instead of just jump to the message.

![image](https://user-images.githubusercontent.com/1702709/28305496-0ad01c66-6bc6-11e7-9153-4451b148369b.png)

#### Possible fixes
Remove the link, or set the href to `#hash`

**Comment by esethna** [comment]
Thanks @giabao, just to verify, the expected behavior would be that it jumps to the post in permalink view in the current window, rather than opening a new desktop window? I think this makes sense.

Are you interested in working on a PR for this?
