### ISSUE TITLE
PDF preview doesn't work for 4.0.0

### ISSUE THREAD

**Issue by muirdok** [mattermost/platform#6968]
#### Summary
it doesn't work. You could see progress but it's never shown. tested on two instances (upgraded from 3.7 -> 4.0.0)

#### Steps to reproduce
Open any sent pdf file

#### Expected behavior
Preview is shown

#### Observed behavior (that appears unintentional) 
it shows only progress (opening)

#### Possible fixes
not defined

**Comment by jasonblais** [comment]
Thanks @muirdok! I've filed a ticket for this https://mattermost.atlassian.net/browse/PLT-7179

**Comment by muirdok** [comment]
Thanks!
