### ISSUE TITLE
Enabling SSO ignores causes "DisableTeamCreation" to be ignored

### ISSUE THREAD

**Issue by Caligatio** [mattermost/platform#698]
I would like the ability to completely block all team creation after I create the teams I want.  I just upgraded to 0.7 and it appears that, if SSO is enabled, there is no way to completely disable team creation.

I attempted to set [DisableTeamCreation](https://github.com/mattermost/platform/blob/release-0.7.0/config/config.json#L100) config setting to `true` but it appears that the [createTeamFromSSO](https://github.com/mattermost/platform/blob/release-0.7.0/api/team.go#L83) function does not call [isTreamCreationAllowed](https://github.com/mattermost/platform/blob/release-0.7.0/api/team.go#L286) which is the function that pays attention to the config setting.

**Comment by coreyhulen** [comment]
Thanks for reporting the issue.  A fix (https://github.com/mattermost/platform/pull/700) has been submitted and should appear in master within the next 24 hrs.

**Comment by it33** [comment]
Closing as fixed in v0.8 since #700 is now merged
