### ISSUE TITLE
Mattermost does not read the AWS S3 region setting

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [mattermost/platform#6999]
After upgrade to Version: 4.0.0  (4.0.1)
```
[EROR] /api/v4/users/<some hash>/image:WriteFile code=500 rid=<some hash> uid=<some hash> ip=*.*.*.* Encountered an error writing to S3 [details: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1']
```
`"AmazonS3Region": "eu-west-1"` in config file.
I had to move the bucket to another region which is not a very good idea as for me.

**Comment by jasonblais** [comment]
@Ilya-Kuchaev Which version did you upgrade from? And it sounds like it used to be working fine?

**Comment by Ilya-Kuchaev** [comment]
From 3.10.0. Yes. Everything worked fine. As for now I do not see the Region field to setup it from UI. Config or ENV variable editing only.

**Comment by grundleborg** [comment]
Hi @Ilya-Kuchaev . Thanks for the bug report. I've had a look through the code, and it does appear that the AWS region setting is no longer actually used. I've filed a JIRA ticket for the development team to investigate here https://mattermost.atlassian.net/browse/PLT-7208
