### ISSUE TITLE
How do I run mattermost with rethinkdb instead of mysql?

### ISSUE THREAD

**Issue by kamilion** [mattermost/platform#70]
What's the best way to get rid of the mysql dependancy in the dockerfile and rely solely on rethinkdb for storage and changes()?
I can see that most of the structures in go are already using json to describe objects.
In general, I would expect rethinkdb to be able to take over for mysql's storage and using redis to broadcast changes by using using @dancannon's [gorethink](https://github.com/dancannon/gorethink) Go bindings to access rethinkdb's [changes](http://rethinkdb.com/api/python/changes/)() api.

I'm not all that familiar with Go's syntax, but I could take a stab at an ugly PR if nobody else wants to.

**Comment by it33** [comment]
Hi @kamilion, forks of mattermost are definitely encouraged, and if you do something interesting with RethinkDB, I think both RethinkDB and Mattermost communities would be interested in seeing it, 

In terms of the core team being able to take a merge request, the best approach is opening a feature request (http://www.mattermost.org/feature-requests/) and seeing the community support rise around it, which may lead to the core team either marking its status as "accepting merge requests" (https://mattermost.uservoice.com/forums/306457-general/status/1588438) if it makes sense to have it added by the community, or "planned" (https://mattermost.uservoice.com/forums/306457-general/status/1588357) if they decide to add it. 

Does this help?

**Comment by it33** [comment]
Hi @kamilion, per http://forum.mattermost.org/t/why-is-my-github-issue-being-closed-without-a-pull-request/36, I'm closing this ticket. Please feel free to open an new ticket if you think differently?
