### ISSUE TITLE
4.0 Nicknames Gone?

### ISSUE THREAD

**Issue by bios-ben** [mattermost/platform#7003]
#### Summary
4.0 removed the ability to display nickname as default for users, so everyone is back to their lowercase regular login name. Can we get that back, nickname can make the names display much nicer.

#### Steps to reproduce
4.0, set nickname in account settings, send a message and it'll be login showning not nickname

#### Expected behavior
I'd expect if I set nickname to "TEST" and my login was "test" that it'd display "TEST" when I typed messages.

#### Possible fixes
Revert the removal of the option "Use nickname for message display" or whatever it was < 4.0

**Comment by lindy65** [comment]
Hello @bios-ben,

Thanks for your feedback,

You're still able to change these settings in the System Console - you can read about it in the [changelog](https://docs.mattermost.com/administration/changelog.html#removed-and-deprecated-features).

**Comment by bios-ben** [comment]
Ah I found the new setting, this is a great place for it, the problem is it doesn't work. When I toggle it to Nickname and click Save it just toggles back to username selected. What information would be useful to debug this or is it a known issue? 

----- Original Message -----

**Comment by lindy65** [comment]
Hey @bios-ben,

I have tried to repro this issue on our server running v4.0 but am not able to.  Are there any errors in your console?

Could I have your help sharing a screenshot of your "About Mattermost" modal?  You can access this via the 3-bar main menu > About Mattermost.

Also, do any other System Console settings save?

**Comment by bios-ben** [comment]
You can close the ticket, apparently during the upgrade the config was incorrectly migrated so nothing saves. Working to correct it now which will likely fix this issue.

----- Original Message -----

**Comment by lindy65** [comment]
Ah, glad to hear you've found the problem!  Let us know if you still experience problems.

**Comment by clark42** [comment]
Hello !
I see this issue is closed now
I've just made the upgrade this morning, and lot of my users are frustrated to have no choice anymore.
can we know why this setting can not be overload user side ?

**Comment by bios-ben** [comment]
I force my users to all see the same thing and agree with the global change because it'd be annoying to have someone talk about "Joe" and another "xman57" because two people have different display modes set and can't agree on what's displayed. Just my thought, I won't tell your users to not be frustrated ;) 

----- Original Message -----
