### ISSUE TITLE
4.0 choose font option gone?

### ISSUE THREAD

**Issue by bios-ben** [mattermost/platform#7004]
#### Summary
This may be a new feature request as well, but before 4.0 we could select one of a few fonts, now that option is gone.

#### Steps to reproduce
Upgrade to 4.0 there's no font setting under the account settings.

#### Possible fixes
Add back the original font selector?
(feature) With theme customization, why can we only change colours and not fonts? I'd think font should be a part of the theme changes and support any of the standard CSS comma separated list of fonts so it uses what's available in priority. On Windows I used to have to it set to Lato becacuse it rendered nicely unlike the Helvetica Neue stuff that looks terrible for some reason on my machine. There's other fonts out there that are very clear as well I'd likely choose from as the current one is a bit blocky and short.

**Comment by lindy65** [comment]
Hi @bios-ben,

Thanks for your feedback,

We posted [this issue](https://forum.mattermost.org/t/removing-font-setting/3367) on our forum at the beginning of June giving a heads up about the font setting removal along with the reasons why.

Could we have your help leaving your feedback there for our design team?

**Comment by bios-ben** [comment]
I've commented there, thanks. 

----- Original Message -----

**Comment by lindy65** [comment]
Thanks @bios-ben!

I'll close this issue off then and we can track feedback in the forum issue.
