### ISSUE TITLE
Can't render incoming webhook's attachments anymore

### ISSUE THREAD

**Issue by jostyee** [mattermost/platform#7009]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
After rebuilding the master branch, the Desktop can't render incoming webhook message's attachment, last build I did on Jul.7th was working fine.

#### Steps to reproduce
Build latest platform codes, send a webhook message to mattermost(e.g.: Open a GitLab issue or comment one), only the main parts are showed, the comment itself disappears.

#### Expected behavior
Properly rendering.
<img width="363" alt="2" src="https://user-images.githubusercontent.com/88564/28502196-b6dae352-6fb2-11e7-87a1-a7f445f62b18.png">

#### Observed behavior (that appears unintentional) 
<img width="323" alt="1" src="https://user-images.githubusercontent.com/88564/28502224-570f44ee-6fb3-11e7-958c-fcbe4f1edfa0.png">

**Comment by jasonblais** [comment]
Thanks @jostyee! Reproduced and filed a ticket here https://mattermost.atlassian.net/browse/PLT-7212

Looks like it's not an issue on the 4.0 release, only on `master`.

Thanks again for the report!

**Comment by lindy65** [comment]
A PR has been submitted to fix this issue with the v4.1 release in August.
