### ISSUE TITLE
On macOS, Notifications dismiss themselves even when they are configured to the Alert type

### ISSUE THREAD

**Issue by jake-griffin** [mattermost/platform#7026]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
I have configured Mattermost notifications to be the Alert type in OS X Notification Preferences. When an alert pops up, it looks correct, however the notification is dismissing itself. For Alert notifications, they should remain visible until interacted with. Badge notifications dismiss themselves.

#### Steps to reproduce
I am using macOS Sierra (10.12.5) and Mattermost Version 3.7.0 (3.7.0.3.7.0).

1. Configure Mattermost notifications in OS X Notifications preferences to be of the Alert type
2. Minimize or close the Mattermost window
3. Have someone send you a message, triggering a notification

#### Expected behavior
The notification appears and remains until interacted with.

#### Observed behavior (that appears unintentional) 
The notification appears, but then dismisses itself after a few seconds.

**Comment by lindy65** [comment]
Hi @jake-griffin,

Thanks for your feedback,

To clarify your step 1. above, have you set the `Notification duration` in `Account Settings > Notifications > Desktop Notifications > Notification duration`?

If so, this could be a bug.  Could you tell me which version of Mattermost you have installed?

**Comment by jake-griffin** [comment]
Yes, I am using the Desktop App. I don't see an option for Notification Duration. Under `Account Settings > Notifications`, all I see is `Send desktop notifications (For all activity/Only for mentions and direct messages/Never)`, `Desktop notification sounds (On/Off)`, `Email notifications (On/Off)`, `Mobile push notifications (disabled by my system administrator)` and `Words that trigger mentions`.

**Comment by lindy65** [comment]
Thanks @jake-griffin,

Ah, ok - hence my confusion...  You're on the Desktop App ;)

I'm not sure that this functionality has been added yet.  Could we have your help opening this issue in the [Desktop App repo](https://github.com/mattermost/desktop/issues) please?  

Thanks!

**Comment by jake-griffin** [comment]
Will do, thanks!
