### ISSUE TITLE
Disabling WebRTC in Chrome causes Mattermost 4.x to white screen

### ISSUE THREAD

**Issue by XANi** [mattermost/platform#7032]
#### Summary
Whole page is just white after logging in.

#### Steps to reproduce
Install WebRTC Block in Chrome. Refresh page.

#### Expected behavior
Mattermost working but without video/audio calling. WebRTC have serious privacy problems ( [example](https://www.perfect-privacy.com/webrtc-leaktest/) ) and (at least until big heads at google decide it would be nice to opt-in instead of opt-out) it would be nice to have working chat without having to have WebRTC enabled. Didn't happen in 3.9

#### Observed behavior (that appears unintentional) 
A white page.

Same behaviour happens at pre-release.mattermost.com

**Comment by jasonblais** [comment]
@XANi Thanks for the report.

1) If you uninstall the browser extension (is this the one you're referring to: https://chrome.google.com/webstore/detail/easy-webrtc-block/cmjcmogcdofcljpojplgmfpheblcaehh?hl=en), does it still cause Mattermost to freeze?
2) When you say `Disabling WebRTC in Chrome`, do you mean disabling it from Account Settings?

**Comment by XANi** [comment]
Disabling extension fixes it. Apparently using different WebRTC blocker also does.

> is this the one you're referring to: https://chrome.google.com/webstore/detail/easy-webrtc-block/cmjcmogcdofcljpojplgmfpheblcaehh?hl=en

No, I typed the name of plugin exactly. It seems it got de-listed from store for whatever reason.
I did test with [diferent one](https://chrome.google.com/webstore/detail/webrtc-leak-prevent/eiadekoaikejlgdbkbdfeijglgfdalml?hl=en) and it works fine with that one.

I've used https://browserleaks.com/webrtc to test and only difference (well, only visible one) between the two was that the problematic plugin blocked `RTCPeerConnection` and `RTCDataChannel` but under same conditions in firefox (both shown as blocked after disabling webrtc in firefox options).

So it kinda looks like badly plugin blocked too much. But then there is other question, I have WebRTC disabled on Mattermost server, why client was trying to use it without checking if it is actually supported


> When you say Disabling WebRTC in Chrome, do you mean disabling it from Account Settings?

I don't think Chrome has option for it (Firefox just have it under about:config), hence me using plugin

**Comment by jasonblais** [comment]
> I have WebRTC disabled on Mattermost server

You mean you disabled WebRTC via config.json (or System Console)?

The feature is still beta/preview mode so there might be some bugs with that feature.

**Comment by XANi** [comment]
Yes, WebRTC in mattermost itself was disabled

**Comment by lindy65** [comment]
Hi @XANi,

Thanks for your feedback, 

We've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7253) to investigate the issue.

**Comment by lindy65** [comment]
Closing this off here as we can track via the Jira ticket above.
