### ISSUE TITLE
No image preview in compiled version.

### ISSUE THREAD

**Issue by iUkka** [mattermost/platform#7038]
#### Summary
No image preview in compliled version of MM.
On downloaded precompiled version on same DB and same config all perfect.

#### Steps to reproduce
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

cd ~/go/src/github.com/mattermost
git clone https://github.com/mattermost/platform.git
cd platform
make build
make packages

unpack to opt, chown, run platform

Copy any image, paste to channel
.
![image](https://user-images.githubusercontent.com/5823637/28679917-58dc6e8a-72fd-11e7-8000-20923aab5b47.png)

**Comment by iUkka** [comment]
ouch, corry, my fault.
in my config file was no section

        "PreviewWidth": 1024,
        "PreviewHeight": 1024,
        "ProfileWidth": 128,
        "ProfileHeight": 128,

After compile and install 3.10 version platform give me panic:
panic: Invalid preview width for file settings.  Must be a positive number.

**Comment by jasonblais** [comment]
No worries @iUkka! Glad you were able to resolve it!

**Comment by qqshfox** [comment]
@iUkka exactly same issue here, however adding these to `FileSettings` seems not fix the problem for me. Do you fix the problem?

**Comment by qqshfox** [comment]
The problem exists in both v4.0.1 and v4.0.2. Upgrading to master branch (345bb2236) fixed the issue.

**Comment by iUkka** [comment]
Just take a deafult config.json and make configuration again.
