### ISSUE TITLE
Crash on 32 bit ARM

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#7055]
#### Summary
I'm trying to run Mattermost on an Android ARMv7 host but it crashes at launch.

#### Steps to reproduce
Clone the latest master on a 32 bit ARM host and run `go run cmd/platform/*.go`.

#### Expected behavior
It should run without crashing.

#### Observed behavior (that appears unintentional) 
```
[2017/07/29 14:43:02 UTC] [INFO] Loaded system translations for 'en' from '/data/data/com.termux/files/home/go/src/github.com/mattermost/platform/i18n/en.json'
[2017/07/29 14:43:02 UTC] [EROR] SMTP server settings do not appear to be configured properly err=Failed to open connection details=dial tcp: lookup dockerhost: No address associated with hostname
[2017/07/29 14:43:02 UTC] [INFO] Current version is 4.0.0 (///)
[2017/07/29 14:43:02 UTC] [INFO] Enterprise Enabled: 
[2017/07/29 14:43:02 UTC] [INFO] Current working directory is /data/data/com.termux/files/home/go/src/github.com/mattermost/platform
[2017/07/29 14:43:02 UTC] [INFO] Loaded config file from /data/data/com.termux/files/home/go/src/github.com/mattermost/platform/config/config.json
[2017/07/29 14:43:02 UTC] [INFO] Server is initializing...
[2017/07/29 14:43:02 UTC] [INFO] Pinging SQL master database
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xb655a148]

goroutine 2131 [running]:
sync/atomic.addUint64(0x9629394c, 0x1, 0x0, 0x970f5140, 0x961db524)
	/data/data/com.termux/files/usr/lib/go/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/mattermost/platform/store.(*SqlSupplier).GetReplica(0x96293930, 0xb65c58e8)
	/data/data/com.termux/files/home/go/src/github.com/mattermost/platform/store/sql_supplier.go:258 +0x34
github.com/mattermost/platform/store.SqlSystemStore.SaveOrUpdate.func1(0xb75b3a38, 0x96293930, 0x96f21c80, 0x96f54140)
	/data/data/com.termux/files/home/go/src/github.com/mattermost/platform/store/sql_system_store.go:54 +0x24
created by github.com/mattermost/platform/store.SqlSystemStore.SaveOrUpdate
	/data/data/com.termux/files/home/go/src/github.com/mattermost/platform/store/sql_system_store.go:66 +0x6c
exit status 2
```

#### Possible fixes
This seems to be related to https://github.com/golang/go/issues/13868 (see more explanation [here](https://golang.org/pkg/sync/atomic/#pkg-note-BUG)).

Here is a quick and dirty fix that successfully avoids the crash:
```diff
diff --git a/store/sql_supplier.go b/store/sql_supplier.go
index 0f4ab8380..d6dd5458d 100644
--- a/store/sql_supplier.go
+++ b/store/sql_supplier.go
@@ -86,10 +86,10 @@ type SqlSupplierOldStores struct {
 }
 
 type SqlSupplier struct {
+       rrCounter      int64
        master         *gorp.DbMap
        replicas       []*gorp.DbMap
        searchReplicas []*gorp.DbMap
-       rrCounter      int64
        srCounter      int64
        oldStores      SqlSupplierOldStores
 }
```

**Comment by AmadeusSG** [comment]
Thank you for finding the error, have been searching for the cause for quite some time. 
There is also another place to set that quick and dirty fix: 
```
<mattermost/platform path>/app/web_hub.go
line 29:
type Hub struct {
        connectionCount int64
        connections     []*WebConn
        //connectionCount int64
        connectionIndex int
        register        chan *WebConn
        unregister      chan *WebConn
        broadcast       chan *model.WebSocketEvent
        stop            chan string
        invalidateUser  chan string
        ExplicitStop    bool
        goroutineId     int
}
```

This is for the site and team statistics to work normally, otherwise it'll just show `Loading` instead.

**Comment by lindy65** [comment]
@AmadeusSG @Rudloff 

Would either of you be interested in submitting a PR to fix this?

**Comment by AmadeusSG** [comment]
I'll submit a PR within 24 hours. New to open source contributing, just submitted CLA, and recloned the latest `master` branch to push to `PLT-7055` branch.

**Comment by lindy65** [comment]
That sounds great @AmadeusSG!  Thank you so much :)  

Please let us know if there's anything we can help with

**Comment by AmadeusSG** [comment]
May I know how long I need to wait for push access?

**Comment by lindy65** [comment]
Hi @AmadeusSG,

As you've already signed the CLA (I've confirmed it's received) you can submit a PR.  It will go through a review process by our devs.

**Comment by AmadeusSG** [comment]
The problem is that I can't push to `PLT-7055` due to 403 Forbidden error code, so can't submit a PR, unless I'm missing a step or two.

**Comment by lindy65** [comment]
Ah, I see... I'll ask one of the secs to help you on this,

**Comment by AmadeusSG** [comment]
I've resolved it - I forgot to fork it to my account. I've just submitted a PR, please check.

**Comment by lindy65** [comment]
Pleased you resolved the problem... 
Yes, I see your PR and our devs will review and give you feedback. 
Thank you for your pull request 😀
