### ISSUE TITLE
[Question]/[Issue] SMTP Mail Cache

### ISSUE THREAD

**Issue by vrenjith** [mattermost/platform#7057]
If the SMTP server is not reachable, is there a mechanism in Mattermost to cache the outgoing mails and flush them when the server is available again?

**Comment by prixone** [comment]
Hi @vrenjith I've looked around the code and I don't see any sort of method storing or caching those, I will assume it was initially done to rely on the mail server for queue and deliver-ability. I've further asked to Mattermost to confirm my answer, but I will assume in this case you would have to open a feature request at https://mattermost.uservoice.com/ for that. Once it reach 10 or more votes it will be considered for implementation.

Alternatively if you're a developer your self and want to contribute you could suggest that to the team and pick on the Help Wanted for it.

Once I have a quote from Mattermost I will update it here.

**Comment by lindy65** [comment]
Hi @vrenjith 

I'll close this issue off here.  Feel free to open a feature request as per `prixone's` suggestion above :)
