### ISSUE TITLE
Add support for custom header/footer on webpages

### ISSUE THREAD

**Issue by Caligatio** [mattermost/platform#707]
It would be extremely useful for a straight-forwarded way of adding a custom header and footer to the static HTML pages.  For instance, my employer requires some boilerplate legalese on every internal webpage and currently this would require editing nearly every HTML file in /web/templates.  Similarly it would be nice to be able to add badging to the header of every page with a logo or something along those lines.

Currently I'm somewhat achieving this by using a nginx reverse proxy with sub_filter but it's hacky and causes the vertical spacing to get off.

I should note that there is something similar already in place, [head](https://github.com/mattermost/platform/blob/master/web/templates/head.html) and [footer](https://github.com/mattermost/platform/blob/master/web/templates/footer.html), but head is actually the HTML &lt;head&gt; object and footer isn't used everywhere.

**Comment by it33** [comment]
Hi @Caligatio, thanks for the feature idea!

Could we as your help to add this to the [Mattermost feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be upvoted? 

Through the feature idea forum you'll be able to discuss the feature with other interested users, and receive notifications as the feature moves from an idea to [planned](https://mattermost.uservoice.com/forums/306457-general/status/1588357), as implementation is [started](https://mattermost.uservoice.com/forums/306457-general/status/1588360) and implementation its [completed](https://mattermost.uservoice.com/forums/306457-general/status/1588363). 

Alternatively, some features ideas may be set to [accepting pull requests](https://mattermost.uservoice.com/forums/306457-general/status/1588438) from the community for completion, and you'll receive alerts on that as well. 

The more specificity and detail you can include in your feature idea post, the easier it will be for like-minded users to upvote and for the core team and external contributors to think through implementation. 

Highly appreciate your interest in improving Mattermost.
