### ISSUE TITLE
blank page on webclient 4.0.2 after changing language ang logout

### ISSUE THREAD

**Issue by eburghar** [mattermost/platform#7075]
#### Summary

We hit a bug today which impacted one of our user on mattermost 4.0.2 (4.0.0 and 4.0.1 have the same behavior). After login (through gitlab), the user receives a grey page with a never ending 3 cycling dots. The mobile application is working normally. Apparently this is related to changing the language.

#### Steps to reproduce

Change user language settings to `fr`, then logout and try login again.

#### Expected behavior

Have access to the application in the chosen language even after logout.

#### Observed behavior (that appears unintentional)

An exception is thrown in the browser

```
jQuery.Deferred exception: invalid language tag:  o@https://mm.local.lan/static/main.70e5db8d2b39ede5feef.js:1:650627
```

#### Possible fixes

Change the locale setting to `en` in the database, and refresh page.

**Comment by lindy65** [comment]
Thanks for your feedback @eburghar,

We have a [ticket](https://mattermost.atlassian.net/browse/PLT-7231) for fixing this issue in progress at the moment.

**Comment by lindy65** [comment]
I'll close this issue off here as we can track via the Jira ticket above.
