### ISSUE TITLE
GitLab integration fails after upgrading to 9.3.8

### ISSUE THREAD

**Issue by lambertjosh** [mattermost/platform#7089]
We are trying to troubleshoot an issue that began with Omnibus GitLab 9.3.8. Essentially after this release, when you try to create a Mattermost group from within GitLab, it fails. 

This GitLab issue has more details, but was hoping folks from Mattermost could assist in investigating as well. 

https://gitlab.com/gitlab-org/gitlab-ce/issues/31835

Note that 9.3.8 included a Mattermost version bump to 3.10.2 (6ebf54).

**Comment by jasonblais** [comment]
Thanks @lambertjosh for the report! I've nudged one of our developers to help take a look.

We'll keep you updated.

**Comment by jasonblais** [comment]
Actually @lambertjosh, just to clarify, when you say `Mattermost group creation fails`, what do you mean by "group"?

Do you mean a "Mattermost team" or a "Mattermost channel"?

Or is this in some way related GitLab groups https://docs.gitlab.com/ce/user/group/index.html

**Comment by lambertjosh** [comment]
Hi @jasonblais, sorry for the confusion. Within GitLab we have the feature to automatically create a Mattermost Team when you create a GitLab group.

When you do this, both the Group and Team creation fail.

<img width="712" alt="screen shot 2017-08-01 at 9 19 52 pm" src="https://user-images.githubusercontent.com/25085430/28853557-57e36a0a-76ff-11e7-9a15-6c7ab17c2ada.png">

**Comment by it33** [comment]
Hi @lambertjosh is there anything in the Mattermost log files when this error happens?

**Comment by lambertjosh** [comment]
@it33 thanks for taking a look. Unfortunately the only real entry in the Mattermost log files is:

AuthorizeOAuthUser: Invalid state, 

One of our engineers has done some deeper traces, and it looks like we are getting a 307 back when trying to exchange the `code` for an `access_token`.

https://gitlab.com/gitlab-org/gitlab-ce/issues/31835#note_36471243

**Comment by jasonblais** [comment]
Hey @lambertjosh, I replied to the GitLab thread https://gitlab.com/gitlab-org/gitlab-ce/issues/31835#note_36598866

**Comment by jasonblais** [comment]
The corresponding GitLab issue has now been resolved: https://gitlab.com/gitlab-org/gitlab-ce/issues/31835
