### ISSUE TITLE
Feature Request: Integrate with GitLab web hooks

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#711]
Is there any plan to support gitlab event(issue, merge request, push, tag and etc) to post messages to mattermost channel?

just like how gitlab and slack works with. https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/integration/slack.md

Or am I missing some document anywhere?

**Comment by coreyhulen** [comment]
A PR (https://github.com/mattermost/platform/pull/715) has been submitted for this feature.

**Comment by coreyhulen** [comment]
The PR has been merged and is now in master.

**Comment by chengweiv5** [comment]
Hi @coreyhulen, as I see #715 implemented incomming hooks which define a payload format, as I know gitlab currently send web hook in its own format, so I think there is still a big gap to use web hooks between gitlab and mattermost, am I right? I think a plugin, for gitlab or for mattermost, is missing.
