### ISSUE TITLE
mobile layout showing names between each message

### ISSUE THREAD

**Issue by mmclau14** [mattermost/platform#7111]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
when only the chat roll is visible (mobile / tablet) names show up between each message wasting unnecessary space

#### Steps to reproduce
simply resize the browser until the sidebars disappear. names will appear between messages in message groups that are > 1 message

#### Expected behavior
chat roll should look basically the same (no extra names)

#### Observed behavior (that appears unintentional) 
names (duplicates) are placed between messages in a group

#### Possible fixes
do not render the name in message groups
if this is because on mobile messages can appear longer, then there is probably a way to remind the person reading who wrote that item a different way / different ui

**Comment by lindy65** [comment]
Hi @mmclau14,

Thank you for your feedback,

Can you tell me which version of the mobile app you are seeing this on?  The "Mattermost Beta" or "Mattermost Classic" app?  And on which platform - Android or iOS?

Currently, tablets are not supported but we plan to include them on the roadmap soon.

Thanks!

**Comment by mmclau14** [comment]
so i am actually just seeing this on my desktop app. I'm on a mac osx sierra 10.12.6 (16G29) and all i had to do was resize it to 640px wide

**Comment by lindy65** [comment]
Hi @mmclau14,

Sorry, it seems I misunderstood.  Are you using the desktop app on Mac but shrinking it to mobile view?

And I'm not clear whether you mean resizing to 640px wide has fixed the issue for you or whether shrinking to that size causes the issue?

**Comment by lindy65** [comment]
Hi @mmclau14, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by mmclau14** [comment]
yeah. so i'm resizing to half of my screen so i can do something else in the other half.

**Comment by lindy65** [comment]
Thanks for the feedback @mmclau14,

Please could you post a screenshot here so I can chat to one of the product managers about the issue?

**Comment by lindy65** [comment]
Hi @mmclau14, 

Circling back on this...  Having chatted to the product team, it seems that changing the way names are currently displayed in mobile view is a feature suggestion and not a bug.

Could we have your help opening a feature suggestion on our [forum](https://mattermost.uservoice.com/forums/306457-general) where you and others can vote to increase the popularity of the suggestion.  The more votes a suggestion gets, the more chance it has of making it into the product.

Thanks!
