### ISSUE TITLE
[Help Wanted] [PLT-7307] Use symbols in keyboard shortcuts dialog on Mac, instead of "ALT", "CMD"

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#7112]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7307)

Observed:
![image](https://user-images.githubusercontent.com/13119842/28934115-bf40cb62-784d-11e7-8b7c-7eb5363c4904.png)

Expected: ALT and CMD buttons use the keyboard symbols on Mac. This seems to be the standard, and is also how the shortcut is displayed on the Switch Channels button on the channel sidebar.

**Comment by fraziern** [comment]
I can tackle.

**Comment by jasonblais** [comment]
ah sorry @fraziern -- this change was actually incorporated into https://github.com/mattermost/platform/pull/7064

I forgot to close this issue. Would there be another one you're interested taking a look?
