### ISSUE TITLE
[Help Wanted] [PLT-7285] Change "Cancel" to "Close" in Account Settings > Security > OAuth App page

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#7114]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7285)

Change "Cancel" to "Close" in Account Settings > Security > OAuth App page

"Cancel" doesn't really make any sense, and is inconsistent with the User Access Tokens page.

![image](https://user-images.githubusercontent.com/13119842/28933926-f9e26cd6-784c-11e7-9143-89264a4e0ac0.png)

**Comment by 94117nl** [comment]
I would like to start working on this

**Comment by jasonblais** [comment]
Go for it @94117nl! 👍

**Comment by tejasbubane** [comment]
I think this one can be closed.

**Comment by lfbrock** [comment]
thanks @tejasbubane! Closed.
