### ISSUE TITLE
Deleted Message Does Not Delete Attachment from the Server

### ISSUE THREAD

**Issue by nashbrydges** [mattermost/platform#7139]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
I created a Mattermost installation and created test channel. Added a message which included a sample file attachment (Excel spreadsheet). When I deleted the message, the attachment remains on the server.

#### Steps to reproduce
As stated in Summary, this is the case no matter who creates the message and deletes it. 

#### Expected behavior
A deleted message with an attachment SHOULD delete the included attachment. Any other message linking to this deleted message should contain a "Deleted message" warning and attachment should not be available.

#### Observed behavior (that appears unintentional) 
A message with an attachment where the message is deleted does NOT remove the attachment from the server. This is a massive fail in terms of implementation as you are dealing with a forever increasing size requirement. One where attachments, regardless of whether they are needed or not remain on the server and finding them is nearly impossible on a production system since folder names are not intuitively named.

#### Possible fixes
Sorry, I do not have the skills to provide this detail other than describe the issue and expected behaviour.

Mattermost Version = 4.0.1
Server = Ubuntu 16.04.2
Database = MySQL
![proof_that_attachment_remains_on_server_after_message_delete](https://user-images.githubusercontent.com/25962967/29036178-5916351c-7b6c-11e7-86e1-fbb1cdce82ad.png)

**Comment by prixone** [comment]
I don't think that is unintentional because all the said "delete" feature of Mattermost is a soft delete, that means it doesn't completely delete anything it just hides it.

So if you go to your database directly and search for the message you deleted you will find it there along with the DeleteAt which indicates when it was deleted.

So the same goes for the file, access to the file from Mattermost is removed but it does not physically delete the file.

**Comment by nashbrydges** [comment]
Thanks @prixone . I'll instead add my vote for this option in the recommended features/improvements.

**Comment by DareDareHub** [comment]
@nashbrydges 
> The problem is that currently the mattermost installation will grow indefinitely.

SO TRUE... 
In a time when space is going to be the next challenge, a feature to be able to delete files on the server side seems to be a must have.
