### ISSUE TITLE
Trying to change other user's profile image doesn't work (the api docs says it should when you have permission)

### ISSUE THREAD

**Issue by giladgd** [mattermost/platform#7143]
#### Summary
When trying to change other user's profile image as documented in api.mattermost.com ([link](https://api.mattermost.com/#tag/users%2Fpaths%2F~1users~1%7Buser_id%7D~1image%2Fpost)) via POST `/users/{user_id}/image` from a user with the `system_admin` role/permission or the `edit_other_users` permission it doesn't work.

#### Steps to reproduce
1. Authenticate using the api into a `system_admin` user.
2. Get some other user's `user_id`.
3. Make a http request to `/api/v4/users/{user_id_of_the_other_user}/image` [as described in the docs](https://api.mattermost.com/#tag/users%2Fpaths%2F~1users~1%7Buser_id%7D~1image%2Fpost).
4. The profile image of the other user wasn't changed.

#### Expected behavior
The user with the `user_id` specified in the url should receive the new profile image.

#### Observed behavior (that appears unintentional)
The profile image of the session user has changed.
(Session user - the user used to authenticate with to make the http request)

#### Possible fixes
I see that [in this code](https://github.com/mattermost/platform/blob/master/api4/user.go#L270) the `user_id` from the session is used instead of getting it from the url.

**Comment by lfbrock** [comment]
Hi @giladgd - this seems like it might be a bug, would you be interested in making a pull request to fix it?

**Comment by lindy65** [comment]
Hi @giladgd,

I'll close this issue off now as we can track via the Jira ticket link above.

**Comment by giladgd** [comment]
I'll try to fix it, although I'm new to golang

**Comment by giladgd** [comment]
I just saw it was already fixed.
Thank you :)
