### ISSUE TITLE
oauth redirect_uri mismatch

### ISSUE THREAD

**Issue by smoebody** [mattermost/platform#7152]
#### Summary
Login with Gitlab-Oauth fails, presumably due to differing `redirect_uri`s

#### Observed behavior (that appears unintentional) 
When logging in via gitlab-oauth i can see the following log messages from gitlab:

1. This request happens after clicking the *gitlab* button
```
Started GET "/oauth/authorize?response_type=code&client_id=8bec2668203d747e3fa08d27d16f0a8a895b8448fd8ffe4dceaf1815a0d1242f&redirect_uri=https%3A%2F%2Fchat.metaccount.de%3A443%2Fsignup%2Fgitlab%2Fcomplete&state=eyJhY3Rpb24iOiJsb2dpbiIsInRva2VuIjoiZWd1N3BramZraHk2c2Y5ZmN5OXVwcWlmZmVhaXdvbXNrbXo1b3pycmY0a3N4anU4eHJhNzNvYXl3ZmE3ZG1xaCJ9" for 172.23.0.13 at 2017-08-08 12:44:08 +0000
Processing by Oauth::AuthorizationsController#new as HTML
  Parameters: {"response_type"=>"code", "client_id"=>"8bec2668203d747e3fa08d27d16f0a8a895b8448fd8ffe4dceaf1815a0d1242f", "redirect_uri"=>"https://chat.metaccount.de:443/signup/gitlab/complete", "state"=>"eyJhY3Rpb24iOiJsb2dpbiIsInRva2VuIjoiZWd1N3BramZraHk2c2Y5ZmN5OXVwcWlmZmVhaXdvbXNrbXo1b3pycmY0a3N4anU4eHJhNzNvYXl3ZmE3ZG1xaCJ9"}
```
_as you can see the redirect_uri is `https://chat.metaccount.de:443/signup/gitlab/complete`. be aware of the additional portnumber, which seems not to be configured anyware._

2. This request is done from the browser after granting the auth-request in gitlab
```
Started POST "/oauth/authorize" for 172.23.0.13 at 2017-08-08 12:44:11 +0000
Processing by Oauth::AuthorizationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ciYh0rBzM3TS6iffJuG2IOyNXqFI0JKNHAcrWlgKdONneI8urrhjImPE+JCZhdN+vEFeMfG+Pu8jcSOUVcIWnA==", "client_id"=>"8bec2668203d747e3fa08d27d16f0a8a895b8448fd8ffe4dceaf1815a0d1242f", "redirect_uri"=>"https://chat.metaccount.de:443/signup/gitlab/complete", "state"=>"eyJhY3Rpb24iOiJsb2dpbiIsInRva2VuIjoiZWd1N3BramZraHk2c2Y5ZmN5OXVwcWlmZmVhaXdvbXNrbXo1b3pycmY0a3N4anU4eHJhNzNvYXl3ZmE3ZG1xaCJ9", "response_type"=>"code", "scope"=>"api", "nonce"=>""}
```
_here as well the `redirect_uri` has the port number *443* in it_

3. This request comes from mattermost after performing the redirect invoked by gitlab
```
Redirected to https://chat.metaccount.de/signup/gitlab/complete?code=615c6522e08777db91848cbe53add06ea05b1a1d863fe55088fc2cfd9cbd9a26&state=eyJhY3Rpb24iOiJsb2dpbiIsInRva2VuIjoiZWd1N3BramZraHk2c2Y5ZmN5OXVwcWlmZmVhaXdvbXNrbXo1b3pycmY0a3N4anU4eHJhNzNvYXl3ZmE3ZG1xaCJ9
Completed 302 Found in 44ms (ActiveRecord: 18.1ms)
```
_ it contains the code, nothing special here_

4. this is the request by mattermost to fetch the token with the provided code
```
Started POST "/oauth/token" for 172.23.0.8 at 2017-08-08 12:44:11 +0000
Processing by Doorkeeper::TokensController#create as JSON
  Parameters: {"client_id"=>"8bec2668203d747e3fa08d27d16f0a8a895b8448fd8ffe4dceaf1815a0d1242f", "client_secret"=>"[FILTERED]", "code"=>"[FILTERED]", "grant_type"=>"authorization_code", "redirect_uri"=>"https://chat.metaccount.de/signup/gitlab/complete"}
Completed 401 Unauthorized in 20ms
```
_in this request the redirect_uri is missing the port number, which IMHO is the reason the auth-process is failing with error 401 Unauthorized_
_
#### Possible fixes
make sure, the redirect_uri is always identical

#### Additional
I am using Gitlab 9.4.3, provided as docker-image by https://github.com/sameersbn/docker-gitlab and
mattermost 4.0.2 provided as docker-image by https://github.com/mattermost/mattermost-docker

**Comment by lfbrock** [comment]
Hi @smoebody - are you using Mattermost behind nginx? 

If so, can you check the `X-Forwarded-Proto` is set to https? (Looks like others have had similar issues [here](https://github.com/mattermost/platform/issues/6489#issuecomment-305917377) so wondering if it's the same thing.)

**Comment by smoebody** [comment]
It is a bit more complicated. Yes, mattermost is used behind an nginx reverse-proxy and the `X-Forwarded-Proto` is set to `https`.
But the network between gitlab and mattermost is dedicated to this two services and they communicate in plain http and without any nginx reverse-proxy.

i'm almost certain that the differing `redirect_uri` is responsible for this issue. why are they different afterall?

**Comment by enahum** [comment]
Have you checked that the SiteURL setting in your config.json matches?

**Comment by smoebody** [comment]
Thanks. That was it! It had the port number in it. After removing and restarting it worked flawlessly.

closing
