### ISSUE TITLE
Token auth broken

### ISSUE THREAD

**Issue by nomorebugs** [mattermost/platform#7163]
#### Summary
MM version: 4.0.0
Gitlab-ce version: Version: 9.4.3-ce.0 (Omnibus Package Debian)

Using token auth is not working any more (only session auth).

#### Steps to reproduce

Follow auth like in docs:
(account not created by gitlab sso)

```
curl -i -d '{"login_id": "email@my_mail.local","password": "my_pw"}' https://somemm.org/api/v4/users/login
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 09 Aug 2017 13:56:20 GMT
Content-Type: application/json
Content-Length: 543
Connection: keep-alive
Set-Cookie: MMAUTHTOKEN=1k4unghaztd4zxr8ss3g76hd4w; Path=/; Expires=Fri, 08 Sep 2017 13:56:20 GMT; Max-Age=2592000; HttpOnly; Secure
Set-Cookie: MMUSERID=khgjdb8bupdbdyy18xq586fqea; Path=/; Expires=Fri, 08 Sep 2017 13:56:20 GMT; Max-Age=2592000; Secure
Token: 1k4unghaztd4zxr8ss3g76hd4w
X-Request-Id: h9rfi5b1438hpqioegeichuaaw
X-Version-Id: 4.0.0.4.0.2.9043495ca31f3603079af3f236a22170.false
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload;
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none

{"id":"khgjdb8bupdbdyy18xq586fqea","create_at":1485947034396,"update_at":1502197066725,"delete_at":0,"username":"mattermail","auth_data":"","auth_service":"","email":"email@my_mail.local","nickname":"","first_name":"","last_name":"","position":"","roles":"system_user","notify_props":{"channel":"true","desktop":"all","desktop_sound":"true","email":"true","first_name":"false","mention_keys":"mattermail,@mattermail","push":"mention"},"last_password_update":1485947034396,"last_picture_update":1485948006520,"locale":"en"}
```

```
curl -i -H 'Authorization: Bearer 1k4unghaztd4zxr8ss3g76hd4w' https://somemm.org/api/v4/users/me
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Wed, 09 Aug 2017 13:58:08 GMT
Content-Type: application/json
Content-Length: 186
Connection: keep-alive
Expires: 0
X-Request-Id: 9mhzxj7bzjnafp8iitpis87n5h
X-Version-Id: 4.0.0.4.0.2.9043495ca31f3603079af3f236a22170.false

{"id":"api.context.session_expired.app_error","message":"Invalid or expired session, please login again.","detailed_error":"","request_id":"9mhzxj7bzjnafp8iitpis87n5h","status_code":401}
```

#### Expected behavior

- api calls with token auth working

#### Observed behavior (that appears unintentional) 

- see above

**Comment by jasonblais** [comment]
Thanks @nomorebugs for the report. Which version did it used to work (either Mattermost or GitLab Omnibus version)

**Comment by MishkinBerteig** [comment]
Yikes!!! Just installed this, and spent the last 2 hours struggling with this.  Trying to use Postman to test the APIs on our new installation (4.0.3, AWS Elastic Beanstalk with Docker).  Same problem exactly.  Token authentication does not work.  The initial login call works, and calls that do not require authentication work (e.g. creating a new user), but everything else fails.

**Comment by jasonblais** [comment]
Hmm, thanks for letting us know @MishkinBerteig. 

Was Mattermost v4.0.3 the first version you installed?

**Comment by MishkinBerteig** [comment]
Yes - it was the first version we installed.  We just started working on it all today, late this morning Eastern Time.

**Comment by jasonblais** [comment]
@pichouk @prixone @sousapro Wondering if you guys would have any thoughts on the above errors?

**Comment by MishkinBerteig** [comment]
Hypothesis: in Postman, when doing a /users/login POST, the headers returned include two cookies that have immediate expire dates... perhaps this is a reflection of a calculation problem on the back end in which the Token returned is set to expire immediately instead of after some reasonable amount of time.  Here are the headers from an example login attempt that seems to work properly:

```
Access-Control-Allow-Origin →
Connection →keep-alive
Content-Length →517
Content-Type →application/json
Date →Sat, 12 Aug 2017 02:07:06 GMT
Server →nginx/1.13.3
Set-Cookie →MMAUTHTOKEN=e8fok7wytbrcjmm767nz81drky; Path=/; Expires=Mon, 11 Sep 2017 02:07:06 GMT; Max-Age=2592000; HttpOnly
Set-Cookie →MMUSERID=dkrdhnbob3rdux6ireurdr147w; Path=/; Expires=Mon, 11 Sep 2017 02:07:06 GMT; Max-Age=2592000
Token →e8fok7wytbrcjmm767nz81drky
X-Ratelimit-Limit →101
X-Ratelimit-Remaining →100
X-Ratelimit-Reset →1
X-Request-Id →krq6urhkwtd5iggac9zsd8hoqc
X-Version-Id →4.0.0.4.0.3.2d97b4e074a37ee0f620ea91a507e34d.false
```

**Comment by MishkinBerteig** [comment]
Oh Lord.  I inserted a colon where there shouldn't have been one.  My mistake.  :-(

However, along the way, I discovered the new EnableUserAccessTokens config setting defaults to false, I changed it to true through an environment variable (MM_SESSIONSETTINGS_ENABLEUSERACCESSTOKENS) and that may help the other person who opened this ticket.  Based on looking at the code, this was also a problem that I was having.

**Comment by nomorebugs** [comment]
@MishkinBerteig Thx for mentioning the new configuration option. I will have a look. For now I am calling the API with session auth. But it breaks mattermail service.

@jasonblais I don't know the previous version I updated from, but it can be only like one to two months old.

**Comment by lindy65** [comment]
Hi @nomorebugs, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
