### ISSUE TITLE
Support Google Auth as 2FA on Team Edition

### ISSUE THREAD

**Issue by cybershambles** [mattermost/platform#7166]
#### Summary
2FA is basic security

#### Steps to reproduce
2FA is just missing from the account settings

#### Expected behavior
Google auth second factor enabled in accounts settings

#### Observed behavior (that appears unintentional)
Google auth second factor not available to users.

**Comment by lindy65** [comment]
Hello @cybershambles,

Thank you for your feedback.

2FA is available in Enterprise Edition.  If you'd like to request a trial licence for your corporation, you can do so here: https://about.mattermost.com/trial/

**Comment by sbrl** [comment]
Hey, @lindy65.

I agree with @cybershambles here. In today's world there are more breaches than ever. A large number of small groups without the money to spend on an enterprise-grade chat solution rely on Mattermost as a primary meeting place for their communities. To this end, it is _not cool_ denying people a basic step they could potentially take to keep their accounts secure.
