### ISSUE TITLE
Mattermost continuously reloads on Chrome after upgrade

### ISSUE THREAD

**Issue by andreacappelli** [mattermost/platform#7176]
#### Summary
After upgrading to Mattermost 4.0.2 every Chrome client already logged in start to reload the page until cookies are cleared and a new session is started

#### Steps to reproduce
1) Setup a 4.0.0 instance
2) login with Chrome
3) stop mattermost
4) upgrade to 4.0.2
5) start mattermost
6) refresh chrome

#### Expected behavior
After upgrading already connected client should reload the page once and then start to use the service

#### Observed behavior (that appears unintentional) 
The web page start to reload, in the console we can see "Updated version detected, reload" (not completely sure about the message, I was not able to tak a screenshot and teh relod rate was quite high)

This happens only with Chrome (not Firefox) on many OS (Ubuntu, MacOS Sierra) after mattermost upgrade

With release 4.0.2 this happen also when configuration changes and the service is reloaded

#### Possible fixes
Didn't know

**Comment by lfbrock** [comment]
Hi @andreacappelli - are you still seeing this issue? Is it happening for everyone on the server using Chrome?

**Comment by andreacappelli** [comment]
Hi @lfbrock I upgraded to 4.1.0 as soon as it was released and after the upgrade the issue seems gone

Every user had to logout and then clean cookies, but after that nobody reported problems

**Comment by lfbrock** [comment]
Okay great, well I'm glad it's sorted out - going to close the GitHub issue, and will re-open if other people hit similar problems
