### ISSUE TITLE
Database password routinely dumped in cleartext to logs

### ISSUE THREAD

**Issue by alerque** [mattermost/platform#721]
The Mattermost logger currently has a very unsafe habit of dumping the database password in clear text to the log file. E.g.

> [2015/09/19 07:12:09 UTC] [INFO] Pinging sql master database at 'mattermost:*******@unix(/run/mysqld/mysqld.sock)/mattermost?charset=utf8mb4,utf8'

(Note I have manually starred out the database password from my instance, but the line I copied had the full cleartext password where I have 8 *'s above.)

Not only does this turn up in the dedicated `mattermost.log` file but it ends up in the systemd journal which is definitely not a safe place to be putting passwords. This line of the config file should be filtered before being dumped to the log. It _should_ always be safe to copy log entries. Of course giving away hostnames, ports, and configuration details is always something do do carefully, but these lines should not have raw secret credentials.

**Comment by coreyhulen** [comment]
Thanks for the bug report.  This has been fixed in master with https://github.com/mattermost/platform/pull/724
