### ISSUE TITLE
Ubuntu systemd daily apt download activities stop the Mattermost service

### ISSUE THREAD

**Issue by theriverman** [mattermost/platform#7223]
#### Summary
Ubuntu systemd daily apt download activities stop the Mattermost service.

#### Steps to reproduce
It is not reproducible manually except that you manually issue the scripts I guess.
The problem occurs in my production environment, so I cannot do trial and error right now.

`root@my-company:/home/# lsb_release -a`
`No LSB modules are available.`
`Distributor ID: Ubuntu`
`Description:    Ubuntu 16.04.3 LTS`
`Release:        16.04`
`Codename:       xenial`

`mattermost@my-company:/opt/mattermost$ bin/platform version`
`Version: 4.0.0`
`Build Number: 4.0.3`
`Build Date: Wed Aug  9 18:46:16 UTC 2017`
`Build Hash: 737b46823fc8f59e9aa19fdce5533b8edb1f7f24`
`Build Enterprise Ready: false`
`DB Version: 4.0.0`

#### Expected behavior
To describe my issue, let's read the excerpt from logs:

**SYSLOG**
> root@my-company:/var/log# cat /var/log/syslog | grep "Aug 16 06:32"
> Aug 16 06:32:04 my-company systemd[1]: Starting Daily apt upgrade and clean activities...
> Aug 16 06:32:18 my-company NetworkManager[1104]: <info>  [1502857938.7090] manager: kernel firmware directory '/lib/firmware' changed
> Aug 16 06:32:25 my-company systemd[1]: Reloading.
> Aug 16 06:32:25 my-company systemd[1]: Starting Daily apt download activities...
> Aug 16 06:32:25 my-company systemd[1]: Started ACPI event daemon.
> Aug 16 06:32:25 my-company systemd[1]: Stopping Mattermost...
> Aug 16 06:32:25 my-company systemd[1]: Stopped Mattermost.
> Aug 16 06:32:25 my-company systemd[1]: Stopped PostgreSQL RDBMS.
> Aug 16 06:32:26 my-company systemd[1]: Stopping PostgreSQL Cluster 9.5-main...
> Aug 16 06:32:27 my-company systemd[1]: Stopped PostgreSQL Cluster 9.5-main.

**MATTERMOST**
> mattermost@my-company:/opt/mattermost$ cat logs/mattermost.log | grep 2017/08/16
> [2017/08/16 06:32:25 CEST] [INFO] Stopped jobs
> [2017/08/16 06:32:25 CEST] [INFO] Stopping Server...
> [2017/08/16 06:32:25 CEST] [INFO] Closing SqlStore

#### Observed behavior (that appears unintentional) 
nginx threw error **502 Bad Gateway**

#### Possible fixes
The only fix was issuing the following commands:
`sudo service mattermost restart`
`sudo service nginx reload`

The only workaround I see right now is turning off the auto system update in `/etc/apt/apt.conf.d/20auto-upgrades` but I can't tell if this is a mattermost issue (faulty init.d script?) or an Ubuntu issue :(

**Comment by prixone** [comment]
Well, this is definitively not a mattermost issue or bug, but rather a Ubuntu issue and you might get a quicker help/response from the ubuntu commuty for example https://askubuntu.com/ or https://ubuntuforums.org/index.php.

A quick question which may be your case, when you reboot your server does mattermost auto start by default? If not I suspect you need to do:

```
sudo update-rc.d mattermost enable
sudo update-rc.d postgresql enable
```

So those services will start again once apt is done or the system is rebooted.

**Comment by lindy65** [comment]
Hi @theriverman, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by MattBred** [comment]
I also experienced this today. Ubuntu 16.04.
This is the install guide I followed: https://docs.mattermost.com/install/install-ubuntu-1604.html

Syslog:
```
Oct 24 06:05:32 chat systemd[1]: Starting Daily apt upgrade and clean activities...
Oct 24 06:05:42 chat systemd[1]: Reloading.
Oct 24 06:05:42 chat systemd[1]: Started ACPI event daemon.
Oct 24 06:05:42 chat systemd[1]: Stopping Mattermost...
Oct 24 06:05:42 chat systemd[1]: Stopped Mattermost.
Oct 24 06:05:42 chat systemd[1]: Stopping MySQL Community Server...
Oct 24 06:05:44 chat systemd[1]: Stopped MySQL Community Server.
```

And while MySQL restarted, Mattermost did not.

The `/lib/systemd/system/mattermost.service`

```
[Unit]
Description=Mattermost
After=network.target
After=mysql.service
Requires=mysql.service

[Service]
Type=simple
ExecStart=/opt/mattermost/bin/platform
Restart=always
RestartSec=10
WorkingDirectory=/opt/mattermost
User=mattermost
Group=mattermost
LimitNOFILE=49152

[Install]
WantedBy=multi-user.target
```

**Comment by wurst-hans** [comment]
Encountered this issue yesterday. Ubuntu 22.04. with Mattermost 7.40. Daily apt stopped Mattermost and MySQL, restarts MySQL but not Mattermost. It might be simple for you to say that it's a task related to Ubuntu. I've used [this](https://docs.mattermost.com/install/installing-ubuntu-2004-LTS.html?src=dl) manual for installation. Maybe the systemd script is faulty!?

**Comment by anx-ag** [comment]
Did you replace the postgresql targets in the mattermost systemd file as mentioned in the documentation you linked? Can you post the contents of your systemd unit files related to the mattermost service?
