### ISSUE TITLE
Reloading page makes it blank after some secs

### ISSUE THREAD

**Issue by S6066** [mattermost/platform#7242]
Sometimes I have a DNS error, or a Network Changed one, and I have to reload (Ctrl + R) the page.
When doing that, after some seconds the page becomes blank one second and reload again
I'm using Mattermost Desktop version 3.7.0, server is using 4.1.0
Video: https://youtu.be/pyeaz3hp5b4

**Comment by yuya-oc** [comment]
Basically, Mattermost webapp reload itself to refreshing caches when version mismatch is detected. If you have recently updated the server, possibly the mechanism might make something wrong.
As a known workaround, would you try using Ctrl+Shift+R (Clear Cache and Reload)?

**Comment by S6066** [comment]
When reloading without having the "network changed" or an error like that, the bug doesn't occur.
I tried deactivating and reactivating my wifi, and the bug still occurs with Ctrl+Shift+R.
(Had to press it twice because of a mistake, the webapp reloaded twice)

**Comment by yuya-oc** [comment]
@S6066 I think this issue should be tracked in the mattermost/desktop repository. So I created mattermost/desktop#573. Please use it for more feedback.

@jasonblais Would you close this one?
