### ISSUE TITLE
Regression: Load More Messages is not appearing in all channels

### ISSUE THREAD

**Issue by duncan-brown** [mattermost/platform#726]
Summary: The Load More Messages link is not appearing in all channels.

Steps to reproduce: Running mattermost from gitlab-ce-7.14.1+20150915013012.git.172.bc6f10f-ce.0.el6.x86_64.rpm create several channels and fill with text. 

Expected behavior: Every channel should have "Load More Messages" so that users can repeatedly click and see all message history back to the creation of the channel.

Observed behavior: Some channels have the "Load More Messages" link and messages can be retrieved back to the channel creation time. Others display the current messages and then the channel creation message at the top of the page and history is not retrievable.

The messages do exist in the database. The first messages in Town Square are:

```shell
-sh-4.1$  /opt/gitlab/embedded/bin/psql --port 5432 -h /var/opt/gitlab/postgresql -d mattermost_production
mattermost_production=# select id,channelid,createat,message from posts;
id             |         channelid          |   createat    |     message                                                                                 
 67pq3eeqhf83dp89h7fero5toy | h67msppcppn5pftfheiwwzc58y | 1442344242333 | Hello
 d39ssorycidbi8mqmch57qgrkr | h67msppcppn5pftfheiwwzc58y | 1442344851895 | Testing
 fqfhj7if4i8njkftjo3f8hwfje | h67msppcppn5pftfheiwwzc58y | 1442345524783 | Hi Duncan!
 8a9k5rybe7gixn9got413r56ne | h67msppcppn5pftfheiwwzc58y | 1442345532790 | test to larne
 3k9joao6rbdf3eqwphb48694hr | h67msppcppn5pftfheiwwzc58y | 1442345545808 | Hello again
 9ptuh8iqmigkxq8a5ayr8w9m6e | h67msppcppn5pftfheiwwzc58y | 1442345546197 | this is a test
 h6rkigkumtdtfngj43swums4zc | h67msppcppn5pftfheiwwzc58y | 1442345671677 | Another test
 rdd9pinh3bbptqnzxyjbti6zhy | h67msppcppn5pftfheiwwzc58y | 1442346549073 | hello
```

However when Town Square is viewed from a browser, the Load More Messages button is not visible and the user can't go back and find these messages (see attached screen shot).

<img width="1030" alt="screen shot 2015-09-20 at 9 17 32 am" src="https://cloud.githubusercontent.com/assets/11262902/9980891/83b36ae0-5f78-11e5-925b-69328d9ff0c8.png">

**Comment by it33** [comment]
Thanks @duncan-brown, highly appreciate the bug report, could you let us know what browser you're using?

**Comment by duncan-brown** [comment]
@it33 the problem appears on Chrome Version 45.0.2454.93 (64-bit), Safari Version 8.0.8 (10600.8.9), and Firefox 40.0.3 on OS X 10.10.5. Thanks for looking into this.

**Comment by duncan-brown** [comment]
On Chrome, I get this error message in the java console. It also looks like other features stop working (e.g. auto-completion of usernames).

<img width="571" alt="screen shot 2015-09-20 at 10 49 23 am" src="https://cloud.githubusercontent.com/assets/11262902/9981247/ea8d5da4-5f85-11e5-8eb8-bf243f7b6541.png">

**Comment by it33** [comment]
Hi @duncan-brown, we're wondering if your issue might be related to a websocket configuration issue. Do you see anything like [this](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/740) in your log files?

**Comment by duncan-brown** [comment]
I don't see any error like that in the logs:
```shell
[root@pycbc nginx]# pwd
/var/log/gitlab/nginx
[root@pycbc nginx]# grep "websocket connect err" gitlab_mattermost_access.log gitlab_mattermost_error.log error.log current 
[root@pycbc nginx]# 
```
Apparently the error appears intermittent, frustrating my attempts to debug. It has failed once today, but worked on three subsequent tries. Right now, Chrome can see to the beginning of Town Square with no problems.

**Comment by coreyhulen** [comment]
A lot of work has gone into the LHS, center and RHS panels.  Closing this as no repo.
