### ISSUE TITLE
Channel's display name cannot handle special characters

### ISSUE THREAD

**Issue by petramies** [mattermost/platform#727]
![special_chars](https://cloud.githubusercontent.com/assets/14278742/9983032/fef9ad9c-5ff8-11e5-8eca-b5f897cc1269.PNG)

**Comment by it33** [comment]
Hi @petramies, 

It seems the Display Name is showing special characters in your screenshot, did you mean the "Handle" is unable to display special characters? 

Also, "Handle" is not a great way for us to describe that field, it's actually the name used for the web address for the channel, and it'll be named "Channel URL" in the next release. 

Below is work in progress on the new UI to make this more clear: 

![screenclip 316](https://cloud.githubusercontent.com/assets/177788/9985691/cd16c1e2-5fe5-11e5-8418-dc22ba747194.png)

The URL will be automatically generated from non-special characters in the Display Name of a channel, and if the Display Name is all special characters the user will be prompted to enter a Channel Name that can be used as a URL

Does this address your issue?

**Comment by it33** [comment]
@petramies, thanks again for reporting the issue. If I'm interpreting it correctly I believe it's fixed in the Oct 2 release, please let us know if you still see it?
