### ISSUE TITLE
Mattermost doesn't fall back to default values for missing configuration settings, but raises panic

### ISSUE THREAD

**Issue by balasankarc** [mattermost/platform#7276]
Regarding: https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2377#note_38157608

### Problem
As per https://docs.mattermost.com/administration/config-settings.html, where it says 
> For any setting that is not set in config.json or in environment variables, the Mattermost server uses the default value as documented here.

if a setting isn't provided either in config.json or as environment variable, a default value will be used. However, upon testing I found out that that is not the case. For example, I deleted the "ListenAddress" key from config.json and tried to run mattermost using `sudo -u mattermost ./platform`, and was met with the following panic

```
panic: Invalid listen address for service settings Must be set.

goroutine 1 [running]:
github.com/mattermost/platform/utils.LoadConfig(0x134ac99, 0xb)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/utils/config.go:333 +0xc78
github.com/mattermost/platform/utils.InitAndLoadConfig(0x134ac99, 0xb, 0xc420048960, 0x10)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/utils/config.go:272 +0x61
main.runServer(0x134ac99, 0xb)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/cmd/platform/server.go:47 +0x50
main.runServerCmd(0x1aa9ea0, 0x1ad4a58, 0x0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/cmd/platform/server.go:42 +0xe0
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0x1aa9ea0, 0xc420010200, 0x0, 0x0, 0x1aa9ea0, 0xc420010200)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1aa9ea0, 0x1aac920, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0x1aa9ea0, 0xc4200001a0, 0xc4200001a0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/cmd/platform/mattermost.go:33 +0x2d
```
A few other configurations I have had similar experience are as follows
* ServiceSettings
  * ListenAddress
  * MaximumLoginAttempts
* TeamSettings
  * MaxUsersPerTeam
  * EnableUserCreation
* SqlSettings
  * MaxIdleConns
  * MaxOpenConns
* FileSettings
  * DriverName
  * PublicLinkSalt (Theoretically, this should be used only if EnablePublicLink (whose default value is `false`) is set to true.
* RateLimitSettings
  * PerSec
  * MemoryStoreSize

This is contradictory to the note given in the documentation and I assume this is a bug in the Mattermost codebase as I was able to delete several other configuration keys and Mattermost started without any issue. So this is happening with certain keys only.

### Possible solution
Make sure Mattermost uses default values for all the configuration settings if not found in config.json or via env variables.

/cc @esethna @jasonblais

**Comment by jasonblais** [comment]
Great question! I think that sounds like a bug, but have reached out to our developers to confirm,

**Comment by jasonblais** [comment]
Thanks again @balasankarc for the report. Have filed a ticket here: https://mattermost.atlassian.net/browse/PLT-7472

Would this be something you'd be interested helping fix, given you've already looked at this issue.

**Comment by jasonblais** [comment]
@balasankarc we have a PR for fixing this here: https://github.com/mattermost/platform/pull/7320

**Comment by balasankarc** [comment]
Thanks @jasonblais .
