### ISSUE TITLE
Docs mention wrong default value for EnableSignInWithUser

### ISSUE THREAD

**Issue by balasankarc** [mattermost/platform#7277]
As per https://docs.mattermost.com/administration/config-settings.html#enable-sign-in-with-username , the default value for `EnableSignInWithUser` is `false`. However, in the [shipped config.json file](https://github.com/mattermost/platform/blob/master/config/default.json#L128), it is `true`.

Is that actually a typo or doesn't that file list the default values? If it is a typo, I can open up a PR to fix it. :) But if I am mistaken about that file holding the default values, sorry for all the noise and feel free to close this issue.

/cc @esethna @jasonblais

**Comment by jasonblais** [comment]
@balasankarc You are correct, looks like that's a typo. The [config.json file](https://github.com/mattermost/platform/blob/master/config/default.json) contains the default values.

If you'd like to submit a pull request to fix it, that would be very helpful!

**Comment by balasankarc** [comment]
@jasonblais Opened https://github.com/mattermost/docs/pull/1452 for fixing.

**Comment by jasonblais** [comment]
Thank you!!

Also, I discussed this with a developer and https://github.com/mattermost/platform/blob/master/config/default.json actually doesn't contain the default values in release builds. A few of the settings are changed in release builds [here](https://github.com/mattermost/platform/blob/master/Makefile#L396). The first part surrounded by pipe characters in the sed command is the line in the config file and the second part is what it's replaced with.

The particular value for `EnableSignInWithUser` should be `true` however, thanks for submitting a fix for it.
