### ISSUE TITLE
Feature Request: UI - Notification: blink taskbar when new message has arrived

### ISSUE THREAD

**Issue by petramies** [mattermost/platform#728]
There are situations when I'm not near my computer and new message arrives. When I return to my computer, it would be nice if taskbar icon would blink by telling me that there are messages that I haven't read. 

This feature should be included in 'Send desktop notifications'-option.

**Comment by it33** [comment]
Hi @petramies , thanks for the feature idea!

Could we as your help to add this to the [Mattermost feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be upvoted? 

Through the feature idea forum you'll be able to discuss the feature with other interested users, and receive notifications as the feature moves from an idea to [planned](https://mattermost.uservoice.com/forums/306457-general/status/1588357), as implementation is [started](https://mattermost.uservoice.com/forums/306457-general/status/1588360) and implementation its [completed](https://mattermost.uservoice.com/forums/306457-general/status/1588363). 

Alternatively, some features ideas may be set to [accepting pull requests](https://mattermost.uservoice.com/forums/306457-general/status/1588438) from the community for completion, and you'll receive alerts on that as well. 

The more specificity and detail you can include in your feature idea post, the easier it will be for like-minded users to upvote and for the core team and external contributors to think through implementation. 

Highly appreciate your interest in improving Mattermost.

**Comment by it33** [comment]
Closing this for now, @petramies, if you do [open a feature idea in the forum for upvoting](https://mattermost.uservoice.com/forums/306457-general), please post back here?
