### ISSUE TITLE
Bug: Mixed content alerted on pasted images using http://

### ISSUE THREAD

**Issue by cybershambles** [mattermost/platform#7300]
![image](https://user-images.githubusercontent.com/7995198/29739257-9e2b90d8-8a7c-11e7-94ed-8ede0ff40926.png)

#### Summary
Firefox is alerting that mixed content is used on my https:// mattermost when somebody posts an image that is http://

#### Steps to reproduce
![image](https://user-images.githubusercontent.com/7995198/29739268-d8038946-8a7c-11e7-8cdb-1927d8a0f457.png)
paste link to image hosted in http://
![image](https://user-images.githubusercontent.com/7995198/29739271-e12e8b06-8a7c-11e7-8977-d9c05cccb861.png)

#### Expected behavior
No idea.. load the image in a way that doesn't make the browser sad?

**Comment by MusikPolice** [comment]
Is `puu.sh` your domain? Or is it the domain where the image was originally hosted? If the latter, it looks like when an image is pasted in to Mattermost, it isn't uploaded to the system, and instead, your browser just tries to expand the link by fetching it from the source. If that's the case, then there's not much we can do to fix it, unless we want to make pasting a URL to an image cause that image to be uploaded to Mattermost.

**Comment by hmhealey** [comment]
Hi @cybershambles. It's a known issue that posting plain http images causes that warning to be printed. We have [a ticket to proxy external images with Mattermost](https://mattermost.atlassian.net/browse/PLT-3383), but it hasn't seen much activity lately

@MusikPolice `puu.sh` is just an image hosting site.  Nothing special about it, but it is definitely 3rd party

**Comment by cybershambles** [comment]
1) Yes, third party
2) That's understandable.. thanks

**Comment by lindy65** [comment]
Hi @cybershambles,

I'll close this issue off for now and we can track via https://mattermost.atlassian.net/browse/PLT-3383

**Comment by K1LLUM1N471** [comment]
Hello,
I just verified that the mixed content "bug" still exists in version 5.20.1.

I guess the easiest solution is to suppress the preview of previewable content whose url prefix is HTTP.

Kind regards,
K1LLUM1N471

**Comment by hmhealey** [comment]
Hey @K1LLUM1N471. Do you have an image proxy enabled on your server? This warning will occur without one since the client has to load the image from the remote server directly.
