### ISSUE TITLE
Only Admin/Owner should be able to delete channel

### ISSUE THREAD

**Issue by mmarif4u** [mattermost/platform#7302]
I know it is discussed somewhere in other thread, but i cant find it.

Mattermost Team Edition as of now(4.1.0) have still delete channel for all users to click and wipe the whole channel out. I know it is/was stated that the channel will be archived instead of delete. 

But to me it should not be available to other users except Owner/Admin etc, it is literally a security flaw and should have better means to be addressed properly no matter EE or TE.

**Comment by lindy65** [comment]
Hi @mmarif4u 

Thank you for your feedback,

I think the thread you're looking for is [this one](https://forum.mattermost.org/t/how-to-add-a-policy-enabling-only-certain-people-to-delete-public-channels-and-private-groups/2838)?

**Comment by mmarif4u** [comment]
Hi @lindy65 

Thanks for the link, yup thats the one and i totally agree with @it33 .

**Comment by lindy65** [comment]
Awesome, thanks for letting me know :) I'll close this issue off here for now then.

**Comment by mmarif4u** [comment]
Hi @lindy65 

I don't understand, why close the issue here?. Is it not the right place for issues?, if so it is confusing to have many places for logging issues.

**Comment by lindy65** [comment]
Hi @mmarif4u,

Apologies, yes - this is the correct place for issues.  As your issue is the same as the issue I linked above, I closed this one and we can track via the original issue.  It just makes it easier to track similar issues in one place.
