### ISSUE TITLE
Is there a plan to implement a simple Slack-like native client?

### ISSUE THREAD

**Issue by medvednikov** [mattermost/platform#735]
That would be really, really useful.

For example, Rocket chat is using Electron:

https://github.com/RocketChat/Rocket.Chat.Electron

Thanks

**Comment by it33** [comment]
Hi @medvednikov, thanks for the feature idea!

[Quentin Nerden](https://mattermost.uservoice.com/users/87407974-quentin-nerden) shared a [similar idea](https://mattermost.uservoice.com/forums/306457-general/suggestions/8867134-add-a-app-for-desktops) in the [Mattermost Feature Idea forum](https://mattermost.uservoice.com/forums/306457-general). Please consider upvoting the ticket to add your support? 

Through the feature idea forum you'll be able to discuss the feature with other interested users, and receive notifications as the feature moves from an idea to [planned](https://mattermost.uservoice.com/forums/306457-general/status/1588357), as implementation is [started](https://mattermost.uservoice.com/forums/306457-general/status/1588360) and implementation its [completed](https://mattermost.uservoice.com/forums/306457-general/status/1588363). 

Alternatively, some features ideas may be set to [accepting pull requests](https://mattermost.uservoice.com/forums/306457-general/status/1588438) from the community for completion, and you'll receive alerts on that as well. 

The more specificity and detail you can include in your feature idea post, the easier it will be for like-minded users to upvote and for the core team and external contributors to think through implementation. 

If there are planned features that you or others in the community would like to explore implementing yourself to make a pull request, please let us know on the [Mattermost forums](http://forum.mattermost.org/). We would love to support your work. 

Highly appreciate your interest in improving Mattermost.
