### ISSUE TITLE
Feature Request: Ability to remove "Switch to [TEAM]" from main menu 

### ISSUE THREAD

**Issue by doublej42** [mattermost/platform#773]
I had trouble signing in with oauth and ended up creating a group /zjdyhb7hwfrejetyyp8dphe7gw/
This name (not the friendly name) shows in the menu when I am on any group.

Because of the length of this name the menu does not display on any other groups as the line "switch to zjdyhb7hwfrejetyyp8dphe7gw" is to large.

It would be nice to be able to destroy or leave this group but I am the only member.

**Comment by it33** [comment]
Hi @doublej42, thanks for the feedback! 

We've created a ticket to enable team owners to deactivate teams, which should address your issue. You can track its progress through this link: https://mattermost.atlassian.net/browse/PLT-365

Please re-open this ticket if you feel this issue should be handled a different way.
