### ISSUE TITLE
LDAP Intergration

### ISSUE THREAD

**Issue by Trozz** [mattermost/platform#78]
It would be great to have LDAP intergration

**Comment by kaychaks** [comment]
+1. 

LDAP integration is a must for it to be used inside enterprises. That would be a great differentiator from Slack as well. 

Would love to know if it's in the roadmap.

**Comment by acaranta** [comment]
+1 Agreed That would be brilliant for Enterprises and th eintegration of their already existing LDAP management DB ;)

**Comment by it33** [comment]
@Trozz , @kaychaks, @acaranta, it's definitely on the feature list and we're looking at different options on how to deliver this. It's a matter of when not if. 

Give us until end of next week to incorporate the early community feedback into our plans for next release and share with the community?

**Comment by acaranta** [comment]
done thx ;)

**Comment by fangpeishi** [comment]
Is it possible to release the commercial version with LDAP support? Looking  forward to it.

**Comment by redtux** [comment]
As I was just looking for the same: https://github.com/Crivaledaz/Mattermost-LDAP

**Comment by Jacq** [comment]
> As I was just looking for the same: https://github.com/Crivaledaz/Mattermost-LDAP

Are you still using this?, have you try other OAuth similar integrations?
