### ISSUE TITLE
Multiple Feature Requests

### ISSUE THREAD

**Issue by dumblob** [mattermost/platform#796]
There seems to be missing information about the following very important topics (at least from the enterprise point of view):

* support for email communication with non-mattermost world ("backward-compatibility" with the current systems, customers, etc.)
  * mailing lists (how can one subscribe, what are the limitations, how about filtering based on headers, etc.)
* end-to-end encryption (is there any?, how to achieve it?, how about end-to-end encryption and email integration?, what for an infrastructure is needed for end-to-end encryption?, what for an infrastructure is needed for only storage encryption?, etc.)

**Comment by it33** [comment]
Hi @dumblob, appreciate the feedback, 

There seem to be multiple topics here and it seems difficult to manage all the pieces in one issue. 

Could we interest you in starting one or more forum threads on this at http://forum.mattermost.org/? 

It's just one-click to participate with your GItHub account,

**Comment by dumblob** [comment]
>Could we interest you in starting one or more forum threads on this at http://forum.mattermost.org/?

I was considering it, but creating an Issue on GitHub was way easier. Not speaking about issues with cross-referencing, synchronizing information, splitting the community into two groups (the one, who reads GitHub and the one, who was bold enough to **create an account** at http://forum.mattermost.org as it's impossible to just log in using GitHub account), etc.

Before I'll decide whether to create yet another account (this time at http://forum.mattermost.org), I can't resist to ask. Is there really any firm reason why not to discuss things here at GitHub in [nicely labeled](https://github.com/neovim/neovim/issues) and easy-to use well-prepared environment which is well integrated with contributions (be it a documentation, coding/programming, or anything else) if you already use this GitHub repository as **not** read-only anyway?
