### ISSUE TITLE
"A team with that domain already exists"

### ISSUE THREAD

**Issue by the4ndy** [mattermost/platform#80]
When trying to set up a team on a fresh install of Mattermost I am running into an issue on the last page of the signup process where I input my password, it is telling me that "A team with that domain already exists". This is obviously in error as it is a fresh setup / install. The only thing I can think of is that I used the same domain name (a testing domain name I own) and such for testing because Mattermost currently does not support sub domains, but this was used on a separate server, network, and was an offline setup (though the server and client did have internet access). Does this app "phone home" in anyway? I believe I read something about Google Analytics...does the app report in to the parent companies Google Analytics and then does the app check that that domain is unique? That would be not cool in my opinion....I am all about you guys collecting data on your free open source software but not if it breaks it :(

Let me know if this is something stupid im doing wrong or if there is anything i can do to help. I will continue you investigate the issue and update it here

**Comment by coreyhulen** [comment]
I suspect you're trying to use a reserve word for the team domain.  Things like admin, test, api, etc cannot be used to created a team, although you should have seen the error earlier in the signup process.

The system can be configured to collect analytics data, but is not configured by default.  If you wish to collect your own data you can do so by modifying the web/static/config/config.js SegmentWriteKey.

**Comment by it33** [comment]
hi @the4ndy, we started a forum thread about this issue at http://discourse.mattermost.org/t/error-a-team-with-that-domain-already-exists/19. You can continue the conversation with a 1-click login with your GitHub account.

Since this topic does not appear to require a code change, we're closing the Issue in GitHub. Please open a new issue if you feel a code change is appropriate.
