### ISSUE TITLE
GitLab omnibus issue: Token request failed

### ISSUE THREAD

**Issue by jhoanir** [mattermost/platform#804]
Hi,

I've been installed the last gitlab-mattermost and following step by step the howto to activate de SSO built in but I got this error:

> ==> /var/log/gitlab/gitlab-rails/production.log <==
> Started GET "/oauth/authorize?response_type=code&client_id=9476c971a4e9f31e507ad9cef2937d62c12808e5d2179e02f148dbfd4fe4590f&redirect_uri=https%3A%2F%2Fsland.tech%2Fsignup%2Fgitlab%2Fcomplete&state=eyJoYXNoIjoiJDJhJDEwJEJjQ25CREJSb1ZpZXI2YndrMjdGVS41MklXNkJFYmtna2wyVXNBbnBjRjF2dkpndTBFTy5lIiwidGVhbSI6ImFyZHVpbm8wMTIzNDU2Nzg5In0%3D" for 181.39.192.168 at 2015-09-25 02:32:04 -0500
> Processing by Oauth::AuthorizationsController#new as HTML
>   Parameters: {"response_type"=>"code", "client_id"=>"9476c971a4e9f31e507ad9cef2937d62c12808e5d2179e02f148dbfd4fe4590f", "redirect_uri"=>"https://sland.tech/signup/gitlab/complete", "state"=>"eyJoYXNoIjoiJDJhJDEwJEJjQ25CREJSb1ZpZXI2YndrMjdGVS41MklXNkJFYmtna2wyVXNBbnBjRjF2dkpndTBFTy5lIiwidGVhbSI6ImFyZHVpbm8wMTIzNDU2Nzg5In0="}
> Completed 200 OK in 79ms (Views: 56.9ms | ActiveRecord: 12.2ms)
> Started POST "/oauth/authorize" for 181.39.192.168 at 2015-09-25 02:32:06 -0500
> Processing by Oauth::AuthorizationsController#create as HTML
>   Parameters: {"utf8"=>"âœ“", "authenticity_token"=>"[FILTERED]", "client_id"=>"9476c971a4e9f31e507ad9cef2937d62c12808e5d2179e02f148dbfd4fe4590f", "redirect_uri"=>"https://sland.tech/signup/gitlab/complete", "state"=>"eyJoYXNoIjoiJDJhJDEwJEJjQ25CREJSb1ZpZXI2YndrMjdGVS41MklXNkJFYmtna2wyVXNBbnBjRjF2dkpndTBFTy5lIiwidGVhbSI6ImFyZHVpbm8wMTIzNDU2Nzg5In0=", "response_type"=>"code", "scope"=>"api"}
> Redirected to https://sland.tech/signup/gitlab/complete?code=0ef6ece6b75952874cf76b1eb96c2027c650924a360f9b257f7c69e5fd33c37d&state=eyJoYXNoIjoiJDJhJDEwJEJjQ25CREJSb1ZpZXI2YndrMjdGVS41MklXNkJFYmtna2wyVXNBbnBjRjF2dkpndTBFTy5lIiwidGVhbSI6ImFyZHVpbm8wMTIzNDU2Nzg5In0%3D
> Completed 302 Found in 19ms (ActiveRecord: 5.6ms)

> ==> /var/log/gitlab/mattermost/current <==
> 2015-09-25_07:32:06.47690 [09/25/15 02:32:06] [EROR] /signup/gitlab/complete:AuthorizeOAuthUser code=500 rid=6jbc5d83oin7pnq6mgp18w94ar uid= ip=181.39.192.168 Token request failed [details: Post https://git.sland.tech/oauth/token: x509: certificate is valid for rdi.sland.tech, sland.tech, not git.sland.tech]

![2015-09-25](https://cloud.githubusercontent.com/assets/4220943/10103292/aafc853e-6368-11e5-83ff-d5e067119502.png)

Thanks in advance.

--
Jhoanir Torres

**Comment by it33** [comment]
Please post to https://gitlab.com/gitlab-org/omnibus-gitlab
