### ISSUE TITLE
Accepting Pull Requests: Update Mac OS X instructions to replace boot2docker with Docker Machine

### ISSUE THREAD

**Issue by pstonier** [mattermost/platform#814]
Installation instructions for OS X provides commands for boot2docker to be run, but Boot2Docker has been deprecated. https://docs.docker.com/installation/mac/

**Comment by it33** [comment]
Thanks @pstonier, good point. 

Hmm... would you be interested in becoming an approved contributor to Mattermost by helping us update the [Mac OS X install instructions](https://github.com/mattermost/platform/blob/master/doc/install/single-container-install.md#mac-osx)?

**Comment by pstonier** [comment]
I just created a pull request with updated instructions. I'm new to using docker, but seemed to be able to figure it out and get up and running.

**Comment by pstonier** [comment]
https://github.com/mattermost/platform/pull/816

**Comment by justyns** [comment]
I can confirm the instructions in https://github.com/mattermost/platform/pull/816 worked for me(at least for the docker part)

**Comment by coreyhulen** [comment]
thanks, PR merged.
