### ISSUE TITLE
Post search: We encounted an error while searching for posts

### ISSUE THREAD

**Issue by petramies** [mattermost/platform#822]
Post a new message: 
```
Just testing if I can find this text -- (by lattimer boromits)

<Whohaa>
-- don't do this --
(maybe))?
```
Search text by 
```
--
(by lattimer
<Whohaa>
))?
```
All these will give message "We encounted an error while searching for posts"
```
[09/27/15 17:50:53] [EROR] /api/v1/posts/search:SqlPostStore.Search code=500 rid=bi4quhrns3dsibwxczmo8855sc uid=cfpjbixcz3rt8mkn61qo5juqdw ip=127.0.0.1 We encounted an error while searching for posts [details: teamId=5fyhoik18jbgdyg8iqnrsh4mkh, err=Error 1064: syntax error, unexpected $end]

```

Before search
![before_search](https://cloud.githubusercontent.com/assets/14278742/10123385/f91ed648-6540-11e5-933a-4d6ad7750bc2.PNG)

After
![after_search](https://cloud.githubusercontent.com/assets/14278742/10123386/fcb3159e-6540-11e5-824e-0430250278cb.PNG)

**Comment by coreyhulen** [comment]
Are you running postgres or mysql?

**Comment by coreyhulen** [comment]
@petramies thanks for the report.  I was able to repo this issue.  Including `(` or `)` the the search field causes the errors.

**Comment by lfbrock** [comment]
Jira ticket filed here https://mattermost.atlassian.net/browse/PLT-526

**Comment by coreyhulen** [comment]
PR submitted https://github.com/mattermost/platform/pull/943

**Comment by coreyhulen** [comment]
PR has been merged to master.
