### ISSUE TITLE
Can not send mail, mattermost doese not respect gitlab email setting?

### ISSUE THREAD

**Issue by netroby** [mattermost/platform#826]
Can not send mail, mattermost doese not respect gitlab email setting?

The gitlab was running very well, i am sure i correct configure mail send configure for gitlab. 
But mattermost does not respect the configure of gitlab.

What the right way to configure mattermost email setting?

**Comment by it33** [comment]
Hi @netroby, please see Mattermost install instructions at: https://github.com/mattermost/platform/blob/master/doc/config/smtp-email-setup.md

If you're running GitLab Mattermost from GitLab 8.0 omnibus, it should install and configure all the correct email settings automatically. If you're installing manually, please follow above instructions.

**Comment by netroby** [comment]
I installed gitlab 8.0 with it's ominibus, but mattermost email send not working.

**Comment by it33** [comment]
Hi @netroby, [it turns out GitLab isn't automatically setting up email,](https://forum.mattermost.org/t/automatic-email-configuration/1746/3?u=it33) sorry, I thought it was.
