### ISSUE TITLE
Accepting Pull Requests: Mattermost can not send message start with slash(/)

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#827]
I try to send a absolute path as a message in mattermost, e.g. /file/path, but it didn't sent, and no error occurred.

**Comment by it33** [comment]
Thanks @chengweiv5, 

This is a bug with the new slash commands feature. Community pull requests welcome here, potentially a good starter project.

**Comment by chengweiv5** [comment]
slash commands is cool! `/me will give a try`

**Comment by sinistersnare** [comment]
What is the intended behaviour of messaging `/file/path`?

I say that double slashes should work, a la sending a message with raw text `"//foo/bar"`  will render as `"/foo/bar"`

`/say` is common in IRC (along with //)
