### ISSUE TITLE
Debian 8: Mattermost crashes Chrome browser when setting user profile picture

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#828]
I'm using `Version 45.0.2454.93 (64-bit)` on Debian 8, when I was trying to set user profile picture, the `select` action will crash the whole browser.

**Comment by it33** [comment]
Thanks @chengweiv5, could we ask your help to upgrade to the [latest release](https://github.com/mattermost/platform/releases) and see if the issue persists? 

This may have been fixed in a related PR already,

**Comment by chengweiv5** [comment]
I think this may a chrome bug on my platform, debian 8 and chrome 45, it may crash always the first time I'm trying to upload a file, e.g. in redmine or github.

So I'll close this one this time.
