### ISSUE TITLE
Accepting Pull Requests: Add code syntax-highlighting

### ISSUE THREAD

**Issue by damianwilczek** [mattermost/platform#829]
e.g. implement this https://highlightjs.org/ into yours project

**Comment by it33** [comment]
Thanks @damianwilczek, there's an existing ticket accepting pull requests for this: https://mattermost.atlassian.net/browse/PLT-395

Community contributions for this [highly welcome](https://github.com/mattermost/platform/blob/master/doc/developer/code-contribution.md).

**Comment by thorsteneckel** [comment]
Hi there! https://mattermost.atlassian.net/browse/PLT-395 says it was done, but the commit was reverted here: https://github.com/mattermost/platform/commit/c86df0f0c6c79c98238e8a1a84cb9fab5a69a635

Can you tell why and when it will come? Thanks.

**Comment by coreyhulen** [comment]
its back in.
