### ISSUE TITLE
Enable install without internet access (for community members on air-gapped networks)

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#84]
Hi, I just gave a try to mattermost follow steps in README.

However, `http://dockerhost:8065` only give me below page, nowhere to sign up, seems something gone wrong?

![screen shot 2015-06-27 at 10 26 52](https://cloud.githubusercontent.com/assets/689798/8390128/5e6c8fc2-1cb7-11e5-9748-c7f97d6cac65.png)

I setup mattermost in my workstation and access it from home (Mackbook with google chrome 43.0.xxx) via VPN.

**Comment by KirinHuang** [comment]
I have the similar problem, like blow error:
```log
GET https://fb.me/react-with-addons-0.13.1.js net::ERR_NAME_NOT_RESOLVED
(index):14 GET https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js net::ERR_CONNECTION_TIMED_OUT
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery(anonymous function) @ bootstrap.min.js:6
user_profile.jsx:27 Uncaught ReferenceError: React is not defined60.../stores/user_store.jsx @ user_profile.jsx:27s @ _prelude.js:1(anonymous function) @ _prelude.js:11.../dispatcher/app_dispatcher.jsx @ channel_header.jsx:7s @ _prelude.js:1e @ _prelude.js:1(anonymous function) @ _prelude.js:1
(index):25 GET https://www.google.com/jsapi?autoload={%27modules%27:[{%27name%27:%27visualization%27,%27version%27:%271%27,%27packages%27:[%27annotationchart%27]}]} net::ERR_CONNECTION_TIMED_OUT
(index):42 config.js missing LogglyWriteKey, Loggly analytics is not reporting
(index):67 config.js missing SegmentWriteKey, SegmentIO analytics is not tracking
(index):90 config.json missing AnalyticsUrl, Snowplow analytics is not tracking
(index):133 Uncaught TypeError: window.setup_login_page is not a function
```
some assets can't access from china, or inner network.

**Comment by it33** [comment]
@chengweiv5, thanks for the report. 90% sure this is our fault for not including a link to the list of supported browsers in README.md: http://www.mattermost.org/mattermost-0-5-0-released/

Can you let me know if the issue still shows up if you're able to switch to a browser below? 

Supported Operating Systems and Browsers:

PC: Windows 7, Windows 8 (Chrome 43, Firefox 38, Internet Explorer 11)
Mac: OS 10 (Safari 7, Chrome 43)
Linux: Arch 4.0.0  (Chrome 43)
iPhone 4s and higher (Safari on iOS 8.3, Chrome 43)
Android 5 and higher (Chrome 43)

This is potentially a CSS rendering issue we need to fix, particularly if you're on Linux as our testing there is very limited.

**Comment by it33** [comment]
@chengweiv5, thanks for the update, could we ask you to right-click on the text and select "Inspect Element" and paste here the HTML you see? 

@KirinHuang, I've opened a new issue on your comment, I believe it's a different topic, please reply back if you think differently?

**Comment by chengweiv5** [comment]
I'm using Mac OS X 10.10.3 (14D136) and google chrome Version 43.0.2357.81 (64-bit), I did try several times, issue confirmed.

See picture below.

![screen shot 2015-06-28 at 12 55 35](https://cloud.githubusercontent.com/assets/689798/8395224/7273d5ea-1d96-11e5-820c-53e77e266bc9.png)

**Comment by ralder** [comment]
theare are errors with loaded scripts in Network tab (inside Google Developer Console) ?

**Comment by chengweiv5** [comment]
@KirinHuang I can download `https://fb.me/react-with-addons-0.13.1.js` from my docker host, see below:

```
wget https://fb.me/react-with-addons-0.13.1.js
--2015-06-29 15:55:00--  https://fb.me/react-with-addons-0.13.1.js
Resolving fb.me (fb.me)... 173.252.120.6, 2a03:2880:2130:cf05:face:b00c:0:1
Connecting to fb.me (fb.me)|173.252.120.6|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xfa1/t39.3284-6/11057090_1409891529318902_1450546493_n.js [following]
--2015-06-29 15:55:13--  https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xfa1/t39.3284-6/11057090_1409891529318902_1450546493_n.js
Resolving fbcdn-dragon-a.akamaihd.net (fbcdn-dragon-a.akamaihd.net)... 96.17.109.152, 2001:428:4c02::cda8:ec2a, 2001:428:4c02::cda8:ec21
Connecting to fbcdn-dragon-a.akamaihd.net (fbcdn-dragon-a.akamaihd.net)|96.17.109.152|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 659553 (644K) [text/javascript]
Saving to: ‘react-with-addons-0.13.1.js’

react-with-addons-0.13.1.js                     100%[=======================================================================================================>] 644.09K  24.6KB/s   in 13s    

2015-06-29 15:55:28 (48.2 KB/s) - ‘react-with-addons-0.13.1.js’ saved [659553/659553]
```

**Comment by KirinHuang** [comment]
@chengweiv5 i access this resource from china, that's the reason.

**Comment by it33** [comment]
hi @chengweiv5 sorry for the late reply, this is probably because you can't reach the jquery library from your browser--we should have included it in the download and we didn't. There's a feature request to do this and I think we probably will soon: http://mattermost.uservoice.com/forums/306457-general/suggestions/8637517-enable-installer-to-complete-without-referencing-e

In the meantime, here's how to work around: 

1] Somehow get a compressed 1.11.3 version of jquery from a different download source (if you can't access https://jquery.com/download/ ) 
2] Copy the downloaded jquery-1.11.3.min.js into web/static/js 
3] In web/templates/head.html if he replaced line 12 which looks like this 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> 
with this 
<script src="/static/js/jquery-1.11.3.min.js"></script> 
4] Reload dockerhost:8065.

**Comment by jwilander** [comment]
Hi @KirinHuang please see @it33's comment for your issue as well and if you can't access react-with-addons either you can hopefully use the following steps to work-around that. If you have trouble finding copies of jquery-1.11.3.min.js and react-with-addons-0.13.1js, we might be able to get you some copies.

```
1] Somehow get the 0.13.1 version of react-with-addons from a different download source (if you can't access https://facebook.github.io/react/blog/2015/03/16/react-v0.13.1.html ) 
2] Copy the downloaded react-with-addons-0.13.1.js into web/static/js 
3] In web/templates/head.html replace line 11 which looks like this 
<script src="https://fb.me/react-with-addons-0.13.1.js"></script> 
with this 
<script src="/static/js/react-with-addons-0.13.1.js"></script> 
4] Reload dockerhost:8065.
```

@chengweiv5 would you be able to paste the contents of your javascript web console here? It looks like you're missing the jquery library as well but it's hard to confirm without being able to see your console. Also does your VPN force all internet traffic through the tunnel or does it allow non-VPN related traffic to access the internet directly?

**Comment by chengweiv5** [comment]
@it33 , just verified that I can signup from company, seems it's a real network issue which may download some resources that can not accessed from home, china only issue. :-(

I'll paste `console` log when I at home.

**Comment by it33** [comment]
Hi @chengweiv5, really sorry we didn't better anticipate developers in China. 

There was a feature request submitted to fix this: http://mattermost.uservoice.com/forums/306457-general/suggestions/8677084-add-ability-to-use-ip-address-team-instead-of-te

It might take a week to get the pull request in, and the next major build release, 0.6.0 is end of month. So the options are a) download things locally from China through some VPN, b) wait until end of next week for us to ship the bits (your call on whether to pick them off individually or take a cut of the bits under development, or c) wait until the next major build version where we'll have gone through a full manual test pass.

**Comment by coreyhulen** [comment]
This is now fixed with https://github.com/mattermost/platform/pull/130
