### ISSUE TITLE
Accepting Pull Request: /join redirects to an incorrect url

### ISSUE THREAD

**Issue by justyns** [mattermost/platform#842]
I ran into this issue on the master branch.  

* I created a new channel called `test`
* Left that channel using the UI
* Sent `/join test` and received an error in the browser:

```
Mattermost needs your help:
Sorry, we could not find the page.

Go back to team site
```

The URL it took me to was http://localhost:8065/channels/test, but it looks like that should have been http://localhost:8065/teamname/channels/test

Note:  It does join the channel and it shows up in the last after clicking the back button.

I'm still poking around in the code, but this looks like it might be an easy fix for my first contribution :)

**Comment by it33** [comment]
Thanks @justyns! Nice find, would love a PR to fix this!

**Comment by justyns** [comment]
Quick question!   I was able to fix this pretty simply by using `context.GetTeamURL()`, but that breaks the `TestJoinCommands` test in command_test.go.    
`GetTeamURL()` returns a full/absolute url like `http://localhost:8065/someteam/channels/test` instead of a relative url like `/someteam/channels/test`.

1. Is there an easy way to get the context or otherwise get the url that would be used during the test?  `if rs5.GotoLocation != "/channels/"+channel2.Name {` would somehow have to match an absolute url instead of just '/channels...'
2. Is using an absolute url for the redirect location okay in command.go?   The alternative seems to be storing teamName in session/context, or adding an extra sql query(using `Srv.Store.Team().Get(c.Session.TeamId)`) to the join command function.

**Comment by coreyhulen** [comment]
thanks. https://github.com/mattermost/platform/pull/854 has been merged into master.
