### ISSUE TITLE
Accepting Pull Requests: Autocomplete suggestions misaligned on master

### ISSUE THREAD

**Issue by trashcan** [mattermost/platform#844]
Hello,

I noticed that the autocomplete suggestions looked a little broken on master. 

Before:
![screen shot 2015-09-28 at 5 28 31 pm](https://cloud.githubusercontent.com/assets/195789/10150789/55a300bc-6607-11e5-9e6a-fbcc47e008a4.png)
![screen shot 2015-09-28 at 5 28 38 pm](https://cloud.githubusercontent.com/assets/195789/10150794/5ef435fa-6607-11e5-8607-ea647150ff1f.png)

I wrote a quick patch to add the pull-left and pull-right classes.

After:
![screen shot 2015-09-28 at 5 35 11 pm](https://cloud.githubusercontent.com/assets/195789/10150808/6f6f9866-6607-11e5-8e13-561923c02219.png)
![screen shot 2015-09-28 at 5 35 17 pm](https://cloud.githubusercontent.com/assets/195789/10150810/789eab20-6607-11e5-892e-e70ff1ff9fcc.png)

I freely admit I'm terrible at CSS, so don't hesitate to change it if it's not the way you want. PR incoming

**Comment by it33** [comment]
Thanks @trashcan! Great work! Just need reviewers, should go in soon,

**Comment by it33** [comment]
Completed in https://github.com/mattermost/platform/pull/845, thanks @trashcan!

**Comment by trashcan** [comment]
No problem. Myself and some of my coworkers really want to use Mattermost as a replacement for Slack and are happy to contribute. Do you have any feedback on issues that need help besides the ones marked as newbie friendly? Is it OK to submit simple features that exist in slack but not MM? Like the `/shrug` command?
