### ISSUE TITLE
Accepting Pull Requests: Display Nickname instead of username

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#847]
Is it reasonable that mattermost should display nickname if user has configured one instead of username in post messages?

especially that username generally doesn't support non-english words, like chinese, while nickname does, so a nickname in user native language is much friendly I think.

**Comment by it33** [comment]
Thanks @chengweiv5, agree this makes sense, especially for non-English users. This was a planned feature that got pushed back. If you or anyone in the community is up for adding it, the development team would be supportive. 

Ticket marked "Accepting Pull Requests": https://mattermost.atlassian.net/browse/PLT-480

**Comment by coreyhulen** [comment]
There is a func in utils.jsx getFullName(user) that should be used.

**Comment by coreyhulen** [comment]
sorry meant getDisplayName().  If first attempts to set the nick name, then full name, then falls back to username.

**Comment by chengweiv5** [comment]
I think I'll give a try, thinks for your hint. :-)

**Comment by medokin** [comment]
+1

**Comment by gabel** [comment]
Any news on that?

**Comment by chengweiv5** [comment]
@gabel I recently didn't managed spent some time on mattermost and in short future, please anyone go and take this PR.

**Comment by gabel** [comment]
@chengweiv5 thx for the info... looks like I need dive into go lang :dancers:
