### ISSUE TITLE
Regression: The system admin cannot update team name, error "You do not have the appropriate permissions"

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#868]
I created a team with gitlab 7.9.2 oauth and then trying to update the team name like below, however, it failed.

![mm-team-update](https://cloud.githubusercontent.com/assets/689798/10182447/d79ddeac-6756-11e5-8a66-a03beeae9997.png)

**Comment by it33** [comment]
Thanks @chengweiv5, nice find! Looks like a regression we need to fix.

**Comment by coreyhulen** [comment]
I think this is the same issue as https://mattermost.atlassian.net/browse/PLT-461.  If you're system_admin then you cannot rename the team, but if your just admin (ie the team admin) then it will succeed.

**Comment by it33** [comment]
Hi @chengweiv5, if you create a second account and give it "Team Admin" permissions, are you able to rename the team?

**Comment by coreyhulen** [comment]
Fixed with https://github.com/mattermost/platform/pull/884
