### ISSUE TITLE
Version information strings not parsed

### ISSUE THREAD

**Issue by alerque** [mattermost/platform#870]
In the _Account Settings_ » _Security Settings_ page the Version number stings aren't properly parsed. It looks like some kind of string substitution isn't happening.

![town square - sandbox mattermost - mozilla firefox_068](https://cloud.githubusercontent.com/assets/173595/10190917/a2a87848-6778-11e5-9e7d-e68f0a7357af.png)

1.0.0-RC1

**Comment by coreyhulen** [comment]
Hi @alerque,

Is this a developer build?  The official RC1 compiled bits located at https://github.com/mattermost/platform/releases do set this information correctly.

in the make file you can see lines like
```@sed -i'.bak' 's|_BUILD_NUMBER_|$(BUILD_NUMBER)|g' ./model/version.go
@sed -i'.bak' 's|_BUILD_DATE_|$(BUILD_DATE)|g' ./model/version.go
@sed -i'.bak' 's|_BUILD_HASH_|$(BUILD_HASH)|g' ./model/version.go```

the official build runs 'make travis'

**Comment by alerque** [comment]
No, this is not a developer build, it is an install from the Archlinux [AUR pagkage](https://aur.archlinux.org/packages/mattermost). The [build recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mattermost) doesn't have `make travis`, nor would I have expected it to! That's would be a very unorthodox make target to run to build a production package. That being said it looks like the build process could use a bit of cleanup for non-docker builds. Obviously those sed rules or some extra make targets could be built into the build recipe (and I will alert the maintainer to this issue) but perhaps this could get moved to someplace saner and the stand-alone build process could be made less difficult to deal with.

**Comment by coreyhulen** [comment]
the default target for our makefile is "travis", also there is a "make dist" that will build a distribution.  With that said I would recommend taking the official build from https://github.com/mattermost/platform/releases.
