### ISSUE TITLE
Blank space not recovered after error message in Chrome

### ISSUE THREAD

**Issue by alerque** [mattermost/platform#871]
Using Chrome, if an error message appears in the drop down bar at the top (in my test case I didn't have websockets working so there was a connection error message) if you dismiss the bar, the blank space it occupied is not recovered. Additionally the actual chat pain is scrolled internal to the page (pushed down by the amount the top bar took up) such that the last chat message is cut off. The chat log will scroll up and down but it's maximum down position is not far enough down to read the last message in the list.

1.0.0-RC1

**Comment by coreyhulen** [comment]
thanks @alerque for the report.  Can you supply the version of chrome and platform (mac, win, etc) you are using.  I was only able to repo the issue if I was resizing the browser at the same time the blue bar appeared.  Once I dismissed the blue bar the area was reclaimed and on the next blue bar it was working as expected.  Is this what you are seeing?

**Comment by alerque** [comment]
This was on Mac OSX 10.11 with Chrome 45.0.2454.101.

And no, that isn't the behavior I was seeing. I didn't do any resizing at all until after the problem occurred at which point I was trying to reclaim the missing space and resizing didn't have any effect. Only refreshing the page from scratch would fix the issue, which came back for me many times as I was also dealing with a miss-configured proxy that didn't upgrade requests to websockets. Every time the bar came back and I dismissed it the space would be lost and the scrolling would be broken until I did a full refresh.

**Comment by coreyhulen** [comment]
Hi @alerque.  I'm still not able to repo it as described.  Can you maybe attach a screenshot of what you're seeing?

thanks.

**Comment by coreyhulen** [comment]
PR submitted https://github.com/mattermost/platform/pull/951

**Comment by coreyhulen** [comment]
PR has been merged to master.
