### ISSUE TITLE
Redirect URL doesn't set the right protocol

### ISSUE THREAD

**Issue by alerque** [mattermost/platform#873]
The Mattermost interaction with the Gitlab API is broken in that it passes a redirect URL as a query parameter that is hard coded to be HTTP even if the site is being served over HTTPS.

The current work around is to ① catch port 80 requests on the mattermost domain and redirect them and ② to add a second set of URLs to the Gitlab application entry to allow the HTTP variants. This is an undesirable workaround to say the least.

The Mattermost instance needs to either auto-detect that is is being served up over and HTTPS link and pass the correct parameters or ask for this information in the config file so it can be configured to force the correct parameter.

This was [previously reported on the forum](http://forum.mattermost.org/t/mattermost-with-gitlab-sso-ignores-https-scheme-when-creating-implicit-token-request/249?u=alerque) by @Venomed in relation to 0.7.1, but the bug still exists in 1.0.0-RC1 and is a show stopper as far as initial setup goes if you don't specifically work around it.

**Comment by coreyhulen** [comment]
Hi @alerque thanks for the report.  I think this was a problem but it appears to be fixed in 1.0.  The method GetProtocol() https://github.com/mattermost/platform/blob/master/api/context.go#L198 checks for the header property "X-Forwarded-Proto" which should be set by your load balancer.  This allows mattermost to detect https and set the url properly.

can you confirm your configuration for Nginx has the line `proxy_set_header X-Forwarded-Proto $scheme;`  ?

**Comment by alerque** [comment]
@coreyhulen This is still a problem in 1.0.0-RC1 which is why I took the trouble to report it. I am not using Nginx, my SSL termination and proxy server is Apache. And yes I do have the corresponding header set.

    RequestHeader set X_Forwarded_Proto "https"

**Comment by coreyhulen** [comment]
I not that familiar with apache but I think `X_Forwarded_Proto` needs to be `X-Forwarded-Proto` with dashes instead of underscores.

**Comment by alerque** [comment]
@coreyhulen That actually did the trick. I'm kind of surprised because I've used that header format before (that line was copied from other configs where this is working). Perhaps the difference is in the detection method? In any case that works for Apache»Mattermost.

**Comment by coreyhulen** [comment]
Not certain.  The standard name is with dashes as seen in https://en.wikipedia.org/wiki/List_of_HTTP_header_fields.  Our experience with both Nginx and Amazon ELB is dashes.  I suspect if you have another app dependent on that header it checks for both.  In any case I'm glad it works :).
