### ISSUE TITLE
Error validating config file, Invalid at rest encrypt key for SQL settings. Must be 32 chars.

### ISSUE THREAD

**Issue by apaatsio** [mattermost/platform#878]
I did docker build&run and got this error:

```
panic: Error validating config file=/config_docker.json, err=Invalid at rest encrypt key for SQL settings.  Must be 32 chars.
```

Problem is in the docker configs `docker/{1.0,dev,local}/config_docker.json`. The AtRestEncryptKey in those files is only 31 chars, so the error message is valid and the problem is in the config files.

**Comment by lfbrock** [comment]
PR submitted: https://github.com/mattermost/platform/pull/882

**Comment by it33** [comment]
Thanks @apaatsio!

**Comment by coreyhulen** [comment]
this has been merged to master.
