### ISSUE TITLE
Show context for search results

### ISSUE THREAD

**Issue by ptersilie** [mattermost/platform#879]
When searching for a message, the result only shows the message that matches the result. Sometimes a single message doesn't make clear what the topic was about, so being able jump to the context of that message would be very useful.

**Comment by lfbrock** [comment]
Thanks ptersilie! I think this is something we really need - here's a Jira ticket tracking the issue, it's currently planned for v1.2
https://mattermost.atlassian.net/browse/PLT-88

**Comment by ptersilie** [comment]
Cool. Thanks a lot lfbrock. I'm looking forward to v1.2 then.

**Comment by it33** [comment]
Hi @ptersilie, didn't make it for v1.2, it's almost in for v1.3, adding @esethna to circle back when the ticket in the above link is in.

**Comment by ptersilie** [comment]
@it33 Thanks a lot. I'm looking forward to v1.3 then. :)

**Comment by esethna** [comment]
@ptersilie This has just been [merged](https://github.com/mattermost/platform/pull/1475) to master!
