### ISSUE TITLE
Feature Request: Heroku Installation

### ISSUE THREAD

**Issue by arkokoley** [mattermost/platform#88]
I want to run mattermost not locally, but on Heroku. What should be on the procfile?

**Comment by it33** [comment]
Hi @arkokoley, sorry for the late reply, for now, the best source of information would be the Docker file. 

The core team is working on making a number of changes to smooth out the install process (enabling install without domains, enabling local storage as option over S3, etc. 

http://mattermost.uservoice.com/forums/306457-general/status/1588357), and this should make Heroku setup easier by end of next week. 

If you're interested in contributing on Mattermost + Heroku, we're highly welcome guidance on the project forum: http://forum.mattermost.org/

**Comment by it33** [comment]
Reopening this ticket as we're getting more requests for Heroku install. Curious what the interest level is for this feature?

**Comment by zaksoup** [comment]
I'd certainly be interested in what heroku support might look like.

**Comment by billgloff** [comment]
Heroku support would be awesome!

**Comment by michaelachrisco** [comment]
Heroku does support go so a heroku install is doable. https://blog.heroku.com/archives/2015/7/7/go_support_now_official_on_heroku

**Comment by vishnugopal** [comment]
Would be awesome to have Heroku support!

**Comment by stmcintyre** [comment]
+1 for Heroku support. Awesome work so far!

**Comment by tommyvn** [comment]
https://github.com/tommyvn/mattermost-heroku is a good start, feel free to use/base another solution on, but be warned that there are two major issues and one minor one.
Major issues are the encryption related config is hardcoded to the defaults and the data storage is the filesystem, which means you'll loose anything stored there on a dyno restart, probably daily.
Minor issue is that the version is currently hard-coded to 1.1.0 on the github release URI.

Pull requests to fix those are welcome if I don't get to it myself soon.

**Comment by it33** [comment]
Thanks @tommyvn!

This is awesome! Listed it here: http://www.mattermost.org/installation/ and mentioned here: https://twitter.com/mattermosthq/status/657292214695956480

Highly appreciated!
