### ISSUE TITLE
Accepting Pull Requests: Gravatar support

### ISSUE THREAD

**Issue by justyns** [mattermost/platform#885]
I am working on a patch to add gravatar support to mattermost.  Would this be accepted/desired?

At the moment, the `/api/v1/users/userid/image` api call is going to take care of downloading the gravatar and saving it to the disk in place of the ones that are currently being generated.   It'll still load the profile image from disk if it exists, so users can upload custom profile pics the same way.

**Comment by it33** [comment]
Hi @justyns, sounds awesome!!

We've love to have your help on this. One request: Please create a setting to enable or disable this feature from the System Console -> Privacy Settings menu, and disable by default. 

In future, profile pics might also be populated through SSO settings, so having things off by default reduces the chances of unintentional conflicts.

**Comment by alerque** [comment]
I agree that this would be a nice feature _and_ that defaulting to off is a good idea. My one concern is that the normal usage pattern for Gravatar is to actually serve up the image directly from them. This allows users to change their profile images across many services without having to login to every service and update. Perhaps a per-user option could be added alongside uploading a custom image to "use Gravatar" instead.

**Comment by trashcan** [comment]
Would it make sense to pull custom uploaded images from the gitlab user if it is present? I don't know how much integration is wanted since MM is still a stand-alone product.

**Comment by alerque** [comment]
For my case (and I suspect most instances of SSO using Gitlab) that would make sense. Obviously it would have to be a mechanism that was only enabled with the SSO, but I think most folks would welcome the option. After all they are logging in _AS_ their Gitlab user.

**Comment by fungos** [comment]
:+1: for direct gravatar support

**Comment by it33** [comment]
Adding @esethna to create a ticket for this we can route into the Accepting Pull Requests list

**Comment by esethna** [comment]
Thanks everyone, I've created the accepting-pull-requests ticket [here](https://mattermost.atlassian.net/browse/PLT-1286). Please feel free to comment on the proposed implementation.

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in Jira.

**Comment by bbodenmiller** [comment]
@justyns any progress getting this added?

**Comment by bbodenmiller** [comment]
@amyblais I can't update https://mattermost.atlassian.net/browse/MM-1555 but it looked like folks think it's not useful for self-hosted instances but that's inaccurate, lots of self hosted instances run local gravatar services and want to integrate them with Mattermost so users can update their photo in one place and show up in Mattermost, GitLab, and other integrated services they might run.

**Comment by amyblais** [comment]
Hi @bbodenmiller It is an old ticket so it's possible it wasn't considered useful at the time - I've reopened the ticket and sent it to triage for our team to re-consider.
