### ISSUE TITLE
UserStore performance issues on Chrome and Safari

### ISSUE THREAD

**Issue by jdeng** [mattermost/platform#888]
I imported a 1K person team and after login the browser just got frozen. Sometimes I needed to use Force Quit to kill the browser processes. The issues come from two places:
* Downloading 1K profile images almost immediately after getting the profiles (web/react/components/member_list_team_item.jsx & web/react/components/member_list_item.jsx). Some lazy loading profile images mechanism might solve this problem.
* UserStore performances: too many localStorage operations and two many messages when receiving the team's profiles. In below's diff I removed some localStorage operations, commented out message emitting for every profile and the page can be now rendered, not too fast but acceptable.

BTW the ActionTypes.RECIEVED_PROFILES and a few more seem to be a typo? (receive vs recieve)
```
--- a/web/react/stores/user_store.jsx
+++ b/web/react/stores/user_store.jsx
@@ -71,6 +71,9 @@ class UserStoreClass extends EventEmitter {
         this.getStatus = this.getStatus.bind(this);
 
         this.gCurrentId = null;
+        this.gCurrentUser = null;
+        this.gProfiles = null;
+        this.gProfileUsernameMap = null;
     }
 
     emitChange(userId) {
@@ -157,15 +160,19 @@ class UserStoreClass extends EventEmitter {
         return currentId;
     }
     getCurrentUser() {
-        if (this.getCurrentId() == null) {
+        var id = this.getCurrentId();
+        if (id == null) {
             return null;
         }
 
-        return this.pGetProfiles()[this.getCurrentId()];
+        if (!this.gCurrentUser || this.gCurrentUser.id != id)
+            this.gCurrentUser = this.pGetProfiles()[this.getCurrentId()];
+        return this.gCurrentUser;
     }
     setCurrentUser(user) {
         this.setCurrentId(user.id);
-        this.saveProfile(user);
+        this.gCurrentUser = user;
+        this.saveProfile(user, true);
     }
     getLastEmail() {
         return BrowserStore.getItem('last_email', '');
@@ -203,12 +210,17 @@ class UserStoreClass extends EventEmitter {
 
         return active;
     }
-    saveProfile(profile) {
-        var ps = this.pGetProfiles();
-        ps[profile.id] = profile;
-        this.pStoreProfiles(ps);
+    saveProfile(profile, sync) {
+        if (profile) {
+            var ps = this.pGetProfiles();
+            ps[profile.id] = profile;
+        }
+        if (sync) {
+            this.pStoreProfiles(this.pGetProfiles());
+        }
     }
     pStoreProfiles(profiles) {
+        this.gProfiles = profiles;
         BrowserStore.setItem('profiles', profiles);
         var profileUsernameMap = {};
         for (var id in profiles) {
@@ -216,13 +228,18 @@ class UserStoreClass extends EventEmitter {
                 profileUsernameMap[profiles[id].username] = profiles[id];
             }
         }
+        this.gProfileUsernameMap = profileUsernameMap;
         BrowserStore.setItem('profileUsernameMap', profileUsernameMap);
     }
     pGetProfiles() {
-        return BrowserStore.getItem('profiles', {});
+        if (! this.gProfiles)
+            this.gProfiles = BrowserStore.getItem('profiles', {});
+        return this.gProfiles;
     }
     pGetProfilesUsernameMap() {
-        return BrowserStore.getItem('profileUsernameMap', {});
+        if (! this.gProfileUsernameMap)
+            this.gProfileUsernameMap = BrowserStore.getItem('profileUsernameMap', {});
+        return this.gProfileUsernameMap;
     }
     setSessions(sessions) {
         BrowserStore.setItem('sessions', sessions);
@@ -311,8 +328,9 @@ UserStore.dispatchToken = AppDispatcher.register(function registry(payload) {
             }
             var profile = action.profiles[id];
             UserStore.saveProfile(profile);
-            UserStore.emitChange(profile.id);
+//            UserStore.emitChange(profile.id);
         }
+        UserStore.saveProfile();
         break;
```

**Comment by lfbrock** [comment]
Thanks jdeng! I filed a ticket here to track the issue - https://mattermost.atlassian.net/browse/PLT-516

**Comment by jwilander** [comment]
Thanks @jdeng, yeah this is definitely something we want to fix with decently high priority.

**Comment by coreyhulen** [comment]
This is in master and will ship with 1.2

**Comment by jdeng** [comment]
The issue seems still there (but it is better as Chrome no longer gets frozen).
See attached profiling result.
<img width="1238" alt="screen shot 2015-11-05 at 7 50 09 pm" src="https://cloud.githubusercontent.com/assets/196648/10989003/ae828c54-83f6-11e5-8de8-b091cffc62b7.png">

**Comment by coreyhulen** [comment]
How many users do you have?  We have a bunch more work planned for 1.3 to improve this.

fyi, @jwilander

**Comment by coreyhulen** [comment]
Looks like the getProfiles is still de-serializing the large json object every time.  I wonder is we just store it on the UserStore and only get it from sessionStorage if UserStore.profiles == null.

Also getCurrentUser can be next to nothing if we switch it to global.window.mm_user.

**Comment by jdeng** [comment]
I used 1k users for testing. I think caching it in UserStore should solve this issue (I actually tried that).

**Comment by coreyhulen** [comment]
The fix is in master.  I tested with 2K users and didn't notice any problems.

**Comment by jdeng** [comment]
Thanks. It is much better now.
