### ISSUE TITLE
Context menu is not fully visible if team name is too long

### ISSUE THREAD

**Issue by medokin** [mattermost/platform#889]
Summary:
Context menu is not fully visible if team name is too long

![image](https://cloud.githubusercontent.com/assets/456683/10215187/9cbc3418-681f-11e5-9a40-be742d701ea3.png)

Steps to reproduce:
Create a team with a very long name.

Expected behavior:
Menu should expand to right side, instead of left.

**Comment by it33** [comment]
Hi @medokin, 

Thanks for the report! This should be fixed in v1.0-RC2, long team names are now truncated with ... 

Example: 

![screenclip 65](https://cloud.githubusercontent.com/assets/177788/10220185/2cdfae10-67fa-11e5-8ae5-828258b4f94f.png)
