### ISSUE TITLE
X509?

### ISSUE THREAD

**Issue by clemenko** [mattermost/platform#893]
Is there a way to pass in X509 usernames for auto account creation?

**Comment by it33** [comment]
Hi @clemenko, thanks for the feature idea!

While this isn't currently supported, could we interest you in adding this to the [Mattermost feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be upvoted? 

Through the feature idea forum you'll be able to discuss the feature with other interested users, and receive notifications as the feature moves from an idea to [planned](https://mattermost.uservoice.com/forums/306457-general/status/1588357), as implementation is [started](https://mattermost.uservoice.com/forums/306457-general/status/1588360) and implementation its [completed](https://mattermost.uservoice.com/forums/306457-general/status/1588363). 

Alternatively, some features ideas may be set to [accepting pull requests](https://mattermost.uservoice.com/forums/306457-general/status/1588438) from the community for completion, and you'll receive alerts on that as well. 

The more specificity and detail you can include in your feature idea post, the easier it will be for like-minded users to upvote and for the core team and external contributors to think through implementation. 

Highly appreciate your interest in improving Mattermost.

**Comment by it33** [comment]
Closing while awaiting submitter response, please feel welcome to re-open,
