### ISSUE TITLE
Slack imported posts all timestamped with current time

### ISSUE THREAD

**Issue by teviot** [mattermost/platform#902]
When performing a Slack import all posts are timestamped with the time of the import.
Expected them to show the time from the "ts" field in Slack's JSON file.
Version 1.0.0 (2403/Thu Oct 1 16:33:52 UTC 2015/e0c3d74146ffa608aa83a5e44e52976b9a7f56d2)
Just browsing the code - CreateAt may be getting clobbered by PreSave() during import?

**Comment by it33** [comment]
Hi @teviot, thanks for the find! 

If you see a potential fix, I wondered if we could ask your help to make a pull request to fix? 

We'd love to have you join the contributor community,

**Comment by teviot** [comment]
Thanks @it33 I'll give it a shot
