### ISSUE TITLE
Accepting Pull Requests: Possible bug in rhs_thread.jsx

### ISSUE THREAD

**Issue by jdeng** [mattermost/platform#916]
Saw one exception at rhs_thread.jsx:30
```
rhs_thread.jsx:30 Uncaught TypeError: Cannot read property 'channel_id' of undefined
```
And there are other similar code in the same file.
```
        var channelId = postList.posts[postList.order[0]].channel_id;
```

The issue I saw is that sometimes `postList.order[0]` (one post from search result, expanded, so order.length == 1) is not in `postList.posts` (contains many posts in the channel). Seems to me like data out of sync between order & posts.

My guess is when reloading the page, `postList.posts`  loads all the posts in the channel but `postList.order` remain the same selected post from the search result.

**Comment by it33** [comment]
Hi @jdeng, thanks for the bug report! 

We're having a difficult time seeing this happen. If you notice it again, could you help us figure out steps to reproduce? 

We'll keep an eye out as well,

**Comment by coreyhulen** [comment]
The error message at https://github.com/mattermost/platform/issues/726#issuecomment-141793528 looks related.

**Comment by jdeng** [comment]
I think it is the same issue. The call stack is the same.
Possible way to reproduce it:
1. Search something
2. Expand one post from the result list (details shown in the right pane)
3. Click another channel
(or close the browser tab and reopen it, and click another channel

Not sure if this can reliably reproduce though. (I ingested a few thousand posts for my test and this happens almost quite often)

**Comment by it33** [comment]
Thanks @jdeng! Yes, this repros consistently. Marking this as accepting pull requests until we assign someone internally to fix. Highly appreciate the report!

**Comment by coreyhulen** [comment]
A lot of work has gone into the RHS.  Closing this as no repo.
