### ISSUE TITLE
[Help Wanted]: Data-Only Containers with Migration Support

### ISSUE THREAD

**Issue by aksakalli** [mattermost/platform#919]
As of now, the project is running in a single container. Upgrading your Docker image will erase all the data in the container. ([Upgrading Mattermost](https://github.com/mattermost/platform/blob/master/doc/install/single-container-install.md#upgrading-mattermost))

It will be better to use an individual MySQL image as [data-only container](http://www.offermann.us/2013/12/tiny-docker-pieces-loosely-joined.html). When you want to upgrade your application, you could keep your database container. To achieve this, a migration mechanism is required in order to be able to run updated application with the old database container.

**Comment by zeroware** [comment]
I agree, it would be cleaner to have SQL running inside another container.
For now, i'm using a file volume (-v option) to store mysql data and files for Mattermost. 

I was wondering if there's already a SQL migration tool builtin inside the application ?

**Comment by aksakalli** [comment]
There is an export/import feature under development: 

https://mattermost.atlassian.net/browse/PLT-22?filter=10002

If the recommended way to upgrade an application is by exporting from old version and importing to new version, it would make sense to have only one container for entire app. But I was thinking of migrating old data through database and file system when you run the newer image by running a migration routine.

**Comment by apaatsio** [comment]
Yes, the db and the app server should be decoupled.

This is necessary for scalability and availability, too. In production you usually want to run at least two app instances behind a load balancer. The all-in-one approach doesn't support this.

**Comment by it33** [comment]
Agree with the thinking here. The Docker container created by the core team is meant for preview, rather than production. 

There's some [early work from the community on more sophisticated Docker setup](https://hub.docker.com/r/lazyfrosch/mattermost/) listed on [Mattermost Install Guides page](http://www.mattermost.org/installation/), 

If someone has already set something up like this, perhaps it could be shared with the community?

**Comment by leecade** [comment]
:+1:

**Comment by it33** [comment]
There's some nice work here on this topic here: https://github.com/lazyfrosch/docker-mattermost

Anyone from the community interested in contributing or continuing the work?

Upgrade guide here: https://github.com/mattermost/platform/blob/master/doc/install/Upgrade-Guide.md

**Comment by it33** [comment]
[Production install on Docker now available](https://github.com/npcode/mattermost-docker) thanks to @npcode!
