### ISSUE TITLE
Database initialization fails on MySQL<5.6

### ISSUE THREAD

**Issue by stephenfin** [mattermost/platform#928]
I have an empty database added on a MySQL 5.5 server and have configured my `config.json` as such:

```json
    "SqlSettings": {
        "DriverName": "mysql",
        "DataSource": "mattermost:password@tcp(mysqlserver.xyz.com:3306)/mattermost?charset=utf8",
        "DataSourceReplicas": [],
        "MaxIdleConns": 10,
        "MaxOpenConns": 10,
        "Trace": false,
        "AtRestEncryptKey": "7rAh6iwQCkV4cA1Gsg3fgGOXJAQ43QVg"
    },
```

However, when I attempt to start the `platform` binary I get an error message like so:

```
root@silv-mattermost-server:~# /srv/www/mattermost/bin/platform -config=/etc/mattermost/config.json
[10/05/15 21:07:54] [INFO] Current version is 1.0.0 (2467/Fri Oct  2 16:47:14 UTC 2015/a049b34dfb6b7c6251bcc0642284b6f4a0bff8ec)
[10/05/15 21:07:54] [INFO] Current working directory is /root
[10/05/15 21:07:54] [INFO] Loaded config file from /etc/mattermost/config.json
[10/05/15 21:07:54] [INFO] Server is initializing...
[10/05/15 21:07:54] [INFO] Pinging sql master database
[10/05/15 21:07:54] [INFO] Pinging sql replica-0 database
[10/05/15 21:07:54] [CRIT] Failed to create column Error 1146: Table 'mattermost.Users' doesn't exist
panic: Failed to create column Error 1146: Table mattermost.Users' doesn't exist

goroutine 1 [running]:
github.com/mattermost/platform/store.SqlStore.CreateColumnIfNotExists(0xc2080547e0, 0xc20802c098, 0x1, 0x1, 0x7f29381e9d70, 0xc20802c0b0, 0x7f29381e9dc8, 0xc20802c0e8, 0x7f29381e9e88, 0xc20802c130, ...)
        /home/travis/gopath/src/github.com/mattermost/platform/store/sql_store.go:306 +0x880
...
```

This was encountered when following [this guide](https://github.com/mattermost/platform/blob/release-1.0.0/doc/install/prod-ubuntu.md) with some modifications. It appears there are issues with MySQL 5.5 that may need to be addressed if other users are using this (it's a requirement for me).

**Comment by stephenfin** [comment]
I still don't know if this is a bug but I was able to get it working. In case anyone else encounters this issue, I was able to work around it by first [setting up the docker version](https://github.com/mattermost/platform/blob/release-1.0.0/doc/install/single-container-install.md) and then running:

```bash
docker exec mattermost mysqldump --user=mmuser --password=mostest --databases mattermost_test > mattermost.sql
# make some modifications to the SQL file
mysql --host=mysqlserver.xyz.com --user=mattermost --password=password mattermost < mattermost.sql
```

The modifications in question are given below. To summarize, I removed the `CREATE [DATABASE]` and `USE [DATABASE]` commands, and I changed the storage engine to MyISAM as [the version of MySQL was <5.6](http://stackoverflow.com/a/20964330/613428).

```diff
--- mattermost.sql.bak  2015-10-06 15:14:57.588895000 +0100
+++ mattermost.sql      2015-10-06 15:17:52.632403000 +0100
@@ -16,14 +16,6 @@
 /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

 --
--- Current Database: `mattermost_test`
---
-
-CREATE DATABASE /*!32312 IF NOT EXISTS*/ `mattermost_test` /*!40100 DEFAULT CHARACTER SET latin1 */;
-
-USE `mattermost_test`;
-
---
 -- Table structure for table `Audits`
 --

@@ -40,7 +32,7 @@
   `SessionId` varchar(26) DEFAULT NULL,
   PRIMARY KEY (`Id`),
   KEY `idx_audits_user_id` (`UserId`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -72,7 +64,7 @@
   PRIMARY KEY (`ChannelId`,`UserId`),
   KEY `idx_channelmembers_channel_id` (`ChannelId`),
   KEY `idx_channelmembers_user_id` (`UserId`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -110,7 +102,7 @@
   UNIQUE KEY `Name` (`Name`,`TeamId`),
   KEY `idx_channels_team_id` (`TeamId`),
   KEY `idx_channels_name` (`Name`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -141,7 +133,7 @@
   PRIMARY KEY (`Id`),
   KEY `idx_webhook_user_id` (`UserId`),
   KEY `idx_webhook_team_id` (`TeamId`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -167,7 +159,7 @@
   `RedirectUri` varchar(256) DEFAULT NULL,
   PRIMARY KEY (`Token`),
   KEY `idx_oauthaccessdata_auth_code` (`AuthCode`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -198,7 +190,7 @@
   `Homepage` varchar(256) DEFAULT NULL,
   PRIMARY KEY (`Id`),
   KEY `idx_oauthapps_creator_id` (`CreatorId`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -228,7 +220,7 @@
   `Scope` varchar(128) DEFAULT NULL,
   PRIMARY KEY (`Code`),
   KEY `idx_oauthauthdata_client_id` (`Code`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -270,7 +262,7 @@
   KEY `idx_posts_root_id` (`RootId`),
   FULLTEXT KEY `idx_posts_message_txt` (`Message`),
   FULLTEXT KEY `idx_posts_hashtags_txt` (`Hashtags`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -305,7 +297,7 @@
   PRIMARY KEY (`Id`),
   KEY `idx_sessions_user_id` (`UserId`),
   KEY `idx_sessions_token` (`Token`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -329,7 +321,7 @@
   `Name` varchar(64) NOT NULL,
   `Value` varchar(1024) DEFAULT NULL,
   PRIMARY KEY (`Name`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -363,7 +355,7 @@
   PRIMARY KEY (`Id`),
   UNIQUE KEY `Name` (`Name`),
   KEY `idx_teams_name` (`Name`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
@@ -413,7 +405,7 @@
   UNIQUE KEY `Username` (`Username`,`TeamId`),
   KEY `idx_users_team_id` (`TeamId`),
   KEY `idx_users_email` (`Email`)
-) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 /*!40101 SET character_set_client = @saved_cs_client */;

 --
```

**Comment by coreyhulen** [comment]
@stephenfin glad you figured this out.  I suspect it has something todo with mysql < 5.6.  Just a word of caution, we only test with 5.6, and there are some known issues with 5.5, mainly full text search.  Switching to MyISAM may have allowed the full text index to be created but the search query my still fail.  I would also be careful with utf8 vs utf8mb4 (a general mysql problem, basically mysql utf8 isn't really utf8).  We hit issues rendering certain characters like Apple emojis.

**Comment by stephenfin** [comment]
Any plans to extend testing to MySQL<5.6? It seems like it should be fixable as I've seen no issues with the application yet, outside of initial install (however you've pointed out some potential pitfalls that would need investigation). If not, would it be appropriate to include this as a requirement in the documentation?



From: Corey Hulen

Sent: Tuesday 6 October 13:26

Subject: Re: [platform] Table 'mattermost.Users' doesn't exist (#928)

To: mattermost/platform

Cc: Stephen Finucane



@stephenfin glad you figured this out. I suspect it has something todo with mysql < 5.6. Just a word of caution, we only test with 5.6, and there are some known issues with 5.5, mainly full text search. Switching to MyISAM may have allowed the full text index to be created but the search query my still fail. I would also be careful with utf8 vs utf8mb4 (a general mysql problem, basically mysql utf8 isn't really utf8). We hit issues rendering certain characters like Apple emojis.

**Comment by coreyhulen** [comment]
Currently there are no plans, but it's really dependent on what the community wishes to use.  I am curious to see if you find any other issues :)  Please keep us posted.  

We should probably make the documentation more obvious on what is supported.  https://github.com/mattermost/platform/blob/master/doc/install/Production-Ubuntu.md#set-up-database-server does mention 5.6+, but it's buried and not obvious.

**Comment by stephenfin** [comment]
Once I figure out how to add tests then I'll start trialing stuff. No apparent issues outside of the initial setup so far though!

**Comment by muloka** [comment]
@coreyhulen Any plans to use something else other than MySQL for full text search? Something like SOLR or ElasticSearch?

**Comment by coreyhulen** [comment]
@muloka Yes, I'm a big fan of ElasticSearch/Lucene.  We feel full text search will only get us so far and we'll need something more.  It's on the roadmap (I'm not sure the tix is ported over to the public jira), but it's aways out.  It's also dependent on some other big features like a job scheduler for things like re-indexing, etc.

**Comment by it33** [comment]
Closing since issues appears to have been solved

**Comment by stevekessler** [comment]
Where is this SQL being generated from? For my purpose,  I would rather just add the  ENGINE=MyISAM DEFAULT CHARSET=utf8; to the source before the database is created.  

Thanks,
Steve
