### ISSUE TITLE
Many 404 Links in Readme

### ISSUE THREAD

**Issue by sinistersnare** [mattermost/platform#930]
Hello, was talking about Mattermost with some coworkers, and one tried to install it locally.... He then complained that the installation links 404 now. It seems there was a change to the build system (?) 3 days ago, so now there are 404s.

I could straight up fix the URLs but I didnt know if there were any moving parts, so Im just going to make this issue.

**Comment by it33** [comment]
Ooo... We're installing some new software to render our markdown in HTML and I think that process might have broken a few things,

**Comment by crspeller** [comment]
@sinistersnare Should be fixed now. My bad! However we now have: http://docs.mattermost.org/
