### ISSUE TITLE
How to set the Mattermost config in a Docker container?

### ISSUE THREAD

**Issue by nevson** [mattermost/platform#96]
Is there some way to set the Mattermost config when starting the Docker container?

**Comment by nevson** [comment]
fyi, I think the [configuration](https://github.com/sameersbn/docker-gitlab#available-configuration-parameters) from [docker-gitlab](https://github.com/sameersbn/docker-gitlab) can be a good example. Also it would be awesome if you could link in custom docker containers for MySQL and Redis that should be used instead of the internal one as shown [here](https://github.com/sameersbn/docker-gitlab#linking-to-mysql-container) and [here](https://github.com/sameersbn/docker-gitlab#linking-to-redis-container).

**Comment by crspeller** [comment]
You can access the config by running these commands:
1. `docker exec -ti mattermost-dev /bin/bash` 
2. `cd src/github.com/mattermost/platform/config` 
3. `vi config_docker.json` 
4. Make your changes
5. `docker stop mattermost-dev` 
6. `docker start mattermost-dev`

**Comment by nevson** [comment]
I see, thanks for the hint. Anyhow it'd be nice if this can be done when starting the container. This would make upgrading the docker container much easier as you can simply pass in a configuration on startup instead of manually editing the config in the container.

**Comment by Hainish** [comment]
:+1:

You can also copy the file from the docker container to the host, then use that as the authoritative config file, sharing it with the container at runtime:

```shell
docker run -d --name=mattermost-tmp mattermost/platform:helium
docker cp mattermost-tmp:/go/src/github.com/mattermost/platform/config/config_docker.json .
docker rm -f mattermost-tmp

docker run --name mattermost-dev -d --publish 8065:80 -v $(pwd)/config_docker.json:/go/src/github.com/mattermost/platform/config/config_docker.json mattermost/platform:helium
```

**Comment by crspeller** [comment]
Closing because question has been answered. If you still have an question, feel free to continue the discussion at http://forum.mattermost.org/.
