### ISSUE TITLE
Graceful handling of `Enable Team Creation = false`

### ISSUE THREAD

**Issue by stephenfin** [mattermost/platform#960]
When you disable team creation (`SETTINGS` > `Team Settings` > `Enable Team Creation`), entering an email and hitting `Sign Up` on the root page (e.g. `http://mattermost.example.com/`) will not appear to do anything. Investigating this further, you can see an error message in the browsers console:

```
error in singupTeam msg=Team creation has been disabled. Please ask your systems administrator for details. detail= rid=788r53uyyprhpf6bgp19w5q4ew
```

You can also see this error in Mattermost's log

```
[2015/10/07 15:27:25 IST] [EROR] /api/v1/teams/signup:isTreamCreationAllowed code=500 rid=kzu8utxqrjrxjcpj3wxr91kn5c uid= ip=10.254.39.18 Team creation has been disabled. Please ask your systems administrator for details. [details: ]
```

There are at least four changes required here, plus an optional one that would (strictly IMO, of course) improve usability:

<ol type='a'>
<li>
At a minimum, there should be a visual indicator (a toast?) suggesting why the sign up failed. An improvement would be to redirect to a page suggesting why the failure occurred.
</li>
<li>
The error message should be demoted to a debug - it's too easy to trigger this case and it's really not that important that I should be seeing dozens of red, <code>EROR</code> (sic) class messages in my log: they hide the important stuff
</li>
<li>
I really don't think this should be a <code>HTTP 500 Internal Server Error</code> error. <a href="http://www.w3.org/Protocols/HTTP/HTRESP.html">w3org</a> state that the <code>500</code> status code represents:

<pre>The server encountered an unexpected condition which prevented it from fulfilling the request.</pre>

I don't think this is an "unexpected condition": we expect it and just don't want to let the user do it. This makes it more akin to a <code>HTTP 403 Forbidden</code>, or:

<pre>The request is for something forbidden. Authorization will not help.</pre>

However, this is mostly semantics so I could be dead wrong here.
</li>
<li>
<code>:s/EROR/ERROR/g</code> :smile:
</li>
</ol>

As for the optional thing, I don't know if this is a feature request or a usability bug. I think (again: strictly IMO here) it would significantly improve usability if you were to change how the "Sign up" page works in general. I've found it a pitfall (both for myself and my "test pool" of users) that going to this page will encourage you to create a new team when the vast majority of users will instead want to join an existing team (especially within an organisation). If anything, the priority of the "Sign up" and "Find my team" button/link should be inversed (making this page more akin to a "Sign in" page). It would be even better if you could add the ability to view the teams you're part of via the web UI rather than relying on email.

I'll try working on this and my other issues as soon as I figure out where to start.

**Comment by coreyhulen** [comment]
https://github.com/mattermost/platform/pull/966 address most of these issues.

for:
a. an error msg is displayed under the button now.  This was just a bug, the server error handling code was removed.
b. I agree, but any non-200/300 status is automatically logged and would be a pain to fix.
c. Switched to `403 Forbidden`.  It was `501 Not Implemented`, but

**Comment by coreyhulen** [comment]
updated previous comment, hit send too soon.

**Comment by stephenfin** [comment]
Indeed it does - nice work. What are your thoughts on the *"optional"* bit?

**Comment by coreyhulen** [comment]
For the optional stuff I agree.  For a lot of organizations it makes sense to show all available teams when it's a small number, on-prem and behind a vpn or something.  Historically we've approached this from a SAAS model where keeping the teams private is preferred because the machine is internet accessible.  I wonder if we should have an option to *show all open teams* as a list on the main page when selected.  We also get feature requests for the case involving a single team.  I goto http://mysite/ and get redirected to http://msite/MyOneAndOnlyTeam

**Comment by stephenfin** [comment]
I think this would be a good idea. As you say, keeping the teams private makes sense in a public SAAS model but when deployed behind a firewall (a understated advantage of Mattermost over Slack) this doesn't make so much sense. The configuration option would be a really useful feature for behind-firewall deployments.

I also like the redirect for single teams: this is how [patchwork](jk.ozlabs.org/projects/patchwork/) (the project I'm working on most in my free time currently) does it and it makes perfect sense.

**Comment by stephenfin** [comment]
I tried to log this as an idea (as this bit is probably an idea rather than a bug) but I've used all my points :disappointed:. Nonetheless, consider this a feature request.

**Comment by coreyhulen** [comment]
I've created https://mattermost.atlassian.net/browse/PLT-565 to track this issue.  Looks like single team is already being tracked as https://mattermost.atlassian.net/browse/PLT-340

**Comment by coreyhulen** [comment]
Fixed in master.
