### ISSUE TITLE
Provide valid URLs for "System Console" page

### ISSUE THREAD

**Issue by stephenfin** [mattermost/platform#962]
When I'm in a channel, the URL of the page is set to `[SERVER]/[PROJECT_NAME]/channels/[CHANNEL_HASH]`, like so:

    http://mattermost.example.com/my-team/channels/7hy9yrcjymxm7fezxg68uo8rpy__6w4ebb9tscuru3qw6gk5ghwjqz

However, when I go to "System Console", the URL of the page is always set to `[SERVER]/admin_console`, like so:

    http://mattermost.example.com/admin_console

This means that if I'm in a pane (`SETTINGS` > `File Settings`) and refresh the page then I am frequently moved to another page. It's not *awful* but a lot of IBM software I have used (:cough:Clearquest:cough:) worked like this and I've found it generally makes seemingly simple things like "Oh, you want to change this setting? Go to this page: xxx" really difficult. If possible, it would help if the URLs were proper URLs and would bring you back to the same tab/pane each time (e.g. `admin_console#service_settings` or `admin_console/service_settings`)

This may apply to more aspects of the web UI, but I've yet to discover them.

**Comment by coreyhulen** [comment]
A PR was submitted and accepted.
