### ISSUE TITLE
Docker accept configs 

### ISSUE THREAD

**Issue by CHIEFnChowCombo** [mattermost/platform#964]
Dockerfile needs to be updated a bit so that you can pass in configs, without needing to build the docker image locally. (You should be able to do a `docker pull`, and then just apply your specific configs to the pulled image.

At the moment, the docker image is configured with a local config.json. I believe the best short-term course of action to improve the flow of things, would be to add a `VOLUME` to the Dockerfile, and updating the docker docs to show how you can mount a host config volume so that your image starts with "overridden configs".

Working on PR.

**Comment by it33** [comment]
Ticket appears out-of-date, closing for now and propose opening in [feature idea forum](www.mattermost.org/feature-requests/) if someone wants an Accepting Pull Request ticket to have this added.
