### ISSUE TITLE
API & documentation

### ISSUE THREAD

**Issue by apaatsio** [mattermost/platform#974]
Is the API comprehensive enough so that one could build an independent front-end for it? E.g. building a mobile app and using the server from mattermost as the backend.

Moreover, is there going to be API documentation? The readme says "API documentation coming in Beta2", but I couldn't find any.

**Comment by coreyhulen** [comment]
Documentation of the APIs is still high on our list of todos.  The web client does 99% of it's work via the RESTful JSON web-service.  The last 1% is some extra error checking/setup the web server does, but isn't needed or has a similar API call.  You can think of https://github.com/mattermost/platform/blob/master/web/react/utils/client.jsx as a javascript driver for the web-service.  Also https://github.com/mattermost/platform/blob/master/model/client.go is a similar golang driver used by the unit tests.

**Comment by coreyhulen** [comment]
start at https://github.com/mattermost/platform/blob/master/doc/developer/API.md

**Comment by coreyhulen** [comment]
https://github.com/mattermost/platform/blob/master/doc/developer/API-Web-Service.md

**Comment by pattyland** [comment]
All Links are dead :(

**Comment by hmhealey** [comment]
@pattyland Here's some updated links. We recently moved our documentation into its own repository and made it available at docs.mattermost.com.

http://docs.mattermost.com/developer/api.html
http://docs.mattermost.com/developer/web-service.html

**Comment by pattyland** [comment]
Thank you very much! Would love to see some kind of documentation of the Javascript Driver, like how I create and manage users via the API. They links you provided are only for posting stuff into Mattermost...
