### ISSUE TITLE
File attachment is unintuitive (UX problem)

### ISSUE THREAD

**Issue by apaatsio** [mattermost/platform#976]
The file attachment flow is quite unintuitive.

This is what the user has to do if they want to just upload a file without writing any text:

1. Click the attachment icon
2. Choose file and click Open
3. Click the text field to focus
4. Hit Enter

The steps 3 and 4 here are the problem. From UX perspective it doesn't make sense. Why do I have to focus the text field? Why do I have to switch from mouse to keyboard?

My suggestion is an "Upload" button, so that the flow would be: 

1. Click the attachment icon
2. Choose file and click Open
3. Click Upload

User still has the option to write text in the text field if they desire, but they also have the quick option to just upload the file.

**Comment by it33** [comment]
Thanks @apaatsio, would this be addressed by adding a "Send" icon to the right of the message input box, similar to the mobile web experience? 

It would function the same as 3) in the proposed solution, but it would work for both message sending and file uploading.

**Comment by apaatsio** [comment]
For me it's ok. But I assumed there's a reason (simplistic design, perhaps) why such an icon/button has been omitted in the first place.

**Comment by it33** [comment]
@esethna, please queue for UX Design meeting in the context of the usability tests we ran recently?

**Comment by lfbrock** [comment]
The keyboard focus now switches to the text box after an upload, so you can press enter and send the file easily. No upload button was added at the moment due to space limitations.
