### ISSUE TITLE
Accepting Pull Requests: HTML encode non-English characters like åäö for emails

### ISSUE THREAD

**Issue by mcyrrer** [mattermost/platform#990]
Email notifications sent by mm does not support non english characters like swedish åäö. I suspect the same goes for other non english chars too.

Suggestion: support email sent using html encoded in utf-8 or a corresponding solution.  

Attached is a picture of an email using letter ö

![image](https://cloud.githubusercontent.com/assets/590115/10390863/a5b581ac-6e7b-11e5-8dcb-63f43058b807.png)

**Comment by coreyhulen** [comment]
A pull request was submitted and accepted.
