### ISSUE TITLE
Animated gif support

### ISSUE THREAD

**Issue by Eronarn** [mattermost/platform#991]
![screen shot 2015-10-09 at 8 17 46 am](https://cloud.githubusercontent.com/assets/536435/10393499/4da525f2-6e5e-11e5-8a3a-6f215be15948.png)

This is a critical piece of functionality and we can't adopt Mattermost until it reaches parity with Slack on this feature.

**Comment by it33** [comment]
Thanks @Eronarn, we've been wanting to add this for a while, seems like multiple people are asking for it now on [forum](https://forum.mattermost.org/t/autoplay-gifs-and-image-importation/304) and in [feature ideas](http://mattermost.uservoice.com/forums/306457-general/suggestions/9429126-support-giphy-integration-as-slack-does). Added [tracking ticket](https://mattermost.atlassian.net/browse/PLT-616) to track this.

**Comment by coreyhulen** [comment]
PR submitted https://github.com/mattermost/platform/pull/1098

**Comment by coreyhulen** [comment]
this is in master.

**Comment by Frankstar** [comment]
do i miss something? its not animated for me ... (2017)

**Comment by raatti** [comment]
gifv also fails to work

**Comment by dfsp-spirit** [comment]
Animated GIFs work when posted as a link, but not when uploaded using the attachment function.
